### ISSUE TITLE
Runtime data updates should allow transform changes

### ISSUE THREAD

**Issue by rbishop-bah** [vega/vega#100]
The runtime View.data() function enables updating data in the scene.  Data definitions include transforms and other stuff besides just the data values.

I ran into a situation where I was adding a transform to a data set at runtime -- one that was not defined in the initial spec.  I assumed this would be allowed; there is nothing in the docs (that I can find) to indicate that only data *value* updates are allowed or that data transforms must be defined in the spec to be recognized.

Doing this tanked the visualization.  The particulars are probably not important; I can provide details if necessary.  Long story short, a copy transform wasn't being executed so a path was failing in vg.data.link.line() because x["source"] wasn't there.

So I don't know whether this is a bug or a feature request, but I think Vega should allow full dynamic data definitions and not require data transforms to be defined in the spec, as it seems to imply with its View.data() function.  If that feature is not included the docs should be edited to clearly indicate that only data *value* updates are recognized in the View.data() function.

**Comment by arvind** [comment]
With Vega 2, you cannot shim in a data transformation at runtime after parsing a specification. However, [[Signals]] can be used to dynamically determine transformation properties, or [[Predicates]] and production rules can be used to have mark visual properties transduce between data sets (via scale transforms). 

If you do need to change a data transformation pipeline at runtime, this will require reparsing the spec.
