### ISSUE TITLE
How to place legend entries horizontally?

### ISSUE THREAD

**Issue by sukeshlaghate** [vega/vega#1003]
I am new to Vega, however like to say thank you for making life easy. Amazing library/tool you guys have created. 
The legend entries are always stacked vertically ( in column), I was wondering if it is possible to have the legend entries placed in a row i.e. horizontally? I could not figure out from documentation how I can achieve this. Would appreciate if anyone can guide me how this can be achieved?
This comes in handy where chart real estate is at a premium :)
If it is not possible currently would like to submit a feature request for same.

**Comment by sukeshlaghate** [comment]
Here is the example where horizontal legend entries would look aesthetically pleasing.

**Comment by jheer** [comment]
Thanks for sharing the issue! 

Vega does not (as of yet) support horizontal symbol legends natively. However, this question has been raised previously and you can create your own by overriding some of the encoding properties. For more, see #943.

I've added a new feature request issue for this (#1005).

**Comment by sukeshlaghate** [comment]
Thanks Jeffrey, will try it out.

**Comment by sukeshlaghate** [comment]
Hi Jeffery,

I tried the example as mentioned in #943 it works for two categories, however when i introduced another category 'graph C' it did not work. It shows the third category overlapped with first.

See attached snapshot.
![horizontal_legend](https://user-images.githubusercontent.com/25061957/30541081-7096672e-9c97-11e7-87fa-316b4159c2c3.png)

Also spec for same is as follows

`{
    "$schema": "https://vega.github.io/schema/vega/v3.0.json",
    "width": 500,
    "height": 300,
    "padding": 20,
    "signals": [
        {
            "name": "cellSize",
            "value": 100
        }
    ],
    "scales": [
        {
            "name": "x",
            "type": "time",
            "range": "width",
            "domain": {
                "data": "stats",
                "field": "x"
            }
        },
        {
            "name": "y",
            "type": "linear",
            "range": "height",
            "nice": true,
            "zero": true,
            "domain": {
                "data": "stats",
                "field": "y"
            }
        },
        {
            "name": "colorlegend",
            "type": "ordinal",
            "domain": {
                "data": "stats",
                "field": "graph"
            },
            "range": "category"
        },
        {
            "name": "legend-series-x",
            "type": "ordinal",
            "domain": {
                "data": "stats",
                "field": "graph"
            },
            "range": "width"
        }
    ],
    "legends": [
        {
            "fill": "colorlegend",
            "orient": "top",
            "title": "Measure",
            "encode": {
                "title": {
                    "update": {
                        "fontSize": {
                            "value": 14
                        }
                    }
                },
                "symbols": {
                    "update": {
                        "x": {
                            "scale": "legend-series-x",
                            "field": "value"
                        },
                        "y": [
                            {
                                "value": 20
                            }
                        ],
                        "fillOpacity": {
                            "value": 0.5
                        },
                        "stroke": {
                            "value": "transparent"
                        }
                    }
                },
                "labels": {
                    "update": {
                        "x": {
                            "scale": "legend-series-x",
                            "field": "value",
                            "offset": 15
                        },
                        "y": [
                            {
                                "value": 20
                            }
                        ]
                    }
                }
            }
        }
    ],
    "marks": [
        {
            "type": "group",
            "from": {
                "facet": {
                    "name": "series",
                    "data": "stats",
                    "groupby": "graph"
                }
            },
            "marks": [
                {
                    "type": "line",
                    "from": {
                        "data": "series"
                    },
                    "encode": {
                        "enter": {
                            "x": {
                                "scale": "x",
                                "field": "x"
                            },
                            "y": {
                                "scale": "y",
                                "field": "y"
                            },
                            "stroke": {
                                "scale": "colorlegend",
                                "field": "graph"
                            },
                            "strokeWidth": {
                                "value": 3
                            },
                            "strokeOpacity": {
                                "value": 0.7
                            }
                        },
                        "update": {
                            "fillOpacity": {
                                "value": 1
                            }
                        },
                        "hover": {
                            "fillOpacity": {
                                "value": 0.5
                            }
                        }
                    }
                }
            ]
        }
    ],
    "axes": [
        {
            "orient": "bottom",
            "scale": "x",
            "domain": false,
            "format": "%H:%M",
            "grid": true
        },
        {
            "orient": "left",
            "scale": "y",
            "title": "%",
            "grid": true
        }
    ],
    "data": [
        {
            "name": "stats",
            "values": [
                {
                    "graph": "graph A",
                    "x": 1500492300000,
                    "y": 63.87579568625058
                },
                {
                    "graph": "graph A",
                    "x": 1500492420000,
                    "y": 140.14065294117647
                },
                {
                    "graph": "graph A",
                    "x": 1500492540000,
                    "y": 72.7588843137255
                },
                {
                    "graph": "graph B",
                    "x": 1500492300000,
                    "y": 63.056507451016294
                },
                {
                    "graph": "graph B",
                    "x": 1500492420000,
                    "y": 200.446230588187426
                },
                {
                    "graph": "graph B",
                    "x": 1500492540000,
                    "y": 72.30749882357728
                },
                {
                    "graph": "graph C",
                    "x": 1500492300000,
                    "y": 73.056507451016294
                },
                {
                    "graph": "graph C",
                    "x": 1500492420000,
                    "y": 210.446230588187426
                },
                {
                    "graph": "graph C",
                    "x": 1500492540000,
                    "y": 175.30749882357728
                }
            ]
        }
    ]
}`
