### ISSUE TITLE
Native support for horizontally-oriented legends.

### ISSUE THREAD

**Issue by jheer** [vega/vega#1005]
This issue has been raised in #943 and #1003.

**Comment by g3o2** [comment]
Maybe one could extend this request by allowing legend items to be placed within a given grid? Though item collision is likely going to cause trouble. Just a thought ...

**Comment by ericsoco** [comment]
I can make time to try implementing this, is [LegendEntries.js](https://github.com/vega/vega-encode/blob/master/src/LegendEntries.js) the right place to start? I don't have much of an understanding yet of how Vega's scenegraph / dataflow work so might be an uphill battle, but with some clues I might be able to make some progress.

**Comment by jheer** [comment]
The heavy lifting of legend design and layout is done within the Vega parser, which translates legend definitions into a collection of lower-level Vega mark definitions. Here are the relevant files:

- https://github.com/vega/vega-parser/blob/master/src/parsers/legend.js
- https://github.com/vega/vega-parser/tree/master/src/parsers/guides (see the `legend-*` files)

A tricky part of horizontal symbol legends is accounting for variable label lengths, which requires computing font metrics for knowing the rendered length of the text. However, if one enforces a maximum length (beyond which text is truncated) then one could more simply pick a fixed offset.

**Comment by ericsoco** [comment]
I already started to implement this and then got derailed...turns out it's good I did, since 4.0 handles this nicely. Thanks @jheer!
