### ISSUE TITLE
How to eliminate gap on a stock chart?

### ISSUE THREAD

**Issue by rleiwang** [vega/vega#1007]
I am trying to draw a stock chart. There is a gap on non trading days. Is there a way to eliminate the gap?

**Comment by domoritz** [comment]
Can you use an ordinal scale?

**Comment by rleiwang** [comment]
Can you point me to examples that change temporal to ordinal?  I changed scale type to ordinal, it doesn't work

`{
    "$schema": "https://vega.github.io/schema/vega/v3.0.2.json",
    "width": 700,
    "height": 200,
    "padding": 5,
    "autosize": "fit",
    "data": [
        {
            "name": "ndx_0",
            "values": [
                {
                    "date": 1500854400000,
                    "open": 5920.930176,
                    "high": 5950.580078,
                    "low": 5912.740234,
                    "close": 5941.370117
                },
                {
                    "date": 1500940800000,
                    "open": 5927.100098,
                    "high": 5945.060059,
                    "low": 5916.290039,
                    "close": 5930.649902
                },
                {
                    "date": 1501027200000,
                    "open": 5944.160156,
                    "high": 5954.379883,
                    "low": 5939.169922,
                    "close": 5950.72998
                },
                {
                    "date": 1501113600000,
                    "open": 5994.02002,
                    "high": 5995.77002,
                    "low": 5847.049805,
                    "close": 5917.029785
                },
                {
                    "date": 1501200000000,
                    "open": 5883.700195,
                    "high": 5918.310059,
                    "low": 5868.919922,
                    "close": 5908.919922
                },
                {
                    "date": 1501459200000,
                    "open": 5928.680176,
                    "high": 5932.370117,
                    "low": 5871.790039,
                    "close": 5880.330078
                },
                {
                    "date": 1501545600000,
                    "open": 5900.640137,
                    "high": 5905.290039,
                    "low": 5880.450195,
                    "close": 5895.169922
                },
                {
                    "date": 1501632000000,
                    "open": 5934.069824,
                    "high": 5936.149902,
                    "low": 5859.620117,
                    "close": 5914.22998
                },
                {
                    "date": 1501718400000,
                    "open": 5915.72998,
                    "high": 5917.470215,
                    "low": 5879.720215,
                    "close": 5891.200195
                },
                {
                    "date": 1501804800000,
                    "open": 5899.689941,
                    "high": 5912.560059,
                    "low": 5877.060059,
                    "close": 5899.910156
                },
                {
                    "date": 1502064000000,
                    "open": 5909.450195,
                    "high": 5936.790039,
                    "low": 5903.75,
                    "close": 5934.72998
                },
                {
                    "date": 1502150400000,
                    "open": 5922.640137,
                    "high": 5972.930176,
                    "low": 5910.5,
                    "close": 5926.350098
                },
                {
                    "date": 1502236800000,
                    "open": 5879.549805,
                    "high": 5920.959961,
                    "low": 5866.169922,
                    "close": 5919.390137
                },
                {
                    "date": 1502323200000,
                    "open": 5880.140137,
                    "high": 5887.27002,
                    "low": 5783.359863,
                    "close": 5788.189941
                },
                {
                    "date": 1502409600000,
                    "open": 5792.319824,
                    "high": 5844.609863,
                    "low": 5785.259766,
                    "close": 5831.529785
                },
                {
                    "date": 1502668800000,
                    "open": 5878.640137,
                    "high": 5916.330078,
                    "low": 5878,
                    "close": 5908.169922
                },
                {
                    "date": 1502755200000,
                    "open": 5917.290039,
                    "high": 5919.75,
                    "low": 5893.850098,
                    "close": 5907.72998
                },
                {
                    "date": 1502841600000,
                    "open": 5920.680176,
                    "high": 5944.97998,
                    "low": 5899.560059,
                    "close": 5917.419922
                },
                {
                    "date": 1502928000000,
                    "open": 5896.319824,
                    "high": 5903.870117,
                    "low": 5796.319824,
                    "close": 5796.319824
                },
                {
                    "date": 1503014400000,
                    "open": 5803.899902,
                    "high": 5831.080078,
                    "low": 5770.140137,
                    "close": 5790.910156
                },
                {
                    "date": 1503273600000,
                    "open": 5791.04248,
                    "high": 5804.298828,
                    "low": 5750.499023,
                    "close": 5786.537109
                }
            ]
        },
        {
            "name": "ndx",
            "source": "ndx_0",
            "transform": [
                {
                    "type": "formula",
                    "expr": "datum.open > datum.close",
                    "as": "isIncrease"
                }
            ]
        },
        {
            "name": "mid",
            "values": [
                {
                    "date": 1501200000000,
                    "point": 5867.580972701515
                },
                {
                    "date": 1503273600000,
                    "point": 5782.926350735754
                }
            ]
        },
        {
            "name": "low",
            "values": []
        }
    ],
    "scales": [
        {
            "name": "xscale",
            "type": "time",
            "domain": {
                "data": "ndx",
                "field": "date",
                "sort": true
            },
            "range": "width"
        },
        {
            "name": "yscale",
            "domain": {
                "fields": [
                    {
                        "data": "ndx",
                        "field": "low"
                    },
                    {
                        "data": "ndx",
                        "field": "high"
                    }
                ],
                "sort": true
            },
            "range": [
                {
                    "signal": "height"
                },
                0
            ],
            "zero": false,
            "round": true,
            "nice": true
        },
        {
            "name": "color",
            "type": "ordinal",
            "domain": {
                "fields": [
                    {
                        "data": "ndx",
                        "field": "isIncrease"
                    }
                ],
                "sort": true
            },
            "range": [
                "#ae1325",
                "#06982d"
            ]
        }
    ],
    "signals": [
        {
            "name": "anchor"
        }
    ],
    "marks": [
        {
            "name": "line_0",
            "type": "line",
            "from": {
                "data": "mid"
            },
            "encode": {
                "enter": {
                    "stroke": {
                        "value": "#652c90"
                    }
                },
                "update": {
                    "path": {
                        "field": "path"
                    },
                    "x": {
                        "scale": "xscale",
                        "field": "date"
                    },
                    "y": {
                        "scale": "yscale",
                        "field": "point"
                    },
                    "strokeWidth": {
                        "value": 3
                    },
                    "opacity": {
                        "value": 0.2
                    }
                }
            }
        },
        {
            "name": "line_1",
            "type": "line",
            "style": [
                "line"
            ],
            "from": {
                "data": "low"
            },
            "encode": {
                "enter": {
                    "stroke": {
                        "value": "#652c90"
                    }
                },
                "update": {
                    "x": {
                        "scale": "xscale",
                        "field": "date"
                    },
                    "y": {
                        "scale": "yscale",
                        "field": "point"
                    },
                    "strokeWidth": {
                        "value": 3
                    },
                    "opacity": {
                        "value": 0.2
                    }
                }
            }
        },
        {
            "name": "high_low",
            "type": "rule",
            "style": [
                "rule"
            ],
            "from": {
                "data": "ndx"
            },
            "encode": {
                "update": {
                    "x": {
                        "scale": "xscale",
                        "field": "date"
                    },
                    "y": {
                        "scale": "yscale",
                        "field": "low"
                    },
                    "y2": {
                        "scale": "yscale",
                        "field": "high"
                    },
                    "stroke": {
                        "scale": "color",
                        "field": "isIncrease"
                    }
                }
            }
        },
        {
            "name": "open_close",
            "type": "rect",
            "style": [
                "bar"
            ],
            "from": {
                "data": "ndx"
            },
            "encode": {
                "update": {
                    "xc": {
                        "scale": "xscale",
                        "field": "date"
                    },
                    "width": {
                        "value": 5
                    },
                    "y": {
                        "scale": "yscale",
                        "field": "open"
                    },
                    "y2": {
                        "scale": "yscale",
                        "field": "close"
                    },
                    "fill": {
                        "scale": "color",
                        "field": "isIncrease"
                    }
                }
            }
        },
        {
            "type": "group",
            "name": "overview",
            "signals": [
                {
                    "name": "brush",
                    "value": 0,
                    "on": [
                        {
                            "events": "mousedown",
                            "update": "[x(), x()]"
                        },
                        {
                            "events": "[mousedown, window:mouseup] > window:mousemove!",
                            "update": "[brush[0], clamp(x(), 0, width)]"
                        },
                        {
                            "events": "mousedown, window:mouseup",
                            "update": "[x(), x(), brush[0], brush[1]]"
                        }
                    ]
                },
                {
                    "name": "anchor",
                    "push": "outer",
                    "on": [
                        {
                            "events": {
                                "signal": "brush"
                            },
                            "update": "brush[2] === brush[3] ? [0,0] : [invert('xscale', brush[2]), invert('xscale', brush[3])]"
                        }
                    ]
                }
            ],
            "marks": [
                {
                    "type": "rect",
                    "name": "brush",
                    "encode": {
                        "enter": {
                            "fill": {
                                "value": "#333"
                            },
                            "fillOpacity": {
                                "value": 0.2
                            }
                        },
                        "update": {
                            "x": {
                                "signal": "brush[0]"
                            },
                            "x2": {
                                "signal": "brush[1]"
                            },
                            "y": {
                                "value": 0
                            },
                            "y2": {
                                "signal": "height"
                            }
                        }
                    }
                }
            ]
        }
    ],
    "axes": [
        {
            "scale": "xscale",
            "labelOverlap": true,
            "orient": "bottom",
            "tickCount": {
                "signal": "ceil(width/40)"
            },
            "zindex": 1,
            "encode": {
                "labels": {
                    "update": {
                        "text": {
                            "signal": "timeFormat(datum.value, '%m/%d/%y')"
                        }
                    }
                }
            }
        },
        {
            "scale": "xscale",
            "domain": false,
            "grid": true,
            "labels": false,
            "maxExtent": 0,
            "minExtent": 0,
            "orient": "bottom",
            "tickCount": {
                "signal": "ceil(width/40)"
            },
            "ticks": false,
            "zindex": 0,
            "gridScale": "yscale"
        },
        {
            "title": "",
            "scale": "yscale",
            "labelOverlap": true,
            "orient": "left",
            "tickCount": {
                "signal": "ceil(height/40)"
            },
            "zindex": 0
        },
        {
            "scale": "yscale",
            "domain": false,
            "labels": false,
            "maxExtent": 0,
            "minExtent": 0,
            "orient": "left",
            "tickCount": {
                "signal": "ceil(height/40)"
            },
            "ticks": false,
            "zindex": 0,
            "grid": true,
            "gridScale": "xscale"
        }
    ]
}`

**Comment by rleiwang** [comment]
@domoritz I tried several different ways and still can't it to work. Would you have any suggestions or point me to an example?

**Comment by domoritz** [comment]
You changed color to ordinal but x is still a time scale. Try a band scale (https://vega.github.io/vega/docs/scales/#band). You can see how we do this in Vega-Lite (and also look at the generated Vega code) at https://vega.github.io/vega-lite/docs/bin.html#example-histogram-with-bin-transform.

**Comment by rleiwang** [comment]
Thanks, I changed to point and it worked
