### ISSUE TITLE
d3.geoBound in Vega?

### ISSUE THREAD

**Issue by mfincker** [vega/vega#1009]
Hello,
I would like to filter the polygons of a TopoJSON based on latitude and longitude. Would it be possible to expose d3.geoBound as an expression function in Vega?

Thanks.

**Comment by jheer** [comment]
Hi! Vega currently supports a `geoBounds` expression function that (given a projection plus a GeoJSON object) returns the projected (x,y) bounds.

To clarify, is this request to expose the _top-level_ `d3.geoBounds` method to get a spherical (lat / lon) bounding box instead?

**Comment by mfincker** [comment]
Hi,
Indeed I would like to get the spherical bounding box in lat/long, not the projected one.
Thanks!

**Comment by jheer** [comment]
Added in Vega 3.1! If you pass a `null` value for the projection to the expression methods, the global d3 variant will be invoked instead of a projection-specific method.
