### ISSUE TITLE
Custom look for the legend

### ISSUE THREAD

**Issue by orck-adrouin** [vega/vega#1010]
Hi,

I found this library today and it looks like it would work great for my data visualization needs.  I would like to know if it is possible to customize the look of the legend to display something like this: 

![image](https://user-images.githubusercontent.com/16353378/30304560-16a9f844-973c-11e7-9498-a371e63409ca.png)

I figured out how to display the donut chart however I cannot figure out if it is possible to customize the legend to look like the above mockup.

**Comment by domoritz** [comment]
You won't be able to use the native legend to wrap as explained in https://github.com/vega/vega/issues/1005. However, you could create a legend by composing the right data transforms, and mark definitions. I think you should be able to get something very close to what you're showing above with that method.

**Comment by orck-adrouin** [comment]
Thanks, I'll look into that.
