### ISSUE TITLE
Support data driven domain with minor expansion for scales

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1012]
As discussed in https://github.com/vega/vega-lite/issues/2988, it would be helpful if Vega scale domain's data reference supports minor expansion from the extent of the referenced field (like Tableau does). 

This would be useful for using bars with continuous scale.

**Comment by jheer** [comment]
I could imagine an additional scale parameter that could be used to indicate that an expansion should be performed, and by how much. There are two unresolved questions though:

1. How should the expansion be calculated? Some possibilities: 

    - An _absolute domain value offset_. This is the simplest, but highly data dependent. I'm thinking this is not very useful: if one knows the correct domain value offset one might just adjust the domain calculation accordingly.
    - A _fractional offset value_ in terms of the scale range (e.g., expand by 5% on each side). This seems more useful, but requires computing domain value offsets from range value offsets. This may differ for different scale types.
    - An _absolute pixel offset value_ in terms of the scale range (e.g., expand such that there are 10 pixels of buffer space on each side). This may be more useful than a fractional offset as, in general, font sizes and symbol sizes are less likely to vary as much across examples as the scale range. I'm thinking this is the most desirable default option.

2. How should scale expansion interact with scale `zero` and `nice` settings? Should expansion be performed prior to either adding `zero` or performing `nice` adjustments? I think so.

@kanitw let me know what you think...

**Comment by kanitw** [comment]
Thanks jeff. I agree with you for both points. 

_Fractional offset value_ seems useful but may add too much complexity to the system.  
I think absolute pixel offset_ value should be fine enough and is in fact better for theming. 
Basically, our default symbol / bar band size is a fixed numeric pixel value.  If someone develops a new theme with a bigger symbol size / bar band size, it is easier to adjust the absolute pixel offset in the theme rather than fractional value (which interacts with the plot size that in turn may depends on range step, paddings and cardinality for discrete scales). 

For 2. I agree the expansion should definitely be before `zero` and `nice`.  Further expanding after zero does not make sense since zero may already expand the domain enough that we do not need to further expand beyond zero.  A similar rationale is applicable for nice.

**Comment by jheer** [comment]
This functionality has been added and released in Vega 3.0.3. Use the `padding` property on a continuous (linear, log, sqrt, pow, time, or utc) scale to set the pixel padding for each edge of the scale range. The scale domain will be appropriately adjusted based on the underlying scale type.
