### ISSUE TITLE
Examples do not work in the editor

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1013]
https://vega.github.io/vega/examples/reorderable-matrix/ -- shows fine, but once you click "View in Online Vega Editor", it fails with `Error: Expression parse error: "xAxisIsDistance ? if(data('tooltipDataDistance').length, data(gi'tooltipDataDistance')[0].value, '') : if(data('tooltipData').length, data('tooltipData')[0].value, '')"`.  Vega version 3.0.2

**Comment by domoritz** [comment]
Hmm, it works for me. Can you clear your browser cache and try it again?

**Comment by nyurik** [comment]
yes, must have been a browser caching issue.  Ideally it shouldn't happen, but probably not worth pursuing, so closing ))

**Comment by domoritz** [comment]
Yes, ideally we would use the version in the schema but that's a Vega editor issue.
