### ISSUE TITLE
Dynamic data filtering per mark in v3

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1017]
In Vega v2, it was possible to decide if the mark should be drawn or not using a pre-transformation on each individual mark.  When datapoint was not applicable to the specific mark, it was possible to simply filter it out (skip) it.  In Vega v3, it seems the only way is to draw each mark transparently, thus causing a performance hit, especially if all the data for a specific mark needs to be hidden.

Is there a simple way in Vega v3 to do dynamic data point filtering?  Or to enable/disable a whole mark? Thanks!

**Comment by jheer** [comment]
I'm not sure which v2 feature you are referring to. Perhaps you are referring to data transforms defined within the mark `from` property? (v3 removes this feature.)

In any case, you can always filter data. If necessary, create a derived data source (in the `data` block) and apply a filter transform. Then have the mark definition draw from that filtered set.

**Comment by nyurik** [comment]
@jheer basic scenario: you want to hide a mark based on a condition. Is the best way to do it is to create a top-level data source? In v2, I would use `from` with a filter. Thx!

**Comment by jheer** [comment]
Yes, using a derived data source is equivalent to a `from`-based filter in v2.
