### ISSUE TITLE
Axis labels disappear when angled

### ISSUE THREAD

**Issue by pelotom** [vega/vega#1019]
**Note**: I'm describing this in terms of vega lite specs for brevity, but I've verified the problem is in vega.

Using this vega lite spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Google's stock price over time.",
  "data": {"url": "data/stocks.csv"},
  "transform": [{"filter": "datum.symbol==='GOOG'"}],
  "mark": {
    "type": "line",
    "interpolate": "step-after"
  },
  "encoding": {
    "x": {"field": "date", "type": "temporal", "axis": { "labelAngle": -64 } },
    "y": {"field": "price", "type": "quantitative"}
  }
}
```

I obtain the following chart with slightly-angled labels:

![64](https://user-images.githubusercontent.com/128019/30941042-783f3c64-a398-11e7-8f50-c0a8a224326d.png)

However if I decrease the angle one more degree:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Google's stock price over time.",
  "data": {"url": "data/stocks.csv"},
  "transform": [{"filter": "datum.symbol==='GOOG'"}],
  "mark": {
    "type": "line",
    "interpolate": "step-after"
  },
  "encoding": {
    "x": {"field": "date", "type": "temporal", "axis": { "labelAngle": -63 } },
    "y": {"field": "price", "type": "quantitative"}
  }
}
```

suddenly half the labels disappear:

![63](https://user-images.githubusercontent.com/128019/30941079-99f8adea-a398-11e7-97ab-9b2d969f4099.png)

I'm guessing this is a "feature", and what's happening is that vega is removing labels when their bounding boxes overlap, however as you can see the labels are nowhere close to overlapping in their actual text here, and it's quite unfortunate that they're being removed. If it's indeed working as intended, could there be a configuration option to disable this feature?

**Comment by domoritz** [comment]
For now, you can disable `labelOverlap`. The docs for it are at https://vega.github.io/vega-lite/docs/axis.html#labels.

**Comment by pelotom** [comment]
@domoritz setting `"labelOverlap": false` doesn't seem to work; the labels still get removed.

**Comment by domoritz** [comment]
That's not good. Can you file a bug with an example spec at https://github.com/vega/vega-lite?

**Comment by pelotom** [comment]
Sure, although as I said it seems like Vega is the one doing the removal...

**Comment by domoritz** [comment]
Yes, Vega is doing the removal but Vega-Lite is generating the Vega spec. I want to make sure it's generating the right code.

**Comment by pelotom** [comment]
Ah, it looks like no matter what you put for `labelOverlap` in the vega lite spec, the generated vega spec has `"labelOverlap": true`.

**Comment by jheer** [comment]
There may also be issues at the Vega level if the spec and config disagree. I have changes already pushed to vega-parser that should ensure that this does not happen (i.e., that an explicit `labelOverlap: false` in the spec will not be overridden by a `true` config setting). These will be included in the next Vega release. (Note that there may still be an additional Vega-Lite issue wrt Vega spec generation.)

**Comment by jheer** [comment]
Given the above, I'm closing out the issue here. The Vega-Lite issues should be tracked over on that repo. Thanks for the report!

**Comment by domoritz** [comment]
Isn't the main issue that Vega removes overlapping labels if the bounding box (not angled) overlaps and not just when the text actually overlaps?
