### ISSUE TITLE
Does Vega 3.0.2 support template to translate domain value to pixel in Path?

### ISSUE THREAD

**Issue by rleiwang** [vega/vega#1023]
Hi,

I would need to draw a custom shape with path. The svg path string like 
            { "name": "path", "value": "M20,30 L50,40 L80,60 L20,45 Z" }

I need to translate domain value to pixel, I tried something like
M{{scale('xscale', xval)}},{{scale('yscale', yval)}},

but it doesn't work. Could you shed light on how can I translate the value?

**Comment by jheer** [comment]
If you are using a custom SVG path string for the `symbol` mark type then you can not embed expressions. Instead, you can change the `x`, `y`, and `size` encoding properties to modify the path geometry externally to the SVG string. So to translate, simply use the `x` and `y` encoding properties.

If you are using a `path` mark, you can similarly set the `x` and `y` encoding properties to translate without modifying the SVG path string. For more complicated customization, you can also generate an SVG path string using a signal expression within an encoding block. For example, something like this:

```json
"encode": {
  "update": {
    "path": {"signal": "'M0,0L' + scale('xscale', datum.xval) + ',' + scale('yscale', datum.yval) + 'Z'"}
  }
}
```

**Comment by rleiwang** [comment]
@jheer I didn't ask clearly what's my goal. I am trying to draw a shape connected by a series of data points based on user selection. At run time, I would update data using vega view api.
`[{x:1,y:1}, {x:2,y:2}....]`. 

How can I use `path` mark to generate SVG path that would do as `M1,1 L2,2..... Z`? Any pointers?
