### ISSUE TITLE
editor hard crash

### ISSUE THREAD

**Issue by mattijn** [vega/vega#1029]
the editor (https://vega.github.io/editor/) crashes continuously

just change `signals` to `signalsx` for example in https://vega.github.io/editor/#/examples/vega/histogram, or `name` to `namex`. This happens with all examples btw.

after crash first need to empty browser cache multiple times to be able to reload

**Comment by domoritz** [comment]
It's a Vega-Editor error: https://github.com/vega/vega-editor/issues/new
