### ISSUE TITLE
Font family for axis ticks

### ISSUE THREAD

**Issue by Lacroute** [vega/vega#1031]
Is there an option to set a font family for the ticks?
Text are generated with this style:
```
font-style: normal;
font-variant: normal;
font-weight: normal;
font-stretch: normal;
font-size: 10px;
line-height: normal;
font-family: sans-serif;
fill: rgb(0, 0, 0);
opacity: 1;
```

Thanks

**Comment by jheer** [comment]
Yes, you can either:
1. Update the default configuration. See https://vega.github.io/vega/docs/config/
2. Use custom encoding definitions. See https://vega.github.io/vega/docs/axes/#custom-axis-encodings
