### ISSUE TITLE
Guide orientation as a signal

### ISSUE THREAD

**Issue by Lacroute** [vega/vega#1033]
Hi,

Can legend orient be binded to a signal instead of a string? Of course, the signal should return a string from the [authorized keywords](https://vega.github.io/vega/docs/legends/#orientation).

It could be useful to move the legend, via a select for exemple, if it overrides the graphic.

**Comment by jheer** [comment]
Thanks for the issue! The legend orientation is currently required to be a constant value. However, at the cost of some significant refactoring across modules it may be possible to generalize this to support signals. I'm marking this as a feature request; we'll take a closer look in the future.

**Comment by domoritz** [comment]
I'm renaming the issue to support guide orient in general. It would be nice to not only set legend orientation as a signal but also axis orientation.

**Comment by haldenl** [comment]
Experimentally supported as of #2610
