### ISSUE TITLE
LabelFlush when last tick is not the max value

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1035]
![image](https://user-images.githubusercontent.com/111269/31484285-8ba6a0ba-aee4-11e7-98e4-f0c971cc2d3b.png)

It's still weird that the last tick's label still gets flushed 

Spec: https://pastebin.com/JLj8xYqv

**Comment by jheer** [comment]
Yes, `labelFlush` currently uses the _indices_ (first and last) of the labels to perform the flush adjustment. In the future, we could try to modify this to be based on an interpolation fraction offset (e.g., 0 or 1, in the extreme) to decide if adjustment should be performed. The necessary modifications would be expressed as signal expressions within the axis label spec generation inside vega-parser.

**Comment by jheer** [comment]
Fixed in [vega-parser v2.3.0](https://github.com/vega/vega-parser/releases/tag/v2.3.0). Will be included in the next Vega release.
