### ISSUE TITLE
The default  axis titlePadding = 2 may be too tight in some cases

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1041]
For example, from https://github.com/vega/vega-lite/blob/master/examples/compiled/bar_aggregate_count.vg.json

![image](https://user-images.githubusercontent.com/111269/31703409-4bc67e0a-b391-11e7-82a2-5670e8e704a7.png)

the y-axis can be a little too tight.

I think maybe 4 or 5 would be a better value.  

If it's helpful, you can see SVG diffs my experiment in VL for titlePadding = 5, https://github.com/vega/vega-lite/pull/3136. 

(I guess we better change the whole Vega default rather than just VL.)

**Comment by jheer** [comment]
Fixed by changes in [vega-scenegraph v2.0.4](https://github.com/vega/vega-scenegraph/releases/tag/v2.0.4) and [vega-parser v2.3.0](https://github.com/vega/vega-parser/releases/tag/v2.3.0). Will be included in the next Vega release.
