### ISSUE TITLE
Setting loader on view or with function behaves differently

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1049]
I tried setting the loader via `view.loader(loader)` but it didn't set the loader correctly. See https://github.com/vega/vega-lite/pull/3151#issuecomment-338547657. Setting the loader when I create the view via `new vega.View(runtime, {loader})` worked flawlessly.

**Comment by domoritz** [comment]
Changes in embed: https://github.com/vega/vega-embed/commit/cd1360ff0090006e97c93edac32bd76265006766#diff-4ba6e76849e991374fac65644a2f688aL118

**Comment by jheer** [comment]
If you have a reproducing example, please share. The constructor simply calls `view.loader(loader)` internally, so I'm not sure yet why you are experiencing issues...

**Comment by domoritz** [comment]
https://bl.ocks.org/domoritz/bc933a16a9375418ca13bc773065af73/07f17ad10e6bd0f029300a5da9081a98eddd292f

```js
    var runtime = vega.parse(spec);
    
    var loader = vega.loader({baseURL: 'https://vega.github.io/editor/'});
    
    // loader.load('data/cars.json').then(console.log).catch(console.warn);
    
    // works
    var view = new vega.View(runtime, {loader: loader})
      .logLevel(vega.Warn)
      .initialize(document.querySelector('#vis'))
      .run();
    
    // does not work
    var view = new vega.View(runtime)
      .loader(loader)
      .logLevel(vega.Warn)
      .initialize(document.querySelector('#vis'))
      .run();
```

**Comment by jheer** [comment]
Thanks! The loader is being updated correctly. However, the View constructor loads dependent data sources _immediately_ upon instantiation. So, the old (default) loader is already being invoked prior to updating the loader to a custom instance. The working approach (as noted above) is to pass in the loader as a constructor option. Whether or not we should consider deprecating the `loader` method is the subject of another issue (with its own pros, cons, and complications); for now I will simply update the `view.loader(...)` method documentation to make sure the nuances here are made clear.
