### ISSUE TITLE
Invalid JSON Schema

### ISSUE THREAD

**Issue by jhngrant** [vega/vega#1054]
My IDE can use JSON schema to provide auto-completion. This has been useful for learning the Vega specification.

There are some directive properties which don't appear in the auto-completion, such as Title properties, which led me to check the following schemas:

- https://vega.github.io/schema/vega/v3.0.json
- Or locally in: /node_modules/vega/build/vega-schema.json

An XML/JSON editor I have has reported the following error when I open either of these schemas:
```
File https://vega.github.io/schema/vega/v3.0.json is not well-formed.
	Value of 'type' is not of expected type.
		Error location: defs / layout / oneOf / 0 / properties / headerBand / oneOf / 1 / type
```
The same error is reported using an online JSON Schema Validator ( www.jsonschemavalidator.net ):
```
Error parsing schema
Message:
     Expected array or string for 'type', got Null. Path 
     'defs.layout.oneOf[0].properties.headerBand.oneOf[1].type', line 1326, position 22.
```

**Comment by jheer** [comment]
Thank you! We will investigate soon.

**Comment by jheer** [comment]
Hmm. Based on your output above, it appears to breaking on the directive `{"type": "null"}`, however this legal _JSON Schema Draft 4_ (which is what Vega uses). For more, [see the null type documentation](https://spacetelescope.github.io/understanding-json-schema/reference/null.html). Looking at your error output, is it possible that somehow `"null"` (a string value) got mapped to `null` (the null value identifier)?

I tested at both http://www.jsonschemavalidator.net/ and https://json-schema-validator.herokuapp.com/syntax.jsp without issues, using the schema files at  both https://vega.github.io/vega/vega-schema.json and https://vega.github.io/schema/vega/v3.0.json. Finally, I've been using the schema for autocomplete in Microsoft Code for some time now with no issues.

As a result, I'm closing the issue. However, please feel free to report back if you have continuing issues and can provide a successful replication of any errors. Thanks again!

**Comment by jhngrant** [comment]
@jheer I confirm the schema was mangled at my end causing the JSON validation to fail. I apologize for wasting your time.

I have reported the auto-complete issue of missing directive properties to the vendor of my IDE: https://youtrack.jetbrains.com/issue/WEB-29436

Thank you for sharing Vega. It is such a useful and well-engineered system. Over a short period of time, Vega has given my productivity a significant boost.
