### ISSUE TITLE
Vega 3 equivalent of view.data(...).update(...) in JavaScript API?

### ISSUE THREAD

**Issue by mercurio** [vega/vega#1055]
Looking through the Vega 3 upgrade doc I can't figure out what would be equivalent to 

view.data('table')
  .insert([{"x": 1}, {"x": 2}])
  .update(function(d) { return d.x > 5; }, 'y', function(d) { return d.y + 5; });

(that's from this page of the 2.0 docs:  https://github.com/vega/vega/wiki/Streaming-Data )

Do I just use view.data() to access the data, and then modify it directly?

Thanks, sorry if this is a stupid question.

**Comment by domoritz** [comment]
Use Changesets. We have a streaming data example in the Vega-Lite docs.

**Comment by mercurio** [comment]
Thanks, looks like vega.changeset().modify() is what I needed.
