### ISSUE TITLE
add format property for text marks generally

### ISSUE THREAD

**Issue by malecki** [vega/vega#106]
Axes allow a format property, but text marks more generally should be formattable. Displaying values of points on a dot plot, for example.

**Comment by arvind** [comment]
With Vega 2.0, we've updated the documentation to discuss the `template` property that can be used to specify string value references (e.g., for the `text` property). Check out the [budget forecasts](http://vega.github.io/vega-editor/?spec=budget_forecasts) or [index chart](http://vega.github.io/vega-editor/?spec=index_chart) examples.
