### ISSUE TITLE
Calculation in vega

### ISSUE THREAD

**Issue by KimKS2017** [vega/vega#1063]
I select two values from two different index in section "data".  But now I need to summarize this values. How can I do this? I can't find information about how to apply for to different data-set in one calculation.

**Comment by jheer** [comment]
We currently do not support 'union' operations of multiple data sets (except for scale domain definitions, which can pull values from various data sets and fields). If you only have two individual data values, you might use an expression function to directly access and summarize those values. The result could be stored in a signal that you could then visualize.

In general, it is helpful to provide a more complete description of the intended output, and what issues might be preventing you from achieving it. Example specifications that others can run and debug is also very useful. For general usage questions, you might instead consider posting to the Vega JS Google Group: https://groups.google.com/forum/#!forum/vega-js
