### ISSUE TITLE
Dynamic time format does not use 24 H format

### ISSUE THREAD

**Issue by amaino** [vega/vega#1065]
I have graph that can show data from 3 months to 1 day and when showing only for one day it will show the time as 9 fm, were fm is the swedish locale version of AM, but the time format in the swedish locale file is  "time": "%H:%M:%S"

I would like the time type for scales to respect the 24 h format of the locale formating file. We never use AM and PM in sweden so it looks very strange.

**Comment by g3o2** [comment]
[https://vega.github.io/vega/docs/api/locale/](https://vega.github.io/vega/docs/api/locale/)

**Comment by amaino** [comment]
That is what I use as I get the locale fm and not AM on the axes. The problem is that it should not even use AM/PM but show me the time in 24 h format. As can be seen in the image below, both graphs uses the same configuration for the x axes.

![image](https://user-images.githubusercontent.com/88597/32375621-9c2fe3ea-c0a2-11e7-8a47-e4d704cd41d5.png)

**Comment by jheer** [comment]
Thanks @amaino! Under the hood, Vega uses D3 scales and the [d3-time-format](https://github.com/d3/d3-time-format/) module. If I'm not mistaken, it looks like d3-time-format includes AM/PM by default in the [Locale configuration for Sweden](https://github.com/d3/d3-time-format/blob/master/locale/sv-SE.json). You might file an issue on that repo if you think it warranted.

In the meantime, I see two immediate solutions for Vega:

1. Create your own locale configuration file by modifying the one linked above, and use that with Vega.
2. Use the existing locale configuration for Sweden, but provide a custom date-time format for your time axis via the [axis `format` property](https://vega.github.io/vega/docs/axes/).

I hope that helps!
-jeff

**Comment by amaino** [comment]
That is not correct, the Swedish locale uses 24 h format. I do not see any %p in my file or the one you linked to, or do you mean something else?  The problem is the dynamic formating that is done for type time depending on the time span. That is showing the date if span is over several days and time if the time span is around 24 h

The question then if this is done by Vega or D3, someone is not using the locale configuration to format the time.

**Comment by jheer** [comment]
You're right! The problem arises not from d3-time-format or locales but by the automatic formatting applied in d3-scale's time scale: https://github.com/d3/d3-scale/blob/master/src/time.js#L61

Solution 2 in my earlier comment still applies, but will not exhibit dynamic changes of format as the time range changes.
