### ISSUE TITLE
Area Labels

### ISSUE THREAD

**Issue by curran** [vega/vega#1067]
Greetings,

I noticed there are no labels on the areas in the stacked area examples.

I created a library for adding labels to areas that may be useful to position labels: https://github.com/curran/d3-area-label

For example:

[![image](https://user-images.githubusercontent.com/68416/28940637-0376ab84-78b3-11e7-858b-7b0320ea9e5a.png)](https://bl.ocks.org/curran/929c0cb58d5ec8dc1dceb7af20a33320)

This issue is more to open a discussion of whether this feature or area labels would be considered within the scope of Vega. If not, it would be interesting to see if there's possibly a way to post-process the SVG generated by Vega in order to add labels to stacked areas.

Amazing work, and really excited to start using Vega-Lite 2.0!

**Comment by domoritz** [comment]
Cc @willium

**Comment by willium** [comment]
The vega-labels package I’ve been working on is actually using a similar algorithm for area. That said, I haven’t had a lot of time to work on it recently. It’s definitely within scope as a vega transform (but not necessarily as something to do to the SVG afterwards since Vega can render non SVGs), but I think we decided we’d like to support a large subset of make types before we add labeling.

**Comment by jheer** [comment]
Thanks @curran! This could be a useful feature to add. I think the best way to go about it would be to create a new transform definition that can live in it's own module (a la vega-voronoi, vega-wordcloud, etc). Even if it was not part of the standard Vega build, other users could import the transform and use it in their Vega specs.

Post-processing of SVG is also an option, but outside of Vega proper and so beyond the scope of issues here. In other words, knock yourself out! :)

I'm going to close this issue as there is not immediate "todo" here for the Vega dev team, but feel free to continue the discussion here!

**Comment by curran** [comment]
Thanks @jheer ! Makes perfect sense.

@willium Is there any work in progress for the vega-labels package? I'd be curious what the algorithm looks like.

Perhaps we could join forces and isolate the algorithm as an independent module.

I made the mistake of tying the API to SVG in particular with d3-area-label. I'd like to try refactoring d3-area-label so its output is agnostic of the rendering technology, so could be more easily leveraged as a dependency of a future Vega transform package for area labeling.
