### ISSUE TITLE
Sign of metric

### ISSUE THREAD

**Issue by KimKS2017** [vega/vega#1068]
How can I sign two metric with different title?
![ex1](https://user-images.githubusercontent.com/31929345/32377208-f22ef988-c0b7-11e7-9e83-557137fffc0b.PNG)

**Comment by jheer** [comment]
Hi! Your question does not provide enough context to understand what you are trying to achieve. In general, please share an image or description of the intended output, and what issues might be preventing you from achieving it. Example specifications that others can run and debug is also very useful.

For general usage questions, you might instead consider posting to the Vega JS Google Group: https://groups.google.com/forum/#!forum/vega-js
