### ISSUE TITLE
Invalid bind.element silently fails

### ISSUE THREAD

**Issue by kenklin** [vega/vega#1069]
The following attempts to bind a signal to an external HTML element `#mycontrols`.

	<!DOCTYPE html>
	<html>
	<head>
	  <title>Embedding Vega-Lite</title>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/vega/3.0.7/vega.js"></script>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-lite/2.0.0/vega-lite.js"></script>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/vega-embed/3.0.0-rc6/vega-embed.js"></script>
	</head>
	<body>
	<div id="mycontrols"></div>
	<div id="vis"></div>
	<script type="text/javascript">
		// Based on https://vega.github.io/vega-lite/docs/bind.html
		var yourVlSpec = {
		  "$schema": "https://vega.github.io/schema/vega-lite/v2.0.json",
		  "data": {"url": "https://vega.github.io/vega-lite/data/cars.json"},
		  "selection": {
			"org": {
			  "type": "single",
			  "fields": ["Origin"],
			  "bind": {"input": "select", "options": ["Europe", "Japan", "USA"],
	//			  "element": "#mycontrols"
				  "element": "#BADID"
			  }
			}
		  },
		  "mark": "point",
		  "encoding": {
			"x": {"field": "Horsepower", "type": "quantitative"},
			"y": {"field": "Miles_per_Gallon", "type": "quantitative"},
			"color": {
			  "condition": {
				"selection": "org",
				"field": "Cylinders", "type": "ordinal"
			  },
			  "value": "grey"
			}
		  }
		}
		vegaEmbed("#vis", yourVlSpec);
	</script>
	</body>
	</html>

If the bind.element (`#BADID`) is not found, the Javascript console reveals the following uncaught exception.  

    Uncaught (in promise) TypeError: Cannot set property 'innerHTML' of null
        at lookup$2 (vega.js:28580)
        at vega.js:28560
        at Array.forEach (<anonymous>)
        at View.initialize$1 [as initialize] (vega.js:28559)
        at embed (embed.ts:129)
        at demo.html:40

In the more complicated detail/overview code I have (not shown) which had a similar bind.element typo, no marks are displayed at all which prompted me to dive and create the simpler example above.  I've investigated and have a proposed patch to `lookup$2` and `bind$1` which calls `view.error` to emit ...

    ERROR Signal's bind.element #BADID not found.

**Comment by jheer** [comment]
Thanks for raising the issue! Fixed in vega-view v2.0.4. Will be included in vega 3.0.8.
