### ISSUE TITLE
scale parameter in toImageURL

### ISSUE THREAD

**Issue by eibanez** [vega/vega#1072]
I would like to request adding a parameter to the toImageURL that can change the overall size of the exported plot.

I've been using saveSvgAsPng with vega 2 and I has that option
https://github.com/exupero/saveSvgAsPng

> If you want to scale the image up or down, you can pass a scale factor in an options object:
>    saveSvgAsPng(document.getElementById("diagram"), "diagram.png", {scale: 0.5});

This allows me to size a plot for a website, but export high-resolution images that can be used elsewhere. Having native support in vega would be very helpful.

**Comment by jheer** [comment]
Added in vega-scenegraph v2.1.0 / vega-view v2.1.0 and released in vega 3.0.9. The `toCanvas`, `toSVG`, and `toImageURL` methods now accept an optional numeric `scaleFactor` by which to multiply the output image size.

**Comment by eibanez** [comment]
Many thanks!
