### ISSUE TITLE
Remove canvas dependency for core Vega

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1073]
Requiring canvas dependency (or any other lib that uses native node bindings and requires C++ compilation) is always a challenge. I think it would greatly simplify Vega integration into large existing projects if it didn't require canvas, but offered it as either a separate package, e.g. vega-server, or used some other npm install magic.  Or we could create `vega-no-canvas`?

The moment I add vega lib as a dependency every user who wants to contribute to my project is required to install several native libraries/packages. And the instruction is complex and different for each OS / version. The issue also shows up for build integration (my project now has to specify complex travis configuration, or alter Jenkins, ...).

**Comment by pzrq** [comment]
I've also see this cause `package-lock.json` deltas between different environments depending on whether the installation steps were followed correctly.

**Comment by pelotom** [comment]
Having `vega` in my dependencies leads to this ugly yarn warning on MacOS X due to canvas:

> warning Error running install script for optional dependency: "/Users/tom/code/console/node_modules/canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: /Users/tom/code/console/node_modules/canvas\nOutput:\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@8.9.0 | darwin | x64\ngyp info spawn /usr/bin/python\ngyp info spawn args [ '/Users/tom/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'make',\ngyp info spawn args   '-I',\ngyp info spawn args   '/Users/tom/code/console/node_modules/canvas/build/config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/Users/tom/.config/yarn/global/node_modules/node-gyp/addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/Users/tom/.node-gyp/8.9.0/include/node/common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=/Users/tom/.node-gyp/8.9.0',\ngyp info spawn args   '-Dnode_gyp_dir=/Users/tom/.config/yarn/global/node_modules/node-gyp',\ngyp info spawn args   '-Dnode_lib_file=/Users/tom/.node-gyp/8.9.0/<(target_arch)/node.lib',\ngyp info spawn args   '-Dmodule_root_dir=/Users/tom/code/console/node_modules/canvas',\ngyp info spawn args   '-Dnode_engine=v8',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'build',\ngyp info spawn args   '-Goutput_dir=.' ]\n./util/has_lib.sh: line 31: pkg-config: command not found\ngyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp\ngyp ERR! configure error \ngyp ERR! stack Error: `gyp` failed wi

Does anyone have any tips on how to work around this?

**Comment by thomasneirynck** [comment]
+1 on this issue. It's ugly spam.

----

Depending on your package manager, you can suppress the warning.

> yarn install --ignore-scripts

The compilation isn't executed. This will work if your project doesn't rely on any build-steps (I'd assume the majority of projects fall in that category).

> npm install --no-optional

The canvas module isn't pulled in since it is optional.

**Comment by pelotom** [comment]
@thomasneirynck yeah, I've been using the latter approach.

**Comment by nyurik** [comment]
I just published a temporary workaround -- https://github.com/nyurik/vega-nocanvas -- simply use it instead of vega.  I suspect there might be some code bloat. I will keep it updated when the new Vega versions come out.

**Comment by jheer** [comment]
I've added a new vega-canvas module that centralizes instantiation of canvas instances. It does not include explicit dependencies / optional dependencies on node-canvas libraries, deferring to parent projects to include node-canvas when desired.

The vega-scenegraph and vega-wordcloud modules now depend on vega-canvas, and so do not directly import node-canvas (other than as a dev dependency for testing).

Vega 3.0.10 has been released and now includes explicit optionalDependencies on `canvas` and `canvas-prebuilt`. This is done to maintain compatibility, such that node.js use and command line utilities continue to work as expected. To create a Vega variant that does not attempt to import node-canvas, you can basically copy the main Vega repo and remove the optionalDependencies from package.json.

I'm considering adding a new vega-client module to the Vega org that does exactly this, which would then replace Yuri's vega-nocanvas. Feel free to share any additional thoughts here.

**Comment by nyurik** [comment]
@jheer awesome news, thanks!  I agree that Vega should stay backward compatible this way. Also, I can simply add you to the vega-nocanvas, or even delete that project to reduce confusion.

Going forward, I think we can create a new library, e.g. `vega-lib`, that will include just the ES6-structured code (no combined build files, canvas dep, or docs).  The tests should be moved to `vega-lib`, or possibly even down to individual sub-projects, but excluded from publishing via `.npmignore`.   The `index.js` file should be moved to `vega-lib` as well, and `vega` will have just a single line `index.js`  to import it all.

`vega` will continue publishing everything, including the combined/minified build files, but `vega-lib` will be a much better alternative for direct usage in other projects without any unneeded extras or build results.

**Comment by nyurik** [comment]
I just published a https://github.com/nyurik/vega-lib (also in npm).  Seems to be working, except that I had to include the build steps - wouldn't work without them when used downstream.  @jheer I can transfer it to https://github.com/vega -- this way `vega` could depend on `vega-lib`, removing potential code forking.

**Comment by jheer** [comment]
Thanks everyone. This issue can be addressed by using vega-lib, which is now official: https://github.com/vega/vega-lib - Vega without the canvas dependencies, optional or otherwise.

**Comment by davidanthoff** [comment]
Is there going to be a similar vegalite-lib?

**Comment by jheer** [comment]
I'll redirect that question to @kanitw and @domoritz. I believe Vega-Lite only depends on Vega for testing purposes, so canvas should only be an issue there if you are loading the devDependencies to run test cases.

Another question is vega-embed. That project should probably just import vega-lib instead of vega proper, but I'll leave that question to the devs on that project.

Feel free to file issues directly on the relevant repos!

**Comment by nyurik** [comment]
Should `vega` depend on `vega-lib` to minimize potential build / code synchronization issues?

**Comment by jheer** [comment]
My original thinking was "yes", but then I changed my mind when I went to implement this. For the time being I found it more convenient to manage all the example specs (including those in both tests and documentation) from a single repo (Vega), test them all together prior to release, then release vega-lib in parallel. I'm open to revisiting this later on, though.
