### ISSUE TITLE
Text in layout header got truncated mysteriously

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1074]
Please look at the compiled Vega from this spec: 

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "Stock prices of four large companies as a small multiples of area charts.",
  "transform": [
      {
          "filter": "datum.symbol !== 'GOOG'"
      },
      {
        "calculate": "datum.symbol+datum.symbol",
        "as": "symbol2"
      }
  ],
  "width": 300,
  "height": 40,
  "data": {
      "url": "data/stocks.csv"
  },
  "mark": "area",
  "encoding": {
      "x": {
          "field": "date",
          "type": "temporal",
          "axis": {
              "format": "%Y",
              "title": "Time",
              "grid": false
          }
      },
      "y": {
          "field": "price",
          "type": "quantitative",
          "axis": {
              "title": "Price",
              "grid": false
          }
      },
      "color": {
          "field": "symbol2",
          "type": "nominal",
          "legend": null
      },
      "row": {
          "field": "symbol2",
          "type": "nominal",
          "header": {"title": "Symbol"}
      }
  }
}
```

I'm not sure why header labels get truncated although I haven't set limit. 

![image](https://user-images.githubusercontent.com/111269/32977825-3e83033c-cbea-11e7-9f58-c0d395d303cc.png)

That said, if I add `limit: {"value": 60`}`, then it no longer gets truncated.  So it seems like there is a magic "limit" number for header label text?  Not sure if that is intended.

**Comment by kanitw** [comment]
Note that adding 

```
"config": {
    "style": {
      "guide-label": {
        "limit": 500
      } 
    } 
  }
```

also do not work in this situation.

**Comment by jheer** [comment]
This happens because you are using `title`. Vega automatically limits a title to the enclosing group's defined width / height (see [title.js#L92 in vega-parser](https://github.com/vega/vega-parser/blob/master/src/parsers/title.js#L92)). This is a feature, not a bug... :)

Potential solutions include:
- Don't use `title`. For example, use a `text` mark instead.
- Explicitly set the `limit` property in the `encode` block.
