### ISSUE TITLE
Force collide with different-sized nodes

### ISSUE THREAD

**Issue by mdettelson** [vega/vega#1076]
Hi!

I'm trying to build a bubble chart where each node's radius is determined by a numeric value for a field.  I was hoping to have all of these different-sized nodes touch each other and not overlap, but it seems like the collide force transformation only allows for a universal radius.  This leaves me with lots of space between the nodes.  

Is it possible to run the simulation with different-sized nodes, or is there a workaround that I could use in the meantime to remove gaps?

**Comment by jheer** [comment]
You found the solution! That is the preferred way to go for the time being, as expressions allow you to invoke scales in the context of transform parameters.

**Comment by BMPMS** [comment]
I still can't get this to work:

  "transform": [
        {
          "type": "force",
          "iterations": 100,
          "static": false,
          "forces": [
            {"force": "collide", "iterations": 10, "radius":15,"strength":1},
            {"force": "x", "x": "xfocus", "strength": 1},
            {"force": "y", "y": "yfocus", "strength": 0.2}
          ]
        }
      ]

works perfectly.

When I change it to:

  "transform": [
        {
          "type": "force",
          "iterations": 100,
          "static": false,
          "forces": [
            {"force": "collide", "iterations": 10, "radius"{"expr":"scale('radius',datum.value)"},"strength":1},
            {"force": "x", "x": "xfocus", "strength": 1},
            {"force": "y", "y": "yfocus", "strength": 0.2}
          ]
        }
      ]

there is no collide radius..

This is my scale:

  {
      "name": "radius_size",
      "type": "quantile",
      "domain": {"data": "topics", "field": "value"},
      "range": [5,10,15,20]
    }

very frustrating!

**Comment by mdettelson** [comment]
Looks like you're missing a ":" after "radius", and the first value of your scale function in the expression should be 'radius_size')

If you fix those two spots, everything else looks ok at first glance

**Comment by BMPMS** [comment]
Many thanks for you help - it worked when I added:

"radius": {"scale": "radius_size", "field": "value"},

to the symbol update section.  Getting the hang of it now - just takes a while adjusting from d3.

**Comment by vlsd** [comment]
@BMPMS do you mind posting the code that worked? I can't figure out if it was the edits suggested that helped you or something else (the symbol update section?)

**Comment by BMPMS** [comment]
Hi Vlad,

It’s a long time since I’ve worked on this one and I don’t normally do Vega.  If you send a bit more info I might be able to help but quite busy at the mo.

**Comment by vlsd** [comment]
Hey, no worries, it's not a big deal. Thanks for getting back so fast :)
