### ISSUE TITLE
`config.mark.fill` doesn't work

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1082]
Try this - it shows fill as blue instead of green. Rename `mark` to `rect` inside `config`, and it will work.

```json
{
  "config": {
    "mark": {
        "stroke": "red",
        "fill": "green"
    }
  },


  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 400,
  "height": 200,
  "padding": 5,

  "data": [
    {
      "name": "table",
      "values": [
        {"category": "A", "amount": 28},
        {"category": "B", "amount": 55},
        {"category": "C", "amount": 43},
        {"category": "D", "amount": 91},
        {"category": "E", "amount": 81},
        {"category": "F", "amount": 53},
        {"category": "G", "amount": 19},
        {"category": "H", "amount": 87}
      ]
    }
  ],

  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "domain": {"data": "table", "field": "category"},
      "range": "width",
      "padding": 0.05,
      "round": true
    },
    {
      "name": "yscale",
      "domain": {"data": "table", "field": "amount"},
      "nice": true,
      "range": "height"
    }
  ],

  "axes": [
    { "orient": "bottom", "scale": "xscale" },
    { "orient": "left", "scale": "yscale" }
  ],

  "marks": [
    {
      "type": "rect",
      "from": {"data":"table"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "category"},
          "width": {"scale": "xscale", "band": 1},
          "y": {"scale": "yscale", "field": "amount"},
          "y2": {"scale": "yscale", "value": 0}
        }
      }
    }
  ]
}
```

**Comment by jheer** [comment]
This happens because any defaults defined at the `mark` level may be overridden by defaults targeting a specific mark type. The Vega config includes a [default `rect` mark fill color](https://github.com/vega/vega-parser/blob/master/src/config.js#L73), which overrides anything set for the `mark` parent class.

So while perhaps not what you were seeking, this is the intended behavior. I'll update the documentation now to make this clearer.

**Comment by nyurik** [comment]
@jheer I understand that its the behavior we have now, my concern is that there is no way to override the `defaultColor` variable - I can only override each mark type in turn.  From what I can see, there is almost never any use of setting the `config.mark`.  Can you think of a usecase when `config.mark` should be used?

**Comment by jheer** [comment]
You could use `config.mark` for some cross-cutting concerns like default opacity settings, but in general it is not nearly as useful as the mark-specific settings.

Right now the Vega defaults are hard-wired in the parser and all additional configuration values are treated as overrides to that. If you have an idea on how to change that to make it more useful (perhaps ignoring built-in defaults altogether) feel free to raise those in a new "feature request" issue.
