### ISSUE TITLE
config.mark does not behave as expected

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1083]
It seems that `config.mark` behavior is highly counter-intuitive, and not very useful. For example, if I have multiple marks in a graph, including lines, rectangles, areas, and other types, and I want the default color to be red instead of the default blue, I would expect this config to simply change the defaults:

```json
{
  "config": {
    "mark": {
        "stroke": "red",
        "fill": "green"
}}
```

My expectations would be that marks like line would use the strike color, and areas and rectangles would use the fill - after all, I'm just changing the defaults.  But instead, the line uses fill, and rect and area start using stroke, but ignore the fill change.

Here's a sample with 3 marks (area, rect, line).  I would expect it to show area and rect with green fill, and line to be red, but neither area or rect should have storke set, and line should not have a fill.  On the other hand, if I set `config.line.fill = green`, than yes, it should override the default transparent fill.

```json
{
  "config": {
    "mark": {
        "stroke": "red",
        "fill": "green"
    }
  },


  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 400,
  "height": 200,
  "padding": 5,

  "data": [
    {
      "name": "table",
      "values": [
        {"category": "A", "amount": 28},
        {"category": "B", "amount": 55},
        {"category": "C", "amount": 43},
        {"category": "D", "amount": 91},
        {"category": "E", "amount": 81},
        {"category": "F", "amount": 53},
        {"category": "G", "amount": 19},
        {"category": "H", "amount": 87}
      ]
    }
  ],

  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "domain": {"data": "table", "field": "category"},
      "range": "width",
      "padding": 0.05,
      "round": true
    },
    {
      "name": "yscale",
      "domain": {"data": "table", "field": "amount"},
      "nice": true,
      "range": "height"
    }
  ],

  "axes": [
    { "orient": "bottom", "scale": "xscale" },
    { "orient": "left", "scale": "yscale" }
  ],

  "marks": [
    {
      "type": "rect",
      "from": {"data":"table"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "category"},
          "width": {"scale": "xscale", "band": 1},
          "y": {"scale": "yscale", "field": "amount"},
          "y2": {"scale": "yscale", "value": 0},
          "fillOpacity": {"value": 0.5}
        }
      }
    },
    {
      "type": "line",
      "from": {"data":"table"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "category"},
          "y": {"scale": "yscale", "field": "amount"}
        }
      }
    },
    {
      "type": "area",
      "from": {"data":"table"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "category"},
          "width": {"scale": "xscale", "band": 1},
          "y": {"scale": "yscale", "field": "amount"},
          "y2": {"scale": "yscale", "value": 0},
          "interpolate": {"value": "monotone"},
          "fillOpacity": {"value": 0.5}
        }
      }
    }
  ]
}
```

**Comment by nyurik** [comment]
Here's an example of what the above behavior means in practical terms.  In Kibana, I need to change the default color palette for Vega & Vega Lite. Here's [the code](https://github.com/nyurik/kibana/blob/82dc45ab3b856e4fa31cf7193f63c26acd5a928e/src/core_plugins/vega_vis/public/vega_view/parse_input_spec.js#L183):

```js
// Vega Lite
setDefaultValue(spec, ['config', 'mark', 'color'], defaultColor);

// Vega
setDefaultValue(spec, ['config', 'arc', 'fill'], defaultColor);
setDefaultValue(spec, ['config', 'area', 'fill'], defaultColor);
setDefaultValue(spec, ['config', 'line', 'stroke'], defaultColor);
setDefaultValue(spec, ['config', 'path', 'stroke'], defaultColor);
setDefaultValue(spec, ['config', 'rect', 'fill'], defaultColor);
setDefaultValue(spec, ['config', 'rule', 'stroke'], defaultColor);
setDefaultValue(spec, ['config', 'shape', 'stroke'], defaultColor);
setDefaultValue(spec, ['config', 'symbol', 'fill'], defaultColor);
setDefaultValue(spec, ['config', 'trail', 'fill'], defaultColor);
```

**Comment by jheer** [comment]
Yes, this is what is currently necessary, as there is no "magic" `color` setting for Vega that uses fill or stroke selectively depending on the mark type. This possibility was briefly discussed among the development team but rejected due to unclear semantics (for some marks, either color channel may be wanted) and the added complexity.

The result is that, as you note, the top-level `mark` config object is of limited utility in its current form, as settings for more specific mark types override it.
