### ISSUE TITLE
US map with states

### ISSUE THREAD

**Issue by neekand** [vega/vega#1084]
I am new bee to Vega, trying to show US map with states. when I run my us-map.json its working fine on online vega editor, but not my index.html. not getting any errors either., just blank page.
following is my json & index.html.

{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 960,
  "height": 600,
  "autosize": "none",

  "data": [
  
    {
      "name": "states",
      "url": "us-10m.json",
      "format": {"type": "topojson", "feature": "counties"}
      
    }
  ],

  "projections": [
    {
      "name": "projection",
      "type": "albersUsa"
    }
  ],

  
  

  "marks": [
    {
      "type": "shape",
      "from": {"data": "states"},
      
      "transform": [
        { "type": "geoshape", "projection": "projection" }
      ]
    }
  ]
}

index.html

<head>
 <meta http-equiv="content-type" content="text/html;charset=utf-8">
<script src="http://d3js.org/d3.v3.min.js"></script>
 <script src="https://vega.github.io/vega-editor/vendor/d3.geo.projection.min.js"></script>
<script src= "https://cdnjs.cloudflare.com/ajax/libs/topojson/3.0.2/topojson.js"></script>
<script src="https://vega.github.io/vega-editor/vendor/d3.layout.cloud.js"></script>

  <script src="http://trifacta.github.io/vega/vega.js"></script>
  <script src="https://vega.github.io/vega/vega.min.js"></script>
   </script>

</head>

Vega tutorial
<h1 id="title">Let's Try Vega</h1>
<div id="viz"></div>
<div id="text">test</div>

<script type="text/javascript">
   
	function parse(spec) {
	//var view = new vega.View(vega.parse(spec));
  		vg.parse.spec(spec, function(chart) {
  		  this.view = chart({el:"#viz", renderer: "svg"}); 
  		 });
	}
	parse("../javascript/json/us-map.json");
	

</script></html>
thanks,

**Comment by nyurik** [comment]
Check if there are any errors in the console.  Also, make sure the file `us-10m.json` is in the same dir as the graph (check browser debugger networking tab - see if the file loads ok)

**Comment by neekand** [comment]
thank you for the reply. if I pass bar chart json, Its working fine, I can see the chart. but with US map json, for same index.html, getting a error "typeerror: function func is not a function" in vega.js.

**Comment by jheer** [comment]
The example HTML above appears to be using a combination of imports that cut across multiple versions of Vega (v2 and v3). Vega 3 uses `vega.parse` syntax, where as Vega 2 uses `vg.parse.spec`. Be sure to standardize on using only Vega 3 imports and syntax. The default Vega v3 build (e.g., https://vega.github.io/vega/vega.js) will include d3, etc for you now.

Be sure to follow the instructions and examples at https://vega.github.io/vega/usage/

Hope that helps!
