### ISSUE TITLE
Point scale with larger outer padding

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1090]
It would be great to set padding larger than 1 so that I can have marks that are overlapping each other but not overlapping the axes or edges of the chart. 

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "point",
  "encoding": {
    "x": {"field": "a", "type": "ordinal", "scale": {"paddingOuter": 5}},
    "size": {"field": "b", "type": "quantitative"}
  }
}
```

Ref https://github.com/vega/vega-lite/issues/3231

**Comment by jheer** [comment]
This is constrained by d3, so not (directly) a Vega issue:

For more, see:
- https://github.com/d3/d3-scale#point_padding
- https://github.com/d3/d3-scale/blob/master/src/band.js#L65
