### ISSUE TITLE
Adding an interpolated color scheme

### ISSUE THREAD

**Issue by mdettelson** [vega/vega#1091]
Hi,

I've been trying to add my own interpolated color scheme using the guides, but the syntax I'm supposed to use isn't quite clear.

Last thing I tried looked like this:

vega.scheme("sm", vega.interpolate({colors: ["#D6EDFE", "#30A7FB"]}));

How exactly am I supposed to implement this?

**Comment by jheer** [comment]
To add an interpolator, you need to add a custom interpolator function. Here is a basic example:

```js
// define interpolator function that maps [0,1] -> colors
function gray(f) {
  var val = Math.max(0, Math.min(255, Math.round(255 * f))) + '';
  return 'rgb(' + val + ',' + val + ',' + val + ')';
}

// register interpolator as a custom scheme
// now "mygray" can be used within Vega specs
vega.scheme("mygray", gray);

// retrieve scheme, check value
vega.scheme("mygray") === gray // true
```

You might use methods from the d3-interpolate library to help with this. The `vega.interpolate` function simply serves as a lookup for such d3 interpolators. In the example above, the function `gray` could alternatively be defined using `vega.interpolate('rgb')('#000', '#fff')`.

**Comment by amitvshah25** [comment]
Sorry for dumb question, but once I do 

vega.scheme('my-color-scheme', ["#D6EDFE", "#30A7FB"]);

I am doing 

view = new vega.View(vega.parse({..}))
        .renderer('canvas')  // set renderer (canvas or svg)
        .initialize('#view') // initialize view within parent DOM container
        .hover()             // enable hover encode set processing
        .run();

But it does not render anything, and throws no error ... If I have any of the predefined color schemes in my spec, it renders again ... Not sure what i am doing wrong .. ?
