### ISSUE TITLE
minified vega-core.js causes problems

### ISSUE THREAD

**Issue by slowkow** [vega/vega#1093]
Do you know why this is happening?

Eventually, I would like to create a single standalone html file that contains everything (css, javascript, html, etc.), but I anticipate that this issue is going to hold me back.

This html file works perfectly, without any errors:

### `vega-success.html`

```html
<html>
<head>
<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="https://vega.github.io/vega/vega-core.min.js"></script>
</head>
</html>
```

On the other hand, this one throws an error:

### `vega-error.html`

```html
<html>
<head>
<script src="js/d3.v4.min.js"></script>
<script src="js/vega-core.min.js"></script>
</head>
</html>
```

I downloaded the files like this:

```bash
mkdir js && cd js
wget https://d3js.org/d3.v4.min.js
wget https://cdnjs.cloudflare.com/ajax/libs/vega/3.0.8/vega-core.min.js
```

I'm serving the files like this:

```bash
python -m SimpleHTTPServer 8000
```

Here is the error (truncated because it is long):

```
Uncaught SyntaxError: Invalid regular expression: /[ÂªÂµÂºÃ€-Ã–Ã˜-Ã¶Ã¸-ËË†-Ë‘Ë -Ë¤Ë¬Ë®Í°-Í´Í¶Í·Íº-Í½Í¿Î†Îˆ-ÎŠÎŒÎŽ-Î¡Î£-ÏµÏ·-ÒÒŠ-Ô¯Ô±-Õ–Õ™Õ¡-Ö‡×-×ª×°-×²Ø -ÙŠÙ®Ù¯Ù±-Û“Û•Û¥Û¦Û®Û¯Ûº-Û¼Û¿ÜÜ’-Ü¯Ý-Þ¥Þ±ßŠ-ßªß´ßµßºà €-à •à šà ¤à ¨à¡€-à¡˜à¢ -à¢²à¤„-à¤¹à¤½à¥à¥˜-à¥¡à¥±-à¦€à¦…-à¦Œà¦à¦à¦“-à¦¨à¦ª-à¦°à¦²à¦¶-à¦¹à¦½à§Žà§œà§à§Ÿ-à§¡à§°à§±à¨…-à¨Šà¨à¨à¨“-à¨¨à¨ª-à¨°à¨²à¨³à¨µà¨¶à¨¸à¨¹à©™-à©œà©žà©²
```

Here's what I see in my console:

![localhost_8000_vega-error_html](https://user-images.githubusercontent.com/209714/34050369-9d23a0be-e188-11e7-9338-ff48f58611b0.png)

I'm using Chrome 63.0.3239.84 on a Mac.

**Comment by slowkow** [comment]
This works without errors!

### `vega-success2.html`

```html
<html>
<head>
<script src="js/d3.v4.min.js"></script>
<script src="js/vega-core.js"></script>
</head>
</html>
```

## How to fix this issue

The only difference between `vega-success2.html` and `vega-error.html` is the use of minification on `vega-core.js`.

The minified version does not work, and the non-minified version works perfectly.

So, with some bisection, it should be possible to figure out exactly why the minification is causing the error. (For example, delete half of the code, minifiy, load it and see if the error goes away. If the error disappears, then the problem is in the deleted half of the code.)

Still, I cannot explain why the error only appears when I host the file myself. This suggests that there might be an issue independent of the vega code, perhaps in the Chrome browser. I don't know.

**Comment by jheer** [comment]
Thanks for raising the issue. This appears to be a character set encoding issue. Perhaps the server-provided MIME type differs from the local Python server? In any case I was able to replicate the issue, and fix by making the character set explicit:

```html
<html>
<head>
<script src="js/d3.v4.min.js" charset="UTF-8"></script>
<script src="js/vega-core.min.js" charset="UTF-8"></script>
</head>
</html>
```

**Comment by jheer** [comment]
p.s. I will also inspect our build scripts. Perhaps by changing a parameter to the minifier we can prevent others from running into similar issues.

**Comment by slowkow** [comment]
Thank you! I did not know about the character set encoding.

**Comment by jheer** [comment]
UglifyJS does support an ascii-only export option that escapes unicode characters. Enabling this flag adds ~5kb to both vega.min.js and vega-core.min.js. Do we want to live with that extra 5kb? An alternative would be to update the usage documentation to use the script `charset` attribute. I'm leaning towards the latter, but am happy to consider any feedback on the issue.
