### ISSUE TITLE
chart type: candlestick

### ISSUE THREAD

**Issue by nimo23** [vega/vega#1095]
Please provide the chart type: candlestick.

**Comment by g3o2** [comment]
Vega is about a grammar of graphics, not about chart types. However, you will find an example in the vega-lite documentation.

**Comment by nimo23** [comment]
ok, thanks.

**Comment by kanitw** [comment]
@g3o2 -- Thanks for answering for us.  Just for a bit more context -- as a grammar of graphics, you can compose a variety of (interactive) visualizations using primitives where as charting library, while convenient for creating certain chart types, would provide you a limited number of fixed templates.
