### ISSUE TITLE
Flow layout [mark order] of layout engine not supported?

### ISSUE THREAD

**Issue by mattijn** [vega/vega#1097]
While reading the [layout specifications](https://vega.github.io/vega/docs/layout/) I can see the `columns` attribute, with which I can determine that I want my two group marks to be placed vertically (`"columns": 1,`), but is there any possibility to change the order of my group marks? The current flow layout seems to be the fixed to the order of group marks as is configured in the specification. 

Example use-case:: 
```
"marks": [{"type": "group", "name": "plot0"}, 
          {"type": "group", "name": "plot1"}] 
```

Current implementation with `"columns": 2`:
```
+------------------------+
|           ||           |
|  plot0    ||  plot1    |
|           ||           |
|           ||           |
+------------------------+
```
Current implementation with `"columns": 1`:
```
+-----------+
|           |
|  plot0    |
|           |
|           |
+-----------+
+-----------+
|           |
|  plot1    |
|           |
|           |
+-----------+
```
But I'm looking for the reversed order for the plots using `"columns":1` 
(hoping for something like `"order": [1,0]`)
```
+-----------+
|           |
|  plot1    |
|           |
|           |
+-----------+
+-----------+
|           |
|  plot0    |
|           |
|           |
+-----------+
```

**Comment by domoritz** [comment]
Can't you just add a `sort` to the group mark (https://vega.github.io/vega/docs/marks/)?

**Comment by mattijn** [comment]
I'm not sure how I would do that. The `sort` variable is placed within a `group` mark, but the `layout` specifications are only respected for multiple group marks. I tried to create a over-coupling single `group` mark including a `sort`, but then my two sub-groups are drawn on top of each other (while I didn't got the `sort` working properly, what is the `field` for the two `group-marks`?). 

Minimum specification:

```
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "data": [
    {
      "name": "arrows",
      "values": [
        {"x": 25,  "y": 25, "size": 50, "angle": -45, "color": "orange"},
        {"x": 75,  "y": 25, "size": 75, "angle": -50, "color": "blue"},
        {"x": 125, "y": 25, "size": 100,"angle": -60, "color": "red"},
        {"x": 25,  "y": 75, "size": 35, "angle": -30, "color": "orange"},
        {"x": 75,  "y": 75, "size": 50, "angle": -70, "color": "lightblue"},
        {"x": 125, "y": 75, "size": 75, "angle": -40, "color": "blue"},
        {"x": 25,  "y": 125,"size": 35, "angle":   0, "color": "orange"},
        {"x": 75,  "y": 125,"size": 50, "angle": -30, "color": "lightblue"},
        {"x": 125, "y": 125,"size": 75, "angle": -10, "color": "blue"}  
      ]
    }
  ],
  "layout": {
    "columns": 1,
    "bounds": "full",
    "align": "all"
  },  

  "marks": [
    {
      "type": "group",
      "name": "plot0",
      "marks": [
        {
          "type": "text",
          "from": {"data": "arrows"},      
          "encode": {
            "update": {
              "text": {"value": "☃"},
              "x": {"field": "x"},
              "y": {"field": "y"}, 
              "fill": {"field": "color"},       
              "angle": {"field": "angle"},
              "fontSize": {"field": "size"}
            }
          }
        }
      ]
    },
    {
      "type": "group",
      "name": "plot1",
      "marks": [
        {
          "type": "text",
          "from": {"data": "arrows"},      
          "encode": {
            "update": {
              "text": {"value": "☕"},
              "x": {"field": "x"},
              "y": {"field": "y"}, 
              "fill": {"field": "color"},       
              "angle": {"field": "angle"},
              "fontSize": {"field": "size"}
            }
          }
        }
      ]
    }
  ]   
}
```

**Comment by jheer** [comment]
Here is an overview regarding layout ordering:
- Across group mark specifications, the ordering within the specification is used.
- Within a group mark specification with multiple group instances, the `sort` directive can be used to order the group items, affecting both their rendering order and their order in the layout.

I'll update the [Layout documentation page](https://vega.github.io/vega/docs/layout/) to include this information.

**Comment by mattijn** [comment]
It's a few months later and I'm still struggling with this..

I've created a group mark including multiple group instances. I can change the layout using the value for `columns`, but still cannot find a way how to sort the group instances:
![autumn2](https://user-images.githubusercontent.com/5186265/46276475-7f6a3800-c560-11e8-8abd-4ad104b3dc5c.gif)


As can be seen I'm struggling with the `field` directive within `sort`. Currently I use:
```json
"sort": {"field":"mark.items[0].items","order":"descending"}, 
```

Because `VEGA_DEBUG.view._runtime.subcontext[0].group.mark.items[0].items` returns a two-element array of the nested groups. 

But this approach has no any effect on the ordering of the groups.

My code is available with the following encoded [long-url](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgGY6ABjoArWNwB2kADTgoAE3R5MOANqqIoCEajz0qZNijpWeVqkUrjESBXQAbVsliW9To8EgAD0sAJgBWJSgAT1CIqFhGAC8LHDCJSMh0eWo3FLAAWgAWOMh4bjduACdLSABiMIAOBvgAdlFIAF9HPzAA4JwWkpiccIyE5MtBjKycvPy0jLKK6pw6gDMQ9GQWkM7uvz7LAEZR6NixpLyjiXSrbNzLfIA2W9LyqpratQBOJ+Lvvb6JyHEZDSYlcZ5UQlGYPHD5USvJYfVb1JqtdpdIHGEFgKZnAYQy6WBZ3WaPFpI94rKC1DbIUTfQqAnq9ILHU6QYZ4okTQnTe5zQpU5afDZbHYsnq4znck68qEwwWWEUo2mNZptKUHdn8glgeUXPlgUmZZXwxGLalikIMpna4G6g2yjkK8EC8nw65W0Wo8XbXYdbFgAC6QKDEBD3UgGEqAGtvLogYYnJA8FFCHlINRKtxWIRlMHIKZzDUyqh2AB9QgVPCFvyQOSVOs4AJrRjINxqGqxuNcPBoWA6CQh-uD5RQKpqZA0yDThDIeRqRjZB3ONzoKJ5ltspZ2eSJsAhDLsPNLw+QNasNxuCeZNyMaiKVbuW9Yhu9w++aXB4xpjNZjmeYFvsPTFmYWY1tweASPWrJQJ+Pi-sCyENummY1AOgR1qB8FQGsuaoJYAQaFoNTWLY9hrvBkCLmU07EahYH5qReQpnhaHINhxEuO4ng1IAPBuAML71EcVA-Rsu2nbdqswTvmJqbcm2HZdjUMTyQpRiXowN48VJqmrMi1QaZpZJwpJKkyWZFgmZpl4KHgADKxKttp0k1JCnRMX4EYKb5eH+T0YasrZ-hMf+GGrEB+Zway4GlqsUF4EcsVgYhSZiexHERVmWE4d5WkEdwRGuaR2hWDY+6iWBdHcAxrYFX+LGaGxjWpnlPGuB4WaAKhk1V4U6ynubJ-U0UpbkGWcoVidpumufpVlvKK03ZbCbETYta2jXFawOc5xpDZNjbEoFYmnfB50+UxwU9OdN0QL5YYdEAA)


<details>
  <summary>Or click here</summary><p>

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "data": [
    {
      "name": "autumn",
      "values": [
        {"x": 25, "y": 25, "size": 50, "angle": -45, "color": "#588c73"},
        {"x": 75, "y": 25, "size": 75, "angle": -50, "color": "#f2ae72"},
        {"x": 125, "y": 25, "size": 100, "angle": -60, "color": "#d96459"},
        {"x": 25, "y": 75, "size": 35, "angle": -30, "color": "#588c73"},
        {"x": 75, "y": 75, "size": 50, "angle": -70, "color": "#f2e394"},
        {"x": 125, "y": 75, "size": 75, "angle": -40, "color": "#f2ae72"},
        {"x": 25, "y": 125, "size": 35, "angle": 0, "color": "#588c73"},
        {"x": 75, "y": 125, "size": 50, "angle": -30, "color": "#f2e394"},
        {"x": 125, "y": 125, "size": 75, "angle": -10, "color": "#f2ae72"}
      ]
    }
  ],
  "marks": [
    {
      "type": "group",
      "name": "comb_plot",
      "sort": {"field": "mark.items[0].items", "order": "descending"},
      "layout": {"columns": 2, "bounds": "full", "align": "all"},
      "marks": [
        {
          "type": "group",
          "name": "plot0",
          "marks": [
            {
              "type": "text",
              "from": {"data": "autumn"},
              "encode": {
                "update": {
                  "text": {"value": "🍃"},
                  "x": {"field": "x"},
                  "y": {"field": "y"},
                  "fill": {"field": "color"},
                  "angle": {"field": "angle"},
                  "fontSize": {"field": "size"}
                }
              }
            }
          ]
        },
        {
          "type": "group",
          "name": "plot1",
          "marks": [
            {
              "type": "text",
              "from": {"data": "autumn"},
              "encode": {
                "update": {
                  "text": {"value": "☕"},
                  "x": {"field": "x"},
                  "y": {"field": "y"},
                  "fill": {"field": "color"},
                  "angle": {"field": "angle"},
                  "fontSize": {"field": "size"}
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
```
</details>
