### ISSUE TITLE
generate specific interface (let's say, bs4) from Vega

### ISSUE THREAD

**Issue by Casyfill** [vega/vega#1098]
is there any way to generate specific interface / general purpose HTML from within Vega specification? I want to use bootstrap dropdown (which is div, technically), and not only to bundle it with Vega's signal, but also to create them from within Vega. Will be thankful for any direction! (sorry, didn't find any gitter for that question)

**Comment by jheer** [comment]
I think you're asking if you can have the bound input elements (generated for signal `bind`) targeted to specific elements on an HTML page? If so, the answer is yes. You can either:

- Send all elements generated via `signal.bind` placed in a target container by using the second argument to the [View.initialize](https://vega.github.io/vega/docs/api/view/#view_initialize) method.
- Target specific input elements to a specific DOM element from the specification itself by including an [`element` directive within the signal `bind` specification](https://vega.github.io/vega/docs/signals/#bind).
