### ISSUE TITLE
height limitation?

### ISSUE THREAD

**Issue by JoeVirtual** [vega/vega#1102]
Hello, 
is there a limitation to the allowed _"height"_ of a _tree_ graph?

I have a _tree layout_ with many nodes (approximatly 1500 end nodes) and if the _"height"_ is set greater than _16384_ the displayed nodes at the bottom start to "smear". 

You can reproduce the described effect with your own provided example (https://vega.github.io/vega/examples/tree-layout) for a _tree layout_ by setting the _"height"_ to 17000.

Thanks and a happy new year.

**Comment by jheer** [comment]
Vega itself does not set a height limit, but the browser puts limits on the size of a canvas element. In such cases, you can switch to use the SVG renderer instead.

For more see https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element

**Comment by JoeVirtual** [comment]
Thanks for the info.
