### ISSUE TITLE
Not able to create an autosize object in config

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1103]
From https://github.com/vega/vega-lite/issues/3250, Vega-lite only passes the config to Vega -- so this is an error in Vega

> Perhaps I'm missing something, but if I try to create an `autosize` object in `config`, Vega-Lite reports the fatal error `TypeError: Attempted to assign to readonly property.`. The documentation implies that `config` can use `autosize` with an object parameter. This becomes a problem when wishing to set some of the other autosize parameters that require an object (`resize` and `contains`)
> 
> This is valid:
> 
>     "config": {"autosize":"fit"}
> 
> But this generates the error:
> 
>     "config": {"autosize": {"type":"fit"}}
> 
> Setting the same as a top level property rather than via `config` works fine:
> 
>     "autosize":{"type":"fit"}
> 
> 
>

**Comment by jheer** [comment]
Fixed in vega-parser v2.4.0 and released in vega 3.0.9.
