### ISSUE TITLE
Gitter?

### ISSUE THREAD

**Issue by Casyfill** [vega/vega#1110]
Hey, can we perhaps set up a gitter or any other discussion platform for Vega?
I am having a hard time with plenty of simples questions, and not sure where to ask them (issues definitely not meant for that, and StackOverflow does not help much). Thank you!

**Comment by domoritz** [comment]
You can ask questions on the mailing list: https://groups.google.com/forum/#!forum/vega-js

**Comment by jheer** [comment]
We have also opened up our Slack organization to the Vega community. You can sign up here: https://communityinviter.com/apps/vega-js/join

That said, the mailing list is still the preferred place to post questions for usage help!
