### ISSUE TITLE
Is there a way to add arrowheads to a graph?

### ISSUE THREAD

**Issue by stathissideris** [vega/vega#1111]
I'd like to visualize a graph where the direction of the connections is significant, not just the links between nodes. Is it possible to add arrowheads to the linkpath? (or any other way)

**Comment by domoritz** [comment]
Yeah, check out this example by @kanitw https://github.com/vega/vega-lite/pull/3283/files?short_path=186d624#diff-8d3db2764434588a085647a3bbb1cb4d. He uses `triangle-right` and `triangle-left` shapes.

**Comment by stathissideris** [comment]
Apologies for asking here, thanks for the prompt reply!

**Comment by kanitw** [comment]
The triangle shapes solution only works well for orthogonal lines though.
