### ISSUE TITLE
Different CDN

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1113]
Filing here but it's relevant for Vega-Lite as well. 

We should consider using a different CDN in our docs as cdnjs takes a day or tow to update after we make a release during which the example code in our docs doesn't work. 

I don't know what the alternatives are but https://unpkg.com looks promising and came up first in a quick google search. It should be trivial to switch but I don't want to make the decision alone. 

cc @yifanwu

**Comment by jheer** [comment]
Thanks, unpkg is fine with me. We can also add an entry to `package.json` if we want it to point to the minified file by default. There is also https://www.jsdelivr.com/

I just checked and D3 includes entries for both in it's package.json.

**Comment by domoritz** [comment]
jsdelivr looks more mature. Let's go with that one.

I added the CDN links to the package.json for vega-embed in https://github.com/vega/vega-embed/commit/d926de007f3b57e7f0a379a2046f11da17232b12

**Comment by domoritz** [comment]
Switched to jsdelivr Vega-Lite in https://github.com/vega/vega-lite/pull/3307

**Comment by domoritz** [comment]
Corresponding Vega PR: https://github.com/vega/vega/pull/1114

**Comment by domoritz** [comment]
I've update Vega-Lite, Vega-Embed, and Vega-Tooltip. The remaining Vega docs changes are coming in https://github.com/vega/vega/pull/1114.
