### ISSUE TITLE
ascending sort of ordinal scale for stacked bar chart

### ISSUE THREAD

**Issue by tvald** [vega/vega#1115]
#515 describes how to sort a simple bar chart by value (height), but that method doesn't work for a stacked bar chart. Is there a field similar to `y` which contains the sum of grouped values?

Excerpt from #515 with sorted domain:
```js
{
    domain: {
      data: 'rows',
      field: KEY_CATEGORY_1,
      sort: { field: 'y', op: 'max' },
    }
}
```

The spec we're using to stack is:
```js
{
    transform: {
      type: 'stack',
      groupby: [KEY_CATEGORY_1],
      sort: { field: KEY_CATEGORY_2 },
      field: KEY_VALUE,
    },
}
```

**Comment by jheer** [comment]
You might try creating a derived aggregated dataset that groups by `KEY_CATEGORY_1` and computes the sum by which you wish to sort. Then use this dataset as the `data` input for your ordinal scale.

Derived data set with aggregate transform:
```js
{
  "name": "agg",
  "source": "rows",
  "transform": [
    {
      "type": "aggregate",
      "groupby": [KEY_CATEGORY_1],
      "ops": ["sum"],
      "fields": ["y"],
      "as": ["ysum"]
    }
  ]
}
```

Updated scale domain:
```js
{
  domain: {
    data: 'agg',
    field: KEY_CATEGORY_1,
    sort: { field: 'ysum', op: 'max' },
  }
}
```
