### ISSUE TITLE
Document view.runAsync()

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1119]
I'm not sure whether this is part of the public API. It would be useful to have access to this method to wait for the dataflow to run before adding an element to a page. See https://talk.observablehq.com/t/bug-report-layout-gets-pushed-around/111/3

cc @mbostock

**Comment by domoritz** [comment]
Relevant: https://github.com/vega/vega/issues/908

**Comment by jheer** [comment]
`View` is a subclass of `Dataflow`, and `runAsync` is a public method of `Dataflow`. So yes, `view.runAsync()` is callable and returns a Promise that resolves once the dataflow graph re-evaluates.

**Comment by domoritz** [comment]
Great, I will send a PR to add documentation to https://vega.github.io/vega/docs/api/view/.
