### ISSUE TITLE
Listen for resize events

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1120]
In Observable, cells need to know when an element is resized. Either Vega provides a way to listen for any kind of dataflow executions or ideally an API to listen for resize events of the canvas or SVG. 

There is a discussion about this issue at https://talk.observablehq.com/t/bug-report-layout-gets-pushed-around/111. 

There is a proposal for a browser API but it is not implemented yet: https://wicg.github.io/ResizeObserver/.

**Comment by jheer** [comment]
Other than initialization, resizing of a Vega View's output canvas or SVG is performed here: https://github.com/vega/vega-view/blob/master/src/View.js#L111
This might be a good starting point for adding a resize listener.

That said, I'd need a bit more context / description to understand what precisely you are (or aren't) requesting here, and how it would interface with environments such as Observable.

**Comment by domoritz** [comment]
Cells in Observable need to know the dimensions of the elements that are in them. However, since Vega can asynchronously re-execute and change the size of the (SVG or canvas) element, Observable has no way of knowing when it needs to resize cells. To fix this, the Vega view could add a method to register resize listeners. I am thinking of something like https://github.com/vega/vega-view/pull/18. 

CC @mbostock

**Comment by jheer** [comment]
View resize listeners added in Vega 3.1.
