### ISSUE TITLE
[Docs] use &nbsp; instead of space between brackets

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1132]
Many doc pages use this expression:  `{% include type t="Number[]" %}`.  It produces `number[ ]`, with a space between the square brackets, but browsers often insert a space in between, making it look bad.  I am not exactly sure where the actual HTML generation takes place. Please use `&nbsp;` instead of the space for it. Thanks!

**Comment by jheer** [comment]
We currently [use a punctuation space (`&#8200;`)](https://github.com/vega/vega/blob/master/docs/_includes/array#L1), as a full space character (which is what `&nbsp;` uses) seemed to wide.

Perhaps the narrow no-break space (`&#8239;`) will suffice?

**Comment by nyurik** [comment]
sure, as long as its nonbreaking :)

**Comment by jheer** [comment]
Switched to use `&#8239;`.
