### ISSUE TITLE
Use of geoshape size to encode data

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1134]
I would like to encode some data with the size of a geoshape. This would allow us to build a chart like https://beta.observablehq.com/@jashkenas/quakespotter-0-1. 

Related Vega-Lite issue: https://github.com/vega/vega-lite/issues/3335

**Comment by jheer** [comment]
I need a bit more specificity here. Do you mean you wish to set the [`pointRadius`](https://github.com/d3/d3-geo#path_pointRadius) for `d3.geoPath`? Or something else?

**Comment by domoritz** [comment]
> Do you mean you wish to set the pointRadius for d3.geoPath?

Yes, that would be sufficient for the use case I have. I would like yo have the equivalent of `size` for `symbol` marks but for Point and MultiPoint geometries. I assume that the size would be in pixels, is that right? 

I don't think resizing complex shapes makes much sense because we would need to measure the area and resize the shapes accordingly (similar to https://www.census.gov/dataviz/visualizations/021/res/graphics/021_cartograms_201_1x-01.png).

**Comment by jheer** [comment]
Added in Vega 3.1! The `geopath` and `geoshape` transforms now support an `Expr`-valued `pointRadius` parameter. To see it in action, see the [earthquakes example](https://vega.github.io/vega/examples/earthquakes/).
