### ISSUE TITLE
Formatting a parsed date on an axis throws error

### ISSUE THREAD

**Issue by tomtaylor** [vega/vega#1137]
I'm using vega 3.0.10 to parse a date from a JSON blob. I'd like to format the date on the x-axis as a `%H:%M` time, but it throws an error `ERROR Error: invalid format: %H:%M`. Curiously, I'm able to format it as `.2`, leading me to believe it's being stored as a `number` internally.

I've uploaded the spec over here:

https://gist.github.com/tomtaylor/55d50eca2a928f37855a5b32f1188745

If you change line 491 to "%H:%M" it throws the error.

**Comment by jheer** [comment]
The x axis scale type is `linear`, which assumes numeric data. Try changing it to type `time`!

**Comment by tomtaylor** [comment]
Oh! Thank you @jheer!
