### ISSUE TITLE
Mark's sort behave inconsistent across browser and may be unstable?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1140]
Originally we see a report that the sort is inconsistent across browser:  https://github.com/vega/vega-lite/issues/3243

Basically this [vega-lite spec](https://pastebin.com/gp2fc47d), shows different result in Chrome and Firefox.  

![vega_editor](https://user-images.githubusercontent.com/111269/36069852-abceb154-0ea5-11e8-8ea6-96da0e1aaf49.png)
![vega_editor](https://user-images.githubusercontent.com/111269/36069882-b5636764-0ea5-11e8-9d45-2c62edb78a1a.png)

I also found that applying filter transform for a data subset in Chrome may make the order change as well.  

For example, if I add `{"filter": "datum.rating > 4000"}` to the top-level

![item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_appletimemachineextra_and_applebluetoothextra_and_airportextra_and_batteryextra_and_appletextinputextra_and_appleclockextra_and_appleuser_and_item-0_and](https://user-images.githubusercontent.com/111269/36069914-01074816-0ea6-11e8-813e-2ad16ca87529.png)

(Note I post a Vega-Lite spec here as it's easier to modify but you can paste it in the editor -- I believe that the problem lies at the Vega level though.)

**Comment by jheer** [comment]
This looks like the result of unstable sorting in the face of duplicate keys (which can vary across browser). Vega makes no claims regarding sort stability at present.

One option could be to also sort by internal vega ID values to get consistency. In addition, it might be possible for VL to generate unambiguous sort definitions.

**Comment by jheer** [comment]
FYI I added a stable sort criteria for mark-based sorting. In addition to whatever sort criteria provided, it will secondarily sort in ascending order by Vega's internal tuple IDs (basically a counter for the order in which tuples are first observed). This will be included in the Vega 3.1 release.

There still may be cases where additional user-level sorting criteria are desired! In the example above the dip seen in the Firefox version reflects the actual data observation order (Chrome does not!). If a monotonic progression is desired, the generated Vega spec should include sort criteria both for increasing x and for increasing y.

**Comment by roy7** [comment]
Great, thanks. :) At the time I was making this chart I could have reversed the order of the data points, but that'd reverse it in both browsers and so it'd still remain wrong for some viewers. With the sort being stable, that wouldn't have happened and all would be well. (To work around it at the time I added a tiny increment to the data points to make them non-unique.)

**Comment by jheer** [comment]
Fixed in Vega 3.1! We now use a stable sort, based on ascending order of Vega tuple ids.
