### ISSUE TITLE
xfocus and yfocus are not documented nor in schema

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1142]
The [beeswarm plot example](https://vega.github.io/editor/#/examples/vega/beeswarm-plot) uses `xfocus` and `yfocus` in the symbol mark, yet it is not documented anywhere. There is also no mentioning of it in [schema.json 3.0.10](https://github.com/vega/schema/blob/master/vega/v3.0.10.json).

**Comment by jheer** [comment]
Vega supports inclusion of arbitrary properties within encoding blocks. The schema allows this, as the `encode` block schema includes `"additionalProperties": true` for this purpose.

In the beeswarm example these properties are added to conveniently record the focus coordinates in properties that are not overridden by the force layout. It might be useful to add a sentence about this to https://vega.github.io/vega/examples/beeswarm-plot/.

**Comment by jheer** [comment]
I updated both the marks documentation and beeswarm description to include mention of arbitrary encode property names.

**Comment by nyurik** [comment]
@jheer thanks!  I was not aware that you can define your own encoding channels beyond the built-in ones like `fill` and `stroke`.  Is there a documentation somewhat that describes how these channels can be created, how Vega treats them, and how they can be used in other parts of the graph?  Thanks!

**Comment by nyurik** [comment]
@jheer sorry, I think I missed the comment about the doc update.  From what I read in the doc change, does it mean Vega mark encoding values (stroke, fill, ...) can be thought of as magical `formula` transforms that change the datum? And any other transforms that are part of the mark can use these values as if they came from the data source?

**Comment by jheer** [comment]
Not quite. The datum objects are untouched. The properties defined by encoders (x, y, fill, ...) are written to the **scenegraph items**. But otherwise, yes, other transforms _defined in a `mark` context (not in a `data` context)_ can use those values.

**Comment by nyurik** [comment]
@jheer that's still a bit confusing.  The [forces doc](https://vega.github.io/vega/docs/transforms/force/#forces) lists `x` param as [a number](https://vega.github.io/vega/docs/types/#Number), but [beeswarm example](https://vega.github.io/editor/#/examples/vega/beeswarm-plot) specifies `"x": "xfocus"`. Aside from the [types documentation issue](https://github.com/vega/vega/issues/1139), `xfocus` string somehow gets resolved to accessing a scenegraph item, whereas most transforms only access signals and datum. What are the resolution rules? Does it say anywhere when transform accesses scenegraph vs regular datum/signal expressions?  Lastly, if understanding scenegraph is critical for writing Vega, should some of the [vega-scenegraph](https://github.com/vega/vega-scenegraph) docs be moved to the documentation?
