### ISSUE TITLE
gradient() expression func throws an error on scale name

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1143]
Adding this type of a formula transform causes `scale.domain is not a function` error.

```json
        {
          "type": "formula",
          "expr": "gradient('color', [0,0], [100,300])",
          "as": "blah"
        }
```

P.S. I so wish I could use the output of this function with the `stroke` mark parameter - so that a line would gradually change its color from one point to the next.

**Comment by jheer** [comment]
Fixed in vega-parser v2.5.1, will be included in next Vega release.
