### ISSUE TITLE
Feature request - Set data URL with a signal

### ISSUE THREAD

**Issue by banutr** [vega/vega#1147]
Hi,

Please add support  to provide signal to 'url' param of data in spec to the existing  String type.
Since assets/ data end points of different apps are not the same, it helps to have a signal set URL thus giving the flexibility to the app.

Here's the post on forum which has more details:
https://groups.google.com/forum/#!topic/vega-js/4cO1ZjbKJJc

The workaround was to edit the spec & have vega re-render. 
While this works, it's still a lot of action for setting a URL

**Comment by nyurik** [comment]
I think this is a dup of https://github.com/vega/vega/issues/523

**Comment by nyurik** [comment]
Also, this might be implemented by #912
