### ISSUE TITLE
Feature request - YAML support for vega spec

### ISSUE THREAD

**Issue by banutr** [vega/vega#1148]
Hi,

Can YAML be added as a format to specify spec.

Since YAML is better readable & can also allows comments,
it's easier to both document & maintain the spec.

For those who are looking for a way to use YAML in current version of vega here's something that might help if your building tool is webpack:

Load the YAML using [yaml-loader](https://www.npmjs.com/package/yaml-loader) which converts it to JSON.

**Comment by jheer** [comment]
Thanks for the suggestion! You are of course free to use YAML to write specs. Simply convert it to JSON, and pass the JSON to vega.parse as usual. There is really only more line of code involved. As such, we have no plans to add a YAML converter dependency to this main Vega repo.

However, this might be of interest within the vega-embed or vega-editor projects, so feel free to file feature requests there!

**Comment by domoritz** [comment]
We've talked about YAML before but the consensus was that we don't want to have two ways of writing specs as it would mean that we need to have docs for JSON and YAML and we would need to debug specs written in both languages. You can find more detail at https://github.com/vega/vega-editor/issues/54#issuecomment-220524034. As Jeff said, it's easy to use YAML in your own application as YAML is a strict superset of JSON (for example http://visdown.com/ by @amitkaps) but we are hesitant to support it in our (low level) libraries.
