### ISSUE TITLE
Add "flatten" transformation

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1155]
A very common usecase we see with Elasticsearch results is visualizing multi-level aggregation results such as [these](https://gist.github.com/nyurik/93feb77955e068ab804bcf7f20a8aeb5), or in a simplified form:

```js
[
  { key:'a', nested: [ {v:1}, {v:2} ]}
  { key:'b', nested: [ {v:3}, {v:4}, {v:5} ]}
]
```
which needs to be flattened out into a form usable by Vega:
```js
[ {key:'a', v:1}, {key:'a', v:2}, {key:'b', v:3}, {key:'b', v:4}, {key:'b', v:5} ]
```

I would like to propose a `flatten` transform with these params. I think some of them are similar to the lookup transform.

```js
{
  type: "flatten",

  // Should work the same way as "format.property" in "data",
  // e.g. allow values like "subfield[0].subsubfield".
  property: "nested"

  // Optionally keep just these fields from the current object (performance)
  // otherwise will keep everything.
  // For the above example, we don't need to keep the "nested" field in the result
  parentFieldsToKeep: ["key"]

  // Optionally copy just the selected values (performance)
  // otherwise will copy everything. Similar to "values" in lookup transform.
  // The above example has only the "v" field anyway, so this line has no effect.
  values: ["v"]

  // Optional, similar to "as" in lookup transform.
  // If subfieldToCopy is given, must be an array of the same size, otherwise must be a string.
  // For array, specifies that "v" (from above) should be set as "newV" in the object.
  // When copying the whole object, this is the 
  as: ["newV"]
}
```
Needs better param names.

## Flattening object subvalues
This portion could be implemented at a later date. I did see a case like this, but I think this is less frequent than the above. Transform params are TBD.

```js
[
  { key:'a',  nested: {foo:1, bar:2}}
  { key:'b',  nested: {foo:3, bar:4, baz:5}}
]
```
Expected result could be one of these. Either treat object as an array of one element:
```js
[ {key:'a', foo:1, bar:2}, {key:'b', foo:3, bar:4, baz:5} ]
```
or convert each key-value pair into a separate object:
```js
[
 {key:'a', k:'foo', v:1}, {key:'a', k:'bar', v:2},
 {key:'b', k:'foo', v:3}, {key:'b', k:'bar', v:4}, {key:'b', k:'baz', v:5}
]
```
The second case can be enabled with a `flattenObjects: ["k", "v"]`, specifying the key-value field names. If the value is `false`, autoconvert objects to single value arrays.  The default is TBD.

## Flattening other values
In case the value is neither an array nor an object, we could treat it similar to the second variant of the object expansion. It becomes equivalent to a formula transform.
```js
[ { key:'a', nested: "meaning" },  { key:'b', nested: 42 } ]
```
```js
[ {key:'a', v:'meaning'}, {key:'b', v:42} ]
```

## Multi-level and multi-item flattening
This could be solved by chaining several `flatten` transforms together.  @jheer, if there is a significant performance hit of using several chained transforms to achieve this, lets define how to parametrize this. Otherwise, not worth it.

There are two cases when multiple flattening operations may be required: multiple lists in the same object under different fields:
```js
[
  { key:'a',  nested1: [ {v:1}, {v:2} ],  nested2: [ {v:3}, {v:4} ]}
  { key:'b',  nested1: [ {v:5}, {v:6} ],  nested2: [ {v:7}, {v:8} ]}
]
```
The second case is sub-level with sub-sub-level
```js
[
  { key:'a',  nested: [ { sub: [ {v:1}, {v:2} ] }, { sub: [ {v:3}, {v:4} ]}]}
  { key:'b',  nested: [ { sub: [ {v:5}, {v:6} ] }, { sub: [ {v:7}, {v:8} ]}]}
]
```
This array of 8 values is the expected result in both cases:
```js
[
 {key:'a', v:1}, {key:'a', v:2}, {key:'a', v:3}, {key:'a', v:4},
 {key:'b', v:5}, {key:'b', v:6}, {key:'b', v:7}, {key:'b', v:8}
]
```

**Comment by jheer** [comment]
Thanks! Would be nice to further define the specification before considering implementation.
- Is unnesting of object keys (not just arrays) needed?
- Is recursive flattening also needed? Or should that be handled via multiple flattens.
- Etc.

**Comment by nyurik** [comment]
@jheer I clarified it a bit -  I think I hit save too early the first time.
* I am not sure what you mean by "unnesting of object keys (not just arrays)". Could you give an example?
* I think recursive flattening is not necessary because that can be done with multiple transforms, unless you can think of some significant performance benefits. Defining what to take from each level might become overly complex and error prone from a single transform.
thx!

**Comment by nyurik** [comment]
I think I understood what you meant by object keys, so added them into the ticket. We could spec it out but leave implementation of this case for later, as this is not as urgent

**Comment by nyurik** [comment]
I just did some tests on the implementation, works perfectly, thanks!   My only concern - is there a performance impact for copying the original source object, or is it never gets cloned recursively?

**Comment by jheer** [comment]
Added in Vega 3.1!

There is some overhead with copying source objects, but it is not too bad in practice (particularly as these transforms tend to be run once upon initialization and never run again). Vega already does object copying internally whenever a derived data source includes transforms that would modify the upstream data -- otherwise you could end up polluting your data across distinct data streams.

**Comment by seanziee** [comment]
@nyurik Would you mind pasting your tests you did for the flatten transform? I'm having some issues getting the data out correctly from the ES aggregations and it would be nice to see what you did! :)

**Comment by seanziee** [comment]
I can’t figure out the usage when I have an aggregated/nested
aggregated result. For example, how do I flatten data in this format:

```
"aggregations": {
    "InfluencerName": {
      "doc_count_error_upper_bound": 839,
      "sum_other_doc_count": 35818,
      "buckets": [
        {
          "key": "Aubrey Graham (Drake)",
          "doc_count": 4474,
          "brand": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 1342,
            "buckets": [
              {
                "key": "Nike",
                "doc_count": 1250
              },
              {
                "key": "Moncler",
                "doc_count": 1120
              },
              {
                "key": "OVO",
                "doc_count": 762
              }
            ]
          }
        },
        {
          "key": "Ariana Grande",
          "doc_count": 3958,
          "brand": {
            "doc_count_error_upper_bound": 119,
            "sum_other_doc_count": 2670,
            "buckets": [
              {
                "key": "La Perla",
                "doc_count": 485
              },
              {
                "key": "Alex Woo",
                "doc_count": 428
              },
              {
                "key": "Levi's",
                "doc_count": 375
              }
            ]
          }
        }
      ]
    }

```

I’ve tried all different variations for the `fields` parameter to no
avail! I’m pushing it into a `nest` transform afterwards to then go
into a treemap diagram. I’ll post the results once I figure it out but
would appreciate any help with the flatten transform!

**Comment by nyurik** [comment]
@seanziee try to use `console.table(VEGA_DEBUG.view.data('source'))` from browser's dev console - you will see what this transform will look like.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "width": 400,
  "height": 200,
  "padding": 5,
  "data": [
    {
      "name": "source",
      "values": {
        "aggregations": {
          "InfluencerName": {
            "buckets": [
              {
                "key": "Aubrey Graham (Drake)",
                "brand": {
                  "buckets": [
                    {
                      "key": "Nike",
                      "doc_count": 1250
                    },
                    {
                      "key": "Moncler",
                      "doc_count": 1120
                    },
                    {
                      "key": "OVO",
                      "doc_count": 762
                    }
                  ]
                }
              },
              {
                "key": "Ariana Grande",
                "brand": {
                  "buckets": [
                    {
                      "key": "La Perla",
                      "doc_count": 485
                    },
                    {
                      "key": "Alex Woo",
                      "doc_count": 428
                    },
                    {
                      "key": "Levi's",
                      "doc_count": 375
                    }
                  ]
                }
              }
            ]
          }
        }
      },
      "format": {
        "property": "aggregations.InfluencerName.buckets"
      },
      "transform": [
        {
          "type": "flatten",
          "fields": ["brand.buckets"],
          "as": ["val"]
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "band",
      "domain": {
        "data": "source",
        "field": "val.key"
      },
      "range": "width"
    },
    {
      "name": "y",
      "type": "linear",
      "round": true,
      "nice": true,
      "zero": true,
      "domain": {
        "data": "source",
        "field": "val.doc_count"
      },
      "range": "height"
    }
  ],
  "axes": [
    {
      "scale": "x",
      "grid": true,
      "domain": false,
      "orient": "bottom",
      "tickCount": 5
    },
    {
      "scale": "y",
      "grid": true,
      "domain": false,
      "orient": "left"
    }
  ],
  "marks": [
    {
      "name": "marks",
      "type": "symbol",
      "from": {"data": "source"},
      "encode": {
        "update": {
          "y": {
            "scale": "y",
            "field": "val.doc_count"
          },
          "x": {"scale": "x", "field": "val.key"},
          "size": {"value": 30},
          "shape": {"value": "circle"},
          "strokeWidth": {"value": 2},
          "opacity": {"value": 0.5},
          "stroke": {"value": "#4682b4"},
          "fill": {"value": "transparent"}
        }
      }
    }
  ]
}
```

**Comment by seanziee** [comment]
Ok awesome! Thanks for your help and I've gotten very close; I've been working through it and I'm 90% there. I have one last question. My final ES query I'd like to use a filtered query agg and the flattening isn't quite working for the format that the filtered query comes in.

My query that I'm sending off is:
```
"size": 0,
      "aggs": {
        "InfluencerName": {
          "terms": {
            "field": "personname.keyword",
            "size": 5
          },
          "aggs": {
            "brand": {
              "filters": {
                "filters": {
                  "Field1": {
                    "query_string": {
                      "query": "*",
                      "default_field": "event"
                    }
                  },
                  "Field2": {
                    "query_string": {
                      "query": "a*",
                      "default_field": "event"
                }
              }
            }
          }
        }
      }
    }
 }
```
My result set comes back something like this:
```
"aggregations": {
    "InfluencerName": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 121,
      "buckets": [
        {
          "key": "Peter",
          "doc_count": 74,
          "brand": {
            "buckets": {
              "Field1": {
                "doc_count": 0
              },
              "Field2": {
                "doc_count": 74
              }
            }
          }
        },
        {
          "key": "Mike",
          "doc_count": 57,
          "brand": {
            "buckets": {
              "Field1": {
                "doc_count": 1
              },
              "Field2": {
                "doc_count": 56
              }
            }
          }
        }
```
I'm having a hard time flattening the data because the structure for a filtered query is a bit different( I think maybe because the names `Field1` and `Field2` are not "key" as it is with the nested agg) and I'm curious if this would need a feature request or if I'm missing something. How would I be able to get a filtered query like this to work?

Also, this is my working code for making a tree diagram with a nested aggregation for anyone's reference!
```
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
    "width": 960,
  "height": 500,
  "padding": 12.5,

"signals": [
    {
      "name": "layout", "value": "squarify",
      "bind": {
        "input": "select",
        "options": [
          "squarify",
          "binary",
          "slicedice"
        ]
      }
    },
    {
      "name": "aspectRatio", "value": 1.6,
      "bind": {"input": "range", "min": 0.2, "max": 5, "step": 0.1}
    }
  ],
  "data": [
    {
      "name": "tree",
      "url": {
    //  %context%: true
     // %timefield%: @timestamp
      
      index: all
      body : {
          size:0,
          aggs: {
            InfluencerName: {
              terms: {
                field: personname.keyword
                size: 2
          
              },
              aggs: {
                brand: {
                  terms: {
                    field: brandname.keyword
                  }
                }
              }
            }
          }
        }
      }
       # We only need a specific array of values from the response
      format: {property: "aggregations.InfluencerName.buckets" }
      "transform": [
        {
          "type": "flatten",
          "fields": ["brand.buckets"],
          "as": ["val"]
        },
        {
          "type": "nest"
          "keys":["key","val.key"],
          "generate": true
          
        },
           {
          "type": "treemap",
          "field": "doc_count",
          "sort": {"field": "doc_count"},
          "round": true,
          "method": {"signal": "layout"},
          "ratio": {"signal": "aspectRatio"},
          "size": [{"signal": "width"}, {"signal": "height"}]
        }
      ] 
    },
    {
      "name": "nodes",
      "source": "tree"
      "transform": [{ "type": "filter", "expr": "datum.children" }]
    },
    {
      "name": "leaves",
      "source": "tree",
      "transform": [{ "type": "filter", "expr": "!datum.children" }]
    }
  ],
  "scales": [
    {
      "name": "color",
      "type": "ordinal",
      "range": [
        "#3182bd", "#6baed6", "#9ecae1", "#c6dbef", "#e6550d",
        "#fd8d3c", "#fdae6b", "#fdd0a2", "#31a354", "#74c476",
        "#a1d99b", "#c7e9c0", "#756bb1", "#9e9ac8", "#bcbddc",
        "#dadaeb", "#636363", "#969696", "#bdbdbd", "#d9d9d9"
      ]
    },
    {
      "name": "size",
      "type": "ordinal",
      "domain": [0, 1, 2, 3],
      "range": [256, 28, 21, 14]
    },
    {
      "name": "opacity",
      "type": "ordinal",
      "domain": [0, 1, 2, 3],
      "range": [0.15, 0.5, 0.8, 1.0]
    }
  ],

  "marks": [
    {
      "type": "rect",
      "from": {"data": "nodes"},
      "interactive": false,
      "encode": {
        "enter": {
          "fill": {"scale": "color", "field": "key"}
        },
        "update": {
          "x": {"field": "x0"},
          "y": {"field": "y0"},
          "x2": {"field": "x1"},
          "y2": {"field": "y1"}
        }
      }
    },
    {
      "type": "rect",
      "from": {"data": "leaves"},
      "encode": {
        "enter": {
          "stroke": {"value": "#fff"}
        },
        
        "update": {
          "x": {"field": "x0"},
          "y": {"field": "y0"},
          "x2": {"field": "x1"},
          "y2": {"field": "y1"},
           "fill": {"value": "transparent"}
        },
        "hover": {
          "fill": {"value": "red"}
        }
      }
    },
    {
      "type": "text",
      "from": {"data": "nodes"},
      "interactive": false,
      "encode": {
        "enter": {
          "font": {"value": "Helvetica Neue, Arial"},
          "align": {"value": "center"},
          "baseline": {"value": "middle"},
          "fill": {"value": "#000"},
          "text": {"field": "key"},
          "fontSize": {"scale": "size", "field": "depth"},
          "fillOpacity": {"scale": "opacity", "field": "depth"}
        },
        "update": {
          "x": {"signal": "0.5 * (datum.x0 + datum.x1)"},
          "y": {"signal": "0.5 * (datum.y0 + datum.y1)"}
        }
      }
    }
  ]
}


```

**Comment by nyurik** [comment]
@seanziee I don't think you need `flatten` transform for your data. When you have a pre-defined list of sub-aggregations (Field1, Field2), you can use a [fold transform](https://vega.github.io/vega/docs/transforms/fold/) instead:

```json
        {
          "type": "formula",
          "expr": "datum.brand.buckets.Field1.doc_count",
          "as": "field1"
        },
        {
          "type": "formula",
          "expr": "datum.brand.buckets.Field2.doc_count",
          "as": "field2"
        },
        {
          "type": "fold",
          "fields": ["field1", "field2"],
          "as": ["subField", "subCount"]
        }
```

Note that you don't actually need to use formula transforms, and use the direct access to the Field1 & Field2 inside the `fold`, but this would make the `subField` too long and cumbersome to use.

**Comment by nyurik** [comment]
@troy012 could you attach your data and the vega code you use?

**Comment by lyeesim988** [comment]
@nyurik  Hello, how to flatten the aggregation output in the nested bucket? Below is my ES code:
``` GET index_main/_search
{
  "size": 0, 
  "query": {
    "bool": {
      "filter": [
        { "match": { "ID": "3yG" } }
      ]
    }
  }, 
  "aggs": {
    "day": {
      "date_histogram": {
        "field": "Screen_Date",
        "interval": "day"
      },
      "aggs": {
        "hour": {
          "date_histogram": {
            "field": "Screen_Date",
            "interval": "hour"
          },
          "aggs": {
            "sum_point": {
              "sum": {
                "field": "totalpoint"
              }
              }, 
              "sort_data": {
          "bucket_sort": {
            "sort":[
                { "sum_point": { "order": "desc" }}
              ],
            "size": 1
          }
        }
              }
            }
          }
        }
      }
    }
```
My output:

```
"aggregations": {
    "day": {
      "buckets": [
        {
          "key_as_string": "2018-04-01T00:00:00.000Z",
          "key": 1523059200000,
          "doc_count": 32,
          "hour": {
            "buckets": [
              {
                "key_as_string": "2018-04-01T16:00:00.000Z",
                "key": 1523116800000,
                "doc_count": 4,
                "sumcounter": {
                  "value": 365
                }
              }
            ]
          }
        },
        {
          "key_as_string": "2018-04-02T00:00:00.000Z",
          "key": 1523145600000,
          "doc_count": 96,
          "hour": {
            "buckets": [
              {
                "key_as_string": "2018-04-02T02:00:00.000Z",
                "key": 1523152800000,
                "doc_count": 4,
                "sumcounter": {
                  "value": 612
                }
              }
            ]
          }
        },
        {
          "key_as_string": "2018-04-03T00:00:00.000Z",
          "key": 1523232000000,
          "doc_count": 96,
          "hour": {
            "buckets": [
              {
                "key_as_string": "2018-04-03T14:00:00.000Z",
                "key": 1523282400000,
                "doc_count": 4,
                "sum_point": {
                  "value": 230
                }
              }
            ]
          }
        },
        {
          "key_as_string": "2018-04-04T00:00:00.000Z",
          "key": 1523318400000,
          "doc_count": 64,
          "hour": {
            "buckets": [
              {
                "key_as_string": "2018-04-04T13:00:00.000Z",
                "key": 1523365200000,
                "doc_count": 4,
                "sum_point": {
                  "value": 890
                }
              }
            ]
          }
        }
      ]
    }
```

I need the "key_as_string": "2018-04-04T13:00:00.000Z" and "sum_point" value to create bar using Vega.
Thanks.

**Comment by bijipadhy** [comment]
Hello,

I am also able to get it to parse two aggregations - has anyone been able to parse more than 2? Please reply. It's urgent.

**Comment by nyurik** [comment]
@bijipadhy could you attach an example graph that is not working?

**Comment by bijipadhy** [comment]
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",

  "signals": [
    {
      "name": "labels", "value": true,
      "bind": {"input": "checkbox"}
    },
    {
      "name": "aspectRatio", "value": 1.6,
      "bind": {"input": "range", "min": 0.2, "max": 5, "step": 0.1}
    },

    {
      "name": "layout", "value": "tidy",
       "bind": {"input": "radio", "options": ["tidy", "cluster"]}
    },
    {
      "name": "links", "value": "diagonal",
       "bind": {"input": "select","options": ["line", "curve", "diagonal", "orthogonal"]
      }
    }
  ],

  "data": [
    {
      "name": "tree",
      "url": {
      
      index: automataactivity
      body : {
          "aggs": {
            "grp1": {
              "terms": {
                "field": "party_name.keyword"
              },
              "aggs": {
                "grp2": {
                  "terms": {
                          "field":  "acct_type_name.keyword"
                        },
                    "aggs": {
                      "grp2": {
                        "terms": {
                          "field":  "acct_type_name.keyword"
                        }
                      }
                    }  
                }
              }
            }
          }
        }
      },
      "format": {
        "property": "aggregations.grp1.buckets"
      },

      "transform": [
        {
          "type": "flatten",
          "fields": ["grp2.buckets"],
          "as": ["k"]
        },
        {
          "type": "nest"
          // "key": "key"
          "keys":["k.key","k.doc_count","k.key"],
          "generate": true
          
        },

        {
          "type": "tree",
          "method": {"signal": "layout"},
          "field": "key",
          "ratio": {"signal": "aspectRatio"},
          "size": [{"signal": "width"}, {"signal": "height"}],
          "as": ["y", "x", "depth", "children"]
        }
      ]
    },
    {
      "name": "links",
      "source": "tree",
      "transform": [{"type": "treelinks",orient":"vertical","shape": {"signal": "links"}}, {"type": "linkpath","shape": {"signal": "links"}}]
    }
  ],
  "scales": [
    {"name": "color", "type": "ordinal", "range": {"scheme": "magma"},"domain": {"data": "tree", "field": "depth"},
      "zero": true}
  ],
  "marks": [
    {
      "type": "path",
      "from": {"data": "links"},
      "encode": {
        "enter": {"stroke": {"value": "#ccc"}},
        "update": {"path": {"field": "path"}}
      }
    },
    {
      "type": "symbol",
      "from": {"data": "tree"},
      "encode": {
        "enter": {
          // "fill": {"scale": "color", "field": "depth"},
          "stroke": {"value": "white"},
          "size": {"value": 400}
        },
    
    "update": {"x": {"field": "x"}, "y": {"field": "y"},"fill": {"scale": "color", "field": "depth"}}
      }
    },
    {
      "type": "text",
      "from": {"data": "tree"},
      "encode": {
        "enter": {
          "text": {"field": "key"},
          //"text": {"field": "doc_count"},
          "fontSize": {"value": 10},
          "baseline": {"value": "top"}
          
    },

        "update": {"x": {"field": "x"}, "y": {"field": "y"},"dx": {"signal": "datum.children ? -7 : 7"},
          "align": {"signal": "datum.children ? 'right' : 'left'"},
          "opacity": {"signal": "labels ? 1 : 0"}}
      }
    }
  ]
}

**Comment by bijipadhy** [comment]
Hi Yuri,

Thanks for your help however my issues seems to be resolved. There was some data issue. Now I have a new problem. Looking for your help in that topic.

I created a tree, but the tree link line shows up even after the last leaf node. Could you please help me how to remove that one. I want the tree to end at the count. don't want the trailing lines after the numbers.


![image](https://user-images.githubusercontent.com/46340838/50675043-81391100-1011-11e9-9fb2-40c7c97928c4.png)

**Comment by nyurik** [comment]
@bijipadhy same problem - see my previous comment. I cannot help you unless you have something I can try.

**Comment by bijipadhy** [comment]
Hi.. Thanks for your interest but I can't share the data due to confidentiality. Could you please help me in another topic?

I want to use scripted fields in the vega tree. How can I do that. I know we can't use the kibana created scripted fields. I have gone through the following article: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-script-fields.html


More precisely, I have few jobs running. They have some status like Running, pending, exception, completed. I want to take a count of them. How can I write the logic to get their count in the tree node?

**Comment by nyurik** [comment]
@bijipadhy you don't have to share the real data - as long as the data looks close enough to the structure you have, and has a few values that kinda resemble what you are trying to do, it will be good enough - as long as I can plot it as something useful.  I cannot help you with scripted fields - I don't know much about them. Also, please refrain from using this ticket as a general ES support - you should post all of these questions on https://discuss.elastic.co - so that the entire Elastic community could help you.

**Comment by biji-padhy** [comment]
Hi,
Here is my code and the sample data file attached. Please help me to get rid of the last set of leaf nodes where no data comes.

`{
  $schema: https://vega.github.io/schema/vega/v3.0.json
  signals: [
    {
      name: labels
      value: true
      bind: {input: "checkbox"}
    }
    {
      name: aspectRatio
      value: 1.6
      bind: {input: "range", min: 0.2, max: 5, step: 0.1}
    }
    {
      name: layout
      value: tidy
      bind: {
        input: radio
        options: ["tidy", "cluster"]
      }
    }
    {
      name: links
      value: diagonal
      bind: {
        input: select
        options: ["line", "curve", "diagonal", "orthogonal"]
      }
    }
  ],
  data: [
    {
      name: tree
      url: {
        %context%: true
      // Filter the time picker (upper right corner) with this field
        %timefield%: last_update_time
        index: automataactivity
        body: {
          "aggs": {
            "business": {
              "composite": {
                  "sources" : [
                    { "competency_name": { "terms" : { "field": "busn_competency_name.keyword" } } 
                    }, 
                    { "component_name": { "terms" : { "field": "busn_component_name.keyword" } } 
                    }, 
                    { "busn_srvc_name": { "terms" : { "field": "busn_srvc_name.keyword" } } 
                    }
                  ]
              },
                "aggs": {
                  "Comp" : {
                    "filter" : { "term": { "automata_status.keyword": "Completed" } }
                    },
                    "Exp" : {
                    "filter" : { "term": { "automata_status.keyword": "Exception" } }
                    },
                "percentage": {
                "bucket_script": {
                  "buckets_path": {
                    "excp": "Exp._count",
                    "comp": "Comp._count"
                  },
                  "script": "Math.round((params.excp/params.comp) * 100)"
                }
              }
                  }
            }
        },
        }
      }
    // format: {property: "aggregations.mycount.buckets"}
      transform: [
        {
          type: flatten
          fields: ["aggregations.business.buckets"],
          as: ["a"]
        }
        {
          type: nest
          keys: ["a.key.competency_name", "a.key.component_name","a.key.busn_srvc_name", "a.percentage.value"],
          generate: true
        },
        {
          "type": "tree",
          "method": {"signal": "layout"},
          "size": [{"signal": "height - 100"}, {"signal": "width - 100"}],
          "as": ["y", "x", "depth", "children"]
        }
      ]
    }
    {
      "name": "links",
      "source": "tree",
      "transform": [
        { "type": "treelinks" },
        {
          "type": "linkpath",
          "orient": "horizontal",
          "shape": {"signal": "links"}
        }
      ]
    }
  ],
  scales: [
    {
      "name": "color",
      "type": "sequential",
      "range": {"scheme": "blues"},
      "domain": {"data": "tree", "field": "depth"},
      "zero": true
    }
  ],
  marks: [
  {
      "type": "path",
      "from": {"data": "links"},
      "encode": {
        "update": {
          "path": {"field": "path"},
          "stroke": {"value": "#105bdd"}
        }
      }
    },
    {
      "type": "symbol",
      "from": {"data": "tree"},
      "encode": {
        "enter": {
          "size": {"value": 300},
          "stroke": {"value": "black"}
        },
        update: {
          "x": {"field": "x"},
          "y": {"field": "y"},
          "fill": {"scale": "color", "field": "depth"}
        }
      }
    }
    {
      "type": "text",
      "from": {"data": "tree"},
      "encode": {
        "enter": {
          "text": {"field": "key"},
          "fontSize": {"value": 12},
          "baseline": {"value": "top"},
          "fill": {"value": "#C0C0C0"}
        }
        update: {
          "x": {"field": "x"},
          "y": {"field": "y"},
          "dx": {"signal": "datum.children ? -7 : 7"},
          "align": {"signal": "datum.children ? 'right' : 'left'"},
          "opacity": {"signal": "labels ? 1 : 0"}
        }
      }
    }
  ]
}
[sample.txt](https://github.com/vega/vega/files/2855588/sample.txt)

`
