### ISSUE TITLE
format.property doesn`t work with derived data sources

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1157]
Just like [arc-diagram](https://vega.github.io/editor/#/examples/vega/arc-diagram), in some cases multiple datasets are combined into one data source:

```js
{
  data1: [ {...}, {...}, ... ],
  data2: [ {...}, {...}, ... ],
}
```
The [data's format](https://vega.github.io/vega/docs/data/#format) has a `property` parameter for json data sources, which solves it if a single data subset is needed.  Yet, in some cases like the arc diagram above, the graph needs to access multiple subsets of the same data. The arc diagram solves it by declaring two identical data sources. This may be fine in some cases (browser handles caching), but is problematic in data injection and custom loader scenarios.

Please enable `format: {property: "..."}` for data objects with the `source` parameter, simply treating them as a `type: "json"`. With this change, arc-diagram example would have 3 instead of 2 data declarations:

```js
data: [
  { name: "rawData", url: "..." },
  { name: "data1", source: "rawData", format: {property: "subset1" } },
  { name: "data2", source: "rawData", format: {property: "subset2" } }
]
```

**Comment by jheer** [comment]
Thanks for the suggestion, but this is not one we plan to implement. A data source in Vega is realized as a collection of tuples, whereas input JSON is not. That is why it makes sense to dereference a JSON property for input data source parsing, but not in a derived data source.

I assume the motivating issue here is the redundant loading of data? If so, a better strategy for us may be to perform an internal optimization that recognizes redundant data loading requests and caches accordingly.

**Comment by nyurik** [comment]
@jheer this is not the reason. In Elasticsearch, and later in Wikipedia, I use a complex object for the URL, instead of a string. The object describes all aspects of a query. Take a look at [this blog post](https://nyurik.github.io/Vega-Trends-Graph-for-Kibana/) (scroll down), the "url" to is a very elaborate object, and it could be much bigger. As part of that result, the graph could get a very complex tree-like result.  Without the `source` support, I cannot access multiple sub-trees in it to use them for different visualization components.
