### ISSUE TITLE
3.1.0 release needs to update `vega-view-scenegraph` in deps

### ISSUE THREAD

**Issue by ericsoco** [vega/vega#1167]
When I build my project with `vega@3.1.0`, I get the following (Webpack) build error:

```
[WDS] Warnings while compiling.
../packages/chartbuilder/~/vega-view-transforms/src/Bound.js
"export 'boundClip' was not found in 'vega-scenegraph'
```

This is due to a mismatch between `vega-view-scenegraph` dependencies:

`vega@3.0.8:`

```
$ npm ls vega-scenegraph
└─┬ vega@3.0.8
  ├─┬ vega-parser@2.3.2
  │ └── vega-scenegraph@2.0.4  deduped
  ├── vega-scenegraph@2.0.4 
  ├─┬ vega-view@2.0.4
  │ └── vega-scenegraph@2.0.4  deduped
  └─┬ vega-view-transforms@1.1.1
    └── vega-scenegraph@2.0.4  deduped
```

`vega@3.1.0:`

```
$ npm ls vega-scenegraph
└─┬ vega@3.1.0
  ├─┬ vega-parser@2.5.1
  │ └── vega-scenegraph@2.0.4 
  ├── vega-scenegraph@2.3.1 <-- diverges from downstream dep versions
  ├─┬ vega-view@2.2.0
  │ ├─┬ vega-parser@2.3.2
  │ │ └── vega-scenegraph@2.0.4  deduped
  │ └── vega-scenegraph@2.0.4  deduped
  └─┬ vega-view-transforms@1.2.0
    └── vega-scenegraph@2.0.4  deduped
```

**Comment by jheer** [comment]
I'm not sure of the precise issue as I don't commonly use Webpack. However, the Vega repo has a `yarn.lock` with the most recent version of vega-scenegraph (2.3.1). The other modules (parser, view, view-transforms) include vega-scenegraph in their package.json dependencies such that they will pull the most recent version so long as the the major release number remains 2.

Is it possible you have stale `node_modules` folders for the other Vega modules?

**Comment by ericsoco** [comment]
Oops, sorry -- apparently `yarn` didn't clean out old deps correctly, or Webpack had a stale cache...or something. Ye olde `rm -rf node_modules` fixed the issue. Sorry for the noise!
