### ISSUE TITLE
Seeming invalidities in "valid" test specs

### ISSUE THREAD

**Issue by pelotom** [vega/vega#1169]
In adapting the valid test specs from `vega` to `vega-typings` I came across a couple of specs that seem to contain invalidities:

- I can't find any documentation of a `name` property on the top level spec:
https://github.com/vega/vega/blob/0cd5b6b5350c6f91a5cf8be79ad204fea23ff34a/test/specs-valid/wordcloud.vg.json#L3
- The `title` property here seems to have been accidentally embedded inside the `labels` object:
https://github.com/vega/vega/blob/0cd5b6b5350c6f91a5cf8be79ad204fea23ff34a/test/specs-valid/movies-sort.vg.json#L111-L119

**Comment by jheer** [comment]
Thanks @pelotom! Fixed the related specs.
