### ISSUE TITLE
Specify target in href links

### ISSUE THREAD

**Issue by jakevdp** [vega/vega#1171]
It would be useful to be able to specify the ``target`` in ``href`` links within vega plots. One example is plots within the Jupyter notebook, for which a normal ``<a href="">`` changes the window and can lead to a loss of state.

It would be nice to let this percolate up to Vega-Lite as well :smile:

**Comment by domoritz** [comment]
As a workaround, for now, you can add some code to the page to show a warning before state is lost. https://stackoverflow.com/a/1119324/214950

**Comment by jheer** [comment]
Note that if you shift-click you _should_ get the link to open in a new tab. At least, that works in a normal web deployment of Vega.

**Comment by jheer** [comment]
TODOs to service this request:
1. Update vega-view to ensure shared view.loader is passed to scenegraph handler instance.
2. Update vega-loader to include a 'target' option to set global href link target.

**Comment by jheer** [comment]
Added via updates to vega-view and vega-loader. Once the next Vega version is released, the following will set the default link target within the URL sanitization and loading system:

```js
new vega.View(runtimeSpec, {
  loader: vega.loader({target: '_blank'})
});
```

Perhaps vega-embed should also be updated to expose `target` as a parameter?

**Comment by ted-dunstone** [comment]
Would it be possible to provide a simple example showing how this could be achieved (updating the target) in a jupterlab notebook?

**Comment by domoritz** [comment]
I don't have the time to make a full example right now but I think you can just pass a dictionary with `{'target': '_blank'}` to the Vega-Embed `loader` option property.
