### ISSUE TITLE
Cannot format a derived data source

### ISSUE THREAD

**Issue by pelotom** [vega/vega#1174]
Starting from [this example](https://vega.github.io/editor/#/examples/vega/timelines): ![before](https://user-images.githubusercontent.com/128019/36914800-572bbe36-1e03-11e8-8a4b-b8107eb53eff.png)

It seems like I should be able to take this data declaration:

```json,
    {
      "name": "events",
      "format": {"type":"json", "parse":{"when":"date"}},
      "values": [
        { "name":"Decl. of Independence", "when":"July 4, 1776" },
        { "name":"U.S. Constitution",     "when":"3/4/1789" },
        { "name":"Louisiana Purchase",    "when":"April 30, 1803" },
        { "name":"Monroe Doctrine",       "when":"Dec 2, 1823" }
      ]
    }
```

and split it up, deferring the formatting to a derived dataset:

```json
    {
      "name": "events_source",
      "values": [
        { "name":"Decl. of Independence", "when":"July 4, 1776" },
        { "name":"U.S. Constitution",     "when":"3/4/1789" },
        { "name":"Louisiana Purchase",    "when":"April 30, 1803" },
        { "name":"Monroe Doctrine",       "when":"Dec 2, 1823" }
      ]
    },
    {
      "name": "events",
      "source": "events_source",
      "format": {"parse":{"when":"date"}}
    }
```

and this should be semantically equivalent. However the formatting doesn't seem to be working:

![after](https://user-images.githubusercontent.com/128019/36914805-5e0a4858-1e03-11e8-8df7-ded32bb6488c.png)

For context, I'm using vega programmatically and allowing users to provide their own simplified specs, which are then augmented. Their spec will be augmented with a single root data source which they don't configure, and to which their subsequent data declarations will be appended. So they need to be able to make derived data sets off the raw one and do formatting as they see fit.

**Comment by jheer** [comment]
Yes, the `format` directive is only applicable to input data, it does not apply to a derived data source. If you want to parse specific fields in downstream data, you can still do so using formula transforms.

**Comment by pelotom** [comment]
Ok, the formula transform approach makes sense. Maybe the schema should reflect that `source` and `format` can't be used together?

**Comment by domoritz** [comment]
@pelotom Just FYI, Vega-Lite automatically creates the formula transforms when parsing derived data.

**Comment by jheer** [comment]
@pelotom Agreed! The schema should be fixed. Will do.
