### ISSUE TITLE
Config for axisLinear?

### ISSUE THREAD

**Issue by pelotom** [vega/vega#1175]
The [documentation](https://vega.github.io/vega/docs/config/#axes) on axis configs says,

>Additional property blocks can target more specific axis types based on the orientation ("axisX", "axisY", "axisLeft", "axisTop", etc.) or band scale type ("axisBand"). For example, properties defined under the "axisBand" property will only apply to axes visualizing "band" scales.

Based on this I thought I could enable gridlines for axes attached to linear scales like so:

```json
"axisLinear": {
  "grid": true,
}
```

but it seems to have no effect.

**Comment by jheer** [comment]
This works for the axisBand type only, not other types. We can further clarify the documentation here.

**Comment by pelotom** [comment]
Thanks for the clarification!
