### ISSUE TITLE
Ability to flip axes purely via signals

### ISSUE THREAD

**Issue by pelotom** [vega/vega#1176]
I was attempting to implement a checkbox bound to a signal which would effectively flip the axes of a chart, but it doesn't seem possible without at least allowing `scale.type` and `axis.orient` to be signals. Would that be a feasible change?

**Comment by jheer** [comment]
Unfortunately this would be a difficult change to make. The axis and legend generation code in the vega-parser use this information to determine how axes/legends should be constructed. While it _might_ be possible to add a layer of indirection here that pushes decisions to the runtime, if so it would be a substantial effort and is not on our roadmap. In general, these is a tension between how malleable Vega specifications should be versus what should be the responsibility of any spec-generating software. For the time being, this functionality falls in the latter category.

While perhaps not fully supportive of what you propose, you can change the _data field_ backing a scale to swap variables in response to signals, as in https://vega.github.io/vega/examples/scatter-plot-null-values/

**Comment by pelotom** [comment]
>While perhaps not fully supportive of what you propose, you can change the data field backing a scale to swap variables in response to signals

Yeah, which only works as long as the scales and axes are the same for x and y. Unfortunately I need something a little more powerful. Thanks in any case for the response!

**Comment by HalukaMB** [comment]
So, but what do I have to do in case, I have one time-axis and a ordinal-axis and I want to be able to flip them. Because the describe workaround by @jheer only works when both axis are of the same type, right?
