### ISSUE TITLE
How to add tooltips to wordclouds

### ISSUE THREAD

**Issue by mhlr** [vega/vega#1178]
I would like to associate tooltips with words in a wordcloud.
It looks like vega already has both tooltips and word clouds.
How does one combine them?
For example how would one add tooltips to https://vega.github.io/vega/examples/word-cloud/
to make the counts appear ave each word?

**Comment by jheer** [comment]
One example is already available at the online Vega editor, which uses the vega-tooltip plugin to provide the tooltips: https://vega.github.io/editor/#/examples/vega/word-cloud

Alternatively, you can add a `tooltip` encoding channel for the wordcloud text marks to use Vega's built-in tooltip support, like so:

```
    {
      "type": "text",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "text": {"field": "text"},
          "align": {"value": "center"},
          "baseline": {"value": "alphabetic"},
          "fill": {"scale": "color", "field": "text"},
          "tooltip": {"signal": "'Count: ' + datum.count"}
        },
       ....
```

You can find documentation of the tooltip encoding channel under general mark properties (scroll down): https://vega.github.io/vega/docs/marks/text/
