### ISSUE TITLE
bug with signal update?

### ISSUE THREAD

**Issue by Casyfill** [vega/vega#1180]
I am working on an interactive bar chart plot, and what I want to is to color bars depending on their sign - basycally green for positive and red for negative (although in my case both colors are blue).

It seems that everything works fine, except that after a few switching radio buttons you'll notice wrong 
coloring (especially for `Inventory` or `Median Days on Market`). I still can't get if this is a vega bug or something wrong with the data. Here are the specs.

https://gist.github.com/Casyfill/104f2ae4cd7aea57372611414c97f923

**Comment by jheer** [comment]
Hi @Casyfill! Two problems in your spec:

1. The `fill` color must be in the update block, not the enter block, to update in response to signals.
2. You want number coercion to ensure your values are `0` and `1` (as expected by your color scale), not `true` or `false` (as generated by comparison operators). Here's a fix for that:

```js
"fill": {"scale":"c", "signal":"+(datum[column] > 0)"}
```

Hope that helps!

**Comment by Casyfill** [comment]
thanks a lot!
