### ISSUE TITLE
Allow Donut Chart negative angles for startAngle and endAngle

### ISSUE THREAD

**Issue by lobo-tuerto** [vega/vega#1183]
The way the current specification is doesn't allow for a variety of configurations ---for example a guage like shape is basically impossible to get, you can get an _inverted_ guage-like shape though.

Solution would be to allow for an angle range of -6.29 to 6.29, instead of only 0 to 6.29.

**Comment by jheer** [comment]
Vega imposes no limits on the angle range. You can make a gauge shape if you like. Perhaps you are referring to the slider ranges of some of the examples pie/donut charts? If so, that is simply a limitation of how the signal bindings in those examples are configured, not the underlying language.

The example included in the [arc mark documentation](https://vega.github.io/vega/docs/marks/arc/) allows you to specify both negative and positive angle values.

**Comment by lobo-tuerto** [comment]
Gotcha, thanks for the reply!

**Comment by lobo-tuerto** [comment]
Got a bad impression when looking at this example: https://vega.github.io/vega/examples/donut-chart/

I thought the signals definitions where some type of set-in-stone specification for a particular kind of chart.
