### ISSUE TITLE
Function signal?

### ISSUE THREAD

**Issue by pelotom** [vega/vega#1184]
I'm using Vega programmatically, and need to be able to embed a new top-level function which is usable by all specs. I figured I should be able to just define a signal whose value is a function:

```js
const spec = {
  // ...
  signals: [
    {
      name: 'myFunction',
      value() {
        // ...
      }
    },
    // ...
  ],
  // ...
};
```

However it doesn't work when I try to use it in an expression, throwing `Unrecognized function: myFunction`. It's interesting because the signal `myFunction` is visible, it's just attempting to invoke it which fails.

This may be a duplicate of #385, but I'm not trying to define a new transform...

**Comment by nyurik** [comment]
@pelotom See the new discussion in #385 - you can create global functions using `vega.expressionFunction` call.

**Comment by pelotom** [comment]
Awesome, thanks for the heads up!
