### ISSUE TITLE
Add preferred citation to readme and/or docs?

### ISSUE THREAD

**Issue by dhuppenkothen** [vega/vega#1185]
Is there a preferred way of citing Vega in a scientific journal article or grant proposal? I would like to make sure that the project receives appropriate credit when I use Vega, but I couldn't find the preferred reference to cite either in the documentation or in the readme (I'm assuming there is one).

I found some publications [here](https://vega.github.io/vega/about/research/), but it wasn't clear to me which one I should cite.

**Comment by arvind** [comment]
Hi Daniela,

Thanks for the question! Although our architecture has evolved and matured since, I think the “Reactive Vega” paper is the most appropriate to cite if you’re using Vega in your work (bibtex here: http://idl.cs.washington.edu/bibtex/reactive-vega-architecture).
