### ISSUE TITLE
Feature request: Ordinal scale - Configurable automatic domain extension 

### ISSUE THREAD

**Issue by banutr** [vega/vega#1189]
This is in relation to the fix provided for https://github.com/vega/vega/issues/1166 in version 3.2.0

Can there be a config handle in the spec to control the domain extension feature rather than disabling it if explicit domain is mentioned. It will be nicer if disabling is the default but still an option is available for enabling extension.

**Comment by jheer** [comment]
Feature request received. Thanks! Will investigate for the next minor release.

**Comment by knomdlo** [comment]
Any chance this can be done in next minor release.

**Comment by jheer** [comment]
Yes, this has been released in vega-encode 3.1.0, and will be included in the upcoming v4.0.0 release.
