### ISSUE TITLE
Feature request: Change vega versions in editor

### ISSUE THREAD

**Issue by banutr** [vega/vega#1191]
Hi,
Would it be possible to have a drop down to change vega lib versions in the online editor.
Currently the editor (I assume) runs the latest version.

With this, it would be easier to compare spec's visualization across versions

**Comment by domoritz** [comment]
That would be a neat feature. It's a bit tricky to implement and I haven't found a convincing reason to implement it yet. What is your use case?

**Comment by banutr** [comment]
A case that I faced: 
https://groups.google.com/forum/#!topic/vega-js/V0Mt5t2BwmY

Yes release notes do point out the changes but I would prefer to also try out the new version before upgrading it in my project.

**Comment by domoritz** [comment]
For that, I recommend forking our block from https://bl.ocks.org/domoritz/cd636b15fa0e187b51b73fc60b4d3014 and fixing the version number when loading the library from jsdelivr. I don't think it is worth the additional complexity in the editor.
