### ISSUE TITLE
Pivot transform not included in 3.2.0 or 3.2.1 releases

### ISSUE THREAD

**Issue by jlasserre** [vega/vega#1192]
It seems to me that vega-transforms V1.3.0 should be included in package.json for V3.2.0 but that doesn't seem to be the case.

Am I missing something ?

**Comment by jlasserre** [comment]
More info...
In Vega Editor, the schema seems to suggest that the pivot transform exists...
![image](https://user-images.githubusercontent.com/11434804/37401687-4c3dd896-275f-11e8-9251-cc92613a8af8.png)

but an error message is displayed when trying to interpret it:
![image](https://user-images.githubusercontent.com/11434804/37401725-61b5ef92-275f-11e8-8c99-1d4bc98115cc.png)


NOTE: for some odd reason, I **was** able to use the pivot transform for a few hours two days ago. I left to watch TV and when I came back a couple hours later it wasn't working anymore. I have no logical explanation for that behavior but I still thought I should share ;-) That was on Monday March 12th. (in the late evening, and since then, I have not been able to use the Pivot transform in Vega Editor).

**Comment by jheer** [comment]
Thanks! I can confirm that the `pivot` transform *is* included in these releases. For example, you can go to https://vega.github.io/vega/, open the JavaScript console, and enter `vega.transforms.pivot` to confirm the presence of the transform.

So, this appears to be a bug in the Vega editor. I'm guessing stale versions of submodules (i.e., vega-transforms) were accidentally bundled up in the current deployment.

As a result, I am closing this issue but will open a new bug report on the Vega editor repo.

**Comment by MD65** [comment]
Hello ! 
I can confirm that it doesn't work yet. I'am working on KIBANA platform.

**Comment by MD65** [comment]
![bug_pivot](https://user-images.githubusercontent.com/11718182/40653749-5fba000c-633c-11e8-90cd-1e7d624a53a3.PNG)

**Comment by MD65** [comment]
Thanks ! @jheer
