### ISSUE TITLE
Please add support for Angular 5 / Typescript

### ISSUE THREAD

**Issue by king612** [vega/vega#1194]
Just getting started with Vega, but there seems to be a dearth of integration support for Angular 4/5 or Typescript in general.  Any plans to support, encourage, or add this (similar to the Python integration)?  Lotta Angular developers out here that'd love to have a node module to surface Vega natively in our Typescript.

**Comment by jheer** [comment]
Hi, thanks for the comments. You might be interested in the Vega TypeScript bindings at:
https://github.com/vega/vega-typings

These are now exported by the Vega library (https://github.com/vega/vega/blob/master/index.d.ts).

However, it is beyond the scope of the core Vega library to provide "plug-and-play" components for specific web application frameworks (though others have built such components for React, etc). We are happy to consider additional repos in the Vega organization to assist such libraries should community members want to propose and develop them!

**Comment by domoritz** [comment]
@kristw created https://github.com/kristw/react-vega and we might have a GSoC student improving the react components this summer.
