### ISSUE TITLE
X-axes time breaks

### ISSUE THREAD

**Issue by onehost1** [vega/vega#1199]
![innograf_2018-03-16_12-14-11](https://user-images.githubusercontent.com/7464668/37746206-cf3a458e-2dc4-11e8-81ad-aa0a834fa213.png)

We have got an old project that I'm looking to upgrade to Vega Js. One of the features the old product had was to join graphs when there is change of time, either positive like in this graph or negative like daylight saving. Like in attached image. If time changes, it makes a yellow line with detail about the change.

I know this would be possible (to implement something similar by extending VegaJs) but if I can avoid reinventing the wheel that would be ideal...Do we have something similar (yellow line in the attachment) in VEGA?

I could even add a special flag with change of time the break happened, like power shutdown etc and duration of that.

I appreciate the help!

**Comment by jheer** [comment]
A direct way to do this is:
1. Add a new data source that explicitly includes the dates/timestamps for the desired breaks.
2. Include a `rule` mark to visualize those breaks as lines.

Alternatively, if your input data has a special flag included, you could create a derived data set that filters out objects that do not have a flag set, and visualizes the remaining objects using a `rule` mark.

The following example shows a timeline with labeled breaks:
- https://vega.github.io/vega/examples/timelines/

**Comment by jheer** [comment]
For "fun", here is a spec that calculates daylight saving time breaks by generating records for all days within a range and checking to see which days are longer or shorter than 24 hours. Results may vary depending on your local time zone...

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "width": 400,
  "height": 200,
  "padding": 5,

  "signals": [
    {
      "name": "oneday",
      "update": "1000 * 60 * 60 * 24"
    }
  ],

  "data": [
    {
      "name": "dates",
      "values": "date\n1/1/2012\n1/1/2018",
      "format": {"type": "csv", "parse": {"date":"date"}},
      "transform": [
        {
          "type": "extent",
          "field": "date",
          "signal": "extent"
        } 
      ]
    },
    {
      "name": "days",
      "transform": [
        {
          "type": "sequence",
          "start": 1,
          "stop": {"signal": "ceil((extent[1] - extent[0]) / oneday) + 1"}
        },
        {
          "type": "formula",
          "as": "date",
          "expr": "datetime(year(extent[0]), month(extent[0]), datum.data)"
        }
      ]
    },
    {
      "name": "fallback",
      "source": "days",
      "transform": [
        {
          "type": "filter",
          "expr": "(datetime(year(extent[0]), month(extent[0]), 1 + datum.data) - datum.date) > oneday"
        }        
      ]
    },
    {
      "name": "springforward",
      "source": "days",
      "transform": [
        {
          "type": "filter",
          "expr": "(datetime(year(extent[0]), month(extent[0]), 1 + datum.data) - datum.date) < oneday"
        }
      ]
    }
  ],

  "scales": [
    {
      "name": "time",
      "type": "time",
      "domain": {"data": "dates", "field": "date"},
      "range": "width",
      "nice": "day"
    }
  ],

  "axes": [
    {
      "scale": "time",
      "orient": "bottom"
    }
  ],

  "marks": [
    {
      "type": "rule",
      "from": {"data": "fallback"},
      "encode": {
        "enter": {
          "x": {"scale": "time", "field": "date"},
          "y": {"signal": "height"},
          "y2": {"value": 0},
          "stroke": {"value": "sienna"},
          "strokeDash": {"value": [5,2]}
        } 
      }
    },
    {
      "type": "rule",
      "from": {"data": "springforward"},
      "encode": {
        "enter": {
          "x": {"scale": "time", "field": "date"},
          "y": {"signal": "height"},
          "y2": {"value": 0},
          "stroke": {"value": "forestgreen"},
          "strokeDash": {"value": [5,2]}
        } 
      }
    }
  ] 
}
```

**Comment by onehost1** [comment]
Thanks Jeffrey for your kind response. I will take these inputs as the basis of my implementation.
