### ISSUE TITLE
Access to original legend encoding value

### ISSUE THREAD

**Issue by alexchantastic** [vega/vega#1203]
I've looked through the docs and previous issues and can't seem to find if this is possible or not, but is it possible to access the original legend coding value?

For example:

```js
"legends": [
  {
    "stroke": "color",
    "encode": {
      "symbols": {
        "interactive": true,
        "update": {
          "fontSize": {"value": 12},
          "fill": {"value": "transparent"}
        },
        "hover": {
          // I want to add something like this which would give me access to the 
          // original color value used for the stroke encoding
          "fill": {"scale": "color"}
        }
      }
    }
  }
]
```

**Comment by jheer** [comment]
Yes! From the [legend documentation for custom encodings](https://vega.github.io/vega/docs/legends/#custom):

> Each legend symbol and label instance is backed by a data object with the following fields, which may be accessed as part of a custom visual encoding rule:
>
> - `index` - an integer index
> - `label` - the string label
> - `value` - the data value
> - `size` - the symbol size (for symbol legends only)

In your example, you could use:

```js
      "hover": {
          // I want to add something like this which would give me access to the 
          // original color value used for the stroke encoding
          "fill": {"scale": "color", "field": "value"}
        }
```
