### ISSUE TITLE
Question: How do you zoom in the viewport to a desired position within a map?

### ISSUE THREAD

**Issue by palewire** [vega/vega#1204]
Forgive me if this is an elementary question, but I have been unable to find an example in your documentation. 

My goal is to load a broad nationwide dataset with Vega, and then zoom the view to a narrow location. For instance, your nationwide unemployment example creates this map. 

![screenshot from 2018-03-25 08-47-01](https://user-images.githubusercontent.com/9993/37876976-1a6ee6e0-3009-11e8-975f-30c68c5b763b.png)

I would like to draw that entire map, but then instruct Vega to zoom in on Southern California. The result would be something like this. (Forgive the rough example, I drafted it simply by magnifying my browser.)

![screenshot from 2018-03-25 08-48-18](https://user-images.githubusercontent.com/9993/37876998-49cc36a4-3009-11e8-9ce6-351ac4ff81b1.png)

Reading your [excellent documentation](https://vega.github.io/vega/docs/projections/) suggests this would achieved by some combination of fiddling with attributes like `fit`, `scale`, `center` and `extent`, but it's unclear to me the best route to take. 

In my most common use cases, I am mapping data in the web Mercator projection (i.e. the decimal degrees favored by Google Maps and Leaflet). Ideally, using an interface like Altair, I'd be able to submit a center or bounding box in those same units to set the default framing of my map.

Leaflet makes it a snap with [a method called `setView`](http://leafletjs.com/reference-1.3.0.html#map-setview). Zooming in on Los Angeles only requires you submit a center point and a tile zoom level.

```javascript
mymap.setView([-118.3, 33.9], 12);
```

Leaflet also offers another helpful method, [`fitBounds`](http://leafletjs.com/reference-1.3.0.html#map-fitbounds), which can set the view at the maximum possible zoom based on the submitted bounding box.

How can I achieve a similar effect in Vega? I have experimented with the settings in your helpful online editor but haven't been able to nail it. You can see one effort to set the center and extent below. 

I would appreciate any guidance you provide, and once I better understand how to solve this problem I vow to submit an example for your documentation that can help others.

```javascript
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "width": 960,
  "height": 500,
  "autosize": "none",

  "data": [
    {
      "name": "unemp",
      "url": "data/unemployment.tsv",
      "format": {"type": "tsv", "parse": "auto"}
    },
    {
      "name": "counties",
      "url": "data/us-10m.json",
      "format": {"type": "topojson", "feature": "counties"},
      "transform": [
        { "type": "lookup", "from": "unemp", "key": "id", "fields": ["id"], "values": ["rate"] },
        { "type": "filter", "expr": "datum.rate != null" }
      ]
    }
  ],

  "projections": [
    {
      "name": "projection",
      "type": "mercator",
      "center": [-118.3, 33.9],
      "extent": [
        [-119.1302490234375, 35.02099970111467],
        [-116.91650390625, 33.063924198120645]
      ]
    }
  ],

  "scales": [
    {
      "name": "color",
      "type": "quantize",
      "domain": [0, 0.15],
      "range": {"scheme": "blues-9"}
    }
  ],

  "legends": [
    {
      "fill": "color",
      "orient": "bottom-right",
      "title": "Unemployment",
      "format": "0.1%",
      "encode": {
        "symbols": {
          "update": {
            "shape": {"value": "square"},
            "stroke": {"value": "#ccc"},
            "strokeWidth": {"value": 0.2}
          }
        }
      }
    }
  ],

  "marks": [
    {
      "type": "shape",
      "from": {"data": "counties"},
      "encode": {
        "enter": { "tooltip": {"signal": "format(datum.rate, '0.1%')"}},
        "update": { "fill": {"scale": "color", "field": "rate"} },
        "hover": { "fill": {"value": "red"} }
      },
      "transform": [
        { "type": "geoshape", "projection": "projection" }
      ]
    }
  ]
}
```

**Comment by jheer** [comment]
While some details can vary slightly across projection types, the parameters you'll want to modify are `scale` (to set the zoom level) and `rotate` and/or `center` (to control where in the world you're zooming in).

These two examples are good starting points for experimentation:
- https://vega.github.io/vega/examples/world-map/ (allows exploration of all projection parameters)
- https://vega.github.io/vega/examples/zoomable-world-map/ (demonstrates how to enable interactive panning and zooming using a Mercator projection)

Underneath the hood, Vega uses D3 (in particular the [d3-geo module](https://github.com/d3/d3-geo)). As a result, any projection settings from a relevant D3 example should directly transfer to Vega as well!

While Leaflet is wonderful, the last time I checked it makes basic assumptions such as the projection type (Web Mercator) or orientation (e.g., north is up). The projection system used by Vega/D3 is more general and so enables a wider array of designs, but requires more complex settings.

You might also be interested in the `fit` parameter to Vega projections, which given GeoJSON data will set the `scale` and `translate` parameters to ensure that the provided geo data is visible (using [d3-geo's `fitExtent`](https://github.com/d3/d3-geo#projection_fitExtent)). You'll still need to make sure the rotation is appropriate, though. A simple example using `fit` is included in Vega's test suite: [map-fit.vg.json](https://github.com/vega/vega/blob/master/test/specs-valid/map-fit.vg.json). You can copy and paste that file into the online Vega editor to play with it.
