### ISSUE TITLE
Is view.change works?

### ISSUE THREAD

**Issue by Muskos** [vega/vega#1205]
May be I miss understanding. I created codepen for demonstration. In this codepen there are two method. 
`updateView` we use it at now
`changeView` this method use view.change

https://codepen.io/Muskos/pen/EEboEg

view.change change nothing. Can you help to understand this functional? Or is it bug?

**Comment by domoritz** [comment]
Does [this tutorial](https://vega.github.io/vega-lite/tutorials/streaming.html) help you?

**Comment by Muskos** [comment]
@domoritz no
My example:
`
var changeSet = vega.changeset().insert(newData);
    vegaElement.change('Table', changeSet).run();
`
Tutorial:
`
var changeSet = vega.changeset().insert(valueGenerator()).remove(function (t) { return t.x < minimumX; });
        res.view.change('table', changeSet).run();
`
I think it is similar? But in my case it doesn't work.

**Comment by jheer** [comment]
Hi @Muskos! Your variable `newData` is an object with a single key (`"Table"`). However, the changeset `insert` method expects a flat array of values, just like the second argument of `view.insert`.

Try running this instead: 
`vegaElement.changeset().insert(newData.Table)`

To make this clearer, I've updated the documentation at https://vega.github.io/vega/docs/api/view/#data

**Comment by Muskos** [comment]
@jheer Thank you for solution. It't work. But I can't understand it. 
```
vegaElement.changeset().insert(newData.).remove((item) => {
        return item.v < 80000
    })
```
I insert `newData`. (okey - this moment is wrong, but: ) Date appears in vega runtime (` vega._runtime.data.Table.values`). Next I see remove function log, but function didn't delete date. 
My be it's not a bug. But it's strange behavior.
