### ISSUE TITLE
Transform type Sample

### ISSUE THREAD

**Issue by onehost1** [vega/vega#1207]
Hi guys,

I am struggling to understand how sampling of data works.

Let me explain it. I have data where I have one or more line graphs.

I added below line:
```
"data": [
          {
            "name": "table",
            "transform": [
              { "type": "sample", "size": 5 },
            ],
            "values": [
        {"x": 0, "y": 28, "c":0}, {"x": 0, "y": 20, "c":1},
        {"x": 1, "y": 43, "c":0}, {"x": 1, "y": 35, "c":1},
        {"x": 2, "y": 81, "c":0}, {"x": 2, "y": 10, "c":1},
        {"x": 3, "y": 19, "c":0}, {"x": 3, "y": 15, "c":1},
        {"x": 4, "y": 52, "c":0}, {"x": 4, "y": 48, "c":1},
        {"x": 5, "y": 24, "c":0}, {"x": 5, "y": 28, "c":1},
        {"x": 6, "y": 87, "c":0}, {"x": 6, "y": 66, "c":1},
        {"x": 7, "y": 17, "c":0}, {"x": 7, "y": 27, "c":1},
        {"x": 8, "y": 68, "c":0}, {"x": 8, "y": 16, "c":1},
        {"x": 29, "y": 49, "c":0}, {"x": 29, "y": 25, "c":1}
      ]
          }],
```

If I increase the sample size to more that the data, it works fine. However, as soon as the data exceeds the sample size, it does funny thing... See attached...

Looks like Vega sample transform randomly samples all the points. We need to sample random values of x and get corresponding value of y to render for screen. I am pretty sure I am missing something. It can't be a bug on Vega side.

Can you guys please hold my hand on this one... 

![chrome_2018-03-28_15-23-46](https://user-images.githubusercontent.com/7464668/38010377-16c5acdc-329c-11e8-85b7-ea86667844ca.png)

**PS: Real dataset is really large with x axes having timestamps in microseconds so really large dataset...**

**Comment by onehost1** [comment]
I think I am looking at the wrong area. 

sample transform might not work in my case. I will have to make a signal and values should be arithmetically sampled on the 'marks' section?
 { "type": "sample", "size": 5 }, 

Appreciate your help. Still trying to get my head around this awesome library.

Any literature or videos that you may point to is really appreciated as well.

Cheers

**Comment by onehost1** [comment]
#577 Looks similar to what I am struggling to handle...

**Comment by jheer** [comment]
The `sample` transform performs random sampling only. If you want to perform down-sampling, you need to determine an appropriate function for summarizing a downsampled range. I'm copying the response to #577 below...

-----

The basic way to accomplish downsampling in Vega is to use an `aggregate` transform in conjunction with a `bin` transform (or similarly functioning `formula` transform) to discretize the domain. You will have to determine the appropriate bin granularity yourself (e.g., using Vega expressions). Then the aggregate can group by these bins and generate the appropriate down-sampled value(s) (average, median, min, max, ...).

To make that all a bit more concrete, here is an example. The `pixelRes` signal indicates the desired pixel granularity of downsampling (samples up to every 1 pixel, up to every 2 pixels, etc), which helps parameterize the `bin` transform. The data is then downsampled via groupby `aggregation`, with the ability to view different aggregate operations.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "width": 180,
  "height": 390,
  "padding": 10,

  "signals": [
    {
      "name": "pixelRes", "value": 1,
      "bind": {"input": "range", "min": 1, "max": 10, "step": 1}
    },
    {
      "name": "aggrOp", "value": "mean",
      "bind": {"input": "select", "options": ["mean", "median", "min", "max"]}
    }
  ],

  "data": [
    {
      "name": "sp500",
      "url": "data/sp500.csv",
      "format": {
        "type": "csv",
        "parse": {"price": "number", "date": "date"}
      },
      "transform": [
        {
          "type": "extent",
          "field": "date",
          "signal": "dateExtent"
        }
      ]
    },
    {
      "name": "downsampled",
      "source": "sp500",
      "transform": [
        {
          "type": "bin",
          "field": "date",
          "extent": {"signal": "dateExtent"},
          "step": {"signal": "pixelRes * span(dateExtent) / width"},
          "nice": false,
          "as": ["datebin0", "datebin1"]
        },
        {
          "type": "aggregate",
          "groupby": ["datebin0"],
          "ops": [{"signal": "aggrOp"}],
          "fields": ["price"],
          "as": ["price"]
        }
      ]
    }
  ],

  "scales": [
    {
      "name": "xDetail",
      "type": "time",
      "range": "width",
      "domain": {"signal": "dateExtent"},
      "nice": false
    },
    {
      "name": "yDetail",
      "type": "linear",
      "range": "height",
      "domain": {"data": "sp500", "field": "price"},
      "nice": true, "zero": false
    }
  ],

  "axes": [
    {"orient": "bottom", "scale": "xDetail", "tickCount": 3},
    {"orient": "left", "scale": "yDetail"}
  ],

  "marks": [
    {
      "type": "line",
      "from": {"data": "downsampled"},
      "sort": {"field": "datum.datebin0"},
      "encode": {
        "enter": {
          "stroke": {"value": "steelblue"},
          "strokeMiterLimit": {"value": 1}
        },
        "update": {
          "x": {"scale": "xDetail", "field": "datebin0"},
          "y": {"scale": "yDetail", "field": "price"}
        }
      }
    },
    {
      "type": "symbol",
      "from": {"data": "downsampled"},
      "encode": {
        "enter": {
          "size": {"value": 16}
        },
        "update": {
          "x": {"scale": "xDetail", "field": "datebin0"},
          "y": {"scale": "yDetail", "field": "price"},
          "fill": {"value": "steelblue"}
        },
        "hover": {
          "fill": {"value": "firebrick"}
        }
      }
    }
  ]
}
```
