### ISSUE TITLE
Provide access to top-level plot styling

### ISSUE THREAD

**Issue by hadley** [vega/vega#121]
Analogous to the group mark properties, it would be nice to be able access the plot "mark" to a add background or borders.

**Comment by arvind** [comment]
A top-level `background` property is now available, however strokes are not.

**Comment by arvind** [comment]
This is now available via a top-level [`scene` property](https://github.com/vega/vega/wiki/Visualization), introduced in [version 2.4](https://github.com/vega/vega/releases/tag/v2.4.0).
