### ISSUE TITLE
Vis is clipped when width and height are signals and autosize:fit

### ISSUE THREAD

**Issue by GCheung55** [vega/vega#1213]
Starting a new thread since #755 has been closed.  

@jheer thanks for adding `containerSize`. Using `containerSize` with `autosize:fit` causes a weird issue with axes that I’m I still investigating. I posted in the Vega slack channel, but here’s a copy/paste of the issue:

>I’m having some trouble with having a responsive visualization with width and height signals derived from `containerSize` expression. I want to have the visualization use `autosize:fit` so that the width and height are exact. I’ve put together a gist, where I’m using hardcoded values in the width and height signals because the Vega editor doesn’t allow for responsive width/height. The main issue is that the x-axis is clipped. What should I do to get the x-axis to be included within the hight of the chart? https://vega.github.io/editor/#/gist/vega/gcheung55/1794eb9447be6b16ecd5083763724f56/50cf15a6081b424057e929e4675e98505eb16aed/bar.json

>Looks like the y-axis is also pushing the bars some, so the furthest bar on the right looks cropped.

**Comment by jheer** [comment]
Fixed in v3.3.0. Thanks!
