### ISSUE TITLE
Duplicate Labels in Heatmap

### ISSUE THREAD

**Issue by shbosh** [vega/vega#1215]
I have been trying to create a heatmap with days in the x-axis but using "nice":"week" gives me duplicate labels (see attached). The spec that I used can be found below. Any help is greatly appreciated! 

{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "width": 800,
  "height": 500,
  "padding": 5,
  "config": {
    "title": {
      "fontSize": 14
    }
  },
  "title": {
    "text": "Spending Patterns",
    "anchor": "start",
    "offset": 4
  },
  "signals": [
    {
      "name": "palette",
      "value": "Viridis"
    },
    {
      "name": "reverse",
      "value": false
    }
  ],
  "data": [
    {
      "name": "temperature",
      "values": [
        {
          "date": "04/01/2018 10:00",
          "temp": 39.4
        },
        {
          "date": "04/01/2018 11:00",
          "temp": 30
        },
        {
          "date": "04/02/2018 12:00",
          "temp": 39.0
        },
        {
          "date": "04/02/2018 13:00",
          "temp": 38.9
        },
        {
          "date": "04/03/2018 13:00",
          "temp": 38.9
        }
      ],
      "format": {
        "parse": {
          "temp": "number",
          "date": "date"
        }
      },
      "transform": [
        {
          "type": "formula",
          "as": "hour",
          "expr": "hours(datum.date)"
        },
        {
          "type": "formula",
          "as": "date",
          "expr": "datetime(year(datum.date), month(datum.date), date(datum.date))"
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "time",
      "domain": {
        "data": "temperature",
        "field": "date"
      },
      "range": "width",
      "nice": "week"
    },
    {
      "name": "y",
      "type": "band",
      "domain": [
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        0
      ],
      "range": "height"
    },
    {
      "name": "color",
      "type": "sequential",
      "range": {
        "scheme": {
          "signal": "palette"
        }
      },
      "domain": {
        "data": "temperature",
        "field": "temp"
      },
      "reverse": {
        "signal": "reverse"
      },
      "zero": false,
      "nice": false
    }
  ],
  "axes": [
    {
      "orient": "bottom",
      "scale": "x",
      "domain": false,
      "title": "Day",
      "format": "%A"
    },
    {
      "orient": "left",
      "scale": "y",
      "domain": false,
      "title": "Hour",
      "encode": {
        "labels": {
          "update": {
            "text": {
              "signal": "datum.value === 0 ? 'Midnight' : datum.value === 12 ? 'Noon' : datum.value < 12 ? datum.value + ':00 am' : (datum.value - 12) + ':00 pm'"
            }
          }
        }
      }
    }
  ],
  "legends": [
    {
      "fill": "color",
      "type": "gradient",
      "title": "Total Spending ($)"
    }
  ],
  "marks": [
    {
      "type": "rect",
      "from": {
        "data": "temperature"
      },
      "encode": {
        "enter": {
          "x": {
            "scale": "x",
            "field": "date"
          },
          "width": {
            "value": 50
          },
          "y": {
            "scale": "y",
            "field": "hour"
          },
          "height": {
            "scale": "y",
            "band": 1
          }
        },
        "update": {
          "fill": {
            "scale": "color",
            "field": "temp"
          }
        }
      }
    }
  ]
}
<img width="993" alt="screen shot 2018-04-02 at 11 10 13 am" src="https://user-images.githubusercontent.com/12219448/38181626-7b1e666a-3666-11e8-8cbb-cc80be10d394.png">

**Comment by jheer** [comment]
Hi! Your x-axis label format is set to `"format": "%A"`. Try removing this line or replacing it with the desired date-time format.

**Comment by shbosh** [comment]
Hi @jheer thanks fro the quick reply! I tried removing it but I ended up with this: 
![image](https://user-images.githubusercontent.com/12219448/38205745-37cf544a-36da-11e8-9c2e-89eef348741d.png)

**Comment by shbosh** [comment]
Resolved it using  -- "nice": {"interval": "day", "step": 14}. Thanks!
