### ISSUE TITLE
Empty="all" does not count as selection for logical "and"

### ISSUE THREAD

**Issue by zanarmstrong** [vega/vega#1216]
Steps to reproduce: 

Go to this Observable: 
https://beta.observablehq.com/d/316c6133938023d1

Click on "1982". You'll see this. This is surprising. By clicking on 1982, now none of the years are selected and all the points in the scatterplot are grey. But, it looks like all the countries are selected because they're all still colored.

![qyj1e0r7bei](https://user-images.githubusercontent.com/7397271/38221990-3bdea178-3697-11e8-8564-02bc187c36fa.png)

If you then right click on "USA", "Japan" and "Europe", you'll see the following.

![nygexgf24lb](https://user-images.githubusercontent.com/7397271/38222025-6ebc622e-3697-11e8-93d5-be8671495f4d.png)

I would have expected to see the latter image in both cases. In both cases, I've selected the year "1982" and I would expect all of the countries of origin to be selected (either because I've selected them all by selecting nothing... or because I've selected them all manually by right-clicking). 

---
The two key things that seem to be happening are that: 

1 - I'm using "empty=all" 
2 - Selection is based on a logical and

Somehow the empty=all doesn't seem to count for the logical "and"

**Comment by arvind** [comment]
Hi @zanarmstrong! I'm not able to view your Observable notebook unfortunately (I get a "Sorry, we couldn’t find that page." error). If you're able to give me access to the spec (or copy and paste it into this issue), I can help you debug further.

**Comment by arvind** [comment]
Aha, I think I found it here: https://beta.observablehq.com/@zanarmstrong/vega-lite-interaction and I think I know what the problem is. A current limitation with selections is that they do not work over any aggregated fields (like your middle chart). We note this limitation on the [project transform](https://vega.github.io/vega-lite/docs/project.html#current-limitations) page but perhaps should surface sooner.

**Comment by arvind** [comment]
Actually, I may have spoken too soon. Tracking this issue as vega/vega-lite#3593.
