### ISSUE TITLE
Documentation:  Please make printable

### ISSUE THREAD

**Issue by king612** [vega/vega#1218]
With the current html layout of the docs, printing is effectively impossible.  Every page renders for printing as a single page with the scrollable portion in the center (the main content) chopped off.

The documentation is fantastic, and thank you for providing it.  But it would be even more useful if it could be printed for reading offline, for use on closed systems with no connection, etc.  I know it's harder, but it would really be awesome if the entire docs could be downloadable in a PDF.

Thank you for a great piece of work!

**Comment by domoritz** [comment]
We could include a printer friendly CSS style. This could also be reused to create PDFs. Another option would be to move the documentation over to https://www.gitbook.com/ (as they support PDf generation). We just need to figure out how to move over the content and embed examples.

**Comment by king612** [comment]
Actually, it looks like my issue was from using older browser versions.  I was able to print at home last night no problem.

More generally, I think this is a _great_ opportunity for someone to write a book.  I've seen no Vega/Lite books on the market, and the platform seems to be very popular and growing.  A good book with explanations of all the key concepts, how they interrelate, with great conceptual figures and a progressive refinement of examples would sell well I think.
