### ISSUE TITLE
How can I use Vega in a frontend-only Node application?

### ISSUE THREAD

**Issue by andrewbanchich** [vega/vega#1219]
I'm new to Vega and having an issue with using the npm module. I'm trying to use it in a Vue project without any server-side rendering, but npm says it needs "cairo" installed for some kind of SSR related stuff.

I'm not sure what the purpose of this is, though, since I just want to use it client-side. If I include the CDN script instead of trying to install from npm everything works fine, but I would prefer using npm instead. Am I misunderstanding something?

Thank you.

**Comment by domoritz** [comment]
Canvas is only an optional dependency so you can ignore the warnings. If that's not an option, check out vega-lib. It's Vega without the canvas dependency.
