### ISSUE TITLE
Provide public API to access view._origin

### ISSUE THREAD

**Issue by thegorgon** [vega/vega#1221]
If you're embedding an autosize chart and want to display other elements on the page around it, having access to the view's `_origin` property is necessary to correctly position the elements relative to the chart.

I'm currently accessing this information by directly using the `_origin` property, but it would be ideal if this was provided either through a view API function or a signal.

Is this something you've considered?

**Comment by jheer** [comment]
Sure, that should be easy to do. Will most likely include in next release, probably in 1-2 weeks.

**Comment by thegorgon** [comment]
Thanks @jheer - appreciate the quick response.

**Comment by jheer** [comment]
Added in v3.3.0!
