### ISSUE TITLE
Background fill for axes

### ISSUE THREAD

**Issue by onehost1** [vega/vega#1223]
I have line chart that allows pan-zoom functionality, bit like https://vega.github.io/editor/#/examples/vega/zoomable-scatter-plot. I note that as you pan and zoom, the chart overlays the axis and apparently there is no way to set the background to the axis so that as chart is panned-zoomed the axis is still in clear view...
![chrome_2018-04-05_12-18-36](https://user-images.githubusercontent.com/7464668/38344260-eaf22e38-38cb-11e8-9bb8-1ecd9a1fdb20.png)

**Comment by domoritz** [comment]
You can add `"clip": true` to the mark as in https://github.com/vega/vega/pull/1224.

**Comment by onehost1** [comment]
That fixes it. Thanks!
