### ISSUE TITLE
Signal bind element not found: null

### ISSUE THREAD

**Issue by king612** [vega/vega#1225]
I'm trying to get vega-lite to run inside of Angular 5.  Using a simple hello world type example for a vega/vega-lite spec, I get the following runtime error:

ERROR:  Signal bind element not found: null

The vega-embed folks said this looks like an underlying vega issue.  It occurs in the logger.

The relevant details are [here](https://github.com/vega/vega-embed/issues/64).

Any help or suggestions would be greatly appreciated.  Would really like to use vega-lite in my Angular app.  Thank you.

**Comment by jheer** [comment]
Thanks for sharing, but I can't really debug without a workable example with which to reproduce the bug. That said, the fact that this is a signal bind issue raises some possibilities to explore:

If you are using standard signal binding, Vega will try to create new HTML elements (`<input>` or `<select>` elements) within the container element given to the Vega View constructor. I don't know how opinionated Angular is about such things.

Vega also supports customization by targeting other container elements in which to generate the input elements. If a specified container element (possible the result of using a CSS query string) does not exist, you'll naturally get an error.

In the worst case, you can create signal bindings yourself, bypassing Vega's binding support (in which case you will want to omit any `bind` properties from your Vega signal definitions. To then add bound elements you'll need to instantiate your own input elements and register appropriate event listeners, etc. 

And to be clear, this all concerns the Vega level, so does not address any issues regarding how Vega-Lite generates its Vega specifications.

**Comment by king612** [comment]
Thanks.  I believe I have isolated it down to a vega-embed issue, and the error message is just a misleading error.  Using straight vega and vega-lite in my Angular 5 app (TypeScript), the exact same spec renders just fine.  I will post over there, but in case it pops up again, digging around in the Chrome tools debugger seems to indicate some issue with strictness checking when TypeScript generates the packaged code.  This appears to happen upstream of the vega logger error, so I think that's just a downstream symptom when things are blown during the init/startup routines in embed.

Thanks again for your help and suggestions.
