### ISSUE TITLE
Using a signal to size the legend title causes it to draw on top of the legend

### ISSUE THREAD

**Issue by pelotom** [vega/vega#1228]
For example, adding

```
  "config": {
    "legend": {
      "titleFontSize": {
        "signal": "18"
      }
    }
  },
```

to [this chart](https://vega.github.io/editor/#/examples/vega/scatter-plot), it renders as

![image](https://user-images.githubusercontent.com/128019/38449522-ee481fc6-39c4-11e8-9fc0-bb5e701083da.png)

whereas using a simple value,

```
  "config": {
    "legend": {
      "titleFontSize": 18
    }
  },
```

it draws correctly:

![image](https://user-images.githubusercontent.com/128019/38449549-45d5ed54-39c5-11e8-8f1f-7827067108d0.png)

The same phenomenon occurs when setting the `fontSize` in the `legend`'s `encode` block.

**Comment by jheer** [comment]
Vega v3.3.0 includes more refined handling of legend parameters, including support for signal values for legend title `fontSize`. Thanks!

**Comment by pelotom** [comment]
@jheer hmm, https://vega.github.io/editor/#/ says it's on Vega 3.3, but the issue doesn't seem to be fixed when I test there with

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "width": 200,
  "height": 200,

  "config": {
    "legend": {
      "titleFontSize": {
        "signal": "18"
      }
    },
    "axis": {
      "titleFontSize": {
        "signal": "18"
      }
    }
  },
  
  "data": [
    {
      "name": "data",
      "values": [{ "x": 1 }]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "linear",
      "round": true,
      "nice": true,
      "zero": true,
      "domain": {"data": "data", "field": "x"},
      "range": "width"
    },
    {
      "name": "size",
      "domain": {
        "data": "data",
        "field": "x"
      },
      "range": [
        0,
        1000
      ]
    }
  ],
  "axes": [
    {
      "scale": "x",
      "grid": true,
      "domain": false,
      "orient": "top",
      "tickCount": 5,
      "title": "Foo"
    }
  ],
  "legends": [
    {
      "size": "size",
      "title": "Bar",
      "offset": 50
    }
  ]
}
```

**Comment by domoritz** [comment]
That might have been my fault (i.e. the fault of JS build systems and dependency management). It now works. 

![image](https://user-images.githubusercontent.com/589034/39072803-7b8ac966-44a0-11e8-9647-ddd983e92269.png)

**Comment by pelotom** [comment]
Great, thanks!
