### ISSUE TITLE
Using variables as data

### ISSUE THREAD

**Issue by Sneijky** [vega/vega#1229]
Hello.

On the following example : [https://vega.github.io/vega/examples/line-chart/](url), is it possible to replace the hardcoded values in "values" with variables? 
for example:
```
"data": [
    {
      "name": "table",
      "values": [
        {"x": var1, "y": var2, "c":0}, {"x": var3, "y": var4, "c":1}
      ]
    }
  ]
```
where varX represents variables from other data.

Thanks in advance

**Comment by kenklin** [comment]
Remember that Vega specifications are in JSON format, and Vega isn't a programming language, so it does not have what you think of as _variables_.  That said, if you are programming in say Javascript (or any other programming language) to create your Vega, you can write code to create the specification with variables assigned to `values`.  In my report generator program, I have functions calculate different parts of my spec before passing it to `vegaEmbed` in my HTML.

```
const myvalues = [
  {"x": var1, "y": var2, "c":0}, {"x": var3, "y": var4, "c":1}
  . . .
];
var myspec = {
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  . . . 
  "data": [
    {
      "name": "table",
      "values": myvalues
  . . .
}
const json = JSON.stringify(myspec);
```

https://vega.github.io/vega/docs/data/

**Comment by jheer** [comment]
Thanks for clarifying @kenklin! Vega does have a notion of variables with its `signal` abstraction, but signals are primarily for enabling interaction and parameterization. There is not a general notion of variables as requested here; instead it is common for generating JavaScript code to dynamically set up a Vega spec for visualization as Ken describes.
