### ISSUE TITLE
Group is not created without fill

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1236]
This looks to be either a bug, or docs need to be explicit about this.  This graph only captures mouse events if the group has a `fill` parameter. Without it, the mouse events are ignored.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "width": 400,
  "height": 200,
  "padding": 5,
  "title": {"text": {"signal": "test"}},
  "signals": [
    {
      "name": "test",
      "value": "move the mouse",
      "on": [
        {
          "events": "@grp:mousemove",
          "update": "floor(x())+', '+floor(y())"
        }
      ]
    }
  ],
  "marks": [
    {
      "name": "grp",
      "type": "group",
      "encode": {
        "enter": {
          "fill": {"value": "#fff"},
          "x": {"signal": "0"},
          "y": {"signal": "0"},
          "width": {"signal": "width"},
          "height": {"signal": "height"}
        }
      }
    }
  ]
}
```

**Comment by jheer** [comment]
This is standard web SVG behavior. No fill is treated as non-existent. Set fill to transparent to make it capture events. The stroke (if present) should also capture events. Feel free to file a PR if you think there is a good place in the docs we should call this out. Thanks!

**Comment by nyurik** [comment]
@jheer compared to `rect` mark, are there any other nuances I should be aware of?  It seems `group` is almost identical to `rect`.

**Comment by jheer** [comment]
That's about it!
- Group marks contain other marks; content can be clipped to the group mark's width and height.
- Group marks can have a colored background, identical to a rect mark.
