### ISSUE TITLE
how to include timedelta slider for datetime object

### ISSUE THREAD

**Issue by mattijn** [vega/vega#1238]
I've a line chart with datetime objects on the x-axis and number objects on the y-axis (using stocks example).
Now I would like to have a vertical rule, based on mouseover and using the slider.
![rule_datetime](https://user-images.githubusercontent.com/5186265/38547802-5d0050b2-3cb0-11e8-8a31-895a0e3be6d1.gif)
The mouseover rule function appropriate, but I cannot get the slider to work.

The slider only handles number values, so how can I translate these numbers into a timedelta object (if it exist)? 
And how can I connect this timedelta object to my datetime() object? 

Or should I use the slider as an index in the datetime array? Current timestep of the slider are in months.

Any thoughts are appreciated.

The url to this visualization in the vega-editor: 
https://vega.github.io/editor/#/gist/vega/mattijn/e9159e58eb9225caf05de246c998c73d/25614e7a8a0aefdfd9db3e5156262ea48a5cdeb3/vega3_rule_slider_datetime.json

**Comment by mattijn** [comment]
Did not succeed with the slider and a (probably not existing) timedelta object. But using a `bind select` and combined `events` in the  `on` statement also got what I need.

```
  "signals": [
    {
      "name": "indexDate",
      "update": "datetime(2004,7,1,0,0,0)",
      "on": [
        {
          "events": [{
              "type": "mousemove"
            },
            {
              "type": "touchmove"
            }],
          "update": "invert('xscale', clamp(x(), 0, width))"
        },
        {
          "events": {"signal": "dateTime_select"},
          "update": "timeParse(dateTime_select, '%b %d %Y')"
        }
      ]
    },
    {
      "name": "dateTime_select",
      "value": "Mar 1 2005",
      "bind": {
        "input": "select",
        "options": [
          "Aug 1 2004",
          "Sep 1 2004",
          ...
          "Feb 1 2010",
          "Mar 1 2010"
        ]
      }
    }
  ]
```

**Comment by mattijn** [comment]
Since a `date` object is measured in milliseconds since epoch, can use these values for a `range` slider where `min`, `max` and `step` are in milliseconds.

![slider_datetime](https://user-images.githubusercontent.com/5186265/38680147-e152f052-3e65-11e8-8680-1a0235bc21a2.gif)


```
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "signals": [
    {
      "name": "timestamp",
      "value": 1484113200000,
      "bind": {
        "input": "range",
        "min": 1484112000000,
        "max": 1484113800000,
        "step": 600000
      }
    },
    {
      "name": "datetime",
      "update": "timeFormat(timestamp, '%d %b %Y %H:%M')"
    }
  ],
  "marks": [
    {
      "type": "text",
      "encode": {
        "update": {
          "fill": {
            "value": "#000"
          },
          "text": {
            "signal": "'datetime: '+datetime"
          },
          "fontSize": {
            "value": 20
          }
        }
      }
    }
  ]
}
```
And combining this with a lookup using `abs()` to get the nearest timestamp, like:
```
    {
      "name": "lookup_date",
      "source": "source",
      "transform": [
        {
          "type": "filter",
          "expr": "abs(datum.date - timestamp) < 4.32e+8"
        }
      ]
    },
```
I can get the `range` slider to work as a `timedelta` object:
![slider_datetime2](https://user-images.githubusercontent.com/5186265/38686209-1f79d9fa-3e74-11e8-8adc-272ed5336016.gif)

Final spec in editor:
https://vega.github.io/editor/#/gist/vega/mattijn/e9159e58eb9225caf05de246c998c73d/53c3b7d1e9fdaa181397cc3889913c9cd88ca442/vega3_rule_slider_datetime.json

**Comment by josesaranda** [comment]
How did you get the value of Y and printed it at the top?
