### ISSUE TITLE
Events on area/line marks only register for the first point

### ISSUE THREAD

**Issue by arvind** [vega/vega#124]
On the stacked_area example, register a click handler:
ved.view.on('click', function(e, i) { console.log(i); });

Click at several points along the same area. Notice that the same item (with the same key) is returned every time. However, under item.mark.items, there are several items registered. This also occurs with line marks. 

Ideally, the event handlers would return the closest point/item.

**Comment by ajturner** [comment]
What was the resolution to this? It still seems to be an issue.

**Comment by kgarrity22** [comment]
Hi! I'm wondering if anyone found a solution to this? I'm using react-vega and still running into this issue for area marks
