### ISSUE TITLE
Preassigned colors for multiple line charts

### ISSUE THREAD

**Issue by onehost1** [vega/vega#1240]
I would like to set the color for each of the chart externally.

I try to do make a scale which is array of available colors like :
```
{
    "name": "color",
    "type": "ordinal",
    "range": [
            '#84C9CB',
            '#8A3EC3',
            '#C3587E',
            '#097D8A',
            '#98F76D',
            '#54AD38',
            '#EC1055'
     ]
}
```

then in marks, I have set it as :

```
"marks": [
          {
            "type": "group",
            "clip": true,
            "from": {
              "facet": {
                "name": "series",
                "data": "table",
                "groupby": "PointId"
              }
            },
            "marks": [
              {
                "type": "line",
                "from": {"data": "series"},
                "encode": {
                  "enter": {
                    "x": {"scale": "xscale", "field": "TimeStamp"},
                    "y": {"scale": "yscale", "field": "Value"},
                    "stroke": {"scale": "PointId", "field": "PointId"},
                    "strokeWidth": {"value": 2}
                  },
                  "update": {
                    "x": {"scale": "xscale", "field": "TimeStamp"},
                    "y": {"scale": "yscale", "field": "Value"},
                    "strokeWidth": {"value": 2},
                    "stroke": {"signal": "colorupdate"}
                  },
                  "select": {
                    "strokeWidth": {
                      "value": 3
                    }
                  },
                  "hover": {
                    "fillOpacity": {"value": 0.5}
                  }
                }
              }
            ]
          }
        ]
```
*Stroke* value points to the signal:
```
{
    "name": "colorupdate",
    "update": "scale('color', 'PointId % 6')" // point id is id of the group and 6 is length of color array. There should be better way for array.length in Vega but again I am no expert in Vega.
},
```

This same formula is used externally for items selected for chart:
**'color = ['PointId'] % color.length**

For some reason, and I am no expert in Vega, same color shows for all charts...

**Comment by jheer** [comment]
Hi! `'PointId % 6'` is a string, so you are always applying your color scale to a string constant. Also, signals compute values, not functions, so referencing `"colorupdate"` in your encoder will only provide a constant.

Try using the following for your stroke color encoder. The contained expression will then get evaluated for each data point being visualized.

```json
{
  "stroke": {"signal": "scale('color', datum.PointId % 6)"}
}
```

p.s. There is also a `length(array)` function for getting the length of an array. For example `length(range('color'))`. All expression functions are documented here: https://vega.github.io/vega/docs/expressions/

**Comment by onehost1** [comment]
@jheer thanks for the answer. It looks like it takes index of the datum.PointId instead of the value. Tried multiple things but same result. If value of PointId is 321, the value seem to come as 1. I cannot properly debug if datum.PointId is indeed 1 or 321 but multiple tests since yesterday lead to the same conclusion.

Can you please highlight on it... Thanks!

**Comment by jheer** [comment]
If you need to debug a signal expression, you can use the `warn` function to print debugging output to the browser's JavaScript console. For more, see the documentation at https://vega.github.io/vega/docs/expressions/#warn

**Comment by onehost1** [comment]
Thanks for pointing me to the page for debugging. It was always there but wasn't able to get my head around until now. Thank you.

Looks like I am able to find why correct color is not showing.
```
{
  "stroke": {"signal": "scale('color', datum.PointId % 6)"}
} 
```
**datum.PointId % 6** returns the index of the color scale. However, `scale(name, value[, group])` expects the value and not the key, hence I am always getting value of color[1] = '#ff0' rather than what I am expecting. Please see if that makes sense and if my prognosis is correct?

**Comment by kenklin** [comment]
The [Color Schemes](https://vega.github.io/vega/docs/schemes/) page has a **Registering Additional Schemes** section whose approach may also be useful.

**Comment by onehost1** [comment]
@kenklin thanks. I will be utilizing that next. However, that doesn't change the situation at hand.

**Comment by onehost1** [comment]
Another way could be to set color that Vega sets as a result of schemes to the external label (legend). Is it possible to 'catch' the filling color for the line charts and programmatically update the background colors of the external assets?
