### ISSUE TITLE
[enh] Allow override of the "key" default field in "nest" transform

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1241]
The [nest transform](https://vega.github.io/vega/docs/transforms/nest/) automatically creates `key` field when `generate` is set to true. This creates confusion when the original data already contains `key` field. Please overload the `generate` to also accept a string in addition to the boolean. E.g. `true` - uses the default `key`, and a string is used as a field itself. Thanks!

**Comment by jheer** [comment]
This is a sensible request, but unfortunately not as simple as you might think. We use the `nest` utility from d3-collection to generate the internal tree nodes. That utility hardwires the names of the generated object properties (`key`, `values`). While we could roll our own version of the utility or post-process its output, that would add extra maintenance, overhead, and/or code bloat. I don't see the need here being urgent enough to make the change at this point. In the worst case you could use a `formula` transform prior to `nest` to copy a `"key"` field to a property with a different name.

**Comment by nyurik** [comment]
@jheer i added a [pull request](https://github.com/d3/d3-collection/pull/26) for the `nest` d3 function, so hopefully this can be fixed once it makes it to d3.  Would it be ok to keep it open in the mean time?
