### ISSUE TITLE
Colors in sequential scale?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1252]
Please see the Vega output of the following VL spec:

```
{
  "layer": [
    {
      "mark": "rect",
      "encoding": {
        "color": {
          "type": "quantitative", "aggregate": "mean", "field": "precipitation",
          "scale": {
            "domain": [15, 2, 0.1, 0],
            "range": ["purple", "darkorange", "yellow", "white"]
          }
        }
      }
    },
    {
      "mark": "text",
      "encoding": {
        "text": {"type": "quantitative", "aggregate": "mean", "field": "precipitation"}
      }
    }
  ],
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/seattle-weather.csv",
    "format": {"type": "csv"}
  },
  "encoding": {
    "x": {"type": "ordinal", "field": "date", "timeUnit": "day"},
    "y": {"type": "ordinal", "field": "date", "timeUnit": "month"}
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v2.3.0.json"
}
```

![visualization 4](https://user-images.githubusercontent.com/781659/39074642-137419f2-44a7-11e8-9585-12e132d26c2d.png)

Notice in particular that Wednesdays in June have a value of 0.14, but the color is associated with the value 0 in the scale (or somewhere between 0 and 0.1 at best)

Originally from https://github.com/vega/vega-lite/issues/3631

**Comment by jheer** [comment]
This is not a bug. I think you are expecting pure linear interpolation of colors, but that is not what Vega does for sequential scales. There are two discrepancies here:

1. Sequential scales do not currently support domains with mid-point values; this is what is primarily causing the observed issue. Only the min and max domain values are used to determine interpolation. This design is debatable (one could file a feature request against vega-scale, which houses our sequential scale implementation), but it does mirror the limitations of d3-scale's sequential type.
2. On a more minor note, to create smoother color contours Vega uses basis spline interpolation when generating a sequential scale from a list of colors. (See https://github.com/vega/vega-encode/blob/master/src/Scale.js#L170) As a result of interpolation, the color curve may not exactly pass through given control points (e.g. "yellow"). This approach is consistent d3-scale-chromatic (e.g., https://github.com/d3/d3-scale-chromatic/blob/master/src/ramp.js#L4)

If you really want multi-point linear interpolation, set the scale type to "linear"!

**Comment by kanitw** [comment]
For Vega-Lite, we uses sequential by default.  One question is whether it makes sense to auto change the default to linear for color, if `domain` is specified with more than 2 values?

**Comment by jheer** [comment]
Sounds reasonable (and useful) to me, but may complicate end user's reasoning about what VL does. However, you would lose spline interpolation of the colors, but I'm not sure if that matters all that much. Alternatively, one could open a PR on vega-scale that updates our sequential implementation to support multi-point domain interpolation...

**Comment by kanitw** [comment]
Since it's a pretty small issue, let's say users should set scale type to linear for this use case for now. 
We have bigger fish to catch :)

**Comment by domoritz** [comment]
I think it's bigger fish to fry, not catch :-P

**Comment by kanitw** [comment]
Ok.  In Thai, it's "catch" first. lol
