### ISSUE TITLE
A way to apply different strokeCap to an isolated point on a line mark

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1253]
We discussed that if the expression has a function to check if the previous and next sibling points have valid values, this would be useful so that users can define production rules for strokeCap. 

Im thinking that  another alternative would be having new `"strokeCap"` = `"auto"`, which apply `"butt"` to connected points, but apply "square" to isolated points.  (This might be too magical, but I think it's worth mentioning anyway.)

**Comment by jheer** [comment]
Unfortunately this is not currently possible. Despite _visually_ having multiple segments, a line or area with "undefined" points is still represented as a single Canvas/SVG path. You'd need to break up a single line/area into multiple marks to be able to change any stroke properties. However, doing so would require redesign and reimplementation of a large swath of scenegraph rendering and event handling, and also probably require us to drop functionality from d3-shape and instead also reimplement a bunch of underlying utilities.
