### ISSUE TITLE
Errors are not caught if thrown in event handlers

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1254]
An error that gets thrown in an event handler, e.g. tooltip, does not get caught and redirected to the vega.error, resulting in fatal error in Kibana (full app collapse).

I am not sure what is the best place to catch such errors. On one hand, the events start at 
[CanvasHandler.initialize](https://github.com/vega/vega-scenegraph/blob/94823ecca642eb334c00d57f7d2236264949e155/src/CanvasHandler.js#L23), but that would only handle canvas.  Is there a better place to capture any errors that occur inside Vega, including external event handlers?

**Comment by jheer** [comment]
Thanks! You're right that the tooltip handler currently doesn't trap errors and route them to view.error (which is where they should go, not vega.error!). I will look into fixing that.

However, despite the title of this issue, other event handlers _should not_ have this problem. See https://github.com/vega/vega-view/blob/master/src/events.js#L56, which traps any handler errors and redirects them. If you are seeing "leaked" errors from event handlers, please share a reproduction so we can investigate!

Note that the above statement applies to event streams defined within a Vega spec. If you are adding your own *external* event handlers using `addEventListener`, then you are responsible for the error handling.

**Comment by nyurik** [comment]
@jheer thanks!  I wasn't sure why tooltip handler had a different handling mechanism than other events, and bypassed error capturing/redirection.

I cannot agree with your last statement though.  If Vega initiates the call chain (attaches to browser event), and some Vega plugin fails to capture it, I believe it should be Vega that captures that error and redirects it to the `view.error()`.  This is very similar to how other libraries, e.g. Promise lib, behave - it calls user function, but it always wraps that call in a try/catch, to ensure that error gets redirected to the failed promise.  Without this rule, it would put a significant and unnecessary burden on all Vega users to add "glue code" between Vega and plugins.

For example, my [vega-leaflet plugin](https://github.com/nyurik/leaflet-vega) calls `addSignalListener` [for 3 signals](https://github.com/nyurik/leaflet-vega/blob/master/src/VegaLayer.js#L129).   If the handler (or some lib it calls) throws an exception, that error would not be handled anywhere, crashing the whole system. If a user wants to use my plugin, and notices this, they could only fork the library - there is no way for them to fix it "from the outside".  On the other hand, Vega as a proper "plugin host" could wrap event handler invocation inside a try/catch, and redirect exceptions.

So it is either two lines of code in Vega, or every plugin author should keep this in mind and test for it and ensure it gets done, plus all plugin users who have no easy way to fix it if Vega is missing those two lines.  I think it is much safer and more convenient for everyone to just handle the errors in one place, and never worry about them.

What do you think?

**Comment by nyurik** [comment]
Would passing a single `error` parameter to all scenegraph instances during construction solve this?  I presume it is the view that creates them, so having that function would allow event dispatchers to use it without knowing anything about the view? Thx!

**Comment by jheer** [comment]
Maybe. I can think about what might make sense when I have more time. FYI, you mentioned signal listeners above... I should add that those "automatically" get trapped errors routed to `view.error` because they are invoked within dataflow evaluation. Any errors arising from a dataflow operator are trapped by [`dataflow.run`](https://github.com/vega/vega-dataflow/blob/master/src/dataflow/run.js#L76).

Also Vega v3.3.1 has been released, including error trapping for the tooltip handler.

**Comment by nyurik** [comment]
ah, thanks, will migrate today!  Which of the callback-invoking methods have/don't have that?  I will add a PR to document this.

**Comment by jheer** [comment]
FYI, in more recent Vega View releases I centralized error trapping support, and added an extra level of trapping for signal listeners, such that they should no longer disrupt the rest of the dataflow execution. Internally generated events (e.g., event streams defined in Vega specs) include error trapping as well. At this point, error trapping is not performed for resize listeners or externally added event listeners. 

I think we should definitely add error trapping for resize listeners. That will be easy, and is needed.

For general event listeners, there are two approaches to consider:
- Wrap event listeners callback with error trapping functionality from the View level.
- Push error handling down into the scenegraph itself ([e.g., in the CanvasHandler]( https://github.com/vega/vega-scenegraph/blob/master/src/CanvasHandler.js#L139)). The challenge here is that there is not a direct, generalizable path for routing errors back to `view.error`, as the scenegraph can be used independent of a Vega view.

**Comment by jheer** [comment]
Error trapping for both resize listeners and external event listeners has been added as of [vega-view@3.1.0](https://github.com/vega/vega-view/releases/tag/v3.1.0).
