### ISSUE TITLE
Global variables support

### ISSUE THREAD

**Issue by marlen2610** [vega/vega#1257]
Is it possible to define global variables within Vega? I need some kind of counter to handle my control flow with transformations using this counter, is there a way?

Thanks

**Comment by domoritz** [comment]
Are signals what you are looking for?

**Comment by jheer** [comment]
Yes, you can define `signals`, both in the top Vega scope (for global variables) or within nested group scopes (for local variables). Signals can then be referenced in any expressions and can be used as parameters to data transforms. Here is the primary documentation page: https://vega.github.io/vega/docs/signals/

Vega does _not_ allow arbitrary variable assignments, but you can write handlers (update statements, event handlers, data set trigger handlers) to generate new signal values in response to a number of different events.

**Comment by marlen2610** [comment]
Thanks for the answers, I've been looking into signals but I only can see events like click, mousemove, keyup... on Supported Event Types, what I need to do is to have some kind of counter and update it when some condition is met when transforming my data, is that possible?
