### ISSUE TITLE
Use specific lib versions in vega and vega-lib package.json

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1259]
Currently vega and vega-lib use major version only style of specifying dependencies, e.g.  `"vega-dataflow": "3"`. This is incorrect because it creates ambiguity that installer can treat in different ways.  Lib's package.json must specify the minimum required version for that lib to do what it needs.  In case of "3", it means the lib can do what it promises with ANY minor/patch version of 3.

Let's say there are two libs, A and B, and both rely on the same lib X.  If A requires a version "3.1.1", and B requires "3", than yarn & npm can install just version "3.1.1", even if the current version of lib X is "3.2.0". So if lib B actually needs 3.2, it must say so to avoid using 3.1.1.  The fact that yarn installs the latest of "X" is due to the fact that there are no other lib requiring an older version.

A consequential problem is the lock file. If user uses vega 3.1.0, and they want to update, their expectation is usually just bump the version to 3.2.0.  This approach works for nearly all other libs, but with Vega, one also has to delete node_modules and rebuild the lock file, or else even though the node_modules/vega and the lock file get updated, the vega sub-libs will remain at the original versions.

**Comment by domoritz** [comment]
I ran into this problem a couple of times in the editor. @nyurik probably remembers.

**Comment by jheer** [comment]
Vega 4.0.0-rc.1 now uses detailed lib versions for dependencies.
