### ISSUE TITLE
data is not sorted after points are added or removed

### ISSUE THREAD

**Issue by mattijn** [vega/vega#1260]
I have a visualization where I can add (on mousedown) and remove (shift + mousedown) a point in the chart. But the data is not reordered after a new point is added.
![slider_datetime3](https://user-images.githubusercontent.com/5186265/39238709-3f6eaa82-487f-11e8-891c-44f1a85f722e.gif)

I expect it sorts the data based on field `x` since I use a `collect` transform including ordering:
```
  "data": [
    {
      "name": "data_points",
      "values": [{"x": 20, "y": 7.5}, {"x": 60, "y": 6.6}, {"x": 92, "y": 8}],
      "on": [
        {"trigger": "addPoint", "insert": "addPoint"},
        {"trigger": "remPoint", "remove": "remPoint"}
      ],
      "transform": [{"type": "collect", "sort": {"field": "x", "order": "ascending"}}]
    }
  ]
```

Spec in vega-editor: https://vega.github.io/editor/#/gist/vega/mattijn/f3ad3afa7c4738a2e334fb5b940c766f/fc9a0de233af39c485ac592677ad0d552c2bb25b/vega3_add_remove_points_sort.json

**Comment by mattijn** [comment]
I added an empty dataset `{"name": "data_collector"}` and a signal as such:
```
    {
      "name": "data_points_sorted",
      "update": "modify('data_collector', data('data_points'), true)"
    }
```
Now in the `marks` I use the `data_collector` in the `from` statement and it works.. somehow and somehow not:
![fwd7yuxj7z](https://user-images.githubusercontent.com/5186265/39269587-938189c4-48d3-11e8-8273-da7141f2d5a8.gif)
- I can add a datapoint in between others and the dataset is sorted by the `x` field. Great.
- The hover is fixed on all points except for the latest point added and only after adding a new points 'previous hovers' will disappear. 
- Once I try to remove a point the dataset is becomes unsorted again and removing points becomes even impossible.

Spec (simplified):
```
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "width": 700,
  "height": 200,
  "padding": 5,
  "data": [
    {"name": "data_collector"},
    {
      "name": "data_points",
      "values": [{"x": 20, "y": 7.5}, {"x": 60, "y": 6.6}, {"x": 92, "y": 8}],
      "on": [
        {"trigger": "addPoint", "insert": "addPoint"},
        {"trigger": "remPoint", "remove": "remPoint"}
      ],
      "transform": [
        {"type": "collect", "sort": {"field": "x", "order": "ascending"}}
      ]
    }
  ],
  "signals": [
    {
      "name": "addPoint",
      "on": [
        {
          "events": "click[!event.shiftKey], mousedown[event.buttons && !event.shiftKey]{20}",
          "update": "{x: invert('xscale', x()), y: invert('yscale', y())}"
        }
      ]
    },
    {
      "name": "remPoint",
      "on": [
        {
          "events": "click[event.shiftKey], mousedown[event.buttons && event.shiftKey]{20}",
          "update": "datum"
        }
      ]
    },
    {
      "name": "data_points_sorted",
      "update": "modify('data_collector', data('data_points'), true)"
    }
  ],
  "scales": [
    {
      "name": "xscale",
      "type": "linear",
      "range": "width",
      "zero": false,
      "domain": {"data": "data_points", "field": "x"}
    },
    {
      "name": "yscale",
      "type": "linear",
      "range": "height",
      "nice": true,
      "zero": true,
      "domain": {"data": "data_points", "field": "y"}
    }
  ],
  "axes": [
    {
      "orient": "bottom",
      "scale": "xscale"
    },
    {
      "orient": "left",
      "scale": "yscale"
    }
  ],
  "marks": [
    {
      "type": "line",
      "interactive": false,
      "from": {"data": "data_collector"},
      "encode": {
        "update": {
          "x": {"scale": "xscale", "field": "x"},
          "y": {"scale": "yscale", "field": "y"},
          "stroke": {"value": "#ffcc66"},
          "strokeWidth": {"value": 2}
        }
      }
    },
    {
      "type": "symbol",
      "from": {"data": "data_collector"},
      "encode": {
        "update": {
          "x": {"scale": "xscale", "field": "x"},
          "y": {"scale": "yscale", "field": "y"},
          "stroke": {"value": "#ffcc66"},
          "fill": {"value": "#ffcc66"},
          "strokeWidth": {"value": 1}
        },
        "hover": {
          "strokeWidth": {"value": 5},
          "stroke": {"value": "red"},
          "fill": {"value": "red"}
        }
      }
    },
    {
      "type": "area",
      "interactive": false,
      "from": {"data": "data_collector"},
      "encode": {
        "update": {
          "x": {"scale": "xscale", "field": "x"},
          "y": {"scale": "yscale", "field": "y"},
          "y2": {"scale": "yscale", "value": 0},
          "fill": {"value": "#ffff66"},
          "fillOpacity": {"value": 0.15}
        }
      }
    }
  ]
}
```

**Comment by jheer** [comment]
Here's an explanation:
- The `sort` directive on a `collect` transform will ensure the _data_ is sorted. However, this is not the same as sorting the _marks_ bound to the data. Initially, the data is sorted and this sort order in turn determines the order in which the data objects are bound to marks within a data join. However, this is not true across updates in which you add/remove points.
- As you add and remove data points, the underlying data array is re-sorted. BUT, the data join processes tuples incrementally, simply appending or deleting marks as data points are added or removed. Across updates, the data join functions separate from the collector's sorting.
- To solve your problem, you want to sort the _marks_, not the _data_. Adding an appropriate `sort` directive to your `area` mark definition should fix things. You can then also delete your `collect` transform. The `sort` documentation is under https://vega.github.io/vega/docs/marks/#top-level-mark-properties

Hope that helps!

**Comment by mattijn** [comment]
For future reference:
I solved this by the way some time ago:

- drag a point when mouse-down on point
- insert a point with shift+click on a location in the chart
- remove a point with alt+click on a point (on Mac this is option+click).

Vega-editor long-[url](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KAHdGAExbYwADgAMuxREgpG1fFoBM+w1ELo1axjOpaArDchr0eTDgDaShCgECFQMuioyFqe3ugA+oTcTniwCoEhkBToADasyKn+wJAAHpYGUACeWgDsdK4AvvJgRaU4AGzlkFXtdG2NzSVaAJwWTV1a2vUAujahkLJaAaGhRXgATqbUyGvRsGvwClCo3I4AZt1QewdjWbn50Wpr6C6N6SuQ65vb0fZqAApJGR4Q6QJywbbAnCQX4A5KQV7LEKrDbULY7KFrNCwoEgzHHKjRPHY4H1N5gKbpUkQGZKSCwUzhbIFMBLJFkyDhSK7fZpRGZHJ5aIAQi8eFYqF5y3mcn8ZKCkGQVCBzMgAAFRfFEslYAlAXgsMdWOC1NxlHIxqxCKKolDReL4bNlkVFchldFVDITcoDdwjchLSDLdbhXaJVTlhTQgi2XzOTaoI9npK5rdBbbvPbHUYFrLEUE5RkXW6oR6vT6-fjkE1S6by8bTeaC0Yg9545BgMUcE4qGs8AAKADkxQQOWQA6a8GyEUIfeKfYAlE1yqoNIh54uwBUuzIe-2BxUR9kxxOp6gZxUF-IDCYzHh1-VIAXw6FIyFo-nYxE2zC9cmMjmWQLYI8yMIsUmiQ16zNPwwLodhWAIWRYDAAAyFCwFg2BEEYU48AAaWQCpUPQoVYJyfDCKmYArAfLMpRbPA2w7bdd0HYd4FHccwDndcmi3MBuwhQcDw4o8uIve9HxA58QlfCB32adk40JLFfzo6VFiApsoDAlVIOQL0ZBgpU8DghC8CQ4iwFIky6CwnCKKItCMNs8iCIqKiaL-PkGLbUMpLzGTqUpUIlBpIxD3uXMYylZSoXY0dvKgPAKkINtsicZB0B2dSnmcNsV00dSAC9tm4LRThycF1JNDAnEWcoAEZ9DksAFOAuY4sqSKko+VL0sy7LeryrZohvcx1JkRh4HjdY8hKsqtDmqt2Vq9B6v8JrdFa8NwqgdBiiiwCVnZbgNldSEoHYbhEIldSevinr1LwaaAGsAGFfRxHBmue5gj2iAARRhYB8GQZpZVApl66gNjUJa1nm9lXXgE54w6qVYfULQMZ8q1Wxxul1m4V70f5O5ogAYiGGmHUuYnSYAdXUTQcCKVN410OhGvqIK3zoowXvgV7mSKXzCdBtYSbJjnonYKdhfhXmBagKd2GQJkce0yBxbZ7SjFORhsmyQnZaheX0EVhSQOhZwAbZ8m0zAXRrbzSBTlkPAAGVGFK02BXjRqLD5qMnxVj5-rJ3WBg9oEfb9h2zbARrRF512jDWjbFJA5t8cYiWGZlgO5YV166aJqWmZZxB-Ypn7eafMkZPa07zu+1XkFw3qHu60Soj+4XPtYdu2j+vB7agAAJZBTHwSGAGoADkAEE-mh9SsfhnBlvUlG0a1m3N4PnOdbzsnJel2uncganaf6CvpeZ1cr857mG+k8OhZFwno6KC-SZfiXS2Zc07hzVhrUW2tf76ygIbY2gDzalwdDA221AJ7s2LjgF2Ks5ix29r7Iuddk7B20iHNqn9I4-zPoTPB8dCFOxTqAgsnhuB1RlNnE+v8H4AMTpgq6SD77-2QE-VmAwk48zIXzZuYUPAYDWN-aKH4pQpTStEDKMh+7smSNsS2L0CQ4EqkyFafJThSwlA7DUDxYi6m1Mgvk0hew0MYBrLeUBSiuwVODfeesbbQJzm4iWfdogJQBmMQ2Ljgl2JPhcP+QSoQiUSmE5x2RXHjHThkIRCCoCU1OKceA8A2htCiTbIRIia68KISQ6STdKSOlxmEL8VifA2OVC04Ez1+q7AqKga6Jt1KmNYYTSx6ZmlajdB4hxl0ijhJSZEjxe81Do2YX4k+rQBg9xKE9WByTUnuJwZUQJiV4lbPdjs6IVR0kRULlkm+uT8mFOKW7OBJsKnXxyXkgpRTLn00rsI6uWSeZh2YYgbgPZj4lMLmUrJDR9ncPoW2TE8NvmnPga8hFBl4SN0RM3Op7IVHfkxJgdS2injwD0fGQx1V2QDPMQMYZCZrFjPAhMs6UzTkRPio80CXjFngvotQnxqzDkT02UEpJHKAnIpiXSOJvdEnbIlWk2FFQLDCrbAk0JUAk7YO1s8m57zckPORc8gA8nYeAzBpXau5g0LFyxpHBXqEAA)
