### ISSUE TITLE
Add option to have tooltip handler invoked continuously for mouse movement events while over a mark

### ISSUE THREAD

**Issue by pelotom** [vega/vega#1263]
Prior to v0.9 of `vega-tooltip`, tooltips would follow the cursor, which was desired behavior for our tool. Now that it's based on `vega`'s `tooltip` functionality, it is unable to do that because the handler is only invoked on `mouseover`.

**Comment by jheer** [comment]
We are changing the tooltip "trigger" event from `mousover` to `mousemove`. This has already been implemented, but not yet released. It will be included in the next Vega release.
