### ISSUE TITLE
dx/dy text mark offsets are applied post-rotation

### ISSUE THREAD

**Issue by mprudhom** [vega/vega#127]
The docs say that dx should be the "horizontal margin, in pixels, between the text label and its anchor point" However, the offset appears to be applied after the rotation is applied to the text. For example, a text label with an angle of 90° and a dx of 20 will actually be moved down 20 rather than to the right. 

Reproduce with the following:

```javascript
{
  "data": [
    {
      "name": "angles",
      "values": [0, 45, 90]
    }
  ],
  "marks": [
    {
      "type": "text",
      "from": {
        "data": "angles",
        "transform": [
          { "type": "formula", "field": "message", "expr": "'My angle is ' + d.data + '°'" }
        ]
      },
      "properties": {
        "update": {
          "fill": { "value": "orange" },
          "x": { "value": 20 },
          "y": { "value": 20 },
          "fontSize": { "value": 20 },
          "text": { "field": "message" },
          "angle": { "field": "data" },
          "dx": { "value": 50 }
        }
      }
    }
  ]
}
```

**Comment by arvind** [comment]
Hmm, Vega 1.5 and Vega 2 render the above specification identically. This looks correct to me (perhaps it was fixed and we missed closing this issue), but if you believe it is a bug, please re-file this issue in the [vega/vega-scenegraph](https://github.com/vega/vega-scenegraph/issues/new) repository. Thank you!

![download](https://cloud.githubusercontent.com/assets/42262/8607002/c5434e3e-2644-11e5-839d-eb39bb67a6a2.png)
