### ISSUE TITLE
Add timer-based signals to Vega

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1271]
One of the constant asks I hear is how to do animations in Vega.  Animations require timer-based event mechanism, so one solution is to add a signal that changes on timer.  This issue is to discuss the best interface/approach. It doesn't have to be implemented in core vega, but would be good to get everyone's opinions.

### Simple - name-based
This, somewhat hacky approach, allow addition of timers with the minimal Vega code changes. A Vega plugin could iterate over all signals, and if any signal names match `/^timer_([0-9]+)$/`, automatically update signal's value with the `new Date()` object every (number) milliseconds.  The timer can be paused/resumed by setting its value to truthy/falsy value.

```js
signals: [{
  "name": "timer_1000",  // will be updated once a second
  "value": true
}]
```

### Complex - core support
Extend core event parsing mechanism to allow parameter passing. This approach might be more flexible in some cases, but also makes it harder to suspect/resume timer as needed.
```js
signals: [{
  "name": "myTimerSignal",
  "on": [{"events": "timer(1000)", "update": "..."}]
}]
```

**Comment by domoritz** [comment]
I believe we could use this to implement games in Vega :-)

**Comment by nyurik** [comment]
I think most of the use cases involve various forms of animation, e.g. one user request was to make an alarm-style animation - like a big pulsating red dot indicating a problem. Some other ideas could be trend indicators (e.g. small up or down arrows next to the ticker names indicating upward/downward trend at the moment)

**Comment by g3o2** [comment]
Banal but probably common use case: observing a bubble plot through time à la Hans Rosling. Right now this can already be achieved by streaming data or by manually sliding through the data via bind.

**Comment by nyurik** [comment]
@g3o2 unless you are replaying existing data, I don't think timer will help with that.  You want the data source to produce a stream of events, or possibly use [observable approach](https://github.com/vega/vega/issues/893) (feature request)

**Comment by domoritz** [comment]
Another use case: hypothetical outcome plots or HOPs.

**Comment by domoritz** [comment]
@nyurik I don't think the Hans Rosling style visualizations need live data. 

How about a data source that works with websockets. I think that would be super useful and I'd upvote an issue if you create it!

**Comment by nyurik** [comment]
@domoritz good idea, but i think this shouldn't be a core feature yet - maybe a plugin? Several reasons:
* WS hasn't been standardized as a data transmission format - each site implements its own custom protocol
* I wouldn't want Vega update to all of a sudden support a new protocol by default for security reasons. The less functionality is enabled by default, the more secure the product is.  (smaller attack surface).

As for Hans Rosling viz - agree, I think I misunderstood @g3o2 to mean streaming data support, not (looped) time animation.

**Comment by g3o2** [comment]
My apologies for my lack of appropriate terminology to express my idea above. 

Currently, I'm using a bind selection in vegalite, which filters the (already loaded) data. With the mouse wheel I can then sort of create an animation - it would be nice to just hit a "play" button to do exactly that or to loop over a user-ordered array of "years".

Indeed no stream needed, though my guess is that this would be an alternative way of achieving the same effect

**Comment by mattijn** [comment]
Not considering the discussion if animations are only a distraction.
Following the earthquakes [example](https://vega.github.io/vega/examples/earthquakes/), would be nice to be able to set a flight path and fly-over eg. the mid-ocean ridges like the 3min video here: https://youtu.be/PdTlCNzCkg4?t=35m43s (including voice-over of Paul Wessel would be a great addition).

**Comment by tonne1** [comment]
@g3o2: exactly. Timer-animated visualizations can give insights we wouldn't get as easy without, because we don't have to map time to distance. You can see all the data in one chart rather than in 20 or 50 small multiples.

The general scenario is that you have multi-dimensional temporal data over some periods, say unemployment rate over the last 20 years by state. You'd slice the data by year, each year triggered by a timer step and smoothly transitioned to the next year. You could use a bar chart and a map, synced and both using the same heatmap. Sort the bars by unemployment rate, animated. bar length and heatmap both encodings of the unemployment rate. bar domain/dimension = state.

Animated cost/revenue bubble chart over departments, each bubble a department. Break-even line across. Bubble radius encoding department size. Bonus: let bubbles leave a trace (their path in time).

Age distribution over time, additionally grouped and color coded by age groups.

These charts are like time machines, you sit back and watch the things unfold. Anomalies are easy to spot, and then you can drill further.

**Comment by domoritz** [comment]
https://github.com/dgrtwo/gganimate supports animations in ggplot and can be an inspiration for how a timer could be used.

**Comment by jheer** [comment]
Vega v4.0.0-rc.2 now includes a timer event (`{"type": "timer", "throttle": 500}` or `"timer{500}"`). For documentation, see https://vega.github.io/vega/docs/event-streams/

One or more examples for the gallery on the website are still forthcoming. However, multiple examples are now included as test specifications within vega-lib:
- https://github.com/vega/vega-lib/blob/master/test/specs-valid/gapminder.vg.json
- https://github.com/vega/vega-lib/blob/master/test/specs-valid/hops.vg.json

However, note that this adds a timer event only. It does not include animated transitions (i.e., interpolated transitions or tweening). We intend to add this at a future date, but that effort will require some major modifications to Vega internals. In the meantime, though a bit hacky, you _can_ use CSS transitions in conjunction with the SVG renderer to perform some animated transitions.

**Comment by g3o2** [comment]
One could do similar kind of animations based on brushing through a scatter plot along a dimension such x or y, allowing to slowly visualise the relationship between variables in a scatter plot matrix. Would the current implementation of timer event already render this possible? Or would this involve more complexity?

I guess this use case could scale to other interaction techniques.

cc: @nyurik @domoritz

**Comment by tb582** [comment]
Hi - checking in to see any movement (pun) on this ? I too would like this bubble chart idea with updating/real-time like data.

**Comment by jeffemandel** [comment]
I've been using timer{1000} quite successful in a realtime pharmacokinetic simulation. I'm working on a demo of the system, and would like very much to be able to fast-forward based on a signal/expression:
`timer{if(fast_forward ? 100:1000)}`
Where fast_forward is a signal.
