### ISSUE TITLE
Question: Embed Vega graph

### ISSUE THREAD

**Issue by emilmirzayev** [vega/vega#1272]
Hi. I have a question regarding embedding of a Vega  graph to my blog which I built with Jekyll. I am not very knowledgeable  with HTML concepts, that's why [this](https://github.com/vega/vega/wiki/Embed-Vega-Web-Components) was not very helpful for me. After figuring that out, i would also write a docu for that and maybe you can add it to vega docu. Thanks!

**Comment by jheer** [comment]
The wiki page you linked to is out-of-date, as it was written for Vega 2. Perhaps some of the more recent documentation will help?

- https://github.com/vega/vega-embed - The Vega embed project, including usage example
- https://vega.github.io/vega/usage/ - Vega usage / deployment documentation

Some level of HTML familiarity will inevitably be required to get custom embedding up and running, but hopefully these links prove helpful. We're also happy to accept Pull Requests with improved documentation!
