### ISSUE TITLE
Travis testing fails on vega-dev repo

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1274]
I tried to enable TravisCI on vega-dev, and ran into a few issues.

* Travis ignores `postinstall` script for some reason, and had to be forced
* Travis could not clone repos using ssh because it has no ssh key, thus had to change to https
* once enabled, tests fail in many places

I created two PRs there, one that just enables travis, and another that also switches to submodules. The second one greatly simplified my multi-repo management (because of various commands like `git submodule forech ...`, dirty-tracking, and extra tools available), so I do think we should switch to them. Once everything is ready, I think we should simply move things to vega repo, to keep things consistent.

**Comment by jheer** [comment]
Moved this to https://github.com/vega/vega-dev/issues/3
