### ISSUE TITLE
Vega editor should auto-(re)-size charts

### ISSUE THREAD

**Issue by mprudhom** [vega/vega#128]
It would be nice if the online Vega editor would see if a spec has width and height set, and if not, set it automatically to the size of the frame in which the viz is being rendered. In addition, it could set the window.onresize to perform an update on the view.

To best support this, the example specs should have most of their properties that are currently defined in the "enter" set be moved to the "update" set so that the marks are correctly re-positioned.

I'd be happy to implement this if there is any interest.

**Comment by m48u** [comment]
+1 
dynamic width would be a great feature especially when using Bootstrap for layout.

**Comment by arvind** [comment]
We have broken the editor out to a [separate repository](http://github.com/vega/vega-editor/). Please re-file this issue there, or submit a pull request if you'd like to see this functionality :)
