### ISSUE TITLE
Legend labels for binned data

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1280]
Shouldn't the first and last label be visible below?

<img width="118" alt="screen shot 2018-05-18 at 23 30 43" src="https://user-images.githubusercontent.com/589034/40265768-9cc63f66-5af3-11e8-9150-7cb2798641de.png">

Same issue in https://vega.github.io/vega/examples/county-unemployment/

**Comment by jheer** [comment]
No. This is the design. It matches NY Times style. In some cases the end points are undefined anyway (e.g., -Infinity, +Infinity).
