### ISSUE TITLE
Interactive legend for line chart question

### ISSUE THREAD

**Issue by coenhallie** [vega/vega#1284]
Hello,

I am working on a line chart which needs an interactive legend where users can simply enable/disable certain lines. I have tried to replicate the functionality of this [example chart](https://vega.github.io/editor/#/examples/vega/interactive-legend), to no avail. I have added my chart below. I have embedded some values which are normally fetched from an API.

This is my chart, you can see that the legend is not working correctly. [HERE](https://vega.github.io/editor/#/gist/vega/coenhallie/faf2825e7b95917a1430ccb56673ee13/641767e0091b19aa290ea96b40dca999c7d1d2ef/vegachart.json)

Many thanks for helping.

Kind regards,

Coen H.

**Comment by jheer** [comment]
Hi! The GitHub issues here are for handling bug reports, feature requests, and other Vega development issues. For help using Vega, please post on the Vega mailing and/or join the Slack organization! You can find links for both on the Vega website (scroll down to the bottom): https://vega.github.io/vega/
