### ISSUE TITLE
Why does axis's tickCount affect tick label format?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1287]
![image](https://user-images.githubusercontent.com/111269/40288951-9ce6e180-5c6a-11e8-8495-380e7b8f7ecc.png)

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/seattle-weather.csv"},
  "mark": "tick",
  "encoding": {
    "x": {"field": "precipitation", "type": "quantitative", "axis": {"tickCount": 100}}
  }
}
```

![image](https://user-images.githubusercontent.com/111269/40288932-8f17e77a-5c6a-11e8-95aa-07da08511b83.png)

The ticks now have `.0` for all numbers

Is this just artifact of JS floating point calculation?

**Comment by domoritz** [comment]
I think it's because the ticks actually have values that need the precision. However, their labels are not visible because the labels overlap and so many are removed.

**Comment by domoritz** [comment]
I still think this is a bug, though.

**Comment by jheer** [comment]
I disagree that this is a bug. The precision correctly aligns with the number of ticks and currently will stay consistent when changing the pixel length of the axis.
