### ISSUE TITLE
Allow scaffolding to contain SVG element with CSS refs

### ISSUE THREAD

**Issue by mprudhom** [vega/vega#129]
It seems that if you modify the expected styling (<https://github.com/trifacta/vega/wiki/Runtime#basic-use>) to contain an existing SVG element, it winds up getting clobbered the first time the spec is rendered. It would be nice if Vega identified the existing declaration of an SVG element and didn't overwrite it so that the SVG can contain styling definitions (e.g., so that the background color can be set).

```html
<html>
<body style="padding: 0; margin: 0; overflow: hidden;">
  <div id="viz-visualization">
    <div class="vega">
      <svg xmlns="http://www.w3.org/2000/svg" class="marks" width="100%" height="100%" viewBox="0 0 486 387" preserveAspectRatio="none">
        <defs>
          <style type="text/css"><![CDATA[
            svg {
              background-color: red;
            }
          ]]></style>
        </defs>
      </svg>
    </div>
  </div>
</body>
</html>
```

**Comment by arvind** [comment]
For simplicity, Vega starts with a clean slate every time. I recommend stashing the styling you with to preserve and re-applying it (if you can't apply it _after_ Vega spec parsing to begin with).
