### ISSUE TITLE
map projections

### ISSUE THREAD

**Issue by Fil** [vega/vega#1292]
Hello, as we briefly discussed in OVC:

https://vega.github.io/vega/examples/projections/ shows how to include d3-geo-projection in a webpage, but I would like to do the same with @observablehq

I don't see if it is possible and how to add d3-geo-projection (and d3-geo-polygon).

In that specific case, vega is loaded with `require('@observablehq/vega')`, seemingly providing no means to "inject" an enriched d3.

WIP at https://beta.observablehq.com/d/9012763e5a853616

**Comment by jheer** [comment]
I just released a new module that may help: [vega-projection-extended](https://github.com/vega/vega-projection-extended). This module adds the projections from d3-geo-projection to Vega's projection registry. The basic HTML usage is to simply import as a script after Vega has been imported.

That said, I have not done any testing with Observable... I don't know if a bound `vega` variable will be accessible to the new module upon import within Observable's runtime. Let me know if you try to use it. I'm happy to make modifications (or accept PRs) to ensure it works on Observable.

**Comment by domoritz** [comment]
@ydlamba, can you include this package in the editor so we can run vega.github.io/vega/examples/projections?

**Comment by Fil** [comment]
Using code from vega-projection-extended and from @observablehq/vega I was able to put this together: https://beta.observablehq.com/@fil/vega-projections

Thank you!
