### ISSUE TITLE
Visualize LineString on Map

### ISSUE THREAD

**Issue by jc92** [vega/vega#1293]
I was wondering how can one plot linestrings on vega. 

The output I get is simply the worldmap but I am unable to visualize the line.

Data format:
` "location": {
      "type": "linestring",
      "coordinates": [
        [
          -77.03653,
          38.897676
        ],
        [
          -77.009051,
          38.889939
        ]
      ]
    },
    "traffic_level": 5,
    "timestamp": 2
}`

Given the above example I tried the following:

{
  $schema: https://vega.github.io/schema/vega-lite/v2.json
  data: {
    # URL object is a context-aware query to Elasticsearch
    url: {
      # The %-enclosed keys are handled by Kibana to modify the query
      # before it gets sent to Elasticsearch. Context is the search
      # filter as shown above the dashboard. Timefield uses the value 
      # of the time picker from the upper right corner.
      # %context%: true
      index: traffic_data
      body: {
          query: {
            range: {
              discovered_ts: {gte: 0}
            }
          }
        size: 10000
        _source: ["location"]
      }
    }
    # We only need the content of hits.hits array
    format: {property: "hits.hits"}
  }
  "mark": {
    "type": "geoshape",
    "interactive": false,
    "encode": {
      "enter": {
        "path": {"field": "location.coordinate"},
        "stroke": {"value": "black"},
        "strokeOpacity": {"value": 0.15}
      }
    }
  },
  "config": {
    "kibana": {
      "type": "map",
      // Initial map position
      "latitude": 50,   // default 0
      "longitude": 9,   // default 0
      "zoom": 5,          // default 2
      // defaults to "default". Use false to disable base layer.
      "mapStyle": "default", 
      // default 0
      "minZoom": 5,
      // defaults to the maximum for the given style,
      // or 25 when base is disabled
      "maxZoom": 13,
   // defaults to true, shows +/- buttons to zoom in/out
      "zoomControl": false,
      // defaults to true, disables mouse wheel zoom
      "scrollWheelZoom": false,
      // When false, repaints on each move frame.
      // Makes the graph slower when moving the map
      "delayRepaint": true, // default true
    }
  }
}

I would be grateful if anyone could point me to an example of a doc that it relevant to the problem.
Thanks in advance.

**Comment by jheer** [comment]
LineString should project without issue. See below for an example Vega (not Vega-Lite!) spec using the `geopath` transform (`geoshape` is similar). If using Vega, the documentation for [projections](https://vega.github.io/vega/docs/projections/), [geopath](https://vega.github.io/vega/docs/transforms/geopath/), and [geoshape](https://vega.github.io/vega/docs/transforms/geoshape/) may be helpful.

I did notice a couple issues with your examples. First, `"linestring"` should be `"LineString"` to match the GeoJSON specification. Second, your spec is a Vega-Lite specification, but you are posting to the Vega repository.

- If you want Vega-Lite help I suggest you post to the shared Vega/Vega-Lite Google Group at https://groups.google.com/forum/#!forum/vega-js.
- If you want to file bug reports or other issues for Vega-Lite, please go to the Vega-Lite repository: https://github.com/vega/vega-lite.
- I also see you are using Kibana; please use an appropriate Kibana forum if you believe any issues are arising from Kibana / Vega / Vega-Lite integration. Thanks!

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "width": 950,
  "height": 500,
  "autosize": "none",
  "data": [
    {
      "name": "geo",
      "values": [
        {"geo": { "type": "LineString", "coordinates": [ [ -77.03653, 38.897676 ], [ -77.009051, 38.889939 ] ] }, "traffic_level": 5, "timestamp": 2 }
      ],
      "transform": [
        {
          "type": "geopath",
          "projection": "projection",
          "field": "geo"
        }
      ]
    }
  ],
  "projections": [
    {
      "name": "projection",
      "type": "mercator",
      "size": {"signal": "[width, height]"},
      "fit": { "type": "LineString", "coordinates": [ [ -77.1, 39.0 ], [ -77, 38.8 ] ] }
    }
  ],
  "marks": [
    {
      "type": "path",
      "from": {"data": "geo"},
      "encode": {
        "enter": {
          "stroke": {"value": "purple"},
          "strokeWidth": {"value": 5},
          "path": {"field": "path"}
        }
      }
    }
  ]
}
```

**Comment by jc92** [comment]
Dear @jheer ,
Thanks pointing me towards the relevant resources.
I adjusted your code to take data from elastic search instead of using the hard coded one for the first part called"geo".

However, I am unable to do the same when you set the fit property:
` "fit": { "type": "LineString", "coordinates": [ [ -77.1, 39.0 ], [ -77, 38.8 ] ] }`

Could you point me out how to dynamically choose the line to project onto the map please?

Thanks in advance,
