### ISSUE TITLE
Document Sphere object. Any others?

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega#1298]
I see from the [Earthquakes Example](https://vega.github.io/vega/examples/earthquakes/) that a sphere can be generated with 

```javascript
"data": [
    {
      "name": "sphere",
      "values": [ {"type": "Sphere"} ]
    }
]
```

I struggled to find any documentation that said geo spheres could be generated in this way. Have I missed something or does this need to be documented? Are there any other presets like this available?  I was also slightly surprised that such a built-in data object could be generated directly rather than as a result of a `transform` in the way graticules are constructed. Is there a reason for the difference in approach for spheres and graticules?

**Comment by jheer** [comment]
This is not a Vega feature, it is pure GeoJSON data supported by the underlying d3-geo library. From a Vega perspective this is simply inline inclusion of data.
