### ISSUE TITLE
[DOC] Indicate which Vega version added each new feature

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1299]
Users frequently have somewhat older version of Vega available to them for various reasons. When looking at the documentation, they should be able to tell if something is not (yet) available to them.  For example, the new timer event feature should have a `[4.0]` tag next to it, and a popup indicating that this feature is only available since 4.0 version.  Same goes to new features like flatten transform.

P.S. I don't think we need to do this with the features available from the start of 3.0, only what was added afterwards.

**Comment by wiibaa** [comment]
It seems this was covered by #1353 and is used quite well now.
I suppose this could be closed and if necessary an issue on the vega-lite project be opened if relevant
