### ISSUE TITLE
Question: How to use Axes Format

### ISSUE THREAD

**Issue by MatthewCarrington** [vega/vega#13]
I have adapted the basic Bar Chart example to use a date and time axis and it works OK but when I add the format option on the axes I don't get what I'd expect. Any chance you can tell me what I'm doing wrong ?

{
  "width": 400,
  "height": 200,
  "padding": {"top": 10, "left": 30, "bottom": 20, "right": 20},
  "data": [
    {
      "name": "table",
      "format": {"type": "json", "parse": {"x": "date"}},
      "values": [
	  {"x":"2013-04-04 09:43", "y":28}, 
	  {"x":"2013-04-04 09:44", "y":55}, 
	  {"x":"2013-04-04 09:45", "y":43}
       ]
    }
  ],
  "scales": [
    {
      "name":"x", 
      "type":"time", 
      "range":"width", 
      "domain":{"data":"table", "field":"data.x"}
    },
    {
      "name":"y", 
      "range":"height", 
      "nice":true, 
      "domain":{"data":"table", "field":"data.y"}
    }
  ],
  "axes": [
    {
      "type":"x", 
      "scale":"x",
      "format":"%H:%M"
    },
    {
      "type":"y", 
      "scale":"y"
    }
  ],
  "marks": [
    {
      "type": "line",
      "from": {"data":"table"},
      "properties": {
        "enter": {
          "x": {"scale":"x", "field":"data.x"},
          "y": {"scale":"y", "field":"data.y"},
          "stroke": { "value": "red" },
          "strokeWidth": {"value": 1 }
        }
      }
    }
  ]
}

Also is this the best place to ask basic usage questions or is there somewhere else ?

Matthew

**Comment by arvind** [comment]
I think this may have been fixed sometime during v1 development. Regardless, with v2, an axis' `format` property is passed to `d3.time.format` if the associated scale is a `time` scale.
