### ISSUE TITLE
render gif image

### ISSUE THREAD

**Issue by easymavinmind** [vega/vega#1303]
can we render a gif image and send it with base64 too?

**Comment by jheer** [comment]
Vega supports PNG (as provided by HTML5 Canvas) and SVG output. Vega uses browser built-in support for these features. To generate a GIF image I believe you would have to use an external 3rd party library. If using Canvas rendering, you might access the Canvas instance generated by Vega and then use it to generate a GIF (and perform Base64 encoding) using your own JavaScript code.
