### ISSUE TITLE
How to merge two arrays ? 

### ISSUE THREAD

**Issue by MD65** [vega/vega#1306]
**If I have this data-set**
 {
    "name": "names",
    "values": [
      {"id": "A", "name": "label A"},
      {"id": "B", "name": "label B"},
      {"id": "C", "name": "label C"}
    ]
  },
  {
    "name": "values",
    "values": [
      {"foo": "A", "bar": 28},
      {"foo": "B", "bar": 55},
      {"foo": "C", "bar": 43},
      {"foo": "C", "bar": 91},
      {"foo": "D", "bar": 81}
    ]
}

**How can I obtain this result  ?:** 
{ "name": "merge"
  "values": [
 {
    "name": "names",
    "values": [
      {"id": "A", "name": "label A"},
      {"id": "B", "name": "label B"},
      {"id": "C", "name": "label C"}
    ]
  }
         {
    "name": "values",
    "values": [
      {"foo": "A", "bar": 28},
      {"foo": "B", "bar": 55},
      {"foo": "C", "bar": 43},
      {"foo": "C", "bar": 91},
      {"foo": "D", "bar": 81}
    ]
}

]
}

**Comment by jheer** [comment]
This does not appear to be a Vega development or documentation issue. Please post on the Vega Google Group instead. If you do post there, I recommend including additional context -- such as why you are trying to merge these dataset definitions and what you then want to do with them -- to give others a chance to potentially suggest alternative approaches to meet your goals.
