### ISSUE TITLE
Superfluous key in treelinks examples?

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega#1309]
Some examples for creating tree visualizations that include link symbols have a `key` property defined for `treeLinks`. This appears contrary to the [documentation](https://vega.github.io/vega/docs/transforms/treelinks/) and Vega 4 schema validation.

* https://vega.github.io/vega/docs/transforms/tree.vg.json
* https://vega.github.io/vega/examples/tree-layout
* https://vega.github.io/vega/examples/radial-tree-layout

Should `key` be removed from these examples?

**Comment by jheer** [comment]
Fixed, thanks!
