### ISSUE TITLE
Fine-grained axis & grid z-ordering options

### ISSUE THREAD

**Issue by mprudhom** [vega/vega#131]
I would like to draw lines above my data marks, but underneath my text annotation marks so that the text doesn't have gridlines drawn over it. The example appended below shows a bar chart with nice white grid lines over the bars, but the text annotations of the bar values also has the grid lines draw on top, which looks bad.

The axis "layer" property values of "front" and "back" is insufficient for handling this case. One possible solution could be to have "layer" accept a z-ordering number which indicates where in the list of marks that the axis should be inserted. Or maybe the axis could take a "mark" property, which would be the name of the mark that the axis would be placed relative to. E.g., ```{ "type": "y", "scale": "y", "grid": true, "layer": "back", "mark": "my_annotations" }``` would mean that the axis is to be drawn below the mark named "my_annotations".

A simpler solution might be for the "marks" list to accept an axis object and use its position in the mark list to dictate the z-ordering of the axis, but this would be a bigger change.

```javascript
{
  "width": 400,
  "height": 200,
  "padding": {
    "top": 10,
    "left": 30,
    "bottom": 30,
    "right": 10
  },
  "scales": [
    {
      "name": "x",
      "type": "ordinal",
      "range": "width",
      "domain": {
        "data": "table",
        "field": "data.x"
      }
    },
    {
      "name": "y",
      "range": "height",
      "nice": true,
      "domain": {
        "data": "table",
        "field": "data.y"
      }
    }
  ],
  "axes": [
    {
      "type": "x",
      "scale": "x"
    },
    {
      "type": "y",
      "scale": "y",
      "grid": true,
      "layer": "front",
     "properties": {
       "grid": {
         "stroke": {"value": "#FFFFFF"},
         "strokeOpacity": {"value": 1.0},
         "strokeWidth": {"value": 1.0}
       }
     }

    }
  ],
  "marks": [
    {
      "type": "rect",
      "from": {
        "data": "table"
      },
      "properties": {
        "enter": {
          "x": {
            "scale": "x",
            "field": "data.x"
          },
          "width": {
            "scale": "x",
            "band": true,
            "offset": -1
          },
          "y": {
            "scale": "y",
            "field": "data.y"
          },
          "y2": {
            "scale": "y",
            "value": 0
          }
        },
        "update": {
          "fill": {
            "value": "steelblue"
          }
        },
        "hover": {
          "fill": {
            "value": "red"
          }
        }
      }
    },
    {
      "type": "text",
      "from": {
        "data": "table"
      },
      "properties": {
        "enter": {
          "x": {
            "scale": "x",
            "field": "data.x"
          },
          "y": {
            "scale": "y",
            "field": "data.y"
          },
          "align": {
            "value": "center"
          },
          "dx": {
            "value": 60
          },
          "fontSize": {
            "value": 30
          },
          "text": {
            "field": "data.y"
          },
          "fill": {
            "value": "black"
          }
        }
      }
    }
  ],
  "data": [
    {
      "name": "table",
      "values": [
        {
          "x": 1,
          "y": 28
        },
        {
          "x": 2,
          "y": 55
        },
        {
          "x": 3,
          "y": 43
        }
      ]
    }
  ]
}
```

**Comment by arvind** [comment]
Thanks for re-opening this discussion for Vega 2.0, Marc (uwdata/vega#82). I'm copying my answer from there for posterity, in case we choose to revisit this decision. 

> This use case can be expressed through an interleaving of group marks, one that contains the bars and another that contains the axes and text marks.

> Axes and legends go through an additional parsing stage behind the scenes, and both the markup and scene graph representations are distinct from marks. As a result, I'm not inclined to merge these three areas of the specification language.
