### ISSUE TITLE
How to get the lenght of a array  of data and the lenght of a field ? 

### ISSUE THREAD

**Issue by MD65** [vega/vega#1311]
Hello everyone ! 

How to get the lenght of a array  of data and the lenght of a field ?

**Comment by kenklin** [comment]
The **length** function returns the length of the input array https://vega.github.io/vega/docs/expressions/#array-functions

**Comment by MD65** [comment]
Thanks @kenklin  but I want concrete example please, because i have this error `Unrecognized signal name: "lenght"`

**Comment by kenklin** [comment]
FYI "lenght" above is a typo.

It may be useful if you post a small code snippet of your coding attempt.  From https://groups.google.com/forum/?fromgroups#!forum/vega-js ...
 
> For technical discussions, a link to a small, working example is far more helpful than pasting large chunks of code into email. (Small code snippets are okay.) For hosting examples, see JS Bin, JsFiddle and bl.ocks.org.
