### ISSUE TITLE
Support for GeoTIFF for contour?

### ISSUE THREAD

**Issue by mattijn** [vega/vega#1313]
I noticed some great updates in release of Vega version 4 regarding contour mapping using raster arrays. 
Will this mean that there is a slight change that GeoTIFF can be read directly from source, like in this bl.ocks from Mike Bostock: https://bl.ocks.org/mbostock/4886c227038510f1c103ce305bef6fcc?

I know that block depends on the great, but non-d3, package [geotiff.js](https://github.com/geotiffjs/geotiff.js), so maybe (probably) this is not in scope?

**Comment by jheer** [comment]
Built-in GeoTIFF support is out of scope for the core Vega library. Of course, you can use geotiff.js to separately load a file, then pass the resulting raster to Vega.

In the future, we could perhaps explore ways to make Vega extensible at runtime (much like we do for projections, color schemes, etc) with "plug-in" loaders for new file formats, but that would be a separate issue.
