### ISSUE TITLE
Don't use shorthand font property in SVG output

### ISSUE THREAD

**Issue by davidanthoff** [vega/vega#1315]
Currently the SVG output of vega uses the [shorthand font property](https://www.w3.org/TR/CSS2/fonts.html#font-shorthand). This is a feature that librsvg [doesn't support](https://gitlab.gnome.org/GNOME/librsvg/issues/34) at this point (and in fact there is a discussion in that issue that kind of seems to suggest that it might not be spec compliant, although I'm not sure about that). librsvg seems by far the best option right now to convert a SVG image into PNG, PDF, PS etc., and it seems really widely used in all sorts of software. There also doesn't seem to be any real alternative open source solution that one could use instead, so I think it would be great if vega just outputed SVG files that librsvg then can convert successfully.

The only change that would be required is really that instead of using the ``font`` property in the CSS ``style`` attribute, vega would output individual properties like ``font-style``, ``font-family`` etc.

This is currently a pretty big problem for the julia wrapper for [VegaLite.jl](https://github.com/fredo-dedup/VegaLite.jl). We use librsvg for all our output handling (saving to PNG, PDF, PS, viewing things in clients that don't support vega-lite nativly etc.), and this essentially means that right now any non-standard font configuration doesn't show properly.

CC @domoritz and @kanitw because it affects a Vega-Lite frontend.

**Comment by g3o2** [comment]
> This is a feature that librsvg doesn't support at this point

So what would prevent librsvg's developers to support this feature?

**Comment by davidanthoff** [comment]
> So what would prevent librsvg's developers to support this feature?

I guess in theory nothing, but the following all makes it unlikely in my opinion that this would be a strategy that solves this anytime soon: a) that issue has been open on their repo for 3 years, b) they seem to be in the middle of a major rewrite to port everything to rust and c) it would take a long time for any new rsvg version to be adopted in the various distributions/apps that use it.

For the julia wrapper more specifically, it was a major feat to pull of all the cross-compile of the current rsvg and make it available to all packages easily on all packages (not by me, others did that). Realistically I just don't see anyone redoing all of that with some potential future rust version anytime soon. So I think I'll just have to work with the currently shipping version of librsvg for the julia wrapper for Vega-Lite.

So yes, this is clearly asking the Vega folks to work around a bug upstream. But I think in this case that might be a good strategy because it would make the vega output work on a lot more downstream software, plus the change doesn't seem associated with any major drawbacks: yes, the SVG files would get slightly larger, but it only applies to text elements, which I would typically imagine isn't that big of a deal.

**Comment by domoritz** [comment]
This seems like a small cost both in terms of overhead and development in Vega. It may be enough to change https://github.com/vega/vega-scenegraph/blob/6c6d96ab50acc2a345dc9bbe7cd20556ec98fbc5/src/util/text.js#L84.

**Comment by davidanthoff** [comment]
And probably [here](https://github.com/vega/vega-scenegraph/blob/6c6d96ab50acc2a345dc9bbe7cd20556ec98fbc5/src/SVGRenderer.js#L374) and [here](https://github.com/vega/vega-scenegraph/blob/6c6d96ab50acc2a345dc9bbe7cd20556ec98fbc5/src/SVGStringRenderer.js#L216), right?

**Comment by domoritz** [comment]
Yes, it probably needs to return an object instead of a string.

**Comment by domoritz** [comment]
Yes, it probably needs to return an object instead of a string.

**Comment by davidanthoff** [comment]
What would be the best strategy to make this land in a shipping Vega-Lite version as soon as possible? This does end up being a pretty major bug for the julia wrapper (obviously caused by rsvg, but from a user point of view it is probably pretty irrelevant what the root cause is).

Vega v4.0.0 seems pretty close, is there still a chance to get it into that? Are there still maintenance releases planned for v3.x.x? Is the plan that Vega-Lite switches over to Vega v4.0.0 rather sooner when it is released? Any guidance would be great!

The code changes that are required look pretty harmless, but then I'm not at all familiar with the codebase, and I'm a bit worried how much time it would take to get all the build/test systems up and running for me to open a PR. Is there maybe even a chance that one of the core devs here could do a PR with this? It probably would be a lot more efficient, than me staggering around in the dark ;)

**Comment by jheer** [comment]
One reason we use a single font string is for consistent use between Canvas (which accepts only a single font string) and SVG (which accepts either). So the change points noted above are correct, but changing them directly would break Canvas rendering. 

It is frustrating to make changes based on another tool's lack of coverage of web standards, but I'm also sympathetic to the arguments advanced here! I'll take a look and see if I can find a reasonable fix.

**Comment by jheer** [comment]
I just released vega-scenegraph v3.2.0, which now uses separate style properties for each font property in the SVG renderers. @davidanthoff, would you mind taking a look (for example, by rebuilding vega or vega-lib with the latest vega-scenegraph) and let me know if this fixes your issues with librsvg? Then we can roll this into the Vega 4 release. Thanks!

**Comment by davidanthoff** [comment]
Oh wow, that was amazingly fast, thanks!!

I tried to rebuilding vega/vega-lite for a while now, but I'm stuck in getting the environment setup to build/run etc... I think I'm at a point where I should give up with this, because so far I'm not even close to build things, let alone then somehow using it from within the julia package (the julia package just installs things via npm).

Is there maybe a chance that you could compile [this](https://gist.github.com/davidanthoff/37d07b03e448a7bcf005cce0d73455f1) spec into a SVG and post that here, and then I can test whether that gets processed properly in the pipeline that follows? That is probably the minimal example where the font ends up looking incorrectly when I convert things to PNG etc. I suspect that is a thing of 2 minutes for someone who has everything set up... If not, let me know and I might have another stab at getting things to work on my end.

**Comment by jheer** [comment]
Sure, we can test that and get back to you soon.

**Comment by davidanthoff** [comment]
Great, thanks, much appreciated!

**Comment by jheer** [comment]
Here is the output SVG. It's small enough that I'll just paste it here on GitHub!

```svg
<svg class="marks" width="210" height="66" viewBox="0 0 210 66" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g transform="translate(5,40)"><g class="mark-group role-frame root"><g transform="translate(0,0)"><path class="background" d="M0.5,0.5h200v21h-200Z" style="fill: none; stroke: #ddd;"></path><g><g class="mark-symbol role-mark marks"></g><g class="mark-text role-title" style="pointer-events: none;"><text text-anchor="middle" transform="translate(100,-10)" style="font-family: sans-serif; font-size: 30px; font-weight: bold; fill: blue; opacity: 1;">Foo</text></g></g></g></g></g></svg>
```

**Comment by davidanthoff** [comment]
I just passed that SVG through our rsvg->cairo->png pipeline, and it all looks correct, so this works! Thanks so much for sorting this out so quickly!

**Comment by jheer** [comment]
Great. I'm closing out the issue. The updated SVG output will be included in the next Vega release!
