### ISSUE TITLE
label based slicer to select nested object

### ISSUE THREAD

**Issue by mattijn** [vega/vega#1316]
It would be nice to make a label based slice to select a nested object. I can use the existing `project` transform as such:
```
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "data": [
    {
      "name": "source",
      "values": [
        {"foo": {"a": 5, "b": "string_0"}, "bah": 0},
        {"foo": {"a": 6, "b": "string_1"}, "bah": 1},
        {"foo": {"a": 7, "b": "string_2"}, "bah": 2}
      ],
      "transform": [{"type": "project", "fields": ["foo"]}]
    }
  ]
}
```
but this still returns a nested object:
```
[{foo: {a: 5, b: "string_0"}}, 
 {foo: {a: 6, b: "string_1"}}, 
 {foo: {a: 7, b: "string_2"}}]
```

Where I  was hoping for:
```
[{a: 5, b: "string_0"},
 {a: 6, b: "string_1"},
 {a: 7, b: "string_2"}]
```

Maybe in the `project` transform the `as` can accept `null` value to make this possible?
`"transform": [{"type": "project", "fields": ["foo"], "as": null}]`

Or, completely different, as a real slicer under the data `format`:
`"format": {"type": "json", "property": "[:,'foo']"}`

**Comment by silvestrelosada** [comment]
+1 I think this feature is really needed, mosto of systems return data using nested objects (ie elasticsearch aggregations) And you cannot select nested objects to visualize them. This is new feature request that will be very usefull

**Comment by jheer** [comment]
I certainly understand the desire for convenience here, but also want to point out that you can already accomplish un-nesting of semi-structured data with the existing Vega transforms.

For example, in the example provided above, you can simply provide explicit nested field names to the `project` transform:

```
"transform": [{"type": "project", "fields": ["foo.a", "foo.b"], "as": ["a", "b"}]
```

While the above example is slightly more verbose, it doesn't add a disproportional costs: if you are going to project them, I assume you already have to reference these fields by name elsewhere in your specification in order to visualize them. I've updated the [`project`](https://vega.github.io/vega/docs/transforms/project/) transform documentation to include an example of this form.

Also, in addition to `project`, the [`flatten`](https://vega.github.io/vega/docs/transforms/flatten/) transform can be used to help deal with arrays of objects contained within nested JSON input.

Nevertheless, the idea of a slicer syntax -- either under the data `format` property or as a new transform -- is interesting. While not currently on our high-priority list of features, feel free to share suggestions for the design of an appropriate query syntax.

**Comment by silvestrelosada** [comment]
I have another example that come from elasticsearch
 [
        {"foo": [{"a": 5, "b": "string_0"},{"a": 5, "b": "string_2"},{"a": 5, "b": "string_2"}], "bah": 0},
        {"foo": [{"a": 6, "b": "string_1"}{"a": 6, "b": "string_2"},{"a": 6, "b": "string_2"}], "bah": 1},
        {"foo": [{"a": 7, "b": "string_1"}{"a": 7, "b": "string_2"},{"a": 7, "b": "string_2"}], "bah": 2}
      ]

The ouput should be

 [{"a": 5, "b": "string_0"},
{"a": 5, "b": "string_2"},
{"a": 5, "b": "string_2"},
{"a": 6, "b": "string_1"},
{"a": 6, "b": "string_2"},
{"a": 6, "b": "string_2"}, 
{"a": 7, "b": "string_1"},
{"a": 7, "b": "string_2"},
{"a": 7, "b": "string_2"}]

if ne nested value is an array or an object containing other objects I think project wont work.

Best

**Comment by jheer** [comment]
As I noted in my previous reply, you can use the `flatten` transform to handle array-valued data. Here is a complete example -- based on your data above -- that uses `flatten` and `project` together to map semi-structured data to a flat table structure.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "data": [
    {
      "name": "data",
      "values": [
        {"foo": [{"a": 5, "b": "string_0"},{"a": 5, "b": "string_2"},{"a": 5, "b": "string_2"}], "bah": 0},
        {"foo": [{"a": 6, "b": "string_1"},{"a": 6, "b": "string_2"},{"a": 6, "b": "string_2"}], "bah": 1},
        {"foo": [{"a": 7, "b": "string_1"},{"a": 7, "b": "string_2"},{"a": 7, "b": "string_2"}], "bah": 2}
      ],
      "transform": [
        {
          "type": "flatten",
          "fields": ["foo"],
          "as": ["foo"]
        },
        {
          "type": "project",
          "fields": ["bah", "foo.a", "foo.b"],
          "as": ["bah", "a", "b"]
        }
      ]
    }
  ]
}
```

**Comment by silvestrelosada** [comment]
Thanks!!

**Comment by jheer** [comment]
I'm closing out this issue for now, as the needed functionality is already provided. If someone would like to propose a more complete design for alternative un-nesting procedures, please feel free to share them in a new feature request issue.

**Comment by mattijn** [comment]
I'm sorry for still commenting on this issue. I did not had the time yet to work out an real use-case example/proces for which I opened this issue.

So assuming we want to make a bar chart using using three variables (`country`, `population` and `registered road vehicles per 1000 inhabitants`):
<img width="638" alt="complicated_chart" src="https://user-images.githubusercontent.com/5186265/41372908-f364e402-6f4e-11e8-9caa-2125273b6df8.png">

And we've prepared our data in a `pandas` `DataFrame` within `python` (eventually all of this should be possible through `altair`/`vega-lite`). 
This `DataFrame` then looks as follow:
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>country</th>
      <th>gdp</th>
      <th>population</th>
      <th>reg_veh_per_1000_inh</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Belgium</td>
      <td>389300.0</td>
      <td>10414336.0</td>
      <td>678</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Luxembourg</td>
      <td>39370.0</td>
      <td>491775.0</td>
      <td>508</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Netherlands</td>
      <td>672000.0</td>
      <td>16715999.0</td>
      <td>477</td>
    </tr>
  </tbody>
</table>

which is converted to `row-oriented JSON` for usage within `vega`: 
```
[  
   {  
      "country":"Belgium",
      "gdp":389300,
      "population":10414336,
      "reg_veh_per_1000_inh":508
   },
   {  
      "country":"Luxembourg",
      "gdp":39370,
      "population":491775,
      "reg_veh_per_1000_inh":678
   },
   {  
      "country":"Netherlands",
      "gdp":672000,
      "population":16715999,
      "reg_veh_per_1000_inh":477
   }
]
```
Where part of my generated `vega` [specification](https://vega.github.io/editor/#/gist/vega/mattijn/8a56f17b1609ad74c4f49d7132de0a58/4c7901bae38780dd62802b48b2ea1ef770ac37d2/json_barchart.json) includes the following:
```
...
"encode": {
  "enter": {
    "x": {
      "scale": "xscale",
      "field": "country"
    },
    "y": {
      "scale": "yscale",
      "field": "population"
    },   
    "fill": {
      "scale": "color",
      "field": "reg_veh_per_1000_inh"
    },
...
```

but in `pandas` the same `DataFrame` might also contain a `geometry` column:
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>country</th>
      <th>gdp</th>
      <th>population</th>
      <th>reg_veh_per_1000_inh</th>
      <th>geometry</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Belgium</td>
      <td>389300.0</td>
      <td>10414336.0</td>
      <td>678</td>
      <td>POLYGON ((3.3 51.3, 4 51.3, 5 51.5, 5.6 51, 6....</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Luxembourg</td>
      <td>39370.0</td>
      <td>491775.0</td>
      <td>508</td>
      <td>POLYGON ((6 50.1, 6.2 49.9, 6.2 49.5, 5.9 49.4...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Netherlands</td>
      <td>672000.0</td>
      <td>16715999.0</td>
      <td>477</td>
      <td>POLYGON ((6.1 53.5, 6.9 53.5, 7.1 53.1, 6.8 52...</td>
    </tr>
  </tbody>
</table>

In this case the (`Geo`)`DataFrame` will be using the geospatial data format `GeoJSON` as interchange data format for usage in `vega`, which in this case looks as follow:
```
{  
    "type":"FeatureCollection",
    "crs":{  
       "type":"name",
       "properties":{  
          "name":"urn:ogc:def:crs:OGC:1.3:CRS84"
       }
    },
    "features":[  
       { "type": "Feature", "properties": { "country": "Belgium", "gdp": 389300.0, "population": 10414336.0, "reg_veh_per_1000_inh": 508 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 3.3, 51.3 ], [ 4.0, 51.3 ], [ 5.0, 51.5 ], [ 5.6, 51.0 ], [ 6.2, 50.8 ], [ 6.0, 50.1 ], [ 5.8, 50.1 ], [ 5.7, 49.5 ], [ 4.8, 50.0 ], [ 4.3, 49.9 ], [ 3.6, 50.4 ], [ 3.1, 50.8 ], [ 2.7, 50.8 ], [ 2.5, 51.1 ], [ 3.3, 51.3 ] ] ] } },
       { "type": "Feature", "properties": { "country": "Luxembourg", "gdp": 39370.0, "population": 491775.0, "reg_veh_per_1000_inh": 678 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 6.0, 50.1 ], [ 6.2, 49.9 ], [ 6.2, 49.5 ], [ 5.9, 49.4 ], [ 5.7, 49.5 ], [ 5.8, 50.1 ], [ 6.0, 50.1 ] ] ] } },
       { "type": "Feature", "properties": { "country": "Netherlands", "gdp": 672000.0, "population": 16715999.0, "reg_veh_per_1000_inh": 477 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 6.1, 53.5 ], [ 6.9, 53.5 ], [ 7.1, 53.1 ], [ 6.8, 52.2 ], [ 6.6, 51.9 ], [ 6.0, 51.9 ], [ 6.2, 50.8 ], [ 5.6, 51.0 ], [ 5.0, 51.5 ], [ 4.0, 51.3 ], [ 3.3, 51.3 ], [ 3.8, 51.6 ], [ 4.7, 53.1 ], [ 6.1, 53.5 ] ] ] } }
    ]
 }
```
and you feel it coming.. now to create the same chart, parts of my `vega` [specification](https://vega.github.io/editor/#/gist/vega/mattijn/7b183145044ffef9df56f74207dd1438/ab5f2e36718d934bba71e7c0afa6434112b1b369/geojson_barchart.json) has to be defined as follow:
```
...
"encode": {
  "enter": {
    "x": {
      "scale": "xscale",
      "field": "properties.country"
    },
    "y": {
      "scale": "yscale",
      "field": "properties.population"
    },
    "fill": {
      "scale": "color",
      "field": "properties.reg_veh_per_1000_inh"
    }
...
```
if `"format": {"type": "json", "property": "features"}` is set in the `data` property.

Without knowing the underlying difference between `row-oriented JSON` and `GeoJSON` this is very confusing. Especially if there was NO usage of the `geoshape` capabilities in `Vega`/`Vega-lite`. 

@iliatimofeev came up with an interesting idea in https://github.com/altair-viz/altair/pull/818 to register the values of the member `"properties"` in the `Feature object` as top-level [`Foreign Members`](https://tools.ietf.org/html/rfc7946#section-6.1), so the array of `features` in the `GeoJSON` example becomes as follow:
```
[
      {
        "country": "Belgium",
        "gdp": 389300,
        "population": 10414336,
        "reg_veh_per_1000_inh": 508,
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [ [ [3.3, 51.3], [4, 51.3], [5, 51.5], [5.6, 51], [6.2, 50.8], [6, 50.1], [5.8, 50.1], [5.7, 49.5], [4.8, 50], [4.3, 49.9], [3.6, 50.4], [3.1, 50.8], [2.7, 50.8], [2.5, 51.1], [3.3, 51.3] ] ]
        }
      },
      {
        "country": "Luxembourg",
        "gdp": 39370,
        "population": 491775,
        "reg_veh_per_1000_inh": 678,
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [ [ [6, 50.1], [6.2, 49.9], [6.2, 49.5], [5.9, 49.4], [5.7, 49.5], [5.8, 50.1], [6, 50.1] ] ]
        }
      },
      {
        "country": "Netherlands",
        "gdp": 672000,
        "population": 16715999,
        "reg_veh_per_1000_inh": 477,
        "type": "Feature",
        "geometry": {
          "type": "Polygon",
          "coordinates": [ [ [6.1, 53.5], [6.9, 53.5], [7.1, 53.1], [6.8, 52.2], [6.6, 51.9], [6, 51.9], [6.2, 50.8], [5.6, 51], [4, 51.3], [3.3, 51.3], [3.8, 51.6], [4.7, 53.1], [6.1, 53.5] ] ]
        }
      }
]
```
While I think this is a great (mis?)usage of `GeoJSON`, I still hope we can use conventional `GeoJSON` as a data interchange format and somehow get this data `transform` within `Vega` and `Vega-lite`.

I didn't knew we could use nested field names in the `project` `transform` so given _standard_ `GeoJSON` as input data we can register the object values within the `"properties"` member as `"foreign"` member as such:
```
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "width": 400,
  "height": 200,
  "padding": 5,
  "data": [
    {
      "name": "table",
      "values": {  
        "type":"FeatureCollection",
        "crs":{  
          "type":"name",
          "properties":{  
              "name":"urn:ogc:def:crs:OGC:1.3:CRS84"
          }
        },
        "features":[  
          { "type": "Feature", "properties": { "country": "Belgium", "gdp": 389300.0, "population": 10414336.0, "reg_veh_per_1000_inh": 508 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 3.3, 51.3 ], [ 4.0, 51.3 ], [ 5.0, 51.5 ], [ 5.6, 51.0 ], [ 6.2, 50.8 ], [ 6.0, 50.1 ], [ 5.8, 50.1 ], [ 5.7, 49.5 ], [ 4.8, 50.0 ], [ 4.3, 49.9 ], [ 3.6, 50.4 ], [ 3.1, 50.8 ], [ 2.7, 50.8 ], [ 2.5, 51.1 ], [ 3.3, 51.3 ] ] ] } },
          { "type": "Feature", "properties": { "country": "Luxembourg", "gdp": 39370.0, "population": 491775.0, "reg_veh_per_1000_inh": 678 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 6.0, 50.1 ], [ 6.2, 49.9 ], [ 6.2, 49.5 ], [ 5.9, 49.4 ], [ 5.7, 49.5 ], [ 5.8, 50.1 ], [ 6.0, 50.1 ] ] ] } },
          { "type": "Feature", "properties": { "country": "Netherlands", "gdp": 672000.0, "population": 16715999.0, "reg_veh_per_1000_inh": 477 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 6.1, 53.5 ], [ 6.9, 53.5 ], [ 7.1, 53.1 ], [ 6.8, 52.2 ], [ 6.6, 51.9 ], [ 6.0, 51.9 ], [ 6.2, 50.8 ], [ 5.6, 51.0 ], [ 5.0, 51.5 ], [ 4.0, 51.3 ], [ 3.3, 51.3 ], [ 3.8, 51.6 ], [ 4.7, 53.1 ], [ 6.1, 53.5 ] ] ] } }]
      },
      "format": {"type": "json", "property": "features"},
      "transform": [
        {
          "type": "project",
          "fields": ["properties.country", "properties.gdp", "properties.population", "properties.reg_veh_per_1000_inh", "type", "geometry"],
          "as": ["country", "gdp", "population", "type", "geometry"]
        }
      ]         
    }
  ]
}
```
While this works in `Vega` (awesome btw), will it require from the user that she knows upfront all nested field-names (those being used and not being used) within `"properties"` and project these  + `type` and `geometry`. 

To conclude, I've become slightly off-topic, but I wish that a certain `format` or `transform` exist that can do this automagically given `GeoJSON` as input data. Maybe just with `"format": {"type": "geojson"}` as this specific type of `project` `transform` only applies to `GeoJSON` structured `JSON`.
