### ISSUE TITLE
Fit to container

### ISSUE THREAD

**Issue by andrewbanchich** [vega/vega#1317]
Maybe it's because I'm new to Vega, but I'm having a lot of trouble figuring out how to do this. I'm using the Node `vega-lib` module and the View API.

All I'd like to do is to set the height and width of the SVG to `100%` and allow Vega to dictate the aspect ratio via the `viewBox` attribute.

Is this possible?

**Comment by domoritz** [comment]
Vega sets the `viewBox` attribute so you can resize your SVG and keep the aspect ratio. To set the size of the chart, have a look at the width and height (as well as padding) attributes in https://vega.github.io/vega/docs/specification/. 

We usually use the issue tracker for bugs and feature requests. For questions, please use the mailing list or [slack](http://bit.ly/vega-slack).
