### ISSUE TITLE
continuously vary the color of a line/trail

### ISSUE THREAD

**Issue by Alcampopiano** [vega/vega#1326]
Hello,

I'm tying to encode the color of a line to a continuous variable. I thought that I could use the trail mark and specify color, but this doesn't work (only size does). So I can change the entire line/trail to a specific color, but I cannot seem to have the color change as a function of say the y axis for example.

Here is an example of what I'm looking for:
![line](https://user-images.githubusercontent.com/4624246/41515956-14a0b252-7280-11e8-9735-5c6efeadb1dd.png)

Is there a way to do this?

Sincerely,
Al

**Comment by jheer** [comment]
(This issue duplicates #1187.)

Line, area, and trail marks are drawn as a single shape, which limits them to a single fill color. Varying colors can be achieved using a [gradient fill](https://vega.github.io/vega/docs/expressions/#gradient), though you are limited to linear gradients (varying along x/y, but not, for example, by arc length).

Here is a basic example using a rect mark:

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 300,
  "height": 100,
  "scales": [
    {
      "name": "color",
      "type": "sequential",
      "range": {"scheme": "viridis"}
    }
  ],
  "marks": [
    {
      "type": "rect",
      "encode": {
        "enter": {
          "width": {"signal": "width"},
          "height": {"signal": "height"},
          "fill": {"signal": "gradient('color', [0,0], [1,0])"}
        }
      }
    }
  ]
}
```

**Comment by Alcampopiano** [comment]
Thanks for the example, but yes, I was looking to be able to use any arbitrary set of values to specify the color a mark, such as a line or trail. I guess conceptually since the trail can vary in size (despite being a single shape as you mentioned), it perhaps could also be allowed to vary in other ways as well. I would imagine that varying the size of a mark is equally as common a thing to do as varying the color, and both seem to fit within the grammar of graphics philosophy. Of course there may be practical issues that make this difficult.

Thanks again for the response. Vega is amazing.

Allan

**Comment by jheer** [comment]
Yes, I completely agree that your suggestion fits within a grammar of graphics philosophy. Unfortunately, the underlying rendering technologies (Canvas, SVG) make this more difficult and/or inefficient than we would like. Thanks for raising the issue!

**Comment by Alcampopiano** [comment]
My pleasure. You guys are doing very important work.

Al

**Comment by pratapvardhan** [comment]
This is helpful to create linearGradient on `sequential` scale. 

Would it possible to make this work with `threshold` scale or alike to construct a `linearGradient` like below?

```
<linearGradient id="gradient_596" x1="0" x2="0" y1="0" y2="1">
    <stop offset="0" stop-color="red"></stop>
    <stop offset="0.7" stop-color="red"></stop>
    <stop offset="0.7" stop-color="green"></stop>
    <stop offset="1" stop-color="green"></stop>
</linearGradient>
```

It appears, `gradient` function doesn't accept scales other than `sequential`.
