### ISSUE TITLE
First-class API for inspecting runtime scales

### ISSUE THREAD

**Issue by ericsoco** [vega/vega#1330]
I'm finding more and more use cases for inspecting the runtime after parsing a spec, including:
- pulling the derived domains of scales generated from spec
- retrieving keys from ordinal scales

Data inspection has an API, via [`View.data()`](https://vega.github.io/vega/docs/api/view/#data).
[Signal inspection](https://vega.github.io/vega/docs/api/view/#signals) does as well, but scale inspection does not. Would be nice to avoid `view._runtime` calls.

**Comment by jheer** [comment]
Added in vega-view v3.3.0. Will be included in Vega 4.0.0.

**Comment by domoritz** [comment]
This will be useful for making requests based on the current view as well.

cc @saba9
