### ISSUE TITLE
Add Token and params to request url

### ISSUE THREAD

**Issue by darge98** [vega/vega#1335]
Hi,

I want to know if it's possible add a Token Bearer and Params when chart do the request.

Thanks.

**Comment by jheer** [comment]
As of Vega 4.0.0-rc.1 and later, we use the web standard `fetch` API to request URLs. You can create your own [vega Loader](https://github.com/vega/vega-loader) instance and pass it as an option to the Vega View constructor. The loader `options.http` property provides the parameters to pass to `fetch`.

See the [vega-loader documentation](https://github.com/vega/vega-loader) for more.

**Comment by domoritz** [comment]
You can also pass the loader or loader options to Vega embed if you use that.

**Comment by darge98** [comment]
There's an example of how use it? Thanks

**Comment by domoritz** [comment]
For example, to change the baseURL of the loader:

```json
embed('#vis', spec, {loader: {baseURL: 'https://vega.github.io/vega-datasets/'}})
```

More details are at https://github.com/vega/vega-embed

**Comment by darge98** [comment]
Thanks for the response, I don't use the embedded, I use the view, i have a config file with this property:
`"data": [
    {
      "name": "table",
      "url": myUrl
    }`

I want add an header and options to this url. I can't do this

**Comment by domoritz** [comment]
This cannot be done in the Vega spec itself. You need to change the loader as @jheer mentioned in https://github.com/vega/vega/issues/1335#issuecomment-399279334.

**Comment by darge98** [comment]
So, it's correct something like this? 

`vega.loader({
            http: {
                headers: myHeaders
            }
        })
            .load('config/vegaPieChart.json')
            .then(function (data) {
                render(JSON.parse(data));
            });`

`function render(spec) {
            view = new vega.View(vega.parse(spec))
                .renderer('canvas')  // set renderer (canvas or svg)
                .initialize('#view') // initialize view within parent DOM container
                .hover()             // enable hover encode set processing
                .run();
        }`

**Comment by jheer** [comment]
Your snippet will use a loader with custom headers to load your Vega JSON spec file. If you want those headers to also be applied when loading data or images referenced by your Vega spec, you need to also pass the customized loader as one of the View constructor options:

```js
var loader = vega.loader({ http: { headers: myHeaders } }),
    view;

loader.load('config/vegaPieChart.json')
  .then(function(data) { render(JSON.parse(data)); });

function render(spec) {
  view = new vega.View(vega.parse(spec), {loader: loader})
    .renderer('canvas')
    .initialize('#view')
    .hover()
    .run();
}

**Comment by domoritz** [comment]
Or with Vega Embed

```
embed('#view', 'config/vegaPieChart.json', {loader: { http: { headers: myHeaders } }});
```

**Comment by darge98** [comment]
Ok thanks, that is what i need. It's also possible add query string params with the loader?

**Comment by jheer** [comment]
You can't add query string params through the loader options, but if you create your own version of the `sanitize` method and override the default you could modify an input url as you see fit.
