### ISSUE TITLE
Selectable text inside vega view

### ISSUE THREAD

**Issue by jlasserre** [vega/vega#1338]
I am often faced with the problem of wanting to provide a way for users to copy-paste a text label displayed in vega visualisations but have yet to come up with a proper solution.

It can be done by updating an element on the web page when said item is clicked but that's generally not very user friendly and does require a large amount of work for such a small return.

Would it be possible to make it so that text displayed in vega visualisations could be selected and copy-pasted ? This should apply to marks, legend labels, axis labels, titles etc...

Thanks a lot :)

**Comment by domoritz** [comment]
If you use the svg renderer, you can copy and paste text. It won't work with the canvas renderer.

**Comment by jheer** [comment]
@domoritz is exactly right. If you need to support text selection, use the SVG renderer, which then leverages the browser's built-in facilities for text selection, copying to clipboard, etc. Recreating this functionality in Canvas would be expensive and difficult to get exactly right; as a result we don't plan to add such features at this time.
