### ISSUE TITLE
Position titles left aligned with the data

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1346]
This doesn't seem to be possible with the title directive in Vega. 

<img width="693" alt="screen shot 2018-06-27 at 22 55 18" src="https://user-images.githubusercontent.com/589034/42015688-31a81be4-7a5d-11e8-8265-7bf1a3684f55.png">

**Comment by jheer** [comment]
Sure it is: use `”frame”: “group”`

**Comment by domoritz** [comment]
Oh, I missed that. It was also missing from the Vega-Typings but I fixed that.
