### ISSUE TITLE
Unlisted domain items no longer generate proper values

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1357]
Reported to Kibana at https://github.com/elastic/kibana/issues/20183.  In the older Vega versions, this graph produced first image, but in the later versions domain handling has changed, produces second image.  Was this breaking change intentional, or is this a regression? Thx!

| older version | current version |
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/1641515/42611150-bf1b3e42-8562-11e8-944f-0ab1bd134c48.png) | ![image](https://user-images.githubusercontent.com/1641515/42611159-cd9cf6d6-8562-11e8-8150-9587c9d338eb.png) |

In this graph, the color scale's domain was incorrectly defined to not include all values -- `"domain": {"data": "srcdata", "field": "stk1"}` -- instead of `"fields": ["stk1", "stk2"]`, but as always the expectation is that current graphs would continue working as before, despite the upgrade.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "autosize": {"type": "pad", "contains": "padding"},
  "width": 600,
  "height": 600,
  "data": [
    {
      "name": "srcdata",
      "values": [
        {"stk1": "IT", "stk2": "MX", "xx": 1},
        {"stk1": "MA", "stk2": "CN", "xx": 2},
        {"stk1": "US", "stk2": "CN", "xx": 3}
      ]
    }
  ],
  "scales": [
    {
      "name": "color",
      "type": "ordinal",
      "range": {"scheme": "category10"},
      "domain": {"data": "srcdata", "field": "stk1"}
    }
  ],
  "marks": [
    {
      "type": "rect",
      "from": {"data": "srcdata"},
      "encode": {
        "enter": {
          "fill": {"scale": "color", "field": "stk1"},
          "width": {"value": 50},
          "height": {"value": 50},
          "x": {"field": "xx", "mult": 50},
          "y": {"value": 50}
        }
      }
    },
    {
      "type": "rect",
      "from": {"data": "srcdata"},
      "encode": {
        "enter": {
          "fill": {"scale": "color", "field": "stk2"},
          "width": {"value": 50},
          "height": {"value": 50},
          "x": {"field": "xx", "mult": 50},
          "y": {"value": 150}
        }
      }
    }
  ]
}
```

**Comment by jheer** [comment]
This is intentional, as it fixes buggy behaviors. The change is to disable implicit domain extension when an explicit domain is provided. This was discussed in a [GitHub issue](https://github.com/vega/vega/issues/1166), and noted in the [change log for v3.2.0](https://github.com/vega/vega/releases/tag/v3.2.0).

To restore the old (generally unsafe!) behavior, one may add `"domainImplicit": true` to the color scale definition. The `domainImplicit` parameter was added in [v4.0.0](https://github.com/vega/vega/releases/tag/v4.0.0).

**Comment by nyurik** [comment]
@jheer thx for the explanation! Hopefully there are not too many users who were affected by this. I agree that it is better not to have an implicit values, but I really wish we didn't break working graphs like this, especially in a minor version release.
