### ISSUE TITLE
geoshape transform requires `datum` for the field

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1359]
It seems that the `field` parameter for the `geoshape` transform always requires `"datum.fieldname"` instead of just `"fieldname"`. Is this by design, and if so, how should this be documented?

**Comment by jheer** [comment]
That should depend on where you use `geoshape`. If you use it a normal data transform pipeline, `fieldname` will suffice. However, if you use it as a post-encoding transform, the scenegraph items are the data objects and `datum.fieldname` references the field on the datum backing the scenegraph item. This is a standard Vega convention across transforms that can be used post-encoding.

**Comment by nyurik** [comment]
@jheer thx, I will add some documentation about this -- I figure that if someone like me who has worked with Vega for many years doesn't know this, others will need the same help.  I am thinking of a common template (with a very short paragraph of text) that we can add to every such transformation. How abou this text:
> This transformation can also be used as a post-encoding transform inside the mark's `transform` block. When used in this way, the datum-related fields must be accessed as `datum.my_field`,  instead of `my_field`.

**Comment by nyurik** [comment]
@jheer is there a list of transforms that can (or cannot) be used in marks?

**Comment by jheer** [comment]
Yes, it is included in the vega-schema (excerpt below). Any transform that does not generate new tuples or adds/removes tuples from a stream can be used: this is determined by checking the transform definition `metadata` flags `generates` and `changes`.

For reference:
- The schema for valid post-encoding transforms is defined here: https://github.com/vega/vega-parser/blob/master/schema/transform.js#L153
- The parser raises an error if an invalid transform is included in a mark here: https://github.com/vega/vega-parser/blob/master/src/parsers/mark.js#L68

```json
  "transformMark": {
      "oneOf": [
        {
          "$ref": "#/defs/binTransform"
        },
        {
          "$ref": "#/defs/collectTransform"
        },
        {
          "$ref": "#/defs/extentTransform"
        },
        {
          "$ref": "#/defs/formulaTransform"
        },
        {
          "$ref": "#/defs/joinaggregateTransform"
        },
        {
          "$ref": "#/defs/lookupTransform"
        },
        {
          "$ref": "#/defs/sampleTransform"
        },
        {
          "$ref": "#/defs/windowTransform"
        },
        {
          "$ref": "#/defs/identifierTransform"
        },
        {
          "$ref": "#/defs/linkpathTransform"
        },
        {
          "$ref": "#/defs/pieTransform"
        },
        {
          "$ref": "#/defs/stackTransform"
        },
        {
          "$ref": "#/defs/geojsonTransform"
        },
        {
          "$ref": "#/defs/geopathTransform"
        },
        {
          "$ref": "#/defs/geopointTransform"
        },
        {
          "$ref": "#/defs/geoshapeTransform"
        },
        {
          "$ref": "#/defs/forceTransform"
        },
        {
          "$ref": "#/defs/packTransform"
        },
        {
          "$ref": "#/defs/partitionTransform"
        },
        {
          "$ref": "#/defs/stratifyTransform"
        },
        {
          "$ref": "#/defs/treeTransform"
        },
        {
          "$ref": "#/defs/treemapTransform"
        },
        {
          "$ref": "#/defs/voronoiTransform"
        },
        {
          "$ref": "#/defs/wordcloudTransform"
        },
        {
          "$ref": "#/defs/crossfilterTransform"
        },
        {
          "$ref": "#/defs/resolvefilterTransform"
        }
      ]
```
