### ISSUE TITLE
Create vega json schema

### ISSUE THREAD

**Issue by dnmiller** [vega/vega#136]
It would be nice for vega to have a json schema (http://json-schema.org/) so that third-party tools could more easily keep up with any changes.

I could take a shot at this over the weekend, but I wanted some feedback first.

**Comment by arvind** [comment]
Vega 2.0 now provides a JSON schema. It can be compiled by running `npm run schema`. A pre-built version will be available at [http://vega.github.io/vega/vega-schema.json](http://vega.github.io/vega/vega-schema.json) on release.
