### ISSUE TITLE
Title directive doesn't have align

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1362]
I guess that this was intentionally as we could use `anchor` for most cases. 

However, when we use `angle` to rotate the title like the `row_header` in this example: https://pastebin.com/HRTPcaY4. 

We have to manually set the title align via `encode` block.  (`anchor` is no longer sufficient.)

**Comment by jheer** [comment]
Sounds reasonable to me. I will interpret this issue as a request for an `align` parameter that, if provided, will override the automatic settings generated for the current `anchor` value.

**Comment by jheer** [comment]
Added in vega-parser@3.7.0.
