### ISSUE TITLE
Question: Accessing original data in legend

### ISSUE THREAD

**Issue by Eveliyse** [vega/vega#1363]
I have data of the form:
```
{alphaID: 'A', category: 'Apple', count: 1},
{alphaID: 'B', category: 'Banana, count: 1},
{alphaID: 'C', category: 'Cantaloupe', count: 1},
```
I've made a bar chart where the `band` scale uses the `alphaID` field and the `linear` scale uses the `count` field. I then have a legend where I would like to display the labels as `{alphaID} - {category}`. I'm trying to do this by using the `labels` `encode` to overwrite the text but I don't have access to the original datum.
___

What would be the best way to access the original data backing the legend? I notice the documentation says:

> Each legend symbol and label instance is backed by a data object with the following fields, which may be accessed as part of a custom visual encoding rule:
> 
>     index - an integer index
>     label - the string label
>     value - the data value
>     size - the symbol size (for symbol legends only)

I thought at first `value` would be the original data but after some poking I've come to the conclusion that `value` is just the raw input for `label` (please correct me if I'm wrong!)

**Comment by jheer** [comment]
Yes, the `value` field in generated legend entries is just the raw value (for either `alphaID` or `category`, whichever is driving the scale domain for the legend). It does not generally make sense to link to data objects here as a legend entry might represent any number of backing data points.

One option is to generate a new field for your original data, using the `formula` transform to perform the string concatenation. Then create a scale (possibly redundant) and legend based on that field.
