### ISSUE TITLE
Short gradient legends have only one label

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1364]
<img width="120" alt="screen shot 2018-07-14 at 22 40 16" src="https://user-images.githubusercontent.com/589034/42730918-647d8e16-87b7-11e8-8f5f-76e23d7186f9.png">

The issue is that labels are only placed in the middle of the legend and not the ends. I wonder whether the default should be changed (I remember filing an issue about this but can't find it right now). 

Related: https://github.com/vega/vega-lite/issues/3853

**Comment by jheer** [comment]
I do not see a link to a reproduction at vega/vega-lite#3853. Please include a spec that reproduces the issue if you want me to look into this.

**Comment by jheer** [comment]
The legend label logic in vega-encode is proceeding as follows:

1. The LegendEntries operator is not given specific label values, so invokes `labelValues`. The `count` parameter is set to `2`, based on a calculation involving the legend width. (The `count` signal expression is in [vega-parser](https://github.com/vega/vega-parser/blob/master/src/parsers/legend.js#L70)).
2. The `labelValues` method then invokes `tickValues` for the sequential scale.
3. The `tickValues` method then invokes `scale.ticks(count)` on the d3 sequential scale with `count` set to `2`, producing the resulting ticks. This attempts to do nicing for the labels. If the value range is itself not nice, this can result in fewer labels than desired.

Some options on the Vega-Lite end include:
- Use nice for all scales, including color. I don't think this is necessarily a good idea however, as users may not want their color scales padded. In any case, users should have a way of disabling this if it is the default, in which case the problem recurs.
- Set the `values` explicitly to be the scale domain. This will ensure the domain endpoints are included, but will not take advantage of extra resolution when the length increases.
- Set the `count` explicitly. Similar problem as above.

Given the issue above, I'm leaning towards a different fix inside Vega:
- For continuous gradients only: if the `values` are not explicitly set and the `labelValues` function only returns one label, ignore that output and use the domain end points instead.

Let me know if you have any thoughts on the notes above!

**Comment by domoritz** [comment]
Thank you for the explanation! 

I've tried to enable nice for all quantitative scales in Vega-Lite but the scales are generally getting worse. See https://github.com/vega/vega-lite/pull/4033/files. I think the best option is to fix this in Vega.

**Comment by jheer** [comment]
Fixed in vega-encode@3.1.4. For continuous gradients, now if no explicit `values` are provided and 2 or fewer labels are generated Vega will use the domain end points (so long as there is a non-zero domain span).
