### ISSUE TITLE
Setting `fill` to "none" does not work when using with condition

### ISSUE THREAD

**Issue by chanwutk** [vega/vega#1367]
This is the testing spec:
```
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "width": 400,
  "height": 200,
  "padding": 5,
  "data": [
    {
      "name": "table",
      "values": [
        {"category": "A", "amount": 28},
        {"category": "B", "amount": 55},
        {"category": "C", "amount": 43}
      ]
    }
  ],
  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "domain": {"data": "table", "field": "category"},
      "range": "width",
      "padding": 0.05,
      "round": true
    },
    {
      "name": "yscale",
      "domain": {"data": "table", "field": "amount"},
      "nice": true,
      "range": "height"
    }
  ],
  "axes": [
    {"orient": "bottom", "scale": "xscale"},
    {"orient": "left", "scale": "yscale"}
  ],
  "marks": [
    {
      "type": "rect",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "category"},
          "width": {"scale": "xscale", "band": 1},
          "y": {"scale": "yscale", "field": "amount"},
          "y2": {"scale": "yscale", "value": 0}
        },
        "update": {
          "fill": [
            {"test": "datum.category === 'A'", "value": "blue"},
            {"value": "none"}
          ]
        }
      }
    }
  ]
}
```

- When rendering to svg, the render works fine. The bar "B" and "C" are hidden.
- However when rendering to canvas:
	1. The bar "B" and "C" are not hidden, and have the same color as bar "A"
	2. When hover the mouse over bar "B" and "C", the color turns black:
![jul-16-2018 15-48-17](https://user-images.githubusercontent.com/30903997/42787578-ed84cd74-890f-11e8-93b1-e23d1014e42d.gif)

This is the expected output:
![screen shot 2018-07-16 at 15 50 43](https://user-images.githubusercontent.com/30903997/42787603-05ce9a5e-8910-11e8-8c8c-4bb728a3e461.png)

**Comment by jheer** [comment]
Apparently HTML5 Canvas (on Chrome at least) does not accept `"none"` as a color.

Try the following in the browser console:

```js
var ctx = document.createElement('canvas').getContext('2d');
ctx.fillStyle // "#000000"
ctx.fillStyle = 'red'
ctx.fillStyle // "#ff0000"
ctx.fillStyle = 'none';
ctx.fillStyle // "#ff0000" -- NO EFFECT
ctx.fillStyle = 'transparent';
ctx.fillStyle // "rgba(0, 0, 0, 0)"
```

The solution for now is to use `"transparent"`, which is supported. While not part of the SVG spec, browsers also support it for SVG, while our SVGStringRenderer transforms `"transparent"` to `"none"` when generating static SVG output.

**Comment by chanwutk** [comment]
I also tried using `null` and it works. What is the difference between `"transparent "` and `null`?

**Comment by chanwutk** [comment]
Thank you
