### ISSUE TITLE
Logarithmic and power color scales

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1369]
Only `linear` scales have a good scale for color, namely `sequential`. For `log` scales(and also the default `linear`) scales, we don't have a good color range.

See https://github.com/vega/vega-lite/pull/4040 for details. 

The proposed solution is to implement `sequential-log` and `sequential-pow` and use them in Vega-Lite.

**Comment by kanitw** [comment]
If possible, it might be be simpler from a user's perspective to make `linear`, `log`, and `pow` use their sequential variants when they specify a sequential color scheme as the range. (They shouldn't have to change the scale type from `log` to `sequential-log` to enable the scheme.) 

That said, I understand that there might be some subtleties that make this not possible.

**Comment by domoritz** [comment]
We could do this in Vega-Lite but I think for Vega it makes sense to keep these separate.

**Comment by kanitw** [comment]
> These scales do not expose invert, range, rangeRound and interpolate methods

I think range, rangeRound, interpolate could be just ignored if users provide sequential color scheme.   

However, the question is given there is no "invert", would that cause a problem for consolidating them?

**Comment by domoritz** [comment]
Part of https://github.com/vega/vega/issues/1536
