### ISSUE TITLE
How to access array of json objects in vega

### ISSUE THREAD

**Issue by varmatangoit** [vega/vega#1375]
I am using vega in kibana. I try to access array of json field but I cannot able to access that field, could anyone help me to resolve this issue. I attach my vega json and index name is pie

index data sample:

{ "_index": "pie", "_type": "flare", "_id": "2", "_version": 1, "_score": 1, "_source": { "id": 2, "parent": 1, "data" : [{"memory":{"value": 50}}]} }

**Comment by domoritz** [comment]
You can write an expression like `datum._source.data[0].memory`. Since this is a kibana question, I'm going to close it and ping @nyurik.

**Comment by nyurik** [comment]
@varmatangoit in general it is probably better to ask the question at [Elastic Discuss forum](https://discuss.elastic.co/). Also, if you only need to access just a single value inside the result, @domoritz answer should work. If you need to iterate over all values in the array, you would need to either flatten it using flatten transform, or use groups.
