### ISSUE TITLE
sort nominal field axis by secondary field, one layer chart

### ISSUE THREAD

**Issue by eamoore** [vega/vega#1376]
I have a simple data frame with nominal key (Y axis) and quantitative value (X axis)
I am  attempting to sort the Y axis according to a descending sort on the quantitative field.  

The chart has one layer, so I think it is a different problem than https://github.com/vega/vega-lite/issues/3710.

Here's a snippet from the Vega-Lite, Editor $schema": "https://vega.github.io/schema/vega-lite/v2.4.3.json"

"encoding": {
        "x": {"type": "quantitative", "field": "correlation"},
        "y": {
          "type": "nominal",
          "axis": {"grid": true, "title": "pair"},
          "field": "pair",
          "sort": {"op": "count", "field": "correlation", "order": "descending"}
        }
      },

This is unsuccessful. Sort order is on the key field, "pair".
If I change the op from "count" to "mean", I get the expected sort.
What's going on here?

not ok:
![image](https://user-images.githubusercontent.com/20135569/43023937-97c1bcde-8c3a-11e8-8991-3958283357f0.png)

ok:
![image](https://user-images.githubusercontent.com/20135569/43023920-892ce518-8c3a-11e8-9b8d-78c08c006e79.png)

Specs for each chart are attached. 
[successful-sort-json.txt](https://github.com/vega/vega/files/2215314/successful-sort-json.txt)
[unsuccessful-sort-json.txt](https://github.com/vega/vega/files/2215315/unsuccessful-sort-json.txt)

**Comment by jheer** [comment]
This appears to be a Vega-Lite question, in which I case I encourage you to instead post it at https://github.com/vega/vega-lite/issues

Thanks!
