### ISSUE TITLE
Create a Roadmap

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1377]
## Planned to work on or being worked on

* Labeling for scatterplots and line charts
* Support for log color scales
* Sharing in the Editor (https://github.com/vega/vega-editor)

## On our radar, but we don’t have a clear timeline for it

* Arrow integration for better scalability
* Animations (#641)
* Arrow reader (#1300)
* Support in Wikipedia (https://phabricator.wikimedia.org/T165118)

See https://github.com/vega/vega-lite/issues/4078 for Vega-Lite equivalent.

**Comment by g3o2** [comment]
I would like to add text wrapping to the roadmap, both for guides (legends, axes, titles, labels, etc.) and for the text mark. (#488)

**Comment by domoritz** [comment]
I moved all of these into a more general Vega and Vega-Lite roadmap. See https://docs.google.com/document/d/1fscSxSJtfkd1m027r1ONCc7O8RdZp1oGABwca2pgV_E/edit#.
