### ISSUE TITLE
Inset Plots

### ISSUE THREAD

**Issue by pagpires** [vega/vega#1378]
Hi, is it possible to generate inset plots using vega (different-size plots overlapped with each other, something like [this](https://stackoverflow.com/questions/21001088/how-to-add-different-graphs-as-an-inset-in-another-python-graph))? Please let me know if I missed the doc/resource... Thanks in advance!

**Comment by kanitw** [comment]
I don't know there is any existing example, but you can surely use [group marks](https://vega.github.io/vega/docs/marks/group/) for each plot and customize each group to have different x/y/width/height.

**Comment by domoritz** [comment]
Since we use the issue tracker for bugs and enhancements and not questions, I'm going to close the issue. Feel free to respond here if you find a solution.
