### ISSUE TITLE
API to listen for data chages

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1383]
It would be great if we could listen for data changes similar to how we can listen for signal changes. 

We could use this feature in the Vega editor to show and update the datasets that are used in a chart.

**Comment by domoritz** [comment]
cc @ydlamba

**Comment by domoritz** [comment]
We don't do that, though. I'd say instead we just pull (using a r freh button).

**Comment by kanitw** [comment]
? not sure what you mean, but I agree we should have this API. :)

**Comment by jheer** [comment]
Added in vega version 4.3.0.
