### ISSUE TITLE
Internal signal values are not updated before signal listeners are called

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1384]
```json
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "signals": [
    {
      "name": "a",
      "value": 0
    },
    {
      "name": "b",
      "update": "a + 1"
    }
  ]
}
```

Add a listener to a and print value of b.

```js
VEGA_DEBUG.view.addSignalListener('a', () => console.log(VEGA_DEBUG.view.signal('b')))
```

Then update a

```js
VEGA_DEBUG.view.signal('a', 1).run()
```

I would expect to see the value `2` printed but instead get `1`.

**Comment by domoritz** [comment]
@arvind, do you have some insights into why this is the behavior?

**Comment by jheer** [comment]
Yes, for better of worse this is working as designed.

Internally, a signal listener is itself a dependent operator that evaluates when its upstream signal updates. So in this example, the signal listener operator for `a` is a peer of the downstream signal operator `b`. Moreover, to ensure consistent behavior, listeners are given the lowest possible rank value for the dataflow priority queue, and so are _always_ evaluated prior to normal operators (e.g., standard downstream signals).

If you want to access any updated values downstream of the signal you are listening to, you can register a callback with `view.runAfter` (to invoke synchronously upon completion of dataflow evaluation) or using `setTimeout(callback, 0)` (to invoke asynchronously).

**Comment by domoritz** [comment]
Oh, I forgot about `view.runAfter`. This works for me.
