### ISSUE TITLE
Logo and Branding for Vega and Vega-Lite

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1386]
Vega still lives without a logo but it would be nice to have some recognizable branding. 

We could go with the logo style that Altair uses: https://github.com/altair-viz/altair/issues/212#issuecomment-338428670

![image](https://user-images.githubusercontent.com/589034/43657136-ad9cdea6-9709-11e8-91c5-fe8dc0f71065.png)

Let's use this thread for further proposals and discussions.

**Comment by domoritz** [comment]
Here is a differently colored version of the Altair derivative (using IDL colors).

<img width="295" alt="screen shot 2019-01-21 at 16 58 08" src="https://user-images.githubusercontent.com/589034/51505830-cabd8600-1d9d-11e9-9aee-340da7899624.png">

**Comment by domoritz** [comment]
My V design works fairly well for Vega-Lite as well. 

<img width="702" alt="screen shot 2019-01-21 at 17 18 18" src="https://user-images.githubusercontent.com/589034/51506306-9ac3b200-1da0-11e9-91b7-e8375a0065d2.png">

**Comment by domoritz** [comment]
A few more experiments

<img width="943" alt="screen shot 2019-01-21 at 18 43 42" src="https://user-images.githubusercontent.com/589034/51509009-7ff73a80-1dac-11e9-9cea-46cb30a95a1f.png">

**Comment by domoritz** [comment]
V with hard shadows (could make it into a single-colored version easily)

<img width="344" alt="screen shot 2019-01-21 at 22 12 05" src="https://user-images.githubusercontent.com/589034/51515716-9fe92700-1dc9-11e9-93a7-11678571296d.png">

Circle logo (Vega star)

<img width="364" alt="screen shot 2019-01-21 at 22 12 10" src="https://user-images.githubusercontent.com/589034/51515735-af687000-1dc9-11e9-86b9-de7c228f402c.png">

**Comment by kanitw** [comment]
I like this one: 


<img width="601" alt="image" src="https://user-images.githubusercontent.com/111269/51517667-56500a80-1dd0-11e9-9c12-980747554e8f.png">


though I'm not sure why the L part doesn't align?

**Comment by RandomFractals** [comment]
I like the set @kanitw picked, but I'd rather see if altair team would let you use their color scheme. That purple and orangy yellow is too veteran ribon looking.

I think light blue and nice yellow alter team used would be more appealing and connect the overarching dots to altair lib too.

**Comment by Casyfill** [comment]
I also like the one @kanitw picked - and the altair one. Wfiw, re branding - could vega/vega-lite have purple as it's default color, instead of ugly steel blue? This way many your examples will be "branded"

**Comment by domoritz** [comment]
> ugly steel blue

It's actually [`#4c78a8`](https://www.color-hex.com/color/4c78a8), not [`steelblue`](https://www.color-hex.com/color/4682b4) 😛. Jokes aside, I'm okay with chaning it but blue is more neutral than purple.

**Comment by domoritz** [comment]
A nice property of the hard shadows in the ribbon logo is that we could make a monochrome version easily.

<img width="887" alt="screen shot 2019-01-22 at 17 02 11" src="https://user-images.githubusercontent.com/589034/51575591-8991a880-1e67-11e9-8875-020c91500161.png">

> though I'm not sure why the L part doesn't align?

All of these are quick drafts.

**Comment by domoritz** [comment]
In Altair colors.

<img width="677" alt="screen shot 2019-01-22 at 17 07 56" src="https://user-images.githubusercontent.com/589034/51575758-48e65f00-1e68-11e9-9505-a3634b592eeb.png">

**Comment by domoritz** [comment]
Alt(ernative)

<img width="412" alt="screen shot 2019-01-22 at 17 15 13" src="https://user-images.githubusercontent.com/589034/51575996-4fc1a180-1e69-11e9-872f-2d2dab55e661.png">

**Comment by Casyfill** [comment]
Like it!

**Comment by RandomFractals** [comment]
Love the blue set! Ship it! :)

**Comment by arvind** [comment]
I like the blue color scheme as well, and it has the added advantage of moving us away from a UW/IDL-first branding now that the core dev team is spread across multiple affiliations :)

**Comment by domoritz** [comment]
New logos are at https://github.com/vega/logos
