### ISSUE TITLE
Undefined Errors in vega version 4

### ISSUE THREAD

**Issue by RishabhSachan** [vega/vega#1388]
Hi, i had some code, which works fine till 3.3.1 but doesnt work in any of the latest vega version from 4.0.0.rc-1 till 4.2.0

Here is the screenshot when used with view.logLevel(vega.Error)

![image](https://user-images.githubusercontent.com/12508104/43771974-611c30ec-9a5e-11e8-9abb-cdcf9a51b791.png)

My scenario is i am getting state of view and setting the state, and other properties such as width and height. This works fine till version 3.3.1

**Comment by domoritz** [comment]
Can you send us a minimal spec that shows the erro so that we can debug?

**Comment by RishabhSachan** [comment]
https://jsfiddle.net/rishabh_sachan/e8ty53nL/
Here is the fiddle link to minimum code where issue is reproducible. Spec is used by two views, so interactions are done in javascript.

I have added vega 4.2.0 as resources where issue is reproducible.
If you switch to vega 3.3.1 (https://cdn.jsdelivr.net/npm/vega@3.3.1) errors are not coming.

**Scenario to reproduce error:**
Right side are two charts which on click is shown on left side. Once you open page click on Assignee2 to change the left chart, at that time, errors can be seen in console.
In vega3, errors are not occurring on changing chart same way.

**Comment by Mohanraj-86** [comment]
@domoritz Did you get a chance to check this issue?

**Comment by domoritz** [comment]
No, I was out camping for the last ten days 😁

I have a lot of things to catch up on before I can look at this but it's great to have a working example for the issue.

**Comment by Mohanraj-86** [comment]
Thanks @domoritz We have production release this month end where this is blocking. Once you get time, can you check this with priority?

**Comment by domoritz** [comment]
Hmm, I don't have the cycles to debug more than a thousand lines of code. If you send me a smaller example that shows the error (preferrably without a lot of JS), I will make it a priority.

**Comment by domoritz** [comment]
I found that `datum` is undefined in one of your charts.

```json
"update": {
          "x": {
            "signal": "w / 2"
          },
          "y": {
            "signal": "w / 2"
          },
          "startAngle": {
            "signal": "(datum ? datum.startAngle : 0) +offsetAngle"
          },
          "endAngle": {
            "signal": "(datum ? datum.endAngle: 0)   +offsetAngle"
          },
          "outerRadius": {
            "signal": "w/2"
          },
          "innerRadius": {
            "signal": "w/4"
          },
```

You can try to debug from here: https://jsfiddle.net/e8ty53nL/5/. This may not be a Vega bug after all. 

Fyi, you don't need expressions to use offset. 

```json
{
  "marks": [
    {
      "name": "baseMarks",
      "type": "point",
      "from": {"data": "source"},
      "encode": {...}
    },
    {
      "type": "text",
      "from": {"data": "baseMarks"},
      "encode": {
        "update": {
          "x": {"field": "x", "offset": 4},
          "y": {"field": "y"},
          "text": {"field": "datum.label"}
        }
      }
    }
  ]
}
```

**Comment by Mohanraj-86** [comment]
Thanks @domoritz . Let us go through it.

**Comment by RishabhSachan** [comment]
@domoritz 
Hi, our code shared was big so as to maintain the specific errors we were getting after vega upgrade.
I will try to share lesser javascript code in which issue still reproducible if we could reduce it further.

However below is more details found for the above error. The datum **undefined** is misleading as it was working fine in vega3, but might have become undefined in some flow in vega4.

I requested the interactive property to be used as signal which is used in our code. The error is occurring in same **when we try to set interactiveFlag signal** (signal passed to interactive property in mark) after the data changes.

This flow was woking fine in vega version 3 in our code and stopped in vega version 4.

I found the errors were resolved if we remove signal from interactive property in mark.
For now to maintain our functionality we are setting interactive by getting state and then setting interactiveFlag. 

**example**: 
view.signal('interactiveFlag',true);
we have **rewritten** the above line as:
let state = view.getState();
state.signals.interactiveFlag = true;
view.setState(state).run();

As we are just updating interactive property it should not have caused error when updating via run() but works with manually updating value.
This changes are needed in version 4 for us.
Here is the working fiddle with just above state change implementation.
https://jsfiddle.net/e8ty53nL/31/

Let us know if this helps to narrow down the issue or changes in vega upgrade if any. Thanks.

**Comment by domoritz** [comment]
I still believe that you should change the code rather than that Vega should change. I'm not yet convinced that there is a bug in Vega but if you find a small example that works in the editor, we can have a look at it again and work out a fix. I hope you understand. Thanks!

**Comment by RishabhSachan** [comment]
@domoritz yes I understand that the issue might be on our code.
 I am still trying to find the exact cause so that I can change the code.
If i am able to reproduce the issue during that in a sample smaller code, I will share that. Thanks.

**Comment by domoritz** [comment]
Sounds good. Thanks.

**Comment by jheer** [comment]
Closing for now, as this does not appear to be a Vega bug. Will re-open if needed when more evidence arrives!
