### ISSUE TITLE
Add symlog axis scaling?

### ISSUE THREAD

**Issue by mattpitkin** [vega/vega#1392]
If you have data that spans many orders of magnitude across both positive and negative values it is often useful to be able to plot both the positive and negative ranges on a logarithmic scale, with a linear range spanning between them. This is done in, e.g., Matplotlib, using the [`symlog`](https://matplotlib.org/gallery/scales/symlog_demo.html) scaling.

Would adding something like this be possible in Vega?

Refs vega/vega-lite#4127

**Comment by mattpitkin** [comment]
@jheer thanks, I'll add my support for that PR and see if there's any more momentum to get it into d3.

**Comment by mattpitkin** [comment]
It looks like symlog has been added in #1544

**Comment by jheer** [comment]
Yes it has! It will drop in a Vega 5.0 release within the next week.
