### ISSUE TITLE
Keypress event (and other key related events) not working

### ISSUE THREAD

**Issue by dhkim16** [vega/vega#1393]
This is a very simple example that grows the bar upon clicking and decreases the bar upon pressing any key, but the keypress does not function.

```{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "width": 960,
  "height": 500,
  "padding": {"left": 50, "right": 80, "top": 20, "bottom": 30},
  "signals": [
  	{
      "name": "h",
      "value": 50,
      "on": [
        {
          "events": {"type": "keypress"},
          "update": "h - 10"
        },
        {
          "events": {"type": "mousedown", "filter": ["event.button === 0"]},
          "update": "h + 10"
        }
      ]
    }
  ],
  "data": [],
  "scales": [
    {
      "name": "xscale",
      "type": "linear",
      "domain": [0, 50],
      "range": "width"
    },
    {
      "name": "yscale",
      "type": "linear",
      "domain": [0, 100],
      "range": "height"
    }
  ],
  "marks": [
    {
      "type": "rect",
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "value": 25},
          "width": {"scale": "xscale", "value": 10},
          "y": {"scale": "yscale", "signal": "h"},
          "y2": {"scale": "yscale", "value": 0},
          "fill": {"value": "#000"}
        },
        "update": {
          "y": {"scale": "yscale", "signal": "h"}
        }
      }
    }
  ]
}
```

Filters like `"filter": ["event.button === 0", "event.shiftKey"]` do seem to work, though.

To add: this behavior seems consistent with Chrome, Firefox, Opera, Safari.

(P.S., I don't know if this is a feature or a bug, but in this specific example, I had to put `"y": {"scale": "yscale", "signal": "h"}` in both the `enter` and the `update`. Just having it in `update` does not display anything.)

**Comment by jheer** [comment]
Thanks for sharing this report. Technically this is not a Vega bug, but rather an issue with how the web browser handles keyboard input. A web page element must have the text entry "focus" for key events to be routed to it. By default, Vega's generated SVG or Canvas elements will not have that focus.

One way to enable text focus is to add the "tabindex" HTML attribute to an element, then hit the tab key until it receives focus. Other options include the DOM element [`focus` method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus).

Happy to consider further additions to Vega that might simplify the use of text input, so feel free to submit more specific feature requests as well.
