### ISSUE TITLE
Floating point issues with bin thresholds

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1395]
See https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq6ArIoiQUjavl0B2AAz2oB9Hkw4ANpKEKAQ4VAy6Kg6OJC+-sYRDngATugysABm3KmousHJ4WFF4ZB4AJ6EsVDslkmlDlmMyAA2RnENjZAa1FGtupB1mV2lkBgAHsOwugAc3t3IE3jIMngFAIx0G-JgAEx0ezYAuiHJAL5nEKcRl9fePfDorcgzQWclEZBRMYPw3K1cqMUlUakNLABaXIWfrAnzcDD1HCfZI9ZywuKwZAAR1Yq3gyAAFNM6LB-Kk8LsSWTuIQwABqMDUlaEKmWWCklkASkgVzA5wWZXSVhqwEeAjB7FaeNyGWoOju4UVxweL3lMgMbzAgTFzVaAzi-0BqUg51O5yAA

![image](https://user-images.githubusercontent.com/589034/44107485-618353f0-9fac-11e8-97da-2447d4cf728c.png)

Is there a way to avoid these with a difefrent setup? The legend was generated from Vega-Lite.

**Comment by jheer** [comment]
This example uses a `bin-ordinal` scale, but the current implementation of that scale does not include a `tickFormat` method. As a result the label is generated via string coercion and so does not handle standard floating point issues.

A solution would be to update the [`bin-ordinal` implementation](https://github.com/vega/vega-scale/blob/master/src/scaleBin.js#L65) to include an appropriate `tickFormat` method. As the `bin-ordinal` scale assumes a numerical domain, adding `tickFormat` should be straightforward _if_ we assume the bin steps are linear.

In the meantime, including `"format": ".1f"` (for example) in the legend definition will clean up the labels.

**Comment by domoritz** [comment]
This is not an issue anymore. I'm closing this issue.
