### ISSUE TITLE
Base property in axis

### ISSUE THREAD

**Issue by chanwutk** [vega/vega#1398]
I run in to a problem while I was creating a Vega example.
The unit of one of the axes is degree, so I would like this axis to start from 0 and increment by 60 until 360. However, when I set `domain` in `scales` to `[0, 360]` and `tickCount` in `axes` to 6, the ticks start at 0 and increment by 50 until 350 like this: 

<img width="915" alt="screen shot 2018-08-17 at 13 59 32" src="https://user-images.githubusercontent.com/30903997/44288604-d40e5980-a225-11e8-8c50-3afc8ab7a87a.png">

The solution I have is manually set the value of axis to:

```json
"values": { "signal": "sequence(0, 361, 30)" }
```
It seems like hacking, so I think it would be great to have a property to set the size of the base of axis like what [Bin Transform](https://vega.github.io/vega/docs/transforms/bin/) have.

**Comment by jheer** [comment]
Thanks for the suggestion! Vega relies heavily on D3, and currently we pass the tickCount down into D3 scales, which then produce the current behavior. As a result, this is unlikely to change as it would require implementing a new layer of indirection (that said, if anyone has good ideas, we're happy to discuss ideas or review PRs to the vega-encode repo!). Or, if you have ideas for D3 scales you might make recommendations there.

I do not consider setting custom values to be a "hack", even if it feels less elegant.
