### ISSUE TITLE
Add tree layout with evenly spaced leaf nodes

### ISSUE THREAD

**Issue by metasoarous** [vega/vega#1399]
Hi there. I'm attempting to use the Vega [tree transform](https://vega.github.io/vega/docs/transforms/tree/) to visualize phylogenetic trees for a bio/immunological analysis application, but am not able to get the leaf nodes of tree to be evenly spaced along the y axis:

![image](https://user-images.githubusercontent.com/88556/44304291-ed3e0580-a30c-11e8-9c37-21413d3bb6d7.png)

As you can perhaps see in the figure above, I'm trying to align the tree nodes on the left with additional data being plotted on the right (in this case, a visualization of where the mutations fall in the sequences corresponding to the leaf nodes in the tree). However, if you look closely, you can see that the vertical spacing between labels is not constant, but seems to depend on how deeply nested in the tree the label is. This makes it impossible to achieve what I'm aiming for as currently set up.

Currently I'm using the `cluster` tree transform method, but it doesn't look like `tidy` would give me anything closer to what I'm looking for. I'm wondering if you'd consider adding another option that would evenly space out the leaf nodes, as desired in this case.

I imagine that this should be a simple (:crossed_fingers:) postwalk of the tree, assigning successive integers to the leaf nodes, and taking the average of children positions for intermediate nodes. I could totally write this myself as a pre-processing step on the data, but if it's feasible for this to go directly into vega as an alternative tree transform method, I'd much rather see that pan out. Thoughts on this?

Thanks in advance!

**Comment by jheer** [comment]
Thanks for the request! I've updated the vega-hierarchy module to support a boolean `separation` flag for the `tree` transform. If `true` (the default), then sibling nodes are placed closer together than cousin nodes. If set to `false`, the separation among nodes will be uniform, as in a traditional dendrogram. These updates will be included in the next release of Vega.

**Comment by metasoarous** [comment]
Amazing! Thank you so much!
