### ISSUE TITLE
Top-level units type specification

### ISSUE THREAD

**Issue by mattijn** [vega/vega#1400]
In a side project I was hoping to parse Vega created SVG output directly to a laser-cutting machine. 

This was not directly possible and the easiest problem was the lack of a `units` property in the top-level specification to define the `width` and `height` in millimeter rather than pixels. 

The inclusion of a `units` property might be useful for defining visualizations for specific paper sizes as well.

**Comment by jheer** [comment]
Thanks! If there is a simple PR (perhaps for the SVG output rendering methods?) that helps with this I'd be happy to review. However, I'm a bit hesitant to add this as an official feature as (1) we'd like to keep specs consistent across renderers, and not introduce renderer-specific configuration into the JSON schema, and (2) this particular issue seems fixable with some very basic output post-processing. As a result, I'm closing this issue, but again, happy to review API-level (rather then spec-level) PRs that might assist customization of SVG output.
