### ISSUE TITLE
Scroll bars in Vega

### ISSUE THREAD

**Issue by eladshe** [vega/vega#1402]
Hi,

I started using VEGA to create visualizations in KIBANA. 
When trying to visualize a NxM matrix, which exceeds the size of the screen, there was no vertical or horizontal scroll bars. 
Even the examples given in the gallery seem to have the same issue (https://vega.github.io/editor/#/examples/vega/tree-layout)

What can I do to add scroll bars?

**Comment by domoritz** [comment]
I fixed the issue in the Vega-Editor. It now scrolls if the visualization is too large.

**Comment by eladshe** [comment]
perfect, thanks!!

**Comment by domoritz** [comment]
Since this is a kibana issue, let's tag @nyuriks.

**Comment by domoritz** [comment]
There isn't anything that Vega can do so I'll close this issue.

**Comment by prakashgupta1605** [comment]
It it possible to hide the scrollbar?  I am displaying some texts in vega visualizations which I am using in a dashboard. I don't want to display the scrollbars because they make the dashboard look ugly.

**Comment by jheer** [comment]
You should be able to use external CSS rules for the overflow property on the Vega container div to control scrolling behavior.

**Comment by prakashgupta1605** [comment]
I tried the following property and it works. Thanks
`"autosize": {"contains": "padding", "type": "fit"  } ` 
However, it didn't work on Kibana 7.17 but it works on 8.10
