### ISSUE TITLE
Drag interaction in force-directed-layout example fails in Firefox

### ISSUE THREAD

**Issue by Mahog** [vega/vega#1403]
When working with the [specification of the force-directed-layout example](https://vega.github.io/vega/examples/force-directed-layout/) in Firefox (currently on 61.0.2) on both Linux and Windows, the drag interaction on node marks fails, producing the following error message: ```ERROR ReferenceError: "event is not defined"```. 

The culprit appears to be one of the triggers on the node mark, which accesses the ```x()``` and ```y()``` operators: 
```
[...]
{
    "trigger": "fix",
    "modify": "node",
    "values": "fix === 1 ? {fx:node.x, fy:node.y} : {fx:x(), fy:y()}"
}
[...]
```

A simple workaround that works both on Firefox and Chrome is to store x and y in an additional signal for the current mouse position, updating on ```:mousemove```, like so: 

```
{
    "name": "mousePosition", 
    "value": {"x": -1, "y": -1}, 
    "on": [
        { "events": ":mousemove", "update": "{x: x(), y: y()}"}
    ]
}
```
and then referencing that instead of ```x()``` and ```y()``` inside the trigger:

```
{
    "trigger": "fix",
    "modify": "node",
    "values": "fix === 1 ? {fx:node.x, fy:node.y} : {fx:mousePosition.x, fy:mousePosition.y}"
}
```

**Comment by jheer** [comment]
Thank you! Fixed using a slightly different alteration in both the vega example gallery and in the vega-lib test suite. It appears some browsers (Chrome) define an `event` global in the midst of event processing but others don't (recent Firefox). Vega definitely should not expect this global to be bound.
