### ISSUE TITLE
duplicate tick labels in quantitative scale

### ISSUE THREAD

**Issue by Alcampopiano** [vega/vega#1406]
Hi all,

You can see [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDuCWAmAXAFpAXGArABmwGnCmQFNYBzZRdMAZlwIkgGMB7AOwDNzrQJHFYiADbEekDu0QBlWAC9RGAEzYAvgz6Q2AVwC2AI2IAnAGItDOgIZUMkAHTYOkdYwDOiAJ4iehPlD0XDMRc5BTBlNR8NMi0EYgBaAWFQ4HFJGXlqRUwI30Zo2LihCwMhMQk2aRDM1UicjRcmCy8MFP82eAAFC3h4WDYyAEk2NiNqbFtMPD8Ldq6evrIAeS1EUYxx7OcoETJidqD3fRYhdNCARnooRJFTCtPqqcgiktvKjIwzgA46xgsAD1gLjE12Ir3uSnw22KxCEYKqH2+hDqkHgVgs3l8kAAbk0tMQgRgANqRCC8XKMVGraiQC4AejOZ3pnycJI0bAsOlCkAAVkCtpiWHtqGd+fUmMgWMdqQBZAAyABUpCzyfxkIZ8RKhPBqDRWT8+GTySirFy6WdFEzlSrNByubyrUbBWxhaLXOLJaUbHLFQ7cpAUOqXJrtRhdeT9aTWRSTdSzTRLa6oOzOdT7YnIE6XVGoA0JVKvQqlemAxrjiHaHrRYa-ZTTdh6Ravr7McmuRYyM2NJmlOncx6ZYXO6rA8HMpXWdXMbXY-WzvGm+nW9T20OoN2wr33fmoN6i9n-WrS1qx+Gq-vpzYzQB2BP7pc2CxMVcZoWhzd5z1QABSiwAEotnxLIMy2FcdyUnDQLygM1MFvFUk1takdAAB2fdcABZ337Gwf3-QDD2A48lDA3IIOjKlL1nAA2ODrXvKAULQ18wEw-c+23SBcIA4sCNHYjTwnc8Y0o+l52ZRdEIfaAmOdDBJjYrdP0gABpAYADkAHF8JHECMHQkjfDIqAoJpWd0Noo16MgCxpPTdd5PgyB2KU1TNO0o9y30gTwKEijoNnWCFzvSSoBsmTqAc61nOpVytJ4nSiJYgyDV8ut6RooLHKssK7OYyKjWimxYvcwjPL1SIAF0kXUSBLEMABral-ECGq9lYXp+gxDQ-mBdxkK5NgWB0PomicKAuBhcsbRTfVIHcXr+upABHLQZkSKxYCxURHnbMh1TIYSoFYLQKkgFRqsISAABJc2ISxqUoRBkJcNBaVpLaDtsMhBGQLQ9FsWAWFpW7LHe4gDsKQRiHexRbHQ2waFsXl2EgEAVCAA/view) that the chart has duplicate tick labels. 

Setting tickCount can avoid this for a static chart; however, when using a selection to filter the chart, the issue cannot be controlled. Please see [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDuCWAmAXAFpAXGArABmwGnCmQFNYBzZRdMAZlwIkgGMB7AOwDNzrQJHFYiADbEekDu0QBlWAC9RGAEzYAvgz6Q2AVwC2AI2IAnAGItDOgIZUMkAHTYOkdYwDOiAJ4iehPlD0XDMRc5BTBlNR8NMi0EYgBaAWFQ4HFJGXlqRUwI30Zo2LihCwMhMQk2aRDM1UicjRcmCy8MFP82eAAFC3h4WDYyAEk2NiNqbFtMPD8Ldq6evrIAeS1EUYxx7OcoETJidqD3fRYhdNCARnooRJFTCtPqqcgiktvKjIwzgA46xgsAD1gLjE12Ir3uSnw22KxCEYKqH2+W0g-0BAA0xM8YQBBfrNMA1CB1SDIVhsRrWMAAbUivFykHgVgs3lyGgAbk0tMQgRhqSzfLS+RoGatqJALgB6M5nSWfJyRQWaCw6UKQABWQK2CpYe2oZ01fMgDWQLGOooAsgAZAAqUjlgt8kBQhi5xqE8GoNHluR+fIF9vpVhVErOihldvtjDYSpV6vDEcg2rYuv1LMNTGNppslptcf9Tpdx3dGE9EZ9LL9CuFQewkpoYZTdKjytFsYbDsTya9qaNJtKWettrbGnzLldRdoXb4ZdyFYNVdFwdDX1zCqbKosZBXBo7SiHrnTvfNA63qZHY8yk8JQ9nqfnNmDdeXe6ga9FG5PdJ3YWfaYzfag2aDpew7IM6o6FhepbXsBjB3lAwYAOz1jBL7Rm+TAfu2OrFj+PaZlAABSiwABKLJhIFgeeHzAdO-IoQGIr3jWZyYMhEaRmhNg6AADuRjBfgALLhB74ZARGkXxVygQWbqQfatF8DedJwWKzEAGxsexirNlxvE-oJwl-qK4lkT+Z4QUoNHQexUAqQ+mnxq+NgWNAkkJthWCGYeNgANIDAAcgA4m55myRgAlWcBSkOnZzECQ5-pOVALluV+kz0Xh-6QH5QUhdJ4FhWAEVQVF9GxZKrFPvRSXIq5+keelNm-t5UA5cFZn5VRRWRRG0VCoGC7qQlq6ccldX0WlXmiW1eWURZ3WlpOAC6XrTpAliGAA1qKzpMFQ+qQHsrC9P0zIGqwQhmGdCqkr0AjsNdebuNxKoAI5aDMiRWLArKiD+XAwuOjqdRBuEwsQe2wA9NguODe1mNgalnJAPX+uyQicqKQjkJQZCGBY7go4KCmQH8j2ns9KpmCdTTkciALcmAKQgqKoXugpjAA4VwNzbJk4qKtB0kDjFI4AdsMiJD0NM5Ohpw4gCNI+TdIeC9orBLif3AYdZIsCdZCM5SzDHFdS1DgmSY2Ew2NMNt5tgccv2imQl3+KU5vEDxHhvkIpT84LXowAgKAergtRbLODFMi0svo5yhulU15VSsNBo1a2E0eXqGUiVlgGzTJ44lvJ1lacnS6yj+6capnltgNnTWZUeOYdbzReo4KfWwQNTG1qnqbV6lWdTXnx6t4XHod76ZU9-BzEV25NXvvVdeKCPzdAU1bNycTpfxsnj6V9Vo3IpuK+ZOv-Yt-R2+WSVvUz4xc+SkhVVNUvGHnzhOdGTYJkFwVccZwp7lkftWCq-dGwnx4kPOuQkf4tTEiRUyN8QaFUUCAmcYDBqSg0m-LSNUYFfyKpfQiyCAFdQwffe0XdbKz1Un3fBjkT4pWIY1LSTdfIBXaqgtu1Biol0TmXehwZ4pMMSiw8aTVJoIOmtwih80BG7yEfvERzFKpH3fpI2B1B2Hxk4a1eR49AH8MwXRJOajcGQIdEvKRWkZGN1zqKGaxiupKL5ALQUK0WRrQ2ttGw-hAgHSOnrBYytGAXSui0R0lNRRsBYDoPotNHhcyBk3EmwR3gy3jKrFU8TElRndtrVJop5zmx2Hscc2hfbmwaE0ZIkB8b9FCJSC4UwcBLU8R4hsjpewCF4tE3JcSElJPdlAEpNh5wkzJjHHJsSbD5NGXTFEjNmaCDxIaRAWh4B7EQGAV8HNxmwEBnEtC-MemE1mU9NWNh3qfUEN9J25sNx42IGQehrAtAVGWQzYEsBbYAGEWBfIpEJK46y8m6AMIYMALAOBgGKLDMkXJIBdJ8QHVMwsKAUjoPgQOiAmkuAkOYaglIUhcCEKsQI0SJYQ3unXOWksFaGERsjFQKgzaBzgEgVAxYw6+C6ZyxgAASI0nto5EEQIgbiLg0DinFL9d5tgyCCGQFoPQtgobijFZYBVbyLCFEEMQBVihbACVsDQWw6oHogBUEAA/view) for an example.

**Comment by domoritz** [comment]
Related #621

**Comment by domoritz** [comment]
Actually, I filed this already in a different repo: https://github.com/vega/vega-encode/issues/14.
