### ISSUE TITLE
Render badly arc in symbol shape path

### ISSUE THREAD

**Issue by evanliomain** [vega/vega#1408]
I try to draw some custom arrows in svg and feed it to the symbol shape attribut.

Here a simple example:
```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 500,
  "height": 250,
  "marks": [
    {
      "type": "symbol",
      "encode": {
        "enter": {
          "shape":{"signal": "arrowDownPath"},
          "size":{"signal": "pow(200, 2)"}
        }
      }
    },
    {
      "type": "symbol",
      "encode": {
        "enter": {
          "x":{"value": 300},
          "shape":{"signal": "arrowUpPath"},
          "size":{"signal": "pow(200, 2)"}
        }
      }
    }

  ],
  "signals": [
    {
      "name": "arrowUpPath",
      "value": "M.8,-1A.25,.25 0 0,0 1,-.8 L1,.3A.2,.2 0 0,1 .6,.3 L.6,-.3 L-.6,.9 A .21,.21 0 0,1 -.9,.6 L.3,-.6 L-.3,-.6 A .2,.2 0 0,1 -.3,-1 Z"
    },
    {
      "name": "arrowDownPath",
      "value": "M.8,1 A.21,.21 0 1,1 1,.8L 1,-.3A .2,.2 0 0,0 .6,-.3L.6,.3L-.6,-.9A .21,.21 0 0,0 -.9,-.6L.3,.6L-.3,.6A .2,.2 0 0,0 -.3,1Z"
    }
  ]
}
```

Which render like this:
![vega editor](https://user-images.githubusercontent.com/6391294/44589344-a3e03100-a7b8-11e8-8dda-13df741c3c3b.jpg)

However, when I put this path in an svg file:
```svg
<svg xmlns="http://www.w3.org/2000/svg" style="fill:none" viewbox="-1 -1 2 2">
    <path fill="transparent" stroke="green" stroke-width=".01" d="M .8,1
    A .25,.25 0 0,0 1,.8
    L 1,-.3
    A .2,.2 0 0,0 .6,-.3
    L.6,.3
    L-.6,-.9
    A .21,.21 0 0,0 -.9,-.6
    L.3,.6
    L-.3,.6
    A .2,.2 0 0,0 -.3,1
    Z
    "/>
    <path fill="transparent" stroke="red" stroke-width=".01" d="M .8,-1
    A .25,.25 0 0,1 1,-.8
    L 1,.3
    A .2,.2 0 0,1 .6,.3
    L.6,-.3
    L-.6,.9
    A .21,.21 0 0,1 -.9,.6
    L.3,-.6
    L-.3,-.6
    A .2,.2 0 0,1 -.3,-1
    Z
    "/>
</svg>
```
That render like this:

![selection_001](https://user-images.githubusercontent.com/6391294/44589617-4bf5fa00-a7b9-11e8-8be4-080e98fc2942.png)

Their are a diff rendering the arc path.

It seems it's due to a miss interpretation of the sweep flag from `A .25,.25 0 0,0 1,.8` => `A .25,.25 0 1,0 1,.8`

**Comment by jheer** [comment]
Thank you! This was due to a bone-headed bug I inadvertently introduced when adding support for scaling path definitions. This has been fixed in vega-scenegraph and will be included in the next Vega release.

However, please also note that the paths in your Vega spec and the paths in your SVG example are not the same. When I use the path definitions in your SVG example I now get matching output in Vega.
