### ISSUE TITLE
Word cloud doesn't show special characters

### ISSUE THREAD

**Issue by tuomastik** [vega/vega#1409]
Here is an example of the issue: https://gist.github.com/tuomastik/13a3b8ca1458fb7ca3f0b096ea646987

**Comment by domoritz** [comment]
Thank you. Can you send us the Vega spec itself rather than the notebook? It'll make it easier to debug and resolve this issue.

**Comment by tuomastik** [comment]
> Thank you. Can you send us the Vega spec itself rather than the notebook? It'll make it easier to debug and resolve this issue.

```
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "width": 800,
  "height": 400,
  "padding": 0,

  "data": [
    {
      "name": "table",
      "values": ["Normal text", "ä", "ö", "&", "?", "-", "¤"],
      "transform": [
        {
          "type": "countpattern",
          "field": "data",
          "case": "lower",
        },
        {
          "type": "formula", "as": "weight",
          "expr": "if(datum.text=='VEGA', 600, 300)"
        }
      ]
    }
  ],

  "scales": [
    {
      "name": "color",
      "type": "ordinal",
      "range": ["#d5a928", "#652c90", "#939597"]
    }
  ],

  "marks": [
    {
      "type": "text",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "text": {"field": "text"},
          "align": {"value": "center"},
          "baseline": {"value": "alphabetic"},
          "fill": {"scale": "color", "field": "text"},
          "tooltip": {"signal": "'Count: ' + datum.count"}
        },
        "update": {
          "fillOpacity": {"value": 1}
        },
        "hover": {
          "fillOpacity": {"value": 0.5}
        }
      },
      "transform": [
        {
          "type": "wordcloud",
          "size": [800, 400],
          "text": {"field": "text"},
          "rotate": {"field": "datum.angle"},
          "font": "Helvetica Neue, Arial",
          "fontSize": {"field": "datum.count"},
          "fontWeight": {"field": "datum.weight"},
          "fontSizeRange": [50, 70],
          "padding": 2
        }
      ]
    }
  ]
}
```

**Comment by jheer** [comment]
The issue here resides not with the `wordcloud` layout, but with the `countpattern` transform's default `"pattern"` parameter. The default tries to isolate only "word" characters, stripping out punctuation characters as well as other unicode ranges. You can change the pattern parameter to achieve different results. For example, simply adding `"pattern": ".+"` to the countpattern transform will show all characters, but will no longer split "normal text" into separate words.

**Comment by tuomastik** [comment]
Thank you @jheer!

**Comment by jbenavidesv87** [comment]
@tuomastik, maybe this is too late, but in my case, i needed to add spanish words without breaking them, so i changed the pattern from `"pattern": "[\\w]+"` to `"pattern": "[\\w\á\é\í\ó\ú]+"`, that means words including á, ..., ú characters in them.
