### ISSUE TITLE
Custom content-type for vega JSON

### ISSUE THREAD

**Issue by CMCDragonkai** [vega/vega#1412]
I'm thinking of outputting Vega spec JSON from my APIs which can later render graphs. However I want to have a proper content type for the Vega JSON, that is differentiated from normal JSON. Can there be a custom vega content type?

https://www.iana.org/form/media-types

**Comment by domoritz** [comment]
Vega and Vega-Lite have schemas that you can use and we also sometimes use .vg and .vl file name extensions. Jupyterlab has a custom mime type for Vega. I doubt that iana will standardised Vega soon, though.

**Comment by CMCDragonkai** [comment]
What's the mimetype provided by JupyterLab? You can always submit the desired mimetype to the form above.

**Comment by domoritz** [comment]
`application/vnd.vega.v4+json` see https://github.com/jupyterlab/jupyterlab/blob/master/packages/vega4-extension/src/index.ts

**Comment by jheer** [comment]
Closing out issue here. Please feel free to respond / update if there are new developments, including acceptance of a custom MIME type by IANA.
