### ISSUE TITLE
How to merge the two arrays into one

### ISSUE THREAD

**Issue by yzpnet** [vega/vega#1413]
How to merge the two arrays into one in vega

for example:
[
  {"a","1"},
  {"b","1"},
  {"c","1"},
]

merge

[
  {"d","1"},
  {"e","1"},
  {"f","1"},
]

into

[
  {"a","1"},
  {"b","1"},
  {"c","1"},
  {"d","1"},
  {"e","1"},
  {"f","1"},
]

**Comment by domoritz** [comment]
Thank you for the feature request. I believe this is a duplicate of https://github.com/vega/vega/issues/554. Please let me know if you don't think it is.

**Comment by domoritz** [comment]
It has not been implemented yet.
