### ISSUE TITLE
Request trim & split string expression functions

### ISSUE THREAD

**Issue by roying** [vega/vega#1414]
Vega v4.2.0 has a number of string expressions:
   https://vega.github.io/vega/docs/expressions/#string-functions

Could trim() and split() be included?

**Comment by domoritz** [comment]
We always consider pull requests for new expressions. Also, note that you can use the extension API to add new functions to Vega until they are added and released.

**Comment by jheer** [comment]
Split was added in v4.3. It would make sense to add trim, too.
