### ISSUE TITLE
data.format.parse does not work when injecting data through the view API

### ISSUE THREAD

**Issue by rawenous** [vega/vega#1416]
I can't seem to enter time as a string using format and parse when injecting data through the view API.

This works fine when entering the data directly in the spec. 

```json
 "data": [
    {
      "name": "table",
      "format": { "type": "json", "parse": {"time":"date"}}
    }
  ]
```
But using the view API the format directive does not seem to work. The current work around is to do like this:

```javascript
var data = [
{"time": "2018-08-19", "amount": 74, "name": "adam"},
{"time": "2018-08-20", "amount": 150, "name": "adam"}
];
var currentData = view.data('table').slice();
data.forEach(x => x.time = Date.parse(x.time));
var changeSet = vega.changeset().insert(data).remove(currentData);
view.change('table', changeSet).run();
```
If this is not supposed to work then I suggest the documentation is updated to reflect this?

This is my spec. I tried  transform using the date expression but they also expect time in milliseconds.
```json
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "width": 500,
  "height": 200,
  "padding": 5,
  "background": "transparent",
  "data": [
    {
      "name": "table",
      "format": { "type": "json", "parse": {"time":"date"}},
      "values":[{"time": "2018-08-19", "amount": 74, "name": "adam"},
      {"time": "2018-08-20", "amount": 150, "name": "adam"}]
  }
  ],
  "scales": [
    {
      "name": "x",
      "type": "time",
      "range": "width",      
      "domain": {"data": "table", "field": "time"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "zero": true,
      "domain": {"data": "table", "field": "amount"}      
    },
    {
      "name": "color",
      "type": "ordinal",
      "range": {"scheme":"greys"},
      "domain": {"data": "table", "field": "name"}
    }
  ],
  "axes": [
    {"orient": "bottom", "scale": "x", "format": "%b %d","domainOpacity":0.3},
    {"orient": "right", "scale": "y", "grid": true, "domain":false, "ticks": false}
  ],

    "marks": [
    {
        "type": "group",
        "from": {
          "facet": {
            "name": "series",
            "data": "table",
            "groupby": "name"
          }
          },
          "marks" : [
          {
            "type": "line",
            "from": {"data": "series"},
            "encode": {
              "enter": {
                "x": {"scale": "x", "field": "time"},
                "y": {"scale": "y", "field": "amount"},           
                "strokeWidth": {"value": 2}           
             },
              "update": {               
                "strokeOpacity": {"value": 1.0},
                "stroke": {"scale": "color", "field": "name"}
              },
              "hover": {
                "strokeOpacity": {"value": 1.0},
                "stroke" :{"value": "#0082F0"}
               }
            } 
          }                
          ]
        }
    ]
  }
```

**Comment by jheer** [comment]
Thanks! The View API expects pre-parsed data, injected as one or more JavaScript objects. The format instructions are only applied on load of external (or embedded) data sets. I agree that the documentation should be improved to make this clear! I have correspondingly updated https://vega.github.io/vega/docs/api/view/

**Comment by vincerubinetti** [comment]
@jheer Not sure if this is related, but didn't want to make a new issue.

I'm using Vega to make a force-directed-graph visualization. I noticed when you import data [like this](https://vega.github.io/editor/data/miserables.json) inline with the spec, Vega seems to go through the `links` and replace the `node.id`'s with references to the actual `node` objects. But when you add/remove/change data through `view.data.add/remove/change`, it doesn't go through this "linking" process, I suspect out of the same philosophy as you state above: `The View API expects pre-parsed data`.

Is that internal Vega "linking" process exposed in any way? Is there a way I can trigger it any time the input data changes?
