### ISSUE TITLE
Statistical distributions in Vega expressions

### ISSUE THREAD

**Issue by naveedpash** [vega/vega#1419]
Hello all,
First of all, AMAZING work and thank you all contributors for Vega-lite

I am trying to build a [funnel plot](https://stats.stackexchange.com/questions/5195/how-to-draw-funnel-plot-using-ggplot2-in-r). 

I'm doing this using data scrapped from the [US surgeon scorecard website](url) with the objective of comparing surgeon adjusted complication rate across varying surgeon experience (number of cases performed that year). The idea is that a surgeon with lower experience is bound to have a higher complication rate but a funnel plot will help put that into perspective by putting area encoding channel representing the 95% confidence interval. The x axis is a increasing sample size and the y-axis is the variable of interest (the adjusted complication score of the surgeons). The plot shows the surgeon complication rate as the number of operated cases per surgeon increases. Therefore this is not the same as the currently provided ci0 and ci1 transforms.

The area encoding channel is obtained by cross-meshing the complication rates with the number of cases (something that can be achieved with fold transform) and then using it to compute probabilities from a distribution of choice (in my case the t-distribution). The complication rates with p values > 95% and < 5% are then used for the area encoding channel.

I know I can achieve this in python or R and feed the results into Vega (slash altair) but I thought this should be feature of Vega since the purpose of this calculation is solely visualization and nothing else. It doesn't belong anywhere else in my code.

Does any one have suggestions acheive this with the current features available?

The following is my data set and incomplete funnel plot:

**Comment by jheer** [comment]
Vega only has limited statistical distribution support built-in. It does not include the t-distribution, for example. You might try creating a custom `formula` transform with the desired math to calculate the values you need (perhaps over the output of an `aggregate` or `joinaggregate` transform, if needed). It's a bit unruly, but workable. In the past, I've put the normal PDF equation into a formula to plot a theoretical curve.
