### ISSUE TITLE
Title pans while dragging or zooming in the map

### ISSUE THREAD

**Issue by mattijn** [vega/vega#1420]
Cross-posting of https://github.com/vega/vega-lite/issues/4173

Observe the behavior of the title when panning or zooming in the map
![46018933-4acb2c00-c0db-11e8-9d36-5aea6694dd8d](https://user-images.githubusercontent.com/5186265/46035678-e83a5600-c103-11e8-90ca-09c9d66ee2cf.gif)

This can be reproduced with the following spec+data: [long-url](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL6DW4KJQCG1CaRzwJAWwKlIk6QFoA7ADYmiBgFZo0AIx8ATHwEBOTZQBGDTQQfQJEhicoGGADkgiYpAKEgBOANaykNQAngAOyliQADbI8MrskGnUBKFxsMlSiVCp6WEBohCQBPBwlGnoWKAQVXDJsKFRsQkq8LAKaRLJkJkoBMmUKqn2oWExFWJVAB5d8cXRBAr5s8OjhBMqaZQEK4EtUPNN0WsqAI4ArhLw1MjSL7gZUGMHSfBxCuo0gBnaTJZJAgJiM5QIHjAjQF4IWSLGFwhEdFjaZHnKrddbZXK4IYjFFVexHFRAtzJAgQyo46q1WD1eCoCFYADakBWmXmAF16edIEikhyFLB7rDKLAiPB2BR4NKiBhxZKCPc4nywAA+MAKpUqiWw8UfACEJJxUGos3gQMKORUYqNLhlcr1RxlhrVGq1uv1ntVxtgZotDIAXrB+ioiJxxubBS1gmFIlcUGCVABiKx8EZfZBggDycQk0FelzATAAdCZzAZMiDQrBwusY69lNChaFaQUPipUO17MSUYIofToq8ab1-oDbaDwaHIAASKmcEIqHjUOJAjAAeh3H1QEkrqFetHu9kryFgO5Xmwk+4Ih-UqRy+-Mle0larACsgUix2oEiwtQ7LYCiqhSBIWi6PoRimBYVhMLYDhOC49huB4Xg+P4nKkmBlpVEcJwqOYTBmOoNYUdYAAqLAYHRLChpaKTIDMcwqF2Ja8AmQp-ACwJzqB8D3GCPGJiCYRAuoCDqCedDnqQ5jaCYTB4R2LTNARWSKsRSSkeRlEmDRDFMPRTBMQy0yzKE5Z4PcBDqL+Fm8dOAlDPOWDCaJeFVBJoRSTJclnvYpBeckaliZpzFESselkQw6hMHwFHmLRpkmc5iZWexSS4PZjl0j5UB8TOElgkJInJGJvnSP50nwLJp4KVgSkqRFeFRQyMUkfFiXJTWaVmWZmVVNlNkcQQXEjcVrmzu5FXeQRMK1QFDVBc1YB8NYhjtZanVCt1cUmAlTAJeYviDRl1UlKx1m2ZxCLTZAJVueVoWVddkB+atjXySFWAGOdqmWupED7Ymh1QPpJ1nRdJnDZ9Y22XlDlOZ9L1zW9nkfUVX0rfVv3BYpvgsJWmjHedBjkww53aLtOLg4ROmxVDvVIX1l3peZiO3TlUAPdxuMY2VHlgGFn3fQT63-WAmjWAYwM4qD+FaZDkDQ4l1gc-DjE82x425flaNC7NIsLVVuOS4FTUy+Y1jWCYlY074VMUy75N0yDkW42rGuUadnMI7jSMqCjBVPcLgnvYtWlW2tNv8CYvjvm7rvO1T9PnIzUC+71-sMIHuvB7zBv85Nj3o6bUfYzHzFx4TG0qdopGZxpPvMz1JgGIlJjqHwJiF9zxf68jRuFUtz1V-N0cWxP9fS-wfCaO+7up9TfCt2D7fHCz6tkd3ZF9wPOtDxPIdJALEdT1jYs43P+PW39pAmEZBgGJvKvRR3R0H+YiWpSfJ658oBh2NhPSO08a6z1jg-eOT8sB8AMNoPglY06U2pudBgH9s7aR3p3X+-9B5AJLvdcugtwHX1FuLS2sCG4yzMHbRW5xlY4Nzl3f+6hzpEL1ndCaU1K78UxqLF+9tfAS1oQvLAx1m7vy9h1beulWbsKYH-LhgCeF8zsqjceWkIE3wYNtbQ4jJJSwTggzQPhKzoLXsdbBCjd76QPslJgBhuHD14RfMhV9BFm2fio8wDBPx1hoSYx+RMpEGGsLoOxE82FOMSq49R7jNGgJ0cxPRotdC6GMXVMJG0to7TkXtex+C+pHzcWfEhfCK4mx8dXMARkAnyxyT9SRDTl7yxiarb+Sj4n9wqVpYBWjw4CNKvU8mmgGAtNMfAsAnhEFkxsc7T2StvaxJ6XvZRCUTCaAGcxIZqTvFjMgbLJgmhNCoOmXkmWDALCfnThg925gulfzwT-RK2zdlJMqSPap5DdGUNAuYEwyDTqXJCbkuB4SGm+FBS8rqGzHEfL7kwPZlkqmG20Uc16mTrC+BMFcqFG1DA7OrA8te8KDqIv3sigQaKhRDMvqMnFQLmAvymRC1pZiGnyzakUhmJT3kuPKd8wZGKQFj2xUI0ChiCWcpmdCpwZzKyr3JbcylENqXKO7v00V+zxWQCZbU45N9zCaF8DoMR8rrmKSStYJhLQWGCt6YlbQiU4ZcyDj8jxEqsXMulc-CmHL76hKJTc3weLUGPLQb4DVTM3kuqYG6pgHqhpF29Zoo1FC6knIQkhNg1qw2KRrJoB1EAnXrITZsg+bq6V6vRb8zFIzjUsuflYC1hK6GkAVhGqxqrrFYP5VnZ11bXUovpVlA1WaAU5pvnwbQkyaydracC6wS9UFxpzlqg+mhx31oZQaw5-rfFSN8L4BgDBwUhshV2gGQNN24MUaOs5e7PXprFY2su-CW0BqwMwKwfhl3cvMEpFxD64mJV3bqt9p8P0+sNV4499TbnWEwUB2ZlgzXvlkas+Rlan1IpfdBtNsH9WfuGWAmdJrRYBIEOYdD0Kqa1nA9u91kGJ2jUPZKpDJydnHStderlszlKlpY1Wwjvh2P7sneR6d6TAWMD8EvXwV6YGhtvWASw20y1gArd08TNKU0ipg8Q8jR6f0nrAPbbaDGNraGUjh5haz9MEcM5J4jV1kmlwQ9+7N1HQKGEmZoPgtnbZKZ03p15rnlFazrSZjR3nzN+dbVIgx9tQukFLdEodbd8MOMM7F1F0nOOycQxZ+pBgdm1gE2pm9K6mMRec1F-L7CVLa3i150efryu8YMBG6wlZsxDaG8G2rQnoUWLAzlreeXSltaShxm6pXfNUZS2AN+FgWAZZavZvluHimzfeW1uLJHTPwaS6t39DSF32w-PZ+7D3tA1brhI7lcsFZiei93Y7RWOsZu83JhkGTQJ9YdjTbbmnJuNbwy5lr32mDGdOwlrrzbktXZ2aWgtgmFUbVhaSxzjqmsIoM61hHHmuZnczWVtHlmZEptGy99TK7fBbWhwd2Hc3e7AsWyxMz3GetzppspCHqGXafbhxRLnx8-twapyt+Ts7RbkyQsF1TjO6vAdF2zgVh2XUv1fUjzrod+c04qymkDIv5bYfF5zg3nn-ukPl0DhTWA5ZPeQRDu220LkE-LUTqlJPvuqK+TLsj8HAcuUV6BfFSlm4Q4EA5m3R3g884OSby7lme2lrVwyee3Km4t2m5-YnX2UqI-t7LxL6eFf+e7UhIyEOX5d0HftnXHPk-l4p8jv5UrLPJ3PcLwtGn+7nWt0X1hWrk29xUqnrj3XTcnIMX1uV2ObVSJBWepPSip8UV+4bh3PeeM322grZpQ+2n93ltr4duvNk7-J16yvjuakL5vk3Kr1h4+tR91vu-PdO+P5h4pLV7O5R6MDJy3KN4gYga-76TJqqLGSh4Nrh7U4Z71IqQn4BLx4WBi7j4jpwEcJ2yz7LYv5oG8YlqX7YFW4bp4G34EEqKcKIH75P7G7z5kGmp4pJRQEWIrJOYw7NadzwGMHEHnYgGR615-ogYkx3aPYPYM656vazIML2qwFkTJrOLS7MFAFV5sE15rY+AWIqbDbGGN5bRUw0Gt437t7b5lJkQiFy6kF6Ho61jApnrx6BKF6WG5bWF-5JQAHvraHP7-JOGWZmDnIuKaDx6RJvyqEgplIP4BHIHAG6GgESFgALqWBGLn754eG+66b+6aok7JrbJ74V6BGH4C7CKGD2zmHGFDbx4dLX7eECFHTFG772E6Go7sFK7aBrpVh1H1HZFKGAyoYWF8Hs4tE2GnScIh5aFJGdGUYhH1KwrNyXqyEPaRFDHQpdxRJNEzY+H0FnSzFlHzFBG97oE+DoIyGyGbGr5FoIL4okyxFtEnYnEHokHBGpFrYgq1iGHx72qia0EHFqG0qlFd5G5NqLFfFXZRKUFbGNz2ZmpjGE78El4tbJrdxqJIHvEoFO7iHfHaAGCIJro55Ch56zJbS7HPEJKcKppvEyaiEpH4no4qQuGN4dJ5GRZomCE0kJGkanGsFdFLG8YBJJzBJ3EaY7JRJj5eH7GTG+E6qaH0kla4mOHQmhFPYUyf7wk3JGRgrArNw-FGnUlJofIdFnFH7CJPYWICCkniSKGKp8Dnoqa3K0ZunqpAnyn0HFHmmClQnMmhE4HkyN6woCAmm1pgmAECmQlpLqnoGeBvy3FjY470I1F7HF4B7RbJoRm+meJ4mJjA7Py9HzoWAQ6BajHaB+CVmwpVmckFHxpZmQacJKngkH55lqkBnoGTK1hRJlnnLzoqrVlDl+CaAmm7rc7FZLaMlClxm8ZLynT0Y6nFpmrpkT5FFNl8mU4A6oHClv5yxdzZJLl-pRL4pfj4opoqTnmxqencmtEbktlRk4nJEzmdlzkuFJnq7jYbQga6B1momZnolsavGtksExnnFzmVnLye4FKrn4EglGbAWPkMkOGfGvlv7ywKyBIQ6VYyJWK2B2wdIdImnuYPmJFPkLGxloVVGnQ7Ke6AwWLEX+H8nkUWmVFAovwuyllHnraIK9GoJmCVaIICUmAmmFa5lfodkFku6abHQWCRrinJlr7rZvxmBkwEXqW2B8At7jFt5enwViWTm87Tn+lSVgFSJLyTJZESkrq7awV0H6V24gXlFgWWmgQCVnIKWfkpmKRyyFKykZmFGNnsyIVkXIXbn5lVCFktQb5JqeUKFM7cpUyBaVgn6pXVF-kTG3k2FtYBLiU+aSWRXSXQEWByzYXaYpyGmVUGnUk5UFyGVp5MmmVpEgoIQoJxVkkOnfla41Vk6kXMVhWsWv40ZmrnproQ7KRaWfjKbTXmpOk9VMVbko4mWFVmU8pmCobx5Jpdw1XT50lOXRkSWoVNVrYBLAoGHjVyVViRLVE3WRI7UUR7VIUqnPnLUzSrWkS8pY6KX3GbSvx2XAlxH64hX9XPUUXgWmpmrNzPbxUa4Uk4EZW6VZV-5A2RmhWg2DXdFApIKBJkTjWAxaUqqXlE0Xk1V-w7J5UXa7k0aIJ9YhbcWTWeE6VWF6WA1k3HH7UsUVFDWsos7zryEdUJXCYTIDYqKlorkrkbw3kAU8mUSbnd7tlHUrVpEBIqIlrjUOyWBWKuna0WDaUomZXS13my19WLV+mUXHVXa0ZEnQ0C2w3QrEkxFS2BUta7qHwgoU1iEW2WZKRnUGB2k1SC322NGxGu3T7aB5UR5e31Kx79wLr+3LSB0bTK5x23VpWjlO0Nku3-5y0Qm+ovlR0nJAz9nx6wrMYZ1bok6h0LXy2HXg00aoY0wpoQ7BZkSOwLpII8E8HXn+VrnRau1-xIQR07mzkcG3JIQqbtX2mJ0yyTIYUqoOwRpJwOzWAh0cKD31Vz751K1rb9x3IDaT0B1235L2zZY91wU7KEGPVo1TkoV11ApRJGQRrN29GkzE1XkiXl2PpZ0MFYlzGc0uVsX8CBb2ZllOnyxkzzrnrAouJmqr1+E51tm12uX8CVlOlWDN1noXqDbum60WBwPJQIOgV52vWTyrWVa2CD7WXcpOAs6OxOCQM0wqRElwMJTA2m0K1338DyzBaRIQ4kzmoT3MA+AuJCOS1n32UX3TFsM10Ubm3b1XYXoWqwrYU7Jx3QOAzIJdxyxwOKke2NXyOZ7LzzqLlUOzKJkqIpX0NPaMNTbiMA2u26Mb0fGcN-qBJZ58NmoWBkwd0+MLq8H62I2G1KKu05lOOqmK1vVpEGLVaEl8OBI6ApWEUaXp12Ms0hOOVPU31g3IMAwkwRr81T1H0yyRLIIqbWPqNKR4Of1sKu1QYm0yOU0j2ZK6BJofkw1fkyzIJJVOwVOaN9ZwN1ND0RWRNrZOD2ZOlfVeVKUrHArViL3zPL1wMkV6Nb0jNXalr2oe7cXt0qTVhUz5PBbWNLPV2535UROkNpGAznpkR02mPQpnpIJ+1CPPMiMf2pNI36Su0GXYkDVm0uNgAx5IIr7fUabUyGDz1WNQNvNM3NEfNkRfMZPX1GW305PKX4pJwFOH0dOkD2qn4fgGkEstWr3Hb1OnONNUXR6TI0yYsJ1FOZbW1t39z7Pe5LzEu9VDMFVrOWalrMCeCTPtPeVYAN1EkqozUs7mp61+7-nO2dy7oo0rMkNRUNJnKVlbN3NJ1rqkoMO9OSv5HSuZ2yuS6Isg1ZMY1U2gSHPjMH20vYtCsoYqYiOOvCMI3M1wsX3G0KtyNcvoGnSbNWUgttIs61goJMOVNaMr3VNapyt-yEPOVIOANYAiZISAwi7II0xWJi2Zui2xGSaHyxsHWyP-MiICDBZ8Pkxnoqo2MaOx05vZ2kuINnP-MWKWCWoi7973I1mdvVm1s-1X0mvIvZMJvKv4rMAmMBvcoOw1iXrMuQsenvNBObK5uqJ9vsPxvc2ZYWo4VjtTM-UqQqK2lZvi0pMwtyluu5sEP1tEOFuotdwd0s4i4Ky6CDZaMHOQM9sXscvnNKu2DMDnI0t4zT1+LAqTIpVL1gcRrPKRsk65usOo39sNWrMXPfEXpWBQXcV4on1fjVsvudJQfRYwfGuruNuoucHnRJyN40VGTVhCU0eCU9uOM-Po1-M3tLy3IdrcWsmatkyvvlPQsBOusLv6S5sMd-2-McMkdOmwpP0cdJpJooK0fCWII9uhOMemvMdDvN5ZJtO222vKvu4+5hszvd0nsBUGtHS5sqeidMficaceUGJdwUckzKq+Od0Zx4cta5uDNhMvVetIfo6AuVmN6XlJRWJ9Pmre4uuwuCdkSecnMNuR0GPoFdy1hikUc1GOyzWZfisRvzsyvmeaycKJKqcDtLW+dKtJw1jY1Bf0M5cme90ecFe1iftFvJeVYuxBdL3+Plooh8hQggCCBAA)

The y-axis domains push the title upwards when the top value of the y-domain is on the top of the chart frame and also push it side-wards when y-axis domain values increase or reduce by tenfold.

**Comment by jheer** [comment]
Thanks! This happens because the title is being positioned relative to the overall chart bounds. As you pan/zoom the display the axis labels are changing, which subtly changes the computed bounding box with which the title position is calculated.

There are a few possible solutions to this:

1. At the Vega level, change the `title` definition to use `"frame": "group"` rather than `"frame": "bounds"`. This will position the title relative to the primary width/height signals, rather than the dynamically calculated bounds. If Vega-Lite does not expose this control, feel free to file issue on that project.

2. Adjust the axis labels to use flush layout, so that they do not exceed the corresponding chart bounds. See the Vega axis documentation for more.

I hope that helps!
