### ISSUE TITLE
Using autosize: fit and containerSize() causes filter select bug

### ISSUE THREAD

**Issue by eharkins** [vega/vega#1421]
As it says in https://github.com/vega/vega/pull/1248, #1213 was resolved and setting the width signal to update with `containerSize()` as is done here (https://github.com/vega/vega/issues/1325#issuecomment-408374134), in addition to setting `autosize: fit` in order to get a plot to fit exactly (including padding, legends, etc) into the size of its container works. However, when using a filtering select like https://vega.github.io/vega-lite/docs/selection.html#filtering-data, the selected area will shift to a different range of values on the first resize event. I'm wondering if this has to do with the width signal being updated by window resize events, as well as the `autosize: fit` and any updates it may make to fit the view into its container. The width signal reflects a discrepancy between two values when updating, which may have to do with it being updated from multiple sources. This issue is not the case with `autosize: pad`, so I am wondering if it could be a bug related to how `autosize: fit` updates the width signal or if I am misinterpreting how to take advantage of both `autosize: fit` and `containerSize()`.

**Comment by jheer** [comment]
Thanks! I'll keep this issue open for now. Please share a replicating example if you can.

**Comment by eharkins** [comment]
Update: this is in fact also an issue with `autosize: pad` and does not just happen on the first resize event. My latest thought is that the way the `brush_{x,y}` signals are getting updated when the width signal changes does not necessarily map the new width with the range of selected values to the correct unscaled x,y coordinates within the viz. By default with this type of filter select, it appears that the `brush_{x,y}` signals are `clamp`ed on the `width` but not set up to recompute from the range of values they should cover according to their corresponding scales. The best idea I could think of to persist a selection when the `width` or `height` has changed (I have not implemented this): update the unscaled coordinates of `brush_{x,y}` based on the signal containing the scaled range of values that should remain selected when the size changes. Currently, these unscaled coordinates, `brush_{x,y}`, are the coordinates used to draw the selection, and the coordinates used to find scaled values for the selected range (called `brush_{x,y}_field` in the example below).
```
 {
      "name": "brush_x",
      "value": [],
      "on": [
        {
          "events": {
            "source": "scope",
            "type": "mousedown",
            "filter": [
              "!event.item || event.item.mark.name !== \"brush_brush\""
            ]
          },
          "update": "[x(unit), x(unit)]"
        },
        {
          "events": {
            "source": "window",
            "type": "mousemove",
            "consume": true,
            "between": [
              {
                "source": "scope",
                "type": "mousedown",
                "filter": [
                  "!event.item || event.item.mark.name !== \"brush_brush\""
                ]
              },
              {
                "source": "window",
                "type": "mouseup"
              }
            ]
          },
          "update": "[brush_x[0], clamp(x(unit), 0, width)]"
        },
        {
          "events": {
            "signal": "brush_scale_trigger"
          },
          "update": "[scale(\"x\", brush_x_field[0]), scale(\"x\", brush_x_field[1])]"
        },
        {
          "events": {
            "signal": "brush_translate_delta"
          },
          "update": "clampRange(panLinear(brush_translate_anchor.extent_x, brush_translate_delta.x / span(brush_translate_anchor.extent_x)), 0, width)"
        },
        {
          "events": {
            "signal": "brush_zoom_delta"
          },
          "update": "clampRange(zoomLinear(brush_x, brush_zoom_anchor.x, brush_zoom_delta), 0, width)"
        }
      ]
    },
    {
      "name": "brush_x_field",
      "on": [
        {
          "events": {
            "signal": "brush_x"
          },
          "update": "brush_x[0] === brush_x[1] ? null : invert(\"x\", brush_x)"
        }
      ]
    },
```
Maybe making the signals more dependent on the scaled range of values than the unscaled coordinates would make things more robust on resize. If the source of truth is the range of scaled values to be selected, this can be more strictly updated only when the signals for creating / changing a selection are updated. Meanwhile, the unscaled coordinates to draw the selection on the screen can be a function of this scaled range of selected values, and the size of the viz.

Thanks for your response and please let me know if I should clarify anything here.

Here is an example of the unwanted effect:
Here is a selection before resizing the window (note it ranges from ~42k to ~44k and does not include the right datum)
![screen shot 2018-10-08 at 12 02 42 pm](https://user-images.githubusercontent.com/12140437/46630903-95e13800-cafa-11e8-9560-cfb42b38359f.png)
Here is the same selection after having resized the screen (the range has shifted so now both data are selected without having manually changed the selection)
![screen shot 2018-10-08 at 12 04 23 pm](https://user-images.githubusercontent.com/12140437/46630955-c628d680-cafa-11e8-98c2-3c30d9e5e842.png)

**Comment by jheer** [comment]
I think I understand the issue and have a replication. Please let me know if this is correct:

1. Load this [example in the online editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBjWLAZwDoArCgewDtIBfAGnCgDcSmz58AbVAQIkCgFMcEkvACWTfCNFiARlgwUAFksjwAngAcJ+SHMbwJWLrDwtOEdg6gBbcgGtTh+uYEcVkBKMvNDmAOZKzmIAHroAZnJS0KYAEvSUEt4A7laQbHpGJqiQAI4YsBZyiPJcJk4qYvrxiTjJxQCyctIUAPrGWD0A4rY4ivkGxqZlFfLVcrWszvaObGjOelgVFHHpLkJRaJAJOJZYupLSsgrMxeqaOizLogC6-qKQbliexd6+eetBELhSINKCxVDKUFHFptKAAQRIJCkVgQ1zyUAmRSg00qcwWbyhFDI0l00HobnMQgADGwAEwAVmeTxU9QakCaEIOYgSSVMABE5BRDDhYEiXEE-AVJsUcbNUfiuVAibYsegyRSbmBBDSwPSqVSmQdmWAnixniAWEA).
2. Draw a brush somewhere in the top chart.
3. Open the JavaScript console and enter the following: `VEGA_DEBUG.view.width(400).run()`

The result is that the brush stays put in pixel space. It does not adjust its position to match the changed size.

Is this the "buggy" behavior you're reporting? If so, it is not a bug within Vega itself, but rather a limitation of how Vega-Lite defines its brushes and selections -- in which case please close out this issue and file an issue on the Vega-Lite repo (maybe with a title like "Interval selection brush extents do not update with changes of chart size")!

**Comment by eharkins** [comment]
Thanks @jheer, I didn't close this at first because for some reason I was convinced that for some reason I should have expected the brush selection signals to update on width change. I will open an issue in Vega-Lite. Sorry for the delay
