### ISSUE TITLE
Rendering time-series area plot with specified tooltip

### ISSUE THREAD

**Issue by aashidham** [vega/vega#1422]
My vega-embed spec looks like the following:

```
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "width": 500,
  "height": 200,
  "padding": 5,



  "data": [
    {
      "name": "table",
      "values": [
        {"u": "2018-01-01","v":2},
        {"u": "2018-01-02","v":1},
        {"u": "2018-01-03","v":2},
        {"u": "2018-01-04","v":2},
        {"u": "2018-01-05","v":3}
      ]
    }
  ],

  "scales": [
    {
      "name": "xscale",
      "type": "time",
      "range": "width",
      "zero": false,
      "nice":{"interval": "day"},
      "domain": {"data": "table", "field": "u"}
    },
    {
      "name": "yscale",
      "type": "linear",
      "range": "height",
      "nice": true,
      "zero": true,
      "domain": {"data": "table", "field": "v"}
    }
  ],

  "axes": [
    {"orient": "bottom", "scale": "xscale", "tickCount": 20},
    {"orient": "left", "scale": "yscale"}
  ],

  "marks": [
    {
      "type": "area",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "u"},
          "y": {"scale": "yscale", "field": "v"},
          "y2": {"scale": "yscale", "value": 0},
          "tooltip": {"signal": "'In this category: ' + datum.u + ' the value is '+datum.v"},
          "fill": {"value": "steelblue"}
        }
      }
    }
  ]
}

```

It returns no errors, but just renders an empty plot. Why does this not render any points? Am I not parsing the time data (column "u") correctly?

@kanitw @jheer @nyurik apologies for what might be a simple oversight, but insight would be appreciated

**Comment by roying** [comment]
The data field "u" has to be parsed as date, e.g.

```
  "data": [
    {
      "name": "table",
      "values": [
        {"u": "2018-01-01","v":2},
        {"u": "2018-01-02","v":1},
        {"u": "2018-01-03","v":2},
        {"u": "2018-01-04","v":2},
        {"u": "2018-01-05","v":3}
      ],
      "format": {"parse": { "u": "date:%Y-%m-%d"}}
    }
  ], 
```

See: https://vega.github.io/vega/docs/data/#format

**Comment by aashidham** [comment]
@roying @domoritz 
Got it, thanks. How do I adjust the `tooltip` property so I can parse `datum.u`? Right now, the tooltip displays a huge date string and I would like to format the date with a shorter string.

**Comment by domoritz** [comment]
You can use time format expressions.

**Comment by aashidham** [comment]
Yes I am aware. But where should I put these so that the tooltip will be able to use them in the datum variable?

I couldn’t find any info on this in the documentation. A code snippet using these formatting functions to change the tooltip rendering would be much appreciated. 

Aaditya

**Comment by roying** [comment]
Example:
`"tooltip": {"signal": "'In this category: ' + timeFormat(datum.u, '%b %d, %Y') + ' the value is '+datum.v"}`

See: 
https://vega.github.io/vega/docs/expressions/#string-functions
https://github.com/d3/d3-time-format/

**Comment by aashidham** [comment]
Thanks again. One final question: how do I format the x-axis correctly? I tried adding a `"format":"date:%Y-%m-%d",` inside the `scales` object, but the x-axis descriptions for each tick are still truncating each other, making the x-axis impossible to read. 

For example, the first tick reads '2018', then the next tick reads '06 AM' then '12 PM' then 'Tues'.

Generally, more time series examples in Vega (with actual timestamps, not just integers as years) would be tremendously helpful in the Vega examples gallery.

**Comment by roying** [comment]
Example:
```
  "axes": [
    {"orient": "bottom", 
    "scale": "xscale", 
    "format": "%Y-%m-%d",
    "tickCount": 5
    },
```
See: https://vega.github.io/vega/docs/axes/
