### ISSUE TITLE
Cross-filter example looks incorrect

### ISSUE THREAD

**Issue by zanarmstrong** [vega/vega#1427]
I was checking out the [interactive cross-filter flights example](https://vega.github.io/vega/examples/crossfilter-flights/) for Vega.

I noticed that when I selected a part of the middle "local departure hour" chart that appeared to have no data, I still saw data in the other charts. 

![wb10pqfdk8c](https://user-images.githubusercontent.com/7397271/46774906-a12e9200-ccb9-11e8-946f-03838bbce2b3.png)
 
Is it that there are one or two datapoints that fall in that range, but the max y-value on the histograms is so large that we can't see the difference between a count of 2 or 1 vs 0?

**Comment by jheer** [comment]
Yes, there are records in some of those bins, but so few that they are not clearly visible with a linear scale. If you [change the departure time histogram to use a `sqrt` scale you can see them](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KAHdGAExbYwAVgAMuxREiF0atYxnUt2xUsixG1GegA2sLQG0lEYFGepkLUgkdAAnPAAJZEd8BSgKV1ZAnABGfTAAX0MIMF9If2SoEPCABVNzSzjIBJck611M7J8-dACglBi8KtZCNXQ8QsgACmLI6Op8MABqMFGyswtqAEowACowAGZIRu9clracSDVkF3QATwBRAA8BmS75eMTCjwBaADYDMBSADl0AXR2OT2+VagzwjAC11u90etWenwATKIAVldnkCkFzLA8FDkHcqjU6jgPIjRPoUU1gRjDsdTmcAMoDQgEp5aNKUozsCxqLTASAWQisLqHULoSyBB6QVAWLQIyUYK6yz72JlsjKAnLo0FBcEBRnIZmSwmFFIcqBcmQ8nB8gVCoKi8VVaVyHC6OgImxQBWyyXYg1aN0e9WooFag5QLF4fWG2FEr76M2QC1W3L8mSC4VQB3UCVemU4PTy9CKnAIhNQP3Mgu6YOUsODWnnABKYpz3V6-QbJ3OuPxidknl2oaHQKgyCod3c1vsjmcLkx3bOAC1uNxUJAQ6OgZAen0BkEPENG2cW+KSX8psfTzmPCk-ktSAiwC8wMeV2uHkfF9fkOfL9-W1-O8HyfGY31XVA-kgEcIE3LdQC3bdxzxPApygAABY8sDUdgXHgFxGHgABrABCB5MMXAAhUJWFgRBsNw-DCNIhQYJyHcO33Q4PGPXs8HPB5eJuFDbz+KC2Lg0cEMQoxkMnA8KLpajaPo1BuFo5A1G4ZQZAeVRLW0rA1I0noAQAPjAfStOUIz1NgNBuCoEjWJkoxd07A8r0A89pjACwqHCIYAHJj3peBXGQIKHiuIYlhWF9-OQQKQsXMKIqisArjUqglkEgCzzvXzEuS0LwpcSLoti+K-JkAK8GC0r0ui7LkCWcSZMk4dXLHCdUIUrDjPs6zdMs7lDMG5BTLACyrPGuyHKclzXI4vdBg8Z0vzpABBGQkG4UIHmK+qUrpNLyoymK4tysAFU284dr2g6arqhrUrKirMqqtroI6kc-l2ST6wXOl33XI1WVdfsXTADxpK3SA5L6w5FPOLBlBQE4yLAFGzmUui0YxlxnLNNzOMGN1tDWMB0HYWAhlgEwZDuk9ALiqnCG0oYUjofRdE9RG6FpPB0AATXZzmUjeB4BaF9AAFluGOOKftHDJ-qBQH9i7bbdsQfaWThAMoc8OHRwR3q0MgHHbI04bibYlaPMOI7XtO96Lqqjc-oBustZ1CFkB-dtVv9yFhL7EdIAHYk2NN+HEbQvkHCcVxQ+QUGNxJ9j3K4qBD11QPvP+KYC5-USQOfMAC9Bz9S6Li864K+9H186uIPaxDOs1NjZItoJ0ILhi8II4isYHgO8fonDh+Y+3usd3PIA8Au+IEquA9Xu8O63LufB7nqUMtjxx4CSebaG7SRtmmyJqmmaxpv+aWrn5ac7Wxub3+IraqS46C7Oj6l1qouyCv-d2zVHKtQeB-ICAIZggLAU1T6bMEo-2Sog86ECcrb1VlnOOZsE4KUHhNYaekH7n0moQcyo0DKPw0s-JaMkF5rQ2gXB6esnoIIDgAj2V0Hi3TYbrfah00F-24eA5BcUcEa29hrX2IJwyQDbmuA2cYDCR2jjDfBvdD790HujZAmNyIFzPgYzGjCzZvyCBTKmNM6YMzFEMGBbN1gc2UFzHm+h+a9UFicYWYtXESylmAGWfj5aK1aksFWGt1Y5E1gosEAd2H63BobSGGjoawwdoQ5GxD5p2wsduKxztRHBQwYAz2GRZFxPkdSCMjBsRB0lMU+p2I+KFKgJorwMltHsRyamZOc5MQNLwBnXe2cyYHiPCMsuxdIxl2Ai3F8kYa5gGmY0+ul4ZneUWaBV8IzQbSJqbHfe5tdHI0jEPJio9yKRjPtPa5LEs6kxDtxSMq9-iCRGZvMS0TcEnPnv0pemERlnxIZfMhtCKF3xodZChDDnlQBaUveZ9dv4vRCiMnhlUUHPV-g1LFEisqQOuqipu6L8WYuxNiyRlcQGRhpcS7Bfy5EAuWkC4+lzwU6UhXC2+VDpqwrmvQyBL8mHIvWhYdZeBkmcNKVSqMRKvr8OLNK2VIiMUMqVVdI5sFqmwVqdqGkByIKqMKOo+GXTelnPkhckZBNDFE1uaCmi+MzFEw6S8p2UAbHrDsfTRm0qfwuLAG4jxvNvEoV8S4fx4t3GS2lj42WCslZRJHGrH2aI-bGuxLKs1RsMkm2yX3O12IKEFKzswoI9LCVIKAV7LcsSDVZoSUEJluZqgQzABas2VqbVIxUOQiaLVg7esgJdDcTbMhKD+LYIwe5MAxy6mbOpkAABmBEJh9UTKwUI84aT9BEBuzosAXhll0ERSQ0g5CJjwA6WAa79rriXYhXpRg8BnEIIMC0VQ12MBOCmI4i5PV9PDpmJOs5U40kXO08ZRhKy8hnCnfdEZUqqjg1AdAaEPBAbpLoKox4UiQCnaynppyP1fqCD+yUf6ANpxA7JMDiHBlQagCvJjGGVT+mnCxlDSjuHocRZALDnh+MBHw5KAuRGSPHLI-PCj36ZQ0f-S4QDkYxTwAlKc5ATGeOQb4+8jjQmEN6eQ8M6lgnTkieJEcEZEnWl4GkxJPB5HP2DHgKEbgsAH2MBjUlBjFZ9Ntr-X50IAX10qbUNh3D5wqgFwIyMjTgRZ2nIAI5JFCGcQc3UfBIaGdBukQcMO5d42nIriKStBZzXgIr+8ZN6sbQDGdc6KzvWw2iSOq66TqXuJHBTVGxQ8kTFpDA+YYYxay5JgOCXsRJeI4mbMgwOhbr+YDTrRrUNuwih0pRbmggERkMgMIO3POsEtFoO9SRhtrnQGNiDZmCs9iM5HRbQRVAaEQKtus63FHlJ2-1w4B2jthYW+pc7OBLvIGu6N6G938tsY3s9+Gr3Djvc0Jm5d25V1au27evbgOLDA5O2DlMkPoe3dh3l1jtm2lI7NijwdH3VvNZAHYDAoQiLtcx+xY4CBQiMEIOCTRkAAAii4wARBGdwagoowY-e1rFvHlHDgy-UoaSOeJ4ARN5Nku4-nrSnKyzx96+3zg9fzY9ybnS11rvspmMsnG0efdM-DyATvM6nOW7EF31PRhRE6B7+eIWUN8mNDqe9JhQgoQbZ3dNLXtwLuy6+052PFwvAtO4Yz6lQiaaCMerdmfyP3sfaEZ9MN957xy+xAHWZkDSBcFQELAwQcV-YrOfaJoKvsSb-rgZVWoBXB72FqpVfiu5Fb++-HmHqAy+EPuLvRhVc9HYEb8bx57MTekwvqARFkCr4mxvtQnmqxgDXa4eyreR+uXq9Oxt8f2IIAilz5P89V1nEf+VcLNfIBA+O0JkbFOiGielu6eFgmeUAtGqmQQWuZ2XQnGDOsMVOfGfu4wsQWQ3aN+V+QIKWkcxYdeSe8EUc-O0ehw7A3ABAKivoJuluACMe2B9+Rg7OnOBBUkrmyute8AvWr+G2E2k84Wmu2uBuVeCMeuYWQhVeUAq+oeXaNY2+kAXu4GSB0BiAYQYwAeY+RgweiGYehwAAxGuvAAYQYXQa5GPlWuIcISWH3g9q1hFK7OcDSl5GeP8FEhoQPgiMxv3vYO9PYQyBIk4TeMBCYb9N1Fgf8nJstN-lHpweFhYM3ugJwYwFQFoGfm4FDqcmup5mXnyMAZtucKATIO4JxgIccDrsIShL3m+mbFodODoRWAMCcLhHUGER1F3uYePhIQPsxtQXkX4bjhAZFsDOcPhm4eOh4cbttjQSbspnRpbkRpKNwDbnbloC8CkKMVId4ZMZIR-h2pAYBjAfiOseMQMj0ZAO-tMbGOai0bHqEc5mykwlEcgDEUJnEUlAkeCMkTgKkfZEJiUYUFUbJKIWURIWcdoTIaMQoZ4TYcECoeEP7itqMTUamHURFlHuwPzsRMEZ3G0S0gCexFYXDtTjsb4Y4flJ-PeIHiCe7rUV2msZfvvNcc2hEQ8VPpANEVwctK8aKIkZ8afufukYCrtIIR0TliIc3sCcIRsXUbIRPrgKgYoaVocCgeoXIUidIWkgMWiRiURFiTvDiZMhYaKQSUoYcMSSdA4f4WSbAq4XIdScibSYyarAyXccyYhLtuwUojphyUwlye8UkYUN8QKeykKaUYaUwhUWISKZKWCRqS8NoKMQMDcDGXGJAFtKEPzjUGAGLnSGss6DabKUmFhicITsmd+uQXgCooibIFGIwAAF7-GdoakpCiBVl3AADq8ppZQQegIxqpvmIejZKZuECROpjpMitxIRo4U6qIHW8MvOHmAuQu0MkAAAKgHBLlLjLq0DtquvFkroMEvurvHCGf8bruKWGWbBsTsabmcObqkimXudbrbsgPbjKfPHaYSXxu7pxpCT7sgbCWoQiUJmqYOWCBHmENHo6dcTOXOYeiwdzvDLuQHAUYXvPNILurnocPnvgKhZEcXk+vBS-iCY8fXo3r5uKXIe3lHj6AWUPlCa7oPuRf5mObJjlniZPh6egDPlHrQPPgWYeSvqJgXBvlJvNgWbvvvsJQRsfikfyfSd1JgX9AwbYeVM-vBCnjwecbjmwYMLAKluEOFgAXdkcHBYcAXChb+oMUqWDnAUJggZ+coaofCWgQ8P8BJEpazvDHgWpVJEQf+viKQeWZQSpYknqCbtcTgfDEwT5QhWbI8c8Rpb9hPK6p9r8SeRKcGeeVGaKVKeCXIb+dYa7sqUBbRf2V2XoUYYYfALqeEaKbiQWcaYqSFWUuIkgjAuePmZ0WMfRUST4aAq1ZguvAEAshSSxQ1qYS6URSyR6eyeFpkSotOLkWJsgBZZxr6TyQGfyWlVrqGdleGUCReUwiBSiX6I0YbGNRqPPPVV1Y1acX9jMVAWZQHL2Q1ccUnHdQNbsVZQjgEPMU+csTgKsesd0VsWcdeQ9fsTZZSZKW9ZsZ-ocFpZ-veVcfJRNa0fcW6fFd6W6etR8ZtWkdtcKXiWKZUQWblRqW+SCQVQ5UqQBc5bZaVS4AOSiX+lqcxDVaRnVQaXtctI1V4WaeUhlO1S4dDaKR+aBWqKjZOXqRjfDFjbEaIX6byYGYTbtcTRGRlfPOTWohCZ2X+Y5XCZ2YiWVTSRqaicgOiezRdWYddSCXzdCQLZ9ULQHCNZ1VSeoJoKbXGHSaPs6eja6XLayYmdjfDLjf6bJQTdpulYdQQgdTzUwtrYUHGQmV6eVVAAADLcBlRZkGiqG7rIBgBrkBBrJ6y7pu3CHsBFlA5p1JhBXritk1n1lp3NkN0dkB5e2DA9mi1B4m32lm3DmYnW1+03FTmZqzlmzzn86C48DLki6Ja7QF2S7YjS6y47k8GRj-asmHk7Z-Ga19Jx1VGgkTHw1QDdZ2jI3mbCwL1VCLHPmvmO4e3O6FXU7flCbU0mlFB01G3AW93qkPngVR6HHuUy2Ry5HdJTVunY4jIWVZ4YWDDYXbpF5igPoEUvrdTsVsaslR6kXIB0WUVOAd5aCiB9mhY9V8aMWkPW1d4YPumDBcWz68VaZdUCWr44aRiH4jJb7iV76X2H4yVfFyW+0KXANTnKVw34FoOsHcGKKI1MORGsm-4t7zxGWU5LWRgwMDGzFFBQ3wGAQmwf0wlOXf0YEiP0GeVmzeWEW5b7T+WZi10UFgwhWX20ERViPRVWPx3V5YNPEh0rrr0uoqT8HR2eNIQH1k1p2U3CHv1NWGOG0qmM3M1dqQD6FVXGFUOt7tE0P22u5mk46DVkrknl1Gmw0xO5O1r5PbJNyuFS0j0y0B1xXeMJXzxh3K1bUZFZFAGmUOarWq2nnlFhNdXHVJOnUuBNGBDpPCG22WEg0n006Kr9ERZaNzMvU3UlOnF5NfVLORh-VRxLEvkrFrFyFXmnGyOWVLMHEM1dVnBrOg2nMX2uhD0TnYmy0NMzU+MK3xEbUR0-FR07V9Oika0x3wyJ0Bi63t3P3-lGPxODO-0S1YWMBs2D2X76mvIhNmzZO9V2EKqOGVOFPd3LTi11E+05YsVQUubyaNO+PbgtP40-OCl-N73HlZU0MgsPP5V60QsG2AUuUJM12s0W3akc2sVXXc1ZNkNBBlPUr+G4vWn4tMKEsOk1M7yTXqUUsenB0fNvFfMCOR30tE0ZOAtovbisvPjxlyEasd1BArmihUAuBZnz2aa5m+Z15FPzyV32TV2WuBUONytumPp3D0h1kNlEstmqnVlt0rZetQBd3G1M010D2jlKtOnS05DTkzogBVJAA).
