### ISSUE TITLE
Initialize a bound signal with expression

### ISSUE THREAD

**Issue by arvind** [vega/vega#1435]
I need to be able to initialize bound signals using an expression. However, if I set a signal's `update` property, manipulating the query widget no longer updates the signal value (though, confusingly, the binding element _does_ update). Setting the `react: false` flag does not have any effect.

```json
{
  "signals": [
    {
      "name": "foo",
      "update": "1970+1",
      "bind": {"input": "range", "min": 1969, "max": 1981, "step": 1}
    }
  ]
}
```

**Comment by jheer** [comment]
This is possible using the `init` signal property, released in Vega v4.4.0.
