### ISSUE TITLE
Debug guide refers to "debug console" which appears missing in new online editor

### ISSUE THREAD

**Issue by meglin** [vega/vega#1439]
The current version of the [Debugging Guide](https://vega.github.io/vega/docs/api/debugging/) states "To access the view in the [online editor](https://vega.github.io/editor), open the debug console and use VEGA_DEBUG.view." However, I cannot find the debug console in the new editor (it is present in the [old editor](http://vega.github.io/vega-editor/)).

Thanks

**Comment by jheer** [comment]
This is simply referring to the standard JavaScript console provided by all modern web browsers. In Chrome, you can use the menu: View -> Developer -> JavaScript Console
