### ISSUE TITLE
Graph crashes due to floating point math

### ISSUE THREAD

**Issue by seanlaff** [vega/vega#1443]
The following graph will fail to render. However, if the first data point in `table` is changed from `null` to say `1` OR the last data point in `table` is changed from `0.1999800034490951` to say, `1`, the problem goes away.

I think the error is caused by the `range` calculation in the `y` scale, however I couldn't narrow the problematic code down across the vega repos, and I couldn't get any logs out of the online vega editor because every time I set `VEGA_DEBUG.view.logLevel(10);`, vega overwrites it when it redraws the visualization.

This only happens on the canvas renderer.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "width": 500,
  "height": 300,
  "scales": [
    {
      "name": "x",
      "type": "time",
      "range": [0, {"signal": "width"}],
      "domain": [1541013540000, 1541014200000]
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "zero": false,
      "domain": {"data": "table", "field": "value"}
    }
  ],
  "axes": [
    {"orient": "bottom", "scale": "x", "labelOverlap": true, "grid": true},
    {"orient": "left", "scale": "y"}
  ],
  "marks": [
    {
      "name": "mypoints",
      "type": "symbol",
      "style": ["point"],
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "stroke": {"value": "red"},
            "x": {"scale": "x", "field": "timestamp"},
            "y": {"scale": "y", "field": "value"}
        }
      }
    }
  ],
  "data": [
    {
      "name": "table",
      "values": [
        {
          "timestamp": 1541013715955.0002,
          "value": null
        },
        {
          "timestamp": 1541013905955.0002,
          "value": 0.2        },
        {
          "timestamp": 1541014095956,
          "value": 0.1999800034490951
        }
      ]
    }
  ]
}
```

**Comment by jheer** [comment]
The null value is being mapped to zero, which then causes that point to be rendered very far offscreen. This causes a "crash" with the canvas renderer because it results in the attempt to create a canvas far larger than what the browser allows. Solutions include (1) filtering out invalid values, (2) using `clip` property on your symbol marks to force clipping of the plotting region, or (3) using a different `autosize` type to avoid blowing up the view size. I recommend considering both (1) and (2) in particular. Hope that helps!

**Comment by seanlaff** [comment]
@jheer Thanks for the help! I think the `clip` is the most appropriate strategy for my use case since `null` values are important to me. However I run into this problem

<img width="593" alt="screen shot 2018-11-02 at 10 38 46 am" src="https://user-images.githubusercontent.com/3194832/47921715-aaabb400-de8b-11e8-9534-9d31a3d13d84.png">

Is there a good way to have vega intelligently add some buffer to my scales so the points aren't split in half- or should I handle that myself?

**Comment by jheer** [comment]
Sure, you can add scale padding to your x and y scales, e.g., `"padding": 5`.

For more, look under https://vega.github.io/vega/docs/scales/#quantitative

**Comment by seanlaff** [comment]
Since I my data was nulls, the correct solution was to set the `defined` flag on my line mark. I.e

```
defined: { signal: "datum.value !== null" }
```
