### ISSUE TITLE
Document if we can visualize already hierarchical data with the tree transform

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1446]
From the tree transform document, 

> Internally, this transform processes a collection of special tree node objects generated by an upstream nest or stratify transform.

But since Vega marks expects an array of data for `marks`, it seems like we can't visualize if the data is already hierarchical like this:

```
{
  "name": "A",
  "children": [{
    "name": "B",
    "children": []
  }, {
    "name": "C",
    "children": [{
      "name": "D"
    }, {
      "name": "E"
    }]
  }]
}
```

If I'm right, perhaps we should make it clear in the document that the data must be flatten in order to use with Vega.

**Comment by jheer** [comment]
Trees must be specified using the `stratify` or `nest` transform over tabular data. I'm not sure where exactly we would document this outside of those transforms. Feel free to open another issue (or PR) with a more specific suggestion. Thanks!
