### ISSUE TITLE
Provide View API for updating style config

### ISSUE THREAD

**Issue by ericsoco** [vega/vega#1450]
Vega View provides APIs for updating some properties like width, height, background and padding, but there's no way (that I can find) to pass in a new style config (the second argument to `vega.parse()`) without tearing down and rebuilding the View.

Would be nice to have a hook on `View` for this, tho I'm not sure it's possible given the scenegraph / dataflow structure.

**Comment by jheer** [comment]
Unfortunately this request can not be met, as the config values *must* be available at parse time.
