### ISSUE TITLE
Chrome working, but not Firefox.

### ISSUE THREAD

**Issue by sornen** [vega/vega#1454]
This code is working fine in chrome but not firefox.

```javascript
var test = [{ y: 4, date: 2 }, { y: 3, date: 5 }]
this.view.change('table', vega.changeset()
        .insert(test)
        .remove((_) => true))
        .run()

console.log('test', test)
```
With firefox after the .run() method it does not work and for example test[0] is
```
0: {…}
__ob__: Object { value: {…}, dep: {…}, vmCount: 0 }
date: Getter & Setter
y: Getter & Setter
Symbol(vega_id): 383
```
whereas with chrome which works after .run() test[0] is
```
0:
date: 2
y: 4
Symbol(vega_id): 325
```

**Comment by domoritz** [comment]
I transferred the issue over to Vega.

**Comment by jheer** [comment]
@sornen Can you report which version of Vega you are using? Also it helps if you include a working JSON spec alongside the View API calls. Thanks!

**Comment by sornen** [comment]
Thanks @jheer

I am using vega-lite.3.0.0-rc8. 

Below is the json spec

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "name": "table"
  },
  "vconcat": [
    {
      "width": 200,
      "height": 60,
      "mark": "line",
      "selection": {"brush": {"type": "interval", "encodings": ["x"]}},
      "encoding": {
        "x": {
          "field": "date",
          "timeUnit": "monthdatehours",
          "type": "temporal",
          "axis": {"title": "time", "labelAngle": 0}
        },
        "y": {
          "field": "y",
          "type": "quantitative",
          "axis": {"title": "", "tickCount": 4, "grid": false}
        },
        "color": {"value": "#fab630"}
      }
    },
    {
      "width": 200,
      "mark": "area",
      "encoding": {
        "x": {
          "field": "date",
          "timeUnit": "monthdatehours",
          "type": "temporal",
          "scale": {"domain": {"selection": "brush", "encoding": "x"}},
          "axis": {"title": "", "labelAngle": 0}
        },
        "y": {"field": "y", "type": "quantitative", "axis": {"title": "light flux"}},
        "color": {"value": "#fad000"}
      }
    }
  ]
}
```

**Comment by jheer** [comment]
Hmm, I am seeing the same behavior in both Chrome and Firefox. I first load your spec in the online Vega editor. Then I run the following code in the web console:

```js
var test = [{ y: 4, date: 2 }, { y: 3, date: 5000000 }]
VEGA_DEBUG.view.change('table', VEGA_DEBUG.vega.changeset()
        .insert(test)
        .remove((_) => true))
        .run()

console.log('test', test)
```

Note that I increased the date timestamp in the second object to have a more reasonable range, if use a smaller value then the timestamps get mapped to the same `monthdatehours` value.

Once I run this code, the chart updates, showing the axis domain and marks. I see the same behavior regardless of browser.

**Comment by sornen** [comment]
@jheer Thanks for you help. This allowed me to find a solution. I oversimplified the problem for you, but including the actual date format that I was using, does not work in firefox but works in chrome.
```javascript
var test = [{ y: "4", date: "2018-Nov-01 11:27:01"}, {y: "3", date: "2018-Nov-11 21:27:01"}, {y: "2", date: "2018-Nov-29 21:27:01" }]
```
With
```javascript
var test = [{ y: "4", date: "2018 Nov 01 11:27:01"}, {y: "3", date: "2018 Nov 11 21:27:01"}, {y: "2", date: "2018 Nov 29 21:27:01" }]
```
works in both browsers.

**Comment by jheer** [comment]
Great! Yes, a longstanding known problem is that different browsers support differing date formats as part of their implementation of the JavaScript built-in `Data.parse` method. Sigh...

**Comment by domoritz** [comment]
This is a known issue with Safari. Please refer to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse
