### ISSUE TITLE
Allow update to facet by field signals?

### ISSUE THREAD

**Issue by eharkins** [vega/vega#1461]
In this [example](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAIuvTUw3VnjDow65PDzoZ1VgBt06sO3WtYiMHm4wREZqRBcQ-DBCbkYZPFg6BSVIdAtuWEYAL2RsKEJ0ZSSISHzlZVjqXIBWRWLldAdcgG0lCGBIGXRUHP0vH0QAfVgA20gAX1qIMFApqY6unpUG9AGABiLZqFZ1F1zIeodSeHcEqVkN2cgAM251DDxcmc3ivABPQkXIM7lJ55KTxbtAASt1gyGiAHdkOo9jJWKh2NCFFAALKMFxqAYfdQDADi6BcLnO+jhCKRY1aUwpswmlKel063T28G4LnhMgGym4GFiFzm0m28E+BxW61+czwxhksBud2a7TeHz2JmotloeBy8igqvMhHYr3lkAy1E6u30V3QQrw+vGAF0xrbKdSwLbJkaQqbYM06fMmebLchrQatZAKATWJ8AJrIdx8yDsWKFHD0uaxQgWPZgjH2ZGQbjaXRenAtZ7FADymiYPyg0djlIgjpptJ9jM+SHRygGEMYyhYubDbMWACZVqtabN2q3mcEXJ2UBEHiGBxHciOx+KU8Up-pWDJmHzisvAePNnm9GAS6X2sgqHEi1BUOYwY+qLnWIQDp9GLAACrvjEABQ6u+AEAJSgWAAD8YDAYQYFgDgu77s6syNlSSiuskbivOYDzJpS-xlBUjyQOo3AQrkACMqwhiybKoOe1EnsU3BXFcYJ4dMkB0eyP7MBiVHrgRPEMfe7TGqaewYk4LAASKAEAOQiRyXI8jICngeM4qkeR95Dtp7DmDIyj3tcri7NpBIesqhKQEoJ6QBg6gANb3pebT1lA25QMpAC0Oh4AJ4ovO8nywQeUBkQJ+h+QFQWeZAcWAolyAAB6ceJHoEnsFpWjaExQKx7GBoJIbDK80XaqwPbIP5-E5ChYDMdMCXeTpEIDCgBRIsFUCKmFZHvhFOmVe1vldaoMK9ZAyAyCyqgke+n4kfOoQZe6JrZTFM5zsgC7jGMzXFOgqVqN6pYtRdxQIASnzBp5ly3Iws2cZAGJXIuD1zKqPa5BaLhgr1lxJXsaIYrAWLQniBJEj8X3FG4iIuGWVA7OghC5JKEZAxKjDwM5ADCRnrRJW0+XtLgAe2s6dXta2kKIqygVp8NQJkiZpVRX2NQ2Tobq1CzMqy7K091U0Jf1ezhdNUVtsLDHjTGk3DVcZGoCRIpC-RKncugvJHVA0jqOtVzPbOewHPCTS5YG+q2rmtzK-o6AILN5ROCzfwg-hF0pelJGk2aUAKQpADU+S2HE1sBkG9sGyxbEcaVX1Gm8o3ODVvmI8gFkp+wLs57EnyoD2ygCZ5BszXN3ALcmkBLQ0yXdr2iAB1lQfcTtXY9n2h2Nc1m5eYLMXyxyNzcBq4te6FUuDRjMusnL2u+ePk8q2rGvLFrIuqXrciV0bJtm0mSx4FbNuxw76hO1ALtCsZxGV7N83JQ3Gokc3fZ14H04dt3LcHUridM6xYvqD0uDdUaqUIqPU0C9PYhkCDchgd9TQJ9-qA1ZoleqewQTqDBJCHqWDs4uAAGJsl8JjbwyAcYI3QEjFG0I3AYxwFjGhWCdD4yJruEm7dmQUypl3T+iAGZM09ldSA7NjKcxwJRbmnk0IQAHgLP05NbLTUlvoaWCVyqjSFOohKqtkE+1LNcGOJE2oX1zJrfQIo1i5lgjab+fD-R5QNIdCu01D4kVNjnE+TR9gNHPjHO2kBXSFWvkiYsKRXYPw9vaaaz8a6AhTm-FJV0oDCLbptDu1NOxZPjnMVa+BsmSW2n-YpDweboWeAfdubkwFYMseY2hUAjyPEKSxc87krrgNMTeF6blxLmHUEKTMLIlQhk0Q+J8aBuCvgdK0y4aS9jfj-IQQCF8ILQQvghGCc8AIAB1uI5xcMc0CdBLbq1Zko1mijNiFL6VuYeUA+i+AGNA1poZwyLCaJhDJZ5zoZMusC4oAy7yPBuaeAUozPgIHzJqKFwMZ76EfD4ZAXIIRw1BZcU2Lg16gJxaeAAhOCvAXANSoDAAAH2pWAMlFK0B0Ccs5OgrYwDEoALycrAMct5gx+XHJQQC2IABlCZyAAIMuYGgZmSzTFiolVK285KZWoDlUi08iqEXKpeoy9VwqJHao+LquI+rmaat5kSzpp4Vn6CaKlACSE8CgS1I651oF7ZQptR5IlM0VViUtYbEZYz9DdmMuRQ108lSotmS+RFRLigsmlPCRYbD5WXERHgKEs0gWJpBfm66Ia4USqjRI6ZjlZmYuxYW4oeKCUXiDX8UlKr9U0rpdKylzL3CsvZVynlfLvDvMFZAMtIqZDip1Z22VY6jUTqVdOg1Ga52TpNYujVtbLjGsleuuym6XRNqasuicRpi17HDZi3MFa0VgiGtUjJ9yMk+rmHaqATR+UfKaKscJ8A3CoDgu6vcLqtQ0TAHk-+LBPV7uBc+p5p4yViQ2mU15Q7BiQOQAMSUIRqDkmXfXD8jc9hNHQ0cyAqVjlag-Xggh5FoRfttK6sAJHjnkeRFR0E4JaPqCaJRBjXrQWwc1f6wZpSybxlQ5hqUsA3Aak5DnRoz7iivu4n+wgAAlRwOGAL5BkAAGSLu4ACH7JSOGk43AYjgkC3DoGlDUcQPmUYkyZ6UMmMOqHxfQVKYBSBMZ00ZpzUnXMWbmogaztmXofPAiBrU4HhEWoE-KuDlwEOiY7h+zI3BuRyY8+I0F+HloxVUxppwkqMvcn0zIGM6h-P9Ac54CTZXUDBas+oOgqVHO1ca9lhwjHQOxZ7ogeLMG7ncxxnB30nx2P4M41CKeEjiSNtBUluYKXnE5IQRJ6BimtgEffr0Tb9GwDcp5R+1KPHbRQTAHCQkezYiozwKR1jHX3mpSG0+kbF1HlNJeeJ2r90AXtOLP8+b3SoXLbBQGyF+bT2ChLQi2dIUY0zPRdWhHUB61RMW4WyALa9VqvbfS1taru0uTZQsDl3LeW-eHahoVx7UzzqnUTylG7sfbtNaqlnaPijs93fTnnjO13M5nUGx9V1tv5cI-a14TqgOMZlx6-jMHEtCdWwWnFMPYXnsTJG+niUUXI+fPMhNibuKyFgKmqh2Mg3xkDDm0HtbwemJhaGw2pb+cSgN5WlH5Ea21uuOiBtPT-e47Nfj2lhO8ddpZWT7oFOB3U4FbT0dHut2C53cLpdh60+roz1HmdqeGe545+a7nWr08l7VW9wtYuEuHuGbD7XEaKJTK9ze5Ad7Reaol8p99EnXj0Zi6pgCCu5fRbA13SpUHvUq79WrzK639u1fQ5J7DuGhO9+Y5AV4FH6u1bBpibE0NCSyHo4xrfO+2MSYPxDI-+IT8yHO9PuvS3VeQ7W8hxPknTNBfcwpvDymv6XQ6mmmkqOmFWVWNW7yzmZmsmlmoWrW4W9mrwz2gwMBv+8m9Arw3mvmjgUBaBgW5m8BYW6UEWrwUWYAfWk+dM+A1en2s+Gu8+SGYm6WmWTWf+mAPeu2bYRWoBAEjWEBhmH6KBe+7yXWxBrWIhrBWWHBvWMW1BC4dBpY96UwteR6jSAKbUH6N+kMOI9+sMhqgKhKwKTuwmEKH+LB-euWwKkue2KGf2h2x2ohgwA+vGl212Lgt2Mg92pGl+qBAw5B0G72D6o2GhEiWhEmK+WG1AOGc2vsymAExK34AAguoMYDLlNjRrNhBBHgBKHHdtCA9ixrvqdqBI4ZTqHJkTNnRt+mAAAGR1FgD5HeGFGPYlGbZlFuFOGVESbUbVHca8bgT1GNGJEpFpHoAZHX7oiH5Qz6GyA5F0p5EFHGy+HtF-ZlG1HdHaHTG36zEwyn61ENFNHLFFHb5rHvLkHnZHYVHbHgy6HH6wxP7bLOFDDHAYir4xHQh7LABjBBEPJjbfaqJf5nwbIm6+wLbB5Xhv4ibGFEoL6f5VGEIwjbZtDMFpZTF3F377H7yarA55bKaIlcbDEvE6FYkP6XbADOo4DHJ5LHJNFgAKQDAKT0kAQXzRxuIMZaixCTwDgkAXjABJLuzUDUlka76+Kzgil9FIm75IF4A4CEmzYFQCnVxCkil+FgDinKAimkl7EP4ymkFxDykYkzF6HYkOhjB7IeF-GfYfbKEAmaE-bGaEFwEha3CGGA7TA2pGFY4ZKmFq6Qm+mHqa6u5Gju5BnXpVq+5l6OQ9oRG1b8rWnDZEp4k2HKbACpQ4CAbMDy44Cj7ZlaiykfI4DSZ4ySqlEFkGl4ABHFnhBCj4EBGgS-Heq2m1L2nhGOkBY-7mYcHuk-IdJfIQlg7QnmE+k4pO4QJnpho64t7hlt5xrG7RnJoW6qLppBlZr255qFrjnO6Tlu7w6F6I7FyRlYpl6XAspxk079CJnWqF4N5a5TnN5Xpznoqd61pqE2nJkAHcF7DplGm1boFEGumtZea+RgBZnAZgCvB-nQHOkYYSF0DYGgV5kupNkCYtn-FhG+wXmDDiFAWGGDmv5z7v6jmEXY4u5w6TKzlI6QAQgoA5yLnm6W6sLUIe4xkuTYUDAJlBoqHPApkAppkZlgWy75mQW5nCUoXXkPLoU0htlYUdmdZsHdaYADkO4mHDnxCbmkXQ7kXjL7lUWfC0XID0WsVLlMX+AsVBnnnyWXmULcW4l4ayiu6rl+rKaQgASUR0CjiUQFmtocGRhgAABUUQ5E7lAAbD5XqhwSiMkppM2SEfQZhaYhxY+OUFcP9iDppVCURTCVxD-EvtAf+A1F+QVjMqlTLoOsviMMgOcWgYVVqGwkobUtJTUpsHxQ+D2g0hdONhxR+uwJUF8hWrYDmF8r+loFbuwgCoKekjYS9JjqYXikHO0B6ZAAAMQADMG11hAKC1ZY+Q8AzABodcHpqwdAlEQ4VQPFVI8qth01eW0CsJY54Zagr08kFV7ywwtw1VkAFy0k1ALAxJr1X+H1tg5y9GdAzq1xCetJkA9JjJzJocYArJMc7JtsrwDG0ZeV9hL29GklCV+aS1fZOAY49lQmh1JFal-uGowwFsywpGH6wNX1P1s0f1fgRxgN9NVVoN364NQGkNVO0NsNTJLJbJF8dsrO2lLiWNLhON3F9OBNg4uQxNn5QmqUQ4mVgZlNz1NNDgdNkRnN31dAv1-1bNtNb1aG+tGxtoPNzAfNNJO0dJCNcNwtyNotaN4tpumNX+Z2vGuNdpQa8tK4RNl1qEeGrwatD1WlpuVNL1ptQNFthtzNxtjR7Netn1XNVtENThdtHYDtDJQtCNSNVoKNsc7tfqntwh52vtrZ-t3yCtQduJcV4uoRXVgJbYXcLKXoA1XusArwCIrIhhuivyJQMQcQYSXyRi6sdcNi6O5iXpU1UOqZ35JieW+YloB1JEx1dAAA7BLgterb0k9dTbYkEqgE0MclKVxschdk4R4QTt+AAHLoD31yQn1n2QAX2zZX0LFgBXJv06mml6lhJ8230R4P1P0v1nyn3HL-0PGyBf3RkekeGy013LUwERzwLB2qF4bDBkTOS-L+2H0x2QNv0f3QhX3APmR32wCP3P2-3n0cbSlhLf10OQAwNzEyDkM32UOgPUPgMsNsPYnwOsWIPmTIP42EN7DEoARG2IAQPoC62VVp3fVDG5EUAuAACScQ0IA4Cj71+tWoVymkrF6GWsbprFmpewBMFUHM+CVdGF+Ntdgd2otg7iJNfqAQrIOgLC6ueWntVydjSieG91uVbxnwny6Ox8uCDDXGW1EiZN4koTewwYETfioMOx9x7D4wjdH5ftLdDpQJvVqGhhg1dgn0AKo13jzlEi89y91TWjMIdce9R1hNfUUm6Do9h011r6phwTAZB9mtR9p88jZtQw8dMjANsdHNSjlt1tlgWdncOdMNjt+diNItISbtGNktXtMt+aKJXEx1mDDYod+9eT2O0d2twzcd0zCdMkrNydkzqdIN31YNmdlO2ds4udTtBdazHJpdGu5d-eOziaezAdiwStOKbVvsqtJzWVZzWtx9OtIzDN5yNzLNEziLVzTzMzrzUN9tSzed8NqzLt6z6NxjWzp2ldYjiaoLithzLood4d5NGtcLgzgSGLUzWLqLSdP9DzijWLLzvN8zAtyzhLhdgYxdYtmzi+UtARlLuzctjjYLdLkLzuko3AeDMLzw25Lw8LMrZ2tR-aLx3tF2RxFdBrlOFdPtwjLTNFwQ78VLcJiruQHhyr2Tyh8ivF00wCnVsLvsJj+gnyWCT08CvQE8AQ6sXyP0yg4qt0SThhUb41A1eMhMxMqW-C6Igif8wioizMXpu8vIOAGCE1EiJC94RbXyGAqUAAopWYrRW7EDW3ZpxDRBwsm2WwSJggClIqoME6sM3b687ok-oOleCXAqPfoO9GUxIlGzG1AvG2gom621wqmxYbkgIuBpUjm7E5cPm+eOW8QvQjnO2wDMW77JW42yG5QfWzIBe+O1e0u65H9B26e6Yt2zIpQR661U6BhG6Ohj676qeG1IG9Gp8OEJVrGNNLu5vI0Ai6KLmBY-oKQ8iTLKAc0KBvCWJv1gAosq1KWYu38NkGRONXzHSCondMNBWmB1VsNFB1PVvLB-YiGAh6iOk2SQYZXFKDhoaJ7RuzQVUiBm1R0Hh8xdbgR9CNwMRzJaR38G1HRGYxLF7o7LENlJB7rAW1xNPWy3B0x5E-oFY2B5NJ3cGsbONRx6h-oEp5JN+0c1hDQG7P+z44bGqxqyPESHEbjIFJ8PpzY53QlDU459dL3YZADAvfEUvQF6eE0-sza2g+4Bg9davftW8BvS0ydTvazCodUv3D+8kMmqbJUHXCdN+JGCRCXDe7WzgGtWOBSBSEAA), I am doing a facet of the data using a signal called `facetby`. This works; however, when you try to update that signal, (whether using pre-faceted or data-driven facet style) it gives the following errors and does not update the facet in the visualization:

* Using `field` (pre-facet), I get "ERROR Error: PreFacet does not support field modification." 
* Using `groupby` (data-driven), I get "ERROR Error: DataJoin does not support modified key function or fields."

After reading the [docs](https://vega.github.io/vega/docs/marks/#facet), I'm not sure what else to try. Am I going about this in the wrong way or am I bumping into the fact that changing the field by which the plot is faceted (via a signal) is currently not possible?

**Comment by roying** [comment]
See example workaround solution:
https://groups.google.com/forum/#!topic/vega-js/ke6s3QW201Q

**Comment by eharkins** [comment]
@roying Thank you! Do you know if there has been discussion re: allowing a signal update in scenarios like this when vega expects a field name? It did seem like that was the issue, because most other places in my example allow signals except the [comparators/sorts](https://vega.github.io/vega/docs/types/#Compare).

**Comment by roying** [comment]
See: https://github.com/vega/vega/issues/1417

**Comment by eharkins** [comment]
Thanks again!
