### ISSUE TITLE
finding max and min from dataset in vega

### ISSUE THREAD

**Issue by vikkya** [vega/vega#1462]
Hi, 

I have my data set like [this](https://api.myjson.com/bins/nvucq).

can anyone help me how to find the max and min value from "circle1_amount", "circle2_amount", "circle3_amount" 3 fields.

I tried extent but i'm only able to get max and min of one field. 

i want max and min value from three fields. 

Thanks
Vikky

**Comment by domoritz** [comment]
You can find the min and max with an aggregate transform.

**Comment by domoritz** [comment]
Are you trying to find the max of all three fields for each row or the max of three fields at once (per column)?

**Comment by vikkya** [comment]
I'm trying to find max of three fields at once.

So expected output as per my given dataset is [119, 1248]. 
My any circle*_amount can have max or min.

**Comment by jheer** [comment]
You can use an aggregate as described above. If needed, you can then access the aggregate values from signals using the `data` expression function.

**Comment by cnrmck** [comment]
> I have my data set like [this](https://api.myjson.com/bins/nvucq).

@vikkya could you copy paste your data format here for the rest of us?
