### ISSUE TITLE
word cloud transform deadlocks with zero size:

### ISSUE THREAD

**Issue by iliatimofeev** [vega/vega#1464]
### how to reproduce

change size in [examples/word-cloud](https://vega.github.io/vega/examples/word-cloud/)
```js
     ...
      "transform": [
        {
          "type": "wordcloud",
          "size": [0, 400], <------------change to zero: see Warning
          "text": {"field": "text"},
          "rotate": {"field": "datum.angle"},
          "font": "Helvetica Neue, Arial",
          "fontSize": {"field": "datum.count"},
          "fontWeight": {"field": "datum.weight"},
          "fontSizeRange": [12, 56],
          "padding": 2
        }
     ...
```

**Warning:** you will need to clear local storage of vega editor (in Chrome). It will get into this deadlock on load otherways.

**Comment by ganeshpatro321** [comment]
![Screenshot from 2019-03-16 20-21-05](https://user-images.githubusercontent.com/30416891/54477478-3ec05b80-482e-11e9-9175-7078b6835c77.png)

This particular part of code is causing the package to go into deadlock.
@domoritz 

Can we find a way around from here itself to avoid deadlock.

**Comment by domoritz** [comment]
Thanks for finding the problematic code. I'm not familiar with this code. @jheer will know.

**Comment by ganeshpatro321** [comment]
Hello @jheer  

I thnk if the while condition isnt satisfied for some time, then we can maybe return something saying, its invalid.
What do you say?

**Comment by jheer** [comment]
I think it might be simpler to just check for zero size up front, assuming that the deadlock does not occur in other conditions. I'm taking a look at this right now.
