### ISSUE TITLE
Synchronous spec parsing

### ISSUE THREAD

**Issue by mprudhom** [vega/vega#147]
It would be nice if vg.parse.spec would be synchronous when no callback function is passed in: the function could immediately returning the chart object (or throwing the error). This could be handy for doing things like analyzing the result of a set of transforms o the data.

Initial investigation into doing this reveals that one problem is that vg.parse.data invokes the callback via a setTimeout(callback, 1) call, even when all the data is inline and not requiring async fetch.

**Comment by arvind** [comment]
I'm closing this out to keep the `vg.parse.spec` method simple. Unless there's a compelling case to offer both asynchronous and synchronous parsing, having `vg.parse.spec` return differently based on whether or not the spec contains URLs introduces unnecessary complexity to the code and users' mental model.
