### ISSUE TITLE
latest vega libraries dependency to d3-array

### ISSUE THREAD

**Issue by m1lky1223** [vega/vega#1470]
updates to vega libraries from 2 days ago to user d3-array 2.0.2 caused IE to not able to load any vega chart. any idea ?

**Comment by m1lky1223** [comment]
https://github.com/d3/d3-array/issues/87
any suggestion if i can still use vega 4 and running it on ie ?

**Comment by jheer** [comment]
Yes, in addition to d3-array 2.0+, other Vega projects (vega-lite, vega-embed) are dropping default ES5 support. Already, Vega was not IE-compliant, requiring polyfills for a growing number of features (Promises, Symbols, the Fetch API). You have a few options to consider to get IE to work.

1) The most future-proof way forward is for projects that bundle Vega to use [Babel](https://babeljs.io/) or a similar tool to transpile Vega and dependencies to ES5-compliant code.

2) Currently Vega itself does not use ES6 constructs, beyond the above mentioned polyfills. A simpler approach that should work -- but is not at all guaranteed to work in the future -- is to use the vega-core build file (which omits D3 code) and import D3 separately, like so:

```html
<head>
  <script src="https://vega.github.io/vega/assets/promise.min.js"></script>
  <script src="https://vega.github.io/vega/assets/symbol.min.js"></script>
  <script src="https://vega.github.io/vega/assets/fetch.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/d3@5.7.0"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega@4.4.0/build/vega-core.min.js"></script>
</head>
```

3) For the time being, you could also peg your Vega version to 4.3.0, while you decide how you'd like to adjust for future releases:

```html
<head>
  <script src="https://cdn.jsdelivr.net/npm/vega@4.3.0/build/vega.min.js"></script>
</head>
```
