### ISSUE TITLE
SVG or HTML element in a Tooltip

### ISSUE THREAD

**Issue by vikkya** [vega/vega#1475]
Hi,

I was trying for something like SVG or HTML Element in a tooltip.

I followed vega/vega-tooltip and was able to modify tooltip text color, border, background-color. 

I was curious if we can implement HTML element inside tooltip, it would be nice.

Also could you please let me know is this possible with vega@4. If yes please let me know the approach.

Thanks,
Vikky

**Comment by jheer** [comment]
Vega allows custom tooltip handler plugins (vega/vega-tooltip is one example of this), if you want to implement your own SVG or HTML tooltips. Here is the documentation: https://vega.github.io/vega/docs/api/view/#view_tooltip
