### ISSUE TITLE
Color legend for log scales has insufficient ticks

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1483]
In [this chart](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq6ArIoiQA7owMtdAZgAMn+7mSNqfF0ARgBOHxNYPABPABsdHEh4ZFjY4wcDdDxMHABtJQhQCGKoGXRUBKhM7IBaAA53AHZ2ZDqANk8AM0a29wAmbuD0TwM60J74OuHgupnPdJKoCnRY1mRYXXzF4uBIDW0PTzqbNrbgujCbUUaGvrr5KHhuVhk8DxvRHyh2S11POm8nj6ojONgAvr5trt9pU+qdvKE+nQ+p5TqE6nVRCcHklnq8QsE+qF3DifnIcP9AbNjhCCotoVpYSDRHdxKJZo0bESZm0cU8Xm8cDZQuFSb8KQDPMF3G1wZD6XtGbo+u5go04XU6E1xg0bD0+XjBWBPqcxeSwJSpaFgnK6SUGQccH1gtdZaE6Cy9XCXX0+gaBcrZcEzX9JcDZbTtoU7YtFY6wDNgp50W0PVzgY0wkd5dtcQGnZ5rjnY2TQ94vMmRVXq1XGjGIJGow7KjMxiLGnR1ac1TYbC7-ficDaziGJeXe7ao2BmyE6n1Gu4rnRZUTRP1enZHoaQqIk6OLZLd55J024y3Glj3LMAcE2uF0Y1s1v8wnb5vIKWx4XZSeoWeQm0WKhFiFwuu4wFzpiA5GscwbfOKB7eFyjZ-jCAFXOi4gnKIwHuO4a6iNBuiPry8HmpaepYihCpoUOVwooWy6iNcfb3oRz6DmAXLsR+CGWm0RK-jRSpDoB7Iop23bAlWpF5pxnxfLx5GSm0mJCfa-50aENhHKmLqqRe1ZEU6GL7paC6hNRGm0QmgGeD0qaouygHtL2xlgL6fpkWW9nEjpgIBYCwRWTsmkJnO-SqpKMouli+ocUat6yZ+iFHOy6mhTZYTHL65y3seIJ1IZ7mEvc3lfuE7ghYUYXZcE9U2BcC7OiyxyhO5UHlal2mctV061XUx43Jqma9gujSPu+-KcSOXWUkmhI4TWy19TOQ7jL0XgAo0G1ZlN244CyZk3qiGU1VlAl3qiFy9kmKKfDx01Gjhx1SoSq21eMUrHHQDQYv9GL7S+86vfVvXFudIkeUcVrnDpmatZR7nOqDKofVloS9MBjU9GEy3I++KXzXcZ39TZzqFp87o2DKmIU1cJXtXNN74ejUMUxNIIeouq71WVcmJY0oPgaTa0JjchbAR6fRA5xe7M1KVEQ2TUNhHhQJIl4eHa3hsuJYTfE3jp-mBYFwXK2LMxcpByKIscCNwiVPFE0bbRs-GdWTQC7SnL7gElQbylSqC7uwsCczuL9E7R7JT26EzSllrejSh8qdx4fVdDjEmXK9NKjOg+qothS1vYdJ2S01nrBKF4Npum1VFsl8mMwslqyZNCbXkCwBoMNJXy1VnUqdOgJ7JS+ME1T1P7kJy732WU3WULi6P1ep5nmz6D2Mjx5wqIguFzcn7QsJSE3fz3jg-LSnS-s2qeHl8Hfu+1vCsor2u8y54-Q2p2wHMUAY9A6YA56GyBDnL+hkGiR0XCVRS89nRuzvvGZ0YwMQdkzEVE2x4OqvVysXcmNxiQzE7OqDevoSRnxwGAoOvo7zX2rMPFBsJZgumTE1Qep8e5Cnwf0Qh7MbCzC8EiLkXgeiIhlCVKhicxwqmYfWFWqDVJ4WYsieu9k36yMQsCRcX87LYM7DLdyztwHSS-oiFkmMtTGOoWAfmiCrgCNQeNMY4gBLVxwMlMxHQNGBT6F-HsKJ3TSh1trLRiCfz6IfqcSS2C8Hv0zLvG0qpMSKTjkOOC2jKTzgjCw5UE0USyizlkjJXF8Fzj8QFRuiixZ3EkX-KRdjA5ljuODWptUEYykjseGBYT3LeLocSL+wTukXFRNJWsCTskAiJDSfJJlfF-znJ440r0vCiC-oCXo-wKEUIieArw2l9EEUXHQE4L82jcLKYMssqolYdJsjKGma53RYmRusgJCzbKfFXucsJ2tu5lJkfPfhzjKheBdJyN5MiyktLHBnKpgJNnfMJFcO8mp7KrNMUHR+4KQhCLGM6TsALVHuRBYclku8mhYxuMiEq6yWLUvIVySklzTjAJfBS3FNNd7piTKmBOZSL6HKEfinAV4WR3HOHXBuDKFYyhRY89ma4kxtyFSAkVuK7zio8jMIk7c-Gws1es9pU5La4WFB2Y1wN1mDV1beIkmDVlarLJ8BR5qwpFQmr9Rh6J5UzMpsg5VHsTgyk7AG+eWIbTJM5qmfmZSslRr1EipCFiegXEjeAwqyTVQnElH4oFICk3Zp2voho5ys1Bxwp-b51ouSGo0aUk1CsdJ5JDZUHS7R6V2JLUHPsV8-XBs9TZMYVyq1lj7Ga08WUBVwwnWOa2u9BpjDTH45ttrW2613sSa6Ckm0fNbcxcEMYAC6dIwRKFPb4SAGAABOABrDYeQ6RFFjGUCouhb3oEfRsYskAYiEEqHsaIqB2DcDSP+qIcRKi5CSIwO98B4iQGvTGSAnQ73cFQLoXY1QchVCyOgeoTQWjtC6D0fogxhijA2pMaY1J5ghUgMgGQTwDCVDfbmVghBqgccUQ4bg+h4DMGiDhyAyxViVH+LffjUBOiMFSJsWT0Ypy5jwOsI0kBqisFQLkAAOkpAzp6wAAF4zNgBkKwVIYAAA+NmwCMFgAAOXQE5gAFNp3TBmyRGYAJS2fs55-TAsjOmfM5Z6zdmHPOdcx5rIOngtPT8wFsAQWDMwlC2ZkzFmrOxBS45lz7m0tnj8wsVTxRxMrDWLoCLsRlNgD6tZeAKxgNPFiNwO9Cg5OMBSEYRIaFL3ldQ+VgD3AIN4EYIQHD9XFTUDKGkRIwADMABFHPZFY8gAzOBOgdYwHgOLeAEvecsEZh4BmDO+bO5AJzOmWh3rANwToYAACSMgojoA27ALbYAdt3r2wdo7IWUNXYu1djLuhfv-eK+D69YBzuQF82CSAsnGtQAAB5iYQC1r9GOcTyd61+0sqPICiZwNCZryHEiibxz12IfWz7E9gIgdAQGxMSeq4kYTiHkODajLzko-OGtXpvVj+Iz6wBbB2Ghj9wHcdocA8B2IlhkA-rKxVgwWH0AIU47GPDX68PEeaK0Do3RegDEzNRsYEwpjfTmGrko6Haf08TjGJjd6PvUFg18Bkc2VhfucK4RAkAwTDffYwZIug8B3rWP+7QmHI-R+QBe+UOuHAy6-dT+X0RWeJHa9Yf9GuMDa8UVpwj+vCOG9Iybij5uhgjCt20OjtvBr24q-junX646u--e7qwsGffza-SgAIQQIQWlDw7mQ4fKhR7WMn190vyitYgx11vAHs+K+4PntDhetfmlT+rsviQDcNCN2R03lGLf19ozbxMLflaO4J-1pU3e0O9895sSAABibonR2CdE6C62-08GQBZEaEAInwq0sHUzvUIAgyyGA0QCQ2RwF2FxMHQDR3WCU3tDQ1F1lzXw6x604g-G4AICwzX2oDvRcAhxWFgGQH-QmzwEpygFW3ew2zX1iHQBaFiAADFVgmcE8Y80NODuCAB5KgO9TgqbHAWfeg+XcPB9AAYRAQHz90538FiDcwDxYFIE+F82D1j0sHYwxyHHnxwNzDwIzwIKoJY003iE6DeH-UoOoO21oLkLU2YGYOu1u2QHu0exeze3W2SD-WEK4JSHEN8KkK-UoOQGQAMEz1zE0CMOQBMITDMKlwsIp2AwSNjEINsK-XsMcLQ2cIMFEKExE1DF5GKKoIMAAGUsiccKCajBD3DddNcEJOg3D-0RCUhxdOjYg6D-0MA0cABRNHdTTiCIXMVASwMYiYo0KY2MCbeAJ9GggY1oh3JImQYwv4C9NAhweIT3bY8XSXFTWMeTRTTnFfTrJw93CwWwgAGRY2oDcDJ1m0H0504NQEIDc2H0CDwAeH9mhk8H0KYx6NiAiMkJZ2iLvViPiLXxYzYz4ynBAzAwg3FwPwd24140x2Zxz36nZ1awQyQx0DH0gEE3QGExiDZyqyk07DBEF1QO2EF151D1xBkHk2sDeIwMcwAE0xMZiZA5j8iJVPAGSQAwQgA) the legend has to ticks.

![image](https://user-images.githubusercontent.com/589034/50188798-a7537700-02d7-11e9-9ffa-0dafc2f54fe4.png)

**Comment by domoritz** [comment]
Here is a simpler example: https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq6ArIoiRYeAJ4AbHTkjxkr18YcG6HiYOADaShCgENFQMuioHlCBwQC0ABwAzADs7MhpAGwADABmWfkZAEylAIzohQZpAJxl8Gl11Wkdhf4xUBTorqzIsLrhvdHAjlqJGYVpNvn51XTVjTaiWZkVafJQ8NysMni62WmihbuQ7Ja6hXSFDxWiSzYAvvbjYJMa2roViw9GhU6BVCotGmkzgtLvtDsccNVqhVGhlLtc5Dg7g85h03h9xt9pn9nqJtuJRJ0sjZkR18jCDkdbI1GhcoOjbvdCtUMvk8RFeoTfjgKhlqll-mk6NlmpkbGV6XDdOdFmibpjOatqnzPl8pkKwBVqhteY06KS5f8jRUKgrGcLedVVRiwFjCk9ee9+TFBYlkWUVrb4WBHWy1S77s80p6dT7dNytflOdjk49A3GnRzChtGtHPrH7Zk6HY9gygyGrmGsaI1tq83rEo0tcDZink+XYXaDRn1YUbGDawT67Y5ombSXFQju+He4jmXP5-P8rnBz9Ek18lk05PQ86sTYxQOBUOEdUwcti15S+md5nqVH8UfV7o0nNTaI+62Hu2r8Kp3uMhkh7eseYAomCZqfti34Tl2N49us76vF6YAALr8khEAoR8jjwAMwyjPyUS9JAcQJLol6uNwABOPQxJALiEIkkCUdYD4BNwGBhkR4yQMkIRJEE6DpNkuQFCUZSVDUdQNM0+StO0nQvrRxHFIwPhGJ4T7Icu0SQFR6BWIkoSQAAxKUxTsMUxQKFAJmFMgpJZNZaExBhqHYe41DIDIBgjGEhHIZAqm+OR+yUTRbFQNQ+kWN5eAADLedQLC6IS1BxH4nirN0bkQG5aGvEAA. 

The problem seems to be log legends that are short.

**Comment by jheer** [comment]
Related to #1467. Log scales clearly need a different tick count heuristic here (at least for vertical gradients).

**Comment by domoritz** [comment]
Thanks! Feel free to close this issue as a duplicate or leave it open as a different test case.

**Comment by jheer** [comment]
Closing as duplicate. This example is referenced from #1467.
