### ISSUE TITLE
Tooltip handler clears rendered chart

### ISSUE THREAD

**Issue by ericsoco** [vega/vega#1487]
`View.tooltip()` calls `_resetRenderer`, clearing any rendered chart. It wasn't hard to debug or work around this, but it was surprising to see my screen start going blank after I wired up a tooltip handler.

Is it absolutely necessary for this to happen? It's an unexpected and undocumented side effect.

**Comment by lizozom** [comment]
This issue causes another bad scenario, which is harder to work around:

If a user has a custom controls container
https://github.com/vega/vega/blob/b0dbd40da64fda541cfe2c848c0965457009c766/packages/vega-view/src/initialize.js#L7

And then add a tooltip, it will call _resetRenderer
https://github.com/vega/vega/blob/5cbb35351def4fd061fc6ffbe6ac2ac190914f20/packages/vega-view/src/View.js#L197

But the call to _resetRenderer doesn't use the elBind parameter, hence duplicating the controls 
https://github.com/vega/vega/blob/5cbb35351def4fd061fc6ffbe6ac2ac190914f20/packages/vega-view/src/View.js#L221

**Comment by jheer** [comment]
The renderer needs to be reset when the tooltip handler changes. The expectation is that the client must call `run` or `runAsync` after such changes -- which if called should preclude users from seeing the screen go blank!

Commit 9345133 updates the documentation to make it clear that the run call is needed.
