### ISSUE TITLE
SyntaxError is triggered when vega is used through shadow-cljs

### ISSUE THREAD

**Issue by mraveloarinjaka** [vega/vega#1496]
SyntaxError is triggered when vega-expression is passed through the Google closure compiler.
That error prevents the vega library from being used from clojurescript.

shadow.js.js:88 Uncaught SyntaxError: Invalid regular expression: ...
Range out of order in character class
at local_vega.js:30059
at local_vega.js:3
at Object.shadow$provide.module$local_vega (local_vega.js:2)
at Object.shadow.js.jsRequire (shadow.js.js:85)
at Object.shadow.js.require (shadow.js.js:111)

**Comment by jheer** [comment]
Should be fixed by #1505
