### ISSUE TITLE
problem with this._update in Operator?

### ISSUE THREAD

**Issue by Sigfried** [vega/vega#1498]
As mentioned in https://github.com/vega/vega-dataflow-examples/issues/1, there's some problem with the dataflow examples code. I'm tracing it back to lines 39 and 190 in Operator.js in this repo. In the example code, with a breakpoint on line 190 (1811 in the bundled code), it pauses on that line twice with no problem, then throws an error: ```this._update is not a function```

On the third time through, it's an object that looks kind of like this:
```
{field: ƒ, case: "lower", pattern: "[\w']{2,}", stopwords: "(i|me|my|myself|we|us|our|ours|ourselves|you|your|…ly|own|same|so|than|too|very|say|says|said|shall)", pulse: Operator}
case: "lower"
field: ƒ anonymous(_ )
pattern: "[\w']{2,}"
pulse: Operator
flags: 0
id: 3
pulse: Pulse {dataflow: Dataflow, stamp: 1, add: Array(1), rem: Array(0), mod: Array(0), …}
qrank: 3
rank: 3
stamp: 1
value: [{…}]
_update: ƒ readText(_, pulse)
__proto__: Object
stopwords: "(i|me|my|myself|we|us|our|ours...
```

But on line 39 (```this._update = update```), update is an object from the beginning. I have no idea what any of this code is about. I was just poking around in case there was something obvious to fix.

**Comment by jheer** [comment]
Closing out, as this pertains to a now outdated Vega version running in the vega-dataflow-examples repo.
