### ISSUE TITLE
Default color ramp order 

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1499]
As [Schloss et al.](https://schlosslab.discovery.wisc.edu/wp-content/uploads/2018/09/SchlossGramazioSilvermanParkerWanginPress.pdf) shows that quantitative color maps normally have dominant _dark-is-more_ effect, unless there is apparent variation in opacity. 

> The results suggest that if a design goal is to produce colormaps that match people’s inferred mappings and are robust to changes in background color, it is beneficial to use colormaps that
will not appear to vary in opacity on any background color, and to encode larger quantities in darker colors.

I think we should consider two things: 

~~1) Scheme config for `config.range` should support `reverse`.  For example, many people may want to make their theme reverses the `viridis` color map by default.  (Yes, people can always apply `reverse` in each spec, but that means that our config doesn't really support this common theming use case.)~~ [**Supported**](https://github.com/vega/vega-parser/issues/95#issuecomment-444235024)

2) Re-consider our default `"heatmap"` scheme.  (It should be reversed?)  -- 

This may be considered as a breaking change, and thus may be harder to do than 1).  
That said, I doubt if people really uses `config.range.heatmap` that often in Vega.
(Vega-Lite's `rect` and `geoshape` use `heatmap` range by default for color -- and this is a good time to break it since we haven't release 3.0) 

FWIW, this example is driving me crazy every time I look at it.  (Why is yellow the highest value?)

![image](https://user-images.githubusercontent.com/111269/49419527-15c30180-f73c-11e8-9e34-2e758ba05695.png)

**Comment by jheer** [comment]
Fixed by color scheme updates in v5.
