### ISSUE TITLE
Add minspan, maxspan, & avgspan group property values

### ISSUE THREAD

**Issue by mprudhom** [vega/vega#150]
It would be nice to be able to set properties of a field based on the maximum of the width or height of the enclosing group so that you could maintain the aspect ratio of a mark. For example, I want flexible group widths, but have a square rect that is centered within the group:

```
{
  "type": "rect",
  "properties": {
    "update": {
      "width": { "group": "minspan" },
      "height": { "group": "minspan" }
    }
  }
}
```

Similarly, "maxspan" would be set to the maximum of the group & height, and "avgspan" would be set to the average of the two.

**Comment by arvind** [comment]
Thanks for re-opening this issue for Vega 2.0, Marc (uwdata/vega#68). I believe we closed it because we determined that Vega's new [[Signals]] can support the use cases you described here.
