### ISSUE TITLE
Never render duplicate axis labels

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1503]
In https://github.com/vega/vega-encode/pull/11#issuecomment-384479845 I proposed to only render unique labels. The tricky thing is to figure out which labels to show. Intuitively, we should show only the label that is closest to the value it is representing. 

```json
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "height": 200,
  "padding": 5,

  "data": [
    {
      "name": "table",
      "values": [
        {"amount": 3.8},
        {"amount": 1.5},
        {"amount": 4.3},
        {"amount": 2.1},
        {"amount": 1.1},
        {"amount": 3.3},
        {"amount": 1.9},
        {"amount": 2.7}
      ]
    }
  ],

  "scales": [
    {
      "name": "yscale",
      "domain": {"data": "table", "field": "amount"},
      "nice": true,
      "range": "height"
    }
  ],

  "axes": [
    { "orient": "left", "scale": "yscale", "format": "d" }
  ]
}
```

We currently show

![image](https://user-images.githubusercontent.com/589034/42183817-128f6692-7df8-11e8-9908-f96446991aac.png)

But should show

![image](https://user-images.githubusercontent.com/589034/42183914-690494ca-7df8-11e8-995d-37f4f5c1703d.png)

**Comment by jheer** [comment]
In the example above, the user is "getting what they asked for" in terms of the formatting, even though I agree that the output is not desirable. Right now, we do not parse the formatting flag to set constraints on axis tick generation (e.g., a minimum span of 1 for 'd').

If anyone has ideas for how to do such label-value alignment checks efficiently and accurately -- or has ideas for alternative approaches to this class of problems -- please feel free to share!

**Comment by domoritz** [comment]
Can we apply the same algorithm that we use for label overlap prevention but define overlap as two adjacent labels having the same text?

**Comment by jheer** [comment]
Closing out this issue due to the addition of `tickMinStep` (which can ensure integer steps) as well as recent modifications for smarter label format selection for discretizing color legends.
