### ISSUE TITLE
nest vega tree text at different tree levels

### ISSUE THREAD

**Issue by sandeepap11f** [vega/vega#1504]
Getting text label at the leaf level with below code, how to get text at other levels of tree (Job, region)

{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "data": [
    {
      "name": "tree",
      "values": [
        {"id": "A", "job": "Doctor", "region": "East"},
        {"id": "B", "job": "Doctor", "region": "East"},
        {"id": "C", "job": "Lawyer", "region": "East"},
        {"id": "D", "job": "Lawyer", "region": "East"},
        {"id": "E", "job": "Doctor", "region": "West"},
        {"id": "F", "job": "Doctor", "region": "West"},
        {"id": "G", "job": "Lawyer", "region": "West"},
        {"id": "H", "job": "Lawyer", "region": "West"}
      ],
      "transform": [
        {"type": "nest", "generate": true, "keys": ["job", "region"]},
        {
          "type": "tree",
          "method": "tidy",
          // "field": "id,job,region"
          "size": [{"signal": "width"}, {"signal": "height"}]
        }
      ]
    },
    {
      "name": "links",
      "source": "tree",
      "transform": [{"type": "treelinks"}, {"type": "linkpath"}]
    }
  ],
  "scales": [
    {"name": "color", "type": "ordinal", "range": {"scheme": "category20"}}
  ],
  "marks": [
    {
      "type": "path",
      "from": {"data": "links"},
      "encode": {
        "enter": {"stroke": {"value": "#ccc"}},
        "update": {"path": {"field": "path"}}
      }
    },
    {
      "type": "symbol",
      "from": {"data": "tree"},
      "encode": {
        "enter": {
          "fill": {"scale": "color", "field": "id"},
          
          "stroke": {"value": "white"},
          "size": {"value": 400}
        },
        "update": {"x": {"field": "x"}, "y": {"field": "y"}}
      }
    },
    {
      "type": "text",
      "from": {"data": "tree"},
      "encode": {
        "enter": {
          "text": {"field": "id"},
          "fontSize": {"value": 30},
          "baseline": {"value": "middle"}
          
    },

        "update": {"x": {"field": "x"}, "y": {"field": "y"}}
      }
    }
  ]
}

**Comment by jheer** [comment]
I'm not exactly sure what this issue is requesting, but in any case it appears to be a usage question, and so would be better suited to the Vega Google Group or Slack channel.
