### ISSUE TITLE
Specify a minimum distance between labels for overlap determination.

### ISSUE THREAD

**Issue by TickleThePanda** [vega/vega#1507]
I'm using `"labelOverlap": "parity"` which generally works quite well. However, there are cases where the labels get close together and difficult to read, as shown in the example below.

![Labels too close together.](https://user-images.githubusercontent.com/13658288/50515662-f5b60200-0a9d-11e9-9fcd-ded1eaa303ff.png)

Is there any way to specify a minimum distance or padding between labels?

**Comment by jheer** [comment]
Currently there is no way to specify this (other than explicitly added whitespace to your labels, which sounds terrible...). In the future it is possible we could add a tunable tolerance or offset parameter for the label bounds overlap calculation. Currently we have a hard-wired extra spacing of 1 pixel.

I'm flagging this issue as an enhancement request to add a new parameter here.
