### ISSUE TITLE
Why isn't `sequence` included in standalone Vega-expression?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1508]
I remember that runtime functions are not included in 
https://github.com/vega/vega/blob/master/packages/vega-expression/src/functions.js.

However, I wonder why `sequence()` isn't included given it can be run independently?

**Comment by jheer** [comment]
I am creating a new vega-functions package that houses specialized expression functions. The built-ins within the vanilla vega-expression package are intended to be relatively minimal and reflect common built-in JavaScript operations. While technically we could move a few of the other expression functions there, I'm not sure if there is a strong need at this point.

Or, put another way, give me a strong reason and I can reconsider and potentially re-open the issue!

**Comment by kanitw** [comment]
Just to give you more context, in Vega-Lite, we now define some rules using Vega expression and try to evaluate it at compile time if possible (and keep the formula if the expression depends on a signal).  


This is simplify our codebase as we only have to define the rules once without having to repeat the logic to check if a certain property is a `SignalRefComponent`. (Vega-Lite internal representation of a Vega `SignalRef`.)

![image](https://user-images.githubusercontent.com/111269/52380591-40268900-2a23-11e9-92d3-7ca3f57498a5.png)

(See this [commit](https://github.com/vega/vega-lite/commit/91b7761efbd50c6d6e1f549588ba671b885dd22f) for more.) 

I don't have strong opinion whether this should be in the main vega-expression or not.  I assume that the `vega-functions` will make it easy to include specialized function that can work during compile time such as sequence when we invoke vega-expression. So that should be fine.

**Comment by jheer** [comment]
Sounds good. Why don't you take a look at vega-functions when it lands and if you still have questions / issues we can revisit them!
