### ISSUE TITLE
Support for strokeWidth scale in legend

### ISSUE THREAD

**Issue by marcprux** [vega/vega#1513]
When trying to encode a field as "strokeWidth" in the editor with vega-lite 3.0.0-rc10, the following error is raised: "Error: Missing valid scale for legend." Setting "strokeWidth" to a constant value does seem to work.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43}
    ]
  },
  "mark": "square",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "strokeWidth": {"field": "b", "type": "quantitative"}
  }
}
```

**Comment by kanitw** [comment]
(Moving from Vega-Lite)

We previously add `strokeWidth` as a channel in Vega-Lite to support conditional encoding. However, we haven't make `legend` in Vega support `strokeWidth` as a channel yet.  

I think this is a reasonable additional since users may want to combine the `strokeWidth` with `strokeDash` to encode data. Here is one example:

![image](https://user-images.githubusercontent.com/111269/50544489-85d48280-0c29-11e9-8482-836f1408f072.png)


http://gnuplot.sourceforge.net/demo_4.6/dashcolor.2.png

**Comment by marcprux** [comment]
FTR, manually disabling the legend for the "strokeWidth" encoding does render the vega-lite without error:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43}
    ]
  },
  "mark": "square",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "stroke": { "value": "green" },
    "strokeWidth": {"field": "b", "type": "quantitative", "legend": false }
  }
}
```

Perhaps we could just default to legend=false for strokeWidth for the short-term until proper legend support is added? That way it won't be confusing when people try one of the documented encoding properties and get an error.

**Comment by kanitw** [comment]
@marcprux -- I think that's a good idea, though I think that we better just fix it in Vega.  Feel free to submit a PR for either solution.

**Comment by marcprux** [comment]
For the record, the same issue applies to the "strokeOpacity" encoding: unless the legend is explicitly disabled, the "Error: Missing valid scale for legend." will be raised when trying to use the encoding.

**Comment by kanitw** [comment]
https://github.com/vega/vega-lite/pull/4454 disables legend for `fill/strokeOpacity` and `strokeWidth` in Vega-Lite.  We can enable them again once we support any of these in Vega.

**Comment by kanitw** [comment]
I think supporting legend for  `fill/strokeOpacity` is lower priority than for `strokeWidth`.
