### ISSUE TITLE
Hide overlapping ordinal axis labels

### ISSUE THREAD

**Issue by marcprux** [vega/vega#1520]
Temporal and quantitative axes prevent overlapping labels by showing the right number of labels to prevent occlusion. Ordinal labels should do this as well by simply dropping intervening values that might cause the overlap. It could be an option, but since overlapping axis labels are always ugly and unreadable, I think it should be the default.

![occlusion](https://user-images.githubusercontent.com/659086/50857069-7e645600-135a-11e9-8920-557c5435c919.gif)

**Comment by jheer** [comment]
You can enable the desired behavior by setting `"labelOverlap": true` for your ordinal axis. If you want this to be the default behavior, you can set it in the config. For example:

- `"config": {"axis": {"labelOverlap": true}}` (for all axes), or
- `"config": {"axisBand": {"labelOverlap": true}}` (for specific axis scale type)
