### ISSUE TITLE
rounding/truncation artefacts when setting non-integer rect dimensions

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega#1521]
When creating a "heatmap" composed of `rect` marks, it appears not to be possible to set reliable width and height values for each `rect` so that there is no sub-pixel gap or overlap between adjacent marks. I suspect this is due to floating point truncation/rounding as it applies only when the `width` or `height` is not some nice multiple of the `rect` width/height.

In many cases this can be overcome by setting the `rect` width/height to be 1 pixel larger than necessary. But this leaves overlay artefacts if the fill colour is not opaque. 

An example of the problem here:

https://gist.github.com/jwoLondon/527f27c26523cf7a7f492aad69b7c771

Is there any way around this?

**Comment by jheer** [comment]
Yes, there is! If using a `band` scale, set the `round` property of the scale to `true`. Note that this can result in leftover unused space in the range. You might also want to set the `align` property to determine where the "used" portion of the range is positioned. (Visual encodings also support a `round` property, but this simply rounds the number with no other considerations. The `band`/`point` scale rounding logic is more nuanced, ensuring all bands have an equal width and are contiguous.)

vega docs: https://vega.github.io/vega/docs/scales/
d3-scale docs: https://github.com/d3/d3-scale#band_round
