### ISSUE TITLE
Gridlines disappear when height is only set implicitly

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1524]
In the [spec below](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KAHdGAExbYwAJgAMuxREjpWebrEYAvZFsiF0ahUsgYATgGtYWgNpKIoCECoPABPQhscSGpXblZCJyCjZBl4bjUIsADEozi1dDwMrOyjVQ1ELWBICnQAG1YMvV0AX0NioxRGanwKqtr6rUamv0Sh7Jbho3QAD2QvHF82ouLIBFqMlYS2qG5XRmS8W3ZuAm5UTbao3cccPFd6icDRxIBdYafn1pX4NbmwBcClkYZOhUOsvK0gpBQuFbDVGDJkOhXOdApA1Kd0PCfAYwABGfQfB6QVzoGTUDLeHGNV5Bd4gJpAA), the grid is invisible. When I [set the height explicitly](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KAHdGAExbYwAJgAMuxREgpG1fFr0GlkdKzzdYjAF7ItkQujULrGAE4BrWC0AbSUIUAhIqDwAT0JXHEhqX25WQm8oo2QZeG41BLAIzKM0tXQ8AqLio1UNRC1gSAp0ABtWAssAX0NqoxMzPAam1vaLfU6wzIni7smjdAAPZCCcUN6q6sgEVoKtjN6obl9GbMHE9m4CblR93qTjrxw8X3a5yOnMgF1Jj8+erfgOxWYDWkQ2Rhk6FQuyCPSikFi8TcLUYMmQ6F8t0ikDU13QqJCBjAAEZ9H83pBfOgZNQCsEiZZvlFfiBOkA), the grid appears.  

```
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "width": 200,
  "autosize": "pad",
  "marks": [
    {
      "type": "group",
      "encode": {
        "update": {
          "width": {"value": 200},
          "height": {"value": 200}
        }
      },
      "axes": [
        {
          "scale": "s",
          "orient": "bottom",
          "grid": true
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "s",
      "type": "linear",
      "domain": [0, 100],
      "range": [0, 200]
    }
  ]
}
```

**Comment by jheer** [comment]
The axis needs to know the height somehow, and so uses the default spatial axis range, which is defined by signals. The solution is to set a `height` (or, in the transposed case, `width`) signal, which can be done within the group mark's scope if desired. Alternatively, axes also accept a `gridScale` property, and will then use the range of that scale to determine gridline extents.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "width": 200,
  "autosize": "pad",
  "marks": [
    {
      "type": "group",
      "signals": [
        {"name": "height", "value": 200}
      ],
      "encode": {
        "update": {
          "width": {"value": 200},
          "height": {"value": 200}
        }
      },
      "axes": [
        {
          "scale": "s",
          "orient": "bottom",
          "grid": true
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "s",
      "type": "linear",
      "domain": [0, 100],
      "range": [0, 200]
    }
  ]
}
```
