### ISSUE TITLE
how can i select top 1 data by specified field in dataset?

### ISSUE THREAD

**Issue by yechanpark** [vega/vega#1525]
hi. im using vega3.

i want to select top 1 element by 'contentDelay' in 'Data5' array 

![how select top 1](https://user-images.githubusercontent.com/18444806/51436817-a7c89e80-1cd7-11e9-9e66-53b5f1681f70.jpg)

in Data5, 'contentDelay' is already sorted (by descending)

but i don't know how can i select top 1 data (in this case, 'Data5.0' object.)

following 'filter' transform doesn't working.
```json
"transform" : [
        {
          "type" : "filter",
          "expr": "max(datum.contentDelay) === datum.contentDelay"
        }
]
```
above filter returning all of datas in Data5. ('Data5.0', 'Data5.1')
this mean 'filter' transform applying the filtering each data in dataset.

but i want to compare each other in Data5.

how can i select top 1 data?
i will use Data5's other field.

so, i cant use 'aggregate' transform's 'max' operator. 
this transform causing data format's changing.

i want to use dataset format for using Data5's other datafield. not only 'contentDelay'.
but i want to filter only one that i want to show.

**Comment by domoritz** [comment]
You can use a window transform to assign a counter and then filter by it. 

@jheer in light of our efforts to support larger data, would it make sense to add a limit transform?

**Comment by yechanpark** [comment]
@domoritz thx for your response.

i added following 'window' transform, and this working perfectly.
```json
"transform" : [
        {
          "type": "window",
          "sort": {"field": "contentDelay", "order": "descending"},
          "ops": ["rank"],
          "fields": [null],
          "as": ["rank"]
        },
        {
          "type" : "filter",
          "expr": "datum.rank===1"
        }
]
```

and dataset's format is not changed, and just 'rank' filed is added each array element.

thx 😄 

close this issue
