### ISSUE TITLE
Can I draw scroll bar each graphs in one vega script?

### ISSUE THREAD

**Issue by yechanpark** [vega/vega#1527]
hi. im using vega3.

im drawing multiple graphs in one vega script.
like this [example](https://vega.github.io/vega/examples/pi-monte-carlo/)

i want to drawing vertical scroll bar at each graphs like this.
![scrollbar each graphs](https://user-images.githubusercontent.com/18444806/51456312-837cc880-1d90-11e9-94b3-08c5c76f577a.jpg)

at first (left) graph, if Y-Axis's element will be expanded infinitely.
then, first graph will be hard to see all of the element, and graph's height will be too long.
so i need vertical scroll bar.
in same aspect at second graph, so i need horizontal scroll bar.

i tried to adding signal into 'marks' property, but inner signal cant be binded error occured.
so i must declare 'signals' property at outer-separated-config. 
but if scroll bar's position is too far from graph, this is weird. hard to control it.

and i cant separate graphs via multiple vega scirpt.
because all of graphs must interacting each others.
(for filtering dataset or Click Event.
if i choose some element on first graph, second graph will be showing only one element that i choosed.)

how can i fix this?

**Comment by domoritz** [comment]
I don't think you can do that in a single spec since Vega renders to SVG and canvas and does not support CSS overflow, which you could use for this. However, you can make multiple charts and communicate through the Vega view API.

**Comment by yechanpark** [comment]
@domoritz thx for your fast response.

can i use 'Vage view API' in kibana 6.4.1 ??

**Comment by domoritz** [comment]
I don't think so (cc @nyurik).

**Comment by domoritz** [comment]
Also see https://github.com/vega/vega/issues/1402

**Comment by yechanpark** [comment]
@domoritz 

thank you
and thank you 😄😄😄😄😄
