### ISSUE TITLE
multiple time data request with parameter

### ISSUE THREAD

**Issue by yechanpark** [vega/vega#1530]
hi, im using built-in vega 3.2  in kibana  6.4.1.

my graphs interact each other.

when i clicked component in graph1,
this component's xscale's value and yscale's value will be clue for graph2's dataset.

but, all of Vega (and Vega-lite) Examples implemented 'one request and one response'.

so, i'm requesting all of datas that i need to growing graph or not.

i'm using aggregate with multiple depth.  this is too slow to use.
(Of course, i will refactoring my heavy query)

i thought
'how can i provide what i selected component's x/y scale's value as parameter for second data request (including multiple times) via Signals (or ClickEvents etc) ? then, unused datas will not be into request parameters and response, query performance will be improved..'

if i can use this feature,
elasticsearch's resource will be improved and download speed (response json) will be improved too.

i'm using 'filter' transform to filter datas that grpah2 needs now.

but i cant find those example. can i do this?

P.S.
i saw #1424 . what i told thing is same aspect in this issue ??

**Comment by jheer** [comment]
It sounds like you are determining which dataset (really, query) to use for graph 2, based on selection information from graph 1? As of version 4.2, Vega supports dynamic signal values for the data `url` parameter, which could allow you to generate dynamic REST queries. However, I don't know how this interacts with any Kibana-specific facilities; @nyurik might know the answer to that!

For more, see:
- https://vega.github.io/vega/docs/data/#dynamic-data-loading

**Comment by nyurik** [comment]
Kibana currently uses a fairly dated (~v3.3) version of Vega, and needs to be updated. It is great that Vega supports fully dynamic data sources now!  P.S. @jheer are there any examples available of the dynamic data? I saw the docs, but it only explains it as text, not as a Vega spec snippet. Thanks!

**Comment by jheer** [comment]
@nyurik No online examples of dynamic data at the moment. Free free to open a new documentation request issue!

**Comment by yechanpark** [comment]
@jheer
@nyurik
thx for your response. l will update and check vega 4.x

:D
