### ISSUE TITLE
range scale doesn't come up always - choropleths geo map

### ISSUE THREAD

**Issue by false9striker** [vega/vega#1531]
I have a choropleths geo chart created using vega. 

Issue: The range scale is not coming up always. It comes when the application is up and then on refresh or some action on the page it shows empty rage scale(without the color bar), values are coming fine though. 

Please find the vega editor link with chart [here](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq6ArIoiQA7owMtdADgAMn+7mSNqfFtvX0hYPABPABsdHEh4ZCio4wcDdDxMHABtJQhQCAKoGXRUWKhpVgAnBIB9AEYUwqgq5Lj8IhJyKloGZjZOHlJkCzVK0jSM0kduSqiDAFo6us9USWk5X0LIADMZjDxdfKaHSMIyyDVCbilZRuOd5HSq8-huVhk8SsZkWEhcgoAvpsChdKugZLBdpVULocsc8v97qdzttGFE8MhKnd4ZBkAAPQhYuITVirFwAQgAvMs-vCwADEWAALr-IH-I5bYqlXRhN7VZA1TzYk5giFQmHZRkIuknCJnHlRbjcADWrEIwqaO0q3Al5T5tQawPuyuQER5Lg1W1RiQMv2ykAtTKNmvQdrAWUg1GQ3EgLLpbLpHJxyJ5Xuu60tILDNzkcTDkYcGmoxVaUCQaIMNSuhFYUXSPBkNWj60FtPhDOOTsZkAo6CirB+sKlYCD92kpQAwm8Ph4AJy951bdsCiboTwAJl045CzYcFrAOAAzOPByDXgZzgBBABKCbT3c+Zrim8qXo+lkwzYD8NbmuHXfeBxw4+WPlnetKNVHE6nM5lUHnJcADZVwcdctwAVT3eID0qI8oE3VhwjBKJGEvf1V1vIcdWQB8e2fTw6nHRdQI-Ed0jHScCLff8HSMBcwHcUQaJlGCNx5CCAGVoNeR84I4mRmGGTiMgxX4r0w99eU7A9dDqdwiJAqThy-Cif2o0i6MgBjFxsJTaPAnkAEkADkeNg+DICMmQLHQ8tJNo+9ZJwOpmL-ViVO-KiwGndy6S0hiiNETTDLiDtN3MvjLI7cFDDs45r2OLCQScx8PAAdiAuxlJw1SMnUsBXxY-zALARdexXKTQqgAApAAFSKPn4uIavQfQ5Ak5tksTHC8KfQqiMXYKcs-Ly5O8YqcVK9xx301jqsgCCAGlGsPAShIMMAlssagDB1MsEocjzeucnyhuyxzcrGnBe0m+5StEJiQu4di4gAWQADVW5qoDe-FGFeA6mkSppurIvq5Mei7jtGtTvNuzTSrqPTnteqAOwACW+6LEAvIHChBwowek3DTvHdL3AHEbyPy+G7s1UrMtR84ACFd2eqKeRZsFNDRfHASO-zUvwsBmM0zy4d0BGpNKoD3GZrmAHlsa57hUIoND+YgQmCmJ4X+tEXsvHFq7JZu+mtll0QSKql7zm3KCOaayztyQjR4uBwWcX1vtjepvLKKli2QUZmxKoMu2eU4gBRFW4k4xxhmQDqMK66mIZco3g562HaaDxH6OfUQ5v8haADEjLjqAy8sPMbK1+kvbbE60pwR7s7IgOCul2jSpsCmFbiEzladtah5mRx0DNTrA3T07KY7kmu7pgvtLbmx5dttHIDegBNKud7rKf3YbnXpRh0nW8YrOTdzwPzdXhiN5LnEFrqlbR5+yA6vQZVGHCcEp8m53hbiLact8ab3x8ovRmyxB5QAAFoRU-pZTibwWBgE3NsL48APYE2AdhGSV8iKeCppdO+BVwEy0LmAdK45hoR23tHbiKCo76EsEAtO5DL4i1EMsMhF9l6-kfs+Gwi9y7s1tpzOIZdRQJE4bPbhGdRa9mXBAoRBERFgCAlQxh5w6oABUD51RmHgVgtBkgzxvHPYhi41H+2utArRFMGHzUjseWOrC4gQToJuOgscrFJRsbw9RjjdGsT7jYVxpd3FQBMggg+JlkCODAAgx4dcjBXgKIyP0gIlBVgcISa4yB4B4ALG6OEutqxcnOEUiQJSym3GdGELQZRgAtOTHWHkWRnCuEQPIMAKAAj4CZJAHWOxmCHA6SmHk6Y5hZm4DmPMjTCzFlkKWcZIY4ilGqOkGYQMKzMlCHmCI6DDj-FMIYCwVgpnakcONAZMF6yoFjIVTwIMnmkghHJYEkB2DdltDybYuZki-LrAEV5kA6yWO1qEDAlRlQVPZNUko5wTmYkFDUeFiKNQXDlOcWAiA2o6GaeEaIZRKn3DDIS4l-MCmamwftHAyVICjh5BUfk9R+bjOTtVFlaoJhtKkqiJI5z-wOFrPWc4ABiXsQE5VyobrC5SnwVRCvFVASVDYeSOFxhiJVjcpJqDVmU9UzL3wOGtHMc0mT-yHISoyTZopIR7CbIo1iWyoDUqJfKTSdSGkFh5P60pgarw5NZMCW8eL5Rxm1GqXFNTZm43mdmXM+Z1nUDjeqUlkQYizMSKC6svLYn8sIIKqZvS3DMumV0uIlbEBjMeUMwI-V2lJhmW0fwLaxn2oFtWbFSL3X+UTXEOZmZU3LILFi9ACLfiaU9WEH1JKVXkthJ6b0NL5T0v8oy3U7S2VxA5bUIUZ8QTFrRmDBwAr0jqo1VAEVqZKV3svcGH4-VWVPFQFkAAOiTPqv6mRgEpMBsAMgQVgAAD4QbAP-Ey6ATIAAoSRft-frADABKPc-ktVlDA0kC1nsCNEzCLgvNo7k3jsWWmlZNRXiKixI8q1RhD2gIOL2-827xUXCVOiRgZqWxEZShC2tUBgC-rQaUMA-7dDinSEhz9P6-0HgAwM39v70P0gNQTAj7HCO0U+OCF10I3XipfbKGNXqN1LqwyCYNKyg3anqSGppgmJk2h5MhxTYYANafpO+XJDrKzNJiGeQFkoh04gfUmjMCylnpsLHR-ZmlM2GG+B8AAMsnagVaWw1tTPEPMqBCAIebfgAZQFgrQM8Jh09JxmBkagBJ5AUnZJhsrKyfJoQEB1kbOFqp9wR1pgo7F6jU7EsMerAu2AyAACODZzxdOaXtDAHDq0Hr1FUY9Ch73fGtSxohPZxnaG1DJus03mmii9FM-gaBzgRALdwRwmbkDJ3YFKxt1YbvcjiPdpIj3nuvfex1iA9KYIyFRNYc1Wx0B4n-vvKHmpUCWGjniDEItFyeAjRcslDWo0JFFQjtsqqTQ8gMxCfQlRk4HEdcDvzAIgA) 

Also please find attached both images. In first image it works fine similar to editor example. Second image shows how it comes later. There are not errors shown in the console as well. 

Image 1(works fine)

<img width="953" alt="works_fine" src="https://user-images.githubusercontent.com/628338/51599667-36325f80-1f26-11e9-84d5-8a1135c7973c.png">

Image 2(doesn't work)

<img width="1182" alt="doesn t_work" src="https://user-images.githubusercontent.com/628338/51599682-3fbbc780-1f26-11e9-9b51-a97d9e63abbf.png">

**Comment by false9striker** [comment]
This was happening due to # getting appended in the url. 

With `e.preventDefault();` this is fixed.

**Comment by jheer** [comment]
Glad you figured it out!
