### ISSUE TITLE
how can i set default date set in Signal?

### ISSUE THREAD

**Issue by yechanpark** [vega/vega#1533]
Hi. im using vega3.

im using vega with elasticsearch.

in ElasticSearch, there is 'Terms Aggregation' and this aggregator has 'min_doc_count' property.

'min_doc_property' insert value '0' to response by force even if no results exist in query's response
but terms aggragation occurerd heavy traffic(need many resources) and making too many buckets.

when i using 'date_histogram' interval '1m',  elasticsearch returning data array by 1 minutes.

in terms aggregation, if there aren't exist data that matched in condition, return empty buckets.
so, if i want to drawing graph include value '0', i must using min_doc_count.

but i cant use 'terms aggregation'. there are too many datas.
so, my request query using 'Composite Aggregation' for query performance.
'Composite Aggregation' doesn't support 'min_doc_count' property.

this mean if today 12:00's value is 0, graph doesnt draw at 12:00's value.
so, i don't know today's 12:00 value is actually 0  or increase steadily.

so, i decided 'implement dateset of daily minute that all graphs can sharing' in vega.
ex. 00:00 ~ 24:00

i must declare this value via Signal.
(sharing multiple graphs each other for using 'Scale'.)

so, if dataset's date in dateset(Signal), drawing dataset's value.
and if dataset's date not in dateset(Signal), drawing 0  like this.
![nodata](https://user-images.githubusercontent.com/18444806/51730961-c99d9900-20bc-11e9-9502-316e9f3f5dd7.jpg)

i want to drawing like this using 'Composite Aggregation'.
![yesdata](https://user-images.githubusercontent.com/18444806/51731091-2bf69980-20bd-11e9-92b9-276598f51412.jpg)

can i do this?

P.S.

is this right?
```json
    {
      "name" : "myDomain"
      "update" : "[datetime(0,0,0,0,0,0,0), datetime(0,0,0,23,59,0,0)]"
    }
```

i need 'HH', 'MM' date only.

**Comment by jheer** [comment]
Yes, you can set dates in a signal using the `datetime` expression function within a signal definition's `update` or (as of Vega 4.4) `init` property.

For more, see:
- https://vega.github.io/vega/docs/signals/
- https://vega.github.io/vega/docs/expressions/#datetime-functions

**Comment by yechanpark** [comment]
@jheer
thx for your response.

i will check that docs

:D
