### ISSUE TITLE
viewing vega charts on older browsers

### ISSUE THREAD

**Issue by xujiboy** [vega/vega#1535]
Hi,

I am trying to view python `Altair` generated `Vega` charts (in html format) in a older browser in REHL6, specifically, Firefox 45 ESR, but the page just appear blank and it seems to me that the browser can't render it. `Vega`, `Vega-lite`, and `Vega-embed` are sourced in the html file as the following:
```
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm//vega@4"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm//vega-lite@2.6.0"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm//vega-embed@3"></script>
```
I wonder if this problem is due to Javascript ES6 support issue, and how can I get around it, without updating the browser (I don't have root access).

I use the browser to navigate to Vega online editor and it appears blank as well. Interestingly, when I navigate to the [Example site of Vega](https://vega.github.io/vega/examples/) I have no problem viewing the examples.

**Comment by domoritz** [comment]
We switched Embed to ES6 in https://github.com/vega/vega-embed/commit/72c46743df76418787631dd2c7466903bb929426. You can use an older version if you need es5. Vega 4.4 also drops support for es5 so you would need to use 4.3. 

Firefox 45 EST ended support in June 2017. I recommend that you contact your administrator to update.
