### ISSUE TITLE
Support join in view API

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1537]
D3 now supports join and I think it would be a great addition to Vega as well. I don't think it makes sense for encoding blocks but it would be cool to have it in the view API. I imagine this will be particularly useful once Vega has transitions (cc @yhoonkim). 

https://github.com/d3/d3-selection/blob/master/README.md#selection_join

**Comment by jheer** [comment]
I don't understand this feature request. The new D3 `join` is a new syntax for the existing enter/update/exit data binding. Vega does not use this functionality of D3 and performs its own data join internally. So I don't know what is being requested here.

**Comment by domoritz** [comment]
D3's join functionality encapsulates enter, update, and exit in one instruction. I think it could be useful to have something similar to join in the Vega view API for data updates (https://vega.github.io/vega/docs/api/view/#data-and-scales). 

Instead of 

```js
view.change('data', vega.changeset().remove(vega.truthy)).insert(newData).run()
```

one could write

```js
view.join('data', newData).run()
```

Under the hood, Vega could figure out what tuples have been removed, edited, or remain unchanged and send a more efficient changeset down the dataflow. Or am I missing something here?

**Comment by jheer** [comment]
To do this reliably one would need an explicit key function. In D3, the join is between the data objects and DOM elements. This context is different: it is comparing an old data set with a new data set. The "base condition" of joining based on array index doesn't seem sensible here. Moreover, we'd open up a new surface area for errors, such as input arrays containing objects that repeat key values. As a result, I'm not convinced this addition would gain us much. Perhaps with a different design we could improve on the current approach involving an explicit changeset? In the meantime I'm closing this out, but feel free to add file a new issue if you have ideas for a thorough API design.
