### ISSUE TITLE
Support richer axis & legend title text layout.

### ISSUE THREAD

**Issue by marcprux** [vega/vega#1540]
The `titleAlign` property does not seem to work as expected in v3.0.0-rc12. With the following spec that tries to right-align all the titles:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {"url": "data/barley.json"},
  "mark": "bar",
  "encoding": {
    "x": {"aggregate": "sum", "field": "yield", "type": "quantitative", "axis": { "titleAlign": "right"}},
    "y": {"field": "variety", "type": "nominal", "axis": { "titleAlign": "right"}},
    "color": {"field": "site", "type": "nominal", "legend": { "titleAlign": "right"}}
  }
}
```

the output has the titles pushed leftward. They should (presumably) be aligned against the right edge of the legend/axis.

![image](https://user-images.githubusercontent.com/659086/51933527-82bae680-23cf-11e9-817c-3c7bd7a9dd5f.png)

**Comment by jheer** [comment]
The `titleAlign` field maps to the `align` encoding channel for a text mark. It determines only how the text is oriented relative to its x/y anchor point, it does not change that anchor point.

If you change the title position (set the title x-coordinate to the width of the legend) you can get the desired effect!

**Comment by marcprux** [comment]
The problem is that the width of the legend/axis is not known ahead of time, so there's no general way of aligning these titles without hardcoding a width (which might change due to resizing, etc.).

I think everyone would agree that the current behavior of "titleAlign" is unattractive and not what an end-user would expect. So perhaps this issue could be re-phrased as an enhancement request to center-anchor titles against their respective axis/legend spans so that changing the alignment will behave as expected.

**Comment by jheer** [comment]
I hear you. The answer also depends on whether we're talking about Vega or Vega-Lite here.

In Vega, the axis width *is* accessible, either via the `width` signal or by using the `range` expression function. The legend width can be unpredictable, but can be constrained to known max width. 

That said, I can see value in providing richer layout options for title positioning as part of the vega-view-transform ViewLayout operator. Any such options might then be accessible to Vega-Lite as well. I'm re-opening the issue and flagging it as a feature request in response!

**Comment by jheer** [comment]
Note: There is also interest in supporting alternative text layout strategies for legends (#1465); namely placing the title inline for a horizontally-oriented legend. It might make sense to consider both requests in tandem.

**Comment by marcprux** [comment]
Another quirk of the current layout is that aligning a left-oriented legend title to the left looks fine:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {"url": "data/barley.json"},
  "mark": "bar",
  "encoding": {
    "x": {"aggregate": "sum", "field": "yield", "type": "quantitative", "axis": null},
    "y": {"field": "variety", "type": "nominal", "axis": null},
    "color": {"field": "site", "type": "nominal", "legend": { "title": "Some Long Legend Title", "titleAlign": "left", "orient": "left" }}
  }
}
```

![image](https://user-images.githubusercontent.com/659086/52164901-ecd0d580-26c6-11e9-93eb-6a788506ea02.png)

But right-aligning the legend title pushes the rest of the visualization to the right by what appears to be the size of the text:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {"url": "data/barley.json"},
  "mark": "bar",
  "encoding": {
    "x": {"aggregate": "sum", "field": "yield", "type": "quantitative", "axis": null},
    "y": {"field": "variety", "type": "nominal", "axis": null},
    "color": {"field": "site", "type": "nominal", "legend": { "title": "Some Long Legend Title", "titleAlign": "right", "orient": "left" }}
  }
}
```

![image](https://user-images.githubusercontent.com/659086/52164946-a760d800-26c7-11e9-85c8-dd2abf067e37.png)

**Comment by roying** [comment]
For Vega users interested in rendering custom legend layouts, it would be very helpful if the legend parameters (title, labels, symbols, gradient) are accessible via Vega view API by signal expression.

**Comment by domoritz** [comment]
@roying you can use signals to drive any of these parameters and drive those signals via the view API. You have to define the signals yourself, though.

**Comment by roying** [comment]
What I meant is a way to get all the parameters (data backing) the legend from Vega view API so custom legends (and perhaps "plugins") can be implemented in javascript (similar to Vega's support for tooltip). For example: view.data("mylegend")
