### ISSUE TITLE
Ambiguous documentation for vega-expression package

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1556]
Following the conversation in #1508, I think the main confusing part for `vega-expression` is that its [README](https://github.com/vega/vega/tree/master/packages/vega-expression) states that: 

> Parses a limited subset of JavaScript expressions into an abstract syntax tree

(and link "limited subset" to https://vega.github.io/vega/docs/expressions/).

This implies that the Vega-expression supports all functions in https://vega.github.io/vega/docs/expressions/ by default. 

However, it only supports even more smaller subset (as some other functions are in `vega-functions`, not in the `vega-expression` itself).

**Comment by jheer** [comment]
Agreed. I think the `vega-expression` readme should clarify what constants and functions are provided that package alone. Thanks!
