### ISSUE TITLE
Why my Vega tree shows blank leaf nodes at the end of the tree?

### ISSUE THREAD

**Issue by biji-padhy** [vega/vega#1560]
Hi All,

I am trying to plot a flatten tree transformation using the vega visualization in kibana. I am able to plot the tree perfectly but unnecessary leaf nodes are getting created with no data. Could someone please help me to get rid of the extra child nodes? Thanks in advance.

I am attaching my code snippet, sample data and tree picture for your reference.

![image](https://user-images.githubusercontent.com/46964414/52633474-829c0a00-2eea-11e9-8dc8-ea0ed3ccec81.png)

[Vega Tree source Code.txt](https://github.com/vega/vega/files/2855644/Vega.Tree.source.Code.txt)

[sample.txt](https://github.com/vega/vega/files/2855650/sample.txt)

**Comment by nyurik** [comment]
Please follow [these instructions](https://gist.github.com/nyurik/736c34970ba3c32f3fe3d45d66719b3e) when posting Kibana questions. Thanks! :)

**Comment by domoritz** [comment]
Can we make these instructions a pound issue here?

**Comment by nyurik** [comment]
@domoritz I would charge more than £1 for that ;)  But yes, we should make those instructions more prominent on the issue page.

**Comment by domoritz** [comment]
I like your suggestion to put it in an issue template. We've had success with this in Vega-Lite.

**Comment by jheer** [comment]
I opened a PR with some new issue templates: https://github.com/vega/vega/pull/1563

Feel free to share any feedback there before I add these to the project. (And ignore the duplicate template in there, I'll fix that later...)
