### ISSUE TITLE
internet-explorer.md does not appear to be linked from anywhere

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1569]
Looking at the documentation, it appears https://vega.github.io/vega/usage/internet-explorer/ is not linked from any other docs, especially the https://vega.github.io/vega/usage/#ie page. Should that page be deleted or linked to? Also, would it make sense to mention that Vega <= 4.3 supported IE 10 & 11?

**Comment by nyurik** [comment]
@jheer in the above, should `index.md` link to `internet-explorer.md` ?

**Comment by nyurik** [comment]
(Unless I'm misunderstanding how `[supporting Internet Explorer](internet-explorer)` works)

**Comment by jheer** [comment]
It is linked.
