### ISSUE TITLE
Tooltip handler duplicates controls rendered in custom controls container

### ISSUE THREAD

**Issue by lizozom** [vega/vega#1575]
This is similar, but not identical to issue [1487](https://github.com/vega/vega/issues/1487)

Basically, if a user has a custom controls container
https://github.com/vega/vega/blob/b0dbd40da64fda541cfe2c848c0965457009c766/packages/vega-view/src/initialize.js#L7

And then adds a tooltip handler, it will call _resetRenderer
https://github.com/vega/vega/blob/5cbb35351def4fd061fc6ffbe6ac2ac190914f20/packages/vega-view/src/View.js#L197

But the call to _resetRenderer doesn't use the **elBind** parameter, hence creating duplicate controls inside the internal vega-binding container.
https://github.com/vega/vega/blob/5cbb35351def4fd061fc6ffbe6ac2ac190914f20/packages/vega-view/src/View.js#L221

**Comment by jheer** [comment]
Thanks! Fixed in @d54d67c, will be included in the upcoming 5.0 release.

**Comment by lizozom** [comment]
@jheer Sweet!
When is the release scheduled to?

**Comment by jheer** [comment]
Release scheduled soon -- within the next few days!
