### ISSUE TITLE
Axis labels overrun title when using a larger-than-default labelLimit

### ISSUE THREAD

**Issue by pelotom** [vega/vega#1580]
[Example](https://vega.github.io/editor/#/gist/vega/pelotom/e2945b1925e473a9d4a4a37b0fe70811/3923af89e0a92e5a557ef268f7a0c3eb797d6ff7/axis-title-overrun.spec.json):

![visualization 2](https://user-images.githubusercontent.com/128019/52992073-19256b00-33c4-11e9-983e-dbaa0d1ab52d.png)

It seems like the maximum space alotted between the title and axis for tick labels is fixed, and designed to match the default `labelLimit`.

I saw [this issue](https://github.com/vega/vega/issues/155) which looks like it might be the same issue, but the last comment there seems to indicate it should've been resolved with Vega 4.

**Comment by jheer** [comment]
This is a configuration issue. Here we've updated `labelLimit` for axes, but not `maxExtent`, which defaults to 200 (20 pixels more than the default label limit of 180): https://github.com/vega/vega/blob/master/packages/vega-parser/src/config.js#L134

Set `"maxExtent": 520` in your axis config and things will behave as you expect.

**Comment by pelotom** [comment]
@jheer ah, I missed the `maxExtent` option, thanks!
