### ISSUE TITLE
Various treemap issues

### ISSUE THREAD

**Issue by mprudhom** [vega/vega#159]
Consider the treemap spec appended below. There are a few issues:

* The treemap transform seems to assume the "treejson" format, and if the data is not hierarchical, some datums don't have any "data" property, and thus raise an error if "data.someField" is references in a mark property. So a "filter" transform is required to filter out any datums that don't have any "data" property. If the filter transform in the spec below is omitted, the following inscrutable runtime error is thrown:

```console
[Error] TypeError: 'undefined' is not an object (evaluating 'x[f]')
	(anonymous function) (vega.js, line 79)
	reduce
	(anonymous function) (vega.js, line 79)
	(anonymous function) (vega.js, line 4852)
	buildItems (vega.js, line 4794)
	build (vega.js, line 4759)
	buildGroup (vega.js, line 4831)
	build (vega.js, line 4764)
	build (vega.js, line 6419)
	update (vega.js, line 6646)
	(anonymous function) (editor.js, line 64)
	(anonymous function) (vega.js, line 4643)
```

* Treemaps do not automatically resize when view.width(X).height(Y).update() is called. This may be because the size is also a function of the treemap layout, but that layout should be recalculated if the enclosing view is resized. For example, observe the lack of resizability at http://glimpse.io/gallery/treemap.xhtml

* The "treemap" transform appears to need to be on the top-level data, and cannot be a transform on the mark itself. If the "transform" list is moved from the top-level "data" element to the "from" mark element in the spec below, the following inscrutable exception is raised:

```console
[Error] TypeError: 'undefined' is not an object (evaluating 'group[d]')
	(anonymous function) (vega.js, line 2728)
	map
	size (vega.js, line 2727)
	treemap (vega.js, line 3736)
	(anonymous function) (vega.js, line 4162)
	reduce
	(anonymous function) (vega.js, line 4162)
	from (vega.js, line 4283)
	build (vega.js, line 4754)
	buildGroup (vega.js, line 4831)
	build (vega.js, line 4764)
	build (vega.js, line 6419)
	update (vega.js, line 6646)
	(anonymous function) (editor.js, line 64)
	(anonymous function) (vega.js, line 4643)
```

* The example treemap spec in the editor references a "depth" field, but it isn't documented in the outputs at https://github.com/trifacta/vega/wiki/Data-Transforms#-treemap. Inspection of ved.view._model._data["tree"] reveals some interesting properties that may bear documentation: "area", "depth", and "parent"

Here is the spec that can be used to demonstrate the aforementioned issues:

```javascript
{
  "padding": "strict",
  "data": [
    {
      "name": "tree",
      "values": [
        { "name": "A", "size": 1 },
        { "name": "B", "size": 2 },
        { "name": "C", "size": 3 },
        { "name": "D", "size": 4 }
      ],
      "transform": [
        { "type": "treemap", "value": "data.size" },
        { "type": "filter", "test": "d.data != null" }
      ]
    }
  ],
  "scales": [
    {
      "name": "color",
      "type": "ordinal",
      "range": "category20",
      "domain": { "data": "tree", "field": "data.name" }
    }
  ],
  "marks": [
    {
      "from": { "data": "tree" },
      "type": "rect",
      "key": "data.name",
      "properties": {
        "update": {
          "x": { "field": "x" },
          "y": { "field": "y" },
          "width": { "field": "width", "offset": -1 },
          "height": { "field": "height", "offset": -1 },
          "fill": { "scale": "color", "field": "data.name" },
          "fillOpacity": { "value": 1 }
        },
        "hover": { "fillOpacity": { "value": 0.8 } }
      }
    }
  ]
}
```

**Comment by arvind** [comment]
Lots to unpack here :) Let's see:

1. The treemap layout is based on [d3.layout.treemap](https://github.com/mbostock/d3/wiki/Treemap-Layout). It doesn't require data to be in treejson format specifically, but rather requires an array of nodes with a `children` pointer. Vega exposes the [children property](https://github.com/vega/vega/wiki/Data-Transforms#-treemap) for this. 

2. With Vega 2.0, the treemap transform's width and height can be specified via signals, allowing it to be resized along with the visualization. 

3. I'm not able to reproduce this issue with Vega 2.0. Perhaps we fixed it inadvertently :) 

4. `depth` is now a documented output property (`layout_depth`). 

Thanks for filing the issue, Marc!

**Comment by floribon** [comment]
I would like to bounce back on point 1 (the three others seems to have been fixed indeed).

It is easy to generate a "hirarchical" format from a data set by facetting the data and using "values" as the "children" field for the treemap transform.

However this only produces one datum, and in order to obtain a flat array of all areas the live editor example relies on the "treejson" formatting which is applied when loading the data.

Is there any workaround to that? Or could you consider allowing us to use an equivalent of {"format": "treejson"} that we could use at the mark level?

Without that we cannot generate multiple treemaps, or nested charts with generated treemap, or anything rather than plain single-treemap on load.
