### ISSUE TITLE
Vega 5 breaks webpack builds

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1596]
I'm getting a lot of errors of the form

```
ERROR in ../vega/packages/vega/build/vega-core.mjs 15:0-64
Can't reexport the named export 'formatDefaultLocale' from non EcmaScript module (only default export is available)
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./src/index.tsx
```

<img width="835" alt="screen shot 2019-02-20 at 18 10 35" src="https://user-images.githubusercontent.com/589034/53138343-db971e00-353a-11e9-93f1-7f4038e3b425.png">

I already changed my resolve to `extensions: [".ts", ".tsx", ".mjs", ".js", ".json"]` but it's not resolving the issue. Could this be a problem with the way vega generates .mjs files?

**Comment by domoritz** [comment]
It seems to work after adding

```
 module: {
      rules: [
        {
          test: /\.mjs$/,
          // include: /node_modules/,
          type: "javascript/auto"
        }
       ]
  }
```

but it seems like a hack. This could be a webpack issue but if it is, then it's a problem for a lot of Vega users.

**Comment by jheer** [comment]
Thanks! I just did some testing and it appears this is entirely a file extension issue. Within a webpack project, if I rename the module file in `node_modules/vega/build` and update package.json `module` to reference the renamed file the errors go away and everything works. I'll update the build scripts accordingly.
