### ISSUE TITLE
Tooltip on mouseover, hover, click

### ISSUE THREAD

**Issue by gitfoxi** [vega/vega#160]
A lot of the D3 demos tell you something more about a datapoint when you hover or click -- either in a floating tooltip or a fixed frame. Here's one that makes excellent use of the feature:

http://www.nytimes.com/interactive/2012/05/17/business/dealbook/how-the-facebook-offering-compares.html?_r=0

I was wondering what it would take to get Vega to do this? You'd have to attach extra info to the points. Instead of just X and Y, now you have Info. That would be straightforward but then what do you do to get the event to update the display? In the Vega examples, hover is clearly supported but there's only examples of using it to highlight the hovered mark.

I'm not sure if I'm making a feature request or if this is something that's doable already and I'm just asking how.

**Comment by orbisvicis** [comment]
Looking for an update on this, I opened a [StackOverflow question](https://stackoverflow.com/questions/65975046/show-tooltip-during-keypress-etc).
