### ISSUE TITLE
Convenience function to generate bins

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1601]
I often see myself writing `sequence(bin_maxbins_10_Rotten_Tomatoes_Rating_bins.start, bin_maxbins_10_Rotten_Tomatoes_Rating_bins.stop + bin_maxbins_10_Rotten_Tomatoes_Rating_bins.step, bin_maxbins_10_Rotten_Tomatoes_Rating_bins.step)`. It would be great to have a function like `bins(bin_maxbins_10_Rotten_Tomatoes_Rating_bins)` instead.

**Comment by jheer** [comment]
I'm supportive of this. Perhaps with some optional parameters to adjust the domain (e.g., if you pan bins outside the defined start/stop, we might still generate new bin boundaries)?

**Comment by domoritz** [comment]
In that one could fall back to the `sequence` method, I think.
