### ISSUE TITLE
Add tests to make sure schema is valid

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1604]
AJV can test whether a schema in valid (e.g. does not have unknown references). We should add a test that uses this functionality.

**Comment by jheer** [comment]
Are you referring to this? https://github.com/epoberezkin/ajv

**Comment by domoritz** [comment]
Yes. I didn't realize that it's not yet a dev-dependency. Here is the test we run in Vega-Lite: https://github.com/vega/vega-lite/blob/c53b7394f0ed7929401cebaf3261635b84f97e24/examples/schema.test.ts.
