### ISSUE TITLE
Grid rendering issue with axis offset

### ISSUE THREAD

**Issue by roying** [vega/vega#1609]
In Vega v4.4.0 and v5.0.0-rc1, if axis is defined with offset value >0 and grid as true, the grid lines are offset by the same amount and appear shorter than expected. 

Note: This issue was reported in 2016:
"Axis's grid not extended when adding an offset to the axis #519"
https://github.com/vega/vega/issues/519

and was supposed to be fixed:
"Axis gridlines should account for offset (fixes #519)"    https://github.com/vega/vega/commit/96c539f831da716641436baaaf7d1ada10f4ba09

Example:
https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwogAw7FESCkbV8WgEy6DUQujVrGM6ltHXI8WQDMTW0BEN4zAA2yL5K-lCesngAyowAXqE4AIwAbOFgAL5KmYpKkIF4IWERBcgAHni+kLAmMuhBWpAA5AAK3ISsQeiBsmDcnmAAYg0A1sgysMjIYJ4ATtyoYM1gANRgAJ7I6HOwANo6ALpry2B43KfrWzv7yYeQ2RC5IPlqPZg4exl+EVD1qEkoHh0OxitZShQGqxkLAtF9fv5gJBrnMtMkABwAdlcNg6XR6PDkKQAzDoAJzPBEQJEotHosn6XGdbq9IlgZKiUToylUmnbVEpMnJRmQQh4lmErQAFlEyXMPIRfJ2aLJlnkTPxrK06IxOgVvyVAvZZOJxPVovFBNkaNEQtE+oihpVxLJ5rFzKtbPMUvR3odiOR-JVUtSbstWpw5l92P91MDysFVg1EutkaF9NjYCdgtSUrDHojYHMZPROsz2eNmOS+c1ksjqT0mPL8aNyRL1eTnosUp0xebtMF6JxFoLdaLpp7-aDg9dncL5nMpKb4INLZVDJrKa95h0WKnCeNQs3Xcj5mSLv3rbJquP87POntK8da8FJtvY4X3vlT4DA8PebnD8ox0ZJL3XYd3VrVMiylcxMWJMDX1DQDoMsXM9R-OM-zbMlMXfVD4JNRDD3RfCvTJXRHwyZ9sOvWcRygtliTPP1MKzF8iz0EVIK3LRTUxIViJ3ECyL40Ri2Xajf2nTje1EnBiVSZIBKEvQzRQpjUl9Ck2IrYSAIY3iFMxKUiN0jjhIg8Mx2JdFiUxVJVJ0ZDDJPMAXT0blzL-YS8I0viTVSRzvJk4TSP8hSSzPJz6J4tye2UnSpKw0KQO46zoJ7WVQJCg8d2SDtXMLHsQyoql2J8kDzHksAewZMreQskD1KKscpTlLlVOSAy4uK5TMSbKTDh-Ao5nQSYojmVA4WSrNZoCDZCEBSAKjwCYqjYwxvGQII1CaWlNqgWpqHqRocBbWFZseX5DgyfUflKf5lvGmRuGBLURshIJoVhT5ZoeqkamBOYqkFU1DpWmQ9sFGUIbWyomgAOXQeJGDAAAlLpQiu3T5qO4HQeNH0IYmaHjXpOHVqaABxAARdGwAACgAUXQWA8DAankCm8aNgASkgK6hrupRhpeQwEAaGEZsdKTICeppygUOW8EW5agkcIMRrGpxltUDREGVhFIESBYtE8BophGtRFnQRxqjeYEmmBUFQnNbbdv2oNrqeFcAcMBXzo2I3fgKNWmg1mQtblnXqGW4xTA2uWZEYeBATwOZoRG03uC0DOs7lm2MHtnAkUdj4gRBMFIkYHayda60fayP3k-QAEmg8IJuFREbVaWppu4cU6Q9KIu7bZMv3iaF63q7d3a89874aqf1IFjwE9kgUF0HgUYFCgOZkD226ImusX8nQcppb+2Xje72uZEJyAQk8JPjcl4og5H-wCmCZb2lHNaXuf9Wh2CHs4FI+g5bUDmOoPOmdkAjQGJ4KYhMkRfWhGiPUd0W531getJo7A3rnGmiND+y0lYjUmhgJ+e1gFFGWgATWjsbQIu8ADC3BWCPxtCNGBcCcD50QXLZBqDqgYMBMKJuZ88iGAwHMUYv0wDwkRCrcO51D7wDfqHeYiwHZT3OjPd6kpV4TA8GoQE-sf7rW5iUcqUAlalxqPAKWit96QA9vXdmOwV4Q3KOYao5C3Hzzrk0UmDwIbBycRIrQGE8bIgCU446w9zoJzMJmLajAghnXYkE86ndu7uM8c7KmGSoAdB3swKJ7EYk4B0HQeUQsETSNwaHPu6tNbfy2gsaaTjy7OyrqEUxMhzGWNmpDNaRorGlEcJMsULJLGQFqVAVAsg3qyCGX4wJLjP4OKKQveutIynIm2a4r+ITF7+WOezBY4xxFQmWuzaYQRQSYOuRnbg4wADq6hNDRIeXxJup8pItO+Go-u51YAbFQEQxoVCen6KdkvQZES5ZmO4BYuxxsbFTPiY43JOyKH7NCUHb2kTTm7JORc+uvUTEQxuZ8xZyygbPNeZs+JDLvm-MNv876ki6ANXKh4rJOT0EAvOsoRAzB2X2KOgkJl4r3LYPKkCrIIsIDn0MCEOOUMlEqOpHLbw2SO7cC7j3FWf8mitG5jwOhIj8E8KXh0AAtC-bRpRRHIEJqRNFIyMVjKFVCmFpqlHTJ-qwQgjsA2yvxrc5APyDb3L5bEspEtEDoAhTUxVNQACOrAdgypjZACp8AqlJswXUugCE8aqqeCC9VYBbrZCAA

**Comment by jheer** [comment]
Thanks @roying! I think there is a subtle error in your specification: the offset should be `"offset": 10`, not `"offset": {"value": 10}`. The offset is a top-level axis property, not a mark channel encoder.

**Comment by roying** [comment]
@jheer Thanks, Jeff.
The grid lines are rendered properly with "offset": 10

But "offset" also accepts signal expressions such as
   "offset":  {"signal": "5 + 10"}
and the same rendering issue with
    "grid": true

**Comment by jheer** [comment]
You’re right! We should fix that. Thanks again!
