### ISSUE TITLE
Allow group references in axis & legend properties

### ISSUE THREAD

**Issue by mprudhom** [vega/vega#164]
It would be handy to be able to reference group properties like width & height from within axis and legend properties, so that things like titles and tick lengths could be set relative to the size of the spec (or enclosing group). E.g.:

```json
  "axes": [
    {
      "type": "x", 
      "scale": "x",
      "title": "X Axis",
      "properties": {
        "title": {
          "fontSize": { "group": "width", "mult": 0.2 }
        }
      }
    }
  ],
```

**Comment by arvind** [comment]
Duplicate of #151 which is resolved in Vega 2.0.
