### ISSUE TITLE
main / module confusion

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1642]
I'm building an app with webpack and noticed that the Vega `module` points to a file that has all the code bundled into one file. Webpack prefers module over main and so I end up with a bundle that cannot be optimized. Is this wrong in webpack or is this wrong in Vega?  Vega-Lite behaves the opposite way and so changing the default behavior in Webpack does not solve the issue.

**Comment by jheer** [comment]
I don't mind reverting. The reason it was done in the first place was in response to https://github.com/vega/vega/pull/1532. But so far these changes seem to have caused more headaches than help...

**Comment by domoritz** [comment]
I think it makes sense in general to have versions that are bundled, use require, or es 2015 imports but right now the entries are pointing to the wrong files. The Vega editor currently includes Vega twice.

**Comment by jheer** [comment]
Based on this, I plan to merge your PR and have `module` point to `index`, while keeping the built module file as part of the distribution.
