### ISSUE TITLE
argmin/max does not work correctly with dates

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1650]
In this [Vega-Lite spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgB3RgBMW2MABYADMfURIO9Hkw5QEC6wBOYg5evo+ebvADWsOnhYCkgNAF9zKDwndCVYADNuJ1QDAG0NCHsHC3jGMTxkJwMs7JzGZDEdN1gAT1R2bldI0qhkAEdWdFccSABBXoAFABlQlrCMsHGIAF1IyDF0GsK0iZKHSAwnXzcJJWQ1CYtkJXhuHUYlamLD9YAPa5bsyFyKqp6rAoPH9bwawn2egVUIQkl1Ro8IjcLDUHt8oC9Km5CE5GPB9s1HpBfv83B1YnhmNZGFRwWMblMHJDsmsLNFYgkkikcOlvjTSpB0NRqE5hJ9mVDSmzvpBuIQ3OgnNQMPcMXD4eVEe9rOiBS0ObBxZLpQB9D77VWU2WPIWY0WaqUXL5y9YIt5QPVW61QdAanoSi1KXXK0lwinfaYCv0OWY3DYS7Z2AVYv4AqA8+B4R3s3JiMQAeUI6HgzBhOGMdAATOSjZBjqdzpdYWrc2ATWVXubUBcvQU6MjUSq5dGcT08UoCTYCSTA0boQWq5jbY30LcW8g2yi0T7slTMTpkDY8is5XWbQq7Rytc29XQHaP2djY1i0CCYq4DREwAbd-XFc6tTO56fveenpe3ECt5gg+AoBmSK4aAGYRAA), I calculate argmin/max of date and try to plot the price value.  However, we can see that the range of argmin/max doesn't match the output. 

The tooltip also shows that the min date isn't the first date in the data, same of the max date.  

![image](https://user-images.githubusercontent.com/111269/53457010-7b462780-39e5-11e9-8f24-27cd5dcabc05.png)

Since Vega-Lite simply outputs Vega transform, I suspect that the bug is in the Vega transform.  (That's why I file the bug here.)

**Comment by jheer** [comment]
The argmin / argmax operation works by calling vega-util's `extentIndex` method. I just double-checked it and it worked fine with Date object inputs. Your example, however, does not actually use dates. The compiled Vega specification is passing string values from the date field into the aggregate. They need to be parsed to dates first.

Also, please don't post localhost URLs into GitHub issues; please use proper links to the online editor. (I updated your link for you!)
