### ISSUE TITLE
Expression field dependency tracker doesn't strip quotes from quoted field names.

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1653]
In this [spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgB3RgBMW2MABYADMfURIO9Hkw5QEC6wBOYg5HxES5KrQbM2nDxCtCJWNrDIeLCkYeh8eNzwANawdPCwFGoaFgBm3E4YeAbAkIToThHFltbIbmG1AL4NGg3mUHhO6EqweQUGANolOYxieMhOVcPIYjpusACeqOzcrqpQyACOrOiuOJAAgvsACgAykE0Aum2QyErw3DqMStRVAB6TjNOze-Vq7fOEWp7MaoQj5HZ-SB4ZhiIFQX5Na5idDzcYDbJgewOCzI1ETHD9DHYrHY7GQCKw+DQ5TFImkizsJysWCIKp4AFwyBPMZOCgQtY3O4PJ7UWADSDvK7rUHstxKZSNOnY1pKhyQDBOJJuCRKWptekWW73R7PWkG0mQeZm80WqYzNyEJyMeB61X0qEctxbLrQmzQqhZG0W9CvRhiuyQfKfJRFPZO6j4c5uhwqoMWbhleDMK12ZNk+5KR7UlS5tMWsawWNQWHPFgAClidYAOpBGczEAB9Sv5ZAtgCUfcDZbVfLErDhxjo0jzKf1acgo-HBgAjDPmkH1wbUwaSQaoZ1ur1UAMhiMeVUKcgqTwS1A2yzzg0rsn1eUtXsda6g4LjSLrd+c0xGdck+e09kdZ0v2HD1AS9bYY2YaxGADOdv19WEHSdF0hzLSAQzDKoo1uKtIHjRNNw3ZMKNJaiIAuDFtwgXcLA6LoenyY8CVVU9RjRCNL2vGk9nvVlEW4l90GoagnGEMZ0TLEoMzccpqFQJ5ITtb54RqSF0HDKAVLUpQOwRVCd0jQhlKcVSQw00CtOqOSBT0qybNeEydNo0l6PNLzn3dDV30xGDORkqlIQzdAs1lHBJwAJkYtUjWFU1Sz3d4I001yjI8sY6F+AV2Vg4E0DBTpXESslXjij4vmykNcuQfLPLMixANPOq9kMp5GroCDsMKz09m9BC-WQxpWqgeYasy+z6vc+o+qwxV6Wozd6IaIA), it seems like the aggregate argmin/argmax doesn't get re-evaluate when the selection changes, which in turn changes the data that feeds into the aggregate transform.

If I drag the brush fast enough, I can see that the `argmin`/`argmax` aggregate gets evaluated, but not re-evaluated as the brush moved. 

![image](https://user-images.githubusercontent.com/111269/53470169-a183bb80-3a15-11e9-9f0b-b80fd62f59b5.png)

## Similar, but not problematic cases

Note that

1) [applying min/max in `aggregate` after selection filter](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgB3RgBMW2MABYADMfURIO9Hkw5QEC6wBOYg5HxES5KrQbM2nDxCtCJWNrDIeLCkYeh8eNzwANawdPCwFGoaFgBm3E4YeAbAkIToThHFltbIbmG1AL4NGg3mUHhO6EqweQUGANolOYxieMhOVcPIYjpusACeqOzcrqpQyACOrOiuOJAAgvsACgAykE0Aum2QyErw3DqMStRVAB6TjNOze-Vq7fOEWp7MaoQj5HZ-SB4ZhiIFQX5Na5idDzcYDbJgewOCzI1ETHD9DHYrHY7GQCKw+DQ5TFImkizsJysWCIKp4AFwyBPMZOCgQtY3O4PJ7UWADSDvK7rUHstxKZSNOnY1pKhyQDBOJJuCRKWptekWW73R7PWkG0mQeZm80WqYzNyEJyMeB61X0qEctxbLrQmzQqhZG0W9CvRhiuyQfKfJRFPZO6j4c5uhwqoMWbhleDMK12ZNk+5KR7UlS5tMWsawWNQWHPFgAClidYAOpBGczEAB9Sv5ZAtgCUfcDZbVfLErDhxjo0jzKf1acgo-HBgAjDPmkH1wbUwaSQaoZ1ur1UAMhiMeVUKcgqTwS1A2yzzg0rsn1eUtXsda6g4LjSLrd+c0xGdck+e09kdZ0v2HD1AS9bYY2YaxGADOdv19WEHSdF0hzLSAQzDKoo1uKtIHjRNNw3ZMKNJaiIAuDFtwgXcLA6LoenyY8CVVU9RjRCNL2vGk9nvVlEW4l90GoagnGEMZ0TLEoMzcVAnkhO1vnhGpIXQcMoBUpQOwRVCd0jQhlJDNTQI06o5IFHTzNeQytNo0l6PNFzn3dDV30xGDORkqlIQzdAs1lHBJwAJkYtUjWFU1Sz3d4I3U5Snic2z-lg4E0DBTpXGislXgij4vgc9LFXpajN3ohogA) does not lead to the same problem.

2) [applying argmin/max in `joinaggregate` after selection filter](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgB3RgBMW2MABYADMfURIO9Hkw5QEC6wBOYg5HxES5KrQbM2nDxCtCJWNrDIeLCkYeh8eNzwANawdPCwFGoaFgBm3E4YeAbAkIToThHFltbIbmG1AL4NGg3mUHhO6EqweQUGANolOYxieMhOVcPIYjpusACeqOzcrqpQyACOrOiuOJAAgvsACgAykE0Aum2QyErw3DqMStRVAB6TjNOze-Vq7fOEWp7MaoQj5HZ-SB4ZhiIFQX5Na5idDzcYDbJgewOCwdLo9fKodHY7FY4kOSBybhPdDUahOYRjIlk4klbiENzlagYd5rSBTGZ1GqQ9CwDlOLnoV4AfQRbWZDlZ7L2nNQT0h-O+8KFvJFYq5TxlQua8ogFwx2ONxKu5qgEVh8GhymKNos7CcrFgiCqeABcMgTzGTgoEN5t3uj2eopw-Ug7yu61BPrcSmUjRtrRtkAwTiSbgkSlqcvJYYeTxedhdUHuYnyzpNVeUj0dKmjlZJbeJUOQsCKewA1GFWKg6CqDfU6IQnIx4MgwAAeMAD6xDkfi7mGsYTqczrL17GQYNiVh+unIW6QDsQS3y631g87Y9uemzSsZ+WQeZ1k18z4CvaT6dCw7KFfTcLYumhGxoSoXdv0lRgo0xSB8k+JReygKdqHwc5XyLfc2XQeBmE-Cs73uJQmx4FskLGHs81uagWAACliJiAB1IDdD1EClHt8mQDiAEpBMhQ9HxwYw6GkN9vzEuEAEZX3TDEZIgUlyVxbpekJVt5SGEZAyqO1kAdKi3C4z1zlUllgMpalaXpWhGV0vdFT1bl1V-TVqkZHVEMgFVJQ3Ro8OZNzlTXNVeQ1QVfKgXUIv1JRgpw+szXla8HFvTts1zPZ8yAskbjuUtni-Irq1rUjv3IyinRc+t1LvWj0MgJc8BXUdkvHACZ3ndrOrXIKeu3Qq9wsOS3FPc9LzATKyWy99Jr2Z8Lwy0KLBIzFgJi-9Rtg98fUBMDtjQ5hrEYGCNo0mE-V6sb33gxDWSnW5Wsw7D5ocL7MstM0GiAA) is also fine  (I can still drag the brush from a range that goes down fine.)

![image](https://user-images.githubusercontent.com/111269/53470434-7ea5d700-3a16-11e9-88ea-9482d7c8b401.png)

**Comment by jheer** [comment]
Thanks! Turns out this is a very subtle bug from deep inside Vega's guts. The aggregate is fine -- the argmax values are being calculated correctly with each update to the selection's data store. The problem is that the downstream formula transformations aren't processing data updates.

Digging deeper, it turns out that the dependent fields that the formula checks for modification are incorrect: `"argmax_date"` (with quotes included as part of the field name!) rather than the correct `argmax_date`. The problem stemmed from the field dependency tracking within the vega-expression code generator. Stripping quotes from extracted datum field names solves the bug.

Thank you again for catching this deep-seated error. I will include the bug fix within the upcoming v5 release.

**Comment by jheer** [comment]
Also turns out that this is now the 1000th closed issue on the Vega repository! 🎉 😄

**Comment by kanitw** [comment]
:tada:

**Comment by domoritz** [comment]
💯💯💯💯💯💯💯💯💯💯
