### ISSUE TITLE
Error reading topojson file with Vega v5.0.0-rc3 vega-core.js

### ISSUE THREAD

**Issue by roying** [vega/vega#1657]
Example Vega spec: https://vega.github.io/vega/examples/dorling-cartogram/

Issue: For Vega 5.0.0-rc3, using vega-core.js this way (as described in: https://vega.github.io/vega/usage/):

> <script src="https://cdn.jsdelivr.net/npm/d3@5.9.1"></script>

> <script src="https://cdn.jsdelivr.net/npm/vega@5.0.0-rc3/build/vega-core.js"></script>

results in error:

> vega-core.js:132 WARN Data ingestion failed data/us-10m.json TypeError: Cannot read property 'feature' of undefined
> - at topojson (vega-core.js:1831)
> - at read (vega-core.js:1872)
> - at View.request (vega-core.js:1965)

Note: vega 4.4.0 vega-core.js and vega-core.min.js works with no errors:

> <script src="https://cdn.jsdelivr.net/npm/vega@4.4.0/build/vega-core.min.js"></script>

**Comment by jheer** [comment]
TopoJSON is not included in the vega-core bundle, nor in D3. You’ll want to import topojson-client separately.

**Comment by jheer** [comment]
p.s. I’m frankly surprised this works for you with 4.4.0, as I don’t recall any changes to our build config here!

**Comment by jheer** [comment]
Updated the documentation at https://vega.github.io/vega/usage/

Thanks!
