### ISSUE TITLE
Chart title not displayed with Vega 5.0.0-rc3 "autosize": "none"

### ISSUE THREAD

**Issue by roying** [vega/vega#1658]
The geographic map examples at https://vega.github.io/vega/examples/ include

> "autosize": "none"

as described in https://vega.github.io/vega/docs/specification/#autosize

But when chart title is added to Vega spec, such as

> "title":   {"text": "Unemployment by U.S. County"},

the title is not displayed. 

The chart title is displayed, however, when "autosize" is removed or specified as "autosize": false

Example:

https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwATgBsABkURIKRtXxbR+w0sjpWebrEYAvZFsgzZ7xeEh5mABt3HCUIcIiwYH9kAA88DwBVGTRCQO4AT1RkGTwwdgywRLoAZTowAGFuVlyMyABfX2M1dDxMHABtMKju4xl0bI8a1IVeqFYAJ0CPFrbSYdQ0zOzcujxYClHIqAAzbgmMBJxovAzCEKh1zfkoQnQJ2Au7B24G7sbu0G3PAaf4atyjGQsC2kUgk2mOEgsxErFgAFoAIz6VCSaRyIxgvYHVpaE5nJ6OQjcKSyBS7ZCtSZ-AEBYENTERfwTdAyWDY1BaLrbCDAS4EjzpbgAa1YhHJkB2E24nKhC3FN0gwuQdSh6glOyBgTUIM6kHVAF1FRR0IFWPS9Sy8O4DWAPjyovzzh5NYFrRMJXFCB6obNWKircgwABCAC8YBkrEC0ztYwN7yURpAtm9JOQ8ACsl1YG54S+YP6gyhqYk6czGLG-gFUNN7GQD0SsEwCYgSdsCFNFpzn0rhZp6Q9jPCVedUIAjqxWQE3KCmWoZehGHJOoYwPo6IjREnviyZNQLtF+GgnuwzfTFf8akcwAB2eotsBt4zBfcyHVcnvfV2QqD-Aez4d9iBXIPHYbgCBleEJjMCwh2MAI8GCJIUkWdIshyBI4N2fZDg8ddEQAUkgB8nygDAJmFbNc15StTlHKBYEQdBnSwyVpVlKJoVadpf1pIEQXtMEcn+NQDzGYwMPrPFLm4bg3UYcVjkgZxqH6H9JRw1oAAo-QDVpkBuAByfCCMMgBKBpBO+MVZgPXZGGjPFlPgTsPD-fYNS1NQPEDBo7Sw4xEG4KgfUdSUHJ-aITTPHzkG8+pY22KzhzwXd2Rwj8HT5Ecnn3JwmJY25pVLDMeGXIq01KslEsieMInvVsQHvIA

**Comment by jheer** [comment]
Similar to axes and legends, titles are placed outside the data rectangle defined by the width and height properties. As a result, their default placement is outside the region clipped by autosize “none”.

Using autosize “none” basically states that you are going to assume all responsibility for layout and visibility.

In this case you have multiple options. One is to position the title yourself by overriding properties such as the offset. Another is to use explicit clipping for your map and then use a different autosize method.

Hope that helps!

**Comment by jheer** [comment]
[Here is an example of using autosize `none` with adjusted `offset` and `baseline` title properties.](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwATgBsABkURIKRtXxbR+w0sjpWebrEYAvZFsgzZ7xbbzMAG3ccUAhjPGQADzwPAFUZNEIA7gBPVGQZPDB2FLBYugBlOjAAYW5WTJSFJWNuADM62GQYnABaAEYbMKh2dCaAxgSPR0JIJQBfX2M1dDxMHABtGrBQ7qgZdHSPCsTqtahWACcAjxm50h3UJNT0zLo8WAo9tcg67kOMFpXIPBTCYKgDye8ighHQhyaHnsjkg42Wk2Wq26nk2AMg8HKmUYyFgz2RRxOOEgZxErFgHX0qEk0jkRhebw+sy0wB+fzRI24UlkCigdWQsyOaIxFX8ONhdOReEO6BksAZqC0S32EGAgLZHmS3AA1qxRiDXoduAqiZc9VAtcgqkT1DzXtiAmpcYtIDaALr6ijoAKsMXO6URSCusAI5UrNX-Dx1RgBCKHW1RQhxolnVhU-3IMAAQgAvGAZKwAidg8sIK74Up3SBbInOch4P5ZE6wEqwkiwiitkSaxI6w3aSXw2ivexkBDYrBMOXS1MoAgvb7m4iBx2hdxknGJe3fhGiQBHVgy-xuPHttRG9CDRWGMD6OjtUSV-aQaUyagAln8NBo9jesX64WZFoADscLdKBYCVrYQRvjIjqKkuT5RoWHgYuuJ61Ic2KAUS7DcAQRqtJh5gxJu4SBGi8SJMkaQZCRy7ykyRK3u0ACkYxgRWM6QBghxak2LYqsu25orAiDoBGpG8oaxrfCSKGYqKuIhi8GQYmo74DsYtGjsygLcGu-ijCEkDONQGyEry7yfAAFCmaazMgIIAOTMSxTkAJSwspT66mc768tGFkfvA87yWh+pRsgDoeOmsLBpJxiINwVBJmGdrIcZnq-jFyBqHF4FgZJPwvnKVnwaGqqsjuUBvk4YkSaCho9vWPByF2TW9q1kDFvsZYcaWIBwkAA)
