### ISSUE TITLE
Vega Loader expects to be running on node

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1662]
https://github.com/vega/vega/blob/master/packages/vega-loader/index.js, which gets used from https://github.com/vega/vega/blob/master/packages/vega-loader/package.json#L22 uses require and expects to be running on node. However, when i use a bundler like rollup, I get this file even in a desktop build.

**Comment by domoritz** [comment]
The problem goes away when I set `nodeResolve({browser: true})` in rollup, which I guess is fine.

**Comment by jheer** [comment]
Yes, this is the intended design.
