### ISSUE TITLE
Support row/column-footer-title?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1664]
The layout directive has support for both header and footer, but not for footer-title. 

For [a faceted plot that uses row-footer for labels](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7RiiJAPo8mHAG0lEUBG9QZ6VDo4kNKsAE7wyAD6AAzGPvZhADa6Dk4i7OihicgAnpLScnbxkABm3KEYeLrAkHg5hIFQUrKQAL5FPrWh6DKwZRW67vHeXsPetfWNkOjU1KHCeDodY5Bz3KyE7DmDkBSZjMh1ClAai8eQOciZkAC6y8OQ3MQ7sKyot-fFJQeJBrA7OR+RjuHhW6H+bmCb0igOQv1uoJ87URIxRnTqDRSsGc8AA1nExvY1hstjs9qEDkd5FBLtcQYT7N84UYgq9UDCgQTCcFylUcDUmfDIacdHcoOUDMhQjtJQhkDILFZbsiGcoIWBXFD2bDfpFsZkqtStRzmZF5cDPp1uCUSrBDiltKFuJA0WBWiibqCVaiHn4AiknQB3SIGbgYSxc8YhcJTaMRGKR+x4bq9frvNw1DFTGZzBZLKDEzbbSG06U3VqepFKeknRjUPyJdVDEaQP1TJCMXWBxgGFjnPaJViNABM0Wi3s8rf8UxyesWhH76EHI-Hy1GnTbKQ7upQdfwiagG0cZyCGQVsH0EQAFKHwzIrwByHIPgCUdGyVhY1OidAAjN+6GiUQXzAAAqMBZ2xZAFy9asikgRJ0BydY+TAdc9EMRVrBwUdlkeG07VQmogwAFWYbJdF-VdQUgeBuEHVBekovD2HWc8UhKVhEmSPClzrOQgiXZIlG9SAMFCXEm1BdD7E3IIgwAWjwcilhRCZMSCQsD0gJ0KPk7hAyUlTtOUvA9LQ11amQAAPVCLiuaVLXFAj7RwKinMeCl5Ts7ISkNSzsRyczVlYHtkCMsydBRd0kTXNS5KgINIhQQwpRMyYUi0z4dPoqZFJSyVHLUkonXTNDUmcAMDJDMN0AjCco15apSk5IJjzeVwAB17MybqbnOCU0sEuUFUsawGvseU6MlZqjycRoal3ah935YJ+KXLdEE7AxkuQPcqlaQ7svQazkCkwkZOKBAlxnA8rS8mQfOQPy7vGOYe10EolztJyk2MoJyUpbZfqgTRLElazKNdGL4krbwGsuqd-X04Mym4RYioeLNMqdDZtN0vKDIUtGMe0kqw2a48XES6rbzquQJpOJrVsFFkoHa1Aup60I+oG0JCpScEIlGpVGdqf6LO5RZbOajR6w2oIHwfABqfR5kernS15xn7GtW1XLAdzLPKA5HoDfbXuCOpguoULJQUxD2DhS2SunHH1gXDyMjtRJLCmVAewMCjouyqbuBm1a5pPcqlpW8q5YbTbtt2i3DphiAEfit2gjohiZEiEm0uy7HNNxz21IJrd6LeGRie4dGi7UsOI-KqOFsgbte0QWX1uSHOtq7Hs+zT47TvOsZLs6a7gshkHPNNuzWIICm5-etmvsbZA59M4KAGU3jAa0IM5OfHbhAAxQdYG7nBkyHU-0CdxIAHkqCydAF1v0J79dP68QAYTYkRNa8s+5QAiJ2K824dqdxYKQAALNEF8bQ55gwVDZKGhJ07eDhhnOKvps7gLhDxNSJcCxl20oFYKERuJk1KtUSyX0IjAISqUdAzDzhUyxOsGMCYjSFlJCWByyoQ5qWkKEYBrMZROA6t1LWtwPjin5kNDU0wRpYWVKHGQ00FqWTbgw1UHch433jr3JOg8u4oN-rgPay1gEJwVuAgeO1Y4HWhqIh44lJKDFdJPcYrDoGRC8f8beGV5LIHgP5QxVDGiagyGWOe5Myo1C4UEJh9odbjGbro1UCRCDHhybkxknYwHNiKZ4axUszp2Q5lzNkJpfh9TAAAXlaWAGQXFEhgAAD7dLAIwWAAA5dAgybwyM5t1epOoDB9WQSDbkA4hy6A6dxSp8RMkXWCPAG6VdEjlHOFI1kzAdDYNVDWIptR66JGUp-SW5T7AOLAZAYA3V96oEPiUY+zJuo4DTE4MZeBZHGmmX1ak3VuovjBbsfYhwcg-LAErZWtTuqA1haCsAkzjnwsRcitaiw+qtBdPcjZxRIarWnlMWeUBDknGhNMs0CorH3MgNZYcsttkzwOa1Wl2ogRzgNEy8pFx2U7KCMDal3LoVeSOCSzoriRXBXFZAM8bM77IFOWMDVVYsEelHmdHxF1rFbNFVAWeRqTbeRSEvNQ7xV4UgMLvDlt07UfS-j-QxykAFAJ7qArce1EhQOcZEWBiAEFIMFdyOmEZfnfS3kas+jZPqxrnhgayABRWylqcDRBTZYDNiwzbZu3owPE6oN4-SNWgiGuhojuOGLgt0cETAUvHhUghyNTXpQ0lAX2MhhHZSjQJO5DxUlMzCPGWIHlWZNmBXy-UEjzhTL5eaBEwwxYpmoLEnNpjfX92TiGto5z-ElsaGq7KjpnRuuQF6fBxRWHA1IWEqAKrtKDspmkbh46oiTolcyFIqKqRMwXVe9dPRN2y3nD6xOYq5zQTaGLMwWEACSMg+3SmzX+bKiGxrP1UCon8QEb3SSzh22i9F9nFyfZ5RUG0B21WjeVUdPIv18N-UKWsZwjTiNQmq0DVh2zzWoOUB9DxLAY0IPReaKREDwGEtqsANYEI0HNK24d4wLWFufejG1r7GDzEiTwIdkBEAm00LIZwJCHi5xruqAAzNlb4tCc7kcxsUOYhgF4ABl5TUD7OSsxOdEKoEIIG5OrjqQADZ4HUlHOGsWO9YzHO0tk2WORUCsUTZHfJUnyWIA-u3RZsYACOrBMgnLTrBCAim6IyG+NhcqJ0BkAE1moBxkPmrNYBbPjndK0IAA), it's a bit weird that the row-header title has to be always on the left.

![image](https://user-images.githubusercontent.com/111269/53690255-fc6e2900-3d1b-11e9-9176-5bcd22e39eb8.png)

**Comment by jheer** [comment]
Added via the new layout `titleAnchor` parameter, released in v5.0.0-rc5.

**Comment by kanitw** [comment]
:tada: That's very fast :)

**Comment by kanitw** [comment]
Thank you!
