### ISSUE TITLE
Vega 5.0.0 Legend "offset" independent control over vertical and horizontal positioning

### ISSUE THREAD

**Issue by roying** [vega/vega#1674]
Vega 5.0.0 legend "offset":
> https://vega.github.io/vega/docs/legends
> "Legend offset: In the case of left, right, top and bottom orientation, the offset parameter determines how far away the legend is placed from the rest of the chart. If the orientation is none, the offset parameter is ignored. For all other settings, the offset determines the distance the legend is moved inward from a corner of the data rectangle."

Use case: Trying to center or right-align the entire legend above the plot area. 

Issue: For right-aligned legend, "orient" can be set to "top-right" but the legend is inside the plot area. Using "offset" works but that changes both the vertical and horizontal distances simulaneously by the same value (instead of changing only the vertical position).

Question: Would it be possible to have independent vertical and horizontal legend offsets (e.g. "offset-x" and "offset-y) using signal values? 

Thanks

**Comment by jheer** [comment]
I see two different issues here. A use case and a feature request. The feature request is for multiple offsets (x and y) for top-left, top-right, bottom-left, and bottom-right oriented axes. However, I'd prefer not to complicate the design in ways that don't apply to other orient types (like right, left).

The primary question, though, regards center- or right-aligned legends above the plot area. For this you should not use "top-right", but rather use `orient: top`, then use the new Vega 5 legend layout config options. For example, try including this as part of the config:

```js
"config": {
  "legend": {
    "layout": {
      "top": {
        "anchor": "middle" // or "end" for right-aligned
      }
    }
  }
}
```

For more, please see the tutorial [A Guide to Guides](https://observablehq.com/@vega/a-guide-to-guides-axes-legends-in-vega), which is an Observable notebook. In the last section ("Axis & Legend Placement"), you can adjust the layout to get a desired effect, then copy the `legendLayout` notebook cell values to get the Vega JSON spec for the legend layout config.

**Comment by roying** [comment]
Jeff, Thanks for the explanation and example!
