### ISSUE TITLE
Unclear documentation for valid values of SymbolType

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1676]
> Default shape type (such as "circle") for legend symbols.

It is a bit ambiguous what "shape type" means.

I guess we support all [symbol shapes](https://vega.github.io/vega/docs/marks/symbol/)?

> The symbol shape. One of the plotting shapes circle (default), square, cross, diamond, triangle-up, triangle-down, triangle-right, or triangle-left, or one of the centered directional shapes arrow, wedge, or triangle. Alternatively, a custom SVG path string can be provided. For correct sizing, custom shape paths should be defined within a square bounding box with coordinates ranging from -1 to 1 along both the x and y dimensions.

(But I guess we have to add "stroke" to the list.)

**Comment by jheer** [comment]
Thanks. Only symbol mark shape types are allowed. Mark types are not permitted.

Perhaps we should update to this (with link to symbol mark docs):

> Default [symbol mark shape type](https://vega.github.io/vega/docs/marks/symbol/) (such as "circle") for legend symbols.

And, yes, we definitely need to make sure `stroke` is included among the shape types!
