### ISSUE TITLE
feature-request: interactive zoom

### ISSUE THREAD

**Issue by jaredly** [vega/vega#168]
Would be awesome, and I don't imagine it would be super difficult (especially in svg). I might work on a patch

**Comment by arvind** [comment]
Vega certainly isn't abandoned :) As per @jaredly's request above:

> use CommonJS module system (probably browserify)

Check!

> fully unittest it (currently very minimal tests)

Check!

> have a separate repo for the "playground"

Check! See [vega/vega-editor](http://github.com/vega/vega-editor/)

> allow rich interactivity, not just highlight-on-hover

Check! See [[Signals]] and [[Predicates]], and the [interactive examples](http://vega.github.io/vega-editor/?spec=budget_forecasts)

We're very excited about Vega 2.0, we hope you all are too :)

**Comment by jaredly** [comment]
@arvind thanks for sticking with this! I'm very happy to see this progress.
