### ISSUE TITLE
ability to set legend fill order

### ISSUE THREAD

**Issue by blset** [vega/vega#1682]
Hi

when using a fill legend for a stacked bar chart, the legend order is always from top to bottom
whereas the stack order is from bottom to top

would it be possible to have a reverse = TRUE option so that the order of the legend follows that of the stack

thanks

**Comment by blset** [comment]
maybe It can be done already using the values property

**Comment by jheer** [comment]
You can either use the values property of the legend, set sorting criteria (or manually rearrange, if an array literal) for your scale domain, and/or use an explicit `sort` parameter for the `stack` transform (and ensure your legend scale matches that).

**Comment by blset** [comment]
Ok but it seems impossible in the legend block to  pull a field from a named data set defined in the data block

I tried 

`values : {signal : "data('adhoc_data_with_field_in_correct_order').field"}`

 I see no function to extract a single column from an array of object, like pluck or map

thanks

**Comment by jheer** [comment]
I'm not sure why you would need to do that. In any case, the data backing the legend is an entirely different, internally generated dataset. The actual value shown in the legend is accessible as the `"value"` field of those data objects.

If you'd like more detailed feedback, feel free to share a simple specification that demonstrates your issue.

**Comment by blset** [comment]
For the legend order relative to the stacked order, I solved the problem using a scale for the legend that is the reverse of the scale used for the stacked bar chart


what I was trying to do before was extracting an array of values from a dataset declared in the data block. A scale definition of type category does it, since it extracts one field of a dataset.
I can call it in an expression with `domain('name_of_scale')
So there is  a way to extract one column of a  dataset through scales. Though only unique values.

So I guess  everything's fine

I just note that
you can access a dataset anywhere through the expression `data('name_of_dataset')` as indicated in the docs, but after that you can do nothing with it.

What about a function to extract one column of a dataset in the form of an array in an expression context ?
together with some complementary Array functions : sort and sample

**Comment by blset** [comment]
Finally, that does not work to reverse the scale because the wrong colors are picked 


if  i define for instance in the config block (rcategory reversed order of category)
```
 "range" : {
      "rcategory" : [
        "#bab0ac",
        "#9b7461",
        "#ef9ba7",
        "#ad7aa1",
        "#ecc853",
        "#5da052",
        "#79b7b2",
        "#dd565c",
        "#ef8e3b",
        "#5079a5"
      ],
      "category" : [
        "#5079a5",
        "#ef8e3b",
        "#dd565c",
        "#79b7b2",
        "#5da052",
        "#ecc853",
        "#ad7aa1",
        "#ef9ba7",
        "#9b7461",
        "#bab0ac"
      }
    

```
and then with `source0` a data set sorted according to a field `lx `and `modleg`  the same data set  sorted in reverse order 
```
 "scales": [
    {
      "name": "color",
      "type": "ordinal",
      "domain": {
        "data": "source0",
        "field": "lx"
      },
      "range": "category"
    },
    {
      "name": "rcolor",
      "type": "ordinal",
      "domain": {
        "data": "modleg",
        "field": "lx"
      },
      "range": "rcategory"
    }
  ]

```
and then use rcolor for legend and color for stacked bar chart

```

  "legends": [
        {
          "fill": "rcolor",
          "labelColor": "rcolor",
        }
      ],

 "marks": [
        {
          "type": "rect",
          "from": {
            "data": "source0"
          },
          "encode": {
            "enter": {
              ...
          "fill": {
                "scale": "color",
                "field": "lx"
              }
            }
          }
        },
```
that does not work unless number of modalities of domain is equal to number of defined colors in range config block



so here is a simple specification
the best that can be done to avoid hard coding the values of the legend is 

 ```
  "legends": [
        {
          "fill": "color",
          "labelColor": "color",
          "values": {
            "signal": "domain('color')" // woud like to reverse that array !
          }
        }
      ],


```
so we would need a reverse array method or a reverse parameter in domain function

otherwise there is no way I can see to match the stack order and the legend order 

here is an illustrative example

https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq6AjAAZFESPFkAzRtZygITgE7orHS8lHyh4dDwabl8AT10AbUgAYlE7AHYATnRRBSgk5FcADmQAZnZc5PNRADZReAqkzPY09gAmBtEDdDtRdvk85Hh4QtEShsM09HQbBoKM9nQ0hvm0gBZqmf7khfY7dHqAXRCwAF8lE8dcZA98WzsHEw1qGXQAG1gE4+9QqBfUIKgC18ABVEL5kLBEMYflAKG9WAD7McLkovscnH8AaYAshXgB1RgGFjQn6QOGvBG6ap2ZGXCDfUKQTG6SD+CysD50nyQViELqRFn6GS4glExBgABUYBmtLRMKZ6H+LIovlYr2QABlkFZiVynLz+Vj2rLQgzucycGTVeqALKWEmMg0RLEy0Io03o36KrHcVyuTaenl850swqQE0+M0Y70s32uPqBp0Cy1LCP0wMW3DWzXa6i6xPB5NQVNuuly0mZyDoXzwAAaDu5SaxJTs4dL5cZler8AAmg39YWsatW2mwFGvUrLULcQAFQz92HwgGiUfjhWTqCRAAeeHY3C3C7JS90rRp7Y98srrg02kP5MpOEKq4zManONeAHk-bBkHg78ecDPHx3UjF8N0gAB3Ql83lJsWTAVpJTAad8Wg8UAGpkPfOcjGRJQDkuSAMF8ABrD4cHiVEL1JPAYkILFqF8bheUPbUXAMAFxycbVIl8XQuO5KCxX4z15SeF5XkFd9RWJUTgL1UkUBuP9ghhMSPAklklOoW45IgM41NOT0QMZBA3ghT5DIE6NwLM9UDwUxlaPolkFhkIxHO5AxuAwe1VMMryIkwS0fy3CzPMZdxcSMS1XjiPTTgiqB-ECFkhNkwyDJ+AiqNJdVqG1AxyLASirISyB3FeSTLRcV5ogXRlXnQdhcQAYW4Oq+Jqjr6qSyBokYHiWXVVw-z6pqWteAAxWQ8AAZS0AEMj6+8LP8gKoHEt4WW83yZAACgAclq6JDoASjbAKTLUyA2O4DiRI2pxYBiVA93eR6noHQ1Pq+57EHQFz1r+pxVpZWAAEdWGrHQEphLKvoRq6EqRt1PRy+ViLIyy1Oszc6KxcF4DG8rXCY1BfoCyB+WCzbkDCj4Ub6u6HuBwzbpkXjKY2yADzZp7IDsrEhYcuHSSi14YqgOKGqpuMfxUscxfU55tstNyDHSxAjpF87SFWS6QdRq6ksZLXuYFoXwfCezZfZjXdDsOgVyN03uTifmeaty04jdyLBsllkYldP7rp5mJ2k9qnvagX3le5CWpcgGIR1d+OKsYKqLa9m2sROvi-YTgOk9eA94+N+GUbksPQJ55zCcGEmebJnzs9JGnwfpiymfKlnOLFjmuaj+U+aVkHntz63zNF8eoET4a49n-rv1-NuvY0tXAQCTW0J13Otz1g34-08vC8gtC15umPBf3u2bodwDndP9OPbH8eb-MoO7-leefZDxGz4R0vmJSePtv6ki2tVKA-JWCoDoMHMAmEnY5GfiDDOWdh43TBpaCCiBmCwyNmLCuwFq5yTITCI4aMIAY2gUFHG6ZLyvigKge6+V-wUjWiVOSeNIAkWQK-SAAYea1UFPAOg8AhFU2wWADI1Q6BpBKIUcao9IAQwACIQw1NYcaAiAASPl-iM0yp5HhfCBEJmER1UR4jJHs2kTYOgGRRg2GUSyRgqwMgGAAGp30gDLS0+jUCGN8QAOSBLoEofUZDcHCTgFx5UQndgiVE7gSS4l9XEgAfTSWAAAtPE9ezxMmxOlCk1oOTxAuzUjXBhVMzEsjGH1ERU4xESN8fYugLZChKPKqXFkJEZyoFeK4Xx-ioCBOCX1MJ1ZknlWiSU1oUycmRLmakmsJ4MkaWyesnA+TNlFJKXs1Z5SdlgCfMY7h5V6mWgNk0qxLSbHtIAmAB4PM+mWkQIgCghAACqoy9EGPCgkkpKyebzJmTgUFVNEmnKhezaJyz9kyG2fUdJ5UsklIKVTaJJzUXSmQdXExVz+EslsTdZpehWkWKkc8jIqw6CrBKCULF7N3lQHUZo7RvSBFTTQMEwllyebXKgNS9mFLTBUqeRwiJdAbA2FWKIVxlp3GeJ8TolkvKglAp5tMrqYA4U3XBXqllV8tmYoFWVIVJLLSNPKuKwgkqVrPNaAy3oirekqIGUMkZ6rLSasmcCiF+qUkLKWacxZqyckmpVsinJRzCnIsOdGis3BcW6EqRa3GxKBG3Ltfcyl4jRVYOea8qmbLICfO+X831UB-XauhSCkNQaDXyhhXiiNYK1ntqRSi2wPbMVlJyec6pRKrUCLJfKe1rSMgZClQ+GR4gPElDSEq9lGitH-JZAAURkD+N66pDY-BqW-dmwrIBFsnfmiV4iZ1zoBC60QhQ7DJsaiolV3jN2Wh3Xu9gB6pmNtWQO9FZqg02EzTCUx1qoC2ssVA698Bb1OulXExxrRqgdrLZ6wZwzP1QG-WgX9Oh-3NqbXqjD7M20bMjacl93Islxto89EDer43YtTRUp+FzLV1Kg5AXNsHrEIdnUh+dpbWUqMrb83DkB8P7qI4GvVLaU0AZ1Tk8jhqu1UYTb2tF2mgOdrTY+UhFCFKQDwClWArhogUwooKqm9cWToGoIxYQAo+qMWYoQdgr9SoCz6W7XhJKEqUJHXZ9mDnupVUbr46QvhFZ4ycL-LhaD6lixoTzaIHE9W+a+tTCE8BCqWGsGlqumV0bPkYbZZiNZkCtlM6tYqOWfiQfHb4qdjyRNLTkQonpbyVEco3TWyAEzu5cazWOlkF7STtbaZ12wjjnGrsgO+tV3KWQjc5Ap2Znb9PQsRdRvFjHNpbIY-20Dg7TkZrGxB7NDS2tXodR18qHSum9cw-07DPq1sBMBZtnVKm2OhoSftztame2neAwcoNrH4XsdOcO+Go6eM5vu3Bx7s3nslqW5J6t33xm-dCQD2HRObqUchSkkH0cTs0bO8ai7h2CXXea7dy0E7psPcdZj5DMj6WMuZUtgbXK3k8r5aN0L3HT28am4yGb0vuTSJKLK+V7q+tuI8R+obda-sNpI4B87kPE2gfA8zibNrUeCbl6DZ1rrWgq-e5aL1OHNei+1xRknl4YlBvU62sHB2+0G503ko7gtmO6BhxpwzYArvi-G8jlk-Gqay7vY7bHXypPO61a70n7vlO69U+GinBeA9Rtp-7gzQ7jfUUl61u5aPp3Ca5-OpxDKMjLoF+uoXZaBGycI4e88sfq+TfNw8oTyecAPqfcH8tK3pM97-Vt8neu6cB-NUzqvN0z0wcTxzm9DeeYdIyGh73eUsPetn7ugj8--t58B17sN3a-e6ap0UiHenofB5xRxqpiOwsb94wnsVHfUfObQCVPKtc-H9K-HXRTUjbbPbIvUHBA5-WNGnFffXcveHYzbKUzczAISzazehE3ezAmcGPAfYEiXxJLI8aVdzJiXkbzQg1leKDaELH-CXG6CLMIDqdUYmGLaIeLAeJLJrCbNLALTLZAbLdOdABAQrKwPvNSVg6pLA0IRQ66NcSsbUSA+TMSarArcGXQ2rQ8XA3dKzXwGzZLAfDgkgy0SqLmZmLcQgPVamCIWBOgOKMAAAXg8LAEOjn2QEOnkP0iR3C2sL0EGkoOLmVGPEr1rmIKBjnmszVEwD6mkJZFQEJAAEErAoD2Z6ZHCWR9oYE4FYAyC4ssjqB1REEwAii6BCpyjKizowBSBjQ19YiQj4iKpEimpfFUjLQtwC5e4HCnC2RGAOQkINADoaj0iDB6jkBGjMJux6wYjal2isRTDUAkiejipeZfA2dGQ8inD9oRiOR0I4wbAzoJQJjCiXC4FpjZizp0JFjAjEpf95RODOizDNiUjtiYhdjfEDiCjjjYBTi-RzikJckXBYBri8BXC7jsi5iqjuw+xliT0rCOj1ivjypeioB+jLcoAATLQjjDBRjgSVQ1RkA7QZB0IyT1QtQdREAJQajP8awLiripjMj4SHiniUSeF3iMTujviWR+it9cihidobi6BcT0ImS4d4AJQwRyS6S8wGSaj6N1keTyo+SujkisSfiBieYCTkpiSxipQIT1BoTYSOSKiETHiaxkTWiVi0S1jtStig5fA8TboxTCSgTqTsxKTfTFTcwWBGSJTmT4BGjTTISLTbirT1R5iwAkTnjjZVCuR1CmFBYu4s9noDD9DWAas6tAxjD8CzDGC2inSWRbCJD-ivTaEYS4F3CABCbw3wi-OTAI5QnwVQ-CQiPAZgA9YGMzemRWMzPsghF4pwJqGIZiAQxkN4DSRzLOLkZwHiKsnAczBEJc3svAdUAAIW3kdnOEIiFkaw7HNHTMXholCL8UsGQBmVM12nQD8lRMZA7hCgMILPZioODnkJrlZACAKi0muB0j-AqwrHTPziMKvMy0sG2nvJ8kfLkCjmcLINzPzNlgzmimGjLjYNJBSgApqmdGoGiGYPklPJskJggpwKgt8AsE0jgr2jbmQtpiIlYRoHQqoL6WMlMzwrzkIuIsPSyiODOCAA

**Comment by jheer** [comment]
Why not use the `sort` property of the `stack` transform? Here's a [modification of your shared spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq6AjAAZFESPFkAzRtZygITgE7orHS8lHyh4dDwabl8AT10AbUgAYlE7AHYATnRRBSgk5FcADmQAZnZc5PNRADZReAqkzPY09gAmBtEDdDtRdvk85Hh4QtEShsM09HQbBoKM9nQ0hvm0gBZqmf7khfY7dHqAXRCwAF8lE8dcZA98WzsHEw1qGXQAG1gE4+9QqBfUIKgC18ABVEL5kLBEMYflAKG9WAD7McLkovscnH8AaYAshXgB1RgGFjQn6QOGvBG6ap2ZGXCDfUKQTG6SD+CysD50nyQViELqRFn6GS4glExBgABUYBmtLRMKZ6H+LIovlYr2QABlkFZiVynLz+Vj2rLQgzucycGTVeqALKWEmMg0RLEy0Io03o36KrHcVyuTaenl850swqQE0+M0Y70s32uPqBp0Cy1LCP0wMW3DWzXa6i6xPB5NQVNuuly0mZyDoXzwAAaDu5SaxJTs4dL5cZler8AAmg39YWsatW2mwFGvUrLULcQAFQz92HwgGiUfjhWTqCRAAeeHY3C3C7JS90rRp7Y98srrg02kP5MpOEKq4zManONeAHk-bBkHg78ecDPHx3UjF8N0gAB3Ql83lJsWTAVpJTAad8Wg8UAGpkPfOcjGRJQDkuSAMF8ABrD4cHiVEL1JPAYkILFqF8bheUPbUXAMAFxycbVIl8XQuO5KCxX4z15SeF5XkFd9RWJUTgL1UkUBuP9ghhMSPAklklOoW45IgM41NOT0QMZBA3ghT5DIE6NwLM9UDwUxlaPolkFhkIxHO5AxuAwe1VMMryIkwS0fy3CzPMZdxcSMS1XjiPTTgiqB-ECFkhNkwyDJ+AiqNJdVqG1AxyLASirISyB3FeSTLRcV5ogXRlXnQdhcQAYW4Oq+Jqjr6qSyBokYHiWXVVw-z6pqWteAAxWQ8AAZS0AEMj6+8LP8gKoHEt4WW83yZAACgAclq6JDoASjbAKTLUyA2O4DiRI2pxYBiVA93eR6noHQ1Pq+57EHQFz1r+pxVpZWAAEdWGrHQEphLKvoRq6EqRt1PRy+ViLIyy1Oszc6KxcF4DG8rXCY1BfoCyB+WCzbkDCj4Ub6u6HuBwzbpkXjKY2yADzZp7IDsrEhYcuHSSi14YqgOKGqpuMfxUscxfU55tstNyDHSxAjpF87SFWS6QdRq6ksZLXuYFoXwfCezZfZjXdDsOgVyN03uTifmeaty04jdyLBsllkYldP7rp5mJ2k9qnvagX3le5CWpcgGIR1d+OKsYKqLa9m2sROvi-YTgOk9eA94+N+GUbksPQJ55zCcGEmebJnzs9JGnwfpiymfKlnOLFjmuaj+U+aVkHntz63zNF8eoET4a49n-rv1-NuvY0tXAQCTW0J13Otz1g34-08vC8gtC15umPBf3u2bodwDndP9OPbH8eb-MoO7-leefZDxGz4R0vmJSePtv6ki2tVKA-JWCoDoMHMAmEnY5GfiDDOWdh43TBpaCCiBmCwyNmLCuwFq5yTITCI4aMIAY2gUFHG6ZLyvigKge6+V-wUjWiVOSeNIAkWQK-SAAYea1UFPAOg8AhFU2wWADI1Q6BpBKIUcao9IAQwACIQw1NYcaAiAASPl-iM0yp5HhfCBEJmER1UR4jJHs2kTYOgGRRg2GUSyRgqwMgGAAGp30gDLS0+jUCGN8QAOSBLoEofUZDcHCTgFx5UQndgiVE7gSS4l9XEgAfTSWAAAtPE9ezxMmxOlCk1oOTxAuzUjXBhVMzEsjGH1ERU4xESN8fYugLZChKPKqXFkJEZyoFeK4Xx-ioCBOCX1MJ1ZknlWiSU1oUycmRLmakmsJ4MkaWyesnA+TNlFJKXs1Z5SdlgCfMY7h5V6mWgNk0qxLSbHtIAmAB4PM+mWkQIgCghAACqoy9EGPCgkkpKyebzJmTgUFVNEmnKhezaJyz9kyG2fUdJ5UsklIKVTaJJzUXSmQdXExVz+EslsTdZpehWkWKkc8jIqw6CrBKCULF7N3lQHUZo7RvSBFTTQMEwllyebXKgNS9mFLTBUqeRwiJdAbA2FWKIVxlp3GeJ8TolkvKglAp5tMrqYA4U3XBXqllV8tmYoFWVIVJLLSNPKuKwgkqVrPNaAy3oirekqIGUMkZ6rLSasmcCiF+qUkLKWacxZqyckmpVsinJRzCnIsOdGis3BcW6EqRa3GxKBG3Ltfcyl4jRVYOea8qmbLICfO+X831UB-XauhSCkNQaDXyhhXiiNYK1ntqRSi2wPbMVlJyec6pRKrUCLJfKe1rSMgZClQ+GR4gPElDSEq9lGitH-JZAAURkD+N66pDY-BqW-dmwrIBFsnfmiV4iZ1zoBC60QhQ7DJsaiolV3jN2Wh3Xu9gB6pmNtWQO9FZqg02EzTCUx1qoC2ssVA698Bb1OulXExxrRqgdrLZ6wZwzP1QG-WgX9Oh-3NqbXqjD7M20bMjacl93Islxto89EDer43YtTRUp+FzLV1Kg5AXNsHrEIdnUh+dpbWUqMrb83DkB8P7qI4GvVLaU0AZ1Tk8jhqu1UYTb2tF2mgOdrTY+UhFCFKQDwClWArhogUwooKqm9cWToGoIxYQAo+qMWYoQdgr9SoCz6W7XhJKEqUOqejZ8jDbLMRrMgVspnVrFV8xB7NpLfFTseSJpaciFE9LeSojlG6a2QAmd3LjWax0sgvaSNLbSMu2Ecc41dkB31qu5SyYrnIFOzM7fp6FiLqN4sY5tLZDH+2gcHacjNpWkvlZtalq9Dr0vlQ6V0nLmH+nYZ9a1gJgKOs6pU2x0NCS+udrUz2kbwGDlBtY-C9jpzh3w1HTxnNc24MLZq0tktjXJPVq2+MnboT9s3cBzdSjkKUnHejsNmjo3jXjYGwSqbPxIPjpe4JyrjJpF0oZUywbfi8vrq5W8nlfKSsjrs6e3j6PuTVap6DZ5JRZXyvdbltxHiP2FbrbthtJHANjYu4m0D4GkfJdm3c17jqPvIYQq61ozO1uWi9ThjnJOucUeB5eGJQb1OttO-1vt-OdN5Nxxiq7uOcUcaqQ98nN0z38apjTu9jsvtfKk8rrVquQfq+Uzz1T4bwd+4N1GmH+uDNDqF9RCnKOxeCcQ5L+dTiGUZGXY1-LhOy0CNk4Rw954ytPYq6jh5QnHc4AfU+3H5bmvScz3+zrYPeew4N+axHEebe8Zg-b+b07hNx8RKh9DjXFebaJ9u3dBGa97Z9wdrXYbu16905Dop529Om7h+mzjZPuOR5ZHbsVneb3d55tIsTN1y3far6PuTAPJ9A+vyD3XJ2A-aaD43vnoe7vGeyqZ8zARLPWfocLuuAmcGPAfYEiXxX+RcaVdzJiXkbzf-VleKDaGhdmaQXwRWPGJwCAxLAWepMWZAuWXwDiPVbAnmDiBAQqSwawPAquTKMLHPWpTsJhDmH9cfCBKLeAYWdgmLQ8b-XdKzXwGzLhTfG6BzS0SqLmZmLcQgPVamCIWBOgOKMAAAXiULAEOmr2QEOmz3kmt3lFEL0EGnAOLmVGPHD1rnsyALEOszVEwD6nQGKiIkJAAEErBWD2Z6ZpCWR9oYE4FYAQC0CXDqB1REEwAfC6BCpAjgizowBSBjRm9zD2Z9CKprCmpfF7CWQtwC5e4pCZC2RGAOQkINADowjUBnDXDkBojMJux6wzCGCRDLC54UjbDyp0jLRMiJ1SQPCZD9o8iOR0I4wbAzoJQijvC5C4FSiDBIiKj0JqjtD9JHtEiGjkiBCbC0iHCYhfAOjGQuivDejYB+i-RBikJckXBYBRi8B5CJipjKiwBuw+xaiT16igZGiVjUi7CHDMjacoAdjLQejDB8j9iVQ1RkA7QZB0IgT1QtQdREAJQwjzcawhiRiSiyigjpjZiHieEkj+DUBVj3iMjfB293Ccidoxi6BPj0I4Tbt4AJQwRgSoS8wYSwj6N1kMTyosSmi1ig4sieYfjkp-iCipQTj1BzjLiUT1RKi7i5jEpdCaIljsTcSWj1jfAvjbpiTfi9jwTsxQTNS6TcwWBYTST4T4BojBTTiRTxixSKiQjJSP9QgQt5iOxzQmDQp61TIuDwYuDYtAxeDf8BD4CEinisRxDkBuSqZeTZCLi4FFCABCVQ9Qi-QjLQ20nwe0oyahQiPAZgA9YGMzemRWMzLMghaUpwJqGIZidA44KsV4DSRzLOLkZwHiEM3QczBEeszMvAdUAAIW3kdnOEIiFgS0dJsixEXllOeL8UsGQBmVM12nQD8keMZA7hCk9NlgzmiiDn-h0PlBSgKi0muB0j-HCwrCYPzh4KWOiAsE0hnJ8jnLkCjgjNpkFhXM8jXMDlijLit23ICF3JqmdGoGiEQK3IDOHJZBrB6lDKcnPMIMsG2mvL2jbgfJZBYQMDYRfIgLx20JrlZG-Lzj-IAsPSyiODOCAA).

**Comment by blset** [comment]
because in your modification, the legend and the stack do match,

 but the they take the color I defined in the range in reverse order


when i define 

"range": {
      "category": ["#5079a5", "#ef8e3b", "#dd565c", "#79b7b2", "#5da052", "#ecc853", "#ad7aa1", "#ef9ba7", "#9b7461", "#bab0ac"]
    }

I expect the first color to be down the stack so I need to sort the stack transform ascending, and then the legend is reversed unless I hard code the values


I need the first color to be down the stack because I apply this range of colors
to  comparable variables that do not necessarily have the same number of modalities but that coincindes anyway on the first ones

for instance var 1 MODA MODB MODC
                   var 2 MODA MODB MODC MODD

using your modification, comparable modalities, do not receive the same color

**Comment by jheer** [comment]
OK, thanks. I believe understand your issue better now. I will open a separate feature request issue. At minimum, I don't see any reason not to support an array `reverse` expression function. It might make sense to add sort or reverse functionality for more control over symbol legends.
