### ISSUE TITLE
add support for wkt files

### ISSUE THREAD

**Issue by djouallah** [vega/vega#1686]
all our geometric data is saved as WKT, which is basically a csv file with a column geometry, it will be nice if vega-lite support that format

**Comment by domoritz** [comment]
Could you implement a loader like https://github.com/vega/vega-loader-arrow?

**Comment by jheer** [comment]
We do not plan to add built-in WKT support to Vega. However, there are existing WKT to GeoJSON converters you might use to prepare your data for web-based visualization. For example: https://github.com/mapbox/wellknown

If desired, you could also use a converter as the basis for your own custom `wkt` Vega data loader plugin, following the arrow loader example linked to above. If you end up building this and making it available as an open source release, we'd be happy to link to it!

Hope that helps!
