### ISSUE TITLE
Document about Vega's scalability

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1697]
Following up from Slack: 

> It’s not a simple question, so we should break this down along a couple of categories…

> 1. Data ingest (depending on the kind of input source). Serialization is typically the dominant scalability issue with Altair (largely outside of Vega itself!).

> 2. Data transformation. For example, filter and aggregation over 1M elements.

> 3. Encoding and rendering. Time to first render given a set of input data objects that map directly to scenegraph items. (edited)

> 4. Interaction performance. This could break down into multiple aspects, including re-encoding elements and re-aggregating source data in response to user input.

> We ran official benchmarks with Vega 2. That repo is likely still around somewhere if we want to reuse its approach with the modern stack.

**Comment by jheer** [comment]
OK, I created: https://observablehq.com/@vega/vega-performance-tests

The notebook might be nicer if we included visualizations, etc, but this is a start.

**Comment by jheer** [comment]
Added link to performance benchmarks to README.md.
