### ISSUE TITLE
Graticule labels 

### ISSUE THREAD

**Issue by mattijn** [vega/vega#1705]
It would be nice if there is a possibility to include `graticule` labels in the maps.

Since d3-geo only does projection and generation of paths some other mechanism should be used I assume.

See original issue at d3-geo repo: https://github.com/d3/d3-geo/issues/159

Where @mbostock shared this observable notebook: https://observablehq.com/@d3/graticule-labels

**EDIT**: the reason why I'm asking is I would like some reference axis in the following [Vega-editor spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7RiiJADujAyxsAGN3dzJG1fLoBmDy9IA3Q8TBwAbSUIUAgEqBl0VB0cSFZqACdnY0T7ViyAG11IfCISciz0BwZmNnZWWGQs+Fk8ZBk8OjbUUgwCRgkZUjCI5rxYfvRYDqz+5FhEACYDAH0AMyLuB2QitDX2IslpOS9EyA3uLIHdYEg8AE9CNKg1Qm4pWQUoDeRwwqvSCpJarTbbXb7VCHEoAX1iYHhEAAuiFCFlPsh4HgeDJYLoYol4vlIMlUqV0Zjsbi8iSNNo7pANNRkiV0lEnC5EPIwChfPhkZBYecEpdmIzmazSmN0AAKADkmRyBnlAEohSL7E8XqVnJ0cU9aRcssgtli8ABNXR4LKsZAIpFgVEmDBZADW+OiCOJFzJQNdHqNou1QKW6B1mqgs0e+wJkGoyHUiHDOmd+V+GNQjJlpSVuWFCPsnTaBlePpJrEIYzLhbpNu4brLkAo6CKdtKR3Q8DdGtrF1mGMbAHVnK4cPcW23Xm46KIC+mLhtGEU2WB7ghW0C2tssj8xXsjOlKS8sjjFnQW7v5wutdxuEUcYQ7n26b4pelgPKtjswHs0PqwHYZADH2KgijAKJUGReUcDGVhUDoY8WjPWAL3QLJYUgF8IEddNcISa8LhtdA8SuG4CXuENSgTJMUz3SkJHNGkjwxRjqW+WFkQdJQ0yjeBN09CDvVrUkUi3e9riDLVniBIpLH+XdI1CbgMEsbNwkiKA8yMHl9yKQ89AxE8ULQq8lOqKwgRQcIMCfJTtAxXQNlbZpuJREJ9gTGQDEEqJKOYWN0m-BxfyhACgJA5AwIgqC9yXFdSm3STOJAWEgA) (geo data in a cartesian projection)

**Comment by jheer** [comment]
You can add graticule labels in Vega using a similar approach as the D3 Observable notebook you shared. [Here is an example specification](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAdgDMABkURIKRtXxbRugCxGohdGrWMZ1S3cjpWebrEYAvZC1IBzUFECVIP2oZdAAbWC0AbSUIYChY1CCcSDwAT0Ig+SgKeNZsqFRGOLjkACdIMABfOzSM9CzghHiikrKKgEYB0WalAF1FSMI67glkeDweGUScFIg01PXITIqQmbmFpfD1rfzCrWAos1i44LOgls3jbtqLq5j4rvgeyEeT4xmeHQeAqSUMYHB+gmTyg8GQMhBDVWkOh-ygeDq6GWcWBoJhaXeN2Cqg0iDApDAACZfq1-pdokScqZzHhyVTfjCxpsmuNJsY1MDMKtNqA0dsOrscXhErTjBisbAAGbcOqoZL4sCitGnAq7WDIACO5RkcOO2ueQLqeC0AFoAByGDUW7iELR2gay-5REGunADfQanlorknP7rLUncWdHJxWQymG5THLZWq9XmiPa3K6rqG42mz2R2CW604G0DB0FrZFl1acsep1QIvIX1gACcAfNQf+IfWYY2Yp2XUIKDqRQTpTi5RWYCSl3uwQAysP6g8exA+5qE4OcsoVXEwp7IKw6rccgKgaRdye1GX-ahJNI5IeUxgS5vzVnzjkfIRZo+zWKirIMCx6SliYQwl2660hmxjblA1CYos8CsK8h7ysmKpqsK6botmOSIcCjAoa8ozBtyvIRMYGB1AA1tOazhgm845LAiDoOch7wHEjAthi5TPjM2GapA55CghSHEahDyHvC8DcGoFSwVs8KIhcDbejMtHIAA6uomg4JcE7lLWG5ikWWlKZAxm7AAxE4YRmV6irVKeIk2VoMioXEUH-L50HMUmSpYWm2rpJ+uzUMgvjsZx9j7PMiyyME0yzIlRxkd23Iwcx+GNrFY5itxvFaPxyCCdwwmXGJxJ7o5skmgpSkapAqn1Op5rGC5NRvB5OS2fog0cp2kHoUFL6hWi4UsQh0VsRxvR7GlhzJTkqUHElciZSca7NDlYozVEBUAVsxV8XUAkJoqQlvDVrHLqONIJnJTUdZmrCEOezWdY2GLcNpemkr1-SmZWFqWcDk52YN+jDdq-l7YFCoTThYV4V+s0xQtCjxctm0pQlK1bQju0bspEV3MgAAe1oVVVomCsEUqJE5rWNYpb1im1SLvp1kBU5DJk4PoTmRvE1yC7sdRmBYotbOw6D6jxMhWX1lTqGorxy3K1NvvS1yfDk6DsLAAAU56sPeYkAJRgAA1GAADkAANjv22A5sgVbgpgAAPBCYAAPxOwubs4I7AByjvW09P2QN1blGSD-Uw3DaJy0en24pzmZ5G8DKG423y1KbjvrelsiO8UYLFBb3tAmM1tJAMYxp35kHZSKuUY7kusnV1N2GQzQJM8CLMNfJHOGS13M52KAtDwXbmQCSmja1A4sxJLTPIIq1rr5ACtKy4qvJ+rTha2D6J94vBvL8bZt13QNvuy7bsO57eCW8-Pv+-oQchzDk7KOMcD4J23inIaCMAofg+l9OeXo863w+MvF4yBS7lyJlXGc4In5iUbs3Vu0Dtq9k7iccmh0QQ037lAa6lVbqMxjHGWOXoXpT15lzBE7Vp5xyQe5M+Isr6eB4lvIeatIBwi4Q0A+R9kDK1PlDYI7BuAEHoQfKhetCSF08CbT+38X4Ozfu7PR9d0B+wDsHR2OkgGOwAKLRxYR+cBYiz6QAGlAwMlZM7wJ4XzBeIkl5fB6Bgwmm1sFJDwYKYoUIm5QjbqGDuoZ9pekoX3OmDCR5MOWI4lS7NvqZlnr4j8fD9YoOCMyWWQjN5yBcYonIki1IyMVnIk+ED0Q1nUTfAJd9ggPxMT-IEttDGu2MZEoE5j-6WOsWAcO9jQFCOcfwupUB3Gw2IRnOB2cimZn8aUxkRdgll1CUscJYz0DRIIXE9ZiTSEQC5DyIAA).

I also added a corresponding Observable notebook here: https://observablehq.com/@vega/vega-world-map-with-coordinate-labels

**Comment by mattijn** [comment]
This is completely great! Now I want to publish a paper with some Vega maps🌍
