### ISSUE TITLE
2 issues with axis label datum.index

### ISSUE THREAD

**Issue by melissachang** [vega/vega#1719]
**1. datum.index is Nan**

[vega editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7QECJAA2yAGZ5dABkV2oawroCMAOxedpAATozU+B4h9uzcBNyoAQBsSgC+IZAA7owGLLoAzO4ATHSBKQAcAKzVolWB1VmweACeTrqQ8MgODsb2Buh4mDgA2koQtt5QMuioOjiQ0qxh3QD67v3TkBToDqzIsLrj03ZTp-bO6N14a7v7Cz5hB1sXUPDcrDJuOCXVhU0JhdIBZUPMjDgrg5YMhYsC8MgAB4-J4HX7-aqvYHcfQARxeODwz2QQO8mVJZwp3kgVxudz2BNROjhpy6n2+uj+AJZ21B4N0UJhPOpCORnSJaLAXMxwtCOPQ+MegpJb3SFIAukDyd5zqFZvNOoNhhssfZlqtHktPhaTTzIET0DJYM5uGFkmMqWBday2oRLS63awHJhZfYkYQwoahqxUKMADo067IW73A4J9UAXizCYlyATYAA-GB3GAcP5Tdt0EdFq01rTk-SHmtpGFbpYDEjIJ61adNWSlOrmpFZtDjkDvTM5pbay1kH47anHoV-Fq4RPIPrLShItE7axCEbLexHQZYPpugAKAxJdCWC8Acla94AlHQnFYWPJi3RRCUv+46H8EpnzAAAqMAZwRPwtQHLIMDCABraswBOSlWU3Tp4KQit7VaP1OjCZB4DcO0WnaR5UNZY9Iw1O1nDCJIbE9EEhhGKAjXQE0KW1bZkBkD4OyYt5IH3Q8hLed4VhbcSJKgRdOkIbhLARGjZJ44TnEYXox1kyZPR9Q4URYvAY3jNkvjwdMwCzDMwBkIMHDAAAfJywEYWAADl0A8q9o1jBMPgs9NnwrYT5Jwezen0ux1IkidhIQPZLQ+BxXVC4FNJ6CF2MYMFkCMaKIB7CTB2iyB5XgZhWhkiSlngJLOgqqr0upTKHGy8q8ReaLYp9bhuAcPBGD8HB4u2DRqBHTp73vABqI1TJzJFLMgdUuzU0MoERGqEvqjpFm2zbLkYLLOkCjkes2yBERKHbgUS-atpa0JwuLS6yuq0bCqgB7p2e47TsWesUwZHR3tkyBtyiFExupX7Omqo6oGPGRstzHru24mCIFKs09sOHS0O2DCDpw31LQcSxkHQSM7WvDBLDugZWKjY1NllGkTvas72Tcbi7TCR1qAoz1PE9WGfuHPZOlyfJEHWi5iu8XHicYbpdFzO1tAYjXiVXccKQ3KcEbJvCjxPHD6dvOQvuEjjWc49nmLajrgcbF4OZbGGypxTDGaul2EbrJMQabL21nbTtMdOXqoEFqxHjGpYoKZ0IJqmmtmxT6Pplj0xDAsKwAEkZBkZBIxwADfztMxC+oAB5VRy48QC-0NvZhw8fWdUNkn3gGtK7XJxqwkL6W6ZvRnbeBe3Fg421na5jq+Xy9KrVbXWDn5w34+FwnWQAYlEer2AMUQ14P9hnGQfxnE2DVu6J6k+8665mqHs2FKUjkJ4Zm2vWYrPdirEF4aSXo1LqzJmJe03iqXOAshYizeGLN4K5ezYzACrSA6BEQEw9D3Vk8NSZ2ldCdDkix4iJGSHaagERsrKjtMGdgPQABisg8AAGUtCPH8Cg7YTDWH7FgPLQkxJGHoGYQ4euVAwjBhGmATWhshrwAQgAYV5qnJYUs+iLG6FpC8ssWCkFEO4EK29WSaEjttMsj89KEPxp0Q6htSF8SMpQtQ1DDa0LyBwhxNYcLeLRmIpRas1EaOnoQ7RZ1kD6MMYgYxpiFZkl-tbAUewhSGwEaOSE6TYSGwwIiAAosiVxMR8mWGKQichxYh6hOQgww2ljUadkrrYgB9iGr+JIREUpiwnCuACXQtJ0I8msiyWw74XDtABDbmMiRPQAAyuVmAzL4dSJpHZrFgH8HaPiAlE7MSychCWkBlLl2uENKgsCrqiSGAc3SPh+qDWGqnSJk1pZzz8kkiSStFY537ACzBWQPgyE0tYCJyhETuTuiCSeMh1GpQrlAA+6BkDsEKMeQZeQEVpUWAfNF+UXA4SyTipFkAD6FEpc4aot1xGSImUZAAsuwmEYRBYkUyfMhwDKADqMToa6GqO4NZoQskAAUC6WHBWAAAnLUlR9TcltOwVC2AABNGFqAKklOqcUDBap0hAA)
Hover over "true"

**2. datun.index would be easier to use as an int, rather than 0-1 float**

[vega editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7QECJAA2yAGZ5dABkV2oawroCMAOxedpAATozU+B4h9uzcBNyoAQBsSgC+IZAA7owGLLoATO6eJrB4AJ5OupDwyA4OxvYG6HiYOADaShC23lAy6Kg6OJDSrGF1APruTX2QFOgOrMiwul19dr0b9s7odXiTC0vDUACa3GEc6GCWYACS7IboMvJgAHKRyBGYsdu13KwZG4cP4ABwpX4bSAWVBDIw4XYOWDISFzPDIAAewLOFyuNxk90eLRe70+3xB4Nm2yg3H0AEdlro8JdkN0+pk2d4tn9dvtDotGSMAKptRBgMIrPLIIGwMC5FjvC4sL4E54GMAAdRW6LCBIAouNachnmBnnVymEKlS-vAAUCAqCAMyo7zQxiw5DwsCI5Eu0LorE1EXoMUSjQGaV4WXysVvJUoXWmmTqrXlFVgA1hI0ms3ay0Ux3WqG09AMk7M5acuwc6ncqG85AHI6CqAAcUG7EYJtuqZ1BIAIowKIwNLJXgAVFBgduoTs-Kuu22A7Fg0rU5ruuG6H0ohf+zHYyAzucEnva9OD4ejkmT5DTjtdikzP32Etlpksvc17Z1uYNpsCickB6rA3YEh81BfF2RZzEu9ogoEzp7huHpejuL4+AeNQgWBpKQeSYBBIWGGQG+LYVqy1Lfhsv6uv+-LHDUADKALKomAASJoAMKIJYKwomAPGWPO65QHBK6BP4JEwluCKLL6yGYYGIwsaoCYEpxBJCTI-GvNp6AIf4MGumR5aflRfq0aE9HNkBDxQSahC0qwDitDwMiyrcTH6JYxmhOJqSFNJm6etu8m7qJkABoe9nfASTmEC5bmyJ5BLeeglggikhR+a+9LkeZ2zUX0Vk7HsjYMS2kAAAqAhI6CdviYAADIhhcKLVegADWI5tHIJEBSCACsoLBahYVIhF65RVhIy1TI9WNbcrWIO18idT15TPMNoK5TS+VmZWFl7qVUA2YBNS1V8ahgAASow8C4VdYQ3fdtp7f8y4BENa7TTJoVyZNJHRZdywvdwd0PU9YOvQ93DDc+imkQdH5HUVllI+djEjFx3AOEkJ5NQAsp69QOJYel4wT0EDXaK6iKNSP-Wh4XA7NUC4-js5dqeBIkxGDQU4JVPcwZhEMx9pmo5R6MnZj5UAdjUAAELSrQ5NNcrzzUK5EawIgH2DeLohjbJ3qs0jIMjKrViLIwmva7rKyICCoiiJLKM4BRX4Y5FWNVdVXysMOuHNe66CvIHlyG3TASOr91JuuNgMKZFVtQFHwc801YcYJHQcgvHHulgVaMbMVXLy3ytk1CTyZ3l5jBfGE1zNcgsg6LTX0goUjORczE2p9N6eQHXEZNUxTdhC3LXtzpPe7SRUte4V5e+9N-tAUxEQtc8XUmuOgyMA4TXKmAQoANIx93hG96bAPm0Dlvs5A2-261Mj7wSh+oMfp9TpfBexd3wrzLuydeidN41AvpYMUtx2IQyEmAImsDBLMAqK8AAak3PAAxkhd3grfE2TMQosyfmnF+MCZBwI0og3iyDUFcXQVgnBeCe7uyXp7MA3tjq1irhVGuIwACCzgIiPS0ugCI7B2DGl5mALWYQiTqGvoQ-whQkL91IYPKaicR4iLEdxSRjBpGyIdooww6ge7ESRsvbhq9wFyz9grSqdlkzZ3HPUVg1BWD-zvJfFRK4wT3zIUPXRL87huIPp47xvjz4XxBGCYBpcZZr0cRvZxgioDNVYIgCo1wzzsFYBUASF9pR5ICQEfwEISHJ0fqEv4I9sm5PyQSLUhTimvFKTIPJCSUhJMOikhxfCnHVwuiMVsrB6otzwPbCJFhcIINYOUMc44AAaFSEkaL+lolOOiGkvwmVMty9xIlyMWcsl4azNn9Olj7NJkCMljKgPoqGBIhEyHNMyCoE9WKIGyNqc+TENmETUcE7RbNlLPNEa8sA7zPmWh+Wpf55RAUJJypwkuAy7nDPSaMpWkBxzqHEfbW4dw2gOCtAQwJQUalm3Qs-SFBKiXPBJQSMliwKhopuaAwZ3gK6bH4YrKq2l+JgH7BlJqqyRxsG1o8GQAw9K8QGMC-w7gACcYLdkQsPCK5EYqJW3ClfrVgsrngKsEkqsWqq1XcrsWAvlECeSPPxZpC1fE9W3FVhISw1BFXCRVe4Pu2zan0ooYy11uqG4Ei9T6v1AwQSBttTw2WOKHl4qqsrCIMz9ZNT1FYVyyYkzqiYraPABajBUoCO4YItKH6huHi-TNzBpW5vzWqItYAS0JHLQmwISb7EOvuU69NQESYYhhXCvM3zlrqFhVYeoKw9J22cBcGQNMkZG1VTWzRIaLZhsPGOidHyp051ne8yCThYBLvJiu3Uj5CLVv7fa6sjr6zOqqgAMUsGunNtwv0yHLQGoamq6l7KhCPf9P6aFgH-T2h9Q0n28pfUOt9I6agACl0D6B0h67+3AuoVG4K8TD2GgMgfrWExlJHniituISgjRGwDUZkAmhDGKQF2qQxAflPRBUuJqOcS4jwmoPCeCSCCDkVXgnI3uhtjLBN4lJUSZ4rwJMETBH09jLYdzYp-HxzJkBgyhklBGGUcpmCxnjOmdtvZ0yZmzKqY9FpKUbtjhSapO66Wyco4eIz4oTORmjBZxUL11Idts4mezhBTG5mcwWW1OneF6ZGQIp5R4Hy4QiwOIcI53ITinMeddkVN3SdrSEsDaIDkZbkVlsVOXrz5bvIVq1oJEaRVsYllNyXcWpfxThORamivTRKx54NXnyFycPP1pqg2rWIQS+FXTNF9NpdUmxDS3ElW6Tdcqyt7mZMTZ88xX56YI1bd9DtubRktMnE66k1Nw7etVVitnBKSUZkpQnj5fqrmb4aYO-U8D4SZFxTAG91yH2PJfYyixwi2UFuTSWyVFb+L5qLVZbvVaEp1rdV6s8KTo3E4Dy1Qyw8aOGoY5WmtDaePYf+BGgj5ESPK4paFUBZ6sNxFNQ5xDN63ACcA4q66EePPIZc9uKLvnCNGdcbADxsAp1IBQJxiLQmtx+ZkyFpzamIlhtucIqVzzdbvP7MZdr0WciNeCxJObucrtF42K4XdoZ3W01PaAjbdWGOtZtr1gbPbBvCd-GJ6B7VNRPd2wdr752rsOGO8xdo5nArWf8bmkHEOcjc4RzAJnAXZXwWk8uun7Oy1w750uIXNr00OuLaS8tlPBmx5Rs7VPGebcO556N+VsPIwm8T1b63OeyAgE3cT3X5HDfVs7w-l-MAP8-63DPv4gP-388k-3cxafe8D5HxPovgB8Tb4O-a072vXX689bZ9A1B8C6H2xQdQtBlQWGNjwZ3sbxvDum8PFQ6DCC3UMKP5MLP5gDYKv6DDsIy5J68aT74ovJc5cRGImK4QKJKKrAr6G4f7d6F7CLQoIFIEyIoGSJoFWJQHj4s6X6p5QBzLuLRI+L75+JXwYFB5Qgh4Ubf41A0FRJLAxIMFxIJLH7V6n6I7kHJ6UEGZNJ5JNRtJFIlJlK66JwjaC495ZI5JSEFKyGdLyG9JkHn4T7iFpaHKSLHJcFnIAgXLyBrLv5E47Kh44FtiTLGEzInLzJmFLJqCXKrLXKj67LQEK4o5VTwEmiTrOaIosDIp4CArWHB62HsFA6MpBFvJOZfJhF-IApChMRco+GgZ+GK7K5QCEoIAsoibkoubFb66r5d4F4b4jCFHEolEcpZHx4cbO6DoPaobu41CRr6oY5GoypWByrmr6TRGsGxEm7xE6rnZ3jiq9HSomoDFmrZ76QJo2rZGtHIbtF-jvpARnburN4xpWBxoKE2gVGYE2G7pf4TE1C7E4b7HIDeqHGXYJqCGJw14iF6EUFu5X7WxZotq3B5o6ztrtpdplpqgjFzBsHjGVaMpNrZrQYAnlodoglwZbq6H3au6PbfFQCHpc4hEpEzqyjnoLpXqCTLqrpDaKGnEsEQljGXHQkHqYhHrwrToEjNRnrzqXrXqMC3prpWqPprFn7okX5fFUGQCQZ-EEiwZgnMHKH2FinfoSkwaWAonuBsbNHaaCku7CmYminMa0Z4YMbEZYb44ylr52E1FQB6m4Zz74aEZGnYasZonshVgAC6bIxUv4kAeCQELQbQ0wMEowAIEwQEYwwZ-pqIUULcHkt6yQnQKGaIFQ0WNQMZSUH0mIhAYQNQvprAqAHQAAOkrtsQWS6QALxlkFkKbCZKZiaqZkhdgFlgAAD8YA7gYAOA2ZuZBZm8xZZZJZBZfmYYUoZmMYIW624W54kWho0WOYyRloDZzZ-gbZYAHZ+ZhZI6PZ5Z6WFu0hE52WV4eWc+BWGW85YAhQS5K5XZRZkApZm502tws2J5jo55rQOZq53Z15vZBZa2YWNx22+kJ5ogz5eAr5l565H5m5L2jkzkEO7kqUna32J5Q0QFIFa57uG5fZNUdUFOOcbU2ONOW0MgJ5KQyFnZqFbO6FBZkuMKEuMMvOcMJ5gQJFb5V5N5GFtuJefMpM1ulMXMc4J5oITFoFaF4FGFEeGsnqjshgzsJ5aqglZFLiFFNUxeocZeOeQcJ5qqcl75rFBZfejczcg+HcGli57ZL5pF2ln5r8W+n8O+v8e+BIS+F8GlZ5plwF5lLFllv+TU-+SCD+YowBGCoBrCgwGlT5rlKFFlm5iRpJUihBciqBFisAGlgF4V7lYFOlkAphc+dBsSl8GlSFqVzF6VllkhLSmoyA7Sch3S6AGlxFhVQl5FIlBZRh0ysypy3l5hHhlhqyGljF9V8ltkil0VeJCKXkvyERgKGlAl-VkVGFdRxRpKpRGlslM1Hlm53RMxkqcxpq8qSxlqJ5xQWla1GFv51pBxvql2B1Jly5ZlRVwlGVsJipCJQJhayJaoB1LlN1bld1jVGVOJwRs5LJLU7JF6i6pJN65JNVkATZp5YVX1EVx1BZ4pv6kpyp710NzZhQKV8NaV91llVpze9GdpTGxphFGNp5BVp5mmSM6AqwIwFQkwm8kw0gL0kwlgEYGIkAX4rp7pSgLpWQGg1AAwSIawbInp3pNQDNaYfgEZmSjo-g7pvw4tgwQEKAkQ0QEZrAhAvpQEcqBgsA+gdQAAFAYEkDDkbQAOQVAW0ACUdATgVgLArw7gdAogQULZdAaiNtYAAAVGAFLeiH4LzRAPzSYBgGEF1HTWAOsGIa6BLSMOHZHQGZUEmSMBKPAG4BGeUFUCcDHVCI8Jma6RGaIkkDYHuNCK0O0FAL6egP6VWPypANKLaBGGXYnFrTra3cNuMCzZ3ZFAZk5JYDqFzaJPLjsMfI0HGaJDAVPfYOiOUFmbdQWeJMWWAL2WADIC5CfAAD5b03CwBvDoBvAm2L2fRAjFk217SuiZIb0NCKTcYYTT0z2jCPTVAjC2j4yZkP3WRNwOBehJxbh31y6KSh0n57DoK93TRFGv37RgOVCX1nQ-1-1SyKSj0+DcB4wzJ+A4CnT2CC3C01AW0W0ADUF5M0WIxZw964qDkAnN2DgDz9iwQEnNX9SuiDNQAUKDJEGIOUdDT9UDTD8D8wTy7gnDSMVovDU9DD0DkAZRkjzgbDIwUCojkUatUQ2IODUA-DktgjettyI93N5cwdYAIDmjL9KwotnxoQ8dUAzDVYUUiZQE5MOkkiAZptGAvkEjrBldC9fpVe9YCjYksc9dEZUZkEFj2wCc+hiceDiwNQuQ+QBsBjfQJjcdD0AyEZ2gWYejGxsdVjKt2jEZKdut0pdjbjMOEDroNdPjtdfjf4ATA1F0fogZL0FTcwtINQv8P2fs9TDNTNLNBw7NmIlDhjQpoQoTJwVkowgdrTroMTE9UAAdyAQdVEwTdjZgFgVgESOkmZOALtbtEZ6zPqAA8qoF8B4J7TSlCHbELR4IrWLXY9Y-8B-cnQ4zUBcBs7ExGWUx4-4UTt4yMDXeGeXfI-UH-QPE0-09k20XMOM+E1CAAMSiCPTsAGBx6JzwvsDODID+DOAzA83QuP15NDBvOG3gOFOvMjAD32hfNm0-OTNVMAuV1AuQL1NSwQtKhQs5OuiwuT0RN+gK0bBul8p81ZDoAYjmO8uEu4NmM1C2PFgRCRg1DxCJD4J2PUARDYFQiuQyIOAfqyB4CTzaBVoRnav1AfpLD6zSwmsNT1BHNUBhCuRYOcaFMPRdS4w3yTNzPsPIDHxG3xMsCkCiDuAX2rNQiaCDO0OER3OWPSuMOysBkXBNyEKQDKtqCqtQjqt5Alpxv00BmZtegUQuvwBuv66euRD4Nv0+sOB+t5ABtBshujPNC0tyDr5zCmsi2tuugYAYh6hYiKu7MRmdO9voiEKROz2utR1xFQDhv1yRsiMEu-NzBaO5sRmJv9tQBOCuB5savVFts2u6v6uGsnCgp2Ptu5zMABDFAZMRsBARlN3cAt2eN7s6tR2K6D1fB7AzJUBWtIzt2tATP0NqAYOMBOsaO4PluxOMtuVcCzu+1gBG0O3UAsDH1tCW2hlTDuC2022kBnkAC0hEDbU96QKDSTwrZHxjWQtoMg8j1gT7kAYrI4rT0Izb2uOzUA8L6AFVjojw27eQrHNQ8LFVpMzgAZ7b-HIw8LjoUnzgQ06Kp7+7erybRM+ryI08rQonCn+rWo6t2IP0Y7G7+7nU5gPqugGqdjMyxbk7mpxU9H46sApwTHQ7fbhC8cRjxH6QQAA)

If you hover over "African Caribbean", you'll see "14.0000...0002". `datum.index` would be easier to use if it were `0`, `1`,`2`, etc, instead of a `0`, `1/14`, `2/14`, etc.

**Comment by jheer** [comment]
Thank you! I'll be releasing a fix for item 1 above. For item 2, we have existing end user applications that depend on the fractional value for customized placement. Switching back to an integer would constitute a breaking change. So we will hold off on that for now.
