### ISSUE TITLE
Setting style config drops all other properties in default style config

### ISSUE THREAD

**Issue by marcprux** [vega/vega#1723]
Whenever any `"config": { "title": { … } }"` property is set, it prevents the title from rendering. Observe the lack of title in the following spec:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "title" : { "text" : "Title" },
  "config": { "title" : { "fontWeight" : "bold" } },
  "mark": { "type": "point" },
  "data": { "values": [ [null] ] }
}
```

Removing the title config shows the title as expected.

It seems that the title color is not getting defaulted/set, because the following *does* display the title:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "title" : { "text" : "Title" },
  "config": { "title" : { "fontWeight" : 800, "color": "purple" } },
  "mark": { "type": "point" },
  "data": { "values": [ [null] ] }
}
```

This is new as of 3.0 RC14 or RC15, and I suspect it may be related to the new config precedence issue reported in #4745.

**Comment by kanitw** [comment]
This is also leading to another problem in https://github.com/vega/vega-lite/issues/4768.  

So I'd say that this is quite an important bug.

**Comment by kanitw** [comment]
Some of Vega-Lite's mark config (e.g., `config.bar/point/circle/square`) also gets redirected to style config and this is causing a similar problem namely that default style no longer applies.  

For example, [setting `config.point.stroke = "red"` changes the strokeWidth](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgE6Asl2Ex3PJcTcA7oyXUwL3bGSE3WzB0JU0wVEYxHTBCINoxByVYMAAzbl0wCnR9blZk+GzYOjUNSE1rTBxgSFZdMWwtCtIC33lFFQBfdQhIDF0AawbIAI88Ep7kJXhuTQ9qBtAIHoAPBcgUxmQxTSGACXS-ANdbNUg8AE9YoYBHVhCjPGtGKkgujR7ztY2tndMAWUiOgA+rFdECAOLoBLKU4XK6mW73ZhPF4dDRvHrTJQbeZVd5QEZKMZVSCwPC6bj9ZBDXTIHZoiBotFAA).
