### ISSUE TITLE
Discrepancy in object and array type checkers

### ISSUE THREAD

**Issue by algomaster99** [vega/vega#1735]
### Bug
The function [`isObject()`](https://github.com/vega/vega/blob/504012b0498e7fb5b885bdb5028aa9784b14e4af/packages/vega-util/index.d.ts#L38) return `true` when `[]` passed as an argument.

### Details
There is also a function [`isArray()`](https://github.com/vega/vega/blob/504012b0498e7fb5b885bdb5028aa9784b14e4af/packages/vega-util/index.d.ts#L33) which, I think, is made for checking the above types of arguments.

This is happening since JavaScript considers both `{}` and `[]` as `object`.

**Comment by jheer** [comment]
Not a bug. As you note, `Array` is indeed an `Object`, hence `isObject(array)` returns true. This is as intended, and you can use the `isArray` method in conjunction should you so desire.
