### ISSUE TITLE
How to generate a Flamegraph (flat sunburst) diagram?

### ISSUE THREAD

**Issue by falconair** [vega/vega#1736]
Hi, I think a flame graph[1] will be a great addition to Vega. As far as I can tell, it is pretty similar to a sunburst diagram, if it was unrolled to be flat, rather than circular.

[1] https://github.com/spiermar/d3-flame-graph

**Comment by jheer** [comment]
You can do it! Short version: Form a hierarchy (using `stratify` or `nest` as needed), apply a `tree` layout to calculate box coordinates, then use a `rect` mark to visualize.
