### ISSUE TITLE
Bug in Binning?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1737]
In this [spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5QECJAroxrZLGxgA2sEgAPAIzYADHQDs7x9IBMLgGwALL7+-u6B-gC+qnZOrnQufu4ArI4AnIFp0skZLo7J0bHOWG7+0tJBABw+0pk+-j4pgYUOxW7hlZUu0p0+yT3+juktcSV0mZXJLu55NYk5Ls0xrfE5DaFhLl0+gY6VI210Qe5z6f6VaX3uWQfx1z0n3gHJ7oOBS0Wrad17gTt5aUq-jSUWWozcyR2L2S-QutR8lWCtzG2XSPUyLjSe3CFWkyLc6RyiNSF26-S2eLBbXxdARDUxfWSEU6MJpjjKgQCfyBnVq1UpnzGiz20nCEx8GRSjhSNJ80sq7my31CjkC10abP6+Rqfy8gX5yVBgoJZSB10haTSMzyLgKVPiqpci06QOyFyGnjZ7kqjgRaoRNR6Aa9QUynMcTphErSbMRIKG2U5gP8qVjgdFXk6eym+TZg3z70anmkIq95Xq5UGEpql329rGe0aPVq0iygRhLw+KyFXh8NW8yuqybtxoSU0R7MuTs83kcbKDXjS5NSfb7dcFc-rm9HQx23m9oemVsR+Jp0wt03qm297YF3ZcyO398fL63bPqnL8CouXWkztPb71g+QEJN8IIzPqiKTOEWwATuhYkt6tQZH+SIgeyirApy5a+uBspfl0WL5G8vr7AAuho0QaMY8DKPAOhWNYGgQAYhhGAA7owmgsFY+QuOobFGCgjDUPgVhTAJgmQMgSi0ZojBKNQVisYJUD2MpzGqVA7AKRpWlSRg9g6Uolg4H4mmqVR+lGAAZowyBiJoVgrJJ+mQHgACehDIM5ACOrDoEoeDMDojBUGoFlScFeBiD5OArJFEBWVpkAeXp1mQOg1DUAATsIeBxVAtGsEFEXWVAnneX5AVBSFwXha5KXRbFzkAMLcCVeCQIlYCRJFyVsZAGA5QA1s57DoDl3VsQNYAqYYkCcdxiC8RJkXSbJ3DyYp6WqQ4u0pXZDlOfFcSNXtlWFZA-mBdFoUNT1RjNVdcQ9X1lnnVAw1jfF8CMDl8AtZp71gBRkRAA), 

the dotplot of the same data shows a max value of 1, but the histogram only have .9-.95 as the max bin.  We might have a bug in the binning logic.  

![image](https://user-images.githubusercontent.com/111269/55130952-05170c80-50da-11e9-9373-f1e90dc9cbb5.png)

**Comment by kanitw** [comment]
![image](https://user-images.githubusercontent.com/111269/55130929-eadd2e80-50d9-11e9-9d40-47de437b03bd.png)

**Comment by jheer** [comment]
I double-checked the Vega logic, and everything looks OK. So I walked through it step-by-step to discover that... this is a floating point precision error that breaks a rounding operation. 😭 

I'll see if we can modify the math to make it more robust.

**Comment by domoritz** [comment]
😱

**Comment by jheer** [comment]
So far the best solution I’ve found is to add a tiny epsilon value (`1e-14` works, smaller numbers do not) prior to flooring, creating a “close enough” region to the boundary. But I will need to add a bunch of tests around this before moving forward.

We may also want to consider what happens when we outsource computation to a backend system. For example, do we see any similar issues in database queries that include the bin assignment logic (`start + step * floor((value - start) / step)`)?
