### ISSUE TITLE
Add default to transform

### ISSUE THREAD

**Issue by csgibson** [vega/vega#1739]
I have a data set that has some nested values that need to be folded before a stack transform. Some of the properties are not defined on every object and are fed to the stack as `undefined`. The stack runs and spits out `NaN`. 

I would like a way to specify a default value (in place of `NaN`, `undefined` or `null`) for either of the transforms, or a way to transform properties to a default value:
```
{
  'type': 'fold',
  'fields': {'signal': 'foldsArray'},
  'as: ['stackFoldKey', 'stackFoldValue'],
  'default': {'value': '0'} // example
},
{
  // example
  'type': 'default',
  'key': 'stackFoldValue',
  'value': '0'
},
{
  'type': 'stack',
  'groupby': ['key']
  'field': 'stackFoldValue',
  'default': {'value': '0'} // example
}
```

**Comment by csgibson** [comment]
[Example chart](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwADgAMuxREgpG1fFr0GlkdKzzdYjAF7ItkGbNeGoj6jPQANrBaANpKEKAQUVD+qK44kLCshMgATgDC3AHcqcHe0ZAUgazxYCGQGNTIMniY8lCpyGoKUACeyAHZyi2Q1I3VPfCt6HL1kOwBJZAAuuFgAL75YJHRMehxbgBmWWqwAIKpqeitCnNGRZOl5ekA8gAyNwBKAMp0ldW1PbcPL3SNzWNvk9Xu1OtxuoD7sCGP1RlAgb8hiMvlDfhMprNovMlNNvJA1OhPjgwtEVgVYqVILUJl4zlALiVgsS6aSWatIABJAAiWisq358JuAFUAHIAFS0AGYACxLAWCn7PLRk+VRCroKo1TA4ACMsrZ-Mg-y0OoA7HLVZBQV1eRb5b1YSa7QLIEi5Dg+aqCujSgAmA1RbFexYBlX27lOgNGW6iiU4aU650FBFKnBhy3vLUm31J9nGnC+nNRtXW8GRr0FPrIAY4SW5gpu8sVow+rT+5tB1Uhr3pw0Rgv1wWxrQATk9XsgKeVxaMmaJYB1okHRnzYGldZnbQ6NoLG+bRirNbA44rruG7rARf3UFbOFNxc78u7qt77P7YD3p5j4q0pqvX9RVNlk3dVNXnHVtGXBomhNfVrytbcy11f9mwdasLz1KCz2RHAADYsNvHQHwDZ95VfAp3zggDhxwEcqInKc0xAudtTAUR8JA1clxA0tul1E8J0PC8BMtRtdUTEDCJ1dsK0fAVSIFci1XfbjUO-OMwFNVSAMVad4JYk1tNQ1dfXo09eKlT9UKE20QLEhcCMuNtiODXMlKMd8OLU4Uf3jMz7UY4D9I1D5WMwziYN3LCLI9LCbNiuzzy0IzT0ImTgxItzi05Hk70HScfI06UUMtQL3LVAz+Kw1dwvgmKFy8-c0KPET7Xs1qXTSlyuyy1D30g7L1IsCTvN0pjgrA1jJSs09Vxmid6t9Ab4Pi48sPsnUOsNQj7w7TLQ2y98R3yoa7y2tUyuYkKs3E6rIoa6LEL4j8Rqa1blqa9rHKmeNuqfXrT3fTaTsKrRpRSgLAL0prKp0O7mhwCHLUW87K0dBL4K+ySnOQv75IBicgdehjQbvYnSqh8aYeu+dpXNCKEcvEqFqe2yVvRtbEpwzn4K6vbXIOvrcoXZmXVOsARw+kmxqC6nJosRrjPu0X7Xq-zLVWlWXSx3mcbXPH+QU-lypyk15rF0mwFwpHDUuibQq0XCtcNGrHrBZ7UbVVbPaMHWmr52T9p7Q7hdq6jfMvdXbcp2XUNh5282Vt2dzXOKOZ9qA-dQqTcIN1YjdWE2gZt9lxclcnIZl8rZxp1jTPh5Lk6Qnm3vT9akox-29fSrsSLpXE6SpI4ZFgbZUlQUI2SUqlWhSNxCEYWkJ02ReAkZgrhzZRYXwDGe56wSBtjX05l9X3ZlUSUx-ACLYdn2Q5jkgAuCnQJkykSWp4AAawAMR2ABpZAJwxiwE-r-HYAA1YorhMT4ynrvPAs9KSgPQN-E+GtUjcGSOwE4xJTYD1Ph0deKDv5-zXlApyW9+5zE7AQnw8BAjIDfiSKI6Z3DrEpPALIOR0EFEQfvKAOQ1CMGvrwtUahuAYBERfAk84qToBpD0FeRC3AkPAWvQBJwC5GhGFUC+-A0ClGAJfPwgRVHJDSJkbIuQn5yVoXiDAqQv7MLmGw-hlJ0CpHgGIowmxMETzTPiQkrF5GKO0dULhagjFskgB8NI0N7Qr06PohhAROHcNSEos+qiwFkLUJop+uZIAAA99FXzMQkVQGhEBgFIJeQpu9cHLBMaIhIJgzB4FqfUuSWJnSQGSLI6Jp9Og3EIKg5gTTjEMlKLoOgppn5qlAZgr+RjCjQLcHgYesAxmNBqA0icKDUh4D2DIagaSL7KOPgkQ5xzTnnIWUYaoagTlnNWZc9eTyXn3KKSImQaRHjoGEawN+xjfCtKgAAClkawVAdBWi6DAAAKjAO0-AXTfQAEounQthUNB5gi7D-MBYwYFZTTE3wSFCwkMK4U6iRSi5Apg0V1Mxdi6luLQb4qpNwLIeBGCEDJeCoJeAYVPy3n0xA3AqCZKpokxgIyxnwAmRfaZJouVLO4CslV6zKmIGYK4HpgY6R2JxCAeYQA)
But sometimes not all of the colors are defined on the data objects.

**Comment by jheer** [comment]
Have you tried using a calculate transform?

```json
{
  "type": "calculate", "as": "property",
  "expr": "datum.property === undefined ? 0 : datum.property"
}
```

**Comment by csgibson** [comment]
There doesn't appear to be a calculate transform. I am assuming that it's the same as `formula`?
After poking around for a little bit it appears to answer all of my current use cases; so problem solved!

**Comment by jheer** [comment]
Ha ha, yes I meant `formula`. Calculate is the name used in Vega-Lite and I got my wires crossed...

Glad that fixed your problem!
