### ISSUE TITLE
Automatic date parsing (type inference) performs worse than JSON.parse

### ISSUE THREAD

**Issue by willium** [vega/vega#1743]
I've tested with many of the datasets in vega-datasets, and also stubbed out some fake date-like data. The follow is the results when tested on [my date-like data](https://github.com/vega/vega/files/3026108/fake_date_data.zip)

### using vega-read
```
const data1 = vega.read(loaded, {type: "json", parse: "auto"})
console.log(vega.inferTypes(data1, Object.keys(data1[0])))
```
prints 
> {date1: "number", date2: "string", date3: "number", date4: "integer", date5: "string"}

### using JSON.parse
```
const data2 = JSON.parse(loaded)
console.log("inferTypes", vega.inferTypes(data2, Object.keys(data2[0])))
```
prints 
> {date1: "date", date2: "string", date3: "date", date4: "integer", date5: "string"}

---
I think this might be a bug in `vega.read` 

Why?
I assumed it has something to do with type inference, but I now am not so sure. I tried:
1. using datalib's `inferAll` instead of `vega.inferTypes` but got the same results
2. explicitly specified the types instead of using `parse: "auto"` and got the same results

**Comment by jheer** [comment]
I need to look closer, but keep in mind we can use time stamps to represent dates *post parse*. Those should work as valid input to all downstream date methods inside Vega. (If not, that’s a bug.)

That may be why you’re seeing number where you expect date? We make no guarantee on the output of the infer types method *after* you’ve already done a proper inference-based read of the data.

**Comment by willium** [comment]
Interesting! That might be the issue here.

As you know, Voyager needs to map from the primitive data types to Vega-Lite types. I spoke with Dom briefly about this, but there are some functions/features missing in vega-loader and vega-statistics that are in datalib and are used by CompassQL and Voyager. If/when we do plan to stop using datalib in favor of other vega-* libraries in those places, would we need to add some of those summary stats and potentially the ability to do this kind of post-parse inference?

**Comment by jheer** [comment]
I don't use datalib at all in Vega 3 onwards. You'd have to ask others about usage in the tools they maintain. In the worst case, within a specific application one could perform initial data loading separately, perform whatever analysis is needed, then pass it to Vega.

**Comment by jheer** [comment]
> \> vega.toDate('2010-01-01')
> 1262304000000
