### ISSUE TITLE
Point scale does not sort after data change

### ISSUE THREAD

**Issue by csgibson** [vega/vega#1756]
I have a simple line chart using a point scale on the x axis that does not work as expected when the data is changed. My application allows data to be hidden and restored and the chart responds to these changes. If data from the center of the chart is hidden, then the data is restored it does not return in the original place. Instead it is added to the end, even though the data is sorted.

```json
{
  "name": "xScale",
  "type": "point",
  "range": "width",
  "domain": {
    "data": "data",
    "field": "label"
  }
}
...
{
  "name": "xAxis",
  "orient": "bottom",
  "offset": 10,
  "grid": "true"
}
```
```js
// this is controller
let oldData = this.view.data('data')
let newData = this.model.getBins();

this.view.change('data', vega.changeset().insert(newData).remove(oldData));
```

**Comment by jheer** [comment]
The sort order of the underlying data implies no guarantees for the scale domain sort order, particularly when adding/removing data from consideration. Use the `sort` property of the scale domain itself to ensure the scale domain is ordered the way you want. For more, see https://vega.github.io/vega/docs/scales/#domain
