### ISSUE TITLE
Corner radius should be less than mark span

### ISSUE THREAD

**Issue by marcprux** [vega/vega#1768]
When the `cornerRadius` of a bar exceeds half the span from the scaled data, effects like this result:

![Exported](https://user-images.githubusercontent.com/659086/56388841-0c6f9880-61f6-11e9-9dbd-94da591eb31c.png)

This is odd-looking. The `cornerRadius` should be pegged at runtime to be one half the span of the mark so the mark's corner curve doesn't invert.

The image above was generated from the following vega-lite spec:

```json
{
  "$schema" : "https://vega.github.io/schema/vega-lite/v3.json",
  "autosize" : {
    "contains" : "padding",
    "resize" : true,
    "type" : "fit"
  },
  "data" : {
    "url" : "data/seattle-weather.csv"
  },
  "encoding" : {
    "color" : {
      "field" : "weather",
      "legend" : {
        "title" : "Weather type"
      },
      "scale" : {
        "domain" : [
          "sun",
          "fog",
          "drizzle",
          "rain",
          "snow"
        ],
        "range" : [
          "#e7ba52",
          "#c7c7c7",
          "#aec7e8",
          "#1f77b4",
          "#9467bd"
        ]
      },
      "type" : "nominal"
    },
    "x" : {
      "axis" : {
        "title" : "Month of the year"
      },
      "field" : "date",
      "timeUnit" : "month",
      "type" : "ordinal"
    },
    "y" : {
      "aggregate" : "count",
      "type" : "quantitative"
    }
  },
  "height" : 449.5,
  "mark" : {
    "cornerRadius" : 24,
    "size" : 58,
    "type" : "bar"
  },
  "width" : 937
}
```

**Comment by jheer** [comment]
Thanks for filing the issue! Here is the relevant file: https://github.com/vega/vega/blob/master/packages/vega-scenegraph/src/path/rectangle.js

The fix for this issue should be well-contained to this single file of rectangle-rendering code, and so is a nice candidate for an external PR. Contributions welcome!

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega/pull/2127
