### ISSUE TITLE
Map view fails if GeoJSON transform is passed a `null` feature value.

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega#1770]
When linking a data source to a geo data source with lookup, we have two choices. Either make the geo data the primary data source and lookup the secondary attribute data; or make the attribute data primary and lookup the geo data.

When the geo data are primary and not all secondary data match, only those matched are encoded, which is expected and desired behaviour:

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "url": "https://vega.github.io/vega-lite/data/us-10m.json",
    "format": {"type": "topojson", "feature": "states"}
  },
  "projection": {"type": "albersUsa"},
  "transform": [
    {
      "lookup": "id",
      "from": {
        "data": {
          "values": [
            {"attId": 53, "att": "Washington"},
            {"attId": 12, "att": "Florida"}
          ]
        },
        "key": "attId",
        "fields": ["att"]
      }
    }
  ],
  "encoding": {"color": {"field": "att", "type": "nominal"}},
  "mark": "geoshape"
}
```
<img width="306" alt="primaryGeo" src="https://user-images.githubusercontent.com/1846999/56424934-1652d380-62aa-11e9-8e94-1b3b617894d7.png">

If the attribute data are made primary, only the matched attributes are shown, which again is desired and expected behaviour:

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "values": [
      {"attId": 12, "att": "Florida"},
      {"attId": 53, "att": "Washington"}
    ]
  },
  "projection": {"type": "albersUsa"},
  "transform": [
    {
      "lookup": "attId",
      "from": {
        "data": {
          "url": "https://vega.github.io/vega-lite/data/us-10m.json",
          "format": {"type": "topojson", "feature": "states"}
        },
        "key": "id"
      },
      "as": "geo"
    }
  ],
  "encoding": {
    "color": {"field": "att", "type": "nominal"},
    "shape": {"field": "geo", "type": "geojson"}
  },
  "mark": "geoshape"
}
```
<img width="303" alt="primaryAtt" src="https://user-images.githubusercontent.com/1846999/56425032-8c573a80-62aa-11e9-826d-772648ed95be.png">

However, in this attribute-as-primary spec, if one of the attributes is not found, then none of the map features is shown (line 7):

```javascript
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "values": [
      {"attId": 12, "att": "Florida"},
      {"attId": 53, "att": "Washington"},
      {"attId": 999, "att": "Dummy attribute"}
    ]
  },
  "projection": {"type": "albersUsa"},
  "transform": [
    {
      "lookup": "attId",
      "from": {
        "data": {
          "url": "https://vega.github.io/vega-lite/data/us-10m.json",
          "format": {"type": "topojson", "feature": "states"}
        },
        "key": "id"
      },
      "as": "geo"
    }
  ],
  "encoding": {
    "color": {"field": "att", "type": "nominal"},
    "shape": {"field": "geo", "type": "geojson"}
  },
  "mark": "geoshape"
}
```

This seems like a bug to me. I would expect it to show at least the matched geoshapes rather than nothing at all. It is problematic because it is not always obvious what the complete set of feature ids/properties are in a topojson file, so it can be quite easy to include a non-matching attribute.

**Comment by domoritz** [comment]
Ahh, I see. Thanks for moving the issue.

**Comment by jheer** [comment]
Fixed in #1773

**Comment by mattijn** [comment]
Did this land already in Vega-Lite? 
For me it is still giving an `[Error] null is not an object (evaluating 'n[r].geometry')` on the spec in question of Jo.

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoNZgCSytAEYATEtNoQAMUFsATjVUgAvgpPYLNABWAGZ7bEcAdSQIGBpZMkw5Hz8QU0DUAE5s8MxHABEGBAQATwACUw8mBkw4HwBdXxAcNzZJOChMdnlNEEwSnDr0HSY4NwgAVQgUJsw3JFkIADN3BCNQVzYAawYcR3TLJSXWtd7VdTRQBjdBRyxcfCJSCmo6RhZ2XgohEQJzpAIDAg-CsAAYEFIZPIjqs1Jc+gMhn02Dg2lDFCAlnA1NckRB1LUDN4mls4CVHJ4UmkDOgyHA2A0lHBZFA2Mp4mR4azXG54UsaHBBJZhhElP1Bo5ZGwEPEdFTYkgJb1+YLhSA6QyxYjHBrpMliUpkG4tjr6QqJd4gA)

<img width="866" alt="image" src="https://user-images.githubusercontent.com/5186265/109026866-7f82a980-76c0-11eb-868f-81114a3fcba1.png">

**Comment by domoritz** [comment]
Vega-Lite does not run the visualization, only Vega does. I am making a new release of the editor with the latest versions now.

**Comment by mattijn** [comment]
Ah v5 fixed it. 
<img width="866" alt="image" src="https://user-images.githubusercontent.com/5186265/109028353-fec4ad00-76c1-11eb-8ed1-c2c178ded1fc.png">
Congrats!
