### ISSUE TITLE
Time Axis Abbreviations

### ISSUE THREAD

**Issue by alexej-d** [vega/vega#178]
Is there a built in method to use D3's abbreviated time formats like "Jan", "Feb", "Mar" and so on for the axes?

**Comment by dazzaji** [comment]
Wondering if this has been addressed?  Looking at doing something similar... Thanks.

**Comment by arvind** [comment]
Axes for `time` scales should now support [d3.time.format](https://github.com/mbostock/d3/wiki/Time-Formatting) specifiers. Please re-open the issue if you run into any issues.

**Comment by ronakrrb** [comment]
Can we also use d3.time.format.multi specifiers?
