### ISSUE TITLE
Extend title, add subtitle and caption support.

### ISSUE THREAD

**Issue by jheer** [vega/vega#1781]
Common feature requests around titles and captions include:
- Subtitle in addition to title text.
- Caption or source line(s), typically placed at the bottom of the chart.
- Multi-line text (Perhaps using an array of strings? Not clear how to handle signals, though.)

See also #1759.

**Comment by roying** [comment]
Hi Jeff, 
How about extending Vega to output html (text and signal values) to DOM elements similar to signal binding.

For example, we can define style and DOM elements as:

```
<style>
.chart-overall-container{
	background-color: whitesmoke;
	width: 600px;
	padding: 10px;
	font-family: Helvetica, sans-serif;
}
.chart-title {
	text-align: center;
	font-size: 24px;
}
.chart-subtitle {
	text-align: center;
	font-size: 20px;
}
.chart-note {
	font-size: 12px;
}
.chart-source {
	font-size: 14px;
}
.chart-visual {
	background-color: white;
}
</style>
  
<div id="chart_01" class="chart-overall-container">
	<div id="chart_header_title" class="chart-title"></div>
	<div id="chart_header_subtitle" class="chart-subtitle"></div>
	<div id="chart_vis" class="chart-visual" ></div>
	<div id="chart_footer_note_1" class="chart-note"></div>
	<div id="chart_footer_note_2" class="chart-note"></div>
	<div id="chart_footer_source" class="chart-source"></div>
</div>
```
For the Falkensee example (https://vega.github.io/vega/examples/falkensee-population/), suppose Vega supports "html" in spec:

```
"html": [
		{	"element": "#chart_header_title",
			"text": "Population of Falkensee",
		},
		{	"element": "#chart_header_subtitle",
			"text": {"signal": "'from ' + years[0] + ' to ' + years[1]"}
		},
		
		
		{	"element": "#chart_footer_note_1",
			"text": "Area in each year,[5][6] since 2011 based on "
		},
		{	"element": "#chart_footer_note_1",
			"text": "Census",
			"href": "https://en.wikipedia.org/wiki/2011_European_Union_census",
			"newWindow": true
		},
		{	"element": "#chart_footer_note_1",
			"text": " from 2011"
		},
		
		
		{	"element": "#chart_footer_note_2",
			"text": "Detailed data sources are to be found in the Wikimedia Commons."
			"fontStyle": "italic",
		},
		
		
		{	"element": "#chart_footer_source",
			"text": "Source:",
			"fontWeight": "bold"
		}
		{	"element": "#chart_footer_source",
			"text": {"signal": "'Wikipedia'"},
			"href": {"signal": "'https://en.wikipedia.org/wiki/Falkensee'"},
			"newWindow": true
		}
	],  

```
then the result in DOM would be:

```
  <div id="chart_01" class="chart-overall-container">
	<div id="chart_header_title" class="chart-title">
	
		Population of Falkensee
	
	</div>
	<div id="chart_header_subtitle" class="chart-subtitle">
	
		from 1875 to 2014
	
	</div>
	
	<div id="chart_vis" class="chart-visual" >
		
		<!-- chart visual -->
		
	</div>
	
	<div id="chart_footer_note_1" class="chart-note">
	
		Area in each year,[5][6] since 2011 based on <a target="_blank" href="https://en.wikipedia.org/wiki/2011_European_Union_census">Census</a> from 2011
		
	</div>
	<div id="chart_footer_note_2" class="chart-note">
	
		<i>Detailed data sources are to be found in the Wikimedia Commons.</i>
	
	</div>
	<div id="chart_footer_source" class="chart-source">
	
		<b>Source:</b> <a target="_blank" href="https://en.wikipedia.org/wiki/Falkensee">Wikipedia</a>
	
	</div>
  </div>
```
and the rendered chart would appear as:
![vega_falkensee_example_with_header_footer_html](https://user-images.githubusercontent.com/37225856/56751981-42140480-6755-11e9-8a2b-5c32bc44420f.png)


Vega currently supports generating html "input" with signal binding: https://vega.github.io/vega/docs/signals/#bind

The proposal here is to extend this functionality by allowing html to be generated in specified DOM elements.

Thanks, Roy

**Comment by g3o2** [comment]
For what's it's worth, I'll reference #782 here.

**Comment by palewire** [comment]
IMHO, here are the extra metadata elements that Vega should support:

**Subtitle**: A sentence or two below the headline but above the plot that describes the chart at greater length.
**Footnote**: A small note below the chart, but above the source line, that describes any caveats with the data.
**Source**: A small note in the bottom left that lists data sources.
**Attribution**: A small note in the lower right, even with the source line, that credits the creator.

**Comment by jheer** [comment]
Thanks @roying for the ideas. These are useful ideas for a browser environment, but I feel they lie just outside the intended scope of Vega. For example, one could imagine writing another library that utilizes Vega but adds surrounding HTML elements. On the other hand, the approach doesn't fit with some of our other use cases, such as server-side generation of static PNG, SVG, or PDF documents.

Thanks also @palewire for the suggestions. We will take these into consideration as we plot out our next moves! (No pun intended.)

**Comment by g3o2** [comment]
> one could imagine writing another library that utilizes Vega but adds surrounding HTML elements

wouldn't this be a feature for vega-embed?

**Comment by domoritz** [comment]
This could be in embed but I'd rather keep it lean.

**Comment by kanitw** [comment]
This is another ask for subtitle workaround (https://sg-links.stackoverflow.email/wf/click?upn=pDzA4vSaPmKy14MynsLvnYWRZSfuHQ1lxRE0-2FGicu5vhg37G-2BHGVI8C8lzlIs5XWoilPuvWkiaQMqo86QW4NfmDq3e1zqff9BWK7BtICNw5UvXn2qjIHhzLy615qLAjoPFn-2FBB-2FQZuxw2InQ3CPQTApy-2F3bfyndWnklHD75zwC9g37ujfYJo-2FG8MxyZX3OpU_4-2BtY5N1pMU5r9tK6dNyAMVcVhKS5D8QeRwTYV9ouLeYvUVsRBB6TMG9DU27lHYjrGt6at63UcjBl6YIbyb6ieaq2gqEv2-2F3rehqZwlLScBFdo-2BSil-2BR-2B3WR5Mgak-2Figcp5DuT4k-2FYhy-2BHyDxEIcub8UTwVwhrxpuknhaja9-2Fx4Xtr9cUVdgEHppy9VwTWEc8v-2BkBXqfjhR7oFEsCnmSej2lPjUwE91cYw6NW4RixmIQ-3D).

**Comment by kanitw** [comment]
I wonder if we can just support title to be an array with style support.

So that if there are two titles on the top, they are stacked (and one of them can serve as a subtitle.

**Comment by palewire** [comment]
I defer to you guys on the proper solution, but I can ensure you that a subtitle, sometimes known as the chatter or deck in newsroom speak, is routine in journalism and included in almost every chart. To me, it's common enough that justifies and always-available, but optional, attribute.

**Comment by jheer** [comment]
FYI I agree that we should have subtitle support. I'd like to prioritize this for an upcoming minor release, most likely v5.6.
