### ISSUE TITLE
Combine `formula` with `facet`

### ISSUE THREAD

**Issue by sampsyo** [vega/vega#180]
It's currently impossible to apply a `formula` transform to the output of a `facet` transform (or, in my case, the subsequent output of a `stack` transform). This is because the implementation of `formula` tries to iterate over the data using `forEach` (via `vg.data.mapper`), which only works for arrays, whereas the output of a `facet` is an object.

This set of transforms:

    "transforms": [
      {"type": "facet", "keys": ["data.something"]},
      {"type": "formula", "field": "x", "expr": "1"}
    ]

leads to an error like:

    vega.js:2720
        data.forEach(func);
             ^
    TypeError: Object #<Object> has no method 'forEach'

It would be incredibly useful to be able to apply formulas to the contents of the faceted data.

**Comment by arvind** [comment]
With Vega 2.0, `facet` can now take an optional `transform` property -- an array of transforms that are applied to the data values within each facet. Other transforms can also *follow* a `facet` and operate on data values that represent each facet. See [the documentation](https://github.com/vega/vega/wiki/Data-Transforms#-facet) for more information.
