### ISSUE TITLE
Rename GradientLinear/Radial to Linear/RadialGradient in vega-typings?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1807]
We will likely import this to Vega-Lite.  Thus, it will show up in the schema and Altair.

So Linear/RadialGradient might be a more natural name?

**Comment by domoritz** [comment]
Note that we also call it in that order in the schema: https://github.com/vega/vega/blob/235572cece28d80efae3866d40821151279e48e5/packages/vega-scenegraph/schema.js#L122. I think the typings and schema should be consistent.

**Comment by jheer** [comment]
PR?

**Comment by jheer** [comment]
Fixed in #1884.
