### ISSUE TITLE
Can I fix the X-axis at the bottom. 

### ISSUE THREAD

**Issue by vikkya** [vega/vega#1808]
Hi,

Can I fix x-axis at the bottom i.e. if my svg height is 500 and I have 100 bars and I want overflow-x: scroll kind of property on y-axis.([example](http://bl.ocks.org/lmatteis/895a134f490626b0e62796e92a06b9c1)) 

Is it possible in vega axes properties?

I tried with CSS by adding overflow-y: scroll on y -axis g element and position: fixed for x-axis g element but nothing worked.
Need some help understanding it how can it be done.

Thanks

**Comment by jheer** [comment]
Hi, GitHub issues are meant for managing bug reports and feature requests, not for usage questions. For those, please use our Slack channels, StackOverflow, or Google Group.

But to answer your question, I don't think what you're requesting can be done from a single Vega specification. You could create two separate views (one for a chart, one for an axis) and then compose them using CSS to get the desired scroll behavior.
