### ISSUE TITLE
Minus sign instead of hyphen for negative numbers

### ISSUE THREAD

**Issue by kirkpsmith** [vega/vega#1826]
When displaying negative numbers, use a minus sign `−` (unicode 2212) instead of a hyphen `-`. There could be an option (like this one in [matplotlib](https://matplotlib.org/gallery/api/unicode_minus.html)) to specify either option (but defaulting to the minus sign would be optimal).

In IDLE, you can see the difference between a true minus sign and a hyphen with this:
`print(u'f\u2212f\nf\u002Df')`
or
`print(u'f\u2212f\nf-f')`

Reference: [Unicode for "hyphens"](9jkorpela.fi/dashes.html)

**Comment by jheer** [comment]
Thanks for the issue! Vega uses [d3-format](https://github.com/d3/d3-format) to perform number formatting. While Vega allows customization of the [format locale definition](https://vega.github.io/vega/docs/api/locale/#formatLocale), unfortunately, I don't think that d3-format supports customization of the minus sign character at this point in time.

**Comment by kirkpsmith** [comment]
Ah gotcha. Should this be an issue in d3-format then?

**Comment by domoritz** [comment]
@kirkpsmith I'm sorry that we lead you from Altair to Vega-Lite to Vega to D3 here but this feature request really trickles down. At least I don't think we will send you to the browser vendor. Thank you for your persistence.

**Comment by kirkpsmith** [comment]
Haha no worries, I'll open the request there instead!

**Comment by dankrusi** [comment]
Hi @kirkpsmith, this made it's way into d3 right? Can you provide a link to the issue? Kind regards

**Comment by tuner** [comment]
@dankrusi, this one https://github.com/d3/d3-format/issues/62 ?

Stumbled upon that issue when my minus signs (hyphens actually) broke when using an ASCII-only font...
