### ISSUE TITLE
Clipping to viewport should exclude clipped regions from total size

### ISSUE THREAD

**Issue by marcprux** [vega/vega#1829]
The following spec shows unclipped viewport content overflowing the viewport and expanding the bounds of the overall canvas:

![image](https://user-images.githubusercontent.com/659086/52544691-464c9a80-2d80-11e9-95d2-0b352f427ec0.png)

```json
{
  "mark": {
    "type": "text",
    "fontSize" : 100
  },
  "width" : 200,
  "height" : 200,
  "config" : {
    "background": "lightgreen",
    "view" : {
      "clip" : false,
      "fill": "lightblue"
    }
  },
  "data" : {
    "values" : [["ABCDE"]]
  },
  "encoding" : {
    "text" : {
      "field" : "0"
    }
  }
}
```

However, when you set clip to "true", the overall rendered dimensions remain the same, just the overflow contents are hidden:

![image](https://user-images.githubusercontent.com/659086/52544706-7431df00-2d80-11e9-8cd2-58165b75b98e.png)

What one would expect to happen is that the region that is clipped out of the viewport would no longer contribute to the overall size calculation of the canvas, like this:

![image](https://user-images.githubusercontent.com/659086/52544716-7f850a80-2d80-11e9-8b0a-ac1d7d5f5611.png)

**Comment by kanitw** [comment]
If that's the case, let's move this to Vega for now then.

**Comment by jheer** [comment]
If I add `clip: true` to the Vega code for the generated text mark, the viewport is clipped as desired.

In contrast, Vega-Lite is setting `clip: true` as a config style property for the top-level group mark. This is equivalent to setting the `clip` encoding channel for that group mark, which involves a different processing pipeline. The group content is then properly clipped at the scenegraph level, but the view layout logic is not properly considering the group-level clip property, hence the layout weirdness. This is a Vega bug... will fix!

However, it's important to keep in mind what you want to achieve. Setting `clip` as an encoding channel for a group indicates that *all* group content should be clipped, including axes, legends, and titles. If you only want to clip specific mark items within a group (not *all* group content) then the output Vega should use the mark-level (not group-mark encoding / style level) `clip` property.

**Comment by domoritz** [comment]
Just to clarify whether there is an action item for Vega-Lite here. The view-level  clipping in the example is manually set in the Vega-Lite spec. Vega-Lite generates correct clipping of only marks for example in our [overview+detail example](http://0.0.0.0:8080/#/examples/vega-lite/interactive_overview_detail). As I understand it, Vega-Lite doesn't need to change.

**Comment by jheer** [comment]
Sounds good to me. Just clarifying above to make sure everyone's on the same page!
