### ISSUE TITLE
Update d3-time-format

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1830]
It would be nice to have https://github.com/d3/d3-time-format/pull/58 (see https://github.com/d3/d3-time-format/issues/56) but the library is not maintained anymore so it might make sense to fork it or copy the relevant code into Vega instead. 

Another alternative would be to consider a wrapper for native time formatting with escape hatches for non-standard features like quarter.

**Comment by kanitw** [comment]
This would be useful for supporting an initial for month (J F M A M ...) in Vega-Lite as well.  (Currently I cheat by [adding `[0]` to the encoding block](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQA4t27UANsgDksMLDzd4AazCFN8ZGG5V1YHamR0FJUh0VjtYRgAvZGwoQnRlQIhIOOVlRhlqGNFFJIB3RmUWGIAmAAZSnNxkRmp8EvLKyFsAT3MYyDdTU0SVdDxMHABtJQhQCHGoGXQ-dulWdTcAfVKeich57v1lPpFbewdYOnhYClXxyAAzbnUMPBjgSDxmwmj9Y9P5WPR1WFewB+2eD+kEB0QAvp8QchTIxUMxkOp2vJIBCRuc8Op0DJYFcbjFhhMJg8ni92hdGKYgYjIcgAB4udqA1ioOiwZqodjcUwAXl5FgMAHkBQYLCjKoT-miJY9nsDcahWKZMOKJVB0LB2qhZCxFqCztK6Qytn1kL5kAAKCpgLUyFjmpmoQYAHRBJpdAF0AJSfACMnytAf9nsgUvGqNVkojSRJcuuCqV+sJwQ1+htOtBi2QMgSKoN9MRxqBZstnzTiHtfWZztdQI9nrAAGowH7m-622AA8HQxBw6qxlGZaT9OhqNR1MIgYm1mPuKxCOxmvjIGXdSaFMvtYhV0DM9nIO7c0nuMQl34sfvD2tydDlCmwINkq5ogfu+d1afkFjFi5GG596-ewlfsI0HOUKSpKdzkNAtejwKsXRXUEPTAABCXkwBkRVTDAAAyHDUMYWAADl0CIis4MdBDN23ZA6xDCMwVDd00UYiAXySDB1AOfE0WA84phmVNvm4w9QPacd4DuUSWjaIZIHYb4L1DS51G4VB7hrAYoDmBZkGWMVlKzeBuFUe5X3WQg9RwPjpXJLoNIodBTFYYEAGIABZ4AAdgADnQHyDKjKA7C5HRCDMoKknCagpk2KBgBdUEwHNMtPRdHAzQAMTjPpyPgjdbS3JCLzACwAFJ2Asb0wBdABZT8ZA8C5nCfdKwHlXKHWrM8ZG-VqSpdF1PTBeio0A1VIFpDSECc4Epsha9TASVNqL1SFuAuC5fjuHBinG6VaWKab4Fm9p5qgRblqgRCTV3HMoA2rbTRiABaPbL3ORdrKaE7ZKgRcFsYG9NQavrf3BD6kmaI7vpmv7IABqBHOcv5SlY1V0YmTGwHR9jtN+tQeKJZSBLmxMxP0M1yeUNT0HSDTLrvQYAR2WZZ10-TAeBlbCposUWf6Nn5iWFYuaWzVVturMEjBd19qgTEMj+QYrQeaLYvafJCkQFE8bWFI0gyLIWJVGzJmmYEAeUmN2hhGRP2pZSaYwenvsBLSmnZkWFAuoHxdTUGfz-eXIEV6hlbVmoNf0FAajqCEOz1-jwZiDEXNEqJVNT9QXJYpQ8eCWlCaGXjlLhsnROuIHbXaTkCDU8mxwKGILic35RJ0PB4aSlLN2DUSlXYaEAEEYRi23kAuKTlMH6FMuc2AdYynPkAH9Ah9MAUvCVcLl-Tmf1+hAAhWc9z31fDJkYzTOs8zZ9MO8zbWOcrP+R46R2t-1ac9ospyvA8osmRunUqFUqoq3dCibGWNQwhwiOkVQU0cA+hNqXaU5czrkyrlmT+8luD13UqJJuygADKBN2hW2lMQ7O+9pTOzpnodqbcL7SnvneVuD8WFJgwLSAAorSIENccAVGUnCGQ-DBGfxEdKHQjh2HMIzggukMRSioOJug8h+hKFHk0DgieU9G6aCuhw9u1tmDw3qliJqLUU5rw3lvBEO8aFcLWLIhwABhU+n9I4xR-m8aophzSx1qHgUg7lSjBjgUopBzY1HjDNj9U6WisG6KEVAcwBiiFGLIUkqA81lLUPPh3X8HivHTSjn4qAbgKRBOqCEsJETApJnoa7JhnC7HQnke00R6A+ECL0cI0SYiJEDI7MUuRLcFHKXgdmZRwi85sRAGCIAA).)

![image](https://user-images.githubusercontent.com/111269/59655763-40146380-9150-11e9-8eae-5eeedd543762.png)

**Comment by mbostock** [comment]
I’ve added support for a quarter directive.

**Comment by domoritz** [comment]
Thank you @mbostock!

**Comment by domoritz** [comment]
Vega now has an updated version of d3-time-format.
