### ISSUE TITLE
[Bug] font size slider does not automatically update the graph

### ISSUE THREAD

**Issue by 111andre111** [vega/vega#1834]
I have changed the example from the tree:
https://vega.github.io/vega/examples/tree-layout/
https://vega.github.io/editor/#/examples/vega/tree-layout

with following customer changes in comparison to original
```
line 6: inserted
  "autosize": {"type": "fit", "contains": "padding"},
```
then
```
after line 7 : inserted
     {
      "name": "fontsize",
      "value": 8,
      "bind": {"input": "range",
              "min": 5,
              "max": 45
      }
    },
```
apply update
```
moved line 99
          "fontSize": {"value": 9},
to line in update section inserted after line 102:
          "fontSize": {"signal": "fontsize"},
```

**Comment by 111andre111** [comment]
The problem is at the moment, that if I change the sliders here, the layout does not update based on the font size slider changes.

**Comment by domoritz** [comment]
Can you share a working example with the [Vega-Editor](https://vega.github.io/editor/)?

**Comment by 111andre111** [comment]
Sure, n.p.
Here we go:
https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwANgAMuxREgpG1fFoCMeg0siF0atYxnUtow1HSs83WIwBeyFrAkHgAnoRBOJAAZswKUPCyeOjOsFp2Dk4ukAC+HrZ+1DLoADbpOADaShBgoLW1kCWoUVAxyX6BCjWNFGWsrQAcHg2Q7M5qwZDOhN4ZAE7oLkEjDWtGqM5uq+ujGAAeWgAsoj0QuT35SvVrTegtGaXo7MjlCZB9pQNaePMDO1BxjJJjgQjM5tEkMh4ABrdjcQ4XBpXBo3UbNVqQJ5hbhzeRQT7faJ4dRhbrrMYTKbgvALBw8d7cQgk2QVMCVUKk97wL6wPDIeaQAC6SNqKNqaMaGMezhh6XxH36mKc6GosjK5NuQJBdTOjRpGVgr2htIBRiZLJkbI5pWcK0SrHmVHeKrVJVKjPmLG4bo1Qr1ovOSiFilsanQKS01VReruD2J82QK1jjo90XDKVIMSeick0jkANCiyt7XmqCjeogkop4Uiht+EcYMTJZsaMOQZOi6k1uyg9kTMjwAGkOxl+8hB5BK2Bxetq7da5jfkme7tIC1vTqQkV3Y90Di5rO151WpVt6Zd9ETGZafk6pAdxroqoNIgwABaMAWfR5EPTozoNakAtlAhwKmoyDMog3KIIwpRqAOwrToGtT+siqzznGmK2jIcqrkY0iOvAS6JsmNbFrApbllU07AFAi4ZMuryyukM6tvOowMdEOEwvYmitua8yMBOtJXtwQn+MkGoCVAsCIOgdagg+F5PlAPHpChyJ6mhYrBqGBHwGUyDWj0mHSpC3ClOJ+H0RE2F2uggqFsW1CtNuULxlAGDUBgeSFmo3AYFsSkZpgCYrgqcSvDqkAQVBfmxoE8zcD8fzIJcekgLYGDzHhNExjWdljhG0GFjEyXUfeoUyrhGmFhOSQQcE06QKwhAZm5-59iVUxRfBxWaEeFJ8sl7ZTISmIAMTwDNeTIQGlwYbGXGyWEqDwh6ZUVVM1XhUEQ1QA13BNaCLUiQKzW9gRARuYqXytN+ugHaMI3cGNSkTRkk0xD9c29s9UBtR1l1XZAhxKX1MWIjJwG9cJ-XRGSANGHEpRpveCBGRkSRWU5bTwzFcWDfN6woUemEraEyD7KasblYFO0RmF9GkQlFJHSduq9pA52CqdV30dTon3pDGTSsjgKAcxMi3Z90SbI4pT7chrate1EadQLsTJAAyjdUyPuj2uDiebOg+DIsExk0NdbDENW4jZvc2oFvnsUqmxRGrCoHQSBwQhE5gAA-B+ADsYA4KHTtrmUF4GypRsZt7vuwfBA7B2AADkQk3pnEdZ0rMR4Jn0cUky6DwMwnYYwne4vOUGcWPnuh-bsmkzhlED+hcQA

**Comment by jheer** [comment]
First, you will want to set `"autosize": {"type": "fit", "contains": "padding", "resize": true}` if you want the overall chart dimensions to change with the layout.

Second, note that the tree layout itself is calculated separately from the font size. You may want to further modify the `tree` transform size property as needed when you adjust the font size.

Hope that helps!
