### ISSUE TITLE
"Infinity" values break quantitative scales

### ISSUE THREAD

**Issue by fedarko** [vega/vega#1835]
[Link to a small example spec in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7RiiJADujAy10AmAAwe7uZI2r47l4+kLB4AJ4ANjo4kPDIkZHG9gboeJg4ANpKEKAQ+VAy6KgxUNKsAE7xAPoeyQVQFOiRrMiwunkN9ojM7TjAkD14fWCZAxlQAJIyAGaWzOEKUOy6AIwAvvJg47oAzFuQKzgALOsAuus5+ZtX9jPcFRh4HaYV3ITIFRG6g710Q+1LgUbgVOgVIEUSj9UulavVweUqqVQtxKjU6j5wXgKugZLB7o9dNkurlbg1IBEPj85pE8J94STIMgAB6ECrQtKsVCZAA6kHQfLOYAAhABeUVgGSsRJgABkspFjFgADl0MqABQwrm8-mCgCUcoVWu5fPYgpF4sl0sihsVKrVms5JsO+sgZIgQIaZyunrOIQwFQA1iNifkwfkIcVkQHgwz7JTkbBwqh2NwkpiI2EoqVMqZuJZnn6yZAZm9UC8YRNIJW4SDycgZPBuAZSuHwaxCDDW+6I+90PAFi8mi1Sh46AB2OskqA0pL9SDD1o-bG42D6CoN55TxlhN6B1uheDNZFNyIPJYlxgJIyxTDbroU7hpvCMQgdHsI-xFOdQYB8gW6ASTyOng2r-oKWx8nyeqQS6gEPMBxo6makB+mAUGQHq6xutOHoZg+zIvAgx4-IRBxzNePx3vh5KLPOxHRD8izkVekQ3sskCel0XHXD6ShFvYDFtESVxtoUUakXGUAJj8kSWMg6DsjR1bcBglgVmkVY1hiM6sex-KccpOJWDm3jbKEX7ND8TguIgnECeSMiMPEujYq0ynaG8rkVK0PoZmJkZQrEzHFjJsRyTIClKcWBiqeg6nzpWHKwjpl6UbEKz3lAxnUDmAwaNQ34-Cg-iBJsYAeA54JOS5OBucgHmfNw3m+cC-nFpCJ5pueylhVADwWEVymxWpciJZpyXoHCLHpcoF7SF8LXIFlkA5SeaQ0A8ix8RADn8sywlZKJxZCZJykPFeMjPBl3AEKpUmQNQFTOIBzSwA1oXMIxt4PZE6DsAkABiLSwHZdU+R9D5-QDkQAPJUBUf1vuD7mffAgYAMKoldRGWT+cR+JE6o2SwpDHB4eqGcWmiWC2hE4KsfnHQ+p2xGRxYXZuPypnd5bKU9zgAMpHt9UAhQ+AvsfVvXOZj2PXeZBVFbE8SMETJOIGTFNUw+I3xWNYAzG9kPktDCQjEbkTvcpGDMgAosydI4zg3jFqglgO07Cuuw+L7oxbxsebTLK6B4TOgidIvIuL5Kc87UDRDMzz8897GW9bn14KLhy-f9CTw58SNLTL6NY6w8f5XjPyq0TJUBHgWuUytNMyHTazh2GkckcFD1xwrkCJ8nxaS8L3dQOzEup8XaNy+XCuV4VVkq4T6p1-gjc6+SesJYbgfFmbVuvVbJvgrbntcy7Nse47F8VSXsY4OnJ8Ri3bcuztYB7dEuWtyGzPkrubg+5q7dWipPQwl08AABkGzUFcPRKuKs-qoEIKvPw9ctgADZjhbE8NrFaSYUxpgACrhCpCrRgVRGIyyzsiTAykGxNhbO+acoRkypkPv0D8UAOxdhYbhO4asfwDEXMiFceJ1xcyyg+PsA5vjzlEaHCcPFuI9hUWAHivoQDrCAA) (generated from a Vega-Lite [spec here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCY6ARjoArWNwB2kADTgoAE3R5MOUBAiQK6Ma2SxsYM+YuJm903ucu3DgNqevCGBIEygASQ0AM0YNZgBPHSh2B0UAX11A52DQ6W0khwAWVIDnAF0SsGLndIDISO4AJww8B2DCBu5CZAa8BJxIVzxYOkH7KsqMqAwGgGsHSEJuGJbJyGQNeG59GOpW2oAPVrrGZDF9ecw8yF6u+YBHVnQNPGYjRipIGudIPsdj0-O-WSVxuyHuj2erxeHy+5kgmzEjSO0QBF0S1zit36Gm4qBi1k+emKqSAA), and based on the example spec used [here](https://github.com/vega/vega-lite/issues/4965)).

If one of the values for a quantitative scale is `"Infinity"`, Vega will interpret this as a numerical value. This results in the corresponding axis in the visualization losing ticks/labels, and the general display of the visualization getting kind of messed up. Here's a screenshot of this. Note that changing the lone `"Infinity"` value to something like `2` restores the display to its normal appearance.

_Top: current visualization, where the `x` axis (for field `a`) has been "broken" due to the presence of an Infinity value. Bottom: the same visualization, but with the Infinity changed to a 2._
![visualization (1)](https://user-images.githubusercontent.com/4177727/59314728-6ecf9d00-8c6b-11e9-8348-39c6b7155c4e.png)

![visualization (2)](https://user-images.githubusercontent.com/4177727/59314796-c968f900-8c6b-11e9-971e-b22be7c15681.png)

This problem is exacerbated when the scale being messed up is a colorscheme—if you add `,"color": {"field": "a", "type": "quantitative"}` to the `encoding` of the Vega-Lite spec above,  things get really broken (screenshot below).

![visualization](https://user-images.githubusercontent.com/4177727/59314670-33cd6980-8c6b-11e9-8be3-9d7972d918eb.png)

The way I see things, I think a reasonable way to handle this would just be filtering out non-finite values by default from quantitative scales? I'm not sure if that is a Vega or Vega-Lite decision to make, so I figured I would post this issue here initially.

**Comment by jheer** [comment]
Thanks for the issue! The current design does not strip infinite values from the scale domain calculation (though I agree that the result with the legend is particularly bad!). However, at minimum at least it is apparent that there is a problem with the chart.

If the scale domain calculation ignores infinite values, the scale domains are calculated without problems. However, the chart then subsequently breaks when trying to visualize infinite values (running an infinite value through a finite-domain scale produces an infinite pixel position, for example). In this case, canvas-based renderings don't show anything at all, as the layout calculation determines the chart should have an infinite width and/or height, and the browser simply fails to allocate the canvas.

So, I'm not yet certain what the best configuration should be for Vega. Our general philosophy has been to be transparent and minimize "magic" default behavior. I'm uncomfortable automatically removing / filtering data values entirely. That said, Vega-Lite, on the other hand, does perform null filtering. Perhaps those generated expressions should be updated to filter out non-finite values? (cc: @kanitw @domoritz)

**Comment by fedarko** [comment]
Thanks for the detailed response. I wasn't aware that "infinite" dimensions were used in that way—that's a cool solution! I can see how relying on users to do the filtering, or just doing non-finite-value filtering in Vega-Lite instead of Vega, might be a better way of doing things.

One (hopefully non-invasive) suggestion I have—maybe as a temporary fix, or maybe in general—would be generating a warning if a scale contains any non-finite values. When I first ran into this issue, it took me some time to diagnose `Infinity` values as the cause of the strange chart behavior; if a warning is raised saying something like `'x' scale contains non-finite values`, that should make things clearer for users on why things look odd.

In any case, thanks so much for your help and for your work on Vega/Vega-Lite! These tools have been super useful.

**Comment by domoritz** [comment]
I agree that it would make sense to filter out infinite values in Vega-Lite. Please open an issue and if you can a pull request.

**Comment by fedarko** [comment]
Created an issue (https://github.com/vega/vega-lite/issues/5325), thanks @domoritz. I'm going to close this issue since it seems like it's been superseded by that one.

**Comment by jheer** [comment]
Thanks again @fedarko. I think adding a Vega console warning if a calculated extent is non-finite is a great idea. Will add soon!
