### ISSUE TITLE
Vega sorts the data whenever sorting enabled or not (2.5.0)

### ISSUE THREAD

**Issue by shmutalov** [vega/vega#1836]
We are using Vega 2.5.0, and have an issue with sorting. When we set `sort: false` in domain, it always sorts the data.

- Open the old Vega editor, paste sample data then parse. Rendered chart must show values without applying ordering to data.
- Vega 2.5.0
- Sample data for [old Vega editor](https://vega.github.io/vega-editor) (2.x version) 
```json
{
  "width": 80,
  "height": 1,
  "padding": "auto",
  "data": [
    {
      "name": "column",
      "values": [
        {"member": "qwerty","index": 5},
        {"member": "5","index": 1},
        {"member": "12","index": 2},
        {"member": "11","index": 3}
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "ordinal",
      "domain": {"data": "column","field": "member", "sort": false},
      "range": "width"
    }
  ],
  "axes": [{"type": "x","scale": "x"}]
}
```

**Comment by jheer** [comment]
Thanks for the issue! There may be a bug here (@arvind would know better for the v2 code base). However, we stopped actively supporting v2 a few years ago, so I would encourage you to move to a more recent version if that is feasible.

**Comment by shmutalov** [comment]
@jheer Currently, we cannot migrate to a newer version because of lot of legacy code, maybe in the future. Thank you anyway.

We investigated that bug occurs when cells were built. Axis values created as javascript object properties, and if they are numbers, `object.keys` will always return sorted set.
