### ISSUE TITLE
display node name in the vega force directed layout

### ISSUE THREAD

**Issue by learncurve** [vega/vega#1850]
Hi,is there a way to display node name in the vega force directed layout? There are ways to do it in D3 force directed layout, but can not find a way to do it in Vega.

I am using the following text type under marks, it can fetch node name, but the position is always not correct,

    {
      "type": "text",
      "from": {"data": "node-data"},
      "encode": {
        "enter": {
          "text": {"field": "name"},
          "fontSize": {"value": 9},
          "text-anchor": "middle"
        },
        "update": {
          "x": {"signal": "cx"},
          "y": {"signal": "cy"} 
        }
      }
    }

thanks for help.

**Comment by jheer** [comment]
Hi! This is a usage question, but a bug, feature request, or related issue. I recommend using the Google Group or Slack to post usage questions.

You should be able to add a text label to a node. Either use a text mark and set the x, y coordinates using a force-directed layout (not from a global signal, as in your snippet), or use standard circular nodes and add a text label mark on top it (e.g., using [reactive geometry](https://vega.github.io/vega/docs/marks/#reactive-geometry)).
