### ISSUE TITLE
The pivot transform fails when a dataset is dynamically loaded

### ISSUE THREAD

**Issue by iaindillingham** [vega/vega#1851]
Consider [the following specification][1], which dynamically loads a dataset from a given URL:

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "signals": [
    {
      "name": "url",
      "bind": {
        "input": "select",
        "options": [
          "https://gist.githubusercontent.com/iaindillingham/f592ceee43b6a83d5614de5636be514e/raw/438d7b403c079c78cd6837ff633c18b33130105b/df1.csv",
          "https://gist.githubusercontent.com/iaindillingham/f592ceee43b6a83d5614de5636be514e/raw/438d7b403c079c78cd6837ff633c18b33130105b/df2.csv"
        ]
      },
      "value": "https://gist.githubusercontent.com/iaindillingham/f592ceee43b6a83d5614de5636be514e/raw/438d7b403c079c78cd6837ff633c18b33130105b/df1.csv"
    }
  ],
  "data": [
    {
      "name": "table",
      "format": {
        "type": "csv"
      },
      "url": {
        "signal": "url"
      },
      "transform": [
        {
          "type": "pivot",
          "field": "dimension",
          "value": "metric"
        }
      ]
    }
  ]
}
```

[Each of the datasets][2] have dimension and metric columns, but the values of each differ. Using the data viewer in the online editor, notice that when dynamically loading the second dataset, the `field` values of the first dataset are retained. As these values aren't present in the second dataset, the pivot transform fails.

[1]: https://vega.github.io/editor/#/gist/vega/iaindillingham/f592ceee43b6a83d5614de5636be514e/312e6954572d9a2d43f8f8096ce262f5e386c15f/pivot_bug.vg.json

[2]: https://gist.github.com/iaindillingham/f592ceee43b6a83d5614de5636be514e

**Comment by jheer** [comment]
Thanks! The Pivot transform needs to check if the input data stream has changed, and force a re-initialization of the internal aggregation state if so. Will fix soon.
