### ISSUE TITLE
The joinaggregate transform fails when a dataset is dynamically loaded

### ISSUE THREAD

**Issue by iaindillingham** [vega/vega#1852]
This is similar to #1851. Consider [the following specification][1], which dynamically loads a dataset from a given URL:

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "signals": [
    {
      "name": "url",
      "bind": {
        "input": "select",
        "options": [
          "https://gist.githubusercontent.com/iaindillingham/91225ed53e42a4cdc3c97f61c5ffe6b9/raw/468159226ee5b34e01e0fbf36f9b4f5d558636db/df1.csv",
          "https://gist.githubusercontent.com/iaindillingham/91225ed53e42a4cdc3c97f61c5ffe6b9/raw/468159226ee5b34e01e0fbf36f9b4f5d558636db/df2.csv"
        ]
      },
      "value": "https://gist.githubusercontent.com/iaindillingham/91225ed53e42a4cdc3c97f61c5ffe6b9/raw/468159226ee5b34e01e0fbf36f9b4f5d558636db/df1.csv"
    }
  ],
  "data": [
    {
      "name": "table",
      "format": {
        "type": "csv"
      },
      "url": {
        "signal": "url"
      },
      "transform": [
        {
          "type": "aggregate",
          "groupby": [
            "dimension"
          ],
          "fields": [
            "metric"
          ],
          "ops": [
            "sum"
          ]
        },
        {
          "type": "joinaggregate",
          "fields": [
            "sum_metric"
          ],
          "ops": [
            "sum"
          ]
        }
      ]
    }
  ]
}
```

Using the data viewer in the online editor, notice that the result of the `joinaggregate` transform -- which is in the `sum_sum_metric` column as I've retained the default column names throughout -- is correct. Now, dynamically load the second dataset. Notice that the result of the `joinaggregate` transform is incorrect: it seems that the previous result is carried over:

* Expected result for first dataset: 6
* Expected result for second dataset: 14

1. Result on page load: 6
1. Switch to second dataset: 20
1. Switch to first dataset: 26
1. Switch to second dataset: 40

Whilst I haven't determined whether the bug is related to the `joinaggregate` transform alone or the combination of the `aggregate` and the `joinaggregate` transforms, I feel that carrying over the previous result is a bug.

[1]: https://vega.github.io/editor/#/gist/vega/iaindillingham/91225ed53e42a4cdc3c97f61c5ffe6b9/13fdfe373ac769f9ccd4d2396b396bc2950cf27b/joinaggregate_bug.vg.json

**Comment by jheer** [comment]
Thanks! This is a somewhat subtle bug, in which the removed tuples output by the aggregate were changing, but the joinaggregate wasn't getting the necessary cue to re-initialize the state. Hence prior summation values weren't being decremented as they should. Will fix soon.
