### ISSUE TITLE
Allow for autosize: fit along one dimension only

### ISSUE THREAD

**Issue by willium** [vega/vega#1857]
See [this Vega-lite issue](https://github.com/vega/vega-lite/issues/5133) for the motivation, and [this spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAgmHbp1YJKbxgW6K9PV5Y1lGACeAWgroANqzXHXZ2QwAA9PHz9YOgUlSHRWPG5YRgAvZGwoADNmGIhIQnRlZUYZagzRRTyAd0ZlFgyAFgAGJsqoWDxXb3T9eGRvb1yVW0wcAG0lCFAIGagZdFQe9u5WdT6AfSah2chVwf1lEdJCbkJWb1tdSWk5Np3M7nUMPAzgSE7CJcgpWUgAXzuM3e6nQMlgDyeGTGbw+X2y3jwyHUCigyBChGRB1srFQdFcyFMYAAvESwAAmFpbP4AXUmYABdOmszmCy+hzw6E22yB0lWfQykF5a2QXMBeTwILBENQULpsyZzKBsIF6Go1HUwkR3MVkHVK0I7FcULi1HS1LFzMgp1gxtgOMg5rlluy-WUNvG+WQp26DotO3Q7rAY0FOPWn29ZqdED+TtpsxjEEdeWS1Hm3kDE3lkHmiwFrnWHWQhBRkC8viWFIZ8qd2dZApQjGo+G1UFYhHZXxMMjdBT6AAplNwMCU+wByVyjgCUdG6pRY8jATToAEYF0umqJJ2AAFRuAuI4t0hNgJNQDDqADWGcZNZzX3PV5b71cnwFGvgLwtgs6Po9JmRp73OoQ6vJA7KjMMHJclWlrIDI8DcKorxRq27a2EsCqKlkjADKBZZ+AKADEDTwAA7AAHOg5H-H6QIhKBCA+F89ELpALreMoAp2qgYZeoQPowVhUAhGSDHwExAosVA+FLE0glYZARo4G8jG-lARqsexnH6Kq6TyTqDZNi8ymCuJamKSWXbadY6h+Meir2TMjnHqeplMde1Y6neklPsq+jeCUBLIl+g7DnoYBvOBArgaK2GulxobhvxelfpKppQq0EWCo2aYCjUdSIP8gFAjIjD8jgEp+F+aTARklXIEegKYXk3n6BpNZ+VAVlPqF6AlMhQlgSMXErMKoooWxjDxTp6W0YKjzGVlpwJTKmlTRxApJQJTr6VAaUYd+RYMTlPh5vuR1-Lt+SFMUpQAJIyDISIZEuq41gURQlNQADyCTPTg66iEeSiuegIRqLKnmWqpzFPo8U0yItkDsNwBAgV+6q1BkmQ+LAyBfjoeDmScZwXDovxfhc7D9AAYr4sCFRVtn4zWVP9N9VDqBcxZM1VHVlReADCKyI8dqanb0yA4X2+UsKQzSTjRNYpCUqj0Tgy6NTeOowz5X7w3BSMo2jq01pjygAMpmV87U6ubdXMwTAvC6wosmSmuWS9LsuIPLTSK1dvX9TgOPpizOps+m2O4+HloYCEACiISIm7i5fqgJRJyni2tPz8CPiHMfVaraIvVrUM7LrbVw5ohsCt0mSfmbmjWaHeNO0TXy6U+kcc0i3MO3zOoq92pca8DiYgH8QA) demonstrating a failure case:
![image](https://user-images.githubusercontent.com/356976/60394781-3c80c500-9ade-11e9-8fa2-01ec2ebac3f1.png)

This is present in the latest version of Vega (5.4.0)

If this is not a straight forward thing to detect and fix without further user specification, I wonder if it might best to introduce more granular support for specifying the dimensions to fit, e.g.
```
"autosize": "fit-width" | "fit-height" | "fit-both"
```

**Comment by kanitw** [comment]
Oh there is "fit-x" / "fit-y" since 3.1 (but not when we first implement the fit behavior) --  forgot to check.
