### ISSUE TITLE
Feature Suggestion: color contrast check

### ISSUE THREAD

**Issue by benib** [vega/vega#1860]
# goal
It is possible to check the contrast value of colors to make sure labels are rendered with a good constrast ratio. This would improve accessibility of produced charts.

# reason to add this to vega
color/fill properties can be computed at runtime. Signals, other expressions, data, can influence the color. To ensure a minimum contrast ratio it is helpful to have the ability of applying different text colors depending on expression values so this can be defined in production rules of the marks.

This would allow to render labels in a chart like this either black or white, depending on the contrast with the color of the bars.
<img width="325" alt="Screenshot 2019-07-03 at 13 28 01" src="https://user-images.githubusercontent.com/821875/60588133-6bc15b80-9d96-11e9-85c0-394bd4637fd9.png">

# possible solutions
1. add a dependency to https://github.com/gka/chroma.js to vega-functions and use it's contrast function (with the possibility to expose more of chroma.js API if there is a need)
2. implement lumincance/contrast functions directly in vega-functions based on https://en.wikipedia.org/wiki/Rec._709 by converting the colors to rgb using d3-color and then computing the luminance using the coefficients described in this standard.

# example of usage
```
fill: [
  {
    "test": "contrast('black', scale('colorScale', datum.value)) > 4.5",
    "value": "black"
  },
  {
    "value": "white"
  }
},
```

I am happy to work on either solution and provide a PR if you think the addition of luminance/contrast functions are useful and something you would merge into vega.

**Comment by domoritz** [comment]
You can actually prototype this by [adding expression functions at runtime](https://vega.github.io/vega/docs/api/extensibility/#expressions). I do think that a simple contrast formula would be nice. https://danielleszafir.com/ has done some amazing work on this issue recently and I think we should build on it if we want to add a formula.

**Comment by benib** [comment]
I am doing this by adding an expression function according to solution 2 just now. It works great so far. I definitely have to check out Danielles work on this and would love to have a solution to this in core vega instead of depending on runtime added expression functions.

**Comment by domoritz** [comment]
@connorgr has written some JS libraries for color comparison based on her work that we could leverage.

**Comment by jheer** [comment]
Thanks! If there is a useful -- and ideally relatively simple! -- function to add, I'd be happy to review it. I'm wary of adding new third-party dependencies that might bloat the (already large) Vega footprint.

As @domoritz mentions, one can always add functionality to Vega for custom deployments using the extensibility API. This would be my preference as a default starting point, as ultimately we can't add every extension one might request.

**Comment by benib** [comment]
Closing this as the functionality is implemented and merged with https://github.com/vega/vega/pull/2004.
