### ISSUE TITLE
How to filter children nodes after `stratify`?

### ISSUE THREAD

**Issue by chenzhutian** [vega/vega#1863]
Hi! I have a hierarchical data like this: 
```
[
    {"id": "A", "parent": null, "v": 3},
    {"id": "B", "parent": "A", "v": 1},
    {"id": "C", "parent": "A", "v": 2},
    {"id": "D", "parent": "C", "v": 1},
    {"id": "E", "parent": "C", "v": 1}
  ]
```
The `v` of each item is the sum value of its children.
I want to visualize the data using [`partition`](https://vega.github.io/vega/docs/transforms/partition.vg.json) transform and only want leaf nodes' sizes depending on their `v` while other internal nodes' sizes depending on their children, e.g.,
![image](https://user-images.githubusercontent.com/3315274/60699574-21bbaf80-9f27-11e9-8573-7ae9c7bc8b44.png)

But what I actually have is 
![image](https://user-images.githubusercontent.com/3315274/60699586-35671600-9f27-11e9-977d-8101a5374d2b.png)

I try to reset the `v` of internal nodes to `0` via
```
      "transform": [
        {
          "type": "stratify",
          "key": "id",
          "parentKey": "parent"
        },
        { "type": "formula", "expr": "datum.children? 0 : datum.v", "as": "v"},
        {
          "type": "partition",
          "field": "v",
          "padding": {"signal": " padding"},
          "round": {"signal": "round"},
          "size": [{"signal": "width"}, {"signal": "height"}]
        }
      ]
```
But it fails since there is not `children` field in the output of `stratify`.

Currently, I first apply a `partition`, and then use `formula` to filter, and apply a `partition` agin to get what I want:
```
    "transform": [
        {
          "type": "stratify",
          "key": "id",
          "parentKey": "parent"
        },
        {
          "type": "partition",
          "field": "v",
          "padding": {"signal": " padding"},
          "round": {"signal": "round"},
          "size": [{"signal": "width"}, {"signal": "height"}]
        },
        { "type": "formula", "expr": "datum.children?0:datum.v", "as": "v"},
        {
          "type": "partition",
          "field": "v",
          "padding": {"signal": " padding"},
          "round": {"signal": "round"},
          "size": [{"signal": "width"}, {"signal": "height"}]
        }
      ]
```
It seems a little bit awkward. 
There is a [`node.sum(value)`](https://github.com/d3/d3-hierarchy#node_sum) functionin in `d3-hierachy` to fulfill my requirement.
What's the correct way to acheive what I want in Vega?

Many thanks!

**Comment by jheer** [comment]
Unfortunately, there is currently no way to access the children counts prior to running a layout in Vega. One option would be to annotate your data ahead of time: either by using zero values for internal nodes or including a `leaf` field that you could use to calculate the proper value.

Of course, if all leaf nodes have the same value, a simple count would suffice. I will update the vega-hierarchy layouts to apply `node.count` (instead of `node.sum`) if no value field is provided.
