### ISSUE TITLE
Axis overlap with rect marks 

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1867]
When using the default zindex=0, y-axis overlap with rect, but x-axis doesn't.

![image](https://user-images.githubusercontent.com/111269/60760731-598e2a00-9fef-11e9-9031-284c474fb16b.png)

[Spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7RiiJFh4AngBsdOSPGQuXx+wfQ8TBwAbSUIUAgoqBl0VHcoaVYAJy8AfQAGP2ioFN8PAKDSeHRk2ElpOTscyAAzbmSMPF1gSGdCBMgpWUgAX2rotuT0GVh6xt0wnKjI6ai2pw7dSHRqamThPB0Buch17lZCdidJyAB5ZMYmKqgAYVdLA2QyyABdHenIbmJT+JG3j41WqMbwGWCnAASDVgyEI3AA7s8AeFduhwaFIH8ZGkoWVYQika8UdFesSwESSUp3iYNNRYi50WApjNILF4ssAB5pRywhRQCjoFysBIAJgy-RRrTZnXhjAMLD5kEOhU67BGYP0XgAFAZuBhLFqAOQcw0ASjobisLHkYAyNoyprAACowFyeYQ+jspXFOk5uVsPTbIAKhaLxV7WT7ligrvhFcrAqr1bBNcgdXr0AbDU4zRbkFbEPb7Y6XX73X0qdVMaUANaM5kRMmR9keDDJOvZQbtTobeDNQEOZxuU695rUz61ZJ6lqQQrBRIHVLITKepv5+DcJ4tMn2BNbbdzebAnwzhCCzoblwNRXA0HLLE46H4xHJVeH+wc08lYceT9B28uEYHj3C4jzPOCErvlAsryogX7npyipqjIQFgHgyTCpB76QCcOCtGeP5QCc-4goBywXFclhvthMbUHGeEON+vpIequjoZhO5gKS0zcVEvHjokTH1pKTbSohA7dssyFGAOur6nIDFzssSRLiuJF3sBDwoeBirSMkzQ4OxyBYYMwxWAk+EBqeVz0py-q8r0JnzGYFhWAAkjIMhIjgdpNi5ljUGcqjebaKJObMgxiR4xFNpJHjSZ28xyZmClgK0SkeCp6RZOpZEeBR1y6Q0BloRhxkDmZ1AWYOvIMbStnRfZHqOQO-nuZ5IW+Z8bWBcFr4+WFXqiVGHiXteEmLJ0oFeaUiX+BmVGKYE84OIu2U3qRqGYsgIyPnicIvtRpkjFV0Y7XgGCBk2lhbMkcIuIm0bwL4A7aFOui1IKMJhZWJjoByyDCdEEXzARnR-k2DQgjIJWQOw3AENOA7rHKH1fcgEnMIRkAgWBLwDg97DeAAgqBdLLJcdH9k2hMk1YhEigA7F1NS0y4ABCaLeJYnSoHKBjDgT6BEy4ZxUMkD0eoZZWDSJnxg8sMWfFD+aw24tTU58KOoZ9DIY7FWOdAVVE-RAAmQG4VUoUDMxNse+RQGNr7I8MFiqwAMvm1AKnVNmCssz1xIQWq0fgNoAGwACw2mKDpHaDTioPDLgACqTQHjCpILBt4NjACyO0yGA3C1GAuIwgdSKm+SIC9EAA)

However, moving y-axis to the top produces the same overlap.

![image](https://user-images.githubusercontent.com/111269/60760758-b1c52c00-9fef-11e9-9702-a6722f067b57.png)

It seems like the axis would overlap with rect marks at x/y = 0, but not at x/y= width/height. 

I wonder if we should adjust this in Vega somehow? 

As Vega-Lite is now putting axes behind marks by default in 4.0, we're deciding if we should have a special case for left/top-axes of rect mark.
But if we gonna fix this in Vega anyway, we might not need to change in Vega-Lite.

**Comment by jheer** [comment]
Is there a specific proposal here? Axes include an offset parameter, but this can also have the effect of causing the domain line of one axis and gridlines for an orthogonal axis to align poorly.

> It seems like the axis would overlap with rect marks at x/y = 0, but not at x/y= width/height.

This is indeed what happens, keeping in mind that (0,0) is the upper left corner.

**Comment by kanitw** [comment]
Honestly, I can't think of a good fix for this. :(

**Comment by jheer** [comment]
OK, I'm going to close out the issue then, but feel free to reply / re-open if new ideas emerge. :)
