### ISSUE TITLE
Documentation on vega-dataflow package

### ISSUE THREAD

**Issue by churtado** [vega/vega#1873]
Hello,

Apologies if this not the correct place to submit this. I'm trying to understand the code inside the dataflow package, but can't find documentation on some of the properties of operators, such as  qrank, rank and stamp. I've tried looking through the code and the API reference.

Are these bits not documented?

**Comment by domoritz** [comment]
https://observablehq.com/@vega/how-vega-works is a great start to dive into Vega internals.

**Comment by churtado** [comment]
Thanks for that, it's very informative! From what I can tell, the dataflow package took several ideas from streaming engines. I'll have a read through the research papers to see if I can understand better.

**Comment by domoritz** [comment]
Yes. Have a look at our paper at https://idl.cs.washington.edu/papers/reactive-vega/. I'm going to close this issue.
