### ISSUE TITLE
Link on Homepage is broken

### ISSUE THREAD

**Issue by bkfarnsworth** [vega/vega#1894]
Go to https://vega.github.io/vega/

Click the button:
![image](https://user-images.githubusercontent.com/6440842/62429209-e698d180-b6c8-11e9-8cd2-6762a7806fb7.png)

The link goes to a 404

**Comment by domoritz** [comment]
This will be fixed once we make a release but I am waiting for getting permissions to do so. For now, please use 5.4.0.

**Comment by domoritz** [comment]
Thank you. I just created the missing tag.
