### ISSUE TITLE
Support shared extent from derived extent in kde transform

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1898]
Currently, Vega KDE as used in https://vega.github.io/vega-lite/docs/density.html#example-stacked-density-estimates, shared extent requires specifying explicit extent values.  

However, we should also support using a shared extent from observed minimum and maximum values of the density value field _across groups_ (currently the default does observe the min/max for each group independently).

`"extent": "shared"` could be a natural syntax for this. 

(We would need this in Vega first to fix it in Vega-Lite.) 

cc: @jheer

**Comment by domoritz** [comment]
Can you explain why this is needed? The density is 0 outside of the returned extent, right?

**Comment by domoritz** [comment]
Is the issue that the densities are cut off too early?

<img width="403" alt="Screen Shot 2019-08-06 at 10 01 29 AM" src="https://user-images.githubusercontent.com/589034/62522099-44e0c400-b831-11e9-8dcd-c12b3ca5a00a.png">

What is a case when you would not want to share the extent? If we don't have one, maybe it should be the default.

**Comment by kanitw** [comment]
See the examples for density in https://github.com/vega/vega-lite/pull/5271:

From `area_density` to `area_density_stacked`, somehow users have to specify a fixed `extent` and `steps` in order to have the fixed extent and step across the groups. 

Besdies `extent`, actually the `steps` option would benefit from a "shared" option as well.

**Comment by jheer** [comment]
Similar to binning, you can always use an `Extent` transform to compute the extent for all data, bind it to a signal, and then use it to parameterize the `KDE` transform.

That said, I'm happy to update `KDE` with a new parameter for convenience. I'd prefer not to union-type the array-valued `extent`, which if defined should always be used. I propose a new `resolve` parameter that can either be `"shared"` or `"independent"`. If shared, both the extent and the steps can be synchronized. That means that you could provide a custom extent and still get synchronized steps...
