### ISSUE TITLE
vg2xxx: can they take input from stdin?

### ISSUE THREAD

**Issue by jowens** [vega/vega#1905]
Currently `vg2pdf`, `vg2png` and `vg2svg` only take an input from a file. Can they alternately, if no file is specified, take input from stdin? They are useful in pipelines (`vl2vg foo.json | vg2pdf`) and hopefully easily modified to allow this.

**Comment by domoritz** [comment]
They do read stdin: https://github.com/vega/vega/blob/a66c45dc78f0d5c74ddae95054df38bd14bd389a/packages/vega-cli/src/render.js#L59. Does it not work?

**Comment by jowens** [comment]
Oh! I'll assume that works then. Kindly update the documentation?

https://vega.github.io/vega/usage/#cli

**Comment by jheer** [comment]
Fixed.
