### ISSUE TITLE
Text scale config property

### ISSUE THREAD

**Issue by marcprux** [vega/vega#1959]
For accessibility reasons, we need to have the ability for a vision-impaired user to be able to increase the size of all the text in a visualization. I propose a top-level `textScale` config property that will adjust all text (text marks, as well as axes/legends/headers & titles) by a specific percentage.

The scale would apply after evaluating all the config's `fontSize` properties, but can be overridden by specific `fontSize` properties specified in the mark definitions.

This might be implementing by just applying the `textScale` after evaluating the existing `group-title`, `guide-label`, and `guide-title` built-in style font sizes.

**Comment by jheer** [comment]
Thanks for the request! This might relate to #1904: if we add signal config as described there, it could be used in conjunction with signal-valued config entries to implement this.

In fact, I you can already do this manually if you add an explicit `textScale` signal to your Vega specs. You could then use a modified config file that references the `textScale` signal to define fontSize values for text mark and style entries.

Here's an example of what that might look like within a single Vega spec:

```json
"config": {
  "text": {
    "fontSize": {"signal": "10 * textScale"}
  }
},
"signals": [
  {"name": "textScale", "value": 1}
]
```

If we adopt my proposal in #1904, the `textScale` signal could be moved into the `config`, allowing all customization to be defined in a single place and in a reusable manner. Let me know if you have any thoughts regarding this approach.

One current limitation is that the vega-parser only adds config and style entries to the `enter` encoding set. As a result, the text size won't dynamically change if the `textScale` signal is updated at runtime. So I would also need to update the parser to move entries to the `update` set if they are signal-valued.

**Comment by marcprux** [comment]
That would work nicely for text signals, but would it also be possible to scale the default `fontSize` in the built-in guide styles like `group-title`?

**Comment by jheer** [comment]
Yes, so long as the corresponding configuration entries were over-ridden to use signal expressions that reference the scale parameter.
