### ISSUE TITLE
Support different radius for different rect corners

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1968]
Currently, we have the `cornerRadius` property, which controls the radius for all corners of the rect marks. 

![image](https://user-images.githubusercontent.com/111269/63755933-af8d9880-c8e1-11e9-910c-a880148d1fcc.png)

However, designers often prefer that bars have rounded corners only for the top of the bars:

![image](https://user-images.githubusercontent.com/111269/63755801-8240ea80-c8e1-11e9-94e5-0b72f4b994ba.png)

![image](https://user-images.githubusercontent.com/111269/63755860-971d7e00-c8e1-11e9-97ac-c527968b521e.png)

For syntax, we could name the new encoding channels in one of the following ways:

1) `(topLeft/topRight/bottomLeft/bottomRight)CornerRadius`
2) `(top/bottom/right/left)CornerRadius`

I think 1) would be more flexible, but 2 would better support the described use case.  (We would only need to use `topCornerRadius` to produce the plots above.)

**Comment by jheer** [comment]
Here's where to start implementation: https://github.com/vega/vega/blob/master/packages/vega-scenegraph/src/path/rectangle.js

If following the analogy of CSS `border-radius`, the property name should probably be `cornerTopLeftRadius`, etc. CSS also supports `border-radius` with multiple entries. In Vega, this would be a number- or number-array-valued encoding channel.

Next one would need to update the schema and typings to reflect any new encoding channels.

**Comment by kanitw** [comment]
Thanks for the pointer. :) 

Another alternative syntax would be an object-based `cornerRadius`, where we can specify: 

```
cornerRadius: {topLeft: 2, topRight: 2}
```

This is perhaps more consistent with the `padding` object in Vega.

We could even consider additional syntactic sugar like: 

```
cornerRadius: {top: 2}
```

for both `topLeft` and `topRight`. 


Once we agree on a syntax, I can look into implementing this in the upcoming months. Perhaps, after CHI deadline.

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega/pull/2127
