### ISSUE TITLE
cornerRadius for stacked bars (data-driven clips?)

### ISSUE THREAD

**Issue by kanitw** [vega/vega#1969]
As I think about rounded corners in #1968, the tricky case is rounded corner for a stacked bar chart like this:

![image](https://user-images.githubusercontent.com/111269/63756389-7c97d480-c8e2-11e9-97dc-43792427fc70.png)

We could set corner radius to only the top bars, but it won't work when the radius isn't small and some of the top bars are very small. 

The better way to do this is perhaps to create another bar chart layer (without the colors) and use it as a clip mask for the stacked bar chart layer. However, AFAIK, we can't make a mark group serves as a clip mask for another yet.  

(There might be another solution, but I figure we better open this issue so we can further discuss.)

**Comment by jheer** [comment]
Individual corner support for `cornerRadius` added in v5.8.0. "Data-driven" clips might be achieved using a signal value to set the clipping path when using `path`-based clipping.
