### ISSUE TITLE
Argument count bug in view.data()

### ISSUE THREAD

**Issue by soul-codes** [vega/vega#1970]
I'm pretty new to Vega and trying to set it up so that it can render changing data, I found that there seems to be conflicting information about the functionality of `view.data()`, for v5.5.0.

According to the [documentation](https://vega.github.io/vega/docs/api/view/#view_data) (emphases are my own):

> If only **one** argument is provided, returns the data set with the given name. The returned array of data objects is a live array used by the underlying dataflow. Callers that wish to modify the returned array should first make a defensive copy, for example using view.data('name').slice().
>
> ≥ 5.5 If **two** arguments are provided, removes the current data and inserts the input values, which can be either a single data object or an array of data objects. This call is equivalent to:
>
> ```
> view.change(vega.changeset().remove(vega.truthy).insert(values));
> ```

However, in the implementation, there is only discrimination between **zero** and **non-zero** arguments:

https://github.com/vega/vega/blob/2f0f47b3c52bf61acc095cb47ae769eb44b18dcc/packages/vega-view/src/data.js#L12-L16

This seems strange because in this implementation, `name` on line 14 is always `undefined`. My guess would be that line 13 should have been `arguments.length <= 1`

The typings also appear to agree with the documentation and support the guesswork above:

https://github.com/vega/vega/blob/2f0f47b3c52bf61acc095cb47ae769eb44b18dcc/packages/vega-typings/types/runtime/index.d.ts#L39-L40

Not sure if my line of reasoning is correct here, hence an issue first to confirm with those who are knowledgeable. I'm willing to PR such a trivial fix if that's useful.

N.B. For the moment I could just use

```ts
view.change(vega.changeset().remove(vega.truthy).insert(values));
```

as a workaround.

**Comment by jheer** [comment]
Thanks! That looks like a bug. And a rather careless one at that (my fault!). Will fix soon.
