### ISSUE TITLE
Fold Transform

### ISSUE THREAD

**Issue by arvind** [vega/vega#2]
We should have a "fold" data transform. It'd make it easier to build stacked bars, and other small multiples, for unfolded data.

**Comment by espinielli** [comment]
It looks like this bug is back...I get low numbers of flight in the interval 9-14
![screen shot 2015-11-24 at 10 58 56 am](https://cloud.githubusercontent.com/assets/891692/11363478/6e2fbfd4-929a-11e5-8597-c1a0a09df492.png)
