### ISSUE TITLE
granular hover properties for group marks

### ISSUE THREAD

**Issue by beyang** [vega/vega#200]
Here's the use case: There is a bar chart with text marks displaying the numeric quantity above each bar. I would like to be able to hide the text marks and show them only when the user is hovering over a particular bar.

![image](https://cloud.githubusercontent.com/assets/1646931/3605764/b140abe6-0d2e-11e4-9748-a7c7e894bf4f.png)

This might involve extending the "hover" property in a group mark to be able to accept selectors for sub-marks, e.g.,

```
...
"hover": {
  "child-mark": { "mark": "name-of-child-mark", "fillOpacity": { "value": 1.0 }}
}
...
```

I've just started to try out Vega, and I'm not sure if this type of feature falls under the "visualization grammar" mandate or whether the idea is to add external CSS for additional interactivity like this.

Thanks for making this awesome library, by the way!

**Comment by dennisobrien** [comment]
This looks very promising.  Are any of these Vega extensions available today?  Or are there plans to bring this into core Vega?

**Comment by arvind** [comment]
Hi @dennisobrien, we're actively working on integrating these new interactive primitives with Vega 2.0: https://github.com/uwdata/vega/tree/v2 We should have more to say (including a release) soon!

**Comment by dennisobrien** [comment]
Looking forward to it @arvind!

**Comment by arvind** [comment]
And Vega 2.0 has now been merged into master. See [Signals](https://github.com/vega/vega/wiki/Signals) and [Predicates](https://github.com/vega/vega/wiki/Predicates) for more information, or play with the new interactive examples in the [Vega Editor](http://vega.github.io/vega-editor/).
