### ISSUE TITLE
Is this feasible to put one more parent edge to the radial tree layout?

### ISSUE THREAD

**Issue by Migh213** [vega/vega#2003]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Clearly describe the goal of the feature request. Why is it needed?
- [x] Describe an envisioned solution. What do you want the new behavior to be?
- [x] If applicable, share mockup images or links to examples illustrating the desired output.
- [x] If applicable, share JSON spec designs for how the behavior would be made available in Vega.

Hi,

I was trying to draw a family tree via Radial Tree Layout since every generation in that family is pretty wide. However, the radial tree layout only has one parent node. 
So, may I ask how to put one more parent edge to link a node with another parent so a child can link to both their father and mother.

I'm quite confused about which files to focus on.  But an experienced programmer in other domain. So it would be nice if someone can point out which files I should pay attention to.

**Comment by jheer** [comment]
_(This is a usage question, and so better suited to the Vega discussion forum or Slack channel!)_

You can overlay graph edges (non tree-edges) on a layout if you like. However, you will probably (1) want to define the edges in a separate data table, with lookup keys for the corresponding nodes, and (2) use the `lookup` transform to link the edge data objects to the corresponding nodes. You can then access the node (x, y) coordinates to place the edges appropriately.

For an example of performing such lookups for graph edges, see the `path` mark definition in https://vega.github.io/vega/examples/arc-diagram/
