### ISSUE TITLE
Unable to get Data from url using signal and following datasources are empty

### ISSUE THREAD

**Issue by mathiastiberghien** [vega/vega#2014]
Hi,
I have issue when i try to load a data from url using signal reference.
Did I configure something wrong?
Thanks
Here's my sample: [Vega Editor Sample](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KLEbUZ6ADaxsAbSURQEI8ajrUybJHjMAngv0mIkCptYWskAAroATo20OxgC+io4GgSaQZu6QAI5uPnahYU6MMsyWAOT4RCTk6ISMdNyEyDIA7sjoLMg+GITFPtSkACbVIgBMdKKkAGbcPsjw6LB4APyxALyZANTWeDYzmQBkrOl4sJPmeH7wywWFLZMd8ACc7L0AHL0ADADsAIwAbPAAzE83HzfwN+yXL70fgAWB4dU43TKQCIQIJKAC6yUgbTwmCwemMhki0UsyPQAH0HvZHM5XMhtGiHvIOvJXvIgXCHCEHJjjFF0OYce08b0fNxUHjWD4NETIoLhR4csQyKQCkUSmVKtUUHUCo1mrjSF0ev1BsNRhNJt4-LBVutNttdvtCIdjmcLtd7s83h8vj8-gDgaDwVDgslwsTsR5cdzefyxXiVGpNCLWWLsMBIJH1OK4gk7LDfcyImyOUGuR0Y0YSRo3OSdJTqbT6Yz4SAgkA)

I you look in the data viewer:
"data_1": hard-coded values, have the expected data
"data_from_url":  hard-coded url, have the expected data
"data_from_url_signal":  url based on signal reference, data table is empty
"data_2": hard-coded values, data table is empty

if you add define datasources after "data_from_url_signal" the data remains empty
There are no logs indicating any failure

**Comment by roying** [comment]
An error is shown in the javascript console:

> ![screenshot_vega_error](https://user-images.githubusercontent.com/37225856/65048368-fa735c80-d931-11e9-86aa-a1baacd5392d.png)

For data in JSON format, Vega expects an array of objects.
https://vega.github.io/vega/docs/data/


The data from the URL is in this format which is not what Vega expects:
```
{
	"cod": "200",
	"message": 0.0069,
	"cnt": 40,
	"list": [{
			"dt": 1568646000,
			"main": {
				"temp": 27.05,
				"temp_min": 26.3,
				"temp_max": 27.05,
				"pressure": 1019.99,
				"sea_level": 1019.99,
				"grnd_level": 1008.76,
				"humidity": 38,
				"temp_kf": 0.76
			},
			"weather": [{
					"id": 802,
					"main": "Clouds",
					"description": "scattered clouds",
					"icon": "03d"
				}
			],
			"clouds": {
				"all": 39
			},
			"wind": {
				"speed": 3.08,
				"deg": 317.028
			},
			"sys": {
				"pod": "d"
			},
			"dt_txt": "2019-09-16 15:00:00"
		}, {
			"dt": 1568656800,
...

```




The workaround is to use javascript to fetch data from the URL, process the data, and then replace the data in the Vega dataset using Vega View API:

       view.data(name[, values])

> (Vega version ≥5.5) If two arguments are provided, removes the current data and inserts the input values, which can be either a single data object or an array of data objects.

https://vega.github.io/vega/docs/api/view/

**Comment by mathiastiberghien** [comment]
Thanks for the answer, I'll think to use the javascript debugger now (I'm new to Vega but really enjoy it)
But in my sample, I also defined a datasource with the same url than the one using scale, but this one doesn't fail even if the query return also one object.
I was expecting that the behavior should be the same using inline url or signal url: both failing or both succeeding

**Comment by jheer** [comment]
Thanks for sharing the issue! I agree that the two loading methods should behave similarly. I've made a minor adjustment to the `Load` operator in the `vega-transforms` package that will ensure any retrieved values are wrapped in an array if not already array-valued, such that behavior of built-in and dynamic URL loading are better aligned. This fix will be included in the next release.

**Comment by mathiastiberghien** [comment]
Great, thanks!
I really enjoy your work by the way.
The visualization grammar approach is awesome

Le mar. 24 sept. 2019 à 10:56, Jeffrey Heer <notifications@github.com> a
écrit :
