### ISSUE TITLE
GeoJSON transform seems to be producing invalid FeatureCollection structure

### ISSUE THREAD

**Issue by afdta** [vega/vega#2016]
The issue arose while trying to use the geoBounds() function on a FeatureCollection generated by the geojson transform. I've tried several input geometries, but the result of geoBounds() always comes back [[NaN, NaN], [NaN, NaN]]. Using the generated FeatureCollection in the projection fit field also causes an issue rendering the map.

This example demonstrates the issue with geoBounds(): https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwATgAMuxREgpG1fFoBs+w1HSs83WIwBeyLZBmy3ipZDXo8TBwAbSUIUAhIqBl0VDccSHhuVhk8RmRYBTDIyFYAJwAbd3wiEnI89GUGZjZ2VlhkPKTU5FS6JNQhWi6RDFg8RtI1bnhYIYCReoBaAEZdVElpORsoyAAzbjyMPC1gSDwAT0J4qAdCbilZBSg15AD8k8Tk1PTMgF9st5WwCKjo2PikAAKtwAGJ3PAPADC3AKBWQ8DSV2+Rmk+XgjySKTSGSyf1OFRksA2W0gYBC2QgAEhgFT9kdAWtGAUBnk8fiwHTkAAPQhsrB+e4LajIbhxPB5A5gACEAF5ZWAZKw4ZBKZEvmrwpqcodjthICKLkt2RyoIbLnIBYbxZKTRzIE5qDEigK1vBVaaPviALqfEBKb0+Ix8i4IpFErShKK-VYxOLuEMSO1GXWPdAFdiNTJ+iCB-2rR3OzLksBRyIxnJxwHsZ5qTIoqCsQj+Ab6w0AIVrsAAFEq4fIwG6AJQe9UBny+DB5ADWmQp0bV9L1CVgiHQeob6zyYt2gsC7ixL1xGvxkFaSTUJwrq1arN2N2ZLp+kAo6dYjwAxMhdN-v5AvmA2qmjk-TbtOV4vm+gIfgAzHB8H-g2wEFhK3DgQA6uomg4Hsr4FO+Wi6HQABMoheshHLkVEJ5-PshLEpsqCRtqwCnAy7iGqu67eFAiZhjwlq8duSZgFRkS+tRAYgG8QA

I created another example which demonstrates that all works fine when generating the FeatureCollection directly using topojson. You can view that here: https://jsfiddle.net/0gz9f8q7/7/

**Comment by jheer** [comment]
Thanks for posting the issue! We'll take a closer look soon.

**Comment by afdta** [comment]
The resulting FeatureCollection that I see generated in Vega looks like this
{
"type":"FeatureCollection",
"features":[
{"type":"MultiPolygon","coordinates":[...]},
...
}
My, admittedly limited, understanding of the GeoJSON spec is that feature objects should have a geometry property, and coordinates should nest inside of that.

**Comment by mattijn** [comment]
The `geoBounds()` function requires a *Feature* as [input](https://vega.github.io/vega/docs/expressions/#geoBounds).

The TopoJSON input dataset is within Vega transformed to a GeoJSON Feature Collection. This Feature Collection is a bag of Features. 

In the following example I filtered a complete random Feature by id and used it as input for the `geoBounds()` function. Upon inspection in the signal viewer this gives a good result (signal `bounds`).

See vega-spec in [editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAZgAMuxREgpG1fFr0GlkdKzzdYjAF7ItkGbNeGoa9Hkw4ANpKEKAQ4VAy6KiuOJDw3KwyeIzIsAoh4ZCsAE4ANm74RCTkOejKDMxs7KywyDkJycjJdAmoQrQdIhiwePWkatzwsAN+IrUAtACMuqiS0nLeEZAAZtw5GHhawJB4AJ6EsVD2hNxSsgpQK8h+uUfxicmp6QC+mS9LYGERkdH3CUl9hkflBpLl4P9Hik0sCfrsyjJYGsNlpAjt9oc3CtGHk+jlLpBkAAPQj4uK+PCsObqMAAXlpYFEll0kBeAF13ko2d5IKSzsh4ClZOkgplvssojE3HyJLDlo4XNtII5qFECnFAqoNIh5GATGY8GzWZ8jNitjgdiq1W4KegABQAcgByT2DoAlMbMkYMfd0Hl2PV0pyINzrFa-SKwMEIjtJfd2I81OlddlCBT7tRkNwAEKJ2B2mSsPJ5XW2x3O-buwK6Nket4hnkYHIAa0j0fC4qyPrcsEQ6ExJquOW4qCVtrcFeenpBhJkCTUR07y2aeO2Xrh2OLSooftY9wAxMhdEej9OQVlesPm4vIDu8nu3PvtM+X2fz6C8FfkAB1dSaC23ruRy6HQABMoj1uekERB867wugiLIqOQTogcGZZr2-ZeFAMoCkKchxDKrIcjBXIgC8QA).

I also referred in the `fit` property within `projections` to this filtered dataset to make the map 'zoom' to the extend of this Feature.

<img width="267" alt="image" src="https://user-images.githubusercontent.com/5186265/65282276-cf0c8f80-db34-11e9-8216-6ca350d0899d.png">

I actually don't know when I need to use this `geoBounds()` function..

**Comment by afdta** [comment]
I believe geoBounds() should accept a FeatureCollection. The function is a wrapper for [d3.geoBounds()](https://github.com/d3/d3-geo#geoBounds), which accepts a GeoJSON object as its argument (I think the Vega docs could be clearer here). In this example, it works: https://jsfiddle.net/0gz9f8q7/7/ (see line 100).

My suspicion is that the FeatureCollection generated within the Vega geojson transform is not properly formatted, causing the geoBounds() function to fail. 

FYI, I'm using the output of geoBounds() to refine the default map projection parameters to better fit the local area. Cheers.

**Comment by mattijn** [comment]
I cannot get the `geoBounds()` function to work with a FeatureCollection within the vega-editor. I don't know why this works in your jsfiddle.

I did find that the `us-10m.json` topojson file contains multiple geometries with empty listed arcs (ids: `22051, 51735, 51740, 51520, 72049`). Upon conversion to Features this creates an empty coordinate list. I think is wrong in the topojson file. But it could be filtered with:
```json
{
  "name": "counties_valid",
  "source": "counties",
  "transform": [
    {"type": "filter", "expr": "datum.geometry !== null"},
    {"type": "filter", "expr": "datum.geometry.coordinates.length !== 0"}
  ]
}
```
Next, I saw multiple Features with duplicate ids in this file.
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>id</th>
      <th>2201</th>
      <th>15009</th>
      <th>26033</th>
      <th>15007</th>
      <th>22051</th>
      <th>26003</th>
      <th>26029</th>
      <th>26061</th>
      <th>26083</th>
      <th>26089</th>
      <th>26097</th>
      <th>55000</th>
      <th>55003</th>
      <th>55029</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>15</td>
      <td>4</td>
      <td>3</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
    </tr>
  </tbody>
</table>
That is probably not good either.

**Comment by mattijn** [comment]
I think this is a bug too.
The `fields` property in the `geojson` transform produces good output as such:
```json
{
    "type":"FeatureCollection",
     "features":[
        {"type":"Feature","geometry":{"type":"MultiPoint","coordinates":"[Object]"}}
    ]
}
```
The `geojson` property in the `geojson` transform produces falsely output as such:
```json 
{
    "type":"FeatureCollection",
    "features":[
        {"coordinates":["[Object]"],"type":"Polygon"},
        {"coordinates":["[Object]"],"type":"Polygon"}
    ]
}
```

When using the `geojson` property in the `geojson` transform it should nest the geometry within a `geometry` key in each feature and the feature should have a `type` key with `Feature`.

On a side note I noted that the `geoBounds()` function does not work with Features that contain 3 distinct coordinates. It should have 4 distinct coordinates to output good values.

My geoBounds output for a polygon with 3 distinct coords: `[[-180,-90],[180,90]]`.
My geoBounds output for a polygon with 4 distinct coords: `[[5,52],[6,53]]`.

Used spec:
```json
{
  "data": [
    {
      "name": "mp_raw",
      "values": [{"lon": 5, "lat": 52}, {"lon": 6, "lat": 53}],
      "format": {"type": "json"}
    },
    {
      "name": "fc_raw",
      "values": {
        "type": "FeatureCollection",
        "features": [
          {
            "geometry": {
              "coordinates": [[[5, 52], [6, 52], [6, 53], [5, 52]]],
              "type": "Polygon"
            },
            "properties": null,
            "type": "Feature"
          },
          {
            "geometry": {
              "coordinates": [[[5, 52], [6, 52], [6, 53], [6, 52], [5, 52]]],
              "type": "Polygon"
            },
            "properties": null,
            "type": "Feature"
          }
        ]
      },
      "format": {"type": "json", "property": "features"}
    },
    {
      "name": "mp_transform",
      "source": "mp_raw",
      "transform": [
        {
          "type": "geojson",
          "fields": ["lon", "lat"],
          "signal": "fields_transform"
        }
      ]
    },
    {
      "name": "fc_transform",
      "source": "fc_raw",
      "transform": [
        {
          "type": "geojson",
          "geojson": "geometry",
          "signal": "geojson_transform"
        }
      ]
    }
  ],
  "signals": [
    {
      "name": "f_bounds_3_coords",
      "update": "geoBounds(null, geojson_transform['features'][0])"
    },
    {
      "name": "f_bounds_4_coords",
      "update": "geoBounds(null, geojson_transform['features'][1])"
    },
    {"name": "mp_bounds", "update": "geoBounds(null, fields_transform)"},
    {"name": "fc_bounds", "update": "geoBounds(null, geojson_transform)"}
  ]
}
```

**Comment by jheer** [comment]
The Vega `geojson` transform expects to receive `Feature` objects as input when using the `geojson` accessor. (In hindsight, I think `feature` might have been a parameter name...) The examples above instead pass in `geometry` objects. Here, it looks like you want the `geojson` transform to use the full feature datum, not just the `geometry` property, but there is not currently a way to specify this. As a fix, I will adjust the transform to use the `identity` function (take the feature datum as-is) if neither the `geojson` nor the `fields` parameter are specified.

@mattijn: I'm not sure why the `geoBounds` method was failing for you. You might test with the latest version of d3, in case you're using an older Vega version. If you notice any errors, you could file an issue on the d3/d3-geo repository. I also noted that the coordinates you used in your example:

```
[[[5, 52], [6, 52], [6, 53] [5, 52]]]
```

Lead to the following output from d3.geoBounds:

```
[[-180, -90], [180, 90]]
```

Changing the point order like so:

```
[[[5, 52], [6, 53], [6, 52], [5, 52]]]
```

instead results in:

```
[[5, 52], [6, 53]]
```

So the winding order does matter!

**Comment by jheer** [comment]
Also, as an alternative to passing Feature data objects through directly, the following code snippet can be used to construct proper Features as part of the `geojson` transform parameters:

```json
{
  "type": "geojson",
  "geojson": {"expr": "{type: 'Feature', geometry: datum.geometry}"}
}
```

`{"expr": "..."}` acts as a lambda function that takes a data object (`datum`) as input. Note that you could also construct an identity function this way as well:

```json
{
  "type": "geojson",
  "geojson": {"expr": "datum"}
}
```

**Comment by mattijn** [comment]
Good catch regarding the winding order! I thought I got the hang of it now but apparently it still bites me.
Also interesting info on the `expr` and lambda functionality!

**Comment by afdta** [comment]
Great stuff, thank you!
