### ISSUE TITLE
Axis title position doesn't react to format change

### ISSUE THREAD

**Issue by skokenes** [vega/vega#2017]
I am using a linear axis with a numeric format that is dynamic via a signal. I have an axis title with titlePadding set to 8. On initial render, the title correctly renders 8 pixels away from the axis labels. However, when the format of the axis labels change, the title does not recalculate its position to be 8 pixels away.

[See this example.](https://vega.github.io/editor/#/url/vega/N4KAkARAJAzgxgCwKYFsCGEBcACCCAu+ADjJgPRkBuSA5mgHQ0CW+CArgEb1MD2Z8ydFVpoqAVnoArGDwB2EADTgIAdyYATVlmwBGAAx6lkZExoFtAZgNGIRNOvVNZNbaDCR8PItv1HIHHkIeFB9DcEgAGyQAM3xtAA49cABfGzQ2TxgmAC8kV3CIfABPIjycCFk5PL8IACckLNztfFq2JBq4OXw0JxhtCE7ZfCQhiBSbdTRu7QBtAF0bQejTfPcINAAPJj6cNzX1YJ7ZAGEeCJ5a-uwAYiQAFiQAdiQORXDIA-QnAHUNLRwdH4PEw4ABrU7nS7lG5wDjqABM6gAnG93JE0BwkBEIRcrtcLPc4GIUUCIBEMViAGJdfoASSGSFq2EoaEupPJmIiAHlqLVyd5yjR6kh1EVUWt8CwojiobgbgS7kSSe9ClKkNShgBlHJlXSAlWS-BRDX4b5IUzmaEANgM4uBRqQAAV7I5nAlwslxsosjRZGgIjtsDNwnsKmgULqINELug4jUWRE2v0ALRQBT0K0APzZBQ4TnUqzWTiIGX6tXsvDtEC8krkgZmEFT6azbNwyeblzmHpSC29cH9DVmob9Ef68AH4sKJUjEScSFZk8+R1mhnhBl7a3LzkjJjMcR7aQ2g5wMz2kAuTBGcXKUViVfHUTH-cfpMNj-KAFkitgACpqqvRrUsaFmsPp+hE-SAcB7ypAaarOg4TguDg8Qel2yRAA)

**Initial render:** 
![image](https://user-images.githubusercontent.com/5554373/65378699-39831400-dc8a-11e9-8851-6716be0a7f66.png)

**On format signal change:**
![image](https://user-images.githubusercontent.com/5554373/65378706-499af380-dc8a-11e9-8103-f19226fd87a6.png)

**Comment by jheer** [comment]
Thanks for posting the issue! I've pinned down a bug within our (re-)layout logic. This will be fixed in the next release.
