### ISSUE TITLE
Issue updating a Topojson Map with new scale and translation

### ISSUE THREAD

**Issue by DeveloperUX** [vega/vega#202]
I created a map in topojson format.  Map shows up as expected but whenever I try to send in the map data as part of an `update` I get an error saying:

> Problem calling View.data:  TypeError: undefined is not a function 

The map renders fine the first time it's displayed, after modifying the spec and calling update nothing happens.  The new spec works fine in the Vega editor but the changes don't seem to propagate to the visualization.  I narrowed down the problem to these lines in the **vega.js** file

![screen shot 2014-07-23 at 1 06 26 pm](https://cloud.githubusercontent.com/assets/1531338/3676824/ba88af48-128b-11e4-8910-b9e1562c5bb9.png)

![screen shot 2014-07-23 at 1 05 34 pm](https://cloud.githubusercontent.com/assets/1531338/3676810/9df8c8b8-128b-11e4-9778-1ec09e1eb881.png)

Issue seems to be the way the world data is being passed in.  Where as the other Data objects I'm using are being passed in to the `view.data()` function as a list of objects, the world data object simply has a string.

![screen shot 2014-07-23 at 1 07 56 pm](https://cloud.githubusercontent.com/assets/1531338/3676853/f0ab8a6e-128b-11e4-97d6-4adf5d18772e.png)

![screen shot 2014-07-23 at 1 02 32 pm](https://cloud.githubusercontent.com/assets/1531338/3676764/81f2c01a-128b-11e4-886d-9cf8d20b3080.png)

The weird thing is the map is still rendered properly the first time even though I get the same error message.  It's only when updating that the map does not change given the new spec.

##### Below is the initial spec I am using:

```json
{
  "name": "Map",
  "width": 940,
  "height": 480,
  "padding": 0,
  "data": [
    {
      "name": "world",
      "format": {
        "type": "topojson",
        "feature": "countries"
      },
      "url": "https://rawgit.com/daviderwin/dramaticglobe/master/data/world-110m.json",
      "transform": [
        {
          "type": "geopath",
          "value": "data",
          "projection": "robinson",
          "translate": [
            470,
            240
          ],
          "scale": 100
        }
      ]
    }
  ],
  "scales": [],
  "marks": [
    {
      "type": "path",
      "name": "MapMark",
      "from": {
        "data": "world"
      },
      "properties": {
        "update": {
          "fill": {
            "value": "#BBBBBB"
          },
          "path": {
            "field": "path"
          },
          "stroke": {
            "value": "#f2f4f7"
          }
        }
      }
    }
  ]
}
```

**Comment by arvind** [comment]
Please re-open this issue if you're still facing troubles with Vega 2.0.
