### ISSUE TITLE
Can't update large dataset

### ISSUE THREAD

**Issue by buckle2000** [vega/vega#2024]
Vega just kind of broke if I try to update large datasets (500+ items). There is no error message.

Screenshot:
![screenshot](https://user-images.githubusercontent.com/10850402/65530911-71729d00-debe-11e9-8098-dafb3f3f910c.png)

package versions:
```
{
  "dependencies": {
    "vega": "^5.6.0",
    "vega-embed": "^5.1.3",
    "vega-lite": "^4.0.0-beta.2"
  }
}
```

Here's an easy example:
the schema is straight from [here](https://vega.github.io/vega/tutorials/bar-chart/)
https://gist.github.com/buckle2000/9decc5268d7adbaa5f2a565e5401852d

**Comment by jheer** [comment]
The bar chart example you're reusing specifies rounding on the x-axis `band` scale. However, you're passing in more data values than there are pixels, so this process results in a degenerate layout.

If you remove the `round: true` (see [this example](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAFgAMuxREgpG1fFoBM+w1ELo1axjOpbRipZDXo8mHAG0lCFAIEKgZdFRkLUgfdgAbKJtQyAp0ONZkWC0-YEh4bxpuACcAT2xIAEEKhUgI7lYZPGwANl0AX3lc-LxC0vKKgCEauoamrABGAE4OroLqYrKsSoBhYdR6xpaADhm8uYX+gBE1jbHRZt3u3sXKgFET0ZaAdkv9vqWKgDEHzawni1ePXm70qAHEfmNmjtOnsgQcPgAJCHYUQvGFXYE3CoASWRWAAzONAdd+gApPFQ4mY-oAaTxFmm6LeWIAMnjxgCmXCQRUALLsxmzblYgByeNE7S5JI+AHk8fjBbDpZUAAri7RU+GVACKeO0Gql1I+ACUKQahcqKgBlPGKjFaioAFXZ0ItRsqAFV2UTDQ6AGp4p7mpXuioAdT1wftPIAGuK0W6HQBNCmiTU8gBa4p9iZBA2q8lq60eEwTIa1AyGhZGv2aad9edW1eLv1EduZ5QGx2bp2wrvLefuPZLHPTNwG32Hv3G-ej4-BU7GT3xY87SMX2Hbws7uI3fzLc875L34yjHaWAzpe-xB-PkAGbL3zS3yoG-OvFwb47Fe-+q4vcp7lY-73mqe6oiBAy6r+kq5uOponiuX6djaT6fnBnbOnus53gMXrXi+7oDAGe7aLe24XhGpGchhF5xuBOEUfeKYnrBA7jlm1EgcsBZFr2ExnkxyxVnxJYWIxyrLE2omtjR7HlMs3YyWcbGHksyxDsp2AWDm8nqZOWl-IJkkLoZ+LGe6yzroZUzcbuNmEVqyzHoZoj1rRkDLFehnAch6mPoZTzoXpnnvjZulqZ5P5mapd7LIBNlyZFyxgTZEmWdBPnBclCFmRZTmoTZ+UgssWGudlcX4T5EVxSRMXcVRRXcfR1XcSxrmxUJnGuTVTGHLxNZjAqIGHCJg3YISI3SeNBKdcqhxKTN5kjZpS1ze6hwGTN6Vaocpkzdo7khYc1lLUld6HPZS29fNLkzc+I3edtI0BQd5HzWFM3nCN0VLUdkWHAlB07SChypTNQYjZlX3rbtuVrSNhXPX5kCHGVENIR5hxVRjI11TNtko4cjVfe9G0tTNFgVX17UE8VNyHN1B3-XetwDS2Q3nUxtxjRz2BPCz3PTXzWDaDd7q3ItIvjLDIK3KtItiyBtxbdLmMhbc+3S7LNy3Kditk1qtxXSLFiG3Ld2K9Tyq3E9Itucrr0i-iXM259ItPOLRu-SLzTWxLQP2yDuvg6bOvlLc0P2+HSy3PD9v0xHSMe67Evo0Hys4wnyv4-b5u6yTiup0bFMZyjty087jly0zzsx5Anzs-xlIo58vP8RYxcgp8wv8aOrdS-xSutwrHfq5Fnyq339efFrHde93+v8Q7rcm8vM+W33-tap8dvN9v3dO-xAsgZ87v8cH5SfD7Hcz4H-GTa3ocX6fUfz6f8fH4nSyfMnHfVzcT46cx6nyzu-VuucH4z0Lsvb+DdS7N0vj-SuQ9x53k+LXIeB8bigibiWfEgtlSgnbiWFeHlQS9zEtg8ooJB4llaCBUEo8Sx6EYVPEsntGFz3odQpYoIl4lgATQte9CF44M3hwruOC94cLgaCI++D66gnPiwtBTFQQ31kYw++9ChF8OfvQtRRC36KMYZ-UhejICgj-mJKRNDgEcPzjQsB+C5GQKoYwmBYknF8IQWJJBViUH4ICaCTBI5LEIjwb8ThKMEQkNbD4yACJKHRKMe6BEdDWyEPScw2svCknsN+MNWJ3Dpx2KWAiARvwdIgQRCIrJtSJG1nKUkmR04xHlARAo6JcCEQqKKb0zRrZ64Ih0dExJCIDG1l6SYhpsTzE9NqTYhJtSHG-H1LUlx1SRnuO2bUrx1SIl+NrB0ipQTawTLCesxJ2IokqRAtieJYwNko2xCksYncHmZI+acyA2JclLmyVqbEhSzg3NKR8gJ2IqmQoefU+5rymlDUsdiNpgKHndKXDc-pZxfnYiGbC15YznlpOBVMs4KLZlLnrtiBZYxxikpBNiZZQ08VrKXHirZ9KoW7OeTcg5zz8nYmOei155znlAqZVchFHlSR3JaJY0kTztK-NJO8locDSTfM3CBUkAKUSKtBQa3VELti6phdgGcur4UTUZTcUkSLLWKrRdpO15RSSYpRPk0kOKUSqoJSiTVxL+aqvJfzTVVLtKKrpdgbQbqlikhZRNAJpJ2UTUVVy2NiTSS8omqqgVKIWmkhFYW3V4qdUo1JNKlE8bIA0nlVgZovyaTKr+PXGk6rRaSpuDSbVot8k0n1X8bt5QaRGtFrWmkprG2TotVgCUIEaQ2tFi0mkjqCQBJpC6rAFhJ2esbZYmkvrG3toDQSQ9wb52rrDTugdkad1wJpDG+dh6k0TsXWm2ai7M0Embbmv4q6C0EgHSWgDi7y07s3dW+diSWQNv7h5FkrbTwgRZJ2x+iG+34nriyIdZCQosnHTLVD07Dqobnc0FpLJl2+UQ+up4sHt2WJZPu-EASWTHrY6hs9LtUOXosCOpYLIb0t0Q-e0QvyWTPok6ht9zRa0sk-TJlGLIf3aHY-+h6KmgPiVQ6BptqGINxtQ9B0QLTeQNt4yjXkraLBwN5J27QljeR9oZSBXkQ71PufHaJkKvJp0Ib8xRgJvJl3fWs+urTHleTbtELW3k+7PnWc4783kZ7aN+f46lm9rDrP3oY+559f5rNvrI9Zz9Tx668h-cV6L-7IbWaAzE6LoGrXWYg-hyKvJoOEw8iKBtTmQIilbXWIbnaUMoxFFhxJIoh3jHySKcdcWhsBdrSKCjLSRTLvGL8kU675tDe3QyIbiWFvHrIkNs9w8+uXr9kNm9DW+vid28+0bk2307aG5+5ak2f3jEE5AEU-7PuTaA5RoboH8QLYg5YkUpmAcygbcpjyMpW0XZRjKdDCO+2+cijKPDliZTjoKxj6dDCMdzuMxj5dQUQIyno-kmUsW4Eyn3bVkKMpzsI544Ty9-26c3qSyj+9NSMdFYR3Jlnn7At47U-XGU9X5dAZl3eGUoHcso6My0mU0GqceRVA2t7+u0cA5VI5-JKo+1thAiqTzFvx1Q5twFxJKo52WJVMu7QLSVTrtEAElU27rshRVIl73XObdnv97d35KoHve-vRh4Pr3a0qg+zHz9Qvg8-v9-+3dNumtwJVPplPEH5M256-k7USOAfajR787U6HEnaity07UQ7RceW1MTmv06rOd7nTeEC2pl3NCb+u-EtbtSB6b6xmvnHJ88cr7duB2ob1+6HyL+vr3W9vuWyjbUGem8-qiyFbUmnK-K5r+r+vRn6-QYCcaeDljjR15AsaTtzQ4HGj7ZnyKxo8O-LGhEZf697P5u5v4j7P6+71zGjbrLhv77og4eTGjHpG4hTGhnrP6Xro7IE5b5LGj3qj5v5Fa1rGhyaAFKb4FqYA7GiabP5AbaD4GQ6kEQYnwozGjQYT4gRWiG5wJWitqVbcGdrs6RRWiua1pWhzb1xWjjqMHcGka-JWiU58HLqD4oxWjrrHbqGxbSH7oBJWjHpUzcFnqdZ3hWh876F4HcHiYA5WjSaKFvp2bcEZ6KE-rI4hRWj-rYbcFAb6H6aJJWgdYSG66-KOgNok4eSOgCG1qOidoZaRSOhYYBKOgAEgSOgO75KOhk6JKOgD45E0aZHj45Hbp94hSOj7plaRGGEA6OhnpoEJGXqJ4JE3oq5MSOj3pyEoyOjPreFdFyYtKOifrg5dHH4xH-pe5pE6Y1GQ5wKOgdYDG64A4egDaWIeitpmYgQehY6bF9pB6RQejt71wegZGbHTpsEeQehzpaEXFha1oejj5HFMabEVGrGcb5IegmEBIeiXoiF3geg3pNF-GEFHE9GrG74tIejS5LE-qO4owejjGJIehg4QmtarEQalH7EhEgR+hI71x+jrG-J+hxEBJ+hW61p+hDoREhR+jjrXHUmkYA5+iU54kj5wJ+iRbklHaWJ+hs7kmGF4lnrNbUk-F4kPbkmEGEk9GMmOF4lKbcluFsleGElNbkmgYbEox+hGZ4nQaPYhRhhI6WJhjrGGkf71xhh9q6mRRhipEoxhjE6JJhhnH5JhgUZmk0YOnrqVF6nbrk4eRhhs4tJhjHq9Z6lXaGnYHOmC61phj5ZmnSZmmOEOlDGBlqbOm56Gk6ZwJhhqmGnokBJhg6m1oxi8EgQxgjaWIxiOYVm7EBIxiUktIxhEaJIxi971wxhXFwIxg06dmenNnbptYeQxj7rW4owxioFtl1H5Ixj8YNmC6dkJ5Tnb6lkfYVnfa-Ixg-od4hQxheGdlAYjmDn6YNnzGlnQb1F3hJgNpbmRRJjrEBJJjjaJJJg-6-JJhDpEEoxJgO73lnG1pJhXEA5JjbaWJJj7b5JJiB4gWIHgWcb1xJiYEgRJiXqmFMRJhr4tJJgJ4YXPp7EXlvrwGfnJmIU1YYXA73lAa9EeRJigbxEXkQa-4Xk9YA4ZhI6-IZho71wZjjbMW7FwIZiHEgQZjE61oZgBb5IZhXGJIZhhZsW+7MX9mcX7qf6CXBl8UmFSWNGWIZiC4BIZgdHMU9EtIZi75SVymCVuHMV0GCU6YiVqnMXol8WcEXAAC6gQYAbQSgzl7gRgsApg4QcQWQ-gblwQoQYQEQUQOAMQ3A3AcQeAjAhACgblRgqQ6QEVYAwAHQSVUAsg2QWVQQkAyAVAjQgVUARQyA8AeAWAxYsAyA3AVARQCgUArAhAXgPQ0QrVrAqAkAmVoVIQuQhVyAxV0QZVFVVV9QNV9QTQ8gRgzVrVaVkAGV3VWVrloQHlEAXlIAHgCAaQmQuVoQIVyQ4QkQ0QAAHttQkIlb1TECUIQPNewOgDIGoJdaFZ4NwBgE4FoLkK1b4FALEBddNZAAAGaMDIBxBPWRWHg9UvVFAPXUDzWqAaCIDPXJB2AOBOAuA4C6B0C6CiBuVQ1BBZWQBHXzUlDnWJCE1qBvXoAfU4BfXeA-UxDoDxCJBQDA2g3g1QDjT40hBE2MDwBpV4BFAZBJA80w3ODzUmBmBNB42eXeWc0nW7VBX7XZVFAg2-BQDsDcAEBvWNWQBk2nX63uUi3AAq1q1jBQAJCA1TVQD62RWk35AXXuWy2bVGAYBFAADWJVAQ+1hNeAN181I1U1hNgNRQOttNng9N5Qf1UQ3NRgg18A3AagaVB1L1g1PQDVtNeVPNJ1n1etDt81Z1+dutbNYN0QkNItV1CNmg4dttUAhdO1ut91j1WgPoWdRgiw6VedDddt+tANJdHNWksdL1JQFgudtdkA9tDdANKVGQWg7QWdQ9M1LVBQn1bdrNjAcQcQudM981sAPQoN8Qs9a1vVRtWdxgdVyAGd6Va9QNG9W94dO9w1yAT1x9vVr9IQ793NKdRgftt10QPQJ1QdV18didydZ9adl9q9J9PNaQfl29aQs9ENEDDVi9PN91NVcQTgydKQCDd1WteAOtqDRgwNm98DqV0QAAxBPviEtdA6g5ALNSvZndA0YDnTXUXZFfXf9TbX5WkP-dFbFfFXQIeADU3RzVjfWDfR3bkOPZPdw3rbw-fb9QI3FYQHQONADdwIDYDTVebQALScg30APm0yOKP8MxWqPqN8xEPr2b0yh2DwDMAd3e0sP5U9B73tXeCdVgAAC8fjYABDFj8Vutj9mNNj+VoTYARIa9K1J979EAn9nlIAHlQAA)) you'll see the bar chart.

However, even then there's still too many categories for the available space. In response you can either filter the number visible categories, or increase the width of the chart (either by increasing the width parameter, or by removing it and using [a scale range step](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04XMkbV82MACYADNsURIhdABNjjGdQ2jFSyMfR5MOANpKIoCJ6gz0qZBshHdgAbf30vKAp0YNZkWA1nYEh4BxpuACcAT2xIAEFchUhfblYZPGwANm0AX3kklLw0rJzcgCFC4tLyrABGAE5a+tTqDOysPIBhDtQSssqADkHk4dGWgBFp2e7RCqWGprG8gFFNrsqAdj2V5vHcgDFTuaxzzSvGkZu8gHFH7orFurLd6rW4ACV+2FEl0B+w+h1yAEkIVgAMw9N4HFoAKWR-wxcJaAGlkZoBjDrvCADLInqvcnAz65ACyNLJQwZ8IAcsjRDV6ZjbgB5ZEotlAgV5AAKPIALPiQXkAIrImVy-kE24AJVxavZEtyAGVkWLYQrcgAVGkAvUavIAVRp6PVZoAasjzrrxbbcgB1FWe02MgAaPOhNrNAE1caJ5YyAFo8p3hz6tAryIozM69MNehWtdrpzpPCox50pqaFzNPUQmik5VobStbbDW3Mpk5NrO02OHVoPTtPHqtwO9n4D7rnFE9+vg8fYWsc+tIufPHMj+s4lc9AN18atYkrlFr3eQVrUlcVBcS1osw+7Mu97krl7TvfClc6V+n6UrqFf1rKs+fLJr22pblOD71kaF73iB9aWiuw4nq0DqHletqtG6K4ysei57n62F0nBe4hr+SF4aeUZbsBba9gmhFfhMaYZs2vQ7hREwFixWaaOREoTBW3HVkRtE5BMjZCdsNHruMEwdpJ2CaEmomyf2CnPOx-FjupKKabaEyzup-SMcuRnoQqEybupoilsRkATAe6mfpBsnnup5ywSp9m3kZykyfZT46dJJ4TO+Rkif5Ew-kZfH6YBTmeZFYE6XpFnQUZqWfBMCHWYlIWoU5fkhVhQWMQRGWMaRhWMVR1nBRx9HWUVFFrMxRbdKKX5rFx7XYGiXWCb1qL1RKawSUNuldfJE0jbaaxqUNsUKms2lDTKtleWshkTRFJ5rKZE3NaNVlDZeXWOYtXVuWtuGjT5Q07F1gUTRt-lrGFa1LZ8azRUNHpdfFD2zctyUzV16WXS5kBrDlf0QXZawFXDXUlUNxlQ2s5UPbdc1VUNmh5S1tVo5lhxrI1a2vSeRxtVWHW7RRRw9XT2DnFTjODSzWAykdtpHONXM9MDnxHNNXM81+RwLYL8NeUcq2C8LhxHNt4s4wqRwHVzmjqyLJ3i4TEpHBdXM2ZL11cyiDNG-dXPnLzGvPVzFSG3zH2m19yu-drSs5EcgOm774xHKDpuk37EN29bfOwx7ktI2Hkuo6buvK1j4vRxreNx1DRzE5b5kixTltB5Ady06xeJQ3czOsZomefHcnOsd21cC6xEvV2Ldey-5dzSy3pd3ArdcO43qusWb1da5PQ-6y3rsKncJuV4vjcW6xbNfnctusZ7OR3E7ddD+7rH9dX3t79vAej9voeb+H4x3JHdeF4cdyxz328J7f1fJ2fQ906T0fmXbOld95P3zh3XuJ47jFw7mvQ4XwK5ZhROzCUXxa5ZinnZL4zceKIJyF8duWYqhfi+N3LMMpS5fAHlme25CR6kMIeML4E8sxvyITPUhY8kHz3oQ3JBK96EgK+BvVBNDd5UJgRRL4R8RHkNPqQzhrDL6kJkRgm+EjyH32wSoyAXwX48UEUQz+9DU5EJ-qg0R-8CHkKATxCxrCwE8QgQYqBqC3FfHgV2fRoIUFPAYVDUEWDqxOMgKCfBgSNG2lBCQ6s6DYmUOLCwiJdCnidWCUwwcJjxignYU8JSX5QTcIScU-hxZckROEYOXhORQTiMCSA0EUiMnNPkdWUuoIlGBPCaCNRxZmlaLKcE3RTTilGLCcUsxTxVTFKsYUrptjFnFIcYUvxLjix1LyR44sfSfGzPCQiAJUkvwIlCd0OZUMERRO6PXM58S7nbMgAiZJE5EkKgROk7YRzsl3LcQiAp-yzmlNOdcipHV9EIhqe8s5jSJxHNadsZ5CIOnAuuT0y5MTPkDO2FC4ZE5S4IjGd0Ho2LPgIkmR1FFMyJwooWaSgFyzLlHLWZc1JCJNmwuubsy5HyKUHLBXZLEJzKj6KxBcxSzysS3MqCArEjz5xfixG8yE4rvlquVX8hYyqgXYCHMq0FfVyWHCxBC-V4qYWKRNTkLE8LISpKxEiyE0q0WQnlZi1m0rcWs3lQSxS4qSXYBlDa8YWIqV9TcViWlfVxUMuDeErEzK+rSrZZCKpWIuXpuVbypVUMsSCshKGyAhJRVYAqM8wkkrnil0JLK7m-LDiEkVdzVJhJVXPEbTkQkGrubFsJNq8t-a9VYF5F+QkRruZVMJOa1EbjCRWqwJoft9ry36MJM68tta3WonXZ60d06fVLrbf6pdIDCRBtHeuiNfbx0xuGuO+NqJK3JueNOtNqI21ZrfeO3NS752FtHeEykZbW52UpNW7cX5KT1vPuBltKJS6Ug7TgrylJe1C2g4O9a0GR0VCqZSSdzlwOzvOMBxd+jKSrpRG4ykm6aPQZ3VbaD+7NBdvGJSI9VdwOntEM8ykl6+PQZvRUYtlJ71CahpSJ9MpaOvrOlJj9vFoPfordBv9IboOAdEFUpkZbmNQyZNWzQICmT1plPopkLayVfiZB22Ttne3ca8kyQdYGXN4bcUySdj1DOzoU3ZJki7RDFqZKu+5hn6PPKZDu4jLnWPRaPdQ2zp6yO2cvS+QzN6cOGfvecUuTIn2ZcC6+-6hmP1BMC9+g1hm-2of8kyQD6M7KcjLRZr8nJq0lg6-WqDUNOQIfCZyDtPRUmcl7SFjrbni2cjw1Uzkk6ejPM5LO0bHXF2kg6+Fsbm6cIdZ3Z3Fr+6XYdaPWVlrvHluXu6-1m9S2Ov3smv1p9PR2OQE5K++7-WP34Y69+lEY2-36M5Npt7goy2SbsoKate2oaClg2Dltzn-KChQ-owUva0tw8HWQuHI7NNw8nR5L8gpSOpMFMFkBgpV3Fa8oKXbYOmPo-3a9knR6ItQ9PUUuHGWwciap-e9zKOZOl0FKV0XH6hcnkFN+5LcONNVMFIBgndlJRlpu6rmHb3JTmdSZKFtNYvySns3r3tAOjdufCZKEd+jJSTplFUyUs7RBuMlIuw7XlJThcdwzo3O7XfHeeZKM7jvT1wc99d4tko7tB-vRzz3T7XevuXUbirIDJSqaj3+0TRumupMVBDt7ioYfPMVLB8JioDdVMVB27ndlFSY6L4Ogz9eR1Hi-IqSdFQK+zpRMWxU7uK-UaL-R-vTH8-HZAYqI9LuO9c9L9d6vN7JtQ0VHHivT6AteUVPJ-Pkui+y9Lxp0vgG3GalA-ozUJevyanrRUEBmoW3x-8pqFDzzNQYYf83y-Nub9d8v87qXJqIupODfqul9nZJqJuhrl5JqDupfvurDpAUlqkpqKet3jfhlsWpqCJu-hJqgTJm9pqPJpfh+jKKgf9tgX+lvFDJqIBn3l+AaOriAgaNWvlowfWrTv5AaNZsWgaCNqXAaL2uQYwdhs8gaPjiwZOu3lDAaLOptrIcFoIaum4gaJugTIwTuvVieAaCzqoSgYwbxm9gaIJuITeiZowXHuIU+pDl5AaK+ohowR+qoapuEgaHVnwcrs8uaGWljnZOaGwcWuaPWnFv5OaAhm4uaG-l+OaGbqkuaDjuEuaG3kkURvEb3kkYui3l5OaKujlv4eoW9uaDujAWEfuuHmEUelLhROaKeiIVDOaJeo4Q0SJlUuaPer9g0ZvkEa+g7jEUpkUf9iAuaHVm0crm9naG1vonaNWjpl+HaAjvMS2h7v5HaLXqXHaHEfMYOjQXZHaCOgoXsT5sWnaL3hsRRvMXkdMfRqknaFoW4naPulwSeHaEehUS8egRsU0dMcvlUnaILhMU+ublDHaL0eEnaD9n8dVtMX+tkasV4V+C6BDqXC6LMc8i6CEW4i6AbsWi6B2n4V5C6L2ocYSdhm9i6PjiiV3iAi6P5riRtvoi6DTrieoSiTupVoSU8SiWdriegeiU0eSeYSiRJoyTYTSQ4eiRVrid+nMVDC6BpiiYBudl5D6BDvoj6LMeqXfqXD6C2sqf5D6NEVDD6JjuEj6Dsakj6HhjqURmabOvkSqYurjnZD6DTlUj6Jus1iqQduqYgZaezsWj6KljqYJjqeYWaR0e6TJpacnuqUpiAj6DKeqbCW4j6EqcWkGMwV+EGF1vokGOZnmcsW4kGPiVUkGBhuEkGM3qXEGAcSAkGETvWfaZWYujVnZEGKuoblDEGNATWSUakkGKxmWezvWWHgOYvtmXdnmY9s8kGE+nXl5EGA4fWR+l2e2apmWaMdmYBqUSeBGGWguf5BGLMW4hGL1uEhGE-s8hGB2hgVDBGGbqeTscWhGAcW9hGItvohGKtqkhGO7l+eAb+fRqXBGPAV+BGPutoRRBGDPlUhGGHnBZeisXuTeqAfeZGeBUVnBZ9qeR+s0XZBGN+qEXuX+s-nuU1m9nGBDs8nGDDqXHGL1pRcsSAnGOsV+HGJjsWnGG5qknGAceEnGD5jRc7pRa2fRauvfuxZ6SxVoQJeUfonGOzm4nGHUZRU0VUnGMvgJSKexTYZRSQexUplxTKZRbCSxfQbsAALpuBgDVBKCWU2AGCwCqA+DBDxAuA2UeARCQA+B+ABB4DcDcDBB4CMCEAKA2UGBRAxD+A4DAC1ARVQCyAJAJXuCQDIBUBlDuVQDpDIDwB4BYCZiwDIDcBUDpAKBQCsCED2CNABDVWsCoCQDxURCeBJDpXICZUBA5V5UFUlBFUlDlDyAGCVXVUxVQBxWNUJXWVeB2UQAOUgC2AIDRBxDJVeBeVeA+W+CjWQAAAei1oQ4VzVgQmQhAW17A6AMgxgB13lxg3AGA5gGgSQ1VTgUAQQ+1g1kAAAZowMgMEJdTgKJE1d5ekOddQKNUkLAI0GFTgKzuEOtUYKYOYJYDgNoHQNoKIDZYDe4AlRtX5f9ZkHtWENjTdXdXILFXYA4M9YEOgCEGEFAF9T9X9VAL1JjZ4D5YwPAKNXgOkLELDazcDRYFtSgKoOoBjfZY5UzdtctR5atYlekN9U8FAOwNwAQLdeVZAATQELtSkPtbZbzcALLfLd0FAKEB9QNVABrXjRrbZWLfNQYBgOkAANZZWuCrXY14DHVbVdUDXY0fXpCq1k1PU5CvX+As0GDtXwDcDGBg0pVQDtWNBlWxUx0GDbUPXq3a1bVa1LVq302-UBDrih3eUADujAxgLAqdFtUAmdb1it51jNToSdUAYwYA4N6dAQ+Nrd71OdjNCkBd61mQmg5drdltHdkQ0QsQGgNQMdvdFVVVqQD1Ddn1jAwQwQqdUV49-1ENyAP1IQ49M1zVutMdkAiAJVyACdzdC9X1y9q9Y9ntyAl1e9zVD9ngT9LNa1rN7tJ1-lyA213th14dkd0d+9sdZQp989QDBg0QLl190VedcdoD09BgZ1RVwQ5gYNkAa9p1ytAVDVCDdNS9K9ZNGDAQAAxH3iiBNUA9PZAMNXPYneA5XYPVnf9VXbTerS5dEP5YFcFaFXQOuO9WdRdRPXQKWAvU3S3Uw43Rre9c5dQK5Zw0FSFYQHQL1O9dwB9R9UVUbQALR0gL2NA-3l3sMEMvVcOKPKMsy4OL3L2ChGDwDMBN0u30PN2BBxBG3k14D1VgAAC8PjYAAVCjoVatRDyNuDqVwTYA6IDdU1+9T9EAL99lIAdlQAA) to set a unit bar width).
