### ISSUE TITLE
Add affine transforms for path marks

### ISSUE THREAD

**Issue by mathiastiberghien** [vega/vega#2030]
That request is related to #135 but suggests a different approach

Consider the visualization: [responsive light](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwANgAMuxREgpG1fFoAsog0sjt08ANbUATt1Yy1WyHhfoZsIToLsgyeAq2sKYy6AA2sFoA2koQoBDpUDGoyNiQCHHIAOrqmoYZUIwyzLkATPoR5VDslV5YwJCVhKzhWJB+MtQ58lColdjWw5AYAB5aegZQsHjIhFrWAL4pYOtlqVtGWTm9+bHIABLIpua76R1VPZAAjNYN5XYt2O2d3bn9gwojMZYCYjdCzHBWBZ5ZarHAbLY7LZpN6Hbx4ZinV4ZSAUOKsI5QSAIm7I7GonDQ9B4VgJG5GXGxfHeFweKoDLG3ZqeT53LoPWDIU7wcKTbiEdGyBI4RJ9VmVagAyDIFxuFyKpZiwjILwAXU2GURGVJt3JTVilUcHPpeIJvnxdKgsiS+3SxsaSqoYSlYDdjSgeAAnlq0YxsmqHe6WG4CJicI99LoXQaI7dWIQ1FSCZAAITsc0yS1J7YunXEpEuyDkvLwApWqBpjPLXKjGQAChORRKiFIdV0dAMHYuVzwpGefd0AEoicny+6qx2ABp1yANzO5DvFDTd3v96fpQ2uivzmunACay9XTeOJ-OlzMI7Hu4RSh1ZUgjcw0tnKPQ2W8S0zWkKwZfFvUSKAWRkNkFUmZVVXVPBNW1SAwFLA0XzfDswIw2x0TwWMfS2HxkGmHofUWaI4hDfCcm2G5IAAM1kPAAGVGAALwJOp6O4BiGIFMjRCUA8pmCRxsKNCtA2DCkglKCtQngbg1AJX0jFCZY1RwNTbgYxhYliLQdOxEDVKLd1XHQNRGA05krMYKiU3dDViGdP13MIjyPMgXj+OQMibC89zICU2JuC0lREGYHJzL9A8gsPBL3V8gStD7AB2JzvNC8LvAAYgsQq9yS4sSrQoL9Q8+K-UgaZ4CMijqBiQyKVULcexQ6r3QDertMa5rvBMe8OtKuKUxXdM1zaWLsTkxAGrySiWqgAByVAwBWgBqRcACoAFo9E2laNu2m9Tx2qwjrAdATt2w7jq2jtzrqK7dDAN7Hlum8Fx2x4XuOt6bse76dvur6Cme3RXvesBPuBgofr2v6oYBlbOqLTYXUqiBqt9HwgyzObl0U5SzOCjTlSM2LYsY-TluM25TKpkrIEs6zbIpPxrMcmbbgDR40roAAOLLsRciSSs8yWjBS-y0tFmqcoiyBlCipteZnaWGeC2WAroABOBX3SV7xXGQANiqS7GgvKrzrcaLq3jqhaoiaqjWq7EbHexHqXaWwa73wL2MfGy8jlASAib6xa3eWyA1vB05EbB+Gzx2-7rsT5AfpT06IfTlGYY+rOfuR6GKCzyGrqBvOk9BwvU+QKuAZhuHa+z-ay5bivG-Ova6nR9z7dGnGSSkgnvCJh0lRkJSVOZmqKYihmaed6PXYGj32pqTqssgX31-9ikhqDneR-Kb360mq9CMjql5sP2PvATxvk4b9vm8z1-66u3uC+h4u38u4wxrndd+T1-4t0Ae3RGwDdBozojTPSBk3JBW1rcZYSx-x4CpDSMAABeQhG1ILQTRkbKATNtIa1uGzGyYQ7Lc0MuQow4tUFa2oclPiqUcCBWlrcE2rU1YxT4YgkR6CdZcLljwugNRmFvAEVAM2oRLYlUvl5cRNVdZaEeHI7ECiVZCJUVbDhqFqHDwdgrDRxEsEUgAtSWABCiErTguFY6AAyNxYA8wWjrMFShUsWa0I5hBeyPNpbQjFBLdhIiZaSICro-h3AwrK1VtFIxCU1EeQ0ZwvyetZEmL0Uk3KnNkIFNEXw7JbwtFxgSUYfRqT1YiPMR5W2FVeaZL2CzfxlTWZczoWRPooSmEmIia5L8YiymxNyfLSZUB6mGLKR0v0lTsTVPejI2pcyinKzytoPZ6SKoJJWbcNZOjZkhW2d4Bpwi+HNPcq0u27TYoPP3FjMsklIwT1kvfYms9SYL3dEvAFfoaZLDcI4VSFCbTeDzA4S05Tgpgu4BCzcmhH6bygELHaHZd6r16uRGOGKVaezPpk-e+LgD9XdrgQOI5SUhyLBNRs4caZRwJRval8d1rfz2hYcBZ1frpWriXC6-L87xgAbDEVQtC7wMHnFN5mtEpvGkoTH508SbzyoeTMIlNtUeRpmKBwzALbR38X2fWogEU1TXuyo+KgSW4q8uSv2T9j60uDkPUO18ybeTZZSwlnKX4wP2pdB6H99oZ1ASDMNlcLqiElW3Xa+tZVgB7hGvlwrv6xr-s8RNIq9opteggslyDlrJASlYzBAy7F4MIfg4hcoBhkOoTiaF+rAl9OCYMxhvjvL80Fvk8JrDxkVPOWs3hIiLnJKuQsppRzx1xMFobc5+ilFyEWSYl5Q92mWNbdW7BuCHH1o2i4lw7jPHeILH2903SRlBPoZzIZN6aoDukUOyWoyomS2OVM7h71NnTuKZFNJiyF0xMdEu6RK6INAeViELwm7pbboVRkvdXT20BKSr0+y3a+lhM-W+9ZH6WYjrABWsdsGJ2AfmaB+dZTf2QemdBmjlyKS7P2UhyWKGHZPK8ih4e1tKqlnWEAA)

If you change the scaleWidth or scaleHeight of the visualization the light with scale correctly, despite the scale having only path marks.
To achieve that, I first created the light using 200x150 size, then I added a scaleX and scaleY signal and in each path, I multiplied the x and width values of the path by the scaleX and the y and height values of the path by the scaleY. It works but this is really painfull as you can see in the code (this sample could also an answer to #578).
A nice improvment should be to have a scaleX and scaleY property in the path marker that will automate my code at render time. This could be an easy way to make paths responsive

**Comment by jheer** [comment]
Thanks for sharing this. Rather than incorporate scaleX and scaleY properties, a more general solution might be to support affine transforms (scale, rotate, shear, etc) for path marks. 

Perhaps something like this?

```json
{
  "type": "path",
  "encode": {
    "update": {
      "transform": {"value": "rotate(-10 50 100) skewX(40) scale(1 0.5)"},
      "path": {"value": ...}
    }
  }
}
```

As path marks already use [SVG path strings](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#Path_commands) for the path format, it seems consistent to use [SVG transform strings](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform) as the transform format.

I've added the feature request label. If anyone is interested in implementing this, a good place to start is https://github.com/vega/vega/blob/master/packages/vega-scenegraph/src/marks/path.js

**Comment by mathiastiberghien** [comment]
I'll be happy to work on this. I reviewed the code and I discovered that:
- a symbol is a path
- a symbol with size of 4 will render the same as a path because half of squareroot of size is used as scale factor
- a symbol has an angle property to be able support rotation
- x and y properties are defining path and symbol  translation


I suggest to:
- improve the existing scale implementation and make it take 2 scale factors instead of one in [https://github.com/vega/vega/blob/master/packages/vega-scenegraph/src/path/render.js](https://github.com/vega/vega/blob/master/packages/vega-scenegraph/src/path/render.js)
- add scaleFactor ({x: numberValueRef , y: numberValueRef}, and angle propeties to path mark schema in [https://github.com/vega/vega/blob/master/packages/vega-schema/src/encode.js](https://github.com/vega/vega/blob/master/packages/vega-schema/src/encode.js)
- modify path method to support scale and angle in [https://github.com/vega/vega/blob/master/packages/vega-scenegraph/src/marks/path.js](https://github.com/vega/vega/blob/master/packages/vega-scenegraph/src/marks/path.js)

This should have a minimal implementation cost because most of features are already implemented and tested (there is already a scale test for path by example) and will be consistent with symbol usage

If you still prefer to work on a path transform parser that will generate the transformation matrix for the canvas, I can also do that but what I don't like with the approach is that
- properties are more intuitive and consistent with the usage of x, y and angle properties for translation and rotations
- as the transformations will almost always depend on a variable, it will require for the user to build a transform string with signal reference wich is less user friendly

What do you think?

**Comment by jheer** [comment]
Added by #2123 for inclusion in v5.8.0
