### ISSUE TITLE
Allow to bind gradientstop color to signal

### ISSUE THREAD

**Issue by mathiastiberghien** [vega/vega#2031]
Consider the visualization: [animated light](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwANgAMuxREgpG1fFoAsog0sjt08ANbUATt1Yy1WyHhfoZsIToLsgyeAq2sKYy6AA2sFoA2koQoBDpUDGoyNiQCHHIAOrqmoYZUIwyzLkATPoR5VDslV5YwJCVhKzhWJB+MtQ58lColdjWw5AYAB5aegZQsHjIhFrWAL4pYOtlqVtGWTm9+bHIABLIpua76R1VPZAAjNYN5XYt2O2d3bn9gwojMZYCYjdCzHBWBZ5ZarHAbLY7LZpN6Hbx4ZinV4ZSAUOKsI5QSAIm7I7GonDQ9B4VgJG5GXGxfHeFweKoDLG3ZqeT53LoPWDIU7wcKTbiEdGyBI4RJ9VmVagAyDIFxuFyKpZiwjILwAXU2GURGVJt3JTVilUcHPpeIJvnxdKgsiS+3SxsaSqoYSlYDdjSgeAAnlq0YxsmqHe6WG4CJicI99LoXQaI7dWIQ1FSCZAAITsc0yS1J7YunXEpEuyDkvLwApWqBpjPLXKjGQAChORRKiFIdV0dAMHYuVzwpGefd0AEoicny+6qx2ABp1yANzO5DvFDTd3v96fpQ2uivzmunACay9XTeOJ-OlzMI7Hu4RSh1ZUgjcw0tnKPQ2W8S0zWkKwZfFvUSKAWRkNkFUmZVVXVPBNW1SAwFLA0XzfDswIw2x0TwWMfS2HxkGmHofUWaI4hDfCcm2G5IAAM1kPAAGVGAALwJOp6O4BiGIFMjRCUA8pmCRxsKNCtA2DCkglKCtQngbg1AJX0jFCZY1RwNTbgYxhYliLQdOxEDVKLd1XHQNRGA05krMYKiU3dDViGdP13MIjyPMgXj+OQMibC89zICU2JuC0lREGYHJzL9A8gsPBL3V8gStD7AB2JzvNC8LvAAYgsQq9yS4sSrQoL9Q8+K-UgaZ4CMijqBiQyKVULcexQ6r3QDertMa5rvBMe8OtKuKUxXdM1zaWLsTkxAGrySiWqgAByVAwBWgBqRcACoAFo9E2laNu2m9Tx2qwjrAdATt2w7jq2jtzrqK7dDAN7Hlum8Fx2x4XuOt6bse76dvur6Cme3RXvesBPuBgofr2v6oYBlbOqLTYXUqiBqt9HwgyzObl0U5SzOCjTlSM2LYsY-TluM25TKpkrIEs6zbIpPxrMcmbbgDR40roAAOLLsRciSSs8yWjBS-y0tFmqcoiyBlCipteZnaWGeC2WAroABOBX3SV7xXGQANiqS7GgvKrzrcaLq3jqhaoiaqjWq7EbHexHqXaWwa73wL2MfGy8jlASAib6xa3eWyA1vB05EbB+Gzx2-7rsT5AfpT06IfTlGYY+rOfuR6GKCzyGrqBvOk9BwvU+QKuAZhuHa+z-ay5bivG-Ova6nR9z7dGnGSSkgnvCJh0lRkJSVOZmqKYihmaed6PXYGj32pqTqssgX31-9ikhqDneR-Kb360mq9CMjql5sP2PvATxvk4b9vm8z1-66u3uC+h4u38u4wxrndd+T1-4t0Ae3RGwDdBozojTPSBk3JBW1rcZYSx-x4CpDSMAABeQhG1ILQTRkbKATNtIa1uGzGyYQ7Lc0MuQow4tUFa2oclPiqUcCBWlrcE2rU1YxT4YgkR6CdZcLljwugNRmFvAEVAM2oRLYlUvl5cRNVdZaEeHI7ECiVZCJUVbDhqFqHDwdgrDRxEsEUgAtSWABCiErTguFY6AAyNxYA8wWjrMFShUsWa0I5hBeyPNpbQjFBLdhIiZaSICro-h3AwrK1VtFIxCU1EeQ0ZwvyetZEmL0Uk3KnNkIFNEXw7JbwtFxgSUYfRqT1YiPMR5W2FVeaZL2CzfxlTWZczoWRPooSmEmIia5L8YiymxNyfLSZUB6mGLKR0v0lTsTVPejI2pcyinKzytoPZ6SKoJJWbcNZOjZkhW2d4Bpwi+HNPcq0u27TYoPP3FjMsklIwT1kvfYms9SYL3dEvAFfoaZLDcI4VSFCbTeDzA4S05Tgpgu4BCzcmhH6bygELHaHZd6r16uRGOGKVaezPpk-e+LgD9XdrgQOI5SUhyLBNRs4caZRwJRval8d1rfz2hYcBZ1frpWriXC6-L87xgAbDEVQtC7wMHnFN5mtEpvGkoTH508SbzyoeTMIlNtUeRpmKBwzALbR38X2fWogEU1TXuyo+KgSW4q8uSv2T9j60uDkPUO18ybeTZZSwlnKX4wP2pdB6H99oZ1ASDMNlcLqiElW3Xa+tZVgB7hGvlwrv6xr-s8RNIq9opteggslyDlrJASlYzBAy7F4MIfg4hcoBhkOoTiaF+rAl9OCYMxhvjvL80Fvk8JrDxkVPOWs3hIiLnJKuQsppRzx1xMFobc5+ilFyEWSYl5Q92mWNbdW7BuCHH1o2i4lw7jPHeILH2903SRlBPoZzIZN6aoDukUOyWoyomS2OVM7h71NnTuKZFNJiyF0xMdEu6RK6INAeViELwm7pbboVRkvdXT20BKSr0+y3a+lhM-W+9ZH6WYjrABWsdsGJ2AfmaB+dZTf2QemdBmjlyKS7P2UhyWKGHZPK8ih4e1tKqlnWEAA)

If you change the satus property, the color of the light will change accordingly.
As the light use gradient, I wasn't able to bind the gradientstop to a color or a scale. I had to create some tests copy/pasting the gradient. It should be really nice to be able to bind to a signal or use a scale on gradientStop colors.

**Comment by jheer** [comment]
Gradient definitions do not support the use of signals inside of them when provided as a `value` in an encoding. However, you can define gradients separately as `signal` values, which in turn can reference other signals. Here is [a modified animated light example](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwANgAMuxREgpG1fFoAsog0sjt08ANbUATt1Yy1WyHhfoZsIToLsgyeAq2sKYy6AA2sFoA2koQoBDpUDGoyNiQCHHIAOrqmoYZUIwyzLkATPoR5VDslV5YwJCVhKzhWJB+MtQ58lColdjWw5AYAB5aegZQsHjIhFrWAL4pYOtlqVtGWTm9+bHIABLIpua76R1VPZAAjNYN5XYt2O2d3bn9gwojMZYCYjdCzHBWBZ5ZarHAbLY7LZpN6Hbx4ZinV4ZSAUOKsI5QSAIm7I7GonDQ9B4VgJG5GXGxfHeFweKoDLG3ZqeT53LoPWDIU7wcKTbiEdGyBI4RJ9VmVagAyDIFxuFyKpZiwjILwAXU2GURGVJt3JUHg3Fi3DVdKgrEIaipBMp1NgYAAvB6wAByFkyNnUL1gAD83tcyFCgZwSypNPdnq9ytVgYAZMmwOxYpVHMHvSE1JHvQBibQlr1Eg0k-aZdDZbyudBqRihEVVyB2h3LbzAeuN5s4H0NxhxL3DDXEaXAbgAMynArwOAW5stLn7ykQzGQXp2YEnM7nC7oNWGS6tOBPLm3u9nyHnYEex4tp+9a43W715fShvSxoONadPabMIag5Ix20dLsAL7XNB2HYYAE9HgPI8wDHEgwESK99zARdHxXZ912WLdhkwm8DwATgfZcz1w9Z32JJFW1NOxMxkRwQKgBkmRwXx8RtSBZCSKs9kabFkCoMIpR3IS3jwOCtTRRhsmtaTsRYNwCExHBHn0XQVO2G1sTAzsKQAQgzLMP0afVyh1eijUYv9chOIZWyMo4pkqAAKZzig0RBSDqXQ6AMZyLiuPBSGeILdAASks-SGMaSByTyeACgADXYtt7XA440tOXyWAC-Rgvir9hJRRy8oKABNLK3Kc-LzkuMwIqi0qESUHUykgDtMGlRLKtrClo2WWlW045BJMSKBfX9RVEytdU8E1bVIDAWyDS6nrnOm7bbHRPBNKk1TkGmHod0WaI4gUo6cgS7Ep1kPAAGVGAALwJOobn4vcbzWJQvymYJHD2+yktk+SKSCUpW1Cc01AJH9bmbZUtGRx7GFiWJ0b0+k8SRvHbkgsJmRgnGDJE6ExTBkS6faadrwuqFz28F9O3KunygZv7mboAB2SZWYpQsLDFyBrK59JNql7Y9M5pLpngdGruoGIcYpVQ-IC9aFbeODlZwYBVfV7wTFanW5bpvXQJy4yMapmHEBVvJro1qAvVQb0AGpnPSgAqABaPRvcDL1faamr-asUOwHQH2-f9kOw4j2r-bqWPdGwu8E6agPHgzwMs-j8PE+T3O08L7Os8eCvTgDwOC90TOyytkTNirSWHu-VtIadJ2svh7hEdxumlTCNGjb0vTICnLH3Yd7FJtH2WjBJi6+nJ9ix4QrQgoADkppLUME1ejV+pm96F3C2YInIba5nnL-I6-lzrEI4IlomIBlqWu6so+UAlYuyiGrG6msSj+WAt3HehtLquzAe7YwLV8CW3-p+Sm2UOxHFAJAAeRsTbgI9l7Uuecg7l1IZXZugYS6p3rknahddkBRyrlnGuTD86sLABQJhLDGG0LLowyhpw+GZ2zrXYRyAG5NzETwyRUdA51F1tJdBXdObIx8HJfuVJnZ8SHiPKeY9UZqkMVzSAwCCEINNhA7W0CH5GANiAt2ZsUERTsSozBDUp54J0U4xB3hPYcPIUIuhzD078KCRQ0Joii7iKCTI2JAiyFROcjE6uOdJHSNYa3exUA57Y3RlYohkB15f2tp3OyPcIZaO8APPRMgEaEyMRPExJ0zFLDcI4JGHECbeAzA4NiMCqYdO4F0wqztLGgOsVAfe-tnK60AeYuBxsilIK1kVOxizHGTOcRSc2qD3HW08XbHBM98HwKmcUwJmSg4WBCak-2jx+axySRlaO9zI6PMYWwjJoSA772+TklRFSKyDVUjU6Gvj6mNJXklYxsKqZigcMwT+ljl7kVEEMxWyzCFrMgWgrZOLVkuPCmgjx0ksG5TaWPc5KzLlIOuX825ohY7yKDlXV59CY4pwedy9JEimVkW+dw3h7yXlBL5Wy54Yj2E3MDkKluCyZ75IXsSik69gLoIgKozqP8QDrCAA).

**Comment by mathiastiberghien** [comment]
Thanks!
