### ISSUE TITLE
Using gradient color with test case generate warnings

### ISSUE THREAD

**Issue by mathiastiberghien** [vega/vega#2032]
In the sample: [animated light](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwANgAMuxREgpG1fFoAsog0sjt08ANbUATt1Yy1WyHhfoZsIToLsgyeAq2sKYy6AA2sFoA2koQoBDpUDGoyNiQCHHIAOrqmoYZUIwyzLkATPoR5VDslV5YwJCVhKzhWJB+MtQ58lColdjWw5AYAB5aegZQsHjIhFrWAL4pYOtlqVtGWTm9+bHIABLIpua76R1VPZAAjNYN5XYt2O2d3bn9gwojMZYCYjdCzHBWBZ5ZarHAbLY7LZpN6Hbx4ZinV4ZSAUOKsI5QSAIm7I7GonDQ9B4VgJG5GXGxfHeFweKoDLG3ZqeT53LoPWDIU7wcKTbiEdGyBI4RJ9VmVagAyDIFxuFyKpZiwjILwAXU2GURGVJt3JTVilUcHPpeIJvnxdKgsiS+3SxsaSqoYSlYDdjSgeAAnlq0YxsmqHe6WG4CJicI99LoXQaI7dWIQ1FSCZAAITsc0yS1J7YunXEpEuyDkvLwApWqBpjPLXKjGQAChORRKiFIdV0dAMHYuVzwpGefd0AEoicny+6qx2ABp1yANzO5DvFDTd3v96fpQ2uivzmunACay9XTeOJ-OlzMI7Hu4RSh1ZUgjcw0tnKPQ2W8S0zWkKwZfFvUSKAWRkNkFUmZVVXVPBNW1SAwFLA0XzfDswIw2x0TwWMfS2HxkGmHofUWaI4hDfCcm2G5IAAM1kPAAGVGAALwJOp6O4BiGIFMjRCUA8pmCRxsKNCtA2DCkglKCtQngbg1AJX0jFCZY1RwNTbgYxhYliLQdOxEDVKLd1XHQNRGA05krMYKiU3dDViGdP13MIjyPMgXj+OQMibC89zICU2JuC0lREGYHJzL9A8gsPBL3V8gStD7AB2JzvNC8LvAAYgsQq9yS4sSrQoL9Q8+K-UgaZ4CMijqBiQyKVULcexQ6r3QDertMa5rvBMe8OtKuKUxXdM1zaWLsTkxAGrySiWqgAByVAwBWgBqRcACoAFo9E2laNu2m9Tx2qwjrAdATt2w7jq2jtzrqK7dDAN7Hlum8Fx2x4XuOt6bse76dvur6Cme3RXvesBPuBgofr2v6oYBlbOqLTYXUqiBqt9HwgyzObl0U5SzOCjTlSM2LYsY-TluM25TKpkrIEs6zbIpPxrMcmbbgDR40roAAOLLsRciSSs8yWjBS-y0tFmqcoiyBlCipteZnaWGeC2WAroABOBX3SV7xXGQANiqS7GgvKrzrcaLq3jqhaoiaqjWq7EbHexHqXaWwa73wL2MfGy8jlASAib6xa3eWyA1vB05EbB+Gzx2-7rsT5AfpT06IfTlGYY+rOfuR6GKCzyGrqBvOk9BwvU+QKuAZhuHa+z-ay5bivG-Ova6nR9z7dGnGSSkgnvCJh0lRkJSVOZmqKYihmaed6PXYGj32pqTqssgX31-9ikhqDneR-Kb360mq9CMjql5sP2PvATxvk4b9vm8z1-66u3uC+h4u38u4wxrndd+T1-4t0Ae3RGwDdBozojTPSBk3JBW1rcZYSx-x4CpDSMAABeQhG1ILQTRkbKATNtIa1uGzGyYQ7Lc0MuQow4tUFa2oclPiqUcCBWlrcE2rU1YxT4YgkR6CdZcLljwugNRmFvAEVAM2oRLYlUvl5cRNVdZaEeHI7ECiVZCJUVbDhqFqHDwdgrDRxEsEUgAtSWABCiErTguFY6AAyNxYA8wWjrMFShUsWa0I5hBeyPNpbQjFBLdhIiZaSICro-h3AwrK1VtFIxCU1EeQ0ZwvyetZEmL0Uk3KnNkIFNEXw7JbwtFxgSUYfRqT1YiPMR5W2FVeaZL2CzfxlTWZczoWRPooSmEmIia5L8YiymxNyfLSZUB6mGLKR0v0lTsTVPejI2pcyinKzytoPZ6SKoJJWbcNZOjZkhW2d4Bpwi+HNPcq0u27TYoPP3FjMsklIwT1kvfYms9SYL3dEvAFfoaZLDcI4VSFCbTeDzA4S05Tgpgu4BCzcmhH6bygELHaHZd6r16uRGOGKVaezPpk-e+LgD9XdrgQOI5SUhyLBNRs4caZRwJRval8d1rfz2hYcBZ1frpWriXC6-L87xgAbDEVQtC7wMHnFN5mtEpvGkoTH508SbzyoeTMIlNtUeRpmKBwzALbR38X2fWogEU1TXuyo+KgSW4q8uSv2T9j60uDkPUO18ybeTZZSwlnKX4wP2pdB6H99oZ1ASDMNlcLqiElW3Xa+tZVgB7hGvlwrv6xr-s8RNIq9opteggslyDlrJASlYzBAy7F4MIfg4hcoBhkOoTiaF+rAl9OCYMxhvjvL80Fvk8JrDxkVPOWs3hIiLnJKuQsppRzx1xMFobc5+ilFyEWSYl5Q92mWNbdW7BuCHH1o2i4lw7jPHeILH2903SRlBPoZzIZN6aoDukUOyWoyomS2OVM7h71NnTuKZFNJiyF0xMdEu6RK6INAeViELwm7pbboVRkvdXT20BKSr0+y3a+lhM-W+9ZH6WYjrABWsdsGJ2AfmaB+dZTf2QemdBmjlyKS7P2UhyWKGHZPK8ih4e1tKqlnWEAA)

You can see a lot of warning: the fill property of some path is using an array (using tests): it is rendering fine, so the warnings seems inappropriate

**Comment by jheer** [comment]
Thanks that appears to be a schema validation problem. We will investigate...

**Comment by jheer** [comment]
I've merged fixes to the schema generation logic, for inclusion in the next release. Thanks again!
