### ISSUE TITLE
Unexpected positioning of image if one of width or height not specified

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega#2033]
I think this straddles the boundary between 'bug' and 'feature' but given the behaviour is unintuitive, I've labelled it as a bug.

If only one of an image's width or height is specified and that is different to an image's native dimension, the image is positioned in an unexpected location. For example the images used below have a native size of 100x100 pixels but have been specified with a width of 25 pixels. This results in them being vertically aligned as if they were 25x100 pixels even though the aspect ratio is preserved. The appearance is therefore that they have been incorrectly positioned on the vertical axis.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {
        "x": 0.5,
        "y": 0.5,
        "img": "https://vega.github.io/vega-lite/data/ffox.png"
      },
      {
        "x": 1.5,
        "y": 1.5,
        "img": "https://vega.github.io/vega-lite/data/gimp.png"
      },
      {
        "x": 2.5,
        "y": 2.5,
        "img": "https://vega.github.io/vega-lite/data/7zip.png"
      }
    ]
  },
  "encoding": {
    "x": {"field": "x", "type": "quantitative"},
    "y": {"field": "y", "type": "quantitative"},
    "url": {"field": "img", "type": "nominal"}
  },
  "mark": {"type": "image", "width": 25, "aspect":true}
}
```

<img width="258" alt="imagePosition" src="https://user-images.githubusercontent.com/1846999/64100596-cf024680-cd63-11e9-9841-1df7fde8b105.png">

It would make more sense that if only one of `width` or `height` is specified and `"aspect":true`, that the unspecified dimension is calculated from the aspect ratio of the image and the provided dimension (an implicit `"height":25` in the example above).

The unintuitive behaviour is also seen when the native dimensions of an image are not square. In the example below, I would argue it makes more sense for the `"baseline":"bottom"` to refer to the actual bottom of the image, not square implied by `width` and `height`:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"values": [{"x": 5, "y": 5}]},
  "layer": [
    {
      "encoding": {
        "x": {
          "field": "x",
          "type": "quantitative",
          "scale": {"domain": [0, 10]}
        },
        "y": {
          "field": "y",
          "type": "quantitative",
          "scale": {"domain": [0, 10]}
        },
        "url": {"value": "https://gicentre.github.io/data/images/LillyTarn.jpg"}
      },
      "mark": {
        "type": "image",
        "width": 100,
        "height": 100,
        "baseline": "bottom"
      }
    },
    {
      "encoding": {
        "x": {"field": "x","type": "quantitative"},
        "y": {"field": "y", "type": "quantitative"}
      },
      "mark": {"type": "circle"}
    }
  ]
}
```

<img width="251" alt="nonSquare" src="https://user-images.githubusercontent.com/1846999/64101051-e4c43b80-cd64-11e9-993e-5e5d7b820ef4.png">

**Comment by jheer** [comment]
Thanks for the issue! I've fixed the underlying behavior in Vega, for inclusion in the upcoming 5.7.0 release. Now, if one of width or height is defined and the other is not (and assuming `aspect` is true), then the actual image file aspect ratio will be used to determine the undefined width or height.

@kanitw: I believe Vega-Lite will need to change to take advantage of this update. The generated Vega code for the first example provided generates both `y` and `y2` channels (one anchored at a zero value...) when the height is not defined, which will result in the height property being set (improperly) on the Vega scenegraph items. I think this is a mistake and should be fixed.
