### ISSUE TITLE
Apply cornerRadius to the top-level background

### ISSUE THREAD

**Issue by kanitw** [vega/vega#2043]
Is there a way to apply `cornerRadius` to the top-level `background` property? 

If not, would adding `cornerRadius` to the top-level property a sensible thing?

**Comment by jheer** [comment]
Not really. The top-level background is not a mark, it is the global background color. Different renderers might realize that in different ways, of course. For canvas it is the background color of the raster.

In Vega one could always add a rect mark with dimensions matching the width and height signals...

Or perhaps you could use CSS to style the Vega HTML elements (either the container div or canvas/svg element)?
