### ISSUE TITLE
Inconsistent merge logic for configs

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2045]
Configs are often used as themes. In a specific Vega spec, one might want to further customize the config and override specific properties. We use this functionality in Vega-Lite, the editor and Vega-Embed. However, with the new [signals in the config](https://vega.github.io/vega/docs/config/#signals) it becomes unclear how to correctly merge configs.

Specifically, when merging two arrays there are two options. 1. overwrite the array and 2. union the arrays. We think that 1 is what a user wants for all properties except the signals. Signals should behave more like a map than an array.

I'm going to send a PR to add a function to merge configs to Vega-Util. 

cc @kanitw @arvind @jheer

**Comment by jheer** [comment]
Totally agree that Vega should export a `mergeConfig` utility for external use. This method should probably mirror the existing merge implementation in vega-parser, which we could pull out to vega-util. See my review of #2047 for more.
