### ISSUE TITLE
Derived Data Streams not recalculated as expected

### ISSUE THREAD

**Issue by anagrius** [vega/vega#2048]
I have an issue, where when I base one data set on another using `source:` the data in derived stream reverts to the original object (in the source I derive from).
 
I have made an example that demonstrates my issue (See explanation below):

https://vega.github.io/editor/?#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAguuTowSdOrxhYibgHdGM6mDvJG1fGG4AzMxdheVOpgOqjIdApKkOiseNywjABeyNhQhOjKkRCQ6crKjtSpoorZDsosqQDMAAzVJbhuHnipAEy19ZAJ1DLoADawqWAA2koQwFA9YamQ3tzcClAUfawpOHjqK-JQ7I6ZOMCQjoSx2JBIyPAA1uzcAB6QAL5gD0oAuh3K6HiYOCMQY6N-pBJqsoNJWOp4MgAPrVLL-bJLXorAa-QEIg73HAARi2kCRK1S2Ie9QRY0gWLALTxBNBlRJ6P+mKqNOWoIAtMTGe9GZB1ugZLBZupUKk-mTyXgAJ6EUEzbgi1i9TCkiWQZC3QjqaazeaqsnRVFQXWQRn-F4S16AhkY3kg6bgyEw7HwhGdbgQqEOj1O2GuoH8wXC0VoiUAsMBmVy7yMXp4ZDa-UGjVa6afPCsVB0WlgAA8YDhYDNzyT4YjUGlsp1CtQSpVxeyKe1+mxcNLQPQRvxbMgRYjFrJVoRNqZdvQU30Em4jmQmST7s9oKGC99Lrxjqhfp5asDQprYuLoHLFaj03g3F6vQuzXb2WkllS4xmjGQvT2wwpkHeUAVqmbH87KEZHyJwvwHCURwlI9yz5U99BjOME39NUm2mOwLBkAAKdNMzoW4thwrNaS2dYVgASlNftuWtQE3hAB4gA

I have two datasets `source_0` and `source_1`, where `source_1` is derived from `source_0`.
Then the two are joined in the dataset called `joined`.

`source_1` only contains the items that have value < 0 (in this case only x=3), and sets their value=10.

I therefor expect “joined” to contain 4 elements, where the two entries with x=3 have values -1 and 10.

That is exactly what happens.. until I toggle the signal foo. After this signal is set. BOTH values get set to -1, where I would have expected them to remain -1 and 10.

While if I DON'T derive the data in “source_1" from “source_0”. Then there is no problem:

https://vega.github.io/editor/?#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAguuTowSdOrxhYibgHdGM6mDvJG1fGG4AzMxdheVOpgOqjIdApKkOiseNywjABeyNhQhOjKkRCQ6crKjtSpoorZDsosqQDMAAzVJbhuHnipAEy19ZAJ1DLoADawqWAA2koQwFA9YamQ3tzcClAUfawpOHjqK-JQ7I6ZOMCQjoSx2JBIyPAA1uzcAB6QAL5gD0oAuh3K6HiYOCMQY6N-pBJqsoNJWOp4MgAPrVLL-bJLXorAa-QEIg73HAARi2kCRK1S2Ie9QRY0gWLALTxBNBlRJ6P+mKqNOWoIAtMTGe9GZB1ugZLBZupUKk-mTyXgAJ6EUEzbgi1i9TCkiWQZC3QjqaazeaqsnRVFQXWQRn-F4S16AhkY3kg6bgyEw7HwhH4tlG8US5k4Sqs5EcrmW-VQfmC4WitESgHRoHS2U6xi9PDIbUht0arXTT54VioOi0sAAHjAcLAZue6bAoFj2XjcojSpVFeyme1+mxcKr2XQRvdAcg5djFrJVoRNqZdvQU30Em4jmQmRDnW4EKhYpXa+dC03TthkB5arDQoVkeGFZrtb5Mrl8G4vV6F2a3bBCua+2NjGQvT2wwpB7xBVVHbP9eyhGR8icA8RwlCdvRbUMb0TZNU1daN1U1EDIDsCwZAAChzPM6FuLZCPzWktnWFYAEpTWHblrUBN4QAeIA

Am i missing something about how streams are updated or is this a bug? I am guessing it is because I am actually modifying the underlying data object in the first example. Is there a way to avoid that?

The only way I have been able to produce the results I expect is by using an aggregate transformation that emits a new row per input row (by grouping by a unique property). This preserves the value in the joined dataset:

https://vega.github.io/editor/?#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAguuTowSdOrxhYibgHdGM6mDvJG1fGG4AzMxdheVOpgOqjIdApKkOiseNywjABeyNhQhOjKkRCQ6crKjtSpoorZDsosqQDMAAzVJbhuHnipAEy19ZAJ1DLoADawqWAA2koQwFA9YamQ3tzcClAUfawpOHjqK-JQ7I6ZOMCQjoSx2JBIyPAA1uzcAB6QAL5gD0oAuh3K6HiYOCMQY6N-pBJqsoNJWOp4MgAPrVLL-bJLXorAa-QEIg73HAARi2kCRK1S2Ie9QRY0gWLALTxBNBlRJ6P+mKqNOWoIAtMTGe9GZB1ugZLBZupUKk-mTyXgAJ6EUEzbgi1i9TCkiWQZC3QjqaazeaqsnRVFQXWQRn-F4S16AhkY3kg6bgyEw7HwhGdbgQqEOj1O2GuoH8wXC0VoiUAsMBmVy7yMXp4ZDa-UGjVa6afPCsVB0WlgAA8YDhYDNzyTTOL2Wlsum6Go1GMtHj-rVdY9hHYUrFFMgPIj2RjyF6yiNQ3xbIW8vmPd7kG4xE7GHueIX3dLQPQw9HyJSeJNVojNrDoF7UEr0YVqCVKvLUBT2v02Lhq+y6+mtMgRf33OtqqPBvt+gkbhHGQTIk3dT1QRHR0oWhF08WgmE4SnN1AyFc8xWLX8Iz5KNpngbhel6C5mifMEFWafZjUYAc9mGLt3igBVVDvOj1yhGR8icbsLTDA8JSwsMcKrfQYzjBMm2TTUWMgOwLBkAAKdNMzoW4tiUrNaS2dYVgASlNT9LWtQE3hAB4gA

**Comment by jheer** [comment]
Thanks for the issue! You triangulated an "interesting" interaction between how Vega handles derived tuples and the formula transform implementation. I added bug fixes for each, for inclusion in the next Vega release.

**Comment by anagrius** [comment]
Great thanks!
