### ISSUE TITLE
Allow comment properties in every element

### ISSUE THREAD

**Issue by anagrius** [vega/vega#2050]
Specs can become very large and hard to read for others - and even yourself.
Since JSON does not allow comments, I suggest that vega could allow every element (data, transform, marks, etc.) to have a `comment` property and still satisfy the JSON schema.

This will allow better readability and maintenance.

E.g.

```json
{
   "comment": "We need to filter out elements below zero to avoid graphic artifacts.",
   "type": "filter",
   "expr": "..."
}
```

**Comment by jheer** [comment]
Thanks! Currently, `signal` definitions and the top-level spec permit a `"description"` property for comments. We could certainly extend this to other elements of the schema.

**Comment by anagrius** [comment]
That would be very useful, since you often have to do "tricks" that would be nice to explain.

**Comment by ethn** [comment]
It's potentially confusing that the top-level "description" field shows up in aria labels (ie, is user-facing) and the signal "description" field is explicitly for inline documentation (ie, is for developers). I would recommend deprecating the "description" field on signals and allowing "comment" fields in pretty much every element type.
