### ISSUE TITLE
Circle pack sorting does not work

### ISSUE THREAD

**Issue by csabapocsai** [vega/vega#2054]
Hi,

I am using the following code:
`{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 800,
  "height": 800,
  "autosize": "pad",
  "data": [
    {
      "name": "tree",
      "values": [{"id": 1, "name": "", "parent": null, "relative_abundance": 100}, {"id": 170, "name": "Prevotella copri DSM 18205", "name_and_abundance": "Prevotella copri DSM 18205: 26.97 %", "parent": 1, "relative_abundance": 26.9748}, {"id": 86, "name": "Bacteroides vulgatus PC510", "name_and_abundance": "Bacteroides vulgatus PC510: 4.36 %", "parent": 1, "relative_abundance": 4.3610999999999995}, {"id": 144, "name": "Faecalibacterium prausnitzii L2-6", "name_and_abundance": "Faecalibacterium prausnitzii L2-6: 4.15 %", "parent": 1, "relative_abundance": 4.1535}, {"id": 159, "name": "Bacteroides sp. 4_3_47FAA_u_t", "name_and_abundance": "Bacteroides sp. 4_3_47FAA_u_t: 3.76 %", "parent": 1, "relative_abundance": 3.7566}, {"id": 6, "name": "Ruminococcus sp. 5_1_39BFAA_u_t", "name_and_abundance": "Ruminococcus sp. 5_1_39BFAA_u_t: 3.09 %", "parent": 1, "relative_abundance": 3.0896}, {"id": 138, "name": "Sutterella wadsworthensis 2_1_59BFAA", "name_and_abundance": "Sutterella wadsworthensis 2_1_59BFAA: 3.02 %", "parent": 1, "relative_abundance": 3.0207}, {"id": 64, "name": "Blautia wexlerae DSM 19850", "name_and_abundance": "Blautia wexlerae DSM 19850: 2.91 %", "parent": 1, "relative_abundance": 2.9090000000000003}, {"id": 22, "name": "Bacteroides uniformis ATCC 8492", "name_and_abundance": "Bacteroides uniformis ATCC 8492: 2.83 %", "parent": 1, "relative_abundance": 2.8277}, {"id": 62, "name": "Bacteroides massiliensis B84634 = Timone 84634 = DSM 17679 = JCM 13223", "name_and_abundance": "Bacteroides massiliensis B84634 = Timone 84634 = DSM 17679 = JCM 13223: 2.41 %", "parent": 1, "relative_abundance": 2.4058}, {"id": 84, "name": "Bacteroides faecis MAJ27", "name_and_abundance": "Bacteroides faecis MAJ27: 2.15 %", "parent": 1, "relative_abundance": 2.1454999999999997}, {"id": 157, "name": "Bacteroides clarus YIT 12056", "name_and_abundance": "Bacteroides clarus YIT 12056: 2.08 %", "parent": 1, "relative_abundance": 2.0844}, {"id": 133, "name": "[Eubacterium] hallii DSM 3353", "name_and_abundance": "[Eubacterium] hallii DSM 3353: 1.86 %", "parent": 1, "relative_abundance": 1.865}],
      "transform": [
        {
          "type": "stratify",
          "key": "id",
          "parentKey": "parent"
        },
        {
          "type": "pack",
          "field": "relative_abundance",
          "padding": 7,
          "size": [
            {
              "signal": "width"
            },
            {
              "signal": "height"
            }
          ],
          "sort": {
            "field": "relative_abundance",
            "order": "descending"
          }
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "color",
      "type": "ordinal",
      "domain": {
        "data": "tree",
        "field": "depth"
      },
      "range": [
        "white",
        "#FFC9B3"
      ]
    }
  ],
  "marks": [
    {
      "type": "symbol",
      "from": {
        "data": "tree"
      },
      "encode": {
        "enter": {
          "shape": {
            "value": "circle"
          },
          "fill": {
            "scale": "color",
            "field": "depth"
          },
          "tooltip": {
            "signal": "datum.name + datum.relative_abundance"
          }
        },
        "update": {
          "x": {
            "field": "x"
          },
          "y": {
            "field": "y"
          },
          "size": {
            "signal": "4 * datum.r * datum.r"
          },
          "stroke": {
            "value": "white"
          },
          "strokeWidth": {
            "value": 0.5
          }
        }
      }
    },
    {
      "type": "text",
      "from": {
        "data": "tree"
      },
      "encode": {
        "enter": {
          "text": {
            "field": "name_and_abundance"
          },
          "fontSize": {
            "value": 8
          },
          "baseline": {
            "value": "middle"
          }
        },
        "update": {
          "x": {
            "field": "x"
          },
          "y": {
            "field": "y"
          },
          "dx": {
            "signal": "(datum.leftside ? -1 : 1)"
          },
          "angle": {
            "signal": "datum.leftside ? datum.angle : datum.angle"
          },
          "align": {
            "signal": "datum.leftside ? 'center' : 'center'"
          }
        }
      }
    }
  ]
}`

And it is providing something like that:
![image](https://user-images.githubusercontent.com/4962964/66261190-31b68a00-e7c9-11e9-9397-19cf55666dd7.png)

I would like to see and organized bubble chart, something like this:
![image](https://user-images.githubusercontent.com/4962964/66261142-7db4ff00-e7c8-11e9-8ec9-8da75e8d7807.png)

Is there any suggestion how to use this sorting functionality?

Regards,
Csaba

**Comment by jheer** [comment]
Thanks for sharing the issue. I double checked and found that the internal tree sibling nodes are indeed being sorted in the proper manner. Though you will want to set the sort field to `"value"` rather than `"relative_abundance"`, which is where the summed values for tree nodes are stored.

Moreover, if I copy your data over and use d3.js directly I get identical results to Vega. So I think the output is just what the pack layout produces given this specific dataset and parameters. If there happen to be any errors, you might submit an issue to [d3-hierarchy](https://github.com/d3/d3-hierarchy), which is what Vega uses. 

Here is the d3 code I used. You can copy and paste it into the browser console if you go to [d3js.org](https://d3js.org/):

```js
var data = [
  {"id": 1, "name": "", "parent": null, "relative_abundance": 100},
  {
    "id": 170,
    "name": "Prevotella copri DSM 18205",
    "name_and_abundance": "Prevotella copri DSM 18205: 26.97 %",
    "parent": 1,
    "relative_abundance": 26.9748
  },
  {
    "id": 86,
    "name": "Bacteroides vulgatus PC510",
    "name_and_abundance": "Bacteroides vulgatus PC510: 4.36 %",
    "parent": 1,
    "relative_abundance": 4.3610999999999995
  },
  {
    "id": 144,
    "name": "Faecalibacterium prausnitzii L2-6",
    "name_and_abundance": "Faecalibacterium prausnitzii L2-6: 4.15 %",
    "parent": 1,
    "relative_abundance": 4.1535
  },
  {
    "id": 159,
    "name": "Bacteroides sp. 4_3_47FAA_u_t",
    "name_and_abundance": "Bacteroides sp. 4_3_47FAA_u_t: 3.76 %",
    "parent": 1,
    "relative_abundance": 3.7566
  },
  {
    "id": 6,
    "name": "Ruminococcus sp. 5_1_39BFAA_u_t",
    "name_and_abundance": "Ruminococcus sp. 5_1_39BFAA_u_t: 3.09 %",
    "parent": 1,
    "relative_abundance": 3.0896
  },
  {
    "id": 138,
    "name": "Sutterella wadsworthensis 2_1_59BFAA",
    "name_and_abundance": "Sutterella wadsworthensis 2_1_59BFAA: 3.02 %",
    "parent": 1,
    "relative_abundance": 3.0207
  },
  {
    "id": 64,
    "name": "Blautia wexlerae DSM 19850",
    "name_and_abundance": "Blautia wexlerae DSM 19850: 2.91 %",
    "parent": 1,
    "relative_abundance": 2.9090000000000003
  },
  {
    "id": 22,
    "name": "Bacteroides uniformis ATCC 8492",
    "name_and_abundance": "Bacteroides uniformis ATCC 8492: 2.83 %",
    "parent": 1,
    "relative_abundance": 2.8277
  },
  {
    "id": 62,
    "name": "Bacteroides massiliensis B84634 = Timone 84634 = DSM 17679 = JCM 13223",
    "name_and_abundance": "Bacteroides massiliensis B84634 = Timone 84634 = DSM 17679 = JCM 13223: 2.41 %",
    "parent": 1,
    "relative_abundance": 2.4058
  },
  {
    "id": 84,
    "name": "Bacteroides faecis MAJ27",
    "name_and_abundance": "Bacteroides faecis MAJ27: 2.15 %",
    "parent": 1,
    "relative_abundance": 2.1454999999999997
  },
  {
    "id": 157,
    "name": "Bacteroides clarus YIT 12056",
    "name_and_abundance": "Bacteroides clarus YIT 12056: 2.08 %",
    "parent": 1,
    "relative_abundance": 2.0844
  },
  {
    "id": 133,
    "name": "[Eubacterium] hallii DSM 3353",
    "name_and_abundance": "[Eubacterium] hallii DSM 3353: 1.86 %",
    "parent": 1,
    "relative_abundance": 1.865
  }
];

var t = d3.stratify().id(_ => _.id).parentId(_ => _.parent)(data);
t.sum(_ => _.relative_abundance);
t.sort((a, b) => b.value - a.value);
d3.pack().size([800, 800]).padding(7)(t)
```
