### ISSUE TITLE
Top level `title` prop alters layout `spacing`

### ISSUE THREAD

**Issue by johnmdonich** [vega/vega#2058]
When adding a top-level `title` prop to a faceted chart it expands the `facet.spacing` so that the title fits into the first facet column and expands the spacing across all of the column facets

This can be seen using the [Grouped Bar Chart Example with a title added](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gUVgCcx2LTvSlC3QqzE6eS+YpUBfdREh4j6JbABm3EaoZgDaGhDAkP6MYnjIRmaQ2nisqHQAnsjoRmAAvHlgAEwADGWQ7hFgUfDoYvB2OshJKWl0sMgAHvmFRWAA-GAA5ABiaHXIQ2A4QwCyE0NqUOiwSdTISpoJFRoAuh5QAO6MmixmUbDxhGYAjEWVnhhGANZJ7DlqGl7MYs04kAAVH7IMCMWBgZ6MTboMBiZTUT6eDbwbiaKEI-RVSAosRpFSYiCEqAxZBiTRJdDrJZeDKEP5QIJopR1amwQjoeDo24lKoPQmQDLnKqeSnUIzCeJJWBpakkslJOk2X7UvC0+mQACOrF8eGYDioiKJy06YPO3zwyv+1ls9l1ympYpOZn8dQ6rl5B08nSFRuJjFJ5P+60221UUFVdKSSm4qChLM9-PQJtW+nNlqgOyJfM8OKCPqN0X98qDGy2iTDNMj-2jseZpgTngQEzNPiUVJwoUgAGIAKIAQQAnAAOAAiRWpXYAbABWAcAYTnfcgu3dWY0fOxyhiGOqWIo-sOZsuRm4z3V3l8bJyGzwFQTkCTptTmhj6ChAHUTmccDdV2B3e6QA)

![grouped-column-with-title](https://user-images.githubusercontent.com/2266667/66231080-92ec3980-e6b3-11e9-9e17-8d9bdef84f6e.png)

The spec looks like this:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": { "url": "data/population.json"},
  "transform": [
    {"filter": "datum.year == 2000"},
    {"calculate": "datum.sex == 2 ? 'Female' : 'Male'", "as": "gender"}
  ],
  "width": {"step": 12},
  "mark": "bar",
  "title": "Title is kinda long",
  "encoding": {
    "column": {
      "field": "age", "type": "ordinal", "spacing": 10
    },
    "y": {
      "aggregate": "sum", "field": "people", "type": "quantitative",
      "axis": {"title": "population", "grid": false}
    },
    "x": {
      "field": "gender", "type": "nominal",
      "axis": {"title": ""}
    },
    "color": {
      "field": "gender", "type": "nominal",
      "scale": {"range": ["#EA98D2", "#659CCA"]}
    }
  },
  "config": {
    "view": {"stroke": "transparent"},
    "axis": {"domainWidth": 1}
  }
}
```

**Comment by kanitw** [comment]
I'll move this to Vega for now.

**Comment by jheer** [comment]
Thanks for the issue! This is a bug that was accidentally introduced with recent changes to the title/subtitle functionality (5.7.0). Fortunately it is easy to fix and a patched version will be released soon.
