### ISSUE TITLE
Schema incorrect for custom title encoding?

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega#2071]
Apologies if I have misunderstood how the new (Vega 5.7) title encoding is supposed to be specified, but encoding one or more of `title`, `subtile` or `group` results in a schema validation warning `Matches multiple schemas when only one must validate.`.

Here is a [simple example](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAFgAMuxREh5mAG2RbQEI3mQAPPFsgBBMCbzmFSo7A7vPWC5gvuz+FobWkOgySNwATtiQsHjocY4RRuimjNRygfDIMrYJGVCF8NxqFljAYN6RYdhW1i2QhcWW9S1GAGaMpqZNkBRZrNVJtsim7KZjkAC+Xdbzpa2shGrotp3d3ZBqdkOwOTJZiQcLSxCLuytLSX5m1WDNu21FyAk4r7tQfQNDEazcZ9OLIdhxRjwADWl1+YDu8Mg60222+V0iFxqSROZ0CFxu8IxhJaiL21Di3HWTQx7w66PhkX+g2+w1Gz0gAGI1DyFqs3qoNIhAezsHpdGTGZAUDl8CLgdgAMwS4lLEkIpSSnG5LKwLQAbXqtUgp1QHIu8igQLmOAATPp+ZB2IwZGpLJAXYRWI4cJA4tFqOEoKgXdgDMH0IccOLLRNkIQtABGeYaiAAXRA8yAA)

Is this because the schema should be `anyOf` rather than `oneOf` for the title encoding properties (thanks to @domoritz for suggesting this might be the case) ?

Relatedly, it took me a while to work out how exactly to specify a title component's encoding (and I still may have misunderstood how to specify them correctly), so perhaps there is scope to include a simple example in the [custom title encodings page](https://vega.github.io/vega/docs/title/#custom).

**Comment by jwoLondon** [comment]
Thanks @jheer .

Shouldn't the example, now added to the doc page, assign an object to `title` rather than an array of objects?

**Comment by jheer** [comment]
Yup. 🤦‍♂ Fixed.
