### ISSUE TITLE
'cumulativeLogNormal' is not exported from 'vega-statistics' with Vega v5.7.2

### ISSUE THREAD

**Issue by eeyshen** [vega/vega#2076]
There is a compilation error with vega v5.7.2:

Attempted import error: 'cumulativeLogNormal' is not exported from 'vega-statistics'.

**Comment by jheer** [comment]
Thanks for the issue, but I am unable to replicate the error.

1. If I install either `vega-statistics` or `vega` from npm, the method is included.
2. If I check out a fresh copy of Vega from GitHub, the build has no issues.
3. If I go to the [Vega website](https://vega.github.io/vega/) and open the console, the method is included.
4. You can confirm that method is exported from vega-statistics [here](https://github.com/vega/vega/blob/master/packages/vega-statistics/index.js#L14).

Is it possible your project settings are stale? For example, if you clear your node_modules and package lock files and reinstall, do you still see an error?

**Comment by eeyshen** [comment]
Sorry. It is caused by stale package lock file. Thanks for quick response.
