### ISSUE TITLE
KDE bandwidth estimation can produce zero value

### ISSUE THREAD

**Issue by colececil** [vega/vega#2085]
When using the `randomKDE()` function from vega-statistics and having Vega estimate the bandwidth, it is sometimes coming up with a bandwidth of 0. This is causing me to get `NaN` back when calling the resulting distribution's `pdf()` method. Here is an example of a situation where this happens:

```javascript
const distribution = vega.randomKDE([377, 347, 347, 347, 347, 347]);
console.log("PDF value: " + distribution.pdf(350));
console.log("bandwidth value: " + distribution.bandwidth());
```

When running this, I get the following log output:

```
PDF value: NaN
bandwidth value: 0
```

I found a website [here](https://www.wessa.net/rwasp_density.wasp) that does kernel density estimations, and I tried inputting the same values there. It was able to draw a chart that looked correct, and it came up with a bandwidth value of 7.70296436734367. When I tried entering this as a second parameter in `randomKDE()`, it then worked as expected. So I'm assuming this is just an issue with the code that estimates the bandwidth.

I am using version 1.6.0 of [the vega-statistics NPM package](https://www.npmjs.com/package/vega-statistics). I don't know what version that corresponds to in the git repository, but I'm assuming that is the latest version of vega-statistics.

**Comment by jheer** [comment]
Thanks for raising the issue. Vega's KDE implementation uses [Scott's rule (heuristic) for automatic bandwidth determination](https://github.com/vega/vega/blob/master/packages/vega-statistics/src/kde.js#L56), which goes to zero if the variance is zero or if the lower and upper quartile boundaries are identical (as in your example). We should definitely makes this more robust.

**Comment by jheer** [comment]
It looks like the 7.70296... arises by simply ignoring the quantile term when it is zero. The R method used in the linked website uses a different scale factor (0.9 rather than 1.06), but is otherwise the same (as per https://stat.ethz.ch/R-manual/R-patched/library/stats/html/bandwidth.html). I will update the Vega method to similarly rely on the variance term when the quantiles coincide.

**Comment by jheer** [comment]
Vega 5.7.3 (and vega-statistics v1.6.1) have been released!
