### ISSUE TITLE
how add page bottons to legend？

### ISSUE THREAD

**Issue by xuanhun** [vega/vega#2092]
When there are too many legends, we need to turn pages，like this：
![image](https://user-images.githubusercontent.com/2384516/67174070-5cbcf280-f3f3-11e9-875c-6318e38268e5.png)
![image](https://user-images.githubusercontent.com/2384516/67174088-69d9e180-f3f3-11e9-9d0e-0d816714f0e7.png)

I try to do it by group marks，but it war hard to filter data by index of a data

**Comment by kanitw** [comment]
FWIW, if you're having that many colors, you should also revise if using colors and legend is an effective choice.

**Comment by xuanhun** [comment]
> FWIW, if you're having that many colors, you should also revise if using colors and legend is an effective choice.

I know that ，but I was asked to do that.

**Comment by xuanhun** [comment]
I have achieved it by using custom marks
