### ISSUE TITLE
How to load data from another source?

### ISSUE THREAD

**Issue by win32nipuh** [vega/vega#2097]
How to load data from a database or AJAX request instead of reading it from a file like here:

```
 vega.loader().load('../../sample-data/demovote.tsv').then(function (text) {
        var data = vega.read(text, { type: 'tsv' });
        scatterplotTest.viewer.render(options, data);
    });
```

**Comment by danmarshall** [comment]
This load() function *is* an ajax request. https://github.com/vega/vega/tree/master/packages/vega-loader#load
