### ISSUE TITLE
Color opacity discrepancy between SVG and Canvas

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2110]
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28},
      {"a": "B", "b": 55},
      {"a": "C", "b": 43},
      {"a": "D", "b": 91},
      {"a": "E", "b": 81},
      {"a": "F", "b": 53},
      {"a": "G", "b": 19},
      {"a": "H", "b": 87},
      {"a": "I", "b": 52}
    ]
  },
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  },
  "layer": [
    {"mark": {"type": "bar", "opacity": 0.5, "color": "red"}},
    {"mark": {"type": "bar", "opacity": 0.5}}
  ]
}
```

[Spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJhYjVITHIw7dLrBIneMAHdmiMGnbJNbU0wTXQ8ejUNSFDw7DBQCAhICnQxVh04gG0NRPjITFMzNSh2OIAmAA4AX3VciGB8uMgAIWLIUpwAVk6anMSGgqgAYTaOsGkAZl66vMHIABFRuIBOAEZpuoGmgFElnAr12s3G0wAxPbBOqaPcrdMAcQvV5Y3bk6gACQuKgHZX-vekAAkhdOmUqn0ALoaDaQZBKeDcTSMJTUOIJRKQAAe6MgADNGMgxJomphVFA8ABPQjIJrcXTIpSpSD-SCU3EEokk0ylcmQKk0poAR1Y6CURnCRioLJhR0gYnQlOQuiyfQaGF0AGtcQLaTynG1uIR0PBmOycAAGOidPmIsT0pq6AIs-7qpzanANXVNRwqvlGk1muJWnoQiDQqpAA)

SVG:
<img width="244" alt="Screen Shot 2019-10-28 at 12 02 39" src="https://user-images.githubusercontent.com/589034/67709270-da947700-f97a-11e9-9ff6-472185ee3c3d.png">

Canvas:
<img width="240" alt="Screen Shot 2019-10-28 at 12 03 01" src="https://user-images.githubusercontent.com/589034/67709294-e718cf80-f97a-11e9-8798-e8b9cde56ef6.png">

Chrome 78.0.3904.70

**Comment by jheer** [comment]
I'm not sure this is a Vega issue, as opposed to a browser-level issue. If you directly set the color using `rgba` you can still see compositing differences in the output (using of SVG `fill-opacity` style or Canvas `globalAlpha`, as Vega does, produces similar results). As Canvas and SVG are different rendering systems, they may have slightly different default compositing pipelines.

Here is an example:
```html
<canvas width="200" height="200" style="width:100px; height:100px;"></canvas>
<svg width="100" height="100">
  <line x1=0 y1="50.5" x2=100 y2="50.5" stroke="grey"/>
  <rect x="10" y="10" width="80" height="80" fill="rgba(255, 0, 0, 0.5)"/>
</svg>
<script>
var ctx = document.querySelector('canvas').getContext('2d');

ctx.strokeStyle = 'grey';
ctx.lineWidth = 2;
ctx.beginPath();
ctx.moveTo(0, 2*50.5);
ctx.lineTo(2*100, 2*50.5);
ctx.stroke();

ctx.fillStyle = 'rgba(255, 0, 0, 0.5)';
ctx.fillRect(2*10, 2*10, 2*80, 2*80);
</script>
```
