### ISSUE TITLE
flatten transformation should create index field

### ISSUE THREAD

**Issue by Timmmm** [vega/vega#2114]
From the [`flatten` example](https://vega.github.io/vega/docs/transforms/flatten/):

> Input data:
> 
> ```
> [
>   {"name": "alpha", "data": 123, "foo": [1, 2]},
>   {"name": "beta",  "data": 456, "foo": [3, 4, 5]}
> ]
> 
> ```
> 
> Result:
> 
> ```
> [
>   {"name": "alpha", "data": 123, "foo": 1},
>   {"name": "alpha", "data": 123, "foo": 2},
>   {"name": "beta",  "data": 456, "foo": 3},
>   {"name": "beta",  "data": 456, "foo": 4},
>   {"name": "beta",  "data": 456, "foo": 5}
> ]
> ```

It would be infinitely more helpful if the result were:

```
[
  {"name": "alpha", "data": 123, "foo": 1, "index": 0},
  {"name": "alpha", "data": 123, "foo": 2, "index": 1},
  {"name": "beta",  "data": 456, "foo": 3, "index": 0},
  {"name": "beta",  "data": 456, "foo": 4, "index": 1},
  {"name": "beta",  "data": 456, "foo": 5, "index": 2}
]
```

**Comment by domoritz** [comment]
You can add the index with an additional window transform. Would that solve the problem for you?

**Comment by domoritz** [comment]
No, it’s not hard but the question is why it’s important to add indexes directly. It adds some overhead and if most programs don’t use it, we better not add two ways to do the same thing.

**Comment by Timmmm** [comment]
It's more logical, faster, and gives the correct index. Surely those are enough reasons?

Also I'm not sure that `row_number` would work anyway - wouldn't that result in this?

```
[
  {"name": "alpha", "data": 123, "foo": 1, "index": 1},
  {"name": "alpha", "data": 123, "foo": 2, "index": 2},
  {"name": "beta",  "data": 456, "foo": 3, "index": 3},
  {"name": "beta",  "data": 456, "foo": 4, "index": 4},
  {"name": "beta",  "data": 456, "foo": 5, "index": 5}
]
```

**Comment by domoritz** [comment]
Can you help me understand why it's more logical? That seems like a subjective statement to me. Can you show us a few examples that use `flatten` and then `window` to add an index? Examples will help me convince myself that this shortcut is useful. Is it actually faster? I fear that this addition will make the common case (that doesn't need the index) slower.

To add the correct index, you can `groupby` the `name` and `data`.

Just to note, I intuitively agree that an index can be useful in many cases. My goal here is to justify the engineering decision to add a shortcut for something that can already be achieved (even though it may require some more code).

Thank you for raising this issue, sending a pull request, and engaging in a design discussion.

**Comment by Timmmm** [comment]
> Is it actually faster?

Definitely, it's a simple loop. `window` is way more complicated. Several complex functions calls per element.

> I fear that this addition will make the common case (that doesn't need the index) slower.

Fair point - If that is a worry it could be made into a separate loop.

> To add the correct index, you can groupby the name and data.

That is *definitely* going to be way slower. And what if `name` and `data` don't exist? For instance:

```
[
  {"foo": [1, 2]},
  {"foo": [3, 4, 5]}
]
```

to

```
[
  { "foo": 1, "index": 0},
  {"foo": 2, "index": 1},
  {"foo": 3, "index": 0},
  {"foo": 4, "index": 1},
  {"foo": 5, "index": 2}
]
```

My use case is that I have a number of items in different bins. The data comes from the server as an array of arrays like this:

```
[
   [{id: 3, name: "hello"}, {id: 8, name: "goodbye"}],  // bin 0
   [{id: 5, name: "whatever"}, {id: 4, name: "meh"}, {id: 9, name: "bleh"}],  // bin 1
   ...
]
```

And I want to be able to show the data in various ways - all the items at once, or maybe just some of the items from one bin.

One option is to do the flattening in Javascript and then when I want to show some items from one bin I just filter on the bin number. That would work, but it's pointless extra work because I'm flattening the array only to make Vega filter the items again, when they were already sorted into bins in the first place!

My current solution is to flatten the data in Javascript and store both the unflattened and flattened data. This does double the memory usage, but I suspect having Vega do the flattening instead would result in the same memory usage. In any case it is not very elegant.

Using hacks like `window` might be fine if I just had a few thousand items but my data set is very large. Ideally I would like to show 10 million items. That doesn't seem achievable but really the more items I can show the better.

**Comment by domoritz** [comment]
Thanks for the explanation! In terms of the API, I wonder whether there could be problems with using the name `index` since it may already exist in the dataset. Maybe we can make it configurable (with index being the default and also a way to disable the index field)?

How about:
* By default, we don't add an index. 
* There is an option `index` in the `flatten` transform, which can either be a boolean `true` or a string name. If the value is `true`, we use `index` or `foo_index` (where `foo` is the field that is being flattened) and otherwise we use the string value as the name of the index field.

Sounds good?

**Comment by Timmmm** [comment]
> Sounds good?

Yep sounds like a good design to me. That's what my pull request was meant to do actually (except the option of a boolean) but maybe I misunderstood the code.

**Comment by jheer** [comment]
Added in 0cc590a.
