### ISSUE TITLE
Documentation error: Data format schema.parse:"auto" is not the default

### ISSUE THREAD

**Issue by danmarshall** [vega/vega#2116]
The [Data Format](https://vega.github.io/vega/docs/data/#format) documentation and [vega.read](https://github.com/vega/vega/tree/master/packages/vega-loader#data-format-parsing) documentation state that `parse: 'auto'` is the default. However, if `parse` is omitted, I am not getting that default behavior, specifically with regard to dates.

```js
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "data": [
    {
      "name": "csv_no_parse",
      "values": ["date,amount\n01/01/1980,28"],
      "format": {"type": "csv"}
    },
    {
      "name": "csv_auto",
      "values": ["date,amount\n01/01/1980,28"],
      "format": {"type": "csv", "parse": "auto"}
    },
    {
      "name": "json_none",
      "values": [{"date": "01/01/1980", "amount": 28}]
    },
    {
      "name": "json_no_parse",
      "values": [{"date": "01/01/1980", "amount": 28}],
      "format": {"type": "json"}
    },
    {
      "name": "json_auto",
      "values": [{"date": "01/01/1980", "amount": 28}],
      "format": {"type": "json", "parse": "auto"}
    }
  ]
}
```
[show in editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABN0eTDgDaSiKAj6oM9KmTYo8WBQD6M7lcLoATrFOKDESBXQAbVslhmmpCqeMjyxtysMngAOjIADACMpEmkiQCcABzx8gBMmZAAum7ukABm3I4YeGbAkHgAnoSmOJAWFJAAvjpgnSW6PR5GJmZtllborHjcCoNQXr7+gcFqYRFRsQnJqRnZeQXFc+WV1bX1TS3mlgpQDs6XkJPTXT19PXqlww9SsjayrkcFn4Alo6iEHqkdll4jdHqhItEzPlOoVXv0wB8DJAvqMfjI-vYnC5Zu55j5gYEwatRpDkrsYfIoOtEThkYdSccqmozo1mrjpHJugY3gZMfpscZvgKJlMZuiPEClqCVqEads6dDYcyaqzMij5VAKlydRjznzWnjYXdia0njMhfoHajukA)

Expected:
default behavior as `parse: 'auto'`

Actual:
When using `parse: 'auto'`, dates are converted to numbers. When not using `parse`, dates are left as strings.

**Comment by jheer** [comment]
Thanks for catching this! I've updated the documentation accordingly.
