### ISSUE TITLE
Axis tick unexpectedly fails to be labeled

### ISSUE THREAD

**Issue by afdta** [vega/vega#2138]
Here's an example documenting the issue: https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwogAw7FESIXRq1jGdS2jFSyAnQAbZLC0BtJRFARvUGelTIWpAAHgoe3pB4AJ6EgTiQDtyWBj5QatwY5m4ATHp68mDZunkAuik+kABO6BZxKuqa4QC+SmUgtujBzm7hXql28I51IWGpUNyVjMgyeEHs3AQZo-0O6OzIDgDyVJWrhFoAZo6wyOURFI6s3TiuRXkFxflgAIx5T7lvJc2tIC1AA

Note: Setting tickCount to 5 forces the drawing of the label in this case.

**Comment by jheer** [comment]
Thanks for the issue! This behavior should be specific to log scales and stems from Vega's underlying use of d3-scale. If defined, Vega tries to follow the behavior of an existing `tickFormat` method provided by a scale implementation. In the case of logarithmic scales, the built-in formatting suppresses some labels to avoid overlap (see [log.js#L122](https://github.com/d3/d3-scale/blob/master/src/log.js#L122)), though as you observed this behavior is also affected by the tick count. (In this case, the tick count gets set to the number of entries in the values array, which elsewhere can help ensure proper precision for the formatted labels..

There are multiple ways we might want to update Vega to address this (short of changing the behavior entirely). For example, if `labelOverlap` is explicitly set to `false` we might suppress this filtering behavior. In any case, it seems that we should suppress this behavior when explicit `values` are given, as in the example here.

**Comment by jheer** [comment]
Filter suppression for explicit values added in v5.8.0.
