### ISSUE TITLE
Make hidden canvas an off-DOM element?

### ISSUE THREAD

**Issue by jheer** [vega/vega#215]
A hidden (display: none) canvas is used for renderer-agnostic font metrics during bounds calculation. This scheme may work with an off-DOM canvas element. Need to test.

**Comment by arvind** [comment]
@jheer, is this still relevant? Closing it for now. We can re-open on vega/vega-scenegraph if need be.

**Comment by jheer** [comment]
The hidden canvas is now off the DOM!
