### ISSUE TITLE
Text/value pair for Select Input options

### ISSUE THREAD

**Issue by danmarshall** [vega/vega#2152]
Hello, I'd like the ability to have a value associated with the text for a Select Input, so that we can have "pretty" display for "ugly" values in a dropdown menu.

![image](https://user-images.githubusercontent.com/11507384/68698644-3c85dc80-0536-11ea-9f44-75a6f38b3ebc.png)

Currently, I am able to work around this by looking up the display text in a table to get a corresponding value, but it feels clunky (requires a 2nd signal...). Seems like a core concept for a Select widget.

Here's my workaround:
```js
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "height": 60,
  "width": 300,
  "signals": [
    {
      "name": "DateTime_display",
      "value": "Year",
      "bind": {
        "name": "Date format",
        "input": "select",
        "options": [
          "Year",
          "Quarter",
          "Month",
          "Week",
          "Day",
          "Hour",
          "Minute",
          "Second"
        ]
      }
    },
    {
      "name": "DateTime_format",
      "update": "data('DateTime_selected')[0] ? data('DateTime_selected')[0].format : '%Y'"
    }
  ],
  "data": [
    {
      "name": "DateTime_all",
      "values": [
        {
          "display": "Year",
          "format": "%Y"
        },
        {
          "display": "Quarter",
          "format": "Q%q %Y"
        },
        {
          "display": "Month",
          "format": "%b %Y"
        },
        {
          "display": "Week",
          "format": "Week %V %Y"
        },
        {
          "display": "Day",
          "format": "%x"
        },
        {
          "display": "Hour",
          "format": "%x %H:00"
        },
        {
          "display": "Minute",
          "format": "%x %H:%M"
        },
        {
          "display": "Second",
          "format": "%x %H:%M:%S"
        }
      ]
    },
    {
      "name": "DateTime_selected",
      "source": "DateTime_all",
      "transform": [
        {
          "type": "filter",
          "expr": "datum['display'] == DateTime_display"
        }
      ]
    }
  ],
  "marks":[
    {
      "type": "text",
      "encode": {
        "update": {
          "text": {"signal": "timeFormat(datetime('2015-11-11 17:52:04.003'), DateTime_format)"},
          "fontSize": {"value": 22},
          "x": { "value": 20},
          "y": { "value": 40}
        }
      }
    }
  ] 
}
```
[open in Vega editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgGY6AK1jcAdpAA04XMkbV82MADYADIoiQA7owAmLDaO26lkWKpnoANrA0BtJRFAQvUe6mQbIABF0PGQAFUY-AH1jRlhCB3QATwV3L0gKR1Z-HEgATWR0ACdU7312RhljDU8y-V8cqGDQsAAzbiKMPFK6qErCVm7c2GQHZHhuvV7IbkI8HhlnHDde9ILintXIAEVWYtCSqa2AWVkzI+mAdWRkAGtN6eCUi7rIAAluVkO01+PKwf8LzKkAAyuNZNUfl4ALpQgC+aThF1q3kgDQCzXCkWQUXanRCD30rEIxhCjUgpLw6AAFAByTERaIjMYTZDGWkAShc2mhYAA-GBKTT6WTGTjmeNQuyuTy6HiumAcLSAKR5WmQRFKaFTCkhTDLNIo9Lo3IM7FRRwOQlQTIObJLMArXpG16xeKJFK5dbfVb6eUE3KqjWrJFQjxh9JuhLJAK7fbIH2+yD+oZQbbKgCOYCDEdDqxdwKjHoCpxk5wjfo6XQCyvY2bywd6eedFagRZjuWud2tqJTAS7t2zADV6426s26gXUe3PU0Y0De1WA1BlQAPMdlCdlKeRuLR2fvT6JrZ9wOr7NvLCWDfeLfeHf6Gcl-6hHvpU8r8-Ky-K443rx3l4D5tnuxa5GC8AQm+lb4qmkBrheWC-khIL-hACJ1LCt7IlCaLoH4GKiuaEqstUQI2Ee8Dkma0SWtakB4EU6CLPKrgRsBDFJIQ5KtIwDgHNBUDIKuhAlLklKsKgLi0jOtK8gAvPJYA0TiT65lCWEAVqOoYEUtxLE64avHgXHkqEq6TLhyAyJBxiNDukDEpS9mtgxwmpsANh2I4ATzH4ABiS54NSzl+cgdIAEzaAAjAArAAtNF0WJdFYDRQA7FgsURVeAAsdCWKInLyMpRHRCmHKQIBi5liCjAAF72RkWSNBFEXVek644MANotRoUUdfos49c1dqNLl2gYU28KahAvIgAiQA)

**Comment by jheer** [comment]
In terms of a potential (backwards compatible) solution, how about a `"labels"` array (parallel to the `"options"` array) with the desired text labels? If an entry in the labels array is `null` or `undefined`, the options value will be used as in the current implementation.

Another approach might be to support objects (e.g., `{"value": ..., "label": ...}`) within the `options` array, but I'm skeptical of that approach, at it collides with the use of object-valued options and so is not backwards compatible.

**Comment by danmarshall** [comment]
I'm fine with the `labels` approach. 👍

> the use of object-valued options 

Now I'm curious, what is displayed for "object-valued options"? Is it `"[object Object]"` ?

**Comment by jheer** [comment]
😆 Yup, `[object Object]` is the label. But the value is still valid!
