### ISSUE TITLE
Rounded corners on group marks don't clip children

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2155]
<img width="513" alt="Screen Shot 2019-11-12 at 17 29 14" src="https://user-images.githubusercontent.com/589034/68725031-08301180-0572-11ea-94da-ff228db92c59.png">

in https://vega.github.io/vega/docs/marks/group/

I would expect the elements inside the group to be clipped to the shape of the group mark.

If this works, we can clip stacked bars by putting all rects for a bar into a single group.

**Comment by jheer** [comment]
The current design is as-intended, but I think it probably makes sense to switch to corner clipping.
