### ISSUE TITLE
TimeUnit transform documentation (Vega v5.8.0)

### ISSUE THREAD

**Issue by roying** [vega/vega#2156]
https://vega.github.io/vega/docs/transforms/timeunit/

_{"date": Date(2018,  0, 11), "unit0": Date(2018,  0,  7), "unit1": Date(2018,  9, 21)},_

Should _Date(2018,  9, 21)_ be: _Date(2018,  0, 21)_ ?

**Comment by jheer** [comment]
🤦‍♂ Thanks, fixed!
