### ISSUE TITLE
'__spreadArrays_1' is undefined while using vega with stencil js in internet explorer 11

### ISSUE THREAD

**Issue by learnwithratnesh** [vega/vega#2159]
I am currently using:
"vega": "5.4.0",
"vega-embed": "4.2.2",
"vega-lite": "3.4.0"
 in stencil component application. I have to give IE support in this app but i am getting error.
I have added "core-js": "3.4.1" for polyfill support.

I am getting error:
'__spreadArrays_1' is undefined in IE , in chrome everything is working fine.

My tsconfig configuration:
"compilerOptions": {
    "downlevelIteration": true,
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": false,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "moduleResolution": "node",
    "module": "esnext",
    "target": "es2017",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "jsx": "react",
    "jsxFactory": "h",
    "noEmitHelpers":false
  }

Is IE not supported by vega if yes then how to resolve above issue ?

**Comment by jheer** [comment]
Please see https://vega.github.io/vega/usage/internet-explorer/

Beyond that, I'm afraid I don't have any experience with the environment/tools you're working with.
