### ISSUE TITLE
Nested scope picker in Editor 

### ISSUE THREAD

**Issue by danmarshall** [vega/vega#2176]
I use the Editor frequently, especially the Data Viewer and Signal Viewer. These work on the main scope, but have no visibility of deeper scopes in [group marks](https://vega.github.io/vega/docs/marks/group/):
> Group marks provide their own coordinate space and can include nested data, signal, scale, axis, legend, title and mark definitions

It would be helpful to inspect these nested data and signals.

I have also looked at the [view API itself](https://vega.github.io/vega/docs/api/view/) which has [.data](https://vega.github.io/vega/docs/api/view/#view_data) and [.signal](https://vega.github.io/vega/docs/api/view/#view_signal) methods for the main scope, but not nested scopes.

**Comment by jheer** [comment]
You can access nested scopes at the console through the `view._runtime.subcontext` array. For editor support, I suggest filing issue over at https://github.com/vega/editor

**Comment by danmarshall** [comment]
Thanks!

**Comment by domoritz** [comment]
In the editor, you can use `VEGA_EDITOR` as described in the help modal.
