### ISSUE TITLE
histogram counts/labeling is surprising when nice=false

### ISSUE THREAD

**Issue by zanarmstrong** [vega/vega#2181]
If I create data that is simply the integers from 0 to 29 (including 0 and 29), I would expect a histogram to look something like this:

[histogram](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgBY6ABjoArWNwB2kADTgo8TQDNG1bGFAQIkDACcA1mYuWrebtzF5GhMxtZixehAAvrrOkBSMyADujoGWkCgm+GbSioqhzlBRjAAmLGZyaXFBeiF6kDnoeJg4TlYa6KjIZhVVogBs7QBMAIwAHADsPcgD7IbsAJzdAKwDOXIT0-ATE12Kcj1d7YqYpRmt1bDIeLCxYZXVIp29g8Oj41Nds-OLy6vrm9s1YADacRB1TKQAAeZkU-zAZUy5ghVlBOB6EKhmUBYXhYC6SIyzlR8XR0ixENxcIKhOhxKg6OmZJRsMpZnaNJxdJBZgGTMsFNZOD6HIBLPREz5MOhJIR4OhyOZovpCMRkuxnIFZk2wq56J6BIVROVCLkat1YB61O15MNPUZptpMu5RvZVulott-QNNo1QodSrdZjWrqd6N6fuhtq6mM9-O9OC6WsyUq9-p9+vDIoTUZNscVEdTGMtGZ1kYx9rzZoLXV5yfVPo9sbiAF09uVkBoDDlGBpTLU4rbcZB2G2zk6NIx4M0cHgbKxkMLIMZkGIci1QZmoHgAJ6EUdQACOrHQGk81U8VEgxUVkFXA7C6Go1Bswjwm8gBlY+50EMga43LR3e4PVUYx7FA2Vi2A4OC9ugNgnkEQA)

![nice](https://user-images.githubusercontent.com/7397271/69289067-37690300-0bb0-11ea-8fee-ccc209bfe265.png)

This is what I see what nice=true or nice is not specified. 

However, when "nice=false", I see [this](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgBY6ABjoArWNwB2kADTgo8TQDNG1bGFAQIkDACcA1mYuWrebtzF5GhMxtZixehAAvrrOkBSMyADujoGWkCgm+GbSioqhzlBRjAAmLGZyaXFBeiF6kDnoeJg4TlYa6KjIZhVVogBs7QBMAIwAHADsPcgD7IbsAJzdAKwDOXIT0-ATE12Kcj1d7YqYpRmt1bDIeLCxYZXVIp29g8Oj41Nds-OLy6vrm9s1YADacRB1TKQAAeZkU-zAZUy5ghVlBOB6EKhmUBYXhYC6SIyzlR8XR0ixENxcIKhOhxKg6OmZJRsMpZnaNJxdJBZgGTMsFNZOD6HIBLPREz5MOhJIR4OhyOZovpCMRkuxnIFZk2wq56J6BIVROVCLkat1YB61O15MNPUZptpMu5RvZVulott-QNNo1QodSrdZjWrqd6N6fuhtq6mM9-O9OC6WsyUq9-p9+vDIoTUZNscVEdTGMtGZ1kYx9rzZoLXV5yfVPo9sbiAF09uVkBoDDlGBpTLU4rbcZB2G2zk6NIx4M0cIZ0GIjsLIMZkGIci1QZmoHgAJ6EUdQACOrHQGk81U8VEgxUVkFXA7C6Go1Bswjwm8gBlY+50EMga43LR3e4PVUYx7FA2Vi2A4OC9ugNgnkEQA):
![ notnice](https://user-images.githubusercontent.com/7397271/69289120-63848400-0bb0-11ea-862d-30fc0650009a.png)

It is surprising (misleading?) that changing "nice" to false would mean that the data for values >= 25 would end up in the 20-25 bucket AND that the column for 25-30 would be visible and empty. The natural interpretation of that chart is that there are 10 values in the 20-25 bucket and 0 values in the 25-30 bucket. But, that's not true. 

Additionally, it's strange that it's still choosing "nice" bin cut-off points of multiples of 5 when I explicitly set "nice" to be false. 

Doing some debugging, it appears that what's happening is that: 
1. It's choosing the min/max of the data for the binning extent (which makes sense). In this case, [0,29]
2. When the max data value in the extent is not a "nice" number (multiple of 5 or 10 in this case), the max value of the last bin is set to be the last nice value SMALLER than the max. Or 25 in this case. And, any values >25 are lumped into the last bin. But, the axis still goes from the min to max value in the extent (in this case up to 29)... and the last bin is still labeled as 20-25.

Setting the extent explicitly to [0,29](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgBY6ABjoArWNwB2kADTgo8TQDNG1bGFAQIkDACcA1mYuWrebtzF5GhMxtZixehAAvrrOkBSMyADujoGWkCgm+GbSioqhzlBRjAAmLGZyaXFBeiF6kDnoeJg4TlYa6KjIZhVVogBs7QBMAIwAHADsPcgD7IbsAJzdAKwDOXIT0-ATE12Kcj1d7YqYpRmt1bDIeLCxYZXVIp29g8Oj41Nds-OLy6vrm9s1YADacRB1TKQAAeZkU-zAZUy5ghVlBOB6EKhmUBYXhYC6SIyzlR8XR0ixENxcIKhOhxKg6OmZJRsMpZnaNJxdJBZgGTMsFNZOD6HIBLPREz5MOhJIR4OhyOZovpCMRkuxnIFZk2wq56J6BIVROVCLkat1YB61O15MNPUZptpMu5RvZVulott-QNNo1QodSrdZjWrqd6N6fuhtq6mM9-O9OC6WsyUq9-p9+vDIoTUZNscVEdTGMtGZ1kYx9rzZoLXV5yfVPo9sbiAF09uVkBoDDlGBpTLU4rbcZB2G2zk6NIx4M0cIZ0GIjpn4shgXgm3gzD90l0JvXk5BjMgxDkWqDp5A8ABPQijqAAR1Y6A0nmqniokGKisgR4HYXQ1GoNmE85aBlYN46BCh4nmekCXtet5VIwD7FA2Vi2A4OC9ugNiPkEQA) or [0,26](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgBY6ABjoArWNwB2kADTgo8TQDNG1bGFAQIkDACcA1mYuWrebtzF5GhMxtZixehAAvrrOkBSMyADujoGWkCgm+GbSioqhzlBRjAAmLGZyaXFBeiF6kDnoeJg4TlYa6KjIZhVVogBs7QBMAIwAHADsPcgD7IbsAJzdAKwDOXIT0-ATE12Kcj1d7YqYpRmt1bDIeLCxYZXVIp29g8Oj41Nds-OLy6vrm9s1YADacRB1TKQAAeZkU-zAZUy5ghVlBOB6EKhmUBYXhYC6SIyzlR8XR0ixENxcIKhOhxKg6OmZJRsMpZnaNJxdJBZgGTMsFNZOD6HIBLPREz5MOhJIR4OhyOZovpCMRkuxnIFZk2wq56J6BIVROVCLkat1YB61O15MNPUZptpMu5RvZVulott-QNNo1QodSrdZjWrqd6N6fuhtq6mM9-O9OC6WsyUq9-p9+vDIoTUZNscVEdTGMtGZ1kYx9rzZoLXV5yfVPo9sbiAF09uVkBoDDlGBpTLU4rbcZB2G2zk6NIx4M0cIZ0GIjpn4shgXgm3gzD90lt68nIMZkGIci1QdPIHgAJ6EUdQACOrHQGk81U8VEgxUVkEPA7C6Go1BswnnLQMrGvOgQgex6npAF5XjeVSMPexQNlYtgODgvboDYD5BEAA) illustrates this. 

Expected behavior: 
If nice is false (and no extent is set or the extent is set to a not-nice value), then the left side of the min bin would be the min of the extent and the right side of the max bin would be the max of the extent. 

Or, that you'd see this same graph, but the right-most bin would be labeled >20. 

I can include some examples showing what other tools would do in a similar situation if desired.

**Comment by jheer** [comment]
I've transferred this issue to vega/vega repo. This is definitely a bug, which I've tracked down to the `Bin` transform in the vega-transforms package. The underlying `bin` determination utility in vega-statistics is doing the right thing, but the transform is making an incorrect assumption about `bin`'s output `stop` value (namely, that it resides on a step boundary).
