### ISSUE TITLE
Clipped group elements should be behind border

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2197]
When group marks are in a clipped, I would expect them to behind the group's border. However, it looks like the group elements are clipped but in front of the border. 

<img width="542" alt="Screen Shot 2019-11-26 at 11 09 55" src="https://user-images.githubusercontent.com/589034/69665694-c27a4b00-103f-11ea-9a3c-522cc52f9649.png">

I think it would be better if Vega either put the group elements behind the border or clipped off elements along the inner stroke.

**Comment by jheer** [comment]
Feel free to open a PR! One approach could be to adjust the clipping region by 0.5 times the stroke width, which should be less hassle than managing multiple elements (foreground stroke, background fill) for each group mark item.

**Comment by jheer** [comment]
Fixed by #2220.
