### ISSUE TITLE
Separate group translate from moving the clip mask.

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2207]
It would be great if Vega had a way to move the clip mast for a group independent of translating the marks inside a group. Right now, moving a clip mask means that all marks also get translated. Because of this, Vega-Lite has to generate complex expressions. See https://github.com/vega/vega-lite/pull/5583#discussion_r351919491.

We could introduce new properties `clipX` and `clipY`. Alternatively, we could add a property `translateChildren` that can be set to `false`.

**Comment by jheer** [comment]
After more thought, I don't think we want to go down this route. The boolean-valued group-level `clip` encode property is specifically for clipping to the group width/height/corners. Other marks contained within the group can also specify their own custom clips.

If we want to define a group-level custom clip, we could perhaps do so by allowing values other than boolean for the `clip` encode property, but in the end that is still functionally equivalent to custom clips defined on the marks within the group (which again we already support).

**Comment by domoritz** [comment]
> If we want to define a group-level custom clip, we could perhaps do so by allowing values other than boolean for the clip encode property, but in the end that is still functionally equivalent to custom clips defined on the marks within the group (which again we already support).

I think we could use this in Vega-Lite if there was an easy way to clip by another mark definition. Custom clips have to be SVG paths or spheres, right (https://vega.github.io/vega/docs/marks/#clip)? Generating paths isn't practical for Vega-Lite, though, since we would have to dynamically create paths in Vega expressions (not having access to the data).

**Comment by domoritz** [comment]
I agree that my proposal wasn't good: it only fixes a specific problem without enabling a lot more things more elegantly.
