### ISSUE TITLE
Embed Font in SVG

### ISSUE THREAD

**Issue by UsorUsor** [vega/vega#2212]
It would be nice to have a convenient way to choose and embed fonts in SVGs. This way you can export with a set font so you are certain that the SVG will be displayed as you specifically intended.

**Comment by domoritz** [comment]
How do you propose we embed the fonts? As base 64-encoded string?

**Comment by jheer** [comment]
I'm not sure about embedded (e.g., base-64 encoded) fonts, but I believe you can include font definitions within a `style` tag in the SVG itself. You could then use CSS font loading mechanisms to ensure custom fonts are loaded (see https://www.w3.org/TR/css-fonts-3/#font-resources). Of course, you can always use the standard HTML-level CSS mechanisms as well.

In general, Vega should not be able to access local font files (that would be a security violation) and so would have no means by which to embed them. So for now I would recommend adding any extra font file data to the Vega output as a post-processing step.

Please feel free to share back anything you come up with!
