### ISSUE TITLE
Title and labels overlap on y axis

### ISSUE THREAD

**Issue by captaindavepdx** [vega/vega#2214]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug / the goal of the feature request.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an example spec in JSON, wrapped by triple backticks like this:
- [x] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

<img width="1491" alt="Screen Shot 2019-11-30 at 5 15 22 PM" src="https://user-images.githubusercontent.com/30560737/69908055-79efc400-1396-11ea-921b-a60a5a300aa7.png">

**Running the following json specification should reproduce the problem,** [Vega Editor](https://vega.github.io/editor/?#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJhYjVITHIw7dLrBIneMAHdmiMLvRLqZE0wTXQ8dDAACnQAawiAcX8CMABhRDcASjo1DUhQ8OwwUAgISAp0MVYdQoBtDWKSyHhuG38AT0LIFN1uWFgMJVSnZGRnACFWRjFtXVgckqhYcN08ABEw5EKAJgAGAEYAdjotgFZ1BchkJU11vE2cXb2ATjoADgBmc8bNVj8jZW2dBOry+pUIvWYxgAktdkAAPQp7UFQZqtJRtGHaBE4PYaAC+XwapVRhHanRSw1GYAA0lM7LNSBTdCNxpNpqMSGAACooMBjbjcGJgACiVF0bTAAFk6VclIwKmAAMqIbisaZgABKyHQmnmjSWblu9zAjyOp2Rl2uRu2+xeHwtPz+xkBwIt4Ks-yUmPhiItJPa3uxJvxhI0xJapPRnQAYmJuPpQkrwncwABVOVij0dC0GlbWh77E50d6fMNQK43DY255vUsXR1hZ04WRnMuQd2Q5SB7Z+iMB2FB94h+pt-1R0yx+OMROK5P2dOMTPMbNt3NrKsFnYHC0V-Mm221h2-RsAnFbN0Qz3dnG9tEYgeFIcQAkji5jjoTsyS1OpbhiOyBGAADyABmYAADLoB4eqlGue6PC8rptruG77jW9ptg2nqFDsxythcHZXg+N6jn26LXmA0jDhARIomRH5QKm4FQmAk4JpgObLOudzVnadaNChPEFuh-GlFhTZgDsF4etCxFgEipF3hRJzUUUimRgxkBsdOERmAAZJKaYZhyy4wYsXHwYWxaieWVqoQhh6Yce2HNkC0mdl6ckKW+9EUQAbKptFNPRnQAOqMEodzOAACk4QoABKMNQPiKkgApiGZkBwfZB5IRcgnGg5GH1s5Em4eabaEbJWK+up-Y1TgByBXV45QGYmhUJF8XamILCZdlQloTZlqVoNRXDeJp5gH57lEQ18m3hpFGvM1Pl3p0QF+AE9gpKqkUSvE3BikoqBXHg-UWTlex+XQBz4QJdljQexXfKVU3vHQOwgpVl7VT6JFrUtclPKtjTvjGcbsWAMJRUoJ5w2IRmLiZeArhcA2FfsRx5Q9o2YyJR5OlNWx4bNf1Bt5YO+V5Oyg+G62mKmKTRmAqzcB4kXs4MFI2KwcycYaV2vLd92lAVvGOSVRMmPJn3fQRv1dl5i31f98m4s+oaA2Spi7Ds0iasgYoVqkPR9AMIrXOzQRKmlYhOLAiAGBdgtPfrdDSOeyGPfjfGE-DiJFp7ZNK-NlP00DYdbHTdEM4xxmzMuwFgdpiZjKM1BLD0qCpGdVLRvGhsKsKBoprOrCaIw1QC3mOVbjuPsSy9YlvTLexewrMmh2r4ex5HPdPmAL40S1mlQikiopC7tdPddDd403E2t4+kuNFV3dBvLVNKV5VGa6+28aZ04+T9P3H49I8+WQTTnS4UotQOvnnzduo8UXse9D1rh861AJ9TzXc+1Ze4jWvkcEs-sXLTRDs-NWM0367xjsFOOkB-5n2vpfb2C9hKvylgHHAw0n7KRVuRRB+8R7a1aqgieADVyXVnh3XGYDIESQfu2RWsCgyYMofeMOn9h5qR4cfGh6C65bzFo3YS3DXp3xwPAzuHkKLDXfO-fh38I6-2oafQB19GESOwUNFhU0QFELknovuqsKZqIPhoqhaCdFiKvldEBk0ZaEI4e-EhvCe7WIoT-KhC4lyo2TqxSGOlRGzzYeLYSftb74MoqvMEHjlYILDipchgj-GaWVNwQghAIrUFzpFKkEwrBKB0LAKU6BaAAC8IqbAcbPXBTCrqxLwVAkmzdH7JLDl49+AUMlBXBqYbovR+j+DAHpX861GmYx2DdCBWDr5tJkfEvYH02GmN6aknuTVBmj06PyNolSpnxEYLoMQlSUiVHYJU0CRS8B+ERqnDidDXb4yDuY0BrSjFuKBOI7pXdOG1R4e-Fa+yhGmAAGoVCuPAeUv5-w0AaW8meF8nGzwBXkZezYYGeJ2RTEGEKsmdAAHJmChEBaKET0VLKukWL6vzERyzxSk0FZjabEtsZpQJKMJT3JecBJQEhyk0ptPXOls8pJxKge4oF+L2XzS2BrL+NiLFUK5H4VAp1-ym3ZtMo+szxXSvypI-c8ymVyNZUqvpZjo5cvVZpTV6BtXIF1aMjwBqyRGpxE8J4w1onmvkasqB6zrU91tUq+1Q8QAAF1VKQCMHgOwhQgp3DhOdUw0UOGVLCF69EDgJQAE1tS6EyiBZQeBFSMBqYVaRsEOBJpTaYUlrBUDsCpNwMCT9KkoHVHmlg9hYAuvsEYU6YAIouEQD0JQf5uBMHgAqeMMx+qNuYHYWKmhK4BHvhaLtIFYDIEzfuC0EhUDMHvjsTlqrSgYF0DEVNbZUaEGNJARwZaE0oCSvgS9JqoBeE0H1HEV6-2QHQKwPAEJa2dFJLqL47YdTbuoDaeDcLuBIcfRcBitFSggSrtMTo4NVBgDLKUZ9r7Z3noRmoEjCxSjoDhIwOYOAcONCba+3aMzSNsfXcgAukVq3QZxMGujUB2P8bwKFZA37j2QFnboDAGVkQXHY+BawF6cAnCvcpnjybkCbowwWHTpR7YdrEGp89x6tPXoWAI9G8Zj2sdw-h3UpgVEPmI9x0oy7RidHQAgCsBTIDcbxGWOzUAgyscgHht1rnzLvJo9xxNbQX2dAAI6sCSMwRsVBEuiayou5tmT8uaBaOgCKtRnj+uI7sXY8bRMElo3RsDjHmPFea+xzoJanBmRU7xiTgnjRzy82J-rlapMyc6PJxTvXdMbsQ0FozI3ovxgwLJkCs2TPoDM7GPmiBCggQqIekLYWLRwi2Jh5rMWCOmHFqd0ikNLsXGu3F9h8qPNNZUyl19y6IoVDy-lgCFYnuidG3pzo2agWbbm8gMwSg0pltMGuaHZHeObSrpFQoYncko6gPuw9x7djGcaFOM6nR9DJXOsTsS5zkDwCgWUUYRhCu46ym0dtf5Bu-pCzpgrsKQcXC2oEbAdRQeNFeMgCX-rWcgXgO8TQ7wnhqAAJAjdKCceXBw-JK9UKrsXpQP4HGQCBdgKu1dQFl+8PYwIZeaCeJ7PyMu6fsC2Ci-XUATiy6eCBV4wWxf1bo41pLigVi1BGyCT7dHtyR4WDNGPJQzjx4gJfJPYBPip62GAYnKqFgB4yd53QK6WNJZe50Vxs3kupdML96jvOQ+ye0AF64QXI+hefCAPEQA).
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with ranged data (aka Gantt Chart).",
  "data": {
    "values": [{
      "company": "Crossman Career Builders",
      "startDate": 2017.25,
      "endDate": 2019.83,
      "duration": 2.58,
      "positionIndex": 1,
      "companyIndex": 1
    },
    {
      "company": "Career Killers/Career Builders: The Book Every Millennial Should Read",
      "startDate": 2017.25,
      "endDate": 2019.83,
      "duration": 2.58,
      "positionIndex": 1,
      "companyIndex": 2
    },
    {
      "company": "Florida State University",
      "startDate": 2015.33,
      "endDate": 2019.83,
      "duration": 4.5,
      "positionIndex": 2,
      "companyIndex": 3
    },
    {
      "company": "Florida State University",
      "startDate": 2007,
      "endDate": 2019.83,
      "duration": 12,
      "positionIndex": 1,
      "companyIndex": 3
    },
    {
      "company": "FAMU College Of Law",
      "startDate": 2019.58,
      "endDate": 2019.83,
      "duration": 0.25,
      "positionIndex": 1,
      "companyIndex": 4
    },
    {
      "company": "ULI Florida",
      "startDate": 2019.83,
      "endDate": 2019.83,
      "duration": 0,
      "positionIndex": 1,
      "companyIndex": 5
    },
    {
      "company": "Florida A&M University",
      "startDate": 2015.33,
      "endDate": 2019.83,
      "duration": 4.5,
      "positionIndex": 1,
      "companyIndex": 6
    },
    {
      "company": "Winter Park High School",
      "startDate": 2019.58,
      "endDate": 2019.83,
      "duration": 0.25,
      "positionIndex": 1,
      "companyIndex": 7
    },
    {
      "company": "AdventHealth",
      "startDate": 2013,
      "endDate": 2019.83,
      "duration": 6,
      "positionIndex": 1,
      "companyIndex": 8
    },
    {
      "company": "Orange County Government",
      "startDate": 2016.75,
      "endDate": 2019.83,
      "duration": 3.08,
      "positionIndex": 1,
      "companyIndex": 9
    },
    {
      "company": "Florida International University",
      "startDate": 2017.58,
      "endDate": 2019.83,
      "duration": 2.25,
      "positionIndex": 1,
      "companyIndex": 10
    },
    {
      "company": "UCF Downtown Campus",
      "startDate": 2018.75,
      "endDate": 2019.83,
      "duration": 1.08,
      "positionIndex": 1,
      "companyIndex": 11
    },
    {
      "company": "2004 Reverend Crossman Endowed Scholarship",
      "startDate": 2004.42,
      "endDate": 2019.83,
      "duration": 15.42,
      "positionIndex": 1,
      "companyIndex": 12
    },
    {
      "company": "University Of Florida Bergstrom Center For Real Estate Studies",
      "startDate": 2007,
      "endDate": 2019.83,
      "duration": 12,
      "positionIndex": 1,
      "companyIndex": 13
    },
    {
      "company": "ICSC",
      "startDate": 2016,
      "endDate": 2019.83,
      "duration": 3.83,
      "positionIndex": 8,
      "companyIndex": 14
    },
    {
      "company": "ICSC",
      "startDate": 2014,
      "endDate": 2019.83,
      "duration": 5,
      "positionIndex": 7,
      "companyIndex": 14
    },
    {
      "company": "ICSC",
      "startDate": 2011,
      "endDate": 2017.33,
      "duration": 6,
      "positionIndex": 6,
      "companyIndex": 14
    },
    {
      "company": "ICSC",
      "startDate": 2014,
      "endDate": 2017,
      "duration": 3,
      "positionIndex": 5,
      "companyIndex": 14
    },
    {
      "company": "ICSC",
      "startDate": 2012,
      "endDate": 2017,
      "duration": 5,
      "positionIndex": 4,
      "companyIndex": 14
    },
    {
      "company": "ICSC",
      "startDate": 2008,
      "endDate": 2014,
      "duration": 6,
      "positionIndex": 3,
      "companyIndex": 14
    },
    {
      "company": "ICSC",
      "startDate": 2012,
      "endDate": 2013,
      "duration": 1,
      "positionIndex": 2,
      "companyIndex": 14
    },
    {
      "company": "ICSC",
      "startDate": 2008,
      "endDate": 2011,
      "duration": 3,
      "positionIndex": 1,
      "companyIndex": 14
    },
    {
      "company": "University Of Florida",
      "startDate": 2015,
      "endDate": 2019.83,
      "duration": 4.83,
      "positionIndex": 1,
      "companyIndex": 15
    },
    {
      "company": "Shopping Center Business Magazine",
      "startDate": 2017,
      "endDate": 2019.83,
      "duration": 2.83,
      "positionIndex": 1,
      "companyIndex": 16
    },
    {
      "company": "Crossman & Company",
      "startDate": 2006.33,
      "endDate": 2019.83,
      "duration": 13.5,
      "positionIndex": 1,
      "companyIndex": 17
    },
    {
      "company": "Boys & Girls Clubs Of Central Florida",
      "startDate": 2015.42,
      "endDate": 2019,
      "duration": 3.58,
      "positionIndex": 1,
      "companyIndex": 18
    },
    {
      "company": "Valencia College",
      "startDate": 2014,
      "endDate": 2018,
      "duration": 4,
      "positionIndex": 1,
      "companyIndex": 19
    },
    {
      "company": "NAIOP",
      "startDate": 2014,
      "endDate": 2015.08,
      "duration": 1.08,
      "positionIndex": 1,
      "companyIndex": 20
    },
    {
      "company": "University Of Florida Online",
      "startDate": 2007,
      "endDate": 2010,
      "duration": 3,
      "positionIndex": 1,
      "companyIndex": 21
    },
    {
      "company": "Trammell Crow Company",
      "startDate": 2000,
      "endDate": 2006,
      "duration": 6,
      "positionIndex": 2,
      "companyIndex": 22
    },
    {
      "company": "Trammell Crow Company",
      "startDate": 1993,
      "endDate": 2006,
      "duration": 13,
      "positionIndex": 1,
      "companyIndex": 22
    }]
  },
  "title": {
    "text": "Positions at Company by Year",
    "fontSize": 24,
    "subtitle": "Number of positions held at the same time in chronological order",
    "subtitlePadding": 5,
    "offset": 20,
    "limit": 500
  },
  "mark": {
    "type": "bar"
  },
  "height": 500,
  "width": 1000,
  "autosize": "pad",
  "padding": 20,
  "encoding": {
    "y": {
      "field": "company", 
      "type": "nominal", 
      "axis": {
        "title": "Company",
        "titleFontSize": 16,
        "titleFontWeight": "normal",
        "titlePadding": 20        
      },
      "sort": {
        "field": "companyIndex", 
        "order": "ascending"
      }
    },
    "x": {
      "field": "startDate", 
      "type": "quantitative", 
      "scale": {
        "domain": [1993, 2020]
      }, 
      "axis": {
        "title": "Year",
        "titleFontSize": 16,
        "titleFontWeight": "normal",
        "titlePadding": 20,
        "format": "f",
        "labelFlush": false
      }
    },
    "x2": {
      "field": "endDate"
    },
    "color": {
      "field": "positionIndex", 
      "type": "ordinal", 
       "legend": {
          "title": "Position",
          "titleAnchor": start,
          "titleOrient":  "top",
          "offset": 20,
          "orient": "right",
          "direction": "vertical",
          "symbolSize": 500
      },
      "scale": {
        "range":[
          "8e8e93",
          "fc3d39", 
          "53d769", 
          "147efb", 
          "fc3158",
          "fd9426",
          "fecb2e",
          "5fc9f8"
        ]
      }, 
      "sort": [
        8, 
        7, 
        6, 
        5, 
        4, 
        3, 
        2 ,
        1
      ]
    },
    "order": {
      "field": "duration",
      "type": "ordinal",
      "sort": "descending" 
    }
  }
}
```

**Comment by captaindavepdx** [comment]
Thanks, @domoritz ! Removing the `labelLimit ` seems to truncate the labels on the y-axis. Is there a way to display the full title and labels without overlapping?

**Comment by jheer** [comment]
The default axis `maxExtent` (the maximum offset for the axis title) is set to 200 in the default Vega config. This partners with the default `labelLimit` setting of 180. If you change the `maxExtent` to a larger value (for example, large enough to include your labelLimit, tickSize, labelPadding) then your issue will be resolved.

**Comment by captaindavepdx** [comment]
Awesome, thank you @jheer !
