### ISSUE TITLE
Missing documentation for strokeOffset

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2223]
strokeOffset is not documented at https://vega.github.io/vega/docs/marks/group/.

**Comment by jheer** [comment]
Yes it is, but it's in the v5.9.0 branch pending release: https://github.com/vega/vega/blob/1ff8354ea856930cdbc902319512dc2c99f7caaa/docs/docs/marks/group.md

**Comment by domoritz** [comment]
Ups, I looked in master. Sorry for the noise.
