### ISSUE TITLE
kde2d documentation missing groupby

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega#2229]
The new kde2d API documentation appears to missing the `groupby` parameter.

(I am curious, because I thought the API docs were generated automatically from the schema)

**Comment by jheer** [comment]
Added `groupby` to the docs in the v5.9.0 branch, which should land very soon. It appears to have been deleted by accident in the process of documentation editing... 🤦‍♂Unlike Vega-Lite, the Vega docs are not tethered to the schema.
