### ISSUE TITLE
Include example for dynamic data in Basic Use section

### ISSUE THREAD

**Issue by jedverity** [vega/vega#223]
Looking at the [Basic Use](https://github.com/trifacta/vega/wiki/Runtime#basic-use) documentation for arguments you can pass to the `chart` constructor, it is not clear how the data object should be formatted (until you inspect the dynamic data example).

Also, reviewing the [Data Examples](https://github.com/trifacta/vega/wiki/Data#examples) for specs makes it look like the proper format is an object instead of an array.

Of course, reading more closely and reviewing examples reveals proper formatting, but it would be helpful to illustrate proper usage inline. For example, either in the Basic Use documentation covering the data property or in the data examples describing dynamic data (or in a separate section altogether describing dynamic data) something like this would have saved me a lot of time:
```
// spec.json
"data": [{"name": "table"}]

// myScript.js
chart({
  el: '#vis'
  data: { table: myData }
})
```
You'd probably want to provide more context than I do here, but you get the idea!

**Comment by arvind** [comment]
Vega 2.0 exposes a new API for runtime binding of data, which we've [documented here](https://github.com/vega/vega/wiki/Streaming-Data). Thanks for posting the issue!
