### ISSUE TITLE
Make bin legend work correctly for negative values 

### ISSUE THREAD

**Issue by kanitw** [vega/vega#2232]
As I make this [spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgE6Asl2Ex3PJcTcA7oyXUwL3bGSE3WzB0JU0wVEYxHTBCINoxByVYMHcWMHYPJWQw9Hh4ZCjda2MwZTB4bgddOjUNSE1rTBxgSFZdMWwtRtJ4dF95RRUAX3UISDwipIAzbl1UToBtFt6xeFYxa2ROyBEGvFZUOjM8gtti5TUodFht4-zC8+GAXVGoDF0Aa22AjzxaseQSgqmg81E6oAgYwAHuDIFNGAVNNsABKzPwBVy2S7jACesW2AEdWCEjHhilRICMNGMcbD4YjtgBZSI6AD6sV0rIA4ugEhdVFA8HitqYiSTmOStlTIVBYIwAF4isAtDImMATVjIAVwhFiJGmO6nIpGfmC4WE4lKUmSykaIYgIZAA) for https://github.com/vega/vega/issues/2231, at least the bin should be `-20 – -15`, not `-20 - -20`?

![image](https://user-images.githubusercontent.com/111269/70182973-c0e10080-1699-11ea-9967-354a494bfcbb.png)

**Comment by jheer** [comment]
Thanks! Fixed by #2234.
