### ISSUE TITLE
Cannot export canvas with images from different domain

### ISSUE THREAD

**Issue by jakevdp** [vega/vega#2238]
I could not reproduce this with the vega editor, but am able to reproduce it this way (OSX 10.14/Chrome 78).
With the HTML file below, choosing "Save as PNG" from the image menu results in a corrupted PNG file:
![image-mark](https://user-images.githubusercontent.com/781659/70240546-43150780-1722-11ea-9a2f-14e1285c9936.png)
The SVG output is fine, and charts without image marks are fine.
```html
<html>
<head>
  <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-lite@4.0.0-beta.12"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
</head>
<body>
  <div id="vis"></div>
  <script>
      var spec = {
        "data": {
          "values": [
            {
              "img": "https://vega.github.io/vega-datasets/data/ffox.png",
              "x": 0.5,
              "y": 0.5
            },
            {
              "img": "https://vega.github.io/vega-datasets/data/gimp.png",
              "x": 1.5,
              "y": 1.5
            },
            {
              "img": "https://vega.github.io/vega-datasets/data/7zip.png",
              "x": 2.5,
              "y": 2.5
            }
          ]
        },
        "mark": {"type": "image", "width": 50, "height": 50},
        "encoding": {
          "url": {"type": "nominal", "field": "img"},
          "x": {"type": "quantitative", "field": "x"},
          "y": {"type": "quantitative", "field": "y"}
        }
      };
      vegaEmbed("#vis", spec, {"mode": "vega-lite"});
  </script>
</body>
</html>
```

**Comment by jheer** [comment]
We can add `img.crossOrigin = 'Anonymous';` when loading image content (in vega-scenegraph ResourceLoader.js), and we will want to modulate this based on the results of uri sanitization (which routes through vega-loader). My initial take is that we would make this the default, but the sanitization routine could opt-out for security purposes.

Of course, external servers will have to provide the appropriate CORS header, which in general is outside of our control.
