### ISSUE TITLE
getting null data in vega while accessing data through url(aws-api)

### ISSUE THREAD

**Issue by Suma3** [vega/vega#2244]
I am trying to access data through aws api in vega but getting data table empty while i am hitting same url(api) I am getting data

([{"category": "HR", "members": 100}, {"category": "Technology", "members": 500}, {"category": "BDE", "members": 200}, {"category": "Retail", "members": 91}, {"category": "Customer", "members": 81}, {"category": "MD", "members": 53}, {"category": "Finance", "members": 19}, {"category": "R&D", "members": 87}, {"category": "Animation", "members": 52}])

tegory": "Animation", "members": 52}])

here is my code that you can run on https://vega.github.io/editor/#/edited could you please help me out here

 {
      "$schema": "https://vega.github.io/schema/vega/v5.json",
      "width": 400,
      "height": 200,
      "padding": 5,

      "data": [
        {
          "name": "table",
          "url": "https://8qt2y8hvig.execute-api.ap-south-1.amazonaws.com/test"
        }
      ],

      "signals": [
        {
          "name": "tooltip",
          "value": {},
          "on": [
            {"events": "rect:mouseover", "update": "datum"},
            {"events": "rect:mouseout",  "update": "{}"}
          ]
        }
      ],

      "scales": [
        {
          "name": "xscale",
          "type": "band",
          "domain": {"data": "table", "field": "category"},
          "range": "width",
          "padding": 0.05,
          "round": true
        },
        {
          "name": "yscale",
          "domain": {"data": "table", "field": "members"},
          "nice": true,
          "range": "height"
        }
      ],

      "axes": [
        { "orient": "bottom", "scale": "xscale" },
        { "orient": "left", "scale": "yscale" }
      ],

      "marks": [
        {
          "type": "rect",
          "from": {"data":"table"},
          "encode": {
            "enter": {
              "x": {"scale": "xscale", "field": "category"},
              "width": {"scale": "xscale", "band": 1},
              "y": {"scale": "yscale", "field": "members"},
              "y2": {"scale": "yscale", "value": 0}
            },
            "update": {
              "fill": {"value": "steelblue"}
            },
            "hover": {
              "fill": {"value": "red"}
            }
          }
        },
        {
          "type": "text",
          "encode": {
            "enter": {
              "align": {"value": "center"},
              "baseline": {"value": "bottom"},
              "fill": {"value": "#333"}
            },
            "update": {
              "x": {"scale": "xscale", "signal": "tooltip.category", "band": 0.5},
              "y": {"scale": "yscale", "signal": "tooltip.members", "offset": -2},
              "text": {"signal": "tooltip.amount"},
              "fillOpacity": [
                {"test": "datum === tooltip", "value": 0},
                {"value": 1}
              ]
            }
          }
        }
      ]
    }

**Comment by roying** [comment]
Vega expects input data as array of objects 
      https://vega.github.io/vega/docs/data/

but your url 
      https://8qt2y8hvig.execute-api.ap-south-1.amazonaws.com/test
returns the following:

`{"data": [{"category": "HR", "members": 100}, {"category": "Technology", "members": 500}, {"category": "BDE", "members": 200}, {"category": "Retail", "members": 91}, {"category": "Customer", "members": 81}, {"category": "MD", "members": 53}, {"category": "Finance", "members": 19}, {"category": "R&D", "members": 87}, {"category": "Animation", "members": 52}]}`

Your url should return just the array without _{"data":_

**Comment by Suma3** [comment]
Hey @roying 
I did try with array format as wel  I just changed for your reference response of url in array.
but still no luck

**Comment by roying** [comment]
Running your vega script on my own computer using Chrome browser gave this error:
 
![error](https://user-images.githubusercontent.com/37225856/70556538-152f2900-1b4f-11ea-95ea-cbcb5ae89d02.png)


See this article about CORS (Cross-Origin Resource Sharing) error: 
      https://wanago.io/2018/11/05/cors-cross-origin-resource-sharing/

**Comment by Suma3** [comment]
@roying 
Thanks got resolved
