### ISSUE TITLE
Potential bug in the wind vector example's size scale

### ISSUE THREAD

**Issue by kanitw** [vega/vega#2245]
https://vega.github.io/vega/examples/wind-vectors/

The domain uses `dir`:

```
{
      "name": "size",
      "domain": {"data": "vectors", "field": "dir"},
      "zero": true,
      "range": [0, {"signal": "maxSize"}]
    }
```

but the encoding uses `speed`: 

```
"size": {"scale": "size", "field": "speed"}
```

Is this intentional?

**Comment by jheer** [comment]
No, that is definitely a bug, which the example compensated for through large `maxSize` values and scale extrapolation. Thank you for catching this! I've pushed a fixed example to the docs.
