### ISSUE TITLE
Docs: vega slack organisation link not active

### ISSUE THREAD

**Issue by IamRavikantSingh** [vega/vega#2252]
Link for joining the vega slack organization is not active in Contributions, Development, and Support section of README.md

**Comment by domoritz** [comment]
The correct link is https://join.slack.com/t/vega-js/shared_invite/enQtMzg1ODUzMzM5OTcwLWE1Yzg2MGY0N2ZlMWIyMjM0MzY4OWZiZWExYTI3Y2JlNmFjZTEwMDAyMjA2ZTMwNmQ1ZWU0MzIzNWM2MzU1MDQ.

@kanitw can you update the bitly link?

**Comment by domoritz** [comment]
Is this fixed?

**Comment by domoritz** [comment]
@kanitw Can you update the bit.ly link?
