### ISSUE TITLE
How to make gauge chart with Vega?

### ISSUE THREAD

**Issue by eeyshen** [vega/vega#2253]
Is it possible to make gauge chart like following with Vega? Thanks.
<img width="304" alt="截屏2019-12-17下午10 24 15" src="https://user-images.githubusercontent.com/31716017/71008825-392cd480-2124-11ea-8740-4b343d58791d.png">

**Comment by domoritz** [comment]
Yes. Check out the clock in https://github.com/vega/vega/pull/2237 for inspiration.

**Comment by mathiastiberghien** [comment]
Here's a gauge sample also: [Gauge sample](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAJlEAGRREgpG1fFt0GQSyLFMz0AG1haA2koigI3qA9TItSDxmRwDDHygKJ1YAnEhIDzAAX3DPRKM-WKhYRG5lADlkZDVQhXTI6Ky8ACcYxJTErwjITMCcvIAVRngAaxdU70goxxitGrqfBp8mnxb0f0CMRhkANUqyiIqRrP16gZnB1rjUZbXtjebh0Zw9PcbyuYXj9AAPM9GBoyusgEY9W8m+weRygeHQ1WoyDw7zCD2+WhkrEcjju02B8yykFYMmYF1m8LiCUB902j0x7HQvWo1W42LUAGFuI5uNU8YMCVAAMTwdhqH5qABsRO8U28BwyGMCADNGMjGczWZ8ttcuQB2VUAQVVADEAELCiCitKkkFBbp9eUstlfdZxdiOSk9A3JIEmyVxGRFErIS2KuG2rmiIPOo1gcW+d1QZnKACSsAA4txuGprcqslKnLBkKixeinlB4MgZHhkNUABqprGENToEuBVQaRCkbQh13NU3VdBqRisWAAJWQUsrrGrtcxJxkAAoGyxm-IwCYzHgAFR6OhBgCUrZJ7cjkELxdLAE1h6O63FF-hm2AANRgTvd3sDqXN9fbtFu-OQWkl6p9rs9v0DwjjW55QA+gHPmAAC0YB-O+uafpiyyen+AG9qeoGYhBT6DjB97of2g6kAALPh8E5sau5flKsh4NqlJ4FaSpVlhgQ4URL4-LoCFUbMpqesUoQAMqMAAXrCpIgWOgQoaW-6Pi4lFhnmmJghCULCWCeAYSx0lgZASyrJUYAALzmWA6mQtCJkAPxgHoYA4EZMJgAAfJZ4LWa59nRnGibJmA9nQT8TlwWFfkJkmahBXBOAhSGSgALqKNYNigZgODuB+1FqeaQGkjU6AyLAtHVKgbjlHxmyggAnoQmJZgAjjEMiFqmszoC4cQZR1gywOpeBaMA2T2E4gR6JALpVf1TGEMNo3UA4jiBJOGBvCZ5mmWAE4+eFOBra8rmwbtlQbhut4OXQPxTaGpIDcg804CNthjStcSHRt2xmRZp3ffZoUHetx07acZ0bqQYCiLdM13YhNVGHg9WYmVqBIpgSqdd1FTVIwxXtZjgzIC8hCss8X0xPhf2U2522iLFNJ0pOoGsKgdAZZd1PIBdOAs2zHN3lzzrEgj4azEjDXSiyaMOn1RhdVL5W1iWKaE0YxOk4rGB4Mztas3QUS4-jyDzqjta6zpbOG3jbUm2AADkdB6FK9sXVtlncFpuMyNQFv69bxsXfZ9sAHpOy7YWh9dLtbrDhNi4MEso9L6Ny1ACtxC8aeQBrZMFkWv5lvhk7wNwsCThXfPs7W6AXZDn2ue7XOxYDO1HSZJ1g9s53LgACjGF3LmAk4-vJhH4Rxz6kKq53CyK8czYjyNa6navp9jkC1dnueBAev5HsXdhTpXev8zXdfD8Dm2-V3lMA857ffZ3xndxufcD2AQ8j6wv4KYBE+ESngKWesNyhJXqMlVKRgEBOGQNjbK8N+J7loKwSEwl4CwMrEnQIjhljIHBJWNQ3AjLDRmpAXqcRgi9AKjVSAMpkCOBTHEAOts55w0gBJGkWgMzOBNg8TsPssiuBgj8dcqo9CqnnKI0Q4jVRgHASLRBhw9yCW9OgzBLFsFxFwZ6AhLEiEkOemQihoJ8p9ToYwBhTCcY23auUdhnDuDcMzHw0kAjIRuBggATgMGAHx8jlLhjJIEKymkMGlE0cvbReC9EPAMegZYpCEbkJriEsxhMLFWMCCwuxmwHGlicTgHhWYWLuKEQ5KRAAORyCj547iQV+KhPR1ERIeFoqMMS-SkniYkoxySTFmmoeY+hjDAi9XsaU4qHisoiLERIqRcy5G1MNG2BpakvKaW0r2X0LTJLNB6XIGZIV5y+NCilfhUzymQGqMUBQUAWSXLuZAakRQ5ABMUdVCUjSNl4C0nrWAwlEDoAarswhxCEmHLAMI45FTwrnLcY8mZQQjY+1CNBIhyg5Dzn3Iwao8AImghRdQNFI4prLOSJA6w8sXhwLcOcmwGBqh9EqjlcWUT054srKaFBHiWJFlLmoLICcc6HjzgnaBg0NSoqFWmLQIVFnTQRurGQagpXEplUMAM0jZEUoRnDIw+khWLygDKZEC1XpLXGnaR01JaQqt9LdNekAs7PUWstXeBdSwVkVUqze5q7CWvevnUVJ4fXJLkmhRS-q3qyRkKhP+GEw20NHpGwC0bA2BBTQmlwuqapJHsYEtp7LIDgngJWflyYjXJM9WK41thJXSvNRyeVMiJG5ryRkw1STfWmqDS9AN7q4i9odUm0kLqwxuqtcGwujq61b1dRawd07jyzqVVAIsqrG19LXdkcJmIeXIFBWvaBMbni3wCMa-VgwI3ZvTUuyAN7CKrt9Vmp9C6B1Tu-D-MeUb20RHzXkqldT6mJ2LaWysUoaQVQXQMppOb2EVsFd2qSZ4q2+vHf209y7yzPuSfOidi7P17xXaO5oA1wR4DVaUbda7bB7rSb0I9xqjAjOsSksEc8Pm0I3VRtDtGYHUdMYx+jx6TWWNGT1VJl6nWPqje+rDX7f7j1gpOSexFtB6C3KR2Yr65MEY-UGxTP603acGNwQglJmD4cwxmuI7RlBdGobZH4WBJqmYlTSHoGqDMMYtEyK0f7JgFruCBpektKHEyGixSDxDzWwbMaRkVAq+PNBrch2hTh7BNoDPuNL7moAUizDojVHIS2OEIEC9gUJugwz1Z21D6XCqRfNaxrWytbn5edS18TbGs6des2JrJcQt6ddosWUSEk72frG-RRiLJP5wRup18zlmkZTcM-ZxzfQW5hTc1eljso+2TsM3BkdAG83BeJKFuq4XQTNei1BuLqS4gHtw0TNqlbGvvd-F9zquClrZfOHEYjrJOuFYYXgwHKogjmdq3m+rbEaO0JLC8Ia8nbNQCFp1jDx2xmnzoC8fCVddP-zvDOJsPwhT9d+80Vrw205GG4FKKUWY0dwQBEq-bJq6ITe8wpmbDF4BMWqAtn4S2uffgs-AKz622i5Ac-lWKjkcDi9AYBkLrLQO3aCPdh4MXoMEYGa9xLiGUuzDS0j0kmWAcLtKyDt7pJwfFah2pWHgW6nJK7Zb5oKO2c2fvVfc42PZeSctgTy6xPv2pt7PhcnpBKcO+aNZ5jg2JNQC3qJ78zPWdaD+NJutM3ech+58WQXwvlxi8TzpqXMv0f3s24r+yyu4Jw8A+rq7muwtqV10hQIB6YTlo+0h73yqfsj8GNbyFL07d5Yl07yHtuctzVb-+hHMlx+I2a3X6b0tzYuUqKbXfOt9-bHnI7Z2rsfrbSYl7ZYvsT8xCDg7MOF-I5hx+DHS6k5sTMFivbB2l0P+eAkcrsVegwOOhGhmIO3qEuyeO6uOwONaJ4meTOLOUIueHOdWBePO4kfOGOdCdEZe82Q8PwJEK+QW7eHuSiXeISPeuUISPyAAIowMzhBo9jBs9lAP3usCbkPmbt9qWDTvLP9lPrKogaKmAUYPPp6C7iEm7udh2mQl7ipLRr2kIf1ApqEr8lsjQvxvRpQj8n8jpLADsvRvnrRr7sXoZBCiDFoa5HeP-pOP-neGbMfjYZUKQHYQfg7E7AAKSuw3iuz2ySEl6-K4FWEC5zYi4kFkHB7b6GZVyE53iTjcTLiRFC4shaawHqEHZDbp4M73LZ7oHxGBA-CiBpGEFRHkGr51orbS5rYlEGEaQ2T-RxR7Zq7-pAYrJdEqE+7FqwC1SoDsBMhsGxYcEcZNHWTMGsG8HJY06sTr69HJI5DAp4H3paFGEx7uyOTBzS54qhD-44AbE6FX7hTBw1A2zqrQQjiHEOwXFTJooYoyDBGdZ2CTaNGgiGEnHbGxSEB5CTiVIVGl5RHzjaA8xgB-HKApHaBAmzYZHVCglZFOoQE+ah76zDF0iwAE6hQqapHpHC5Ilzo5Gp5sYZ4p5Z5oF+4IFQB+xswYkqpYm1TaBE7470lqCMk-AQwtju5cakhqEb4aH4HHH-IFF0aYKTGbL-KmGYLmEvo14NH6aaE-J7QubtF6oFpcZBLtK2CDHDErQsQCReitKkim7zHKHirZBAq3b+6fr2wACyMEAAzA5GAOgGAM6c6Y5NIi6QKC6Y4E6TBPbHeDfhcT7JOKoiJLgRuIEWAP6dBM6UGR7LfmGRGYelGSEa9O8YqfgbERLvydmfeqmWdsiVYdARmQNpAR6iGhmXUbXgWZ+vZoUEJMgM5q5hmQ8fwfdApg-nsnoeKb4EaYemYWugoZ0W3lQZ8jdo1LqSMQ9mMYbpwc8ugKggELMZ9uPiKmPksbQisdaWIYSpcWirjEuNUd0Z7g1gKSWlutucsUqc0QPpngJuss0aCrKbeVmTaYZpCSkY5EPPiSyIiRmfmZ+YEEWf5qDhLiiQptAcXKXOXBXF4U-KDC-I-mAPXIHpTE3Oejtg-BTMgFTOej3P3IPMPJHkpopF-vTH+ZUfCedISbRhWaidhgfCpkfBXJOIhZTM-DCBfA3NfNtM3PfG3HhQRShdzG-MRQtrSXQCTjHskVRWAP+dUHRTWfKYxXed5JUK2WqRduOWedQVObQajqMQbi9EbsuR4mucPjeQIbWrRpPrIeIT9mDl1BDjIYvkDgVtwAQLFjyaZgsWBBaTrsZR8WaHgKUHEfWQkfjn1tkQKSevgVXLVCyWHrJboS+kUVSZWXECFOUUpaeRObQoXuEaFWRcZr2KQJUgVaOYaBAmlBAOAkkEAA)
