### ISSUE TITLE
Legend alignment issue when setting columns property using a signal.

### ISSUE THREAD

**Issue by afdta** [vega/vega#2268]
The goal is to produce a responsive legend, adjusting the number of columns based on the width of the plot. The first approach produced misaligned legend entries while the second approach (containing the same logic) produced the desired result.

**Misaligned legend when testing width directly in the columns property.** To see misalignment, narrow viewport until legend goes to 1 column.
`"columns":{"signal":"width < 1100 ? 1 : 7"}`
https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwADgAMuxREgpG1fFoBs+w1ELo1axjOpbRipZDXo8mHAG0lCFAIEKgZdFRkLUhaQlQnNWQAJwVAkMhWJIAbaK8fUlj4mUSkyWk5NIBfJQBddyNYU3Cs2C0A0ODQ9PDI6NUNRFSu9NZCPKicSFVi7mUAZUYAL2QACgBKP10aoeGoWTa03bBOo+HIZCoZPFacYEhpTPgJlQTZhSg8AE9CZ8gk5Eay0glRspy6GTG3l+0zUswWy3Wm22h121SONSqoOOKMgPV+Mng3BaO1CEPGfXULDAAB4wABGOn6MAAfnpYBwAHZIFVavUoAh0FkAQc0iduhFfoSstwUlijF8ftEZY5miT0rCME4tHc8r4oIUEsl3pAAGaMZBZNTReBZViwPBGkE4pLoZySqHUGWfbmhNFgOogQNGIXUZDFG5gdohMVGM1ZHKTKUytXy5hC6IAJRoPDkcr2SXNV2ieG4hBTUClrFQMhud0a1FVWCmlMQNPpjN0LLZnOBefOBO4iW1KIan1Q7CJEZj4LDDpStxH4LjWQA8nZ4MxvbdIBRBaxnro6KI-UcT10nUdIFl0OwLVPF0ZRuSF2D5cgAB54bWm82W6K720ojPYZgJCUCzz9DFwBAaogA

In the second example the legend entries remain perfectly aligned regardless of the number of columns.

**Aligned legend when storing the result of the same logic in a signal**
`"columns":{"signal":"ncols"}`
https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwADgAMuxREgpG1fFoBs+w1ELo1axjOpbRipZDXo8mHAG0lCFAIEKgZdFRkLUhaQlQnNWQAJwVAkMhWJIAbaK8fUlj4mUSkyWk5NIBfJQBddyNYU3Cs2C0A0ODQ9PDI6NUNRFSu9NZCPKicSFVi7mUAZUYAL2QACgBKP10aoeGoWTa03bBOo+HIZCoZPFacYEhpTPgJlQTZhSg8AE9CZ8gk5Eay0glRspy6GTG3l+0zUswWy3Wm22h121SONSqoOOKMgPV+Mng3BaO1CEPGfXULDAAB4wABGOn6MAAfnpYBwAHZIFVavUoAh0FkAQc0iduhFfoSstwUlijF8ftEZY5miT0rCME4tHc8r4oIUEsl3pAAGaMZBZNTReBZViwPBGkE4pLoZySqHUGWfbmhNFgOogQNGIXUZDFG5gdohMVGM1ZHKTKUytXy5hC6IAJRoPDkcr2SXNV2ieG4hBTUClrFQMhud0a1FVWFxUtaTrOYcJiW1KIan1Q7CJEZj4LDDpStx74LjWQA8nZ4MxvbdIBRBaxnro6KI-Ucd1027tIFl0OwLUPJ0ZRuSJ2D5cgAB54bWm82W6Kr21RPfDb8hX97v0MXAEBqiAA

**Comment by jheer** [comment]
Thanks for sharing this! There was subtle bug in how the signal code was being passed through to downstream calculations in the vega-parser. I will push a fix.
