### ISSUE TITLE
Add dpi option for PNG cli export

### ISSUE THREAD

**Issue by davidanthoff** [vega/vega#2269]
It essentially would compute a new effective scale factor as `scale * dpi/96` (where `scale` is the old command line `scale` argument, and `dpi` would be the new command line argument, and then it would use the effective scale factor when calling the `toCanvas` function). It would also store that DPI setting in the PNG via the options described [here](https://github.com/Automattic/node-canvas/pull/1179).

I think currently the PNGs that are exported do not contain any resolution information (but I'm not sure), so it would probably make sense to leave it that way if the `dpi` argument is not specified.

**Comment by jheer** [comment]
Thanks for the suggestion. PRs welcome! I think any updates could be localized to the vega-cli package?

**Comment by davidanthoff** [comment]
Alright, PRs for both vega and vega-lite are open.
