### ISSUE TITLE
Unexpected results with Vega v5.8 API timeFloor()

### ISSUE THREAD

**Issue by roying** [vega/vega#2270]
When testing the vega-time API timeFloor(), some results were unexpected based on the documentation: https://github.com/vega/vega/tree/master/packages/vega-time
For example: 

```
vega.timeFloor(["year", "quarter"]   )(new Date(2020, 5, 15))  // Apr 01 2020 
vega.timeFloor(["year", "quarter"], 1)(new Date(2020, 5, 15))  // Apr 01 2020 
vega.timeFloor(["year", "quarter"], 2)(new Date(2020, 5, 15))  // Mar 01 2020 (expected Jan 01, 2020 for "quarter")

```

```
vega.timeFloor(["year", "week"]   )(new Date(2020, 5, 15))  // Sun Jun 14 2020 
vega.timeFloor(["year", "week"], 1)(new Date(2020, 5, 15))  // Sun Jun 14 2020 
vega.timeFloor(["year", "week"], 2)(new Date(2020, 5, 15))  // Sat Jun 13 2020 (expected Sunday for "week")
vega.timeFloor(["year", "week"], 3)(new Date(2020, 5, 15))  // Sun Jun 14 2020 
vega.timeFloor(["year", "week"], 4)(new Date(2020, 5, 15))  // Sat Jun 13 2020 (expected Sunday for "week")
```

Are these return values correct?

**Comment by roying** [comment]
There may also be an issue with transform "timeunit" for units "quarter" and "week" with "step" > 1.
   
Here is a modified version of the new Vega (v5.8) Time Units example
      https://vega.github.io/vega/examples/time-units/
using "timeunit" transform with units ["year","week"] and "step": 4.

Many values of field "unit0" created by "timeunit" transform are not Sundays 
(expected Sunday as start date of "week" interval).

![screenshot_vega_timeunit_yearweek](https://user-images.githubusercontent.com/37225856/71600603-b2adc500-2b1d-11ea-89a1-a411d1a1a859.png)

**Comment by roying** [comment]
Link to Vega editor of above example:

https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwANgAMuxREgpG1fFoDM+w1ELo1axjOpbRNyOlZ5usRgC9kLWBIPABPQkCcSAAzZgUoACdkXwCtPATWZHkoeFk8dCdYLUg7BycXAF9FJRDmABtIsFAIIzxkAA88YoBVOgBlOjAAMTrTfDA+-LxGWGn4IpsjWA5pvAbigCZdAGsJ9FRCBuyAKXQZVnQE0LAAWjAAWUukMC3dAEYFJSWV+uQhvMmoXWUWY6FG8E+LSg0QS+0akGoCW4rEIkJaHhkSG4CWKs0uXUWUG40WisGQXRwb10SiqIBqvmoMjBRRwAG0vk0OUYmah4dNeawZHFCUYKGDMlpWZBQshLvFIMpkMhtpAALoiqDsJxqIKQJyELy45ANeAEomEaayFlgdlQqFSmVy9U2yCoPKINXZB2ynHZBVKlXqqVqdBtT0ukOhcNSxDIhJFVVcsCqioc2lQ5p2yA8+G89DLJLysV1CVRXKCglJyBamQ6nDBfWGqJkk1myDcC08GTWqXlmRttTG9BRlNpwmZqHZuHFVbrDWQFEhsNRPMF5BgAC8G7AAHJB3VhzuwAB+XcAQSosOo64AIkPrgAKVBOACUR5wO4AcqxUOxkAkwGJYZRjMPBYB3SA0yUdU6SMJdMDZDkJ3RHNimiED8AWKtWASOping0h0LGMCbi2bZJGkOR52ibEMApJoQnCeEpFkeU7HjeFPG8SB0yzdIzlgGiElQSUkwgZC7SgMIIhnRgBSFStJMnWJjTrKAl0CDVJ0FZhrWCBkmTwqJ+WQHSul4pSoFmZBURwAAWLSWjE9EDLBGca0gyyLLtCS+KY4p0GoRFhDDRyjERZFCHYKM2QXBTdE9ZyjA7HtID7Nt0EvQLAhgyyjBUuo1B7c46jqP192HRK8qgfNJTS5F+3lCqR2c1NJMTKE2uTaolngMFklEjMq1QqJ2gQfq0UnaT4XYM4dXnWFnHhVQNA9edSkcZwtF0OhdDcKskUFNT0kyec1G4DAnF1VyjKkuTkD6ZAAEdMkxZAHzwGs6DM7JPqcOg8QSPBfq+2YOxfHixyQ4bpyiUJxrnKtpuKUYZB9Sb0UW69ihMUCMbgi6CjketIHgtCMLA+UCrU-TTEM4pVxwwIKm8owAiRNIMiyYbGHgRoTuQKCIBgmp0HaAbEIzIkEkYZBGqidhuAIC75QR+Exr6xHJJiWjQwAFX84z7qp3X6Npxk3KN3lugUvoIngRgVISD6vrM2BsmAWMcJIXcAFIAAkdwqCGKjAbzgGl2X5agBpojbNXinhzXNLu+BtgAYQa+iAHZ51nRpzfpo21mZsPoJ6qAMASbYe2h7XkaiJJTXx6EkREkmyaiIjQKKVmoDl3JByCZyF0IDTh+qyB2mu5Pig1ia-Wp4ozISvvJxWzQSYT0aE79Wbay0N41-RGKGO3qAk4X6FZcK666ctyvZTXHjj6MUINhnia4d3qBi1LMBdCv2vqVXUf94TWWNOwEszMwpSW4NwOo0xbJn3vrdSAwATJmRwCZf4wlQwPiXD+b68Vfr3RtswO2yAHZOxdv9N2L4XzZHSjgISdECGhiIelbIO55A7hfGAAA1LuMA3dMI8LAM1Fhpt2F4CIc1bhdA3jRD4YI4Rz4ZBgAfJlagb4KiQy8o5Yw3BLwTzyjERgICSZgLQowJI7AZZp30UpLqnUhbJhAKmIAA

**Comment by jheer** [comment]
Thanks @roying, it does indeed look like there is a bug in the step adjustment logic for "non-standard" time units. We'll investigate further and fix.
