### ISSUE TITLE
Load url in href by dblclick

### ISSUE THREAD

**Issue by eeyshen** [vega/vega#2285]
Is it possible to define the event to call href? Such as, A URL to load upon mouse double click. Thanks.

**Comment by jheer** [comment]
Currently this is not possible. We intentionally mirror the interactions supported by standard browsers (including the use of shift-click, etc) by creating an HTML `a` element and dispatching click events to it on href-enabled items (see https://github.com/vega/vega/blob/master/packages/vega-scenegraph/src/Handler.js#L143).
