### ISSUE TITLE
Custom defaults/themes?

### ISSUE THREAD

**Issue by ianhoolihan** [vega/vega#229]
Forgive me if I'm wrong, but currently I believe if I want to always use a different font, I must always specify it in the visualisation spec. That is, without manually editing `src/_config.js`, I don't believe I can set a local config. The reason I'd prefer not to edit `src/_config.js` is that (a) I want to keep my config as part of the project, separate from Vega, and (b) it might get over-written when I update Vega etc.

I'm not intimate with Vega (let alone JS), but I wonder if the following (pseudo-code) might work:

* add `"theme": "/path/to/theme.json"` to the high-level specification.
* 1st line of `src/_config.js` is `vg.config = <theme_config>;` instead of `vg.config = {};`
* `src/_config.js` then only adds default items not already specified in the theme.
* then nothing else (?) changes.

I'm not actually interested in being able to choose multiple themes, but this does come as an added bonus of this approach.

**Comment by arvind** [comment]
Vega 2.0 supports specifying a custom configuration when calling `vg.parse.spec`. While this isn't a full-blown theme system, it comes close to the use case you're describing above. The global configuration can still be manipulated by overriding the `vg.config` object, which local configurations inherit from.

**Comment by ianhoolihan** [comment]
Thanks @arvind -- I'll look into it, but it sounds like that will suffice.
