### ISSUE TITLE
Column to Row Transpose 

### ISSUE THREAD

**Issue by jennyfurrsmackie** [vega/vega#2291]
Please:
- Check for duplicate issues. Please file separate requests as separate issues on GitHub.

None found.

- Clearly describe the goal of the feature request. Why is it needed?

Switch data stored in fields or columns to rows in a new table or feature class.
This is useful when your table/matrix stores values in field names (such as Field1, Field2, Field3) that you want to rotate so they're arranged in rows. It lets you switch the field names and the corresponding data values in the fields to rows.

- Describe an envisioned solution. What do you want the new behavior to be?

A quick check-box or toggle that would transpose the underlying data directly from the viz view. This way you don't have to open another db or dataviewing app to manually rotate data that includes headers.

- If applicable, share mockup images or links to examples illustrating the desired output.

![image](https://user-images.githubusercontent.com/1388685/72111149-cbbd2f80-32ee-11ea-8287-c1465f4cc402.png)

- If applicable, share JSON spec designs for how the behavior would be made available in Vega.

**Comment by jheer** [comment]
Vega provides the [fold](https://vega.github.io/vega/docs/transforms/fold/) and [pivot](https://vega.github.io/vega/docs/transforms/pivot/) transforms to map between "taller" and "wider" (cross-tabulation) table forms. Are these not sufficient for your use case? If not, please provide simple before / after examples of what you'd like to compute.

**Comment by jheer** [comment]
As there has been no response, I'm going to assume `fold` and `pivot` are sufficient. Closing out this issue for now!
