### ISSUE TITLE
Bug: Filtering derived dataset modifies the source dataset

### ISSUE THREAD

**Issue by anagrius** [vega/vega#2309]
Hey,

We have had a lot of issues with derived datasets. It seems we have pinned down one of the issues.

If you derive a dataset B from dataset A. And you apply a filter transform to dataset B, the filter will also be applied to the original (A). That means if you derive another dataset C from A, the filter transform applied in B will also take effect in C!

Here is an example where we derive 2 separate datasets (table1 and table2) from the dataset called `input`. We apply a filter transform in `table1` but it all so applies in `table2`.

https://vega.github.io/editor/?#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwANgAMuxREgpG1fFoBM+w1HSs83WIwBeyLZBmy3ipZCfUZdAAbWC0AbSUIUAgYqEDUNxw-PHQAJzwAQRlqIO8oCmDWRLBdSLAAXxsosqN44shkGTUsnLzIAqCirW06CwBOMsqy6Ni49AT3QnRm7NyFfMLi0tih2JHYj3H6xhkZZFSAJWnGVlD5Bc7ivUGqsHWYzYmk+G5UvcPj0-n2xa1lmNWMXutS27mk6W+HS6OAAZsFYMhBkoALo+IxqdApcLDGpjJ5QHaEewKXE-S6hHARUZAyDqLQARnOkBhjGQQTUWgALIDqcBaRycBYmSy2QKdDzRny6TgAMzC1nshm6CVrflc+WirQylU06VgUQaxU4ADsOqiapw2kNYoAHOVccibjjqY96il2HNbkZpKxUvBtjIiXgSS68Kl0DJYDDXqhsdTqvGHi9UAkZMGkgAhACqAHEwAAJACiB0LYAAPABaKvVmu1uv1ishxNQPAAT0I9RZQTw+ybiYaAA9CKl3Bi8KxUFw1GAAHxgGWQXEQM13JcPNsdyasvvx5kKsV7zVe0bJNKZWbFPn+QJBMEpdItOYroyNGatLRX0w39yvx9uZ9QOC6Z3H4X7BGCrzBvaibQaMjorLcwJ4m66AesgFg7t63C+v67iEsSx6QGGEZRjGcbxkhGwbvUhDbseGwikaUCMRy9EPLA97nu+OCfgE4FJBxZ5-pAAENE0wk8aBfG3kkv4XiJbFYRCknXvxgGQSJa6wbE8EAiiaKAfAwTIBSYBUkCpJ1O4LxBK8mEtu29SvGoOzgYRajcBgOwfpAY6YEk7qesx+54RyOqQOG2SXn4SBoPURk9tQrytlYmkrPpIC+BgqQANameZCYntR7hpPA9nMqknk+X57iBf+hGNC8aiXmuYk9iOPFrkYXYySBCDGdZ3C2SO1qhQpXVQAOPmqb1kCqBoiBgKQYCcuNzZQK201gbNJhmHgS1gBh2mjCukCsIQY4tetp4PvJkksXeQnyaJcncSBD2yeJz2KVAUxvnMKnbZM0zCaJOzvEcLlfID0l4bs+yQycoSidh7WI9DfVA0ku34AdR0-ZALxvAjnymbx37PK8EOk2l8bHcuOpIURjklX65UwpVsaSTVAWobk+Oko13DNR+rWNO1ovXT101GQDUA2XZo1JHSolTTDFMqOoLBgBWYDzdry2raJm3q2pxjIKYuPLUdWlsWdF2YldzY3Vxct8h9gGcaDBOvW7h5MWJ-31RNkB-RJmOw0kYffSH4Mk1DZNSRrtLwx8Cdrc7qPx0jW2R7gFt7XjGf9kT1Pp6bs2l9nXz03p1LHbBjr2kAA

```json
"data": [
    {
      "name": "input",
      "values": [
        {"id": 1, "field": 4},
        {"id": 2, "field": 6},
        {"id": 3, "field": 10},
        {"id": 4, "field": 3},
        {"id": 5, "field": 7},
        {"id": 6, "field": 8}
      ]
    },
    {
      "name": "table",
      "source": "input",
      "transform": [
        {
          "comment": "BUG HERE <-----------------------------",
          "type": "filter",
          "expr": "datum.id > 3"
        },
        {
          "type": "pie",
          "field": "field",
          "startAngle": {"signal": "startAngle"},
          "endAngle": {"signal": "endAngle"},
          "sort": {"signal": "sort"}
        }
      ]
    },
    {
      "name": "table2",
      "source": "input",
      "transform": [
        {
          "type": "pie",
          "field": "field",
          "startAngle": {"signal": "startAngle"},
          "endAngle": {"signal": "endAngle"},
          "sort": {"signal": "sort"}
        }
      ]
    }
  ],
```

**Comment by jheer** [comment]
Thanks for sharing. I double-checked this example and the derived data sets are fine. For example, if you look at the data viewer in the online editor you can see that `table2` is being properly derived. The problem comes about because you are defining the color scale using `table` (the filtered dataset) as the domain. This results in an undefined fill color for all filtered items, and so while the contents of `table2` are being visualized, some of them have no fill or stroke color.

If you change the color scale domain to be `"domain": {"data": "input", "field": "id"},` you will see all the items as intended.

**Comment by anagrius** [comment]
Hm, bad example then. Pretty sure we are seeing derived datasources impact each other though. I will try to see if it is just a brain fart.

**Comment by jheer** [comment]
If there is an internal error regarding the routing or reuse of Pulse objects within the dataflow it is possible that derived sources might interact (related issues have occurred, and have been fixed, in the past). Happy to look at future examples and fix any bugs we can isolate.

**Comment by anagrius** [comment]
> related issues have occurred, and have been fixed, in the past
Yes, I reported a couple. That is why i suspected that being the culprit.

You seem to me correct. The color issue was the problem in our own code as well! Thank you!

Maybe the takeaway from this is that it is quite surprising that the `scale` function fails silently if the input is not part of an ordinal color scale.

This might indeed me the root of several of our issues.

**Comment by anagrius** [comment]
It was the combination of `scale` and then later `project` that filtered out the values.
