### ISSUE TITLE
Support for mix-blend-mode 

### ISSUE THREAD

**Issue by alangwilson** [vega/vega#2311]
Scatterplots (among other chart types) would benefit from the ability to choose a blend mode such as "multiply."

It would work similar to blend modes in CSS:
https://www.w3schools.com/cssref/pr_mix-blend-mode.asp

A D3 example can be found here:
http://bl.ocks.org/exakte-aesthetik/fec95cd6e12cc05c059a

The JSON would like something like this:
"mix-blend-mode": {"value": "multiply"}
or
"blend-mode": {"value": "multiply"}
or
"blend": {"value": "multiply"}

**Comment by jheer** [comment]
This could be a nice addition, but requires more design:

1. Where should blend-mode occur in a Vega spec? At the encoding, mark, or group level?
2. Can we implement this with (roughly) equivalent results using both Canvas and SVG?

**Comment by jheer** [comment]
I have a candidate PR for this (#2422), which adds a `blend` encoding channel, and supports both Canvas and SVG.
