### ISSUE TITLE
Expose index and tickCount in axis's backing data?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#2312]
I'd like to create a plot with larger tickSize for first and last ticks. 

However, we currently only expose `label` and `value` in the data object for custom axis encodings.

Is there anyway to access the tickCount and the index of the tick?  If not, we should consider exposing this.  

(I need tickCount so I can check `index === tickCount-1`.)

**Comment by kanitw** [comment]
NVM, I just realize I can compare `datum.value` with either `domain(scale_name)[0]` or `domain(scale_name)[1]`.  :)

**Comment by jheer** [comment]
You can use the existing fractional `index` property. See https://github.com/vega/vega/blob/master/packages/vega-encode/src/AxisTicks.js#L44
