### ISSUE TITLE
SVG Mark

### ISSUE THREAD

**Issue by ghalimi** [vega/vega#2313]
This feature would consist in adding an SVG mark to the set of existing marks. It would allow the display of arbitrary SVG content on a visual. This would be particularly useful for rich text annotations containing:

  - Different font families
  - Different font colors
  - Different font sizes
  - Font icons
  - Additional cosmetic decorations

An SVG mark would have the following properties:

  - `content`
  - `width`
  - `height`
  - `x` (for the bottom left corner)
  - `y` (for the bottom left corner)

Ideally, it should be possible to customize the displayed content in relation to the visual's data using JavaScript's template literals. The proper way to bind data to the SVG content has yet to be defined.

STOIC is happy to contribute some resources to implement this feature once it has been thoroughly discussed and specified.

**Comment by domoritz** [comment]
I moved this issue to Vega. Could you expand on how this could be implemented for various renderers and why the existing marks are not sufficient?

**Comment by ghalimi** [comment]
> I moved this issue to Vega. Could you expand on how this could be implemented for various renderers and why the existing marks are not sufficient?

We have yet to define how this could be supported by different renderers.

Using combinations of existing marks would allow the implementation of certain scenarios, but not all of them. This is due to the fact that SVG is very rich and quite powerful. This is especially true when using the foreignObject SVG element. In fact, a first implementation might limit itself to a foreignObject mark (aka HTML mark). Having such an HTML mark would allow the use of things like icon fonts, which is not possible with the existing text mark.

**Comment by domoritz** [comment]
One of the design goals for Vega was to be renderer agnostic. I'm not sure an SVG mark is something we would likely want to add without careful consideration. However, if you want to push this idea forward, we can give you feedback and iterate with you.

**Comment by ghalimi** [comment]
> One of the design goals for Vega was to be renderer agnostic. I'm not sure an SVG mark is something we would likely want to add without careful consideration. However, if you want to push this idea forward, we can give you feedback and iterate with you.

Would limiting ourselves to HTML make it easier to support all supported renderers?

And would something like [html2canvas](https://html2canvas.hertzen.com/) be an acceptable option?

**Comment by domoritz** [comment]
> Would limiting ourselves to HTML make it easier to support all supported renderers?

HTML is neither a subset, not a superset of SVG. I don't understand what HTML has to do with the proposal. Can you explain what you mean?

We will be doubly careful with new dependencies.

**Comment by ghalimi** [comment]
> > Would limiting ourselves to HTML make it easier to support all supported renderers?
> 
> HTML is neither a subset, not a superset of SVG. I don't understand what HTML has to do with the proposal. Can you explain what you mean?
> 
> We will be doubly careful with new dependencies.

The primary purpose of the proposed feature is to be able to render rich text annotations, with different font families, sizes, styles, and colors, including font icons. These annotations also need proper alignment and wrapping, which is something that HTML is really good at.

Fortunately, SVG offers the ability to embed arbitrary (X)HTML content using the [foreignObject](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject) element.

Therefore, implementing a full-blown SVG mark would make it possible to embed arbitrary (X)HTML content within a Vega/Vega-Lite visual, through the intermediation of SVG's foreignObject element.

I totally agree with you that the inclusion of dependencies should be considered very carefully. I wish we could avoid it, but I suspect that most browsers have a long way to go before we could implement a proper SVG mark without the addition of some dependencies.

**Comment by jheer** [comment]
Thanks for the suggestion! However, an SVG mark is not something we plan to add, given both the likely implementation complexity/bloat and our desire to support multiple rendering options in a relatively straightforward fashion.

**Comment by ghalimi** [comment]
> Thanks for the suggestion! However, an SVG mark is not something we plan to add, given both the likely implementation complexity/bloat and our desire to support multiple rendering options in a relatively straightforward fashion.

I understand. Thank you for your consideration.
