### ISSUE TITLE
Support axis labelOffset

### ISSUE THREAD

**Issue by kanitw** [vega/vega#2317]
Currently we only have `labelPadding` for axis labels. 

Without using the axis encode block, we can't shift the labels in an orthogonal direction, for an alternative axis style, like in the [following plot](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSlU3Co2Sx5ilQF91ESBiMBrMwbwBPQmQzSHhGI3gxYNUobkJ0MICzAAY6AGZXDUhkJXhuTUYlal8NdwAPEogqqAAzOzFNEIBJAFkAEQAhAH0AJR1C4rdqqACgkIBHVnQlPGZ+qjVSqsh0MsZYSuH3MXR2ZDEAMTFWWEQzGvQxWGQhrcgdvbEAYW4xbiNNrfc8pQLZ5V8kDw9jwIW0eFYqC4v2QZQAvAiAIxqKAUS6sYI4JSsMRiTJfZZo46YqAAYmSFMgS2q+K+2Vy+QGnzpD32G301Lpmgq+kgRIxZgAbM5OTTRWARVtJVVae5-Mz3HV9o0cJAetwCDkugAVbgYPDcey9fpFRZ3UYkyCTaazXSzBa3ZardYK5asw7HU7nS7XR3Ve67fYvN4fDkE77KP48FS84GwUGq8GQ6GaWEIuHImJ89Ek7G42V0-mW8mU8UF-05PIFU1h8MBx7ssCgcPLTTy3lFswiYXiiDSqWc-sSx2QWCMABeJOAYE5K2o1CMwmBITyrBmZuGQMClutMzm9uCS2ltNCyjqxVr7mdjebm-dAAV0JpqxewCJEQAmP0jRjwLwAZQnElEUFb8gV-Lxg3eEJSWfRojw0EURSAA): 

![image](https://user-images.githubusercontent.com/111269/72691586-51a15d80-3adb-11ea-8031-0725dd73a276.png)

For Vega-Lite users, this won't be even possible (since we don't really expose the encoding block to users).  So I'm thinking about adding this to Vega-Lite.
However, I think this would be convenient for Vega users as well, so it might make more sense to add this at the Vega level. 

@jheer -- If you think it should be only in Vega-Lite, I can do it only in VL as well.

Note that, in this plot, I use the hidden axis encoding in Vega-Lite to override Vega's axis encode's dx and dy to express what I expect to be `labelOffset` = 6 (which translate to +6 dx/x-offset for x-axis and -6 dy/y-offset for y-axis).  We could also consider exposing this hidden implementation, but I feel like it's not really a good syntax for Vega-Lite. Right now, I only keep the implementation there so we can quickly experiment with this kind of things.

**Comment by domoritz** [comment]
I'm in favor of making labelPadding a Vega property.

**Comment by kanitw** [comment]
> I'm in favor of making labelPadding a Vega property.

`labelPadding` is already a Vega property.  We're discussing if we wanna add `labelOffset` here.

**Comment by kanitw** [comment]
Also note that making Vega-Lite output dx/dy in the encoding block isn't a good solution since it won't work when we use non-zero labelAngle. 

On the other hand, we can't have Vega-Lite output just x/y.offset without overriding default placement logic that Vega produces.

At this point, I'm pretty convinced that doing it in Vega is the right solution.  I'll send a PR.
