### ISSUE TITLE
Remove invisible marks from the scenegraph

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2329]
For example in https://vega.github.io/editor/#/examples/vega/zoomable-scatter-plot, a lot of marks are outside the view but still in the scenegraph. Would it make sense performance-wise to remove scenegraph nodes for elements that are invisible (circles in a scatterplot, lines/areas in a focus and context chart, ...?

**Comment by jheer** [comment]
I'm not sure what you mean. In the example above they *are* clipped, as clipping is a graphics-level operation. Are you suggesting we remove them from the scenegraph? Or removing them from output SVG (for that renderer only)? Or something else?

**Comment by domoritz** [comment]
Sorry for being imprecise. I was suggesting to remove elements from the scenegraph that are completely invisible. I updated the title and issue.

**Comment by domoritz** [comment]
I realize that there is value in keeping these elements in the scenegraph if we want to support animation in the future. So unless you have an idea how we could cleverly remove scenegraph nodes, feel free to close this issue.

**Comment by jheer** [comment]
We use fast O(1) bounds checks to avoid rendering offscreen elements for Canvas, so there is only the iteration cost there, which in most cases is neglible. And even if we remove elements we still have the cost of checking them against the viewport. As items can enter/leave the view at a high rate that could result in high DOM churn for SVG rendering, which might actually hurt performance in a user perceptible way. Plus there is the code and maintenance overhead of managing this, so for the time bring I’m disinclined to explore this further, unless we can point to real use cases where this would make an appreciable improvement.

**Comment by domoritz** [comment]
Sounds good.
