### ISSUE TITLE
Always support null as default

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2331]
Right now, users need to set stroke dash to `[1,0]` or `[]` to have a continuous line but it'd be nice if one could just write `null`. Similarly, one has to set `cursor` to `default`. It would be nice if `null` to get the default just worked. 

cc @kanitw

**Comment by jheer** [comment]
Right now we pass provided values through to the underlying graphics APIs (Canvas or SVG). There are a few exceptions where we special case things (e.g., SVG fill handling) to deal with platform defaults, but in general we avoid having to do this. So I'm sympathetic to this request, but also skeptical. What is the full space of `null` -> default value mapping that we would support?

**Comment by kanitw** [comment]
I disagree with this request.  

For certain things (e.g., axis domain/ticks), the default is enabled, so passing null to get the default is counter-intuitive.  

```
ticks: null // = enable???
```

**Comment by kanitw** [comment]
Also, this proposal would be inconsistent with how we handle default in Vega-Lite.  (`undefined` = default, but `null` could mean something else.)

**Comment by domoritz** [comment]
Okay. Let's not do this for now then.
