### ISSUE TITLE
Bug: Derived Datasets, modify the original in case of filter + formula transforms

### ISSUE THREAD

**Issue by anagrius** [vega/vega#2338]
When using derived datasets we have stumbled across problems with formula transforms used in conjunction with filter transforms.

See example:

https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KLEbUZ6ADaxsYANpKIoCMajrUyHZAAeCg8cgVNrCzjwAnZ3Yjyo7RjIATbGAof0JWPEskZHgAa3ZuGzAAXztUiABdRQhIAPQ8TBx9EyMTU3RzSwCARlsyqEcNZ20ir2MQyEIdaoAGHpTs+rAOrpwAJj6BtsMoUbAAZkn0soy0wcM2yDMXKAD5urLIaVY3eB3dXNqszfd0GVgAM243VGxiodKhqDwAT0IXSAPRgaPDINwHL6QZBWQjgnDWSDTKZfT5DSC-f6WJ4vVgaTDrNHQ2FVfKsVB0QhgADUYFqBPqkHQLVmiK+yxMqxMy1WqSAA

If you check and uncheck (set the signal) multiple times, the value of `p` in the `d3` dataset continues to increment. The expected behaviour is that it would only increment once, no?

This works as long as we do no filter, but this might just be a symptom.

**Comment by roying** [comment]
In your example, the values of field "p" in dataset "d3" continues to increment because the _new_ formula field name "p" is defined **as** the same original field name "p", and so each time the signal "x" is triggered, the dataset "d3" field "p" values are updated.

For the behavior you want, use a different and unique field name in the formula transform.

![screenshot_vega_test](https://user-images.githubusercontent.com/37225856/73080151-5f683180-3e93-11ea-857e-0577c4ab974c.png)

https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KLEbUZ6ADaxsYANpKIoCMajrUyHZAAeCg8cgVNrCzjwAnZ3Yjyo7RjIATbGAof0JWPEskZHgAa3ZuGzAAXztUiABdRQhIAPQ8TBx9EyMTU3RzSwCARlsyqEcNZ20ir2MQyEIdaoAGHpTs+rAOrpwAJj6BtsMoUbAAZkn0soy0wcM2yDMXKAD5urLIaVY3eB3dXNqszfd0GVgAM243VGxiodKhqDwAT0IXSAPRgaPDINwHL6QZBWQjgnDWSDTKZfT5DSC-f6WJ4vVgaTDrNHQ2FVfKsVB0QhgADUYFqBPqkHQLVmAH1CE1YCzZBYkcsTKsTMtVqkgA

**Comment by anagrius** [comment]
Hey, thanks. I am aware that the names are the same, that is the point of the bug report. I still find it very surprising that a derived dataset is stateful. I would expect a since a signal in `d3` changes the transforms would be applied to the "source" (d1) to produce a new values in `d3`.

If that is really the case, it is not clear from the docs.

**Comment by anagrius** [comment]
@jheer Maybe you have some input on this?

It might be related to this one as well:

In this example I am deriving a dataset 'order' to determine the 'sorting order' of the categories. If you the sortField is empty it sorts by 'category' else it sorts by 'value' of the 'position' in each category. In other words, it orders by category name by default, or by the 'position' that you typed in the text field.

The strange thing is, that if you leave out the 'aggregate' transform in the 'order' dataset, it the data in the order dataset will look like expected, but the `lookup` will fail. This does not happen if we do the `aggregate` step at the end of the transforms (try commenting it out).   

https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAZgAMuxREgpG1fFoBMAFgNLIhdGrWMZ1LaMNRYpmegA2sFoA2koQoBARUL6oyFqQ0gBOeABijMh+agqhEZDsLpk4wJAuhKx4cXjIAB7lAL6ekZAU-qyxODKsfn7Z9dnhkVHoMXGMsADK3EnImQ05rIRq6JVxABSJKWkZYACEALy7YB1dYABkJ2DrqelqO-tgAOT3AJSQPUoAup6Qi3iYOCGRfqNaJtKAlMpZAZQZp+VqBf7ZQGQeBLGiTACecQAQgooIRuN48Dw5DhILpcU0WqDdHQAOy9KFhZGo6gY7EU-GE4lxACMFJhrS0NIsDMZRRRlVZCUxpJx8jxBOY3NJFn5VK0PLoPNFUPFLLZso5iqJsji2jVsOpdAAHDqBnrJQaoABBI1c02k8nyymWoVau1IiVo6VxV3ezlKj1QPnegVWgBsAYiDuDMpdbsjJKgqtj6pwNIAnEmmUGpWnIGGFe6s5Bzbnffm6FZi2AU2W4gBhDMmmte6F5sA0xOzQP6kOkrvh43K6MWwWN7Uj5PMx3jqCTquZuI5-sNwd0EVLktj8sb+zTqO1udW+mIsDvHqzIE5EFxSZqZAJSEDeLcVgJeBQWKGRSnKJdIDwBJ0BkWAADNJlQYI7zCMBkJyDsAHkAFksIAUQAOQAFTiAB1ZAwFgxg-EqBIwD-PAwAjHtYDARhYLAaD0RYFxqDARB0BY9hkGQGQLmQBj4No9YeLAFZ0lgcjlHI9YwHYdEwFLNkjxyPB0UIIDKOoz9v0ZKBqkIL9SW2UYJimG4AB97Nkn5WFQOgmOJMA7kuTY1BeNCW2fKEIL0oDVBkNRuGUEzGUgWCoOGf4jj8eVks+NCjHWLRgCgSjrmCHL4h8fwRnGSZKhuAB+B443uMAcHuTTpXuSAwFqd42u0oxuGIYJvhEhSAH0oJkABrSB0tMowBL6kbxofUzAoy9dsLwoi4gASXY7iWMg6C4IQ1iWL8ZBYIY+iwBYci-G4bhRvmVT0iiij0CowIuqgXT9LidBqGoBJhGWD7IH+v9CDUvqmsxSapsgHr4TAIJIAwKoJuBvKMgRpG5rR5bIBm-5IBxhbGVqO8SYgO0gsGRLPvQdgTpizK-wAoDwTAu8IJGg6EkQhFTOpxovqAm67vmJmf3i7g+agd9jOB0bkHLKGJcaDG1CxldU1xqbdzhWboPm4GCcRonDYmgLybeCAH1qIA

**Comment by anagrius** [comment]
I am still unsure what the expected behaviour is.

**Comment by jheer** [comment]
Thanks for raising the issue. The intended behavior is to be stateful, as @roying notes. Re-executions of data transforms are evaluated as continuous queries over the same pool of data objects, not "new" queries that produce new output objects (except, of course, for transforms like aggregate which produce new data objects as output). Among other things, this design helps us maintain good interactive performance.

A derived data set takes two forms: (1) if no writes will be performed (no downstream transforms modify tuple properties) the original tuple objects simply pass through, (2) if writes can occur, copies of the original tuples are made and become the input to the new dataflow. The original example above falls under case 2, in which the tuples in `d3` are new copies made from the original tuples contained in `d1`.

When a property is modified, its prior value is overwritten. The actual tuple object persists (we don't create new objects, we reuse the existing ones). Thus when the filter updates, the same tuples in `d3` are revisited each time, and so the values continue to increment. (In general, one should probably not overwrite existing data properties with new values based on prior values, unless there is a strong reason to do so!)

If the original data source (`d1`) is modified, then (and only then) will the values of all modified tuples be (re-)copied over to the derived tuple objects in data source (`d3`).

I agree that more/better documentation could be helpful here. I think a natural place for this would be to add a new section to the [Data page](https://vega.github.io/vega/docs/data/). Let me know if anyone has suggestions for additional places and/or specific content items to include.

**Comment by anagrius** [comment]
Thank you. This explains a lot. I think the data page makes sense as well as in the Transforms section maybe. There are hints some places about objects being reused, but maybe an example could be good.

Perhaps under the documentation of pretty much every transform that has an `as` field, which a warning that indicates "you probably want to not override an existing field".
