### ISSUE TITLE
More fine grained log level control for command line utilities

### ISSUE THREAD

**Issue by davidanthoff** [vega/vega#2348]
It would be great if there was another command line option that allowed me to suppress the warning `WARN Can not resolve event source: window` that one gets when an interactive spec is converted into say a PNG, while at the same time still having the log level `warn` for all other problems in a spec.

The specific scenario where this is helpful is [VegaLite.jl](https://github.com/queryverse/VegaLite.jl)'s Jupyter integration. Whenever a spec created in Julia is displayed in Jupyter, we send various MIME versions of the figure to the Jupyter client: the actual spec (with its MIME type) and also always a PNG version, so that the notebook shows something in Jupyter clients that don't support the vega MIME types. In general this is super robust, but the problem is that whenever one now shows a spec with interactive features, we use the command line utilities to create the PNG version, and for any interactive spec we now get this event source warning that we don't really want to show. For now I've changed the log level to `error` during the conversion, but that is also not ideal, I would actually like to show other warnings...

**Comment by jheer** [comment]
Hi! You can provide a custom logger if you would like more control over the error messages: use the `view.logger` method, which is inherited from the Vega Dataflow base class (vega-dataflow/src/dataflow/Dataflow.js#L126), to set a new logger instance. You'll need to provide an object whose API conforms to [vega-util's `logger`](https://github.com/vega/vega/tree/master/packages/vega-util#logger). 

Alternatively you can also override the View/Dataflow's log methods directly. Here's one possible approach:

```js
view.warn = function() {
  if (arguments[0] !== MESSAGE_TO_SUPPRESS) {
    // if not suppressed, use standard logging mechanism
    return this._log['warn'].apply(this, arguments);
  }
};
```

Either way, you can introduce logic to intercept the specific message you'd like to suppress and not pass it through.

**Comment by jowens** [comment]
@jheer is there any way to do this filtering from a command line? I call `vg2pdf` (on the command line) on many graphs from within a python script and get pages and pages of this particular warning. If `vg2pdf` had a command-line option to suppress this warning / if there was an easy change I could make to the very short `vg2pdf` script, I'd be delighted. (Figuring out how to filter stderr from python subprocess calls is surprisingly difficult and timesinkish.)

Below script inputs vega-lite, outputs {svg, png, pdf}.

```python
def vl2img(vl_json_in, fileformat):
    """Pipes the vega-lite json through vl2vg then vg2xxx to generate an image

    Returns: output of vg2xxx"""

    # TODO would prefer to do this properly with pipes
    # using | and shell=True is ~safe though given no arguments
    executables = {"svg": "vg2svg", "png": "vg2png", "pdf": "vg2pdf"}
    try:
        exe = executables[fileformat]
    except KeyError as e:
        print(e.output)
    try:
        app = subprocess.check_output(
            "vl2vg | %s" % exe,
            shell=True,
            input=vl_json_in,
        )
        return app
    except subprocess.CalledProcessError as e:
        print(e.output)

```
