### ISSUE TITLE
make scaleX and scaleY respect the x and y position of a path centroid

### ISSUE THREAD

**Issue by mattijn** [vega/vega#2349]
See following animated gif:
![ezgif com-optimize-8](https://user-images.githubusercontent.com/5186265/73372825-1b709480-42b8-11ea-91c4-917999933c55.gif)

The `path` mark is a custom shape drawn at a fixed `x`, `y` coordinate. It is connected to a `scale` signal that controls the `scaleX` and `scaleY` mark properties to control the size of the path.

It would be nice if the `scaleX` and `scaleY` were connected to the centroid of the path. So that upon rescaling the path mark stays centred at the `x`/`y` coordinate.

Created with the following spec ([long editor url](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAFgAMuxREgpG1fFoDM+w1FimZ6ADawtAbSURQEb1AepkWpB2AF4BNj6QFE6sATiiBh7ekOyMMmpawJCphKx4gQBO6DLUYVCoqVoGZegAHloATNa2eMiEWgCMugC+iT0QALo2kGroeJg47j5ePr7o-oEAygDyAKoASgDCAKIKiUZRjjEuE3ve0zNJCw0JFxEAGlqi4beQAJqPzxeQAAqBALJgXR0ADsogsAE52uCLMCAGxw7SQ4HA+QAWiBogAHBZRFDRHpwcDdO12sCwAAZQEg2G6PS6THQzHaCwMzGwtEYzHIizaerg8HaRHAzGY9oUqkM8H4iywiFE+qw9osjl0WGw0TgxWawn89W6UTioHg3T1dqK-UwkXwpUq2EihX1erC3TAmWKw10KXA+os7TtbTwv189oq73w+rM4WQs2wxEe6FSx28lkWVN6dnokHA3mdXSw6H5-n1THxv3AxOIgPaV0B0Oa+l6cs+mP8+NqmVO0lc0TZnsq0XEjWY4k4iGNCxt0FK428xGQ5n9xqmzoQ-3EvNkylG0T5ytqhk5mX95k98EK5ksqUWMVbz0a-2E+HCvSpiz90Rg3Htxsyie3qXthqNLVmaYLgv2rpchCdoyrohJwfGRK6DKYKuhGiJPJmrKmoioqpiSxYGv+mL3qCMINmyR6ZgWGomtC7Q4We8b8ixJFgvoDF9tR2i4qSFh8pC9L+kRYDtHQBjcbx2akh+XKEtobYCkSZ6dCR4JMtoKqasioimvSjqwsWJrxk6uI+pWeaxriWmYnyMpNuqwIMU68a0oi7S2RG8IftCNmOgKNIavESpMh6DJCQi+Zsjx5ZaQKyHIt6tleh+YWxp01bhfmqZwnF8TVtoan1PEbphfi9J2nm-I8XZaJiboYUuvJ0mCk6hUotRIqaqa5pqZC4IesignntJ3ZcUaKnFmyxVOcVxWDTBWJqu0uLavCWmXvOIoQqKAaDR+PJ6MWuEmjCWmNLZuIkYR2auoN1aGeqhmWjSTlabmsbRT2H5uYNuZNVCJKnVKWkmgOumNPmNIih6dq2VYM4+liPr9tGzKmvxWL+v6sOyhpfKGdWRJmv2TI0vm-pQVysKw4V+KSnB158gyEEDoqcLFfyIo3lSsrFVCtJOtGEKaVhdr+bZgoioKWKw5jULnoOCL1P24vM55BJVbDJLlk5gkprFWFQsy2Wmj9NUeliUq8kLH6drpdZDU5Hk8Tywo85yHnLQypIJTxoago2xpQjCxVcpbJFEvxvJctW-Khgd+KzeqxqR5bwrluqAaQ9imFAnrkLdgGsY8a2t4asXzL6E19J5yCHkVUyTLxMa0Kw7X03ep0TkMm+mZEn6AYZynT4Dbez26aS6XFaeHVAnaehdTxHlNnd4-8epuc8nBOsq5m8LARC8SNDpHlywqPKknxld7-PsoHdeeYkoX9SwxG5E9o6DFKiatr0+j6ZTSukMm-HC+I4aIgMnPVUcop76ngdaEs48v6u2LFKek3o66ykJDGfEjQewMQUuvfipofTtmErlfePI2KvijMyM+698R6A8tBUEtI+7z2clnFaJpnRsjfiaWkXM8bImKiqWi5NFQkTlOWIhvNUxqilqOa2OJxF9TtL2XhSNYagldFYcBdpQJ1yWoVEiO83aan2quaEcIERImgViHEeICTE1JGAYIkBTgQD6DMfovQlCDCUJADA+QADWxwwCTDOKcSAfhYjVDCS4T4UA8AAE9CDxMgIQUYiBdhfAAGb5G4KgDIwxRjjCgMsdY2xIBdGSZAZAMh4DcDUPE84MxICsEICMFoGQvFJFgHgIpoS2mRGiJkgAxNoeAwp0CYlqckiIdQcCZAQE4TJdR5BQHyYwZAjh0g4EgA8Op-SjCpNKWsxwmTzlbMgDsvZByoDvBObcJI2TNArLubs-ZgRfgvNebYeA6yHifLsNQBwjhAghACP815QQgVXPeKC+wTgoWMFCLU-pPifDYrAD4wJRhLnIAiVEzwMS4mBE2TEtJGTAiOFSMgdA+Q8kdLUMU9AFQJhVE6ASjphRijxNcFUVZKLIWHNUBoXJXQ-E4ueO0owFLDk3OpekzJ9KZCMuZfUtlGBOWRO5boXlER+UlDcCK8FqLDkmDMHkOpgIZXeHxUMWoxK3CJFWQijZCgoDcHyLsmQeRDnsG4AQYp3rIDUD9Y8oZMRYVgA9eswINyfV+saYGqAVz8l5FuZG9QWgY3IHxSALoQA)):
```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 400,
  "height": 300,
  "signals": [
    {
      "name": "size",
      "value": 50,
      "bind": {"input": "range", "min": 0, "max": 200, "step": 10}
    }
  ],
  "data": [
    {
      "name": "SOURCE",
      "values": [
        {
          "S": 20,
          "X": 5,
          "Y": 5,
          "P": "M 0.7539193767649177,-0.583519540970117 L 0.7604008938438986,-0.5877342994497881 L 0.8995436397026138,-0.6659619697996505 L 0.9021610537886713,-0.688262278073661 L 0.9572384146741291,-0.7267243789116649 L 0.9395224238333406,-0.7742100693699928 L 0.9417952494647346,-0.7960840792316699 L 0.9663627178757457,-0.8101598013539203 L 0.9675139042499143,-0.8202110391401067 L 0.9569494668942136,-0.8435792643389531 L 0.9591497677840333,-0.855351663407363 L 0.9566359604716539,-0.8738739683609709 L 0.970036537324495,-0.8982149813311285 L 0.9859175370848636,-0.936590293121492 L 0.9999998553001257,-0.9451173299108145 L 1.0,-0.9451174175587974 L 0.9694709210859844,-0.9677521082262802 L 0.9275123494066451,-0.9829367926571227 L 0.9044918224675593,-0.9822946059501384 L 0.8908176469864579,-0.9940377728295755 L 0.8641047890693376,-0.9950474859250366 L 0.8540868069945293,-1.0 L 0.8079747414427487,-0.9889621610859919 L 0.7791026474187557,-0.9921288625712525 L 0.7683586615196967,-0.938991488398146 L 0.7553440284980237,-0.9208251852857473 L 0.7476265623786071,-0.9100648645755044 L 0.7100079191102395,-0.9028105220696088 L 0.688230904235823,-0.8911432132581414 L 0.6638442962477016,-0.884606914873876 L 0.6485489909312989,-0.8781061762599881 L 0.6325190427911394,-0.8682298244884458 L 0.6325192640157642,-0.8682298822409069 L 0.611797191038379,-0.8194369321550452 L 0.5895422795527152,-0.7977971184534781 L 0.5818661891703745,-0.7754079019372587 L 0.585703242874799,-0.7553547126590857 L 0.578796546206835,-0.7199187546644599 L 0.594664300079085,-0.7180868484509093 L 0.6085862721071893,-0.7041467876596779 L 0.6235217641255797,-0.6840889451879273 L 0.6329883534091172,-0.6760439502077518 L 0.6326341717346642,-0.6635533106119182 L 0.6243705722121302,-0.6548432406217362 L 0.6221454688492267,-0.6397176050506718 L 0.6221453289508725,-0.6397166542057124 L 0.6332212366314576,-0.6348553337894318 L 0.6354401839675043,-0.6122654150278086 L 0.6202049986387725,-0.5906066185397794 L 0.6336644835395435,-0.5859968745027235 L 0.6757330546681655,-0.586488509134796 L 0.7539193767649177,-0.583519540970117 z"
        }
      ]
    }
  ],
  "marks": [
    {
      "name": "marks",
      "type": "path",
      "from": {"data": "SOURCE"},
      "encode": {
        "update": {
          "stroke": {"value": "#4c78a8"},
          "x": {"scale": "x", "field": "X"},
          "y": {"scale": "y", "field": "Y"},
          "path": {"field": "P"},
          "scaleX": {"signal": "size"},
          "scaleY": {"signal": "size"}
        }
      }
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "linear",
      "domain": [0, 10],
      "range": [0, {"signal": "width"}]
    },
    {
      "name": "y",
      "type": "linear",
      "domain": [0, 10],
      "range": [{"signal": "height"}, 0]
    }
  ],
  "axes": [
    {"scale": "x", "orient": "bottom", "grid": true},
    {"scale": "y", "orient": "left", "grid": true}
  ]
}
```

**Comment by jheer** [comment]
The scale is intentionally defined relative to the origin of the path coordinates. Vega does not currently have a mechanism for calculating a path centroid and performing scaling from that location. I'd recommend using paths defined in an appropriately zero-centered coordinate system, then use `x` and `y` encoding channels for any post-scale translation.
