### ISSUE TITLE
step size of graticules

### ISSUE THREAD

**Issue by mattijn** [vega/vega#2351]
Given the following screen recording:
![min_stepsize_graticules](https://user-images.githubusercontent.com/5186265/72664547-a96a9680-39ff-11ea-8dc2-3284ee9c4ab6.gif)
There occurs a certain undesired behaviour when changing the `step` of the `graticules` to below `0.5`.

The used spec is as follow:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "width": 500,
  "height": 400,
  "layer": [  
    {
      "data": {
        "url": "data/londonBoroughs.json",
        "format": {
          "type": "topojson",
          "feature": "boroughs"
        }
      },
      "mark": {
        "type": "geoshape",
        "strokeWidth": 2,
        "color": "#eee"
      }
    },
    {
      "data": {
        "graticule": {
          "extentMajor": [[-0.52, 51.28], [0.33, 51.7]],
          "step": [0.5, 0.5]
        }
      },
      "mark": {"type": "geoshape"}
    }    
  ]
}
```
or click [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgB3RgBMW2MAFYADMfURIKRtXwHpp81DHoAnsgBOBgNoQNEUBCBUDroeJg4AUGBkKzuYgaQIWGkYso6ygBC3O7crDaw8ooqjlFQAGbZGHgGkaUWeC6EyAl43ITcCspqfnWQZcihsc04kOzZufmQPUEAvtNgMyXRGO4A1jXz9Y3DUNTI3LCI6E3ddVCweDmryADquvo4AExLQZDw3KmeIwDEyH9TpTmsyWtWiSXCYFBr2o7lCjHgrDEOyhUUgyAAHnhkEo8ABZdBybLeLwiYx0QzPIwARjojwAHABdVRgLxkgDMbOZhhpAHYGUzNtELshCN4yYZmeKGYKgVFFvNICt1hFIA0TiM9gcjidZRAZkENNKZkA) to open the used spec directly in the editor.

**Comment by jheer** [comment]
Vega simply passes the `extent`, `extentMajor`, and `extentMinor` properties through to the graticule generator provided by the `d3.geoGraticule` method. So if there is something incorrect in the output, I recommend first testing the d3 method directly, and filing an issue at [d3-geo](https://github.com/d3/d3-geo) if needed.

Here I think the issue may be that `step` pairs with `extent`, and `stepMajor` pairs with `extentMajor`, and so on, and so the original example did not have the correct parameter alignment?
