### ISSUE TITLE
Cannot easily create proper arc (pie) charts with spacing in between 

### ISSUE THREAD

**Issue by dantman** [vega/vega#2354]
I'm aiming to create an arc (pie) chart like this example (just one pie):

![Material Pie](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-design%2F1579302979877%2Fassets%2F1NcYW-3DYktAAtsoaOYw4ehUN3fDhZZLi%2Fpie-vs-bar-dont.png)

But it does not appear there is a proper way to take this example pie chart and add spacing in between the arcs.

[<img width="216" alt="Basic pie chart" src="https://user-images.githubusercontent.com/53399/73582015-3bcb5b00-4440-11ea-83c1-c762a25ee222.png"><br>Chart](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAJgAMuxREgpG1fFr0GlkNejyYcAbSURQEd1BnpUyLZHvsADa+hh5QFOiBrMiwWs5h7m4J7pDqfgCCCi7JkABmjMiBaloALKHJULD2AE546TLUwVpWFUbIMmr1jb44unQAbP0AjADMABwA7ACc2hO6E0OiI6Il2R4AvuVhSRWpxTiQAEJZrVD5hftg-VsJkFXotV1NvQPD49Oz84vLZWthkO1Og1nmAhgMliV+lMxkMJv0JmMxuMRn8IJtUWAdjk0gcAMInVp5ApFLRDFqE+6PYE9UHgkaQ6Gw+GI5E3f6Ap40kZ0Ea6KEjKb9ZbLOFw0QY9EVLG3HFQAAiBN25xJOBGbI8dxqdWpWm5vP5guFolF-VE6pSHJ1qroY102mhulEtsGo20Ywl5ul-1lkAAooqcsrLhNzUZKdrurqbXaHU6+W83aGoJbIzgSnRBboSropiUlroRqbFh6MV6NT6AGIB25BrRjJOah4RkHpzPZ3P5wuiRYNlMg-p0N0jIZjfMLaZO-oSv4AXTZ-mq6BksFy3GqqDiwH8AE9CDTIIQCgozsTLkSLpB1jPsuslHPrAhIjE4tkvZAvD4-PBuIE19WoHgu77muaiMF4gT-jY3AYGBWhbrY9h+AETTyCeF4HGkkr-IuDQ0lu-BoPu8B2DQa7bnol43neoSQBg1QANaxE4r5-Due5+A88CQbk1TQXBNh2A4AHoEEvhYRq7TfmoeEYgCMh4Mg1RwRiRj5IEEE4PhxEgpA36-kpqHniqUCYQ2AAe-GwKY4F+KoGiIGApA6JeDbbpZ1mRH4JhmHgjnObeFTif8rCEAhMmnI2VKppiRlnuGnIuSpyYdAlmmxX4fZiQ2hDoEC0VbhEUQ0roQW3NwrAKdUABKuWMKwTExVZ1A2QcdksH52iUYFfwBe4vX3kYwTUICDXxIkrFqRpUB6X+85rgU8l+Ow3AEHx86gdUyDwHgPByAciDzQAXrI9gQfOkncNJym7IEImFA1W4fvuQ2AgAMndZ3JZV-EKWZeD8bWGHFOsIM9VREADdNsj5NQ10pFU24gm+1CsOoyAALS3ewhRwzWJ1+AAOpAVXcMteDcETqFEwAEoUVA7cRlNgET6TVIwkRM7AS6wOjsCKYwuT-qpJ0AOrIKY5gHDIa4YBBYMbEot7rEAA)

### padAngle

There is padAngle, however padAngle is polar and does not have the same distance between segments at the center and at the ends so it's not good for spacing. If you use padAngle and innerRadius together you can come close, however it requires a lot of trial and error/math and feels more like a hack.

[<img alt="padAngle and innerRadius" src="https://user-images.githubusercontent.com/53399/73582975-9b2b6a00-4444-11ea-995c-e71ca9b9cf72.png">](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAJgAMuxREgpG1fFr0GlkNejyYcAbSURQEd1BnpUyLZHvsADa+hh5QFOiBrMiwWs5h7m4J7pDqfgCCCi7JkABmjMiBaloALKHJULD2AE546TLUwVpWFUbIMmr1jb44unQAbP0AjADMABwA7ACc2hO6E0OiI6Il2R4AvuVhSRWpxTiQAEJZrVD5hftg-VsJkFXotV1NvQPD49Oz84vLZWthkO1Og1nmAhgMliV+lMxkMJv0JmMxuMRn8IJtUWAdjk0gcAMInVp5ApFLRDFqE+6PYE9UHgkaQ6Gw+GI5E3f6Ap40kZ0Ea6KEjKb9ZbLOFw0QY9EVLG3HFQAAiBN25xJOBGbI8dxqdWpWm5vP5guFolF-VE6pSHJ1qroY102mhulEtsGo20Ywl5ul-1lkAAooqcsrLhNzUZKdrurqbXaHU6+W83aGoJbIzgSnRBboSropiUlroRqbFh6MV6NT6AGIB25BrRjJOah4RkHpzPZ3P5wuiRYNlMg-p0N0jIZjfMLaZO-oSv4AXTZ-mq6BksFy3GqqDiwH8AE9CDTIIQCgozsTLkSLpB1jPsuslHPrAhIjE4tkvZAvD4-PBuIE19WoHgu77muaiMF4gT-jY3AYGBWhbrY9h+AETTyCeF4HGkkr-IuDQ0lu-BoPu8B2DQa7bnol43neoSQBg1QANaxE4r5-Due5+A88CQbk1TQXBNh2A4AHoEEvhYRq7TfmoeEYgCMh4Mg1RwRiRj5IEEE4PhxEgpA36-kpqHniqUCYQ2AAe-GwKY4F+KoGiIGApA6JeDbbpZ1mRH4JhmHgjnObeFTif8rCEAhMmnI2VKppiRlnuGnIuSpyYdAlmmxX4fZiQ2hDoEC0VbhEUQ0n0BZBTKMgyIpABKuWMKwTExYV0QWGV-zcKwCnVDVoH1e51A2QcdksH52iUYFfwBe4k33kYwTUICDXxIkrFqRpUB6X+85rgU8l+Ow3AEHx86gdUyDwHgPByAciDbQAXrI9gQfOkncNJym7IEImFA1W4fvuc2AgAMl9T3JZ1-EKWZeD8bWGHFOsCMTVREAzetsj5NQ70pFU24gm+1CsOoyAALSfewhRYzWD1+AAOpAVXcPteDcHTqF0wAEoUVAXcRrNgHT6TVIwkR87AS6wMTsCKYwuT-qpD0AOrIKY5gHDIa4YBBSMbEot7rEAA)

## stroke

You can get something that "looks" exactly like I want by using stroke. However this only works when the background is an opaque solid color and you know what that background color is because it requires the age old hack of hardcoding the background color as the stroke color. Setting the stroke to transparent does not work.

[<img width="223" alt="Screen Shot 2020-01-31 at 4 18 42 PM" src="https://user-images.githubusercontent.com/53399/73583141-6370f200-4445-11ea-8b6a-ec9f49d493f9.png">](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAJgAMuxREgpG1fFr0GlkNejyYcAbSURQEd1BnpUyLZHvsADa+hh5QFOiBrMiwWs5h7m4J7pDqfgCCCi7JkABmjMiBaloALKHJULD2AE546TLUwVpWFUbIMmr1jb44unQAbP0AjADMABwA7ACc2hO6E0OiI6Il2R4AvuVhSRWpxTiQAEJZrVD5hftg-VsJkFXotV1NvQPD49Oz84vLZWthkO1Og1nmAhgMliV+lMxkMJv0JmMxuMRn8IJtUWAdjk0gcAMInVp5ApFLRDFqE+6PYE9UHgkaQ6Gw+GI5E3f6Ap40kZ0Ea6KEjKb9ZbLOFw0QY9EVLG3HFQAAiBN25xJOBGbI8dxqdWpWm5vP5guFolF-VE6pSHJ1qroY102mhulEtsGo20Ywl5ul-1lkAAooqcsrLhNzUZKdrurqbXaHU6+W83aGoJbIzgSnRBboSropiUlroRqbFh6MV6NT6AGIB25BrRjJOah4RkHpzPZ3P5wuiRYNlMg-p0N0jIZjfMLaZO-oSv4AXTZ-mq6BksFy3GqqDiwH8AE9CDTIIQCgozsTLkSLpB1jPsuslHPrAhIjE4tkvZAvD4-PBuIE19WoHgu77muaiMF4gT-jY3AYGBWhbrY9h+AETTyCeF4HGkkr-IuDQ0lu-BoPu8B2DQa7bnol43neoSQBg1QANaxE4r5-Due5+A88CQbk1TQXBNh2A4AHoEEvhYRq7TfmoeEYgCMh4Mg1RwRiRj5IEEE4PhxEgpA36-kpqHniqUCYQ2AAe-GwKY4F+KoGiIGApA6JeDbbpZ1mRH4JhmHgjnOeJORVLx9F4ZAERRPuyiIMwYkNkF3AhQA6uomiaWFkTRBYt4VAFGqsIQCEyacjZUqmmJGWe4aci5KnJh01VpbWBx9rFtUHugQJlVu4WZb0uX-NwrAKdUABKHWMKwTHlVZ1A2QcdksH52iUTlfzZe4633kYwTUICU3xIkrFqRpUB6X+85rgU8l+Ow3AEHx86gdUyDwHgPByAciCXQAXrI9gQfOkncNJym7IEImFFNW4fvuO2AgAMhDAN1cN-EKWZeD8U1JnFOseNrVREBbadsj5NQoMpFU24gm+1CsOoyAALTg+whQUzWf1+AAOpAI3cLdeDcDzqE8wAEoUVBvcRwtgDz6TVIwkQy7AS6wIzsCKYwuT-qpf2JcgpjmAcMhrhgEEExsSi3usQA)

## Solution

I think we need a new property for arc spacing. An `arcSpacing` (`spacing`?) of `2` should have a similar visual effect to `stroke: 2` with a color matching the background color. However instead of affecting the stroke it should inset the polygon enough to create that visual effect.

**Comment by domoritz** [comment]
If `"stroke": {"value": "rgba(0,0,0,0)"},` or `"stroke": {"value": "rgba(0,0,0,0)"},` worked, would that be enough?

**Comment by dantman** [comment]
@domoritz I suppose, but that seems like we're redefining how svg strokes work and could be breaking things.

**Comment by jheer** [comment]
Vega `arc` marks use the `arc` generator from the [d3-shape](https://github.com/d3/d3-shape) library. If you would like to see additional parameters for arc rendering, I recommend filing an issue and/or pull request there.

In the meantime, I believe the best option is to use a stroke (despite the aforementioned limitations). And for more reading about arc separation, see also https://github.com/d3/d3-shape#arc_padAngle

**Comment by roying** [comment]
Here is a simple solution that uses Vega's (v5.9.1) _"padAngle"_ and _"innerRadius"_.
Example is modified version of Vega pie chart:  https://vega.github.io/vega/examples/pie-chart/
The primary changes to Vega spec ("padWidth" is user-defined signal value in pixels):
```
 "padAngle": {"signal": "padWidth / outerRadius"},

 "innerRadius": {"signal": "max(padWidth, innerRadius)"},
```
![screenshot_vega_pie_chart_padwidth](https://user-images.githubusercontent.com/37225856/73612520-8244c500-45ba-11ea-9e3c-47c136cd6e66.png)

https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAFgAMuxREgpG1fFr0GlkdKzzdYjAF7ItkGbNeGo7dPADW1ABO3Kwyam4AnsgANjHcygrWjtQy6DGwWgDaShCgEAVQaaiuOJCweOhBeACCMtQxXlAU6aylYFaFRuyM4VrAkL2Edm5B6PVNkKi9WgZQGAAeWgBsdABMAJzyUBXIhLN0ugCMAL65YCfeeedGxe2QyOF1DZMtMW0r61s3Pr0ROAMhiMymMJgp5jMcHMpugljhVpttuU8HsDsczoVLud8l13OgSm5COg1AB1dSaJFvD5Qq4FSA9PoAwYyYZ4UbjaiTaZyGnzWFaI66DEFLGFHGFPEEsqhFFBABKxMYrEy2x+kCp9yOol0SS6v0ZYEBLOBUFBnPBPz1Eu5ArmlqtRkWWjW+lpDolu32OFO51FBXFdLubl6MmQ8sVyvB6ta7U6uIZ-0NzNZ7LBSJtvJhcLALuhnoFwogfuuesl93g3CCofDaiVKuaMdmbv1iaNKZBHK5kI66f53rzKK9HTookLF1pAdu+Pu0mqUY1WgAZulYMhm-S-v1kybIEhkAF2NwlmPhQBdRTWNToSrZbFqoNlSrsRq63EazI4HIOwGJo5IxeMLEibaMWXQ-s6-6ATEibLKBYqDImADMkFAbacH+ghFgodBWiIeheSYTgojYYmADs+FJuoKwkVoAAcY4QOeap4KCsCLpWqC3t+9pGHgkSEPchCAa+DqQABqFlOJOHNh6lTVM8L5MikaQxG4FRVLU9QvhRRiPGoCntAMynpG4ekGZAOk7JWbJKaYKlqdZFn2gxYCnr6ShMck8DpMgH5gF+-r3tObgVvEQQiXSfECW4la1vZ65qNwGDdgMV43o+6DPpMUmJph6GQGahnlHuUpQN5KLUJWkQuk5mIeRejpVP4fkBSWuJRfcVTwBFRiLiEnFMmlmAZVlFnro8FZqIZ9oPDIsr9DxUAAXEW4ID5IXcGFUY5cGESWZA2ZGXZJllKoGiIGApA5mNi2QJEq3HapZQmGYeCXddLlFjJUCsIQaXTbd6nyVpRU7WUQOaS8N3ulAZkg1uYOw088OXF0IC3US+nw7ZqQnVAmNkud70ymGCq1pGlm3SGpMRn5R2409fILAAFAT5KINs1M1nWACUN23ST3ORjj9nSnYNPk5kWK3RWVYS3WD0MxtctC1Lzk-CeHkgGcQA
