### ISSUE TITLE
titleAngle:0 can cause extra whitespace

### ISSUE THREAD

**Issue by syntagmatic** [vega/vega#2368]
Label trouble when moving the axisY label to the top. Here's an example with the [flight statistics bar graph](https://vega.github.io/editor/?#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwANgAMuxREgpG1fFoDM+w1ELo1axjOpbRNyOlZ5usRgC9kLWBIPABPQkCcSAAzZgUoACdkXwCtPATWZHkoeFk8dCdYLUg7BycXAF9FJRDmABtIsFAIIzxkAA88YoBVOgBlOjAAMTrTfDA+-LxGWGn4IpsjWA5pvAbigCZdAGsJ9FRCBuyAKXQZVnQE0LAAWjAAWUukMC3dAEYFJSWV+uQhvMmoXWUWY6FG8E+LSg0QS+0akGoCW4rEIkJaHhkSG4CWKs0uXUWUG40WisGQXRwb10SiqIBqvmoMjBRRwAG0vk0OUYmah4dNeawZHFspAKGDMlpWZA1OhQpAALqEozsJxqIKQJyELy45ANeAEomEaayFlgdlQqFS0LIS4K7JS1B5RB2s3S9BtF1SmVyxWuxDIhJFeVcsDyioc2lQ5oWyA8+G89DLJLxUXi+FqXWytFQyAqmRqnDBTXaqJkvUGyDcI08GSmqW5QUVjN1LNhiOE6M5uPFVbrJVQFEyj1RBNJ5BgAC8E7AAHJm7KZ2AAPyzgCCVFh1HHABFM9cABSoJwASkXOBnADlWKh2MgEmBicNRmY8LAZ5AI0pFXSjEPMGyOU7dFuyiaJn3wBYQ0gVgEjqYo-1IMCxlfG4tm2SRpDkfsYmxDAKSaEJwnhKRZBTOxA3hTxvEgSMY3SM5YGiXDJRDCAgItKAwgiHtGAFIUCVY9FYl1AsoCHQJ+xzQVmFNYIGSZOCon5ZBpK6WiOKWUwFJ7PMPw0sB1Itdi6KI4p0GoRFhA9ST0URZFCHYOU2Wg-jdDtQSjCrOtIAbGQK3QDdzMCb99KMYS6jUOtzjqOoRXnH0bKMRNJR85E-JTeKFUE8MOODKEctDaolngMFkhYqMoJAqB2gQUrs3RLj4XYM41Ww2FnHhVQNGdbDSkcZwtF0OhdDcKCkUFUT0kybC1G4DAnHVeSwR43k+mQABHTJMWQfc8DzOhVOyPanDoPEEjwI79tmKtjxo9tAMquFilCWq+ygxrilGGQbRxNqzi3YoTBferfzmgo5ELN18mKJCXwWaFGBExatOWkcbTHGjDKMAIkTSDIskqxh4EaKbkE-CBvxqdB2jKgCoyJBJEfSqJ2G4Ag5pTV74Rqkq3o4nCEjwgAVUylN4iToVw91kcZVHOPF7p+L6CJ4EYYSEl2-bVNgbJgH9GCSFnABSAAJGcKluioDI7BmmfwyAGmiCsueel2RTmbYAGE0vwgB2ao6Xe35V2cYEwAMIO1mQABNLQbjeDZsN7ZBV2fCGoEdgTA8jsPjM02XFPlqO9I0q2CspowMASbY6we-mPqiJJ9RB6EkVQdU-xh8DXxo7DkExbgMyCQToMIcTh9C6rFt57m3YRpGolUtysZjLrNEhl2oh5uqRWa-MtDeFecycgjN6gF6Z5TcLRLklHC8gUcYMCCoj-RUINmnuqogvneoDFOoJQ4F0K-MKjAYrqn-oAqAsxkC6nYAA5+iVOLcG4HUaYqIN532KMAZSqkcDKX+ILd0+4hzXgOq5I6CslYqzVojDWx0ZDkJkseY82RfJ4BwExIheASHujIew7IM55AzmPGAAA1LOMAsMIJCLAPFThUseGkNQHQeKgi6BvGiCI8RkijwyDAPuAK1BTwVDuvpV+xhuAbgnqFGIYDC7BEgfCWISR2CM3gNsMxpcQwFQgOXEA4YgA).

Everything looks good except for extra whitespace to the left of the chart, which appears to be based on the width of the Y-axis title text as if the `textAlign` property were set to `right`. Possibly a bug when using `titleAngle`?

![image](https://user-images.githubusercontent.com/156229/73928894-bc4aeb00-4888-11ea-8d19-a560a7842b80.png)

I got  close to the layout I wanted [with this version](https://vega.github.io/editor/?#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwANgAMuxREgpG1fFoDM+w1ELo1axjOpbRNyOlZ5usRgC9kLWBIPABPQkCcSAAzZgUoACdkXwCtPATWZHkoeFk8dCdYLUg7BycXAF9FJRDmABtIsFAIIzxkAA88YoBVOgBlOjAAMTrTfDA+-LxGWGn4IpsjWA5pvAbigCZdAGsJ9FRCBuyAKXQZVnQE0LAAWjAAWUukMC3dAEYFJSWV+uQhvMmoXWUWY6FG8E+LSg0QS+0akGoCW4rEIkJaHhkSG4CWKs0uXUWUG40WisGQXRwb10SiqIBqvmoMjBRRwAG0vk0OUYmah4dNeawZHFspAKGDMlpWZA1OhQpAALqEozsJxqIKQJyELy45ANeAEomEaayFlgdlQqFS0LIS4K7JS1B5RB2s3S9BtF1SmVyxWuxDIhJFeVcsDyioc2lQ5oWyA8+G89DLJLxUXi+FqXWytFQyAqmRqnDBTXaqJkvUGyDcI08GSmqW5QUVjN1LNhiOE6M5uPFVbrJVQFEyj1RBNJ5BgAC8E7AAHJm7KZ2AAPyzgCCVFh1HHABFM9cABSoJwASkXOBnADlWKh2MgEmBicNRmY8LAZ5AI0pFXSjEPMGyOU7dFuyiaJn3wBYQ0gVgEjqYo-1IMCxlfG4tm2SRpDkfsYmxDAKSaEJwnhKRZBTOxA3hTxvEgSMY3SM5YGiXDJRDCAgItKAwgiHtGAFIUCVY9FYl1AsoCHQJ+xzQVmFNYIGSZOCon5ZBpK6WiOKWUwFJ7PMPw0sB1Itdi6KI4p0GoRFhA9ST0URZFCHYOU2Wg-jdDtQSjCrOtIAbGQK3QDdzMCb99KMYS6jUOtzjqOoRXnH0bKMRNJR85E-JTeKFUE8MOODKEctDaolngMFkhYqMoJAqB2gQUrs3RLj4XYM41Ww2FnHhVQNGdbDSkcZwtF0OhdDcKCkUFUT0kybC1G4DAnHVeSwR43k+mQABHTJMWQfc8DzOhVOyPanDoPEEjwI79tmKtjxo9tAMquFilCWq+ygxrilGGQbRxNqzi3YoTBferfzmgo5ELN18mKJCXwWaFGBExatOWkcbTHGjDKMAIkTSDIskqxh4EaKbkE-CBvxqdB2jKgCoyJBJEfSqJ2G4Ag5pTV74Rqkq3o4nCEjwgAVUylN4iToVw91kcZVHOPF7p+L6CJ4EYYSEl2-bVNgbJgH9GCSFnABSAAJGcKluioDI7BmmfwyAGmiCsueel2RTmbYAGE0vwgB2ao6Xe35V2cYEwAMIO1mQABNLQbjeDZsN7ZAAA1BqT4PnwhqBHYEwPI7D4zNNlxT5ajvSNKtgrKaMDAEm2OsHv5j6oiSfUQehJFUHVP8YfA18aOw5BMW4DMgkE6DCHE8fQuqxbee5t2EaRqJVLcrGYy6zRIZdqIebqkVmvzLQ3g3nMnII3eoBeheU3C0S5JR0vIFHGDAgqM-0VCDZ57qqIb4PlAMUdQJQ4F0J-MKjAYrqmAaAqAsxkC6nYCA9+iVOLcG4HUaYqId5P2KMAZSqkcDKX+ILd0+4hzXgOq5I6CslYqzVojDWx0ZDUJkseY82RfJ4BwExMheAKHuiodw7IM55AzmPGAAA1LOMAsMIJiLAPFXhUsBGUNQHQeKoi6BvGiBI6RsijwyDAPuAK1BTwVDuvpT+xhuAbhnqFGIUDS7BFgfCWISR2CM3gNsKxlcQwFQgNXEA4YgA), by setting `titleX: 0`. This removed the extra whitespace, but left-aligns the title to the axis line rather than the left edge of the chart.

![image](https://user-images.githubusercontent.com/156229/73929587-ecdf5480-4889-11ea-9719-137a3c9db9b3.png)

I couldn't find a combination of `textAlign`, `textAnchor` and `titleX` values that yielded the layout I was looking for when using `titleAngle: 0` without creating the empty whitespace in the first image.

**Comment by jheer** [comment]
Hi! At present, setting both `titleX` and `titleY` is the right solution, as this communicates to Vega that it should disable automatic axis title layout and bounds calculation. For now, you will have to include an explicit shift of negative pixels to move the title further left.

The whitespace that arises via other methods is a result of the aforementioned automatic layout. I'm adding this to the queue of things to re-visit in v5.10.
