### ISSUE TITLE
Automatic text wrapping

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2370]
Vega now supports multiline text but this still requires user input. It would be great if there was a way to automatically wrap long lines.

**Comment by adrijshikhar** [comment]
@domoritz I would like to work on this issue.

**Comment by domoritz** [comment]
Thanks for offering to help. I'm afraid though that this is not a good issue to start with as there are many subtleties. Maybe pick another issue to start with.

**Comment by adrijshikhar** [comment]
i thought this would be some frontend fixes. Ok, i will pick up another issue. Thanks

**Comment by jheer** [comment]
If we change the text wrapping to make it automatic, that would constitute a breaking change. Perhaps for now it would be enough to provide a convenient config option to set a global lineBreak pattern?

**Comment by jheer** [comment]
I've added top-level config support for a global `lineBreak` property. This allows text wrapping based on specific delimiter characters (such as newline). This property can be overridden by local specification via mark- or style-level configs and the `lineBreak` encoding channel.

Note that this requires explicit line break characters and does _not_ support automatic text wrapping based on line-length alone. I will open a separate issue to track that request.

**Comment by jheer** [comment]
Added #2434 to track automatic wrapping without an explicit line break delimiter.
