### ISSUE TITLE
Groups often create empty path elements for foreground/background in SVG

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2379]
```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "title": "Hello Vega"
}
```

<img width="405" alt="Screen Shot 2020-02-15 at 19 45 54" src="https://user-images.githubusercontent.com/589034/74598748-eee4a880-502b-11ea-8c74-2f70479cea7d.png">

They don't seem to do anything so we can probably remove them.

**Comment by domoritz** [comment]
Similar elements show up in various places and they are visible to screen readers making it really hard for people with assistive technologies to read a chart.

**Comment by jheer** [comment]
This is true for all group marks. Those paths represent the background and foreground elements of the group. They are supposed to be there and this is not a bug (so removing that label). In the case of dynamic signals, these elements might change content in response to interaction.

It may be possible we could update the SVG renderers to omit these groups if that is highly desirable, but this will require care. I'm adding the discussion label for now.

**Comment by domoritz** [comment]
I wonder what the performance impact of removing hidden groups would be. I could see it having a positive impact on performance when the foreground/background is never visible but a negative impact when they get frequently removed/added because of updates.

Screen readers seem to behave inconsistently across browsers/ runs/ charts so I'm not sure yet how much of an issue the extra elements are but I'll keep investigating.
