### ISSUE TITLE
Issue: Setting "clamp" option for scale may show wrong slope for linear regression line

### ISSUE THREAD

**Issue by roying** [vega/vega#2390]
"Clamp" option for Vega scales:
> "A boolean indicating if output values should be clamped to the range (default false). If clamping is disabled and the scale is passed a value outside the domain, the scale may return a value outside the range through extrapolation. If clamping is enabled, the output value of the scale is always within the scale’s range."
https://vega.github.io/vega/docs/scales/

Vega (v5.9.1) transform "regression" includes method "linear" that will
> "Fit a linear regression model that predicts the field dv as a function of iv. Generates a new data stream with points for a regression ..."
https://vega.github.io/vega/docs/transforms/regression/

For "linear" regression, the "new data stream" comprises two points for a straight line.

ISSUE: If "clamp" option for scale is set to "true" and either point for regression line falls outside the plot domain, the regression line will be drawn with incorrect slope.

Working example of issue in [Vega editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAJgAMuxREgpG1fFr0GlkQujVrGM6ltGLrsUzPQAbWFoDaShCgEKFQXqjIWpAe1F7eAPrw3uiohApgQaGQFD6sUTh4AE75hmFQ7I5qWsCQjoSseNFIyPAA1uzcAB6QAL5Z-RAAum5Gauh4mDiBYSHlkBEFUOOTCZPs3lFlYTl5yH7TWbO7iT04rlC5iQCeWgCMvdvltVcJZ2AAbPKXPgm3ONpHkdQi9fu8AOzfE5-LQAZiB5RB0PeAA4oa9-mAACyPTKI4LIrQATnRv0xokG5SGAyewHCqSWkBW6ASRRobNgHlkCmBMW4rCK8EZzLW6A2W15xXQMlgADNuEVUAFgbMoHhroRGWzqByuXInvioJEWNxqjhIN5HMh0EUeYadsgunhkDImjharF4tF-AYdLohn0DfjIO9CUHEZBMdDbuH5ugDmB-JBtUUEqwMsn2QkKJBqfawJTEXnQr08WARu54D59srZrzFtEENW3nb5urNdFLTJrbag8npdRGaoNIhWzs1NwMI4Ar69MWIAiQfWGY2q5sYX324yuz2x9kigPGSYzE0+xOp3J3csJlNr6t1psMir81BZYxkN4zT8boH64whVoxSlLyABeyBFNwgElMgfbJKk6TujEng+I2yGJHBaR9AMSgVtY6BdDWhzHAq76utEnQEJOGZNo+5o0cgLaLgSJEum6UCbLKp5QPRq7NrclK4UYGBFG0CYzPicyGpAW6NtcqCdN4e4RrKEFKohzLRCKD5RExwYuvAppLJJ9qQKwhArEZz4Ru8Hproy9EtlCb4fl+hK6fmkY1DEdm8euMavu+n7RBiv4vtksDFNwbRGSc+SNs6H4bHF7kmRFEHRQA6uomiIVccUAilUlvt43gAPK2PAzCYqC3j5WADxWSWjWFuUhXGRGMnmjuSnzCpVHqTemk3qK4qhSZ+mGTUjVGGZFlTWFRg2d51a+QxPROYFrmvD0hXBtVy20dxdkbgFLnBWSY1hTEkXRV5eX2Ql3hJTpsYRmlUXIFlI53XsFi7cpjAleV6CVeqP21UsDVhS1iIwyWsbPu1bYatuVo9TsfVqWAtQaeaIopvseqXXpMgGWollXbNEwUwtIZeTxdHHetp1BeaKZpsTHn7QzR18Rmzms1A7M5v98zvbduW-WzyDVKLOzi592WjpLEN-a9vWA2VFVVeDdVQy+cNhIbBbAiqOEgP0QA)

![screenshot_vega5_linear_regression_clamp_issue](https://user-images.githubusercontent.com/37225856/74970488-70518780-53ec-11ea-8a9a-1a9d197d94f2.png)

**Comment by jheer** [comment]
It seems that `clamp` is behaving as-intended but that using `clamp` in this situation is ill-advised. I'm not sure if Vega should be changed in any way... FWIW, Vega provides enough expressive power that there are plenty of ways to "mess up" a chart, though this one is arguably more subtle than most.

I'm going to close out the issue for now, but please feel free to respond with proposals for how Vega might be changed in response to the issue. I'll then re-open as warranted. Thanks!

**Comment by jheer** [comment]
Also note that one can apply `clip: true` to the regression mark (rather than using clamp) if one wants to limit the domain.
