### ISSUE TITLE
Support signals for background color

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2394]
It would be nice if Vega supported signals for the background color.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 400,
  "height": 200,
  "background": {
    "signal": "'red'"
  }
}
```

**Comment by domoritz** [comment]
I guess for now we can do 

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 400,
  "height": 200,
  "encode": {"update": {"fill": {"signal": "'red'"}}}
}
```

**Comment by domoritz** [comment]
Never mind, that's not the same

![image](https://user-images.githubusercontent.com/589034/75104445-d8a39300-55bd-11ea-81c7-408100b57e72.png)

**Comment by jheer** [comment]
Seems reasonable, happy to investigate later on for inclusion in v5.10.

**Comment by jheer** [comment]
Added in PR v5.10.0
