### ISSUE TITLE
Data URI for image mark

### ISSUE THREAD

**Issue by marcprux** [vega/vega#2407]
I believe that it used to be possible to embed a data: URI for an image in the `url` encoding's value, but it no longer renders anything:

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "background": "white",
  "padding": 5,
  "width": 290,
  "height": 200,
  "style": "cell",
  "data": [{"name": "source_0", "values": [1]}],
  "marks": [
    {
      "name": "marks",
      "type": "image",
      "style": ["image"],
      "from": {"data": "source_0"},
      "encode": {
        "update": {
          "x": {"field": {"group": "width"}},
          "x2": {"value": 0},
          "y": {"value": 0},
          "y2": {"field": {"group": "height"}},
          "url": {
            "value": "data:image/png;base64,iVBORw0KGgoAAA%20ANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4%20//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU%205ErkJggg=="
          }
        }
      }
    }
  ]
}
```

This is important for us because we need to be able to generate specs that have no external dependencies, and without being able to embed an image URI we can't use image marks.

**Comment by jheer** [comment]
Thanks! The issue arises due to our URL sanitization, which is currently not accepting URIs with the `"data:"` prefix (as opposed to `"http"`, etc.). I will make the change for the next release.
