### ISSUE TITLE
Allow setting background, width, height, etc with signal

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2417]
It would be nice to be able to write

```js
{
  padding: {signal: '10'},
}
```

instead of having to define a signal named `padding`. 

See https://github.com/vega/vega/pull/2412#issuecomment-592618807

**Comment by domoritz** [comment]
This is not a high priority but I was wondering about it when writing a Vega spec.

**Comment by jheer** [comment]
Added in PR v5.10.0
