### ISSUE TITLE
Text with spaces at the beginning or end gets positioned differently in SVG and Canvas

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2418]
```
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "padding": 5,
  "background": "lightblue",
  "marks": [
    {
      "type": "text",
      "encode": {
        "enter": {
          "x": {"value": 0},
          "y": {"value": 0},
          "align": {"value": "left"},
          "text": {"value": "       Hello Vega"}
        }
      }
    }
  ]
}
```

Canvas

![image](https://user-images.githubusercontent.com/589034/75616866-8f969600-5b0b-11ea-8a15-ead84c609d51.png)

SVG

<img src="https://user-images.githubusercontent.com/589034/75616868-96250d80-5b0b-11ea-8bfc-08fc8327e5b1.png">

**Comment by jheer** [comment]
Ugh. That’s annoying. Personally I find the Canvas behavior more “correct”. But we probably do want to error on the side of consistency, and make sure we document this clearly on the text mark page.

**Comment by domoritz** [comment]
I think the SVG behavior is consistent with HTML where spaces are often collapsed. I'm addressing the inconsistency in https://github.com/vega/vega/pull/2419.
