### ISSUE TITLE
Damage/redraw boundary issue for Canvas renderer

### ISSUE THREAD

**Issue by mathiastiberghien** [vega/vega#2425]
I noticed a bug, several months ago that I forgot to report because it only appear with the canvas renderer ans I mostly work with the svg renderer.

It seems that there is a problem with the refresh area: when you update a mark some lines are remaining.
Here's a screenshot with the issue that can be observed [here](https://vega.github.io/vega/examples/watch/)

If I'm not sure when this was introduce, but I discovered Vega in July and create some visualizations without issues. I then reused the visualizations in september and notice the issue, so it was maybe introduced with the 5.5 version

![Screenshot_20200301-201945](https://user-images.githubusercontent.com/22467324/75666111-8fb2a500-5c75-11ea-9992-2d28061275dc.jpg)

**Comment by jheer** [comment]
Thanks for posting. That looks like an alignment issue between the "dirty" region bounds and the redrawn canvas area. I've dealt with a related issue in the past in the browser (which I fixed) when there are fractional pixel translation offsets in the canvas transformation matrix. I am able to replicate the issue in Chrome on MacOS if I go to the watch example and increase the screen resolution (via Command-+).
