### ISSUE TITLE
Vega & Filtering a Stacked Bar Graph

### ISSUE THREAD

**Issue by kdiale-nerdery** [vega/vega#243]
I'm playing with vega to visualize some data (and using pokemon data to do with) and I'm having some issues getting my filter to work correctly.

I put it up as a jsfiddle [here](http://jsfiddle.net/77ttuxuh/).

The issue is that whenever you attempt to filter down to a particular generation (via clicking a rectangle) it will only ever filter to the gen I data.

It looks as though the problem is happening at the encoding level as when I inspect the data as it's building everything out, everything looks as I expect. I suspect it has something to do with the way it's laying everything out. If you hardcode the generation filter such that two later generations are passed in (IE, `(data.datum.col == 5) || (data.datum.col == 6))` it will then fail by showing only gen I & gen II data.

I suspect that it may be an issue with encoding in the context of a stacked bar graph.

I've been chewing on this for a couple of days and I'm reasonably sure that it's a bug somewhere in the encoding layer although I don't understand that code well enough to be 100% about it.

**Comment by arvind** [comment]
Hi, if you're still experiencing issues, I would recommend asking for help on the [Vega Google Group](https://groups.google.com/forum/#!forum/vega-js).
