### ISSUE TITLE
Text are selected randomly when double-clicking on a view

### ISSUE THREAD

**Issue by mathiastiberghien** [vega/vega#2431]
Here's a sample to reproduce the problem: [Gantt lite](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAFgAMuxREgpG1fFr0GlkdKzzdYjAF7ItkAGbMF1x9RnoAG1gtAG0lCFAIKKh-VFccSDxmANdDaKgKQNZ4qG90qDVkBAAnRkIk2TdgAHJqYu5WQmqsaoAVZORqgF9IcLAutIi+o1icxI6AMVk8AGVnVOGMrJyAZit8yEKSsoq5BJq6hqaW9rwU7t7ogb7I9MhRt3QAD0ZYU5SpmVn5vLvMgOyWgAjAA2QZRTZFeClco8PZQA71RrNNodC59a7RW7Re7oOJuZBUL5vDq-HH-QEJACiRLwwXBRi20J2cKqtSRx1RZ06PQx4OxEIeCUJyGJn2+LjJEIpOSBACYGQUoTDdmzDsiTmjeVd+YtcfiEtxCOh4MwAJ5Sowy4GKyDsRgyNRaAU4h2EOxuYroGTUBb5IyoB1aXR0IGKgPPG2LIywPDIQjB0OLTF3Jkq1n7dlHFE00V4dE6m56oVQBCBP1-ZaJ0S2+2O53RqBuj0JL0+isbQPwkO6GuNyAYJ6JgCcff9pbjCZwPdEydtaZZlUz6s5ua+BaiKaGGxLkC9akYrHpeutCSBuktUDrTpwLohzbwnu9vsvAaD0-DUEHWjlY-9kFjeNgTnPUF1hJcESzDVqjXfNtU3XUdzxMZY3qABrZAAHV1E0W1TzAMM9WvBtx0gB8n3bV8v3fMB1n-b8cHPT8AMnYD8i3CEwNVZcORzWkNwgDi731MZPACAIAGFuACbhimPDZ8JCKAAGIAHYQQAEVEKkqUgMAAF152VRd4UgRFsxaWCBP6RC7l3EUvgmRhxKkmS5MvSBFJU1TVIAQVUiYACEFBUqlRFUlYQQADhCyBlKCiTAu0FZYuUlZtECkE-NSiYgV8zKYoMoztnA0zzOgqz4ME2ycV3VDuAw1zZPkysARyJS4tELq9MM0DjNKtVeMs-iqpsoskINKAHNmPB0OQJr3LwqscA65SutEHriuZAaeIsmCRsuBDxrs5C3CeXyXhJbkPPwyAPK4jNIJXFEAA0wAu15qnkMBqgPWBCACdAzQAOWQlF3h5Q7quO2rToSc7LvFOZJSWtrgQVPqSu4p6huqN6PtgL6fr+gGgdBuIUXFMBkchvkYcFOGoAR152jiGZ4HLG7lqgDSgYAChkn0AEpSFZjsIWIrBgDImR3UfLAAOQFJ4Efb7ICNXZgiwEJIF5uNRcYfE1b11IoAAWWmRABdkagRYATWQdBilii2vkQUhebNA2jfNy2PaBhRdaB0hXZYa3hcDz3w9t73UiDr2xdixP9I4xl+uxsyoM5fHLqJ37XlJkGwZaKZigwOCobGrFizhyAj2QNQxdL8uPMaNR0DjbBIGZkk2Y5lIwAAXmHn6Tdj6owAAfh+gBSO2AFoZ9QRe1DAGeAAksBns2J5wHuxfZ8sh5H6oTYn6fqjnxfl5ntRd-3w3kEPgfh8Hn7Q6twWY4dp3z9n9g15213mAB+fcj6v3fn7T248p6zxvqvDeW8d5gCwKAp+-dkDHzftUD+-szR-0vvA4BaDn6YIgafYOH9o5CwIbfNe7BiEEwPhgrBo9+ZfxFmLWh6A16b23owy6zDwEn2gVw2Bl8EF8OQXvJhj9SGsNRBTcRiD+EoMvjwlRO9K5CRrpNbuBNfI+hSFzNGH4iIOhvGAO8RhyKtmfOLHEXYtDz2HHRTskYcCuOYoBKcYBZzsS2umCCmdnotBzp9b6+d-qAyLhTFohjqDnFGjoiaYwe6+QCKYOQqNKRQHgHmZAztawWJIv+WxpYlbIBVlRdWpUtZgA6ikdwqs8kFKKVAUoZhHwGRAhsB6wTyrZ3ernSJJMYnk06PEzJfhrIpJOnonuAB5KgxRAYJhyWMY0pQ8AWmKfWW8-ZymK2VqrfsGs4T1I6jIWQptIBbPNLFOoyAG4Wh6QEzG20M6DNesMiJxMC7jOLtUZZhS1lgGKKwJJ2iaoMz0WaWR10NluHuunR6ITcZ21+YTUZAKyZAohrMmFIxGaQHhYjaYNMTG5PlIEkyg09qYoJnnMZeK4nVCpjTQl9NiVwoMUYhxSxTG0T2ZY6xTZZYtg6fYmpTicAuLcXcBiYAvH9h8Vofx6RU5Kixmi75LRGUjP+dE1lkzqgJKhXTauqS3BkteBkrJVKxidPMCK0pGwjmwEqdU5i5zZCXKgE0lpkB8lfEKbFZ13T9K9NTKigZWcUQGr+VEwuEyUT2pmckolMQSWIHQFdYxtoHReASK8AAaoEdQfMkjciFmAAAZHWsA1aUgAEJh7VGqNC7l2a9G5tgHbCGHki3yybLActmS1B81tfm5AtaG1gGnRDNtg8O1dqtfMsYfaXqDsLTIYto7x2VofjW+tjbj2tvbZ2y1URhK7kBuwJWsEPIQTCOOMVRhpr1MgAAARSL6R0AAZdAD6AhYHgJk+AaF5C-poKKNQMwzSoHYNJMDEG0JUSMO4WS+StCzWyJ+IwbcO5jBqDKZo7c8CsFQHQGUo0riLCjfRiAvUjDNpyAKRIyAngjuAKWLJgQ3Bsb0hxDwFKfi3j434ATCQ+0Q1gWxpG8wUG0WE0oFMmwO6YBWt2kSgngMFpPMsS5jZ31QDwOgagbJXiLNKoEZo7hAietGZp1oZpCCmpmLNB01BmXcCKAAJWQAAR1YIwYoyBfLUCebQOM9nHPIB6ARqatItCQWs7ZgIzQ8PIGc+Z1z7mUSedKD6XzAXguhfC5F6LxG4tBASxhicTsR1pdgDZ3YdmsAObq7l9A+XTVn1GX52AgWQthYi1F8LMXJldc9YlxsH79lGBqOl9rmXOvxZ631lEA3iZDZGxV8b1XYvrbq3Ro6b75tmYs24VoFmCINcgNNLQMhIUBCSyxJrbg5S6G+-PXQQJ55rFaLoVSWB9Bg4vO9uDX2fu6D+wDoHugooQ4h5XQsF3xyseuwkW71AwByge7GT7CRvu-f+4D3QrRzwo-0A96HOAXviUbFq7cmPEjY6gLj+7UOUvUlpPjwn5nigjsgKTuHugVgU6pysGnkPLuPcW6L2Hf3JdA6BNoLAaxUfM8-KZ9nlmcd3aBHT3nUBYLc-l0T4XMOycI8p9T8HtOoeK7F-DqXQIgSa90Nr8cLOrHy-Mwbznd2UrvatyOxnb35f06gK78nauNda9p8zhjtpZrelgFhsuoQTMB7c6JWSqBIWYCh08QgzsEj2BNnzCjVG6Dh6Fg9vNbhw9o-O-6PXOz3NuCz0XwGdOy8V7M9wavtfqNwcb+95vwp6w69z5jsz+ee+F+LwP8vbgy0VsnWP+vQu8C1untl5TM2BU4mn6OzzTWNLIE8DIBubfoYY7Z13gvZdV+l-XyWsdW+a8dzrxP+TCFTBHAE-JvL9V4KkR0a-W-e-OfJ-UiF-HvZyOMIpaPQfNwHfV4S-YXaAh0BuMAAAHwILAEwNgEgLUFwLvydDgI7zz27wSFUEdG4GUAe08CVjUH9Q+2tzVmhyKnlyNE4KcTVm-D4IXw8C9EmlfQXzAEjySwgEj0u0Y39D907yXwSF73fzQM-wKD-2oywL30oPwOnh33D2Ux3y7AAH1W8p8v1W8aD8hVD6CoAND+8P8h8NNKM9CyCoCb88DV5jDdC6A4MzDAjBwLDocbCCRZ9fcGNr1WdYY9FP0PJpBWBigcNK99MBVEg2xM9C8c94D-xECEhy9uAJAqlTkxC2CAgODQhks8wep7D0hHDRJkCw03CN9v8J1f9PCgjaRG8U98glDH8b1dExhWAZAZgvU4w1BYIWocQX159n9OlfR3D71H0Ut3t7AotjEEg1iAgn0Bj0ghj+glAWNSwMFjN10Ei0kPIiioBCBuAHQKjUxuAMAaIxUPCtMrt2ADNSIqiaiVpGtuCpp6xRD-xpBrccBsto0cQ2wXwGCcJEAPJjQ1ADwfREwgQ4j-drUEhdk9Q7i7RvQnR5xXj0B3j+wKMvj2cfjT9nDGB2C9NLMYSIQ4TN1kBTAXU9QUS0Sg9eMAJ+MAg3AgQwB54wAyxjETj0cRicS6TxJbi1CoBZI0SBMSS3j4QPjKS9MaSal-jGS28tU9xpUJN+SpNBT1DnJJJpJmpVMpT4jYUxhponI5S08FT1ZihlTBTVSyT1SKTNMCRaQ5i7hdThQNjVVZIR1oT3kNhWTnRJN-AzS6jHILSFpghJT287SeUUJZoGosiCSlSHQVTQJSTyTSJNSMjtTmJgyrsmSoy7gYzjTfB4yW9szGorT3I0zhiMye0HTaQiscz5SnC3SPT7piyfTSy-SQy8xAycQqzHtQzSIISIygDmSjB6yrE4zpNEyZo5oUybTNxTi0hIA-04NLjpS7ghMGyBT-SpzB0q4gyLTrykznS9RRR4BuBCg3U7g9j6k9c71YNANgMlYHsnjCkTQkgqBcMgD3siNO4DlpDnCxNJRLzTTHy6RFNJQ7yxCjQTQHlkKmyS1HRNM+ZqhxjJiTkG5Zi84yNvod8ZQD9aI6BRBlNjcOzlDGicRYBENkMghPyZSjz-z4MuLpJgLQ0vQVZGAIKoSoLo9RLeLwTc0nC+TbpYAQsnZXBWLazSIYL2NLsjBsLTQdlYyTT8LxVKTiLSKpiKKAyqLlgiZaLlh6KQwmLGJhM5C+MkL1zjLNy7lmC+ZP10LMEAAqEMKKeQOURvDSzVQ4pjfc5jQ854IofIs8jijBM6Z9UoeohIZDAgV4jyXvDuZ0Lys0uuT1RuR+ZuAqg0-KvAPrQTR+DyV898nS0ib8uSnEbStqoMxC9jDchM-RclL4SlTCtnZ8HYzyxs7y9JflVy3SqACtPwIyiavq9JaZOQSKmK9iFcszUkPCyahFCUg0hTbqxaq8mTPNbdDoWBZ4FmSYbq5TC8YaowPYkFVZdAXxPkpas6AmF6sFZdaoa5O-P+JZFZMFEA+LPczs7Eu4cUsYPEjYWSekr4NwQNBqmQN8j8uC-8VqzGrSwgCjZq6Qmwaa3avq6dc1dSv3M-Vak6lC3Egxamx6-8LDQa8Tca06qAadAKiGtimIzSiEC8tm2mjm-aimtPW6lmjyj69m4wPNAdS66ea6mdAK6cbmroA86wDAYoNCU8rsxIV08Lb1UYtwWgL4Z4mc+oVAIyss74g620RqjGqGjYNpTqowIcHGtnWc6w2agCVK+GB-dM-8J4And2v4+k6oqI4k72mGtKy7NW33ZiDqkO+8uU7TeC0zHEOMWMDow9bfQI6aSfWazDMOyxOc+otymMX2rcp0wU2aym5Kwm2cwPBrFKzmc0uU2uxQsPFs9qWa9O-mooEXTfLonffO5uiEWcp7cu841urcvsjCf220zHPuouhkjIyzKen2meliOaBe2KzHM4hc7u7CDQJEkm5suaY+zQRmnEN84oO-YofzdAA8I8VoI0ADG-HjXqjAwI-Qq-Xwqg2BfcQ8WAe6masQ2+++x+5+2AQKbgHK1Ad+5pGmkyjwuvX+nA-+ow8FJ+4B0B6+iECBwpKB4B1+wgfzDkz+oq7+noiAnwmA-w7B6BvBuu4NWSSBnBo8WB+B8hrpZB7y0g8gwwhhoBo8Zh97C0JOjYRu67Nyzesa0lXelhkwXhyR6GyuhR2R9gIkyC7IWO97MSAIGzHCwys+w0Y0Ay15Fh-S3ChpXuwuszAe7On-Eevo09MACxIikiiYyymY6yyJaikgvOvoseq0bmXQWutypS7mYUuO-ezY7gaSJIXxKQhfZehxrOhIFtIeytFxvMWtIgsALJwi8zcy7x8i3xqcmytqOyoJvJkJr+zMaaZodxzonJ2pr4ei3Jr4ZTLxwoehvOcPZp0g7AvAIR+TcqwvDubouvcPeQS+BeJeFeXhJBLeGYaoWtHAXpzBu+SJODcjH+7wig7Z8ZuICqvAaZ8fR0OZq+RZuhTRVZ9Znp8Yvpvw6yXm-e6KvewSU4kALoIAA)

If the user double-click on a rectangle (event), the first element of events list will appear as selected (see screnshot below):
![Selection_on_double_click_issue](https://user-images.githubusercontent.com/22467324/75769005-b6401100-5d45-11ea-9ec2-00a7effb1cde.png)

This is misleading for the user because it's look like the double-clicked event is highlighted but in fact it is always the first one.

Is it possible to configure the spec to avoid this behavior (which I guess is not really a Vega behaviour, must mostly a browser behaviour)?

**Comment by jheer** [comment]
Yes, this is the default browser behavior with SVG (but not Canvas). We left this as-is by default in case users want to be able to copy text that appears in the visualization. You can change this using the [`config.events.defaults` property](https://vega.github.io/vega/docs/config/#events). The documentation includes [usage examples](https://vega.github.io/vega/docs/config/#usage-1).

**Comment by mathiastiberghien** [comment]
Thanks!
Unfortunately, I'm not able to make it work...
I first try this:
`{"events":{
   "defaults":{
"prevent":true
}
}}`

Then as It has the same behavior I try to add this
`{"window":false}`
then
`{"view":false}`

With `view` set to false I can disable the click on the legends label (when not disabled a click on an event from the legend labels will hide it) but I still have the text selection on double-click.

Did I miss something?

[Gantt lite with events disabled](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAFgAMuxREgpG1fFr0GlkdKzzdYjAF7ItkAGbMF1+LM-VsUAgjZCoZPFhApWCoNWR3WwAbCKiYo0IAJ1DkcOw8DNZkaOCAX0M0yFUZNW5lbATE2GRymMgKRmQ6rAam4pK+8shHahl0Rq0AbWKgitHUVxxIPGZE1xbgtrHCt2802OQEDMZCZdk3YAByagzuVkILrAuAFRXkC5LIAeniozmFqGWeFWADFZHgAMrONY-KAULb-ADMVj2kDih2Opzki0u11u90eLyBbw+XxiM1afzc6AAHoxYISQWDIS5dhU4YltjgAIwANnWRjR8COJx4WKgOJudwez1e70+MTK3xRlMW2XC9NerNa7M5UAAomEUvz9uiRWdsVdJfiZUS5aTguSNiqoGqIqDwszoSidf8uQAmY2og5CjGi86WvHShnE+WldaO37oeZubiEdDwZgATy1Gx9Wi5gfYjGqWgTG2LhDsbgy6Bk1C9eygqGLWl0dALMKMGGp+eNRlgeGQhFb7ZhipRguFmPDuKljwNOTwdoV8ZhkGdQ3gYwb2vhI9EheLalLnagFarixrdZ3FWbYrbugPp8g3ZHAE4n42oAOhyPH2PA0nUNzXFCM5wuBdwmXOMlVmJN-kgGs1EYVhIkDPNFi5XQcyMIsSxwMsjHPPBq1rescI2O9Wz7JsaS0P1P0bIZB2HbkALXICzTFSAJUjedDWgiBxwdNcNwHG4AGtkAAdXUTR0L3blD3wsBCLPGRKxIy8yJvVoqJwZEmNfblDJRH9WLALl2InYMpzDC1Z2tSClxJFdYIpeC3E8RJEgAYW4RJuAyNC1wwsAJigABiAB2HkABFRD1PVIDAABdQDbOA7jePA5zBLAYSIDLddPNVQ1gUYHz-MC4KKM2Dl-giyAYuigBBaLgQAIQUKK9VEaKER5AAOHrmq63zOu0BFRsihFtE6nk2pm4EuVahaRrSjLTWnByrWlPLXJgslRNK798m4KTqqCkLvUU8KotER6UvSjjMq4mc9v4xd8sK1STuTMrF3Bc7LoC666rCprIse0Rnq2kN3t2viIIEw6hNXZVTsgalWtpDUiQhu7IDqzidtAxzpQADTAXG6QueQwAuZDYEIRJ0EzAA5eCo1lNGCoxuCAagHG8fdCEoUJhr8wDV7tvs8nPouanadgenGeZ1n2a5+ZpTFsBPR+gWPKF7GVZeeZwS3VZJd1SA4vZgAKQK6wASlIc3dKgPDjywYBIGI7AhmQVZ4BIhnIFTTFIiwCY7fQQd3cYZNw-twdRoAWTBRAndkag3YATWQdAMgzrPSHtzNE+TqBM-CRBy-ZhQ48r2uWBz12m4r9u86rtZm970aPcgVLfoFN6yZ4sDrWVvG1aZulNc57nHlBDIMBc2N0fcp1SsgVDkDUD3V-Xuq7jUeOFlNvGPct7cwAAXkfxnU+QXuLjAAB+RmAFJ84AWm-qgABagwDfwABJYG-und+OARZ0hvlbZAD8n4XBfu-L+Fxf4AKAd-NQMC4Eagtog5B99Gat2zs7Huhdi7oJ-uwUB+cYFgAIQgu+j9SEXHIQ3SuHtaGYJwSA8BkDoFgCwCwpOyBb6rBIWQsuFc+GAOAUw8RRC2EoIrqQch3cXYKMEewZRZsJFSKQew5+jtKFu14Z-H+6BQEQKgQY6+RjiGmNQezN+1jMGCPsSI2BhjVHSNcVYjBQiHGiMwbY0J0DN7823omE2BDWp1mtgpKWBllI+z+l+f2GkLxQCvORGiL4Ww4D-m+Uyt46I4HKUU8yWhRDWQqKTeWk8KaPBnnTBm88WZsyXjrR4STqCrENnEqAG5EmJFMHIVJtt4CLmQCXDJJ5skB0WE0EOYdnyR1FNHe6kBVjuDDlAOZ4QFmjSOGYEiaVGmtGaSBVpisOmqy6RrXp2s3gDMmSMEZx1MYJJVgAeSoBkNmw4ZkITTEcPA2YlkEWfKs78wdkChwokYbZshdlNRkLINYUBIVZlGtcZAB9szXL2KPE0CMJ45WnjTWeLyF5vOXhcIFCzQVgAKMMvmv1iobkzIYgm4Kdjwzsvcml0p850s6erRlWtmXRh+SJP5CF+WiyZBLIV3IZY2TlmKqeEqpXPJlT0uV-SLh6wNtyo2O8TaqrpIMlJoU7oVNwkeZZTEEWIR0qipsJSwBlJdZRKpYAanPjqTgBp5KRVZQ+sjSVKs56vNNR8i4DqYz2iKv9FVKtWpfOmU6tJ+TTDmFhVkj1uStKIo2T6iOXFMVQAOUcyAJzByLKLZc56NyNh3Oyvqx48b6XGsXu86UuapmKszcqtwiB0D40dSiYsXhFh0gAGpjHUA7QEqwXZgAAGS7rAFu5AABCR+FwLgxJ5Vm6ds787Rjqouyt-tYBrsmWoB2dq53IB3fusAn7oynvvuey91r4kIRnbASm97AyPrcKu9d77xFEh-QepDqxAPAYzWW42CE2bsGDs5OqIEphfjUiEQ0uzIAAAFVj1mqAAGXQPhxIWBUC3CaHceQNGaA5DUOCTMqB2ABVY+x5AdwfVGHcEFOZWh8iFBokYM+F9ww+geOfPArBUB0B9HzBUMJUp9CUC9IwR73UmeQNSStwBvxTLGG4UzsTWhSY9BLAiNmRh2cWBB6M1ij1i09KIsA2ECpKGEqieOmAcAkaVYLBCeAmPzrZPCTFp4yMAnQAEC0dIAVcTGA8HozR1YRaeJmQgKbgZHDrIm7gBwABKyAACOrBGBZFatQIltBBz5bGE0D4CmXSGi0KBbLuXEgPDk4VpmxXSvlfyMWag1W6uNea619rWROsfIK3108-Z4sZErcN2AOXMR5e6D1yb6n0AlbK9KNBLyauwHq01lryA2sdYvt1xoyBttfhCCpQ7x3RSnYKy86bN3Hh3fVg9p7K3XtreEF1s7X3dNHUbGlpYGW3BPAy5ZCTA3FxaBkKwHy-XmLFyfX6XQlO-66C5H-JETxdDRSwPoFn2FSe8bcJT6ntP6e6EZ0NNnbOYluVIzt9LmWoDY+oGAP0eOyf7a51T3QNO6cM6wkL-Q8vOc4CJz5U8FLJ2-Yx5LyA0vccc8G4sZysv5cDnJ0rnnCI+dPC5AiTX7PxeQB11AbnKvdDO-V9oLASJhcG5ouj+Lpvzdcm11b-UhoLde-t4rxYfvVcu416zrXHOVKQHT7z9XXIQ+6DD1+Q32GmJR6xzj6apOU+Vr14kXPmT8-K4z0HkvZfGz9D2MZio+RaywCk2vSYqWvfQrK15IKqBieYA59STI9nuAvwdupzTdAG8u3l7OtwDeReo72JHmb0+15z+14vkuix7Cr-X1p3j2-Se79VCWcP4-fsAhP4sEfs+2YX6X8ui+ghmvvHBvlvr5gUEgjgAVjvpRnSMDOTnFPEMWAfAflvGLh-ksF-lAD-ufgvgAWeEAW+iARpvftUDul-BNoFjAU-nAbAHqNUEgZ4DIKgW-hgcbpPghN5K2v-lfrEKAVpvAXtngEwSgSAgAD7iFgB35cD0GMHIEsHHhsFo4T7YGVBHi1Dy6eDBxqD1oK5Nqc6bRe6ph6FUThyvhGGYHuA1hCzRYf5N79YQBN7i4Gbl4R6qFT7f4z54Fe4WYEHhakGyEIH7aiGKHWIyEN6BYyF3gAD6++tBe+whaBjmKhmBnBp+v+8+vhl+bgMhdIDBagoRB84RAhdAvGURpR3YMRnOCRL+Sh5e+mWGvKWMroN0FQ0grAGQMm1+CWnsSwV4w+M+Y+7B2S6RiwmQ3AEgyKmyVhHQiQuhkw+OuQZKPe7haRah3BZy+BfBz6r6G6Mhro2+BujRouMWOGbgrAMg4ISKocB8zkbRrQxG7+HBFy9YOxeGBGg2pO9g7W1siwHxiQhGxxfehmEA-em424KWvysWbgPYgYYxeK3AxYMxTS3AGAfqakARkW6W7AiWKI2h8xeh8RLoJYlhTE0gqeh6kBXaRgBSCEqgGgiAdUaYagyEdYI4VkpxRu5xiwMKa4CJkA7AtYx4gEaJ6AGJz4l29mvRNaBJre1eNJ+S3qXmyAxaKJrQLJbJku1mQwtmiQbgXI-qYACA24KUveh+leYGXklU+p8JahQUbJdmop6JYomJUpPRuJnskmcx8pmOipXq14pY7mow+p3+NpV0tUIWXJlpYyLR5UNpdUApDpxYTpHEYpEp2S7pSxRoz4cpbgroNaFJlaE2-pdJQZupHmoZ2ZFUVUYMkZ5p6BZxNqCE4kF0fRSZGQjptpaZLpZmTSEW0pnpspPp0pAQpZypqkwZnmZ0kkyAEZkQUZFpzRJsroFWbZiZ9pnZKZ3ZE46ZrpkpA5gM6ow5Oh+ZXxYaQUxZ1JUaa4ZZbmFZIZZ5QMIMc5dZC5DZi54JtGvGUJTZJmmo95wwj5R5EQ96KRTmCZIFNZO5FQOQvgcQfZrQAJuy6OG435DGTGwc8uyJCy6YywVAsmkBpOSmaccKH+km6qLIgFepT56o-mEs4FxuqY6YBK1FlZcG1QEWDsFwlx1xGydxFGc8qmDMMhPoFBQWdAoggWsei5DRbhYaAmQm4wZFxuaFPG1Q-GgmAU2FpyNYocjABFOAE2uePBKlmBsAM6nhk59UtssATWxcrgslqxXuJF-waWaKaYGY0K5ZQF05OSl23FvFNxg4ag9xQl8Iasol8I4lbYUl3IZpjhNmVF1lvlVZkAhAtQDsrR9FLgYAAAVG2ENPIH6Nvk5eSsCWkB+eaeCTSAcMMX+d+IgrCURkcATosEJgQGiXVD-vHKWA+Z5nvE0IfBIsfL1RSh4DPvHNdnFhInVHBdwAhWZRUMhYhRUK5atfiZRW5VOWlQQjlY5RXq0GRH8SlTRYsIkskgdYlTYHmj5WdcLDmrdWVZVRVdGf+QTGxcBQ9U4gTIxe9YyC5slTqalTepBj5l-DSPAq8PtYFsFuNQCayiCugBZMDfdVfNlsCuyhhtiiwbQgQojeytAedmaU0WuCaSdZAHySiEFB0LkP8fEOqRsPNYtTGUYCtUtSiOtRzUxMddtf1WlZ+mmgleLkYOuiMHdexbyY9VMsLeRTgVtRLV9ZTSrPtSTR-h+XpjeSiKZp9X5f+pqH9QCNDQrbrWlRBneq8NYpDV+vtQZGraUEZoMBgBkBJL+dyRsAKVkCioGBuLQOEIzZJjcKgOWVmRjkOYbd7jIPBW5c+PMnwejj2NzfiSOWskkddeTQhD2OLodcLHLknRUHmXUXjv2E1edckUJMoZzYQOpjHbMT5PVR-u5R7QcE+vBsQQcYaI-iLRsIXdmcXRsBnbRXgNBeXRaSMeRR4CnRLv3SXaaWGfXd3RrWkP3tkq2VJA3b9k3eZgOHBkQfsaUYcTPTgVPd7ueXLbPRTauS+aPY2Y3d3d6aeT0QEIlRfS2dfYvS4fXi+bJIyYrX5WvTJHJEyYba0L4BkCwRkLVugMhKhE8KmPRgzX-WlXkbAMESIQocUV-EhChLALDbLcbmAxA1AzA7AJ1NwJ1agAg4ckg7kaUUIYgRgyAlg9Azg3gyAxsIQwssQzg3A4QLVmqTQ4sCgwUUUUwxyiw6hGwznc2kFEQxI6Q+Q-YKgPwx2qbbQ4EfkfIcwZg+IyQ1I6TtmPnRBY-dPenaXVANmNnaTiYKo6ze0eY5Tf3YKcKYRYUFY17t5IkDlixd5Wo4sMxV5aStIwE6xeFN3VvQCC3bvXse+h3YuChmAEeFxTxVccFQJYuEahcMJdIQfZ3UfTZf8LoIvYlTqWFIaUvTECvVXtwAFMsBZHYZvffZEzvYsMem3fvYEYcWAJIWAG05xfFoFak-xaFYJV0tk3E+EF3efTteGK6A8Ik3vbE7k-EyUZ04njgCk3ENo3gl0g3vMyg2g6I75iNZNXgCQWAcIfIJgv-IorgnYsIpAuCBcDuhs5cVs2IXPLxmpnQ3IYUYw8c-MKNWcwcdUFc1grc94g89-E8y84zG84w-lHJb9q4T3mOKCdciUEAA)

**Comment by jheer** [comment]
The options below seem to work for me. You do not want to set `view: false` as that tells Vega to not allow any listeners at all (and no listeners means no handler to prevent default either) -- it is only intended as a security policy for deployments that need to ensure that no third-party code (i.e., as written within a Vega spec) can monitor events.

```json
"config": {
  "events": {
    "defaults": {
      "allow": ["wheel"]
    }
  }
},
```

```json
"config": {
  "events": {
    "defaults": {
      "prevent": true
    }
  }
},

**Comment by mathiastiberghien** [comment]
I've run the the sample on Chrome Version 80.0.3987.122 (Official Build) (64-bit) on Windows 10 these settings have no effect for me.

**Comment by jheer** [comment]
Hmm. I'm on Mac OS using Version 80.0.3987.122 (Official Build) (64-bit). Not sure if this is a platform issue, but that might be surprising given it's the same browser version.

**Comment by stas-sl** [comment]
The issue is a bit old, but I also encountered it on Mac OS, Chrome Version 99.0.4844.84 (Official Build) (x86_64). 

After some debugging, I found that just setting is not enough:
```json
"config": {
  "events": {
    "defaults": {
      "prevent": true
    }
  }
}
```

Looks like if you are not using specific events in your spec, then your view will not listen to them and thus will not be able to call `preventDefault` on them. So in order this setting to work, you have to create a dummy signal listening for the event you want to prevent default behavior. Also you have to identify the right event to listen, you may think this should be `click` or `dblclick`, but actually those event are fired already too late, because selection occurs on `mousedown`, which is fired before them.

Alternatively you can add `!` to the event name (`"on": "mousedown!"`) without setting `events.defaults.prevent` to `true` in config.

The third option, probably even more simple, if you have access to CSS, you can prevent selection using styles:

```css
svg {
  user-select: none;
}
```

https://observablehq.com/d/bc90b2408233e866

https://user-images.githubusercontent.com/4602302/167700460-1f9442c8-2500-46f6-b9b3-c4ebba62fb5b.mov
