### ISSUE TITLE
Can't pass frozen data to vega

### ISSUE THREAD

**Issue by betalb** [vega/vega#2453]
When frozen values are passed to vega as part of spec, an error is thrown that object is not extensible

I've created test case in observable notebook https://observablehq.com/@betalb/vega-plot
It uses the latest published vega version 5.

Currently, vega mutates parts of data that are passed to it. While it is ok when data is loaded from CSV, JSON, and used solely for vega. But it is not good when data is used by multiple parts of code, not only vega itself. This is the reason why we froze data in DEV mode to capture cases when we accidentally mutate data

Code pointer, where passed data is mutated: https://github.com/vega/vega/blob/f28b7eeb0671a2902d414a532bee8ab73fdcd98e/packages/vega-dataflow/src/Tuple.js#L51

**Comment by jheer** [comment]
At minimum, Vega annotates input data objects with an id using a Symbol-valued key. These id values are currently necessary for internal tracking and management. One option is to generate an un-frozen data set and pass that to Vega instead (or Object.create a new set of objects that use the frozen data objects as prototypes). Along those lines, the [JSON data format `copy` property](https://vega.github.io/vega/docs/data/#json) might be of interest.

In addition to the id, any downstream transforms that modify the data will require writes, which would require tuple copying anyway. So depending on the spec, the upfront copy might not add overhead beyond what Vega already needs to do.

Hope that helps! In the future, we could consider adding more logic to our data ingestion that automatically handles frozen data. However, this is the first time we've received a user comment indicating that this might be useful.
