### ISSUE TITLE
Triggers: Inconsistency between remove, toggle and modify methods to select data rows

### ISSUE THREAD

**Issue by mathiastiberghien** [vega/vega#2454]
Hello,
I'm not able to update a table with a trigger.
Am I doing something wrong?
Here's a sample: [modify sample](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYALAAYdiiJBSNq+bXoNRYJmegA2sbAG0lEUBA9RbqZNkiMZeAAnZHRYX0tPSFlnYEhkKhk8RyxIEPg8LHg7RngAawUoADNuIPhfHDwg1mR5KFZCNXQ8Cv9AkLDfAF8AXVcwLqUey0gmvEwsF093Ty90Hz9x9jsI-sMKexqUpzj1bABGeUgNuxrsHS75XbVsACY6482Ki6v-G6wAZiOTs6wL4bWUBik0BblBHkgVRM1GQQT8AWCoXCCnBhlQ3DUjCKAE8-MB1FgER1wl0UbNZo9TsgUpBgD9kFhRKTwYNyT1Zv1WWAAYYEPZqc5+jMot5WgAPMkUvDYwitdjoGQ3SIQwjoNSYmTUc50Q6A0bcDABbBxMYTSHoZYRYqMZB2d5vSCXPVBBUwvyqDSISCcoYjDBBPLbIV66WyvzpPCSqJFIIG42jZpmpYrR3KwzIQIYirCikZlpwrA58mQXGFyDWai2Ox+YymPCkW5gAC0YFQAQAFLX8PJRDoAJQNx0stMQhpjbOowxdyNlitVvxtmSd5AmbtgXt91OTqASstFG12+FKqzwfl+CVO8kUj2aWenlOpCUPeWK7BVGpc8mfjzfy8eItQKGrQtGKkYjpAMZxmWpqLBaKZ-lEGbwFmxrgvESSwqhV4QvYNjxvSfjlBhcIIVekDyuEOQyNmlK-JAbbqvBw5oWOzQTthhi7nE+62vaewPHyD6QE+QJFEU4QznEc72H4L5qDeiDtgA5GKSkDrcjqkcWpZSTYMmpNOg5aVKyCgfGPGHqkBHfp4NkDD6EB9F0QA)

If I use toggle or remove, the appropriate data is removed but nothing happens with modify.

**Comment by na3imk** [comment]
Hi,

Could you tell me if the following answers your question?

[https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYALAAYdiiJBSNq+bXoNRYJmegA2sbAG0lEUBA9RbqZNkiMZeAAnZHRYX0tPSFlnYEhkKhk8RyxIEPg8LFRuVnC1bmU5eSgAM24g+F8cPCDWZGLIVkI1dDwqyBa8VlRIAF8AXVcwXqV+yw7WzCwXT3dPL3QfPzx0djsIocMKezqUpzj1bABGeUhtuzrsHV75A7VsACYG88usa9v-e6wAZlOXquuY02UBi02BbnBHkgNRM1GQQT8AWCoXCCkhhmyakYJQAnojAiEwht5vMzjtkClIMB-lhRL1IJCRiT+vMhkywEDDAh7BTnEM5lFvO0AB5oknQnGEdrsdAye6RKGEdBqLEyahXOgnYEdbgYALYOKdKbQ1brBSlRjIOxfT59BWGIKyuF+VQaRAMzzszlQDBBADWe352rwkva6TwYtJJSCuoNExWy1Nvhu2uQgW4aiqAtJabaCKw2fFeILkGs1Fsdj8xlMeFIDzAAFowKgAgAKav4eSiHQASjrfUZ9qhTU6WfRhg7EZLZYrfhbMnbyBMnbA3Z7dvHUFFJZKlutiPlVngPL8opTJNJrs00+PZtSooaMrl2BqdXZJPfHk-548hagIalZZkGFCMh0gaNYxLI1EzWZMwLTeAMzHC8oFzeEDXHSB7BsON-j8SoknQn8UMgGVwjsAIszJC52hbFUzU-T0h0MEdWmQlCtzjXcrRtQ4Gm5O9IAfEEShKcIpziGd7D8J81CvRBWwAcmFRS+wePpiIvSBi0kmxpNSSd+008U2hAri9xtPDGK-YFv1GEBeiAA](url)

Best

**Comment by mathiastiberghien** [comment]
Hi @na3imk , thanks for your answer.
My sample is indeed wrong, [here](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYALAAYdiiJBSNq+bXoNRYJmegA2sbAG0lEUBA9RbqZNkiMZeAAnZHRYX0tPSFlnYEhkKhk8RyxIEPg8LHg7RngAawUoADNuIPhfHDwg1mR5KFZCNXQ8CsgmvFZUSABfAF1XMG6lXss25swsF093Ty90Hz88dHY7CIHDCnsalKc49WwARnlITbsa7B1u+T21bAAmOpOtisvr-1usAGZj0-OsS5G6ygMUmQLcYI8kCqJmoyCCfgCwVC4QUEMMqG4akYRQAnn5gOosHduqjZrMnmdkClIMBfsgsIiQmFkHQ6WAANRgUQkiFDMm9WYDPlgQGGBD2KnOAYzKLeVoAD1J5LwOMIrXY6Bkt0ikMI6DUWJk1AudCOQLa3AwAWwcXaEyhy1WhUgRUYyDsH3ePR1hiCmthflUGkQkCFw1GGCCeR20vNKrVfnSeCVUSKQUtNrGS0Wjt8V3NyECmIqMvJhZa8KwpbJkDxVcg1motjsfmMpjwpDuYAAtGBUAEABRt-DyUQ6ACUnZ6vJ9kIa7RLaMMw+T9cbzb8-ZkQ+QJhHXIn3qXUEV9dd7s9+0e4qdqUV+bJ5KDmjX8AlfkVjw1WuwVRqwrJACPCAh8PGrKB41aFp5WTWcXXTLp6ztHMVjzODC3gYsbQheIkjhbDH0hewbEzOk-HKPD4VAwjIA1cIchkEsKT+SB+wNJ0gM8ajyXnZpF0IwxTzic8PQRbUrDfW9IE-YEiiKcJVzidd7D8b81GfRABwAcnlLTJzuHpuJrOslJsFTUhXKcjOVZAYMzETPTIzjgKBEDhhAbogA) is an update trying to explain my point.

It seems that to make the modify trigger work you have to provide the entire object that you want to modify, but you can use only one selector field with the remove or toggle trigger.

In my current sample I've used your code but replace the modify parameter which was increase with {id:2} and now it won't work. If I replace modify by toggle like in [that](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYALAAYdiiJBSNq+bXoNRYJmegA2sbAG0lEUBA9RbqZNkiMZeAAnZHRYX0tPSFlnYEhkKhk8RyxIEPg8LHg7RngAawUoADNuIPhfHDwg1mR5KFZCNXQ8CsgmvFZUSABfAF1XMG6lXss25swsF093Ty90Hz88dHY7CIHDCnsalKc49WwARnlITbsa7B1u+T21bAAmOpOtisvr-1usAGZj0-OsS5G6ygMUmQLcYI8kCqJmoyCCfgCwVC4QUEMMeG41Goqz8wHUWDu3UgEKGszAvQgA1J5NGCHsyB2AxmUW8rQAHqiyVCAJ6EVrsdAyW6RSGEdBqNQBagXOhHIFtbgYALYOLtCZQ5Y4x5FRjIOwfd6FSDSIJ4bBVGpXeVBQWwvyqDSIYmeamAwwYIJ5RnTeV4XmtdJmkWGIpBRUqsZLRaa3xWrnIQLcNQVZmzeJJOEqtFQbkR6zUWx2PzGUx4Uh3MAAWjAqACAAoS-h5KIdABKcs9EnByENdop7O4ZAmMxYOL5wt+WsyBtD0t1FutnrdtMc0eQHV6g37R50nGpDlxslRB2aNe79lGgVC83VZDUsn3jyPw-grl+vmLZBsoPy0PhtdqtGKyxt26bwEm-ZHlACYtPCo7ZpA9g2BGvytOUGbwi+R6QAK4Q5DIKZPGcrS1hKOKPi6y71I0zSQVBUCrnEG76giwpWPA9J+ByjzcEURThGaZ42PYfhXmoJ6IHWADkbJSe2dw9FhXK5kJBYiakjZlgpSlpi034RsxBqoZ2UEUYMVLDCA3RAA) sample the id identifier is sufficient to retrieve the object in the data table.

In some case the use won't have the complete object but want to trigger a change using the id. He might also want modify a set of data that are sharing the same property. As this is feasible with toggle and remove method, I was expecting that it was also feasible with modify

**Comment by na3imk** [comment]
Hi @mathiastiberghien 
understood! Unfortunately, I find asking myself the same questions but would love to know the answers! 

I'm gonna just reframe the issues to make sure we agree on what needs to be solved:
==
Indeed, it seems that the "modify" method : 

1- needs the complete object like this (taken from [here](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYALAAYdiiJBSNq+bXoNRYJmegA2sbAG0lEUBA9RbqZNkiMZeAAnZHRYX0tPSFlnYEhkKhk8RyxIEPg8LFRuVnC1bmU5eSgAM24g+F8cPCDWZGLIVkI1dDwqyBa8VlRIAF8AXVcwXqV+yw7WzCwXT3dPL3QfPzx0djsIocMKezqUpzj1bABGeUhtuzrsHV75A7VsACYG88usa9v-e6wAZlOXquuY02UBi02BbnBHkgNRM1GQQT8AWCoXCCkhhmyakYJQAnojAiEwht5vMzjtkClIMB-lhRL1IJCRiT+vMhkywEDDAh7BTnEM5lFvO0AB5oknQnGEdrsdAye6RKGEdBqLEyahXOgnYEdbgYALYOKdKbQ1brBSlRjIOxfT59BWGIKyuF+VQaRAMzzszlQDBBADWe352rwkva6TwYtJJSCuoNExWy1Nvhu2uQgW4aiqAtJabaCKw2fFeILkGs1Fsdj8xlMeFIDzAAFowKgAgAKav4eSiHQASjrfUZ9qhTU6WfRhg7EZLZYrfhbMnbyBMnbA3Z7dvHUFFJZKlutiPlVngPL8opTJNJrs00+PZtSooaMrl2BqdXZJPfHk-548hagIalZZkGFCMh0gaNYxLI1EzWZMwLTeAMzHC8oFzeEDXHSB7BsON-j8SoknQn8UMgGVwjsAIszJC52hbFUzU-T0h0MEdWmQlCtzjXcrRtQ4Gm5O9IAfEEShKcIpziGd7D8J81CvRBWwAcmFRS+wePpiIvSBi0kmxpNSSd+008U2hAri9xtPDGK-YFv1GEBeiAA))

`"signals":[
    {
      "name":"increase",
      "on":[{"events":"rect:mousedown", "force": true, "update":"datum"}]
    }
  ],
  "data":[
    {
      "name":"table",
      "values":[{"id":1,"value":0},{"id":2, "value":0},{"id":3,"value":0}],
      "on":[
        {
          "trigger":"increase",
          "modify":"increase",
          "values":"{value:5}"
        }
      ]     
    }
  ],`


But this doesn't work (taken from [here](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYALAAYdiiJBSNq+bXoNRYJmegA2sbAG0lEUBA9RbqZNkiMZeAAnZHRYX0tPSFlnYEhkKhk8RyxIEPg8LHg7RngAawUoADNuIPhfHDwg1mR5KFZCNXQ8CsgmvFZUSABfAF1XMG6lXss25swsF093Ty90Hz88dHY7CIHDCnsalKc49WwARnlITbsa7B1u+T21bAAmOpOtisvr-1usAGZj0-OsS5G6ygMUmQLcYI8kCqJmoyCCfgCwVC4QUEMMqG4akYRQAnn5gOosHduqjZrMnmdkClIMBfsgsIiQmFkHQ6WAANRgUQkiFDMm9WYDPlgQGGBD2KnOAYzKLeVoAD1J5LwOMIrXY6Bkt0ikMI6DUWJk1AudCOQLa3AwAWwcXaEyhy1WhUgRUYyDsH3ePR1hiCmthflUGkQkCFw1GGCCeR20vNKrVfnSeCVUSKQUtNrGS0Wjt8V3NyECmIqMvJhZa8KwpbJkDxVcg1motjsfmMpjwpDuYAAtGBUAEABRt-DyUQ6ACUnZ6vJ9kIa7RLaMMw+T9cbzb8-ZkQ+QJhHXIn3qXUEV9dd7s9+0e4qdqUV+bJ5KDmjX8AlfkVjw1WuwVRqwrJACPCAh8PGrKB41aFp5WTWcXXTLp6ztHMVjzODC3gYsbQheIkjhbDH0hewbEzOk-HKPD4VAwjIA1cIchkEsKT+SB+wNJ0gM8ajyXnZpF0IwxTzic8PQRbUrDfW9IE-YEiiKcJVzidd7D8b81GfRABwAcnlLTJzuHpuJrOslJsFTUhXKcjOVZAYMzETPTIzjgKBEDhhAbogA))

`"signals":[
    {
      "name":"increase",
      "on":[{"events":"rect:click", "force": true, "update":"datum"}]
    }
  ],
  "data":[
    {
      "name":"table",
      "values":[{"id":1,"value":0},{"id":2, "value":0},{"id":3,"value":0}],
      "on":[
        {
          "trigger":"increase",
          "modify":"{id:2}",
          "values":"{value:increase.value + 5}"
        }
      ]     
    }
  ],`

And even weirder, this is not working either (taken from [here](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYALAAYdiiJBSNq+bXoNRYJmegA2sbAG0lEUBA9RbqZNkiMZeAAnZHRYX0tPSFlnYEhkKhk8RyxIEPg8LHg7RngAawUoADNuIPhfHDwg1mR5KFZCNXQ8CshgAHJ1dqwARnl2insa7p0AX0hRgF1XMFGlSctIJrxMLBdPd08vdB8-FfY7CJnDQbsalKc49Ww+yFOa7DH5K7VsACY6u6GKp5fsAGZ5F8zj8ppEPNE5Gtjh5NlsIVUTNRkEE-AFgqFwgoYVFUNw1IwigBPbBQdEhMJHeFRe7IFJtWlYcmY5B0WlgADUYFE4xxsxhky2MzmEAWSkgCHsdOcMzhEO8rQAHtj4ZA8ETCK12OgZK9wYZCOg1ASZNRHnQ+jCltwMAFsHFlqs1egDhFioxkHZXqlrqN9VAgjrkX5VBpEJBhfNFhggnkLrKrerNX50ngVVtIEUgjb7Utmk79ocJv74oF8RU5VFkEkUfa+YYSVg4tZqLY7H5jKY8KQ3mAALRgVABAAUnfw8lEOgAlD2Jny-XzIA1lhX64Yx2mmxKbPY-EOZKPkCZx9zp8W11BlVuih6vWi9VZ4FK-MqF9SoqHNFvJUXUsrPtqurYFUNQitSYGeBBszgpWUBJq0LSKmmJZZjmW6OnsLpFm+GbVvA5Z1u+pYtKiTZrpA9g2LmtJ+OUNaojhRHauEOQyBWwIPKkQ7Gth87+oYy7NKu76GFecQ3p63r+A+EpPr+kD-lA3BFEU4Sbs2O7tqkgFqJ+iDDu0irtDObwTIx1KQI2GmtruqQbrO5mqoh6mZreUk0VBkEwlBYHTKMQA) where I put the complete object in the signal "increase"):

`"signals":[
    {
      "name":"increase",
      "on":[{"events":"rect:click", "force": true, "update":"{'id':1,'value':0}"}]
    }
  ],
  "data":[
    {
      "name":"table",
      "values":[{"id":1,"value":0},{"id":2, "value":0},{"id":3,"value":0}],
      "on":[
        {
          "trigger":"increase",
          "modify": "increase",
          "values":"{value:increase.value + 5}"
        }
      ]     
    }
  ],`

2- Also, I noticed that the "modify" method is not working with an array of objects, and seems to work only with one object. 

Hope someone can help, I've played a little bit with Vega but really couldn't understand how the "modify" method works. Besides, all examples I found only deal with one complete object.

**Comment by mathiastiberghien** [comment]
@na3imk , thanks for the clarification: my guess is that the modify find object using equality and that the toggle and remove methods are using object property equality which bring some inconsistency. I'll update the title

**Comment by na3imk** [comment]
> my guess is that the modify find object using equality and that the toggle and remove methods are using object property equality which bring some inconsistency. 

mmmm... You're probably right.
Actually I noticed this because I wanted to try to following hack : 
- Create a signal that creates an object property (ie {value:5})
- Filter a dataset with the object properties to get another dataset where all rows with value=5 will be kept
- Pass this filter dataset to the modify method

don't know if I'm clear, but nevermind, as the last step is not working anyway :p

**Comment by jheer** [comment]
To clarify, `modify` only acts on the exact data objects passed in. In this regard it is similar to `insert` which takes exact data objects and inserts them.

Both `remove` and `toggle` operate on predicates: ff the input is an object (but not an existing, ingested data object) all data objects whose property values match the specified input properties are affected, ignoring any other properties on the data objects.

I will update the docs to better reflect this.

Also, [here is a working variant of your earlier example.](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAB3GgBN6aACwAGNTPg0yWVRpkQd4pABsIaANqgTCOGhA1xUAE5wkEezIlXQcUuKYFuhuUJioUKY0UADW0iAAZmwuUPaomC4McDIMOApImGkg+ZgMCCAAvgC61TIlKKjWILZFmEhMpl4gxGZZwU2KaACMMj2mWWhqFVKgg6gATKO9aVMzjgpoAMxL4yu1ID6NoBk6ZHAuDk6u7p7xCGwKNAkAnpfObh5dY30OwN9wqCuH08lH+AAIANRggQVSo1KqGKBmOD9GxIOwOAAe8UwzxwRSYSHEGxkOCQCke4jIk0oI2KbGQTjQoHqDjaHS6CRocFMG3Qg2mIBcRLODnkShgcJkyBcMVRIFx+IcoUw8QSLgZzOKBQaCvanUqMjgzgeaT8gXOWteqFARjIJlMDm0ukwBHmYIAtGCEE4ABTOrBSARqACUbsqgtyJTNGDgOj0NpAdodDh94n9cZdUmhocNIGxia5PL563i0GRWLz4uUifLBvQ2JkhOJaAyWQqHemxzxrTgmNVMnVmsTrPQ7INguNUFNWuNhQuibMxi1-wcqQtF0FhM8UXEMdX6B9FInkbyBRjBdARd5lxJSaR9fz8TYCQSnlVteMZgczYU1ZgvoAOSYoBYbzBGMjWraX6OugAauuBgqFP2WrXiWq6dtUFRAA)

**Comment by jheer** [comment]
In case anyone is curious, the actual logic can be found here: https://github.com/vega/vega/blob/master/packages/vega-functions/src/functions/modify.js
