### ISSUE TITLE
resolveFilter transform return empty table

### ISSUE THREAD

**Issue by mathiastiberghien** [vega/vega#2460]
I'm not able to make the combination crossFilter/resolveFilter to work..
Here's my sample: [CrossFilter sample](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYALAAYdiiJBSNq+bXoNRYJmegA2sbAG0lEUBA9RbqZNkgAndBlqZAB9TEtPSAp7Vl8sJ30ARgBdVzAAX0iwd08vdB8-QOCw9gV0wxi7OOck+QAmNM8s9Nyo73iAoJDQ+HK8qCqahIBmeS0mjwylFMtINXQ8TATWivzCrEgl9jtfbMrY5EcE4Ehl-UgyrH0oPuv5dc7kXZ8ZPFCkyCzT8-lL7DqtwBD0gHT8zzQyDeoXqX3kP2B-yw9RBdxRj3BLyh7xGcIRyL+VzGQKwxNBBSeWOhWjxZ2wYyRWlR2hBYM2ENe71EtOWTMZzKwolZFMxkOhADYvrM1ltirAAGbcfyoZxrNxqjxbACehE68H83FgCsYdjwyH8-QGmvljGeamOTjphIUkD60qtmoAjnF-FrVR7PG0A4ZrNRbHYit0wpgNc19lag8HIKHw5GSqEyrGpvGBomA8mbPY0z0+lmINNg+78ymizhIAAPUI203myAait5Sbl7J58kbLbhS1RaSsfzwTrbXZDzV4OWK5XYMAuD15qJ4HWdfxHbh2KjNs0WnPWk0HvyN-eto+GGxK+Li9trLuZHsytkDsrx5PcUfjvyTvYyrOQQKkqKo4MuCZZtqupFNuu7IBeh5QYhZ5Niel5QTeW7YKID4DE+LSBq+IqbO8fSfiOY4TugOwAQMsrAfOYFLhqq4zhusHSPBKFXlAKGbOe6FIUmWHxCMeGdukHZpBkQA)

In the sample there are no marks, only data and signals.
I created:
- a data table `table` with 3 identifiers, a,b, and c
- 3 signals representing the desired range of values for these identifiers
- a crossFilter transform on table `table` defining 3 queries based on my 3 signals defining the mask on the signal `x_filter`
- 3 tables `table_a`, `table_b`, `table_c` using the transform 'resolveFilter' using `x_filter` for filter and using ignore trying to have in each table only the filter for the identifier having the same name of the table (table_a should use filter using a identifier)

Looking in the Data Viewer, my tables that are using resolveFilter are empty.

Did I miss something?

**Comment by jheer** [comment]
In your `resolvefilter` transforms I think you need  to replace `"filter": "x_filter"` with `"filter": {"signal": "x_filter"}`?
