### ISSUE TITLE
Locale strings are not updating when two locales are used in same page

### ISSUE THREAD

**Issue by venki227** [vega/vega#2461]
Hi Vega Team,

I created two area chart's with `de-DE` and `ja-JP` locales like below. I see only translations for de-DE is shown for both charts. 
Observations:
locale which is loaded first used for rest of the charts.

Please help me to fix this issue. Let me know whether I am doing anything wrong.
```
import de_DE_time_format from 'd3-time-format/locale/de-DE.json';
import fr_FR_time_format from 'd3-time-format/locale/fr-FR.json';

const localeData ={
  'de-DE': {
    format: de_DE_format,
    timeFormat: de_DE_time_format,
  },
  'fr-FR': {
    format: fr_FR_format,
    timeFormat: fr_FR_time_format,
  },
}

function load(locale) {
 vega.formatLocale(localeData[locale].format);
 vega.timeFormatLocale(localeData[locale].timeFormat); 
}
```

JSX
```
<AreaChart locale='de-DE'/>
<AreaChart locale='ja-JP'/>
```

<img width="1541" alt="Screen Shot 2020-03-18 at 7 36 04 PM" src="https://user-images.githubusercontent.com/15823506/77028737-f19e2a80-6956-11ea-8be7-86f58b781ca0.png">

**Comment by venki227** [comment]
Hi @jheer, Please help me on this issue

**Comment by venki227** [comment]
@kanitw. Please help me on this issue

**Comment by jheer** [comment]
I don't know the full context of your application, but the critical bit to know is that Vega's locale settings are currently global (not per-view): once set, they are used by all subsequent visualizations. So one approach might be to make sure that the first visualization is completely rendered (i.e., waiting for the Promise returned by `runAsync` to resolve) before changing the locale and rendering the second visualization. However in the case of interactive updates the first visualization might still update according the new locale settings.

But first and foremost, in your example above, it looks like the number format *is* changing, but not the date format. I'm not sure where ja-JP settings would come from, as I only see de-DE and fr-FR locales imported.

**Comment by venki227** [comment]
@jheer I forgot to add Ja-JP settings. but in real code those were there

**Comment by venki227** [comment]
@jheer Sorry for not giving full context. I created heroku app and deployed here.
https://stark-citadel-61563.herokuapp.com/


Please see the code here

```
import React, {Component} from 'react';

import * as vega from 'vega';
import spec from './spec.json';
import config from './config.json';
import loadLocale from './load-locale.js';


class StandAlone extends Component {

    componentDidMount() {
        this.renderChart();
    }

    renderChart() {
        loadLocale(vega, this.props.locale);    
        const _view = new vega.View(vega.parse(spec, config))
        .renderer('svg') // set renderer (canvas or svg)
        .initialize(this.ref) // initialize view within parent DOM container
        .hover() // enable hover encode set processing
        .run();
    }
    render() {
      return (<div
        className="test"
        ref={el => {
          this.ref = el;
        }}
      />)
    }
}

export default StandAlone;
```
load-locale.js
```

import en_US_format from 'd3-format/locale/en-US.json';
import de_DE_format from 'd3-format/locale/de-DE.json';
import fr_FR_format from 'd3-format/locale/fr-FR.json';
import ja_JP_format from 'd3-format/locale/ja-JP.json';
import en_US_time_format from 'd3-time-format/locale/en-US.json';
import de_DE_time_format from 'd3-time-format/locale/de-DE.json';
import fr_FR_time_format from 'd3-time-format/locale/fr-FR.json';
import ja_JP_time_format from 'd3-time-format/locale/ja-JP.json';


const formatByLocale = {
  'en-US': {
    format: en_US_format,
    timeFormat: en_US_time_format,
  },
  'de-DE': {
    format: de_DE_format,
    timeFormat: de_DE_time_format,
  },
  'fr-FR': {
    format: fr_FR_format,
    timeFormat: fr_FR_time_format,
  },
  'ja-JP': {
    format: ja_JP_format,
    timeFormat: ja_JP_time_format,
  },
};

const loadLocaleData = (vega, locale) => {
  const localeData = formatByLocale[locale];
console.log(localeData);
  if (localeData) {
    vega.formatLocale(localeData.format);
    vega.timeFormatLocale(localeData.timeFormat);
  } else {
    console.error(`Unable to locate locale data for: ${locale}, using en-US default instead`);
    vega.formatLocale(en_US_format);
    vega.timeFormatLocale(en_US_time_format);
  }
};

export const SUPPORTED_LOCALES = Object.keys(formatByLocale);
export default loadLocaleData;
```

**Comment by venki227** [comment]
@jheer you can click on `show de-DE` button to see another area graph on heroku
