### ISSUE TITLE
TypeError: Cannot read property 'getContext' of null

### ISSUE THREAD

**Issue by jpbberry** [vega/vega#2464]
I've been getting this error after some time, and I'm not sure why it started happening but I'm using out of the box vega so. 
Similar to [this](https://github.com/vega/vega/issues/915) issue, however, the answer to it, was a version change, and considering it's two years later, it's safe to say that's not my solution lol.

Version: 5.10.0
[Visualizer](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAB3GgBN6aAQAZVM+DTJY0AJnUycSBQpriyKmQrbJzAYTYAbNgCc0cmHTjSQTpExwTo4u7uiyXpg+1kiYKKgA2qDiSAg+6HFMTtEgxEhODHAQaEkgAB5oGiAAnpUAvlKgFagAjDK1qHoNTfrtaAAs3eVoAMx9qABsQ8394wAc01Y1aC2qi5PjLV2Nw6gA7JuDO81zm1PHaACcmwsAunW3MtD5RSXJqenDMpjVOJ84bHMmF8riQFk+8iUMF8NjsklQoAUsXiIEy2V8ADMaEEFB4KjIoM43B4It4QA0-AEgiFieFIjlCaESfTyTsUmkPLVvr9Pk5zHAkO4ZKDwR4tDpgTJxDQoOlMK5CjIAF5wVxsNDyxUgWFIcxoRHIjxonJYnGc3yM2meMl1Ibsz6WoWonkeNxmFJOEFgsgO2LkNxc7W2XXwg1xI0BdEyU1OXHoKDkh4yJBlV6JUBubHiYHoJhsbC2XzPdHofEgMiuRQahVwGQVxQ0sLWqK+fyBYJEpuklsyNtBABiEkwAGUaCr9FV6woAOqKZSoEZDTNwbMebIYyUgYufQNT6taqeN5lk3tUjtMuknyntwfZ0fjzqTyszufQhdJkDIVwAa2K6edfweBWbAMDgmJqgg+ogBiSCyjm7wcugECqtixQxOGGSRjkwGgUwHQgAmBKdlBeQFBCLK2hSX6-m8AG8vy4GFgi2qGkhKGvBSK6Ego6SgCuURhD0zHbnimLYrGonWMGeqJBoBiPCAKY0H+iLSeIR6Xi2trjKAInoIGMZxssFIQPKbDfrxW5QC8HiOmJZrxqyW5mRZs5QiR+SFPo2kgKBSItsxWJOE4ADyxhQHQHSgKRXmtD5MBsKQgnQTQwVhbBkUeWRlSUAIlEPAVQA)

Code looks like:
```js
new vega
  .View(vega.parse(chart))
  .renderer('none')
  .initialize()
  .toCanvas().then(canvas=>{
     resolve(canvas)
  })
```

Error:
```js
TypeError: Cannot read property 'getContext' of null
    at resize (/home/jpb/node_modules/vegaexp/node_modules/vega-scenegraph/build/vega-scenegraph.js:3665:28)
    at CanvasRenderer.prototype$6.resize (/home/jpb/node_modules/vegaexp/node_modules/vega-scenegraph/build/vega-scenegraph.js:3714:5)
    at CanvasRenderer.prototype$4.initialize (/home/jpb/node_modules/vegaexp/node_modules/vega-scenegraph/build/vega-scenegraph.js:3294:17)
    at CanvasRenderer.prototype$6.initialize (/home/jpb/node_modules/vegaexp/node_modules/vega-scenegraph/build/vega-scenegraph.js:3709:28)
    at initializeRenderer (/home/jpb/node_modules/vegaexp/node_modules/vega-view/build/vega-view.js:657:8)
    at renderHeadless (/home/jpb/node_modules/vegaexp/node_modules/vega-view/build/vega-view.js:780:12)
```

**Comment by domoritz** [comment]
Make sure to run `runAsync` before calling `toCanvas`. Does it solve the problem?

**Comment by jpbberry** [comment]
> Make sure to run `runAsync` before calling `toCanvas`. Does it solve the problem?

@domoritz nope same error

**Comment by domoritz** [comment]
Your code is essentially https://github.com/vega/vega/blob/master/packages/vega-cli/src/render.js, right?

**Comment by jpbberry** [comment]
@domoritz no? I showed my code there...

**Comment by domoritz** [comment]
What I meant was that the code does something similar (and could therefore help you find the issue), not that it's the same. If you post a complete example, I can try to look into it.

**Comment by jheer** [comment]
Looks like you’re running in node.js. Is the node-canvas dependency successfully installed? You may need to add it to your project’s dependencies, as described in the usage docs: https://vega.github.io/vega/usage/#node

**Comment by jpbberry** [comment]
I've gone ahead and reinstalled canvas and it works perfectly. Was having node-gyp issues apparently. Sorry for the mess up

**Comment by domoritz** [comment]
No worries. Thanks for using Vega and reporting issues.

**Comment by iloginow** [comment]
Sorry for bothering. But I'm having the same issue and getting the exact same error. Except that I'm running it in a docker container and reinstalling node-canvas doesn't help. In fact I don't see any issues with the node-canvas installation inside the container. It's just being successfully installed every time. I've tried to install it both globally and locally... even globally/locally at the same time. Got same result with this "Cannot read property 'getContext' of null" error.

Here's my container setup:

```
FROM node:12

RUN apt-get update \
   && apt-get install -qq build-essential libcairo2-dev libpango1.0-dev

RUN npm i -g canvas --unsafe-perm
```

And the code I'm trying to run is basically identical to the Node.js example at https://vega.github.io/vega/usage/#node

I would appreciate any help.

**Comment by jheer** [comment]
A null context most likely indicates a missing canvas installation. Or, at least, one that is not being found during node_modules resolution.

If you are using Vega server-side, I recommend using `vega-cli`, which includes Vega, node-canvas, and the Vega command line utilities -- this is the package primarily intended for server-side use. Users importing just `vega` need to also explicitly install canvas. I'm hoping that perhaps this helps clear up some of the issues people are noting on this thread.
