### ISSUE TITLE
Confusion over the new blend mode: CSS vs canvas (from 4.6.0)

### ISSUE THREAD

**Issue by DougBurke** [vega/vega#2473]
The 4.6.0 and 4.7.0 spec have this as the description of the blend mode:

```
The color blend mode for drawing an item on its current background. Any valid CSS mix-blend-mode value can be used.

__Default value: "source-over"
```

However, "source-over" is not included in the enumerations defined in `#/definitions/Blend` or in the CSS mix-blend-mode (which has `<blend-mode> = normal | multiply | screen | overlay | darken | lighten | color-dodge | color-burn | hard-light | soft-light | difference | exclusion | hue | saturation | color | luminosity`).

It looks from https://github.com/vega/vega-lite/pull/6033 that `"source-over"` comes from the canvas side, rather than CSS side, which makes me wonder

a) should the description include more text (from the vega/vega-lite#6033 issue) explaining this
b) should the enumerations be expaned to include the canvas options, or is there a mapping between canvas and CSS
c) or something else?

(note: I am not trying to use these directly myself, just wondering how to include and document this functionality in my Vega-Lite generating library)

**Comment by domoritz** [comment]
`source-over` is also not defined in https://github.com/vega/vega/blob/master/packages/vega-scenegraph/schema.js#L177.

**Comment by jheer** [comment]
The schema and implementation are as intended, but the documentation was confusing. I've updated the mark property docs to better clarify.

Vega explicitly supports all CSS mix-blend-mode strings *except* for `"normal"`. The corresponding mode in Canvas has a different name: `"source-over"`. To resolve the difference, Vega uses the blend value `null` to indicate the default, which corresponds to both normal (for SVG) and source-over (for Canvas).
