### ISSUE TITLE
Error with transform 'window' using 'prev_value'

### ISSUE THREAD

**Issue by mathiastiberghien** [vega/vega#2475]
Hi,
I'm facing issue using `prev_value` in `window ` transform,
Here's a sample: [window transform issue](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYALAAYdiiJBSNq+bXoNQ16PJiwBtJRFARXUGelTJskeNwrqAPoAZgBOgaHoygpOrpCsoQA2PvhEJOSRygzMbOyssMihfjJ4yCV0fqik3IRlfgFqAIwAnAC0YaTWtqQYsKWhnYx9pEiMwWHIsK3wiZOS0nKWboZ4kTKwwdyhqNiOy64u+3F4AJ61PsGMif0xR3HIAB6EoT6wHH2hjDLUABRdrKgKtw1Mh5PoAMwASjAAF44WAAOQAJQAogBxBFgABkWLAb3YHy+v3+gJk3FQYPkjWhcJhiIAQpicWA-jYAXQushYfCEQAmHT81o6cGtXmiTEAHwlYBJdDJqG5MIR9NCyFs1BkyARkMgsTcAF8lstDndIKdzlhIM9uBJkPA8Lc7lBLshEmpYLtIPKFJBOT6QfBJpAALpG-aQdAehxezzeeS+mxxqzIGyID3BvWuQ2Z5w545nbyWvyJWb2x2m6ShB1YYCQF1uz0eLz+xMh-V57N3E1HM0FnyqGRqbjRMPLSCV6u1+tqRuxlulNujtyQaihbisQjsE6z5uhvOGGpR+xW1UUQIUdCJVjePdO52MV3uz0g1PpjuZjMGpQZ-VAA)

![Transform_window_issue](https://user-images.githubusercontent.com/22467324/77637776-7a6c2600-6f56-11ea-8502-f9e5052e2e2d.png)

I've filtered the data trying to focus on the problem:
In the data, I have deaths count for each country in France by date and from different sources.
For some date the deaths are undefined.
I wanted for each county to have the death count when the deaths count is not defined

My problem is that if the first date of a county is not defined, it receives the deaths count from the previous county which is was not expected because I'm using the name of the county to create group (see the screen shot, that clarify my point)

I think this is an issue, but maybe I have didn't not understood the function?

**Comment by jheer** [comment]
Thanks! Looks like this is indeed a bug where the window operator state is not being property re-initialized between groupby partitions. Will try to fix soon!
