### ISSUE TITLE
resolve transform return full table

### ISSUE THREAD

**Issue by mathiastiberghien** [vega/vega#2479]
Trying to fix the problem reported in #2460 (I hadn't configured correctly the signal reference in resolveFilter)
I have this new issue as you can see [here](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYALAAYdiiJBSNq+bXoNRYJmegA2sbAG0lEUBA9RbqZNkgAndBlqZAB9TEtPSAp7Vl8sJ30ARgBdVzAAX0iwd08vdB8-QOCw9gV0wxi7OOck+QAmNM8s9Nyo73iAoJDQ+HK8qCqahPr5USaPDKUUy0g1dDxMBNaK-MKsSEX2O19sytjkRwTgSCX9SDKsfSg+q-k1zuQdnxk8UKTILJOz+QvsOpu-3ukA6fieaGQr1C9U+8m+QL+WFGgKRwNBG3BLzeAGZYfDUYjscDbkSHmDnpC3lo8adsETEVpido0QVHhSoaIaUtGQymVhRCz1pBMZTQgA2T4zVabYqwABm3H8qGcqzcqo8mwAnoROvB-NxYPLGHY8Mh-P0Bhq5Ywnmojk5ab8yr8+lLLRqAI5xfyalXuzxtf2GazUWx2IrdMKYdXNPaWwNByAhsMRkqhMoxyZxgYJ-1Jmz2VM9PqZiBTINuvPJws4SAAD1C1pNZsg6vLeQmZeyuZBrL8bwi0ukrH88E6Wx2FqieFlCqV2DALnduen2s6-kO3DsVCbpvN2atxr32BO1fDGwbu5bLUTNkV8TFbdWncy3el6M26anGuHo-H6G2XZpRnIJ5UVZUcCXeNMy1HUik3bdkCvfcYOQk981DGt60bI9rwPQw7w3bBRCfAYXxvDwew-N4+jjJNuBHMd+wAyc6JAmQwPnSD1RXDU8DXeDpEQtD8KgNCsFPAtz2wtCKPdSBCPibFSI7dJ2zSDIgA)

The resolve filter seems to be configured correctly now for tables `table_a`, `table_b`, `table_c`
Ignore mask being 6 for `table_a`, I expected that it will filter only the field a and as my range for `a ` is configured as [0,1], I expected to have only the rows where field `a` is equal to 0
Ignore mask being 5 for `table_b`, I expected that it will filter only the field b and as my range for `b` is configured as [1,2], I expected to have only the row where field `b` is equal to 1.
for `table_c`, I expected that rows are filtered on field `c` using the range [2,5] which give me the rows where `c` is equal to 2,3 or 4

Instead of that, all the tables are showing all the values.
I tried to change the ignore number and when the value is equal to the value of the mask of x_filter signal the table return empty (I expected that ignoring all the fields it will returned all the table)

Am I still missing something?

**Comment by jheer** [comment]
The resolvefilter transform expects to feed results into a downstream transforms, typically an aggregate. There may be a bug when feeding output directly (I'll have to check later). In the meantime, [if I add aggregate consumers to the resolve transforms](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYALAAYdiiJBSNq+bXoNRYJmegA2sbAG0lEUBA9RbqZNkgAndBlqZAB9TEtPSAp7Vl8sJ30ARgBdVzAAX0iwd08vdB8-QOCw9gV0wxi7OOck+QAmNM8s9Nyo73iAoJDQ+HK8qCqahPr5USaPDKUUy0g1dDxMBNaK-MKsSEX2O19sytjkRwTgSCX9SDKsfSg+q-k1zuQdnxk8UKTILJOz+QvsOpu-3ukA6fieaGQr1C9U+8m+QL+WFGgKRwNBG3BLzeAGZYfDUYjscDbkSHmDnpC3lo8adsETEVpido0QVHhSoaIaUtGQymVhRCz1pBMZTQgA2T4zVabYqwABm3H8qGcqzcqo8mwAnoROvB-NxYPLGHY8Mh-P0Bhq5Ywnmojk5ab8yr8+lLLRqAI5xfyalXuzxtf2GazUWx2IrdMKYdXNPaWwNByAhsMRkqhMoxyZxgYJ-1Jmz2VM9PqZiBTINuvPJws4SAAD1C1pNZsg6vLeQmZeyuZBrL8bwi0ukrH88E6Wx2FqieFlCqV2DALnduen2s6-kO3DsVCbpvN2atxr32BO1fDGwbu5bLUTNkV8TFbYPK41eDXC9O1GoG9opqnlsgbhiAXB01EYWA8EYGR4DwBQbm4VhXkgSt3Uga1bSORdHTAGRWDsOxOzydtPEIm8PB7dFNnTf9gwQ0dx3QbZdmlGcgnlRVlRwJd40zLUdSKTdt2QK9914kST3zUMa3rRsj2vA9DDvDdsFEJ91RfQw3342t0C-H8FmYxMgMw0DwMg6DYOJBCkJQgD0LsO0QL+e5cPwwjmlWUju2lSi3j6OMkzosd+0YycAtYmR2PnLj1N4rT10Enc5NExNxKwU8C3PGTxLI1ClPibE1OXOL3x0vThD-BSoGMpywIgqCYLgyB4Gs2DbIGNCbQckzmrg1yCLbTz0nbNIMiAA) it looks like the proper filtering is happening.

**Comment by jheer** [comment]
Took another look at this. The `resolvefilter` should always be followed by a consuming transform. If all you want is the original tuples, put a `collect` transform after `resolvefilter`. I will add a note to the transform documentation.
