### ISSUE TITLE
Vega bindings are not semantic HTML

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2490]
For example in https://vega.github.io/vega/examples/pie-chart/

<img width="365" alt="Screen Shot 2020-03-30 at 14 36 15" src="https://user-images.githubusercontent.com/589034/77964379-d0610680-7293-11ea-930e-dda29bd057f6.png">

* The labels are not associated with the form elements (e.g. the checkbox or the slider)
* The label for sliders are showing the values. I believe [labels](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) should be the description, not the value. 
* We could also improve accessibility here and mark the values as hidden since they are already accessible via the slider.

**Comment by roying** [comment]
Please include unique _id_ for each _input_ element so that it can be accessed easily from javascript outside of Vega. Thanks.

**Comment by domoritz** [comment]
That's a separate request, right?

**Comment by roying** [comment]
Example from
       https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label
This syntax includes property **_id_**:
```
<div class="preference">
    <label for="peas">Do you like peas?</label>
    <input type="checkbox" name="peas" id="peas">
</div>
```
whereas this does not:
```
<label>Do you like peas?
  <input type="checkbox" name="peas">
</label>
```

**Comment by domoritz** [comment]
Which is why I personally prefer the latter ;-)
