### ISSUE TITLE
Automatically add aria-role group so screenreader users can skip over large umbers of marks

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2492]
Follow up for https://github.com/vega/vega/pull/2380. 

For example in https://vega.github.io/vega/examples/contour-plot/, it would be great to be able to skip over the points.

**Comment by jheer** [comment]
Related support added in #2548. I believe this concern in covered by the more recent ARIA attribute generation scheme?

**Comment by domoritz** [comment]
Yes, it does. I like that the new ARIA scheme summarizes mark groups into one. However, it currently also prevents screen readers from accessing children. 

I think what we may want is to summarize marks when individual marks don't define aria properties but otherwise still set mark-level properties. Let's continue the discussion in https://github.com/vega/vega/pull/2548.
