### ISSUE TITLE
Wordcloud renders differently in SVG and Canvas in Safari

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2493]
Maybe this is okay. I'm filing this just in case this hints at some issue. 

SVG

<img width="799" alt="Screen Shot 2020-03-30 at 15 06 55" src="https://user-images.githubusercontent.com/589034/77966560-23d55380-7298-11ea-9655-d1722c239475.png">

Canvas 

<img width="798" alt="Screen Shot 2020-03-30 at 15 07 01" src="https://user-images.githubusercontent.com/589034/77966542-1cae4580-7298-11ea-8863-5f2ace621148.png">

![2020-03-30 15-07-49 2020-03-30 15_08_31](https://user-images.githubusercontent.com/589034/77966734-7747a180-7298-11ea-91f1-a90b8f529cfa.gif)

**Comment by jheer** [comment]
I am unable to replicate on Mac OS in the current editor with either Chrome or Firefox. Only Safari displays the problematic behavior, which leads me to suspect it is a Safari bug. Fortunately the difference is small enough that I'm not too concerned, though it would be nice to know why Safari behaves differently.
