### ISSUE TITLE
Add automatic aria labels for marks

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2494]
Follow up for #2380.

It would be great if we could automatically annotate marks with appropriate aria labels. It would be nice if we could describe the data before scales are applied ("circle representing Europe with horsepower 12 and 4 cylinders").

**Comment by jheer** [comment]
Related support added in #2548. Mark item-level aria attributes can be defined using encoding channels.

**Comment by domoritz** [comment]
Not yet. The intention of this issue is to provide default mark-level aria-labels that describe individual marks without the need for explicit descriptions via encoding channels. I can understand if we don't want to do this at all since Vega charts often have marks that would just clutter the screenreader experience.
