### ISSUE TITLE
Calculating and referring to MAX in a visualization

### ISSUE THREAD

**Issue by kuhailamin** [vega/vega#2517]
Dear all,
I'm trying to construct a simple visualization that shows temperature in a given city using a bubble plot. I want to show the max temperature in black, temperatures greater than 20 in red, and the rest in orange. I was able to do almost all of that, except for showing the max in black. I looked into so many tutorials but without success. I'd really appreciate your help. Here are the vis specifications:

{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "An interactive line chart of stock prices, with returns shown relative to a selected date.",
  "width": 650,
  "height": 300,
  "padding": 5,
  "autosize": {"type": "fit", "contains": "padding"},
  "data": [
    {
      "name": "temperature",
      "url": "data.csv",
      "format": {"type": "csv", "parse": {"temperature":"number", "date":"date"}}
    }],
    "scales": [
    {
      "name": "x",
      "type": "time",
      "domain": {"data": "temperature", "field": "date"},
      "range": "width"
    },
    {
      "name": "y",
      "type": "linear",
      "domain": {"data": "temperature", "field": "temperature"},
      "range": "height"
    }
  ],

  "axes": [
    {"orient": "left", "scale": "y"},
    {"orient": "bottom", "scale": "x"}
  ],
    "marks": [
{
      "name": "marks",
      "type": "symbol",
      "from": {"data": "temperature"},
      "encode": {
        "enter": {
          "x": {"scale": "x", "field": "date"},
          "y": {"scale": "y", "field": "temperature"},
          "shape": {"value": "circle"},
          "fill": {"signal": "datum['temperature'] == 25? 'black': datum['temperature'] > 20 ? 'red' : 'orange'"}
      }
        }
      }
    
      ]

}

**Comment by jheer** [comment]
Your approach of encoding the color in a signal expression should work, so long as you don't care about having a legend. (If you do want a legend, you'll want to create a scale with appropriate domain and range for your data and colors, and use that to populate a legend.)

It looks like the primary issue is that you want to support a dynamic choice of maximum value for the black color. To achieve that, you could add a [`joinaggregate` transform](https://vega.github.io/vega/docs/transforms/joinaggregate/) that computes the max value and writes it back to your data (for example, to a new field named `"max"`). Then you can check for the max value in your `fill` signal expression using something like `datum['temperature'] === datum['max'] ? 'black' : ...`.

**Comment by kuhailamin** [comment]
Thanks for the reply. Much appreciated. I tried to implement your suggestion, but unfortunately it didn't work. The visualization wouldn't run. Here are the specs:

{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "An interactive line chart of stock prices, with returns shown relative to a selected date.",
  "width": 650,
  "height": 300,
  "padding": 5,
  "autosize": {"type": "fit", "contains": "padding"},
  "data": [
    {
      "name": "temperature",
      "url": "data.csv",
      "format": {"type": "csv", "parse": {"temperature":"number", "date":"date"}}
            ,

"transform": 

{ "type": "joinaggregate",

"fields": ["temperature"],

"ops": [ "max"],

"as": [ "max_temp"]

}
    }

    ],
    "scales": [
    {
      "name": "x",
      "type": "time",
      "domain": {"data": "temperature", "field": "date"},
      "range": "width"
    },
    {
      "name": "y",
      "type": "linear",
      "domain": {"data": "temperature", "field": "temperature"},
      "range": "height"
    }
  ],

  "axes": [
    {"orient": "left", "scale": "y"},
    {"orient": "bottom", "scale": "x"}
  ],
    "marks": [
{
      "name": "marks",
      "type": "symbol",
      "from": {"data": "temperature"},
      "encode": {
        "enter": {
          "x": {"scale": "x", "field": "date"},
          "y": {"scale": "y", "field": "temperature"},
          "shape": {"value": "circle"},
          "fill": {"signal": "datum['temperature'] == datum['max_temp']? 'black': datum['temperature'] > 20 ? 'red' : 'orange'"}
      }
        }
      }
    
      ]

}

**Comment by jheer** [comment]
Transforms must be provided in an array. Please refer to the documentation and examples. For usage / debugging questions please use Slack, StackOverflow, or the mailing list (see the links on the Vega homepage).

**Comment by kuhailamin** [comment]
Thanks for your feedback. I got it fixed. Apologies for using the wrong place.  A quick thing, it would have been nice if Vega compiler gave me an error message saying that transforms must be specified in an array. 

For the benefit of others, I want to show the solution that works correctly now:

{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "An interactive line chart of stock prices, with returns shown relative to a selected date.",
  "width": 650,
  "height": 300,
  "padding": 5,
  "autosize": {"type": "fit", "contains": "padding"},
  "data": [
    {
      "name": "temperature",
      "url": "data.csv",
      "format": {"type": "csv", "parse": {"temperature":"number", "date":"date"}}
            ,

**"transform": [

{ "type": "joinaggregate",

"fields": ["temperature"],

"ops": [ "max"],

"as": [ "max_temp"]

}]**
    }

    ],
    "scales": [
    {
      "name": "x",
      "type": "time",
      "domain": {"data": "temperature", "field": "date"},
      "range": "width"
    },
    {
      "name": "y",
      "type": "linear",
      "domain": {"data": "temperature", "field": "temperature"},
      "range": "height"
    }
  ],

  "axes": [
    {"orient": "left", "scale": "y"},
    {"orient": "bottom", "scale": "x"}
  ],
    "marks": [
{
      "name": "marks",
      "type": "symbol",
      "from": {"data": "temperature"},
      "encode": {
        "enter": {
          "x": {"scale": "x", "field": "date"},
          "y": {"scale": "y", "field": "temperature"},
          "shape": {"value": "circle"},
          "fill": {"signal": "datum['temperature'] == datum['max_temp']? 'black': datum['temperature'] > 20 ? 'red' : 'orange'"}
      }
        }
      }
    
      ]

}
