### ISSUE TITLE
Custom formatting with locale not inherited as default for tooltips

### ISSUE THREAD

**Issue by EE2dev** [vega/vega#2519]
When a custom Locale is specified for time/ numbers (e.g. to use different thousands and decimal separator) it is applied to the axes but not by default to the tooltip.

See: https://observablehq.com/@ee2dev/vega-lite-custom-formatting-with-locale

**Comment by jheer** [comment]
For better or worse, by default Vega does not provide any special formatting (for any locale!) for tooltips. The tooltip channel does not know about axes or legends (which may or may not exist), and which in some cases might be usefully formatted in a different way. So what you're seeing is most likely the results of JavaScript string coercion on the input values. One option is to instead include desired formatting yourself in the tooltip definition. In Vega you can do this using the [Vega expression language](https://vega.github.io/vega/docs/expressions/#format-functions) (e.g., `format`, `timeFormat`, `utcFormat`).

Vega-Lite, on the other hand, could make more nuanced decisions here as the compiler can reason about the Vega spec it is generating. If there is something Vega-Lite can do better, please file an issue at https://github.com/vega/vega-lite
