### ISSUE TITLE
"Triggers" are not compatible with "derived" tables

### ISSUE THREAD

**Issue by na3imk** [vega/vega#2520]
Hello,
I don't know if this is the intended behavior, but I cannot use "triggers" with a derived table.

When doing so, the chart is not rendered. Please have a look [here](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAgmHbpYjeMfTqwSK3jDIAHulSEANsnlgA7s0RgKdDdWZDA3dHZkN1gwWERubxkwVkJZMFRuVlhQ+Kp1OgUlSF9lFmwwABYABirFCEgURmp8coAmGrqoQnRlZUYZanLRRSLldDxMHABtJQhQCAWoGRdkcsgJ9g9CxfrA4LVymZ2F4Eh4cZpudQBPNYMFKBdMmTw2gA4AX07j0-O8S5uawAQg9IE9WC8hqIvrMdr8LtQrrd9ABhUHgyE4CoAZhhxzmZwRSLWABF0RkIa8cABOACMePx8P+iMB+gAouTnlSwG96d84YTmcT9AAxTmUoa4-mLJkA5FQADi4sxYFp1IZP0FcrWAAlldy3gB2D6wiAAXWlUDw6nQMlgADMrqhDqb8TLXYt1tdCKt9PbGG5-uptm6oE5CMH9GM8KxUFMAOQYvDxs1gAB8YGxVUgHrAJuOFtdkFkLrdp2tTWoyEjUHgHisoPUaG4VDWdeQDfzOzNsJhsPmO0gy1QqzA+g2HlaIc90lY6ngvqtES2luLejAR0Z6001CrNbO9eDXkgTYyrf07c7rp7vaUhaKZmoy2ipZOReHi-W3G4ga004WkB7CE5TABqAEltMuanMgVAvLAaxNvAeBYBS2QttWoIpNGn7RrGkBgTKkAwcgcEIcgSEoZkaGsK8XhQFhFxrKB+HXr2lpzO+Kxtoe-67EEwE4KBq4QRuUFEbBeDwfoiHIXW5gANaYYQ2FrLhzoESc4kkZJZEUahyCZLR9QMf8TEfCxBa3uaIz1AgQQHJB7rHEOXH6I4dkrkWeDep+JgyMovEqNwGD9CBkDRpMS6bKsx7+lEAUXkSgIaSetpVmsJRlKu3S9P0gw4FUdBVMMRbqM8CVgNaIRsf2nEjms1weTFRbKMF6ChYJ4XjJF6zLjFUBxW4FVghSkIpTI5iLlVnilWln6NM0rxWWA971OgjgOaJMpQFcjDaWs7DcAQwWgk1azuecWx5vywA7Zo+36B49pGZAZ36I1l2jl2q1QBg6jyVJW1vs53k+rptFFvaZXOp1EXYL10X4auJHwNwqggbmREvBhgm5vUjhhW9UAXfZoKDcNfzahpnqZYghOfedZ3Hn5FV8njUDyqcROQB9pOxXtQ1rEmSPszzU6ddzvMrlAQGLlUXbHNT9HKYxuOhgNAZuGFstrLA-xRJswEKzsSsNOhNYDm6kD+m4WudTr0nIAFxuLC7eY1WWXk+eDgXW9DYVw1gCNbClKNo4uluDtpONgJHzkExLDNuUzGvxW2SW3Er9S0-TpPJwzzO2qzWcc7nWzvSn1sC8Nwsl2LZeflL-WAfxctuxApsmRHos23bsct-sZHO7mpu5DHceDr32ut0PFn4m7xtgRPXpg+OTgQ85Yfo2r+JY0GGPq2CbhNOupwO7W0fBnXJjZMfMgRwPAlQIdx3qexAFT-bM-6AAxNi-9z0Vu-SAXcD6hkgAnfu3MSbS1eifIIaw8Dfl-IQOglMWS3ELv5cohVoTv3qJzV6ScOaV0fM+RByCdCoOFsebg9p7TZG5AAWlaHXf4jhuRc3gX3L8P4qF0FrvgjWtsADy3R4DMHlJudW5Y1Dci6jGVAYAAC8qjKqUL-Mec+8shEEnPvSdmPY3QL2Wj2E0QA).

If you remove the following piece of code, it renders the chart : 

`    {
      "name" : "table2",
      "source": "table",
      "on": [
        {"trigger": "clear", "remove": "clear"}
      ]
 }`

Again maybe, this is forbidden but I couldn't see anything mentionned in the documentation ([here](https://vega.github.io/vega/docs/data/) and [here](https://vega.github.io/vega/docs/triggers/) )

**Comment by jheer** [comment]
Thanks for the issue. Triggers modify the contents of a table, but are not applicable to a derived table whose content depends on the upstream tables. To prevent triggers and derived flows from competing which each other, triggers are not applicable to derived sets. I will update the documentation to reflect this.

**Comment by jheer** [comment]
Fixed in a6cf2ff.

**Comment by na3imk** [comment]
Thanks!
