### ISSUE TITLE
Allow supplying your own node-canvas to render to

### ISSUE THREAD

**Issue by pixelspark** [vega/vega#2547]
Dear all!

Love your work on Vega. It's been a delight to work with so far. We are embedding Vega in our online tool for making data-driven infographics (see an example here: https://diasli.de/3367/SLafyLSGqP/HHynjfHRN1hcsBp8EoCHy9). 

For this we would like to generate PDF's server side of pages that embed Vega charts. Vega can render to PDF without issue, but node-canvas does not allow compositing multiple canvases into one PDF without loss of quality. What we currently do is render the Vega chart, then get its canvas, then render the chart to the main page using `pageContext.drawImage(vegaCanvas, ...)`. This unfortunately draws the Vega chart as a bitmap to the PDF.

It would be nice if it were possible to tell Vega to draw to a specific canvas (using transforms you can then place the chart on your page). This should allow high-quality (vector) embedding of Vega charts into PDF documents.

Suggested API is to allow calling `toCanvas` with a single `context` parameter (which is a node-canvas 2d context). The chart is then simply drawn at 0x0 to the desired width and height configured for the view:

````
const view = new vega.View(...., {renderer: "none"}).width(desiredWidth).height(desiredHeight);
const canvas = (some canvas we are re-using)
const context = canvas.getContext("2d");
context.save();
context.translate(100,100); // I want the chart at 100,100 in my document
await view.toCanvas(context);
context.restore();
````

Would be happy to implement this myself, but will need some pointers on where to begin!

**Comment by jheer** [comment]
Vega does have existing server-side PDF rendering support through node-canvas. For example, see:
- https://github.com/vega/vega/blob/master/packages/vega-cli/bin/vg2pdf#L11
- Here we pass the following options: `{type: 'pdf', context: {textDrawingMode: 'glyph'}}`

Is it possible for you to invoke that, get the generated canvas/PDF, and use that subsequently? Or do you definitely need to render into an existing canvas?

If the answer is "yes", the code path to follow is:
- View.toCanvas: https://github.com/vega/vega/blob/master/packages/vega-view/src/render-to-canvas.js#L10
- View.renderHeadless: https://github.com/vega/vega/blob/master/packages/vega-view/src/render-headless.js#L17
- View.initializeRenderer: https://github.com/vega/vega/blob/master/packages/vega-view/src/initialize-renderer.js#L6
- CanvasRenderer.initialize: https://github.com/vega/vega/blob/master/packages/vega-scenegraph/src/CanvasRenderer.js#L21
- CanvasRenderer.resize: https://github.com/vega/vega/blob/master/packages/vega-scenegraph/src/CanvasRenderer.js#L35
- resize: https://github.com/vega/vega/blob/master/packages/vega-scenegraph/src/util/canvas/resize.js

I could imagine passing in an existing canvas instance as part of the options argument to `toCanvas`, which could then get passed down into vega-scenegraph's CanvasRenderer. The tricky bit is to then handle the canvas appropriately. The CanvasRenderer currently modifies the canvas size and transform.

**Comment by pixelspark** [comment]
@jheer Yes, I know Vega is capable of rendering to PDF. The point is that there is no way to draw that output into some other canvas without quality loss (i.e. the PDF gets rasterized then drawn; what you really want is for the drawing operations to be made to the target canvas, so it too can output nice and sharp vector PDFs). Working from the canvas Vega creates does not work for us because we want to potentially have multiple Vega charts on the same page.

I believe handling the canvas's transform is pretty easy - we'd just call `ctx.save()` before handing off the context to Vega and then `ctx.restore()` afterwards. Again, I think it would be best to send Vega a context rather than a canvas. 

That said I will look into the code and see what I can do (need to set up the environment for compiling Vega first..)

**Comment by jheer** [comment]
Added in #2575
