### ISSUE TITLE
timeFormatLocale cannot be changed

### ISSUE THREAD

**Issue by marcprux** [vega/vega#2567]
This chart uses the (default) en-US localization for numbers and dates:

<img width="354" alt="Screen Shot 2020-04-27 at 15 29 35" src="https://user-images.githubusercontent.com/659086/80412459-e9150a00-889b-11ea-801e-2ce6a6e2db94.png">

It is generated from:

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "A hypothetical outcome plot that uses animated samples to convey uncertainty.",
  "width": 300,
  "height": 200,
  "data": [
    {
      "name": "steps",
      "transform": [
        {
          "type": "sequence",
          "start": 0, "stop": 12, "step": 1
        },
        {
          "type": "formula", "as": "month",
          "expr": "timeFormat(datetime(2015, datum.data, 1), '%b')"
        },
        {
          "type": "formula", "as": "value",
          "expr": "datum.data * 100"
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "xscale", "type": "band",
      "domain": {"data": "steps", "field": "month"},
      "range": "width"
    },
    {
      "name": "yscale", "type": "linear",
      "domain": [0, 2002],
      "range": "height"
    }
  ],
  "axes": [
    {"orient": "left", "scale": "yscale"},
    {"orient": "bottom", "scale": "xscale"}
  ],

  "marks": [
    {
      "type": "rect",
      "from": {"data": "steps"},
      "encode":{
        "enter": {
          "x": {"scale": "xscale", "field": "month"},
          "width": {"scale": "xscale", "band": 1, "offset": -1},
          "fill": {"value": "steelblue"}
        },
        "update": {
          "y": {"scale": "yscale", "field": "value"},
          "y2": {"scale": "yscale", "value": 0}
        }
      }
    }
  ]
}
```

Once rendered, we can change the number format to French. In the vega editor, this is done by running the following in the console:

```javascript
VEGA_DEBUG.vega.formatLocale({
  "decimal": ",",
  "thousands": "\u00a0",
  "grouping": [3],
  "currency": ["", "\u00a0€"],
  "percent": "\u202f%" 
});
```

Then after re-rendering (e.g., by making a trivial change to the spec), we see the new number format is being displayed:

<img width="352" alt="Screen Shot 2020-04-27 at 15 32 36" src="https://user-images.githubusercontent.com/659086/80412764-54f77280-889c-11ea-9062-875a308850a5.png">

However, if we try to do the same thing with the `timeFormatLocale`:

```javascript
VEGA_DEBUG.vega.timeFormatLocale({
  "dateTime": "%A, le %e %B %Y, %X",
  "date": "%d/%m/%Y",
  "time": "%H:%M:%S",
  "periods": ["AM", "PM"],
  "days": ["dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"],
  "shortDays": ["dim.", "lun.", "mar.", "mer.", "jeu.", "ven.", "sam."],
  "months": ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"],
  "shortMonths": ["janv.", "févr.", "mars", "avr.", "mai", "juin", "juil.", "août", "sept.", "oct.", "nov.", "déc."]
});
```

The chart is not re-rendered with the new locale's `shortMonths`.

Note that if the above script is run in a new editor **before** anything is rendered (i.e., with an empty spec), then the `timeFormatLocale` is used correctly.

<img width="353" alt="Screen Shot 2020-04-27 at 15 37 39" src="https://user-images.githubusercontent.com/659086/80413179-0a2a2a80-889d-11ea-973b-4ca34c437b7e.png">

 But once a render has occurred, changes to `timeFormatLocale` will not ever be used.

**Comment by marcprux** [comment]
I've tested this in both Safari and Firefox, so it doesn't seem to be a browser-specific issue.

**Comment by marcprux** [comment]
Probably related: https://github.com/vega/vega/issues/2461#issuecomment-601363657

**Comment by marcprux** [comment]
Manually executing the `timeFormat` function does seem to see the changes. I.e., the following will correctly print "mer." then "Wed":

```javascript
VEGA_DEBUG.vega.timeFormatLocale({
  "dateTime": "%A, le %e %B %Y, %X",
  "date": "%d/%m/%Y",
  "time": "%H:%M:%S",
  "periods": ["AM", "PM"],
  "days": ["dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"],
  "shortDays": ["dim.", "lun.", "mar.", "mer.", "jeu.", "ven.", "sam."],
  "months": ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"],
  "shortMonths": ["janv.", "févr.", "mars", "avr.", "mai", "juin", "juil.", "août", "sept.", "oct.", "nov.", "déc."]
});

console.log(VEGA_DEBUG.vega.timeFormat("%a")(new Date(0)));

VEGA_DEBUG.vega.timeFormatLocale({
  "dateTime": "%x, %X",
  "date": "%-m/%-d/%Y",
  "time": "%-I:%M:%S %p",
  "periods": ["AM", "PM"],
  "days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  "shortDays": ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
  "shortMonths": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
});

console.log(VEGA_DEBUG.vega.timeFormat("%a")(new Date(0)));

```

**Comment by marcprux** [comment]
The problem seems to stem from the `formatCache`. If I manually clear this cache when applying a new locale, the problem goes away (although I don't know why this only affects time formats and not number formats). One possible solution could be to include the locale settings as part of the cache key, but the easiest solution is probably just to clear the cache as a side-effect of changing the `timeFormatLocale` (which would mean we would need to make our own implementation rather than just re-exporting it: `export {formatDefaultLocale as formatLocale} from 'd3-format';`).

**Comment by jheer** [comment]
Thanks for the issue. Currently Vega “expects” you to set the locale prior to parsing any specs. I plan to revisit the format caches and locale handling soon, hopefully in v5.12.

**Comment by marcprux** [comment]
Understood. I guess it is confusing because you *can* change the number locale between parsing specs and the different number formats show up correctly (although I'm not sure why, since it seems to use the same caching mechanism), so it is confusing that changing the time locale doesn't have the same effect.

**Comment by jheer** [comment]
Yes, that does seem strange. Axis formatting can arise without hitting that cache as well (the cache is only applied to expression function use), which may explain the discrepancy. Again, I plan to revisit and streamline the formatting subsystem in an upcoming release.
