### ISSUE TITLE
Legend isn't visible with orient:right but works on left or with autosize:pad

### ISSUE THREAD

**Issue by rwoollen** [vega/vega#2568]
The legend isn't visible in the attached spec.  It's actually rendered but translated beyond the chart bounds.

Using autosize:pad works as does changing the legend to orient on the left.
Finally it appears to be related to the nested group marks.  If I have only 1 group mark, it also works.

I was wondering if this is related: https://github.com/vega/vega/blob/master/packages/vega-view-transforms/src/ViewLayout.js#L109
 
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KABNkCAE6NCeHnJyQAgmHbpYjeGFh508ANbJlYdOuTowSZ3jDIAHulSEADbIdApKkADujMos2GCiAAwJihCQKIzU+HEATEkpUOiseNxmAF7IccCQeACehBX6AGbMClDwstaMMrBxkIToyspd1JAAvvl9A0MyIziiE8HUyDLKPTgA2koQoBC7UNyay3i9mpnH+XuQzYGBve2BB5BbYKNKALoTyujWcZt7O3soDJ-A0oNZ2MEwoCoBR0IFWGpfs9-pAfHFklAajkABzyNrovGQZTo8bI3ZVNE4DGQLFzeb4nAARkJxKppOh21RcWZmLiABYAMyE+AElTc9kcincwm0sAATh5kBFTJZ4ougKlOGyMri2MVyrA1NZhol0M1YG1vLmQoZYEVxoSpo1XJwNpp3LlwtFRLVZM5lLAbtl2IA7F6VWKmU6UQG+Tq5pald6HdHyS6wHGrRncbb7ST1TG4vT3VrM0mqaqowW0wHi7K+Z7c5W7an-XEAGzxsCh8OG5uO6ttnCdrPtkflu391tgc1hrOMucTo2+jkz9OL2XZRcGvNVv1rgM5ktgdtHg3LtmDg+6ruM8c7qdX82N48N3sXltP9Mv2WM4sPyMWzJD4yWqdR0G6RoDlQJFVwBVdqjqUFICsGxbChVcoGodRuFYQh2FldYuRAzCoGkdRjhwKpmmQQJjSTadUhoujeixfdXmhN5ng4sASLI+A4URDZnng3ZIGBVBkLRatEPqXpCG4LpzlA8CZmQqIYkQDDLmUbgMC6SoiW+TB9HBSFCWY+i0R4iAnVE1IJOQrEZNqOT9ECLpXHUbSxNUpZenSM4fIc8xQTwdQERk8ocLicLItA3T9L0Ncvh+Uz0AhCoLMYWj6JqRkxm49V7KBEE7m4B5vJcpDegOaY4WCqA-OQgS8BoA5nISvT0AMqijLSsEMvMqBLLuQq9h4vjIHQHwhLAP40wOHKZEoqB2G4Ag9NaFCBMhfRpKgUoulUANGTsyAlqOXpgkac5+ME1jtqOlZfHFd4JgwdRbDWeaRNA1zkOw3DCEaq4cJgvrGhsZBVqqRzelgZBDh6FljN6MysqwnC8IIsbRlTSBPu+2DJX3VIAd6IG8May5GnByoybEqH4Bhwz4f0LoZCRgB9RHke21KTMGzLtqp-DZR9GyOUYqAiZ+hbSJKhCKf0ZxXBpjkwa2vrBYRpGcp6GXLmWdpVAZ0joUgI4kfNi3LaUpGFMCb5QSqWF4WQ1BZA22QKiNzWAyqBAHv27bRtD-3LdlIPdqcsOcpY-QagSMYr1ImlskM4O9t5bLctYgrI8BK5GBuLPY-Kyr4-z-QRSlu368wxvoWb3YuNXRv292SaQFeIA)

**Comment by jheer** [comment]
Hmm. At first glance it looks like the layout calculation might be OK, but the legend placement may be incorrect. We will need to investigate what is different in this nested group mark case. The line you highlighted shouldn't be the culprit, as it does adjust the left-right bounds for a right-oriented legend -- but we'll see... Thanks for the issue!
