### ISSUE TITLE
does vega automatically trim space from axis labels ?

### ISSUE THREAD

**Issue by g3o2** [vega/vega#2569]
For some reason, any space padding added via the expression function `pad()` appears to be trimmed by vega, at least for axis labels. With any other character used for padding instead, there is no trimming.

_For purposes of non-verbosity, you will find here below the vega-lite specs instead of the vega specs but with links to the Editor._

Here below a vega-lite [example with the space character used for padding](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckACoowhXd02t4R5WHatN1ZHjDcAZmBbIwVG4KRgCWdE9EdFg-S0RGahRYTwBVAGUwAHEbWBjGJTBkdCRA9DluXTB3JV1kOjUNSE0IzBxgSFZdMWwtFtIgkJ15RRUAX3UISAxdAGseyHZ0XQbJvF10JVhvCtQegG0NCHb4dDF4VjEI5HnCdE0ACma8VlQ6AFkyioB9TOQa5FUYAAzAAGQEAcjA4IhYmQ3jw4IAlGooNF5h9yrofn9apBRhoALoTKB-eC2fLUHqgCCTAAeVMg6Go1FqtDw1zajN01Aw9NM6R+OVgeMBkG8oTEmnmAAUbHYHMYvgAhVzuPAoyB4ACehA5UAAjqwNkY8BFGFQRYcoFqGeLkJL0Z8sb9-hrtbr5kpuKh8qc8Rp8aMgA):

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "The production budget of the movie that has the highest US Gross in each major genre.",
  "data": {"url": "data/movies.json"},
  "mark": "bar",
  "transform": [
    {"calculate": "pad(datum.Major_Genre, 30, ' ', 'left')", "as": "Major_Genre"}
  ],
  "encoding": {
    "x": {"aggregate": {"argmax": "US_Gross"}, "field": "Production_Budget", "type": "quantitative"},
    "y": {"field": "Major_Genre", "type": "nominal"}
  }
}
```

![image](https://user-images.githubusercontent.com/12123506/80455502-26c17380-892c-11ea-89c9-bdc66028f633.png)

Here below [another example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckACoowhXd02t4R5WHatN1ZHjDcAZmBbIwVG4KRgCWdE9EdFg-S0RGahRYTwBVAGUwAHEbWBjGJTBkdCRA9DluXTB3JV1kOjUNSE0IzBxgSFZdMWwtFtIgkJ15RRUAX3UISAxdAGseyHZ0XQbJvF10JVhvCtQegG0NCHb4dDF4VjEI5HnCdE0ACma8VlQ6AFkyioB9TOQa5FUYAAzAAGQEAcgAVOCIWJkN48OCAJRqKDReYfcq6H5-WqQUYaAC6Eygf3gtny1B6oAgkwAHtTIOhqNRarQ8Nc2kzdNQMAzTOkfjlYPjAZBvKExJp5gAFGx2BzGL4AIVc7jwqMgeAAnoROVAAI6sDZGPARRhUUWHKDaxkS5BSjGfbG-f6anV6+ZKbiofKnfEaAmjIA) using the `*` character instead of space for padding:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "The production budget of the movie that has the highest US Gross in each major genre.",
  "data": {"url": "data/movies.json"},
  "mark": "bar",
  "transform": [
    {"calculate": "pad(datum.Major_Genre, 30, '*', 'left')", "as": "Major_Genre"}
  ],
  "encoding": {
    "x": {"aggregate": {"argmax": "US_Gross"}, "field": "Production_Budget", "type": "quantitative"},
    "y": {"field": "Major_Genre", "type": "nominal"}
  }
}
```

![image](https://user-images.githubusercontent.com/12123506/80455588-54a6b800-892c-11ea-9680-98fbbb3197b3.png)

**Comment by jheer** [comment]
Yes. See https://github.com/vega/vega/blob/master/packages/vega-scenegraph/src/util/text.js#L73

We realized recently that SVG performs trimming anyway. So we made the trim explicit in more recent versions to ensure consistent output between SVG and Canvas.

**Comment by tmori3y2** [comment]
I tried to increase the space between words to avoid overlapping characters and lines when the text mark and line intersect. But I couldn't avoid it because of this issue.

If you set xml:space="preserve" in svg//text, you do not need to trim with canvas.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:space

The reason for trying to adjust the position by increasing the space between words is that the cost of splitting the text marks is high. I would like you to be able to select the option of "no trim".

**Comment by tmori3y2** [comment]
> The reason for trying to adjust the position by increasing the space between words is that the cost of splitting the text marks is high. I would like you to be able to select the option of "no trim".

Should I create a feature request issue?

**Comment by tmori3y2** [comment]
I found #2418, so I will link to it
