### ISSUE TITLE
The order of labels should not affect label overlap

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2579]
When setting explicit values on an axis, I would expect that the order does not affect whether label overlap prevention works or not. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/movies.json"},
  "width": 400,
  "height": 100,
  "transform": [{"density": "IMDB_Rating", "bandwidth": 0.3}],
  "mark": "area",
  "encoding": {
    "x": {
      "field": "value",
      "title": "IMDB Rating",
      "type": "quantitative",
      "axis": {"values": [6.9, 1, 7], "labelOverlap": true, "labelFontSize": 20}
    },
    "y": {"field": "density", "type": "quantitative"}
  }
}
```

![image](https://user-images.githubusercontent.com/589034/80832983-7f9a4180-8ba2-11ea-8ecb-6a2703ccc334.png)

A simple solution may be to just sort axis label values. 

Discovered by @donghaoren

**Comment by jheer** [comment]
Currently the overlap method assumes sorted label input, as that is what Vega generates internally. The Overlap transform could perform a sort, but then it will be repeated upon each invocation. So perhaps it is better for AxisTicks and LegendEntries in vega-encode to sort custom values inputs instead. Note that the sort order here can also affect the relative z-index, too.

**Comment by domoritz** [comment]
I think it would make sense to fix this in vega-encode but would that also work if values are set by a signal?

**Comment by jheer** [comment]
Yes, signal-valued parameters are first resolved as part of the dataflow and the computed results are then passed in as the parameter values for a transform.
