### ISSUE TITLE
regression in time axis label formatting

### ISSUE THREAD

**Issue by aaugustin** [vega/vega#259]
I've built a graph where the `x` axis represents a day. I'm displaying one tick per hour formatted as `HH:MM`.

It has been working very nicely until a few days ago. Now, instead of:

    00:00  01:00  02:00  ...  23:00  00:00

the axis shows:

    Tue 17  01 AM  02 AM  ...  11 PM  Wed 18  

Here's the relevant excerpt of my spec:

    var spec =
    { ...
    , "scales":
      [ { "name": "x"
        , "type": "time"
        , "range": "width"
        , "domain":
          { "data": "table"
          , "field": "data.datetime"
          }
        , "nice": "hour"
        }
      , ...
      ]
    , "axes":
      [ { "type": "x"
        , "scale": "x"
        , "format": "%H:%M"
        , "ticks": 24
        , "grid": true
        , "layer": "back"
        }
      , ...
      ]
    , ...
    };

**Comment by aaugustin** [comment]
The latest commit in this area appears to be 214251b920ce668aea11f099e0c26551b068c149 but I'm not sufficiently familiar with the project to tell whether it could have introduced this regression.

I'm loading vega as follows:

    <script src="http://trifacta.github.io/vega/lib/d3.v3.min.js"></script>
    <script src="http://trifacta.github.io/vega/vega.js"></script>

Is there a convenient way to test various git revisions? If there is, I'm happy to bisect the regression — and use the last known good revision until this bug is fixed!

**Comment by aaugustin** [comment]
Well, that turned out to be easy.

I can confirm the regression happened in 214251b920ce668aea11f099e0c26551b068c149.

This version works:

    <script src="http://trifacta.github.io/vega/lib/d3.v3.min.js"></script>
    <script src="https://raw.githubusercontent.com/trifacta/vega/88c932b6dea2f45344bbee7b48b88e5c9e09f11a/vega.min.js"></script>

This one doesn't:

    <script src="http://trifacta.github.io/vega/lib/d3.v3.min.js"></script>
    <script src="https://raw.githubusercontent.com/trifacta/vega/214251b920ce668aea11f099e0c26551b068c149/vega.min.js"></script>

**Comment by arvind** [comment]
Hi @aaugustin, we've just merged Vega 2.0 into the master branch. Please re-open this issue, with a snippet of the input data as well, if you're still experiencing this issue. Thanks!

**Comment by aaugustin** [comment]
Yes, the bug still exist. I'll attach a stripped down version of my graph with randomized data (HTML source + screenshot in Firefox).

**Comment by aaugustin** [comment]
HTML: https://gist.github.com/aaugustin/ec38962aec5cd8c58629

Screenshot:
![screen shot 2015-07-10 at 13 15 02](https://cloud.githubusercontent.com/assets/788910/8617599/a912159e-2705-11e5-8f37-6a4c0a8c62ab.png)

**Comment by aaugustin** [comment]
Since I'm not a contributor to this project, I cannot reopen the issue myself. Can you reopen it? Thanks.

**Comment by arvind** [comment]
Thanks for re-opening the issue. It's been fixed in f5605d1.

**Comment by aaugustin** [comment]
Great, thanks!
