### ISSUE TITLE
Async error not caught properly

### ISSUE THREAD

**Issue by alexeypetrushin** [vega/vega#2599]
The problem is that when the rendering code contains the error - it's not handled properly and escapes.

I originally [created the issue](https://github.com/vega/vega-embed/issues/303) in VegaEmbed but @domoritz investigated it and it seems like it's in Vega, from comment:

> the issue is that Vega uses console.error instead of throwing an error.

# Example

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "Stock prices of 5 Tech Companies over Time.",
  "data": {
    "values": [
      {
        "dates": ["2000-01", "2000-02", "2000-03"], 
        "gold": [1, 2, 1], 
        "silver": [1.5, 1, 2]
      }
    ]
  },
  "transform": [
    {"flatten": ["wrong_dates", "gold", "silver"]},
    {"fold": ["gold", "silver"], "as": ["symbol", "price"]},
    { "calculate": "datetime(datum.dates)", "as": "dates" }
  ],
  "mark": {"type": "line", "point": {"filled": false, "fill": "white"}},
  "encoding": {
    "x": {"field": "dates", "type": "temporal", "timeUnit": "yearmonth"},
    "y": {"field": "price", "type": "quantitative"},
    "color": {"field": "symbol", "type": "nominal"}
  }
}
```

[Playground](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATZAgBOjQnh4qckAMp5u8ANZhC++DrDcAZmACsYACrIkYAMLcqIToSoxO3FS63oyoyHRqGpCa6HiYOKAQEJAU6GKsOthgANoaWWCZ5VnJqYU4xZAATAAMrSLNAIxqUC1tzY3dTa3N7QDMkAC6qmBlVZDU3GKaRcUd043THVMzVdWwjGJRKx107pvrE7MQAL6zlzfq2Xi6obAu3LqoK7PAkC5iqTwyBMJUgAHddMpqAB9FJA2CDBZLQb7Q7IXSTa6PLK-d7I+rzRbLaaQVFHbaQdAIgmwACeqHYi0G9kYjkx2IgwCg8Dy8FYAKBRRqQKMcQAFHDWKg6HCdABKQZUoWyhFgW4QKZJDC6axFX54WmEZBCiRKY0kwjcRhKPB6v4HMTIZY4Fx5WDIEkuB1CsGISSQa5YpLA+DcTTW6h62aQAAedq9yHxWlqCJJBqNQqBwQ+eUGouQAFUwrbTLTkOhPsoWAGOVBafHwknICy2WnDcbTABHVihIxpIxUGvR0NiD4NxPOqB0hlMtsZ0xKILW3PqtUga5AA)

**Comment by domoritz** [comment]
Shows an error in the console:

```
try {console.error("Error")} catch(e) {}
```

Does not show an error in the console:

```
try {throw new Error("Error")} catch(e) {}
```

I think one can reasonably argue that this is correct behavior in Vega. You can override the logger (https://github.com/vega/vega/tree/master/packages/vega-util#logger) to handle errors yourself.

So, I think the behavior is as intended.

Sorry, @alexeypetrushin for asking you to file another issue here. I realize now how all of this works as intended.
