### ISSUE TITLE
Text appears to be aliased

### ISSUE THREAD

**Issue by ronichoudhury** [vega/vega#261]
When I use moderately large fonts (48-72pt), the text appears to be aliased.  This is not a showstopper but having nicely rendered fonts would make a big impact on the overall presentation of charts/vis made with Vega.

Here is an example (with corresponding [Vega spec](http://pastebin.com/cpPY8UeE))

![text demo](https://cloud.githubusercontent.com/assets/2903332/6877011/5d399f02-d4a3-11e4-9ee0-7690a479e30e.png)

(There is also an .svg file showing the same problem but GitHub is not letting me attach it here).

**Comment by jheer** [comment]
Can you please include the browser, version and OS where you experience the
problem? Thanks!

**Comment by ronichoudhury** [comment]
**Browser:** Chromium Version 40.0.2214.91 (64-bit)
**Vega:** I believe 1.5.0 (from looking at http://trifacta.github.io/vega/vega.min.js)
**OS:** Linux (NixOS and Arch Linux)

**Comment by arvind** [comment]
Hi Roni, I believe this should be fixed with Vega 2.0. The text in your example spec renders anti-aliased. Let us know if you still experience any issues.

**Comment by ronichoudhury** [comment]
@arvind I just tried pasting my spec into the Vega 2.0 editor and it still looks pretty bad (more or less the same as the screencap above).  Would you mind posting a screencap from your end so I can compare?

**Comment by arvind** [comment]
Taken with Google Chrome Version 43.0.2357.132 (64-bit) on OS X 10.0.4. What're you testing on? 

<img width="488" alt="screenshot 2015-07-13 13 12 11" src="https://cloud.githubusercontent.com/assets/42262/8659583/cd7ab640-2960-11e5-9a40-e455efed9901.png">

**Comment by ronichoudhury** [comment]
Chromium 43.0.2357.132 - it very well may be a Linux font rendering thing.  Though, fonts rendered in the web page itself, for instance, look totally fine.  Anyway, it definitely seems to not be a Vega issue.  Thanks!

**Comment by jheer** [comment]
Roni - are you seeing a difference between Canvas and SVG rendering?

**Comment by ronichoudhury** [comment]
No difference at all, AFAICT.

**Comment by jheer** [comment]
Interesting. Then I would wager that this is likely not a Vega problem. If
you care, you could try testing with a standalone SVG file and see if you
replicate the problem. What happens if no font is set? If it is set via
external CSS file? Or set via style property (as Vega does)?
