### ISSUE TITLE
Update canvas handler to only add event listeners as-needed.

### ISSUE THREAD

**Issue by eeyshen** [vega/vega#2621]
We get lots of warning about violation in canvas handler. How to fix it? Thanks.

<img width="1411" alt="截屏2020-05-17 下午10 36 32" src="https://user-images.githubusercontent.com/31716017/82151694-57dbf680-988f-11ea-9fe7-3bf2fe97e22e.png">

**Comment by jheer** [comment]
Can you share more about your setup (browser, OS, other pertinent details)? I haven't seen these warnings before, so I'm not sure how Vega is interacting with your browser settings or the site you are using Vega on. Do you see similar warnings if you test a Vega specification in the [online editor](https://vega.github.io/editor/)?

**Comment by eeyshen** [comment]
We use latest Chrome on Macbook Pro,  vega with vega-embed and react-vega. We get similar warnings with the online editor.

<img width="1434" alt="截屏2020-05-17 下午11 21 45" src="https://user-images.githubusercontent.com/31716017/82152640-44cc2500-9895-11ea-9fae-3b244dc617b3.png">

**Comment by jheer** [comment]
Thank you. I now see the warnings if I enabled "verbose" level in the Chrome developer console. In many cases Vega *will* call `preventDefault` on these events, so always marking the listener as passive is not a workable strategy. 

Right now we simply add event listeners for all supported event types by default and dispatch as needed. However, we can avoid these violations in most cases if we instead only selectively add event listeners to the Canvas element when we know they are needed by an internal handler. I'll add this to my queue of work to do.
