### ISSUE TITLE
Successfully set width and height yet fail to render correct width

### ISSUE THREAD

**Issue by tengpeng** [vega/vega#2626]
I am building an interactive dashboard based on Vega. The interactive grid would set the width and the height of Vega viz as users drag resizing.

I find:
1. it successfully set the width and the height of Vega Spec.
2. the height is correctly rendered yet the width is not.

This behavior is not expected because I expect both the height and the width are rendered correctly.

Reproducible code: https://codesandbox.io/s/pedantic-goodall-f0p3c?file=/src/App.js

Screenshot: 
<img width="511" alt="Screen Shot 2020-05-18 at 3 57 30 PM" src="https://user-images.githubusercontent.com/2724786/82188327-4c84db80-9920-11ea-9379-9c963e88e5b2.png">

(The read rect is the parent div that Vega viz is supposed to fit in)

React Prop from React Developers Tool:
{"autosize":{"type":"fit","resize":true,"contains":"padding"},"mark":"line","encoding":{"x":{"field":"a","type":"ordinal"},"y":{"field":"b","type":"quantitative"}},"data":{"name":"table"},"width":465,"height":310}

**Comment by domoritz** [comment]
Take a look at https://vega.github.io/editor/#/examples/vega-lite/bar_size_responsive and also the generated Vega. Does that help?
