### ISSUE TITLE
Pointing URL in   Directed Graph Vega Example to elasticsearch Index

### ISSUE THREAD

**Issue by iNERO9** [vega/vega#2627]
The GitHub issue tracker is for development work such as bug reports, feature requests, and design discussions. It is NOT the place for asking usage questions or seeking debugging help.

If you are looking for help or have a general usage question, you can:

- Join the [Vega Slack organization](http://bit.ly/vega-slack)
- Join the [Vega discussion forum](https://groups.google.com/forum/#!forum/vega-js)
- Search or post to [StackOverflow with the "vega" tag](https://stackoverflow.com/questions/tagged/vega)

**Comment by iNERO9** [comment]
HI I want URL tag to point to my index having similar attributes in the json. I have created two index namely nodes and links same as we have in miserables.json?

Can someone please help me pointing URL to my indexes?

**Comment by domoritz** [comment]
Please follow the instructions for asking questions.
