### ISSUE TITLE
latest vega 5.12.0 error with the sum transform

### ISSUE THREAD

**Issue by blset** [vega/vega#2637]
since very recent vega versions
there  is an error in the transform data step

in this example
the maxt table is supposed to receive the sum of the tottable

the tottable gets the right total from another table buth the maxt does not

the result is that the graph gets overextended
the maxt should roughly receive values  as the sum of c1 and c2 values in the table below

segment | t | y0 | y1 | id | maxt
-- | -- | -- | -- | -- | --
"1. c 11 " | {"c1":"258","c2":"976","segment":"1. c 11 ","t":1589155200000} | 0 | 258 | 1 | 1589760000000
"2.3. " | {"c1":"126","c2":"2924","segment":"2.3. ","t":1589155200000} | 258 | 384 | 1 | 1589760000000
"4.5. " | {"c1":"55","c2":"12649","segment":"4.5. ","t":1589760000000} | 384 | 439 | 1 | 1589760000000

but gets

c1 | c2 | id | maxt
-- | -- | -- | --
"025812655" | "0976292412649" | 1 | 1589760000000

. Looks like c1 and c2 where not summed as numbers

here is the instruction that worked previously

```
 {
         "name":"verytot",
         "source":"tottable",
         "transform":[
            {
               "as":[
                  "c1",
                  "c2"
               ],
               "fields":[
                  "t.c1",
                  "t.c2"
               ],
               "ops":[
                  "sum",
                  "sum"
               ],
               "type":"aggregate"
            },
            {
               "as":"id",
               "expr":1,
               "type":"formula"
            },
            {
               "as":[
                  "maxt"
               ],
               "fields":[
                  "id"
               ],
               "from":"maxt",
               "key":"id",
               "type":"lookup",
               "values":[
                  "t"
               ]
            }
         ]
      }

```
here is the complete example showing the problem
https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhBIAHnAhoA2qABmbAE7JMaEAFIAJgFp9CaSA3akmACoBPHHD2YaCZzK00443eiZs2GzmMtBIADbO6HJhkRaumHHoACI2HiAJkQAKSIaGNOJkaABMAAwAvlKgZJo0hmiYmgxwMjV1qRAwKsVSAMwAuq21hh0wAPJqahBwfgCMpZ61Pn4gkWq6oVARUSD2semZOwBywUyaB3TZufmFJRWDIFASajRFqKDyNErvq0hMcOEAGISTAAZRoAC8orMACwyQ7A3zgqFoWGVVbkHz1H4vcLhADCbHCWj0AHcYHR0uE-gDEWDIdC4RlLnA6cjGeV0YYbChUKoQOIkO49NMGDRwkoZMQIs1vvzqf9wnooAACWazFUWaXhZpoXqle6VdRaHRoUA4JCaaZmjJ6bmYZycmSC4XoTB-OJSmWKFSgKCzPRlCxQYp6AAcADYLNMyO5fHpZpQVar1Zr4YHSmVjJnjLMAOwgI2PAPoXqhmQhhMR3rR8hxlaJ5NqjXxDNZnPFGGFqrFvQwgMV0PoMoCWux5YJpMplvp4eZ0rZ3rZ0NF-190eDwOzKOhOsT9CN6dp21z9tL0oATm7fpLIDDBc36BhpR3IBj9cnTdTrdPC9KS+3a9ewPGFy0eIcQAjWExw-A8p2bY8VjKM9jGKGtV1vbcwMrdAIzzLtd3HeM4K-GcTxAZC-yXfUgLXA8ww3cC9DzYpGPffcQEPBCfwo+dsxhbMowwhMLwIpj0DzARX3Y4jOPg79Z149sBNmdCezoijigHcS716K9CNguTSMQts-wEoNhOHftgwgi98xgjiuIU8jKP41CC0siiBBrR8QAvAQwwc2SnLIpC+NKAR+No29WMC3yLzzaS92C+TQtM7NIvVaK9FfHCKOfIKkMoXokxM39l1zDz1MwnydJherCsDYrSp41yOy7TzelyiD5gEMCZKKkqVTKpSqOXbLcIfHTtyygyOOKZrhta8LzyvTyw2wnqL16bSBqaoaRragChOqhMIpswMYTDUpGuHRbDpW1C1JvBNZk2wMIwaubZIWg7lpQmjPPVMS8uKPCxL2u6-sUtqBJfCbOPs3zihY-rksGlqYfClTnuAxG4p0lGvrfdH9sxlzsdQm6ga0i7hzDJGSaIjGlqx5T3IRt7GNBuy0eZsnWYp9tItKDrToPMG6Yoi9O1uij7v+v9MoDTyQZ6vSIdJp9KCEB722KSrOe6vsYQEG7vpWGEdaTRWKtlzzZd8iMzc1-ntd123-3Gh3uYg53RLlq2PbZsbLwRvSpY2yTA+tvWxrQhGrqlmXrpj4OhbGwHxZAM3k8k82mcMoObZDtz4c8gRtLy9VeiktOS4ztzVIRvqpfVas2K1kBi7jtyUZbtXXtE3au57z3lZb32EzBmF9MLjix9LiLc0C8p+iLF0dmQOQNjfNgGE0KAdndJhPQyTQkHECArHMPkPjlW0HheAFDAf3QHjYPAVBAbeQAeTBHA7CQGQGofAHRASQN8EAdQLBwDkDgTQCZ4iAL0DfBg1JCzrx7JvFwgQT5nzEAfI+LgPQHAvlfG+vpZBvz-jIZ+4RX7f3fkMfeOAmD2G-ntD+X8+SyE0LGeQtCMgoPQMA0BFBwFFnodiDIlA1zwhEW+d0UAADWECoEwJkHAhBSCFFOFQSadBKAiyQO-tvZhlhvAMIfjAp+mhgh6HMRYFRcAOHoE0cI-R6BiRsBUQwHAWpvQ0PXlg0AOD0CkE0PYTAgRoz70PsfPBpD4jkOviaKhpjeHyKYk-KxjDeGYDkdpQplZuEPwgAwEIb5KlCIAV42QIDzgSMdD2TJ0D6haPgYgg8yD6loIwSYh+TjckvxsfUOxDj0BOJkC4tx7Tek7B8X4gJXodQ+gKX-Nea8ZDwFeFgNAEYDQyEiGQLEcpQA+CeIYKIoAID2AQAECUNplhwG6bchkNptS6lQG9ConJ0S4iVOgJ4xJEGLG8LJGJOBjBrF3haPIBQ3hMggI0XxOwQUklCPcx5Dh6kQAAI4MEtBcRIOxbDkNgHAFU1yVTunFHEbZP9LQqPOZYext91BICPn4UA9peQZGSSw-x7CRSk2dEKHY0wlhKCdEyzQLKqGXLYNc55vhXk2hRfYlxNppGiv5psbYyoiQknRJqtFAB1Oo9BPnehKOiOQOq8kuGjFsJIIAYiupabsR1L9lS7U9XoPYAbZUwDYJEx1eIxgWigHQNxoAvlRFKDrWV-j7Q3MsZG6NsabVrNROiAoDpNA4CJGkHN3ylFwACf8uh7KbR8tFdK7snjFkFEdP-RRNRWFASVSqn4Ly3kZqBeoJ16A9oGrdRixBprUXapxCO+e8Zx3ouNVO0IM64CWsMNan4Ca7UyFJFaroO7bWoH1Pan1DDHHyF3vsPQHrDXojjZY316B7AF1va+29j6hzDpfbsf1hrP3BvRKG8Nc7M1cuzce3NqAk0CBTTgNNEbwhRsgwAst0Jq1ssmbynkuDsDJPRHUnY5woC6CLD29N-a60Oug9858XIn27tQGUAF9KL0yLHW+ANwKV1No0EiD5dGOTwjgTy59l63RFKbbR39kmmU7xdYB91X6ZBPt1a+gDbqg0PtlWoWtPx61uiSafL1xGXBie7eIK5VG1UDsMExk9VM2N4gw3oUBPh+MgnZG5n5EYiOWbnX+tc56gvyemdx5T96GVqY436pT2mv16YM7h90ehInRNiURxRDpFOMvhTcN4Agl2ssMMEJABQ614bdIKiTMjyPitdCpgNMgCuIrQEmiKMhyGnLJIeiw9iGDiGxI0Zoejj5uBaby8rlW+QLGdqUB44Tdi3udDQYhqBRstBAD1nYuyyD7KLGV5As3Uv8vwekDTC6GsCglUa0FA3L69eBWkMgWgOHjb0FoG4ERMGhFeIKJ5fIHgHq3Ue66FQgA

**Comment by blset** [comment]
PS the problem is not present with version 5.11.1 but appears with version 5.12.0

**Comment by jheer** [comment]
Please upgrade to v5.12.1, which fixed this regression. Let us know if you’re still seeing issues with the most recent version.

**Comment by blset** [comment]
it's ok with 5.12.1 
but   <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
still pulls maybe 5.12.0 as it fails

**Comment by jheer** [comment]
Not for me. Try clearing your browser cache?
