### ISSUE TITLE
With cross transform, having a dot in the fields names leads to an error.

### ISSUE THREAD

**Issue by johanneskoester** [vega/vega#266]
The error is `TypeError: x is undefined` in line 114 of vega.js.

Steps to reproduce:
Take the scatter_matrix example of the live editor, and modify one field name (also in the iris dataset) to contain a dot.

**Comment by arvind** [comment]
You must escape dots with a blackslash (e.g., `some\.field`) when you reference them within properties.

**Comment by pratapvardhan** [comment]
@arvind -- this quite doesn't seem to work. Here's the [spec](https://jsbin.com/ceyayapoga/edit?html,js,output) where it fails.
