### ISSUE TITLE
Vega logs `Dataflow invoked, but nothing to do.` even if log level is Warn

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2665]
https://github.com/vega/vega/blob/92c7caccf22ee51cd5b059dedfede073da1d9814/packages/vega-dataflow/src/dataflow/run.js#L46 is not guarded by the level. 

Should the level maybe handled in the logger instead of the code?

**Comment by jheer** [comment]
In general, the level should be handled by the logger. However, the reason the dataflow guards some of the calls here is for performance reasons: to avoid marshaling the debug information if it is not supposed to be shown.
