### ISSUE TITLE
array_agg aggregation method

### ISSUE THREAD

**Issue by sgratzl** [vega/vega#2673]
it would be great if vega/vega-lite supports an aggregation operand similar to `array_agg` from Postgres https://www.postgresql.org/docs/13/functions-aggregate.html. 

In the end, it takes all the aggregated values and instead of e.g., computing the sum, it just stores the values in an array. 

My use case is, that I listen externally to selection signals and in case of aggregated values, it is tough to go back to the original items, each time requires to reverse the aggregation manually. The `array_agg` aggregation would solve my problems. Simililary, with functions like `flatten` one can use the array to go back to a flat list, e.g. for a detail plot of the selected group.

**Comment by sgratzl** [comment]
> You could filter the original data and get the tuples where the data falls into the bin you are looking for. Would that work?

yes, but it requires to implement a custom logic for all possible aggregation methods, like binning, group by, ...

**Comment by domoritz** [comment]
Can you send a pull request with a new aggregation function?

**Comment by sgratzl** [comment]
I just checked the code, the undocumented (at a first glance) `values` aggregate operation is exactly what I need.

e..g [manual histogram](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICCNsRpwIUmfIC+S5NoDW+pkm2KQEOILhRM7eU1Pb19MNFBMAE8cOH0IGlkyHw9EHCj9WTlYpTl9EwYvUzh3GzsQTG0kWQgAMzZtBDQAbVAmBLQKhjglGvNBZX0ASQBZABEAIQB9ACU1BLIPJAhmkBGJmbnEybb5JTWp2f8tncm4WQGAXTtQJDIybT5MWNQWkDYcfWIkQS7lpSWhmMDpsyMtrm8PugoGwGLIwv9llCYXCQDYLkp7jCcExIit9hsjmRtu09kCCfNibJTucQFd0SAztDlPNwiBoYJ6qzoec6AFWV4fH4+egBaEPF8fs8QExJailBKunEnt4ZYqygAPVm9bwDdD4w4UnYeKIxfQARwYVX86n8pDlIHVACYtX1dasyQbjglqQMlCapRarXQ5nayrigtr+vpobD4eVogHLXDg7bYqUbEA)

**Comment by domoritz** [comment]
Haha, okay. Let's document it.

**Comment by domoritz** [comment]
Done in https://github.com/vega/vega/pull/2674
