### ISSUE TITLE
Accessibility of Vega for those with visual impairments

### ISSUE THREAD

**Issue by hartman** [vega/vega#268]
As Vega is rolling out to Wikipedia, I was wondering if there have been any thoughts so far about how Vega can support people with visual impairments.

A screen reader currently won't even mention the presence of the graph, let alone explain to a user what it is about. Have there been any discussions ?

**Comment by arvind** [comment]
Hi @hartman, this is an excellent question and perhaps more suitable for a discussion thread on the [Vega Google Group](https://groups.google.com/forum/#!forum/vega-js). I would definitely be interested in learning about how we can make Vega visualizations more accessible for an audience with impairments.
