### ISSUE TITLE
Use WeakMap instead of mutating data with Symbol properties?

### ISSUE THREAD

**Issue by mbostock** [vega/vega#2705]
Vega currently assigns Symbol(vega_id) properties to passed-in data. For example:

<img width="818" alt="Screen Shot 2020-06-09 at 1 31 12 PM" src="https://user-images.githubusercontent.com/230541/84196756-83e53480-aa55-11ea-880a-666c4ef8b77e.png">

Instead of mutating the passed-in data, Vega could use a [WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) to associate a unique identifier with each element in the data set. This could be implemented like so in Tuple.js:

```js
var tupleids = new WeakMap();

function tupleid(t) {
  return tupleids.get(t);
}

function setid(t, id) {
  tupleids.set(t, id);
  return t;
}
```

By avoiding mutation, Vega could use [frozen](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) data, and the API would be cleaner (in my opinion). For example, it would avoid these symbol properties appearing unexpectedly (and nondeterministically) when inspecting data in Observable notebooks, where side-effects are best avoided due to dataflow.

**Comment by jheer** [comment]
Thanks for the suggestion! We'll look into it. At first glance this looks good to me, assuming there isn't a significant performance hit.

**Comment by dantman** [comment]
I was just hit by this issue too. I wanted to use a Vega chart in a React component using data from a GraphQL API using the Apollo client. The data is queried with useQuery and useMemo memoizes a reordering of the data. Somewhere along this line the data is frozen, because this data is immutable and it is expected that nothing modifies it so in development at least the data is frozen to ensure this expectation is upheld.

**Comment by wodddy** [comment]
I have the same problem in Angular. I am using Redux with immutable objects, so when they come to the component - I get the error. I will do some workaround, but would be really nice to have a solution from Vega itself.

**Comment by wodddy** [comment]
If any Angular dev ends up here, use this snippet

      `const values = [...this.values.map(value => ({...value}))];`

**Comment by jheer** [comment]
I conducted some micro-benchmarking, ingesting and accessing a 3-column x 100k-row dataset, and unfortunately using the WeakMap results in _tuple ingest times 2-3x slower_ and _tuple id lookup times 1-2x slower_ than the current symbol-based annotation. (For a more "in context" measure, use of WeakMap also increases the Vega test suite run time on my laptop from 59 sec to 72 sec.)

This impact is large enough that I'm reticent to make the change. Moreover, if I simply make a full copy of the data, the ingestion performance (including the full copy) is around the same as ingestion with a WeakMap... and of course the subsequent access times match the existing performance.

To avoid performing a copy directly in client JS code, one can use the `copy` property of the JSON data loader to have Vega do it for you. See https://vega.github.io/vega/docs/data/#json

I will close this issue for now, but am happy to think about and discuss other approaches. For example, Vega might recognize when an input object [is frozen](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isFrozen) and fall back on the WeakMap method in just those cases... though I'm hesitant to add `Object.isFrozen` checks for all tuple id operations, especially when a one-time data copy may suffice for those cases! Any other ideas?

**Comment by domoritz** [comment]
@jheer Would it make sense to have the `copy` feature also for value arrays then?

```
{
	"name": "table",
	"values": [12, 23, 47, 6, 52, 19],
    "copy": true
}
```
