### ISSUE TITLE
Tooltips on rule marks stop appearing if other marks are added

### ISSUE THREAD

**Issue by aragilar** [vega/vega#2706]
It appears adding additional marks to a plot stop tooltips for rules appearing. I've uploaded an example of this at https://gist.github.com/aragilar/228914349dbc3ccd95cab9ce7362725b, where the only change is the removal of the additional rules.

**Comment by domoritz** [comment]
Please try to reproduce the issue with a minimal example and send us a link to the spec in the editor at https://vega.github.io/editor/. Also, this looks like a Vega-Lite issue. Please file the issue again at https://github.com/vega/vega-lite.
