### ISSUE TITLE
formatPrefix & formatSuffix properties

### ISSUE THREAD

**Issue by marcprux** [vega/vega#2722]
When you want to format a date axis with something fancy like "June of the year 2010, C.E.", vega easily supports this via [d3-time-format](https://github.com/d3/d3-time-format) support for literals in the format expression: `"%B of the year %Y, C.E."`.

Number formatting, however, is limited by the lack of [d3-format](https://github.com/d3/d3-format) support for literal values. So it isn't possible to have your axis values be labelled "521μs" without going through some contortions with scales or transforms.

It probably isn't realistic to expect `d3-format` to add support for literals, but one simple way to provide support could be to add a `formatSuffix` property wherever there currently is a `format` and `formatType` property. This would just tack on the literal `formatSuffix` value after processing whatever is in the `format` expression. Since the vast majority of additional number formatting (that isn't supported by existing `format` expression functionality) is concatenating some string to the end of the number, this would cover most needs. Most of the remaining needs would be covered by an additional `formatPrefix` property.

**Comment by domoritz** [comment]
Couldn’t you instead use a signal for the label text encoding?

**Comment by marcprux** [comment]
There are numerous work-arounds, including signals, scales, and transforms. But given how easy and useful it is to stick some literal values into a date format, number formatting could benefit from similar ease of inserting literals at the beginning and end. 

This is especially for consumers of `vega-lite`, who shouldn't need to understand how signals work in order to accomplish this fairly simple formatting need.

**Comment by kanitw** [comment]
FYI, Vega-Lite axis has `labelExpr` property.  

While I agree that suffix could be useful, it's also not that hard to do/understand:

`labelExpr: "datum.label+'μs'"

**Comment by marcprux** [comment]
I somehow forgot about `labelExpr`! Thanks.

I hereby rescind my enhancement request.
