### ISSUE TITLE
Feature request: Comments in CSV

### ISSUE THREAD

**Issue by danmarshall** [vega/vega#2729]
A SandDance user is requesting a feature for handling #comments within a CSV file.
https://github.com/microsoft/SandDance/issues/245

I'm adding the issue here since we use the csv parsing built in to Vega. Also to gauge whether this is a common accepted practice in the community, or if it would break anyone who has the # appearing in their data.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "data": [
    {
      "name": "csv",
      "format": {
        "type": "csv",
        "parse": "auto"
      },
      "values": [
        "category,amount\na,28\nb,53\n"
      ]
    },
    {
      "name": "csv-with-comment",
      "format": {
        "type": "csv",
        "parse": "auto"
      },
      "values": [
        "#comment\ncategory,amount\na,28\nb,53\n"
      ]
    }
  ]
}
```

**Comment by domoritz** [comment]
CSV isn't really standardized so I think we should stick to the most common parser and let anyone write their own if they need more advanced features. The issue I see with using `#` for comments is that it's not the only natural choice (e.g. I could see `//` working as well). Therefore, I am against adding the proposed feature.

**Comment by amitkaps** [comment]
You could change the csv parser (in your SandDance application) to use something like PapaParse that can handle comments. You can then load the parsed object into Vega.

https://www.papaparse.com/#comments

**Comment by domoritz** [comment]
I'm going to close this issue but feel free to add comments if you have more thoughts.

**Comment by tuner** [comment]
I made a similar proposal to d3-dsv some time ago, but it was politely rejected: https://github.com/d3/d3-dsv/pull/68

However, vega allows for registering custom formats (like vega-loader-arrow). Perhaps a vega-loader-dsv-with-bells-and-whistles could be provided for special cases :) 

Btw, although papaparse has plenty of nice features, it is quite slow if compared to d3-dsv, which vega uses.
