### ISSUE TITLE
Vega-lite selection does not affected the result. How to filter the data? 

### ISSUE THREAD

**Issue by helloconey** [vega/vega#2737]
The GitHub issue tracker is for development work such as bug reports, feature requests, and design discussions. It is NOT the place for asking usage questions or seeking debugging help.

If you are looking for help or have a general usage question, you can:

- Join the [Vega Slack organization](http://bit.ly/vega-slack)
- Join the [Vega discussion forum](https://groups.google.com/forum/#!forum/vega-js)
- Search or post to [StackOverflow with the "vega" tag](https://stackoverflow.com/questions/tagged/vega)

Hi, I am a newbie of vega and vega-lite, and now I am trying to use selection to create an input box that allows me to by entering a specific id, the plot will only show the data of that id. 

However, my code does not affect the plot to enter the id number. What I want to get is like picture2 (using Kibana filter), does anyone have any idea how I can doing that in picture1's code by adding some expression or code? 

![image](https://user-images.githubusercontent.com/48701450/85907534-b5386100-b7c6-11ea-9a17-a1b5b57660ec.png)
(Picture1)

![image](https://user-images.githubusercontent.com/48701450/85907542-bbc6d880-b7c6-11ea-9def-bb3920848d47.png)
(Picture 2 using Kibana Filter)

Thank you very much!

**Comment by domoritz** [comment]
Please use slack and the forums for questions. We use the issue tracker for bugs and feature requests. Not kibana issues, please ask @nyurik.
