### ISSUE TITLE
node-canvas as optionalDependency

### ISSUE THREAD

**Issue by tmcw** [vega/vega#274]
For the browserify usecase, node-canvas is a tricky requirement for vega: it relies on the Cairo library, requires a native package build, and its linking to Cairo is notoriously wonky. It would be great if it was possible to install vega without the node-canvas dependency, given that it's not necessary in browsers or with svg output.

**Comment by idan** [comment]
The cairo requirement makes vega hard to install on Heroku.

I've had success using [tmpvar/jsdom](https://github.com/tmpvar/jsdom) and [domenic/svg2png](https://github.com/domenic/svg2png), which relies in turn on phantomjs to provide the headless bits.

**Comment by arvind** [comment]
Vega's renderers have been broken out as a separate project ([vega/vega-scenegraph](https://github.com/vega/vega-scenegraph)) and the node-canvas dependency has been correspondingly moved as well. Unfortunately, I don't believe we can currently mark node-canvas as an optionalDependency as all the renderers (Canvas, SVG DOM and SVG String) create a node-canvas instance for text bounds calculation (e.g., to make sure legends end up in the right place). 

However, we welcome pull requests to [vega/vega-scenegraph](https://github.com/vega/vega-scenegraph) to loosen this dependency. It certainly has been a sticking point for a lot of environments.
