### ISSUE TITLE
Label transform not registered

### ISSUE THREAD

**Issue by rwoollen** [vega/vega#2741]
`vega-label` appears to be registering its transform, but inspecting the runtime, I don't see the `label` transform available?

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAB3GgBN6aAIwCADDPg0yWVRpkKkmFKgDaocUgRw0IMQwBOUWzOJIANgzgQ0FkAAeaAAsMgCeaAIyHkhMcB52OGw04pgqIAC+UqBBqFEgEXmU+TFxCehJKZgATJnZgSHhjSCl8YnJqQDMdTloAGxNqKEtsW0VHZjBmQC6GdMy0J4+fpbWtuhBMphhOOstKXBIjtIgCmzIKX6aKurzII5I4mR78kowPSBWNnYRWzt7HgORxOZwuknM11uMgeTz22l0mBmMiQAWW5lAiw8e02IEwNCgAGsAMJsBipSIyNiOGhwcnoJhsbDnD6Yva-XH44mkun5Kk0uktOAAM0RcxkyEcBN86M+azsTCQEDgAFkjgSTttdnYIGEEAyEjIhY5mahQEYTNrSc5bFkQLSoGwFOtQAwcObnQ1TfYoEs7DihTSPAo-XUCmgMT6sT8TgH4sH0BFbRAaAAvD3uLzrarqdQZPNZVbfdCtA24-52TBwAKIw3GhDh07GUwgBVK1WS0P2x0e13uhuV6sN2NBuzmhgISglzJ5rYwiBCqn1mWagGjUvJtN+NTXDSzPcZIA)

**Comment by domoritz** [comment]
It's not part of Vega yet. We are working on polishing it before making it part of the official framework.

**Comment by rwoollen** [comment]
Ah.  Thank you

**Comment by domoritz** [comment]
You can add the transform at runtime to try it out, though.

**Comment by NoahMarconi** [comment]
> You can add the transform at runtime to try it out, though.

Are there docs on how to do that at runtime?

**Comment by NoahMarconi** [comment]
Docs if needed: https://vega.github.io/vega/docs/api/extensibility/#transform

**Comment by rwoollen** [comment]
Thanks.  We have it enabled in our fork.  Any plans on bringing it into the core Vega?  (We maintain a fork now purely for adding this transform).

**Comment by domoritz** [comment]
@jheer what's our plan for including vega label in vega?
