### ISSUE TITLE
Some coordinates, calculated with "aggregation": "count", do not take into account the X axis.

### ISSUE THREAD

**Issue by SvetProzhirova** [vega/vega#2744]
The problem arises in the block:
`"transform": [
        {"type": "aggregate", "groupby": ["a"]}...
]`

when accessing the variable datum.count I get the total number of elements, not the number of elements in the X axis.
![image](https://user-images.githubusercontent.com/57715248/86361315-523e4280-bc7c-11ea-94bf-186840c60377.png)

Example [vega egitor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSALJQBWENgDsQAGhAB3GgBN6aAMwAGNTPg0yWNACYNMhUkwpUAbVDikCOGhAmz0kMSQAbBnAhorIcyA47khQcAAEai5MDkgAjPEuUAaaIEwATkjisDE4QfYAvlKgAUEh4ZEy0egoMkmosZUZWTA5eSCFxQ6loWH6UQ5JtQYArI2Z2eg4cEhp7UX+XcE9fZUDsYkjY81d07MdC5NL4cP96IMgdfqjqU0TgbvtALoymE0QAGZsaQi+oJgAnlMYmQyGk+Jh7DJQWwGDgmP9fAtVltsjIGCBniB3jQ4O4FD5LBcMTI2HhEUhSBkyPZMUgCRYiY98kz5jY7A5Xrj3DQfDIxAw0qEHE4aiBXpkPl8fpY-oD7NUQWCKBCXNDYfDyRj9gCgehPt8GMEXHSHBAcJkXHAAB44WboYZqMIAKjCTEy+PNoQAFE4GAhKFAYeJMFIIpQGmGBABKOay3UgCBmKAAaxc2NxClN5skzOZfKgHm8vxAbPlICt0ELAH0XDqy27xJmZOaFAoaOIyABJcTiOB2tThmRpIOZ1CvLzGNjIdtoUAi4WmUXpvEOdLjFqFEBNakOeRKDe0q1FmUJgvuMsVs9wGsktI44OrtjYKdPGTINLJ+lxstqnBp4fSnOi4cmC7jcryWJlJgs4lrYZbvFBcAKFWmCwueEHzug85QsO6oItU7SbnAWRsAo8qgMREJ2qA+GgMuo4gP8kT5Cx+aFl+sHsug-yVuetZyqu7ouC2bYdt2vb9oOgRIK27ZkAA8gwVFoAOAhDiOaDjnAk7TpIqBAc4eqIchqF5BB9GrnMW6ZDu+kJhCf6oA6LGYu+n7FnWDhglA0EyO8AEwZhkGhBCJloUWREkWRMGUX2MFWjBvEXklN5YjiK7oGu2ybnuyh2UlDiXtWURCfUm7YmBHneNBWGmH6AZhAAPAAvL0FSuB4XgOKCcDEbGYrVQuqH+lAYQAHyteoLhuJ4ZZgpm2qDbVw0NRNvQnDIM1degXw2QU8xbWW-xcmwsivmKbBsO4mA0I5dHpQxw5TjWm6JsOyZwAA6ooeWgIdqiboGaQSQASjJNAMASf2dfKsRqJuMBgu8MEWegshwNELwCeg4hTu2HiEWiOBOORjGJVeDg8RTfkPZZCNwDoej5RT3EFZUpWxK9rxsB9MH-ag4iGu4m4AF7tmRCV2fz8MI2wlKJdzvNSzDDjYmC6Q0CmVli421p8yrZUsdq2MDVavlYgFdlBQhIVISh4U+JFgbRXZsXUeW5OFoVKVprTmW3BuNOVcrs3dWCCKbhCZso37CzlRImAAMo0CLpP87EABsm5uhAuLtmnBsXX+8cPiH20gAgEhsGaZSES5uZAA)

```
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "width": 300,
  "height": 200,
  "data": [
    {
      "name": "data",
      "values": [
        {"a": "place 0", "b": "a111", "c": 20, "branch": "apple"},
        {"a": "place 0", "b": "a", "c": 1, "branch": "apple"},
        {"a": "place 2", "b": "c", "c": 25, "branch": "pear"},
        {"a": "place 2", "b": "c1", "c": 25, "branch": "pear"},
        {"a": "place 5", "b": "c", "c": 25, "branch": "pear"}
      ],
      "transform": [
        {
          "type": "aggregate",
          "groupby": ["a", "b", "branch", "u"],
          "fields": ["c"],
          "ops": ["average"],
          "as": ["c"]
        }
      ]
    },
    {
      "name": "trellis",
      "source": "data",
      "transform": [
        {"type": "aggregate", "groupby": ["a"]},
        {
          "type": "formula",
          "as": "span",
          "expr": "50 * bandspace(datum.count, 0.1, 0.4)"
        },
        {"type": "stack", "field": "span"}
      ]
    }
  ],
  "scales": [
    {
      "name": "xscale_",
      "type": "band",
      "paddingInner": 0.1,
      "round": true,
      "domain": {"data": "data", "field": "branch"},
      "range": "width"
    }
  ],
  "axes": [{"scale": "xscale_", "orient": "bottom"}],
  "marks": [
    {
      "type": "group",
      "from": {
        "data": "trellis",
        "facet": {"name": "faceted_tuples", "data": "data", "groupby": "a"}
      },
      "encode": {"enter": {"y": {"field": "y0"}}},
      "scales": [
        {
          "name": "yscale",
          "type": "band",
          "paddingInner": 0.1,
          "paddingOuter": 0.4,
          "round": true,
          "domain": {"data": "faceted_tuples", "field": "b"},
          "range": {"step": 50}
        }
      ],
      "marks": [
        {
          "type": "rect",
          "from": {"data": "faceted_tuples"},
          "encode": {
            "enter": {
              "x": {"scale": "xscale_", "field": "branch"},
              "width": {"scale": "xscale_", "band": 1},
              "fill": [
                {"test": "datum.c <= 20", "value": "green"},
                {"test": "datum.c >= 30", "value": "red"},
                {"test": "datum.c >= 25", "value": "orange"},
                {"value": "yellow"}
              ],
              "tooltip": {"field": "room_"},
              "strokeWidth": {"value": 3},
              "cornerRadius": {"value": 10},
              "href": {"field": "web", "type": "nominal"}
            },
            "update": {
              "y": {"scale": "yscale", "field": "b"},
              "height": {"scale": "yscale", "band": 1},
              "stroke": {"value": null},
              "zindex": {"value": 0}
            },
            "hover": {"stroke": {"value": "firebrick"}, "zindex": {"value": 1}}
          }
        },
        {
          "type": "text",
          "from": {"data": "faceted_tuples"},
          "encode": {
            "enter": {
              "x": {"scale": "xscale_", "field": "branch"},
              "fill": {"value": "grey"},
              "text": {"field": "a"},
              "fontSize": {"value": 16},
              "baseline": {"value": "top"},
              "font": {"value": "monospace"}
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by jheer** [comment]
I don't think I understand the problem... the aggregate you highlighted appears to correctly count the number of items _grouped by property `a`_, and writes them to the property `count`. The aggregation itself knows nothing about the x-axis, nor should it. Here is the content of the `trellis` dataset shown in the editor:

![image](https://user-images.githubusercontent.com/202799/90514891-17c43280-e162-11ea-9a3d-50031702f406.png)

You might want to double-check the use of the `stack` transform. You can use the stack's `groupby` parameter to separately group elements for stacking (for example, to stack at different points along the x-axis if you group by the `"branch"` field). For more, see https://vega.github.io/vega/docs/transforms/stack/
