### ISSUE TITLE
Production rules do not work for legend properties

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2754]
While the schema allows production rules, they don't seem to work. 

![image](https://user-images.githubusercontent.com/589034/87235164-d89a0900-c38d-11ea-8164-29588c59446b.png)

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "padding": 5,

  "data": [
    {
      "name": "source",
      "url": "data/cars.json"
    }
  ],

  "scales": [
    {
      "name": "size",
      "type": "linear",
      "round": true,
      "nice": false,
      "zero": true,
      "domain": {"data": "source", "field": "Acceleration"},
      "range": [4,361]
    }
  ],

  "legends": [
    {
      "size": "size",
      "symbolStrokeColor": [
        {"test": "true", "value": "blue"},
        {"value": "red"}
      ],
      "symbolType": "circle"
    }
  ]
}
```

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhA4kAE3k1xZNAJnykmFKgDaocUgRw0IMQwBOUEzMsAbU5u0EoSCxBFjJAXwC6M6CQ7OAg0fRBDY1MIGgAvGxBMAE8cE3Q7ZTg3aRALNgZxeTRMCwY4GXEaazQAMyCIcpB4vOLSxvk2ZGU0UCcdM3yrBJqaODsi9ABBKGtgiy12Hxl5lTTdABYpAGYANgBGXz8ZYLI4QtC9UBj46LiEiCSEJjY7AGUStgBrOABhF7YLGFQJgQphTCUyjliEFIegmHZId4pKBoQi0rk4EUjmZHs87AAVFLoqA0KzBEB+bxAA)

**Comment by MichaelaLoneWolf** [comment]
Hi
It is possible - I assume that because of update

```
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "padding": 5,
  "data": [{"name": "source", "url": "data/cars.json"}],
  "scales": [
    {
      "name": "size",
      "type": "linear",
      "round": true,
      "nice": false,
      "zero": true,
      "domain": {"data": "source", "field": "Acceleration"},
      "range": [4, 361]
    }
  ],
  "legends": [
    {
      "size": "size",
      "encode": {"symbols": {"update": {"stroke": [{"test": "true", "value": "orange"}, {"value": "blue"}]}}},
      "symbolType": "circle"
    }
  ]
}
```

**Comment by domoritz** [comment]
Yes, they work in encode blocks but not for legend properties directly.

**Comment by jheer** [comment]
Hmm. Production rules are not intended to work as top-level guide properties. I don't think we could add this support either, as top-level values may include literal array values (e.g., for stroke dash). So if the schema allows production rules the error is with the schema generator (and possibly also the TS typings).

**Comment by jheer** [comment]
@domoritz How is this blocking VL?

**Comment by domoritz** [comment]
I think it was blocking a refactoring but if it's not supposed to work, we will keep using the encode block.

**Comment by jheer** [comment]
Thanks @domoritz. I realized that since the schema resolves without issue, we should be able to support the production rules after all. Added PR #2801 to support production rules in top-level guide properties that accept encoders.
