### ISSUE TITLE
Faceted Chart by `Row` and `Column` does not align the data correctly if `sort` arguments are given

### ISSUE THREAD

**Issue by tonylee3399** [vega/vega#2757]
Hi peeps,

This is my first time posting in Vega GitHub. Please correct me if the information given is not complete.

## Describe how to reproduce the bug
The bug can be reproduced by faceting the chart by `Row` and `Column` while giving custom `sort` order.
See appendix for code snippets.

To fix the snippets 2, delete the lines 151–156 and 161–165 to correct the data alignment.

## The Data is described as follow
![image](https://user-images.githubusercontent.com/16498167/87377854-26498800-c5bf-11ea-8b95-ee267e7b1bc1.png)

## Appendix
1. [Correctly aligned  (NO `sort` argument is given)](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAHJQCMlAFYQ2AOxAAaEFBUAzGmTShMdQXAMgky2GwBOaEAhoATRyfWa2gm3aaCGpjdoqmADKNABepqgyAGwaNjRwyph2mGw4IAC+GsQJAO5mWkk0ygxsDBAAEnB6WGgAzAAMDRqFRiVlEADqTvRoYk0ZWSCOSJgoqKDKSAiRw6MCTI4AnDJQks4ATNobSHVLUDsydY5idWJQ-WJwYiemQyNjEHCYEGYPC8ur645bO3sHSCOJzOFwaVxuVzQAG1QAAFaxseRwKDJdCwmRuYJjMizYIbNwADzQ-AasgA7BoAJ5oUl1OpZOEIpEouzozHY3H4jRE1CksQUkDU1AkyhkpYMkDwxHI1GSjEaLFIHF2PGE4mkhoAVipNModUkEqlzNlbIVHJVYjVvMoGx11pkmsNTJlrPlIEVyvQwUt3N10Rkdr5BrUjOlLLRbo9uJ9IB5IoatsF6somo2TrDJq57vNXrqVv4AaTwo1ZPTxtZWajKrzvvtiaFMjLLrRlZz7prsd1GzEdpF-qb4clraVnKtpJkS0DlDEA8z7JHKqzPNJGwFQr7pZDkudg9hw897qXaELQtJ0XpW6NzaH84PwTdy9k9d1ZLTl53c7NC69D91kkkU4NBeobli2t64r+xaUFqvaNu+Gash2Va5mOvakpqcEgdesJIW2wQdo+dTPlBr6zoh4HVmOlDRGufrBlhu64d+h75uhsRFiKM7waBkpMXeR7WmKU5imRaJ8aOta0gBRakpI0QZAAukM2hIFAzwFB4DAIKoEwgLocCCI4KrmhomCUjgszKGwDhTIImQaAi+S6fphmsh+bhmRZdhWTZSB2YMGgQBZUBmIkWiOMU+i6Voni2M5CSuV6JkgJ5lnWcUfn2SlbAeEY6SoDCekJUZ6BEqZ5mzAAjgwFhGGMRikPZoAuSVSblV56DVbVdCjDQjWKbWzXFXYZUgNAfmRKAjjWUgxTQgWagyEp7VVTVRT1X1dx2kNBmtdSgVQBNbwzXNBULUtQypXYXXrb1-VDPANSojITQaMg1gANZ2DgbDFMkGi5D0MDHgMpnGLMADCNjWDKAAEAAi8yw8UsMAGKqc8cCOLDEMwEg1jJBkQA)
![image](https://user-images.githubusercontent.com/16498167/87377890-3cefdf00-c5bf-11ea-959e-c6d727887db8.png)

2. [Charts are incorrectly aligned (`sort` arguments given)](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAHJQCMlAFYQ2AOxAAaEFBUAzGmTShMdQXAMgky2GwBOaEAhoATRyfWa2gm3etxHb7SqYAMo0AF6mqDIAbBo2NHDKmHaYbDggAL4axPEA7mZaiTTKDGwMEAAScHpYaADMAAz1GgVGxaUQAOpO9GhijemZII5ImCiooMpICBFDIwJMjgCcMlCSzgBM2utItYtQ2zK1jmK1YlB9YnBix6aDw6MQcJgQZvfzSytrjpvbu-tIh2Op3O9Uu10uaAA2qAAArWNjyOBQJLoGEyNxBUZkGZBdZuAAeaH49VkAHYNABPNAk2q1TKw+GI5F2NEYrE4vEaQmoElickgKmoYmUUmLekgOEIpEoiXojSYpDYuy4glEkn1ACslOplFqknFkqZMtZ8vZyrEqp5lHW2qtMg1BsZ0pZcpACqV6CCFq5OqiMltvP1agZUuZqNd7px3pA3OF9RtArVlA160doeNnLdZs9tUt-H9iaF6tJaaNLMzkeVuZ9doTgpkpedqIr2bd1ZjOvWYltwr9jbDEpbio5lpJMkWAcoYn7GbZw+Vme5JPW-MFvZLwYlToHMKHHrdi7QBcFJKidM3hqbg7n+6CrqXsjrOtJqYv29npvnnvvOskkkn9TniGZbNjeOI-kWlCaj2DZvumLLtpWOajj2JIarBwFXjCiGtkE7YPrUT6QS+M4IWBVajpQUSrr6QaYTuOFfgeeZoTEhbCtOcEgRKjG3oeVqipOoqkaivEjjWNL-oWJKSFE6QALqDNoSBQE8+QeAwCCqOMIC6HAgh+J6ZoaEo1gopCboRhWiEWvJGiYBSOAzMobAOJMggZBo8J5DpekGSy75uKZ5mym4u5hbmdkgA5Tl2C5blIB5AwmU5UBmAkWiOEU+g6Voni2L58T+UZ872Y5zmuUUiWedFbAeEYaSoNCulFYZHZlbF6AAI4MBYRijEYpCeaAfltVSHUzD1fV0CMNBDQpNYja1diEiZUCJREoCOK5SBFFC+ZqDIikTXYU2FANc23LaS36WNQXra4Onbcge1NQdR2DDFk29eds3zYM8DVCiMiNBoyDWAA1nYOBsEUSQaDk3QwEe-T2cYMwdPCyhkAABAAInMONFDjABiKlPL4OMAMIwEgZkZEAA)
![image](https://user-images.githubusercontent.com/16498167/87377922-4a0cce00-c5bf-11ea-8bc4-7d602087a487.png)

**Comment by domoritz** [comment]
Heya, welcome to Vega. Please look for existing issues and file this in vega/vega-lite.

**Comment by tonylee3399** [comment]
Ah, thanks for pointing out. I think I was brought to vega/vega from this [question#3900](https://github.com/vega/vega-lite/issues/3900). It seems that this issue is already under the radar.
