### ISSUE TITLE
Image marks crash vg2png (with fix)

### ISSUE THREAD

**Issue by nyurik** [vega/vega#278]
As described in https://phabricator.wikimedia.org/T99994

If graph spec has a link to an image mark, vg2png crashes. This is due to the data being read as a string instead of the buffer.

Fixed in https://github.com/trifacta/vega/pull/267

**Comment by arvind** [comment]
This should be fixed with Vega 2.0 (via [datalib](http://vega.github.io/datalib)). Thanks for submitting PR #267.
