### ISSUE TITLE
Arc mark rotation affects container layout

### ISSUE THREAD

**Issue by marcprux** [vega/vega#2780]
Take the following pie chart with an arc mark:

```json
{
  "$schema" : "https://vega.github.io/schema/vega-lite/v4.14.0.json",
  "title" : "Rotated Pie Chart",
  "mark" : {
    "angle" : 0,
    "type" : "arc"
  },
  "data" : {
    "name" : "data"
  },
  "encoding" : {
    "color" : {
      "field" : "category",
      "type" : "nominal"
    },
    "theta" : {
      "field" : "value",
      "type" : "quantitative"
    }
  },
  "datasets" : {
    "data" : [
      {
        "category" : 1,
        "value" : 4
      },
      {
        "category" : 2,
        "value" : 6
      },
      {
        "category" : 3,
        "value" : 10
      },
      {
        "category" : 4,
        "value" : 3
      },
      {
        "category" : 5,
        "value" : 7
      },
      {
        "category" : 6,
        "value" : 8
      }
    ]
  }
}
```

<img width="297" alt="Screen Shot 2020-08-01 at 14 18 55" src="https://user-images.githubusercontent.com/659086/89107853-f0e7cb80-d401-11ea-87a3-207e249f710e.png">

Change the mark's "angle" property from 0 to 45, and it is rendered as:

<img width="321" alt="Screen Shot 2020-08-01 at 14 20 16" src="https://user-images.githubusercontent.com/659086/89107887-212f6a00-d402-11ea-8c55-01cd8e779279.png">

The padding and position relative to the title and legend all changed, even through all we wanted to do was change the default rotation of the pie chart.

**Comment by jheer** [comment]
Thanks @marcprux! This reveals a bug in the arc bounds calculation. Here's the same example with the bounds also rendered, illustrating the problem:

![image](https://user-images.githubusercontent.com/202799/90239880-90588580-de28-11ea-90bc-4a8efb3b604f.png)

**Comment by jheer** [comment]
The crux of the issue is that the `angle` channel for rotating the marks uses an indirect path for bounding box calculation: the bounds are calculated directly, and then rotated to match the `angle`. This results in bounding boxes at arbitrary angles, so we then compute the rectified bounding box in the pixel coordinate space of the rotated bounding box. The process can enlarge the bounding box size, creating the problem here. Clearly we need to fix this.
