### ISSUE TITLE
SVG path gets butchered when used with symbols

### ISSUE THREAD

**Issue by p-himik** [vega/vega#2803]
```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 200,
  "height": 200,

  "marks": [
    {
      "type": "symbol",
      "encode": {
        "enter": {
          "fill": {"value": "#939597"},
          "stroke": {"value": "#652c90"},
          "x": {"value": 100},
          "y": {"value": 100},
          "size": {"value": 1000},
          "shape": {"value": "M.583-.75H-.583c-.092 0-.167.075-.167.167v1.167c0 .092.074 .167.167 .167h1.167c.093 0 .167-.075.167-.167V-.583c0-.092-.074-.167-.167-.167zm-.75 1.167-.417-.417.118-.118L-.167.181l.633-.632L.583-.333l-.75.75z"}
        }
      }
    }
  ]
}
```

Expected shape:
![image](https://user-images.githubusercontent.com/4410314/90307532-b12fe200-dedf-11ea-9e27-cba45255fbeb.png)

Actual shape:
![image](https://user-images.githubusercontent.com/4410314/90307534-b9881d00-dedf-11ea-99ba-3ad921ff8142.png)

What's interesting, the shape itself is changing if you change `"size"` back and forth.

**Comment by jheer** [comment]
Thanks for the issue, which reveals deficiencies in our SVG path string parser. PR #2805 addresses the issue.

**Comment by p-himik** [comment]
Thanks!
Just out of interest - why is there a need to change the path strings in the first place? Couldn't the relevant paths just be wrapped in `<g transform="scale(precomputed_scale_factor)">`?

**Comment by jheer** [comment]
We need to parse the paths for multiple purposes (not just "manual" scaling). For example:

- Support Canvas rendering
- Support internal bounding box calculations

In addition, the internal scaling allows us to avoid adding extra DOM nodes / handlers in the case of SVG output and keeps the internal architecture simpler (and it's already complicated enough...).
