### ISSUE TITLE
404 error on iris.json in Vega editor

### ISSUE THREAD

**Issue by bkamapantula** [vega/vega#2815]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug.
- [x] Use the latest Vega version, if possible. Always indicate which version you are using.
- ~~[ ] If you are using Kibana, first read the [instructions for posting Kibana Vega issues](https://gist.github.com/nyurik/736c34970ba3c32f3fe3d45d66719b3e).~~
- [x] Include error messages or gifs/screenshots of problematic behavior, if applicable.

![image](https://user-images.githubusercontent.com/1143687/90463197-d8fa9200-e0f9-11ea-9bf9-fa07b4e40dc7.png)

Visit any of the below examples that use iris.json in [Vega editor](https://vega.github.io/editor/):

- [boxplot](https://vega.github.io/editor/#/examples/vega/box-plot)
- [top-k-plot](https://vega.github.io/editor/#/examples/vega/top-k-plot)
- [top-k-plot-with-others](https://vega.github.io/editor/#/examples/vega/top-k-plot-with-others)
- [violin-plot](https://vega.github.io/editor/#/examples/vega/violin-plot)

Until it's up, those who would like to use it from [github raw file](https://raw.githubusercontent.com/vega/vega/master/docs/data/iris.json). Useful for prototyping.

**Comment by domoritz** [comment]
This example relies on an outdated vega datasets. See https://github.com/vega/vega/issues/2708. The fix will be in the next release.

**Comment by bkamapantula** [comment]
noted, thanks @domoritz
