### ISSUE TITLE
Separator "." in date data is no longer working 

### ISSUE THREAD

**Issue by pietrasagh** [vega/vega#2870]
Separator "." in date data (e.g. "2001.12.13") is no longer working . Other combinations of "/", " " and "," are parsed correctly (e.g. "2019 ////  10, ,,,, / 01" or "2019    11     01"). It seems that separator "-" can be only one and not combined with any other.
Problem may be due to some update in d3 or deeper in [eslint](https://github.com/eslint/eslint/issues/13568). I noticed it on wikipedia Graph Extension which is using Vega 2.
I tested it on 
in editor for [Vega version Vega 5.15.0 ](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAB3GgBN6aAQAZVM+DTJY0AJjUyFSTClQBtUOKQI4aEJgBOSAGYuaUaSGJIANgzgINEsQY0w7dD1VKMpVAEZYuK8oBkdHNABmAHYANgAWOIBOPRkcRzhiTIEc6NyAXylQMIiQKKKAAiIidva4jXapQalO9vjk1PTUPL1i6pKQMoq0PNU8vJyBAQamkxa2wp6euLjDnrGZFLTMgA5i3KzS8srUDOu4rL0crO3Q3ft9gC0cT0APOIEukzyGSiq3mi2eGUK2SyhVUdQAujIXGxHMhMGhQJgAJ44FqiCReHBIRwQCI7cL2ZogOoNBzOcQQbG44KEkktTA0WwMcR0LzCuhBCwgIlwaleBASZSYkDuOC+BSMv4YjEyaB+QI8kDWWz2AAeXmJpPsApNMnZZBa8iUMEpSAUCho4jI+jyRjYyE9BN+pmtzjcHi8qvV9nFmFUzJ+xpaRItfPsvk9svSdqQXpaWh0+JkIqgEScARkAC84I42GgXH5aX6A5JUPSzGzXO5PFiaGqNegIQnlUhTQaLKAcX3xPj0Ew2Nh-V49b4WuasTi8fYAKRMdrbgCazMaICncBn6bgLiLIBXya8ZEcijQ5bgOpAyEcAGtJSFLS0M3EOwZGpGgzAbXwmxVWsECDMIOycLsI1Zc8oDYBQ6RAc9wkmUBzTbW8oH1M1Iz7aN0FjeNWRTAi73sFNe37ewh1ZCAnDYL9MJ8fwWjYuA1SYHjj1vdjOIAdUUZQCO4gJMhZFl0TqIA)
and [Vega 2 editor](https://vega.github.io/vega-editor/?mode=vega)

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 500,
  "height": 250,

  "data": [
    {
      "name": "traffic",
      "values": [
        {"date": "2020.01.01", "curr": 3764192, "prev": 3560276},
        {"date": "2019 ////  10, ,,,, / 01", "curr": 4292562, "prev": 4044655},
        {"date": "2019    11     01", "curr": 3892767, "prev": 3817267},
        {"date": "2019-12-01", "curr": 4320042, "prev": 3937790}
      ],
      "format": {
        "type": "json",
        "parse": {"date": "date"}
      },
      "transform": [
        {
          "type": "timeunit",
          "units": ["year", "month"],
          "field": "date"
        }
      ]
    }
  ],

  "scales": [
    {
      "name": "x",
      "type": "time",
      "range": "width",
      "padding": 24,
      "domain": {"data": "traffic", "field": "unit0"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "zero": false,
      "domain": {"data": "traffic", "field": "curr"}
    }
  ],


  "axes": [
    {
      "orient": "bottom",
      "scale": "x",
      "format": "%b %Y"
          },
    {
      "orient": "left",
      "scale": "y",
      "grid": true

    }
  ],

  "marks": [
    {
      "type": "line",
      "aria": false,
      "from": {"data": "traffic"},
      "encode": {
        "enter": {
          "x": {"scale": "x", "field": "unit0"},
          "y": {"scale": "y", "field": "curr"},
          "stroke": {"value": "steelblue"},
          "strokeWidth": {"value": 3}
        }
      }
    }
  ]
}

```

**Comment by domoritz** [comment]
Vega uses standard browser date parsing and only [dates in the standard formats](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#Description) are supported. 

Vega 2 probably used datalib and may have used different date parsing ut I haven't checked.

**Comment by domoritz** [comment]
It would be awesome if you help update the graph extension to the latest Vega versions, btw.

**Comment by pietrasagh** [comment]
I checked example code with "." separator on mentioned mozilla website and it works. 
```
const javaScriptRelease = Date.parse('04.12.1995');
console.log(javaScriptRelease);
// expected output: 818035920000
```
My js skills are on "Hello world" level. Wikimedia developers seems to be overloaded with more urgent issues. They started to [work on it](https://phabricator.wikimedia.org/T165118) but got stucked. If you could help would be great. Please contact [Yurik](https://m.mediawiki.org/wiki/User:Yurik) for details

**Comment by jheer** [comment]
Unfortunately, `'04.12.1995'` is simply not a universally valid date. I just tested and it works in Chrome, but not in Firefox. I don't believe this is a Vega-specific issue, but rather a consequence of different browsers supporting inconsistent formats for `Date.parse`. The solution is to change the input data to use a valid date string accepted by all major browsers.

**Comment by jheer** [comment]
Alternatively, you can specify the date format yourself as part of the Vega specification, as described here: https://vega.github.io/vega/docs/data/#format.

You can pass a `format` parameter like `{"myDateField": "date:'%m.%d.%Y'"}` to specify a custom date format.
I don't recall offhand but I believe we supported this in Vega 2 as well.

**Comment by pietrasagh** [comment]
This could be best solution for me. I will check if it works. 
Thanks!
