### ISSUE TITLE
data/sp500-2000.csv is not in Vega Datasets

### ISSUE THREAD

**Issue by domoritz** [vega/vega#2901]
https://github.com/vega/vega/blob/1382f06b72f0b0c08d74d157137a78da4a6b7906/docs/examples/calendar-view.vg.json#L34

This dataset does not exist in Vega Datasets and so the editor does not load this spec correctly.

**Comment by jheer** [comment]
Added `data/sp500-2000.csv` and released vega-datasets v2.2.0.
