### ISSUE TITLE
Unable to pass latest vega-loader & vega-canvas through Google Closure compiler - missing files?

### ISSUE THREAD

**Issue by metasoarous** [vega/vega#2907]
Hi folks

We've discovered a problem with the most recent releases of `vega-loader` and `vega-canvas`:

https://github.com/metasoarous/oz/issues/64#issuecomment-698343242

When trying to build cljsjs output for [Oz](https://github.com/metasoarous/oz), which involves some minification/tree-shaking with Google _Closure_ (that's "s", not "j"; an implementation detail in the _ClojureScript_ ecosystem), it's not able to find the a certain set of files in the most recent releases of `vega-loader` and `vega-canvas`. In particular, the first error that pops up indicates that the `vega-loader.js` file cannot be found:

```
{:tag :shadow.build.npm/invalid-override,
 :require-from #object[java.io.File 0x4d68156d ".../node_modules/vega-dataflow/build/vega-dataflow.js"],
 :require "vega-loader",
 :file #object[java.io.File 0x41ebcb92 ".../node_modules/vega-loader/build/vega-loader.node.js"],
 :override "./build/vega-loader.js",
 :override-file #object[java.io.File 0x5d156b61 ".../node_modules/vega-loader/build/vega-loader.js"]}
```

I realize this doesn't say anything about `vega-canvas`, but I'm assuming once the above was fixed the `vega-canvas` bug popped up. Reverting both packages back one bugfix version has unblocked me for now, but I won't be able to cut releases with newer versions until the underlying issue is resolved.

I'm a bit clueless as to what might have changed in the build process to be causing this, but hopefully this is enough information for you all to track down what might need fixing. If not, please let me know if there's any additional context needed which I might be able to help provide.

Thanks for your time!

**Comment by domoritz** [comment]
Hmm, it looks like the build system is overriding the name of the file. If you look at https://github.com/vega/vega/blob/master/packages/vega-loader/package.json#L21, you can see the names of the files. Maybe you want `build/vega-loader.module.js` instead of `vega-loader.js`. 

Where does `:override-file #object[java.io.File 0x5d156b61 ".../node_modules/vega-loader/build/vega-loader.js"]` come from?

**Comment by metasoarous** [comment]
Thanks for the quick response @domoritz!

To be honest, I have no idea! I don't understand the internals of Shadow-Cljs or Google Closure too deeply, I just use them. But this information will be helpful for me troubleshooting with the author of Shadow-Cljs. I'll get back to you if it looks like there's any way you can help further, and will also report back if we're able to solve this downstream of vega.

Thanks again!

**Comment by domoritz** [comment]
Try clearing your node_modules and any other cached files. Maybe that fixes it.

**Comment by domoritz** [comment]
Oh, and make sure you only have one version of every dependency (if you use yarn, delete the yarn lockfile and re-create it).

**Comment by thheller** [comment]
This line is referring to a file that is no longer part of the package.

https://github.com/vega/vega/blob/f0c23dfba70c5b43486ac730102d2ef942136394/packages/vega-loader/package.json#L41

It used to exist in 4.3.2 but no longer does in 4.3.3

https://unpkg.com/browse/vega-loader@4.3.3/build/
https://unpkg.com/browse/vega-loader@4.3.2/build/

So the override should be changed to either point to the `.module.js` or `.min.js` but not to a file that doesn't exist.

**Comment by domoritz** [comment]
Ohh, I missed those lines. Good find @thheller! 

@metasoarous does https://github.com/vega/vega/pull/2908 fix the build for you (you can try making the two changes by hand in your node_modules)?

**Comment by thheller** [comment]
#2908 will not fix the issue, it'll just create another one.

Removing the overide will make everything using the `"main"` entry to use the `.node.js` file. `"module"` is not the default entrypoint in `shadow-cljs` since mixing ESM and CommonJS is sort of weird and unsolved. Even webpack v5 will have breaking changes in this area. For better compatibility it is better to stick with either all CommonJS or all ESM. Without the override we end up with `node` code which likely isn't what we want.

**Comment by domoritz** [comment]
I see. @thheller Would you recommend that we add an additional bundle `vega-loader.browser.js` that is cjs but has the browser code in it? The question is which file the override should point to since we don't have a cjs bundle with the browser code (except for the minified file, which is umd).

**Comment by thheller** [comment]
I don't actually know anything about these packages so I can't say. The `.node.js` file might be fine if it doesn't actually do anything node specific. UMD is basically fine since it acts as CommonJS when loaded in a CommonJS environment.

**Comment by domoritz** [comment]
the `.node` files have different code that is node specific and shouldn't be included in browser bundles (e.g. they use node fetch instead of the browser fetch).

**Comment by domoritz** [comment]
If the first one isn't enough, then [`da5a042` (#2908)](https://github.com/vega/vega/pull/2908/commits/da5a04230c38febf3d10617c7508efcd3df8b573) should solve it.

**Comment by jheer** [comment]
Hi all, I applied a potential fix (separate from the one @domoritz is exploring in #2908) as part of Vega v5.17.0, which has been released.

@metasoarous, can you please report back on whether or not the fix has resolved your issue? Thanks!

**Comment by metasoarous** [comment]
@thheller @domoritz @jheer Thank you all so much for helping to tackle this!

@jheer This appears to have solved the issue with `vega-loader`, but there may still be a problem with `vega-canvas`. That is, now when I build with `"vega": "5.17.0"` without explicitly specifying `vega-tooltip` or `vega-canvas`, it doesn't complain about `vega-tooltip`, but raises an issue regarding `vega-canvas`:

```
The required JS dependency "vega-canvas" is not available, it was required by "node_modules/vega-scenegraph/build/vega-scenegraph.js".

Dependency Trace:
        oz/app.cljs
        oz/core.cljs
        node_modules/vega-embed/build/vega-embed.js
        node_modules/vega/build/vega-node.js
        node_modules/vega-view-transforms/build/vega-view-transforms.js
        node_modules/vega-scenegraph/build/vega-scenegraph.js

Searched for npm packages in:
        /home/csmall/code/oz/node_modules
```

I seem to be able to require the latest release of `vega-canvas` (1.2.6) and that gets things working. So maybe this is a somewhat different issue, as previously I didn't have to explicitly require `vega-canvas`. Ultimately though, I'm able to get everything building with the most up to date versions, which is fantastic.

Thanks again for all of your hard work!

**Comment by jheer** [comment]
Hmm, not sure why that changed, but vega-scenegraph certainly does have a dependency on vega-canvas for handling image loading.

Based on this I'm going to close the issue for now, but happy to have discussion continue as is helpful!
