### ISSUE TITLE
Documentation is missing info on transforms

### ISSUE THREAD

**Issue by Skorp1** [vega/vega#295]
The Documentation is missing info on certain transforms such as "stats", I'm able to retrieve a cached copy from google however its not on the page. https://github.com/vega/vega/wiki/Data-Transforms

**Comment by arvind** [comment]
Yes, the documentation reflects the set of data transformations available in Vega 2.0 (which is currently available in `master` and will be officially released tomorrow).

**Comment by Skorp1** [comment]
got it, I guess I picked the wrong day to dig in :)
