### ISSUE TITLE
Offical library for Vue 

### ISSUE THREAD

**Issue by jsbroks** [vega/vega#2961]
Vue is a growing front-end framework. It would be nice to have a library similar to react-vega but for Vue.

I would be open to collaborating on this.

There is [vue-vega](https://github.com/nesterone/vue-vega) but doesn't seem to maintained (no Vue 3 support).

**Comment by domoritz** [comment]
We would love to have a Vue component but won't have the cycles to lead the development. If you setup a repository, I would be happy to move it to the Vega organization. We would need to have automatic linting (eslint), CI (Github actions), tests, builds (with Rollup), and ideally typescript support built-in. 

Also paging @nesterone

**Comment by jsbroks** [comment]
@domoritz Looks like I will need to duplicate functions in [react-vega/src/utils](https://github.com/vega/react-vega/tree/master/packages/react-vega/src/utils)

Maybe vega should consider having a monorepo for all frontend framework integrations

**Comment by domoritz** [comment]
Let's copy for now and then refactor?

**Comment by nesterone** [comment]
Hi, @domoritz, @jsbroks 

Yep, vue-vega is outdated, it's better to re-write it from scratch and target for Vue 3

If we are talking about shipping the Vue component under the umbrella for vega org I can help with that too

**Comment by domoritz** [comment]
Awesome. I invited you two to https://github.com/vega/vue-vega.

**Comment by domoritz** [comment]
I'll close this issue for now. Let's keep things going over in the new repo.
