### ISSUE TITLE
Runtime wiki page should point to vega-editor hosted files

### ISSUE THREAD

**Issue by jeffbaumes** [vega/vega#297]
It appears the new hosted files are the following instead of what is currently on the https://github.com/vega/vega/wiki/Runtime wiki page. The links currently in the example HTML do not work - should this page be updated?

```html
    <script src="http://vega.github.io/vega-editor/vendor/d3.min.js"></script>
    <script src="http://vega.github.io/vega-editor/vendor/d3.geo.projection.min.js"></script>
    <script src="http://vega.github.io/vega-editor/vendor/topojson.js"></script>
    <script src="http://vega.github.io/vega-editor/vendor/vega.js"></script>
```

**Comment by jheer** [comment]
Thanks! I updated the wiki to point to the hosted files in the vega-editor repo.
