### ISSUE TITLE
Control drawing order of lines

### ISSUE THREAD

**Issue by mattijn** [vega/vega#2970]
Given a standard line chart specification, such as described here: https://vega.github.io/vega/examples/line-chart/ 
How would one control the order of the lines drawn?

In below figure, the `y`-values at `x`-values 3, 4 and 5 are equal for both lines (5, 7, 8 resp)
![image](https://user-images.githubusercontent.com/5186265/99253933-dc450d00-2811-11eb-91ae-46c929f63ee0.png)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAETJBBpRtAGxri422EkWZtcAB5IEOY3ErSQAdxqz6aAQAMATLwNGRYaABMQTI4SLKyZmT+MrJImCioANqg4k5waCAZTK4exEjGDApoOSD2aMEgAJ5RMlANAL5SoPWojS2oAOxtaACMXT1jMgMAzCN9E3VTzWgALPPj3UuokdOtIO0LW727K6gAHBuLvXNnAvMB12i3A-cHY0+o62fD70eTXz2QyuxxSZ0uf0eoNQbwGEMOmwBADYgbdDlDkUDRo0EZ9frMHnigSi-ojthCBqNCdCKWDcdCAJxAt7oz5Ms7fXEAXQ6XJk0Aq1WyuXyhXqMkwTRwBXQODYZkwHkUSHEZBlXh8flSbGQZjQoDSGUKxVKMgAZjQ4MZZGKQB1FnkEOqWhKperTOZrEqVWrCqFwoqZOJDDLMIoqjIAF5wRRsNBhiNyHVIPWoA3pTJFJAlArmy3Wwote1bR3qqBsYxsRQeSXSwpVxJ5Yze1Vl9LkKsupO6jTpo3oE25kAWq029Dte18kBIexC2pVy3iRXoJhsbA6jwC0roeqLBdwJeFVxmwMgLfOu1T5CKADWEBqoFr6rIsYYOA8ZtjCH1w6QUDgy4ik6hQQDGlr3qkGbGtmpogC+bBvkwAzvMWIDXneD5FG6R5mEOn4bmmchQegoHKNUXQgAe5byD+B6YDGP69KA562nmo62hRAzMVAgqFh++ZjisFEQGGbA3jK3G8eOFZVvx7Hjna9q8spQA)

Currently the orange line is drawn on top of the blue line. What should I do to draw the blue line on top of the orange line?

I tried lots of different things regarding `sort` and `zindex` in `scales` and in `marks`, but all to no avail. It must be something simple I guess, but I'm not seeing it and cannot find documentation/issues either. If this is currently impossible, than I would like to propose it as an feature request.

**Comment by roying** [comment]
Try defining the domain of scale "color" with an ordered array of values for field "c":

![screenshot_vega](https://user-images.githubusercontent.com/37225856/99283454-080cc680-2803-11eb-885d-827dd7c8fe8a.png)

**Comment by domoritz** [comment]
Yes, in this case you need to order the scale domain.

**Comment by dlaliberte** [comment]
I suspect that is not what @mattijn wanted.  Rather than swapping the colors, he wanted the same colors, but the lower line to be drawn on top of the upper line, regardless which colors they are.  The range over overlap is where the domain is between 3 and 5.

I think the answer is that the data for the two series would have have to be reversed.   Drawing the lines in the reversed direction might be OK in this situation, but I think there is a more general problem, or common obstacle, having to do with the fact that all the lines in a multi-series chart are typically drawn with the same (x, y, c) triples, and while it is convenient that VegaLite splits up lines with different color attributes, it is not quite convenient enough to deal with the separate series in all the other ways one might.

So maybe a pattern that would be easier to follow is to first split the data up into separate series, and then specify the attributes of each series, including the order of the series.

**Comment by domoritz** [comment]
I see. If you do want to swap the order but not the colors, the easiest way is to define both the domain and the range.

**Comment by mattijn** [comment]
@dlaliberte, yes you are right. Its not about the color, I meant the order indeed.
@domoritz, I'm sorry, but I'm not seeing it. How to control the order of the lines drawn by defining both the `domain` and `range`?

**Comment by roying** [comment]
Sorry, my mistake. Here is a complete example that creates a new field ("line_order") to control the specific drawing order of the lines.

[Open chart in Vega editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAETJBBpRtAGxri422EkWZtcAB5IEOY3ErSQAdxqz6aAQAMATLwNGRYaABMQTI4SLKyZmT+MrJImCioANqg4k5waCAZTK4exEjGDApoOSD2aMEgAJ5RMlANAL5SoPWojS2oAOxtaACMXT1jMgMAzCN9E3VTzWgALPPj3UuokdOtIO0LW727K6gAHBuLvXNnAvMB12i3A-cHY0+o62fD70eTXz2QyuxxSZ0uf0eoNQbwGEMOmwBADYgbdDlDkUDRo0EZ9frMHnigSi-ojthCBqNCdCKWDcdCAJxAt7oz5Ms7fXEAXUWeQQBXQxVcAH1Ih4xAxFFABUUkCUCjJMIokOIIAAzNiKBA1UCYJo4GUarUMYwoGT6QqmczCzXyRQeBw4e3oaAVOAACgA5K6RVa4DbFHbPVJtGlMAwEFlPVBPVyAJQgRZ6g2FKBsYyuKCYcWa7OoUBqmhwYyyGogP0Bu0gLkyW1wZ1ZED6aXiRLiZI8jo8msgH3VbK5fKFPvCit1+2K-Uy21mCoeWRsZBmGpUgI95XtgVZKmRHlbPky+qTlPoHBsMzZmQbsgy7y+GDzxdIZf5uTpTKy+UeQvF0voeodLyQ7oC0x4yn61geNeMqhOEl4gOIhgCkqVQyAAXvWbBoChcCpE+L6gGGH5CgqIA-iWhQtIB+7AQc6aah4ybToGs7GFBKo3qm6TkJqoFyPhGiEe+hQkd+RYUeg7SAT2SD2P2tSakW4h5iATBsNgi7ilAbqFABWyKXAymWnAarwX2lGJj2yCKAA1hAOpFFOhRkIobAMDg36udqr5qkg0p5oO-LDvWRb2akwmCnKIpijILluTgTADOWZj+uOiZdCA1l2Q5TGWilnmaa+RHBco1QZYZabyGgoCGZg9bVdsoDmf+Ym-rpiZAk12mlCBrUSSsGUQEqbA2QKXU6ZJ9ETmR4l-u8gHSV2HRAA)


![screenshot_vega](https://user-images.githubusercontent.com/37225856/99316994-44581b00-2833-11eb-87c2-0040b3b621f3.png)

```

{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "A basic line chart example.",
  "width": 500,
  "height": 200,
  "padding": 5,
  "data": [
    {
      "name": "table",
      "values": [
        {"x": 0, "y": 2, "c": 0},
        {"x": 0, "y": 7, "c": 1},
        {"x": 1, "y": 3, "c": 0},
        {"x": 1, "y": 4, "c": 1},
        {"x": 2, "y": 2, "c": 0},
        {"x": 2, "y": 8, "c": 1},
        {"x": 3, "y": 5, "c": 0},
        {"x": 3, "y": 5, "c": 1},
        {"x": 4, "y": 7, "c": 0},
        {"x": 4, "y": 7, "c": 1},
        {"x": 5, "y": 8, "c": 0},
        {"x": 5, "y": 8, "c": 1},
        {"x": 6, "y": 3, "c": 0},
        {"x": 6, "y": 10, "c": 1},
        {"x": 7, "y": 3, "c": 0},
        {"x": 7, "y": 6, "c": 1},
        {"x": 8, "y": 1, "c": 0},
        {"x": 8, "y": 5, "c": 1},
        {"x": 9, "y": 5, "c": 0},
        {"x": 9, "y": 4, "c": 1}
      ]
    },

    { "name": "table_2",
      "source": "table",

      "transform":[
      {"type": "formula",
          "as": "line_order",
          "expr": "scale('scale_line_order', datum['c'])"
      },

      {"type": "collect",
        "sort": { "field": ["line_order"],
                  "order": ["ascending"]
                }
      }
      ]
    }
  ],
  "scales": [
    { "name": "scale_line_order",
      "type": "ordinal",
      "domain": [1,0], 
      "range": [1,2]
    },
    {
      "name": "x",
      "type": "point",
      "range": "width",
      "domain": {"data": "table", "field": "x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "zero": true,
      "domain": {"data": "table", "field": "y"}
    },
    {
      "name": "color",
      "type": "ordinal",
      "range": "category",
      "domain": {"data": "table", "field": "c"}
    }
  ],
  "axes": [
    {"orient": "bottom", "scale": "x"},
    {"orient": "left", "scale": "y"}
  ],
  "marks": [
    {
      "type": "group",
      "from": {"facet": {  "name": "series", 
                                   "data": "table_2",
                                   "groupby": "line_order"
      }},

      "marks": [
        {
          "type": "line",
          "from": {"data": "series"
          },
          "encode": {
            "enter": {
              "x": {"scale": "x", "field": "x"},
              "y": {"scale": "y", "field": "y"},
              "stroke": {"scale": "color", "field": "c"}
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by mattijn** [comment]
Thanks a lot @roying! More complicated than anticipated, but it is a workable approach, thanks again
