### ISSUE TITLE
vega2.js and vega2.min.js

### ISSUE THREAD

**Issue by rbishop-bah** [vega/vega#299]
Could you build these for us and put them in the repo please, like they used to be?  

I am having all sorts of problems getting your build instructions to work for me.  I am limited in what I can install on my (business) laptop, for which I do not have complete Admin control.

ON EDIT:  I see now that they are available from http://vega.github.io/vega/vega.js and http://vega.github.io/vega/vega.min.js... maybe put a note to that effect in the build section of the readme for people who don't want to or can't build for some reason.

**Comment by jheer** [comment]
They are also available as part of the tagged github releases and via npm. So you have a number of options! Adding a note to the readme is a good idea.

**Comment by arvind** [comment]
Thanks, a note about built versions has been added to the readme with d6a82f4.
