### ISSUE TITLE
Contour quantization does not support negative numbers.

### ISSUE THREAD

**Issue by yuicer** [vega/vega#2994]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Clearly describe the goal of the feature request. Why is it needed?
- [x] Describe an envisioned solution. What do you want the new behavior to be?
- [x] If applicable, share mockup images or links to examples illustrating the desired output.
- [x] If applicable, share JSON spec designs for how the behavior would be made available in Vega.

I want to mark a mountain height chart through contour. but can not get the trough part when I put a negative number into weight. and there will be a big hole. and the hole will become confused when I  mark the negative number bigger

so how can I mark the correct charts through [KDE2d, Isocontour] transform?

[demo link](https://vega.github.io/editor/#/url/vega/N4Ig7glgJgLgFiAXAVgAyoDQjgUwgczhiTUxAAcBDKKCAO3xKykpkqQG1Q7KBbHJCADOAewCuAJwDGArADdKAGzE4hnUAA8kARiwBPHVgBeO1AF8MmpACZ9hkCcTbzlkFsQBmO0+OmLVxAAWb10HP1d3ZBDfJxcAgDZosNj-N3sDRFtk51T3LIysxzRcpC8QApiciKRg8ptKuLSUb0LwhJaGkp86z07qzO8yxyqAsoyhtqba8b6AqJ6JlP7Ehdmm0Iza4ca87y3J9zGatfdp4+ydph79pfbrk-Sr7a78p4PS73nn-rPmi675hkvkgALTaeKXRArIEPboZFbfAKvKGwo4o-4-bwI95-eGw6FIbEpAC6qR4-EEUBwdCEEBgBiwokkMkETOkshAMAklBpADMRBJeOpOXpyAJECAANZU6xQECMiBGcVcYQEHiKQSQWAIVK0-DqwS4AhEEBmYlYdygHAacgSVlSJQ4AAUAHINC6MAACFgwMS8AB0GgAlKbvFabXaJUIHYpnS69B7vaw-f69CGLOA8IRiBKTFgpOI6DA1IguSozWS+OKQAWi+IJGpGfWWRKqTS6QzOdy+QKhYgVfSxYIIKJazB6-KQLyIDhFHKJfgJNBJ7G5LOS+CK+bhDHVMLydWtFhB9XFPQcJQ7VgJIX52WcFg6BAW-fjDgb0heUohA+QFARLwlD0EgoA+uwUbNhy06zvOaQZt2+DVlq8ChtwVaCJ2J6CGedAXleIA3mIdB3hIKiPs+4qvg474iJ+36-v+gHAYgoGsOBwiQZO0FzhhoYETyiGGlmJpmlglAaHu-agNGjqCEeICLsupakQxAFAXQdGKD+WACjORaCAARiIMDjkKuq7rxWCKSRZF-mpzFflpv66dSOYgLGvLEKJICARIkoliqB6CL5-mTlhUZ6LwRkalgvI3n2rFsKynEZtSBZUiBIBiOQPrigE0kWRK8ncbBWgZhkBWyRKnYlbxGa0kqmUKMo4qBBm06KBqLEgM1KiCAAxFIQ2mmYo2uOFFCsAg+ZnuQSBUXFAGZWBghjvWaipXQ6V5SArnvplQhciIko4AA6tAKHdb14oeO1ECdQA8lQUgdk1Sh9YgqD+tod2dW9LWGQD9VHSd-0fQROByqNGZcjyQj8oKwoTYhIhUChsUzjxrbJgGa2SKapKkkAA)

![image](https://user-images.githubusercontent.com/23371475/101462274-fe483000-3976-11eb-893a-ded3eca8fbf6.png)
![image](https://user-images.githubusercontent.com/23371475/101462815-99d9a080-3977-11eb-98f1-f5d1ec45ebd5.png)

**Comment by yuicer** [comment]
@domoritz @jheer

**Comment by roying** [comment]
Try changing the value of the negative weight (e.g. -40 instead of -160):
  
![screenshot_vega_contours](https://user-images.githubusercontent.com/37225856/101524456-f0cf7d80-3957-11eb-9066-d192bb10b04a.png)

**Comment by yuicer** [comment]
> Try changing the value of the negative weight (e.g. -40 instead of -160):
> 
> ![screenshot_vega_contours](https://user-images.githubusercontent.com/37225856/101524456-f0cf7d80-3957-11eb-9066-d192bb10b04a.png)

yeah，that did work just for this [-40] data. but I can not justify all the data to a proper value?

and I should not  change the  data  I want to show to make the chart looks good

**Comment by mattijn** [comment]
The chart is based on the data you provide.. Can you please elaborate what you mean with _correct chart_. It's hard to understand what you are looking for.

**Comment by jheer** [comment]
I believe the core issue here is that the weight value is assumed to be strictly positive. At minimum, we should update the documentation to reflect this.

**Comment by yuicer** [comment]
@mattijn 

sorry for the bad English ：(

just like the picture below. [this is matplotlib contour example]

I want to describe the mountain height and includes these below sea level parts



>In one word. I want to modify the **sea level**. Maybe just like the area charts based on **y2: {value: 0}**

![image](https://user-images.githubusercontent.com/23371475/101614113-8269e880-3a47-11eb-9130-414b0b73dbb5.png)
![image](https://user-images.githubusercontent.com/23371475/101615477-20aa7e00-3a49-11eb-98a7-38582d463182.png)

and this is another mountain pic

![image](https://user-images.githubusercontent.com/23371475/101616083-df669e00-3a49-11eb-95d3-10c98b9cb7c8.png)

**Comment by yuicer** [comment]
@jheer  yeah！that is the core！
the weight can't  be a negative number

so how can I do something like this?
![image](https://user-images.githubusercontent.com/23371475/101616731-b561ab80-3a4a-11eb-837d-96ce8c8b5279.png)

**Comment by jheer** [comment]
Thanks @yuicer! I was able to dig deeper and it turns out the KDE2D output is OK, even with negative weights (assuming the `count: true` parameter is used). There is however an error in one of the utility methods used by the Isocontour transform to infer the contour thresholds. I've re-labeled this as a bug so we can fix it. In the meantime, if you provide your own `thresholds` array parameter as input to Isocontour you will be able to get proper contour lines.

**Comment by yuicer** [comment]
@jheer 

I've read the pr and have a try. it did have a better display. but still, a hole can't be removed 

so... do this pr is the final fix? the hole here is needed?

**Comment by jheer** [comment]
Hi @yuicer, apologies but I don't think I'm understanding you. What do you mean by "the hole here is needed?"?

The PR should provide a proper set of uniform steps between the min and max values found within the input grid of values produced by KDE2D, and use those as the default contour thresholds. You can always provide custom threshold levels if there are specific contours you would like to have included.

**Comment by yuicer** [comment]
@jheer  sorry for my bad English...
I mark a repo demo [here](https://github.com/yuicer/vega-kde2d-isocontour-demo)

the red line part is the 'hole'

thanks for your advice. Anyway I'll try threshold params

![image](https://user-images.githubusercontent.com/23371475/101716955-54cd7f80-3ad9-11eb-99d5-00e4ae5cf78d.png)

**Comment by yuicer** [comment]
would it better to `return range(start, stop, step)`?
https://github.com/vega/vega/pull/2995
