### ISSUE TITLE
XSS in transform filter

### ISSUE THREAD

**Issue by nename0** [vega/vega#3018]
This was found during the hxp ctf.
### Credit
@cgvwzq and his [writeup](https://gist.github.com/cgvwzq/0392d64fe1aed82f65c1648b71df1a37)

- Describe how to reproduce the bug / the goal of the feature request:
  Paste the below JSON in the [Vega Editor](https://vega.github.io/editor/#/custom/vega-lite).
  [Working demo.](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtYAvgLoEA0IUAThAHZYBmA9pQLZ6j0CWKUGl8IABQAGAPSiAjKICUAWgDkAHWU1SqPlEETpO6ePkhi5FhEoBrAQCNThoA)
  You will see a '1' alert dialog. 
  To my understanding you should not be able to run arbitrary JS using vega-lite json, should you?
- Provide an example spec in JSON, wrapped by triple backticks like this:

```json
{
  "data": {
    "values": [{}]
  },
  "transform": [
    {"filter": "(0//1/)-'\\\n,alert(1))))//'"}
  ],
  "mark": "bar"
}
```

**Comment by domoritz** [comment]
Repro without Vega-Lite: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATJJhSoA2qHFIEcNHIVIA+gAZpIYkgA2DOBDSqAvgF0ZmAE5JxEAGZtnCG6EwAnjha6B40ZphwzsZwAB440egAFAZEAIwEAJQAtADkADqF4lLmUZhJaZlVmUS5IA4NQA)

**Comment by jheer** [comment]
Here is a reproduction in Vega proper:

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "data": [
    {
      "name": "data",
      "values": [{}],
      "transform": [
        {"type": "filter", "expr": "(0//1/)-'\\\n,alert(1))))//'"}
      ]
    }
  ]
}
```

**Comment by cgvwzq** [comment]
I found this in a black-box manner, but I guess the issue should be in https://github.com/vega/vega-expressionhttps://github.com/vega/vega-expression ?

The parser sees a 0 divided by a regexp, while JS treats it as a 0 followed by a comment. Since the resulting parsed expression is passed to eval, we have arbitrary code execution.

**Comment by domoritz** [comment]
The issue also exists in Vega 2.

```json
{
  "data": [
    {
      "name": "data",
      "values": [{}],
      "transform": [
        {"type": "filter", "test": "(0//1/)-'\\\n,alert(1))))//'"}
      ]
    }
  ]
}
```

(try at https://vega.github.io/vega-editor/?mode=vega)

**Comment by jheer** [comment]
The error stemmed from the removal of comments from our parser, which opened the door to seeing "division by a regexp" instead. PR #3019 updates the parser to instead throw when a single-line comment `//` is encountered, which is the intended design.
