### ISSUE TITLE
XSS via event sandbox escape and function rewrite

### ISSUE THREAD

**Issue by cgvwzq** [vega/vega#3027]
Events are passed to the execution context w/o santiziation, and thus it is possible to reach the window object. This by itself is problematic as the expression can access cookies or any value in the DOM. Together with the arbitrary function call provided by the function rewriting mechanism, it leads to XSS.

```json
"on: [{"events":"mousemove", "update": "join({'join':event.target.ownerDocument.defaultView.eval},'alert(1)')"}]
```
I suspect that there are more functions besides `join` that are equally susceptible.
I also imagine it might be possible to achieve the same effect w/o user interaction, but I haven't dig enough.

**Comment by cgvwzq** [comment]
Some functions also support callbacks: `replace('alert(1)',/.*/,event.target.ownerDocument.defaultView.eval`

**Comment by jheer** [comment]
> Some functions also support callbacks: `replace('alert(1)',/.*/,event.target.ownerDocument.defaultView.eval`

Thanks, will patch in 5.17.3.
