### ISSUE TITLE
Creating a an array of pie charts

### ISSUE THREAD

**Issue by walkingone** [vega/vega#3034]
I am trying to create an array of charts like this:

https://vega.github.io/vega/examples/barley-trellis-plot/

except that each chart is a pie chart.

Like in the above example, I am using a single data source and group marks with facet.

Where and how should I apply the pie transform?

I tried doing it at the data source but it computes start and end angles based on the entire data set, not each individual facet (there is no "groupby" in the pie transform).

And I cannot find a place where I can apply it at the facet level.

Any idea?

**Comment by walkingone** [comment]
I have managed to find a workaround with using joinaggregate transform, thank you~

**Comment by toog** [comment]
Hello, can you put an example of your solution, i try to do the same use case.
