### ISSUE TITLE
Applying the extent transform to a field that contains Date instances returns an array of timestamps

### ISSUE THREAD

**Issue by iaindillingham** [vega/vega#3076]
Applying the `extent` transform to a field that contains `Date` instances returns an array of timestamps rather than an array of `Date` instances.

To recreate, paste [the following specification][1] into the Vega Editor. Notice that the value of the `dateDomain` signal is an array of timestamps rather than an array of `Date` instances, even though the `date` field contains `Date` instances.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "data": [
    {
      "name": "table",
      "transform": [
        {"type": "sequence", "start": 1, "stop": 8, "as": "index"},
        {
          "type": "formula",
          "expr": "datetime(2021, 0, datum.index)",
          "as": "date"
        },
        {"type": "formula", "expr": "time(datum.date)", "as": "timestamp"},
        {"type": "extent", "field": "date", "signal": "dateDomain"}
      ]
    }
  ]
}
```

I've raised this bug because I think that the extent of a field should have the same type as the field: one would expect a field of numbers to have an extent that was also numbers, for example. However, I appreciate that `Date` instances can be problematic and that returning timestamps may be preferable. If this is a feature rather than a bug, then I will open a PR on the documentation.

[1]: https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATJJhSoA2qHFIEcNCEVMANlpmYATknEQAZm2MI0qnQE8cW9BDgBHBnHFRDICIrGmGgAjDIBbDhoABwySBDaNOKycAAeIAC+UqCYTi4gVjYMeigyaTjG2vKYcJg0mgAUAEwADE1hAAQtUh3VDAisyWkAlNIg8VUKWlk5edqFCMWlIOWV6HWNfQPVcKNxCev1cAEaUTOOztppNeLBMhY0cHqykzVjEDRk6nqvcAAibGQSUyAF0MmCgA

**Comment by domoritz** [comment]
This is the behavior in Vega. I don't think it's a big problem, though, since Vega's operators can transparently handle timestamps. When is this behavior an issue for you?

**Comment by domoritz** [comment]
Vega's operators transparently handle dates or timestamps so this behavior shouldn't be an issue in any specification. When so you see a problem with this behavior?

**Comment by iaindillingham** [comment]
I've observed this problem within a production rule: [L158 of this specification][1]. The equality test determines whether the current line mark represents the current week.

[1]: https://github.com/iaindillingham/coronavirus-uk/blob/main/specs/deaths_by_week.vg.json#L158

**Comment by domoritz** [comment]
I see how the current behavior is confusing in custom expressions. I'll make this issue as an enhancement request.

**Comment by iaindillingham** [comment]
Thank you @domoritz. I'm not clear, though, whether the equality operator in the production rule *is* transparently handling the `Date` instance. If it is, then the `time` function is unnecessary. Would the enhancement request clarify this?

**Comment by domoritz** [comment]
You are right, Vega does not transparently handle timestamps/datetime in custom expressions.

**Comment by iaindillingham** [comment]
Thank you for clarifying @domoritz.

**Comment by jheer** [comment]
The extent behavior is indeed as designed.

Dates don’t support equality checks directly so one would need proper logic (e.g., number coercion or date/time access methods) prior to comparison.

With respect to date/time functions, Vega should support time stamps anywhere dates can be used. But no manipulation is done for direct value access in an expression.

Hope that helps! I’m not sure what enhancement is being considered here; I think the solution is just to apply the appropriate comparison in the predicate?

**Comment by domoritz** [comment]
We convert to number in https://github.com/vega/vega/blob/57f1139268757b80635c8ae02365b99d39801325/packages/vega-transforms/src/Extent.js#L38 btw.

**Comment by domoritz** [comment]
Ah, right `new Date(2020,1,1) == new Date(2020,1,1)` is false. However, comparisons work: e.g. `new Date(2020,1,1) > new Date(1990,1,1)`. Vega utils also works on dates `vega.extent([new Date(2021,1,1), new Date(1990,1,1), new Date(2020,1,1), new Date(1990,1,1), new Date(1997,1,1)])` so there is a slight inconsistency between the extent transform and https://vega.github.io/vega/docs/expressions/#extent. Do you think we should change extent util or leave things as they are?

**Comment by iaindillingham** [comment]
From the above, then:

1. The `extent` transform is working as designed and converting instances of `Date` to numbers using the `toNumber` function from vega-util.
2. It does this because instances of `Date` don't support equality checks by value.
3. Vega handles both instances of `Date` and timestamps transparently, except within expressions.

I think I would have benefited from knowing about 1. within the [Extent Transform][1] documentation. Could I ask whether the `toNumber` function from vega-util is the same as that used by the [`toNumber` expression][2]? (I think it is, but I don't quite follow what's going on in [codegen.js][3].) If so, then the best way of comparing an instance of `Date` with either the minimum or maximum value of the result of the `extent` transform would be to use this function.

[1]: https://vega.github.io/vega/docs/transforms/extent/
[2]: https://vega.github.io/vega/docs/expressions/#toNumber
[3]: https://github.com/vega/vega/blob/master/packages/vega-functions/src/codegen.js

**Comment by jheer** [comment]
Yes, or just `+date` suffices for date-to-number coercion in most situations, assuming no `null` values are involved.

**Comment by iaindillingham** [comment]
Thanks @jheer. I'm unsure about whether an enhancement is necessary. Documenting the return type of the `extent` transform would be a possibility. However, the return type is evident from the signal viewer and, hopefully, this issue will help other users understand the design decisions. Consequently, I'm going to close this issue.
