### ISSUE TITLE
disambiguate "x" and "y" in Tutorial

### ISSUE THREAD

**Issue by espinielli** [vega/vega#308]
The [Tutorial](https://github.com/vega/vega/wiki/Tutorial) is great...but in one thing it could be improved IMHO.

The section on the Marks could be simplified by disambiguating the "x"'s (and "y"'s) instead of leaving it as an exercise to the reader ;-) (afterall this is a tutorial and you do not want to confuse people).

The snippet for the Marks

```json
          "x": {"scale":"x", "field":"x"},
          "width": {"scale":"x", "band":true, "offset":-1},
          "y": {"scale":"y", "field":"y"},
          "y2": {"scale":"y", "value":0}
```

and the relevant text:

> The first two properties (x and width) set the horizontal position and width of the bar. The x mark  property (the leftmost edge of the bar) is set to the value obtained by applying the scale named "x" (defined in scales above) to the data field x. Note that there are three very different "x"'s here; make sure you understand the differences!

Is adding unnecessary name mapping.

If we define:

* the data fields as `cat` for the categories and for example `res` (short for results) for the values.

   ```json
  "data": [
    {
      "name": "table",
      "values": [
        {"cat":"A", "res":28}, {"cat":"B", "res":55}, {"cat":"C", "res":43},
        {"cat":"D", "res":91}, {"cat":"E", "res":81}, {"cat":"F", "res":53},
        {"cat":"G", "res":19}, {"cat":"H", "res":87}, {"cat":"I", "res":52}
      ]
    }
  ],
   ```

* and the scales as

   ```json
  "scales": [
    {"name": "categories", "type": "ordinal", "range": "width", "domain": {"data":"table", "field":"cat"}},
    {"name": "results", "range": "height", "nice": true, "domain": {"data":"table", "field":"res"}}
  ],
   ```

* and change accordingly all other places where `"field":"x"` or `"field":"y"` or `"scale": "x"` ...

The relevant Mark section could be simplified:

> The first two properties (x and width) set the horizontal position and width of the bar. The x mark  property (the leftmost edge of the bar) is set to the value obtained by applying the scale named "categories" (defined in scales above) to the data field cat.

Of course `tooltip` is affected and the rest of the text would need to reflect the change in data field names.

The full spec then becomes:

```json
{
  "width": 400,
  "height": 200,
  "padding": {"top": 10, "left": 30, "bottom": 20, "right": 10},
  "data": [
    {
      "name": "table",
      "values": [
        {"cat":"A", "res":28}, {"cat":"B", "res":55}, {"cat":"C", "res":43},
        {"cat":"D", "res":91}, {"cat":"E", "res":81}, {"cat":"F", "res":53},
        {"cat":"G", "res":19}, {"cat":"H", "res":87}, {"cat":"I", "res":52}
      ]
    }
  ],
  "signals": [
    {
      "name": "tooltip",
      "init": {},
      "streams": [
        {"type": "rect:mouseover", "expr": "datum"},
        {"type": "rect:mouseout", "expr": "{}"}
      ]
    }
  ],
  "predicates": [
    {
      "name": "tooltip", "type": "==",
      "operands": [{"signal": "tooltip._id"}, {"arg": "id"}]
    }
  ],
  "scales": [
    {"name": "categories", "type": "ordinal", "range": "width", "domain": {"data":"table", "field":"cat"}},
    {"name": "results", "range": "height", "nice": true, "domain": {"data":"table", "field":"res"}}
  ],
  "axes": [
    {"type": "x", "scale": "categories"},
    {"type": "y", "scale": "results"}
  ],
  "marks": [
    {
      "type": "rect",
      "from": {"data":"table"},
      "properties": {
        "enter": {
          "x": {"scale":"categories", "field":"cat"},
          "width": {"scale":"categories", "band":true, "offset":-1},
          "y": {"scale":"results", "field":"res"},
          "y2": {"scale":"results", "value":0}
        },
        "update": { "fill": {"value":"steelblue"} },
        "hover": { "fill": {"value":"red"} }
      }
    },
    {
      "type": "text",
      "properties": {
        "enter": {
          "align": {"value": "center"},
          "fill": {"value": "#333"}
        },
        "update": {
          "x": {"scale": "categories", "signal": "tooltip.cat"},
          "dx": {"scale": "categories", "band": true, "mult": 0.5},
          "y": {"scale": "results", "signal": "tooltip.res", "offset": -5},
          "text": {"signal": "tooltip.res"},
          "fillOpacity": {
            "rule": [
              {
                "predicate": {
                  "name": "tooltip",
                  "id": {"value": null}
                },
                "value": 0
              },
              {"value": 1}
            ]
          }
        }
      }
    }
  ]
}
```

With these changes the exercise for the reader proposed at the end of the tutorial (evolve the tutorial spec to an horizontal bar chart) would become easier and would probably end up in more people continuing to evaluate/use Vega.

**Comment by jheer** [comment]
Good suggestion! I went ahead and updated the tutorial page along these lines, making a few other edits along the way.
