### ISSUE TITLE
No propagation for subtle cross dataset dependencies.

### ISSUE THREAD

**Issue by jheer** [vega/vega#309]
Consider the force transform: it acts on a set of nodes, but also joins against a set of links. The link data may be updated with _source and _target properties that reference the nodes. Upon subsequent updates, if the nodes have their properties update in response to a signal (e.g., dragging a node), the links do not update in response (technically, the _source and _target properties are unchanged, only sub-properties have updated, so the pulse does not propagate). How should we address this?

**Comment by jheer** [comment]
Potentially related is the failure of field updates set on the changeset pulse to propagate through to other data pipelines (e.g., from Force [for nodes] to LinkPath [for edges]). This is being observed after a signal is externally updated via `view.signal(...).update()`. Afterward, the order of invocation [Force, LinkPath] appears to reverse [LinkPath, Force].

**Comment by jheer** [comment]
Some updates:
* The invocation order bug is due to rank changes induced by `View._streamer`, which should basically have -1 rank instead of the rank assigned to it by the graph's counter. So this is a separate, easily fixable error.
* The main issue here is that Force depends on links data, but also updates properties of links data. Operators downstream of links' pipeline might also depend on Force.

**Comment by arvind** [comment]
With the new Force+Lookup transforms, and with `View._streamer` having a hardcoded `-1` rank, I believe this issue is resolved. Please re-open if not!
