### ISSUE TITLE
Add support to set mouse cursor.

### ISSUE THREAD

**Issue by jheer** [vega/vega#314]
It would be nice to be able to change the mouse cursor upon hover of interactive elements or during interactive operations (drag).

Possibilities:
- Add a `cursor` encoding property to marks. This could propagate down for the scenegraph to handle.
- Add a default `cursor` property to top-level spec? (Really, for the root group mark.)
- Let these properties be driven by signals to support interactive update.

Questions:
- When in the midst of performing an interactive operation (drag, brush resize), how might one ensure that the cursor state is sticky (e.g., not overridden by the cursor setting for a mark that the mouse is passing over)?

**Comment by Jerrythafast** [comment]
I needed this for one of my specs. I worked around this by doing the following:
```js
view.on("mouseover", function(event, item) {
  document.body.style.cursor = is_clickable(item)? "pointer" : "auto";
});
```

But it would be awesome if I could just do `"cursor": {"value": "pointer"}` in the mark properties.

Just my two cents :)
