### ISSUE TITLE
Visualization `width: 'container'` does not consider the presence of a legend

### ISSUE THREAD

**Issue by ndimiduk** [vega/vega#3208]
I have a visualization which is a bar chart with a legend on the right side of the mark. When setting the visualization's `width: 'container'`, it's the mark that takes up the entire body of the container, the legend width is not considered. This is easy to see by setting the container to be 100% of the window size.

**Comment by domoritz** [comment]
Did you mean to file this issue against Vega-Lite?

**Comment by ndimiduk** [comment]
🤔 perhaps..
