### ISSUE TITLE
Request to include API for vega-transforms

### ISSUE THREAD

**Issue by roying** [vega/vega#3209]
_Background:_ The current version (v5.20.2) of Vega provide API methods for the packages: 
- [vega-statistics](https://github.com/vega/vega/tree/master/packages/vega-statistics)
- [vega-time](https://github.com/vega/vega/tree/master/packages/vega-time)
- [vega-util](https://github.com/vega/vega/tree/master/packages/vega-util)

_Request:_ Would it be possible to extend the Vega API to include [**vega-transforms**](https://github.com/vega/vega/tree/master/packages/vega-transforms)?

_Examples:_ 
- Add [_Formula_](https://vega.github.io/vega/docs/transforms/formula/) (calculated) fields to dataset
- Create new dataset using [_Lookup_](https://vega.github.io/vega/docs/transforms/lookup/) between two datasets

_Justification:_ Example use case is creating data visualization dashboards using third party datasets that have to be extensively processed. Now each time the Vega app is launched, the entire raw dataset has to be retrieved and processed in the VEGA _data_ block. 

With Vega tranform API, pre-processed datasets for Vega input can be prepared in javascript (using Vega API and other libraries) and cached on web server to reduce the complexity of the Vega spec and to improve performance.

**Comment by domoritz** [comment]
I think having an easy way to run Vega transforms outside of a Vega spec would be very useful.

One way to do it today would be to make a Vega spec that only has data transforms and use the Vega view API to pass the data through the transforms. I suspect there is a more efficient way using the [dataflow](https://github.com/vega/vega/tree/master/packages/vega-dataflow) package.

**Comment by jheer** [comment]
The Vega transforms _are_ exported as part of the Vega build, under the `transforms` object. However, there is no API for invoking them outside of a Vega workflow. One option is to create a Vega spec without any marks / encodings and use it to transform the data, but that is indirect and heavyweight. To simplify this, earlier I created a [vega-dataflow-api](https://github.com/vega/dataflow-api), but it has not been used much and I have not maintained it.

Instead, for stand-alone data transformation needs I recommend using [Arquero](https://github.com/uwdata/arquero). It is more full-featured, more performant, and hopefully you find the API enjoyable to use. Arquero tables can also be passed directly as input datasets to Vega and Vega-Lite!
