### ISSUE TITLE
Group children mark with single backing datum

### ISSUE THREAD

**Issue by floribon** [vega/vega#321]
For consistency purposes and easier dynamic spec building, it would be very convenient to allow children marks of a group to not define an explicit `facet` if they only need to use their parent data element.

Take the following spec, it is a slighly modified version of a public example where the marks are put into groups for more consistency with other charts (such as stacked bar).

This spec works because of the transform ` {"type": "facet", "groupby": ["_none"]}`

This transform is useless and a hack to make vega work. Don't you think it would make sense to display a mark that is backed by a single group data?

````
{
  "width": 500,
  "height": 200,
  "padding": {"top": 10, "left": 30, "bottom": 30, "right": 10},
  "data": [
    {
      "name": "table",
      "values": [
        {"x": 1,  "y": 28}, {"x": 2,  "y": 55},
        {"x": 3,  "y": 43}, {"x": 4,  "y": 91},
        {"x": 5,  "y": 81}, {"x": 6,  "y": 53},
        {"x": 7,  "y": 19}, {"x": 8,  "y": 87},
        {"x": 9,  "y": 52}, {"x": 10, "y": 48},
        {"x": 11, "y": 24}, {"x": 12, "y": 49},
        {"x": 13, "y": 87}, {"x": 14, "y": 66},
        {"x": 15, "y": 17}, {"x": 16, "y": 27},
        {"x": 17, "y": 68}, {"x": 18, "y": 16},
        {"x": 19, "y": 49}, {"x": 20, "y": 15}
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "ordinal",
      "range": "width",
      "domain": {"data": "table", "field": "x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "domain": {"data": "table", "field": "y"}
    }
  ],
  "axes": [
    {"type": "x", "scale": "x"},
    {"type": "y", "scale": "y"}
  ],
  "marks": [
    {
      "type": "group",
      "from": {
        "data": "table",
        "transform": [
          {"type": "facet", "groupby": ["_none"]}
        ]
      },
      "marks": [
        {
          "type": "rect",
          "properties": {
            "enter": {
              "x": {"scale": "x", "field": "x"},
              "width": {"scale": "x", "band": true, "offset": -1},
              "y": {"scale": "y", "field": "y"},
              "y2": {"scale": "y", "value": 0},
              "fill": {"value": "steelblue"}
            }
          }
        }
      ]
    }
  ]
}
````

**Comment by jheer** [comment]
Thanks for the suggestion! However, keep in mind how Vega semantics work: each mark is backed by an array of elements, with one mark instance (including group marks) per array element. So, handing a data set to a group mark can and should result in one group element per datum.

The facet transform you describe above takes the full data set and groups it under a single element. I agree that grouping on a non-existent property is hackery. A simple solution is to change the behavior of facet to group all the data if no "groupby" property is specified -- this would lead to a completely valid (non-hackish) Vega transform. This is already supported by the underlying datalib Aggregator, it is currently not being "fed" correct groupby parameters when they are left unspecified. I have opened a separate issue to make this change (#323), and am closing this issue for now (feel free to re-open this issue if we're overlooking something here).

Also, note that a different approach might be to provide pre-grouped data as input (e.g., data sets with collections of tuples contained as properties of top-level tuples). This was possible in Vega 1.x but is complicated here by Vega 2.0's more sophisticated data ingestion mechanisms. Some kind of (currently non-existent) un-facetting transform would probably be required, though @arvind would know for sure. In any case, given the choice I would advocate for including a facet transform as described above.

**Comment by floribon** [comment]
Thanks a lot for the feedback. I think the support of unspecified facetting will solve my problem.

To put it simply, I assume it is semanticly correct to have "one group and many marks for this group" while I wanted to have "many groups, each one bound to a single datum, and a single mark per group bound to its datum by inheritance". If that doesn't match vega semantics, and I would understand that it is the case, then your suggestion is best.
