### ISSUE TITLE
How to center each rect which has different width to x-axis ticks?

### ISSUE THREAD

**Issue by Shoutmon** [vega/vega#322]
#64 seems to be erroneously closed.

json input:
http://paste.ubuntu.com/12019602/
shown by vega 2.0:
http://7j1yhu.com1.z0.glb.clouddn.com/rects.png

As the input above, the width of rects binds the scale "w", so each rect has different width. I desire to center rects to each x-axis tick, but "offset" in property "width" can only be a number. Is there any solution to handle it?

**Comment by jheer** [comment]
This can be achieved by setting the `width` and `xc` properties for horizontal positioning (or `height` and `yc` for vertical positioning). For an example, see this thread on the vega-js discussion forum: https://groups.google.com/forum/#!topic/vega-js/nRBUV2npW80

**Comment by Shoutmon** [comment]
Thanks,  this really helps. But I didn't find "xc" and "yc" in the documentation before, when will it be updated?
