### ISSUE TITLE
Normalized Standard Deviation

### ISSUE THREAD

**Issue by keckelt** [vega/vega#3233]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Clearly describe the goal of the feature request. Why is it needed?
- [x] Describe an envisioned solution. What do you want the new behavior to be?
- [ ] If applicable, share mockup images or links to examples illustrating the desired output.
- [x] If applicable, share JSON spec designs for how the behavior would be made available in Vega.

---

Hi vega!

I have a grouped histogram of which I sort the facets by standard deviation (most varying to equally distributed, so to say).

However, I would prefer to focus on the relative variation within each facet, i.e., a normalized spread measure, as the values are unevenly distributed between the groups, e.g.:

![image](https://user-images.githubusercontent.com/10337788/120178429-ca551580-c209-11eb-8ed1-a1fc2cd356e2.png)
(Facets are not sorted here)

I suggest normalizing the stdev by the mean, as an `op: 'normstdev'`. I didn't see anything fitting in https://vega.github.io/vega/docs/transforms/aggregate/

Do you think that's something worth adding?

I'm also happy to provide a PR.

**Comment by jheer** [comment]
Just to check: you want to divide the standard deviation value by the mean? If so, you can do that with existing Vega transforms: compute mean and stdev aggregates, then use a formula transform (or `calculate` in Vega-Lite) to transform further.

That said, I'm not sure dividing by the mean will give you what you want? For example, what if the standard deviations vary across groups but in each case the mean is zero...
