### ISSUE TITLE
Expression and expression language are not documented

### ISSUE THREAD

**Issue by espinielli** [vega/vega#324]
(At least) in Data Transform > [Filter](https://github.com/vega/vega/wiki/Data-Transforms#-filter) `Expression` and `expression language` (pointing to `Expression`) are mentioned but no page exists to describe them.

My real problem is that what provided in for example ex_jobs.json in the supplementary material to [Reactive Vega](http://idl.cs.washington.edu/papers/reactive-vega) article is no more working/parsing.
In fact my attempts to transform

```json
    {
      "name": "jobs",
      "source": "jobs_source",
      "transform": [
        {
          "type": "filter", 
          "predicate": {
            "type": "or",
            "operands": [
              {"type": "==", "operands": [{"signal": "filter_gender"}, {"value": "all"}]},
              {"type": "==", "operands": [{"signal": "filter_gender"}, {"field": "data.sex"}]}
            ]
          }
        }
```

to something parsing in Vega 2.0

```json
  "signals": [
    {
      "name": "filter_job",
      "init": {"value":""},
      "stream": [
        {"type": "#textbox:keyup", "expr": "this.item.value"},
        {"type": "area:click", "expr": "this.datum.data.job"}
      ]
    },
    {
      "name": "filter_gender",
      "init": {"value": "all"},
      "stream": [
        {"type": "input[name=gender]:click", "expr": "this.item.value"}
      ]
    }
  ],


  "data": [
    {"name": "jobs_source", "url": "jobs.json"},
    {
      "name": "jobs",
      "source": "jobs_source",
      "transform": [
        {
          "type": "filter", 
          "test": "datum.sex == filter_gender"
        }
```

do not result in anything (error or visualization [well I got a black horizontal line for the year but no ticks nor labels...])

**Comment by espinielli** [comment]
Maybe [vega-expression](https://github.com/vega/vega-expression) could help as a start ... but that is more about the parser, the lower level functionality, rather the user-faced features.
Anyway it is useful to see where certain [functions](https://github.com/vega/vega-expression/blob/master/src/functions.js) are coming from (and how you could add more ;-)

**Comment by jheer** [comment]
Thanks! We've added content about the expression language to the Vega wiki here: https://github.com/vega/vega/wiki/Expressions

By design, there is no simple way to add external user-defined functions. While no doubt useful in some instances, doing so might also render different Vega specs incompatible, so it's not clear if we want to support this. In the meantime, if you believe a new function would significantly improve Vega, feel free to open a new feature request issue.

**Comment by espinielli** [comment]
Great!
I am now struggling to have the string matching working.
Any examples of regex test?
(I am trying to reproduce the jobs example with radio buttons and text are filters...)

**Comment by jheer** [comment]
Here's a simple working example that uses regexp test in a formula transform:
```json
{
  "width": 500,
  "height": 500,
  "data": [{
    "name": "text",
    "values": [
      {"comment": "between 12 and 12.43"},
      {"comment": "43 minutes past 12 o'clock (and 13 seconds)"}
    ],
    "transform": [
      {
        "type": "formula",
        "field": "test",
        "expr": "test(/between/, datum.comment)"
      }
    ]
  }]
}
```

To examine the output in the vega editor, enter the following in the console:
```
ved.view.model()._data.text._collector._data
```
As expected, you'll see that `test` is true in one case and false in the other.

**Comment by espinielli** [comment]
Thanks.
The last bit is gold ... I am in need for debugging tools/tips/tricks/...

**Comment by jheer** [comment]
Great! FYI @jhoffswell has been prototyping more advanced (visual) debugging techniques, but it may be a while before they are ready for prime time...

**Comment by arvind** [comment]
One can also use the [View API](https://github.com/vega/vega/wiki/Streaming-Data#view-component-streaming-api) to inspect data values like so: 
```
ved.view.data('text').values()
```

**Comment by espinielli** [comment]
Good. That is ok for Vega Editor.
For pure Vega in a browser I am just trying out `vg.debug.enable = true;`
