### ISSUE TITLE
Wide legend labels truncate on Firefox

### ISSUE THREAD

**Issue by kevreth** [vega/vega#3242]
Sufficiently wide legend labels truncate with an ellipsis on Firefox. This behavior does not occur on Chrome.

![Screenshot from 2021-06-09 12-22-46](https://user-images.githubusercontent.com/47391465/121298128-8bb40f00-c91d-11eb-9265-cb06d3515070.png)

<code>

    {
      "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
      "data": {
        "url": "data/movies.json"
      },
      "repeat": {
        "layer": ["US Gross", "Worldwdddasdfasdfasdfasdfasdfasdfasdfide Gross"]
      },
      "spec": {
        "mark": "line",
        "encoding": {
          "x": {
            "bin": true,
            "field": "IMDB Rating",
            "type": "quantitative"
          },
          "y": {
            "aggregate": "mean",
            "field": {"repeat": "layer"},
            "type": "quantitative",
            "title": "Mean of US and Worldwide Gross"
          },
          "color": {
            "datum": {"repeat": "layer"},
            "type": "nominal"
          }
        }
      }
    }

</code>

**Comment by wiibaa** [comment]
This does not seem like a bug.
The described behaviour is the same on Chrome/Edge, and the label is truncated because of the default value for legend labelLimit to 160 pixels, you are free to change this value in your spec to display your labels fully 

````
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "url": "data/movies.json"
  },
  "repeat": {
    "layer": ["US Gross", "Worldwdddasdfasdfasdfasdfasdfasdfasdfide Gross"]
  },
  "spec": {
    "mark": "line",
    "encoding": {
      "x": {
        "bin": true,
        "field": "IMDB Rating",
        "type": "quantitative"
      },
      "y": {
        "aggregate": "mean",
        "field": {"repeat": "layer"},
        "type": "quantitative",
        "title": "Mean of US and Worldwide Gross"
      },
      "color": {
        "datum": {"repeat": "layer"},
        "type": "nominal",
        "legend": {
          "labelLimit": 260
        }
      }
    }
  }
}
````

**Comment by domoritz** [comment]
Yep, this is working as intended I think.
