### ISSUE TITLE
Mouseenter Event Doesn't Fire Properly

### ISSUE THREAD

**Issue by ekh64** [vega/vega#326]
I set up a simple spec that has two streams, one on `mouseenter`, and one on `mouseout`. The goal was to have a rect change color on enter and leave. I'm aware this is possible on `hover`, but I'm working on something else a little more involved which requires these event handlers to work.

```json
{
  "signals": [
    {
      "name": "hovered",
      "init": 0,
      "streams": [
        {"type": "@testRect:mouseenter", "expr": "1"},
        {"type": "@testRect:mouseout", "expr": "0"}
      ]
    }
    ],
  "predicates": [
    {
      "name": "isHovered",
      "type": ">",
      "operands": [{"signal": "hovered"}, {"value": 0}]
    }
    ],
  "marks": [
  {
    "name": "testRect",
    "type": "rect",
    "properties": {
      "enter": {
        "width": {"value": 100},
        "height": {"value": 100}
      },
      "update": {
        "fill": {
          "rule": [
            {"predicate": {
              "name": "isHovered"
            },
            "value": "red"},
            {"value": "black"}
          ]
        }
      }
    }
  }
  ]
}
```

I was console logging where I believe the event handlers are registered in [streams.js](https://github.com/vega/vega/blob/master/src/parse/streams.js#L49-L53), and discovered when rendering in canvas, `mouseenter` doesn't trigger at all when entering the mark, instead a `mouseout` event happens. In SVG, there's a `mouseenter` event triggered upon entering the SVG, but not on the specified mark.

In the course of exploring this issue, I did discovered that `mouseover` works properly.

Hopefully this helps.

**Comment by jheer** [comment]
Thanks Erica! The simple answer is that `mousenter` (and it's sibling `mouseleave`) are not currently supported. The reason why is that those events have had inconsistent support across browsers for some time (see http://www.quirksmode.org/dom/events/mouseover.html).

In the spec above, replacing `mouseenter` with `mouseover` has the desired behavior. Also, even if it were supported, pairing `mouseenter` with `mouseout` (as opposed to `mouseleave`) may not give you the behavior you want.

With respect to canvas, only DOM events from the raw `canvas` element are being generated natively by the browser. All events specific to individual items must be inferred. If you're interested in this process, take a look at the [CanvasHandler](https://github.com/vega/vega-scenegraph/blob/master/src/render/canvas/CanvasHandler.js) within the [vega-scenegraph](https://github.com/vega/vega-scenegraph) module.
