### ISSUE TITLE
actions documentClickHandler memory leak  

### ISSUE THREAD

**Issue by pelikhan** [vega/vega#3273]
(This is a follow up https://github.com/vega/vega-embed/issues/733). There is a memory leak in the registeration of the actions menu in vega-embed. The document click handler is registered everytime the spec or data buffer is updated in react-vega; and it won't be garbage collected.

https://github.com/vega/vega-embed/blob/641b65e1bcbaaf2a2b70c783fc0fe1bdfb825d6e/src/embed.ts#L434

**Comment by domoritz** [comment]
I think you missed that embed has its own finalize call.

**Comment by pelikhan** [comment]
It is possible that a call to ``trackEventListener`` is missing for ``documentClickHandler``. I don't see where ``documentClickHandler`` gets registered into the ``view._eventListeners`` array. 

https://github.com/vega/vega/blob/02d79dddb2850a24abfe6a4ebaf8823548709bb5/packages/vega-view/src/events.js#L30

**Comment by domoritz** [comment]
My understanding is that the click listener is added by Vega embed and Vega doesn't keep track of it.

**Comment by pelikhan** [comment]
This is why the original bug was opened against vega-embed which seems to be the culprit

**Comment by domoritz** [comment]
But does the handler stay registered when you call finalize on the embed result?

**Comment by pelikhan** [comment]
So it seems that react-vega is missing a call to the vega-embed finalize 

https://github.com/vega/vega-embed/blob/641b65e1bcbaaf2a2b70c783fc0fe1bdfb825d6e/src/embed.ts#L513

When it recreates the view, it calls view.finalize but it is missing a call to the embed finalize.

https://github.com/vega/react-vega/blob/64502dfa5c99e4c76e8408087e53b951d471c1d8/packages/react-vega/src/VegaEmbed.tsx#L139

When a change to the spec triggers a call to ``createView``, react-vega leaks one documentClickHandler.

**Comment by pelikhan** [comment]
Looks like a dup of https://github.com/vega/react-vega/issues/383

**Comment by domoritz** [comment]
Yes, that's how I see it.
