### ISSUE TITLE
Join function gives [object Object] result

### ISSUE THREAD

**Issue by Kayak007** [vega/vega#3277]
Hi,

I'm using Vega 5.17.0 and trying to work with the **join** function:

**_# join(array[, separator]) ≥ 5.3
Returns a new string by concatenating all of the elements of the input array, separated by commas or a specified separator string._**

Here's the code: 

```json
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "A basic line chart example.",
  "width": 500,
  "height": 200,
  "padding": 5,

   "data": [
    {
      "name": "table",
      "values": [
        {"x":0},
        {"x":1},
        {"x":2},
        {"x":3},
        {"x":4},
        {"x":5},
        {"x":6},
        {"x":7},
        {"x":8},
        {"x":9}
      ]
    }
  ],

  "signals":[
    {
      "name":"table",
      "update":"join(data('table'))"
    } 
  ]
}
```

The result I'm getting for the signal is "**[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]**".
While I was expecting "**"x":0,"x":1,"x":2,"x":3,"x":4,"x":5,"x":6,"x":7"x":8"x":9**" or "**0,1,2,3,4,5,6,7,8,9**".

Can't upgrade Vega for now so not able to use the **pluck** function.

**Comment by domoritz** [comment]
I believe that's expected. Please use `join(pluck(data('table'), 'x'))` if you want just the values.
