### ISSUE TITLE
Vega Examples error

### ISSUE THREAD

**Issue by srinivvenkat** [vega/vega#334]
Hi, 

I use Vincent (https://vincent.readthedocs.org/en/latest/ ) package which uses Vega to draw the plot on iPython notebook. However, it only provides the functionality to export to .json format. I'd like to export it to svg or png. 

So I installed vega (via npm), and tried using the vg2png function as explained in the headless mode wiki.
I am running on Mac, with Python 2.7.6. 

I get the following error when I run the example command: 
bin/vg2png examples/spec/bar.json bar.png

Error: ENOENT, open 'examples/spec/bar.json'
    at Error (native)

How do I test if it is some dependency issue, or if vega is installed correctly?

All I need is a standalone executable that can convert the .json format (generated by Vincent inside iPython) to .png or .svg.

Thanks,
Srini

**Comment by jheer** [comment]
Vincent only supports Vega 1.x. If you are using the more recent Vega releases (2.x) your JSON specifications are likely incompatible. So I would start by installing an earlier Vega version ([v1.5.4 was the last 1.x release](https://github.com/vega/vega/releases/tag/v1.5.4)) and see if that clears up the issue.

**Comment by arvind** [comment]
The specific error you're seeing is because the file `examples/spec/bar.json` doesn't exist. We need to update the documentation to reflect that. Instead, you can use one of the test specifications, e.g., `test/spec/bar.json`

**Comment by srinivvenkat** [comment]
Thanks guys! Installing v1.5.4 fixed the issue! :)
