### ISSUE TITLE
Problematic default formatting of log axis labels between 0 and 1 in Vega 2

### ISSUE THREAD

**Issue by Jerrythafast** [vega/vega#335]
Dear Vega devs,

I am currently porting my Vega 1 graph specs to Vega 2. Some of those feature an axis with a logarithmic scale, and I noticed the default label formatting in Vega 2 is rather problematic for the axis domains that occur commonly in my applications of Vega.

Here is a minimal working example you can copy-paste into the Editor:

```json
{
  "width": 500,
  "height": 500,
  "scales": [
    {
      "name": "x",
      "type": "log",
      "range": "width",
      "domain": [0.001, 20]
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "domain": [0.001, 20]
    }
  ],
  "axes": [
    {
      "type": "x",
      "scale": "x"
    },
    {
      "type": "y",
      "scale": "y"
    }
  ]
}
```

This creates a horizontal logarithmic axis from 0.001 to 20 and a linear vertical axis with otherwise identical settings. Observe that all horizontal axis labels below 1 are "0". The problem worsens if the domain covers more orders of magnitude below 1. Vega 1 provided a more useful default formatting that would still yield unique axis labels (e.g., when the lowest value in the domain was in the order of thousandths, it would use SI-suffix 'm' instead; the lowest value would be "1m").

Also, in an attempt to fix this, I tried specifying `"format": "s"` to force using SI-suffices. This, however, did not help at all, since it seems Vega 2 uses the *upper* bound of the domain to determine the suffix. The problem would be solved if Vega would use the *lower* bound to determine the suffix to use, though perhaps the median of the domain would give nicer results. Or (the best option when covering many orders of magnitude, IMHO) each label could be assigned the optimal suffix separately, such that log scales could go from, say, milli-scale to Mega-scale with no difficulties.

Kind regards,
Jerry

**Comment by jheer** [comment]
Thanks Jerry. This is certainly not the intended behavior. We'll look into it. In the meantime, the following formatting string could work for your example: `"format": "0.3f"`.

**Comment by jheer** [comment]
Actually, you might prefer a formatting style of `".1r"`, which will probably be the new default for log scales in the next Vega release.

**Comment by Jerrythafast** [comment]
Thank you for the suggestions. `.1r` will suffice for my current applications. I definitely think that is the best default.

It would still be nice to see some more intelligent handling of hugely different orders of magnitude with the `s` format, but that might not fully qualify as a"bug".

**Comment by jheer** [comment]
Updated default formatting in b1379e9.
