### ISSUE TITLE
Export Visualization as PNG

### ISSUE THREAD

**Issue by vutukuriajay2241** [vega/vega#3356]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Describe how to reproduce the bug.
- [x] Use the latest Vega version, if possible. Always indicate which version you are using.
- [x] If you are using Kibana, first read the [instructions for posting Kibana Vega issues](https://gist.github.com/nyurik/736c34970ba3c32f3fe3d45d66719b3e).
- [x] Include error messages or gifs/screenshots of problematic behavior, if applicable.
- [x] Provide an example specification and accessible data. Try to provide the simplest specification that reproduces the problem. To share a specification, use the [Vega-Editor](https://vega.github.io/editor/) and click "Share" to embed a working link, or provide an example spec in JSON, wrapped by triple backticks like this:

```json
{
  "width": 500,
  "height": 200,
  "data": [ ],
  "marks": [ ]
}
```

Hi,

I'm attempting to save a visualization as a png picture. As I was trying to apply strokeDash to a mark, I was unable to export. It's causing an error.

Steps to reproduce the error

1. Use this [link](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQXEACOAA8kCHABs4OtgDMdAYSSLMCmkl0mkATzYNMEHZbaKOkg64mzyALQmNOIA1jqyzmSKRhbWMDRwyYqwNFBIJvFImFTSIADuNLL0aABsAAx1MvA0ZFhoAIz1jSA4SLIJ4mRoAjIQLeL5EGgA2qATCHBoIG5McCZTMsT5DIuomIo7MkzRsmig0TjeS7BwUDFMbPogAL7PUnNGu8seXpilWyYdks1LJ3KVjuJTqhzuJLn90MkEmxSmxVOopqhpiAQWCZFBARBHIoQABdV7vEDzL5RWIbEAAoHoBJIMgSfLgk5nEAXK7oCBrW5-GSotQSDFYmmLPEMRSkUrM1kTEwohwwNiK9lkt4fBZLfm9ZKiySbba7SyTOBHTnQ7mw3kgG53B5PV4kmSyIooTE6r77OBSkAy5VMz0ESxuRRwERiY3Y5LiCD+RQIGagTDuHBfQmGmiWXEgGJwMHoSqlA1wcSYADSRaW5crLwp6czwMjAYW9DCXLGZCVSzcniubxAYwAXrtZiPxuz0M1Wn9tVPezPypV6Dpwjp2g0Xm6R3ADUV1N3p8H94ejY2QEhxSB8093Qfqnj0iZZJHJGSyRSqf3ojE6TEGUoF9NtSn2FxEwCFNvWxDNQP9GkAMbNN4L-WJemfEAAgyBtZxw0cJGKZVRhgJAWxtHs+3QJCpldZ492gfIFFTSlPmuNgTACcC0Jo6I4HsUp4zIXZQC4RAvmQMhkCvWQ2GQaIuQ9YpW39UpLAyN8lnkVQYCvcdFGRPYDjgBiZGQRRkNg5svkwvSZEsQyYNAZSvWWf86JkCsoDCUTAxwZS-LsrkNLWKEeiKPTh2zNhCy5BkvgAYigFKrxiwsABEbz0yjTyWdoXleRcbL1dwEAeEiQEc+SlM9VTFmHbzfK5CsiRPcd4tNDoGmi-ZYr8hKlkSywRsKmQGACoo-KeG1Qq09AXRkYtQDm8KwWHDSTGDMS8jMDiuOJBzNPCnTqiK4reOxAwhSqpzapU9A-QarzxB8+QWsrTIuUcfR4RW46ll-DaiIAZRoDqbUG1AAE5hyYG81n4zrAUkypZD28l-MCrkZv+sKlkWu8QoB9B1vdXGl2ouQigYBBKByN8Px0AB+DcAHYdFQHQ2avfJxhPZcz2U2n6dfd8KxZnQAHJlHnKXOelsxLEwKWr1RJAoDoZbKZXFY1l8Vn2gVupCvooA), where I created a small code snippet to reproduce the error.
2. In line 69, I changed the strokeDash value to 1 after opening the tree visualization which is available from [Vega](https://vega.github.io/vega/examples/tree-layout/)
3. Then I tried to save the rendered visualization as a png file.
4. I used the developer console for the above mentioned step, and then ran the following code to export as Png.

```
VEGA_DEBUG.view.toImageURL('png').then(function(url) {
  var link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('target', '_blank');
  link.setAttribute('download', 'vega-export.png');
  link.dispatchEvent(new MouseEvent('click'));
}).catch(function(error) { console.log(error) });
```

Then I got the following error.

```
TypeError: Failed to execute 'setLineDash' on 'CanvasRenderingContext2D': The provided value cannot be converted to a sequence.
    at mt (vega-scenegraph.module.js:1662)
    at $t (vega-scenegraph.module.js:1762)
    at vega-scenegraph.module.js:1739
    at yt (vega-scenegraph.module.js:1709)
    at ui.<anonymous> (vega-scenegraph.module.js:1737)
    at ui.draw (vega-scenegraph.module.js:3688)
    at vega-scenegraph.module.js:2075
    at yt (vega-scenegraph.module.js:1709)
    at vega-scenegraph.module.js:2074
    at yt (vega-scenegraph.module.js:1709)
```

Please try to resolve this as soon as possible. Please let me know is there any way around to export as png with strokeDash Property.

**Comment by vutukuriajay2241** [comment]
Are there any updates??

**Comment by roying** [comment]
According to Vega documentation for **path**, _strokeDash_ should be "an array of [stroke, space] lengths for creating dashed or dotted lines."

https://vega.github.io/vega/docs/marks/path/

Changing your Vega spec to

` "strokeDash": {"signal": "[3, 3]"}`

shows the correct rendering of dashed strokes and no error when exporting as png image file.

[View in Vega online editor](
https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQXEACOAA8kCHABs4OtgDMdAYSSLMCmkl0mkATzYNMEHZbaKOkg64mzyALQmNOIA1jqyzmSKRhbWMDRwyYqwNFBIJvFImFTSIADuNLL0aABsAAx1MvA0ZFhoAIz1jSA4SLIJ4mRoAjIQLeL5EGgA2qATCHBoIG5McCZTMsT5DIuomIo7MkzRsmig0TjeS7BwUDFMbPogAL7PUnNGu8seXpilWyYdks1LJ3KVjuJTqhzuJLn90MkEmxSmxVOopqhpiAQWCZFBARBHIoQABdV7vEDzL5RWIbEAAoHoBJIMgSfLgk5nEAXK7oCBrW5-GSotQSDFYmmLPEMRSkUrM1kTEwohwwNiK9lkt4fBZLfm9ZKiySbba7SyTOBHTnQ7mw3kgG53B5PV4kmSyIooTE6r77OBSkAy5VMz0ESxuRRwERiY3Y5LiCD+RQIGagTDuHBfQmGmiWXEgGJwMHoSqlA1wcSYADSRaW5crLwp6czwMjAYW9DCXLGZCVSzcniubxAYwAXrtZiPxuz0M1Wn9tVPezPypV6Dpwjp2g0Xm6R3ADUV1N3p8H94ejY2QEhxSB8093Qfqnj0iZZJHJGSyRSqf3ojE6TEGUoF9NtSn2FxEwCFNvWxDNQP9GkAMbNN4L-WJemfEAAgyBtZxw0cJGKZVRhgJAWxtHs+3QJCpldZ492gfIFFTSlPmuNgTACcC0Jo6I4HsUp4zIXZQC4RAvmQMhkCvWQ2GQaIuQ9YpW39UpLAyN8lnkVQYCvcdFGRPYDjgBiZGQRRkNg5svkwvSZEsQyYNAZSvWWf86JkCsoDCUTAxwZS-LsrkNLWKEeiKPTh2zNhCy5BkvgAYigFKrxiwsABEbz0yjTyWaYAGYpB0AqSReV5FxsvV3AQB4SJARz5KUz1VMWYdvN8rkKyJE9x3i00OgaaL9livyEqWRLLCm8qZAYAKij8p4bVCrT0BdGRi1AFbwrBYcNJMYMxLyMwOK44kHM08KdOqCrKt47EDCFBqnOalT0D9NqvPEHz5C6ytMi5Rx9HhLbLqWX89qIgBlGg+ptcbUAATmHJgbzWfj+sBSTKlkE7yX8wKuSW0GwqWda7xCsH0F291iaXai5CKBgEEoHI3w-HQAH4NwAdh0VAdB5q98nGE9lzPZTmdZ193wrLmdAAcmUecFf5xWzEsTAFavVEkCgOhNvplcVjWXxufaNW6nK+igA)
