### ISSUE TITLE
Documentation formatting changes (low priority)

### ISSUE THREAD

**Issue by smclements** [vega/vega#337]
Hello,

I have cloned the Vega wiki, and have been making a few formatting changes to the existing documentation. The changes are primarily around the display of properties - I am showing them in a table to get a reasonably consistent layout (using github table markup). I was wondering if you would like me to supply my version back to the project (I don't think there is a pull request option for the wiki)?

I have attached a screen shot that shows an example of the change in formatting. I have worked through all (I think) of the current pages and have changed the inline name/type/description entries to display as shown.

cheers, Sean

![vega_wiki_format_example](https://cloud.githubusercontent.com/assets/466590/9427096/139341d8-49be-11e5-9198-d07cedbdc0e9.png)

**Comment by ajturner** [comment]
This would be useful. Some projects put the wiki in a GH repo so that it has normal versioning. Then use Webhooks (e.g. travisCI) to push merges to master to the origin wiki.

**Comment by smclements** [comment]
Thank you - that sounds like a good idea. I will setup and put in a pull request sometime during the next few days.

**Comment by jheer** [comment]
Thanks! This looks good to me and I'd be happy to see the current wiki refined to use the table formatting. @arvind, any other thoughts on this?

**Comment by smclements** [comment]
Thanks Jeffrey. I have taken @ajturner suggested approach (have created a docs folder in the repo and have made the wiki pages discrete .md pages), with the hope that it will make it easier to track the documentation change. 

I am not sure how to structure a task to take the pages and move them into the wiki (as mentioned by Andrew). If you would prefer to keep the documentation (only) in the wiki, then it should be straight forward enough to edit the existing wiki pages and paste my changes over the top.

The styling shown in the original screenshot probably makes the table styling look nicer than it will in the github wiki (just setting expectations accordingly :-) ).

Just watched your keynote at OpenVis Conf - great stuff. I like the work that you demonstrated - you and your students are doing a great job.

cheers, Sean

**Comment by arvind** [comment]
This looks good to me, thanks for taking it on @smclements! I think it makes the properties much easier to read through. My only concern with the approach @ajturner suggested is changes flowing in the opposite direction -- i.e., how do we ensure that if someone makes a change directly to the vega wiki (e.g., via the online wiki editor interface on GitHub) that these changes propagate back to the repository?

For simplicity, I would be fine if you replaced the appropriate parts of the existing documentation with your updates in situ. Once done, I am happy to go through and verify that nothing was lost in translation :)

**Comment by smclements** [comment]
@arvind, I have updated the wiki in situ with the table formatting. Would you mind performing a sanity check :-)

cheers, Sean

**Comment by arvind** [comment]
Just did a once-over on things, and everything looks great to me! Thanks very much for the contribution, @smclements. Referencing properties is a whole lot easier now :)

**Comment by smclements** [comment]
Thank you @arvind - I appreciate you checking this for me. Cheers, Sean
