### ISSUE TITLE
Catch error with undefined field names with a .

### ISSUE THREAD

**Issue by jwoLondon** [vega/vega#3370]
The following fails to render because the lookup field (`y.y`) contains a dot  ([editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoGsrQBGJQA8LABgC+Ck2dQAma2lcOnIU2gDMHqj+DgC6jiCYAE5IshAAZmxRCEaggmxsANYMOGi+ZkrxUWwpmipqGlo6egaoxvkWSgCelE0B3s6eza2eHQ3B3W2o5mERmXBDDYU0cILKtYYgLW3h9qFKcLJQbMo0smRooDZl8TNzeTZKmE04cHkAjgyxmHRqNKQgEUOgp7MuS4pIjc7uhHs9Xi8PvYIsgopk8lAaFEoII7vYgA)).

It looks like the field name isn't being escaped as it generates the error `undefined is not an object (evaluating '_["y"]["y"]')`

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"id": 1, "x": 10},
      {"id": 2, "x": 20},
      {"id": 3, "x": 30}
    ]
  },
  "transform": [
    {
      "lookup": "id",
      "from": {
        "data": {
          "values": [
            {"id": 1, "y.y": 30},
            {"id": 2, "y.y": 20},
            {"id": 3, "y.y": 10}
          ]
        },
        "key": "id",
        "fields": ["y.y"]
      }
    }
  ],
  "encoding": {
    "x": {"field": "x","type": "quantitative"},
    "y": {"field": "y","type": "quantitative"}
  },
  "mark": "circle"
}
```

Note that escaping the reference to the lookup field `y\\.y` does not solve the issue although it simply fails to recognise the field rather than exit with undefined is not an object error.

**Comment by jheer** [comment]
Hmm. AFAICT, the error is coming out of the lookup transform when it tries to access a sub-property of an undefined property. While we could catch the error and return `undefined` this would still result in a broken visualization and without the benefit of any error messages to convey that something went wrong.

Vega follows JavaScript conventions: accessing an undefined property leads to `undefined`. Trying to access a property of _that_ results in an error. I'm closing out this issue, but happy to consider a subsequent issue or PR that might improve error messaging.
