### ISSUE TITLE
Cross and filter in one step

### ISSUE THREAD

**Issue by Jerrythafast** [vega/vega#338]
Dear Vega devs,

I have a large data set which I would like to cross with itself, but I only want to retain a very specific collection of results. An example: suppose our data consists of the names of all cities on Earth, along with the name of its country and the name of some category (e.g., 'metropolis'). So we have fields `country`, `city`, and `category`. And now I would like to obtain a data set that contains all possible combinations of two cities that are in the same `country` *and* `category`.

In theory, this will do:
```JSON
{
  "data": [
    {
      "name": "x",
      "url": "cities_of_the_world.json",
      "transform": [
        {
          "type": "cross",
          "diagonal": false
        },
        {
          "type": "filter",
          "test": "datum.a.country == datum.b.country && datum.a.category == datum.b.category"
        }
      ]
    }
  ]
}
```
In reality, that doesn't work. Let's say there are 10,000 cities in the data set. That means this `cross` transform will generate 99,990,000 results, even though the `filter` transform would subsequently drop almost all of them. The actual result is that you run out of memory well before the `cross` transform finishes.

Therefore, I would like to request a `filter` argument on the `cross` transform such that only the results that match the filter are actually generated. I.e.,

```JSON
{
  "data": [
    {
      "name": "x",
      "url": "cities_of_the_world.json",
      "transform": [
        {
          "type": "cross",
          "diagonal": false,
          "filter": "datum.a.country == datum.b.country && datum.a.category == datum.b.category"
        }
      ]
    }
  ]
}
```

(By analogy, in SQL when you `JOIN` two data sets together you can avoid this problem by filtering using `ON`.)

Kind regards,
Jerry

**Comment by jheer** [comment]
Thanks for the suggestion. Indeed, __cross__ is intended only for a true cross product (e.g., when creating scatter plot matrices, you want to cross a field set with itself). It is not intended for general joins (though we do provide the __lookup__ operator for one-to-one or one-to-many joins&mdash;but not many-to-many).

I'll interpret this issue as a feature request for a full-featured __join__ operator.

**Comment by Jerrythafast** [comment]
That's exactly what it is! Thanks for the comment.
