### ISSUE TITLE
node-fetch dependency version bump to fix vulnerability

### ISSUE THREAD

**Issue by Gusis93** [vega/vega#3399]
There was recently a vulnerability found in node-fetch: **https://github.com/advisories/GHSA-r683-j2x4-v87g.** Seems like the dependabot is trying to bump the version to fix it but the PR automatic checks are failing: https://github.com/vega/vega/pull/3398.

Is there anyway to check this and merge it? Thank you to anyone that can help

**Comment by jheer** [comment]
Thanks! The next Vega release (5.22) will include the latest 2.x version of node-fetch, which includes a fix.

The dependabot bump fails because it tries to move to node-fetch v3. This creates build and deployment issues due to node-fetch changing from CJS to ESM.

**Comment by Gusis93** [comment]
Thank you for the reply
