### ISSUE TITLE
TimeUnit transform created signal's extent properties not updating when data changes

### ISSUE THREAD

**Issue by roying** [vega/vega#3400]
Vega [TimeUnit](https://vega.github.io/vega/docs/transforms/timeunit/) transform:

> If defined, binds the computed time unit specification to a signal with the given name. The bound has object has unit (the smallest time unit), units (the array of all time units), step, start, and stop properties.

Issue: The signal's **start** and **stop** properties do not update properly when dataset data changes.

See example of issue and workaround using Vega transform _extent_ at:
https://stackoverflow.com/questions/70740136/x-scale-does-not-update-sometimes-on-signal-change-in-a-vega-chart

**Comment by jheer** [comment]
Fixed for v5.22.0.
