### ISSUE TITLE
Changing Axis  Doesn't Resize Axis Labels

### ISSUE THREAD

**Issue by EthanVQ** [vega/vega#3402]
Hi there,

We are hoping to build analytics tools where we can change the x or y axis to look at combinations of variables within the data. This involves changing the variable along the y axis in our case. This prevents the need for an independent graph for each combination of variables.

What I have noticed when changing the variable using a selector, is that the axis labels for the axis that has been changed does not get resized. You are left with labels being trimmed off to the left. In a stripped back example you can see this occuring - link to my example graph is [here](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGgxwaZLGgEAGZTIDuNACb0lqmVAkAzeWlABrGkyTiUqUACc4ETGycBlebYA2ANSTeDM4A8uIASnBGThAwaJgOQQYS8WzeEAAybFBImOyS6A7yigC+xTJaOXYA2qC2CHBoIBWYKDLEAUEQaDUgJg4uAPp1DejCbDCSMgjaWt5wQ0j1jVBzzg0y3kiDw41j4s4gZaB924sjIEyFNtIg01qz8zujZ10bW5gLS6MSB0e9NP0Pk8QGMJjc7g9PudkA5zDdNqcviBcghDlJjgDEedXKipjM5lDGt4JGQAAQQuaknZvLGNFFojGAwnoJAVXG3fGPM6NODqa40oHc9DE8RkiAMBw7YoAXRk8RsECMblRqB6mAAnjhzkqHAgGJsbnAAB44ByNGhGAAUEDgcygrgcAF5HQAdf5M4ZuqSk5oMBCUE6C+rei3W21we1uZ1uilc+pen05P2UWNQkNWm12h3RkAIoNwBO+-15tOkowBG0ASmrNy2jXaZr+Gq1jSQZDITgomHWIA7bAYOCY6u6IAbIFlIDYeBHhgY4kw45kddVTSyA1n8-HMplMggXgr3VqQpAmYjDpu7UC2sx+ZuTBo4i0ZhAD5wDAX6FP9puU9yEi6K6BoSeL3AS1K5u8hLSqU6IgMCmg6LEMgDs05wIfQAC0ACMABMyiHBO0ABAcqpHkiRo3M25zWI+NwODYZDnPARQLjIOCsloD5kGgyiUMoAjlGwyAPs+zR2E0lQ3CYtpPugY4wWR5zDnKmrnN4D5wEgZoyPRopodouiCcJ+SgGJjRmTI0neLJq5QOu-abqUE5IEaJE9G4NBwJuwqRKxJ7ZHMjQUX8HleR+FxsNgQk3ERgXoMOO63Fp5gAWqqmNE436WQ40X2BJLTmZJZQgF5hhaCMoAoTkFUgMOeVWTZY67gF5zBTIFH1Z51nmWuG5+bFSlorILHPgNQV3jYslYcVRo4aNLWNMpo4dCMyilE5xRAA). It seems to stick with the original sizing, but does not update when the variable changes - I have tried many workarounds but none of them seem to work. Since I'm using kibana the only way to do this is if I refresh the page, this would require an entire refresh which can be slow.

Original Render
<img width="578" alt="Screenshot 2022-01-31 at 12 24 42" src="https://user-images.githubusercontent.com/72455159/151793414-c6c8e6df-63c4-4b94-8f39-abe8ac17c3df.png">

Changed the variable in selector. The bottom name is trimmed.
<img width="567" alt="Screenshot 2022-01-31 at 12 25 09" src="https://user-images.githubusercontent.com/72455159/151793468-beb6206b-de4e-4213-9752-b43c2e9674d6.png">

I had originally submitted a ticket to kibana but it seems like a Vega issue hence why I posted this here.

Kind Regards,
Ethan Jones

**Comment by domoritz** [comment]
You have to either call `view.resize()` to set [`autosize.resize`](https://vega.github.io/vega/docs/specification/#autosize) to true. We don't do this by default for performance reasons.

**Comment by EthanVQ** [comment]
> You have to either call `view.resize()` to set [`autosize.resize`](https://vega.github.io/vega/docs/specification/#autosize) to true. We don't do this by default for performance reasons.

Many thanks, works as expected.
