### ISSUE TITLE
[SVG Renderer] Error: Node.insertBefore raised on dynamically filtered and faceted groups 

### ISSUE THREAD

**Issue by ebolyen** [vega/vega#3411]
This issue does not appear to occur in the canvas, only SVG.

Basic pattern:
1. Fold the penguin dataset into yKey, yValue
2. Fold the result into xKey and xValue
3. Filter the very long dataset into matching yValue and xValue
4. Create group-based facets on yKey.

[**Minimal example**](https://vega.github.io/editor/#/gist/1b002dbb5f9ea9d1566bcaa8cb203c8c/spec.json)

Steps to cause the issue:
1. Set the renderer to SVG mode
2. Change `y_axis` signal to any other value
3. Change `y_axis` signal back to the original
![image](https://user-images.githubusercontent.com/3976804/153928004-4c3405e1-5a6b-4813-8e61-398185cf8db4.png)

After this point, changing the `x_axis` will cause the points to re-appear (row labels will still be missing), and changing the dimensions (`child_height`, `child_width`) will cause all element to re-appear correctly.

**Comment by jheer** [comment]
Thanks! Fixed for v5.22.0.
