### ISSUE TITLE
Support Ability to Create Packed Bubble Chart

### ISSUE THREAD

**Issue by PBI-David** [vega/vega#3416]
I'd like to suggest an enhancement to support packed bubble charts like the one below. 

![image](https://user-images.githubusercontent.com/86846675/156037434-bc48a093-fe3b-4b4c-bff6-cbce44de67ac.png)

There are a couple of workarounds using existing functionality (that I'm aware of) but neither are ideal or practical. It would be a better experience to support packed bubble charts natively. 

The first option is to reuse the circle packing logic as per [#2054](https://github.com/vega/vega/issues/2054). However, the drawbacks with this are the need to create an invisible null parent so everything can be nested as well as a needless tree transform. Every datapoint also requires a parent field which is redundant in this case.  You can see an example [here](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAB3GgBN6aABwAGNTPg0yWVRplIGmNhBoAvOGhA4kC6SAVJMKVAG1Q4pAivpMAJzgrGWIkABsGOAg0DxBFNABGGS8fawdbQPFMNHEGMLCZQLDnGlIAfSQmBnEncShfBI0AXylQeNQEgHZNEBTfEAAFQOI2TDh8pAACKDYcfxpJgBEAZQBZSYSVACY1AQc+ipqKqpqkOv6huBGxienZ+aW1je3d1EmtgDZKAE5OyYBSdJITLZDqFcYlcqVaq1epoT4-ToAFhULTa9lQKg+yW8-QAQkgoGN-GxFFFJsQ8hRMAwIJMBgBhASNfa4w4KY4ws5w9AEolwElkumUsLU2n0pmNN5IygAZg+AKBIMS4OKmFKcE5p3OaBl8sa30NRuN3wEaLiGISSKRONS6AAYkg4FBwjQmITiTQGAhJnMjBBxHRzDQFgAZLYAWg+rJ87K1sP6judrvd-Pm3t9-n9gcwwbDkY+0soCQEipkGTgWRVICKkM10O1PJlJdlZtaFsSAm+tvxHoFpIU5IgOEokyRZVlZSRnXtAEFZ2UGGVsj24w2E9Y+cSB0OR2OJ1OZ-PF8u3rLKJ0FYDy8DK6CkjWIeqoScN6hz50BB8Pub2tjeri1gAErejQ4hsDMUBQOKw6jgIZQJBO3x4nOC5LiuAGxmcHLrty-QgQgYEQRB0F0rBkzwYhsrIahJ6YGelBqN8ZY2LeVZgo+aoavGeFoOeagqN8P7tu0CSyioPbWMsxjEuMxSTLIdgQLIbD+PQlZmHSWwIWUXYofOMb1kcuE6ug0nYAKclTIpCjKap6niJp7w6XpqEMWoWwsRW7EPrWz71q+vHvoxOydL+GIfDamH4sUxg0NZcAAB5hAKTqPOsCTfCoAhqIZa6BaZIB4rF6oJclqVwOlGxZTlbxbD8CReWx96qnWPGmfV3xMRoPW9T1srhfCWySbyfaCoOdLVDQABmqmEXSs4ACoMgykwqEi3xbHl2HtTyRVjTuk2BrN-jzZMS0rWtG1bHVlAqLKTXKhxfncSZPL1dsnRhSJEXDdFm4HUKkzIBAZhhDQGk0HSeLrR8spIpMAC8kyLTQCASJVsPw0jVVdB8nTMcjABSDIZbKWxbLK23GQVe1bv2QMg2DEOOVDkww0icMI8jqPo+ImOc9jyMrBll4EzjJNkxTsq3UijXXqxT2+U+r20749VIrsqI-aoUV9ADaaHZM01OlAbOrLORNbJ01M4WrBvbkDJvOublvW7dJaPXe1YvS+XIdcWSICBtJomt96Kdp0I37YbQNQMU-jigAmgAkotGw7F+tu7b2scTdMCfJ2nGe7IW7yMSoXs+a1-k5-CFfWoNHSyrK0duAAoswY1eggAC6kwwOE4MLCLkwtwIVOrjtb39B3Xdpj3-eD-kIZVePMsbHdV5Kt7z0q37jYNFvZq9zIARnBAJ0IDEoCYAAnjg-QQOf6rTXfDgANZwO-6DxDeIIAGlv7WG8tkc099H4gMJB-Bw00IZhAxJxNqM8gQKAUGBMgaAo4gDMJYG+OCdBeDCNYeQSgYAgHNGYMgRDrDaF0GA0+OD7JoFAHA8YiDfYBX9nCGQqlBz+GsBNeoNQMEUKaL3cRMhoDhCiPg-W6AZhhFUg4CB-Q+FgXCA4BQbBkBgRYY4ZwrgQABCCLA+BiDBw4GUC0GsZwyC+DcHIGAdBgggAAMT2ntAyZCVMJGMOQP4D+0R3C3wfk-O+CAmBsGITIaaJJr6oFAE4Fw1gTFWBsZWGYg59F3gFPoiAg9IGJJAKECI-Qzb+Hjuk2JNB8j5JdClawijlE1PYYIuAVjyE2JMNE9UOB8mEM0egZJ3pKB9EmAAakmCMhAlBOF1yaDYhgOBkm+FAIlfRbCEHWA2TYn+rDzHWHfjY3BayCHUKGSABGAAqaZzhRn+EmLcmZcyKFSICGwL++jSmRBIc4sYbycEfK-gAdUUMoYpPzfBqEoGaRZ4CwmpKShhOJOj9HJKMWkwFmS2DZOKbkgRxSxiJVBActp6ADjT3tjY2aWRlgWDOVC1QNj3QQHGGBRl4RfnoEImgxpiyZDLNWfojZxStmIN2TIfZIBxVHMBQoUVoAqE0PQAACheSlaamAzCDkmAAfkmBGRqbwEgAEpAV2MacU5VlyNVwC1TqyqBqXmWsqm8F14gyD8sMODahAyLnEOGfc2ZmrtVkn1ZMAA5MI4kkbJhvGjQSyNYjFkSKAA)

Final result:

![image](https://user-images.githubusercontent.com/86846675/156039161-3af37924-2bc7-411b-a47b-66e33ba56d03.png)

Stroke enabled so you can see the null parent to hold the children. 

![image](https://user-images.githubusercontent.com/86846675/156039280-7dc9bfb1-112e-4868-956b-9293019a731c.png)

The second way is to use the force transform as referenced in https://github.com/vega/vega/issues/1076 but this is not something I could get to work. I'm sure it is possible but the best I could get was is per the online editor [here](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAB3GgBN6aAJwAGNTPg0yWNAIBMmkEgaY2EGgC84aEOIm2ZCpJhSoA2qHFIEt9G5MADZOIMRIQQxwEGheIFCu5GwATgCedgCC0iYIbAzimGhqlAYAHAC+UqAJmElpdgBC2b55BUWUAgKV1YlkKenoAMLNufmFqMUALADM3fG9-XYAIiOt48UqAIxzNXUDIACiq2PtpdtV87V99egAYsdtEx2zF7vX+wDiD+uUmyo7CxuIAAEt9TgB2coAXWhMmgEWisW8vn8IEsNmyCjYyBoklQoBcbjsgRC2QAZjQ4EEFHYWidKiBkkhxGR-B5NhpNAJOTCLj4-HYoGwgilsphUjhUUFcXAkMlsuIaFB-JhklFnNikLi0ATXO4QCTQhSqTT0HS2gymSzUUyEDgQLCQMhkgBrGKeZEC9BQGjJKAhGIycWSuwQVIIJjC8nJbE6kCE-WGh0yODiIUKfygVO1eX4tHWTNohKk9Doo2U6m00YWmQUoJBOPwkvxYWi2sV005NbJtGqtguwvhSKo2QwOi2BnmYWYGj2vOWMg+BvoQkMBCUc2FcrboNWiBklIIJEGiWog9+0IQNwzqBoVXqkDn5XuuJP1FC+uKUJMhQ0BjurMAA8cFzNEAEdkkwAAKVd1zLABKAACAhEIMB05jfQVszgeUZEAtBJm5GQBgMbloXIi5g1RWpAMKGRcRzJAoBnUg0DJCIIDgWsYyPPME0FX1-URBlU3TQtsNzUAIh0PFQCHKIsIKHCeyYJBOOlcRBwiBT0AQRQFFJBkDwKABlAs43k-xNheR8JEwAB1OAdD0PNLLsSNK0nOBaLjY1KxXVw10oN5Fh3EAGBwQlC3wvM-M7fCGQGUA4rsdJt23GEgA).

Can one of the experts let me know if I'm missing any other ways to achieve this chart type and if not, which is the better of the two options I have described above?

**Comment by PBI-David** [comment]
I finally figured out how to create a packed bubble chart using force transform.

![image](https://user-images.githubusercontent.com/86846675/157333361-41b110e7-a8f7-4eb0-97bc-3c43941aeae1.png)

For those who want to recreate this in future, here is the [editor link.](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAB3GgBN6aABwAGNTPg0yWNABYNMnEgUKa4smlAAbOADNMaATIBOOvahchMbHGgAmTRAmNmw2BDQ1AF8ZJAZfCBoALzg0EHEJNJkksnEkGwg0AG1QfIQ09CgAD2kQBhwFJExKuUV6AAICDoCQWLKkCvSoAE86hqaW9O1dTC6evqkBofQyVyRiOhGADTriAoZKtUoAmSYLBWsQCxwE9PXLbJAECyiZZFrUAEZo-ozB1prDZbACaewOR0oXzOFyuNzu6AeZCeL0kqGCHzQP2iAF0ZJMUKhSv8Vj4kEw7OCbIcikTQFBmuQ2K4xugAIJ1QZsBjiJzok4qP4MlpkZmskAAIU5CG5vKilAEAiFjNFLPSAGFpbK+cd9ABmZUisXpAAiWp5OsoAE4fksQMKmWr0ABRc1y-kqW30lXG9AAMTdloEBrtDtV4oA4oH5V8rYbHeKABLRj0AdlxuJyDLstOJ5VaSVSdQUESQr1QoAJ6Uw5MpMnsNDgNku6C5FsWICRlWKXyMeo0ahxf3zwzYNmZdUwIxwrWZ5nyNmLpfLleahLJFKeDabLftPrVsU7SEe90G-kzzyQrgA1rnlq1Mgo4EUZFOZ+kICMEKFF-XXBErirdAa03Ds4HEKA2CfK5wJaVwrgbGxFwrEBoAKVpIPHeD60bZthn3MZD2qew2CgBhaVAXIF2GWpDxGEiyIo1CdGoqpCMPCZGSuQtKkoliCnSHA2FkAAKAIOgAKg6SYGAQSg215KQegASjqNDKXQHiOwgTB-2vXiQH2alWlkGA6DSQ8dL0uAAHV2hgK4jMOLFD18MdMBofwUKogT0BkyJflch4IBI1xIjpHxp1aUKoCecz1g8iRaV7YIdOaGgoDQewCggOB62ZWK7xAGKMLHGxFDiuD0qSwI3FMGhyJg6ocHgzSAEdXEwET-MoHjlPmXpfjtErhlguBsJAT5DGCVkghiYaCtaWoZE+SaGManJdPAshlG8-jkJAIFNinXYhtAEb0DGGRxXo0iNtQrbLF2vi8l8w71mOkYwV+IchztN9WhaaonD-ACUKAjIoOfMCIKhmDeXGq4ChYxyIVGhH4MPJgkFy8rxAMpzWheMxKUPEjeQAZRSAm0e+JV8t5Gy4A8PlQEJ9If0uMmaCQ1HjPSUzzI7IHWeK3Ddx6sNjSG+pGi4lDPnO8X0lo66EOVy6+kCocgA)

I think this can be closed if the devs agree although a simpler way to recreate this would still be useful or possibly consider adding this example to the official docs.

**Comment by domoritz** [comment]
I think this would be a cool example. Could you send a pull request to add it to the example gallery?
