### ISSUE TITLE
Incorrect Extent and Scale for Vega/Vega-Lite time values

### ISSUE THREAD

**Issue by alexkreidler** [vega/vega#3419]
I started with a Vega-Lite spec like this: [Vega Editor link](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtBmx5CBWhEzU6jJgwhxtUOZjizzDhASSC4ADwDW2uBplL20CACYADihlCIBmAAYAdjDEqDgxKAzYpHSANgAWJAAzAEYCsKhK-IJtJAB3AmUxAE4MpES4JGVYxPiixNymZTCwuCLx+Oa4RNjY5RKxXLEI-PzmxIIHYiD+HyQEHC9+VXUpGXkAXyVkbV80UEwATxw4fSYkbUUQTDY2QUwaDg0JhtAw4FcQM4HMoaLIyPcQN4EUUaHBBMp9CdXkoAQg4ABVWR0fSPTqfHHPV7oJwHNi1PQXRlAA)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "url": "https://gist.githubusercontent.com/alexkreidler/28cd830727ce5c5c3ae564af1642ccc4/raw/d595ca7ead370f76bd22efff09e733d156584497/covid-example-data.json"
  },
  "mark": {
    "type": "bar",
    "tooltip": true
  },
  "encoding": {
    "x": {
      "field": "date",
      "timeUnit": "year",
      "type": "temporal"
    }
  }
}
```

It showed a weird chart, so I investigated with the Dataflow view.

The `year_date_end` and `year_date` extents had incorrect start values, like `[ -283978800000, 1672549200000 ]`, which is as a negative value before the Unix epoch is interpreted differently by different systems, and is rendered as January 1, 1960 in the Vega chart.

![debugging_vega_lite](https://user-images.githubusercontent.com/11166947/156701274-675df917-702e-4e32-9f24-00a945a07ee9.png)

I thought perhaps it was an issue parsing the date strings, although they are in the standard 8601 format. So I wrote this VL spec: [Vega Editor link](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtBmx5CBWhEzU6jJgwhxtUOZjizzDhASSC4ADwDW2uBplL20CACYADihlCIBmAAYAdjDEqDgxKAzYpHSANgAWJAAzAEYCsKhK-IJtJAB3AmUxAE4MpES4JGVYxPiixNymZTCwuCLx+Oa4RNjY5RKxXLEI-PzmxIIHYiD+HyQEHC9+VXUpGXkAXyVkbV80UEwATxw4fSYkbUUQTDY2QUwaDg0JhtAw4FdvrVZBAimxtAg0ABtUBQTxQBiCNSvdAQZhmbQ0WRkAAUJwYCEoJzgCniChK8QAlF8kBA3nBsHYACJYkAXAC6SmcDmUhLI9xA3nFRRocEEyjZHO03KcvIuFyAA)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
  "url":"https://gist.githubusercontent.com/alexkreidler/28cd830727ce5c5c3ae564af1642ccc4/raw/d595ca7ead370f76bd22efff09e733d156584497/covid-example-data.json"
  },
  "mark": {
    "type": "bar",
    "tooltip": true
  },
  "transform": [
    {
      "calculate": "substring(datum.date,0,10)",
      "as": "betterDate"
    }
  ],
  "encoding": {
    "x": {
      "field": "betterDate"
      // "timeUnit": "year",
      // "type": "temporal"
    }
  }
}
```

which, with the timeUnit commented out displays as ordinal.

Then I looked at the Dataflow graph and also at the generated Vega.

I narrowed the issue down to the following scale:
```json
  "scales": [
    {
      "name": "x",
      "type": "band",
      "domain": {"data": "source_0", "field": "betterDate", "sort": true},
      "range": {"step": {"signal": "x_step"}},
      "paddingInner": 0.1,
      "paddingOuter": 0.05
    }
  ],
```

When I remove the `domain.sort` value or replace it with `{"field": "betterDate"}`, then it works as expected. (The data is already sorted, so it would be good to compare unsorted original data to verify that it isn't sorted without and then sorted properly with the field specified)

I investigated a bit: after Vega-Lite just generates the `"sort": true` statement, following code parses the spec and takes the first branch (`isObject(sort)` evaluates to `true`), so a sort function is created with the fields ["key"], (also represented as `sort: { $compare: "key", $order: "ascending" }` in the Dataflow view of the Editor. You can see that leads to the wrong output `value`s, but when I fix that sort field in the spec, it shows the right values.

https://github.com/vega/vega/blob/4ca9fae5beab5b4f5a1798db918c42a99b217723/packages/vega-parser/src/parsers/scale.js#L166-L180

![devtools_vega_issue](https://user-images.githubusercontent.com/11166947/156700396-73d29cce-180f-44f2-8003-66db9471fdca.png)

Because the two specs use different transforms (`Scale` and `Extent`), I'm not sure how related the issues are, but I've put everything here for now. I really appreciate any ideas or suggestions you all have.

**Comment by jheer** [comment]
I'll look into any potential sorting issues. But in terms of date parsing, your data **does** have a 1960 date string in the original JSON file! Just search for `1960-01-01T00:00:00.000`, and you'll find it in the first ten rows.

**Comment by jheer** [comment]
I'm not sure I understand the issue involving sorting. Can you please clarify by indicating what values you seeing and _what values you expect to see_? Thanks!

**Comment by alexkreidler** [comment]
Well, that's my bad for not checking the data! I don't think there's any bug at all. Thanks!

**Comment by alexkreidler** [comment]
For anyone else who comes across this, I'll probably use [this guide](https://vega.github.io/vega-lite/docs/scale.html#example-clipping-or-removing-unwanted-data-points) to get rid of the outliers in the data for the scale.
