### ISSUE TITLE
SVG paths with no superfluous spaces get mangled in some cases

### ISSUE THREAD

**Issue by p-himik** [vega/vega#3432]
Extracting https://github.com/vega/vega/issues/3377#issuecomment-1042699447 into a separate issue.

A simple path `M1 0A1 1 0 00-1 0 1 1 0 001 0M0-1 1 0M-1 0 0 1`:
![image](https://user-images.githubusercontent.com/4410314/154437446-f065cd4c-dab0-4cd9-872b-924dfebfdd7f.png)

gets mangled into `M11.180339887498949,0C11.180339887498949,6.174731217790598,6.174731217790599,11.180339887498949,6.845983728302534e-16,11.180339887498949M0,-11.180339887498949L11.180339887498949,0M-11.180339887498949,0L0,11.180339887498949`:
![image](https://user-images.githubusercontent.com/4410314/154437478-8625fbcc-cd91-439a-b986-04c6eadc7e26.png)

The reason seems to be that, while `M1 0A1 1 0 00-1 0 1 1 0 001 0` is a perfectly valid SVG (at lest, works in all browsers and editors that I've tried), the SVG parser cannot handle `00-1` and `001` parts.

The standard is terse but unambiguous here:
> Superfluous white space and separators (such as commas) may be eliminated

`00` above are flags, so separating them from each other and from the next number is indeed superfluous.

Another example: M.5-.8.5.8 gets parsed as M 0.5 -0.8. The implicit line part gets chopped of.

**Comment by jheer** [comment]
Thanks! Fixed for v5.22.0.
