### ISSUE TITLE
mix-blend-mode works for canvas, not svg

### ISSUE THREAD

**Issue by sanand0** [vega/vega#3435]
In the [Vega bar chart example](https://vega.github.io/vega/examples/bar-chart/), I

1. Added `"background": "red",` at the root level
2. Added `"blend": {"value": "difference"},` under `marks[0].encode.enter`.

This works fine for the Canvas renderer.

![image](https://user-images.githubusercontent.com/63734/157818292-ee04328f-da9c-4029-8f12-e10b216ff8a8.png)

But it does not work for the SVG renderer.

![image](https://user-images.githubusercontent.com/63734/157818570-435fb0ad-5897-4673-99ce-7e85a1041c2a.png)

The code seems to add the `mix-blend-attribute` to the path element:

![image](https://user-images.githubusercontent.com/63734/157818722-f9343d7d-d515-4c12-89fb-323a461eb59f.png)

But the [SVG presentational attributes spec](https://www.w3.org/TR/SVG/styling.html#PresentationAttributes) does not include `mix-blend-mode` and says:

> In the future, any new properties that apply to SVG content will not gain presentation attributes. Therefore, authors are suggested to use styling properties, either through inline ‘[style](https://www.w3.org/TR/SVG/styling.html#StyleAttribute)’ properties or style sheets, rather than presentation attributes, for styling SVG content.

Setting the `style="mix-blend-mode: difference"` works as expected.

![image](https://user-images.githubusercontent.com/63734/157819876-cce7ea59-42c9-474c-ab15-c1344ffc5a60.png)

**Comment by jheer** [comment]
Fixed for v5.22.0.
