### ISSUE TITLE
Support local paths for images (file://)

### ISSUE THREAD

**Issue by davibicudo** [vega/vega#3449]
It seems the image mark only works with URLs hosted in the web somewhere, i.e. local paths won't work.
The motivation is to eventually support images in Altair offline HTML-Reports.
Another interesting alternative would be to allow a base64-String encoding the image directly in the JSON specification.

**Comment by jheer** [comment]
Vega already supports base64-string-encoded images using a `data:` URL. [Here is an example](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AFQWYABAwg1xZXUYA2RuLqZIIcAGwAWALRxxUNvNmnkZK7KRMKmkQGygAazJFNgZxWTQQAHcYOjgQnCRZWSMyNAEZRJpZejQARgAGcpl4GjIsMsqZZEVwiDQAbVBMAE8cNPQaXzSZNw95NFAGHADMftAADwmQYiQzBn7ygF8CopLUUEMycVWEwuKYEG2QbqWVtY2rmrrMJcPjswSn+quGRQ-95ardYJGZIVCDJB+Ag4YwAbhsdicUhoADUAEIAeQASolygBpADiZDYAEEyQBSABM5RJADkAMoAVRgAFFGWQyWTGZySQAxADCJIAmpz+bSmN0mGYeQAJFlmFkARRRioAkqVKQAFRxU8pEAAcBESAGZ9QTVSSABoAEVVaLxLPK1pl8zIZmEtLRZIxAE5NJaADLlIWODEyxI8tEAKSxjN1AhZLSjZBTAF5U5dNlmALqbIA).

Image loading in Vega is performed by [instantiating an `Image` object and setting its `src` property](https://github.com/vega/vega/blob/main/packages/vega-scenegraph/src/ResourceLoader.js#L59). When running server-side in Node.js the `node-canvas` library provides the `Image` implementation, so any support for local file loading would ideally be handled through that mechanism.

**Comment by davibicudo** [comment]
Hi jheer, thanks a lot for the example, that solved my problem entirely!
