### ISSUE TITLE
update() fails when data input is empty and an axis/scale reference it.

### ISSUE THREAD

**Issue by pkovac** [vega/vega#345]
If there are no records in the input, the resultant empty domain causes an error in datalib.format.auto.number. In a related problem, if only one record exists, the chart will render and update correctly, sans tick marks. 

(The easiest example to test this with is shiftclick_select; just remove the file reference and replace it with a values: field containing an empty array, or an array containing one record from iris.json.)

Both cases can be fixed by adding two tests to ['interval' in format.js](https://github.com/vega/datalib/blob/master/src/format.js#L47). One to ensure that the domain is non-empty, followed by replacement with an array containing zero, and one to ensure that the span is non-zero, replacing it with 1 if it isn't.

I hesitated to fork and issue a pull request for the changes I've made, as I'm not clear that this is the right layer to fix the problem on.

**Comment by jheer** [comment]
Thanks @pkovac! This does indeed look like a datalib issue more than a vega issue. Please feel free to open a PR over on [the datalib repo](http://github.com/vega/datalib).
