### ISSUE TITLE
VegaLite understands `strokeDash = "x,y"` but `vg2png` requires `[x, y]`

### ISSUE THREAD

**Issue by rben01** [vega/vega#3450]
```bash
vg2png --version
5.22.0
```

`viz.json` (note the `strokeDash` value is `"4,4"`)
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "width": 300,
  "height": 200,
  "data": {
    "values": [
      {"u": 1, "v": 28},
      {"u": 2, "v": 55},
      {"u": 3, "v": 42},
      {"u": 4, "v": 34},
      {"u": 5, "v": 36},
      {"u": 6, "v": 48}
    ]
  },
  "mark": {"type": "line", "strokeDash": "4,4" },
  "encoding": {
    "x": {"field": "u", "type": "quantitative"},
    "y": {"field": "v", "type": "quantitative"}
  },
  "config": {}
}
```

If you turn this VegaLite into an SVG, all is well:

```bash
node vl2vg.js < viz.json | vg2svg > viz.svg
```

![viz](https://user-images.githubusercontent.com/766670/159804827-e94edc68-dc62-4119-bbbb-28b1c3b043c2.svg)

However if you convert into a PNG, the dashed line is rendered as solid:

```bash
node vl2vg.js < viz.json | vg2png > viz.png
```

![viz](https://user-images.githubusercontent.com/766670/159805359-69753413-4d86-4501-92a5-2bb0cdebe963.png)

Despite VegaLite "understanding" that `"4,4"` means the same thing as `[4, 4]` (due to the lucky fact that `[4, 4]` JS-stringifies to `"4,4"`?), it fails to make that conversion when converting to PNG. If you make the change yourself, then it works:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "width": 300,
  "height": 200,
  "data": {
    "values": [
      {"u": 1, "v": 28},
      {"u": 2, "v": 55},
      {"u": 3, "v": 42},
      {"u": 4, "v": 34},
      {"u": 5, "v": 36},
      {"u": 6, "v": 48}
    ]
  },
  "mark": {"type": "line", "strokeDash": [4, 4] },
  "encoding": {
    "x": {"field": "u", "type": "quantitative"},
    "y": {"field": "v", "type": "quantitative"}
  },
  "config": {}
}
```

```bash
node vl2vg.js < viz.json | vg2png > viz.png
```

![viz](https://user-images.githubusercontent.com/766670/159805313-15d24791-1f7c-4d14-861a-22e7fc65a927.png)

To maintain parity between different output formats, I think VegaLite should treat `"x,y"` as `[x, y]` when converting to PNG (and PDF, and any other non-SVG outputs), or at least warn that `"x,y"` is an unsupported value of `strokeDash` in those contexts.

**Comment by jheer** [comment]
The stroke-dash value should always be an array: that is how it is defined in the Vega JSON schema. It may happen to work with SVG, but if so that is an SVG implementation detail and is not what Vega expects. So I'd encourage you to use arrays in your Vega or Vega-Lite specifications!
