### ISSUE TITLE
Path parser crashes on small line distances on v5.22

### ISSUE THREAD

**Issue by dnlbln** [vega/vega#3451]
[Path parser has been rewritten](https://github.com/vega/vega/commit/63abce94bbdad942dd32824099fdb9e038441a4d) in 5.22 and it causes a bug in a specific test case of our arrow charts. Click on the screenshot below to see the full resolution and you will have a good overview of the bug.

![test](https://user-images.githubusercontent.com/3605743/159882714-4e6912da-d533-4d1b-bde9-949667e5a6e3.jpg)

The offending code can be found on line 10 here: https://github.com/vega/vega/commit/63abce94bbdad942dd32824099fdb9e038441a4d

line 10, the code that crashes: **path.match(commandPattern)**. I don't have complete insight in the vega codebase as this is my first time looking into it, but since .match can return null I am pretty confident that regardless the case that there should be a null check there.

I tested it myself and adding a null check will give the exact same result as in 5.21.

**Comment by jheer** [comment]
Thanks! Added null check for v5.22.1.
