### ISSUE TITLE
Binding x axes on scrollable vconcat graphs not working correctly

### ISSUE THREAD

**Issue by martinberoiz** [vega/vega#3456]
Hello,

I believe this is a bug. I try to bind the x-axes on this graph that I am working on (see json)
but I can only pan and zoom on the second vconcat graph and _not_ the first (top) one.

I believe both graphs should let me pan and scroll, is my understanding correct?

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json",
  "title": "Interactive Plot",
  "data": {
    "name": "Multichannel",
    "values": {
      "G1": [[1270294751, 1270298991], [1270299293, 1270302304]],
      "K1": [ [1270291123, 1270291338], [1270291623, 1270299544], [1270300815, 1270302108]]
    }
  },
  "transform": [
    {"flatten": ["G1"]},
    {"flatten": ["K1"]}
  ],
  "vconcat": [
    {
      "width": 600,
      "height": 100,
      "params": [{"name": "region", "select": "interval", "bind": "scales"}],
      "mark": {"type": "rect"},
      "encoding": {
        "x": {"field": "G1[0]", "type": "quantitative", "scale": {"zero": false}, "title": "G1"},
        "x2": {"field": "G1[1]"}
      }
    },
    {
      "width": 600,
      "height": 100,
      "params": [{"name": "region", "select": "interval", "bind": "scales"}],
      "mark": {"type": "rect", "fill": "red"},
      "encoding": {
        "x": {"field": "K1[0]", "type": "quantitative", "scale": {"zero": false}, "title": "K1"},
        "x2": {"field": "K1[1]"}
      }
    }
  ],
  "resolve": {"scale": {"x": "shared"}}
}
```

Thanks for looking into this.

**Comment by PBI-David** [comment]
This should be in Vega-Lite. I don't think it is a bug though. Your data is in a weird format and should really be reshaped. Here is a working example with less redundant code: [Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEJjqC4aEAEllmOACckULaQAEABUFtM6kABMkmFKlDKkCXegCyDIJasEjKynCCTsRIggxwEGgA2qAAcj5+IADiAIxOAB55qDmSAOwykgCcACylYjka+ZJoJeVVAByVlTkAvmppGXq5BUWtFV1VAMyNzcVlMpMVi9V9A756ANJ5jaPzVTkl0yBNLXvdk5PtqyDp6+hbI6dt3QBskkcnc8+VYtUr-TdBvdtsdduVFjJ2jkxDMngsKjlIT0ALp9EAAM3McEcnhAJjYAHc0KB0TRIs49LddBp4EhnKZiT0mRoIDg4FBiSAcEgzAhEqgUiBvHc8eR2KoWZF2TiQDQjKYYlENEw5RT0NBYgkQCiNASaM56GgXjIZDS4DQyFgWiaNMgTABrTmYACebL0Jml2o0cGUUDYzjlZE5+U5SHyNH5oC0mB0aGUQUEaNJ5L0hScLrd6AAjgwwtG3DRSE4NbHcQAvUxsNCYwQQODM46zElkwRqxtejE0QRRXF+5QBrQqJ0JHHNlPoKlOOA52KbPJoxXxd1wClMtdAA)

**Comment by martinberoiz** [comment]
Oh, I guess it's the data format then. I was trying to make it work from the documentation but I guess I don't understand it well enough yet.

Thank you so much to make it work! I will close this issue since it seems it's not really a bug.
