### ISSUE TITLE
Mixing touch and mouse events in signals

### ISSUE THREAD

**Issue by sandbox** [vega/vega#347]
Touch and mouse events in a signal do not appear to play nicely.  

Particularly when adding touch events in an Event stream selector like `"mousedown, touchstart"` and `"mousedown, touchstart, [mousedown, window:mouseup] > window:mousemove, [touchstart, window:touchend] > window:touchmove"`, the signal works on a touch device, but the mouse signals do not appear to fire on mouse devices.

The following block reproduces the issue: http://bl.ocks.org/sandbox/31b8f170f9dbb5591f8d

Sorry if I'm misunderstanding the appropriate usage, as I'm not entirely sure that I've correctly written the event stream selector.

**Comment by arvind** [comment]
Hi John, thanks for filing the issue. Your event stream selector syntax is correct and this is indeed a bug with Vega. I've pushed a fix with 9f61b91 and it will be queued for the next patch release.

**Comment by sandbox** [comment]
Thanks for the quick response, I can confirm it works, and if you were curious [here](http://sandbox.github.io/demos/nba-shot-chart-vega/) is where I used it.  Thanks again :)

**Comment by arvind** [comment]
Wow, that is a really interesting visualization. I particularly like the distribution+brushing of shots around the edges of the court. Really cool!
