### ISSUE TITLE
Sort ordinal scale domain values by "key"

### ISSUE THREAD

**Issue by Shoutmon** [vega/vega#349]
Showing as the following code, I want to let the way of line linking be the ascending order of city. But the sort transform in group mark can't work, how to solve it? 
http://paste.ubuntu.com/12312024/

PS: Using sort transform in the origin data as the following code can work, but I don't want to change the order of the origin data.
http://paste.ubuntu.com/12312114/

**Comment by arvind** [comment]
Thanks for filing the issue, @Shoutmon. What matters here is the sort order of data values for the `x` scale's domain. While Vega currently allows for the domain values of an ordinal scale to be sorted by an aggregate measure of a particular field (e.g., average `sale` in your example), we don't yet support sorting the domain values directly themselves. I'm marking this as a feature request for such functionality. 

In the interim, as you've noticed, moving the sort transform to the original data set is one option. If you'd prefer not to sort the original data, you can easily derive a secondary data source and use that for the scale transform instead, like so:
```json
  "data": [
    {
      "name": "table",
      "values": [
        {"city":"B","year":2003,"sale":10088},
        {"city":"B","year":2003,"sale":4544},
        {"city":"B","year":2002,"sale":2360},
        {"city":"C","year":2002,"sale":2437},
        {"city":"A","year":2002,"sale":3439},
        {"city":"C","year":2001,"sale":6543},
        {"city":"B","year":2001,"sale":8712},
        {"city":"A","year":2001,"sale":5439}
      ]
    },
    {
      "name": "sorted",
      "source": "table",
      "transform": [{ "type": "sort", "by": "city" }]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "ordinal",
      "domain": {"data": "sorted", "field": "city"},
      "range": "width",
      "points": true,
      "padding": 1
    },
```

**Comment by arvind** [comment]
Hi @Shoutmon, 1150aba now allows for the `sort` parameter to be set to `true` to sort an ordinal scale domain in natural order. See [this test case](https://github.com/vega/vega/commit/1150aba7154de5bdc687bf9f7add88de36c83f9f#diff-6c225ea7c34a5a6c8abc63cae3e15e44R896) for more info. This is scheduled to be included in the next release of Vega.

**Comment by Shoutmon** [comment]
Thanks, it really helps:)
