### ISSUE TITLE
Line segments/marks are drawn incorrectly

### ISSUE THREAD

**Issue by az5112** [vega/vega#3492]
Open the chart at the link and move the slider control at the bottom quickly to the right and to the left.  The circle symbols are drawn correctly but line segments get tangled. Reproduced on vega 5.22.1 but I saw the same behaviour on 5.21.0.

To fix the display click **show backlog** twice. (The line will disappear and then redraw correctly.)

[Editor link](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAETJIu2x9mbWwBm2s4oZ1tsmhEzKmDNROkgA7jVn00ADgAGQJl4GjIsNAAWYJkcJFl7cTI0ARkkVzYIGgAvODRQTABPHHz0MzoPRQVcsqcGOBkoCUwkGnEINBB4xPaUgF8ZNUwAGzLCuAAPTC6AMWtbeRGaUmUFDwhmYbGugGU4VUQmOAMAJkDTgEZtAFptcTZPDa26MdmW3eKd9DokZagPFYkAgyiAyIo2AwcB4kOJYGxFF1HMYPOYzBA4DNUJdAoMQNkyOI-p1UABtUBEkFI1qKTCyJCtDztSroemYTE0EEACnOVyk2gAnLdtJcAJQgQYU4GgtQghjiOiORSnfSImTMrEgYAAciKCFk2tQ2lJurg+m1-O1CBaMAt2m1bLg2oAupaip5DcbTebLZ44HAANYut0IT0mopmxR2q024P22SPMMOpBFOPamBsA1Gk0ZhiKCAu-oSqRSqnoZG04g0OBPGRQx1dWVwADyZnRmK56ch+btFbpDKQ-NOUW0ACptBAYDQzJg+46mEV6UUIOLJSBKTLOXB5YqnB5iH8Gl13R4mO1ZAV19LG1vtDuTEzxDhXEi4GMoDMZGxVOoSaSQHqHgnq6IAjEgxwjH+IDWuI9AjEUHh+oG8EgM6-RrhuN5ygqn4gAeIxHmSAGRh4MF+CB9YMpu2G7sqqqkk295Ks6xalqCsiKEgnh6FAAYjGwKQyPhhH1I0IBnuIF6oGxSIZp4uhILx-GCSA7TPpqsBwLxTBsJMHj2BA4FjFJonoSWV5lviU4znOVELkunRCYeZQhOJ56Xph5YBiopgjLIdhUY5qlPi+6Ccck+QyAg7RoJcUVIHp2LBGZMnoHAsEQjgCHqjhXThQmCBcquIFsigZKpSAVg2LheYjF0WC4PgRC0I41B0IwLgYoozSwelmCUM0CAEEgOQCJclynMNAhwAA7FEimnFATAAGxRFEcCnAKgRQHAAgzbI-hQFtAqXDNSAJAQnGeAQcDLfSAjgQIUQCP4AryAAzJta3LacVyyAKApQKcZhbacTCyODQNwO9BBVXQA0QMQgIIsgWKFCUoJQIjHjxPm4wgAi8jVFJchUfpb4rCccAkw26EYderKyAAGk2GzdjtXRw7hTiwhAZgo2g5IgMUpSczQIzsmqIBTDgiLljSmBVjW2gADwALwBZgDAIJQhNUxea4i6CFQSycHgy3LIBcoxOFKtoACEasa12BqitoAA+7vaFybLa5QSyU8TDtO-cDAjCMq7mUbnMo2HKAyBbXTW1uTFONoTvOxmrvaAA-JrfsB6s1PaEavs63rxMwiSpNqMkrHCxjWHbrlMgVG+NMMn0HhMZeBJEnV6A25UeJ938jYSQA+gVbTiEzVeCyA96BN3OGXKh-RoeZnlyLIACazTyrhYh5hz5QLNz4V8wL5UN6L5Ti5L5uTLLXRl-7FNF-5juh+H9fR4PKcW6VWrH5V+H99Yr0VL3cI-cm73mLCAJAUEl6QMwGvTe6M76ILIOCPg7IPDgkhDgBcC8UEgW-FBA+sFUKtxAbIP84gw4jBAkgheUBqFoQwRZY258oD8QxBeGQx9uo8Oqh4HmHR+aKAQILTBxsH5mwTs-S2b9C762Dj-OqhtG731NlLRO8tjBK3kurfOOs1GV20VgoeuE26gNZOAyudZbbQMJGPABNEZh4lYURFBzi6DoKsaCYQbB2hIBwdUCg+CZCEKhCQ3xOFl7kLwAvTYMiQJ2PoQvRSbg4SQg4ekKCOT1BUNwCcGx68uHbx4nxAS350psxPqIyoQxL5SJkTff+wC9FPxfqyK6NTlLaAAGTDO9snTxdsQ66lDG7T23sbFTOdu6bUopir00shqGgfxBkCUaSIrouyyD1MkK03m7TZG33kT0pRfSa5+wrsXFWE4FalT-jo7BuComRQJikoipSaGIKKb-DJdCGFMK4V0qY7JqG0Pbl0P4dUhEwPccFOg2yRhHIlFUhm4lFK1LIFCfZp88VKTqaUU5ws2nXyFl0k2j9bmW1sq0VWGs36PINlHD5FS4X2IJooIm1NUEklAKPAewtAHD0KaQxJqDAlcqweEr5ZMYkQjiQhBJdAklfj+f+AFoL27gvDiwqC7QoCIkhR85o4ctJHwRGjYB8LNWYG1fyom2ToDpSSCkNCG8NmgiOQmTwlLhEkq5uI6l0jLl0oUfo5Rr8Bn4uUu8rB9LFHS3jayBkBdHHF2-ow3+QS4FAMyWA5Yn9hWuNgR45uUqgUyq1XK9eCrQRKsiSqsEariEav-GQnVlD8kzANX5I1zDpVEXkOa5tciujWvfHa2kl5S3OtdRXD1O1JJd19TiyyRzsh5GJQGpNAkiVnMkTSmd6B+JsADKeyqEIOmkoJUGylAY4AasXrKpyBF1gTq0ha8d-5J0AcdSOhtLrp1XJjtIuOvSVHZp1magwdxVH-vng4iWKAi3oG8JJR4bNF3SVAyTPxbqzboCQRu71CCKGpO1oCzJUEliMhNdkqAAJLWptjXB8e7Qp5sGQO0JmlA+ysrMZQFB2GQBzttQRh1y7e2yvIQK8j-5KNeq3SlKD5RY5gR41mrWOtFJQG0AAam0FsnZx6yCkkCCxcdT7lL7vyH6kC0A-i-qFtvSY7mdhDA+XoSSVRYRkFBN4XwMAcYJGo6gQIlBAhpBAGqoLqBRIyGnjFIjYqm77AAI4NDhHAa2k8MuzwkzhfkmASsCZnsJvslXquCbK44b8q5-XHl8z8rpyxxAkRkOFUL9U4DhEiOlmrmXQBvMZvvQdgI6GzuoXiPIEI0BpfXDQU+pkWGTE86ABE1ZqHoB0tgATGwoAea6D587fnKoowZAAFW5VuZG0iGRVtRU2AAqjhXYpQoDTmrIoYrfHSvCaYvyYAuZ8xGm1AAUgABLan6JHUC4E3zNlWGBaE6BcZ0AQmufbfUuhjBnGdi76BlzXa6xtgMABhWbqAZpDFePjYSmNB2dHQiBZAigAx-kvfiPUOkkXSeWNjtbVhTtEam45gSzmEHpWaPIS8lF8FEcSqKqnl3OtzadZ+xtMhAtSTiwIPEGrNfk4Ajr3lJM921AQZgNgbAJYqHe+KnURzPRvzt3kS0zGkBe4Q+-TDlXJWYCNE2d4r3MA+yD0vUPIJvt0F+1pAHJxgfiH401sHts1lFhHvbojbO0CrRHk4G9rPnKHLArxBBSoK8AHUfB+CL1X1ApwR4wCQHfUAxf0D-e6jsOmUmes-L4a71L1gxKS46ZNgchzrPy7xIrzM+NVf4w1-iLX6ArsXZt10UjRu0Am7N73bfVutf76O4v+3BeD2t5-SXqIZeIRvsvH38SNeAx1-L2+pvEX3829Lhh80IgA)

<img width="815" alt="issue-3492-line-segments" src="https://user-images.githubusercontent.com/1263229/167955127-00907fe5-901b-49ae-a69d-dd6b385bced4.png">

**Comment by stas-sl** [comment]
Try adding a sort order:

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAETJIu2x9mbWwBm2s4oZ1tsmhEzKmDNROkgA7jVn00ADgAGQJl4GjIsNAAWYJkcJFl7cTI0ARkkVzYIGgAvODRQTABPHHz0MzoPRQVcsqcGOBkoCUwkGnEINBB4xPaUgF8ZNUwAGzLCuAAPTC6AMWtbeRGaUmUFDwhmYbGugGU4VUQmOAMAJkDTgEZtAFptcTZPDa26MdmW3eKd9DokZagPFYkAgyiAyIo2AwcB4kOJYGxFF1HMYPOYzBA4DNUJdAoMQNkyOI-p1UABtUBEkFI1qKTCyJCtDztSroemYTE0EEACnOVyk2gAnLdtJcAJQgQYU4GgtQghjiOiORSnfSImTMrEgYAAciKCFk2tQ2lJurg+m1-O1CBaMAt2m1bLg2oAupaip5DcbTebLZ44HAANYut0IT0mopmxR2q024P22SPMMOpBFOPamBsA1Gk0ZhiKCAu-oSqRSqnoZG04g0OBPGRQx1dWVwADyZnRmK56ch+btFbpDKQ-NOUW0ACptBAYDQzJg+46mEV6UUIOLJSBKTLOXB5YqnB5iH8Gl13R4mO1ZAV19LG1vtDuTEzxDhXEi4GMoDMZGxVOoSaSQHqHgnq6IAjEgxwjH+IDWuI9AjEUHh+oG8EgM6-RrhuN5ygqn4gAeIxHmSAGRh4MF+CB9YMpu2G7sqqqkk295Ks6xalqCsiKEgnh6FAAYjGwKQyPhhH1I0IBnuIF6oGxSIZp4uhILx-GCSA7TPpqsBwLxTBsJMHj2BA4FjFJonoSWV5lviU4znOVELkunRCYeZQhOJ56Xph5YBiopgjLIdhUY5qlPi+6Ccck+QyAg7RoJcUVIHp2LBGZMnoHAsEQjgCHqjhXThQmCBcquIFsigZKpSAVg2LheYjF0WC4PgRC0I41B0IwLgYoozSwelmCUM0CAEEgOQCJclynMNAhwAA7FEimnFATAAGxRFEcCnAKgRQHAAgzbI-hQFtAqXDNSAJAQnGeAQcDLfSAjgQIUQCP4AryAAzJta3LacVyyAKApQKcZhbacTCyODQNwO9BBVXQA0QMQgIIsgWKFCUoJQIjHjxPm4wgAi8jVFJchUfpb4rCccAkw26EYderKyAAGk2GzdjtXRw7hTiwhAZgo2g5IgMUpSczQIzsmqIBTDgiLljSmBVjW2gADwALwBZgDAIJQhNUxea4i6CFQSycHgy3LIBcoxOFKtoACEasa12BqitoAA+7vaFybLa5QSyU8TDtO-cDAjCMq7mUbnMo2HKAyBbXTW1uTFONoTvOxmrvaAA-JrfsB6s1PaEavs63rxMwiSpNqMkrHCxjWHbrlMgVG+NMMn0HhMZeBJEnV6A25UeJ938jYSQA+gVbTiEzVeCyA96BN3OGXKh-RoeZnlyLIACazTyrhYh5hz5QLNz4V8wL5UN6L5Ti5L5uTLLXRl-7FNF-5juh+H9fR4PKcW6VWrH5V+H99Yr0VL3cI-cm73mLCAJAUEl6QMwGvTe6M76ILIOCPg7IPDgkhDgBcC8UEgW-FBA+sFUKtxAbIP84gw4jBAkgheUBqFoQwRZY258oD8QxBeGQx9uo8Oqh4HmHR+aKAQILTBxsH5mwTs-S2b9C762Dj-OqhtG731NlLRO8tjBK3kurfOOs1GV20VgoeuE26gNZOAyudZbbQMJGPABNEZh4lYURFBzi6DoKsaCYQbB2hIBwdUCg+CZCEKhCQ3xOFl7kLwAvTYMiQJ2PoQvRSbg4SQg4ekKCOT1BUNwCcGx68uHbx4nxAS350psxPqIyoQxL5SJkTff+wC9FPxfqyK6NTlLaAAGTDO9snTxdsQ66lDG7T23sbFTOdu6bUopir00shqGgfxBkCUaSIrouyyD1MkK03m7TZG33kT0pRfSa5+wrsXFWE4FalT-jo7BuComRQJikoipSaGIKKb-DJdCGFMK4V0qY7JqG0Pbl0P4dUhEwPccFOg2yRhHIlFUhm4lFK1LIFCfZp88VKTqaUU5ws2nXyFl0k2j9bmW1sq0VWGs36PINlHD5FS4X2IJooIm1NUEklAKPAewtAHD0KaQxJqDAlcqweEr5ZMYkQjiQhBJdAklfj+f+AFoL27gvDiwqC7QoCIkhR85o4ctJHwRGjYB8LNWYG1fyom2ToDpSSCkNCG8NmgiOQmTwlLhEkq5uI6l0jLl0oUfo5Rr8Bn4uUu8rB9LFHS3jayBkBdHHF2-ow3+QS4FAMyWA5Yn9hWuNgR45uUqgUyq1XK9eCrQRKsiSqsEariEav-GQnVlD8kzANX5I1zDpVEXkOa5tciujWvfHa2kl5S3OtdRXD1O1JJd19TiyyRzsh5GJQGpNAkiVnMkTSmd6B+JsADKeyqEIOmkoJUGylAY4AasXrKpyBF1gTq0ha8d-5J0AcdSOhtLrp1XJjtIuOvSVHZp1magwdxVH-vng4iWKAi3oG8JJR4bNF3SVAyTPxbqzboCQRu71CCKGpO1oCzJUEliMhNdkqAAJLWptjXB8e7Qp5sGQO0JmlA+ysrMZQFB2GQBzttQRh1y7e2yvIQK8j-5KNeq3SlKD5RY5gR41mrWOtFJQG0AAam0FsnZx6yCkkCCxcdT7lL7vyH6kC0A-i-qFtvSY7mdhDA+XoSSVRYRkFBN4XwMAcYJGo6gQIlBAhpBAGqoLqBRIyGnjFIjYqm77AAI4NDhHAa2k8MuzwkzhfkmASsCZnsJvslXquCbK44b8q5-XHl8z8rpyxxAkRkOFUL9U4DhEiOlmrmXQBvMZvvQdgI6GzuoXiPIEI0BpfXDQU+pkWGTE86ABE1ZqHoB0tgATGwoAea6D587fnKoowZAAFW5VuZG0iGRVtRU2AAqjhXYpQoDTmrIoYrfHSvCaYvyYAuZ8xGm1AAUgABLan6JHUC4E3zNlWGBaE6BcZ0AQmufbfUuhjBnGdi76BlzXa6xtgMABhWbqAZpDFePjYSmNB2dHQiBZAigAx-kvfiPUOkkXSeWNjtbVhTtEam45gSzmEHpWaPIS8lF8FEcSqKqnl3OtzadZ+xtMhAtSTiwIPEGrNfk4Ajr3lJM921AQZgNgbAJYqHe+KnURzPRvzt3kS0zGkBe4Q+-TDlXJWYCNE2d4r3MA+yD0vUPIJvt0F+1pAHJxgfiH401sHts1lFhHvbojbO0CrRHk4G9rPnKHLArxBBSoK8AHUfB+CL1X1ApwR4wCQHfUAxf0D-e6jsOmUmes-L4a71L1gxKS46ZNgchzrPy7xIrzM+NVf4w1-iLX6ArsXZt10UjRu0Am7N73bfVutf76O4v+3BeD2t5-SXqIZeIRvsvH38SNeAx1-L2+pvEX3829Lg6YhF7Ul15sd8JQ-UgA)

```json
{
  "type": "line",
  "clip": true,
  "from": {"data": "backlogsize"},
  "encode": {
    "update": {
      "x": {"scale": "xscale", "field": "unit0", "band": 0.5},
      "y": {"scale": "yscale", "field": "backlogsize"},
      "size": {"value": 64},
      "stroke": {"value": "black"},
      "strokeWidth": {"value": 1}
    }
  },
  "sort": {"field": "x"}
}
```
