### ISSUE TITLE
Axis label formatting is unpredictable for temporal variables at large width

### ISSUE THREAD

**Issue by holdenmatt** [vega/vega#3501]
Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues.
- [x] Describe how to reproduce the bug.
- [x] Use the latest versions of Vega and Vega-Lite.
- [x] Provide an [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) spec in JSON, wrapped by triple backticks like this.
- [x] If applicable, include error messages and screenshots, GIF videos (e.g. using https://www.cockos.com/licecap/), or working examples (e.g. by clicking share in the [Vega-Editor](https://vega.github.io/editor/) or https://bit.ly/vega-lite-blocks)

The axis label formatting for "temporal" variables seems buggy or unpredictable.

I've included a minimal example spec below. In the Vega-Lite editor ([link](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQyAE4BrNCCZIVikHFlQ2AExqyyaUAA9LIAGY04g45qgq4STHGMB9T3swATxw4TS8EHDYVJEE9JCsaCFtBJCYnAEFzQVDUfgBOAAYAXyKlQNsHJxd0FTYAdx8jBllMAOCckABHBiQWuk8aUhASpTqaY3o0AEYAJgKCpXgaMiw0ABYADgWQY08UVFBiGIY4JNQAbVA3Dy9ff1QpgDYAZjEAdhnN+e+lWoamlpoZ4zOalK7uTzePytB4vMQbKazb7zX71RpsZow4FiYoKcE3KH3J6vDZ5N6PZHbP7ozFAtbzMEga6Qu4w4liPIbemU1H-DGA1DPAo4xnM27Q6YvClvArcn4gakArFvEV4pkQ8VEqVTMSPLbI3k0gUzPKq-EsiWw56PT7AnkKtFKoFvKZvUUawlsqXAvIUg0Ovm0wXPDYzd0E1mS61rJ6UqmO-lYjZm9URy3Ex44z72xWJoFC3HmzVe63wjb6+W5oMhhlqsWeqOPR4qub+qsCtYzFP1yNW5uPWNthNBtbc8MWrXWrkVyvDgUh7se3sZvLPUc5udYv3j4tRmVzGfxwPzzOF1MTksugofDfHrGms899MvF2rv2zu9A1s7htWj6HlEAyNGFR0XNNJzea1HjlQD2xhMQxzrJdn2eN41jEGZD0NJ1UDlH9lxfMRnjyVsP2AoFCkfZCIJtXVb3IwUZSo8DLxdUiyJwtZtyQli9zeTkYKPBjiNrItf2JN5yy+IdP0FB98JQ-i2PonCa2Yi8oy2d531gzc6TAjSrQRdcVLzQV9QUydQyFQTsLM9DRPPXcjOeJ4sKAzjvksksuQKO0ZIYtZ5J4wziWnX1TJHRCxIIhdyTjOyRzEAznLCptswCzjkvU1KXg2NDy0ijtT28zSNledihJw5KUvEvKSMHDizJEnK6pagDEoFOjWtiwo8hMpqoscp9JzyKYtncuC0DEHUepQkjm0qzqQIc0qrVXIidKqsz4WG6iS36wTdNkhC9t49aMOgor4O4mL5oHTDrum26nLa308hIp7UHfNbiTJZMtuW6auzm0b8sq7aR2TUGDtNXzMp2ryQty7lR0mvTUAws7QquqZXKWjyzMzWqCPpGZXUBwmgwpEnn3pGyEqpgUB2xlG-MKWymfg6LXtJ2VyXRk6plZur6V1fzBq62bfqu6CIoRoNdVprV6UgrbIalkW+dDDLJZhH7kdFgpCkKhWupVGHJXpD6sbN+CLZlmMCgRSmpu+gtHcRPVGbdoitbp2YEM533VsN0m8fpQWGI+ZWvRjTsbzttAWct2EYxm60vptf2VcarOQc9vUrqT1ByVjq3XX-L7JJzuPxo5Am3e91Onhjfrur157a6tuYJc793u7T8nxuDjGZXLoe5mk-vm0H1uQTGxux6Ru6VZmVD4pLyC5+gz5i63l6RrjrscVH2SVQn+epSjnCK0dmYPj7jWYVJS-d62eWZ9eFv38--vTfvpyXWx0GIALDnTIUeob5mX4jvNYrlkpL3PjzI+VtgQxldhjcqb94HAg6lzNAkkcFrimANEBt8HbgJVt-Z2X0ERwJJInfuJsphFAALolCAA)), you can see the axis labels look like this:

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/764380/169899635-a3ddcbe2-3975-4ff1-b9bc-3d04588a7904.png">

The labels seem to switch randomly between different formats. For example, certain labels like "Nov 07", "Nov 21" or "Dec 05" switch to month instead of day of week.

Strangely, labels look fine at width 960 or less, but get wacky at any width 961 or more.

What's the best way to fix this? I could set my own format string, but ideally I'd rely on Vega-Lite's logic here.

Seems like a bug?

```json
{
    "$schema":"https://vega.github.io/schema/vega-lite/v5.json",
    "mark":"bar",
    "encoding": {
        "x":{
            "field":"created_at",
            "type":"temporal",
            "axis":{
                "labelAngle":-90
            }
        },
        "y":{
            "field":"row_count",
            "type":"quantitative"
        }
    },
    "width":1200,
    "height":480,
    "data":{
        "values":[
            {"created_at":1635724800000,"row_count":3220},
            {"created_at":1635811200000,"row_count":3250},
            {"created_at":1635897600000,"row_count":3400},
            {"created_at":1635984000000,"row_count":3050},
            {"created_at":1636070400000,"row_count":3750},
            {"created_at":1636156800000,"row_count":2950},
            {"created_at":1636243200000,"row_count":3717},
            {"created_at":1636329600000,"row_count":3382},
            {"created_at":1636416000000,"row_count":3850},
            {"created_at":1636502400000,"row_count":3300},
            {"created_at":1636588800000,"row_count":3800},
            {"created_at":1636675200000,"row_count":4250},
            {"created_at":1636761600000,"row_count":4400},
            {"created_at":1636848000000,"row_count":3850},
            {"created_at":1636934400000,"row_count":3600},
            {"created_at":1637020800000,"row_count":3650},
            {"created_at":1637107200000,"row_count":3950},
            {"created_at":1637193600000,"row_count":3200},
            {"created_at":1637280000000,"row_count":4450},
            {"created_at":1637366400000,"row_count":5400},
            {"created_at":1637452800000,"row_count":4000},
            {"created_at":1637539200000,"row_count":3900},
            {"created_at":1637625600000,"row_count":3700},
            {"created_at":1637712000000,"row_count":4600},
            {"created_at":1637798400000,"row_count":3900},
            {"created_at":1637884800000,"row_count":3950},
            {"created_at":1637971200000,"row_count":3800},
            {"created_at":1638057600000,"row_count":3450},
            {"created_at":1638144000000,"row_count":3800},
            {"created_at":1638230400000,"row_count":4500},
            {"created_at":1638316800000,"row_count":4000},
            {"created_at":1638403200000,"row_count":4950},
            {"created_at":1638489600000,"row_count":4400},
            {"created_at":1638576000000,"row_count":4550},
            {"created_at":1638662400000,"row_count":4550},
            {"created_at":1638748800000,"row_count":4650},
            {"created_at":1638835200000,"row_count":5550},
            {"created_at":1638921600000,"row_count":3900},
            {"created_at":1639008000000,"row_count":5600},
            {"created_at":1639094400000,"row_count":4400},
            {"created_at":1639180800000,"row_count":5150},
            {"created_at":1639267200000,"row_count":4450},
            {"created_at":1639353600000,"row_count":5800},
            {"created_at":1639440000000,"row_count":5400},
            {"created_at":1639526400000,"row_count":5600},
            {"created_at":1639612800000,"row_count":5600},
            {"created_at":1639699200000,"row_count":6000},
            {"created_at":1639785600000,"row_count":5250},
            {"created_at":1639872000000,"row_count":4850},
            {"created_at":1639958400000,"row_count":5000},
            {"created_at":1640044800000,"row_count":5200},
            {"created_at":1640131200000,"row_count":6550},
            {"created_at":1640217600000,"row_count":6050},
            {"created_at":1640304000000,"row_count":6100},
            {"created_at":1640390400000,"row_count":5400},
            {"created_at":1640476800000,"row_count":5100},
            {"created_at":1640563200000,"row_count":5150},
            {"created_at":1640649600000,"row_count":5650},
            {"created_at":1640736000000,"row_count":5100},
            {"created_at":1640822400000,"row_count":6000},
            {"created_at":1640908800000,"row_count":5750},
            {"created_at":1640995200000,"row_count":5750},
            {"created_at":1641081600000,"row_count":6300},
            {"created_at":1641168000000,"row_count":5300},
            {"created_at":1641254400000,"row_count":5450},
            {"created_at":1641340800000,"row_count":7250},
            {"created_at":1641427200000,"row_count":6100},
            {"created_at":1641513600000,"row_count":6200},
            {"created_at":1641600000000,"row_count":6250},
            {"created_at":1641686400000,"row_count":7650},
            {"created_at":1641772800000,"row_count":7800},
            {"created_at":1641859200000,"row_count":6800},
            {"created_at":1641945600000,"row_count":5600},
            {"created_at":1642032000000,"row_count":6300},
            {"created_at":1642118400000,"row_count":7050},
            {"created_at":1642204800000,"row_count":6700},
            {"created_at":1642291200000,"row_count":7000},
            {"created_at":1642377600000,"row_count":7300},
            {"created_at":1642464000000,"row_count":7600},
            {"created_at":1642550400000,"row_count":7550},
            {"created_at":1642636800000,"row_count":8000},
            {"created_at":1642723200000,"row_count":8950},
            {"created_at":1642809600000,"row_count":6350},
            {"created_at":1642896000000,"row_count":8800},
            {"created_at":1642982400000,"row_count":8800},
            {"created_at":1643068800000,"row_count":7900},
            {"created_at":1643155200000,"row_count":7400},
            {"created_at":1643241600000,"row_count":8350},
            {"created_at":1643328000000,"row_count":7850},
            {"created_at":1643414400000,"row_count":8750},
            {"created_at":1643500800000,"row_count":8100},
            {"created_at":1643587200000,"row_count":9081}
        ]
    }
}
```

**Comment by holdenmatt** [comment]
Thanks for the pointers, that's helpful!

I think what's surprising here is using different format strings for "week" vs "date" intervals. The week boundaries aren't obvious to a human viewer, so the format appears to change randomly in cases like this.

It looks like you can override these format strings in the `vega` `axis` object (as mentioned [here](https://github.com/vega/vega/issues/3116)), but I don't have a great way to do that since I'm compiling from `vega-lite`.

Do you know of any other way to override one of these format strings?

**Comment by stas-sl** [comment]
Hmm, I'm not sure why you're saying you can't override it in VL. I tried:
```json
"x": {
      "field": "created_at",
      "type": "temporal",
      "axis": {
        "labelAngle": -90,
        "format": {
          "week": "%b %d",
          "date": "%b %d",
        }
      }
    },
```
And it works:
<img width="992" alt="image" src="https://user-images.githubusercontent.com/4602302/170760227-f0c400fb-63a3-43bb-b61b-b6b14d451987.png">

Or you want something different?

**Comment by holdenmatt** [comment]
Oh nice, that's perfect, thanks! I must not have been doing something right.

Happy to close this issue as fixed for my purposes? Or do you want to leave open to consider changing a default?

**Comment by domoritz** [comment]
Let's close it. Changing the default is a big design exercise.
