### ISSUE TITLE
How to draw a line which has gradient color and size

### ISSUE THREAD

**Issue by Shoutmon** [vega/vega#351]
It seems that stroke and strokeWidth cannot be gradient like the following picture:
![gradient color and size](http://7j1yhu.com1.z0.glb.clouddn.com/image_20150909121956.png)

If I bind scale to stroke and strokeWidth as the following code, the graph will be like this:
http://paste.ubuntu.com/12318646/
![vega line](http://7j1yhu.com1.z0.glb.clouddn.com/image_20150909123152.png)

Is there any way to solve it?

**Comment by jheer** [comment]
Thanks for the request! Closing this issue as it duplicates #122, which is now vega/vega-scenegraph#13.
