### ISSUE TITLE
Repositioning a chart mark does not reposition the axes

### ISSUE THREAD

**Issue by irwazr** [vega/vega#3514]
When I move a chart into a specific X/Y coordinate, using the "range" field on the Scale, the Axes do not move with the rest of the chart mark content.  There appears to be no way to move the chart axes away from the edges of the entire Vega spec area.

Is this a bug or am I doing it wrong?

Full vega spec:
```
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "A basic bar chart example, with value labels shown upon mouse hover.",
  "width": 700,
  "height": 500,
  "autosize": "pad",

  "data": [
    {
      "name": "table",
      "values": [
        {"category": "A", "amount": 28},
        {"category": "B", "amount": 55},
        {"category": "C", "amount": 43},
        {"category": "D", "amount": 91},
        {"category": "E", "amount": 81},
        {"category": "F", "amount": 53},
        {"category": "G", "amount": 19},
        {"category": "H", "amount": 87}
      ]
    }
  ],

  "signals": [
    {
      "name": "tooltip",
      "value": {},
      "on": [
        {"events": "rect:mouseover", "update": "datum"},
        {"events": "rect:mouseout",  "update": "{}"}
      ]
    }
  ],

  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "domain": {"data": "table", "field": "category"},
      "range": [400 , 800],
      "padding": 0.05,
      "round": true
    },
    {
      "name": "yscale",
      "domain": {"data": "table", "field": "amount"},
      "nice": true,
      "range": [300 , 100]
    }
  ],

  "axes": [
    { "orient": "bottom", "scale": "xscale" },
    { "orient": "left", "scale": "yscale" }
  ],

  "marks": [
    {
      "type": "rect",
      "from": {"data":"table"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "category"},
          "width": {"scale": "xscale", "band": 1},
          "y": {"scale": "yscale", "field": "amount"},
          "y2": {"scale": "yscale", "value": 0}
        },
        "update": {
          "fill": {"value": "steelblue"}
        },
        "hover": {
          "fill": {"value": "red"}
        }
      }
    },
    {
      "type": "text",
      "encode": {
        "enter": {
          "align": {"value": "center"},
          "baseline": {"value": "bottom"},
          "fill": {"value": "#333"}
        },
        "update": {
          "x": {"scale": "xscale", "signal": "tooltip.category", "band": 0.5},
          "y": {"scale": "yscale", "signal": "tooltip.amount", "offset": -2},
          "text": {"signal": "tooltip.amount"},
          "fillOpacity": [
            {"test": "datum === tooltip", "value": 0},
            {"value": 1}
          ]
        }
      }
    }
  ]
}
```

**Comment by irwazr** [comment]
This is how it looks:
![HowItLooks](https://user-images.githubusercontent.com/70178698/173961058-1873f84e-3a4e-4553-857b-0e2f768a0ec5.png)

However this is what I expected/needed it to look like:
![WhatINeed](https://user-images.githubusercontent.com/70178698/173961106-f703366c-75f8-4646-ace4-aa63441939d2.png)

**Comment by PBI-David** [comment]
Use an axis offset. 

[Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAETJBBpRdSRdtgnM2uAA8kCHABs4U7QHc6MbcSQOGcbQ5ITHAOENoQMGyu4toMOBLaCGwMEP6RpIqU0iDusvRoAOwADEUy8DRkWGgCJTJIDJhsBgBecGggOEiy2bJImCioANqg4nZt6P1MTtnevgpowyBQfeRsigCe7ZrZdsnimGgATAAcAL5SoMuYqxvtAEI7SQz71QLnlytka5voAMKPewOqAALABmd5LT7fdoAEQBzyBAE4AIwQq43H4gACi8JeqGOqIukOuX1u6AAYrigQJwUT0aTMQBxKloZGItFQskgAASLPxBVOAF0hTIDGRRqEFiMxu1GmwHGocDMfH40MBziAJFKQHBSPsIO1FHAoJhUE9UmwMtk4r1ru1bQwECAIbq4PrDcbTea4MkDjIbSt2urncLBaLlk4DUNpQhxiBrNAfG0ZJh1jg43pxN0ZLI2MgaBpQLaBiBJtMZAAzGghbroenQjWKJDiMjjQbA2rHEphjpdWQFshoIqUIoCGSKPa1zCKPwQ0ax9rrRPluR5pAFtVyPolsvJkBVmvtXYI50ycSGcbTvzj5uthag2rI7sikBIazzaOa5RuoEgJhsbA82yZc4wTCM9zYCsK1SIEAFpDhKCE1mrPEQCcCs-RAEDF2wmRIOguA4I7IoX2QRQAGso0WVN0w9E1sgrCcnVQItt1lIJpg1N0oDYeRNx-OBFE3axN2w9AwKTBjqwcWtiQxU8choPIYFE8D2gkldM1rQkQB+UAxN03D92k2TjxeDV1kOVTJPQJc1JkWZVVQEiNQDO0WOMhwHE3Ry4wga4QimVVTg1dJBM3KsvJ8lU4yNboQpCokaLja5rEw7jePGUABKEjyfAqQsQF89ooByhS9FSBwCyyoqYvaf9AKdDVIu8jzivQABiUFuudVycFtGqRI8gyNL3MUJVlNh5UVSh61uGQtKHSg3hkPSsLU2yjPGnxJumlRKDMzD8JgtB4I1VKgX0gqdomKaFX2w6FJagB5TooDoH5qIUX8HQQbQAF5Ae0OV7qVBy6uciF2tRYUQuFIA)

![image](https://user-images.githubusercontent.com/86846675/176536169-8cc72dcc-a65e-4d50-a868-787a6918ffcf.png)


I think this can be closed.
