### ISSUE TITLE
In my layouts consisting of equally-sized elements, some child groups overflow their parent group by a few px

### ISSUE THREAD

**Issue by nsajko** [vega/vega#3537]
Original SO question: https://stackoverflow.com/questions/72958607/why-does-the-inner-rectangle-overflow-the-outer-rectangle-in-vega-spec

When I try to create a row consisting of equally-sized equally-spaced columns, the columns seem to be sized and spaced as expected, but the last column overflows the parent group.

The equivalent issue is present for the case of a single column consisting of rows.

The MRE is very simple: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhBIGmNhBoAvOGhDiJamVAkAzGmTSgyAJzYMcxkBEzmA1mvRMANkij2QAXy8ylZcSQXCDQAbVBAhCcQTCRTMjhMAH14QyxpEGIghicAJgAGfN8IpCj1WPjEpIB3GgATegyslxy0AqKpErL0FzhSFyT8pJwkOrqacSMZZtbUAEYANmKNUuje-qS54dHxyYzLOqRMaLmCXIACACpz9bgBoZGxiaNlyLW+u8GUuDTMfZxDsdynEEslUmQsOcALTnXKXW73bZPPavVbqBFfWoNGD-QHRCqgmr1ejQ2Hwj6Ix67F6dFbdEAYrZYxoyA5HE5nK7nAAUGKGzJgpL5SOpAEpvLS3uiKZtvr9cezpRshuD0l4ALoyAXWfyBFxKz784k43wYH4Qv6oUC6oIGxGqv6mqnPHWGPV2r7OlEyNwATwsltAXqMVpsbttPRlDx2Lp8MmQpnsIVQ4Rivpw0TMFisMjg4l0dScoDZQND2tDNv1kY2TONErN8or4arDJlWwd9eD1hmTg6NjsbEc3ey0VMcDq9dsDjgAHkRlA6L7hy1e5QBD446BMOnM+ZLBk8wWiyAS8fy9bmx7a9j6x2mwEI62a3KLZ2Y3tQz20H2p4Pj1-0DHCdTV-Rw53cRdl1mfI1w3DUvCAA)

![2](https://user-images.githubusercontent.com/4944410/178967343-6dd52c6b-6ced-42da-8529-4f092bd2fbe8.png)

The issue is worse with more columns: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhBIGmNhBoAvOGhDiJamVAkAzGmTSgyAJzYMcxkBEzmA1mvRMANkij2QAXy8ylZcSQXCDQAbVBAhCcQTCRTMjhMAH14QyxpEGIghicAJgAGfN8IpCj1WPjEpIB3GgATegyslxy0ADZC4o1S6Jc4Uhck-KScJDq6mnEjGWbW1ABGNq7I3v64QfmRsYmpjMs6pExo+YJcgAIAKjO+gaGt8cmjZZ71G-W71LJ0mX3D6IqEslPlgzgBaM65C5vQbDUYPXbPMroaF3WoNGB7HAHI7lOKAmr1ehgiFQtYw+47J5SEpIkAozZoxo-LF-dQnAAclzOAAoUcNGTBiQB2Um3WHbR4ASm81O6tPpKTgaUwmOxqzFiuV3gAujIBdZ-IEXK8yajCRjfBglV8VahQIagiaNcCVZa4ZSDYYjU73uL4VS6UgAJ4WW2gd2PT0BR3I01+j0+GTIUz2EKocIxIM4aJmCxWGRwcS6OpOUC-HF2kD6ysO42x24M80yq1amtemN002bF3NiO7SuzJxFPx2NiOayD9SmOB1Zu2BxwADyoygdCDE+yQ8oAh8idAmCzOfMlgyheLpZA5Yv1ft7brnYbBPRzZ7bej94VPbdEv7oEnqGHGxR3HAdNynGc52ApcVzXDcWi3Hdd1lA9s3UXMTwLIs2BLawr2sG8bDvH0NifRpLVfW932IpJu2tdJv39OC5kA+cxwvf8QGnWdLVYxxl3cWDQPgtB8m3XcuhQo881PLCcMrPDKwI2tqMbZ9yLosNCKo+t3lorUGI9ITmJ4qCmOiLjIIXfjVwPMyRLEpD90PNDj3zEAz2wi8FNAJSiJ0kj9XU1tKO9fyaM1G1ex-IwjKHEyFzs9ALPitjrMEv8wIAhy90zVD0HQtyPLkssWQrHymzfUKH100iLRkCitKqz8NKixjYpElKQIy4SkogzroIE2z2qyxCcsklzpMw89cNK68KpCjsFUC+qWsqxauwi+iZD7GLuuMkcEuGzi+oO1KYKGvaEPE5DnPy1yZOm+TZvw+bGvWx9lpbSK1o-Dav226LEpY0yjuS06+PO9dhtE0avG1LwgA)

![8](https://user-images.githubusercontent.com/4944410/178967395-3652a710-6f45-479e-b782-6eb06a77f57f.png)

Note that in both examples all the relevant signals are integers, so this isn't a case of floating-point error on my part.

**Comment by PBI-David** [comment]
You need "bounds": "flush".

[Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhBIGmNhBoAvOGhDiJamVAkAzGmTSgyAJzYMcxkBEzmA1mvRMANkij2QAXy8ylZcSQXCDQAbVBAhCcQFzhSFwB9AAYEnCQAE3SacSMZYiCGJwBGADZfCKQo9Vj4hKLUjKyc6RBLdKRMaKKCACYAAgAqPpq4RJS0zOyjco1K6JGxhPhDLBa2jq6SgA5vKQqq9AXkhIB3GnT6NZx2zvVSnZnI+bjRutPzy5l12-Ru-qGABRHFJnC4wPoAWmGL0WEyaZAAlLt9s9avVlmRVl9rhtqjDjhjVl4ALoyUGXVCgfyBFx3ba7DBwFaYazUoJ0h4yOFTVmGGnqADMSQZbgAnhYWZSQNzmlK2bTDvjxo0eb4QEwLOJ0iF0HoXAwIDAGchTPYdeEQJhRThomYLFYZHBxLp0k5QN83SByUa5Xz2Yq0e8wQzCZKqX6FTF8eimZiWWqZUYpfl9U4kmrbA5PSnCupTHB0gzM2xHAB5NJQOii6w5tOUAQ+Hx7S3W23mSwtJ0uz0e6ze3kBf1RwP9tWhgf8gOvGPMhmJmsFNMZuwl7OLvMFosrssVqsL1NoJL1xskrxAA)

![image](https://user-images.githubusercontent.com/86846675/178972063-e7a7c005-a1f3-4595-aa0f-97472933ae53.png)
```


{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "autosize": "none",
  "config": {"group": {"stroke": "black"}},
  "signals": [
    
    {"name": "level_0_padding", "value": 16},
    {"name": "level_1_padding", "update": "1/2 * level_0_padding"},
    {"name": "level_0_height", "update": "168"},
    {"name": "level_0_width", "update": "168"},
    {
      "name": "level_1_width",
      "update": "1/2 * (level_0_width - level_0_padding)"
    },
    {"name": "level_1_height", "update": "level_0_height"}
  ],
  "width": {"signal": "168"},
  "height": {"signal": "168"},
  "padding": {"signal": "30"},
  "layout": {"padding": {"signal": "level_0_padding"}, "bounds": "flush"},
  "marks": [
    {
      "type": "group",
      "encode": {
        "update": {
          "width": {"signal": "level_1_width"},
          "height": {"signal": "level_1_height"},
          "padding": {"value": 0},
          "stroke": {"value": "red"},
          "strokeOpacity": {"value": 0.5}
        }
      }
    },
    {
      "type": "group",
      "encode": {
        "update": {
          "width": {"signal": "level_1_width"},
          "height": {"signal": "level_1_height"},
          "padding": {"value": 0},
          "stroke": {"value": "red"},
          "strokeOpacity": {"value": 0.5}
        }
      }
    }
  ]
}
```

**Comment by nsajko** [comment]
Thank you.
