### ISSUE TITLE
document issue about text marks

### ISSUE THREAD

**Issue by haiwen-shaw** [vega/vega#360]
quote from from document of text marks:
  **dx** is "The horizontal margin, in pixels, between the text label and its anchor point. The value is ignored if the align property is  `center` ."

but according to my test, I found that dx and align(center) can work together, and **it is exactly what I want!**. 
what I want is:
  put a text lable in the middle of each bar of the chart. I use the **dx** to get label's location and use align(center) to make it in the right place. 
  Did I do something wrong or it is the expected behavior?thanks!

**Comment by jheer** [comment]
Thanks for this! The semantics of `dx` has evolved across Vega versions. The current behavior is correct. We will update the documentation accordingly.
