### ISSUE TITLE
Nest transform - give name to generated nodes

### ISSUE THREAD

**Issue by carlosgalvezp** [vega/vega#3629]
Hi!

I'm using the "nest" transform together with "circle packing" to create a visualization that displays a metric over a number of source files ([link](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQXEACOAA8kCHABs4OtgDMdSHVBqKoZnTiRQA1jXFkdJpAE82BkwdSzZFHRgaOEUkRyioJBMdWSRMKmkQAHcaWXo0AQAGQpl4GjIsAuKZV1lZLzICmSRgtggaAC84NBBxCW6ZVPS0AG1QcSNu9ExFOAGQYiSGBVHxyZ6wtkycAEYelBqAJh6mbYBmDbY2SigcHEz2rrQdw7OAXyk1hCmQJjjtvboA4gHDHdCnGoXcFxG53B6dKZnQ47D5fH5-DoAnpQbZguTnE5IDqw+4yR5THbFQqo3rraEdY41QEgHFHHqyAn0w4k+FPVAAFmpAF0ZDMkOIIGFFAhViBMP4cD9xApMJl3HB-BBRiC9mzISARSAyHBlbFMFMZssafLFT1XB5MpZoiYOehyQ9wqrUKAnXAXT1FiZliAPiB3agxmHyhMTD0cnkYCHPlGyDGemUKqq3kLs9myYkzFqI2jsWwTOFMjafuF6mnBmxkF40KAhihprN5r7-eh5KpE6HYt4pqAuIgfolzWRwv5DoUQ3mUzGi5GJt8etAknAABqZQPB1A7GQSWVwUjiTBFlkmGgOmQMHBDH4ACnj9AIhwAlAQhgwEJRFCGObJquPwbmYACau5LBSR4aJGp4mhe2LXreID3o+PRPhmWDvl+P5-gBubAXSID6AAKoOEB+Gox4yHuUwlCAx7FiACHnpeTg3u4mToWkz6vjAuE6AAtCkaS-pQ+g6AAVDoYHboBNIgT0-gUeKVFpOoUFBgxsEnmeSHoJxqG8eamHYZgQmifhlD+DJckFnAkG5oayCKO4y6gFW67+AgTBlo6igNs2chpG2codkmrHiFAbDyCFiExCFEAwEgtregs0HYg4TjdKGTomLGGXyaW5YATIXaunIcB9lFmBXCYaj3MV0ZJOy4l-iBOgANQ6E+NnkjoAD8OgAORSGNPViZgEmDb1o06Ew-jmhAC2oGNo0fvOd4PnxIX6MlrVFaFM1-lJsnyVuU3kZR1FaaG-iHambU9h1tn2fJ4FTapt2aceobhiOR09Py9k2REsngx9jlXRdjnOWSMxsOqIX0XGURmQDSPqgA6rk+QZWjqCFJQAhvKGMBsKQAHFdjw6ZTpPSzByWNBbj+OJoTWWoIc5PkzmQA)). 

So far so good, but the only problem I see is that the intermediate "generated" nodes do not receive any name, and so they get displayed as "undefined". Even the leave nodes get "undefined" name, I guess they get also "generated".

Would it be possible to add a name also to the "undefined" nodes? I'm totally open for other ways to achieve this visualization.

Thanks!

**Comment by PBI-David** [comment]
I think this is a duplicate of here: https://github.com/vega/vega/issues/3406

**Comment by carlosgalvezp** [comment]
Nice, this is exactly what I was looking for! Thank you so much :)
