### ISSUE TITLE
Propagation order bug with derived data source.

### ISSUE THREAD

**Issue by jheer** [vega/vega#363]
I've found a situation where the evaluation order of the dataflow graph is incorrect. It arises when:
(a) an initial data set includes multiple transforms but no additional collectors (i.e., the `input` node acts as the primary collector).
(b) a derived data set (with `mutates` true) then tries to consume the tuples, but its populating `listener` node (which calls `Tuple.derive`) is invoked _prior_ to some of the transforms in the initial data set's pipeline.

Here is a schematic:
```
source:  input -> formula(1) -> formula(2) -> output
derived:    |---> listener -> input -> ...
```
The problem is that the invocation order is: `formula(1), listener, formula(2)`. This appears to be caused by the re-ranking procedure that is run when the derived data set is added as a listener to the source data set in `parse/data.js`. If I replace the re-ranking procedure in `vega-dataflow/Node.addListener` with a depth-first (rather than breadth-first) traversal the problem seems to resolve, _but_ I've not yet convinced myself that this is a valid solution free of other side-effects.

Below is a spec that reproduces the issue. If this ran correctly, the vis would show `1` upon initialization and `2` upon click (and then alternate). Instead it shows `undefined`, then alternates numbers in a lagged fashion (it also demonstrates a text rendering bug, but that is a separate issue I will resolve). Note that if you add the no-op transform `{"type": "filter", "test": "true"}` to the source pipeline the error goes away, as the filter forces a new collector to be included downstream.

```
{
  "width": 100,
  "height": 100,
  
  "signals": [
    {
      "name": "pf", "init": "a",
      "streams": [{
        "type": "click",
        "expr": "pf == 'a' ? 'b' : 'a'"
      }]
    }
  ],
  
  "data": [
    {
      "name": "predict",
      "values": [
        {"actual": 1, "a": 2, "b": 3}
      ],
      "transform": [
        { "type": "formula", "field": "predict",
          "expr": "datum[pf]" },
        { "type": "formula", "field": "diff",
          "expr": "datum.predict - datum.actual" }
      ]
    },
    {
      "name": "values",
      "source": "predict",
      "transform": [
        { "type": "formula", "field": "foo", "expr": "PI" }
      ]
    }
  ],

  "marks": [
    {
      "type": "text",
      "from": {"data": "values"},
      "properties": {
        "enter": {
          "x": {"value": 50},
          "y": {"value": 50},
          "align": {"value": "center"},
          "baseline": {"value": "middle"},
          "fill": {"value": "black"}
        },
        "update": {
          "text": {"field": "diff"}
        }
      }
    }
  ]
}
```

**Comment by arvind** [comment]
Addressed via a depth-first re-ranking in vega-dataflow@4cf093f.
