### ISSUE TITLE
Bug / Doc: "Expression Interpreter" example does not work with older Vega schemata (Altair)

### ISSUE THREAD

**Issue by NiklasBeierl** [vega/vega#3655]
Sorry if I am missing out on something obvious, I am not very familiar with vega, just a security guy making stuff work for my team. But I am pretty sure something is not right here. In the least, the Issue might help someone with similar problems.

My Team is working on an app with a python Webserver, which is deployed with a CSP.  I was very pleased to find the [Expression Interpreter](https://vega.github.io/vega/usage/interpreter/). ( Thanks a lot for investing into security! I am very happy I don't have to deny my team your cool library :) ).

We want to generate the plots using altair (v4.2.2) in the webserver  and then make them available to vega (v5.22.1) on the frontend via JSON endpoints.

Now here is the problem, when I use the example JS code:
```js
let view;

fetch('https://vega.github.io/vega/examples/bar-chart.vg.json')
  .then(res => res.json())
  .then(spec => render(spec))
  .catch(err => console.error(err));

function render(spec) {
  // Parse the Vega specification with AST output enabled
  // Pass a null configuration value as the second argument
  const runtime = vega.parse(spec, null, { ast: true });

  // Call Vega View constructor with an 'expr' interpreter option
  view = new vega.View(runtime, {
    expr:      vega.expressionInterpreter,
    renderer:  'svg',    // renderer (canvas or svg)
    container: '#view',  // parent DOM container
    hover:     true      // enable hover processing
  });

  return view.runAsync();
}
```
It works and renders the example on our page. 

**But as soon as I swap out your example url with a url on our server that returns json from altair, a blank plot is displayed!** An svg with some elements is created in the div container, but it's not showing a plot. There are **no** errors in the console.
Here is the altair code producing the chart on the webserver:
```python
    source = pd.DataFrame(
        {
            "a": ["A", "B", "C", "D", "E", "F", "G", "H", "I"],
            "b": [28, 55, 43, 91, 81, 53, 19, 87, 52],
        }
    )

    chart = alt.Chart(source).mark_bar().encode(x="a", y="b")
    return chart.to_json()
```
Now to the best of my knowledge, the highest schema version you can get out of altair is `v4.17.0`, but the expression interpreter example is in v5, so we figured that the expression interpreter only works with vega v5? But that struck me as odd, so I played around a bit and endet up discovering that [vega-embed](https://github.com/vega/vega-embed#api-reference) has explicit support for expression-interpreter via the `ast` option. So I replaced the render function from the example with:

```js
function render(spec) {
  vegaEmbed('#view', spec, {ast: true});
}
```
 And it worked with the json coming from our server (i.e. altair)! So in principle my problem is solved, but there is either:
 
- A bug preventing the example js code for "expression interpreter" to work with vega v4
- A chance to improve the example code for the expression interpreter. :)

**Comment by domoritz** [comment]
Note that Altair usually generates Vega-Lite, not Vega and the code snippet above assumes Vega. 

Vega-Embed handles both Vega and Vega-Lite and so maybe that's why it works.

**Comment by NiklasBeierl** [comment]
> Note that Altair usually generates Vega-Lite, not Vega and the code snippet above assumes Vega.
> 
> Vega-Embed handles both Vega and Vega-Lite and so maybe that's why it works.

Ahh, that actually makes a lot of sense, I wasn't fully aware of the difference.
And indeed, the altair output has schema: https://vega.github.io/schema/vega-lite/v4.17.0.json
And the example has schema: https://vega.github.io/schema/vega/v5.json

I guess the author of the Expression Interpreter page did not want to presume that vega-embed or vega-lite will be used. Rightfully so, they are separate packages for a good reason. 

Regardless, it might still make sense to include examples for vega-lite there? 

Looking at [this page](https://vega.github.io/vega-lite/usage/embed.html) it seems that the canonical way to mount a vega-lite plot is to use vega-embed? Or is there a way to use vega-lite directly. I looked around but couldn't find one.

If it makes sense to you, I would like to add this to the documentation of the Expression Interpreter:

If you are using vega-embed to mount your plots, you can use the `ast` option to enable the expression parser. This will also work with vega-lite specs. `vega-interpreter` is also already included in vega-embed, so you don't need to include it separately.

```html
<head>
  <meta http-equiv="Content-Security-Policy" content="script-src self cdn.jsdelivr.net" />
  <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-embed@6.21.0"></script>
</head>
<body>
  <div id="view"></div>
  <script src="main.js"></script>
</body>
```
```js
fetch('https://vega.github.io/vega/examples/bar-chart.vg.json')
  .then(res => res.json())
  .then(spec =>  vegaEmbed('#view', spec, {ast: true}))
  .catch(err => console.error(err));
```

**Comment by domoritz** [comment]
I think people should use embed and we have docs there. The Vega and Vega-Lite apis are lower level as you note. Looks like we have resolved this.
