### ISSUE TITLE
Unexpected padding on ordinal scale

### ISSUE THREAD

**Issue by floribon** [vega/vega#366]
When using an ordinal scale with the `points` property set to true, and a `padding` set to 0 (which is the default), there is still some padding on the edges of the axe.

You can see that on both pictures (on the x axis for the area chart and the y one for the heatmap)

![screen shot 2015-09-17 at 4 21 45 pm](https://cloud.githubusercontent.com/assets/2934743/9948479/4c5d6374-5d58-11e5-9f13-6eb4aae11a92.png)

![screen shot 2015-09-17 at 4 22 14 pm](https://cloud.githubusercontent.com/assets/2934743/9948480/4ecac96c-5d58-11e5-8b20-7cc40b2e6db2.png)

Here is the spec of the area chart, which is the same as the example with an `ordinal` with `points` scale instead of `linear`.

If that is expected for any reason please let me know. And best, is there a workaround (I tried negative padding with no success)

```
{
  "width": 500,
  "height": 200,
  "padding": {"top": 10, "left": 30, "bottom": 30, "right": 10},
  "data": [
    {
      "name": "table",
      "values": [
        {"x": 1,  "y": 28}, {"x": 2,  "y": 55},
        {"x": 3,  "y": 43}, {"x": 4,  "y": 91},
        {"x": 5,  "y": 81}, {"x": 6,  "y": 53},
        {"x": 7,  "y": 19}, {"x": 8,  "y": 87},
        {"x": 9,  "y": 52}, {"x": 10, "y": 48},
        {"x": 11, "y": 24}, {"x": 12, "y": 49},
        {"x": 13, "y": 87}, {"x": 14, "y": 66},
        {"x": 15, "y": 17}, {"x": 16, "y": 27},
        {"x": 17, "y": 68}, {"x": 18, "y": 16},
        {"x": 19, "y": 49}, {"x": 20, "y": 15}
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "ordinal",
      "points": true,
      "range": "width",
      "zero": false,
      "padding": 0,
      "domain": {"data": "table", "field": "x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "domain": {"data": "table", "field": "y"}
    }
  ],
  "axes": [
    {"type": "x", "scale": "x", "ticks": 20},
    {"type": "y", "scale": "y"}
  ],
  "marks": [
    {
      "type": "area",
      "from": {"data": "table"},
      "properties": {
        "enter": {
          "interpolate": {"value": "monotone"},
          "x": {"scale": "x", "field": "x"},
          "y": {"scale": "y", "field": "y"},
          "y2": {"scale": "y", "value": 0},
          "fill": {"value": "steelblue"}
        },
        "update": {
          "fillOpacity": {"value": 1}
        },
        "hover": {
          "fillOpacity": {"value": 0.5}
        }
      }
    }
  ]
}
```

**Comment by floribon** [comment]
Does anyone have news about this bug?

It is reproducible and an even simpler scenario: simply take the `bar` example of the vega-editor, and change the width from `400`to `350`.

An extra white padding appears on the left, which mess things in many scenarios (for instance trying to display a continuous x axis of combining multiple charts)

Here is how the `bar` appears with a width of `350`:

<img width="496" alt="screen shot 2015-11-04 at 12 41 24 pm" src="https://cloud.githubusercontent.com/assets/2934743/10951296/96a41586-82f1-11e5-905e-ec15c4a1c689.png">

Or a smaller one with no offset between bar where it is even more visible:

<img width="311" alt="screen shot 2015-11-04 at 12 38 21 pm" src="https://cloud.githubusercontent.com/assets/2934743/10951309/a510a9a4-82f1-11e5-8bd8-e61e5dcb4b75.png">

This is affecting many ordinal charts so I would really appreciate any hint on that, thanks.

**Comment by randyzwitch** [comment]
Don't know what causes it, but `offset` fixes it.

```json
{
  "width": 500,
  "height": 200,
  "padding": {"top": 10, "left": 30, "bottom": 30, "right": 10},
  "data": [
    {
      "name": "table",
      "values": [
        {"x": 1,  "y": 28}, {"x": 2,  "y": 55},
        {"x": 3,  "y": 43}, {"x": 4,  "y": 91},
        {"x": 5,  "y": 81}, {"x": 6,  "y": 53},
        {"x": 7,  "y": 19}, {"x": 8,  "y": 87},
        {"x": 9,  "y": 52}, {"x": 10, "y": 48},
        {"x": 11, "y": 24}, {"x": 12, "y": 49},
        {"x": 13, "y": 87}, {"x": 14, "y": 66},
        {"x": 15, "y": 17}, {"x": 16, "y": 27},
        {"x": 17, "y": 68}, {"x": 18, "y": 16},
        {"x": 19, "y": 49}, {"x": 20, "y": 15}
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "ordinal",
      "points": true,
      "range": "width",
      "zero": false,
      "padding": 0,
      "domain": {"data": "table", "field": "x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "domain": {"data": "table", "field": "y"}
    }
  ],
  "axes": [
    {"type": "x", "scale": "x", "ticks": 20},
    {"type": "y", "scale": "y"}
  ],
  "marks": [
    {
      "type": "area",
      "from": {"data": "table"},
      "properties": {
        "enter": {
          "interpolate": {"value": "monotone"},
          "x": {"scale": "x", "field": "x", "offset": -2},
          "y": {"scale": "y", "field": "y"},
          "y2": {"scale": "y", "value": 0},
          "fill": {"value": "steelblue"}
        },
        "update": {
          "fillOpacity": {"value": 1}
        },
        "hover": {
          "fillOpacity": {"value": 0.5}
        }
      }
    }
  ]
}
```

![vega](https://cloud.githubusercontent.com/assets/2762787/10951469/af046f94-830b-11e5-9f84-6c236a9bcfd8.png)

**Comment by floribon** [comment]
Thanks, this could be a (hacky) workaround but it is too chart-dependent, and most importantly it does not work on the bar example with a width of 350: any value of offset will still produce an exra padding on the left.

**Comment by jheer** [comment]
The spacing is due to the ordinal scale attempting to round to integer pixel values by default. The scale has `"round": true` by default. If you set `"round": false` then the scale will use the full width (but your ticks may end up anti-aliased).

**Comment by floribon** [comment]
Awesome, I was not aware `true` was the default value (not mentionned in the doc), thanks a lot.
