### ISSUE TITLE
STL or other 3D printer input for tactile "visualizations" for the blind

### ISSUE THREAD

**Issue by coderextreme** [vega/vega#367]
I would like to work on STL or 3D printer formats for Vega so that visualizations can be printed to 3D objects.   Please contact me if this has not already been done or it has been done and you have contact information.  Also please contact me if vega is looking for an extension.

**Comment by arvind** [comment]
Hi @coderextreme, this sounds very interesting! To my knowledge, no one is working on something like this so you're more than welcome to take a crack at it. I'd recommend looking at the [vega-scenegraph](https://github.com/vega/vega-scenegraph) module, in particular, which contains our code for the SVG and Canvas renderers. I'd imagine that an implementation for STL/3D will likely work at a similar abstraction level.

**Comment by coderextreme** [comment]
I found this, but the site is behind an invalid certicate beyond this one
page.  http://pseudotron.ist-dein-freund.de/gnuplot-to-3d-model.html
