### ISSUE TITLE
Module parse failed: Unexpected token after upgrading from 5.20.2 to 5.23.0

### ISSUE THREAD

**Issue by Pamwamba** [vega/vega#3683]
Hi, I just saw a warning that the 5.20.2 is vulnerable. (https://security.snyk.io/package/npm/vega/5.20.2)
I decided to upgrade it to vega@5.23.0, but when I run my project I got this error :
```
./node_modules/vega-label/build/vega-label.module.js 598:33
Module parse failed: Unexpected token (598:33)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     }
| 
>     let textWidth = d.textWidth ?? 0,
|         dx,
|         dy,
```

I dont know exactly why this happen and have no idea how to fix it. I saw similar topic that were talking about babel but I'm not using it.
I'm runnin on React 17.0.2, typescript 4.1.2 and my Node version is 14.19.0

**Comment by domoritz** [comment]
That's bullish coalescing (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) which should be supported in node 14. Make sure to upgrade your development dependencies and then it should work.

I don't see exactly what throws this error so I can't help more but I should have given you enough information to resolve the issue in your setup. 

Also note that node 14 is not supported anymore if you are concerned about security. See https://nodejs.dev/en/about/releases/.

**Comment by Waynezhi** [comment]
Hi @Pamwamba, I got the same thing with our vuejs project, you need to config your vue.config.js to use babel-loader for this folder:
```
chainWebpack(config) {
  config.module
      .rule('vega')
      .test({
        test: /\.js$/,
        include: path.join(__dirname, 'node_modules/vega-label/build'),
      })
      .use('babel-loader')
      .loader('babel-loader')
      .options({
        presets: ['@babel/preset-env'],
        plugins: ['@babel/plugin-proposal-nullish-coalescing-operator', '@babel/plugin-proposal-optional-chaining']
      }).end();
}
```

I use `"@vue/cli-plugin-babel": "^4.5.19", ` inside devDependencies of package.json
