### ISSUE TITLE
Wrongly duplicated functions in the 5.23.0 compiled bundle 

### ISSUE THREAD

**Issue by markov00** [vega/vega#3684]
It looks like the latest released version `5.23.0` contains a series of duplicated functions that wrongly interact with each others.

In particular, in my case, the `vega.scheme` function, used to set given new color scheme palette into an object called `schemes`, can't be used anymore correctly because the `configureScheme` function calls instead the duplicated function `scheme$1` that checks for color schemes in the object called `schemes$1`.

Looking at the compiled version in the `docs` folder I can see this:

https://github.com/vega/vega/blob/fb1092f6b931d450f9c210b67ae4752bd3dd461b/docs/vega.js#L14487-L14498

https://github.com/vega/vega/blob/fb1092f6b931d450f9c210b67ae4752bd3dd461b/docs/vega.js#L33224-L33235

https://github.com/vega/vega/blob/fb1092f6b931d450f9c210b67ae4752bd3dd461b/docs/vega.js#L21458-L21475C3

There are also other interpolated functions that are clearly wrongly bundled like `interpolateColors$1`, `colors$1`, `discrete$1`, `continuous$1`

The bundled code in `5.22.1` is ok and doesn't present that defect.
It could be due to the latest changes in the rollup configurations, I can't see much more that could have changed the compiled bundle in the diffs from `5.22.1` to `5.23.0`

**Comment by jheer** [comment]
Thanks! I'll take a look and cut a new release as needed.
