### ISSUE TITLE
Charts will plot outside when there are multiple lines for Y axis

### ISSUE THREAD

**Issue by keizer619** [vega/vega#371]
I have noticed this in Line charts, points will be plotted outside when there are multiple lines as in following screenshot. This only happens when there are multiple lines

<img width="722" alt="screen shot 2015-09-25 at 5 22 14 pm" src="https://cloud.githubusercontent.com/assets/2918812/10099641/275d8444-63a9-11e5-9867-481583bca9bd.png">

Then i was able to reproduce same behavior in Vega Live Editor for stacked area charts as following screenshot

<img width="856" alt="screen shot 2015-09-25 at 5 26 46 pm" src="https://cloud.githubusercontent.com/assets/2918812/10099684/9c442286-63a9-11e5-9b2a-ea29318dcffb.png">

The reason for this behavior is that Vega chart will draw chart by considering first Y axis values only. In first screen shot it has considered gdp column and draw the line chart, when population column value is greater than the maximum gdp value, it will be plotted outside. 

Please let me know if there are any workaround to get rid of this.

**Comment by jheer** [comment]
Thanks! It's hard to reproduce without a spec, but my guess is that the scales are not being set up correctly. Imagine you have two data sets you'd like to plot: (1) a data set named "tableA" that includes a variable "foo" and (2) a data set named "tableB" that includes a variable "bar". You'd like to plot both tableA.foo and tableB.bar on the y-axis. You should then set up the scale domain like so:
```
"domain": [{"data": "tableA", "field": "foo"}, {"data": "tableB", "field": "bar"}]
```

In the case of stacked graphs the scale domain should be driven by the sums of values at each x-coordinate (as is done in the [online stacked area example](http://vega.github.io/vega-editor/?spec=stacked_area)).

If you're still having problems after taking this into account, please feel free to respond with a specification that demonstrates the problem!

**Comment by arvind** [comment]
I'm going to go ahead and close this issue. If you're still experiencing issues, please provide us an example specification that demonstrates the problem. Thanks!
