### ISSUE TITLE
Deprecate predicates in favour of expressions

### ISSUE THREAD

**Issue by arvind** [vega/vega#372]
Our expression language is almost sufficiently powerful to deprecate predicates. The remaining expressivity gap centers around functionality provided by `in` predicates: (1) ranges over ordinal scales, and the simplicity of specifying min/max for quantitative values/scales; (2) extensions/checking for membership within a dataset. 

One option would be to introduce functions to address each of these:

* `in_range(val, a, b, scale)` Tests is `val` is between the `a` and `b`. If `scale` is provided, performs the necessary scale inversion. In the case of ordinal scales, this would check if `val` exists in the set returned by the inversion. 

* `in_data(val, data, field)` Tests if the data set named `data` contains a record whose `field === val`.

**Comment by arvind** [comment]
An open question: would we want to introduce a top-level `expressions` property to enable named expression reuse? Presumably yes. Expression properties in the rest of the specification (e.g., `filter.test`, `formula.expr`, `streams.expr`, etc.) could then be either defined inline or reference a named expression (e.g., `"expr": "datum.a + 1"`, `"expr": {"name": "isSelected"}`). 

Similarly, production rule branches could define the conditions for each branch inline, or invoke a named expression. For example, `"rule": [{"test": "datum.x > 5", "value": "grey"}, {"test": {"name": "isSelected"}, "value": "yellow"}]`.

**Comment by arvind** [comment]
One downside: moving predicates into the expression language makes it more difficult to statically analyze them, e.g., as part of @jhoffswell's work. This could be ameliorated by exposing the AST of the parsed expressions.

**Comment by kanitw** [comment]
>  One downside: moving predicates into the expression language makes it more difficult to statically analyze them, e.g., as part of @jhoffswell's work. This could be ameliorated by exposing the AST of the parsed expressions.

This might also make it a little harder (though not impossible) to develop UI for manipulating the expression.   Vega-lite team are facing the same issue whether we should have “aggregate” and “timeUnit” properties in the encoding spec.

**Comment by arvind** [comment]
@kanitw, Expressions are pretty pervasive in a Vega specification already, so higher-level tools will likely already need to develop a UI to support them, independent of this issue. I'm not sure I understand why adding two new methods would make developing such a UI harder? Could you elaborate?

Similarly, not sure I understand the concern with `aggregate` and `timeUnit`? Do you use predicates or expressions in there?

**Comment by kanitw** [comment]
I'm consider to replace timeUnit with expression.  The original reason that we introduce it as a special property is that we do not have to write our own parser.   
But now that we have vega-expression as its own project, higher level tools like Polestar and Voyager should definitely use the parsing capability to implement the UI. 

For aggregate, we might keep it as a special property at least for now -- unless there is an easy way for us to parse the aggregation function and properly generate aggregate transform, which could be messy.
(If this sounds confusing, let's talk more about it in person when I'm back in town.)

**Comment by arvind** [comment]
Yes, we should talk in person because it's still unclear to me why adding deprecating predicates in favour of expressions affects vega-lite's `timeUnit` or `aggregate` functionality. Note that (part of) the reason I have this issue here, rather than in the vega-expression project, is because I imagine these methods will extend the compiled expression much like our `event` methods [currently do](https://github.com/vega/vega/blob/master/src/parse/expr.js#L10).

**Comment by kanitw** [comment]
Ah let me clarify a bit.  I wasn't very clear at first.  

> why adding deprecating predicates in favor of expressions affects vega-lite's timeUnit or aggregate functionality

It does not.  I'm just noting that we have the same experience that expression make UI develop a little harder – as the UI has to be aware of the AST of the parsed expression like you mentioned above.

**Comment by arvind** [comment]
Done with #478! Thanks @RussellSprouts!
