### ISSUE TITLE
Build broken vega 5.23.0

### ISSUE THREAD

**Issue by mateBe95** [vega/vega#3726]
ERROR in ./node_modules/vega-embed/build/vega-embed.module.js 1854:17
11:24:54  Module parse failed: Identifier directly after number (1854:17)
11:24:54  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
11:24:54  |   // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
11:24:54  |   const editor = window.open(url);
11:24:54  >   const wait = 10_000;
11:24:54  |   const step = 250;
11:24:54  |   const {
11:24:54   @ ./node_modules/react-vega/esm/utils/updateSingleDatasetInView.js 1:0-34 8:24-28
11:24:54   @ ./node_modules/react-vega/esm/utils/updateMultipleDatasetsInView.js
11:24:54   @ ./node_modules/react-vega/esm/Vega.js
11:24:54   @ ./node_modules/react-vega/esm/index.js

**Comment by domoritz** [comment]
We need some more details here. What's at the error location? It looks like it's a webpack issue.

**Comment by mateBe95** [comment]
@domoritz 
 "webpack": "4.43.0",


```
ERROR in ./node_modules/vega-tooltip/build/vega-tooltip.module.js 449:59
Module parse failed: Unexpected token (449:59)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       this.el.setAttribute('id', this.options.id);
|       this.el.classList.add('vg-tooltip');
>       const tooltipContainer = document.fullscreenElement ?? document.body;
|       tooltipContainer.appendChild(this.el);
|     }
```

**Comment by domoritz** [comment]
You need to update your workflow to support the ?? operator. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing
