### ISSUE TITLE
Should scale domain value be accessed in axis via `datum.data`? + Missing Docs

### ISSUE THREAD

**Issue by kanitw** [vega/vega#373]
From my experiments, it looks like in Vega 2 we now refer to the scale value in the template/expression inside axis’s `properties` with `datum.data` while in Vega 1 we just use `data`.  

1) Why should it be `datum.data` rather than just `datum`?  

2) We should update documentation in the [Axes](https://github.com/vega/vega/wiki/Axes) and [Upgrading to 2.0](https://github.com/vega/vega/wiki/Upgrading-to-2.0) pages.

**Comment by arvind** [comment]
(1) Yes, this is was a change introduced to both make the expression and template languages consistent, and allow for direct referencing of signal values by name. I don't believe this is specific to axes/scales?

(2) The [Expressions](https://github.com/vega/vega/wiki/Expressions) and [Templates](https://github.com/vega/vega/wiki/Marks#templates) documentation already reflected this change. I've now [updated the upgrading](https://github.com/vega/vega/wiki/Upgrading-to-2.0#expression-language-and-templates) page as well. Thanks!

**Comment by kanitw** [comment]
For (1), I still believe that this is weird.  

Axes are different from marks in the sense that each datum represents datum object from the scale's domain, which is usually already a value (due to field reference call in the scale creation) rather than the whole datum object (which represents an entire row) like in marks.  

So I wonder why we put the whole datum object in `datum.data` in axes
since here we do not refer to a property called `data`, but actually the whole datum object.

**Comment by arvind** [comment]
I don't agree that axes are different from marks. In fact, behind the scenes, axes are parsed to produce the necessary constituent marks (rules and text) and flow through the remainder of the build/encode infrastructure as regular marks. As a result, these marks are backed by data that is ingested in the same way as the rest of the spec (i.e., within a wrapped object with a `data` property). 

The change you're suggesting introduces complexity and makes the specification language inconsistent between axis submarks and regular marks. For example, consider a data source with inline values `[1, 2, 3, 4]`. This would be ingested as `[{_id: 1, data: 1}, {_id: 2, data: 2}, {_id: 3, data: 3}, {_id: 4, data: 4}]` (#375 notes we need to document this). A mark drawing from this data source could then make a value reference like so: `{field: "data"}`. This is a shorthand for `{field: {datum: "data"}}`. The template follows suite: `{template: "datum.data"}`.

**Comment by kanitw** [comment]
Thank you.  I think this makes sense now. 

However, I think this part is hidden from the user and should note in the document. 

> As a result, these marks are backed by data that is ingested in the same way as the rest of the spec (i.e., within a wrapped object with a data property).

Reading the [doc about axes' `properties`](https://github.com/vega/vega/wiki/Axes) that simply says

> Optional mark property definitions for custom axis styling. The input object can include sub-objects for `ticks` (both major and minor), `majorTicks`, `minorTicks`, `labels` and `axis` (for the axis line).

Most users without deep understanding of Vega data ingestion will not know that data got wrapped in the `.data` property and thus they can refer to the scale data via `{field: "data"}`, `{field: {datum: "data"}}` and {template: "datum.data"}.  

In fact, I totally forgot about how Vega ingests data so I only find that we need it works by debugging and guessing and get it works while still get confused.  (That's why I asked!)

To make it clearer, I just appended the following text to the doc for `properties` in [Axes](https://github.com/vega/vega/wiki/Axes) and [Legends](https://github.com/vega/vega/wiki/Legends) to make it clearer.  

> These mark property definitions can make value references to their scale domain data via `data` property like so: `{field: "data"}`. This is a shorthand for `{field: {datum: "data"}}`. The template follows suite: `{template: "datum.data"}`.

Feel free to further modify it.
