### ISSUE TITLE
Reorganize Value References Doc?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#374]
The table that contains scale, multi, offset, band looks a bit out of place in the [Value Reference Doc](https://github.com/vega/vega/wiki/Marks#value-references).  

Should "field reference object" be extracted as a section under Value Reference?

**Comment by kanitw** [comment]
Just a note that I got confused by the same part of documentation for the second time in a month :)

**Comment by arvind** [comment]
Agreed, that was confusing. I opted for a simpler fix for now -- making the ValueRefs table unbroken, and then having the "field reference object" section follow.

**Comment by kanitw** [comment]
Cool.  I like the new organization and just further modified it a bit (https://github.com/vega/vega/wiki/Marks/_compare/aeaaa74ea17bf647c4234d7e2295308e7d87e532...5ed6548cfe66a8c38dc048fe4744574cc291873a).
