### ISSUE TITLE
Data wiki page does not explain raw array transformations

### ISSUE THREAD

**Issue by jeffbaumes** [vega/vega#375]
Perhaps I'm just missing it - but I think it would be good to explicitly state what happens in the case of raw arrays like `[1, 2, 3]`. I think it's accurate to state that it is transformed into:

```json
[{"_id": 0, "data": 1}, {"_id": 1, "data": 2}, {"_id": 2, "data": 3}]
```

It is helpful to know that data in this case is referred to by `datum.data`.

**Comment by arvind** [comment]
Thanks Jeff! Now documented.

**Comment by jeffbaumes** [comment]
Great! I made a tiny adjustment so the full JSON appears without scrolling to the left - feel free to change if you don't like it.

**Comment by arvind** [comment]
:+1: Thanks Jeff!
