### ISSUE TITLE
Morocco and Western sahara is showing different in topo json 

### ISSUE THREAD

**Issue by vjai29** [vega/vega#3756]
We are using Vega-lite to draw a global map, we have used the topo-json provided by Vega.

sample URL 
https://vega.github.io/vega-lite/examples/geo_params_projections.html

when we compared Morocco and Western maps generated from Vega Topo Json with the UN map of Morocco and Western Sahara, it was totally different.

UN Map https://www.un.org/geospatial/content/africa-2

UN MAP for Morocco https://www.un.org/geospatial/content/morocco

below are screenshots using Vegalite topo Json file ie. below URL

https://vega.github.io/vega/examples/world-map/

[Western Sahara](https://i.stack.imgur.com/gvf7G.png)

[Morocco](https://i.stack.imgur.com/IdD1O.png)

Need your help to modify the TopoJson to achieve similar to UN map shape for Morocco and Western Sahara.

We tried modifying pixel values, it is very complex, need your support to modify the TopoJson to achieve similar to UN map shape for Morocco and Western Sahara.

**Comment by wiibaa** [comment]
I suppose the topojson included in vega are more for demonstration purpose and may not be accurate or latest version.
The error would lies on the topojson itself and not in how Vega is rendering it, for example I loaded a more recent version from https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json in both Vega and mapshaper.org 

![image](https://github.com/vega/vega/assets/659227/82efe2f7-30cd-489f-b232-1118164323eb)
![image](https://github.com/vega/vega/assets/659227/b7f8989d-4d3c-4ad5-858e-fa942935462b)


Alternatively I used Eurostat GISCO provided data from https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/countries

into following example : [Same example using Eurostat GISCO provided topojson](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAEUCQDMaZBoqRMANnG3Ic2tvt1sG4zMoV2H9KwHc2i87KU0iDeNLL0aACcAAzRMvBGWGgCsTJIDJhsEDQAXnBoIOIS+TLZZOJI5hBoANqgFQj56JgAnjglIMSVDE0gjYpQSJmKwUw04rJooOM4GQUQcJZQmMFsqurVqDUglUxwitVp5nsHAKoQKGk5NAgZMJUAogCODJWainCXO9e39I8vYRoEEwSBcwT04hoUAAwgY-MhzOCJFDnq9zO9PkjIVBUYDgaCVjI4C9HkhFBEiQCPstQcZzGTguU2AhkVBgv1BsNghVMCZSeSYABGVYCthkUw4GBQ4LA-ZwMUSqVsmSuUEQUgHOAAWX2nL8IAAugBfI1SepIRrzQaWYJdcw9NCClIyMYTKYgGZzdCmcRkDoIcbJOJ9JAADzQACZYsHZThHSazYULb1FGwQZg4NFbd0msHXZNUNNxLMVt7af7A6gALSCgAcweQ4dQdZjGbjzYT5st3rTQzgwpkdodqDz4wLRZLBR9fvZlarMRkjairbg7cFnaT3ZAqfTcAj2ftuZdY-dntL2-Ls40Nfri7DjtvIFj8dNXd6UDgLn2WcHObQo7dQsPWLL0L19CtrxbO8mygp82xfRMGnfT8M0UAdOj-Edj0AidQOnCC0HnBt71QBc4NXBC3wKVVxAgekMx-EAGBwWQ+wKUJwhgbQCG0fdX03XoaLovt0OY1iMwKBIyCwbjeJAfikIKcUhihBhLAAESQCAYAPYcAPHYDJzLWR2FWdYJE2Go4gAZikAQpEFaJjQU5MCiYPx5EUAB1MIKQww9HWwgyz2ouBQxWDdFPQJgkCgABrcUnDdX8AvQABifRMqy0YTyAkL0D0cx9Ui1z0HGDVCX84d9EqBYgtPEDz1gOB4vc8MTQNGQcFTYQWrUCzaio9BurYXrlnUYJWnad0ygqRFmjafJTSfa0mlAWbKitSolpkHc2K2dajDmqdewY+TEw2+bt1O-tzsO8pNp7Xc+M6kAPy-EYDqfI7HrelDvzu76Hqu97UOFI1XqE+imjqIHjuaH1hLO-jLuoxHofB41XvElAvqikI-ACYITCurBcHwIhaGgNgqwWRRiChBRKBa5mTDWKg4AYAgTOBZQmAydQSAjAg9GcVwaAUAhMhwUaxHEAhoQAOQAFQAJQAfVVgBxdXHK1dWoyjdWABZrIjAA2EQ5eCfR4SGd0psEtZZYkG3Pl5D4CiVtXNZ1vWDeiI3TYt+SXK3ZS1CgNSOiE23FAQQaQEdpTTEj6P5Kxu9FDiyzQGT9BtKQaaZH0VME6AnGU5UqObWWz89Hkd0xP29bXDYOK4B8zj3SHJp11KNuO807SZp+q6agAagj1SNK0mApG0KfU5nuBh5gA1zrg1MO9H4GCnK-ZMG0AB+bQAHI0uNq+z+0VBz7S2RH7PzfDHMebQF7tBxDU8wTWW2P4SJ3ziAP0WR7jFxACNMa-UNCQJ6n1CaEN+LAMLhA0uzJ3SV3QL4fwkw67iAbmtJiLEW5b3bp3XyOkgKo3QBPdyihPJdwiMtXm5Dd7w2AhVE+98ADsfCb53wvkwYRz9lqv3fnDX6B9yTcIvllAR99oyiJkNcCYYUe6YWiAmDAbANQzUHhQ7u1Cx4FDoR5fYTCuIT20ODAe28iGf3QIYD4TBlDxU3qo+QTYP6YXXNogB8cgGLSUvKVBHQoEINdsNeB41XZIONEAA)

and the result seems to be what you are expecting
![image](https://github.com/vega/vega/assets/659227/8d20d5c6-c0e3-43b6-bbb6-07e501660b6d)

**Comment by domoritz** [comment]
Yes, that's the answer. We can update vega-datasets if you'd like to make a pull request.
