### ISSUE TITLE
Document "output” property’s format change.

### ISSUE THREAD

**Issue by kanitw** [vega/vega#377]
For bin transform,  the `output` property takes string as input in Vega 1. 
However, it takes an object of format  `{bin: __newname__}` in Vega 2.

I’m guessing that `output` property’s format has changed in some other transforms as well.  

We should document this in the [Upgrading to 2.0 Page](https://github.com/vega/vega/wiki/Upgrading-to-2.0).

**Comment by arvind** [comment]
From the looks of it, Bin was [the only transform](https://github.com/vega/vega/tree/v1.x/src/data) that supported an `output` property that did _not_ take a mapping object. Odd. But noted in the Upgrading docs regardless. Thanks!
