### ISSUE TITLE
Broken vega X

### ISSUE THREAD

**Issue by sub2GABIgaming** [vega/vega#3779]
So I play a game on roblox nammed bloxfruit, I use a hack on vega X called Hallo Hub and each time I leave after I use the hack the game doesn't save my level but it always does when I'm not hacking so I spent a whole day hacking and I started at level 1698 and at the end I was at level 2303 but today when I turned it back on it went back to 1698 and nothing saved except my 2x exp timer just went down like if I was there and it is not the 1st time this happened

**Comment by domoritz** [comment]
This is not the gaming engine but a visualization framework.
