### ISSUE TITLE
Throw error if undefined variable/property is referred in filter transform.  

### ISSUE THREAD

**Issue by kanitw** [vega/vega#378]
For example, I forget to add `datum` in filter transform’s `test`.  
However, I do not get any error/warning in the console.

**Comment by arvind** [comment]
It is not necessarily an error to have a filter transform that does not test against `datum` -- e.g., you may want to filter tuples solely based on a signal value. Similarly, `undefined` may be a valid value for a property within `datum` or a signal. 

In the event that the expression parser finds a signal reference that does not exist, a `TypeError` is thrown. As per your issue vega/vega-dataflow#6, vega/vega-dataflow@181939d replaces this with a friendlier error message. This will be included in the next version of Vega.

Please re-open this issue if there're other cases not covered above.

**Comment by kanitw** [comment]
Make sense. Thanks.
