### ISSUE TITLE
Renaming Stack’s output

### ISSUE THREAD

**Issue by kanitw** [vega/vega#379]
From `Stack.js` and `Pie.js`, it looks like that to rename the output fields I have to provide output’s `start`, `end`, `mid` properties. 

We should either
a) add `layout_` prefix to `start`, `end`, `mid`  in the output so the documentation would be simple as is.  (The docs says that default names are layout_start|end|mid and people can rename it. )

or 
b) update the documentation to reflect this fact

**Comment by jheer** [comment]
I would recommend using the default Vega 2 output field names.

**Comment by jheer** [comment]
Actually, I think `<field-name>_start|mid|end` is also good. It looks like
that's what you settled on, so no need to change it.

**Comment by jheer** [comment]
(Oops... note that comments above pertain to vega-lite naming decisions. We will address the code/docs disparity here in Vega.)

**Comment by jheer** [comment]
Documentation now updated to convey both output parameter keys and default property names.
