### ISSUE TITLE
Ability to get selected facet in selection handlers

### ISSUE THREAD

**Issue by saliksyed** [vega/vega#3795]
I have a faceted heatmap. I'd like to store the users selection within a particular facet using a box selection. The selection callback takes in encodings and returns intervals -- after several hours exploring, it seems like there is no way to get the actual facet that the selection lies in. 
```
{
    name: "box",
    select: { type: "interval", encodings: ["x", "y"] },
    resolve: "union",
  };
```
This would be a very useful and important feature for us -- happy to help contribute if someone can guide me on where to start.

**Comment by domoritz** [comment]
Selections are in Vega-Lite. Can you file an issue there instead?
