### ISSUE TITLE
Delayed processing of interactions

### ISSUE THREAD

**Issue by jheer** [vega/vega#380]
Interaction processing may be inexplicably delayed, as evidenced by this example:
http://bl.ocks.org/iaindillingham/0683f7ddb90c263c6d92
http://bl.ocks.org/iaindillingham/raw/0683f7ddb90c263c6d92/

In the example, one must drag the brush around for some time before the linked color changes on the map start occurring.

**Comment by arvind** [comment]
I believe this is a result of event processing w/group marks. Adding `"fill": {"value": "transparent"}` to the group mark resolves the issue for me. Will re-open the case if Iain reports continued delays/latency.
