### ISSUE TITLE
Reactively add new marks to existing chart

### ISSUE THREAD

**Issue by yw2278** [vega/vega#3831]
Is it possible that vega can update chart via api or javascript **reactively** when new marks needed to be added?
For example the existing multiline chart have google apple microsoft etc. 
![image](https://github.com/vega/vega/assets/22030956/fd02c060-69d8-4622-a884-a580bad1cd45)
Then I want to add  **meta stock price** in the chart, which is not in the data before, and I want to add the meta stock line **reactively**, _not  repaint the whole chart_, is it possible to do that in vega/vegalite?

**Comment by domoritz** [comment]
Yes, Vega can reactively update. Check the docs about the view api.

**Comment by yw2278** [comment]
Thanks for the reply，I check the docs but cannot find an api that can add a dataset. I know that view can insert data into already exist dataset, but is it possible to insert a whole new dataset?

**Comment by domoritz** [comment]
Look at https://vega.github.io/vega/docs/api/view/

You cannot add new marks. You need to define them in the spec from the beginning but they can have an empty dataset.

**Comment by yw2278** [comment]
Thanks! Now I understand.
