### ISSUE TITLE
"Extent" property for Regression does not modify the regression extent and nullifies the regression.

### ISSUE THREAD

**Issue by chknfr1ed** [vega/vega#3838]
When I try to add the "extent" property as listed in the [vega-lite documentation,](https://vega.github.io/vega-lite/docs/regression.html) the regression no longer exists and instead the data becomes a line chart.

[This](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygK4CcA29zQgegLYHsA3ASwFMBnAOgCtz8A7EAXwBoRUIBPU5eAbVC4IyANbxQUTgAdSGKfmL0oINgDNiqVKTDwoyRKVYhS9AMb4wigObiQAD1vrSqHXBAAlfFCgmABABV8ISh8Cl93aGsVEEkZDABHRAglYhgoYkJZI05HMhcMAEkAWQARACFwyPobNljZN0Tk9LSMrKZWQWExBBjpevZFWTZzVHxeN3VkUgAjZGJTMSM9ZPJVMdx+UCmrKfJyYgZC0oqI9Orow7dPbz9A4NDySrObJgBdNhNzS3Oehx6nfJXLw+egBILQB5PKK1PoJJIpFqZZhsHL-PKuEDFcpQ84wuINeHNSJI9odGLIFZrZAbOACEDbXb7S6Y444mogZnXEFg+5hU7QkBSYQQXDkXT6QwsUCmCCoUyIDg+DAAcncACa4L5lQBqKnBAAUkCgiFwlGQAGVGlMwCwtZQAEyqZUASmiEDFV3tzHeICEolsdQwPjsymG+FG4xAkxmcwW0T+IAA7sQwFAABZu1DEKyMNxzKxp0MgVEAWgArEZPhYoj1g8pa7C3PQgopZdEARj3F7Sa8mEA) is the example pulled from the regression example in the vega-lite documentation:

![image](https://github.com/vega/vega/assets/152239887/b39d8ec2-1b27-434e-9aa3-cec0d128d910)

However, when I add in the extent property to the example, [this](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygK4CcA29zQgegLYHsA3ASwFMBnAOgCtz8A7EAXwBoRUIBPU5eAbVC4IyANbxQUTgAdSGKfmL0oINgDNiqVKTDwoyRKVYhS9AMb4wigObiQAD1vrSqHXBAAlfFCgmABABV8ISh8Cl93aGsVEEkZDABHRAglYhgoYkJZI05HMhcMAEkAWQARACFwyPobNljZN0Tk9LSMrKZWQWExBBjpevZFWTZzVHxeN3VkUgAjZGJTMSM9ZPJVMdx+UCmrKfJyYgZC0oqI9Orow7dPbz9A4NDySrOa4zsfJX4ABhYAVk+AXSY-zYJnMlnOPQcPSc+SuXneASC0AeTyitT6CSSKRamWYbBy0LyrhAxXKqPO6LiDSxzUiuPaHRiyBWa2QGzgAhA212+0uJOO5JefOuCLuyLCpzRICkwgguHIun0hhYoFMEFQpkQHB8GAA5O4AE1wXy6gDUrOCAApIFBELhKMgAMqNKZgFgmygAJlUuoAlNEIAqrp7mMCQEJRLY6hgfG9oiMxhhJjM5gtolCQAB3YhgKAACwDqGIVkYbjmVjzynx8AAtD8jKCLFEerHlC2MW56EFFOrojDie4QwzAUA) is the result:

![image](https://github.com/vega/vega/assets/152239887/f93e17a7-f915-4782-8570-1a1d94065bfc)

**Comment by PBI-David** [comment]
Another question on SO: https://stackoverflow.com/questions/77845962/regression-line-issue-in-vegalite-charts

**Comment by chknfr1ed** [comment]
Got it, I mistunderstood. I've moved it to the VL group. Thanks!
