### ISSUE TITLE
Vage ordinal scale domain support group mapping to range

### ISSUE THREAD

**Issue by yw2278** [vega/vega#3839]
When using ordinal scale in vega, I havedomain ["MSFT", "GOOG", "AAPL", "IBM"] and range ["stroke", "square", "circle"].
I want ["MSFT", "IBM"] map to "stroke", "GOOG" to "circle" and "IBM" to "square", does vega support this kind of grouped mapping?

**Comment by jheer** [comment]
You should be able to simply include repeated values in your range array, e.g., `["stroke", "square", "circle", "stroke"]` in parallel with your domain values.

**Comment by yw2278** [comment]
Got it
