### ISSUE TITLE
Proposal for new `sumnull` aggregation

### ISSUE THREAD

**Issue by nicolaskruchten** [vega/vega#3848]
Today, the Vega `sum` aggregation returns 0 if its inputs are all `null`, whereas the `average` operator returns `null`. As a result, simple line charts which might be expected to be equivalent look quite different, with the `sum` line going to zero and the `average` line being interrupted:

<img width="1052" alt="CleanShot 2023-12-19 at 10 32 38@2x" src="https://github.com/vega/vega/assets/203523/65a9fc8c-b5a6-470b-94c7-974eaa75fa41">

[Spec in Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoAB5oAjEoCeFgL4LTaAEzXn9x6gDMr1LIaDBdxAzVAAWH1CgkLEfMVsAXXsQKDkoNSNQZAAnAGs0UEwrHDg0EGFZEqUcNhpZTDRMLL0kuFkU5VqyfODugDMaOEFlUrMlQuLSgEcGJDq6NRpSECSbTRB+weH0GzGikvRp2cx546WlJDIyLL5MfeS2Bjrl2yDsvLXxu-LKkGra+tQjWaSla7U63RCoA2QxGihAnymMzm6lOJRWfQGMO2cIRByRxxRix+FyuNzu2mEwxeryQuW6uLKtR+fyegKacBabTYHVkXTWkPWmK2PV2EzxRxOROWPihQtKO3he0REsJZxAJOuFFupQgDAQzxpdI+SvQ3zhLIBQI5IK5PL5Hllm1horuh2RCyW6LW0OFCoZboJHuJl01ajuSFIWQuaJeiSAA)

A number of stakeholders of our application would like to be able to have the ability to have `sum` behave like `average` in cases like these, and while I can imagine there is very little appetite for changing the behaviour of `sum` in Vega, I'd like to propose the addition of a new aggregation `sumnull` which would behave the same as `sum` but return `null` when its inputs are all all `null` or otherwise invalid. 

Would the Vega team accept a pull request for such a feature?

**Comment by domoritz** [comment]
Hmm, I wonder what the reason for the different behavior was. Pinging @jheer @arvind

**Comment by jheer** [comment]
Maybe it would make more sense to update the existing sum to have more SQL-like semantics. I don’t  think we had any principled reasons for the current behavior.

**Comment by domoritz** [comment]
Great. I like consistency. @nicolaskruchten do you want to send a pull request and check for any regressions? We can argue that the previous behavior was a bug or at the very least undefined.

**Comment by nicolaskruchten** [comment]
On it!
