### ISSUE TITLE
Custom fuction in vega expression

### ISSUE THREAD

**Issue by kachkaev** [vega/vega#385]
I'm wondering if it is possible to add a new function to be used in vega expressions like this

``` javascript
...
"transform": {"type": "formula", "field": "myNewField", "expr": "myFunction(datum.mySourceField)"},
...
```

After looking at how things are done in `vega/vega-expression`, I tried the following but it did not work:

``` javascript
// Include vega.js and dependencices

window.myFunctionInRealLife = function(value) {
  return value * 42;
}
vg.parse.expr.codegen.functions["myFunction"] = function(args) {
        var a = args.map(vg.parse.expr.codegen);
        return 'window.myFunctionInRealLife('+a[0]+')';
    }

// Use myFunction in a vega spec
```

It would be nice to see a temporal workaround and a proper solution in future releases.

_Just in case: my specific goal is to calculate centroids for geopolygons after they have been projected (i.e convert layout_path to some [x,y]). This can be done using [d3.path.centroid()](https://github.com/mbostock/d3/wiki/Geo-Paths#path_centroid)._

**Comment by jheer** [comment]
Thanks @kachkaev! The expression language is extensible, but at the moment not without performing a custom build. This can also result in specifications that are not usable by others, so in general we are wary of this form of extensibility.

Based on your description, this might instead be a good candidate not for an expression method but a new top-level transform. We intend to release a plug-in system for extensible transforms, but in the meantime it suffices to add an appropriate class to the `vg.transforms` hash. In this case, you might add a simple transform that applies d3.path.centroid to a path attribute.

The [bin](https://github.com/vega/vega/blob/master/src/transforms/Bin.js) transform might be a good starting point, as that similarly only updates the properties of individual objects. If you do end up writing this, feel free to open a PR for inclusion in the library.

**Comment by kachkaev** [comment]
Thanks for these advice Jeffrey and also for planning to make vega extensible in future. It rocks!

**Comment by nyurik** [comment]
I also ran into the issue of needing a custom expression function.  For my usecase, I need users to be able to modify external state of the graph, e.g. call `makeGlobalModification(...)` when some event happens.  At first I was thinking of creating a new function, but it seems the easiest would be to create a new "write-only" signal - pushing a value to that signal would be similar to making a function call.

**Comment by jheer** [comment]
The original issue was specific to Vega 2.

In Vega 3, you can add new expression functions using [`vega.expressionFunction`, a method exported by vega-parser](https://github.com/vega/vega-parser/blob/master/src/parsers/expression/codegen.js#L102). The signature is:

```js
expressionFunction(name, fn, visitor)
```

- The _name_ argument is a string indicating the name of the function as used in the Vega expression language.
- The _fn_ argument is the actual function to invoke.
- The _visitor_ argument is an expression AST visitor which can be used to perform dependency analysis (e.g., for scale or data source lookups). For most basic functions no _visitor_ is needed, in which case this argument can be omitted.

New expressions must be added *before* parsing a spec that uses the custom function. Also this is a *global* operation, and all subsequent Vega views will have access to the function.

We will update the documentation with the above information; closing out this issue now.

**Comment by nyurik** [comment]
@jheer thanks! Does the `fn` parameter get context of the graph, similar to how `options` are passed to the `data.load()` function?  In our case, each graph could have its own context, so the function execution may depend on that.  Thx!

**Comment by jheer** [comment]
Good question! The `this` context bound to the function includes a `context` property that is the runtime context object for the Vega View. To explore this yourself, go to the [Vega home page](https://vega.github.io/vega/), open the console, and try this:

```js
vega.expressionFunction('foo', function() { console.log('foo!', this); });
var spec = {signals: [{name:'bar', update:'foo()'}]};
var view = new vega.View(vega.parse(spec)).run();
```

**Comment by nyurik** [comment]
Thanks @jheer, awesome answer!!! Can't wait for the docs :)

**Comment by nyurik** [comment]
@jheer clarification: `this`-bound context is all Vega objects, not client-supplied. Where would you recommend attaching custom data or functions?  For example, this code doesn't seem like a good idea because I am changing Vega View from outside, which might conflict with the future Vega changes:

```js
//--------- GLOBAL
vega.expressionFunction('myCustomFunc', function () { 
  return this.context.dataflow.myCustomHandler.apply(null, arguments);
});

//----------- PER VIEW
const view = new vega.View(vega.parse(spec, parseOptions), viewOptions);
view.myCustomHandler = () => {...};
```

Also, I noticed that `viewOptions` supports `functions` parameter, that by default uses `functionContext`. The [View API docs](https://vega.github.io/vega/docs/api/view/#view) don't mention it. Would that param be of any use in this case, and if so, how can I access the original `functionContext` to override it? Thx!

**Comment by jheer** [comment]
Why bother assigning `myCustomHandler` to the View? Why not something like this instead?

```js
// -- ALL GLOBAL DEFINITIONS, BUT WITH VIEW-SPECIFIC INVOCATION

if (!vega.expressionFunction('myCustomFunc')) {
  vega.expressionFunction('myCustomFunc', function () { 
    return myCustomHandler.apply(this.context.dataflow, arguments);
  });
}

function myCustomHandler(arg0, arg1, ...) {
  // 'this' resolves to the invoking View
}
```

NOTE: If you do this, do **not** use an [arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) for `myCustomHandler`. Arrow function have a different `this` semantics than normal functions.

Of course, alternatively you could just put your function body inside the function argument to `expressionFunction`...

**Comment by nyurik** [comment]
@jheer `myCustomHandler()` needs to have context beyond what's available in the View.  The View is created elsewhere, and as part of that creation, I have some state, e.g. some object reference that the graph spec came from. In a slightly more verbose example, here's the basic implementation one has to do to have a state beyond the Vega's View instance:

```js
if (!vega.expressionFunction('myCustomFunc')) {
  vega.expressionFunction('myCustomFunc', function () { 
    return myCustomHandlerRedirector.apply(this.context.dataflow, arguments);
  });
}

class Graph {
  render() {
    this._view = new vega.View(vega.parse(this._spec));
    // call myCustomHandler on this instance of my Graph class
    this._view.myCustomHandlerRedirector = () => this.myCustomHandler();
    return this._view.runAsync();
  }
  myCustomHandler() {
    // take action that requires "this" (which has state beyond the Vega View instance)
    ...
  }
}
```

Which means in the above, I need to add  in order for the global expression to be able to find `myCustomHandler`.

P.S. Yep, arrow functions make it much easier to deal with `this`, but in case like callbacks I need to be careful to preserve the context if needed.
