### ISSUE TITLE
Manual Vega Updates

### ISSUE THREAD

**Issue by jhoffswell** [vega/vega#386]
I am attempting to reset the signal values manually to a past state using `ved.view.signal(name, value)` but the behavior is not always as I would expect. Here are some example cases for the overview+detail example and explanations of the strategy/result.

#### Example 1:
In this example, I attempt to set all of the signal values to the values recorded at a previous state and then update the visualization. However, when these commands are executed, only the brush is updated whereas the detail is not changed.
```javascript
ved.view.signal("brush_start", new Date("Sun Jul 15 2001 23:56:00 GMT-0700 (PDT)"))
ved.view.signal("brush_end", new Date("Thu Mar 17 2005 09:36:00 GMT-0800 (PST)"))
ved.view.signal("min_date", 995266560000)
ved.view.signal("max_date", 1111080960000)
ved.view.signal("brush_end_vgGATEKEEPER", false)
ved.view.update()
```

#### Example 2:
However, if I update after every step, the visualization is updated to the expected state.
```javascript
ved.view.signal("brush_start", new Date("Sun Jul 15 2001 23:56:00 GMT-0700 (PDT)"))
ved.view.update()
ved.view.signal("brush_end", new Date("Thu Mar 17 2005 09:36:00 GMT-0800 (PST)"))
ved.view.update()
ved.view.signal("min_date", 995266560000)
ved.view.update()
ved.view.signal("max_date", 1111080960000)
ved.view.update()
ved.view.signal("brush_end_vgGATEKEEPER", false)
ved.view.update()
```

#### Example 3:
Since `min_date` and `max_date` are dependant on the values of `brush_start` and `brush_end,` eliminating the setters for these signals causes the visualization to appear as expected with only a single call to `update()` at the end.
```javascript
ved.view.signal("brush_start", new Date("Sun Jul 15 2001 23:56:00 GMT-0700 (PDT)"))
ved.view.signal("brush_end", new Date("Thu Mar 17 2005 09:36:00 GMT-0800 (PST)"))
ved.view.signal("brush_end_vgGATEKEEPER", false)
ved.view.update()
```
Note: Removing the update to `brush_end_vgGATEKEEPER` also causes the visualization to update appropriately.

#### Conclusion:
After conducting the same set of tests on the crossfilter example, it appears that the problem arises only when setting signals for which the signal value is determined by an `expr` not a `stream.`

**Comment by arvind** [comment]
Thanks Jane! Fixed in a15c0d0.
