### ISSUE TITLE
An issue with a data source in Vega example

### ISSUE THREAD

**Issue by avatorl** [vega/vega#3861]
In the https://vega.github.io/vega/examples/warming-stripes/ example, when opened in Vega Editor https://vega.github.io/editor/#/examples/vega/warming-stripes Vega is failing to load data from "data/global-temp.csv"

```
    {
      "name": "dataset",
      "url": "data/global-temp.csv",
      "format": {"type": "csv", "parse": "auto", "delimiter": ","}
    }
```

![image](https://github.com/vega/vega/assets/59934292/b307986b-7eaa-4e84-a34f-b03093b6baa1)

It loads data correctly when the relative "data/global-temp.csv" URL is replaced with an absolute URL (e.g. "https://raw.githubusercontent.com/vega/vega/main/docs/data/global-temp.csv").

**Comment by domoritz** [comment]
Same as #3860. Data should be in Vega datasets so it's available in the editor automatically as well.

**Comment by avatorl** [comment]
@domoritz Sorry, I'm not sure I understand what "data should be in Vega datasets" means. When I'm creating a new example, is there anything I have to do with the data file other than adding it into the /docs/data/ or is it something that you or someone else will need to fix?

**Comment by domoritz** [comment]
We share datasets from https://github.com/vega/vega-datasets among the different Vega projects. Datasets from there are automatically available in the Vega editor.

We have a bit of a review process for making sure datasets are ready for this repo as they should be generally useful beyond a single example. You can send a pull request and I'm happy to review, merge, and release.
