### ISSUE TITLE
Should aggregate_params be aggregateParams

### ISSUE THREAD

**Issue by domoritz** [vega/vega#3876]
https://github.com/vega/vega/pull/3686 introduces a new property `aggregate_params` but Vega usually uses camel case. Should we change the name? This was already released in https://github.com/vega/vega/releases/tag/v5.26.0, though.

**Comment by arvind** [comment]
Hmm, I'm not sure if Vega is all that consistent? Eg, "countpattern", "joinaggregate", "resolvefilter" have no capitalization, and the window transform has [several operators](https://vega.github.io/vega/docs/transforms/window/#-window-operation-reference) that are space-delimited via underscores (e.g., `row_number`, `dense_rank`, `cume_dist`, etc.). (There's plausibly some consistency within classes of operators/properties)

Also, given that it's been released, I'm not sure switching to camelCase for this specific property is worth breaking backwards compatibility?

**Comment by jheer** [comment]
I agree with @arvind. If we feel strongly about it I could see adding support for a camel case version and maybe deprecating (but not yet removing) the underscore based version?

**Comment by domoritz** [comment]
I have no strong feelings but wanted to flag it since we are adding going to use the parameter in Vega-Lite soon. Since we don't have a lot of consistency in other places, let's just leave it until we feel the need for a global name-refactoring (with backwards compatibility of course).

**Comment by domoritz** [comment]
IIRC the intention with layer was that it is a verb while params is a noun.
