### ISSUE TITLE
In Editor, should be possible to see data and signals from inner group elements.

### ISSUE THREAD

**Issue by mtravers** [vega/vega#3902]
Maybe I'm missing something, but it looks like the Vega Editor won't display data and signals for inner group elements. This would be very useful to me right now, I'm trying to debug a fairly complex visualization.

My suggestion is that these should be made available in the data viewer using standard dropdown, maybe using a dot notation or something (eg show them as group1.data, etc). Something similar for signals. An alternative would be to have some way of selecting a group element and have the debugger look at that, but that sounds more awkward.

Or, maybe there is some way to see this now and I am missing it, in which case the request is to make it more obvious.

Please:

- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Clearly describe the goal of the feature request. Why is it needed?
- [x ] Describe an envisioned solution. What do you want the new behavior to be?
- [ ] If applicable, share mockup images or links to examples illustrating the desired output.
- [ ] If applicable, share JSON spec designs for how the behavior would be made available in Vega.

**Comment by domoritz** [comment]
Please file this issue at https://github.com/vega/editor. Ideally, please send a pull request but I'm not sure what the best way is to build a UI for accessible nested signals.

**Comment by mtravers** [comment]
Done, see https://github.com/vega/editor/issues/1410
