### ISSUE TITLE
Charts using the canvas renderer are blank after switching tabs in Chrome

### ISSUE THREAD

**Issue by jonmmease** [vega/vega#3923]
I noticed today while working with the Vega-Altair documentation that charts were going blank after switching tabs. I was able to reproduce the same behavior in the Vega editor, but only when using the "canvas" renderer (which altair does by default). See the screen recording below.

https://github.com/vega/vega/assets/15064365/2935a4ef-b1b9-400b-a63c-d2142155bde2

Nothing is logged in the browser console when switching tabs unfortunately. And I don't see the same behavior with Firefox or Safari.

I think this started happening relatively recently, but I'm not sure if it corresponds to a Vega update, a Chrome update, or a macOS update. 

System specs:
 - Chrome Version 125.0.6422.61 (Official Build) (arm64)
 - macOS 14.5 (23F79) on Apple M1 Pro

**Comment by jonmmease** [comment]
Ah, looks like this may be a chrome bug: https://issues.chromium.org/issues/328755781

**Comment by jonmmease** [comment]
Closing as, after reading through the issue, it doesn't look like there's anything we can do on the Vega side. In my case a full restart of the browser resolved the issue (for now).

**Comment by domoritz** [comment]
It's the classic chain of tracking down issues: is it a bug in Vega-Lite, is it a bug in Vega, is it a bug in D3, is it a bug in the browser, or is math wrong.
