### ISSUE TITLE
Crash: "c is undefined" in Cross+filter transform after Aggregate

### ISSUE THREAD

**Issue by Jerrythafast** [vega/vega#395]
Dear Devs,

I got another interesting crash. I think I kind of caused this myself, because it seems to be related to the `filter` attribute of the `cross` transform.

Here it is:
```json
{
  "data": [
    {
      "name": "table",
      "values": [
        {"a": 1, "b": 1, "c": 1},
        {"a": 1, "b": 1, "c": 2},
        {"a": 1, "b": 2, "c": 1},
        {"a": 1, "b": 2, "c": 2},
        {"a": 2, "b": 1, "c": 1},
        {"a": 2, "b": 1, "c": 2},
        {"a": 2, "b": 2, "c": 1},
        {"a": 2, "b": 2, "c": 2}
      ]
    },
    {
      "name": "agcross",
      "source": "table",
      "transform": [
        {
          "type": "aggregate",
          "groupby": ["a"],
          "summarize": [{"field": "b", "ops": ["distinct"], "as": ["count"]}]
        },
        {
          "type": "cross",
          "with": "table",
          "filter": "datum.b.a < datum.a.a"
        }
      ]
    }
  ]
}
```

The issue is this: Vega crashes at [line 63 of Cross.js](https://github.com/vega/vega/blob/master/src/transforms/Cross.js#L63) with "TypeError: c is undefined". I am not exactly sure why, but I couldn't get it to crash without the `aggregate` transform so it seems to be related to that as well.

The expected output, which can be obtained by moving the `filter` to a separate `filter` transform, is:
```json
[
  {
    "a": {"a": 2, "count": 2},
    "b": {"a": 1, "b": 1, "c": 1}
  },
  {
    "a": {"a": 2, "count": 2},
    "b": {"a": 1, "b": 1, "c": 2}
  },
  {
    "a": {"a": 2, "count": 2},
    "b": {"a": 1, "b": 2, "c": 1}
  },
  {
    "a": {"a": 2, "count": 2},
    "b": {"a": 1, "b": 2, "c": 2}
  }
]
```

It's probably just an interesting corner case again ;)

Kind regards,
Jerry

EDIT: Small update. It does not seem to be dependent on the `aggregate` after all. The following spec, in which I included the `aggregate` output explicitly, crashes in exactly the same way:
```json
{
  "data": [
    {
      "name": "table",
      "values": [
        {"a": 1, "b": 1, "c": 1},
        {"a": 1, "b": 1, "c": 2},
        {"a": 1, "b": 2, "c": 1},
        {"a": 1, "b": 2, "c": 2},
        {"a": 2, "b": 1, "c": 1},
        {"a": 2, "b": 1, "c": 2},
        {"a": 2, "b": 2, "c": 1},
        {"a": 2, "b": 2, "c": 2}
      ]
    },
    {
      "name": "agcross",
      "values": [
        {"a": 1, "count": 2},
        {"a": 2, "count": 2}
      ],
      "transform": [
        {
          "type": "cross",
          "with": "table",
          "filter": "datum.b.a < datum.a.a"
        }
      ]
    }
  ]
}
```

**Comment by Jerrythafast** [comment]
I investigated this a bit more because I am starting to run into this bug in more circumstances.

It turns out there are basically two conditions that need to be met:
1. There exists a data object in the 'left' data set that is not combined with any of the objects in the 'right' data set.
2. Said object is present in the `input.mod` array passed into the `batchTransform()` method.

In the example above, `{"a": 1, "count": 2}` is not combined with any of the objects in `table`. For some reason I don't understand, when the `batchTransform()` method is called the second time (originating from the `autopad` feature), the `{"a": 1, "count": 2}` object is present in the `input.mod` array. Because it was never comined with anything, it does not appear in the `Cross._cache` array, where the offending code expects it to be.

I can thus conclude one of two possible things is wrong:
1. The `Cross.mod()` method should check whether `this._cache[x._id]` actually exists, or
2. The `Cross.mod()` method correctly assumes that it exists and something else is erroneously adding the data object to `input.mod`.

I am actually suspecting the latter, since I have seen this crash occurring even if the transform was set up as `{"type": "cross", "diagonal": false}` (i.e., a self-cross that excludes the diagonal) on a data set with only one object. I am having a hard time producing a minimal working example for that though.

**Comment by arvind** [comment]
Thanks for this @Jerrythafast. For now, I believe (1) is the reason for this error. When autopad kicks in, the expected behaviour is for datasources to forward _all_ their tuples in `input.mod`, and operators are responsible for their specific bookkeeping. 

In the case of Cross, when new tuples are experienced (`input.add`), we test if they should be crossed and add them to the cache. However, we don't do anything similar in the case of `input.mod` or `input.rem`.
