### ISSUE TITLE
Series Fill Bar chart broken

### ISSUE THREAD

**Issue by billybonks** [vega/vega#3960]
### Reproduction steps
Copy the JSON from https://gist.github.com/billybonks/cec9117dad834d0c76ed1c20c5cc0a46 into https://vega.github.io/editor/#/edited.

May one should have green and purple rectangles, but they are only visible on hover. 
![image](https://github.com/user-attachments/assets/c221c276-7b66-45da-9b87-578473ad2560)

The version used is the one on Vega playground and in my dev environment 5.30.0
Please:

### Expected result

All series data should be properly rendered

**Comment by PBI-David** [comment]
You haven't used a stack transform hence all the bars are layered one on top of the other. https://vega.github.io/vega/docs/transforms/stack/

Suggest this be closed.

**Comment by billybonks** [comment]
👍🏿 that makes sense, thank you.
