### ISSUE TITLE
'Toggle' operators are adding new data values when calling update(), and add duplicates

### ISSUE THREAD

**Issue by Jerrythafast** [vega/vega#409]
Hey guys,

This happens even when Vega calls `update()` internally. Watch this:

Open the [shiftclick_select spec in Vega Editor](http://vega.github.io/vega-editor/?mode=vega&spec=shiftclick_select) and open the JS console. Then type `ved.view.data("selectedPoints").values()`. The result (for me on Chrome 46.0.2490.80 at least) is an array with two objects:
```json
[
  {"_id": 151, "id": 0},
  {"_id": 151, "id": 0}
]
```
The 0 in this appears to be coming from the initial value of the `clickedPoint` signal, and it appears to end up there through internal `update()` calls. If I run `ved.view.update()` and then repeat the above command I end up with an array of three such objects.

Similarly, if I click a point in the visualisation and then run `ved.view.update()`, I again end up with two identical objects (this time of course with the `id` of the point I clicked).

I am also not entirely convinced what a `toggle` operator should actually do... The [Wiki page on Data](https://github.com/vega/vega/wiki/Data) points to the [Streaming Data page](https://github.com/vega/vega/wiki/Streaming-Data), but neither page really explains what it does. I would expect it to add a tuple if it is not present and remove it otherwise, but if I click the same point over and over again it just keeps adding identical elements to the `selectedPoints` data set. How is this different from an `insert` operator?

Kind regards,
Jerry

**Comment by arvind** [comment]
Hi @Jerrythafast, thanks for the bug report. I've pushed a fix with 239b8fe. The insert, toggle, and remove operators should only execute when their corresponding signal value changes. The clear operator is reevaluated on every `update` call, and clears out the data source if the predicate evaluates to true.
