### ISSUE TITLE
Add documentation for reactive geometry

### ISSUE THREAD

**Issue by jheer** [vega/vega#412]
It appears to be missing in the `from` documentation on https://github.com/vega/vega/wiki/Marks

**Comment by kanitw** [comment]
Note from a conversation on slack:

> Simply use `from: {mark: markName}` and then you get the scene graph items as your data elements.  Marks have to be siblings though. That’s the only constraint.

**Comment by domoritz** [comment]
cc @benib

**Comment by domoritz** [comment]
It would be nice to have at least an example here. @willium used reactive geometries in a labeling prototype.

**Comment by kanitw** [comment]
I think Vega papers have some examples.

**Comment by domoritz** [comment]
I see reactive geometry mentioned in https://idl.cs.washington.edu/files/2015-ReactiveVega-InfoVis.pdf but don't see any code examples.

**Comment by arvind** [comment]
The grouped bar example makes use of reactive geometry:
https://vega.github.io/vega/examples/grouped-bar-chart/

-Arvind
-----
Arvind Satyanarayan <http://arvindsatya.com/>

**Comment by domoritz** [comment]
`"from": {"data": "bars"}` is how data from marks in accessed.

**Comment by jheer** [comment]
TODO: Add discussion of reactive geometry to https://vega.github.io/vega/docs/marks/, as a new sub-section under "Mark Data Sources"

**Comment by jheer** [comment]
Added! https://vega.github.io/vega/docs/marks/#reactive-geometry
