### ISSUE TITLE
undefined `x` in line 4936

### ISSUE THREAD

**Issue by unaizalakain** [vega/vega#413]
[Spec](http://paste.debian.net/322675/) works fine in vega-editor, throws the following exceptions when loaded in a [basic document](http://paste.debian.net/322563/):

TypeError: x is undefined vega.js:4936:53
TypeError: scene is undefined vega.js:9567:7

Any idea of what could be going wrong?

**Comment by arvind** [comment]
You're referencing old versions of the Vega libraries (we're working on taking down the Trifacta Vega URL). I recommend grabbing the updated code from [this page](https://github.com/vega/vega/wiki/Runtime#basic-use) of the Vega documentation.

**Comment by unaizalakain** [comment]
I forgot to mention: the spec is successfully loaded and parsed.

**Comment by unaizalakain** [comment]
My first try was with the newer versions listed at https://github.com/vega/vega/wiki/Runtime#basic-use

But I get exactly the same error (loading the non-minified version of vega).

**Comment by unaizalakain** [comment]
The spec is generated using vincent. I get the same error both in Firefox 41 and Chromium 46.

**Comment by arvind** [comment]
Hi @unaizalakain, it looks like your spec is built for Vega 1 (e.g., you reference `data.`) but the Vega library you load is Vega 2. Try using http://trifacta.github.io/vega/vega.min.js instead?

**Comment by unaizalakain** [comment]
Somehow I skipped the part of vincent's docs that say that it only works with vega 1.4! Thank you!
