### ISSUE TITLE
Voronoi without padding explicitly set creates excessively large vis

### ISSUE THREAD

**Issue by pbeshai** [vega/vega#414]
When drawing paths from a voronoi transformation, if no padding is explicitly set in the spec, the vis rendered is very large.

Spec with padding specified: http://jsbin.com/luyuci/1/edit?html,output
![with padding](https://cloud.githubusercontent.com/assets/793847/10953519/7c74ddf6-8316-11e5-9a27-7f4c940dd8e5.png)

Spec without padding specified: http://jsbin.com/luyuci/2/edit?html,output 
(image is clipped for convenience)
![without padding (truncated)](https://cloud.githubusercontent.com/assets/793847/10953530/87da2dc2-8316-11e5-8245-02fa5145060e.png)

**Comment by jheer** [comment]
FYI, the Voronoi transform has a `clipExtent` property. You can set that to the width/height of your data rectangle as an alternative to the padding (e.g., `[[0,0], [<width>, <height>]]`).

**Comment by pbeshai** [comment]
Is there a recommended way to access width and height? I've seen `eventGroup("root").width` and in some cases using a signal that just stores the width value (e.g. http://vega.github.io/vega-editor/?mode=vega&spec=brush).

**Comment by arvind** [comment]
`width` and `height` have been added as top-level signals with [v2.4](https://github.com/vega/vega/releases/tag/v2.4.0).
