### ISSUE TITLE
Make it more clear that copies of data are created and used by vega

### ISSUE THREAD

**Issue by pbeshai** [vega/vega#415]
In the [Data](https://github.com/vega/vega/wiki/Data) documentation it says 
> Vega maps each data record into a data object and assigns it a unique _id.

While this implies that new objects are created for each data record passed in, I didn't realize it. Perhaps emphasizing that the original data remains untouched and that a copy with the _id attribute is used would be helpful. 

It likely doesn't matter for most Vega users, but if you're updating the data used by the vis, it's good to know that new data objects are created each time the data is passed in, and that if you pass the same data object into two different datasets in Vega (e.g. "points" and "highlightedPoints"), different objects are created. 

A side effect of this is that any listeners to signals (i.e., `onSignal` handlers) that receive 'datum' as their value, do not actually receive the initial data point, they receive the vega data object, which may have undesired consequences if the external code is not aware of this difference.

**Comment by arvind** [comment]
Hi @pbeshai, agreed! I've changed the sentence to read:
> Upon load, Vega copies each data record into a new data object and assigns it a unique _id.

Feel free to update/modify as you see fit to further improve clarity.

**Comment by kanitw** [comment]
@arvind  

Would you add an option to use the original data especially if they already have `_id`? 
(This would be very useful for Voyager's use case.)
