### ISSUE TITLE
Choropleth example uses the undocumented parse: "auto"

### ISSUE THREAD

**Issue by kanitw** [vega/vega#416]
[Choropleth example](http://vega.github.io/vega-editor/?mode=vega&spec=choropleth) uses parse in `data.format`:

```
"format": {"type": "tsv", "parse": "auto”}
```

but “auto” is not documented as value for parse in [Data’s doc](https://github.com/vega/vega/wiki/Data)

**Comment by Jerrythafast** [comment]
Similarly, [Shiftclick_select](http://vega.github.io/vega-editor/?mode=vega&spec=shiftclick_select) uses an [undocumented](https://github.com/vega/vega/wiki/Signals) `verbose` attribute for its `signals`.

**Comment by arvind** [comment]
[Auto format](https://github.com/vega/vega/wiki/Data#-json) and [verbose signals](https://github.com/vega/vega/wiki/Signals#signal-properties) are now both documented. Thank you all!
