### ISSUE TITLE
Bin documentation inconsistent with bin_mid

### ISSUE THREAD

**Issue by jeffbaumes** [vega/vega#419]
The updated bin transform that does not require `max` and `min` values precomputed is great. But in the docs for the bin transform, `bin_mid` is mentioned as an output but in the example directly below, only `bin_start` and `bin_end` are generated. In testing this a week or so ago I could not get `bin_mid` to appear - is this a non-feature or upcoming feature that should be removed from the docs?

https://github.com/vega/vega/wiki/Data-Transforms#-bin

**Comment by arvind** [comment]
Thanks Jeff. That output property crept into the documentation prematurely. Vega's master branch has a `bin_mid` property, which will be included in the next release.
