### ISSUE TITLE
Error installing Vega with npm

### ISSUE THREAD

**Issue by Stefanybris** [vega/vega#420]
Hi every time i try to install vega with npm i get the following error;

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! vega@2.3.1 build: `npm run pegjs && browserify index.js -d -s vg | exor
cist vega.js.map > vega.js`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the vega@2.3.1 build script 'npm run pegjs && browserify inde
x.js -d -s vg | exorcist vega.js.map > vega.js'.
npm ERR! This is most likely a problem with the vega package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run pegjs && browserify index.js -d -s vg | exorcist vega.js.ma
p > vega.js

What can I do to fix this problem?? I already have installed browserify and pegjs I have been looking everywhere the past few days and i couldn't find an answer

Hopping you can help me!

**Comment by arvind** [comment]
Hi,

It looks like the "npm run build" command produced this output? Did you
first execute "npm install"?

-Arvind
-----
Arvind Satyanarayan <http://arvindsatya.com/>

**Comment by arvind** [comment]
I'm going to close this issue out since it's been a while. If you're still experiencing issues, please post to the [vega-js google group](https://groups.google.com/forum/#!forum/vega-js). Thanks!

**Comment by Stefanybris** [comment]
Sorry i have been really busy and yes i first excecuted the npm intall and
still the error. Thanks for your answer.......

Le mardi 17 novembre 2015, Arvind Satyanarayan <notifications@github.com> a
écrit :
