### ISSUE TITLE
Axes inside group marks leave empty space if width is reduced by View.width(val)

### ISSUE THREAD

**Issue by Jerrythafast** [vega/vega#429]
This one is probably related to #424. To set up an example, open the [grouped_bar spec in Vega Editor](http://vega.github.io/vega-editor/?spec=grouped_bar), remove the top-level `axes` property and replace `marks` with the definition below:
```json
  "marks": [
    {
      "type": "group",
      "from": {
        "data": "table",
        "transform": [{"type":"facet", "groupby": ["category"]}]
      },
      "properties": {
        "update": {
          "x": {"value": 0},
          "width": {"field": {"group": "width"}},
          "y": {"scale": "cat", "field": "key"},
          "height": {"scale": "cat", "band": true}
        }
      },
      "scales": [
        {
          "name": "pos",
          "type": "ordinal",
          "range": "height",
          "domain": {"field": "position"}
        }
      ],
      "axes": [
        {
          "type": "x",
          "scale": "val"
        }
      ],
      "marks": [
        {
          "type": "rect",
          "properties": {
            "update": {
              "y": {"scale": "pos", "field": "position"},
              "height": {"scale": "pos", "band": true},
              "x": {"scale": "val", "field": "value"},
              "x2": {"scale": "val", "value": 0},
              "fill": {"scale": "color", "field": "position"}
            }
          }
        }
      ]
    }
  ]
```
If you now parse the spec and run `ved.view.width(200).padding("auto").update()`, you can see the axes and bars shrinking, but the graph itself is not resized. That is, empty space remains to the right of the shortened bars. Interestingly, the graph *does* resize when you set the `width` to something higher than the initial value.

The problem does not occur if you remove the axis definition from the spec, so this problem is somehow caused by the fact that there is an axis in the `group` mark.

**Comment by jheer** [comment]
This error stems from the scene bounds not updating appropriately. Across any changes in width less than the original width, the scene bounds remain unchanged when an axis is present (regardless of where that axis is defined -- top-level axes also exhibit the issue). It is possible that the bounds calculation for the axes is either being skipped (leaving the old value unchanged) or updating incorrectly. More investigation to come...

**Comment by jheer** [comment]
I think I've found the source of the problem: the code block surrounding `scene/Bounder.js#L30`. It appears a full re-calculation of the bounds is only triggered in specific circumstances, and resizing of the chart is not currently one of those circumstances. When I comment out the surrounding if statement and else clause, leaving only line 30, the chart size updates as expected. Assigning to @arvind as this issue arises in the build-encode-bound pipeline, not the lower-level bounds calculation methods.

**Comment by arvind** [comment]
Some further investigation. Interestingly, the correct behaviour occurs when you simply manipulate width and update via the API (e.g., `ved.view.width(400).update(); ved.view.width(100).update();`). The bug presents itself when autopadding is run, and only when the width falls under the value defined in the specification. 

For example, `ved.view.width(500).padding('auto').update(); ved.view.width(400).padding('auto').update();` cause the canvas to resize appropriately. However, the extra padding remains when width falls below 300. Or, if `width: 100` was initially specified in the specification, then setting width/autopad with 400, 300, 200, 100 work fine, but break <100.

**Comment by arvind** [comment]
Continuing investigation. Here is another MWE that presents the error. However, if we switch the x-axis to instead use the `cat` scale, the error no longer presents. 
```json
{
  "width": 200,
  "height": 240,
  "data": [
    {
      "name": "table",
      "values": [1, 2, 3]
    }
  ],
  "scales": [
    {
      "name": "cat",
      "type": "ordinal",
      "domain": {"data": "table", "field": "data"},
      "range": "width"
    },
    {
      "name": "val",
      "type": "linear",
      "domain": {"data": "table", "field": "data"},
      "range": "width"
    }
  ],
  "axes": [
    {"type": "x", "scale": "val"}
  ]
}
```

**Comment by arvind** [comment]
Hah, what a great bug. With the linear scale, the very first tick (`0.0`) does not move when the width changes. As a result, it is not marked as dirty. The Bounder only runs full mark bounds on the conditions specified on L27/28 (i.e., if there are new/removed items, if there are no items, or if all items are marked as dirty). Otherwise, it runs item-level bounds recalculation. This is important to maintain interactive/streaming performance.

So, now the question becomes whether Bounder should be less selective about when it should run mark bounds (e.g., a plus/minus on the final condition)?
