### ISSUE TITLE
Plots that render fail schema check

### ISSUE THREAD

**Issue by randyzwitch** [vega/vega#433]
Wanted to coordinate with you folks before I did anything. Do you auto-generate the schema or hand-update it? I have at least a half-dozen different plots that render just fine, but don't pass the schema validation.

If it's hand-updated, I can take a crack at a PR to fix all my issues and submit it.

**Comment by arvind** [comment]
Hi @randyzwitch, each component in the Vega parser defines its schema. These located below the `module.exports` line. For example, see [line 28 of mark.js](https://github.com/vega/vega/blob/master/src/parse/mark.js#L28) for the schema related to non-group marks. These are currently hand-written, and must be updated when changes to the parser are made, so there's a possibility that they may fall out of sync.

During the build process, the schema is stripped from individual files, to minimize the size of `vega.js` and `vega.min.js`, and compiled into `vega-schema.json`. We also have a number of unit tests that verify that example visualizations validate against the schema (`npm run test -- -g "Schema"`). 

Hope this helps!

**Comment by randyzwitch** [comment]
Thanks Arvind. I wrote a bunch of tests for my package and roughly half of my visualizations failed (but all render). I'll see if I can get more details and submit a PR.
