### ISSUE TITLE
"ask the vega team"

### ISSUE THREAD

**Issue by jowens** [vega/vega#436]
Vega team, love your work. Suggestion: Have a forum where users can paste in Vega graphs and get suggestions on how to improve them, both from the perspective of "use Vega better" as well as from "use data visualization better". This is *not* "help me debug my Vega input", it's "here is a working Vega vis, how can I improve it", so it's probably a much more constrained and manageable process. I can justify this by saying that it would be great for {training new students, seeing what's unclear in the documentation, realizing the need for a new feature}, and I do believe those things are true and maybe @jheer will agree, but really I'm just selfishly asking because I want the free help of experts in making my data visualizations better.

**Comment by arvind** [comment]
Hi John, 

There are already some avenues for this including the [vega-js google group](http://groups.google.com/forum/#!forum/vega-js) as well as Jon Schwabish's [HelpMeViz](http://helpmeviz.com). While the former has, so far, primarily been about debugging Vega visualization, and the latter for visualizations in general, I think both would benefit from such types of questions!

**Comment by kanitw** [comment]
On a related note, if any external collaborator would like to integrate github's gist with our vega-editor, that would serve as a nice platform for forking vega examples and work in progress.   

(Maybe start with adding url hash for importing code from gist ... and if you have more time, then allow publishing back to gist?)

**Comment by arvind** [comment]
We've already started exploring this with the [jh-gist branch](https://github.com/vega/vega-editor/tree/jh-gists) in vega-editor. I think we'd hit some issues with authentication that required a server-side component, and made it difficult to maintain our simple GitHub pages deployment.

**Comment by kanitw** [comment]
I see. That's quite unfortunate!

**Comment by jheer** [comment]
Never fear... I'm sure we can find a solution!

**Comment by ajturner** [comment]
Perhaps @benheb can explain how he got GitHub auth, save and load from Gist without any server component http://benheb.github.io/mundi/ + https://github.com/benheb/mundi/

**Comment by jheer** [comment]
Looks like the mundi project routes the OAuth stuff through a separate heroku app. I've seen this strategy elsewhere; definitely one for us to consider.

**Comment by benheb** [comment]
@jheer yep, that's exactly what it's doing. Trying to find the repo I used to set it up, but cannot seem to for the life of me.

**Comment by jeffbaumes** [comment]
Feel free to borrow code from this simple prototype code which deploys a gist-Vega-viewer with Heroku.

https://github.com/XDATA-Year-3/sitar-lite

Generated pages:

http://sitar.herokuapp.com/#jeffbaumes
http://sitar.herokuapp.com/#jeffbaumes/5b6295b0e0297a439164

It uses a very basic Python web server and requires a single user's GitHub credentials to be loaded server-side to make the queries. This could run into the API limit but if caching is added it would likely scale pretty far. A few considerations I've run into:

* How do you let people specify data files? I let people refer to local gist files, the content of which is rolled into the Vega spec at runtime.
* How do you deal with different versions of Vega? There should be something in the gist that can flag which Vega version to target. Sitar lite always points to http://vega.github.io/vega-editor/vendor/vega.js but there is probably a better way.
