### ISSUE TITLE
Global d3 object required, yet not availible when using browserify and npm

### ISSUE THREAD

**Issue by dmitriyshashkin** [vega/vega#438]
I'm trying to use vega with browserify. I add vega as a dependency and follow the instructions listed here https://github.com/vega/vega/wiki/Vega-and-Browserify

I'm trying to create a chart using this simple code:
```javascript
var vg = require('vega');
vg.parse.spec('/js/vg.json', function(chart) { chart({el:"#vis"}).update(); });
```
The specification I use is a trivial one, copied from the polestar contructor.

I'm getting the following error:
>/node_modules/vega-scenegraph/src/util/svg.js:1
>Uncaught TypeError: Cannot read property 'svg' of undefined

I managed to fix the problem by adding d3 as a dependency and creating a global d3 object:
```javascript
window.d3 = require('d3');
```

**Comment by jheer** [comment]
The default Vega build process uses browserify-shim such that d3 is not bundled in the build vega.js and vega.min.js files. Typically d3 is included as a top-level import in the browser. We are considering changing the build process in the future to support more varied (and modular) builds. However, in the meantime the solution is to ensure d3 is present in the global (window) scope.

**Comment by dmitriyshashkin** [comment]
Might be helpful to mention the solution somewhere. As I'm still new with browserify/npm, it took me some effort to assert that the problem is not connected with the way I've set up those tools.

**Comment by Garito** [comment]
Today the documentation is not newbie friendly at all
To help new users you must provide examples that work like their are and the explanation from going from 0 to 100

**Comment by GCheung55** [comment]
@garito can you share your usecase in a new ticket? It will be easier to track since this issue is 2+ years old, is targeting Vega 2.0, and is closed. 

Your usecase would help describe the kind of documentation additions/changes that is needed.

**Comment by Garito** [comment]
Sorry, I end up using eCharts
But the point here is that I discard this library cause I can't use it in a decent amount of time due to the lack of proper complete example
My way of learning things is by copy/paste examples and then modify them to rich my needs

**Comment by domoritz** [comment]
@Garito, I'm sorry that you had such a poor first contact experience. Can you give us some specific things that are missing in the documentation or hard to find?

You mentioned a working example as one thing you miss. I added a link to our example block (https://bl.ocks.org/domoritz/cd636b15fa0e187b51b73fc60b4d3014) to the usage page at https://vega.github.io/vega/usage/.
