### ISSUE TITLE
How do I use scales to drive axis labels?

### ISSUE THREAD

**Issue by domoritz** [vega/vega#440]
The [documentation states](https://github.com/vega/vega/wiki/Axes) that "Custom text can be defined using the "text" property for labels. For example, one could define an ordinal scale that serves as a lookup table from axis values to axis label text."

```json
{
  "width": 400,
  "height": 200,
  "padding": {"top": 10,"left": 30,"bottom": 30,"right": 10},
  "data": [
    {
      "name": "table",
      "values": [
        {"x": 1,"y": 28},
        {"x": 2,"y": 55},
        {"x": 3,"y": 43},
        {"x": 4,"y": 91},
        {"x": 5,"y": 81},
        {"x": 6,"y": 53},
        {"x": 7,"y": 19},
        {"x": 8,"y": 87},
        {"x": 9,"y": 52},
        {"x": 10,"y": 48}
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "ordinal",
      "range": "width",
      "domain": {"data": "table","field": "x"}
    },
    {
      "name": "foo",
      "type": "ordinal",
      "domain": [1,2,3,4,5,6,7,8,9,10],
      "range": [10,21]
    }
  ],
  "axes": [
    {
      "type": "x",
      "scale": "x",
      "properties": {
        "labels": {
          "angle": {"value": 90},
          "text": {"scale": "foo"}
        }
      }
    }
  ]
}
```

However, instead of seeing the values from the scale, I see a function in the text. 

![screen shot 2015-11-17 at 19 34 47](https://cloud.githubusercontent.com/assets/589034/11231949/4b2a6724-8d62-11e5-9e92-cd5f50e1ebfe.png)

**Comment by arvind** [comment]
Try `"text": {"scale": "foo", "field": "data"}`. The documentation can likely be clearer and/or provide an example.

**Comment by domoritz** [comment]
Great, thank you. That helps me fix https://github.com/vega/polestar/issues/348. Feel free to close this issue.

**Comment by jheer** [comment]
I think this should be considered a bug. Even if the input spec is does not conform to the schema, showing function code as a label seems dubious. Throwing and/or logging an error seems preferable.

Here is a minimal spec showing the issue:
```
{
  "width": 400,
  "height": 200,
  "data": [
    {
      "name": "table",
      "values": [{"x": 1,  "y": 28}, {"x": 2,  "y": 91}]
    }
  ],
  "scales": [
    {
      "name": "y",
      "type": "linear",
      "range": "height", "nice": true,
      "domain": {"data": "table", "field": "y"}
    }
  ],
  "axes": [
    {"type": "y", "scale": "y",
     "properties": {"labels": {"text": {"scale": "y"}}}}
  ]
}
```

The offending code block appears to be [parse/properties.js#L278](https://github.com/vega/vega/blob/master/src/parse/properties.js#L278). The parse properties method is making an invalid assumption about predicates. @arvind, is there any easy fix for this? It seems we should know whether or not a predicate is involved. Not sure why we are using the `scale` var to carry such info...
