### ISSUE TITLE
TypeError: (intermediate value).svg is undefined

### ISSUE THREAD

**Issue by cchandurkar** [vega/vega#443]
I'm on my ubuntu 14.04 machine. I tried running `npm install` in master branch and got errors saying "No package 'cairo' found". So I googled around and found [this](http://stackoverflow.com/a/24440069/1209337) answer which recommends installing following packages:

`sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++`

That error wasn't there anymore but there were few warnings. Files were built as expected but while using them I got error in browser saying `TypeError: (intermediate value).svg is undefined` on vega.js.

Here is a script log from terminal:

[screen.log.txt](https://github.com/vega/vega/files/40566/screen.log.txt)

**Comment by jheer** [comment]
Hi @cchandurkar, I looked through the your terminal log and didn't find any issues. Have you tried running the test suite (`npm run test`)? Assuming that runs successfully, my guess based on your description is an error at the usage level, not the build level. If you still suspect a build issue, you might also test with a release build of [vega.js](http://vega.github.io/vega/vega.js).

I'm closing this issue for now, but feel free to re-open along with an example vega spec and invoking html file, etc, that reproduces any bugs.

**Comment by saper** [comment]
I've run into this today. (Using [MediaWiki's Graph extension](https://www.mediawiki.org/wiki/Extension:Graph) by @nyurik).

Basically old Firefox does not like this:

    var d3_svg = (typeof window !== "undefined" ? window['d3'] : typeof global !== "undefined" ? global['d3'] : null).svg;

    typeof window !== "undefined"

gives `true`

    typeof global !== "undefined"

gives `false`

     window['d3']

was `undefined` (for some reason)

and this produces

      TypeError: (intermediate value).svg is undefined

pointing at  [this line (my bundle has a different line number)](https://github.com/wikimedia/mediawiki-extensions-Graph/blob/master/lib/vega2/vega.js#L14092).

**Comment by saper** [comment]
Updating https://www.mediawiki.org/wiki/Extension:Graph from https://github.com/wikimedia/mediawiki-extensions-Graph/commit/da4545c106d88346050b6fe84321f18022c0a901 to
https://github.com/wikimedia/mediawiki-extensions-Graph/commit/3af5fe827b20684b9dcda50545274ab357f3be94 solved it, but similar lines are [still there](https://github.com/wikimedia/mediawiki-extensions-Graph/blob/9f283c0a2e87b8dad54a1b9096c7e3a830506278/lib/vega2/vega.js#L14092).
