### ISSUE TITLE
Cross transform diagonal:false malfunctioning for modded tuples

### ISSUE THREAD

**Issue by Jerrythafast** [vega/vega#450]
Found another bug in the `cross` transform...

```json
{
  "data": [
    {
      "name": "a",
      "values": ["hi", "bye"],
      "transform": [
        {"type": "sort", "by": ["data"]},
        {"type": "cross", "diagonal": false}
      ]
    }
  ]
}
```
This gives me the values on the diagonal... exactly those that I did *not* want to see. You get the correct result if you reverse the order of the values in the `values` array or if you remove the `sort` transform. If you reverse the order of the values and change the `sort` to `"-data"` the problem presents itself as well. Thus, this only happens if the `sort` actually changes the order of the data. That makes me conclude the problem must be in (or downstream of) `mod()`.

Kind regards,
Jerry

**Comment by arvind** [comment]
Just pushed a change in de53021. Due to its streaming nature, Cross can now only ensure tuples along the diagonal are excluded when crossing a dataset against itself.
