### ISSUE TITLE
Unit tests broken since f953a52a8eb

### ISSUE THREAD

**Issue by nyurik** [vega/vega#451]
According to git bisect since the last release, unit tests broke with f953a52a8ebf19493eb36c56250b65e168dcb1ea

**Comment by arvind** [comment]
Hi Yuri,

Can you give us more information? Our Travis CI builds report that all tests are passing: https://travis-ci.org/vega/vega

-Arvind
-----
Arvind Satyanarayan <http://arvindsatya.com/>

**Comment by nyurik** [comment]
Interesting, let me re-install dependencies and try again, maybe that's the cause.  I am seeing many failing tests starting from that revision.

**Comment by nyurik** [comment]
my apologies, stale dependencies. all's good.
