### ISSUE TITLE
How to set Axes when plotting multiple Y Axis

### ISSUE THREAD

**Issue by keizer619** [vega/vega#453]
As indicated in following screenshot i am plotting a multiple Y axis in a line chart by specifying  2 attributes for 2 line. It does not draw properly as we can give one scale for Y axes. If we give first attribute then second one is not plotting in correctly and it can be plotted in outside as well. 

This will become worse if we insert values with streaming data. Is there are anyway to construct a single Y axis by using 2 scale attributes? 

<img width="568" alt="screen shot 2015-11-27 at 5 06 58 pm" src="https://cloud.githubusercontent.com/assets/2918812/11440371/021e2160-9528-11e5-8f17-d23596cf5757.png">

Vega Spec : 

{
  "width": 500,
  "height": 200,
  "padding": {"top": 10, "left": 30, "bottom": 30, "right": 10},
  "data": [
    {
      "name": "table",
      "values": [
        {"x": 1,  "y": 10, "z": 15}, {"x": 2,  "y": 50, "z": 70}
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "linear",
      "range": "width",
      "zero": false,
      "domain": {"data": "table", "field": "x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "domain": {"data": "table", "field": "y"}
    },
    {
      "name": "y2",
      "type": "linear",
      "range": "height",
      "nice": true,
      "domain": {"data": "table", "field": "z"}
    }
  ],
  "axes": [
    {"type": "x", "scale": "x"},
    {"type": "y", "scale": "y"}
  ],
  "marks": [
    {
      "type": "area",
      "from": {"data": "table"},
      "properties": {
        "enter": {
          "x": {"scale": "x", "field": "x"},
          "y": {"scale": "y", "field": "y"},
          "stroke":{"value":"red"}
        },
        "update": {
          "fillOpacity": {"value": 1}
        },
        "hover": {
          "fillOpacity": {"value": 0.5}
        }
      }
    },
    {
      "type": "line",
      "from": {"data": "table"},
      "properties": {
        "enter": {
          "x": {"scale": "x", "field": "x"},
          "y": {"scale": "y", "field": "z"},
          "stroke":{"value":"blue"}
        },
        "update": {
          "fillOpacity": {"value": 1}
        },
        "hover": {
          "fillOpacity": {"value": 0.5}
        }
      }
    }
  ]
}

**Comment by jheer** [comment]
If you want to create a single y-scale defined over multiple domains, try this instead:
```
{
    "name": "y",
    "type": "linear",
    "range": "height",
    "nice": true,
    "domain": {"data": "table", "field": ["y", "z"]}
},
```

If instead you'd like a **dual-axis** chart with _separate_ y-axes, you can keep the spec more-or-less as is, but add a second axis to the chart like so:
```
"axes": [
  {"type": "x","scale": "x"},
  {"type": "y","scale": "y"},
  {"type": "y","scale": "y2", "orient":"right"}
],
```
