### ISSUE TITLE
Throw “data source not found" error for invalid “from” property in Builder.js

### ISSUE THREAD

**Issue by kanitw** [vega/vega#459]
On [this line](https://github.com/vega/vega/blob/master/src/scene/Builder.js#L87), if `this._from` refers to an invalid table, we will get 
```
Uncaught TypeError: Cannot read property 'listeners' of undefined
``` 
as `src` would be `null `

Maybe throw a friendlier “data source not found” error?

**Comment by arvind** [comment]
Fixed with 1fc873d. Thanks!
