### ISSUE TITLE
Documentation: Force layout 'drag' vs 'active' parameter

### ISSUE THREAD

**Issue by Jerrythafast** [vega/vega#460]
Hey guys,

I was looking at the [force_drag](http://vega.github.io/vega-editor/?mode=vega&spec=force_drag) example in the Editor and apparently it is using an undocumented parameter named `active`. After having looked at the [documentation](https://github.com/vega/vega/wiki/Data-Transforms#-force), I suspect the parameter name `drag` in the documentation is wrong and should be changed to `active`.

EDIT: and perhaps also mention in the docs somewhere that the `source` and `target` attributes of the values in the `links` dataset should be indices into the `nodes` dataset. I was first trying to use references to the `nodes` objects themselves (e.g., `lookup` on the `nodes`) and then tried to use the `_id` attribute of the `nodes`, but apparently I should index into `nodes`. (Which raises two follow-up questions: why do it this way, and what happens to the indices if I dynamically add/remove objects to/from `nodes`?)

Jerry

**Comment by jheer** [comment]
Thanks Jerry. I updated the documentation for the `active` parameter.

Currently the `source` and `target` lookups are based on node indices, and streaming updates could very well break the visualization. This is a known problem and we plan to update the code to support id-based reference as well. Feel free to add a formal issue if you'd like to track it.
