### ISSUE TITLE
Sort transform broken with 2.4?

### ISSUE THREAD

**Issue by randyzwitch** [vega/vega#461]
I see in the release notes:

`The sort.order property for ordinal scales was deprecated in v2.5.5 and has now been removed to reduce confusion.`

I have my documentation for Vega.jl render live, and the sorted order changed:

![screen shot 2015-12-01 at 10 06 37 am](https://cloud.githubusercontent.com/assets/2762787/11504425/4be5d93a-9813-11e5-9580-6c6a4591db09.png)

Putting the same code into the Vega Editor, which doesn't seem to have changed yet, shows the proper output:

![vega visualization](https://cloud.githubusercontent.com/assets/2762787/11504441/656937ee-9813-11e5-9112-26e147d157ba.png)

My code is here: https://gist.github.com/randyzwitch/d69c42f418f0f9c5c4c3

The transform I'm using seems like it should still work?

```json
    {
      "name": "aggregate",
      "source": "table",
      "transform": [
        {
          "groupby": "y",
          "type": "aggregate",
          "summarize": {"x": ["average"]}
        },
        {"type": "sort", "by": "-average_x"}
      ]
    }
```

**Comment by arvind** [comment]
Hi Randy, 

There was a bug in prior versions of Vega that caused sort to be incorrectly applied to new streaming tuples. This inadvertently resulted in the sort order propagating through to ordinal scale domains as well. To sort an ordinal scale domain, you can instead specify the sort order on the [DataRef directly](https://github.com/vega/vega/wiki/Scales#sorting-domains-for-ordinal-and-quantile-scales). I will update the documentation to make the difference between the sort transform and ordinal scale sorting clearer, and am investigating whether we can make the situation a little easier for common use cases. 

This change affected one of the example specifications. See [this commit](https://github.com/vega/vega-editor/commit/908bc2c1bc7a59708426eaa6adf7b7b1add440c5) for how I had to update the sorting on the barley example. This new example will available on the editor in short order.

**Comment by randyzwitch** [comment]
Thanks Arvind, I think I see what the fix is, hopefully it shouldn't take much effort for me to patch in my side.
