### ISSUE TITLE
Data streaming (Internal Data Provider) not working for treejson

### ISSUE THREAD

**Issue by JBatUN** [vega/vega#465]
When using a graph data model, streaming / setting a value data provider is working as expected, for example:

// Vega Directive
if (scope.vPatternSelection.model == "graph"){
                    view.data('nodes').insert(scope.master.nodes);
                    view.data('edges').insert(scope.master.links);
             etc...

// Extract of schema file
"data": [
{
      "name": "edges",
      "values": [],
      "format": {"type": "json"}
    },
    {
      "name": "nodes",
      "values": [],
      "format": {"type": "json"},
      "transform": [ …

However, when following the same approach for treejson structure, e.g. with hierarchy layouters, the approach does not work.  You can see the issue in these examples:

1.)  This works as expected using a json file:

http://bl.ocks.org/dbruneel/0b3372ae6e28ce5a7c3e

2.)  Using at runtime it fails (even through the data is exactly the same):

http://bl.ocks.org/dbruneel/d8bd90057e3353e61d22

We think this may be a defect.  Grateful for your assistance.

**Comment by jazzido** [comment]
I stumbled upon the same issue. It looks like the streaming API (reasonably) expects an iterable, which `treejson` objects aren't.

The solution, which I found in [this spec](https://github.com/vega/vega/pull/425#issuecomment-155249882) by @jheer, is to provide the data as a flat table and then apply `treeify` and `treemap` transformations.

**Comment by arvind** [comment]
Thanks @jazzido! You are correct, the streaming API requires array data and so the `treeify` transform would be a good way to support streaming hierarchical data.
