### ISSUE TITLE
Is it possible to define custom symbols/shapes other than the  ones out-of-box present in Vega like circle, square, cross, etc?

### ISSUE THREAD

**Issue by arvindkgs** [vega/vega#475]
As it is possible in D3, I am assuming technically this should be possible.

**Comment by jheer** [comment]
Currently, you can add custom symbols by using the `path` marktype and providing your own SVG path definitions.

We are also currently working on adding style "themes" to Vega, which should include the ability to add new named symbols for the `symbol` marktype. However, that will not be released until at least early 2016.
