### ISSUE TITLE
Support color ramps for ordinal scale

### ISSUE THREAD

**Issue by kanitw** [vega/vega#477]
From a conversation on slack:

> One option might be to support “named” color ramps (similar to Tableau and ColorBrewer). A Vega spec might include the named palette as the scale range. Then, based on the scale cardinality, an appropriate subdivision of colors could be chosen (e.g., 5/7/9). If the cardinality exceeds the largest pre-designed palette, we might fall back on interpolation.

For now, at least having interpolation would be great for VL!

**Comment by domoritz** [comment]
I don't see how a rank transform alone is enough to support color ramps. 

Yes, we can use the rank transform to correctly set the colors of marks with a linear scale. However, if we also have a legend, we cannot use the linear scale because it produces the wrong kind of legend. 

```json
{
  "width": 200,
  "height": 200,
  "padding": "auto",
  "data": [
    {
      "name": "source",
      "values": [
        {"a": "A","x": 1,"y": 1},
        {"a": "B","x": 2,"y": 2},
        {"a": "C","x": 3,"y": 3},
        {"a": "A","x": 4,"y": 4},
        {"a": "B","x": 5,"y": 5},
        {"a": "C","x": 6,"y": 6}
      ],
      "transform": [
        {
          "type": "rank",
          "field": "a",
          "normalize": true
        }
      ]
    }
  ],
  "marks": [
    {
      "name": "root",
      "type": "group",
      "from": {"data": "layout"},
      "properties": {
        "update": {"width": {"value": 200},"height": {"value": 200}}
      },
      "marks": [
        {
          "type": "symbol",
          "from": {"data": "source"},
          "properties": {
            "update": {
              "x": {"scale": "x","field": "x"},
              "y": {"scale": "y","field": "y"},
              "size": {"value": 30},
              "shape": {"value": "circle"},
              "strokeWidth": {"value": 2},
              "opacity": {"value": 0.7},
              "stroke": {"scale": "color_rank","field": "rank"}
            }
          }
        }
      ],
      "scales": [
        {
          "name": "x",
          "type": "linear",
          "domain": {"data": "source","field": "x","sort": true},
          "rangeMin": 0,
          "rangeMax": 200,
          "round": true,
          "clamp": true,
          "nice": true
        },
        {
          "name": "y",
          "type": "linear",
          "domain": {"data": "source","field": "y","sort": true},
          "rangeMin": 200,
          "rangeMax": 0,
          "round": true,
          "clamp": true,
          "nice": true
        },
        {
          "name": "color",
          "type": "ordinal",
          "domain": {"data": "source","field": "a","sort": true},
          "range": ["#AFC6A3","#09622A"],
          "clamp": true,
          "zero": false
        },
        {
          "name": "color_rank",
          "type": "linear",
          "domain": {"data": "source","field": "rank","sort": true},
          "range": ["#AFC6A3","#09622A"],
          "clamp": true,
          "zero": false
        }
      ],
      "axes": [
        {
          "type": "x",
          "scale": "x",
          "format": "s",
          "grid": true,
          "layer": "back",
          "ticks": 5,
          "title": "x"
        },
        {
          "type": "y",
          "scale": "y",
          "format": "s",
          "grid": true,
          "layer": "back",
          "title": "y"
        }
      ],
      "legends": [
        {
          "fill": "color",
          "title": "a",
          "properties": {
            "symbols": {
              "fill": {"value": "transparent"},
              "strokeWidth": {"value": 2},
              "opacity": {"value": 0.7},
              "stroke": {"scale": "color","field": "data"}
            },
            "labels": {
              "fontSize": {"value": 12},
              "text": {"field": "data"}
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by kanitw** [comment]
May add a scale that maps rank's numeric value back to original ordinal value and use the scale in legends' properties.label.text?

(set domain = `rank` field and sort by the original ordinal field, range = original ordinal field)

**Comment by arvind** [comment]
Supported via the new `rank` transform!

**Comment by domoritz** [comment]
the problem is not really solved because we have to do some ugly hacks to get legends working in vl. Though this should be resolved with d3 4's scales.

**Comment by kanitw** [comment]
@domoritz   Actually, I looked closely at d3 scale.  The new sequential color scale takes continuous data as input.  This means they are just equivalent to linear scale with interpolation between custom ramp, which wouldn't be sufficient to remove rank transform anyway. 

I think in D3, you can plug ordinal data into an ordinal scale and get value between [0,1] and pass this to the sequential color scale.   In Vega you can't pass value through two scales.  So rank transform here performs the same function as the first ordinal scale in D3 case.  

So if we really want to support this without rank, we would have to create a custom "discrete sequential color scale" that combines two scales, but I don't know if it is worth the trouble.

**Comment by arvind** [comment]
Right, it wasn't so much that D3 v4's scales would directly support this but rather that we were going to wait on overhauling Vega's scales (or introducing new ones) until D3's new scales were more stable.
