### ISSUE TITLE
Parsing inlined values

### ISSUE THREAD

**Issue by nyurik** [vega/vega#479]
According to [Data page](https://github.com/vega/vega/wiki/Data#data-properties), the format parameter can only be used for external data sources.  Please allow its usage for inline data source as well, and treat it as JSON, because frequently JSON may contain strings of dates that need to be parsed, or other similar transformations.  It would be good to keep this consistent, regardless of data being inlined or external. Thanks!

**Comment by arvind** [comment]
Hi Yuri, that was an error in the documentation. The `format` parameter is supported for both inline and external data sources. For example, inspect `ved.view.data('table').values()` to compare the following spec with and without the `format` parameter.

```json
{
  "data": [
    {
      "name": "table",
      "values": [
        {"x": "1",  "y": "28"}, {"x": "2",  "y": "55"},
        {"x": "3",  "y": "43"}, {"x": "4",  "y": "91"},
        {"x": "5",  "y": "81"}, {"x": "6",  "y": "53"},
        {"x": "7",  "y": "19"}, {"x": "8",  "y": "87"},
        {"x": "9",  "y": "52"}, {"x": "10", "y": "48"},
        {"x": "11", "y": "24"}, {"x": "12", "y": "49"},
        {"x": "13", "y": "87"}, {"x": "14", "y": "66"},
        {"x": "15", "y": "17"}, {"x": "16", "y": "27"},
        {"x": "17", "y": "68"}, {"x": "18", "y": "16"},
        {"x": "19", "y": "49"}, {"x": "20", "y": "15"}
      ],
      "format": {"type": "json", "parse": {"x": "number", "y": "number"}}
    }
  ]
}
