### ISSUE TITLE
png and svg symbol rendering is broken

### ISSUE THREAD

**Issue by nyurik** [vega/vega#481]
Using vg2png produces transparent square with black symbols, and vg2svg produces transparent image with symbols in color.  Adding `"background": "LightGray"` makes PNG totally gray, and SVG - still transparent with symbols on top.

Original report at https://phabricator.wikimedia.org/T122481

![color-symbols](https://cloud.githubusercontent.com/assets/1641515/12011170/831483c2-acd4-11e5-95ad-db9e6716eebf.png)
All files here: [color-symbols-bug.zip](https://github.com/vega/vega/files/72742/color-symbols-bug.zip)

**Comment by danyelf** [comment]
Is this related to https://github.com/vega/vega/issues/1080 ?

**Comment by jheer** [comment]
@danyelf This issue is from 2015 and Vega 2.x, so should be unrelated. Closing out as it is not relevant to current version.

**Comment by danyelf** [comment]
Fair enough. But the current bug 1080 is still buggy and creates invalid
svg. Doesn't affect browsers, does affect svg2pdf and inkscape.
