### ISSUE TITLE
Legends x,y do not work per doc, offset is missing

### ISSUE THREAD

**Issue by nyurik** [vega/vega#485]
https://github.com/vega/vega/wiki/Legends at the end mentions that Legends support x,y coordinate overrides, but it doesn't seem to work, and I haven't found it in code. Also, there is an "offset" param that only affects the X coordinate, and its not being mentioned in the doc.

**Comment by arvind** [comment]
Thanks @nyurik. `offset` has been added to the [legend documentation](https://github.com/vega/vega/wiki/Legends). The `x` and `y` properties should be nested under `properties.legend`. For example, try this legend definition with the [barley example](http://vega.github.io/vega-editor/?mode=vega&spec=barley).

```json
  "legends": [
    {"fill": "c", "title": "year", "properties": {
      "legend": {
        "x": {"value": 10},
        "y": {"value": 100}
      }
    }}
  ],
```

**Comment by nyurik** [comment]
great, thanks!
