### ISSUE TITLE
interpret newline \n character in text or add word wrapping to text marks or text in general

### ISSUE THREAD

**Issue by g3o2** [vega/vega#488]
When working with long text, it would be nice if there was some sort of word wrap to automatically (e.g having a maxchar per line property) or at least manually (e.g using \n) have the text spread over multiple lines.

**Comment by Georgeouz** [comment]
Or maybe it would be easier to implement the parsing of html tags? This would allow the use of <br> & co.

**Comment by arvind** [comment]
Yes, multi-line text would be great! However, Vega's support for multiple renderers (SVG, Canvas, and possible WebGL in the future) make this difficult to support. Your second comment is indeed promising, and perhaps something suitable to add to [vega-embed](http://github.com/vega/vega-embed).

**Comment by jazzido** [comment]
I also ran into this need. For the time being, I'm rendering my Vega charts to SVG and using [d3plus-text](https://github.com/d3plus/d3plus-text) to create the labels. 

IMHO, their [text-wrapping algorithm](https://github.com/d3plus/d3plus-text/blob/master/src/box.js#L119) would be pretty simple to implement within Vega.

**Comment by okal** [comment]
@arvind 

> Yes, multi-line text would be great! However, Vega's support for multiple renderers (SVG, Canvas, and possible WebGL in the future) make this difficult to support. Your second comment is indeed promising, and perhaps something suitable to add to vega-embed.

Pardon my ignorance, but are there specific issues that make this particularly difficult, relative to other characters? Having a list of the possible problems could help someone who'd like to take up the challenge of fixing this.

**Comment by Georgeouz** [comment]
Looks like SVG 2 will allow multi-line text via CSS: https://github.com/w3c/svgwg/wiki/SVG-2-new-features

So there is hope for this important feature to work finally in Vega, that is once major browsers implement it.

**Comment by g3o2** [comment]
A [multi-line text example](https://bl.ocks.org/mbostock/7555321) has been recently produced by Mike Bostock.

**Comment by melissachang** [comment]
The workaround in https://github.com/vega/vega/issues/488#issuecomment-254040462 looks like it's d3, not vega nor vega-list. Any chance someone could publish a workaround for vega-lite (or vega)?

**Comment by jheer** [comment]
_Update (2019.09.23)_: Vega text marks (and axis/legend/title title text) will support multiple lines as of v5.7.0. As a starting point this support requires explicit line breaks by passing in an array of strings as the text value. With this infrastructure, we should hopefully be able to support some form of automatic line wrapping in the future.

**Comment by g3o2** [comment]
Actually, thinking over the original issue, “automatically” was never part of the feature request. Explicit line breaking is absolutely good enough.

Consequently, please do not hesitate to close this issue if you like 😁

**Comment by tonyxiao** [comment]
Can you pass in two separate `field` for `value`? It seems that `value` only accept an array of string, what I'd like to do is to display an array of mixed static string as well as dynamic fields
