### ISSUE TITLE
Incorrect ordering for ordinal scale in presence of negative/float values

### ISSUE THREAD

**Issue by randyzwitch** [vega/vega#491]
A user of my Julia package pointed this out:

```json
{
  "width": 500,
  "height": 200,
  "padding": {"top": 10,"left": 30,"bottom": 30,"right": 10},
  "data": [
    {
      "name": "table",
      "values": [
        {"x": -2.5,"y": 10},
        {"x": -0.5,"y": 15},
        {"x": 1,"y": 28},
        {"x": 2,"y": 55},
        {"x": 3,"y": 43},
        {"x": 4,"y": 91},
        {"x": 5,"y": 81},
        {"x": 6,"y": 53},
        {"x": 7,"y": 19},
        {"x": 8,"y": 87},
        {"x": 9,"y": 52},
        {"x": 10,"y": 48},
        {"x": 11,"y": 24},
        {"x": 12,"y": 49},
        {"x": 13,"y": 87},
        {"x": 14,"y": 66},
        {"x": 15,"y": 17},
        {"x": 16,"y": 27},
        {"x": 17,"y": 68},
        {"x": 18,"y": 16},
        {"x": 19,"y": 49},
        {"x": 20,"y": 15},
        {"x": -1,"y": 10},
        {"x": -2,"y": 15}
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "ordinal",
      "range": "width",
      "domain": {"data": "table","field": "x"},
      "sort": true
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "domain": {"data": "table","field": "y"},
      "nice": true
    }
  ],
  "axes": [{"type": "x","scale": "x"},{"type": "y","scale": "y"}],
  "marks": [
    {
      "type": "rect",
      "from": {"data": "table"},
      "properties": {
        "enter": {
          "x": {"scale": "x","field": "x"},
          "width": {"scale": "x","band": true,"offset": -1},
          "y": {"scale": "y","field": "y"},
          "y2": {"scale": "y","value": 0}
        },
        "update": {"fill": {"value": "steelblue"}},
        "hover": {"fill": {"value": "red"}}
      }
    }
  ]
}
```

![vega](https://cloud.githubusercontent.com/assets/2762787/12235773/ee0b443e-b843-11e5-8c97-a53c20611141.png)

If you change the X scale to linear, you lose the ability to auto-calculate bar width using `band`. So not sure if this is a bug in the ordinal scaling, my misunderstanding, or an edge case?

**Comment by rinzeb** [comment]
I was running into the same problem. A work-around is to provide a 'sort' parameter to the domain of your scale, instead of to the scale itself: 

    {
      "name": "x",
      "type": "ordinal",
      "range": "width",
      "domain": {"data": "table","field": "x", "sort": true}
    },

**Comment by randyzwitch** [comment]
Thanks @rinzeb! I wonder if that's a work-around or the actual right way to do things.

**Comment by arvind** [comment]
Thanks @rinzeb! Apologies for the slow response, @randyzwitch but an ordinal scale's domain is indeed the correct place to define sorting parameters. See [the documentation](https://github.com/vega/vega/wiki/Scales#sorting-domains-for-ordinal-and-quantile-scales) or [schema](https://github.com/vega/vega/blob/master/src/scene/Scale.js#L563) for more information on how this works.

**Comment by randyzwitch** [comment]
Thanks for confirming @arvind! Even though I'm subscribed to this repo, it's hard keeping up with all the great updates to make sure I'm doing things right :)

**Comment by arvind** [comment]
:+1:
