### ISSUE TITLE
`view.onSignal` in Runtime API doesn't tolerate unknown signals

### ISSUE THREAD

**Issue by djamshed** [vega/vega#499]
`view.onSignal('someSignal', onSignalFunc)` produces
`Uncaught TypeError: Cannot read property 'on' of undefined` when 'someSignal' isn't defined as a signal in the Vega spec JSON.

Since `onSignal` is chainable, it would be nice to have it tolerate undefined signals.
```
   view
    .width(w)
    .onSignal('someSignal', onSignalFunc) // chain is broken if 'someSignal' isn't in the Vega spec
    .on('click', onClickFunc)
```

**Comment by arvind** [comment]
Thanks @djamshed! Fixed with 1fc873d -- `onSignal`, `signal` and `data` will now print an error if the given names aren't found, but are still chainable.
