### ISSUE TITLE
Text mark does not have format and formatType property

### ISSUE THREAD

**Issue by domoritz** [vega/vega#505]
I'd expect the [text mark](https://github.com/vega/vega/wiki/Marks) to have the same format and formatType properties that [axes](https://github.com/vega/vega/wiki/Axes#axis-properties) and [legends](https://github.com/vega/vega/wiki/Legends#legend-properties) have. Actually, I also found that legends miss the formatType property (https://github.com/vega/vega/blob/master/src/parse/legends.js#L56).

**Comment by arvind** [comment]
Are the [string templates](https://github.com/vega/vega/wiki/Marks#templates) offered for marks not sufficient? Axes and legends require some more abstraction since we automatically generate the label marks, but it's less clear to me if similar abstraction is required for low-level marks.

**Comment by domoritz** [comment]
Yes, I can use string templates as a work around but it would be nice to be able to use similar abstractions. Maybe vega can just generate the correct template strings? If not, I'll add this abstraction to vl.

**Comment by arvind** [comment]
If needed, adding such an abstraction to Vega-Lite makes more sense IMO. Adding format/formatType to text marks would add an alternate means of expressing only a subset of use-cases for low-level text marks (and one that doesn't seem much shorter than string templates anyways).

**Comment by domoritz** [comment]
Okay. Makes sense. What about the missing `formatType` for legends?

**Comment by arvind** [comment]
Weird, I didn't see that in the initial notification. Sorry! Do you mind opening a separate issue, so we can track it? It's not that the schema is out of sync with the codebase, like axes (#500). Rather, we will need to do some minor refactoring to add support for it ala axes.

**Comment by domoritz** [comment]
Created #506
