### ISSUE TITLE
Incomplete documentation for `from` property of marks

### ISSUE THREAD

**Issue by Jerrythafast** [vega/vega#508]
Dear Vega devs,

I discovered that the [Barley example spec](http://vega.github.io/vega-editor/?mode=vega&spec=barley) uses `"from": {"mark": "sites"}` as the data source for its `text` marks. This feature is not documented on the [Marks wiki page](https://github.com/vega/vega/wiki/Marks).

Jerry

**Comment by arvind** [comment]
Thanks Jerry. We've previously captured this hole in the documentation (#412), and hope to cover it soon.

**Comment by Jerrythafast** [comment]
Oh, I'm sorry for the dupe. Didn't realise that it was already mentioned there.
