### ISSUE TITLE
Zooming does not seem to work for mouse wheel scrolling in the panzoom example

### ISSUE THREAD

**Issue by eidehua** [vega/vega#510]
http://vega.github.io/vega-editor/?mode=vega&spec=panzoom_points

In this example, I am able to zoom in and out perfectly find with a trackpad gesture, but using a mouse scroll wheel seems to break the zoom.

I noticed in the signals xMin, xMax, yMin, yMax has this field:
        {"type": "zoom", "expr": "(xs.max-xAnchor)*zoom + xAnchor"}

When I replace the "zoom" with "wheel" (for the type) for all 4 of the signals, both trackpad and mouse wheel work fine (it seems to me)

Any idea why using "type" : "zoom" would not work for mouse wheel scrolling? I don't exactly understand the signal syntax going on here.

**Comment by Jerrythafast** [comment]
I believe this is a known issue (I've seen this one before). The solution is simple: the `zoom` signal definition needs to have `"verbose": true` added to it.
```json
    {
      "name": "zoom",
      "init": 1.0,
      "verbose": true,
      "streams": [
        {"type": "wheel", "expr": "pow(1.001, event.deltaY*pow(16, event.deltaMode))"}
      ]
    }
```

**Comment by eidehua** [comment]
Yeah that works. Can you explain what verbose does for signals?

**Comment by Jerrythafast** [comment]
As you can see in the signal definition, the `zoom` signal listens for mouse wheel events. Whenever such an event occurs, it computes the amount that the wheel has turned (the 'wheel delta'). On most systems, every 'click' of the mouse wheel is a fixed delta value. Therefore, the value of the signal does not really change (it literally changes to the same value it had before). The `"verbose": true` property tells Vega that even though the value didn't change, the graph should be updated whenever the event fires.

**Comment by arvind** [comment]
The verbose property is [now documented](https://github.com/vega/vega/wiki/Signals#signal-properties) and we've consolidated our examples with a [single canonical set](https://github.com/vega/vega/tree/master/examples) living in the Vega repository. Apologies for the confusion!

**Comment by eibanez** [comment]
Much appreciated!
