### ISSUE TITLE
Heatmap example is shearing

### ISSUE THREAD

**Issue by domoritz** [vega/vega#520]
See https://vega.github.io/vega-editor/?mode=vega&spec=heatmap&renderer=svg

There is some space between the axis and the rectangles. And the space widens as we go further down. 

<img width="795" alt="screen shot 2016-02-11 at 21 41 47" src="https://cloud.githubusercontent.com/assets/589034/12999829/4e7c8918-d108-11e5-9179-3a2468fd5da7.png">
<img width="133" alt="screen shot 2016-02-11 at 21 41 20" src="https://cloud.githubusercontent.com/assets/589034/13000348/3a8fc694-d10e-11e5-865d-c59f3bfacede.png">

**Comment by arvind** [comment]
Thanks, fixed with 8c83836.
