### ISSUE TITLE
Performing "Top N + rest" transformation

### ISSUE THREAD

**Issue by nyurik** [vega/vega#524]
For larger datasets, I keep running into the need to show the list of first N entries, plus show the last entry as "all other".  This is especially useful after sorting the dataset in the descending order, and showing it as a pie chart or a stacked chart.  Noone wants to see the long tail of items that together add up to less than 5% of the total.  Is there a way to do this kind of transformation?

One way to do this would be to have access to the index of an item in the list. Than I could create two datasets with a filter - one with the index less than N, and the other with more or equal to N.  Than I would sum the total of the second group and (somehow?) append that value to the first set.

**Comment by sercand** [comment]
I need to something similar. I want to show a pie chart with top 5 values and sum the rest as others.

**Comment by nyurik** [comment]
Am examples of this is actually now published in the Vega examples gallery. Confusingly, it is called top K rather than top N (don't ask me why))

**Comment by jheer** [comment]
Both terms (top-k and top-n) occur in the database literature, though my sense is that top-k is more common... Closing the issue because examples are now live on the Vega website.
