### ISSUE TITLE
Lookup tranform breaks on keys containing a dot

### ISSUE THREAD

**Issue by jazzido** [vega/vega#526]
Seems that the `lookup` transform does not work when the `on` parameter is a key that contains a dot. I could workaround this issue by renaming that field with a `formula` transform, as shown here: 
https://gist.github.com/jazzido/5660ba691c465010b138#file-normalized_stackedarea-json-L43-L47

**Comment by Jerrythafast** [comment]
May I add to this that I use the same hack (i.e., using a `formula` transform to synthesize a value that `lookup` can use for its `onKey` parameter) when I have a key that consists of two data attributes. With `facet` and `aggregate` transforms you can specify multiple attribute names as the key.

**Comment by danmarshall** [comment]
Try encoding with 2 backslashes preceding the dot, example in #2718

**Comment by domoritz** [comment]
Yeah, if you escape `.`, you should be able to use fields with dots in them.
