### ISSUE TITLE
How to do arithmetic operations on fields?

### ISSUE THREAD

**Issue by keizer619** [vega/vega#529]
How to do arithmetic operations such as division on a field? I have seen for multiplication mult keyword is used as folowing scenario but could not find keyword for operations such as division.

`"text": {"field": "y", "mult":1}`

**Comment by domoritz** [comment]
You can do division by multiplying with a fraction. `"text": {"field": "y", "mult":0.5}`. For other operations, you can use [expressions](https://github.com/vega/vega/wiki/Expressions).

**Comment by keizer619** [comment]
I tried that, but the problem was accuracy. In my case i am creating a Pie chart and i want to calculate Percentage where i want divide by 360. If use 1/360 as something like "mult":0.00277 its not accurate as 7 is a recurring decimal point

**Comment by domoritz** [comment]
I'm sure you have tried the pie transform https://github.com/vega/vega/wiki/Data-Transforms#-pie. Can you post a small complete spec so that we can see whether there is an alternative to achieve what you would like to do.

**Comment by kanitw** [comment]
Also, if you want to use true division, another option is to use formula transform to transform the field first. :)

**Comment by keizer619** [comment]
Please refer attached spec and following screenshot. Assume that i want to display percentage and i have used mult": 0.277777777 as value should be divided by 360 and multiple by 100 to get percentage. The row product CEP is 180 where as it should be 50%, but since 7 is a recurring decimal point it displays as 49.999... . If there is anyway to do a round operation i think we could resolve that. 

Apart from that if we are adding a string value as % for the text, can't we use it in same mark? 
<img width="328" alt="screen shot 2016-02-17 at 8 21 21 am" src="https://cloud.githubusercontent.com/assets/2918812/13098177/ca7d0648-d54d-11e5-8fe0-64071c2c0954.png">

**Comment by domoritz** [comment]
```
{
  "width": 200,
  "height": 200,
  "data": [
    {
      "name": "table",
      "values": [
        {"downloads": 180,"product": "CEP"},
        {"downloads": 60,"product": "DAS"},
        {"downloads": 60,"product": "ML"},
        {"downloads": 60,"product": "ESB"}
      ],
      "transform": [{"type": "pie","field": "downloads"},{
        "type": "formula",
        "field": "percentage",
        "expr": "datum.downloads / 360 * 100"
      }]
    }
  ],
  "scales": [
    {
      "name": "r",
      "type": "sqrt",
      "domain": {"data": "table","field": "downloads"}
    },
    {
      "name": "color",
      "type": "ordinal",
      "domain": {"data": "table","field": "product"},
      "range": "category10"
    }
  ],
  "marks": [
    {
      "type": "arc",
      "from": {"data": "table"},
      "properties": {
        "update": {
          "x": {"field": {"group": "width"},"mult": 0.5},
          "y": {"field": {"group": "height"},"mult": 0.5},
          "startAngle": {"field": "layout_start"},
          "endAngle": {"field": "layout_end"},
          "innerRadius": {"value": 0},
          "outerRadius": {"value": 100},
          "stroke": {"value": "#1"},
          "fill": {"scale": "color","field": "product"},
          "fillOpacity": {"value": 1}
        },
        "hover": {"fillOpacity": {"value": 0.8}}
      }
    },
    {
      "type": "text",
      "from": {"data": "table"},
      "properties": {
        "enter": {
          "x": {"field": {"group": "width"},"mult": 0.5},
          "y": {"field": {"group": "height"},"mult": 0.5},
          "radius": {"value": 140},
          "theta": {"field": "layout_mid"},
          "fill": {"value": "#000"},
          "align": {"value": "center"},
          "baseline": {"value": "middle"},
          "text": {"template": "{{datum.percentage | number:'.1f'}}"}
        }
      }
    }
  ]
}
```

**Comment by domoritz** [comment]
<img width="323" alt="screen shot 2016-02-16 at 21 02 37" src="https://cloud.githubusercontent.com/assets/589034/13100315/a3298a1a-d4f0-11e5-97cc-8d4129c08e40.png">

**Comment by keizer619** [comment]
Thank you very much division is precise with that transformation formula expression.
On the other is it possible  have sum of all downloads within that expression?

{
        "type": "formula",
        "field": "percentage",
        "expr": "datum.downloads / 360 * 100"
      }

**Comment by domoritz** [comment]
To get access to the sum of values, you need to add an [aggregation transform](https://github.com/vega/vega/wiki/Data-Transforms#-aggregate).

**Comment by keizer619** [comment]
@domoritz 

I tried with aggregation transform but it does not work with pie transformation. There texts were overlaps single line was drawn.

`      
"transform": [   
        {
          "type": "pie",
          "field": "downloads"
        },
        {
          "type": "aggregate",
          "groupby": ["product"],
          "summarize": [{"field": "downloads", "ops": ["sum"]}]
        }
        ,
          {
            "type": "formula",
            "field": "percentage",
            "expr": "datum.sum_downloads / 360 * 100"
          }
      ]
`


Then i add summarization inside pie transformation, here chart was drawn but text value showed as "NaN"

`      
"transform": [     
{
          "type": "pie","field": "downloads",
          "groupby": ["product"],
          "summarize": [{"field": "downloads", "ops": ["sum"]}]
        },
      {
        "type": "formula",
        "field": "percentage",
        "expr": "datum.downloads / datum.sum_downloads * 100"
      }
      ]`

**Comment by domoritz** [comment]
```json
{
  "width": 200,
  "height": 200,
  "data": [
    {
      "name": "table",
      "values": [
        {"downloads": 7,"product": "CEP"},
        {"downloads": 2,"product": "DAS"},
        {"downloads": 5,"product": "ML"},
        {"downloads": 7,"product": "ESB"}
      ]
    },
    {
      "name": "summary",
      "source": "table",
      "transform": [
        {
          "type": "aggregate",
          "summarize": {"downloads": "sum"}
        }
      ]
    },
    {
      "name": "layout",
      "source": "table",
      "transform": [
        {"type": "cross", "with": "summary"},
        {"type": "pie","field": "a.downloads"},
        {
          "type": "formula",
          "field": "percentage",
          "expr": "datum.a.downloads / datum.b.sum_downloads * 100"
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "r",
      "type": "sqrt",
      "domain": {"data": "layout","field": "a.downloads"}
    },
    {
      "name": "color",
      "type": "ordinal",
      "domain": {"data": "layout","field": "a.product"},
      "range": "category10"
    }
  ],
  "marks": [
    {
      "type": "arc",
      "from": {"data": "layout"},
      "properties": {
        "update": {
          "x": {"field": {"group": "width"},"mult": 0.5},
          "y": {"field": {"group": "height"},"mult": 0.5},
          "startAngle": {"field": "layout_start"},
          "endAngle": {"field": "layout_end"},
          "innerRadius": {"value": 0},
          "outerRadius": {"value": 100},
          "stroke": {"value": "#1"},
          "fill": {"scale": "color","field": "a.product"},
          "fillOpacity": {"value": 1}
        },
        "hover": {"fillOpacity": {"value": 0.8}}
      }
    },
    {
      "type": "text",
      "from": {"data": "layout"},
      "properties": {
        "enter": {
          "x": {"field": {"group": "width"},"mult": 0.5},
          "y": {"field": {"group": "height"},"mult": 0.5},
          "radius": {"value": 140},
          "theta": {"field": "layout_mid"},
          "fill": {"value": "#000"},
          "align": {"value": "center"},
          "baseline": {"value": "middle"},
          "text": {
            "template": "{{datum.percentage | number:'.1f'}} %"
          }
        }
      }
    }
  ]
}
```

Here you go.
