### ISSUE TITLE
Area "orient" property is declared in docs but not in schema 

### ISSUE THREAD

**Issue by mprudhom** [vega/vega#539]
The docs for the area mark at https://github.com/vega/vega/wiki/Marks#area say there is an "orient" property, but no such property exists in the schema's "propset" def. I suspect that it was removed and the docs haven't been updated, but I don't want to change the docs without logging it as an issue.

**Comment by kanitw** [comment]
Thank you for the help, but as I mentioned in https://github.com/vega/vega-lite/pull/1185.

The correct fix should be adding `orient` property to the Vega schema.

**Comment by arvind** [comment]
Fixed with 69217ec. Thanks @mprudhom.
