### ISSUE TITLE
Regression in vega 2.5.0

### ISSUE THREAD

**Issue by johanneskoester** [vega/vega#540]
With vega 2.5.0, barplots created with vega-lite get errorneously collapsed along the x-axis. The error does not occur with vega 2.4.2.

Code to reproduce:
```
{
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "sample",
      "axis": {"grid": false},
      "type": "nominal",
      "sort": "unsorted"
    },
    "y": {
      "field": "score",
      "axis": {"grid": false},
      "type": "quantitative"
    }
  },
  "data": {
    "values": [
      {"sample": "GBM_T21","score": 0.03683},
      {"sample": "DLD_ETOH","score": -0.040789},
      {"sample": "HCT116_2_T18","score": -0.052044},
      {"sample": "HELA_T18","score": -0.07994},
      {"sample": "MCF7_E2","score": -0.3886},
      {"sample": "T47D_E2","score": -0.54724}
    ]
  },
  "description": "Waterfall plot of score for one feature across samples.",
  "config": {"numberFormat": "g"}
}
```

Result with vega 2.5.0:

![vega-error](https://cloud.githubusercontent.com/assets/1858646/13363829/8dc2defa-dc99-11e5-81c1-9c11c43df901.png)

**Comment by arvind** [comment]
Hi @johanneskoester, which version of Vega-Lite are you using? I suspect you're using a `0.9.x` release which indeed is only compatible with Vega 2.4.x. Vega 2.5.0 introduced a minor breaking change to simplify design decisions in Vega-Lite 1.0. Your spec above, for example, produces a bar chart with the [online editor](http://vega.github.io/vega-editor/?mode=vega-lite). 

![download](https://cloud.githubusercontent.com/assets/42262/13364103/dbbdf738-dc81-11e5-95ab-340da3e3b790.png)

**Comment by johanneskoester** [comment]
Yes I use vega-lite 0.9.3. For the future, I guess it is not possible for you to to restrict older vega-lite npm package versions to certain major/minor versions of vega such that such breakages are avoided by the packaging system?
