### ISSUE TITLE
How to change mark color in signal callback function?

### ISSUE THREAD

**Issue by keizer619** [vega/vega#542]
At the moment i am using on signal callback functions to get data bound item information by using item.datum.<attributeName>. In firebug i noticed that item object has consist of mark details such as type and fill color. Can we use change mark color or do any changes on callback functions? Please refer following callback function i am using and fiddle code for sample scenario.
https://jsfiddle.net/kcm4d9pv/1/

```
var callbackmethod = function(event, item) { 
        if (item != null) {
            item.fill = "red";
              var div = document.getElementById("details");
                   div.innerHTML = "<p> Torque : "+item.datum.torque+"</p>"
                  +  "<p> RPM : "+item.datum.rpm+"</p>"
                  +  "<p> Engine Type : "+item.datum.EngineType+"</p>";
          }
      };

 vg.parse.spec(spec, function(error, chart) { 
 var view  = chart({el:"#dChart"}).update(); 
 view.on("click", callbackmethod);
 });
```

**Comment by domoritz** [comment]
Please post questions in the discussion group at https://groups.google.com/forum/?fromgroups#!forum/vega-js
