### ISSUE TITLE
Using indata() in data transform

### ISSUE THREAD

**Issue by jazzido** [vega/vega#548]
The documentation on [Predicate and encoding functions](https://github.com/vega/vega/wiki/Expressions#predicate-and-encoding-functions) states that `indata()` can only be used in signal stream handlers and mark production rules.

However, I'm using `indata()` within a `filter` transform in a `data` declaration without any problems:

```json
        {
            "name": "visibleSeries",
            "source": "series",
            "transform": [
                {
                    "type": "filter",
                    "test": "!indata('hiddenSeries', datum.dim_0.key, 'key')"
                }
            ]
        }
```

This has proven *very* useful to replace some dirty tricks I was doing with `lookup` to filter my datastreams, so please consider updating the documentation to reflect this.

(BTW, `indata()` and the deprecation of predicates were *great* additions to Vega. Thanks!)

**Comment by Jerrythafast** [comment]
Nice find! If this is considered 'officially supported behaviour' by the Vega devs I'm going to remove some similar hacks that I have as well.

(BTW, I would like to add the `rank` transform to the list of _great_ additions to Vega. And thank you for everything - Vega is awesome!)

**Comment by arvind** [comment]
Right you are! Only `scale` and `iscale` face that restriction. `indata` can indeed be called within any expression string, including those in data transformations. I've updated the documentation accordingly. Thanks @jazzido and @Jerrythafast!
