### ISSUE TITLE
Distribute on jsDelivr

### ISSUE THREAD

**Issue by brauliobo** [vega/vega#551]
It would be nice to have it available in a good CDN like jsDelivr

**Comment by brauliobo** [comment]
Just saw it there, but not up-to-date: http://www.jsdelivr.com/projects/vega

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

**Comment by domoritz** [comment]
We keep https://cdnjs.com/libraries/vega up to date. Note that related libraries (Vega-Lite, Vega-Embed, and Vega-Tooltip are also on cdnjs).
