### ISSUE TITLE
How to zoom?

### ISSUE THREAD

**Issue by tony612** [vega/vega#56]
I draw some maps using the geojson. But their position and size are not proper, so I want to how is there any way to zoom the view? (just like the google map)

And I notice that there is zoom behaviour in D3 (https://github.com/mbostock/d3/wiki/Zoom-Behavior), but I don't know how to use it in Vega.

**Comment by martinvirtel** [comment]
Hi everybody,

Here's a start. Panning with the mouse works, zooming as well, allthough not how you'd expect. For me. You can try out this vega json spec in the public editor at http://vega.github.io/vega-editor/?mode=vega.

https://gist.github.com/martinvirtel/6979457082526dacaf95bb6da5230cb2
