### ISSUE TITLE
use Hjson for specs in order to allow for comments/explanations

### ISSUE THREAD

**Issue by espinielli** [vega/vega#571]
This is a request for enhancements.
The rationale for proposing the use of [Hjson](https://hjson.org/) for Vega and friends specs is to allow for comments explaining the the how/why of the various examples.

The examples made available in the Vega editor are extremely useful but they force whoever is looking at them to *compile* the spec in your head each time.

Hjson would at least allow for embedded comments that could be used to explain close to the spec the why and how.

**Comment by domoritz** [comment]
This would be a vega editor feature. https://github.com/vega/vega-editor/issues/54
