### ISSUE TITLE
Recommended/preferred way to citing Vega

### ISSUE THREAD

**Issue by Jerrythafast** [vega/vega#579]
I would like to cite Vega in a scientific journal article. Do you have any preferred or otherwise recommended ways of referring to Vega in such contexts? If so, I would suggest adding a 'Citing Vega' section to the Wiki docs and/or website so people know how to do it properly :wink: 

Of course I could just put a link to the Vega website or GitHub, but I'd rather give you guys proper credit for your work and just linking to the site doesn't feel like doing so. Nor does it look very professional...

Kind regards,
Jerry

**Comment by jheer** [comment]
Thanks for asking! For now, the best article to cite is probably our recent paper that introduces the current Reactive Vega system: http://idl.cs.washington.edu/papers/reactive-vega-architecture

**Comment by kanitw** [comment]
FYI  I just put links to our papers in https://github.com/vega/vega/wiki

**Comment by Jerrythafast** [comment]
Thanks to both!
