### ISSUE TITLE
Are webfonts supported for the canvas renderer?

### ISSUE THREAD

**Issue by okal** [vega/vega#581]
We'd like to use a custom font loaded from Typekit with the Canvas renderer, but it's unclear if this is supported.

**Comment by dankrusi** [comment]
Yes, they are supported. Just make sure to reference the correct name as you would use in CSS.

Here is a rough example:

https://codepen.io/dankrusi/pen/abZmMyE

Note that you need to ensure the font is loaded before doing your first canvas draw (ie view render).

**Comment by jheer** [comment]
Thanks @dankrusi!
