### ISSUE TITLE
Custom datetime parsing

### ISSUE THREAD

**Issue by aishfenton** [vega/vega#586]
Maybe an invalid feature request (but I can't see an existing way to do this).

Is there some way in vega to specify a custom datetime parser for a field? For example, if i have a temporal field that is encoded YYYYMMDD (as integer, not a string), so Vega doesn't recognize it as a datetime, how do I get vega to treat this as a datetime and tell it the format of that datetime?

**Comment by domoritz** [comment]
You can pass a format to `date`. See https://github.com/vega/datalib/wiki/Import#dl_read It was implemented in https://github.com/vega/datalib/pull/46.

**Comment by kanitw** [comment]
@domoritz  FYI, I just updated the docs about this https://github.com/vega/vega/wiki/Data -- please double check.

**Comment by domoritz** [comment]
I have to check but I think you provide the format it in parse, not
properties.

**Comment by kanitw** [comment]
> but I think you provide the format it in parse, not properties.

Do you mean I have to do it in properties, not parse?  (In the docs, I added to `parse`)

**Comment by kanitw** [comment]
What's properties though?

**Comment by domoritz** [comment]
`property` is to extract a nested property from json. See https://github.com/vega/vega/wiki/Data#-json

**Comment by kanitw** [comment]
Oh gotcha.  I pasted it on the wrong row.  (I started from below actually)
