### ISSUE TITLE
d3 v4

### ISSUE THREAD

**Issue by benstoltz** [vega/vega#603]
Hey guys, I was just curious to see what the intended update path for d3 v4 is going forward? Just curious what the path forward looks like.

(I might be up for helping with that if time allows and if there's no plans at present)

**Comment by arvind** [comment]
Hi @benstoltz, @jheer summarized our roadmap for D3 v4 and future versions of Vega in [this thread](https://groups.google.com/d/msg/vega-js/7yAKpZiK7E0/0XT4FsgZBwAJ) on the vega-js google group. We'll be moving our work to public repos soon, and look forward to your help then!
