### ISSUE TITLE
Unexpected identifier for data value keys with spaces

### ISSUE THREAD

**Issue by peller** [vega/vega#606]
When data value keys contain spaces, Vega fails to parse and emits an "Unexpected identifier" exception, as shown in [this fiddle](https://jsfiddle.net/uLmcL3j1/)

**Comment by arvind** [comment]
Hi @peller, Vega does support space-delimited field names but Vega-Lite (which is what the linked spec is written with) does not yet. Support for it is being tracked in vega/vega-lite#778. Thanks!
