### ISSUE TITLE
Accessibility Issues w/ Vega

### ISSUE THREAD

**Issue by wannabeCitizen** [vega/vega#607]
Hi there,

So I'm working with a group -- Inclusive Design Institute -- who are making accessible data visualizations. That is, representing data such that it is both visualized and sonified. We were seriously considering Vega until we realized the blackbox of the parser makes it very difficult to retain information about the data as it is played with since the canvas/svg spit out on the other end no longer retain inspectable data to easily point at and sonify for someone with a visual impairment.

One solution we have considered is forking your repo and modifying [this file](https://github.com/vega/vega/blob/master/src/parse/data.js) so that we retain our own copy of all data after transformations. However, this doesn't necessarily correspond to the representation and  really makes everything we code completely dependent on Vega since we're inserting our sonification system directly into Vega source.

Do you have any suggestions of how we could integrate Vega while retaining the ability to inspect and sonify the data after its been transformed and parsed?

**Comment by jheer** [comment]
You might start by looking at the Vega scenegraph. It is used as the input to either Canvas or SVG rendering, and contains both the geometric information and links to all visualized data elements. Once you create a Vega view, you can access the scenegraph via `view.model().scene()`. For more, see also https://github.com/vega/vega-scenegraph/

As this is not a direct bug or feature request, I'm formally closing this issue. However, feel free to continue the conversation here.

**Comment by wannabeCitizen** [comment]
@jheer I'm not sure what you mean by a Vega view? Having done one brief read-through of the Vega documentation I am not familiar with that concept. Can you point to how I return myself a View object out of a vega parse?

**Comment by wannabeCitizen** [comment]
Ah going back to look at it @jheer and found this: https://github.com/vega/vega/wiki/Runtime#view-component-api

Which is what I assume you mean. I'll look more into this and let you know if other q's come up.
