### ISSUE TITLE
Custom tick formatting function

### ISSUE THREAD

**Issue by dsschwarz** [vega/vega#608]
I saw that this issue was closed https://github.com/vega/vega/issues/194
However, I'm finding that the d3 number format and the template syntax don't seem to be able to cover my requirements.

I'm looking to customize the SI suffixes (i.e. use B instead of G for 1e9). That's possible to do by overriding some d3 methods, but it's not ideal. Having a custom formatting function would be very helpful here.

**Comment by domoritz** [comment]
Here is an example of how you can use expressions to customize axis labels with an expression: https://github.com/vega/vega-lite-api/issues/12#issuecomment-506739847.
