### ISSUE TITLE
scale's `sort: true` broken

### ISSUE THREAD

**Issue by kanitw** [vega/vega#610]
This spec doesn't sort the field correctly  (Make sure to use svg renderer as the output is larger than canvas size)

![vega_editor](https://cloud.githubusercontent.com/assets/111269/17678968/461fec38-62ee-11e6-9aee-2b0b0e79987d.png)

```
{
  "width": 1,
  "height": 1,
  "padding": "auto",
  "data": [
    {
      "name": "source",
      "url": "data/movies.json",
      "format": {"type": "json","parse": {}},
      "transform": []
    },
    {
      "name": "layout",
      "source": "source",
      "transform": [
        {
          "type": "aggregate",
          "summarize": [{"field": "Title","ops": ["distinct"]}]
        },
        {"type": "formula","field": "width","expr": "21"},
        {
          "type": "formula",
          "field": "height",
          "expr": "(datum[\"distinct_Title\"] + 1) * 21"
        }
      ]
    }
  ],
  "marks": [
    {
      "name": "root",
      "type": "group",
      "from": {"data": "layout"},
      "properties": {
        "update": {
          "width": {"field": "width"},
          "height": {"field": "height"}
        }
      },
      "marks": [
        {
          "name": "marks",
          "type": "symbol",
          "from": {"data": "source"},
          "properties": {
            "update": {
              "x": {"value": 10.5},
              "y": {"scale": "y","field": "Title"},
              "size": {"value": 30},
              "shape": {"value": "circle"},
              "strokeWidth": {"value": 2},
              "opacity": {"value": 0.7},
              "stroke": {"value": "#4682b4"},
              "fill": {"value": "transparent"}
            }
          }
        }
      ],
      "scales": [
        {
          "name": "y",
          "type": "ordinal",
          "domain": {"data": "source","field": "Title","sort": true},
          "bandSize": 21,
          "round": true,
          "padding": 1,
          "points": true
        }
      ],
      "axes": [
        {
          "type": "y",
          "scale": "y",
          "grid": false,
          "title": "Title",
          "properties": {
            "labels": {
              "text": {
                "template": "{{ datum[\"data\"] | truncate:25 }}"
              }
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by Georgeouz** [comment]
I confirm this behaviour on another specification as well. No sorting using the sort.field option on an ordinal scale.

**Comment by kanitw** [comment]
@jheer  I know that you already fixed this for Vega 3 but I wonder if this is easy to fix in Vega 2?
If it's easy, I think it's worth fixing too since I saw this problem come up last tuesday and might occur more during our user studies.

**Comment by arvind** [comment]
@kanitw, it looks like this is happening because some of the values of the `Title` field in `movies.json` are numbers not strings (e.g., `1776`, `1941`). You can add a parsing rule to your data import like so, which fixes the above behaviour:

```json
{
      "name": "source",
      "url": "data/movies.json",
      "format": {"type": "json","parse": {"Title": "string"}},
      "transform": []
    }
```

It should be easy enough to add a run over the domain that coerces the values to strings, which is what I think D3's ordinal scales do anyways.

**Comment by arvind** [comment]
Just released Vega 2.6.2 which first coerces ordinal scale domain values to string before sorting by key (i.e., when `"sort": true`). This should resolve this issue without requiring the explicit parsing step described above. Hope that helps!

**Comment by kanitw** [comment]
Awesome! Thanks!

**Comment by arvind** [comment]
As #613 indicates, the above solution (v2.6.2) is incorrect. Coercing to string will adversely affect ordinal domain values that are numeric or datetime. I've rolled it back and issued v2.6.3 instead. Pending a better solution, I recommend ensuring that fields are parsed to the expected format on load as described in the code block above.

**Comment by Fil** [comment]
Found this issue while searching for an explanation re: the canvas renderer failing.

Your comment "Make sure to use svg renderer as the output is larger than canvas size" makes me wonder if that is what happens when some data points are "off the grid"?

**Comment by domoritz** [comment]
Looks like this is fixed now

<img width="306" alt="Screen Shot 2019-07-06 at 3 23 34 PM" src="https://user-images.githubusercontent.com/589034/60756776-0e314700-a002-11e9-92cb-9f4afdedc134.png">
