### ISSUE TITLE
vg2svg should take stdin as input if given no command-line file argument

### ISSUE THREAD

**Issue by jowens** [vega/vega#612]
`vg2svg`, if given no arguments, should take its input from stdin. This mirrors `vl2vg` and allows a full pipe from vega-lite to svg. Workaround is creating a tempfile.

```
Usage: vg2svg vega_json_file [output_svg_file]
  If output_svg_file is not provided, writes to stdout.
```

**Comment by domoritz** [comment]
Vega-Lite does this. Should be easy to copy what we did in https://github.com/vega/vega-lite/blob/master/bin/vl2vg#L23

**Comment by jowens** [comment]
`vg2png` too, please.

**Comment by jheer** [comment]
This is how the new `vg2png` and `vg2svg` work (Vega 3.x). Thanks!
