### ISSUE TITLE
Broken Color Legend for time scale

### ISSUE THREAD

**Issue by kanitw** [vega/vega#613]
This [spec](http://pastebin.com/ReJDz8yP) works fine in 2.6.1.

![vega_editor](https://cloud.githubusercontent.com/assets/111269/18023150/60621ab6-6baa-11e6-9f3a-a133393f81cb.png)

but broken starting in 2.6.2

![vega_editor](https://cloud.githubusercontent.com/assets/111269/18023225/5f44f332-6bab-11e6-80de-bd44d1d5fc85.png)

cc: @jpocom

**Comment by arvind** [comment]
The bug wasn't introduced in v2.6 but v2.6.2 because I coerce `"sort": true` datarefs to keys. Crap.

**Comment by kanitw** [comment]
Yeah, sorry for wrong version report.  (I just corrected it after conversation with @jpocom)

**Comment by arvind** [comment]
Rolled back the change introduced by v2.6.2, and issued v2.6.3. Apologies for introducing the bug.

**Comment by jpocom** [comment]
Great, Thanks.
