### ISSUE TITLE
scale's sort.op does not appear to react to anything else than "min"

### ISSUE THREAD

**Issue by Georgeouz** [vega/vega#615]
Following a Google discussion suggesting [scale's sort (see Kanit's answer)](https://groups.google.com/forum/#!msg/vega-js/FesFYWh2FA0/buY1mwKVAwAJ) as solution and based on [Kanit's example](http://pastebin.com/yMr93t2J), which I've tested on Vega Editor, it appears that `sort.op` would not reverse the scale's sort order when changing the value of `sort.op` from "min" to "max".

Is this expected behaviour or would there be a bug ?

**Comment by kanitw** [comment]
I think you misunderstand the purpose of `scale`'s `sort.op`.   (Yep! The docs should have a better example.)

> changing the value of sort.op from "min" to "max".

This should **not** reverse the scale's sort order.  This property is for disambiguating how to sort the scale if the `sort.field` has multiple values.

For example,    if you have 3 tuples: 
```
{a: 1,  b:1}
{a: 2,  b:2}
{a: 1,  b:3}
```

If you sort a scale of field `a` by field `b` (`sort.field = "b"`), it's unclear if it should take `b=1` or `b=3` into account for the sorting `a` when `a=1`.  Thus, `sort.op` disambiguates this.  If `sort.op = "min"`, `b=1` will be used for sorting.  If `sort.op = "max"`, `b=3` will be used for sorting.  If `sort.op = "mean"`, b=(1+3)/2 = 2 will be used for sorting.


To reverse scale, you can use `scale`'s `reverse`.

**Comment by Georgeouz** [comment]
Thank you a lot for your guidance ! and sorry for the noise ... Indeed I got confused, the solution being just in front of me all the time. I'd agree on the documentation part but your explanation now complements it nicely.

**Comment by kanitw** [comment]
No problem.  I think our current doc makes it quite hard to understand :)
