### ISSUE TITLE
Broken link on https://github.com/vega/vega/wiki/Embed-Vega-Web-Components

### ISSUE THREAD

**Issue by owendall** [vega/vega#616]
![broken link](https://cloud.githubusercontent.com/assets/10927/18097376/93ff41e2-6eab-11e6-8a35-9ba02bf3bcaf.png)

**Comment by arvind** [comment]
Thanks @owendall. Fixed to point to [this file](https://github.com/vega/vega-embed/blob/master/test/style.css).

**Comment by owendall** [comment]
Great!
