### ISSUE TITLE
[Vega Err] PARSE DATA FAILED: table TypeError: d3_cloud is not a function

### ISSUE THREAD

**Issue by owendall** [vega/vega#617]
I am very new to Vega and Vega Lite, but I haven't had any issue w until I tried the wordcloud.   Am I doing something wrong?  Simple example below gives me the error I posted:
![vega issue](https://cloud.githubusercontent.com/assets/10927/18175983/9b94737c-7041-11e6-9684-43168ab38feb.png)

https://gist.github.com/owendall/a2f1f97ff8be1d42b49ec6d468d949dd

**Comment by jheer** [comment]
It looks like the d3 wordcloud library is not being imported? It is not bundled with the vega.js code and so needs to be included separately, much like d3.

Try adding the following (or similar) to the `head` block of your HTML:
```
<script src="http://vega.github.io/vega-editor/vendor/d3.layout.cloud.js" charset="utf-8"></script>
```

Closing the issue for now, feel free to re-open if this doesn't address the problem.

**Comment by arvind** [comment]
In particular, the order of imports matters. I noticed in your gist that the `d3.layout.cloud.js` library is being imported _after_ `vega.js`, if you move it _before_ the errors should be addressed.

**Comment by owendall** [comment]
Well, now I get "scene is undefined."  I thought I copied this exactly from the Vega Editor  Live...
![scene is not defined](https://cloud.githubusercontent.com/assets/10927/18179172/3fe05b64-704f-11e6-9226-247604ed1d1f.png)
Is there a default to canvas unless specified?  Sorry for the noob questions, but I will post the solution so others can  benefit...

 http://bl.ocks.org/owendall/141e5fb23f37fdcff5842aa57b24d707

**Comment by arvind** [comment]
@owendall Where did you find that spec? It looks like the wordcloud spec for Vega 1. The definition of the wordcloud transform has changed in Vega 2. See the [online wordcloud example](http://vega.github.io/vega-editor/?mode=vega&spec=wordcloud) for a working example.
