### ISSUE TITLE
Scaling breaks when loading data from CSV

### ISSUE THREAD

**Issue by baldwint** [vega/vega#618]
I have the following Vega spec:

    {
      "name": "example",
      "width": 500,
      "height": 200,
      "data": [
        {
            "name": "dataset",
            "format": {"type": "csv"},
            "url": "eg.csv"
        }  ],
      "scales": [
        {
          "name": "xscale",
          "range": "width",
          "domain": {"data": "dataset","field": "distance"}
        },
        {
          "name": "yscale",
          "range": "height",
          "domain": {"data": "dataset","field": "time"}
        }
      ],
      "axes": [
        {"type": "x","scale": "xscale"},
        {"type": "y","scale": "yscale"}
      ],
      "marks": [
        {
          "type": "line",
          "from": {"data": "dataset"},
          "properties": {
            "enter": {
              "x": {"scale": "xscale","field": "distance"},
              "y": {"scale": "yscale","field": "time"}
            },
            "update": {"stroke": {"value": "black"}}
          }
        }
      ]
    }

where `eg.csv` contains the following:

    distance,time
    0,0.0
    4,2.5
    8.,2.4
    9,1.4
    11,.6

When the plot is generated, the x axis caps at 9, and the final data point is plotted off the axis.

![bug1](https://cloud.githubusercontent.com/assets/1120261/18175976/6b496614-7028-11e6-8a77-0df908eae5c5.png)

Indeed, any x-value greater than 9 will be plotted proportionally far outside the data rectangle.

However, if I zero-pad the first column of the csv file, scaling works properly:

    distance,time
    00,0.0
    04,2.5
    08.,2.4
    09,1.4
    11,.6

![bug2](https://cloud.githubusercontent.com/assets/1120261/18175975/6b226866-7028-11e6-8e62-ae867b696e8c.png)

This is not the behavior I expected. If my spec is correct, it might be a bug in Vega's scaling (or possibly Datalib's parsing).

**Comment by jheer** [comment]
The problem is that by default CSV parsing results in string values only. Datalib provides type inference but it needs to be enabled by adding `parse: "auto"` to the format directive.

Here is a working variant of your specification:
```json
{
  "name": "example",
  "width": 500,
  "height": 200,
  "data": [
    {
        "name": "dataset",
        "format": {"type": "csv", "parse":"auto"},
        "values": "distance,time\n0,0.0\n4,2.5\n8.,2.4\n9,1.4\n11,.6"
    }  ],
  "scales": [
    {
      "name": "xscale",
      "range": "width",
      "domain": {"data": "dataset","field": "distance"}
    },
    {
      "name": "yscale",
      "range": "height",
      "domain": {"data": "dataset","field": "time"}
    }
  ],
  "axes": [
    {"type": "x","scale": "xscale"},
    {"type": "y","scale": "yscale"}
  ],
  "marks": [
    {
      "type": "line",
      "from": {"data": "dataset"},
      "properties": {
        "enter": {
          "x": {"scale": "xscale","field": "distance"},
          "y": {"scale": "yscale","field": "time"}
        },
        "update": {"stroke": {"value": "black"}}
      }
    }
  ]
}
```

**Comment by baldwint** [comment]
Oops, thank you. I had read [here](https://github.com/vega/vega/wiki/Data#-csv) that `auto` is the default, so didn't think I had to specify it. Sorry for the frivolous report.
