### ISSUE TITLE
XSS with Vega?

### ISSUE THREAD

**Issue by mscreenie** [vega/vega#620]
I want to allow user uploaded .json files for data visualizations and this project seems a good candidat but have concerns about safety. 

I wanted to know is it safe from cross site scripting? Can a malicious json file be created and parsed with vega to allow for xss?

**Comment by domoritz** [comment]
Vega's expressions are limited to a subset of JavaScript to prevent XSS attacks (https://github.com/vega/vega/wiki/Expressions). Wikipedia actually allows embedding Vega charts (see https://www.mediawiki.org/wiki/Extension:Graph/Demo) and they were concerned about safety before we added a strict expression parser.

**Comment by mscreenie** [comment]
Can fetching of data sources be disabled and can the subset of Javascript be limited or disabled ? @domoritz  Thank you.

**Comment by domoritz** [comment]
You can restrict the data sources by white listing in https://github.com/vega/vega/blob/78b7e81466fd683c93e18c712f464d402e239950/src/core/config.js#L11. The subset of javascript is defined by the expression parser (https://github.com/vega/vega-expression). If you need to limit it further, you'll have to change the code and compile your own vega.
