### ISSUE TITLE
Themes for Vega

### ISSUE THREAD

**Issue by amitkaps** [vega/vega#624]
Is there anyplace to get themes for vega already? This wiki mentions 'excel' and 'ggplot2' ones, but I don't see the code for them.
https://github.com/vega/vega/wiki/Theme-Configuration

Can you share them? We can build on them (instead of starting from scratch) and it would be good to develop some pre-built theme like 'ggplot2', 'economist', 'black, and 'fivethirtyeight' to help in adoption.

I apologies if this is not an issue but more a request for releasing additional documentation code... Can't seem to find a way to label it as such.

**Comment by arvind** [comment]
Hi @amitkaps, we provide a handful of [example themes](https://github.com/vega/vega/tree/master/examples/themes) with Vega which you can preview in the online editor as well (click the cog icon at the top-center of the screen). We would welcome any PRs to include additional themes, like the ones you've suggested. I've also updated the Theme-Configuration wiki page to link to the specific examples it discusses. Hope that helps!

**Comment by amitkaps** [comment]
Thanks @arvind This is great. Apologies, I should have poked around more deeply in the codebase before raising this. Will work on some additional themes and send a pull request when done. Thanks once again.
