### ISSUE TITLE
Using SignalRef in DateRef field?

### ISSUE THREAD

**Issue by Naisunev** [vega/vega#628]
I was trying to use a parameter (vg-embed) with a signal to specify which column from my CSV to show in the graph. For this I was hoping I could use the SignalRef {"signal": "name"}  inside the "field": DataRef for the marks.

Example: 
with signalref:      "marks": [{ "properties": { "update": {"y": {"scale": "y","field": {"signal": "parameter"}},
Instead of:           "marks": [{ "properties": { "update": {"y": {"scale": "y","field": "speed"},

Currently this doesn't seem to work. Am I doing this wrong or could this be a feature request?

**Comment by arvind** [comment]
Hi @Naisunev, you'll want to nest your SignalRef within a `datum` property like so: `"field": {"datum": {"signal": "parameter"}}`. This indicates that the `parameter` signal value should be used to reference a particular property of `datum` which is used as the field definition for a particular visual encoding. Hope that helps!

**Comment by Naisunev** [comment]
ok.. that seems to work! thanks.. but I now have the last hurdle to make it work.

It's the auto-re-scaling of the y axis when I change selection. I tried these in the axis:

  "domain": {"data": "source", "field": {"signal":"parameter"}},
  "domain": {"data": "source", "field": {"parent": {"datum":{"signal":"parameter"}}}},

**Comment by Naisunev** [comment]
@arvind ok.. that seems to work! thanks.. but I now have the last hurdle to make it work.

It's the auto-re-scaling of the y axis when I change selection. I tried these in the scale, but none seem to work:

"domain": {"data": "source", "field": {"signal":"parameter"}},
"domain": {"data": "source", "field": {"parent": {"datum":{"signal":"parameter"}}}},

**Comment by arvind** [comment]
Yes, unfortunately it is not yet possible to specify scale domain fields via a signal. Instead, an alternative option would be to generate all the scales you need for all possible values that the `parameter` signal might take, and then choose between them using the signal (i.e., `"scale": {"signal": "parameter"}` within a particular visual encoding property).

**Comment by Naisunev** [comment]
@arvind Thanks. The workaround works, but things keep popping up elsewhere.
Now the scale updates correctly, but the axis numbers don't.  I did manage the axis title (from another post).

My current axis looks like this. If I change the "scale" component to be "scale": { "signal": "parameter"} it won't parse (since it only accepts string). Any tips for this one?
        {
          "type": "y",
          "scale": "speed",
          "format": "s",
          "grid": true,
          "layer": "back",
          "title": "TEST",
          "properties":{"title": {"text": {"signal":"parameter"}}}
        }

**Comment by arvind** [comment]
The best I can think is to similarly generate an axis per scale, and toggle the visibility of its constituent marks based on the `parameter`. Not ideal by any means, but I believe this should become easier with Vega 3.

**Comment by Naisunev** [comment]
how do I set the visibility of the axis? (or marks?)

**Comment by arvind** [comment]
For each axis property (`axis`, `title`, `labels`, etc.).

```
"properties": {
  "axis": {"opacity": [{"test": "parameter === 'a'", "value": 1}, {"value": 0}]},
  ...
}
```

**Comment by Naisunev** [comment]
works like a charm! If you're interested I'll share the end result.

**Comment by arvind** [comment]
Yes please! Perhaps post to the [Examples Gallery](https://github.com/vega/vega/wiki/Gallery) if appropriate?
