### ISSUE TITLE
Vega chart removal

### ISSUE THREAD

**Issue by bahodir-annaev** [vega/vega#629]
Hi, is there a proper way to remove a chart from document? I'm having detached Canvas element which can't get garbage collected. I am using 

`vg.parse.spec(sp, function (chart) {`
    `var ch = chart({el: cell}).update();`
    `charts.push(ch);`
`});`
...

`charts[0].destroy();`

but it does not seem to help.

**Comment by GCheung55** [comment]
@bahodir-annaev Is this still an issue?

I'm not sure what the `destroy` method does but hopefully it removes all the events/signals from the chart and prepares it for removal, then it's just a matter of removing the `cell` perhaps?

**Comment by bahodir-annaev** [comment]
It is not an issue any more. Thank you for your concern about this issue.

2017-03-07 11:10 GMT+05:00 Garrick Cheung <notifications@github.com>:

**Comment by GCheung55** [comment]
@bahodir-annaev Np. Just trying to help. If it's no longer an issue can you close this? Thank you!
