### ISSUE TITLE
Run external function on hover

### ISSUE THREAD

**Issue by Golovior** [vega/vega#636]
I've been looking for a way to run an own written function when hovering on a mark. I can't find anything about it. Is this possible?
If so; Is it also possible to add variables to the function?

Thank you in advance.

**Comment by floribon** [comment]
You can bind a listener on the view:

```
view.on("mouseover", function(event, item) {
  // access item.mark, item.datum, etc..
});
```

**Comment by Golovior** [comment]
But then what is in the view?
Isn't the view the entire graph area? Or is every part of the area a different view component?

**Comment by floribon** [comment]
The view is an instantiation of the spec. When you write that:

```
vg.parse.spec(spec, function(error, chart) {
  // function chart returns a view
  var view = chart({el: "#vis"});
});
```

You can see that here: https://github.com/vega/vega/wiki/Runtime

Now this obviously assume that you have access to the code that instanciate vega, you cannot add custom "code" within a JSON spec. The alternative is to manipulate signals and rules etc.

**Comment by Golovior** [comment]
Perfect.
I've made a test to see what `item` contains and by usage of the "datum" and "mark" -> "def" info i can exactly determine the different marks.

Thank you once again.
