### ISSUE TITLE
Enable targeted error output

### ISSUE THREAD

**Issue by jheer** [vega/vega#640]
(Migrating uwdata/vega#96)

It would be valuable to target error messages to receivers other than just the JavaScript console. As discussed earlier by @jakevdp, @kanitw and others, this issue notably arises for Altair users in Python.

Vega Dataflow (and hence also Vega View) allows both logging and error handling methods to be over-ridden, providing a straightforward mechanism for doing this. For example, the Vega View class could update output HTML with error messages to make it visible in the browser. However, that might not always be desirable and so would need to be configurable. (Note that in Vega 3, parsing from JSON to Dataflow is a completely separate step, with a different error-handling surface area. So parse errors and runtime errors are separate categories to handle!)

Also, might it be feasible to route error messages back to Python (or other external language environments)? Perhaps that is something ipyvega might do? Thoughts / input welcome.

**Comment by domoritz** [comment]
The error messages should also be shown in the new vega editor. cc @mathisonian

**Comment by jheer** [comment]
As of v3.0.0-rc2, any errors generated during dataflow or event stream evaluation are caught and then routed through the `dataflow.error` (aka `view.error`) logging function. By default this prints to the console. Clients can override this method (by assigning a new function) to perform custom error logging or presentation.

**Comment by jakevdp** [comment]
Awesome! @ellisonbg we might think about how to take advantage of this in notebook & jupyterlab.

**Comment by domoritz** [comment]
cc @starry9, we should use this instead of the try ... catch in the editor.

**Comment by ellisonbg** [comment]
Yes, it would be nice to have better error handling/messaging for users.

**Comment by ellisonbg** [comment]
https://github.com/jupyterlab/jupyterlab/issues/2669

**Comment by domoritz** [comment]
How do I implement this in Vega? I tried passing a function to view.error and setting that function but neither worked.

**Comment by jheer** [comment]
You should be able to either:
(a) Set your own custom logger instance via the view/dataflow `logger` method, or
(b) Assign your own function to view.error (or warn, info, or debug) to perform custom handling / logging.

For example:
`view.error = function() { /* do something customized with 'arguments' */ }`
