### ISSUE TITLE
Are there any examples with live or realtime data?

### ISSUE THREAD

**Issue by srossross** [vega/vega#650]
Does vega support this?

Something like: http://bl.ocks.org/simenbrekken/6634070

**Comment by jheer** [comment]
For Vega v2.x, take a look at these examples included in the main repository: https://github.com/vega/vega/tree/v2.x/test/dynamic

For Vega 3 beta, we don't have related examples yet, but a similar approach works. The [Vega 3 View API](https://github.com/vega/vega-view#data) is changed from Vega 2, but continues to provide methods for dynamically adding and removing data.

**Comment by moroshko** [comment]
@jheer These v2.x examples do not run anymore. 
Looks like the referenced `vega.js` doesn't exist anymore.

```
<script src="../../vega.js"></script>
```

> Uncaught ReferenceError: vg is not defined

**Comment by moroshko** [comment]
Sorry, I forgot to run `npm run build` 😄

**Comment by moroshko** [comment]
Well, the `index_chart.html` example is still broken. It errors:

> PARSE DATA FAILED: indexified_stocks Error: "zip" is not a valid transformation

**Comment by jheer** [comment]
Flagging @arvind as this is specific to Vega v2. The zip transform was removed some time ago, and replaced by the lookup transform.
