### ISSUE TITLE
Unexpected Vega v3 behaviour when using it with Angular v2.

### ISSUE THREAD

**Issue by dbautistav** [vega/vega#656]
Hello Vega people!

I am trying to use **Vega v3** into a very basic **Angular v2** skeleton (using **typescript v2** and **webpack v2**), but obtaining unexpected behavior, which I will try to explain below (from here I will omit versions, but the reference will be [those specified here](https://github.com/dbautistav/ng2-vega/blob/27bb1d85efa83b3f3e4cbdd08b5ac7dcdfa6dd3d/package.json#L25-L81)).

[Full demo repo here.](https://github.com/dbautistav/ng2-vega) 

- First, the bundled version wasn't working for me so I decided to include every dependency listed in [a provided example](https://github.com/vega/vega/blob/6ab84d83a23e66f38e9fcd3586dc8a57cf9349c7/package.json#L55-L74) and [using Vega modules directly](https://github.com/dbautistav/ng2-vega/blob/27bb1d85efa83b3f3e4cbdd08b5ac7dcdfa6dd3d/src/vega/vega.component.ts#L5-L7).

- Second, there were three official example specifications ([first spec](https://github.com/vega/vega/blob/6ab84d83a23e66f38e9fcd3586dc8a57cf9349c7/spec/bar.vg.json), [second spec](https://github.com/vega/vega/blob/6ab84d83a23e66f38e9fcd3586dc8a57cf9349c7/web/prefacet.html#L27-L110), [third spec](https://github.com/vega/vega/blob/6ab84d83a23e66f38e9fcd3586dc8a57cf9349c7/web/group.html#L33-L116)) used to test the described setup.

- Third, after running [the base Vega drawing methods chain](https://github.com/dbautistav/ng2-vega/blob/27bb1d85efa83b3f3e4cbdd08b5ac7dcdfa6dd3d/src/vega/vega.component.ts#L74-L86) for each specification, the results were of two types:
  - [first spec](https://github.com/vega/vega/blob/6ab84d83a23e66f38e9fcd3586dc8a57cf9349c7/spec/bar.vg.json), throws the following error: `EXCEPTION: Error in ./VegaPlotComponent class VegaPlotComponent_Host - inline template:0:0 caused by: Cannot read property 'orient' of undefined` which breaks entire Angular app. [Full stack trace here](https://github.com/dbautistav/ng2-vega/issues/1).
  - [second spec](https://github.com/vega/vega/blob/6ab84d83a23e66f38e9fcd3586dc8a57cf9349c7/web/prefacet.html#L27-L110) & [third spec](https://github.com/vega/vega/blob/6ab84d83a23e66f38e9fcd3586dc8a57cf9349c7/web/group.html#L33-L116) create a `width="9", height="9"` svg square without apparent reason ([2nd spec plot size](https://github.com/dbautistav/ng2-vega/blob/27bb1d85efa83b3f3e4cbdd08b5ac7dcdfa6dd3d/src/vega/vega.component.ts#L183-L184), [3rd spec plot size](https://github.com/dbautistav/ng2-vega/blob/27bb1d85efa83b3f3e4cbdd08b5ac7dcdfa6dd3d/src/vega/vega.component.ts#L290-L291)) as shown in fig-1 and fig-2.

![screenshot from 2016-11-08 21-26-44](https://cloud.githubusercontent.com/assets/8743976/20126376/43864e50-a5fa-11e6-9548-535625663e1c.png)
  **Figure 1. Vega plot-Angular component DOM fragment inspected (dev-tools).**

![screenshot from 2016-11-08 21-34-25](https://cloud.githubusercontent.com/assets/8743976/20126483/364cfb02-a5fb-11e6-8521-9ada9c7f1b17.png)
  **Figure 2. Vega plot-Angular component DOM fragment selected (rendered view).**

What I need is some advice and/or someone pointing me into the right direction (e.g.: documentation, Vega source code, working examples) to understand, find and correct listed issues.

Thanks in advance for your help.

**Comment by jheer** [comment]
Thanks for sharing the issue. In the months since this was initially posted, Vega 3 has been through some substantial updates. Documentation and examples are now online at https://vega.github.io/vega.

If you encounter future issues with Angular integration, feel free to open a new issue along with detailed information about what Vega is (or isn't) doing that is leading to issues.
