### ISSUE TITLE
Allow Axis and Axis label to take in name from vega spec

### ISSUE THREAD

**Issue by HartonWong** [vega/vega#657]
Is it possible to allow axis and axis label to take in name from vega spec?

**Comment by jheer** [comment]
Hi! I'm afraid I don't fully understand what you are asking. Would you mind including an example of the functionality you're hoping to use?

**Comment by ronakrrb** [comment]
I think what @HelenWong is asking for is a way to pass the name to axis group so it can be used as a class. This feature will be a useful one to stylize axis. Currently, a new mark has to be created for the axis if axis is to be provided with a name

**Comment by HelenWong** [comment]
@ronakrrb Thanks for clarifying for me. This is exactly what I mean.
As in https://github.com/vega/vega/issues/182, Vega add the ability to append CSS name to mark. If we can do the same thing to Axis, and axis labels, that will be greatly appreciated! 
![pasted image at 2016_11_30 11_37 am](https://cloud.githubusercontent.com/assets/8700743/20768064/60d66d16-b6f1-11e6-81a4-bfb4bccbfed5.png)

**Comment by jheer** [comment]
Got it, thanks! We'll look into it. Re-classifying as a feature request.

**Comment by jheer** [comment]
Added in vega/vega-parser@1805f2d18e84ec74d0ce6923cefb2df787fc7b12 and released in [v3.0.0-beta.6](https://github.com/vega/vega/releases/tag/v3.0.0-beta.6).

**Comment by HartonWong** [comment]
Thank @jheer for this timely updates! I just want to confirm that if axis labels takes in name in this push?

![1](https://cloud.githubusercontent.com/assets/8700743/20807253/074527c0-b7b3-11e6-959f-1f2ad3c107fb.PNG)

**Comment by jheer** [comment]
No, axis labels do not accept names. However, you can still target them directly with CSS, using the name of the parent axis group and the (now included) role information, e.g. "role-axis-label".

So for this: `{"name": "myaxis", scale: "x-scale", ...}`, you could target the labels with the CSS selector `.myaxis .role-axis-label`.

The available axis role classes are: `role-axis-tick`, `role-axis-label`, `role-axis-domain`, `role-axis-grid` and `role-axis-title`.

For legends, the role classes are: `role-legend-entry` (for the group instance containing labels and symbols), `role-legend-gradient` (the color gradient, for gradient legends), `role-legend-label`, `role-legend-symbol` and `role-legend-title`.

**Comment by HartonWong** [comment]
Ic. That totally makes sense! Thanks for your response! :)
