### ISSUE TITLE
Set group width/height signals from encoding

### ISSUE THREAD

**Issue by arvind** [vega/vega#658]
The `splom-inner.vg.json` defines `chartSize`, `chartPad`, and `chartStep` signals to set the dimensions of each cell of the scatterplot matrix, and then calculate the overall visualization's width/height -- a bottom-up layout. Are we still supporting Vega 2's top-down approach to laying out such visualizations? 

In [this spec](https://gist.github.com/arvind/204e567d07441341d2acfc820e1541a3), I have made the following changes:
1. Add `width` and `height` top-level properties.
2. Remove layout-specific signals throughout the spec.
3. Update the cell group's `width` and `height` encoding properties to be set via the `group` scale range bands. 

These changes almost produce the layout I want -- group marks are correctly positioned. However, it seems that the width/height signals for groups aren't set from the encoding. As a result, the inner scale ranges remain set to the overall width/height, and inner axes extend across the entire canvas.

If this is no longer supported, we should identify it as such in the porting guide.

**Comment by jheer** [comment]
Width and height signals are **not** automatically set. They require manual override, and in most ways supersede the role played by group width/height in Vega 2 sub-specs.

**Comment by arvind** [comment]
Got it. Adding the following block achieves this explicitly. Wonder if there's a way to simplify the relationship between the width/height signals and the encoding properties.
 
```json
      "signals": [
        {"name": "width", "update": "bandwidth('groupx')"},
        {"name": "height", "update": "bandwidth('groupy')"}
      ],
```
