### ISSUE TITLE
Datalib methods in expressions

### ISSUE THREAD

**Issue by domoritz** [vega/vega#661]
Vega 2 used datalib but v3 does not anymore. Should we implement missing functions ourselves or will we add datalib back?

**Comment by domoritz** [comment]
If you want to know what expressions are supported right now, look in https://github.com/vega/vega-parser/blob/1ff08867bbc7b9d53074c75b701924cf0aea6c3b/src/parsers/codegen.js#L53 and https://github.com/vega/vega-expression/blob/master/src/functions.js

**Comment by domoritz** [comment]
Here are some expressions that I think are missing
- [ ] quarter
- [ ] number -> string. We need this when we want to truncate but the input is a number. The other option is to always convert numbers to strings before truncating (e.g. https://github.com/vega/vega-util/pull/1)
- [ ] day and month methods from https://github.com/vega/datalib/blob/master/src/format.js#L211

**Comment by jheer** [comment]
- Opened vega/vega-util#2 to add date-time utilities.
- Will add string coercion to truncate method (also at vega/vega-util).
- A `json` method is possible. For this, please file an issue at vega/vega-parser, including more details about the envisioned function signature and behavior.

**Comment by domoritz** [comment]
I filed https://github.com/vega/vega-parser/issues/3 with some ideas for a debug expression.
