### ISSUE TITLE
Add signal to detect static (SVG/PNG) rendering

### ISSUE THREAD

**Issue by nyurik** [vega/vega#677]
Sometimes it is useful to hide some UI elements from the graph when rendering it server side. For example, UI controls are useless in an image, or could be made gray or semitransparent. There should be a signal "isStatic" or similar to detect and handle such cases

**Comment by jheer** [comment]
Thanks! So, if I understand your suggestion correctly, what you are requesting is to add a signal (named `isStatic` or some-such) that automatically is set to `true` when rendering a graph statically (e.g., to generate output SVG or PNG images). Individual specs would be responsible for then changing their appearance in response to this signal.

One problem here is that visual encoding and rendering are completely separate phases. In general, the dataflow has zero notion of how the resulting scenegraph will be used (static rendering, live rendering, perhaps even both!). It is possible to have View-level methods like `toSVG` and `toCanvas` set a signal, re-run the dataflow, re-render, then reset the signal and run the dataflow yet again. In the current version only re-rendering is performed. So, the changes here would expand the codebase (creating an opportunity for the dataflow state to become inconsistent) and introduce some performance overhead. How significant the performance overhead would be of course depends on how many items depend on the `isStatic` signal. All in all, I'm a bit hesitant to go down this route.

On the other hand, making similar changes _only_ to the command-line utilities `vg2png` and `vg2svg` is feasible and doesn't induce the overhead above, as the dataflow here is being used solely for a one-time server-side render and the `isStatic` signal (if defined) can be set externally prior to render:
```
try {
  view.signal('isStatic', true);
} catch (error) { /* The isStatic signal is not defined. */ }
```

But at this point, you could also just fork off your own custom version of these utilities, with whatever other additions (loading,config, etc) you also want to make. So then there is really no need for changes to Vega itself. You just need to write your own server-side script and orchestrate it as you see fit. The only "cost" I see here is different default outputs of standard utilities versus what your custom scripts produce, but that doesn't strike me as a major issue.

So I'm going to close the issue, as this can be resolved independently. If I overlooked something, or if there are additional arguments for why this functionality should be more deeply baked into either Vega or the default utility scripts, let me know!

**Comment by nyurik** [comment]
@jheer, my goal is to have graphs that are useful in both static and dynamic context -- users would see the graph as an image, and could click to activate it, at which point it changes in the dynamic state (loads Vega lib and all the data). In the active state, the graph may choose to show controls.
Jeff, are you saying that it would be very straightforward for us to create another signal on the server side, in addition to the standard ones like width and height, making it seat to design graphs that are useful in both context? I'm a bit worried about compatibility--at this point the only difference we have are the custom data urls. Using a non standard bool signal might throw an error in other environments

**Comment by nyurik** [comment]
P.S. you said graph parsing has no notion of the rendering environment, but aren't width and height signals come from the rendering env too? This way in a mobile context, user may flip a phone, swapping width and height. A good graph should reorient itself accordingly. Same for desktop - resizing browser window.

**Comment by jheer** [comment]
I'm saying it would be trivial to _set_ the value of a signal on the server side prior to rendering. That signal would need to be defined in the specification, and toggling the visibility of any controls would need to be performed by logic included within the specification definition.

Regarding your "p.s." note: In Vega 3, parsing has no notion of rendering environment _whatsoever_, it just parses the Vega JSON and produces a dataflow description. Once instantiated, a dataflow _can_ talk to the browser to configure sizing through provided expression language functions for accessing environment state (see `panzoom.vg.json` for one example). The _renderer_ (distinct from the rendering _environment_, e.g., a browser) is architected with a strong separation of concerns. 

On a related note, Vega's `bind` capability generates HTML input widgets to dynamically modify dataflow signals and thereby implement interactive graphs. These were part of `vega-embed` for Vega 2.x and are now first-class citizens in Vega 3. Vega `View` only generates these widgets in the presence of a DOM element container; they are automatically omitted during server-side rendering. Perhaps this functionality satisfies some of your needs here?

Here is a diagram that illustrates these relationships:
```
              Vega `View` Component
        |--------------------------------|
        |   ------ Signal Bindings----------------
        |   |                            |       |
        |   v                            |       v
Parse -> Dataflow -> Scenegraph -> Render ---> Browser
        |   ^                            |       |
        |   |                            |       |
        |   -- Events / Expression Fns -----------
        |--------------------------------|
```

**Comment by nyurik** [comment]
I might be misunderstanding something - I'm talking purely from the graph designer perspective:  if i use an undefined signal, i get "Error: Unknown signal ...", which means the signal must be set in all environments.
I could define a new signal `"signals": [{"name": "isStatic"}],` in the graph spec, and in the execution environment (either server side or browser) check if the graph has defined that signal, and if it did, set its value. This seems a bit odd, as that creates a weird and unexpected two way coupling between the graph and its env:   declared in graph, set in the environment, used in the graph. Graph developers should assume that whatever is declared in the graph is fully owned/set/modified by the graph.
We could make it so that the environment always creates that signal - similar to the "width" signal - in that case graph simply uses it, just like it uses "width". But unless Vega team make this signal a standard, any graph created for Wikipedia might not be easily portable to other users. Hence my confusion.
