### ISSUE TITLE
[Vega 3] Question about paddingOuter

### ISSUE THREAD

**Issue by kanitw** [vega/vega#679]
By definition, Point scale’s `padding` is equivalent to band scale’s `paddingOuter`.  

However, setting point’s scale `paddingOuter` has no effect although `paddingOuter` is a part of the JSON schema for point scale. 
Wouldn’t it make more sense that it has the same effect as setting `padding`?  

I know that in D3 there is no paddingOuter method for point, but I think users will get confused about that because of the JSON schema.  If we want to be consistent with D3, we should still at least separate the JSON schema for point and band?

**Comment by jheer** [comment]
Good point. I've made multiple updates in response to this (both published):
- vega-scale v1.1.1 now allows point scales to keep to their `paddingOuter` method.
- vega-parser v1.0.0-beta.16 now has separate schema definitions for band and point scales. The `paddingInner` property is no longer valid for point scales. (Note that you will need to rebuild the schema in the vega/vega repo for the changes in vega-parser to propagate forward.)
