### ISSUE TITLE
Vertical axis is generated incorrectly in static context

### ISSUE THREAD

**Issue by nyurik** [vega/vega#680]
This graph's vertical axis is diagonal if ran through vg2png (Vega 2.x)
```
{
  "width": 200, "height": 200,
  "scales": [{ "name": "y", "type": "linear", "rangeMin": {"signal": "height"}, "domain": [0,10] }],
  "axes": [{ "type": "y", "scale": "y" }]
}
```
![v](https://cloud.githubusercontent.com/assets/1641515/21120294/94fab352-c094-11e6-9a4f-486fffcf5c9d.png)

**Comment by jheer** [comment]
Thanks! The first issue I note is that the `range` specification of the scale is incomplete. There is only a `rangeMin` property, so the maximum end point of the range is not being explicitly defined. However, I don't know if that in itself explains why you get a _diagonal_ line here. Also interesting that this occurs only when using `vg2png`, perhaps node-canvas is treating (or failing to treat) undefined values in a manner consistent with HTML5 canvas. I can confirm I see no axis domain line at all when run in the browser. In any case, I strongly recommend using adequately defined scales!

Flagging @arvind given the issue arises with Vega 2.x. Please let me know if this issue occurs in Vega 3 as well.

**Comment by nyurik** [comment]
@jheer, thanks, the main issue is the consistency. Users would expect an identical graph to be drawn in both static and dynamic context, and we need to ensure that, no matter what mistakes they make. Btw, in case of a mistake, we should show an error. Anything without an error is legit))

**Comment by jheer** [comment]
Scheduled this for eventual maintenance on the 2.x branch. Vega 3 does not currently support `rangeMin` and `rangeMax` so the error can not occur there.

**Comment by arvind** [comment]
For the spec provided, as far as I can tell, the scenegraph is being identically generated for the canvas renderer in the browser and `vg2png`. So, the issue appears to lie with how node-canvas processes the `null` value as a result of an underspecified range. I think the best we can do is log an error message in this case, and I'll push a fix shortly to do so.

**Comment by arvind** [comment]
An error message is now logged with b0a784a.
