### ISSUE TITLE
[Vega 3] Sort transform removed?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#681]
It seems like `sort` transform has been removed, but not noted in the PORTING_GUIDE.
From looking at `matrix-reorder` example, I guess that the new "collect" transform can be used, but I'm not really sure.  

It would be great if you could explain this / add this to the PORTING_GUIDE. :)

Thank you!

**Comment by jheer** [comment]
Yes, the Vega 2 sort transform was really a no-op that added a special annotation to the pulse passing through it. Vega 3 drops this behavior. Instead, there are two options for achieving sorting:
- Add a comparator (`sort` parameter) to a collect transform. This ensures that sorting occurs immediately at the point at which it is requested, not at an indeterminate point down stream in the dataflow.
- Use sort directives as part of a scale domain definition.

I added this info to the porting guide in 955cfe7.
