### ISSUE TITLE
Ordinal scale based on an object field only uses first value

### ISSUE THREAD

**Issue by nyurik** [vega/vega#684]
For a complex legend, creating a scale based on a field with object value only works for the very first value, hiding all others. In my code, I actually create the `"x"` object field using a formula transformation out of other fields in that object.
![image](https://cloud.githubusercontent.com/assets/1641515/21255118/db01f752-c337-11e6-995a-e795289e0e8c.png)
```
{
  "version": 2, "width": 100, "height": 200,

  "data": [
    {
      "name": "annotation",
      "values": [
        {"x": {"text":"aa","color":"#991"}},
        {"x": {"text":"bb","color":"#199"}},
        {"x": {"text":"cc","color":"#919"}}
      ]
    }
  ],

  "scales": [
    {
      "name": "legend",
      "type": "ordinal",
      "domain": {"data": "annotation", "field": "x" }
    }
  ],

  "legends": [
    {
      "fill": "legend",
      "title": "Legend",
      "properties": {
        "labels": {"text": {"field": "data.text"} },
        "symbols": {
          "strokeWidth": {"value": 0},
          "shape": {"value": "square"},
          "fill": {"field": "data.color"}
        }
      }
    }
  ]
}
```

**Comment by arvind** [comment]
Yes, this is unsupported behaviour as D3 v3's ordinal scale domain values are [coerced to strings](https://github.com/d3/d3-3.x-api-reference/blob/master/Ordinal-Scales.md#ordinal_domain). You will need to uniquely identify each of your objects, and then pass in a nested field reference (e.g., `x.id`) to the scale domain definition.

**Comment by nyurik** [comment]
@arvind, thanks, is there an example of ordinal scale, where an axes or legend does a lookup into data to customize color and label text?
