### ISSUE TITLE
Document list of all available events like mousemove, touch, ...

### ISSUE THREAD

**Issue by nyurik** [vega/vega#685]
The page https://github.com/vega/vega/wiki/Signals#event-stream-selectors should list all of the available events. At this point it only mentions a few.

Vega in an error message reported this list: "click", "dblclick", "dragenter", "dragleave", "dragover", "keydown", "keypress", "keyup", "mousedown", "mouseenter", "mousemove", "mouseout", "mouseover", "mouseup", "mousewheel", "touchend", "touchmove", "touchstart" or "wheel"

**Comment by jheer** [comment]
The supported event types are now documented at https://vega.github.io/vega/docs/event-streams/
