### ISSUE TITLE
npm run test failed

### ISSUE THREAD

**Issue by lrpina** [vega/vega#686]
Hello!

I can't pass `npm run test` 

I updated node and npm. Right now the test is failing one test.

The following is the error:
`npm ERR! Darwin 15.6.0`
`npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "run" "test"`
`npm ERR! node v7.2.1`
`npm ERR! npm  v4.0.5`
`npm ERR! code ELIFECYCLE`
`npm ERR! vega@3.0.0-beta.10 test: `TZ=America/Los_Angeles tape 'test/**/*-test.js' && eslint index.js src test`

`npm ERR! Exit status 1`
`npm ERR! `
`npm ERR! Failed at the vega@3.0.0-beta.10 test script 'TZ=America/Los_Angeles tape 'test/**/*-test.js' && eslint index.js src test'.`
`npm ERR! Make sure you have the latest version of node.js and npm installed.`
`npm ERR! If you do, this is most likely a problem with the vega package,`
`npm ERR! not with npm itself`.
`npm ERR! Tell the author that this fails on your system:`
`npm ERR!     TZ=America/Los_Angeles tape 'test/**/*-test.js' && eslint index.js src test`
`npm ERR! You can get information on how to open an issue for this project with:`
`npm ERR!     npm bugs vega`

I looked for a `npm-debug.log` file in the `vega` directory but couldn't find it.

Below is the entire output when I run `npm run test`

`> vega@3.0.0-beta.10 pretest /Users/lpina/Repositories/FamilySleep/vega
> npm run build

> vega@3.0.0-beta.10 prebuild /Users/lpina/Repositories/FamilySleep/vega
> rm -rf build && mkdir build && json2module package.json > build/package.js

> vega@3.0.0-beta.10 build /Users/lpina/Repositories/FamilySleep/vega
> bin/rollup && bin/schema > build/vega-schema.json

↳ build/vega.js

> vega@3.0.0-beta.10 postbuild /Users/lpina/Repositories/FamilySleep/vega
> uglifyjs build/vega.js -c -m -o build/vega.min.js

WARN: Dropping unused function areaRingStart [build/vega.js:14681,9]
WARN: Dropping unused function areaRingEnd [build/vega.js:14685,9]
WARN: Dropping unused function areaPointFirst [build/vega.js:14689,9]
WARN: Dropping unused function areaPoint [build/vega.js:14696,9]
WARN: Dropping unused function linePoint [build/vega.js:14789,9]
WARN: Dropping unused function boundsLineStart [build/vega.js:14836,9]
WARN: Dropping unused function boundsLineEnd [build/vega.js:14840,9]
WARN: Dropping unused function boundsRingPoint [build/vega.js:14846,9]
WARN: Dropping unused function boundsRingStart [build/vega.js:14857,9]
WARN: Dropping unused function boundsRingEnd [build/vega.js:14861,9]
WARN: Dropping unused function centroidPoint [build/vega.js:14910,9]
WARN: Dropping unused function centroidPointCartesian [build/vega.js:14916,9]
WARN: Dropping unused function centroidLineStart [build/vega.js:14923,9]
WARN: Dropping unused function centroidLinePointFirst [build/vega.js:14927,9]
WARN: Dropping unused function centroidLinePoint [build/vega.js:14937,9]
WARN: Dropping unused function centroidLineEnd [build/vega.js:14951,9]
WARN: Dropping unused function centroidRingStart [build/vega.js:14957,9]
WARN: Dropping unused function centroidRingEnd [build/vega.js:14961,9]
WARN: Dropping unused function centroidRingPointFirst [build/vega.js:14966,9]
WARN: Dropping unused function centroidRingPoint [build/vega.js:14977,9]
WARN: Dropping unused function lengthLineStart [build/vega.js:15462,9]
WARN: Dropping unused function lengthLineEnd [build/vega.js:15467,9]
WARN: Dropping unused function lengthPointFirst [build/vega.js:15471,9]
WARN: Dropping unused function lengthPoint [build/vega.js:15477,9]
WARN: Side effects in initialization of unused variable proto [build/vega.js:1086,4]
WARN: Side effects in initialization of unused variable csv$1 [build/vega.js:1455,4]
WARN: Side effects in initialization of unused variable tsv [build/vega.js:1457,4]
WARN: Side effects in initialization of unused variable formatIso [build/vega.js:2797,4]
WARN: Side effects in initialization of unused variable parseIso [build/vega.js:2806,4]
WARN: Side effects in initialization of unused variable kx [build/vega.js:3771,4]
WARN: Side effects in initialization of unused variable ky [build/vega.js:3772,4]
WARN: Side effects in initialization of unused variable areaRingSum [build/vega.js:14654,4]
WARN: Side effects in initialization of unused variable areaSum [build/vega.js:14656,4]
WARN: Dropping unused variable lambda00 [build/vega.js:14657,4]
WARN: Dropping unused variable phi00 [build/vega.js:14658,4]
WARN: Dropping unused variable lambda0 [build/vega.js:14659,4]
WARN: Dropping unused variable cosPhi0 [build/vega.js:14660,4]
WARN: Dropping unused variable sinPhi0 [build/vega.js:14661,4]
WARN: Dropping unused variable areaStream [build/vega.js:14662,4]
WARN: Dropping unused variable lambda00$1 [build/vega.js:14754,4]
WARN: Dropping unused variable phi00$1 [build/vega.js:14755,4]
WARN: Side effects in initialization of unused variable deltaSum [build/vega.js:14757,4]
WARN: Dropping unused variable boundsStream [build/vega.js:14760,4]
WARN: Dropping unused variable W0 [build/vega.js:14876,4]
WARN: Dropping unused variable W1 [build/vega.js:14877,4]
WARN: Dropping unused variable X0 [build/vega.js:14878,4]
WARN: Dropping unused variable Y0 [build/vega.js:14879,4]
WARN: Dropping unused variable Z0 [build/vega.js:14880,4]
WARN: Dropping unused variable X1 [build/vega.js:14881,4]
WARN: Dropping unused variable Y1 [build/vega.js:14882,4]
WARN: Dropping unused variable Z1 [build/vega.js:14883,4]
WARN: Dropping unused variable X2 [build/vega.js:14884,4]
WARN: Dropping unused variable Y2 [build/vega.js:14885,4]
WARN: Dropping unused variable Z2 [build/vega.js:14886,4]
WARN: Dropping unused variable lambda00$2 [build/vega.js:14887,4]
WARN: Dropping unused variable phi00$2 [build/vega.js:14888,4]
WARN: Dropping unused variable x0 [build/vega.js:14889,4]
WARN: Dropping unused variable y0 [build/vega.js:14890,4]
WARN: Dropping unused variable z0 [build/vega.js:14891,4]
WARN: Dropping unused variable centroidStream [build/vega.js:14894,4]
WARN: Side effects in initialization of unused variable lengthSum [build/vega.js:15449,4]
WARN: Dropping unused variable lambda0$2 [build/vega.js:15450,4]
WARN: Dropping unused variable sinPhi0$1 [build/vega.js:15451,4]
WARN: Dropping unused variable cosPhi0$1 [build/vega.js:15452,4]
WARN: Dropping unused variable lengthStream [build/vega.js:15453,4]

vega@3.0.0-beta.10 test /Users/lpina/Repositories/FamilySleep/vega
TZ=America/Los_Angeles tape 'test/**/*-test.js' && eslint index.js src test

TAP version 13
# Vega generates scenegraphs for specifications
ok 1 scene: arc
ok 2 scene: area
ok 3 scene: bar
ok 4 scene: bar-hover-label
ok 5 scene: bar-rangestep
ok 6 scene: chart
ok 7 scene: chart-rangestep
ok 8 scene: error
ok 9 scene: falkensee
ok 10 scene: gradient
ok 11 scene: grouped-bar
ok 12 scene: horizon
ok 13 scene: images
ok 14 scene: legends
ok 15 scene: lifelines
ok 16 scene: nested-plot
ok 17 scene: shift-select
ok 18 scene: stacked-area
ok 19 scene: stacked-bar
ok 20 scene: airports
ok 21 scene: barley
ok 22 scene: budget-forecasts
ok 23 scene: choropleth
ok 24 scene: dimpvis
ok 25 scene: density
ok 26 scene: driving
ok 27 scene: force-beeswarm
ok 28 scene: heatmap
ok 29 scene: heatmap-lines
ok 30 scene: histogram
ok 31 scene: force-network
ok 32 scene: jobs
ok 33 scene: map-bind
ok 34 scene: matrix-reorder
ok 35 scene: map
ok 36 scene: overview-detail
not ok 37 scene: movies-sort
  ---
    operator: ok
    expected: true
    actual:   false
  ...
ok 38 scene: panzoom
ok 39 scene: crossfilter
ok 40 scene: parallel-coords
ok 41 scene: crossfilter-multi
ok 42 scene: playfair
ok 43 scene: population
ok 44 scene: scatter-plot
ok 45 scene: splom-inner
ok 46 scene: splom-outer
ok 47 scene: stocks-index
ok 48 scene: violin-plot
ok 49 scene: tree-radial
ok 50 scene: treemap
ok 51 scene: weather
# JSON schema validates correct specifications
ok 52 schema: airports
ok 53 schema: arc
ok 54 schema: area
ok 55 schema: bar
ok 56 schema: bar-hover-label
ok 57 schema: bar-rangestep
ok 58 schema: barley
ok 59 schema: budget-forecasts
ok 60 schema: chart
ok 61 schema: chart-rangestep
ok 62 schema: choropleth
ok 63 schema: crossfilter
ok 64 schema: crossfilter-multi
ok 65 schema: density
ok 66 schema: dimpvis
ok 67 schema: driving
ok 68 schema: error
ok 69 schema: falkensee
ok 70 schema: force-network
ok 71 schema: force-beeswarm
ok 72 schema: gradient
ok 73 schema: grouped-bar
ok 74 schema: heatmap
ok 75 schema: heatmap-lines
ok 76 schema: histogram
ok 77 schema: horizon
ok 78 schema: images
ok 79 schema: jobs
ok 80 schema: legends
ok 81 schema: lifelines
ok 82 schema: map
ok 83 schema: map-bind
ok 84 schema: matrix-reorder
ok 85 schema: movies-sort
ok 86 schema: nested-plot
ok 87 schema: overview-detail
ok 88 schema: panzoom
ok 89 schema: parallel-coords
ok 90 schema: playfair
ok 91 schema: population
ok 92 schema: scatter-plot
ok 93 schema: shift-select
ok 94 schema: splom-inner
ok 95 schema: splom-outer
ok 96 schema: stacked-area
ok 97 schema: stacked-bar
ok 98 schema: stocks-index
ok 99 schema: tree-radial
ok 100 schema: treemap
ok 101 schema: violin-plot
ok 102 schema: weather
ok 103 schema: wordcloud

1..103
# tests 103
# pass  102
# fail  1`

**Comment by jheer** [comment]
Thanks for reporting the error. I'm able to replicate. This is due to recent changes in Vega sub-modules. We will update the tests appropriately and release an updated version soon. In the meantime, it is safe to ignore this test failure.

**Comment by jheer** [comment]
Fixed in the v3.0.0-beta.10 release. Local + Travis CI tests passing.
