### ISSUE TITLE
vega-embedded graph works in MacOS Safari, Firefox, but not Chrome ("vg is not defined")

### ISSUE THREAD

**Issue by jowens** [vega/vega#689]
http://gunrock.github.io/gunrock/doc/latest/md_stats_engines_topc.html . Visible on both MacOS Safari and Firebox, but not Chrome.

Chrome developer tools say `Uncaught ReferenceError: vg is not defined` (lines 2369, 4596), which corresponds to the `vg.embed` call that looks like this:

```
  var embedSpec = {
    mode: "vega-lite",  // Instruct Vega-Embed to use the Vega-Lite compiler
    spec: vlSpec
  };
  // Embed the visualization in the container with id `vis_MTEPS`
  vg.embed("#vis_MTEPS", embedSpec, function(error, result) {
    // Callback receiving the View instance and parsed Vega spec
    // result.view is the View, which resides under the
    // '#vis_MTEPS' element
  });
```

Any wisdom as to what's going on with Chrome here?

**Comment by jowens** [comment]
Further investigation reveals this is ad-blocking extensions in Chrome. Stay tuned to know which one!

**Comment by jowens** [comment]
And the winner is Privacy Badger, which was completely blocking vega.github.io! Congrats, Privacy Badger, you win today's prize! Hopefully this about-to-be-closed issue will be helpful for a future similarly-puzzled person.

**Comment by jheer** [comment]
Thanks for letting us know! Who knew vega.github.io was so nefarious?

**Comment by jowens** [comment]
@jheer good FAQ entry for y'all!
