### ISSUE TITLE
vg2{svg,png} flags a "[Vega Err] Range is underspecified." on an Altair-specified graph

### ISSUE THREAD

**Issue by jowens** [vega/vega#690]
Sorry to burden y'all with my debugging problems. This code worked before but recently decided to flag this warning (so I'm presuming there's something in my data rather than the spec that changed), though the output still looks good. I would be obliged to know what is "wrong" with this JSON such that it generates this warning.

I generated the warning as:

```
$ vl2vg output/engines_topc_elapsed.json > /tmp/foo
$ vg2svg /tmp/foo > /tmp/bar
[Vega Err] Range is underspecified. Please ensure either the "range" property or both "rangeMin" and "rangeMax" are specified.
[Vega Err] Range is underspecified. Please ensure either the "range" property or both "rangeMin" and "rangeMax" are specified.
```

Here is the input JSON (Vega-lite): https://gist.github.com/jowens/fbeb4083193b7e723beb00baaadb3772

FWIW, the Altair description follows. The broader problem (for Altair, I suppose) is that it would be very hard for an Altair user to understand what has happened since Altair users don't specify range at all.

```
    chart[data] = Chart(df).mark_point().encode(
        x=X('dataset:N',
            axis=Axis(
                title='Dataset',
            ),
            ),
        column=Column('algorithm:N',
                      axis=Axis(
                          title='Primitive',
                          orient='top',
                      )
                      ),
        y=Y(data,
            axis=Axis(
                title=caption,
            ),
            scale=Scale(type='log'),
            ),
        shape=Shape('engine',
                    legend=Legend(
                        title='Engine',
                    ),
                    ),
        color=Color('engine',
                    legend=Legend(
                        title='Engine',
                    ),
                    ),
    )
```

**Comment by arvind** [comment]
Hi @jowens, are you using a version of Vega 2.x from our GitHub repo (rather than a released version?). I ask because that error message is something I only recently added to our v2.x branch, and is as yet unreleased. 

Regardless, you helped uncover a bug with what's in our repo -- Vega-Lite emits scales with a range specified via `bandSize` which the error message was not accounting for. This should be fixed with 76e809a. Thanks!

**Comment by jowens** [comment]
```
$ git status
On branch v2.x
Your branch is up-to-date with 'origin/v2.x'.
nothing to commit, working tree clean
```

What do you recommend me using? There is not a proximate reason I'm on a dev branch, so your suggestion appreciated.

**Comment by jowens** [comment]
... getting latest on that branch removed the error though. :)

**Comment by arvind** [comment]
I would use the most recent stable version of Vega (v2.6.3) which is available [via GitHub releases](https://github.com/vega/vega/releases/tag/v2.6.3) or via npm using `npm install vega` (perhaps `npm install vega@2.6.3`, not sure how npm deals with beta releases by default).

**Comment by jowens** [comment]
Is it tractable to do a similar installation with vega-lite?

**Comment by arvind** [comment]
Sorry, I'm not sure exactly what you mean. With Vega-Lite, we similarly recommend using the most recent stable release (v1.3.1) rather than tracking the dev code which is under pretty heavy churn currently as we're working on v2.0. Like Vega, Vega-Lite's stable releases are available [on GitHub](https://github.com/vega/vega-lite/releases) or via `npm install vega-lite`. Hope that helps!

**Comment by jowens** [comment]
I was asking "What should I do for vega-lite" and I'm hearing "npm install vega-lite@1.3.1". Love it! Thanks!

**Comment by jowens** [comment]
OK, sorry to take your time on this any more. When I installed vega, it nicely did so under vega-lite's install. But where does one typically install packages that are used as support packages like vega and vega-lite? (I'm on OS X but surely any Unix-y answer would do.) Like, if you were going to start a brand new install on a brand new machine, where in the file hierarchy would you begin by saying "npm install vega@2.6.3" and "npm install vega-lite@1.3.1"? (I've never dealt with npm in any way shape or form before.)

**Comment by arvind** [comment]
That really depends on your setup and needs -- I'm not too familiar with how Altair needs things set up, unfortunately. `npm install`, by default, puts the modules in a `node_modules` folder in the current working directory. One option is `npm install -g` which installs modules in `/usr/local/lib/node_modules` and are, thus, available globally (including any binaries included as part of the module). So, for example, if you were to `npm install -g vega`, the `vg2png` or `vg2svg` commands should be available for use throughout your system. More information can be found in the [npm documentation](https://docs.npmjs.com/cli/install).

**Comment by jowens** [comment]
OK. I'll play with it. Global install makes sense. Wish my package manager did these for me. Thanks!
