### ISSUE TITLE
Support for d3.time.format.multi?

### ISSUE THREAD

**Issue by ronakrrb** [vega/vega#693]
@arvind  Can we use [d3.time.format.multi](https://github.com/d3/d3-3.x-api-reference/blob/master/Time-Formatting.md#format_multi) specifiers?

**Comment by arvind** [comment]
These format specifiers are not supported in Vega 2, and I do not believe they are supported in Vega 3 either. One could imagine using Vega expressions to define the "predicate" portion of these specifiers. I've tagged this issue as a `feature-request` to help us better track and consider it.

**Comment by ronakrrb** [comment]
@arvind In that case, how can we get the axis to show date changes in case of hours on the axis?
e.g. http://bl.ocks.org/jebeck/9671241

**Comment by jheer** [comment]
Hi @ronakrrb, the short answer is that multi specifiers are not supported by Vega. Moreover, they are not even supported by D3 v4 (which is what Vega 3 uses). Instead, in D3 v4 you need to write your own custom JavaScript function; see the example near the beginning of the [d3-time-format readme](https://github.com/d3/d3-time-format). 

As you probably already know, in Vega 2 we use the built-in multi format if no other format is given. This alternates between months and years as needed (for example), but does not perform abbreviation. Here is an example:
```json
{
  "width": 10,
  "height": 200,
  "data": [
    {
      "name": "dates",
      "format": {"type": "json", "parse": {"date": "date"}},
      "values": [
        {"date": "03/31/2000"},
        {"date": "06/30/2000"},
        {"date": "09/30/2000"},
        {"date": "12/31/2000"},
        {"date": "03/31/2001"}
      ]
    }
  ],
  "scales": [
    {
      "name": "y",
      "type": "time",
      "range": "height",
      "domain": {"data": "dates", "field": "date"},
      "nice": true
    }
  ],
  "axes": [
    {"type": "y", "scale": "y"}
  ]
}
```

Vega 3 similarly uses a built-in multi-format for time, as defined in the [time scale provided by d3-scale](https://github.com/d3/d3-scale/blob/master/src/time.js). One possible solution for Vega 3 is to define a new named scale type and register it using the `vega.scale` method, but that is a bit overkill.

A more portable approach that could work in both Vega 2 and Vega 3 may be to write your own custom expression and use it to "manually" define the `text` encoding field for the axis label. See the [axis documentation](https://github.com/vega/vega/wiki/Axes) for examples of how to override axis properties in Vega 2.

**Comment by fustkilas** [comment]
How are multi specifiers now dealt with in Vega 5.7.2+ ?
