### ISSUE TITLE
SVG or canvas generation error in Headless Mode

### ISSUE THREAD

**Issue by geekplux** [vega/vega#698]
dependencies error occur when generated the SVG or canvas instance in Node project..

when run following code:

```js
const result = vl.compile(spec).spec
vg.parse.spec(result, function (err, chart) {
  var view = chart({ renderer: 'canvas' })
  console.log(view)
})
```

```js
const result = vl.compile(spec).spec
vg.parse.spec(result, function (err, chart) {
  var view = chart({ renderer: 'svg' }).update()
  console.log(view)
})
```

would throw the err:

```
module.js:442
    throw err;
    ^

Error: Cannot find module '../build/Release/canvas'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/geekplux/Dropbox/project/fun/md-vis/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by geekplux** [comment]
my vega version is 2.6.3

**Comment by geekplux** [comment]
any way to convert vega-lite spec to HTML directly?

**Comment by geekplux** [comment]
Happy New Year! 🤗

**Comment by jheer** [comment]
This may be a node-canvas issue. You might try testing the `vg2png` or `vg2svg` utilities directly in the `vega` directory. If you still receive errors, you have an installation problem, most likely with node-canvas. 

For example:
```
./bin/vg2png examples/bar.json > bar.png
./bin/vg2svg examples/bar.json > bar.svg
```

(Note: In order to provide the most helpful feedback, it's also valuable to include information about your setup, including which OS and node versions you are using.)

**Comment by geekplux** [comment]
Thanks your advice! 👻  It's a `node-canvas` installation problem.

Same errors received when I run `vg2svg` directly...Then I checked the `package.json` in `node-canvas` since maybe some node scripts need to run before installed to build release version.

```json
...
  "scripts": {
    "prebenchmark": "node-gyp build",
...
```

and cairo are required. So just follow the guide https://github.com/Automattic/node-canvas/wiki/Installation---OSX to install.

thank idol again! 😄
