### ISSUE TITLE
Calculating polygon centroids

### ISSUE THREAD

**Issue by nyurik** [vega/vega#702]
Another request from a user - something that we already had to touch on, but now there may be many more with the new datasets technology that allows map geojson hosting - given a set of polygons, figure out the centroid positions within them. Seems that #385 had something similar.

**Comment by jheer** [comment]
Please provide more specific details about the envisioned use case. Do you want to be able to compute centroids for arbitrary polygons (like [d3.polygonCentroid](https://github.com/d3/d3-polygon/blob/master/README.md#polygonCentroid))? Or do you want to be able to compute centroids for a projection GeoJSON feature (like [d3.geoPath().centroid](https://github.com/d3/d3-geo/blob/master/README.md#path_centroid))? Or both?

Either might be surfaced in new expression functions.

**Comment by jheer** [comment]
Some developments on this front:
- vega-parser@1441a6fcf499bff70cd4edb7aa4b4f884b546d0d adds `geoArea`, `geoBounds` and `geoCentroid` expression functions. These take a projection name and GeoJSON datum as input. A new `map-area-compare` example (slated for the next Vega release) demonstrates their use.
- vega-parser@f542213df957306ea280fe1a5a4fdb9f4826f47d adds a top-level `expressionFunction` method that can be used to dynamically extend the expression language with new functions **at runtime**. In general we do not recommend using this facility (as it breaks compatibility across different Vega instances), nevertheless this level of extensibility is now available for use in custom deployments.

These additions will be included in the v3.0.0-beta.12 release of Vega 3. I do not anticipate us adding any of these features to Vega 2, which is in maintenance mode (i.e., bug fixes but no new features).
