### ISSUE TITLE
why not `axes.encode.<action>.<item>.<svg-property>` instead of `axes.encode.<item>.<action>.<svg-property>` ?

### ISSUE THREAD

**Issue by g3o2** [vega/vega#704]
For example

```javascript
"axes": [
  {
    "encode": {
      "enter": {
        "domain": { 
          "stroke": { "value": "transparent" } 
        },
        "labels": { 
          "fill": { "value": "transparent" } 
        },
        "ticks" : { 
          "stroke": {"value" : "transparent"}
        },
        "grid": { 
          "stroke": {"value" : "transparent"}
        }
      }
    }
  }
]
```

instead of (currently)

```javascript
"axes": [
  {
    "encode": {
      "domain": { 
        "enter": { 
          "stroke": { "value": "transparent" } 
        } 
      },
      "labels": { 
        "enter": { 
          "fill": { "value": "transparent" } 
        } 
      },
      "ticks" : { 
        "enter": { 
          "stroke": {"value" : "transparent"} 
        } 
      },
      "grid": { 
        "enter": { 
          "stroke": {"value" : "transparent"}
        } 
      }
    }
  }
]
```

The former is slightly less burdensome to write by human hand than the latter, but probably also slightly more burdensome to read by `vega`.

**Comment by jheer** [comment]
Thanks for the suggestion! Burdensome or not, the current scheme is consistent with mark definitions elsewhere. Not only is this "easier" for the parser, more importantly it uses a consistent form of specification for Vega authors and code generators. So, we do not plan to change this, though I certainly understand your reasoning here.

**Comment by g3o2** [comment]
Thank you for the swift reply! I figured it was easier for the machines to parse, which are probably the main target here given the low-level nature of `vega`. I hope you do not mind that I've suggested it nonetheless :-)

**Comment by jheer** [comment]
We love receiving thoughtful suggestions. We just can't adopt all of them :)
