### ISSUE TITLE
npm install throws "pkg-config: command not found"

### ISSUE THREAD

**Issue by moroshko** [vega/vega#710]
Trying to `npm install` vega@3.0.0-beta.14 throws an error:

![screenshot 2017-01-12 16 53 35](https://cloud.githubusercontent.com/assets/259753/21914369/ba4b518c-d8e7-11e6-9c85-e9e7db41498d.png)

Is there anything I should install prior using vega?

**Comment by domoritz** [comment]
You need to install pkg-config and cairo if you want to develop Vega. If you just want to use it, download a precompiled version of Vega.

**Comment by moroshko** [comment]
Thanks a lot for a quick response!

> If you just want to use it, download a precompiled version of Vega.

What's the recommended way to do this? Is it documented?

I just added `vega` to my app's `package.json`, ran `npm install`, and got the error.

Also, is `vega` available as es6 module? I tried to `import vega from 'vega';`, but `vega` is `undefined` then.

**Comment by domoritz** [comment]
Yes, vega is available as an es6 module. We currently don't have the precompiled files in the repo but will with the stable release. For the latest stable release, see https://github.com/vega/vega/tree/v2.x. For vega 3 you currently need to have pkg-config and cairo to build your own vega.

**Comment by moroshko** [comment]
Even though I got the error above, it still downloaded the build files, and actually everything is working as expected (I just did `const vega = require('vega');`). Is it ok to consume vega like that? I really want to stay with vega 3.

**Comment by domoritz** [comment]
Yeah, that the way to use it. I'm glad it's working for you.

**Comment by GCheung55** [comment]
It would be really helpful to `npm install` without the error.

What's using `pkg-config` and `cairo`?
