### ISSUE TITLE
Are we adding `encode.color`? 

### ISSUE THREAD

**Issue by kanitw** [vega/vega#711]
From our slack conversation (below), we discussed about the possibility of adding `color` to Vega's `encode`.  Not sure if we still plan to do this.   It'd be useful to know before we add `fill` and `stroke` to Vega-Lite.  

    Jeffrey Heer [2:33 PM
    Question: should we add a `color` encoding channel to Vega, which is then automatically routed to `fill` or `stroke` depending on the mark type? (The per-mark mapping could be determined via config file.) This could be helpful for theming and possibly for simplifying Vega-Lite if it adds `fill` / `stroke` support. Thoughts?

    Dominik Moritz [2:38 PM] 
    We already use `color` as a configuration option for `fill`/`stroke` in one option. A color channel in vega that automatically routes to `fill`/ `stroke` would simplify the implementation in Vega-Lite. What happens though if the mark supports both `fill` and `stroke`? Would color reroute to both at the same time? Can users override the stroke in that case (`color` + `stroke` means only `fill` would use the `color` property.

    Jeffrey Heer [3:06 PM] 
    Still working this out, but I would think that `color` would route to only *one* of `fill` or `stroke` (configurable per-marktype). Over-specification (say someone defines `stroke`, `fill` and `color`) would result in error or application of precedence rules. This would happen in `vega-parser`, and so would not have any bearing on the runtime dataflow implementation. (edited)

    [3:07]  
    Where (if anywhere) in Vega-Lite do you have `color` target *both* `fill` and `stroke`?

    Kanit Wongsuphasawat [8:40 PM] 
    Nowhere.  In VL 1, it targets either fill or stroke based on config.mark.filled (which has default value based on mark type)
    Technically, filled itself can be an encoding channel (eg encode boolean field with filled / bordered points). Maybe worth considering if it doesnt make the code too complicated.

**Comment by g3o2** [comment]
Not sure if that's a necessity. vega is meant to be lower level than vega-lite. So far, it has employed the jargon of its dependencies such as `d3` and `svg`, which is a great advantage, in particular due to the available resources. `svg2` is on its way, with changes which will probably impact vega, too.

**Comment by jheer** [comment]
Probably not. The one reason I was considering adding a `color` property was to enable expressive theme configurations: by changing the mapping of `color` to one of `fill` or `stroke`, a theme config might include changes such as defaulting to filled or stroked symbols (for example). In any case, a user would have to use the `color` channel -- they would get no added benefit if they stick to `fill` and `stroke` explicitly. I'd also worry that the additional options might lead to some confusion over what to use and when.

In addition, in v3 we already removed the `x` and `y` axis types (only `orient` is used now), so we've already cut off other forms of theme parameterization such as where axes are positioned by default.

So my preference is to keep Vega simpler, more predictable and low-level. One option for Vega-Lite is to "piggyback" on Vega's theme config files. Vega-Lite might use the same JSON format, but extended with additional options that the Vega-Lite compiler would process. The remaining standard options could then be passed down to the Vega parser as usual.

**Comment by kanitw** [comment]
Thank you for explanation.  I think this rationale make sense.  Two questions.

1. Re: Confusion

> I'd also worry that the additional options might lead to some confusion over what to use and when.

I think we'd have the same problem at the Vega-Lite level.  However, I guess the benefit outweighs the con there.  Basically, we need `color` encoding in Vega-Lite to enable rapid transitions between filled and stroked marks, so I don't think we gonna remove `color` from Vega-Lite.  However, without `fill` and `stroke` properties, users cannot customize both.  So we need to add these two properties to Vega-Lite to support further customization.  (If we do not add this, users have to modify the output Vega to do so, which is not ideal for some group of users such as Altair users.)

If you disagree with this, please let me know. 

2) For piggybacking Vega's theme config files, we (probably one of our undergrad members) should certain audit the Vega-Lite and Vega theme.  Could you point out where can we look at the schema for the theme, so we can do the comparison?

**Comment by g3o2** [comment]
I am perfectly comfortable with the `color` property in `vega-lite`, it is definitely more intuitive for a higher grammar and for most situations it works very well.

Regarding the need for `vega-lite` customisation, I wonder if it was useful to create a mark or an encoding channel, creatively so named `vega`, through which any vega-aware `vega-lite` user would be able to "inject" `vega` encoding properties into `vega-lite` specs. This would require of course some knowledge about the underlying `vega` code generated by `vega-lite` but I guess that's what is meant by vega-aware users ;-)

Alternatively, if it is really only about the color related properties, you could stick with `color` as the default choice encoding channel in vega-lite, with overriding `strokeColor` and `fillColor` encoding channels for more customisation. This naming convention will keep `vega` and `vega-lite` interfaces smoothly separate.
