### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by moroshko** [vega/vega#712]
The following spec throws an error:
> Uncaught TypeError: Cannot read property '0' of undefined

```json
{
  "width": 400,
  "height": 100,
  "scales": [
    {
      "name": "x",
      "type": "time",
      "domain": [1484286340567, 1484372740567],
      "range": [0, 400]
    }
  ],
  "axes": [
    {
      "type": "x",
      "scale": "x",
      "ticks": 3
    }
  ]
}
```

If I add `"orient": "bottom"` to the axis, the error disappears.

I'd expect the orientation to default to `"bottom"` for `"type": "x"`.
Is this error expected?

I use vega@3.0.0-beta.14.

**Comment by jheer** [comment]
The `"type"` parameter for axes was removed in v3, as its usefulness is completely subsumed by the `"orient"` property. For this and other changes, be sure to check out the [porting guide](https://github.com/vega/vega/blob/master/PORTING_GUIDE.md).
