### ISSUE TITLE
where is `result.spec` in vega 3 ?

### ISSUE THREAD

**Issue by g3o2** [vega/vega#716]
In Vega 2, one could fetch the parsed specification in `result.spec`, in Vega 3, this seems to be elsewhere, doesn't it ? My use case if printing to the screen the specification as parsed by Vega.

**Comment by jheer** [comment]
I think you are perhaps referring to vega-embed? That library includes `spec` as part of the callback return result. (Note that vega-embed is intended for Vega 2 only, we do not currently plan to use it with Vega 3.)

In the Vega 3 examples, the process looks like this:
```js
var runtime = vega.parse(spec);
var view = new vega.View(runtime);
// set view options, then invoke view.run()
```
The equivalent to `spec` in vega-embed is whatever is being handed as input to `vega.parse`. We do not return the spec elsewhere, so you'll want to capture it as part of the parsing process.

**Comment by g3o2** [comment]
Thank you!
