### ISSUE TITLE
Legend support for more encoding channels (mark properties)

### ISSUE THREAD

**Issue by kanitw** [vega/vega#720]
Currently legends support specifying scale names for `size`, `shape`, `fill`, `stroke` and `opacity`, but not for other marks properties (e.g., fillOpacity, strokeOpacity, strokeWidth, strokeDash, strokeDashOffset, all other text properties, etc.) 

The already supported ones are definitely the most common.  While others are less common,  
we need them to implement other mark properties as encoding channels in Vega-Lite with proper legends support.  (Otherwise, we will have to add them without legends for now.)

**Comment by jheer** [comment]
This makes me a little uneasy. What you are asking for here would both bloat the code and create opportunities for some seriously convoluted legends :)

I'm also not sure all of these need legend support:
- `strokeDash`: Except for hand-coded ordinal scales, no scale instance maps data values to arrays, which is what strokeDash accepts. So this seems to be of questionable fit. The `strokeDashOffset` only makes sense in the context of strokeDash and probably shouldn't be driven by data anyway -- people won't be able to interpret it.
- `fillOpacity` and `strokeOpacity`: Setting multiple opacities in a data-driven encoding seems unlikely to be very informative. The legend already provides an opacity channel so use that. We may also want to prevent (or warn against) multiple opacity encodings.
- Text encodings are more rare. While I can see an argument for them, I think we should push forward without them and introduce if it proves valuable for users.

More generally, I'm a bit skeptical of making **all** of these properties available as data-driven encoding channels. For some we might consider limiting the channels to constant values. Examples include fill/stroke opacity (let global opacity serve as the encoding channel), strokeDash, strokeDashOffset. 

Vega-Lite is not Vega, and blowing up the surface area may cause new problems alongside the new features. For example, how will interactive selections be projected along some of these dimensions? Will API users be confused about the prevalence of similar-seeing options? So I think this needs consensus before becoming the new design.

**Comment by kanitw** [comment]
Sure, I like the proposal to make most of these channels supporting only constant values for now. (It was on my mind a while ago too, but already forgot about it :p) 

That said, `strokeDash` should be useful encoding for black and white printing.  (I remember Michael complained why isn't strokeDash a proper encoding channel.)

> Except for hand-coded ordinal scales, no scale instance maps data values to arrays, which is what strokeDash accepts. 

Like `shape`,  it should support only `ordinal` scale.  

That said, if it's too complicated.  
I'm fine not supporting mapping field to `strokeDash` for 2.0, which sounds like less work for us for now!

**Comment by jheer** [comment]
Keeping most of these as constants for now sounds good, and we can "upgrade" them to full encoding channels in the future as warranted

For `strokeDash` it sounds like a first order of business is to determine a good default palette. In addition to `ordinal` scales, this could be used for `quantize` and `quantile` scales as well. Then I can revisit this request! And sorry for pulling Vega-Lite design discussions into Vega issues... :)

**Comment by jheer** [comment]
Legend support for `"strokeDash"` was included in the `v3.0.0-beta.15` release.
