### ISSUE TITLE
allow `DataRef` for `axes.values` and `legend.values` in addition to `Array`

### ISSUE THREAD

**Issue by g3o2** [vega/vega#723]
For now, those properties are limited to `Array`, which does not allow any prior data or scale transformation. In addition, `Array` requires hardcoding (i.e. without resorting to external JavaScript), where as `DataRef` would make a specification more parametrisable.

**Comment by jheer** [comment]
FWIW, this can be achieved (in a roundabout way) by creating a separate scale and using that to drive values. For example:
```json
"legends": [
  {
    "fill": "normalScale",
    "values": {"signal": "domain('specialScale')"}
  }
]
```
I don't know if the use case here is of sufficient priority to warrant the changes to the parser and JSON schema that a direct data ref would cause. In addition, the semantics of a data ref are dependent on the scale type (e.g., linear and ordinal scales generate different outputs for the same data ref). So it's not entirely clear what the semantics should be for a direct data ref for axes or legends.

Given these questions and the fact that this is expressible via other means, I'm going to close the issue for now. Thanks for the suggestion!

**Comment by g3o2** [comment]
Hmm, maybe I've misunderstood the concept of data ref: a reference to a data set (itself specified under `data`) instead of a hard-coded array, right ?

A hard-coded values array for axis or legend does have the major drawback that, if the data change, one has to adapt the said array each time. The same applies if one changes the scale type. But I may have misunderstand the key concept, in which case I should revisit my use of terminology in #634.

Thanks for your feedback!
