### ISSUE TITLE
NPM package uses outdated vega-loader

### ISSUE THREAD

**Issue by domoritz** [vega/vega#729]
Downloading the vega package from https://registry.npmjs.org/vega/-/vega-3.0.0-beta.18.tgz and looking at vega.js, we can see that

```js
function fs() {
  return typeof require === 'function' && require('fs');
}
```

But it should be (https://github.com/vega/vega-loader/blob/master/src/loader.js#L158)

```js
function fs() {
  var fs = typeof require === 'function' && require('fs');
  return fs && isFunction(fs.readFile) ? fs : null;
}
```

**Comment by jheer** [comment]
Fixed in 69e35f9. Correct vega-loader version will be included in the next release.
