### ISSUE TITLE
[FR] Can we have a gitter room or slack channel for Vega?

### ISSUE THREAD

**Issue by QuantumInformation** [vega/vega#740]
Would love to see users being able to collab and discuss this lib.

**Comment by jheer** [comment]
Great question. We do have a Vega slack channel set up, but have not (yet) made public announcements for others to join. Coming soon...

**Comment by jfsiii** [comment]
Until then, there is a [vega channel](https://d3js.slack.com/archives/vega) in [the D3 slack](https://d3js.slack.com/) ([invites here](https://d3-slackin.herokuapp.com/))

**Comment by QuantumInformation** [comment]
I actually prefer discord now, it takes 3 secs to setup and it rules!

**Comment by kanitw** [comment]
Just found that this issue isn't closed.   FYI, we do have a Vega slack http://bit.ly/vega-slack.
