### ISSUE TITLE
SVG and Canvas modes: 

### ISSUE THREAD

**Issue by marianess** [vega/vega#743]
If a plot has padding defined manually the plot would not be displayed in Canvas mode, but only in SVG mode. However, if padding is strict or auto the plot will be displayed in both modes.
It looks like user cannot set padding manually in Canvas mode.

**Comment by jheer** [comment]
I'm unable to replicate any padding issues in either rendering mode. If you are still seeing errors, please file a new issue along with a specification that demonstrates the problem.
