### ISSUE TITLE
Binding data to axis labels [Feature Request]

### ISSUE THREAD

**Issue by HartonWong** [vega/vega#744]
From the Vega Documentation, it stated this 
Each element can be styled using standard Vega Value References, as described in the Marks documentation.

And yet we can bind data to Vega.Mark, but not to individual axis labels. It will be really nice, if we can bind data to axis labels created by Vega, such that when we hover to each of the axis labels, we can have access to certain data binded to the axis labels.

**Comment by g3o2** [comment]
As an alternative, you can already render the axis labels as text marks ;)

**Comment by jheer** [comment]
You can not bind _custom_ data elements to axis labels. However, Vega does generate backing data objects for axis and legend items that you can reference in custom encoding statements. You can also use the `values` specification property to control what values are used in an [axis](https://vega.github.io/vega/docs/axes/) or [legend](https://vega.github.io/vega/docs/legends/).

For more (Vega 3.0+), see the following operators defined in [vega-encode](https://github.com/vega/vega-encode):
- [AxisTicks](https://github.com/vega/vega-encode/blob/master/src/AxisTicks.js) - Generates objects of the form `{value: v, label: l}`
- [LegendEntries](https://github.com/vega/vega-encode/blob/master/src/LegendEntries.js) - Generates objects of the form `{index: i, value: v, label: l}`.

Finally, you can always generate your own [text mark](https://vega.github.io/vega/docs/marks/text/) instances for more customized behavior.
