### ISSUE TITLE
Can't format axis

### ISSUE THREAD

**Issue by NeelMohapatra** [vega/vega#745]
We were working on this issue https://github.com/vega/vega-lite/issues/1763 and it seems that vega is unable to format the axis properly. This is the spec we used:
```json
{
  "$schema": "http://vega.github.io/schema/vega/v3.0.json",
  "signals": [
    {"name": "width","update": "data('layout')[0].width"},
    {"name": "height","update": "data('layout')[0].height"},
    {"name": "unit","value": {}}
  ],
  "data": [
    {
      "name": "source",
      "values": [{"a": "A","b": 28.2}],
      "format": {"type": "json","parse": {}},
      "transform": []
    },
    {
      "name": "layout",
      "source": "source",
      "transform": [
        {
          "type": "aggregate",
          "fields": ["b"],
          "ops": ["distinct"]
        }
      ]
    }
  ],
  "marks": [
    {
      "name": "main",
      "type": "group",
      "from": {"data": "layout"},
      "scales": [
        {
          "name": "y",
          "type": "point",
          "domain": {"data": "source","field": "b","sort": true},
          "range": {"step": 21},
          "round": true,
          "padding": 0.5
        }
      ],
      "axes": [
        {
          "scale": "y",
          "orient": "left",
          "format": "d",
          "title": "b"
        }
      ]
    }
  ]
}
```
And the output we got:
![screen shot 2017-02-21 at 6 09 52 pm](https://cloud.githubusercontent.com/assets/12771661/23194087/fd69c05a-f860-11e6-9776-52c2d744693f.png)

**Comment by jheer** [comment]
This is actually by design. You are using a point scale, which assumes an ordinal (not numeric) domain, and so the true domain value should be shown. The format property is used with either numeric (linear, log, pow, etc) or date-time (time) scales -- but not ordinal / band / point scales.

If you think this design decision is in error, feel free to open another issue with a proposal of how the axis tick logic should be updated. For example, how should an ordinal scale know whether the format specifier is a numeric format or date-time format?

**Comment by jowens** [comment]
I am presuming that ordinal is my only choice here; it doesn't seem like any other kind of scale does what I need. Discrete-but-orderable-numeric would seem like my ideal fit.

**Comment by kanitw** [comment]
@jheer Quick question -- If I remember correclty,  we used to have `formatType` in Vega 2.  
Wouldn't that make it possible to do formatting for ordinal scale like in this case?

**Comment by g3o2** [comment]
The `formula` transform in vega and the `calculate` transform in vega-lite allow both to derive a new formatted string variable from an existing numeric one using the `format()` function, which can then be used for the guides. In what way(s) would this solution not satisfy the use case at hand ?

As @jheer has mentioned, the current design is consistent with the [d3-scale](https://github.com/d3/d3-scale#ordinal-scales) documentation:

> [...] an ordinal scale’s values must be coercible to a string, and the stringified version of the domain value uniquely identifies the corresponding range value. [...]

> [...] a point scale’s values must be coercible to a string, and the stringified version of the domain value uniquely identifies the corresponding point. [...]

**Comment by domoritz** [comment]
Formatting the data in a transform has the disadvantage that different values with the same formatted string fall into the same bucket when we aggregate. For example, 1.2 and 1.2 when formatted with `d` are `1`. This may be the desired behavior but I also think it is very off if changing the formatting also changes the aggregation.

**Comment by jheer** [comment]
I believe we've resolved this issue? If not, please re-open along with comments for what remains to be done on the Vega side.
