### ISSUE TITLE
Wrong Bound for horizontal axis labels

### ISSUE THREAD

**Issue by HartonWong** [vega/vega#746]
If I create a signal like follows:
`    {
      "name": "LabelTooltip",
      "init": {"data": {}},
      "streams": [
        {
          "type": "text:mouseover",
          "expr": "{event:eventItem().bounds,data:datum,x1:eventItem().bounds.x1,y2:eventItem().bounds.y2,xHalf:(eventItem().bounds.x2+eventItem().bounds.x1)/2,yHalf:eventItem().bounds.y2+22/2}"
        },
        {"type": "text:mouseout","expr": "{data:{}}"}
      ]
    },`
And hover to vega created horizontal axis labels, y1 and y2 will be somewhere on the top, instead of showing the y-coordinate of the targeted element.
![capture](https://cloud.githubusercontent.com/assets/8700743/23236292/853f0790-f90d-11e6-985e-f55a9ee886b3.PNG)

**Comment by jheer** [comment]
Mark bounds are relative to the coordinates of their parent group marks. To get the final bounds, one must translate the coordinates by adding the (x, y) values for all parent mark groups, up to the root. Internally, Vega scenegraph performs this translation for routing input events and other calculations.

Does this clear up the confusion?

**Comment by HartonWong** [comment]
I see. I actually also figure this out after reading more of the Vega source code. Thanks for the clarification!
