### ISSUE TITLE
fillOpacity on legend?

### ISSUE THREAD

**Issue by Fil** [vega/vega#751]
I'm trying to add a legend to spec/population.vg.json

But I wasn't able to add the same fillOpacity as in the marks, and ideally I would also like not to have to specify the color range twice.

Here's my code so far (note also that I change the colors from pink/blue to a less offensive orange/green).

```
diff --git a/spec/population.vg.json b/spec/population.vg.json
index 3c405ac..beab94f 100644
--- a/spec/population.vg.json
+++ b/spec/population.vg.json
@@ -58,7 +58,13 @@
       "name": "c",
       "type": "ordinal",
       "domain": [1, 2],
-      "range": ["#1f77b4", "#e377c2"]
+      "range": ["#1ba66e", "#d86c44"]
+    },
+    {
+      "name": "ctext",
+      "type": "ordinal",
+      "domain": ["Male", "Female"],
+      "range": ["#1ba66e", "#d86c44"]
     }
   ],

@@ -117,6 +123,13 @@
             }
           }
         }
+      ],
+
+      "legends": [
+          {
+              "fill": "ctext",
+              "title": "Sex"
+          }
       ]
     },
     {
@@ -153,7 +166,6 @@
               "x2": {"scale": "x", "value": 0},
               "y": {"scale": "y", "field": "age"},
               "height": {"scale": "y", "band": 1, "offset": -1},
-              "fillOpacity": {"value": 0.6},
               "fill": {"scale": "c", "field": "sex"}
             }
           }
```

**Comment by jheer** [comment]
Sorry, it is not clear to me from your description what precisely you are trying to achieve.

1. If you have a scale transform that sets the opacity, you can include that in a legend using `"opacity": "scaleName"` in your legend definition.
2. If you want to set legend items to a constant opacity, you can customize the encodings. For example, you might include `"encode": {"symbols": {"update": {"fillOpacity": {"value": 0.6}}}}` in your legend definition.

I hope that helps.

**Comment by Fil** [comment]
I was trying to add a legend that would use the same fillOpacity as the graph, didn't know where to put the call in the legend. Your comment solves it, either on update or on enter:
`"encode": {"symbols": {"enter": {"fillOpacity": {"value": 0.6}}}}`

Here's the updated file, would you like a PR?
