### ISSUE TITLE
IE11 Error: Object doesn't support property or method 'remove' (cf. this._svg.remove() in vega.js)

### ISSUE THREAD

**Issue by yorickp** [vega/vega#753]
vega.js version: 3.0.0-beta.22

Not sure yet what triggered this internal vega.js function, but I guess that might not really matter.
I get a fatal error in IE11 (works fine in Edge, Chrome and FF) triggered by the following line of code in the vega.js library:

(lines 7472-7473)
```
// otherwise remove from DOM
item._svg.remove();
```

Error thrown in IE11:

> object doesn't support property or method 'remove'

this._svg seems to be a SVGLineElement in my case, but I assume that doesn't really matter within the scope of this error.

When I comment out that line in the library, all works fine, but that's not an ideal solution of course. Could this be a bug in the vega library? And if so, what could be the fix?

Thanks in advance!

**Comment by jheer** [comment]
Thanks for the bug report! IE does not support `node.remove()`, so I reverted vega-scenegraph to instead call `node.parentNode.removeChild(node)` and published a new version. If you upgrade `vega-scenegraph` in your node modules the error should be fixed.

**Comment by yorickp** [comment]
Hi Jeffrey,

I upgraded the module and I can confirm it fixes the bug.
Thanks for the swift version update, and the great work!
