### ISSUE TITLE
Cannot format legend

### ISSUE THREAD

**Issue by domoritz** [vega/vega#754]
I am trying to format the labels in my legend but nothing changes. It works when I set `"type": "gradient"`, though. 

```json
{
  "$schema": "http://vega.github.io/schema/vega/v3.0.json",
  "autosize": {"type": "pad","resize": true},
  "data": [
    {
      "name": "source",
      "values": [
        {"a": "A","b": 28},
        {"a": "B","b": 55},
        {"a": "C","b": 43},
        {"a": "D","b": 91},
        {"a": "E","b": 81},
        {"a": "F","b": 53},
        {"a": "G","b": 19},
        {"a": "H","b": 87},
        {"a": "I","b": 52}
      ]
    }
  ],
  "scales": [
    {
      "name": "color",
      "type": "sequential",
      "domain": {"data": "source","field": "b"},
      "range": "ramp",
      "nice": false,
      "zero": false
    }
  ],
  "legends": [{"stroke": "color", "format": ".2f","title": "b"}]
}
```

<img width="59" alt="screen shot 2017-03-05 at 21 51 03" src="https://cloud.githubusercontent.com/assets/589034/23598222/dc46b68a-01ed-11e7-9cca-b0ee95f7f654.png">

**Comment by jheer** [comment]
Works for me. Have you upgraded your modules (most notable vega-encode)?

**Comment by domoritz** [comment]
🚪 🚶 

<img width="75" alt="screen shot 2017-03-06 at 10 55 04" src="https://cloud.githubusercontent.com/assets/589034/23624664/6049bf78-025b-11e7-9feb-fce8b68b8a7e.png">
