### ISSUE TITLE
Responsive charts based on container size

### ISSUE THREAD

**Issue by GCheung55** [vega/vega#755]
This is a Vega 3 feature request: Provide a way to resize the graph based on the container's height/width.

With a combination of the window resize event and `windowSize` expression, there's a way to resize the graph based on the window's dimensions but not the container.

I've been told a workaround is to update the view instance with the containers height/width on window resize.

Example:

```javascript
$(window).on('resize', function() {
    // assume I have an element and viewInstance variables representing
    // the container, and vega View instance, respectively. 
    const $element = $(element)
    const width = $element.width();
    const height = $element.height();
    viewInstance.width(width).height(height).run();
});
```

Perhaps there is an easier and more elegant way to do this within Vega?

**Comment by jheer** [comment]
To the best of my knowledge, per-element resize tracking is not (yet) standard across browsers. (I believe Chrome has a ResizeObserver behind an experimental flag?)

So, it seems the request here is to be able to access the container size in response to a window resize event? If so, the existing functionality (as demonstrated in [panzoom.vg.json](https://github.com/vega/vega/blob/master/test/specs-valid/panzoom.vg.json)) should work, if augmented with a `containerSize` expression function akin to the `windowSize` function.

Would this work for you?

**Comment by jheer** [comment]
I've gone ahead and added a `containerSize` expression function which returns `[el.clientWidth, el.clientHeight]` if the container element `el` exists. It has been released in vega-parser v1.1.0, and will be included in the next Vega release.

**Comment by Casyfill** [comment]
Hey @jheer,
is it possible to bound `width` and `heigth` of the chart to `containerSize`? So far I wasn't able to,
had to bound axes directly (as in panzoom example), but this won't help if I add legends/axes

**Comment by GCheung55** [comment]
@jheer thanks for adding this. Using `containerSize` with `autosize:fit` Causes a weird issue with axes that I’m I still investigating. I [posted in the Vega slack channel](https://vega-js.slack.com/archives/C4RM5HFV1/p1522275367000052), but here’s a copy/paste of the issue:

> I”m having some trouble with having a responsive visualization with `width` and `height` signals derived from `containerSize` expression. I want to have the visualization use `autosize:fit` so that the width and height are exact. I’ve put together a gist, where I’m using hardcoded values in the `width` and `height` signals for the purpose of testing. The Vega editor doesn’t allow for responsive width/height. The main issue is that the x-axis is clipped. What should I do to get the x-axis to be included within the hight of the chart? https://vega.github.io/editor/#/gist/vega/gcheung55/1794eb9447be6b16ecd5083763724f56/50cf15a6081b424057e929e4675e98505eb16aed/bar.json

>Looks like the y-axis is also pushing the bars some, so the furthest bar on the right looks cropped.

**Comment by TheoAbiel** [comment]
Hi  @jheer,

I am new to Vega. Could you please give me some guidance on how to use `containerSize`? Or is in the documentation some information regarding this?

**Comment by TheoAbiel** [comment]
Thank you very much @jheer ! :smiley:

**Comment by brylie** [comment]
@jheer Is there an example of how to create a responsive Vega (Lite) chart? From what I can find, most of the examples have hard-coded width and height. We are designing for tablet and phone devices, which can be turned from portrait to landscape, so would like the chart size to update dynamically.

**Comment by domoritz** [comment]
For Vega-Lite, we have https://vega.github.io/vega-lite/docs/size.html#autosize. Some of the instructions also apply to pure Vega.

**Comment by brylie** [comment]
Perhaps there are one or more divs in the Vega Editor that are constraining the width of the autosize example?

**Comment by domoritz** [comment]
By responsive we mean that the chart exactly fits into the specified with and height. If you want to fill a container, you need to set the width and height through the view API or in pure Vega through the container size signal.

**Comment by dgwyer** [comment]
@domoritz I'm trying to do the same thing as @brylie. Would it be possible to see a working example of the chart filling the container and responding to a (window) resize event?

**Comment by brylie** [comment]
If possible, the charts should be responsive automatically (see: Plot.ly). Wiring up screen resize events to chart dimensions should be abstracted by the library, unless specifically needing to be overridden. Just my two cents.

**Comment by domoritz** [comment]
This is a good goal but we have to carefully design this. I think Vega shouldn't do it but it could be a goal for Vega-Lite. One tricky bit is that sizing composed charts is not easy. Other libraries don't support composition and so never run into this issue.

**Comment by Casyfill** [comment]
@brylie here is our (definitely imperfect) solution, with width/height listener outside (in `main.js`). in this case, only the width was made responsive purposefully - but it is trivial to add height as well.

[example](https://streeteasy-market-data-api.s3.amazonaws.com/vis/v3.1/index.html?data=night_shift/specs.vg.json)

with that being said, indeed It would be great to have this automated one way or another - for example, if vegaEmbed or vega itself would expose `globalWidth` and `globalHeight` signals

**Comment by purpledrgn** [comment]
For anyone interested, you can do it like this. Also useful for any sort of other SVG.

```js
import React from 'react';
import VegaLite from 'react-vega-lite';
import ContainerDimensions from 'react-container-dimensions';

export function Example(props) {

	const spec = {
		"description": "A simple bar chart with embedded data.",
		"mark": "bar",
		"width": 800,
		"autosize": {
			"type": "fit",
			"contains": "padding"
		},
		"encoding": {
			"x": {"field": "a", "type": "ordinal"},
			"y": {"field": "b", "type": "quantitative"}
		}
	};

	const barData = {
		"values": [
			{"a": "A","b": 20}, {"a": "B","b": 34}, {"a": "C","b": 55},
			{"a": "D","b": 19}, {"a": "E","b": 40}, {"a": "F","b": 34},
			{"a": "G","b": 91}, {"a": "H","b": 78}, {"a": "I","b": 25}
		]
	};

	return (
		<ContainerDimensions>
			{ ({ width, height }) => {
				spec.width = width;
				return <VegaLite spec={spec} data={barData} />
			}}
		</ContainerDimensions>
	);
}
```

**Comment by dantman** [comment]
[ResizeObserver](https://caniuse.com/#feat=resizeobserver) is now supported in the latest version of every browser and has pretty decent support. And there are polyfills to optionally support other browsers if more than progressive enhancement is desired.

It would be great if we didn't have to fake a window resize event in order to get a Vega chart's size to update when it's container's size changes.
