### ISSUE TITLE
Signals that use sliders do not seem to work in IE11

### ISSUE THREAD

**Issue by entmike** [vega/vega#756]
Hello all, I hope this isn't a duplicate issue, but I couldn't find one when searching...  I noticed today that while I am usually in Chrome, I'm required to make something also work in IE11 if I hope to leverage Vega...  It seems that sliders do not work in IE11.  Take this example:

https://vega.github.io/vega-editor/?mode=vega&spec=airports-params&renderer=svg

The radio buttons work, however the sliders do nothing, but work fine in Chrome.

Is this a known limitation, and is there a workaround?

**Comment by jheer** [comment]
Thanks for reporting the issue! Vega v3.0.0-beta.27 includes updates to process slider events correctly: unlink other browsers, which fire an `input` event upon intermediate slider changes, IE uses the `change` event. Vega now handles both cases.

In addition, IE does not include the Promise object, which Vega uses for data loading and other asynchronous tasks. I've updated the Usage documentation to note the need for a polyfill (which the documentation site itself now includes).
