### ISSUE TITLE
vega website should react more proactively to incompatible or older browsers 

### ISSUE THREAD

**Issue by g3o2** [vega/vega#759]
Some browsers (e.g. IE11 mobile) do not appear to work with the revised Vega website, at least not with the example pages - examples are simply not rendered. Amazingly, IE11 mobile works with the Vega editor website.

While one may or may not investigate such compatibility issues, it would in any case be more elegant if the website reacted proactively to incompatible browsers. Here are a few ideas:

- show an alternative text notifying the user and provide a non-interactive rasterised version of the example;
- try canvas mode instead of svg, or provide a button which allows to switch between canvas and svg rendering modes.

**Comment by domoritz** [comment]
IE11 on desktop seems to work fine. Do you have any recommendations for how we would be able to test IE11 mobile? 

<img width="1049" alt="screen shot 2017-03-11 at 10 17 40" src="https://cloud.githubusercontent.com/assets/589034/23825738/103fffbe-0644-11e7-89d5-afe2f68cfc91.png">

**Comment by g3o2** [comment]
You mean in terms of [user agent string](https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx) ?

**Comment by GCheung55** [comment]
I think @domoritz meant if you had any recommendations on how to test against an actual IE11 mobile browser.

**Comment by g3o2** [comment]
While I can open and see an example page such as the bar chart in IE11 desktop, I can't say the same of the force or the tree layouts.

**Comment by jheer** [comment]
There were a number of outstanding issues with IE11 desktop: broken range slider event handling (#756), lack of Promise support (IE requires a polyfill), and some site CSS issues. Vega v3.0.0-beta.27 addresses these issues and appropriately updates the documentation. Please feel free to file new issues (or re-open this one) if additional compatibility problems are found.

In case it proves helpful to anyone else, to test IE compatibility I used a free virtual machine available from [modern.ie](http://modern.ie).
