### ISSUE TITLE
[vega docs] broken links in tutorials

### ISSUE THREAD

**Issue by g3o2** [vega/vega#764]
* [Mapping Airport Connections](https://vega.github.io/vega/tutorials/airports/): 
    + [broken link to maps and other data sets](https://vega.github.io/vega/tutorials/static/data/us-10m.json);
    + The update rules are defined as a set of handlers for input events that update the signal value. To learn more about expressions, see the [expression language documentation](https://vega.github.io/vega/tutorials/docs/expressions).

* [let's make a bar chart](https://vega.github.io/vega/tutorials/bar-chart/):
    + [View Source](https://vega.github.io/vega/tutorials/bar-chart.vg.json);
    + "Data sets in Vega can be modified using a collection of [transforms](https://vega.github.io/vega/docs/transform) such as filtering, aggregation and layout operations";
    + and other links to transforms;

**Comment by jheer** [comment]
Thank you! This is very useful feedback. All links should be fixed now.

**Comment by g3o2** [comment]
I've checked the links and they now work, on the vega website that is - obviously not the broken ones here above :-)
