### ISSUE TITLE
vg2svg and image mark does not seem to work

### ISSUE THREAD

**Issue by pgp44** [vega/vega#774]
Hello

I am trying to use vg2svg with the provided image test file (specs-valid/images.vg.json). The rendered svg however has an empty href for the images.

It looks like the issue is triggered by 

```
var Image$1 = typeof Image !== 'undefined' ? Image
  : (Canvas && Canvas.Image || null);

```
In case of the nodejs environment 'typeof Image' does return 'undefined' and later one it then fails on 

`      if (!url || !Image$1) throw 'Image unsupported.';
`

Any suggestions for a possible workaround?

Tx!

Peter

**Comment by jheer** [comment]
Thanks for filing the issue. This has been fixed in vega-scenegraph 2.0.1 and will be included in the next Vega release.
