### ISSUE TITLE
there exist something as encode: select?

### ISSUE THREAD

**Issue by mattijn** [vega/vega#777]
For example in the chloropeth map: https://vega.github.io/new-editor/#/examples/vega/choropleth

Now I've options in the `marks>encode` for `enter`, `update` and `hover`, but is there something in existence that relates to `select`, which triggers once a feature (e.g. state) is selected by a click/touch event?

**Comment by jheer** [comment]
Yes you can do this, but the click/touch handler is not built in: you need to add it within a signal definition. For example, add the following to the choropleth example:

```json
  "signals": [
    {
      "name": "click",
      "on": [
        {"events": "shape:mousedown", "encode": "select"},
        {"events": "shape:mouseup",   "encode": "update"}
      ]
    }
  ],
```
This adds a handler that invokes an encoding block named `"select"` when a mark is clicked, and invokes `"update"` when the mouse is released. Now you just need to define the `"select"` block for the county `shape` marks:

```json
"select": {
  "fill": { "value": "green" }
},
```
Other custom arrangements are possible by controlling which encode blocks are invoked in response to which events. Other than enter/exit/update/hover, the encode block names are arbitrary (they have no special meaning to Vega).

**Comment by mattijn** [comment]
Thanks for the explanation, even more flexible than I realized
