### ISSUE TITLE
Advanced text layout control using foreignObject elements

### ISSUE THREAD

**Issue by mprudhom** [vega/vega#78]
Formatting options for lengthy text labels (e.g., for data mark callouts, annotations, legends, and axes) is important for the polish and readability of any chart. Neither SVG nor Canvas provide important text formatting capabilities like line wrapping, hyphenation, full text justification, or ellipsis truncation. However, these abilities could be supported by generating an SVG "foreignObject" element and embedding it into the SVG.

For example, take this axis definition that wants to automatically wrap, hyphenate, and truncate long axis labels:

```javascript
  "axes": [
    {
        "type": "x",
        "scale": "x",
        "properties": {
          "labels": {
            "text": {"scale": "xlabels"},
            "fill": {"value": "steelblue"},
            "angle": {"value": 50},
            "fontSize": {"value": 14},
            "align": {"value": "left"},
            "baseline": {"value": "middle"},
            "dx": {"value": 3},
            "wrap": { "value": true },
            "justification": { "value": "full" },
            "hyphenation": { "value": "auto" },
            "overflow": { "value": "ellipsis" }
          }
        }
    }
]
```

The SVG that is currently output is:

```html
<text x="233.5" y="9" dy=".35em" text-anchor="start" transform="rotate(50 230.5,9)" style="font-style: normal; font-variant: normal; font-weight: normal; font-size: 14px; line-height: normal; font-family: sans-serif; fill: #4682b4; opacity: 1; ">
  This is some very long text we would ideally like to wrap 
</text>
```

However, we could extend this to optionally include the wrapping options by instead outputting a foreignObject div with an optional fallback to the plain SVG text elements for unsupported rendering environments (using the "switch" technique described at: http://stackoverflow.com/a/6944892/228600).

```html
<switch>
  <foreignObject width="300" height="300" requiredExtensions="http://www.w3.org/1999/xhtml">
    <body xmlns="http://www.w3.org/1999/xhtml ">
      <div style="width: 300px; height: 300px; font-size: 22px; background-color: white; text-align: justify; hyphens: auto; -webkit-hyphens: auto; text-overflow: ellipsis; overflow: hidden; ">
        This is some very long text we would ideally like to wrap
      </div>
    </body>
  </foreignObject>
  <text x="233.5" y="9" dy=".35em" text-anchor="start" transform="rotate(50 230.5,9)" style="font-style: normal; font-variant: normal; font-weight: normal; font-size: 14px; line-height: normal; font-family: sans-serif; fill: #4682b4; opacity: 1; ">
    This is some very long text we would ideally like to wrap
  </text>
</switch>
```

This will render the hyphenation, ellipses, and justification in rendering environments that support it (e.g., a web browser) and will fall back to the SVG text in environments that don't (e.g., node.js, some SVG image editors, etc.). The foreignElement could be generated whenever a text attribute is seen that is not supported by pure SVG.

This obviously only applies to drawing text with SVG, however it could also be made to work with the canvas renderer by creating the SVG text elements and having canvas draw it as an image, using the technique described at http://robert.ocallahan.org/2011/11/drawing-dom-content-to-canvas.html and https://developer.mozilla.org/en-US/docs/HTML/Canvas/Drawing_DOM_objects_into_a_canvas (although there would certainly be some performance hit for visualizations with many text elements).

**Comment by arvind** [comment]
I'm closing this because `foreignObject` is an SVG-specific feature, and would break Vega's abstraction model (supporting multiple renderers across the browser and server side). Supporting multi-line text, and other text layout options, is indeed an ongoing and important issue. Please open a new issue if you've got ideas for how we can support that within the Vega world :)
