### ISSUE TITLE
voronoi diagrams only drawn vertical with too few partitions

### ISSUE THREAD

**Issue by mattijn** [vega/vega#783]
I'm trying to draw a line + point chart, including voronoi diagrams to select the nearest point to the mouse cursor.

But the voronoi diagrams are only drawn vertical, while dividing the data in ony 3 partitions. I'm confused by this behaviour, is this intended?
![voronoi](https://cloud.githubusercontent.com/assets/5186265/25308317/8faf39fc-27b1-11e7-8cb1-297c74f62e8a.PNG)

My vega3 editor specs are here: https://vega.github.io/new-editor/#/gist/vega/mattijn/99c679c6e3729354adefc082c4205bc6

**Comment by Fil** [comment]
I think the issue is that the voronoi is computed on the original values, and on the [0,0,width,height] extent. And almost all original (non scaled) values are outside this extent, except for the 3 first (hence the 3 voronoi cells).

I wish I knew how to fix it.

**Comment by jheer** [comment]
You want the Voronoi to be computed _after_ the scale projection is performed to determine the actual and x and y values. This can be achieved in Vega 3 using a combination of _reactive geometry_ (use the encoded scatter plot _symbol_ marks as the input data for the Voronoi _path_ marks) and _post-encoding transforms_ (add the Voronoi transform to the path marks, not a standard data set transform list). Reactive geometry was supported in Vega 2, but post-encoding transforms are a new Vega 3 feature.

Here is a sketch of how to approach this:

```js
"marks": [
  {
    "name": "symbols", // need unique name to reference later
    "type": "symbol",
    // ... scatter plot symbol encoding here ...
  },
  {
    "type": "path",
    "from": {"data": "symbols"}, // reactive geometry, symbol item is now datum for path
    "encode": {...}, // set desired color properties here
    "transform": [
      // post-encoding transforms, applied directly to scenegraph items
      // the voronoi transforms will write directly to the path property!
      {"type": "voronoi", "x": "datum.x", "y": "datum.y"} 
    ]
  }
]
```
