### ISSUE TITLE
Relation between change sets and updating the view

### ISSUE THREAD

**Issue by twwwt** [vega/vega#786]
Coming from Vega 2 and now trying Vega 3, I came across the question what the model of applying change sets to a view is. How do (i) data sets, (ii) change sets, and (iii) updating the view (re-rendering) relate to each other? More precisely, between any two invocations of `view.run()`, which of the following things are possible/supported:

- Apply one change set only to one data set only (i.e., view must be updated after each update to some dataset)
```
view
  .run()
  .change('ds', vega.changeset().insert([...]).remove([...]))
  .run()
```
- Apply more than one change set to a data set (I understand that this case can be merged into one change set, I just would like to know whether it would work)
```
view
  .run()
  .change('ds', vega.changeset().insert([...]).remove([...]))
  .change('ds', vega.changeset().insert([...]).remove([...]))
  .run()
```
- Apply one change set each to more than one data set
```
view
  .run()
  .change('ds1', vega.changeset().insert([...]).remove([...]))
  .change('ds2', vega.changeset().insert([...]).remove([...]))
  .run()
```
- Apply any number of change sets to any number of data sets
```
view
  .run()
  .change('ds1', vega.changeset().insert([...]).remove([...]))
  .change('ds1', vega.changeset().insert([...]).remove([...]))
  .change('ds2', vega.changeset().insert([...]).remove([...]))
  .change('ds2', vega.changeset().insert([...]).remove([...]))
  .run()
```

So, the question could be rephrased to whether it is possible to *enqueue* any number of change sets to any number of data sets and apply them all at once?

**Comment by jheer** [comment]
Great questions. For one pulse propagation cycle (that is, one invocation of `run`) you can currently:
- Apply one (and only one!) changeset to a specific data set. If you wish to apply multiple changesets you must either batch those changes into a single set, or apply them across multiple `run` calls.
- Apply changesets to different data sets. So you can update `ds1` *and* `ds2` on the same `run` invocation so long as each data set receives only a single changeset.

If you have an example use case where it is critical to apply multiple changesets to a single data set at the same time, feel free to open a new issue with a feature request (and ideally a motivating description for why you can't batch the changes yourself)!
