### ISSUE TITLE
Input box appears twice 

### ISSUE THREAD

**Issue by clarechurcher** [vega/vega#787]
I am using Vega 3.0.0-beta.27

I have an input text box (see below).  If I don't include the "element" parameter in the bind section everything is sweet.  1 input box in the visualisation div
If I put the element to display the input box in a different div it appears twice

 "signals": [
    {
      "name": "playerInput",
      "value": "graeme",
      "bind": {
        "input": "text",
       "element": "#player"
      }
    }
  ],

**Comment by jheer** [comment]
Thanks @clarechurcher! Please try the latest beta (v3.0.0-beta.30), as I pushed a fix for this issue (prompted by comments in the vega-js group). I'm going to close out this issue, but please comment / re-open if you still experience buggy behavior here.
