### ISSUE TITLE
Usage of $schema required?

### ISSUE THREAD

**Issue by randyzwitch** [vega/vega#789]
This is somewhere between a feature request, documentation request and a question (sorry!)

I want to port my Julia Vega library to use version 3 when it comes out of beta. However, Julia uses `$` as a string interpolation, and because of this, it's near impossible to programmatically generate JSON specs. 

Is using `$schema` actually necessary or just metadata? If there is functionality tied to it that I don't understand yet, would it be possible to define an alias of `_schema` or similar? R also uses `$` as a special character for column-indexing on data frames, so `$schema` might be an issue there also.

**Comment by jheer** [comment]
The `$schema` property is strongly encouraged, but is not read nor required by the parser: you can pass specs without $schema through the Vega 3.0 parser and generate views without any issues.

However, if you are generating specs that will be saved, shared, or used in any external context, I recommend adding the $schema property (by whatever means are necessary). The actual property name is not of our choosing: it is the standardized property for linking to a JSON schema, and can be used by tools to enable version checking, spec validation, and code editor autocomplete.

**Comment by randyzwitch** [comment]
Thanks for the explanation Jeff, guess it's off to hack the Julia parser a bit.
