### ISSUE TITLE
Style last label on an axis

### ISSUE THREAD

**Issue by Fil** [vega/vega#791]
<img width="432" alt="capture d ecran 2017-04-27 a 15 10 26" src="https://cloud.githubusercontent.com/assets/7001/25484790/b40f627e-2b5b-11e7-8163-edadb0dfb50b.png">

I'm doing this in a post-processor of my SVG, so that the last label on the horizontal axis is styled in _bold_ instead of _normal_.
```
svg.selectAll('g.mark-group.role-axis:nth-child(3) text:last-child')
      .style('font-weight', 'bold');
```
Can I do it in native vega instead? (Vega 3)

**Comment by jheer** [comment]
You can customize label formatting in Vega using an axis `encode: {labels: {update: {...}}}` block, which can include conditional logic in a signal expression.

However, the tricky part here is knowing which label is the last one. The backing datum for generated axis ticks includes `value` and `label` fields, but that's it. Perhaps it would be helpful to include an ordered integer `index` and a `length` field, or perhaps a [0,1] ordering fraction? I'm open to this change as this is not the first request for specialized position-based formatting for axis labels...

**Comment by GCheung55** [comment]
An alternative is to use CSS. Should work...

.role-axis text:last-child {
    font-weight: bold;
}

**Comment by domoritz** [comment]
@GCheung55 Unfortunately this won't work with the Canvas renderer (or a WebGL renderer in the future).

**Comment by GCheung55** [comment]
@domoritz you're absolutely right. I forgot to mention my solution only works for SVG.

**Comment by Fil** [comment]
If is is allowed to update a signal from within a loop, one could maybe do:
```
      "encode": {
        "labels": {
          "enter": {
            "signal update last with datum.value" ***
          },
          "update": {
            "fontWeight": {"signal": "datum.value == last ? 'bold' : 'normal'" }
          }
        }
      }
```

*** this is the part that doesn't work (and maybe can not be fixed under the vega paradigm)

**Comment by Fil** [comment]
In the meantime and on another part of the graph, I've done seomthing a bit related: computed a derivative data source with `transform:rank` to retrieve an index, and filter on rank>0 to remove the first element. Then I plot my data "without the first element".

To retrieve the _last_ element I might do this twice by using a negative on rank:rank, but it quickly becomes very verbose.

In any case I don't think this is applicable to axis ticks/labels.

**Comment by jheer** [comment]
Here is one possible solution. To perform custom formatting, you can use a signal expression to test if an axis label is the last label among its set of scenegraph sibling nodes. For example:
```json
"fontWeight": {"signal": "item === item.mark.items[length(item.mark.items)-1] ? 'bold' : 'normal'"}
```
