### ISSUE TITLE
label intervals instead of ticks

### ISSUE THREAD

**Issue by Fil** [vega/vega#792]
<img width="560" alt="axis copie" src="https://cloud.githubusercontent.com/assets/7001/25484850/de816a98-2b5b-11e7-9d0b-55ce8cdef938.png">

In this case I want to label intervals (years) instead of ticks (new year's day). Possible with vega 3?

(see also #791)

**Comment by Fil** [comment]
OK I found a solution:

first, create a transform>formula> year in my data
```
data {
     "name": "table",
     …,
      "transform": [
        {
          "type": "formula",
          "as": "year",
          "expr": "year(datum.date)"
        }
      ]

```
second, create an aggregate dataset from the first, grouped by year, then a formula to add `center = (min+max)/2`
```
    {
      "name": "byyear",
      "source": "table",
      "transform": [
        {
          "type": "aggregate",
          "groupby": ["year"],
          "fields": ["date","date"],
          "ops": ["min", "max"],
          "as": ["min", "max"]
        },
        {
          "type": "formula",
          "as": "center",
          "expr": "(+datum.min + +datum.max) / 2"
        }
      ]
    },

```
third, enter text marks centered on that value
```
    {
      "type": "text",
      "from": { "data": "byyear" },
      "encode": {
        "enter": {
          "x": {"scale": "x", "field": "center"},
          "y": {"signal": "height + 36"},
          "text": {"field": "year"},
          "align": {"value": "middle"}
        }
      }
    },
```

phewwww

**Comment by jheer** [comment]
That is a nice solution for your use case! There are simpler methods I might think of, but they do not have your desired property of placing the year in a central position even when only a subset of months are visible for that year.
