### ISSUE TITLE
Firefox hover issue

### ISSUE THREAD

**Issue by Golovior** [vega/vega#794]
Hello,  
  
It seems there is an issue with the hover on Firefox.  

## My (stripped) Code:  
  
    this.view = this.visualize(creationOptions);
    this.view.addEventListener('mouseover', this.onMouseOver);
    this.view.addEventListener('mouseout', this.onMouseOut);

    HoverI = 0;
    onMouseOver(event,item) {
       if(item == null)
            return;
		
        this.currentHover = item;
        if(item['mark']['marktype'] == "symbol")
        {
            console.log('SYMBOL' + HoverI);
            HoverI++;
        }
    }

    onMouseOut(event,item) {
        if(item == this.currentHover)
        {
            console.log('LEAVE' + HoverI);
            HoverI++;
        }
    }

This code is giving in Firefox a constant flow of console logs, even if i don't touch the mouse.  
Chrome is handling this without any problems, so probably this is an issue in firefox itself. Do you have an idea on how to solve this?  

Kind regard,  
  
Frank / Golovior

**Comment by jheer** [comment]
Thanks for reporting the issue! However, we can't reproduce without a complete specification and code. Please submit (or link to) a complete example that replicates the problem, along with your Vega version number, and we can take a look!

**Comment by jheer** [comment]
I tried testing this issue with the following cleaned-up code. I didn't find any issues in Firefox, so I suspect this is an issue in the client side code, not Vega.

```js
view.addEventListener('mouseover', onMouseOver);
view.addEventListener('mouseout', onMouseOut);

var HoverI = 0,
    currentHover = null;

function onMouseOver(event,item) {
   if(item == null)
        return;
  
    currentHover = item;
    if(item['mark']['marktype'] == "symbol")
    {
        console.log('SYMBOL' + HoverI);
        HoverI++;
    }
}

function onMouseOut(event,item) {
    if(item == currentHover)
    {
        console.log('LEAVE' + HoverI);
        HoverI++;
    }
}
```
