### ISSUE TITLE
A question about server side 

### ISSUE THREAD

**Issue by stulang** [vega/vega#796]
code ：
> var vega = require("vega")
> var json ='{  "$schema": "https://vega.github.io/schema/vega/v3.0.json",  "width": 400,  "height": 400,  "data": [    {      "name": "table",      "values": [12, 23, 47, 6, 52, 19],      "transform": [{"type": "pie", "field": "data"}]    }  ],  "scales": [    {      "name": "r",      "type": "sqrt",      "domain": {"data": "table", "field": "data"},      "zero": true,      "range": [20, 100]    }  ],  "marks": [    {      "type": "arc",      "from": {"data": "table"},      "encode": {        "enter": {          "x": {"field": {"gr/oup": "width"}, "mult": 0.5},          "y": {"field": {"group": "height"}, "mult": 0.5},          "startAngle": {"field": "startAngle"},          "endAngle": {"field": "endAngle"},          "innerRadius": {"value": 20},          "outerRadius": {"scale": "r", "field": "data"},          "stroke": {"value": "#fff"}        },          "fill": {"value": "#ccc"}        "hover": {        }      }    },      "type": "text",      "from": {"data": "table"},      "encode": {        "enter": {          "x": {"field": {"group": "width"}, "mult": 0.5},          "y": {"field": {"group": "height"}, "mult": 0.5},          "theta": {"signal": "(datum.startAngle + datum.endAngle)/2"},          "align": {"value": "center"},          "text": {"field": "data"}        }      }    }  ]}'  }      }    }  ]}'
> var view = new vega.View(vega.parse(json))  .renderer('none')  .initialize();
>  view.toSVG()  .then(function(svg) {    console.log(svg)  })  .catch(function(err) { console.error(err); });
Promise { <pending> }
> <svg class="marks" width="0" height="0" viewBox="0 0 0 0" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g transform="translate(0,0)"><g class="mark-group role-frame root"><g transform="translate(0,0)"><path class="background" d="M0,0h0v0h0Z" style="fill: none;"></path><g></g></g></g></g></svg>

Q:
there is nothing in the svg,why? how can i fix it?

**Comment by domoritz** [comment]
Can you try https://github.com/vega/vega/blob/master/bin/vg2svg and see whether it works for you?

**Comment by jheer** [comment]
The problem is that the input spec is a string, not an object. Hence the Vega parser is treating it like an empty specification object, as none of the properties it looks for are defined. I'll add an issue to vega-parser to check the type of the input spec to catch such errors in the future.

The spec provided is also invalid, but that is a different issue. If you run the same view initialization and SVG generation code with the following cleaned-up spec (as an object, not a string), then I see a good deal of generated SVG.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 400,
  "height": 400,
  "data": [
    {
      "name": "table",
      "values": [12,23,47,6,52,19],
      "transform": [{"type": "pie", "field": "data"}]
    }
  ],
  "scales": [
    {
      "name": "r",
      "type": "sqrt",
      "domain": {"data": "table", "field": "data"},
      "zero": true,
      "range": [20,100]
    }
  ],
  "marks": [
    {
      "type": "arc",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "x": {"field": {"group": "width"}, "mult": 0.5},
          "y": {"field": {"group": "height"}, "mult": 0.5},
          "startAngle": {"field": "startAngle"},
          "endAngle": {"field": "endAngle"},
          "innerRadius": {"value": 20},
          "outerRadius": {"scale": "r", "field": "data"},
          "stroke": {"value": "#fff"}
        },
        "fill": {"value": "#ccc"}
      }
    },
    {
      "type": "text",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "x": {"field": {"group": "width"}, "mult": 0.5},
          "y": {"field": {"group": "height"}, "mult": 0.5},
          "theta": {
            "signal": "(datum.startAngle + datum.endAngle)/2"
          },
          "align": {"value": "center"},
          "text": {"field": "data"}
        }
      }
    }
  ]
}
```

**Comment by stulang** [comment]
Thanks  it's working

**Comment by stulang** [comment]
@jheer   thanks    it is working.
