### ISSUE TITLE
Missing "scene" property in the specification page

### ISSUE THREAD

**Issue by kanitw** [vega/vega#797]
`"scene"` is a valid property of a specification according to the schema but is not included in this page https://vega.github.io/vega/docs/specification/.

**Comment by jheer** [comment]
The token `scene` does not appear anywhere in the Vega JSON schema. (I just grepped.) So I'm not sure what you mean.

It was valid in Vega 2 but removed in Vega 3. One can define an `encode` block in the top-level of a specification to achieve what was previously available under `scene`.
