### ISSUE TITLE
Interactive documentation

### ISSUE THREAD

**Issue by viebel** [vega/vega#798]
Vega rocks!

I have read the [Let's Make A Bar Chart Tutorial](https://vega.github.io/vega/tutorials/bar-chart/): at the end you encourage the reader to 
> Copy & paste the full specification above into the online Vega Editor

Would you be interested in embedding the JSON description of the vega charts right into the tutorial in order to make the learning experience more interactive - and  therefore more effective?

I have developed [the Klipse plugin](https://github.com/viebel/klipse) that enables the embedding of interactive code snippets and wrote a demo article of an [integration with Google Charts](http://blog.klipse.tech/data/2017/03/17/data-driven-documents-google-charts.html).

We could discuss it further on twitter or by email.

**Comment by jheer** [comment]
Thanks! We don't plan to add interactive editing to the documentation pages at this point, instead focusing on smooth transition to the full online editor environment.
