### ISSUE TITLE
Duplicate points in trail mark

### ISSUE THREAD

**Issue by jhoffswell** [vega/vega#800]
Using the same `x` _and_ `y` coordinates for two adjacent points in a trail mark produces an error (but this is not an issue for the line mark). For example, changing the `trail` example specification from the documentation to use the following values produces an error.

```
"values": [
  {"u": 1, "v": 28}, {"u": 1, "v": 28},
  {"u": 3, "v": 42}, {"u": 4, "v": 34},
  {"u": 5, "v": 36}, {"u": 6, "v": 48}
]
```

**Comment by jheer** [comment]
Closing here in favor of vega/vega-scenegraph#40. Thanks!
