### ISSUE TITLE
Usage docs incorrect

### ISSUE THREAD

**Issue by toholdaquill** [vega/vega#802]
As a programmer who is new to Vega, I RTFMed, but hit a brick wall at basic usage.

Usage docs (https://vega.github.io/vega/usage/) suggest this simple code snippet:

```javascript
<head>
        <script src="https://vega.github.io/vega/vega.min.js"></script>
</head>

<body>
<div id="vis"></div>
<script>
  vega.embed('#vis', 'https://vega.github.io/vega/spec/bar.vg.json');
</script>
</body>
```

But https://vega.github.io/vega/spec/bar.vg.json returns 404.

**Comment by arvind** [comment]
Good catch. Fixed with 50e20b6 to point to https://vega.github.io/vega/examples/bar-chart.vg.json.
