### ISSUE TITLE
vega embed usage docs linkrot

### ISSUE THREAD

**Issue by toholdaquill** [vega/vega#804]
The usage docs for vega-embed (https://vega.github.io/vega/usage/#embed) offer this code sample:

```javascript
<head>
  <script src="https://vega.github.io/vega/vega.min.js"></script>
  <script src="https://vega.github.io/vega-lite/vega-lite.min.js"></script>
  <script src="https://vega.github.io/vega-embed/vega-embed.min.js"></script>
</head>
<body>
<div id="vis"></div>
<script>
  vega.embed('#vis', 'https://vega.github.io/vega/examples/bar-chart.vg.json');
</script>
</body>
```

However, https://vega.github.io/vega-lite/vega-lite.min.js returns 404.

**Comment by domoritz** [comment]
If you want to use Vega 3, please use https://github.com/vega/vega-embed

**Comment by domoritz** [comment]
Thank you for flagging this. I will send a PR to resolve this.
