### ISSUE TITLE
Hover event not firing with overlapped symbol

### ISSUE THREAD

**Issue by tnavda** [vega/vega#809]
I am new to Vega, so quite possibly this is user error.  This is with v3.0-beta.30.  I'm trying to get a basic tooltip working on hovering on my data point.  I've drawn a stepped line with my data, then drawn an additional circle on the data points.  However, when I hover the circle symbol I can't get any kind of tooltip to show.  I've tried many incarnations of code, but this looks like it should be the closest to working.  Thank you

 var vegaJSONSpec = {
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 600,
  "height": 300,
  "padding": 50,
  "signals": [
    {
      "name": "interpolate",
      "value": "step",
      },
    {
      "name": "tooltip",
      "value": {},
      "on": [
        {"events": "symbol:mouseover", "update": "datum"},
        {"events": "symbol:mouseout",  "update": "{}"}
      ]
    }     
      ],
     
  "data": [
    {
      "name": "table",
      "format": {"type":"json", "parse":{"x":"number"}},
      "values": [
                  {x: 1493926762000 , y:0},
                  {x: 1493926762000 , y:2},
                  {x: 1493926777000 , y:4},
                  {x: 1493926792000 , y:6},
                  {x: 1493926807000 , y:8},
                  {x: 1493926822000 , y:10},
                  {x: 1493927122000 , y:7},
                  {x: 1493927127000 , y:5},
                  {x: 1493927152000 , y:2},
                  {x: 1493927157000 , y:0},
      ]
    }
  ],
 
  "scales": [
    {
      "name": "x",
      "type": "time",
      "range": "width",
      "domain": {"data": "table", "field": "x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "zero": true,
      "domain": {"data": "table", "field": "y"}     
    },
    {
      "name": "color",
      "type": "ordinal",
      "range": "category",
      "domain": {"data": "table", "field": "c"}
    }
  ],
 
  "axes": [
    {"orient": "bottom", "scale": "x",
          "format": "%M:%S", "grid": true
    },
    {"orient": "left", "scale": "y", "grid": true}
  ],
 
  "marks": [
    {
      "type": "group",
      "from": {
        "facet": {
          "name": "series",
          "data": "table",
          "groupby": "c"
        }
      },
      "marks": [
        {
          "type": "line",
          "from": {"data": "series"},
          "encode": {
            "enter": {
              "x": {"scale": "x", "field": "x"},
              "y": {"scale": "y", "field": "y"},
              //"stroke": {"scale": "color", "field": "c"},
              "strokeWidth": {"value": 2},
              "stroke": {"value": "rgba(75,200,150,0.8)"}
            },
            "update": {
              "interpolate": {"value": "step-after"},
              "fillOpacity": {"value": 1}
            },
            "hover": {
              "fillOpacity": {"value": 0.5}
            }
          }
        },
         {
              "type": "symbol",
              "from": {"data": "series"},
              "encode": {
                "enter": {
                  "x": {"scale": "x", "field": "x"},
                  "y": {"scale": "y", "field": "y"},       
                  "stroke": {"value": "rgba(75,200,150,0.8)"}
                },
                "update": {       
                  "x": {"scale": "x", "field": "x"},
                  "y": {"scale": "y", "field": "y"},
                  "size": {"value": "20"},
                  "shape": {"value": "circle"},
                  "opacity": {"value": 1},
                  "strokeWidth": {"value":4},
                  "fillOpacity": {"value": 1},
                  "strokeOpacity": {"value": 1}
                },
                "hover": {
                  "opacity": {"value": 0.5},
                }
              }
            },
           {
                "type": "text",
                "encode": {
                  "enter": {           
                    "align": {"value": "center"},
                    "baseline": {"value": "bottom"},
                    "fill": {"value": "#333"}
                  },
                  "update": {
                    "x": {"signal": "tooltip.x"},
                    "y": {"signal": "tooltip.y"},
                    "text": {"signal": "tooltip.x"},
                    "fillOpacity": [
                      {"test": "datum === tooltip", "value": 0},
                      {"value": 1}
                    ]
                  }
                }
              }          
      ]
    } 
  ]
};
 
var view = new vega.View(vega.parse(vegaJSONSpec))
  .renderer('canvas')  // set renderer (canvas or svg)
  .initialize('#view') // initialize view within parent DOM container
  .hover()             // enable hover encode set processing
  .run();              // run the dataflow and render the view

**Comment by jheer** [comment]
The problem is that your tooltip is using the `x` and `y` data fields of the original data (e.g., the timestamps for `x`), _not_ the pixel values calculated using the scale transforms. Here is a modified definition of your text mark that solves the problem by invoking the scale transforms as well.

```json
        {
          "type": "text",
          "interactive": false,
          "encode": {
            "enter": {
              "align": {"value": "center"},
              "baseline": {"value": "bottom"},
              "fill": {"value": "#333"}
            },
            "update": {
              "x": {"scale": "x", "signal": "tooltip.x"},
              "y": {"scale": "y", "signal": "tooltip.y"},
              "text": {"signal": "tooltip.x"},
              "fillOpacity": [
                {"test": "datum === tooltip", "value": 0},
                {"value": 1}
              ]
            }
          }
        }
```
I also added the snippet `"interactive": false` to ensure that the tooltip text does not interfere with the mouseover/mouseout event streams for the symbol marks.

**Comment by tnavda** [comment]
John,

Thank you that did the trick
