### ISSUE TITLE
Vega crashes with very big data json

### ISSUE THREAD

**Issue by mbooshehrian** [vega/vega#810]
Hi,

I have a chart that has a very large array of data objects and vega crashes while rendering the data. It throws an error in JSON.stringify method. I had a look at vega source code and found out that vega tries to duplicate the spec by doing JSON.parse(JSON.strigify(spec)) to "protect against subsequent spec modification", as the comment says. I removed this line of code and the chart renders without any issues. I am wondering if removing this line would have any subsequent issues.

**Comment by jheer** [comment]
It sounds like you are using Vega 2? I recommend moving to Vega 3, which among many other changes does not automatically copy the spec by default.

In any case, you might also want to separate your data from your specification. For example, you might save the data as a separate JSON file and reference in from your specification. With this change, Vega 2 might also work for you.

**Comment by mbooshehrian** [comment]
Yes, I am using Vega 2 and for some reasons, I don't want to update to Vega 3 yet. So you suggest if I clone the data to be used by Vega spec and then remove the duplication code, it should be safe?
What changes Vega is applying on spec that duplication in required?

**Comment by jheer** [comment]
Yes, remove the data from the `values` property of your data set definition, and instead use the `url` property to point to your (extracted) JSON file.

There are multiple places in the code where Vega maintains a reference to spec. The copy is made such that any external modifications don't then corrupt Vega's internal state. Vega 3 takes a much different approach to parsing that avoids this issue.

**Comment by mbooshehrian** [comment]
So Vega 2 doesn't make a copy of file json content?

**Comment by jheer** [comment]
Only of the Vega specification itself. Not input data loaded separately.

**Comment by mbooshehrian** [comment]
Thanks for your prompt answers! I appreciate it.

**Comment by mbooshehrian** [comment]
I have another question in a case I don't want to use files and put data in spec directly. (The reason is that I am not sure if I can provide the data in a file to be fed to Vega, because I create the data dynamically as the server calls come back to the client.) Currently, I use javascript classes to store data and instances of those are used to create spec data. If I make sure that all the objects are read-only, so that they cannot be changed in any ways, do you think it would be safe to remove duplication from Vega 2 source?

**Comment by jheer** [comment]
In this case I believe it would be safe to remove the spec duplication from the Vega 2 source code. However, it might be cleaner to instead use the Vega API to add the data directly at runtime. You can define an "empty" data set (e.g., provide a name only) and then populate it with data dynamically. Among other benefits, this allows you to keep your spec generation and data generation code separate.

For example, after creating a Vega 2 view instance (and before calling `update`), you could make the following call: `view.data("data-set-name").insert(values)`, where `values` is an array of JavaScript objects. For more, see the [Vega 2 API documentation](https://github.com/vega/vega/wiki/Streaming-Data#view-component-streaming-api).
