### ISSUE TITLE
Knowledge Graph  

### ISSUE THREAD

**Issue by Sudeep-takkar** [vega/vega#811]
I am implementing a knowledge graph and need functionality like in this graph : https://eisman.github.io/neo4jd3/

Can you please help me?

**Comment by jheer** [comment]
You might start by looking at the Vega force example here: https://vega.github.io/vega/examples/force-directed-layout/

 Your question is rather vague: if you formulate more specific questions you are more likely to get helpful responses. Moreover, GitHub issues are intended for filing specific bug reports or feature requests. For more general discussion please see the vega-js Google group: https://groups.google.com/forum/#!forum/vega-js

**Comment by Sudeep-takkar** [comment]
Thanks for the reply,

My Requirements are:
1. Need more information on nodes.
2. Adding nodes dynamically. If you will click on node in neo4jd3, then it will add few nodes.
