### ISSUE TITLE
config.axis.domain(Color|Width) Isn't Working

### ISSUE THREAD

**Issue by NeelMohapatra** [vega/vega#815]
```json
{
  "$schema": "http://vega.github.io/schema/vega/v3.0.json",
  "data": [{"name": "source","values": [{"a": "A"}]}],
  "scales": [
    {
      "name": "x",
      "type": "point",
      "domain": {"data": "source","field": "a"},
      "range": {"step": 21}
    }
  ],
  "axes": [{"scale": "x","orient": "bottom"}],
  "config": {
    "axis": {"domain": true,"domainWidth": 3,"domainColor": "red"}
  }
}
```
generates 
![screen shot 2017-05-17 at 7 06 39 pm](https://cloud.githubusercontent.com/assets/12771661/26183513/0ef3fa3c-3b34-11e7-9747-b3acee921f3b.png)
The color doesn't change nor does the width.

**Comment by jheer** [comment]
Thanks! Fixed in vega/vega-parser@e30e2cf3bc42e1f8b59048855909a7f341647dc7, and will be included in the next Vega release.
