### ISSUE TITLE
Interpolation of axis values improperly split

### ISSUE THREAD

**Issue by tnavda** [vega/vega#822]
If you look at the image below, you can see the time scale axis component is being rendered as 00:0 and 00:5 instead of 00:00 and 00:05.  I finally was able to identify what I think is the issue by stepping through the code.  It looks like Vega identifies the '00:' portion as a string and identifies the second part as a number and tries to do interpolateNumber instead of interpolateString on the entire value.  Which I think is based on regular expression based identification?  I tried setting the format string of the axes to '02d', but given the split like this I'm not sure the format would apply correctly.  Is there/should there be a way to force to interpolateString() for the entire value? Or is this a legitimate defect?

![scale](https://cloud.githubusercontent.com/assets/28634090/26370145/f2170d10-3fc4-11e7-933f-35c95e01f8fb.png)

Below is my sample spec

`  var vegaJSONSpec = {
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 778,
  "height": 389,
  "padding": 50,
  "signals": [
    {
      "name": "interpolate",
      "value": "step",
      },     
    ],
      
  "data": [
    {
      "name": "table",
      "format": {"type":"json", "parse":{"x":"number"}},
      "values": [
    
{x: 1495053866000 , y:5},
{x: 1495053871000 , y:8},
{x: 1495053876000 , y:10},
{x: 1495053881000 , y:13},
{x: 1495053886000 , y:15},
{x: 1495053891000 , y:17},
{x: 1495053896000 , y:20},
{x: 1495053901000 , y:22},
{x: 1495053906000 , y:25},
{x: 1495053911000 , y:27},
{x: 1495053916000 , y:30},
{x: 1495053921000 , y:32},
{x: 1495053926000 , y:35},
{x: 1495053931000 , y:37},
{x: 1495053936000 , y:40},
{x: 1495053941000 , y:42},
{x: 1495053946000 , y:45},
{x: 1495053951000 , y:47},
{x: 1495053956000 , y:50},
{x: 1495057561000 , y:49},
{x: 1495057566000 , y:46},
{x: 1495057571000 , y:45},
{x: 1495057576000 , y:42},
{x: 1495057581000 , y:39},
{x: 1495057586000 , y:38},
{x: 1495057591000 , y:33},
{x: 1495057596000 , y:29},
{x: 1495057601000 , y:27},
{x: 1495057606000 , y:24},
{x: 1495057611000 , y:19},
{x: 1495057616000 , y:19},
{x: 1495057621000 , y:18},
{x: 1495057626000 , y:16},
{x: 1495057631000 , y:14},
{x: 1495057636000 , y:12},
{x: 1495057641000 , y:9},
{x: 1495057646000 , y:6},
{x: 1495057651000 , y:5},
{x: 1495057656000 , y:3},
{x: 1495057661000 , y:2},
{x: 1495057666000 , y:1},
{x: 1495057671000 , y:1},
{x: 1495057676000 , y:0},
                  
      ]
    }
  ],

  "scales": [
    {
      "name": "x",
      "type": "time",
      "range": "width",
      "domain": [1495053866000, 1495057766000],
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "zero": true,
      "domain": {"data": "table", "field": "y"}      
    },
    {
      "name": "color",
      "type": "ordinal",
      "range": "category",
      "domain": {"data": "table", "field": "c"}
    },
    {    
        "name": "scale_convert",
        "type": "time",
        "round": false,
        "domain": [1495053866000, 1495054166000, 1495054466000, 1495054766000, 1495055066000,1495055366000,1495055666000,1495055966000,1495056266000,1495056566000,1495056866000,1495057166000,1495057466000,1495057766000],
        "range": ["00:00", "00:05", "00:10", "00:15", "00:20","00:25","00:30","00:35","00:40","00:45","00:50","00:55","01:00","01:05"]
   }    
  ],

  "axes": [
    {
      "orient": "bottom", 
      "scale": "x",
      "format": "%M:%S", 
      "grid": true,
      "titlePadding": 10,
      "title": "Time (hh:mm)",  
      "values": [1495053866000, 1495054166000, 1495054466000, 1495054766000, 1495055066000,1495055366000,1495055666000,1495055966000,1495056266000,1495056566000,1495056866000,1495057166000,1495057466000, 1495057766000],
      "encode": {
        "title": {
          "update": {
            "fontSize": {"value": 14},
            "font": {"value": "Verdana, Arial"},
          }
        },
        "labels": {
          "update": {
            "fontSize": {"value": 10},
            "font": {"value": "Verdana, Arial"},
            "text": {"scale": "scale_convert", "field": "value"},
            }
          }          
      }
    },
    {"orient": "left", "scale": "y", "grid": true, "title": "Count","titlePadding": 10,
      "encode": {
        "title": {
          "update": {
            "fontSize": {"value": 14},
            "font": {"value": "Verdana, Arial"},
          
          }
        },
        "labels": {
          "update": {
            "fontSize": {"value": 10},
            "font": {"value": "Verdana, Arial"},
            }
          }          
      }
  }
  ],  
  "marks": [  
    {
      "type": "group",
      "from": {
        "facet": {
          "name": "series",
          "data": "table",
          "groupby": "c"
        }
      },
      "marks": [              
        {
          "type": "line",
          "from": {"data": "series"},
          "encode": {
            "enter": {
              "x": {"scale": "x", "field": "x"},
              "y": {"scale": "y", "field": "y"},
              //"stroke": {"scale": "color", "field": "c"},
              "strokeWidth": {"value": 2},
              "stroke": {"value": "rgba(75,200,150,0.8)"}
            },
            "update": {
              "interpolate": {"value": "step-after"}, 
              "fillOpacity": {"value": 1}
            },
            "hover": {
              "fillOpacity": {"value": 0.5}
            }
          }
        },
         {
              "type": "symbol",
              "from": {"data": "series"},
              "encode": {
                "enter": {
                  "x": {"scale": "x", "field": "x"},
                  "y": {"scale": "y", "field": "y"},        
                  "stroke": {"value": "rgba(75,200,150,0.8)"},
                  "fill": {"value": "rgba(75,200,150,0.8)"}
                },
                "update": {        
                  "x": {"scale": "x", "field": "x"},
                  "y": {"scale": "y", "field": "y"},
                  "size": {"value": "20"},
                  "shape": {"value": "square"},
                  "opacity": {"value": 1},
                  "strokeWidth": {"value":2},
                  "fillOpacity": {"value": 1},
                  "strokeOpacity": {"value": 1}
                },
                "hover": {
                  "opacity": {"value": 0.5},
                }
              }
            }    
      ]
    }                            
  ]
};`

**Comment by jheer** [comment]
Thanks for reporting! As you stepped through the code, did you happen to notice if the issue occurs in Vega code or imported D3 code (e.g., from [d3-time-format](https://github.com/d3/d3-time-format))? I suspect it might be the latter, but would like to confirm.

If the issue arises due to D3 code, then I would encourage you to post an issue there as well. Vega will then inherit any fixes upon subsequent releases.

**Comment by tnavda** [comment]
I'm under the impression it is in the Vega code base, but I got a little overwhelmed by all the function references.

in `function interpolateString(a, b) {`

`
  return s.length < 2 ? (q[0]
      ? one$1(q[0].x)
      : zero$1(b))
      : (b = q.length, function(t) {
          for (var i = 0, o; i < b; ++i) s[(o = q[i]).i] = o.x(t); // Here it's already define the function to use 
          return s.join("");
        });
`

Below is snapshot in chrome where I think it is setting the interpolateNumber for the portion after the ":".  If you feel like I should still open against D3 I can.  Is there a way to dump out the exact D3 code that is being used to draw the graph.  So if we say, ok I have any issue, let me see what d3 code is being used to generate the chart and work backwards from that information; and also provide for a D3 issue?

![interpolate](https://cloud.githubusercontent.com/assets/28634090/26373610/2c808c8c-3fd0-11e7-8f05-d63324f09a43.png)

**Comment by jheer** [comment]
The code segment above is from [d3-interpolate](https://github.com/d3/d3-interpolate/blob/master/src/string.js). The default build of Vega rolls up D3 modules directly into the vega.js file, which is why it is difficult to discern the Vega code from the D3 code.

If you can include a stack trace, we will have a better sense of how this code was invoked and thus track down the problem. My best guess so far is that this coming through the [d3-scale `time` scale implementation](https://github.com/d3/d3-scale/blob/master/src/time.js#L26). Thanks!

**Comment by tnavda** [comment]
I captured a screenshot that has the stack trace as well.  Let me know what else I can do to help.

![code_w_st](https://cloud.githubusercontent.com/assets/28634090/26377904/5a5ed4fa-3fe0-11e7-96e1-80ef8f97cb27.png)

**Comment by jheer** [comment]
Thanks. I found the problem. Your `scale_convert` was set to type `time`, but since what you really want is a simple lookup table, you should use type `ordinal` instead. Make that change and everything works.

Of course, if I remove `scale_convert` altogether I get "correct" timestamps for the input values provided, but I assume you are performing a conversion to show values relative to a specific time frame?

**Comment by tnavda** [comment]
Bah, thanks for the help.  I'm 0 for 2 on valid defects

**Comment by jheer** [comment]
Keep trying and I'm sure you'll find one :)
