### ISSUE TITLE
Changes to vega datasets

### ISSUE THREAD

**Issue by domoritz** [vega/vega#824]
I'm trying to merge the datasets back into https://github.com/vega/vega-datasets.

I noticed the following problems
- `cars.json` and `movies.json` use years as numbers instead of datetime strings. 
- `movies.json` uses `TBD` instead of null for unknown release dates. 
- `flare.json` changes from nested to flat.

I prefer only to change the datasets if necessary. My suggestions would be to only change `flare.json` and keep the other files as they are and make changes to the vega specs if necessary.

**Comment by domoritz** [comment]
Here is the PR for new datasets: https://github.com/vega/vega-datasets/pull/18

**Comment by jheer** [comment]
OK, I've added the vega-datasets versions of `cars.json` and `movies.json` to this repo. I also updated the one example that was affected (`parallel-coords`). A future work item here may be to automatically pull from vega-datasets to populate the data sets published as part of the documentation.

These changes will be included in the next beta release (3.0.0-beta.32).

**Comment by domoritz** [comment]
The future work item is in https://github.com/vega/vega/pull/826
