### ISSUE TITLE
Re-evaluate layout

### ISSUE THREAD

**Issue by domoritz** [vega/vega#825]
Is there a way to recompute the layout after adding some data through the view api? My problem is that the initial view doesn't have any data and only after adding data, the legend is populated but is clipped off. 

cc @yifanwu

**Comment by jheer** [comment]
You can request re-layout as part of autosizing if you pass a `"resize": true` flag as part of an object-valued parameter of the top-level `"autosize"` property. See https://vega.github.io/vega/docs/specification/

**Comment by domoritz** [comment]
Fantastic. That solves a problem in a streaming example we are writing. Vega-Lite pull request is in https://github.com/vega/vega-lite/pull/2407.
