### ISSUE TITLE
Signal reference docs have broken link

### ISSUE THREAD

**Issue by domoritz** [vega/vega#828]
"signal reference" links to https://vega.github.io/vega/docs/parameter-types/#signal, which does not exist.

**Comment by jheer** [comment]
Can you point me to the page(s) where you found the broken link(s)? The template script for generating the parameter URLs appears to be correct, so this is probably due to a subset of hand-authored links.

**Comment by domoritz** [comment]
I was only looking at https://vega.github.io/vega/docs/scales/#scale-domains but haven't checked any other pages.

**Comment by domoritz** [comment]
I suppose all links in this search result: https://github.com/vega/vega/search?utf8=%E2%9C%93&q=parameter-types&type= should point to `vega/docs/types/` instead, right?

**Comment by domoritz** [comment]
Done in https://github.com/vega/vega/pull/829
