### ISSUE TITLE
Conditional transform

### ISSUE THREAD

**Issue by boxfish** [vega/vega#832]
I'm building a bar chart that can switch between grouped bar chart and stacked bar chart by binding a radio button to a signal called "mode", which can be either "stacked" or "grouped". 
It would be nice if it is possible to only run the "stack" transform only if the mode=="stacked", maybe a conditional expression for each transform to specify whether it should be activated?

**Comment by jheer** [comment]
There is currently no way to "disable" a transform. However, you can use conditionals within your visual encoding rules which can selectively ignore the output of the stack transform should you so choose!
