### ISSUE TITLE
Add a usage example of "title" to the docs?

### ISSUE THREAD

**Issue by maartenzam** [vega/vega#834]
I'm missing an example of the use of "title" [in the docs](https://vega.github.io/vega/docs/title/).
All the examples in the [gallery](https://vega.github.io/vega/examples/) that have a title use "text" to add one.

I thought it would be as simple as adding 
`  "title": {
    "text": "This is the title"
  }`
to the specification, but that doesn't seem to work.

**Comment by kenklin** [comment]
Alternatively, this is also accepted ...

```
{
  $schema: "https://vega.github.io/schema/vega/v3.0.json",
  title: "This is the title",
  . . .
```

**Comment by jheer** [comment]
It _should_ be as simple as adding `"title": "..."` to the specification, so long as one uses `"autosize": "pad"` (which is the default). If not there might be a bug, in which case please feel free to file a bug report issue!

There are examples of `title` in the test specs in the vega repo, but not in the current set of online examples. Thanks for the suggestion here, we'll look into updating one or more examples shortly!

**Comment by maartenzam** [comment]
I took the example bar chart from the gallery and added the `"title": "..."` and that works. But in my example below (just an experiment to learn Vega), it doesn't.
Not that important, but something is causing the title not to be added.

`{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 800,
  "height": 400,
  "padding": 10,
  "config": {
    "background": "white",
    "axis": {"labelFontSize": 26},
    "title": {
      "orient": "top"
    }
  },

  "title": {
    "text": "This is the title"
  },

  "data": [
    {
      "name": "table",
      "transform": [{
        "type": "collect",
        "sort": {
          "field": "amount",
          "order": "descending"
        }
      }],
      "values": [
        {"category": "A", "amount": 28},
        {"category": "B", "amount": 55},
        {"category": "C", "amount": 43},
        {"category": "D", "amount": 91},
        {"category": "E", "amount": 81},
        {"category": "F", "amount": 53},
        {"category": "G", "amount": 19},
        {"category": "H", "amount": 87}
      ]
    },
    {
      "name": "average",
      "source": "table",
      "transform": [{
        "type": "aggregate",
        "ops": ["average"],
        "fields": ["amount"]
      }]
    }
  ],

  "scales": [
    {
      "name": "yscale",
      "type": "band",
      "domain": {"data": "table", "field": "category"},
      "range": "height"
    },
    {
      "name": "xscale",
      "domain": {"data": "table", "field": "amount"},
      "nice": true,
      "range": "width"
    },
    {
      "name": "fontscale",
      "domain": {"data": "table", "field": "amount"},
      "nice": true,
      "range": [10,32]
    },
    {
      "name": "color",
      "type": "threshold",
      "domain": [0],
      "range": ["orange", "blue"]
    },
    {
      "name": "sequential",
      "type": "sequential",
      "domain": {"data": "table", "field": "amount"},
      "range": ["orange", "blue"]
    }
  ],

  "axes": [
    {
      "orient": "bottom",
      "scale": "xscale",
      "labels": false,
      "grid": true,
      "tickSize": 10,
      "zindex": 1,
      "encode": {
        "domain": {
          "enter": {
            "strokeWidth": {"value": 0 }
          }
        },
        "ticks": {
          "enter": {
          "stroke": {"value": "red"},
          "strokeWidth": {"value": 0 }
          }
        },
        "grid": {
          "enter": {
            "stroke": {"value": "white"},
            "strokeWidth": { "value": 1 },
            "strokeOpacity": { "value": 0.5 }
          }
        }
      }
    }
  ],

  "marks": [
    { "name": "bars",
      "type": "rect",
      "from": {"data":"table"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "amount", "offset": 1},
          "height": {"scale": "yscale", "band": 1, "offset": -5},
          "y": {"scale": "yscale", "field": "category"},
          "x2": {"scale": "xscale", "value": 0},
          "fill": {"scale": "sequential", "field": "amount"},
          "cornerRadius": {"value": 5}
        }
      }
    },
    {
      "type": "text",
      "from": {"mark": "bars"},
      "encode": {
        "enter": {
          "x": {"field": "x2", "offset": -5},
          "y": {"field": "y"},
          "dy": {"field": "height", "mult": 0.5},
          "fill": {"value": "white"},
          "align": {"value": "right"},
          "baseline": {"value": "middle"},
          "text": {"field": "datum.amount"},
          "fontSize": {"scale": "fontscale", "field": "datum.amount"}
        }
      } 
    },
    {
      "type": "text",
      "from": {"mark": "bars"},
      "encode": {
        "enter": {
          "x": {"field": "x", "offset": 5},
          "y": {"field": "y"},
          "dy": {"field": "height", "mult": 0.5},
          "fill": {"value": "white"},
          "align": {"value": "left"},
          "baseline": {"value": "middle"},
          "text": {"field": "datum.category"},
          "fontSize": {"scale": "fontscale", "field": "datum.amount"}
        }
      } 
    },
    {
      "name": "averageline",
      "type": "rule",
      "from": {"data":"average"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "average_amount" },
          "x2": { "scale": "xscale", "field": "average_amount" },
          "y": { "value": -5 },
          "y2": { "value": 400 },
          "strokeWidth": { "value": 2 }
        }
      }
    },
    {
      "type": "text",
      "from": { "mark": "averageline"},
      "encode": {
        "enter": {
          "x": {"field": "x" },
          "y": { "field": "y", "offset": -5 },
          "text": { "value": "Average" },
          "fontSize": { "value": 24 },
          "align": { "value": "center" }
        }
      }
    }
  ]
}`

**Comment by jheer** [comment]
Hmm, your spec works correctly for me. The title text appears at the top of the chart, centered, and with the correct default title font settings. What version of Vega are you testing with?

**Comment by kenklin** [comment]
@maartenzam Works fine here https://vega.github.io/new-editor/

**Comment by maartenzam** [comment]
Ok, I was on beta.28, now on beta.32 and title is appearing now.
Thanks!
(falling in love with Vega at the moment :)

**Comment by jheer** [comment]
The [Falkensee Population example](https://vega.github.io/vega/examples/falkensee-population/) now uses the title directive!
