### ISSUE TITLE
Vega3 documentation should have an "edit" link

### ISSUE THREAD

**Issue by nyurik** [vega/vega#835]
Whenever I see a small (or a big) problem with documentation, I would like to help and fix it, or at least suggest a fix for someone to review (a wiki-way).  The old doc had that, but the new one doesn't even offer a link to the where the doc is stored. Please add some edit link to help us contribute. Thanks!

**Comment by domoritz** [comment]
It's at the bottom of the page. 

<img width="1210" alt="screen shot 2017-05-31 at 11 15 08" src="https://cloud.githubusercontent.com/assets/589034/26646933/6e1624d6-45f2-11e7-96e3-1086e5348739.png">

The Vega-Lite docs have a more prominent link at the top as well.

<img width="748" alt="screen shot 2017-05-31 at 11 15 28" src="https://cloud.githubusercontent.com/assets/589034/26646954/88a50768-45f2-11e7-8854-2e0ea5baf2eb.png">

**Comment by nyurik** [comment]
Ah, silly me, must have been blind. Thanks!

**Comment by domoritz** [comment]
I think the docs should have an edit link at the top as well! @willium added this for VL in https://github.com/vega/vega-lite/issues/1359.
