### ISSUE TITLE
Axes documentation incorrectly shows "template"

### ISSUE THREAD

**Issue by nyurik** [vega/vega#838]
Vega3 axes documentation uses "template" with a blank value. Seems to be a mistake.

line 89 in https://github.com/vega/vega/edit/master/docs/docs/axes.md
          "text": {"template": "{{datum.data|number:'+,'}}"},

in https://vega.github.io/vega/docs/axes/  shows as 
          "text": {"template": ""},

**Comment by jheer** [comment]
Thanks! Turns out this exhibits _two_ errors: (1) the double braces was getting eaten by Jekyll in generating the docs, (2) Vega 3 no longer supports template any way, in lieu of more general signal expressions.

Fixed in a9af871.
