### ISSUE TITLE
vega not running on ubuntu 17.04

### ISSUE THREAD

**Issue by debuggermalhotra** [vega/vega#840]
I cloned into vega git directory as per the instructions and ran npm  install on my Ubuntu 17.04 machine but it threw a bunch of errors and asked me to attach npm-debug.log while opening this issue. But since i can't attach a log file in here, here is the log file: https://www.dropbox.com/s/1kwqh2esmuj7myh/npm-debug.log?dl=0. Instant help will be appreciated as currently vega is acting as a dependency for a project of mine. ThankYou
P.S vega builds just fine on my macOS sierra machine.

**Comment by GCheung55** [comment]
Curious why the prepublish is running from an install.

**Comment by debuggermalhotra** [comment]
Sorry?

**Comment by domoritz** [comment]
@GCheung55 I think that's some odd npm behavior. 

Vega should build on Ubuntu. In fact, all our tests run on travis (https://travis-ci.org/vega/vega), which uses Ubuntu. Please see the list of packages we install at https://github.com/vega/vega/blob/master/.travis.yml.
