### ISSUE TITLE
Config passed to parse overrides spec config

### ISSUE THREAD

**Issue by domoritz** [vega/vega#841]
[The docs](https://vega.github.io/vega/docs/config/) say "Any configuration provided within the specification itself will take precedence over external configurations passed to the parser" but the opposite seems to be the case. 

See https://bl.ocks.org/domoritz/5fa115f7338b9bdab107a1be3e976205

**Comment by jheer** [comment]
Thanks for catching that. The implementation was _replacing_ the specification-level config rather than cascading from external config to internal config. Fixed in vega/vega-parser@2341e57, released in vega-parser v1.0.0-beta.57; will be included in the next Vega release.
