### ISSUE TITLE
`pie` transform: `sort` object instead of boolean property

### ISSUE THREAD

**Issue by g3o2** [vega/vega#843]
pie transform's `"sort": true` sorts the `field` values in ascending order. I would have expected a default clockwise descending sort for pie charts. Maybe styles differ, therefore the request for a sort object.

**Comment by jheer** [comment]
Yeah, the `pie` sort is something of a vestige introduced all the way back in Vega 1. To achieve what you describe here, you can also play with the start and end angles to reverse the direction. 

More generally, though, I recommend using a `collect` transform prior to the `pie` transform, which will allow you to use a general comparator to sort any which way you like.

**Comment by g3o2** [comment]
Thank you! Already the first workaround works very well, wondering why I did not see it myself. :-)
