### ISSUE TITLE
Unexpected date parsing in different format

### ISSUE THREAD

**Issue by nyurik** [vega/vega#848]
Changing `2001-01-01` to either `2001-1-01` or `2001-01-1` produce slightly different graph. This could introduce hard to catch errors.

| 2001-01-01 | 2001-1-01 |
|---|---|
| ![image](https://user-images.githubusercontent.com/1641515/26907815-425fe714-4bc4-11e7-8da2-1800e8127958.png) | ![image](https://user-images.githubusercontent.com/1641515/26907827-5c55ce36-4bc4-11e7-80b3-7c1d044a0741.png) |

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"a": "2001-01-01","b": 28},
      {"a": "2001-01-02","b": 55},
      {"a": "2001-01-03","b": 43},
      {"a": "2001-01-04","b": 91},
      {"a": "2001-01-05","b": 81},
      {"a": "2001-01-06","b": 53},
      {"a": "2001-01-07","b": 19},
      {"a": "2001-01-08","b": 87},
      {"a": "2001-01-09","b": 52}
    ]
  },
  "mark": "line",
  "encoding": {
    "x": {"field": "a","type": "temporal"},
    "y": {"field": "b","type": "quantitative"}
  }
}
```
vs

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {
    "values": [
      {"a": "2001-01-1","b": 28},
      {"a": "2001-01-2","b": 55},
      {"a": "2001-01-3","b": 43},
      {"a": "2001-01-4","b": 91},
      {"a": "2001-01-5","b": 81},
      {"a": "2001-01-6","b": 53},
      {"a": "2001-01-7","b": 19},
      {"a": "2001-01-8","b": 87},
      {"a": "2001-01-9","b": 52}
    ]
  },
  "mark": "line",
  "encoding": {
    "x": {"field": "a","type": "temporal"},
    "y": {"field": "b","type": "quantitative"}
  }
}
```

**Comment by jheer** [comment]
Note that these are Vega-Lite, not Vega specifications... :) I assume that default date parsing is being applied here, which would mean that `Date.parse` is being invoked for each string. That would imply that any undesirable behavior here is the result of the browser implementations, not Vega _per se_. You might try including a specific d3-time-format parsing string to ensure the dates parse as desired.

As for what does or does not happen automatically when the Vega-Lite `"temporal"` type is used, that is an issue for the Vega-Lite repo, not Vega.

**Comment by nyurik** [comment]
@jheer this is clearly a Vega/d3-parsing(?) issue, perhaps related to how d3 instructs the browser (chrome) to parse dates. 

| Dates with zeros | Dates without zero |
|---|---|
| {"x": "2001-01-01","y": 28} | {"x": "2001-1-01","y": 28} |
| {"x": "2001-01-02","y": 55} | {"x": "2001-01-2","y": 55} |
| {"x": "2001-01-09","y": 12}  | {"x": "2001-1-9","y": 12} |
| ![image](https://user-images.githubusercontent.com/1641515/26955964-802f4c00-4c88-11e7-8240-ecd0f6f9286e.png) | ![image](https://user-images.githubusercontent.com/1641515/26956024-e29fecb4-4c88-11e7-9c72-9182105a1099.png) |


```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 500,
  "height": 200,
  "padding": 5,
  "data": [
    {
      "name": "table",
      "values": [
        {"x": "2001-01-01","y": 28},
        {"x": "2001-01-02","y": 55},
        {"x": "2001-01-09","y": 12}
      ],
      "format": {"type": "json","parse": {"x": "date","y": "number"}}
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "time",
      "range": "width",
      "domain": {"data": "table","field": "x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "zero": true,
      "domain": {"data": "table","field": "y"}
    }
  ],
  "axes": [
    {
      "orient": "bottom",
      "scale": "x",
      "format": "%Y-%m-%d %H:%M:%S.%L",
      "tickCount": 5,
      "encode": {
        "labels": {
          "update": {
            "angle": {"value": 90},
            "align": {"value": "left"},
            "baseline": {"value": "middle"}
          }
        }
      }
    },
    {"orient": "left","scale": "y"}
  ],
  "marks": [
    {
      "type": "line",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "x": {"scale": "x","field": "x"},
          "y": {"scale": "y","field": "y"},
          "stroke": {"value": "#00F"},
          "strokeWidth": {"value": 2}
        }
      }
    },
    {
      "type": "text",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "x": {"scale": "x","field": "x", "offset": 5},
          "y": {"scale": "y","field": "y"},
          "text": {"signal": "timeFormat(datum.x, '%Y-%m-%d %H:%M:%S.%L')"}
        }
      }
    }
  ]
}
```

**Comment by jheer** [comment]
As I noted earlier, if a custom data parsing format is not provided then Vega uses the browser's built in `Date.parse` method. Here are the results I see using this method in Chrome:
```
> new Date(Date.parse('2005-01-01'))
: Fri Dec 31 2004 16:00:00 GMT-0800 (PST)
> new Date(Date.parse('2005-01-1'))
: Sat Jan 01 2005 00:00:00 GMT-0800 (PST)
```
I believe this explains the issue you are seeing: for whatever reason the first option seems to be parsed relative to UTC, then second option seems to resolve to local time. This behavior is dependent on the JS runtime. The best solution is probably to provide an explicit date format within `data.format.parse`.
