### ISSUE TITLE
Zoomable bar plot

### ISSUE THREAD

**Issue by lemoncyb** [vega/vega#849]
One problem has been puzzled me for a long time, and I did many attempts but failed.
Is possible for Vega to draw a zoomable bar plot like [this](http://mbostock.github.io/d3/talk/20111018/area-gradient.html) in D3?
Zoomable for x-axis is necessary because we have a huge number of bars.
Thanks!

**Comment by jheer** [comment]
Yes. For a similar example (where the zooming is controlled by an overview plot) see the [overview + detail example](https://vega.github.io/vega/examples/overview-plus-detail/).

Also, the example you shared isn't _technically_ a bar plot. It is an area chart with the interpolation type set to `step-after`!
