### ISSUE TITLE
Doesn't ship with examples or compiled files

### ISSUE THREAD

**Issue by domoritz** [vega/vega#850]
Vega on NPM only comes with the compiled filed but without the examples. If I install Vega from the github tag, I only get the examples but not the compiled files. For the editor, however, it is important to have the compiled files (e.g. the schema). 

I think it would be nice to either ship the examples with npm or add compiled files to tagged github releases.

**Comment by jheer** [comment]
The compiled files are included in git under the `docs/` folder to drive the Vega website.

**Comment by domoritz** [comment]
While this is great fi you can import a file directly, it doesn't work if you just use import or require because https://github.com/vega/vega/blob/master/package.json#L41 points to a file that doesn't exist.

**Comment by jheer** [comment]
Is that a major concern? The npm package includes the build files, which is the primary use case. Also, why do you think it important to include the examples in the npm release? (And I assume you mean the test specs, not the examples in the documentation?)

**Comment by domoritz** [comment]
I need to somehow have both, the compiled files in `build/` and the examples that should be shown in the editor (I assume that is everything is `docs/examples`). For the editor, it doesn't matter whether this is in a github release or in npm. 

If we want everything in npm, but not a github release (which breaks bower btw), we can use https://github.com/vega/vega/pull/856.

**Comment by jheer** [comment]
For use by the editor, all of these files are available in GitHub tagged releases under the `docs/` folder.

**Comment by jheer** [comment]
For bower, one option would be to do something similar to [d3's bower-specific repo](https://github.com/mbostock-bower/d3-bower).

**Comment by domoritz** [comment]
> For use by the editor, all of these files are available in GitHub tagged releases under the docs/ folder.

Yes, but not the compiled files in `build`. This means, I cannot write `import * as vg from 'vega'`. Yes, I could write `import * as vg from 'vega/docs/'` instead but I wonder why we don't just add the compiled files in `build` to tagged releases. 

Beyond that, it may actually be problematic for downstream applications if `main` in `package.json` points to a compiled file. I thought it should point to a file that still has `require`s and `import`s in it so that a bundler can consolidate requirements. At least, that's what I tried to do in vl and embed.

**Comment by domoritz** [comment]
To the last point, it's odd that `vega-dataflow` for example is a dependency of vega but it's actually not needed because the files in npm already have it compiled into the bundle. Or is that what `vega-core` is for?

**Comment by domoritz** [comment]
Okay, I got terribly confused.

The editor creates its own bundles and it uses the `module` property. We can copy the schema and examples from the `docs` directory since we use the git tag instead of npm. 

So the issue is only bower but we could easily fix that by pointing to `docs/vega.min.js` instead of `build/vega.min.js`.
