### ISSUE TITLE
Is it possible to specify dimension of the entire vis instead of dimension of the data rectangle

### ISSUE THREAD

**Issue by kristw** [vega/vega#854]
Use cases: 
- create a chart with certain size, e.g. 1600x900 to put in slides. Setting `width:1600` and `height:900` does not really give me what I want.
- in javascript, if I want to create chart with vega and fit the size of the container `<div>`. I can get the size of the `<div>` but still need to deduct the axes width to get the right `width` and `height` to put in vega spec, which is somewhat awkward. It is more awkward for dynamic data when I do not know the axes width beforehand. 

Would you consider allowing something like `outerWidth` and `outerHeight` in the spec?

**Comment by jheer** [comment]
Hi @kristw! One thing to try is using `autosize: fit`. See https://vega.github.io/vega/docs/specification/ for more information about that.

Another option is to render to SVG using an unmodified Vega spec, and use CSS to set the SVG to the desired pixel dimensions. The visualization will scale appropriately. (Note that this also one option for getting "responsive" visualizations from Vega.)

**Comment by kristw** [comment]
Thanks @jheer for prompt reply! I will give that a try.
