### ISSUE TITLE
Pinch to zoom example broken

### ISSUE THREAD

**Issue by arvind** [vega/vega#861]
On Mobile Safari (iOS 10.3) the [zoomable scatter plot example](https://vega.github.io/vega/examples/zoomable-scatter-plot/) pans correctly on touch down. But, when I pinch to zoom, the display snaps to the following and no subsequent interactions work. Perhaps something wrong with `pinchDistance`?

![img_0164](https://user-images.githubusercontent.com/42262/27212882-17164558-5218-11e7-93f2-cc9e3bf92ab0.PNG)

**Comment by jheer** [comment]
Thanks! Fixed via changes to parser and example specs.
