### ISSUE TITLE
Allow ES6 + use Babel for ES5 support

### ISSUE THREAD

**Issue by nyurik** [vega/vega#862]
Vega seems to be using a lot of ES6 features, such as object destructuring assignments, and yet it use uglifyjs, not uglifyjs-es6. Also, there is a note that IE10 & 11 are also supported [here](https://vega.github.io/vega/usage/#ie), but IE11 does not support many other features either. According to http://gs.statcounter.com/, IE usage is at 4% and dropping. Is it even worth supporting and jumping through tons of hoops?

**Comment by jheer** [comment]
To the best of my knowledge, we do not use object destructuring assignments. We use Rollup to produce ES5 compliant code, then uglify the output of that. Not sure if uglify-es6 is necessary/helpful in that context, but if so please explain and I'd be happy to take a look!

**Comment by nyurik** [comment]
Hmm, I was under the impression that `import {extend, isObject} from 'vega-util';` uses destructuring assignment, whereas it is actually a [language feature](https://stackoverflow.com/questions/33524696/es6-destructuring-and-module-imports).  Still, the fundamental question remains -- are there any reasons to keep IE support?  Something as simple as a variable swap could be done as `[a,b] = [b,a];`. Lambda functions. Proper structuring. The benefits are enormous.

This way it will be up to the user to decide if they want to use ES5 or ES6: either they can apply [Babel](https://babeljs.io/) themselves, or Vega could generate two compiled versions - with and without babel, or Vega can simply have an `npm run-script build-es5` command.

P.S. This doesn't mean we have to rework all of the code right away. Rather, we could set the expectations with Vega 3 being ES6, and all code contributions would adhere to the new standards.

**Comment by domoritz** [comment]
fwiw, I already have to run babel in the editor to compile the import and export statements: https://github.com/vega/vega-editor/blob/redux/config/webpack.config.dev.js#L125

**Comment by nyurik** [comment]
Thanks @domoritz, one more reason not to keep ES5 backward compatibility in code, but use a tool.

**Comment by nyurik** [comment]
I guess this issue should be renamed to "Use ES6 + babel" for Vega build...  Should I open a new issue?

**Comment by wylieconlon** [comment]
I believe this can be closed https://github.com/vega/vega/pull/2179
