### ISSUE TITLE
Add predefined signal API

### ISSUE THREAD

**Issue by nyurik** [vega/vega#864]
Please add an API that allows "Vega hosts" to add host-specific signals.

A "vega hosting" is a use case, when the hosting platform accepts user-contributed content, and does not actually control the content of the Vega spec. For example, Wikipedia allows users to add a graph, and a Wikipedia mobile app or mobile site may render that graph, without having any knowledge of the graph itself.

While working on `Leaflet-vega` plugin, I ran into this problem:  I would like to provide a few additional signals to the graphs, such as `zoom` and `center`. These signals are "host specific", and they are very similar to the way `width`, `height`, `padding`, and `tooltip` signals operate - users expect them to be defined by the host, and use them when needed.

@arvind proposed that host would auto-inject these signals into the Vega spec. While this is easy and workable, I do not think this is a good long term solution, because the host should treat Vega spec as an opaque data object. Parsing and modifying the spec will require the host to always be aware of all the changes to the Vega spec itself - so if at some point signals syntax would change, it would have to adapt to all such changes. I think a proper API is a much better way to fix this. If Vega would accept some "predefined-signals" option, just like it does with data loading and logging, the host would not need to know anything about the content of the graph.

**Comment by jheer** [comment]
Copying my earlier response from Slack:

Regarding the question of "injecting" signals into specs or at parse time, my opinion is that the better option is to update the Vega specification prior to parsing. In terms of what you can achieve (expressivity-wise) there is no real difference here. Moreover, modifying the parser mandates that you have a specialized parsing environment. While this is still to some extent true with "spec-injection", one could update the spec then publish that (rewritten) spec elsewhere without any modification of the Vega runtime. So its more portable over all. I also don't think it "hackish" to modify the spec. The whole purpose of having a declarative JSON format is to enable computational reasoning and modification alongside human editing!

Regarding API changes: as described above, this would be breaking change requiring a 4.0 release. That is something we have no plans of doing! Plus, moving to a 4.0 release might also require an API change, so I don't see a huge benefit here either way.

**Comment by nyurik** [comment]
@jheer why would this be a breaking change? This would simply be an extra option passed to the spec parser. The hosting environment would indicate which signals it will support, and the parser will not require explicit declaration of those signals.  This way a graph can use these signals without declaring them explicitly - just like it can with width/height/...

**Comment by jheer** [comment]
If the signal definition changed so much that the spec injection approach would break, then there is the _possibility_ that the API for parser-level signal injection might also break. Not a certainty, but a possibility. In any case, I don't see a strong reason to support this given the various arguments both @arvind and I have made.

**Comment by nyurik** [comment]
understood, will do injection for now - this is far less critical than other things.
