### ISSUE TITLE
Cursor param not support in axes

### ISSUE THREAD

**Issue by nyurik** [vega/vega#868]
In this graph, the mouse cursor changes to "wait" on hover over bars, but remains an arrow for different axes elements. Ideally, it should be possible to set the custom cursor over the whole axes area (otherwise the blank area between labels will not be configurable), but even setting it over the axes elements should work.

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 400,
  "height": 200,
  "padding": 5,

  "data": [
    {
      "name": "table",
      "values": [
        {"u": 1,  "v": 28}, {"u": 2,  "v": 55},
        {"u": 3,  "v": 43}, {"u": 4,  "v": 91}
      ]
    }
  ],

  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "range": "width",
      "domain": {"data": "table", "field": "u"}
    },
    {
      "name": "yscale",
      "type": "linear",
      "range": "height",
      "domain": {"data": "table", "field": "v"},
      "zero": true,
      "nice": true
    }
  ],

  "axes": [
    {
      "orient": "bottom", "scale": "xscale",
      "encode": {
        "labels": {"enter": {"cursor": {"value": "ew-resize"}}},
        "ticks": {"enter": {"cursor": {"value": "wait"}}},
        "domain": {"enter": {"cursor": {"value": "wait"}}}
      }   
    },
    {"orient": "left", "scale": "yscale"}
  ],

  "marks": [
    {
      "type": "rect",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "cursor": {"value": "wait"},
          "x": {"scale": "xscale", "field": "u", "offset": 1},
          "width": {"scale": "xscale", "band": 1, "offset": -1},
          "y": {"scale": "yscale", "field": "v"},
          "y2": {"scale": "yscale", "value": 0},
          "fill": {"value": "steelblue"}
        }
      }
    }
  ]
}
```

**Comment by arvind** [comment]
By default, for performance reasons, axis and legend elements do not respond to input events. If you add an `"interactive": true` flag to the constituent encoding blocks, the `cursor` should update.

```json
  "axes": [
    {
      "orient": "bottom", "scale": "xscale",
      "encode": {
        "labels": {
          "interactive": true,
          "enter": {"cursor": {"value": "ew-resize"}}
        }
```

**Comment by nyurik** [comment]
@arvind thanks.  I thought I only needed `interactive` for the `update` section.  Is there a way to have a cursor for the whole axes area?

**Comment by nyurik** [comment]
P.S. I submitted a PR #871 to make the graph more discoverable. It's interesting how you did it with a transparent rectangle. I wonder if it would make sense to treat the whole axes as a rect group, just like a legend or a group mark, and have properties on it?

**Comment by jheer** [comment]
There _is_ a group mark that encompasses all the axis elements. It is called `"axis"` and accessible for custom encoding. See https://vega.github.io/vega/docs/axes/#custom.

However, the bounds of the group encompasses all elements, so it can "spill over" outside the pixel scale range (for example if there are long text labels). That is one reason I used a transparent rectangle for the interactive legends example.

**Comment by arvind** [comment]
@jheer: It doesn't seem like the `axis` property is actually having an effect. E.g., 

```json
{
      "orient": "bottom", "scale": "xscale",
      "encode": {
        "axis": {
          "interactive": true,
          "update": {
            "fill": {"value": "red"},
            "cursor": {"value": "ew-resize"}
          }
        }
      }   
    }
```

**Comment by jheer** [comment]
@arvind: The problem was that Vega was expecting the name/interactive properties for the top-level group to be defined as top-level axis properties. I think this is confusing and inconsistent so I've removed the top-level properties so that all custom encode groups behave the same way. This has now been released with the latest versions of both vega and vega-parser.
