### ISSUE TITLE
Resample day timeseries to week sums

### ISSUE THREAD

**Issue by mattijn** [vega/vega#870]
Not sure of its possible in vega, but im looking for a way to get week sums of my daily reported values.

I saw:
```
  "transform": [
        {"type": "formula", "as": "hour", "expr": "hours(datum.date)"},
        { "type": "formula", "as": "date",
          "expr": "datetime(year(datum.date), month(datum.date), date(datum.date))"}
      ]
    }
  ]
```

In the Seattle example: https://vega.github.io/vega/examples/annual-temperature/

But not sure if how the same method can be applied to weeksums

Eventually hope to bind several aggregations (day, week, month, year) to an input signal

**Comment by jheer** [comment]
See the [documentation for supported date-time functions](https://vega.github.io/vega/docs/expressions/#datetime-functions). Currently week-in-year (number of weeks since Jan 1) is not supported, nor is day-in-year (number of days since Jan 1).
