### ISSUE TITLE
parsing of compressed json for data object in url

### ISSUE THREAD

**Issue by mattijn** [vega/vega#875]
Out of curiosity: I can load json files through the `url` command, but I was wondering if this also can support compressed json files, such as gzip compressed json or rjson.

Or never will by design or maybe eventually
or maybe it already does, but I just don't know

**Comment by domoritz** [comment]
Since browsers transparently support gzip compression, Vega doesn't have to add support for it since it already works. See https://en.wikipedia.org/wiki/HTTP_compression

**Comment by mattijn** [comment]
Ok, just found out that most browsers already support this since 2000 (https://webmasters.stackexchange.com/a/22223). Just 17 years too late it's me realizing this;)
