### ISSUE TITLE
Using proper semver in schema

### ISSUE THREAD

**Issue by nyurik** [vega/vega#876]
It seems vega-embed uses version compare code from [stackoverflow](https://stackoverflow.com/questions/6832596/how-to-compare-software-version-number-using-js-only-number) (without a link / credits / license violation?), but I think it would be better if we would use widely used components like [compare-versions](https://www.npmjs.com/package/compare-versions) or even use the [node's semver](https://www.npmjs.com/package/semver) that supports ranges.

The goal is for components such as vega-embed to quickly evaluate if a given spec is compatible with the given Vega engine.  Lets figure this out before the final 3.0.  

Proposal: Proposed change:  Always use `require('semver').satisfies(vegaVersion, schemaVersion.startsWith(digit) ? '^' + schemaVersion : schemaVersion)` to test if requirement is met.  This way host could even have multiple Vega versions, and try them all to see which one would work for a given spec. We could think of the spec as the client code that "depends" on the engine, and hence can use the same semantics in the `$schema` field, e.g. `^3.0.0`, or `^3.0.5` if a certain feature was fixed in the 3.0.5 version.  I think that maintaining a separate version compare code, and multiple implementations with non-standard semantics.

| spec ver | engine ver | warn ? |
|--|--|--|
| 3.0 | 3.0.1 | no, the engine is newer than spec |
| 3.0.2 | 3.0.1 | yes, the spec relies on some bug fix that's not present before 3.0.2  |
| 3.0 | 4.0.0 | yes, spec is major-old |
| 3.0 | 3.0.0-beta.38 | tricky - see how [Semver handles](https://github.com/npm/node-semver#prerelease-tags) prerelease |

**Comment by domoritz** [comment]
Agree with all of the above. @yhoonkim, where does the version comparison code come from? I am in favor of replacing it with the (tested) semver library.

**Comment by domoritz** [comment]
Thanks for the PR: https://github.com/vega/vega-embed/pull/40.

**Comment by domoritz** [comment]
I agree that prereleases are tricky. For our use case, the interpretation in semver is too strict.

```
$ versionCompare("2.0", "2.0.0-beta.5")
1
```

We have three options. One is to accept the semver interpretation and throw a warning for now until we have released the final versions of Vega and Vega-Lite. The other is to wait until the final release before we release embed with these warnings. The last option is removing the beta postfix from the version string before passing it to semver. 

I'm happy to merge @nyurik's branch for now and either wait with the embed release or add some code to strip the beta postfix.

**Comment by nyurik** [comment]
I think showing a warning (esp considering that it only goes to console) is ok for now.  I wouldn't want to waste cpu cycles stripping (in effect - parsing) the version string. So I prefer accepting semver, just to be consistent and because that's what other devs would expect.

**Comment by yhoonkim** [comment]
That’s my fault. As @nyurik said, I used the stackoverflow. I didn’t know I have to attribute it even when using the code from there. I’ll take care of it from now. And thanks for warning me about that @nyurik , @domoritz and letting me know about semver! It seems perfect for this.

**Comment by jheer** [comment]
Thanks everyone. I'm closing this issue as it pertains to vega-embed (and appears to have been handled there), not this specific repo.

**Comment by nyurik** [comment]
@jheer I don't think this is a vega-embed issue.  I think Vega core should show a warning when `versionCompare(schemaVersion, libVersion) > 0`. Embed was simply the one that did it first, but it shouldn't be external libraries that do this validation. This code could be in vega utils, so that Vega-Lite can also call that function with its own versions.
