### ISSUE TITLE
Default axis format for bin may hide important information

### ISSUE THREAD

**Issue by domoritz** [vega/vega#877]
The default axis formatting does not always have the right resolution. In the example below, the format should be `.1f`. 

```json
{
  "$schema": "http://vega.github.io/schema/vega/v3.0.json",
  "data": [
    {
      "name": "source_0",
      "url": "data/movies.json",
      "format": {"type": "json","parse": {"IMDB_Rating": "number"}},
      "transform": [
        {
          "type": "extent",
          "field": "IMDB_Rating",
          "signal": "bin_maxbins_30_IMDB_Rating_extent"
        },
        {
          "type": "bin",
          "field": "IMDB_Rating",
          "as": [
            "bin_maxbins_30_IMDB_Rating_start",
            "bin_maxbins_30_IMDB_Rating_end"
          ],
          "signal": "bin_maxbins_30_IMDB_Rating_bins",
          "maxbins": 30,
          "extent": {"signal": "bin_maxbins_30_IMDB_Rating_extent"}
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "linear",
      "domain": {
        "data": "source_0",
        "fields": [
          "bin_maxbins_30_IMDB_Rating_start",
          "bin_maxbins_30_IMDB_Rating_end"
        ]
      },
      "range": [0,400]
    }
  ],
  "axes": [
    {
      "scale": "x",
      "format": ".1f",
      "orient": "bottom",
      "title": "BIN(IMDB_Rating)",
      "values": {
        "signal": "sequence(bin_maxbins_30_IMDB_Rating_bins.start, bin_maxbins_30_IMDB_Rating_bins.stop + bin_maxbins_30_IMDB_Rating_bins.step, bin_maxbins_30_IMDB_Rating_bins.step)"
      }
    }
  ]
}
```

Without explicit axis format:
<img width="420" alt="screen shot 2017-06-22 at 22 05 58" src="https://user-images.githubusercontent.com/589034/27467400-047e6c0c-5797-11e7-9cf5-30686aacf62f.png">

With explicit axis format:
<img width="423" alt="screen shot 2017-06-22 at 22 05 43" src="https://user-images.githubusercontent.com/589034/27467402-06ff914a-5797-11e7-88af-e0ddbcef3fea.png">

**Comment by jheer** [comment]
The format precision is automatically determined in conjunction with the default tickCount. We could look at the AxisTicks operator in vega-encode (and related utilities) to try and instead use the provided labels as the basis for inference. In the meantime, a quick-fix might be to set the `tickCount` parameter to match the number of explicitly provided labels.

**Comment by jheer** [comment]
I pushed and released a fix in the latest version of vega-encode. The axis tick format generator will now use the count of explicit values as a parameter if explicit values are provided.
