### ISSUE TITLE
Access datum in path mark on force directed layout

### ISSUE THREAD

**Issue by po5i** [vega/vega#879]
Based on this example: https://vega.github.io/vega/examples/force-directed-layout/

I want to achieve change the stroke color (current in `#ccc`) by using a custom field from the data. In my links data I have source, target, value and color. I want to use this field.

Also, is it possible to put a text "over" the relationship line (i.e. the value field)

Thanks

**Comment by g3o2** [comment]
Regarding the first question, the solution is `"stroke": {"field": "color"}` if your `color` field already specifies valid color names, if not, you'll need to add a scale. Also refer to the [path example](https://vega.github.io/vega/docs/marks/path/) and the [Marks documentation](https://vega.github.io/vega/docs/marks/), in particular the section on Field References.

For your second question, you should take a look at [vega-tooltip](https://github.com/vega/vega-tooltip).

**Comment by jheer** [comment]
If I understand correctly, for your second question you'd like to place text labels on graph edges? If so, you can create a new `text` mark instance that uses the same data source as your edges (and thus should have access to the edge end point coordinates via `source` and `target` properties).

You would then need to compute the text (x, y) coordinates and angle. The x, y coordinates can simply be computed by averaging the end points (e.g, `(datum.source.x + datum.target.x) / 2`) to center the text. You could similarly use the end points to compute an appropriate angle (if desired) using the [`atan2` expression function](https://vega.github.io/vega/docs/expressions/#atan2).
