### ISSUE TITLE
setState() broken for states with subcontext

### ISSUE THREAD

**Issue by jhaip** [vega/vega#885]
Visit any example with a subcontext like https://vega.github.io/editor/#/examples/vega/overview-plus-detail

In the browser (I was using Chrome 59) console run
```
VEGA_DEBUG.view.setState(VEGA_DEBUG.view.getState())
```

Produces the error:
```
main.77e7a80b.js:formatted:27890 Uncaught TypeError: Cannot read property 'subcontext' of undefined
    at main.77e7a80b.js:formatted:27890
    at Array.forEach (<anonymous>)
    at x._ [as setState] (main.77e7a80b.js:formatted:27889)
    at ce.le [as setState] (main.77e7a80b.js:formatted:67340)
    at <anonymous>:1:17
```

I believe this is a bug based on the description of [setState](https://vega.github.io/vega/docs/api/view/#view_setState).  Seems to work fine for state descriptions without a subcontext.

**Comment by jheer** [comment]
Thanks @jhaip! This is indeed a bug in the `setState` implementation. I've released a fix in [vega-runtime v1.0.1](https://github.com/vega/vega-runtime/releases/tag/v1.0.1) that will be included in the next Vega release.
