### ISSUE TITLE
Union domains that are signals

### ISSUE THREAD

**Issue by domoritz** [vega/vega#887]
I expect this to work but the y-scale domain is not -10 to 120.

This is causing problems for https://github.com/vega/vega-lite/issues/2511

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 400,
  "height": 200,
  "padding": 5,

  "data": [
    {
      "name": "table",
      "values": [
        {"category": "A", "amount": 28},
        {"category": "B", "amount": 55},
        {"category": "C", "amount": 43},
        {"category": "D", "amount": 91},
        {"category": "E", "amount": 81},
        {"category": "F", "amount": 53},
        {"category": "G", "amount": 19},
        {"category": "H", "amount": 87}
      ]
    }
  ],

  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "domain": {"data": "table", "field": "category"},
      "range": "width",
      "padding": 0.05,
      "round": true
    },
    {
      "name": "yscale",
      "domain": {
        "fields": [
          {"signal": "-10"},
          {"signal": "120"}
        ]
      },
      "nice": true,
      "range": "height"
    }
  ],

  "axes": [
    { "orient": "bottom", "scale": "xscale" },
    { "orient": "left", "scale": "yscale" }
  ],

  "marks": [
    {
      "type": "rect",
      "from": {"data":"table"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "category"},
          "width": {"scale": "xscale", "band": 1},
          "y": {"scale": "yscale", "field": "amount"},
          "y2": {"scale": "yscale", "value": 0}
        },
        "update": {
          "fill": {"value": "steelblue"}
        },
        "hover": {
          "fill": {"value": "red"}
        }
      }
    }
  ]
}
```

**Comment by jheer** [comment]
The scale domain is set correctly in my tests, but with incorrect propagation order. The signal value is added to the backing "dummy" data set using the `modify` expression function. However, modify queues up changes that are then run on a subsequent propagation cycle, such that most operators (including mark encoding, layout, etc) are run _prior_ to the proper domain being set. I will investigate possible fixes...

**Comment by jheer** [comment]
Fixed and released in vega-parser v1.0.0-beta.71. This will be included in the next Vega release.

We now use a "private" expression function in lieu of `modify` to immediately inject a signal value into a data set for use as part of a scale domain. Note that both scalar-valued signals (`120`) and array-valued signals (`[-20, 120]`) will work. Object-valued signals other than `{data: value}` should _never_ be used for scale domains; currently this includes date objects which must be wrapped as `{data: date}`.

**Comment by domoritz** [comment]
I see, so `{"signal": "datetime(2009, 6, 1, 0, 0, 0, 0)"}` needs to become `{"signal": "data": "datetime(2009, 6, 1, 0, 0, 0, 0)"}}`?

**Comment by jheer** [comment]
Yes, modulo typos:
```
{"signal": "{data: datetime(2009, 6, 1, 0, 0, 0, 0)}"}
```

(An array of objects with `data` properties is also valid.)

This is a (somewhat unfortunate?) consequence of the [tuple ingest logic](https://github.com/vega/vega-dataflow/blob/master/src/Tuple.js#L29), which checks for an object and only wraps an input value as `{data: value}` when the object check fails. If we decide that this policy is in error, we could consider changing it (assuming micro-benchmarks don't reveal an undue performance hit with per-tuple date type checks).
