### ISSUE TITLE
Allow load() to return an observable

### ISSUE THREAD

**Issue by nyurik** [vega/vega#893]
Allowing load() to return either a promise or an observable will allow dynamic data sources to supply new data when it becomes available.  This can be done without any changes to the existing load() overloads.

https://github.com/tc39/proposal-observable#ecmascript-observable

Example:

```js
data = loader(url, opts);
if (data.then) {
  // treat it as a promise
} else if (data.subscribe) {
  // subscribe to data refreshes
  data.subscribe( { next: (dataset) => { /* handle the new data set */ }
}
```

**Comment by jheer** [comment]
To clarify the proposal after discussion with @nyurik:
- The proposal here would involve zero changes to the existing vega-loader module.
- The [vega-dataflow loading logic](https://github.com/vega/vega-dataflow/blob/master/src/dataflow/load.js) would need to recognize whether a loader returns a Promise or an Observable, and take appropriate action in response. In the case of an observable, the dataflow would be responsible for creating a changeset that removes all existing tuples from a data source and inserts as new all tuples provided to the `next` method.

**Comment by jheer** [comment]
Vega 5 supports operators that return Promises, pausing dataflow evaluation until the Promise resolves.

**Comment by nyurik** [comment]
@jheer this task is not about promises, or pausing for the data to load. The [observable](https://github.com/tc39/proposal-observable#ecmascript-observable) is a different data type from `Promise`.  Observable's purpose is to simplify "subscriptions" to data - ability for the data source to send **multiple** updates when the new data becomes available - push instead of pull.

**Comment by jheer** [comment]
Yes, and I closed the issue because workable alternatives are available and I do not plan to add this functionality.
