### ISSUE TITLE
can one specify a letter-spacing attribute on titles?

### ISSUE THREAD

**Issue by Fil** [vega/vega#894]
& if so, how?

**Comment by jheer** [comment]
No, AFAIK letter spacing is not supported by Canvas text-rendering, and hence not supported by Vega text marks. One hack-ish workaround would be to use an SVG renderer, set the [name property for the title](https://vega.github.io/vega/docs/title/) to ensure it gets a known unique class name, and use CSS to further style the text.

**Comment by Fil** [comment]
OK makes sense — thank you for the explanation
