### ISSUE TITLE
looking for a very simple grid layout example

### ISSUE THREAD

**Issue by Fil** [vega/vega#895]
In short, what I need to do is the following: 

```
/-------------------\
|  title block      |
\-------------------/

/-------------------\
|  graph block      |
\-------------------/
```

with proper alignments; I think the grid layout might be the way to obtain this, but I'm not sure how to use it and can't find an example

thank you

**Comment by jheer** [comment]
See below for basic scaffolding. As you add content, you will probably need to set `width` and `height` signals within the sub-groups for local graph layout to work as expected. For a similar, but more complicated setup, see the [layout-vconcat test example](https://github.com/vega/vega/blob/master/test/specs-valid/layout-vconcat.vg.json).

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "padding": 5,
  "autosize": "pad",

  "layout": {
    "padding": 10,
    "columns": 1,
    "align": "all"
  },

  "marks": [
    {
      "type": "group",
      "marks": [
        {
          "type": "text",
          "encode": {
            "update": {
              "x": {"value": 0},
              "y": {"value": 0},
              "text": {"value": "Title Block"}
            }
          }
        }
      ]
    },
    {
      "type": "group",
      "marks": [
        {
          "type": "text",
          "encode": {
            "update": {
              "x": {"value": 0},
              "y": {"value": 0},
              "text": {"value": "Graph Block"}
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by king612** [comment]
Thank you for posting this, and the link to the test specs.  Is there a way to see those test specs rendered without having to clone and serve the whole repo?  The online editors don't have access to the data, so they never seem to render anything.  Maybe I'm missing something in how to use the Vega Editor?

**Comment by jheer** [comment]
I'm not sure I follow. If I copy and paste the vconcat example linked above into the online editor at https://vega.github.io/editor/, it works fine for me. All datasets from the vega-datasets repo should be available for use in the online editor.

If there are specific examples or test cases for which the datasets _don't_ align with the editor -- and you believe they should -- please let us know by opening a new issue. Thanks!

**Comment by king612** [comment]
Yep, my bust.  Seems to be working fine now.  I must've had some other issue.  Thank you for getting back to me!
