### ISSUE TITLE
nested data loading error in rc version

### ISSUE THREAD

**Issue by nyurik** [vega/vega#896]
I'm still trying to figure out what has changed, but vega 3-38 worked, and 3-rc does not. The code fails when requesting external data via a loader(). 

Error raised:  `Dataflow invoked recursively. Use the runAfter method to queue invocation.`

**Comment by jheer** [comment]
I'm not sure what you mean by "nested" data loading. Can you provide a simple example to test against?

If you want to see the code that changed, the relevant bits should be in the [dataflow `run` method](https://github.com/vega/vega-dataflow/blob/master/src/dataflow/run.js#L20). The main idea is to prevent an error case where `run` is invoked recursively during dataflow evaluation. For your use case is it sufficient to simply move the pending loader check ([run.js#35](https://github.com/vega/vega-dataflow/blob/master/src/dataflow/run.js#L35)) to be _before_ the recursion check ([run.js#L26](https://github.com/vega/vega-dataflow/blob/master/src/dataflow/run.js#L26))?

**Comment by jheer** [comment]
Closing, per conversation with @nyurik.
