### ISSUE TITLE
Top 50 ggplot2 Visualizations

### ISSUE THREAD

**Issue by nipunbatra** [vega/vega#899]
Hi,
I read the article: [Top 50 ggplot2 Visualizations - The Master List ](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html). I thought that some of the plots were fairly useful/interesting. I tried making analogous plots in Python using Altair. The goal of the exercise being to understand how much of the ggplot2 ecosystem can be currently replicated in Altair.

Since Altair depends on VL which depends on Vega, I thought to open an issue here.

Here is the [Github repo](https://github.com/nipunbatra/50-ggplot-python/tree/master/Altair) containing the desired plot (from the ggplot2 world), the corresponding Altair code and generated plot, and the TODOS to make the plots looks exactly similar.

I wanted to check the scope of each of the TODO. For instance, for the [first notebook](https://github.com/nipunbatra/50-ggplot-python/blob/master/Altair/Scatterplot.ipynb) called Scatterplot, here is the target plot.

![](http://r-statistics.co/screenshots/ggplot_masterlist_1.png)

Here is the corresponding Altair code and the generated plot.

```python
import pandas as pd
midwest= pd.read_csv("http://goo.gl/G1K41K")
from altair import *
chart = Chart(midwest)
chart.mark_circle().encode(
    x=X('area', title='Area'),
    y=Y('poptotal', title='Population'),
    color=Color('state'),
    size='popdensity',
).transform_data(filter = (expr.df.poptotal<50000))
```

![vega 31](https://user-images.githubusercontent.com/60985/27985913-d483eef4-6412-11e7-851f-5aee90b1afa2.png)

The TODO for this plot is as follows:

1. Add smoothing line? Does Vega support it yet?
2. No way to set title?
3. No way to set caption? (Source: midwest)

I have done a similar setup for the other notebooks as well.

I am sure many of these TODOs may be out of scope of Altair, Vega, VegaLite. Some of them might be useful to add. 

Many of the notebooks contain layered charts (composition of basic elements). For example, [diverging lollipop chart](https://github.com/nipunbatra/50-ggplot-python/blob/master/Altair/DivergingLollipop.ipynb), which ends up being complex!

cc @jakevdp, @ellisonbg

**Comment by jheer** [comment]
Thanks! TL;DR this would be a great exercise for Vega-Lite 2.0.

Most of these visualizations can be constructed directly with Vega, which includes support for cartographic mapping, networks, trees, contour plots, violin plots (via built-in kernel density estimation), and so on. Caveats:
- Vega does not have built-in regression support, so regression model parameters would need to be fit outside of Vega and then provided as input data. That might be a useful test exercise.
- Vega does not include built-in integration support for tile maps (Google Map, Leaflet, etc), but can be externally integrated, as in [leaflet-vega](https://github.com/nyurik/leaflet-vega).
- Vega includes basic title text support, but sub-titles and source captions would need to be added using text mark definitions.

Vega-Lite 1.0 / Altair 1.0 will only be able to support a subset of these plots. Vega-Lite 2.0 (currently in beta, Altair 2.0 will follow later) is the right project to test for coverage: it's support for layering, for example enables much more. The default label formats are updated (and are also configurable). Downstream releases are planned with support for box plots, violin plots, and cartographic mapping, so the examples can fill in over time as well.
