### ISSUE TITLE
Add custom mark-level clip region support.

### ISSUE THREAD

**Issue by Fil** [vega/vega#904]
In this example, using a `"clip": true` property clips everything including the dots on the sides. Is there a way to clip marks so they don't "escape" vertically, without clipping them horizontally?

<img width="532" alt="capture d ecran 2017-07-10 a 12 35 27" src="https://user-images.githubusercontent.com/7001/28015011-8352b300-656e-11e7-8927-65d838353d17.png">

**Comment by jheer** [comment]
Not currently. The mark-level `clip` property causes the mark to be clipped against the data rectangle, as defined by the parent group mark extents (in other words, clip to `{x: 0, y: 0, width: group.width, height: group.height}`.

It should be possible to modify the `clip` property to except an explicit clipping region definition as well. However, this will require modifications across vega-scenegraph and vega-parser to implement. I'll flag this is issue as a feature request, and mark it for consideration in Vega 3.1.

**Comment by jheer** [comment]
Since this issue was filed, custom clipping region support was added: https://vega.github.io/vega/docs/marks/#clip

The axis `padding` property for continuous axes was also added. One could use that to ensure sufficient padding is present such that the points do not get clipped out of view.
