### ISSUE TITLE
Merge `run()` into `runAsync()`, and rename as `run()`

### ISSUE THREAD

**Issue by nyurik** [vega/vega#908]
I propose to merge `run` and `runAsync` into one method. From the looks of it, the two methods are nearly identical (both are really async), except that `run()` does not return a promise of completion. So in a way, `runAsync()` can be used wherever `run()` is used at the moment, and simply ignore the return value.

This will make API simpler - users will know that there is only one entry point, and will have an option to wait until data completion.  This will also allow a more intelligent error handling - simply attach a `.catch()` afterwards if needed.

**Comment by jheer** [comment]
Though probably not obvious from the outside, this requested change would require _massive_ changes to a number of Vega elements. For example, the current event stream processing plus subsequent dataflow execution relies on synchronous evaluation. So I do not plan to make this change.

In addition, I'm currently making changes that will alleviate the error handling concerns: no exception will ever result from the dataflow by default. Instead, an (overridable) error handler function will consume any internally generated errors (stay tuned to #892).

**Comment by nyurik** [comment]
@jheer when you say run() is synchronious, does it mean it blocks on async operations internally?

**Comment by jheer** [comment]
Yes, and only in one case: when there is pending data loading, the `run` method exits immediately. The `run` method is then invoked again when all pending loads are complete. What `runAsync` does is simply provide access to the Promise that resolves once any pending loads have completed.

The other place asynchronicity arises is in the renderers for image loading. In such cases the renderer first does all that it can, then re-renders once the resources have been loaded. The analogous `renderAsync` method provides a Promise that resolves once all images are loaded.

**Comment by nyurik** [comment]
Per our conversation - please consider removing the `run()` method from the public API, and only exposing `runAsync()` (possibly as the new "public" `run()`) - this way the API surface would get smaller, allowing internal rewrites later on without exposing this internal feature.
