### ISSUE TITLE
DOC update: Support vega-bindings <div> creation separation

### ISSUE THREAD

**Issue by nyurik** [vega/vega#909]
In some cases, it may be required to create the `<div class="vega-bindings">` element separately from the main Vega container.  This way vega host may separate the canvas from the controls, and position them depending on the screen size or user preferences.

UPDATE: this is already implemented as a second `view.initialize()` parameter - needs documentation.

**Comment by jheer** [comment]
Actually, this is already supported via the second argument to [`view.initialize`](https://github.com/vega/vega-view#view_initialize). I'm updating the documentation to reflect this.
