### ISSUE TITLE
autosize=fit does not include padding

### ISSUE THREAD

**Issue by nyurik** [vega/vega#911]
Per [documentation](https://vega.github.io/vega/docs/specification/#autosize) (and my expectations), autosize=fit should include padding as part of its calculation, keeping width/height unchanged -- just like legends and other elements, padding is part of the graph itself, so if the fit graph is set to 100x100 with padding 10, Vega should attempt to draw everything in a square 80x80. But it seems padding is not subtracted before the autosize calc, but instead is applied afterwards, similar to the autosize=pad behavior.

**Comment by jheer** [comment]
You're right: currently the fit calculation ignores padding, and the documentation, while correct, is not sufficiently clear on this point. Keeping the current scheme "as-is" has higher consistency across layout types, for example `none` sets the size to width/height + padding (possibly with clipping), while `fit` sets the size to the same dimensions but with internal resizing. This scheme also matches the default CSS box model, where the actual size of an element is width/height + padding (+ border, etc).

As a result, I'm not (yet) convinced that we should change the model, but at minimum the documentation should be improved.

**Comment by jheer** [comment]
I've updated the [autosize documentation](https://vega.github.io/vega/docs/specification/#autosize) for more clarity. Note also that the `padding` documentation already states "Padding is applied _after_ autosize layout completes."

**Comment by jheer** [comment]
As of v3.0.0-rc3, Vega now supports an additional `autosize.contains` parameter. If set to `"padding"`, Vega View size calculations become _padding inclusive_. As a result, the `"fit"` autosize mode will attempt to _exactly_ match the provided width and height values. For more, see the [autosize documentation](https://vega.github.io/vega/docs/specification/#autosize).
