### ISSUE TITLE
Add dynamic data loader

### ISSUE THREAD

**Issue by jheer** [vega/vega#912]
Investigate addition of a new transform operator that performs data file loading with support for the following features:
- Dynamic parameterization by signals, causing data refresh
- Periodic polling to pull data updates (perhaps via a new timer signal?)
- Observable support to push data updates (#893)

This operator could be used to handle loading/parsing for data set definitions, replacing the "hard-wired" data loading / pending support currently used in vega-dataflow.

**Comment by nyurik** [comment]
Related to [this forum post](https://groups.google.com/forum/#!topic/vega-js/4cO1ZjbKJJc) - I think dynamic data loading could be done with #839 (observable):
* minimal Vega change:  data loader or even an external system will handle "signal://somedataurl" by subscribing to that signal, and on update it will treat signal's value as a URL, downlading the data, and pushing the update via the observable interface
* thorough Vega change:  introduce some new data-level field, e.g. `"expr": "..."` that will be evaluated as any other dynamic expression, and will use the above method when expr value changes and new data is downloaded.

**Comment by thatguy7** [comment]
Using dynamic data loading would make it possible to work interactively with large data sets through search engines like Elasticsearch by handing off the aggregations and performing dynamic filtering of the data.

This is a valuable enhancement.

+1

**Comment by jheer** [comment]
Vega 5 adds infrastructural support for dynamic loading via asynchronous dataflow processing (for example, see the `Load` transform in the vega-transforms package). We also support signal values for dynamic data `url`, `values`, and `format` properties. As a result, I'm now closing out this issue.

**Comment by aidan-plenert-macdonald** [comment]
@jheer Can you point me to some documentation or examples for Dynamic data loading using Signals?
