### ISSUE TITLE
Issues with Contour Schema

### ISSUE THREAD

**Issue by domoritz** [vega/vega#917]
I get warnings in the editor: https://vega.github.io/editor/#/

Arrays of numbers for thresholds:
![image](https://user-images.githubusercontent.com/589034/28135089-edb4f8ac-66f9-11e7-9b86-8193da20ae18.png)

Using an expression to get x and y
![image](https://user-images.githubusercontent.com/589034/28135062-d0aa127e-66f9-11e7-926d-08c76e1602ad.png)

**Comment by arvind** [comment]
Hmm, I thought we'd dropped the `expr` property in favour of `signal` for inline expressions... Perhaps that's why (though `expr` is what the [contours example](https://vega.github.io/vega/examples/contour-plot/) uses)?

**Comment by jheer** [comment]
@arvind: Yes and no. The `signal` property can include inline expressions that are evaluated to produce a value. The `expr` property is higher-level: it returns a _function_ (not the return value of an expression), allowing things like custom accessors, etc.

**Comment by jheer** [comment]
Thanks for reporting @domoritz.

The error with the `thresholds` parameter is valid: the exported schema does indeed expect a number (or signal). I need to update transform definitions + vega-parser's schema generation to support union types (here, numbers and number arrays). Will try to get to that soon.

The error for the `x`, `y` parameters is perplexing. Those parameters must be `oneOf` three values:
- A string or signal object (`{"signal": "..."}`). The latter _requires_ the `signal` property.
- A field object (`{"field": "..."}`), which _requires_ a `field` property and allows no other properties.
- An expr object (`{"expr": "..."}`), which _requires_ an `expr` property.

The example you've given appears to be unambiguous relative to the current schema. Is there an issue with the validator you are using? The schema file? Or something else that eludes me?

**Comment by domoritz** [comment]
@jheer That's very odd indeed. The editor actually uses two different validators. Internally, the monaco editor uses a validator, which is the one that shows the warning. In addition, we use ajv to show warnings in the panel at the bottom. Ajv does not throw a warning. So it seems like it's an issue with the monaco validator.

**Comment by jheer** [comment]
The `thresholds` schema issue is resolved by vega/vega-geo@20a2ee64957078f6021db49d7da557a4b812d60b: instead of adding a union type, I instead expanded the option across multiple singly-typed parameters.
