### ISSUE TITLE
Document which transform parameters accept signals.

### ISSUE THREAD

**Issue by domoritz** [vega/vega#919]
The [sample transform](https://vega.github.io/vega/docs/transforms/sample/) accepts signals but the documentation says that `size` has to be a number. Is this true for all parameters? Where is this documented? 

```
{"type": "sample", "size": {"signal": "sample_size"}}
```

**Comment by jheer** [comment]
Nearly all transform parameters accept signals (i.e., all basic literal and array types). I agree this is not clearly documented. I think the right approach might be to add a statement on the Transforms page about the wide applicability of signals, and then clearly indicate for each transform any parameters that do _not_ accept signals.

**Comment by domoritz** [comment]
At least it's documented in the schema and the typings so we can close this.
