### ISSUE TITLE
Update axes do not correctly replot points in javascript

### ISSUE THREAD

**Issue by rhytnen** [vega/vega#923]
Spec for the chart is listed at the end.  The relevant JS is:

I create several charts via config file so I have a loop that does:
```
let promise_chart = new Promise((resolve, reject) => {
            v = vega.embed('#' + chart_id, chart_file, chart_options);
            resolve(v)
        }).then( function (val){rig.charts[chart_name].view = val.view });
```

When I get new data to insert I do:
```
function update_raster(chart, oag_packet)
{
    let x_values = oag_packet[chart.key]
    let y = oag_packet['index']
    console.log('index: ' + y)

    for (var i = 0; i < x_values.length; i++)
    {
        x = parseFloat(x_values[i])
        if (isNaN(x) || (x  == undefined))
        {
            console.log('Invalid x-value');
            continue;
        }
        chart.view.insert('table', {'x':x, 'y': y});
    }
    chart.view.run()
}
```

The spec initially has no data so the y-axis updates with ticks with the first entries and it looks correct.  However, when the next set of data comes in and y-axis again updates, the initial marks remain in their original position as if the axis had not rescaled.  When examining the data object for the chart, the x and y points appear correct.

In the following shots - you can see the data that is plotted at y=18 hasn't moved when it is updated and now appears at y=65.  All the data in the second image actually spans y=1 thru y=81.

![canvas](https://user-images.githubusercontent.com/632888/28218223-ba62e86e-686c-11e7-9c25-fb45ce6fc0e8.png)

![canvas2](https://user-images.githubusercontent.com/632888/28218228-bda0e13e-686c-11e7-902a-74a2668dae44.png)

Here is the spec:
```
{
  "width": 450,
  "height": 250,
  "padding": {"top": 10, "left": 50, "bottom": 50, "right": 10},
  "data": [
    {
      "name": "table",
        "values": []
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "linear",
      "range": "width",
      "zero": true,
      "domain": [-1, 7]

    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "domain": {"data": "table", "field": "y"}
    }
  ],
  "axes": [
    {"orient": "bottom", "scale": "x",  "title": "Time From Sham Change"},
    {"orient": "left", "scale": "y", "title": "Catch Trials"}
  ],
  "marks": [
    {
      "type": "rect",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "x": {"scale":"x", "value": 0.15},
          "x2": {"scale":"x", "value": 1.0},
          "y": {"scale":"y", "value":0},
          "y2": {"scale":"y", "value":500},
          "fill": {"value":"#E0F7FA"},
          "fillOpacity": {"value":1}
        }
      }
    },
    {
      "type": "symbol",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "x": {"field": "x","scale": "x"},
          "y": {"field": "y","scale": "y"},
          "shape":{"value":"square"},
          "size": {"value": 10},
          "fill": {"value": "#F44336"},
          "opacity": {"value": 0.7}
        },
        "update": {"fill": {"value": "#F44336"}}
      }
    },
    {
      "type":"line",
      "from": {"data":"table"},
      "encode":{
        "enter":{
          "x":{"scale":"x", "value":0},
          "x2":{"scale":"x", "value":0},
          "y":{"scale":"y", "field":"y"},
          "y2":{"scale":"y", "field":"y"},
          "stroke": {"value": "#4A148C"},
          "strokeWidth": {"value": 2}
        }
      }
    }
  ]
}
```

**Comment by arvind** [comment]
Hi @rhytnen, you're experiencing these issues because the spatial encodings (`x`, `y`, etc.) for your marks are defined on the `entry` property set. If you move them to `update`, the marks should reposition themselves as the data changes. 

For more information on how `enter` and `update` work see [the Visual Encoding portion](https://vega.github.io/vega/docs/marks/#visual-encoding) of the Vega docs, or Mike Bostock's [Thinking with Joins tiroeial](http://bost.ocks.org/mike/join/).

**Comment by rhytnen** [comment]
You're right - as is always the case, as soon as I gave up and posted this, I discovered that I should have add

```
          "x": {"field": "x","scale": "x"},
          "y": {"field": "y","scale": "y"},

```
 in the update black for the marks.
