### ISSUE TITLE
Extrapolate X or Y from line mark.

### ISSUE THREAD

**Issue by GCheung55** [vega/vega#929]
Similar to the [question on SO](https://stackoverflow.com/questions/11503151/in-d3-how-to-get-the-interpolated-line-data-from-a-svg-line), is there a Vega-way of extrapolating the X or Y from a line mark?

**Comment by jheer** [comment]
In general, there is no easy way that works for all cases. Of course, you could do arbitrary calculations within a signal (e.g., access the last two points in a data array and linearly extrapolate from those), but it would be a bit onerous. Moreover, that won't account for non-linear interpolators.

It might make sense to first define an appropriate model for the extrapolation you'd like to perform, then either (a) include extrapolated data as input to Vega, or (b) [register a new transform](https://vega.github.io/vega/docs/api/extensibility/#transforms) that performs the extrapolation within the Vega dataflow.

**Comment by GCheung55** [comment]
@jheer How would I extrapolate based on a scale?

Say, I have 2 data points.

```
[
    {x: 0, y:0},
    {x: 10, y:10}
]
```

How would I figure out what Y is based on a linear scale? If the range is 0 to 15, and I want to Y of a point in the center? I don't know how a transform will extrapolate this with scales - do you have a hint?

To provide more context, with a linear scale, a line mark is drawn. I have a vertical rule positioned on hover. Wherever the vertical rule intersects with the line is what the Y value I'm trying to retrieve. But if I don't have a data point at that corresponds to the X and Y position, I'd have to extrapolate what the Y position/value is.
