### ISSUE TITLE
Need a way to apply axis title's style to row-title

### ISSUE THREAD

**Issue by kanitw** [vega/vega#931]
Currently, to make facet's axis title (which uses layout's `row-title` role to implement) looks like normal axis title, we output hardcoded style in the output.  

However, this means that `config["row-title"]` would no longer work for theming `align`, `fill`, `fontWeight`, `angle`.  

```
  {
      "name": "trellis_barley_row_title",
      "role": "row-title",
      "type": "group",
      "marks": [
        {
          "type": "text",
          "role": "row-title-text",
          "encode": {
            "update": {
              "y": {"signal": "0.5 * height"},
              "align": {"value": "right"},
              "text": {"value": "site"},
              "fill": {"value": "black"},
              "fontWeight": {"value": "bold"},
              "angle": {"value": 270}
            }
          }
        }
      ]
    }
```

I remember briefly discussing about this before OpenVisConf and one option is to support multiple `role`s per mark?

I also wonder if axis title has an implicit `role` that get applied in vega-parser.

**Comment by jheer** [comment]
Yes, there is an `axis-title` role. However, it doesn't have any corresponding config options set, which means any axis-level config should overwrite role-level config. That said, if you want to use the axis-title role within a grid header that shouldn't (I don't think) conflict with anything else.

**Comment by kanitw** [comment]
Note: It seems like if I want to correctly apply axis config to row/column's title and labels, I have to read the `config.axis` and output hardcode mark properties.   

(I'll investigate more and provide a more descriptive comment.)

**Comment by kanitw** [comment]
> any axis-level config should overwrite role-level config

I should apply styles defined by axis config (e.g., `labelColor`, `titleFontWeight`) to facet header's title and labels in some ways.  

If so, what would be the best way to do that? 

One dumb solution is to have Vega-Lite hardcode them in the header, but that means Vega-Lite will have to import the [default config](https://github.com/vega/vega-parser/blob/master/src/config.js).  
Thus, if you want me to go down this route, we may want to extract the default config into its own repo so that Vega-Lite can also import them directly.  

Alternatively, we may think if Vega-parser can have another set of config for header, or  apply axis config to header directly.  However, I'm not sure if this path will be very generalizable as the way we
 structure facet in Vega-lite can be too specific.

**Comment by kanitw** [comment]
The new pending `style` property would solve this problem so I'm closing this.
