### ISSUE TITLE
min/maxExtent and offset should not be applied to axes with neither title or labels

### ISSUE THREAD

**Issue by kanitw** [vega/vega#936]
By setting `config.axis.minExtent`, it gets applied to all axes, including ones with neither title or labels (grid axes) and thus produce weird layout.

![vega_editor](https://user-images.githubusercontent.com/111269/28399453-ebee708e-6cc1-11e7-8825-f5077f40c943.png)

Full Spec: https://pastebin.com/e0FCe20N

Without this, I think `config.axis.minExtent` will not be generally useful.  

(I was thinking that I will solve https://github.com/vega/vega-lite/issues/2684 by just setting `config.axis.minExtent` for Vega-Lite plots.)

**Comment by jheer** [comment]
Thanks for raising the issue. However, I'm not sure it's wise to "automagically" enable/disable this feature. For example, what if I'm using min/max extent to ensure similar alignment across multiple chart instances? An alternative solution here might be to emit `"minExtent": 0` as part of the axis definition for any gridline-only axes that Vega-Lite generates.

Note: there was a related bug in vega-parser that would cause zero (as opposed to `null` or `undefined`) values in the spec to get overwritten by the configuration value. That has been fixed and released in vega-parser 1.2.3.
