### ISSUE TITLE
cannot access vega.zip from the latest beta release

### ISSUE THREAD

**Issue by mpetris** [vega/vega#937]
Hi,

I have a problem downloading the vega.zip from the v3 pre-releases. When accessing the link 
`https://github.com/vega/vega/releases/download/v3.0.0-rc3/vega.zip` for example I get an error message from the S3 backend starting like this:
`
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>` and so on.

Best,

Marco

**Comment by jheer** [comment]
I am unable to replicate the issue: the zip file downloads for me with no issues. I suspect this may have been due to a transient problem with GitHub itself.

**Comment by mpetris** [comment]
Sorry my fault, NoScript was blocking the request from github to amazonaws as a cross site scripting attempt.
