### ISSUE TITLE
add an argument to `datetime()` and `utc()` allowing to switch the month base

### ISSUE THREAD

**Issue by g3o2** [vega/vega#939]
My suggestion would be to add an argument to allow the user to switch between zero-based and one-based month: e.g. `datetime(year, month[, day, hour, min, sec, millisec, monthbase])`, with `monthbase` being `zero` by default and allowing the values `zero` or `one`.

Given that the audience for vega(-lite) includes "non-computer scientists", and that vega(-lite) also follows the objective of describing visualisations, it simply looks weird to see `datetime(2017, 6, 25)` in a specification when the date is supposed to represent `2017-07-25`, even more so when `month` is the only argument to be zero-based.

I understand this is a "feature" of [javascript](https://stackoverflow.com/questions/1453043/zero-based-month-numbering) and thus perfectly understood by computer scientists. But does it really make any sense for vega(-lite) ?

**Comment by kanitw** [comment]
FYI, for Vega-Lite, we have a special [Date Time Definition object](https://vega.github.io/vega-lite/docs/transform.html#datetime), which uses 1-12 for month.   Under the hood, we convert to 0-based month in Vega.  So this should be less of a concern for Vega-Lite users.  

But yeah, it's still confusing for Vega.   (Thanks to Javascript!) That said, I guess that most of Vega users would have more "Computer Science" background as compared to Vega-Lite.

**Comment by g3o2** [comment]
It appears that I've not been properly reading the docs! :-) Sorry for that. I have filed the issue in vega because it pertains to vega expressions but it is true that I've stumbled over the issue when using vega-lite. Let me close the issue for now then.
