### ISSUE TITLE
Orphan node flies away from canvas

### ISSUE THREAD

**Issue by po5i** [vega/vega#953]
Based on the following example: https://vega.github.io/vega/examples/force-directed-layout/

If the data contains a node that is not linked to any other one and the graph is not static, when I drag any node the orphan node flies away out of the canvas. 

Is there any parameter that prevents this?

**Comment by jheer** [comment]
You can adjust the layout by configuring the various forces. A first step might be to add a `distanceMax` parameter to the `nbody` force -- this will limit the range of the repulsive force.

Next, you might explore adding `x` and `y` forces that pull all the nodes to the center of the display. This will counteract the repulsive force to keep disconnected nodes "in orbit".

For more, see the [vega force](https://vega.github.io/vega/docs/transforms/force/) and [d3-force](https://github.com/d3/d3-force) documentation.
