### ISSUE TITLE
Path broken with mark sort 

### ISSUE THREAD

**Issue by kanitw** [vega/vega#954]
I'm trying to replace collect transform with mark sort as @arvind suggested in https://github.com/vega/vega-lite/issues/2669, but somehow the output line is acting weird. 

I'm not sure why. 

![vega_editor](https://user-images.githubusercontent.com/111269/28894183-e5f5a310-7788-11e7-84e6-ebc5132abc59.png)

Here is a spec https://pastebin.com/SxZxds8n

**Comment by arvind** [comment]
Interesting, perhaps there's a bug in mark-level sorting of JS Date objects? E.g., for the area 
```
> items[0].datum.yearmonth_date
< Tue Feb 01 2005 00:00:00 GMT-0800 (PST)
> items[1].datum.yearmonth_date
< Sat Jan 01 2000 00:00:00 GMT-0800 (PST)
```

**Comment by jheer** [comment]
No Vega bugs here. The spec is sorting on a non-existent field, as mark-level sorting sorts _marks_, not _data objects_. Adding a `datum.` prefix to the sort field fixes the ordering:

```json
"sort": {
  "field": "datum.yearmonth_date",
  "order": "ascending"
},
```

**Comment by kanitw** [comment]
Thanks!
