### ISSUE TITLE
Should role still affect SVG `class`?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#962]
Now that we decouple `style` from `role`, I still observe that `role` affect SVG `class`. 
Should `style` be the one that affect `class` instead?

**Comment by jheer** [comment]
No. For a couple reasons:
1. The `style` values are resolved internally within the parser. They are never written to the scenegraph and so are currently unknown to the renderers.
2. The `role` output on the scenegraph is primarily to enable semantic analysis of the graph (for example, as in Jorge Poco's work generating labeled data sets for image analysis of charts). The ability to use roles to style via CSS is only a secondary "feature", and also achievable by adding explicit `name` entries to mark definitions.
