### ISSUE TITLE
npm install vega requires canvas build, too heavy for just client use

### ISSUE THREAD

**Issue by bryansera** [vega/vega#963]
We are using npm for our package manager (instead of say bower), 

But when doing npm install vega, it adds a dep on canvas, which needs to be built.  This makes our build much more complicated (at least for windows).  (see: https://github.com/Automattic/node-canvas/wiki/installation---windows)

Is there a way to make canvas optional?  (since we use vega client-side only there is no need for the npm canvas module...right?)

**Comment by jheer** [comment]
Hmm. I just double-checked and we do not list `canvas` as a required dependency anywhere. It is listed under `optionalDependencies` for the vega-scenegraph and vega-wordcloud modules. As a result, the `canvas` build may fail but that should be non-fatal. You should still be able to use the built vega files without issue in a browser.

If you have more information about how your build is breaking that you think we should address, please let us know.

**Comment by bryansera** [comment]
Indeed, you are right.  Sorry, I was completely thrown off by the violent error message thrown by gyp, and being new to npm thought it was a real issue.  Just and FYI for any other n00b that sees this (below)

(love Vega btw)

gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\bsera\Source\Repos\ExperimentationUI\node_modules\canvas
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.6 (node_modules\canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.6 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by jheer** [comment]
No worries! Indeed, the violent error message is unpleasant...
