### ISSUE TITLE
Marks Points binding with svg images 

### ISSUE THREAD

**Issue by Richard-bizruntime** [vega/vega#965]
Hi Vega Team , I have a group of Svg images i need to use that images in the marks fields instead of points ,i gone through the as per your marks fields documentations "https://vega.github.io/vega/docs/marks/shape/"  but i am not able to find the correct way of binding the different kind of  images in the marks fields. could you any one tell me ,how can we archive this ,Thanks .

**Comment by jheer** [comment]
I'm not sure precisely what you are trying to achieve, but it sounds like you either want an image mark (https://vega.github.io/vega/docs/marks/image/), a path mark (https://vega.github.io/vega/docs/marks/path/) with an SVG path string, or a symbol mark (https://vega.github.io/vega/docs/marks/symbol/) with an SVG path for the shape property.

**Comment by Richard-bizruntime** [comment]
how to provide different types of svg images to different type of category points while making visualization for worldmap for example in airport example case all category points coming in same filled circle but i want different svg image for different category.

**Comment by jheer** [comment]
I'm still not sure what you mean by "SVG image":
- If you mean a separate, complete SVG file defining an image, use the `image` mark type.
- If you mean a SVG path definition, look at the `path` or `symbol` mark types.
