### ISSUE TITLE
Axis shows ticks for parts of year even though we use nice: 'year' in scale already

### ISSUE THREAD

**Issue by kanitw** [vega/vega#966]
From https://github.com/vega/vega-lite/issues/2822
Spec: https://pastebin.com/Wa3krbEc

![image](https://user-images.githubusercontent.com/111269/29189354-03f48ea6-7dcb-11e7-81b2-5cc3cfa67191.png)

Since we use `timeFormat: '%Y'`, the parts of year become duplicates of 2016 on the axis. 

Not sure if this a bug, if it is not, is there any solution to deal with this case?

**Comment by jheer** [comment]
Closing here, replaced by vega/vega-encode#7
