### ISSUE TITLE
The Dorling diagram example shows warnings in editor after redrawing

### ISSUE THREAD

**Issue by mattijn** [vega/vega#973]
After editing a single value in the specs of the https://vega.github.io/editor/#/examples/vega/dorling-cartogram (just to make it redraw again), it will show some warnings for the `text` declaration stating that certain values are not accepted (btw, the proposed valid value `"group"` is accepted, but that won't draw the text labelling)
![dorling_diagram](https://user-images.githubusercontent.com/5186265/29253646-3728d290-8083-11e7-8411-e662cc6f088a.PNG)

**Comment by jheer** [comment]
Thanks! The Dorling example has been updated to be schema-compliant.
