### ISSUE TITLE
How to draw line with arrows in vega

### ISSUE THREAD

**Issue by mattijn** [vega/vega#974]
I have been playing around with drawing simple lines using the types 

- `path` | https://gist.github.com/mattijn/623375863fc6afbd606ab7e56cad941a,
-  `symbol` | https://gist.github.com/mattijn/ada2503a8ee76a7ac85f5682cdebaf8c and 
- `trail` | https://gist.github.com/mattijn/c3d527b92dfa725a9a1b3981e4e00e16 

and the next step were arrows (or lines with arrowheads), but some simple examples or suggestions how to approach this would help. 
Arrowheads needs to be defined in `"value": "M0,-5L10,0L0,5"` style? And are separated from the lines? Or are there predefined arrowhead markers? Eventually was hoping to bind rotation, fill color and size of the arrow(s) to input values. 

Not exactly, but something like this:
![rgg 1](https://user-images.githubusercontent.com/5186265/29253778-888e34a6-8086-11e7-8b1e-0c96e1478fe5.png)

btw: congrats for the v3.0 release!

**Comment by mattijn** [comment]
Made some progress, but not really there. 
![arrow](https://user-images.githubusercontent.com/5186265/29293787-a1883724-814c-11e7-8912-33664c34ddd6.gif)
```
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 200,
  "height": 200,
  "padding": 5,
  "signals": [
      { "name": "color", "value": "orange",
      "bind": {"input": "radio", "options": ["gray", "green", "orange"]} },
    { "name": "size", "value": 2000,
      "bind": {"input": "range", "min": 0, "max": 10000, "step": 100} },
        {"name": "sizeHeight", "update": "size * 0.003"}
  ],
  "marks": [
    {
      "type": "rect",
      "encode": {
        "update": {
          "fill":{"signal": "color"},
          "x": {"value": 27},
          "y": {"value": 50},
          "width": {"value": 100},
          "height": {"signal": "sizeHeight"},
          "opacity": {"value": 1},
          "strokeWidth": {"value": 2}
        },
        "hover": {
          "opacity": {"value": 0.5}
        }
      }
    },
    {
      "type": "symbol",
      "encode": {
        "update": {
           "fill": {"signal": "color"},
          "x": {"value": 150},
          "y": {"value": 60},
          "size": {"signal": "size"},
          "shape": {"value": "triangle-right"},
          "opacity": {"value": 1},
          "strokeWidth": {"value": 4}
        },
        "hover": {
          "opacity": {"value": 0.5}
        }
      }
    }
  ]    
  
}
```
I think I need something similar to an `orient="auto"` (http://vanseodesign.com/web-design/svg-markers/) to make the arrowhead connect to the end of the `rect`. 

And probably because I use a `rect` I am not able to include a rotation. Using a `rule` mark it should be possible to include rotation through connecting `x2` and `y2` to degrees, but than the connecting arrowhead keeps remaining

**Comment by g3o2** [comment]
I don't quite understand why `path` mark would not be appropriate for this task? The challenge for resizing would then reside in deriving the relevant formula.

**Comment by jheer** [comment]
For the base arrow, I would recommend using [a symbol mark with a custom SVG path](https://vega.github.io/vega/docs/marks/symbol/) that defines the arrow shape. This would allow you to position and size the arrows as you see fit. The current limitation is that there is no built-in support for rotation (`angle`) of symbol marks - though that might be a reasonable feature request. Alternatively, you could have a set of SVG paths for different orientations (e.g., 8 angles at 45 degree increments) and select among those in a data-driven way.

Another (perhaps fanciful?) option could be use to use a text mark (which does support rotation via an `angle` property) in conjunction with a Unicode arrow character (→).

**Comment by mattijn** [comment]
Unicode arrows is a good idea and work well for my case. Simple example:
![arrows](https://user-images.githubusercontent.com/5186265/29336879-a5f63194-820f-11e7-9801-38133bfb4ac3.PNG)

```
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "data": [
    {
      "name": "arrows",
      "values": [
        {"x": 25,  "y": 25, "size": 50, "angle": -45, "color": "orange"},
        {"x": 75,  "y": 25, "size": 75, "angle": -50, "color": "blue"},
        {"x": 125, "y": 25, "size": 100,"angle": -60, "color": "red"},
        {"x": 25,  "y": 75, "size": 35, "angle": -30, "color": "orange"},
        {"x": 75,  "y": 75, "size": 50, "angle": -70, "color": "lightblue"},
        {"x": 125, "y": 75, "size": 75, "angle": -40, "color": "blue"},
        {"x": 25,  "y": 125,"size": 35, "angle":   0, "color": "orange"},
        {"x": 75,  "y": 125,"size": 50, "angle": -30, "color": "lightblue"},
        {"x": 125, "y": 125,"size": 75, "angle": -10, "color": "blue"}  
      ]
    }
  ],
  "marks": [
    {
      "type": "text",
      "from": {"data": "arrows"},      
      "encode": {
        "enter": {
          "text": {"value": "➟"}
        },
        "update": {
          "opacity": {"value": 1},
          "x": {"field": "x"},
          "y": {"field": "y"}, 
          "fill": {"field": "color"},       
          "angle": {"field": "angle"},
          "fontSize": {"field": "size"},          
          "align": {"value": "center"},
          "baseline": {"value": "middle"}
        },
        "hover": {
          "opacity": {"value": 0.5}
        }
      }
    }
  ]
}
```

For plotting of a wind-profile map including wind barbs (non-existent in unicode) the rotation of a symbol mark with a custom SVG path might be useful (not sure if these barbs can be drawn in a single SVG path though). Eg like this:
![quickscat rita 2005-09-21 1104 - 704am 1](https://user-images.githubusercontent.com/5186265/29337670-7496ddda-8212-11e7-94e6-c3a78440475a.png)

And the following wind speed/direction profile chart is now probably possible also, using the text mark:
![hrdl_12hr_zspdir](https://user-images.githubusercontent.com/5186265/29337799-053a1244-8213-11e7-9162-e4ac0aa76d48.png)

**Comment by domoritz** [comment]
@mattijn That looks great. I wonder whether we should add angle as a channel to Vega-Lite so that you can create the plot you showed in the last comment with a compact spec.
