### ISSUE TITLE
How should we best improve X-Axis Labels?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#976]
From https://github.com/vega/vega-lite/issues/2880 and https://github.com/vega/vega-lite/issues/2825, we found a few cases where the last value of x-axis labels can go out of bound.  

![image](https://user-images.githubusercontent.com/111269/29296420-015b7c9e-810f-11e7-9059-6b1bf2c6be59.png)

![image](https://user-images.githubusercontent.com/111269/29296592-2b30a5fc-8110-11e7-83cd-dff93d047599.png)

From my investigation, Tableau avoid this problem by 
1) Make the first axis label align left, not centered
2) Hide the last x-axis labels.

Thus I can add the following code to the axis's `encode.labels.update` to avoid the problem

```
"align": {
  "signal": "item === item.mark.items[0] ? 'left': 'center'"
},
"text": {
  "signal": "item === peek(item.mark.items) ? '' : datum.value"
}
```

However, I wonder if this is the solution we should use and wonder if this should be exposed as an option in Vega rather than in Vega-Lite as it might be useful for general Vega users too. 

Also, adding `text` in Vega-Lite means I also need to have a specialized code path to correctly apply "format" to the text as my production rule won't be applied to text automatically anymore.

**Comment by jheer** [comment]
I'll think about possible proposals here. Feel free to suggest some, too! I think there are multiple (non-exclusive) possibilities to consider.

For example:
- Add built-in support for left/right alignment, perhaps relative to the chart width or height.
- Augment the label overlap analysis with options to include consideration of chart width or height.
- Change the default formatting for large values.
- Apply the limit property for text larger than a certain size. (Obviously not ideal and poor for print, but maybe more acceptable if the full string is visible upon hover or as a tooltip?)

**Comment by g3o2** [comment]
Text wrapping comes to mind, as well as providing exposing in-between object (legend, plot, etc.) margin parameters.

As already stated in my comment to vega-lite issue 2825, one should also not forget that design cannot be completely delegated to software. Some responsibility remains with the user: make the numbers smaller if you can.

**Comment by kanitw** [comment]
Thanks @jheer.  I think the possibilities you list sound reasonable.  Here are some comments 

> Add built-in support for left/right alignment, perhaps relative to the chart width or height.

Note that right alignment for the right-most item only works when the number of digit is small.
From my former experiment, it is not perfectly clear that the label is the label of the last tick.
![image](https://user-images.githubusercontent.com/111269/29345029-cb663aec-81f0-11e7-9da6-a8d25199566e.png)

> Apply the limit property for text larger than a certain size. (Obviously not ideal and poor for print, but maybe more acceptable if the full string is visible upon hover or as a tooltip?)

This might be relevant for top-down sizing as well?  (Say if we choose a naive implementation to calculate cell width/height using a fixed formula, instead of implementing a constraint-based engine to auto-adjust the layout.)

**Comment by willium** [comment]
I'm in favor of "change the default formatting for large values."
k for thousands,
m for million,
b for billion...

or potentially on the title do "in millions"?

**Comment by kanitw** [comment]
> k for thousands,
> m for million,
> b for billion...

FYI, previously we have SI units for Vega-Lite and that confused a lot of people. 
I think b is non-standard abbreviation for billions (not to mention what does billion mean) so we better avoid it.

**Comment by g3o2** [comment]
For an automatic solution, SI is a pretty good default as long as it is documented as such and can be undone by the user.

However, the best way is to handle this via a transform on the user side (e.g divide by 1000). It is a common recommendation in specialized literature not to use any big numbers in your visualisations and to document the measurement unit instead in the title, axis, legend or other annotations.

Therefore, Vega should in the medium run add an `annotation` guide to its grammar to allow for better documentation of plots. The use of the text mark is overkill for a few annotations and the existence of `title` further justifies the need. This would allow Vega-lite to automatically label e.g. K as "in thousands".

**Comment by kanitw** [comment]
> For vega this is IMO best managed by the user via transforms (e.g divide by 1000) and relevant annotations. The latter would be easier if a proper annotations guide existed.

If you manually divide your numbers by 1000, you can manually append "(in thousands)" to your axis title.  Thus, I don't think you need a specialized guide in this case.

**Comment by g3o2** [comment]
In vega-lite, I can perfectly live with this solution because it primarily serves data exploration.

In vega, which I'd use for print-ready plots and less common visualisations, a little more flexibility would not hurt, for axes titles are not always the ideal solution.

**Comment by jheer** [comment]
Vega 3.0.3 adds support for flush layout (`labelFlush`) and scale range bounds culling (`labelBound`) of axis labels. Specialized formatting was also considered but would require internal modification of d3's format functions (or a currently unsupported extensibility API) in order to do so cleanly in a way that respects other formatting options. So for the time being we do not have plans to support a "tidier" default number formatting option, though we'd certainly be interested in doing so in the future if it proves more feasible.
