### ISSUE TITLE
Is default number format working correctly?

### ISSUE THREAD

**Issue by kanitw** [vega/vega#977]
If I remember correctly, we discussed about having Vega format automatically applies scientific notation when there are too many digits, but not sure we really did that.  (I tried to search where is the issue, but can't remember which repo is for formatting.)  

If we do, then somehow it does not work for generated Vega-Lite spec. 

For example, in [this spec](https://pastebin.com/rjq2Db2q), there are like 13 digits and it seems like by default Vega axis doesn't autotmatically format things.  

![image](https://user-images.githubusercontent.com/111269/29296970-77e9e0dc-8112-11e7-8c22-57c7f46967d8.png)

Setting `"format": ""`  seems to use scientific notation:

![image](https://user-images.githubusercontent.com/111269/29296977-85930600-8112-11e7-8b74-c1b834df02d7.png)

However, when I decrease the number above `"expr": "datum.people * 0.000001"`, we still uses scientific notation:

![image](https://user-images.githubusercontent.com/111269/29297037-016f189a-8113-11e7-97af-36e58109bb23.png)

I might be doing something wrong, let me know.

I also look at related docs (e.g.,  `https://vega.github.io/vega/docs/axes/`) but it doesn't provide any information about this feature.

**Comment by jheer** [comment]
We do not do anything special for automatic label formatting (along the lines discussed in the past). Perhaps we should fold this discussion in with #976?

**Comment by kanitw** [comment]
Okie
