### ISSUE TITLE
setting an invalid domainMid on a color scale, causes error instead of warning

### ISSUE THREAD

**Issue by peterschretlen** [vega/vega#979]
To reproduce:

1.  Load the heatmap example:  https://vega.github.io/editor/#/examples/vega/heatmap
2.  add a `domainMid` property to the color scale that is outside the domain e.g.  `"domainMid": 10,`

Result:  will give the error below, and the view does not render. 
Expected: a warning message.  `WARN Scale domainMid exceeds domain min or max. 10` . 

```
vega-util.js:132 ERROR TypeError: Cannot read property 'warn' of undefined
    at Y (vega-encode.js:796)
    at G.Ae.transform (vega-encode.js:767)
    at G.ke.evaluate (vega-dataflow.js:1910)
    at G.ke.run (vega-dataflow.js:1891)
    at B.C [as run] (vega-dataflow.js:1430)
    at B.fe.run (vega-view.js:930)
    at vega-dataflow.js:751
    at B.A [as runAfter] (vega-dataflow.js:1509)
    at r.done (vega-dataflow.js:748)
    at <anonymous>
```

I think the issue is https://github.com/vega/vega-encode/blob/master/src/Scale.js#L62
```
  configureRange(scale, _, configureDomain(scale, _), df);
```
should be
```
  configureRange(scale, _, configureDomain(scale, _, df), df);
```

vega-encode errors while trying to log the warning message, because `df` is not passed to `configureDomain`.

**Comment by jheer** [comment]
Fixed via vega/vega-encode#8. Will be included in next Vega release.
