### ISSUE TITLE
Some geo transformations are also needed as expressions

### ISSUE THREAD

**Issue by nyurik** [vega/vega#984]
expressions already have a set of projection-dependent functions, yet there it seems the split between what's available as a transformation and as an expression function. For example, `geoCentroid('projection', datum)` is a function, but `GeoPoint` is a transformation, even though they both operate on a lat/long, with a projection, and return an x,y position.  I am not sure if Vega should move towards expressions, rather than built-in transformations, but I think at least some of them should be available as both.

I think having geoPoint() as a function would help in a number of case. For example, given a geojson with countries, i can auto-calculate the centeroids for each country. But in some cases, I may want to override these values with manual lat/long.  If I had the `geoPoint()` as a function, I could do it as two expressions:
centerOverride = `data('overrides')[datum.countryCode]`
`if(centerOverride, geoPoint('projection', centerOverride), geoCenter('projection', datum))`

It could have been done as one expression if `geoCenter` calculated the center as lat/long rather than x,y (is that even possible?)

Thanks, and as always, it is awesome to have this tech, thank you!

**Comment by jheer** [comment]
You can apply a scale or projection in an expression using the [`scale` function](https://vega.github.io/vega/docs/expressions/#scale) (and similarly for the `invert` function). Perhaps we should add a `geoPoint` alias...
