### ISSUE TITLE
Thin white lines appearing on mouseover

### ISSUE THREAD

**Issue by nyurik** [vega/vega#985]
(This issue has been present in Vega 2 as well, but I cannot seem to find existing bug, so filing)

Most graphs with mouse-over (tooltip) handling show white rectangles when some of the objects are moused over. The thin white lines remain behind even after the mouse is moved out.  In some cases, the white lines disappear after mousing over other regions of the graph.

For repo:

* https://vega.github.io/editor/#/examples/vega/job-voyager -- move the mouse slowly down from the "Farmer" section - observe how Farmer section is filling up with white lines.
* https://vega.github.io/editor/#/examples/vega/circle-packing

**Comment by jheer** [comment]
This sounds like a canvas renderer dirty region handling issue (I fixed a closely related issue in the development of Vega 3). However, I can not reproduce the issue on MacOS 10.12 in current versions of Chrome, Safari or Firefox.

To diagnose, it would be helpful to include:
- Details regarding OS, browser(s) and Vega version.
- A screenshot of the issue.

**Comment by nyurik** [comment]
Google Chrome | 60.0.3112.90 (Official Build) (64-bit)
Revision | 6ee4392c6cef820c64ff50b5fd5eeb8596cd0394-refs/branch-heads/3112@{#702}
OS | Linux


Before mouseover: ![image](https://user-images.githubusercontent.com/1641515/29436154-4f697b6e-8378-11e7-9835-c88dd9f2c41f.png)
After mouseover:
![image](https://user-images.githubusercontent.com/1641515/29436225-9b5e0562-8378-11e7-9ba2-e71b28cca069.png)

Before:
![image](https://user-images.githubusercontent.com/1641515/29436272-be69fb7e-8378-11e7-9a6c-62fd5b84994a.png)
After mouse over the orange circle (note that it doesn't show rect when i select light blue circle, only the orange one)
![image](https://user-images.githubusercontent.com/1641515/29436347-118ab1cc-8379-11e7-8bad-75260e383ce2.png)

**Comment by jheer** [comment]
Thanks. And just to sanity check, can you also confirm that the issue does not occur with SVG rendering?

**Comment by nyurik** [comment]
@jheer update - somehow (no idea how), they are all gone now. I am not even sure if I restarted the browser since the bug report.  No idea what has caused it, but the lines were consistently showing up for a long time until today.  I will close it for now, but may need to be reopened if re-surfaced.
