### ISSUE TITLE
Is it possible to zoom in and out on visualizations via a 'pinch' gesture on touch devices?

### ISSUE THREAD

**Issue by mattijn** [vega/vega#987]
I thought this was possible before (?) but I cannot find any example including the capabilities. 
How to zoom in and out on the visualization by performing a "pinch" gesture, by using two fingers as the corners of a rectangle and moving them either closer together or farther apart to zoom in and out

On https://vega.github.io/vega/docs/event-streams/ it mentions the inclusion of events `touchstart`, `touchmove` and `touchend`, but can a pinch gesture be captured by these events?

**Comment by g3o2** [comment]
AFAIK this is handled by the mobile browsers. So all it takes is the mouse-wheel event.

**Comment by mattijn** [comment]
I knew I'd seen it, the [zoomable-scatter-plot example](https://vega.github.io/vega/examples/zoomable-scatter-plot/) uses zoom in/out by pinch gesture.
