### ISSUE TITLE
window's `ignorePeers` is ignored?

### ISSUE THREAD

**Issue by nyurik** [vega/vega#989]
This example should show barks with values 3,2,1, but instead shows 2,2,1.  Ascending is the same way. Is there a unit test that checks for it?

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 400,
  "height": 200,
  "padding": 5,
  "data": [
    {
      "name": "table",
      "values": [
        {"category": "A", "v": 1},
        {"category": "B", "v": 1},
        {"category": "C", "v": 2}
      ],
      "transform": [
        {
          "type": "window",
          "sort": {"field": "v", "order": "descending"},
          "ops": ["rank"],
          "ignorePeers": true
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "domain": {"data": "table", "field": "category"},
      "range": "width",
      "padding": 0.05,
      "round": true
    },
    {
      "name": "yscale",
      "domain": {"data": "table", "field": "rank"},
      "nice": true,
      "range": "height"
    }
  ],
  "axes": [
    {"orient": "bottom", "scale": "xscale"},
    {"orient": "left", "scale": "yscale"}
  ],
  "marks": [
    {
      "type": "rect",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "category"},
          "width": {"scale": "xscale", "band": 1},
          "y": {"scale": "yscale", "field": "rank"},
          "y2": {"scale": "yscale", "value": 0}
        },
        "update": {"fill": {"value": "steelblue"}},
        "hover": {"fill": {"value": "red"}}
      }
    }
  ]
}
```

**Comment by nyurik** [comment]
Looking at the Window test, the rank value is asserted to be 1,2,3,3,4, ...  (duplicate 3) in all of the tests.

E.g.
https://github.com/vega/vega-transforms/blob/master/test/window-test.js#L81

**Comment by jheer** [comment]
`ignorePeers` applies **only** to the sliding window frame. Quoting from the [window transform documentation](https://vega.github.io/vega/docs/transforms/window/): "This setting only affects those operations that depend on the window frame, namely aggregation operations and the first_value, last_value, and nth_value window operations."

In other words, `ignorePeers` does not have any affect on the `rank` operation, nor should it. To better understand window transforms, it might be helpful to also read descriptions of window queries in SQL databases. Vega uses the same semantics, with Vega's `ignorePeers` flag corresponding to frame clauses of `RANGE` (ignorePeers=false) vs `ROWS` (ignorePeers=true) in SQL.
