### ISSUE TITLE
Add the ability to reference parent group mark data beyond a single hierarchy level

### ISSUE THREAD

**Issue by mprudhom** [vega/vega#99]
According to the discussion at https://groups.google.com/forum/?fromgroups#!topic/vega-js/CNcztBghsZw, it isn't currently possible for a mark to reference the data of an enclosing group if it is more than a single hierarchy level above the mark. One possible way this might be done could be to add the ability to reference group data prefixed with the name of a group mark, such as:

```javascript

{ 
  "data": [ 
    { "name": "data1", "values": [ 1, 2, 3 ] }, 
    { "name": "data2", "values": [ 4, 5, 6 ] }, 
    { "name": "data3", "values": [ 7, 8, 9 ] } 
  ], 
  "marks": [ 
  { 
    "name": "mark_group1", 
    "type": "group", 
    "from": { "data": "data1" }, 
    "marks": [ 
    { 
      "name": "mark_group2", 
      "type": "group", 
      "from": { "data": "data2" }, 
      "marks": [ 
      { 
        "type": "rect", 
        "from": { "data": "data3" }, 
        "properties": { 
        "update": { 
          "fill": { 
            "h": {"group": "mark_group1.data"}, 
            "s": {"group": "data"}, 
            "l": {"field": "data"} 
          }
          } 
        } 
      } 
      ] 
    } 
    ] 
  } 
  ] 
} 
```

**Comment by arvind** [comment]
Vega 2 offers new `group` and `parent` accessors that can be optionally passed a `level` to access ancestors. See [the documentation](https://github.com/vega/vega/wiki/Marks#value-references) for more information.
