### ISSUE TITLE
title directive not supported in some visualization types

### ISSUE THREAD

**Issue by mattijn** [vega/vega#993]
I've been trying to add the top-level `title` specification to various examples in the vega editor, like
```
  "title": 
    {
      "name": "title_chart",
      "text": "title-of-chart, are-u-there?",
      "orient": "top",
      "anchor": "middle"
    }, 
```
But for some visualizations the title doesn't appear. 
For what I saw they are at least all examples part of the Circular Charts and Geographic Maps and some of the Tree and Network Diagrams.

**Comment by jheer** [comment]
In these cases, have you tried using `"anchor": "start"`? The problem with `title` as currently implemented is that the layout is based on the defined `width` and `height` of the corresponding group mark ([see source code](https://github.com/vega/vega-parser/blob/master/src/parsers/title.js#L76)). Some visualizations do not actually define these values, leading to problems with title layout.

There is an existing issue requesting that the title layout be modified: #960. I'm closing this issue, please track #960 instead!
